In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('부산광역시_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 부산광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,부산광역시,전체(시 / 군 / 구),주택용,"938,026","347,151,599","39,062,748,924",112.5
4,201507,부산광역시,전체(시 / 군 / 구),일반용,"182,472","505,383,636","75,844,523,691",150.1
...,...,...,...,...,...,...,...,...
811,201512,부산광역시,해운대구,산업용,983,"21,800,588","2,638,880,119",121
812,201512,부산광역시,해운대구,심 야,"1,073","2,498,830","210,499,664",84.2
813,201512,부산광역시,해운대구,일반용,"13,710","68,237,979","9,554,695,271",140
814,201512,부산광역시,해운대구,주택용,"71,705","51,872,355","6,679,599,686",128.8
815,201512,부산광역시,해운대구,합계,"92,501","149,412,001","19,678,758,450",131.7

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,부산광역시,전체(시 / 군 / 구),주택용,"938,026","347,151,599","39,062,748,924",112.5
4,201507,부산광역시,전체(시 / 군 / 구),일반용,"182,472","505,383,636","75,844,523,691",150.1
5,201507,부산광역시,전체(시 / 군 / 구),교육용,"1,156","32,382,651","4,443,713,861",137.2
6,201507,부산광역시,전체(시 / 군 / 구),산업용,"24,745","718,072,918","94,586,987,283",131.7
...,...,...,...,...,...,...,...,...
811,201512,부산광역시,해운대구,산업용,983,"21,800,588","2,638,880,119",121
812,201512,부산광역시,해운대구,심 야,"1,073","2,498,830","210,499,664",84.2
813,201512,부산광역시,해운대구,일반용,"13,710","68,237,979","9,554,695,271",140
814,201512,부산광역시,해운대구,주택용,"71,705","51,872,355","6,679,599,686",128.8
815,201512,부산광역시,해운대구,합계,"92,501","149,412,001","19,678,758,450",131.7

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,부산광역시,전체(시 / 군 / 구),주택용,"938,026","347,151,599","39,062,748,924",112.5
4,201507,부산광역시,전체(시 / 군 / 구),일반용,"182,472","505,383,636","75,844,523,691",150.1
5,201507,부산광역시,전체(시 / 군 / 구),교육용,"1,156","32,382,651","4,443,713,861",137.2
6,201507,부산광역시,전체(시 / 군 / 구),산업용,"24,745","718,072,918","94,586,987,283",131.7
7,201507,부산광역시,전체(시 / 군 / 구),농사용,"9,818","6,703,378","355,945,128",53.1
...,...,...,...,...,...,...,...,...
811,201512,부산광역시,해운대구,산업용,983,"21,800,588","2,638,880,119",121
812,201512,부산광역시,해운대구,심 야,"1,073","2,498,830","210,499,664",84.2
813,201512,부산광역시,해운대구,일반용,"13,710","68,237,979","9,554,695,271",140
814,201512,부산광역시,해운대구,주택용,"71,705","51,872,355","6,679,599,686",128.8
815,201512,부산광역시,해운대구,합계,"92,501","149,412,001","19,678,758,450",131.7

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,부산광역시,전체(시 / 군 / 구),주택용,"938,026","347,151,599","39,062,748,924",112.5
4,201507,부산광역시,전체(시 / 군 / 구),일반용,"182,472","505,383,636","75,844,523,691",150.1
5,201507,부산광역시,전체(시 / 군 / 구),교육용,"1,156","32,382,651","4,443,713,861",137.2
6,201507,부산광역시,전체(시 / 군 / 구),산업용,"24,745","718,072,918","94,586,987,283",131.7
7,201507,부산광역시,전체(시 / 군 / 구),농사용,"9,818","6,703,378","355,945,128",53.1
8,201507,부산광역시,전체(시 / 군 / 구),가로등,"78,171","12,309,574","1,467,005,179",119.2
9,201507,부산광역시,전체(시 / 군 / 구),심 야,"24,816","17,714,657","1,092,665,557",61.7
10,201508,부산광역시,전체(시 / 군 / 구),주택용,"938,284","434,013,157","59,751,066,811",137.7
11,201508,부산광역시,전체(시 / 군 / 구),일반용,"182,773","611,661,278","86,921,764,915",142.1
12,201508,부산광역시,전체(시 / 군 / 구),교육용,"1,160","34,885,279","4,674,513,194",134.0
13,201508,부산광역시,전체(시 / 군 / 구),산업용,"24,797","684,302,370","87,583,585,777",128.0
14,201508,부산광역시,전체(시 / 군 / 구),농사용,"9,875","8,062,756","397,422,008",49.3
15,201508,부산광역시,전체(시 / 군 / 구),가로등,"78,262","12,939,688","1,495,052,412",115.5
16,201508,부산광역시,전체(시 / 군 / 구),심 야,"24,654","16,684,610","1,062,207,005",63.7
17,201509,부산광역시,전체(시 / 군 / 구),주택용,"938,834","373,727,972","43,644,404,158",116.8
18,201509,부산광역시,전체(시 / 군 / 구),일반용,"182,938","540,944,655","68,490,089,345",126.6
19,201509,부산광역시,전체(시 / 군 / 구),교육용,"1,161","37,466,887","4,229,245,415",112.9
20,201509,부산광역시,전체(시 / 군 / 구),산업용,"24,839","700,729,453","75,485,384,745",107.7
21,201509,부산광역시,전체(시 / 군 / 구),농사용,"9,922","8,019,592","389,544,887",48.6
22,201509,부산광역시,전체(시 / 군 / 구),가로등,"78,349","13,624,582","1,541,818,258",113.2
23,201509,부산광역시,전체(시 / 군 / 구),심 야,"24,560","14,244,719","871,011,795",61.1
24,201510,부산광역시,전체(시 / 군 / 구),주택용,"939,241","340,875,752","38,178,459,096",112.0
25,201510,부산광역시,전체(시 / 군 / 구),일반용,"182,864","465,247,149","54,045,122,113",116.2
26,201510,부산광역시,전체(시 / 군 / 구),교육용,"1,162","30,288,475","3,221,269,638",106.4
27,201510,부산광역시,전체(시 / 군 / 구),산업용,"24,842","674,773,333","70,068,567,108",103.8
28,201510,부산광역시,전체(시 / 군 / 구),농사용,"9,943","7,265,098","362,846,065",49.9
29,201510,부산광역시,전체(시 / 군 / 구),가로등,"78,480","14,532,189","1,585,377,724",109.1
30,201510,부산광역시,전체(시 / 군 / 구),심 야,"24,468","15,434,407","917,009,730",59.4
31,201511,부산광역시,전체(시 / 군 / 구),주택용,"940,137","364,067,506","43,677,606,090",120.0
32,201511,부산광역시,전체(시 / 군 / 구),일반용,"183,002","458,562,597","60,668,302,903",132.3
33,201511,부산광역시,전체(시 / 군 / 구),교육용,"1,160","32,634,186","3,777,199,079",115.7
34,201511,부산광역시,전체(시 / 군 / 구),산업용,"24,873","680,375,062","83,825,534,828",123.2
35,201511,부산광역시,전체(시 / 군 / 구),농사용,"10,114","8,355,024","408,504,659",48.9
36,201511,부산광역시,전체(시 / 군 / 구),가로등,"78,507","15,782,002","1,681,243,538",106.5
37,201511,부산광역시,전체(시 / 군 / 구),심 야,"24,426","24,330,774","1,597,304,893",65.6
38,201512,부산광역시,전체(시 / 군 / 구),주택용,"940,454","379,397,332","47,316,594,701",124.7
39,201512,부산광역시,전체(시 / 군 / 구),일반용,"183,480","497,655,011","70,051,030,272",140.8
40,201512,부산광역시,전체(시 / 군 / 구),교육용,"1,161","41,227,764","4,794,324,933",116.3
41,201512,부산광역시,전체(시 / 군 / 구),산업용,"24,897","696,246,832","88,383,847,902",126.9
42,201512,부산광역시,전체(시 / 군 / 구),농사용,"10,062","8,973,996","458,189,790",51.1
43,201512,부산광역시,전체(시 / 군 / 구),가로등,"78,647","16,576,256","1,739,889,405",105.0
44,201512,부산광역시,전체(시 / 군 / 구),심 야,"24,350","38,420,145","2,951,571,956",76.8
45,합계,합계,합계,합계,"7,565,882","9,942,046,301","1,233,100,496,771",124

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_13776\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201507  부산광역시  일반용  182,472   505,383,636
11  201508  부산광역시  일반용  182,773   611,661,278
18  201509  부산광역시  일반용  182,938   540,944,655
25  201510  부산광역시  일반용  182,864   465,247,149
32  201511  부산광역시  일반용  183,002   458,562,597
39  201512  부산광역시  일반용  183,480   497,655,011

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  부산광역시   강서구  일반용   7,824   21,795,580
181  201508  부산광역시   강서구  일반용   7,895   25,421,472
309  201509  부산광역시   강서구  일반용   7,953   22,691,026
437  201510  부산광역시   강서구  일반용   8,006   19,752,955
565  201511  부산광역시   강서구  일반용   8,033   20,391,845
..      ...    ...   ...  ...      ...          ...
301  201508  부산광역시  해운대구  일반용  13,708   87,092,592
429  201509  부산광역시  해운대구  일반용  13,700   74,312,249
557  201510  부산광역시  해운대구  일반용  13,676   64,713,526
685  201511  부산광역시  해운대구  일반용  13,705   62,732,198
813  201512  부산광역시  해운대구  일반용  13,710   68,237,979

[96 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'부산광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강서구',
 '금정구',
 '기장군',
 '남구',
 '동구',
 '동래구',
 '부산진구',
 '북구',
 '사상구',
 '사하구',
 '서구',
 '수영구',
 '연제구',
 '영도구',
 '중구',
 '해운대구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
55   201507  부산광역시   강서구   합계  44,729   290,557,413
183  201508  부산광역시   강서구   합계  44,949   278,188,514
311  201509  부산광역시   강서구   합계  45,130   270,635,945
439  201510  부산광역시   강서구   합계  45,491   266,943,149
567  201511  부산광역시   강서구   합계  45,717   273,355,838
..      ...    ...   ...  ...      ...           ...
303  201508  부산광역시  해운대구   합계  92,261   176,771,343
431  201509  부산광역시  해운대구   합계  92,372   155,392,064
559  201510  부산광역시  해운대구   합계  92,381   139,324,764
687  201511  부산광역시  해운대구   합계  92,433   140,575,911
815  201512  부산광역시  해운대구   합계  92,501   149,412,001

[96 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[290557413, 278188514, 270635945, 266943149, 273355838, 286608731]
[83856710, 97860808, 87900826, 78732819, 82888617, 90362160]
[80888353, 80435619, 95891970, 86542344, 86139366, 92373171]
[111791047, 126108020, 116302990, 108093179, 108014888, 113683191]
[40655904, 46795003, 43467975, 37400898, 38391616, 42610531]
[70360188, 86495868, 75484298, 65876757, 69090248, 75083609]
[133466668, 158228738, 140378147, 123113057, 125238071, 135046192]
[70351134, 84675961, 73891119, 65976608, 69531129, 72552921]
[148479198, 154011043, 149506314, 133756110, 144891991, 156010123]
[236205263, 248089566, 242863805, 233102165, 233809996, 231985104]
[46859979, 53749032, 48638737, 45474254, 44295600, 50319800]
[43830528, 55329602, 49080149, 42128997, 43406943, 46689239]
[60410540, 73254652, 63566358, 55405558, 57399371, 62324321]
[36629993, 40948600, 38185721, 35076457, 36948525, 41070463]
[34160676, 41606769, 37571442, 31469287, 30129041, 32365779]
[151214819, 176771343, 155392064, 139324764, 140575911, 149412001]
부산광역시 지역별 합계 :  [1666289590, 521601940, 522270823, 683993315, 249321927, 442390968, 815470873, 436978872, 886654779, 1426055899, 289337402, 280465458, 372360800, 228859759, 207302994, 912690902]
부산광역시 고객호수 평균:  [7555, 17724, 8094, 17106, 8962, 16033, 23956, 12702, 13401, 18897, 10370, 11919, 12068, 9798, 6178, 15393]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0           201507  부산광역시   강서구   합계  44,729   290,557,413
1           201508  부산광역시   강서구   합계  44,949   278,188,514
2           201509  부산광역시   강서구   합계  45,130   270,635,945
3           201510  부산광역시   강서구   합계  45,491   266,943,149
4           201511  부산광역시   강서구   합계  45,717   273,355,838
..             ...    ...   ...  ...      ...           ...
107  201507-201512  부산광역시   수영구   합계    11919     280465458
108  201507-201512  부산광역시   연제구   합계    12068     372360800
109  201507-201512  부산광역시   영도구   합계     9798     228859759
110  201507-201512  부산광역시    중구   합계     6178     207302994
111  201507-201512  부산광역시  해운대구   합계    15393     912690902

[112 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201507-201512  부산광역시   강서구   합계    7555  1666289590
97   201507-201512  부산광역시   금정구   합계   17724   521601940
98   201507-201512  부산광역시   기장군   합계    8094   522270823
99   201507-201512  부산광역시    남구   합계   17106   683993315
100  201507-201512  부산광역시    동구   합계    8962   249321927
101  201507-201512  부산광역시   동래구   합계   16033   442390968
102  201507-201512  부산광역시  부산진구   합계   23956   815470873
103  201507-201512  부산광역시    북구   합계   12702   436978872
104  201507-201512  부산광역시   사상구   합계   13401   886654779
105  201507-201512  부산광역시   사하구   합계   18897  1426055899
106  201507-201512  부산광역시    서구   합계   10370   289337402
107  201507-201512  부산광역시   수영구   합계   11919   280465458
108  201507-201512  부산광역시   연제구   합계   12068   372360800
109  201507-201512  부산광역시   영도구   합계    9798   228859759
110  201507-201512  부산광역시    중구   합계    6178   207302994
111  201507-201512  부산광역시  해운대구   합계   15393   912690902

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  부산광역시   강서구  일반용   7,824   21,795,580
181  201508  부산광역시   강서구  일반용   7,895   25,421,472
309  201509  부산광역시   강서구  일반용   7,953   22,691,026
437  201510  부산광역시   강서구  일반용   8,006   19,752,955
565  201511  부산광역시   강서구  일반용   8,033   20,391,845
..      ...    ...   ...  ...      ...          ...
301  201508  부산광역시  해운대구  일반용  13,708   87,092,592
429  201509  부산광역시  해운대구  일반용  13,700   74,312,249
557  201510  부산광역시  해운대구  일반용  13,676   64,713,526
685  201511  부산광역시  해운대구  일반용  13,705   62,732,198
813  201512  부산광역시  해운대구  일반용  13,710   68,237,979

[96 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[21795580, 25421472, 22691026, 19752955, 20391845, 23995725]
[30002529, 36897989, 32061701, 26988600, 27862753, 30632684]
[19243172, 23273066, 20461055, 27959442, 26050748, 25251961]
[31245716, 37177230, 34253569, 29054950, 28680978, 30373839]
[23654974, 28149666, 25892757, 21274201, 21106729, 23433549]
[34557194, 42808678, 37128513, 30415551, 30444659, 33450789]
[68456548, 82509873, 72925967, 60417219, 58992388, 63174825]
[27759506, 34110108, 29979288, 24609634, 25219913, 27429360]
[34101409, 41204496, 35866333, 29654491, 30211515, 33285237]
[32191822, 39538464, 36004402, 29812401, 30273508, 32553188]
[17336385, 20370786, 18260119, 17061901, 15021348, 17682929]
[22568661, 28720682, 25943144, 21225411, 20921151, 22487439]
[31029290, 37441110, 32633983, 26992008, 27060789, 29776424]
[10564023, 12813142, 11853284, 9978919, 10148559, 10985879]
[27930019, 34131924, 30677265, 25335940, 23443516, 24903204]
[72946808, 87092592, 74312249, 64713526, 62732198, 68237979]
부산광역시 지역별 일반용 합계 :  [134048603, 184446256, 142239444, 190786282, 143511876, 208805384, 406476820, 169107809, 204323481, 200373785, 105733468, 141866488, 184933604, 66343806, 166421868, 430035352]
부산광역시 고객호수 평균:  [7975, 15127, 7332, 11794, 7589, 15556, 22833, 10550, 13367, 14219, 6647, 10286, 10956, 5943, 9039, 13699]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13776\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분 고객호수(호)     사용량(kWh)
0           201507  부산광역시   강서구  일반용  7,824   21,795,580
1           201508  부산광역시   강서구  일반용  7,895   25,421,472
2           201509  부산광역시   강서구  일반용  7,953   22,691,026
3           201510  부산광역시   강서구  일반용  8,006   19,752,955
4           201511  부산광역시   강서구  일반용  8,033   20,391,845
..             ...    ...   ...  ...     ...          ...
107  201507-201512  부산광역시   수영구  일반용   10286    141866488
108  201507-201512  부산광역시   연제구  일반용   10956    184933604
109  201507-201512  부산광역시   영도구  일반용    5943     66343806
110  201507-201512  부산광역시    중구  일반용    9039    166421868
111  201507-201512  부산광역시  해운대구  일반용   13699    430035352

[112 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)   사용량(kWh)
96   201507-201512  부산광역시   강서구  일반용    7975  134048603
97   201507-201512  부산광역시   금정구  일반용   15127  184446256
98   201507-201512  부산광역시   기장군  일반용    7332  142239444
99   201507-201512  부산광역시    남구  일반용   11794  190786282
100  201507-201512  부산광역시    동구  일반용    7589  143511876
101  201507-201512  부산광역시   동래구  일반용   15556  208805384
102  201507-201512  부산광역시  부산진구  일반용   22833  406476820
103  201507-201512  부산광역시    북구  일반용   10550  169107809
104  201507-201512  부산광역시   사상구  일반용   13367  204323481
105  201507-201512  부산광역시   사하구  일반용   14219  200373785
106  201507-201512  부산광역시    서구  일반용    6647  105733468
107  201507-201512  부산광역시   수영구  일반용   10286  141866488
108  201507-201512  부산광역시   연제구  일반용   10956  184933604
109  201507-201512  부산광역시   영도구  일반용    5943   66343806
110  201507-201512  부산광역시    중구  일반용    9039  166421868
111  201507-201512  부산광역시  해운대구  일반용   13699  430035352

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201507-201512  부산광역시   강서구  일반용    7975   134048603
96   201507-201512  부산광역시   강서구   합계    7555  1666289590
97   201507-201512  부산광역시   금정구   합계   17724   521601940
97   201507-201512  부산광역시   금정구  일반용   15127   184446256
98   201507-201512  부산광역시   기장군   합계    8094   522270823
98   201507-201512  부산광역시   기장군  일반용    7332   142239444
99   201507-201512  부산광역시    남구  일반용   11794   190786282
99   201507-201512  부산광역시    남구   합계   17106   683993315
100  201507-201512  부산광역시    동구  일반용    7589   143511876
100  201507-201512  부산광역시    동구   합계    8962   249321927
101  201507-201512  부산광역시   동래구  일반용   15556   208805384
101  201507-201512  부산광역시   동래구   합계   16033   442390968
102  201507-201512  부산광역시  부산진구  일반용   22833   406476820
102  201507-201512  부산광역시  부산진구   합계   23956   815470873
103  201507-201512  부산광역시    북구  일반용   10550   169107809
103  201507-201512  부산광역시    북구   합계   12702   436978872
104  201507-201512  부산광역시   사상구   합계   13401   886654779
104  201507-201512  부산광역시   사상구  일반용   13367   204323481
105  201507-201512  부산광역시   사하구   합계   18897  1426055899
105  201507-201512  부산광역시   사하구  일반용   14219   200373785
106  201507-201512  부산광역시    서구  일반용    6647   105733468
106  201507-201512  부산광역시    서구   합계   10370   289337402
107  201507-201512  부산광역시   수영구   합계   11919   280465458
107  201507-201512  부산광역시   수영구  일반용   10286   141866488
108  201507-201512  부산광역시   연제구   합계   12068   372360800
108  201507-201512  부산광역시   연제구  일반용   10956   184933604
109  201507-201512  부산광역시   영도구   합계    9798   228859759
109  201507-201512  부산광역시   영도구  일반용    5943    66343806
110  201507-201512  부산광역시    중구   합계    6178   207302994
110  201507-201512  부산광역시    중구  일반용    9039   166421868
111  201507-201512  부산광역시  해운대구  일반용   13699   430035352
111  201507-201512  부산광역시  해운대구   합계   15393   912690902

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[134048603,
 184446256,
 142239444,
 190786282,
 143511876,
 208805384,
 406476820,
 169107809,
 204323481,
 200373785,
 105733468,
 141866488,
 184933604,
 66343806,
 166421868,
 430035352]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1666289590,
 521601940,
 522270823,
 683993315,
 249321927,
 442390968,
 815470873,
 436978872,
 886654779,
 1426055899,
 289337402,
 280465458,
 372360800,
 228859759,
 207302994,
 912690902]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[8.04, 35.36, 27.23, 27.89, 57.56, 47.2, 49.85, 38.7, 23.04, 14.05, 36.54, 50.58, 49.67, 28.99, 80.28, 47.12]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0     8
1    35
2    27
3    28
4    58
5    47
6    50
7    39
8    23
9    14
10   37
11   51
12   50
13   29
14   80
15   47
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강서구  일반용   8
1    금정구  일반용  35
2    기장군  일반용  27
3     남구  일반용  28
4     동구  일반용  58
5    동래구  일반용  47
6   부산진구  일반용  50
7     북구  일반용  39
8    사상구  일반용  23
9    사하구  일반용  14
10    서구  일반용  37
11   수영구  일반용  51
12   연제구  일반용  50
13   영도구  일반용  29
14    중구  일반용  80
15  해운대구  일반용  47

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201507-201512  부산광역시   강서구  일반용    7975   134048603   8
1   201507-201512  부산광역시   강서구   합계    7555  1666289590 NaN
3   201507-201512  부산광역시   금정구  일반용   15127   184446256  35
2   201507-201512  부산광역시   금정구   합계   17724   521601940 NaN
5   201507-201512  부산광역시   기장군  일반용    7332   142239444  27
4   201507-201512  부산광역시   기장군   합계    8094   522270823 NaN
6   201507-201512  부산광역시    남구  일반용   11794   190786282  28
7   201507-201512  부산광역시    남구   합계   17106   683993315 NaN
8   201507-201512  부산광역시    동구  일반용    7589   143511876  58
9   201507-201512  부산광역시    동구   합계    8962   249321927 NaN
10  201507-201512  부산광역시   동래구  일반용   15556   208805384  47
11  201507-201512  부산광역시   동래구   합계   16033   442390968 NaN
12  201507-201512  부산광역시  부산진구  일반용   22833   406476820  50
13  201507-201512  부산광역시  부산진구   합계   23956   815470873 NaN
14  201507-201512  부산광역시    북구  일반용   10550   169107809  39
15  201507-201512  부산광역시    북구   합계   12702   436978872 NaN
17  201507-201512  부산광역시   사상구  일반용   13367   204323481  23
16  201507-201512  부산광역시   사상구   합계   13401   886654779 NaN
19  201507-201512  부산광역시   사하구  일반용   14219   200373785  14
18  201507-201512  부산광역시   사하구   합계   18897  1426055899 NaN
20  201507-201512  부산광역시    서구  일반용    6647   105733468  37
21  201507-201512  부산광역시    서구   합계   10370   289337402 NaN
23  201507-201512  부산광역시   수영구  일반용   10286   141866488  51
22  201507-201512  부산광역시   수영구   합계   11919   280465458 NaN
25  201507-201512  부산광역시   연제구  일반용   10956   184933604  50
24  201507-201512  부산광역시   연제구   합계   12068   372360800 NaN
27  201507-201512  부산광역시   영도구  일반용    5943    66343806  29
26  201507-201512  부산광역시   영도구   합계    9798   228859759 NaN
29  201507-201512  부산광역시    중구  일반용    9039   166421868  80
28  201507-201512  부산광역시    중구   합계    6178   207302994 NaN
30  201507-201512  부산광역시  해운대구  일반용   13699   430035352  47
31  201507-201512  부산광역시  해운대구   합계   15393   912690902 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)