In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('강원도_계약종별_전력사용량_월별_16상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 강원도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2016년 01 월 ~ 2016년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,강원도,전체(시 / 군 / 구),주택용,"543,810","182,125,820","24,051,104,166",132.1
4,201601,강원도,전체(시 / 군 / 구),일반용,"137,238","426,898,636","55,221,792,408",129.4
...,...,...,...,...,...,...,...,...
907,201606,강원도,횡성군,산업용,596,"14,490,278","1,876,412,953",129.5
908,201606,강원도,횡성군,심 야,"6,500","4,157,353","223,883,946",53.9
909,201606,강원도,횡성군,일반용,"4,729","8,479,760","1,229,330,439",145
910,201606,강원도,횡성군,주택용,"21,558","4,307,577","517,395,703",120.1
911,201606,강원도,횡성군,합계,"49,016","37,250,704","4,242,167,450",113.9

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,강원도,전체(시 / 군 / 구),주택용,"543,810","182,125,820","24,051,104,166",132.1
4,201601,강원도,전체(시 / 군 / 구),일반용,"137,238","426,898,636","55,221,792,408",129.4
5,201601,강원도,전체(시 / 군 / 구),교육용,"1,053","33,050,638","3,410,362,985",103.2
6,201601,강원도,전체(시 / 군 / 구),산업용,"12,571","586,635,833","66,759,603,198",113.8
...,...,...,...,...,...,...,...,...
907,201606,강원도,횡성군,산업용,596,"14,490,278","1,876,412,953",129.5
908,201606,강원도,횡성군,심 야,"6,500","4,157,353","223,883,946",53.9
909,201606,강원도,횡성군,일반용,"4,729","8,479,760","1,229,330,439",145
910,201606,강원도,횡성군,주택용,"21,558","4,307,577","517,395,703",120.1
911,201606,강원도,횡성군,합계,"49,016","37,250,704","4,242,167,450",113.9

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,강원도,전체(시 / 군 / 구),주택용,"543,810","182,125,820","24,051,104,166",132.1
4,201601,강원도,전체(시 / 군 / 구),일반용,"137,238","426,898,636","55,221,792,408",129.4
5,201601,강원도,전체(시 / 군 / 구),교육용,"1,053","33,050,638","3,410,362,985",103.2
6,201601,강원도,전체(시 / 군 / 구),산업용,"12,571","586,635,833","66,759,603,198",113.8
7,201601,강원도,전체(시 / 군 / 구),농사용,"86,894","48,996,291","2,434,189,023",49.7
...,...,...,...,...,...,...,...,...
907,201606,강원도,횡성군,산업용,596,"14,490,278","1,876,412,953",129.5
908,201606,강원도,횡성군,심 야,"6,500","4,157,353","223,883,946",53.9
909,201606,강원도,횡성군,일반용,"4,729","8,479,760","1,229,330,439",145
910,201606,강원도,횡성군,주택용,"21,558","4,307,577","517,395,703",120.1
911,201606,강원도,횡성군,합계,"49,016","37,250,704","4,242,167,450",113.9

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,강원도,전체(시 / 군 / 구),주택용,"543,810","182,125,820","24,051,104,166",132.1
4,201601,강원도,전체(시 / 군 / 구),일반용,"137,238","426,898,636","55,221,792,408",129.4
5,201601,강원도,전체(시 / 군 / 구),교육용,"1,053","33,050,638","3,410,362,985",103.2
6,201601,강원도,전체(시 / 군 / 구),산업용,"12,571","586,635,833","66,759,603,198",113.8
7,201601,강원도,전체(시 / 군 / 구),농사용,"86,894","48,996,291","2,434,189,023",49.7
8,201601,강원도,전체(시 / 군 / 구),가로등,"100,675","17,104,961","1,806,543,450",105.6
9,201601,강원도,전체(시 / 군 / 구),심 야,"94,463","276,985,911","20,794,087,836",75.1
10,201602,강원도,전체(시 / 군 / 구),주택용,"544,587","187,406,980","25,439,963,026",135.7
11,201602,강원도,전체(시 / 군 / 구),일반용,"137,047","427,175,638","55,162,356,950",129.1
12,201602,강원도,전체(시 / 군 / 구),교육용,"1,052","33,741,851","3,610,913,016",107.0
13,201602,강원도,전체(시 / 군 / 구),산업용,"12,588","529,649,384","60,761,276,156",114.7
14,201602,강원도,전체(시 / 군 / 구),농사용,"86,898","50,826,601","2,506,863,850",49.3
15,201602,강원도,전체(시 / 군 / 구),가로등,"100,951","16,213,284","1,776,473,367",109.6
16,201602,강원도,전체(시 / 군 / 구),심 야,"94,398","305,962,244","22,958,102,557",75.0
17,201603,강원도,전체(시 / 군 / 구),주택용,"545,277","166,965,322","20,255,622,988",121.3
18,201603,강원도,전체(시 / 군 / 구),일반용,"136,719","360,573,468","43,932,775,606",121.8
19,201603,강원도,전체(시 / 군 / 구),교육용,"1,053","32,406,720","3,269,042,054",100.9
20,201603,강원도,전체(시 / 군 / 구),산업용,"12,608","605,570,851","57,619,985,657",95.1
21,201603,강원도,전체(시 / 군 / 구),농사용,"109,196","46,745,872","2,328,637,228",49.8
22,201603,강원도,전체(시 / 군 / 구),가로등,"101,239","15,212,952","1,694,823,602",111.4
23,201603,강원도,전체(시 / 군 / 구),심 야,"94,333","240,029,550","16,044,790,422",66.8
24,201604,강원도,전체(시 / 군 / 구),주택용,"546,354","165,472,649","19,881,239,672",120.1
25,201604,강원도,전체(시 / 군 / 구),일반용,"136,659","318,205,895","36,619,666,723",115.1
26,201604,강원도,전체(시 / 군 / 구),교육용,"1,049","27,067,839","2,640,706,858",97.6
27,201604,강원도,전체(시 / 군 / 구),산업용,"12,650","707,587,252","57,292,283,306",81.0
28,201604,강원도,전체(시 / 군 / 구),농사용,"87,890","43,917,327","2,205,291,303",50.2
29,201604,강원도,전체(시 / 군 / 구),가로등,"101,758","15,309,038","1,758,276,572",114.9
30,201604,강원도,전체(시 / 군 / 구),심 야,"94,223","173,896,577","9,415,722,944",54.1
31,201605,강원도,전체(시 / 군 / 구),주택용,"547,136","153,149,206","17,342,895,529",113.2
32,201605,강원도,전체(시 / 군 / 구),일반용,"136,715","291,056,226","34,733,799,395",119.3
33,201605,강원도,전체(시 / 군 / 구),교육용,"1,048","20,845,841","2,279,576,409",109.4
34,201605,강원도,전체(시 / 군 / 구),산업용,"12,681","639,472,522","58,238,363,772",91.1
35,201605,강원도,전체(시 / 군 / 구),농사용,"88,659","40,001,658","2,051,507,942",51.3
36,201605,강원도,전체(시 / 군 / 구),가로등,"102,134","14,813,123","1,745,750,048",117.9
37,201605,강원도,전체(시 / 군 / 구),심 야,"94,094","104,108,677","5,657,080,005",54.3
38,201606,강원도,전체(시 / 군 / 구),주택용,"548,339","152,967,409","17,416,395,127",113.9
39,201606,강원도,전체(시 / 군 / 구),일반용,"137,083","311,719,773","41,994,749,457",134.7
40,201606,강원도,전체(시 / 군 / 구),교육용,"1,047","20,998,960","2,598,393,836",123.7
41,201606,강원도,전체(시 / 군 / 구),산업용,"12,719","606,478,651","69,095,545,719",113.9
42,201606,강원도,전체(시 / 군 / 구),농사용,"89,597","43,755,812","2,176,659,479",49.7
43,201606,강원도,전체(시 / 군 / 구),가로등,"102,492","14,668,303","1,762,582,919",120.2
44,201606,강원도,전체(시 / 군 / 구),심 야,"93,971","62,458,346","3,429,938,428",54.9
45,합계,합계,합계,합계,"5,902,948","8,518,229,891","882,175,734,988",103.6

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_5560\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)      사용량(kWh)
4   201601  강원도  일반용  137,238   426,898,636
11  201602  강원도  일반용  137,047   427,175,638
18  201603  강원도  일반용  136,719   360,573,468
25  201604  강원도  일반용  136,659   318,205,895
32  201605  강원도  일반용  136,715   291,056,226
39  201606  강원도  일반용  137,083   311,719,773

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201601  강원도  강릉시  일반용  18,441   46,313,560
197  201602  강원도  강릉시  일반용  18,449   47,844,473
341  201603  강원도  강릉시  일반용  18,464   42,413,830
485  201604  강원도  강릉시  일반용  18,528   39,081,334
629  201605  강원도  강릉시  일반용  18,535   34,787,439
..      ...  ...  ...  ...      ...          ...
333  201602  강원도  횡성군  일반용   4,740   13,187,176
477  201603  강원도  횡성군  일반용   4,715   10,835,896
621  201604  강원도  횡성군  일반용   4,705    9,121,828
765  201605  강원도  횡성군  일반용   4,704    8,167,363
909  201606  강원도  횡성군  일반용   4,729    8,479,760

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'강원도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강릉시',
 '고성군',
 '동해시',
 '삼척시',
 '속초시',
 '양구군',
 '양양군',
 '영월군',
 '원주시',
 '인제군',
 '정선군',
 '철원군',
 '춘천시',
 '태백시',
 '평창군',
 '홍천군',
 '화천군',
 '횡성군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201601  강원도  강릉시   합계  125,334   180,112,335
199  201602  강원도  강릉시   합계  125,517   175,319,150
343  201603  강원도  강릉시   합계  125,984   166,587,311
487  201604  강원도  강릉시   합계  125,988   171,899,335
631  201605  강원도  강릉시   합계  126,251   159,058,228
..      ...  ...  ...  ...       ...           ...
335  201602  강원도  횡성군   합계   48,297    61,864,733
479  201603  강원도  횡성군   합계   50,410    54,077,905
623  201604  강원도  횡성군   합계   48,717    45,933,428
767  201605  강원도  횡성군   합계   48,834    38,733,125
911  201606  강원도  횡성군   합계   49,016    37,250,704

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[180112335, 175319150, 166587311, 171899335, 159058228, 151210651]
[29947408, 31040248, 27427398, 25124915, 21910060, 21330466]
[243151316, 223996194, 238139927, 246878312, 243073008, 218324671]
[119466706, 109279722, 128124297, 205001748, 127238617, 121617605]
[46209999, 47374510, 41393684, 38273565, 34354773, 33957917]
[23467621, 25116811, 21243687, 17939523, 14294140, 13231130]
[27208462, 27960459, 24480722, 21705913, 19171929, 18434400]
[84571244, 81710135, 97798924, 94032882, 95112993, 91338763]
[236756498, 238994018, 217382508, 191419615, 169437307, 175242893]
[35631232, 36916130, 30233520, 26429147, 22168567, 20765818]
[62526099, 59181890, 54284154, 48270306, 44370321, 40141931]
[53009246, 55084908, 45616772, 38626018, 32269612, 30872521]
[161886131, 168539129, 145368467, 129631709, 113175973, 115436027]
[31739655, 32365689, 29537824, 27638691, 24684763, 25147555]
[72347832, 70075773, 56490781, 46445780, 39516414, 35740017]
[75470822, 77336970, 64968154, 56015430, 48715294, 47673425]
[27127677, 28819513, 24348700, 20190260, 16162129, 15330760]
[61167807, 61864733, 54077905, 45933428, 38733125, 37250704]
강원도 지역별 합계 :  [1004187010, 156780495, 1413563428, 810728695, 241564448, 115292912, 138961885, 544564941, 1229232839, 172144414, 308774701, 255479077, 834037436, 171114177, 320616597, 370180095, 131979039, 299027702]
강원도 고객호수 평균:  [20989, 4614, 7889, 8581, 6360, 3591, 4739, 6406, 24191, 5444, 6142, 6865, 22462, 4600, 8028, 11109, 3799, 8154]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201601  강원도  강릉시   합계  125,334   180,112,335
1           201602  강원도  강릉시   합계  125,517   175,319,150
2           201603  강원도  강릉시   합계  125,984   166,587,311
3           201604  강원도  강릉시   합계  125,988   171,899,335
4           201605  강원도  강릉시   합계  126,251   159,058,228
..             ...  ...  ...  ...       ...           ...
121  201601-201606  강원도  태백시   합계      4600     171114177
122  201601-201606  강원도  평창군   합계      8028     320616597
123  201601-201606  강원도  홍천군   합계     11109     370180095
124  201601-201606  강원도  화천군   합계      3799     131979039
125  201601-201606  강원도  횡성군   합계      8154     299027702

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201601-201606']
Hap

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201601-201606  강원도  강릉시   합계   20989  1004187010
109  201601-201606  강원도  고성군   합계    4614   156780495
110  201601-201606  강원도  동해시   합계    7889  1413563428
111  201601-201606  강원도  삼척시   합계    8581   810728695
112  201601-201606  강원도  속초시   합계    6360   241564448
113  201601-201606  강원도  양구군   합계    3591   115292912
114  201601-201606  강원도  양양군   합계    4739   138961885
115  201601-201606  강원도  영월군   합계    6406   544564941
116  201601-201606  강원도  원주시   합계   24191  1229232839
117  201601-201606  강원도  인제군   합계    5444   172144414
118  201601-201606  강원도  정선군   합계    6142   308774701
119  201601-201606  강원도  철원군   합계    6865   255479077
120  201601-201606  강원도  춘천시   합계   22462   834037436
121  201601-201606  강원도  태백시   합계    4600   171114177
122  201601-201606  강원도  평창군   합계    8028   320616597
123  201601-201606  강원도  홍천군   합계   11109   370180095
124  201601-201606  강원도  화천군   합계    3799   131979039
125  201601-201606  강원도  횡성군   합계    8154   299027702

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201601  강원도  강릉시  일반용  18,441   46,313,560
197  201602  강원도  강릉시  일반용  18,449   47,844,473
341  201603  강원도  강릉시  일반용  18,464   42,413,830
485  201604  강원도  강릉시  일반용  18,528   39,081,334
629  201605  강원도  강릉시  일반용  18,535   34,787,439
..      ...  ...  ...  ...      ...          ...
333  201602  강원도  횡성군  일반용   4,740   13,187,176
477  201603  강원도  횡성군  일반용   4,715   10,835,896
621  201604  강원도  횡성군  일반용   4,705    9,121,828
765  201605  강원도  횡성군  일반용   4,704    8,167,363
909  201606  강원도  횡성군  일반용   4,729    8,479,760

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[46313560, 47844473, 42413830, 39081334, 34787439, 37058209]
[11810757, 11930116, 10420354, 9579899, 8909061, 9189249]
[20423804, 20983867, 18412420, 16562639, 14985447, 15254802]
[15869456, 16014808, 14673527, 13089001, 11663100, 12499769]
[22572778, 22857450, 19663132, 18099371, 16960253, 17554587]
[8208720, 8478183, 7159456, 6231793, 5315796, 5535842]
[11038558, 11081196, 9782717, 8639684, 8136009, 8287123]
[7465833, 7822791, 6574427, 5978212, 5392318, 5786195]
[73601149, 75732279, 64246295, 56187356, 51457213, 57485045]
[14129426, 13995573, 11578510, 10176087, 8971693, 9375158]
[24443501, 21119243, 16768424, 13744371, 13103041, 13156919]
[16941333, 16992279, 13732984, 11775970, 10185594, 10996516]
[64879675, 67265408, 57852750, 51985745, 48124202, 53316050]
[8881489, 9383074, 7779761, 7251177, 6440859, 7790982]
[29911299, 25929333, 19239643, 15364028, 14656584, 14169891]
[24636389, 24103306, 19147703, 16751578, 16448964, 18162835]
[11630049, 12455083, 10291639, 8585822, 7351290, 7620841]
[14140860, 13187176, 10835896, 9121828, 8167363, 8479760]
강원도 지역별 일반용 합계 :  [247498845, 61839436, 106622979, 83809661, 117707571, 40929790, 56965287, 39019776, 378709337, 68226447, 102335499, 80624676, 343423830, 47527342, 119270778, 119250775, 57934724, 63932883]
강원도 고객호수 평균:  [18497, 3762, 6810, 6242, 7722, 2492, 3945, 4045, 23635, 4365, 4891, 4679, 20065, 4095, 5940, 7850, 3144, 4724]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5560\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201601  강원도  강릉시  일반용  18,441   46,313,560
1           201602  강원도  강릉시  일반용  18,449   47,844,473
2           201603  강원도  강릉시  일반용  18,464   42,413,830
3           201604  강원도  강릉시  일반용  18,528   39,081,334
4           201605  강원도  강릉시  일반용  18,535   34,787,439
..             ...  ...  ...  ...      ...          ...
121  201601-201606  강원도  태백시  일반용     4095     47527342
122  201601-201606  강원도  평창군  일반용     5940    119270778
123  201601-201606  강원도  홍천군  일반용     7850    119250775
124  201601-201606  강원도  화천군  일반용     3144     57934724
125  201601-201606  강원도  횡성군  일반용     4724     63932883

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201601-201606']
GyeonGiHap2

                년월   시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201601-201606  강원도  강릉시  일반용   18497  247498845
109  201601-201606  강원도  고성군  일반용    3762   61839436
110  201601-201606  강원도  동해시  일반용    6810  106622979
111  201601-201606  강원도  삼척시  일반용    6242   83809661
112  201601-201606  강원도  속초시  일반용    7722  117707571
113  201601-201606  강원도  양구군  일반용    2492   40929790
114  201601-201606  강원도  양양군  일반용    3945   56965287
115  201601-201606  강원도  영월군  일반용    4045   39019776
116  201601-201606  강원도  원주시  일반용   23635  378709337
117  201601-201606  강원도  인제군  일반용    4365   68226447
118  201601-201606  강원도  정선군  일반용    4891  102335499
119  201601-201606  강원도  철원군  일반용    4679   80624676
120  201601-201606  강원도  춘천시  일반용   20065  343423830
121  201601-201606  강원도  태백시  일반용    4095   47527342
122  201601-201606  강원도  평창군  일반용    5940  119270778
123  201601-201606  강원도  홍천군  일반용    7850  119250775
124  201601-201606  강원도  화천군  일반용    3144   57934724
125  201601-201606  강원도  횡성군  일반용    4724   63932883

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201601-201606  강원도  강릉시  일반용   18497   247498845
108  201601-201606  강원도  강릉시   합계   20989  1004187010
109  201601-201606  강원도  고성군  일반용    3762    61839436
109  201601-201606  강원도  고성군   합계    4614   156780495
110  201601-201606  강원도  동해시  일반용    6810   106622979
110  201601-201606  강원도  동해시   합계    7889  1413563428
111  201601-201606  강원도  삼척시   합계    8581   810728695
111  201601-201606  강원도  삼척시  일반용    6242    83809661
112  201601-201606  강원도  속초시   합계    6360   241564448
112  201601-201606  강원도  속초시  일반용    7722   117707571
113  201601-201606  강원도  양구군  일반용    2492    40929790
113  201601-201606  강원도  양구군   합계    3591   115292912
114  201601-201606  강원도  양양군   합계    4739   138961885
114  201601-201606  강원도  양양군  일반용    3945    56965287
115  201601-201606  강원도  영월군  일반용    4045    39019776
115  201601-201606  강원도  영월군   합계    6406   544564941
116  201601-201606  강원도  원주시  일반용   23635   378709337
116  201601-201606  강원도  원주시   합계   24191  1229232839
117  201601-201606  강원도  인제군  일반용    4365    68226447
117  201601-201606  강원도  인제군   합계    5444   172144414
118  201601-201606  강원도  정선군   합계    6142   308774701
118  201601-201606  강원도  정선군  일반용    4891   102335499
119  201601-201606  강원도  철원군   합계    6865   255479077
119  201601-201606  강원도  철원군  일반용    4679    80624676
120  201601-201606  강원도  춘천시  일반용   20065   343423830
120  201601-201606  강원도  춘천시   합계   22462   834037436
121  201601-201606  강원도  태백시   합계    4600   171114177
121  201601-201606  강원도  태백시  일반용    4095    47527342
122  201601-201606  강원도  평창군   합계    8028   320616597
122  201601-201606  강원도  평창군  일반용    5940   119270778
123  201601-201606  강원도  홍천군   합계   11109   370180095
123  201601-201606  강원도  홍천군  일반용    7850   119250775
124  201601-201606  강원도  화천군   합계    3799   131979039
124  201601-201606  강원도  화천군  일반용    3144    57934724
125  201601-201606  강원도  횡성군  일반용    4724    63932883
125  201601-201606  강원도  횡성군   합계    8154   299027702

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[247498845,
 61839436,
 106622979,
 83809661,
 117707571,
 40929790,
 56965287,
 39019776,
 378709337,
 68226447,
 102335499,
 80624676,
 343423830,
 47527342,
 119270778,
 119250775,
 57934724,
 63932883]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1004187010,
 156780495,
 1413563428,
 810728695,
 241564448,
 115292912,
 138961885,
 544564941,
 1229232839,
 172144414,
 308774701,
 255479077,
 834037436,
 171114177,
 320616597,
 370180095,
 131979039,
 299027702]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[24.65, 39.44, 7.54, 10.34, 48.73, 35.5, 40.99, 7.17, 30.81, 39.63, 33.14, 31.56, 41.18, 27.78, 37.2, 32.21, 43.9, 21.38]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    25
1    39
2     8
3    10
4    49
5    36
6    41
7     7
8    31
9    40
10   33
11   32
12   41
13   28
14   37
15   32
16   44
17   21
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강릉시  일반용  25
1   고성군  일반용  39
2   동해시  일반용   8
3   삼척시  일반용  10
4   속초시  일반용  49
5   양구군  일반용  36
6   양양군  일반용  41
7   영월군  일반용   7
8   원주시  일반용  31
9   인제군  일반용  40
10  정선군  일반용  33
11  철원군  일반용  32
12  춘천시  일반용  41
13  태백시  일반용  28
14  평창군  일반용  37
15  홍천군  일반용  32
16  화천군  일반용  44
17  횡성군  일반용  21

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201601-201606  강원도  강릉시  일반용   18497   247498845  25
1   201601-201606  강원도  강릉시   합계   20989  1004187010 NaN
2   201601-201606  강원도  고성군  일반용    3762    61839436  39
3   201601-201606  강원도  고성군   합계    4614   156780495 NaN
4   201601-201606  강원도  동해시  일반용    6810   106622979   8
5   201601-201606  강원도  동해시   합계    7889  1413563428 NaN
7   201601-201606  강원도  삼척시  일반용    6242    83809661  10
6   201601-201606  강원도  삼척시   합계    8581   810728695 NaN
9   201601-201606  강원도  속초시  일반용    7722   117707571  49
8   201601-201606  강원도  속초시   합계    6360   241564448 NaN
10  201601-201606  강원도  양구군  일반용    2492    40929790  36
11  201601-201606  강원도  양구군   합계    3591   115292912 NaN
13  201601-201606  강원도  양양군  일반용    3945    56965287  41
12  201601-201606  강원도  양양군   합계    4739   138961885 NaN
14  201601-201606  강원도  영월군  일반용    4045    39019776   7
15  201601-201606  강원도  영월군   합계    6406   544564941 NaN
16  201601-201606  강원도  원주시  일반용   23635   378709337  31
17  201601-201606  강원도  원주시   합계   24191  1229232839 NaN
18  201601-201606  강원도  인제군  일반용    4365    68226447  40
19  201601-201606  강원도  인제군   합계    5444   172144414 NaN
21  201601-201606  강원도  정선군  일반용    4891   102335499  33
20  201601-201606  강원도  정선군   합계    6142   308774701 NaN
23  201601-201606  강원도  철원군  일반용    4679    80624676  32
22  201601-201606  강원도  철원군   합계    6865   255479077 NaN
24  201601-201606  강원도  춘천시  일반용   20065   343423830  41
25  201601-201606  강원도  춘천시   합계   22462   834037436 NaN
27  201601-201606  강원도  태백시  일반용    4095    47527342  28
26  201601-201606  강원도  태백시   합계    4600   171114177 NaN
29  201601-201606  강원도  평창군  일반용    5940   119270778  37
28  201601-201606  강원도  평창군   합계    8028   320616597 NaN
31  201601-201606  강원도  홍천군  일반용    7850   119250775  32
30  201601-201606  강원도  홍천군   합계   11109   370180095 NaN
33  201601-201606  강원도  화천군  일반용    3144    57934724  44
32  201601-201606  강원도  화천군   합계    3799   131979039 NaN
34  201601-201606  강원도  횡성군  일반용    4724    63932883  21
35  201601-201606  강원도  횡성군   합계    8154   299027702 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1601-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)