In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('울산광역시_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 울산광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,울산광역시,전체(시 / 군 / 구),주택용,"305,056","134,831,178","18,424,327,713",136.6
4,201501,울산광역시,전체(시 / 군 / 구),일반용,"68,261","187,306,733","25,422,928,676",135.7
...,...,...,...,...,...,...,...,...
283,201506,울산광역시,중구,산업용,519,"2,070,330","313,621,621",151.5
284,201506,울산광역시,중구,심 야,768,"546,415","32,626,592",59.7
285,201506,울산광역시,중구,일반용,"13,132","24,324,955","3,303,116,958",135.8
286,201506,울산광역시,중구,주택용,"69,351","23,484,176","2,793,473,514",119
287,201506,울산광역시,중구,합계,"89,382","52,408,972","6,697,299,639",127.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,울산광역시,전체(시 / 군 / 구),주택용,"305,056","134,831,178","18,424,327,713",136.6
4,201501,울산광역시,전체(시 / 군 / 구),일반용,"68,261","187,306,733","25,422,928,676",135.7
5,201501,울산광역시,전체(시 / 군 / 구),교육용,421,"15,298,340","1,708,801,454",111.7
6,201501,울산광역시,전체(시 / 군 / 구),산업용,"6,026","2,248,509,343","244,130,094,560",108.6
...,...,...,...,...,...,...,...,...
283,201506,울산광역시,중구,산업용,519,"2,070,330","313,621,621",151.5
284,201506,울산광역시,중구,심 야,768,"546,415","32,626,592",59.7
285,201506,울산광역시,중구,일반용,"13,132","24,324,955","3,303,116,958",135.8
286,201506,울산광역시,중구,주택용,"69,351","23,484,176","2,793,473,514",119
287,201506,울산광역시,중구,합계,"89,382","52,408,972","6,697,299,639",127.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,울산광역시,전체(시 / 군 / 구),주택용,"305,056","134,831,178","18,424,327,713",136.6
4,201501,울산광역시,전체(시 / 군 / 구),일반용,"68,261","187,306,733","25,422,928,676",135.7
5,201501,울산광역시,전체(시 / 군 / 구),교육용,421,"15,298,340","1,708,801,454",111.7
6,201501,울산광역시,전체(시 / 군 / 구),산업용,"6,026","2,248,509,343","244,130,094,560",108.6
7,201501,울산광역시,전체(시 / 군 / 구),농사용,"11,013","8,227,090","404,799,091",49.2
...,...,...,...,...,...,...,...,...
283,201506,울산광역시,중구,산업용,519,"2,070,330","313,621,621",151.5
284,201506,울산광역시,중구,심 야,768,"546,415","32,626,592",59.7
285,201506,울산광역시,중구,일반용,"13,132","24,324,955","3,303,116,958",135.8
286,201506,울산광역시,중구,주택용,"69,351","23,484,176","2,793,473,514",119
287,201506,울산광역시,중구,합계,"89,382","52,408,972","6,697,299,639",127.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,울산광역시,전체(시 / 군 / 구),주택용,"305,056","134,831,178","18,424,327,713",136.6
4,201501,울산광역시,전체(시 / 군 / 구),일반용,"68,261","187,306,733","25,422,928,676",135.7
5,201501,울산광역시,전체(시 / 군 / 구),교육용,421,"15,298,340","1,708,801,454",111.7
6,201501,울산광역시,전체(시 / 군 / 구),산업용,"6,026","2,248,509,343","244,130,094,560",108.6
7,201501,울산광역시,전체(시 / 군 / 구),농사용,"11,013","8,227,090","404,799,091",49.2
8,201501,울산광역시,전체(시 / 군 / 구),가로등,"30,208","5,751,346","596,826,315",103.8
9,201501,울산광역시,전체(시 / 군 / 구),심 야,"8,321","25,651,678","1,928,158,425",75.2
10,201502,울산광역시,전체(시 / 군 / 구),주택용,"305,929","133,371,679","18,004,600,030",135.0
11,201502,울산광역시,전체(시 / 군 / 구),일반용,"68,409","178,297,286","24,428,770,355",137.0
12,201502,울산광역시,전체(시 / 군 / 구),교육용,421,"14,093,766","1,596,235,304",113.3
13,201502,울산광역시,전체(시 / 군 / 구),산업용,"6,046","2,010,920,310","216,346,504,234",107.6
14,201502,울산광역시,전체(시 / 군 / 구),농사용,"11,064","7,906,179","389,036,806",49.2
15,201502,울산광역시,전체(시 / 군 / 구),가로등,"30,305","5,396,488","593,583,902",110.0
16,201502,울산광역시,전체(시 / 군 / 구),심 야,"8,305","24,201,046","1,820,435,249",75.2
17,201503,울산광역시,전체(시 / 군 / 구),주택용,"306,619","117,126,932","13,934,772,930",119.0
18,201503,울산광역시,전체(시 / 군 / 구),일반용,"68,345","154,931,185","19,986,273,979",129.0
19,201503,울산광역시,전체(시 / 군 / 구),교육용,420,"13,971,429","1,363,839,601",97.6
20,201503,울산광역시,전체(시 / 군 / 구),산업용,"6,058","2,147,410,808","187,794,747,766",87.5
21,201503,울산광역시,전체(시 / 군 / 구),농사용,"12,086","6,610,360","330,051,987",49.9
22,201503,울산광역시,전체(시 / 군 / 구),가로등,"30,393","4,942,215","552,035,407",111.7
23,201503,울산광역시,전체(시 / 군 / 구),심 야,"8,277","19,935,533","1,333,051,642",66.9
24,201504,울산광역시,전체(시 / 군 / 구),주택용,"307,291","123,521,222","15,272,011,023",123.6
25,201504,울산광역시,전체(시 / 군 / 구),일반용,"68,474","153,894,807","17,927,545,984",116.5
26,201504,울산광역시,전체(시 / 군 / 구),교육용,420,"13,134,591","1,246,089,986",94.9
27,201504,울산광역시,전체(시 / 군 / 구),산업용,"6,084","2,193,140,334","191,578,588,610",87.4
28,201504,울산광역시,전체(시 / 군 / 구),농사용,"11,232","6,112,889","307,229,128",50.3
29,201504,울산광역시,전체(시 / 군 / 구),가로등,"30,427","4,837,657","564,566,769",116.7
30,201504,울산광역시,전체(시 / 군 / 구),심 야,"8,256","16,249,121","894,086,053",55.0
31,201505,울산광역시,전체(시 / 군 / 구),주택용,"308,142","114,269,997","13,182,352,468",115.4
32,201505,울산광역시,전체(시 / 군 / 구),일반용,"68,410","143,024,019","17,115,033,700",119.7
33,201505,울산광역시,전체(시 / 군 / 구),교육용,419,"10,825,108","1,103,032,227",101.9
34,201505,울산광역시,전체(시 / 군 / 구),산업용,"6,092","2,235,075,028","190,325,313,128",85.2
35,201505,울산광역시,전체(시 / 군 / 구),농사용,"11,334","5,150,445","270,716,090",52.6
36,201505,울산광역시,전체(시 / 군 / 구),가로등,"30,498","4,450,413","539,292,304",121.2
37,201505,울산광역시,전체(시 / 군 / 구),심 야,"8,218","10,400,788","574,722,253",55.3
38,201506,울산광역시,전체(시 / 군 / 구),주택용,"309,115","114,747,221","13,327,772,376",116.1
39,201506,울산광역시,전체(시 / 군 / 구),일반용,"68,659","150,136,573","20,387,569,765",135.8
40,201506,울산광역시,전체(시 / 군 / 구),교육용,419,"11,803,747","1,446,347,456",122.5
41,201506,울산광역시,전체(시 / 군 / 구),산업용,"6,117","2,198,170,280","243,414,420,418",110.7
42,201506,울산광역시,전체(시 / 군 / 구),농사용,"11,491","5,379,949","274,529,890",51.0
43,201506,울산광역시,전체(시 / 군 / 구),가로등,"30,619","4,278,885","536,078,057",125.3
44,201506,울산광역시,전체(시 / 군 / 구),심 야,"8,189","6,343,197","357,627,857",56.4
45,합계,합계,합계,합계,"2,591,889","14,989,637,195","1,511,734,800,968",100.9

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_1116\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분  고객호수(호)      사용량(kWh)
4   201501  울산광역시  일반용  68,261   187,306,733
11  201502  울산광역시  일반용  68,409   178,297,286
18  201503  울산광역시  일반용  68,345   154,931,185
25  201504  울산광역시  일반용  68,474   153,894,807
32  201505  울산광역시  일반용  68,410   143,024,019
39  201506  울산광역시  일반용  68,659   150,136,573

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  울산광역시   남구  일반용  24,980   74,411,970
93   201502  울산광역시   남구  일반용  25,036   70,484,037
133  201503  울산광역시   남구  일반용  24,992   61,033,231
173  201504  울산광역시   남구  일반용  24,989   60,279,391
213  201505  울산광역시   남구  일반용  24,951   56,096,407
253  201506  울산광역시   남구  일반용  25,028   59,417,588
61   201501  울산광역시   동구  일반용   8,118   22,230,655
101  201502  울산광역시   동구  일반용   8,126   21,190,358
141  201503  울산광역시   동구  일반용   8,107   18,640,257
181  201504  울산광역시   동구  일반용   8,123   18,775,583
221  201505  울산광역시   동구  일반용   8,119   17,631,110
261  201506  울산광역시   동구  일반용   8,131   18,315,631
69   201501  울산광역시   북구  일반용   8,058   25,385,997
109  201502  울산광역시   북구  일반용   8,086   24,054,266
149  201503  울산광역시   북구  일반용   8,046   20,872,195
189  201504  울산광역시   북구  일반용   8,069   20,594,413
229  201505  울산광역시   북구  일반용   8,048   19,107,614
269  201506  울산광역시   북구  일반용   8,101   20,246,794
77   201501  울산광역시  울주군  일반용  14,060   35,373,862
117  201502  울산광역시  울주군  일반용  14,058   34,282,002
157  201503  울산광역시  울주군  일반용  14,109   29,591,308
197  201504  울산광역시  울주군  일반용  14,178   29,777,987
237  201505  울산광역시  울주군  일반용  14,192   27,132,411
277  201506  울산광역시  울주군  일반용  14,267   27,831,605
85   201501  울산광역시   중구  일반용  13,045   29,904,249
125  201502  울산광역시   중구  일반용  13,103   28,286,623
165  201503  울산광역시   중구  일반용  13,091   24,794,194
205  201504  울산광역시   중구  일반용  13,115   24,467,433
245  201505  울산광역시   중구  일반용  13,100   23,056,477
285  201506  울산광역시   중구  일반용  13,132   24,324,955

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'울산광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['남구', '동구', '북구', '울주군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55   201501  울산광역시   남구   합계  132,472   1,272,672,099
95   201502  울산광역시   남구   합계  132,694   1,157,624,579
135  201503  울산광역시   남구   합계  132,764   1,182,666,085
175  201504  울산광역시   남구   합계  132,961   1,223,070,104
215  201505  울산광역시   남구   합계  133,056   1,269,833,894
255  201506  울산광역시   남구   합계  133,439   1,237,743,546
63   201501  울산광역시   동구   합계   57,421     162,543,984
103  201502  울산광역시   동구   합계   57,688     139,364,021
143  201503  울산광역시   동구   합계   57,842     150,138,485
183  201504  울산광역시   동구   합계   58,081     149,620,057
223  201505  울산광역시   동구   합계   58,254     142,062,948
263  201506  울산광역시   동구   합계   58,361     149,450,734
71   201501  울산광역시   북구   합계   46,903     219,548,752
111  201502  울산광역시   북구   합계   47,143     194,811,214
151  201503  울산광역시   북구   합계   47,458     207,315,649
191  201504  울산광역시   북구   합계   47,317     202,986,217
231  201505  울산광역시   북구   합계   47,415     188,150,923
271  201506  울산광역시   북구   합계   47,629     202,692,402
79   201501  울산광역시  울주군   합계  103,979     905,248,592
119  201502  울산광역시  울주군   합계  104,209     818,894,498
159  201503  울산광역시  울주군   합계  105,287     869,100,858
199  201504  울산광역시  울주군   합계  104,948     879,096,374
239  201505  울산광역시  울주군   합계  105,312     871,740,729
279  201506  울산광역시  울주군   합계  105,798     848,564,198
87   201501  울산광역시   중구   합계   88,531      65,562,281
127  201502  울산광역시   중구   합계   88,745      63,492,442
167  201503  울산광역시   중구   합계   88,847      55,707,385
207  201504  울산광역시   중구   합계   88,877      56,117,869
247  201505  울산광역시   중구   합계   89,076      51,407,304
287  201506  울산광역시   중구   합계   89,382      52,408,972

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[1272672099, 1157624579, 1182666085, 1223070104, 1269833894, 1237743546]
[162543984, 139364021, 150138485, 149620057, 142062948, 149450734]
[219548752, 194811214, 207315649, 202986217, 188150923, 202692402]
[905248592, 818894498, 869100858, 879096374, 871740729, 848564198]
[65562281, 63492442, 55707385, 56117869, 51407304, 52408972]
울산광역시 지역별 합계 :  [7343610307, 893180229, 1215505157, 5192645249, 344696253]
울산광역시 고객호수 평균:  [22149, 9656, 7885, 17487, 14818]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_1116\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1116\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1116\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1116\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1116\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분   고객호수(호)        사용량(kWh)
0          201501  울산광역시   남구   합계  132,472   1,272,672,099
1          201502  울산광역시   남구   합계  132,694   1,157,624,579
2          201503  울산광역시   남구   합계  132,764   1,182,666,085
3          201504  울산광역시   남구   합계  132,961   1,223,070,104
4          201505  울산광역시   남구   합계  133,056   1,269,833,894
5          201506  울산광역시   남구   합계  133,439   1,237,743,546
6          201501  울산광역시   동구   합계   57,421     162,543,984
7          201502  울산광역시   동구   합계   57,688     139,364,021
8          201503  울산광역시   동구   합계   57,842     150,138,485
9          201504  울산광역시   동구   합계   58,081     149,620,057
10         201505  울산광역시   동구   합계   58,254     142,062,948
11         201506  울산광역시   동구   합계   58,361     149,450,734
12         201501  울산광역시   북구   합계   46,903     219,548,752
13         201502  울산광역시   북구   합계   47,143     194,811,214
14         201503  울산광역시   북구   합계   47,458     207,315,649
15         201504  울산광역시   북구   합계   47,317     202,986,217
16         201505  울산광역시   북구   합계   47,415     188,150,923
17         201506  울산광역시   북구   합계   47,629     202,692,402
18         201501  울산광역시  울주군   합계  103,979     905,248,592
19         201502  울산광역시  울주군   합계  104,209     818,894,498
20         201503  울산광역시  울주군   합계  105,287     869,100,858
21         201504  울산광역시  울주군   합계  104,948     879,096,374
22         201505  울산광역시  울주군   합계  105,312     871,740,729
23         201506  울산광역시  울주군   합계  105,798     848,564,198
24         201501  울산광역시   중구   합계   88,531      65,562,281
25         201502  울산광역시   중구   합계   88,745      63,492,442
26         201503  울산광역시   중구   합계   88,847      55,707,385
27         201504  울산광역시   중구   합계   88,877      56,117,869
28         201505  울산광역시   중구   합계   89,076      51,407,304
29         201506  울산광역시   중구   합계   89,382      52,408,972
30  201501-201506  울산광역시   남구   합계     22149      7343610307
31  201501-201506  울산광역시   동구   합계      9656       893180229
32  201501-201506  울산광역시   북구   합계      7885      1215505157
33  201501-201506  울산광역시  울주군   합계     17487      5192645249
34  201501-201506  울산광역시   중구   합계     14818       344696253

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
30  201501-201506  울산광역시   남구   합계   22149  7343610307
31  201501-201506  울산광역시   동구   합계    9656   893180229
32  201501-201506  울산광역시   북구   합계    7885  1215505157
33  201501-201506  울산광역시  울주군   합계   17487  5192645249
34  201501-201506  울산광역시   중구   합계   14818   344696253

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  울산광역시   남구  일반용  24,980   74,411,970
93   201502  울산광역시   남구  일반용  25,036   70,484,037
133  201503  울산광역시   남구  일반용  24,992   61,033,231
173  201504  울산광역시   남구  일반용  24,989   60,279,391
213  201505  울산광역시   남구  일반용  24,951   56,096,407
253  201506  울산광역시   남구  일반용  25,028   59,417,588
61   201501  울산광역시   동구  일반용   8,118   22,230,655
101  201502  울산광역시   동구  일반용   8,126   21,190,358
141  201503  울산광역시   동구  일반용   8,107   18,640,257
181  201504  울산광역시   동구  일반용   8,123   18,775,583
221  201505  울산광역시   동구  일반용   8,119   17,631,110
261  201506  울산광역시   동구  일반용   8,131   18,315,631
69   201501  울산광역시   북구  일반용   8,058   25,385,997
109  201502  울산광역시   북구  일반용   8,086   24,054,266
149  201503  울산광역시   북구  일반용   8,046   20,872,195
189  201504  울산광역시   북구  일반용   8,069   20,594,413
229  201505  울산광역시   북구  일반용   8,048   19,107,614
269  201506  울산광역시   북구  일반용   8,101   20,246,794
77   201501  울산광역시  울주군  일반용  14,060   35,373,862
117  201502  울산광역시  울주군  일반용  14,058   34,282,002
157  201503  울산광역시  울주군  일반용  14,109   29,591,308
197  201504  울산광역시  울주군  일반용  14,178   29,777,987
237  201505  울산광역시  울주군  일반용  14,192   27,132,411
277  201506  울산광역시  울주군  일반용  14,267   27,831,605
85   201501  울산광역시   중구  일반용  13,045   29,904,249
125  201502  울산광역시   중구  일반용  13,103   28,286,623
165  201503  울산광역시   중구  일반용  13,091   24,794,194
205  201504  울산광역시   중구  일반용  13,115   24,467,433
245  201505  울산광역시   중구  일반용  13,100   23,056,477
285  201506  울산광역시   중구  일반용  13,132   24,324,955

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[74411970, 70484037, 61033231, 60279391, 56096407, 59417588]
[22230655, 21190358, 18640257, 18775583, 17631110, 18315631]
[25385997, 24054266, 20872195, 20594413, 19107614, 20246794]
[35373862, 34282002, 29591308, 29777987, 27132411, 27831605]
[29904249, 28286623, 24794194, 24467433, 23056477, 24324955]
울산광역시 지역별 일반용 합계 :  [381722624, 116783594, 130261279, 183989175, 154833931]
울산광역시 고객호수 평균:  [24996, 8120, 8068, 14144, 13097]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_1116\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1116\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1116\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1116\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1116\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201501  울산광역시   남구  일반용  24,980   74,411,970
1          201502  울산광역시   남구  일반용  25,036   70,484,037
2          201503  울산광역시   남구  일반용  24,992   61,033,231
3          201504  울산광역시   남구  일반용  24,989   60,279,391
4          201505  울산광역시   남구  일반용  24,951   56,096,407
5          201506  울산광역시   남구  일반용  25,028   59,417,588
6          201501  울산광역시   동구  일반용   8,118   22,230,655
7          201502  울산광역시   동구  일반용   8,126   21,190,358
8          201503  울산광역시   동구  일반용   8,107   18,640,257
9          201504  울산광역시   동구  일반용   8,123   18,775,583
10         201505  울산광역시   동구  일반용   8,119   17,631,110
11         201506  울산광역시   동구  일반용   8,131   18,315,631
12         201501  울산광역시   북구  일반용   8,058   25,385,997
13         201502  울산광역시   북구  일반용   8,086   24,054,266
14         201503  울산광역시   북구  일반용   8,046   20,872,195
15         201504  울산광역시   북구  일반용   8,069   20,594,413
16         201505  울산광역시   북구  일반용   8,048   19,107,614
17         201506  울산광역시   북구  일반용   8,101   20,246,794
18         201501  울산광역시  울주군  일반용  14,060   35,373,862
19         201502  울산광역시  울주군  일반용  14,058   34,282,002
20         201503  울산광역시  울주군  일반용  14,109   29,591,308
21         201504  울산광역시  울주군  일반용  14,178   29,777,987
22         201505  울산광역시  울주군  일반용  14,192   27,132,411
23         201506  울산광역시  울주군  일반용  14,267   27,831,605
24         201501  울산광역시   중구  일반용  13,045   29,904,249
25         201502  울산광역시   중구  일반용  13,103   28,286,623
26         201503  울산광역시   중구  일반용  13,091   24,794,194
27         201504  울산광역시   중구  일반용  13,115   24,467,433
28         201505  울산광역시   중구  일반용  13,100   23,056,477
29         201506  울산광역시   중구  일반용  13,132   24,324,955
30  201501-201506  울산광역시   남구  일반용    24996    381722624
31  201501-201506  울산광역시   동구  일반용     8120    116783594
32  201501-201506  울산광역시   북구  일반용     8068    130261279
33  201501-201506  울산광역시  울주군  일반용    14144    183989175
34  201501-201506  울산광역시   중구  일반용    13097    154833931

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
30  201501-201506  울산광역시   남구  일반용   24996  381722624
31  201501-201506  울산광역시   동구  일반용    8120  116783594
32  201501-201506  울산광역시   북구  일반용    8068  130261279
33  201501-201506  울산광역시  울주군  일반용   14144  183989175
34  201501-201506  울산광역시   중구  일반용   13097  154833931

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
30  201501-201506  울산광역시   남구  일반용   24996   381722624
30  201501-201506  울산광역시   남구   합계   22149  7343610307
31  201501-201506  울산광역시   동구  일반용    8120   116783594
31  201501-201506  울산광역시   동구   합계    9656   893180229
32  201501-201506  울산광역시   북구  일반용    8068   130261279
32  201501-201506  울산광역시   북구   합계    7885  1215505157
33  201501-201506  울산광역시  울주군  일반용   14144   183989175
33  201501-201506  울산광역시  울주군   합계   17487  5192645249
34  201501-201506  울산광역시   중구  일반용   13097   154833931
34  201501-201506  울산광역시   중구   합계   14818   344696253

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[381722624, 116783594, 130261279, 183989175, 154833931]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[7343610307, 893180229, 1215505157, 5192645249, 344696253]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[5.2, 13.08, 10.72, 3.54, 44.92]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    5
1   13
2   11
3    4
4   45
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0   남구  일반용   5
1   동구  일반용  13
2   북구  일반용  11
3  울주군  일반용   4
4   중구  일반용  45

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201501-201506  울산광역시   남구  일반용   24996   381722624   5
1  201501-201506  울산광역시   남구   합계   22149  7343610307 NaN
2  201501-201506  울산광역시   동구  일반용    8120   116783594  13
3  201501-201506  울산광역시   동구   합계    9656   893180229 NaN
4  201501-201506  울산광역시   북구  일반용    8068   130261279  11
5  201501-201506  울산광역시   북구   합계    7885  1215505157 NaN
6  201501-201506  울산광역시  울주군  일반용   14144   183989175   4
7  201501-201506  울산광역시  울주군   합계   17487  5192645249 NaN
8  201501-201506  울산광역시   중구  일반용   13097   154833931  45
9  201501-201506  울산광역시   중구   합계   14818   344696253 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)