In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('제주특별자치도_계약종별_전력사용량_월별_16하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 제주특별자치도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2016년 07 월 ~ 2016년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,제주특별자치도,전체(시 / 군 / 구),주택용,"240,816","63,262,239","8,299,373,023",131.2
4,201607,제주특별자치도,전체(시 / 군 / 구),일반용,"57,761","156,097,854","22,860,335,158",146.4
...,...,...,...,...,...,...,...,...
139,201612,제주특별자치도,제주시,산업용,"2,254","36,453,634","4,564,505,159",125.2
140,201612,제주특별자치도,제주시,심 야,"4,945","9,678,729","725,037,710",74.9
141,201612,제주특별자치도,제주시,일반용,"43,391","98,547,398","13,995,071,712",142
142,201612,제주특별자치도,제주시,주택용,"178,403","46,584,152","5,514,920,755",118.4
143,201612,제주특별자치도,제주시,합계,"258,700","239,039,811","27,672,553,195",115.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,제주특별자치도,전체(시 / 군 / 구),주택용,"240,816","63,262,239","8,299,373,023",131.2
4,201607,제주특별자치도,전체(시 / 군 / 구),일반용,"57,761","156,097,854","22,860,335,158",146.4
5,201607,제주특별자치도,전체(시 / 군 / 구),교육용,336,"11,278,833","1,373,505,409",121.8
6,201607,제주특별자치도,전체(시 / 군 / 구),산업용,"3,107","47,024,836","6,032,082,669",128.3
...,...,...,...,...,...,...,...,...
139,201612,제주특별자치도,제주시,산업용,"2,254","36,453,634","4,564,505,159",125.2
140,201612,제주특별자치도,제주시,심 야,"4,945","9,678,729","725,037,710",74.9
141,201612,제주특별자치도,제주시,일반용,"43,391","98,547,398","13,995,071,712",142
142,201612,제주특별자치도,제주시,주택용,"178,403","46,584,152","5,514,920,755",118.4
143,201612,제주특별자치도,제주시,합계,"258,700","239,039,811","27,672,553,195",115.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,제주특별자치도,전체(시 / 군 / 구),주택용,"240,816","63,262,239","8,299,373,023",131.2
4,201607,제주특별자치도,전체(시 / 군 / 구),일반용,"57,761","156,097,854","22,860,335,158",146.4
5,201607,제주특별자치도,전체(시 / 군 / 구),교육용,336,"11,278,833","1,373,505,409",121.8
6,201607,제주특별자치도,전체(시 / 군 / 구),산업용,"3,107","47,024,836","6,032,082,669",128.3
7,201607,제주특별자치도,전체(시 / 군 / 구),농사용,"43,135","96,986,609","4,613,072,028",47.6
...,...,...,...,...,...,...,...,...
139,201612,제주특별자치도,제주시,산업용,"2,254","36,453,634","4,564,505,159",125.2
140,201612,제주특별자치도,제주시,심 야,"4,945","9,678,729","725,037,710",74.9
141,201612,제주특별자치도,제주시,일반용,"43,391","98,547,398","13,995,071,712",142
142,201612,제주특별자치도,제주시,주택용,"178,403","46,584,152","5,514,920,755",118.4
143,201612,제주특별자치도,제주시,합계,"258,700","239,039,811","27,672,553,195",115.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,제주특별자치도,전체(시 / 군 / 구),주택용,"240,816","63,262,239","8,299,373,023",131.2
4,201607,제주특별자치도,전체(시 / 군 / 구),일반용,"57,761","156,097,854","22,860,335,158",146.4
5,201607,제주특별자치도,전체(시 / 군 / 구),교육용,336,"11,278,833","1,373,505,409",121.8
6,201607,제주특별자치도,전체(시 / 군 / 구),산업용,"3,107","47,024,836","6,032,082,669",128.3
7,201607,제주특별자치도,전체(시 / 군 / 구),농사용,"43,135","96,986,609","4,613,072,028",47.6
8,201607,제주특별자치도,전체(시 / 군 / 구),가로등,"21,120","3,417,970","443,866,687",129.9
9,201607,제주특별자치도,전체(시 / 군 / 구),심 야,"7,430","7,116,743","444,259,817",62.4
10,201608,제주특별자치도,전체(시 / 군 / 구),주택용,"242,181","83,563,551","14,255,594,697",170.6
11,201608,제주특별자치도,전체(시 / 군 / 구),일반용,"58,529","191,769,955","26,889,490,580",140.2
12,201608,제주특별자치도,전체(시 / 군 / 구),교육용,336,"12,167,224","1,464,014,963",120.3
13,201608,제주특별자치도,전체(시 / 군 / 구),산업용,"3,100","50,542,417","6,440,189,121",127.4
14,201608,제주특별자치도,전체(시 / 군 / 구),농사용,"43,182","105,822,717","4,973,549,509",47.0
15,201608,제주특별자치도,전체(시 / 군 / 구),가로등,"21,375","3,739,909","456,023,041",121.9
16,201608,제주특별자치도,전체(시 / 군 / 구),심 야,"7,407","6,652,850","435,465,822",65.5
17,201609,제주특별자치도,전체(시 / 군 / 구),주택용,"243,601","68,134,489","5,031,510,149",73.8
18,201609,제주특별자치도,전체(시 / 군 / 구),일반용,"59,059","163,811,244","20,794,134,472",126.9
19,201609,제주특별자치도,전체(시 / 군 / 구),교육용,337,"11,354,493","1,198,819,531",105.6
20,201609,제주특별자치도,전체(시 / 군 / 구),산업용,"3,109","48,299,590","5,442,065,253",112.7
21,201609,제주특별자치도,전체(시 / 군 / 구),농사용,"43,268","104,820,853","4,846,628,902",46.2
22,201609,제주특별자치도,전체(시 / 군 / 구),가로등,"21,514","4,081,956","473,028,870",115.9
23,201609,제주특별자치도,전체(시 / 군 / 구),심 야,"7,376","5,318,746","337,015,199",63.4
24,201610,제주특별자치도,전체(시 / 군 / 구),주택용,"244,866","57,274,857","6,152,585,609",107.4
25,201610,제주특별자치도,전체(시 / 군 / 구),일반용,"59,386","135,962,221","15,973,584,789",117.5
26,201610,제주특별자치도,전체(시 / 군 / 구),교육용,336,"9,207,332","933,988,555",101.4
27,201610,제주특별자치도,전체(시 / 군 / 구),산업용,"3,143","45,235,856","4,796,193,849",106.0
28,201610,제주특별자치도,전체(시 / 군 / 구),농사용,"43,344","93,299,872","4,305,415,529",46.1
29,201610,제주특별자치도,전체(시 / 군 / 구),가로등,"21,611","4,435,781","476,006,833",107.3
30,201610,제주특별자치도,전체(시 / 군 / 구),심 야,"7,370","5,179,453","286,512,063",55.3
31,201611,제주특별자치도,전체(시 / 군 / 구),주택용,"246,195","59,161,450","7,083,957,728",119.7
32,201611,제주특별자치도,전체(시 / 군 / 구),일반용,"60,023","133,477,433","17,916,587,620",134.2
33,201611,제주특별자치도,전체(시 / 군 / 구),교육용,336,"9,615,633","1,121,546,439",116.6
34,201611,제주특별자치도,전체(시 / 군 / 구),산업용,"3,184","47,982,822","5,835,827,042",121.6
35,201611,제주특별자치도,전체(시 / 군 / 구),농사용,"43,518","97,934,024","4,578,820,435",46.8
36,201611,제주특별자치도,전체(시 / 군 / 구),가로등,"21,649","4,708,261","491,172,606",104.3
37,201611,제주특별자치도,전체(시 / 군 / 구),심 야,"7,356","8,677,480","572,486,668",66.0
38,201612,제주특별자치도,전체(시 / 군 / 구),주택용,"248,002","62,789,958","7,439,189,348",118.5
39,201612,제주특별자치도,전체(시 / 군 / 구),일반용,"60,817","144,993,020","20,584,321,664",142.0
40,201612,제주특별자치도,전체(시 / 군 / 구),교육용,337,"10,774,658","1,232,457,065",114.4
41,201612,제주특별자치도,전체(시 / 군 / 구),산업용,"3,267","50,320,378","6,470,646,973",128.6
42,201612,제주특별자치도,전체(시 / 군 / 구),농사용,"43,727","109,076,366","5,155,033,864",47.3
43,201612,제주특별자치도,전체(시 / 군 / 구),가로등,"21,709","5,042,423","503,542,115",99.9
44,201612,제주특별자치도,전체(시 / 군 / 구),심 야,"7,341","13,523,583","1,017,701,623",75.3
45,합계,합계,합계,합계,"2,275,596","2,353,937,939","250,031,603,317",106.2

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_8184\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월       시구 계약구분  고객호수(호)      사용량(kWh)
4   201607  제주특별자치도  일반용  57,761   156,097,854
11  201608  제주특별자치도  일반용  58,529   191,769,955
18  201609  제주특별자치도  일반용  59,059   163,811,244
25  201610  제주특별자치도  일반용  59,386   135,962,221
32  201611  제주특별자치도  일반용  60,023   133,477,433
39  201612  제주특별자치도  일반용  60,817   144,993,020

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201607  제주특별자치도  서귀포시  일반용  16,486    49,113,400
69   201608  제주특별자치도  서귀포시  일반용  16,722    61,240,949
85   201609  제주특별자치도  서귀포시  일반용  16,889    52,463,057
101  201610  제주특별자치도  서귀포시  일반용  17,003    44,267,503
117  201611  제주특별자치도  서귀포시  일반용  17,188    42,862,072
133  201612  제주특별자치도  서귀포시  일반용  17,426    46,445,622
61   201607  제주특별자치도   제주시  일반용  41,275   106,984,454
77   201608  제주특별자치도   제주시  일반용  41,807   130,529,006
93   201609  제주특별자치도   제주시  일반용  42,170   111,348,187
109  201610  제주특별자치도   제주시  일반용  42,383    91,694,718
125  201611  제주특별자치도   제주시  일반용  42,835    90,615,361
141  201612  제주특별자치도   제주시  일반용  43,391    98,547,398

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'제주특별자치도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['서귀포시', '제주시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
55   201607  제주특별자치도  서귀포시   합계  122,609   146,790,898
71   201608  제주특별자치도  서귀포시   합계  123,417   169,543,418
87   201609  제주특별자치도  서귀포시   합계  124,132   155,766,951
103  201610  제주특별자치도  서귀포시   합계  124,853   136,016,360
119  201611  제주특별자치도  서귀포시   합계  125,603   140,265,797
135  201612  제주특별자치도  서귀포시   합계  126,500   157,480,575
63   201607  제주특별자치도   제주시   합계  251,096   238,394,186
79   201608  제주특별자치도   제주시   합계  252,693   284,715,205
95   201609  제주특별자치도   제주시   합계  254,132   250,054,420
111  201610  제주특별자치도   제주시   합계  255,203   214,579,012
127  201611  제주특별자치도   제주시   합계  256,658   221,291,306
143  201612  제주특별자치도   제주시   합계  258,700   239,039,811

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[146790898, 169543418, 155766951, 136016360, 140265797, 157480575]
[238394186, 284715205, 250054420, 214579012, 221291306, 239039811]
제주특별자치도 지역별 합계 :  [905863999, 1448073940]
제주특별자치도 고객호수 평균:  [20753, 42457]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_8184\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8184\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
0          201607  제주특별자치도  서귀포시   합계  122,609   146,790,898
1          201608  제주특별자치도  서귀포시   합계  123,417   169,543,418
2          201609  제주특별자치도  서귀포시   합계  124,132   155,766,951
3          201610  제주특별자치도  서귀포시   합계  124,853   136,016,360
4          201611  제주특별자치도  서귀포시   합계  125,603   140,265,797
5          201612  제주특별자치도  서귀포시   합계  126,500   157,480,575
6          201607  제주특별자치도   제주시   합계  251,096   238,394,186
7          201608  제주특별자치도   제주시   합계  252,693   284,715,205
8          201609  제주특별자치도   제주시   합계  254,132   250,054,420
9          201610  제주특별자치도   제주시   합계  255,203   214,579,012
10         201611  제주특별자치도   제주시   합계  256,658   221,291,306
11         201612  제주특별자치도   제주시   합계  258,700   239,039,811
12  201607-201612  제주특별자치도  서귀포시   합계     20753     905863999
13  201607-201612  제주특별자치도   제주시   합계     42457    1448073940

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201607-201612']
Hap

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201607-201612  제주특별자치도  서귀포시   합계   20753   905863999
13  201607-201612  제주특별자치도   제주시   합계   42457  1448073940

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201607  제주특별자치도  서귀포시  일반용  16,486    49,113,400
69   201608  제주특별자치도  서귀포시  일반용  16,722    61,240,949
85   201609  제주특별자치도  서귀포시  일반용  16,889    52,463,057
101  201610  제주특별자치도  서귀포시  일반용  17,003    44,267,503
117  201611  제주특별자치도  서귀포시  일반용  17,188    42,862,072
133  201612  제주특별자치도  서귀포시  일반용  17,426    46,445,622
61   201607  제주특별자치도   제주시  일반용  41,275   106,984,454
77   201608  제주특별자치도   제주시  일반용  41,807   130,529,006
93   201609  제주특별자치도   제주시  일반용  42,170   111,348,187
109  201610  제주특별자치도   제주시  일반용  42,383    91,694,718
125  201611  제주특별자치도   제주시  일반용  42,835    90,615,361
141  201612  제주특별자치도   제주시  일반용  43,391    98,547,398

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[49113400, 61240949, 52463057, 44267503, 42862072, 46445622]
[106984454, 130529006, 111348187, 91694718, 90615361, 98547398]
제주특별자치도 지역별 일반용 합계 :  [296392603, 629719124]
제주특별자치도 고객호수 평균:  [16952, 42310]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_8184\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8184\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0          201607  제주특별자치도  서귀포시  일반용  16,486    49,113,400
1          201608  제주특별자치도  서귀포시  일반용  16,722    61,240,949
2          201609  제주특별자치도  서귀포시  일반용  16,889    52,463,057
3          201610  제주특별자치도  서귀포시  일반용  17,003    44,267,503
4          201611  제주특별자치도  서귀포시  일반용  17,188    42,862,072
5          201612  제주특별자치도  서귀포시  일반용  17,426    46,445,622
6          201607  제주특별자치도   제주시  일반용  41,275   106,984,454
7          201608  제주특별자치도   제주시  일반용  41,807   130,529,006
8          201609  제주특별자치도   제주시  일반용  42,170   111,348,187
9          201610  제주특별자치도   제주시  일반용  42,383    91,694,718
10         201611  제주특별자치도   제주시  일반용  42,835    90,615,361
11         201612  제주특별자치도   제주시  일반용  43,391    98,547,398
12  201607-201612  제주특별자치도  서귀포시  일반용    16952     296392603
13  201607-201612  제주특별자치도   제주시  일반용    42310     629719124

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201607-201612']
GyeonGiHap2

               년월       시구   시군구 계약구분 고객호수(호)   사용량(kWh)
12  201607-201612  제주특별자치도  서귀포시  일반용   16952  296392603
13  201607-201612  제주특별자치도   제주시  일반용   42310  629719124

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201607-201612  제주특별자치도  서귀포시  일반용   16952   296392603
12  201607-201612  제주특별자치도  서귀포시   합계   20753   905863999
13  201607-201612  제주특별자치도   제주시  일반용   42310   629719124
13  201607-201612  제주특별자치도   제주시   합계   42457  1448073940

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[296392603, 629719124]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[905863999, 1448073940]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[32.72, 43.49]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   33
1   43
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0  서귀포시  일반용  33
1   제주시  일반용  43

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201607-201612  제주특별자치도  서귀포시  일반용   16952   296392603  33
1  201607-201612  제주특별자치도  서귀포시   합계   20753   905863999 NaN
2  201607-201612  제주특별자치도   제주시  일반용   42310   629719124  43
3  201607-201612  제주특별자치도   제주시   합계   42457  1448073940 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1607-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)