In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,인천광역시,전체(시 / 군 / 구),주택용,"704,182","302,809,819","35,671,047,769",117.8
4,201507,인천광역시,전체(시 / 군 / 구),일반용,"128,725","443,779,507","64,790,942,654",146.0
...,...,...,...,...,...,...,...,...
523,201512,인천광역시,중구,산업용,536,"65,820,870","7,679,911,181",116.7
524,201512,인천광역시,중구,심 야,"1,443","3,312,624","256,968,136",77.6
525,201512,인천광역시,중구,일반용,"9,962","74,620,856","9,394,701,317",125.9
526,201512,인천광역시,중구,주택용,"30,360","13,355,551","1,650,228,861",123.6
527,201512,인천광역시,중구,합계,"46,581","162,193,595","19,515,561,093",120.3

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,인천광역시,전체(시 / 군 / 구),주택용,"704,182","302,809,819","35,671,047,769",117.8
4,201507,인천광역시,전체(시 / 군 / 구),일반용,"128,725","443,779,507","64,790,942,654",146.0
5,201507,인천광역시,전체(시 / 군 / 구),교육용,995,"25,013,130","3,594,029,345",143.7
6,201507,인천광역시,전체(시 / 군 / 구),산업용,"18,307","1,100,958,753","139,370,693,852",126.6
...,...,...,...,...,...,...,...,...
523,201512,인천광역시,중구,산업용,536,"65,820,870","7,679,911,181",116.7
524,201512,인천광역시,중구,심 야,"1,443","3,312,624","256,968,136",77.6
525,201512,인천광역시,중구,일반용,"9,962","74,620,856","9,394,701,317",125.9
526,201512,인천광역시,중구,주택용,"30,360","13,355,551","1,650,228,861",123.6
527,201512,인천광역시,중구,합계,"46,581","162,193,595","19,515,561,093",120.3

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,인천광역시,전체(시 / 군 / 구),주택용,"704,182","302,809,819","35,671,047,769",117.8
4,201507,인천광역시,전체(시 / 군 / 구),일반용,"128,725","443,779,507","64,790,942,654",146.0
5,201507,인천광역시,전체(시 / 군 / 구),교육용,995,"25,013,130","3,594,029,345",143.7
6,201507,인천광역시,전체(시 / 군 / 구),산업용,"18,307","1,100,958,753","139,370,693,852",126.6
7,201507,인천광역시,전체(시 / 군 / 구),농사용,"20,837","8,823,316","449,060,892",50.9
...,...,...,...,...,...,...,...,...
523,201512,인천광역시,중구,산업용,536,"65,820,870","7,679,911,181",116.7
524,201512,인천광역시,중구,심 야,"1,443","3,312,624","256,968,136",77.6
525,201512,인천광역시,중구,일반용,"9,962","74,620,856","9,394,701,317",125.9
526,201512,인천광역시,중구,주택용,"30,360","13,355,551","1,650,228,861",123.6
527,201512,인천광역시,중구,합계,"46,581","162,193,595","19,515,561,093",120.3

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,인천광역시,전체(시 / 군 / 구),주택용,"704,182","302,809,819","35,671,047,769",117.8
4,201507,인천광역시,전체(시 / 군 / 구),일반용,"128,725","443,779,507","64,790,942,654",146.0
5,201507,인천광역시,전체(시 / 군 / 구),교육용,995,"25,013,130","3,594,029,345",143.7
6,201507,인천광역시,전체(시 / 군 / 구),산업용,"18,307","1,100,958,753","139,370,693,852",126.6
7,201507,인천광역시,전체(시 / 군 / 구),농사용,"20,837","8,823,316","449,060,892",50.9
8,201507,인천광역시,전체(시 / 군 / 구),가로등,"52,132","11,230,721","1,405,494,449",125.1
9,201507,인천광역시,전체(시 / 군 / 구),심 야,"18,107","10,654,072","655,823,618",61.6
10,201508,인천광역시,전체(시 / 군 / 구),주택용,"705,243","367,613,916","51,347,215,595",139.7
11,201508,인천광역시,전체(시 / 군 / 구),일반용,"129,073","502,165,485","70,407,110,738",140.2
12,201508,인천광역시,전체(시 / 군 / 구),교육용,998,"25,363,015","3,618,104,919",142.7
13,201508,인천광역시,전체(시 / 군 / 구),산업용,"18,350","1,131,275,541","133,008,201,757",117.6
14,201508,인천광역시,전체(시 / 군 / 구),농사용,"21,041","11,649,062","567,446,879",48.7
15,201508,인천광역시,전체(시 / 군 / 구),가로등,"52,221","12,076,247","1,456,495,101",120.6
16,201508,인천광역시,전체(시 / 군 / 구),심 야,"18,035","10,250,399","637,233,986",62.2
17,201509,인천광역시,전체(시 / 군 / 구),주택용,"706,752","321,237,055","38,755,855,951",120.6
18,201509,인천광역시,전체(시 / 군 / 구),일반용,"129,304","453,579,013","56,072,043,980",123.6
19,201509,인천광역시,전체(시 / 군 / 구),교육용,997,"25,334,597","2,826,091,361",111.6
20,201509,인천광역시,전체(시 / 군 / 구),산업용,"18,401","1,047,771,639","109,803,791,902",104.8
21,201509,인천광역시,전체(시 / 군 / 구),농사용,"21,171","13,324,075","637,650,004",47.9
22,201509,인천광역시,전체(시 / 군 / 구),가로등,"52,282","12,740,368","1,496,757,367",117.5
23,201509,인천광역시,전체(시 / 군 / 구),심 야,"17,997","8,886,770","539,198,612",60.7
24,201510,인천광역시,전체(시 / 군 / 구),주택용,"707,525","285,006,707","31,964,252,141",112.2
25,201510,인천광역시,전체(시 / 군 / 구),일반용,"129,464","379,934,997","43,679,307,729",115.0
26,201510,인천광역시,전체(시 / 군 / 구),교육용,998,"20,464,056","2,458,124,219",120.1
27,201510,인천광역시,전체(시 / 군 / 구),산업용,"18,400","1,099,532,485","105,288,642,340",95.8
28,201510,인천광역시,전체(시 / 군 / 구),농사용,"21,263","10,241,941","516,727,517",50.5
29,201510,인천광역시,전체(시 / 군 / 구),가로등,"52,967","14,194,005","1,584,545,024",111.6
30,201510,인천광역시,전체(시 / 군 / 구),심 야,"17,959","10,316,938","605,887,975",58.7
31,201511,인천광역시,전체(시 / 군 / 구),주택용,"708,706","303,967,752","36,794,864,119",121.0
32,201511,인천광역시,전체(시 / 군 / 구),일반용,"129,744","380,634,031","50,246,511,331",132.0
33,201511,인천광역시,전체(시 / 군 / 구),교육용,998,"25,158,903","3,241,920,727",128.9
34,201511,인천광역시,전체(시 / 군 / 구),산업용,"18,430","1,113,324,724","130,694,522,937",117.4
35,201511,인천광역시,전체(시 / 군 / 구),농사용,"28,769","20,804,918","756,076,412",36.3
36,201511,인천광역시,전체(시 / 군 / 구),가로등,"52,707","15,391,366","1,682,405,308",109.3
37,201511,인천광역시,전체(시 / 군 / 구),심 야,"17,909","20,697,861","1,352,697,865",65.4
38,201512,인천광역시,전체(시 / 군 / 구),주택용,"709,588","317,714,287","39,926,101,610",125.7
39,201512,인천광역시,전체(시 / 군 / 구),일반용,"130,195","441,183,448","60,456,183,043",137.0
40,201512,인천광역시,전체(시 / 군 / 구),교육용,998,"38,085,600","4,275,906,522",112.3
41,201512,인천광역시,전체(시 / 군 / 구),산업용,"18,449","1,157,487,955","137,299,957,676",118.6
42,201512,인천광역시,전체(시 / 군 / 구),농사용,"25,800","17,103,154","657,497,767",38.4
43,201512,인천광역시,전체(시 / 군 / 구),가로등,"52,820","15,926,061","1,709,543,347",107.3
44,201512,인천광역시,전체(시 / 군 / 구),심 야,"17,852","35,976,450","2,745,713,248",76.3
45,합계,합계,합계,합계,"5,696,691","11,569,684,139","1,375,047,679,588",118.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_7184\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201507  인천광역시  일반용  128,725   443,779,507
11  201508  인천광역시  일반용  129,073   502,165,485
18  201509  인천광역시  일반용  129,304   453,579,013
25  201510  인천광역시  일반용  129,464   379,934,997
32  201511  인천광역시  일반용  129,744   380,634,031
39  201512  인천광역시  일반용  130,195   441,183,448

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  인천광역시  강화군  일반용   7,095   10,912,373
133  201508  인천광역시  강화군  일반용   7,112   13,522,766
213  201509  인천광역시  강화군  일반용   7,151   12,064,442
293  201510  인천광역시  강화군  일반용   7,191   10,231,244
373  201511  인천광역시  강화군  일반용   7,242   11,439,990
453  201512  인천광역시  강화군  일반용   7,264   13,635,249
61   201507  인천광역시  계양구  일반용  12,387   38,054,993
141  201508  인천광역시  계양구  일반용  12,408   43,146,335
221  201509  인천광역시  계양구  일반용  12,400   38,234,872
301  201510  인천광역시  계양구  일반용  12,420   31,343,413
381  201511  인천광역시  계양구  일반용  12,439   31,433,795
461  201512  인천광역시  계양구  일반용  12,471   36,738,995
69   201507  인천광역시   남구  일반용  20,388   48,339,949
149  201508  인천광역시   남구  일반용  20,412   56,092,787
229  201509  인천광역시   남구  일반용  20,442   51,888,215
309  201510  인천광역시   남구  일반용  20,475   41,748,220
389  201511  인천광역시   남구  일반용  20,539   41,411,481
469  201512  인천광역시   남구  일반용  20,562   48,143,252
77   201507  인천광역시  남동구  일반용  21,481   71,523,853
157  201508  인천광역시  남동구  일반용  21,585   82,123,590
237  201509  인천광역시  남동구  일반용  21,656   73,540,706
317  201510  인천광역시  남동구  일반용  21,660   59,996,369
397  201511  인천광역시  남동구  일반용  21,724   59,873,508
477  201512  인천광역시  남동구  일반용  21,818   70,168,118
85   201507  인천광역시   동구  일반용   3,739    9,676,035
165  201508  인천광역시   동구  일반용   3,743   10,793,554
245  201509  인천광역시   동구  일반용   3,734    9,846,834
325  201510  인천광역시   동구  일반용   3,742    8,355,035
405  201511  인천광역시   동구  일반용   3,742    8,632,986
485  201512  인천광역시   동구  일반용   3,745   10,216,361
93   201507  인천광역시  부평구  일반용  22,052   64,459,756
173  201508  인천광역시  부평구  일반용  22,068   73,120,669
253  201509  인천광역시  부평구  일반용  22,081   66,019,818
333  201510  인천광역시  부평구  일반용  22,079   53,711,103
413  201511  인천광역시  부평구  일반용  22,086   52,850,532
493  201512  인천광역시  부평구  일반용  22,170   61,707,571
101  201507  인천광역시   서구  일반용  19,941   65,835,629
181  201508  인천광역시   서구  일반용  20,059   73,626,522
261  201509  인천광역시   서구  일반용  20,109   67,528,227
341  201510  인천광역시   서구  일반용  20,129   57,030,270
421  201511  인천광역시   서구  일반용  20,156   58,565,480
501  201512  인천광역시   서구  일반용  20,277   69,450,471
109  201507  인천광역시  연수구  일반용   8,103   49,897,961
189  201508  인천광역시  연수구  일반용   8,121   55,813,432
269  201509  인천광역시  연수구  일반용   8,121   50,081,125
349  201510  인천광역시  연수구  일반용   8,143   42,548,817
429  201511  인천광역시  연수구  일반용   8,156   42,319,699
509  201512  인천광역시  연수구  일반용   8,181   48,623,514
117  201507  인천광역시  옹진군  일반용   3,687    6,349,138
197  201508  인천광역시  옹진군  일반용   3,689    7,885,362
277  201509  인천광역시  옹진군  일반용   3,705    7,388,472
357  201510  인천광역시  옹진군  일반용   3,714    6,260,326
437  201511  인천광역시  옹진군  일반용   3,735    6,717,027
517  201512  인천광역시  옹진군  일반용   3,745    7,879,061
125  201507  인천광역시   중구  일반용   9,852   78,729,820
205  201508  인천광역시   중구  일반용   9,876   86,040,468
285  201509  인천광역시   중구  일반용   9,905   76,986,302
365  201510  인천광역시   중구  일반용   9,911   68,710,200
445  201511  인천광역시   중구  일반용   9,925   67,389,533
525  201512  인천광역시   중구  일반용   9,962   74,620,856

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201507  인천광역시  강화군   합계   65,497    30,928,642
135  201508  인천광역시  강화군   합계   65,866    36,378,996
215  201509  인천광역시  강화군   합계   66,075    35,397,021
295  201510  인천광역시  강화군   합계   66,257    32,809,601
375  201511  인천광역시  강화군   합계   72,050    47,237,378
455  201512  인천광역시  강화군   합계   70,521    55,219,568
63   201507  인천광역시  계양구   합계   97,590    99,800,407
143  201508  인천광역시  계양구   합계   97,655   159,582,920
223  201509  인천광역시  계양구   합계   97,721    73,361,473
303  201510  인천광역시  계양구   합계   97,761    95,410,657
383  201511  인천광역시  계양구   합계   98,117    99,445,192
463  201512  인천광역시  계양구   합계   97,868   110,597,280
71   201507  인천광역시   남구   합계  182,727   177,001,090
151  201508  인천광역시   남구   합계  182,890   190,180,022
231  201509  인천광역시   남구   합계  183,450   180,333,715
311  201510  인천광역시   남구   합계  183,635   163,755,981
391  201511  인천광역시   남구   합계  183,954   166,944,044
471  201512  인천광역시   남구   합계  184,251   182,135,643
79   201507  인천광역시  남동구   합계  145,953   333,909,472
159  201508  인천광역시  남동구   합계  146,299   341,804,992
239  201509  인천광역시  남동구   합계  146,455   335,014,928
319  201510  인천광역시  남동구   합계  146,662   296,236,859
399  201511  인천광역시  남동구   합계  146,871   312,535,823
479  201512  인천광역시  남동구   합계  147,020   346,403,553
87   201507  인천광역시   동구   합계   24,190   309,718,985
167  201508  인천광역시   동구   합계   24,184   326,444,689
247  201509  인천광역시   동구   합계   24,168   310,302,497
327  201510  인천광역시   동구   합계   24,167   342,917,846
407  201511  인천광역시   동구   합계   24,169   344,887,522
487  201512  인천광역시   동구   합계   24,159   330,268,210
95   201507  인천광역시  부평구   합계  163,520   202,084,117
175  201508  인천광역시  부평구   합계  163,574   215,885,739
255  201509  인천광역시  부평구   합계  163,831   202,621,433
335  201510  인천광역시  부평구   합계  163,770   177,741,476
415  201511  인천광역시  부평구   합계  163,982   184,440,465
495  201512  인천광역시  부평구   합계  163,984   204,541,617
103  201507  인천광역시   서구   합계  141,887   415,743,118
183  201508  인천광역시   서구   합계  142,203   422,170,021
263  201509  인천광역시   서구   합계  142,617   411,547,087
343  201510  인천광역시   서구   합계  142,907   397,914,495
423  201511  인천광역시   서구   합계  143,280   407,664,955
503  201512  인천광역시   서구   합계  143,682   448,483,947
111  201507  인천광역시  연수구   합계   55,412   162,330,711
191  201508  인천광역시  연수구   합계   55,481   180,847,120
271  201509  인천광역시  연수구   합계   55,524   159,966,848
351  201510  인천광역시  연수구   합계   55,552   144,254,846
431  201511  인천광역시  연수구   합계   55,608   149,207,178
511  201512  인천광역시  연수구   합계   55,609   165,878,804
119  201507  인천광역시  옹진군   합계   21,000    11,929,766
199  201508  인천광역시  옹진군   합계   21,053    14,597,149
279  201509  인천광역시  옹진군   합계   21,114    13,571,679
359  201510  인천광역시  옹진군   합계   21,793    18,898,808
439  201511  인천광역시  옹진군   합계   22,521    18,433,265
519  201512  인천광역시  옹진군   합계   22,027    17,754,738
127  201507  인천광역시   중구   합계   45,509   159,823,010
207  201508  인천광역시   중구   합계   45,756   172,502,017
287  201509  인천광역시   중구   합계   45,949   160,756,836
367  201510  인천광역시   중구   합계   46,072   149,750,560
447  201511  인천광역시   중구   합계   46,711   149,183,733
527  201512  인천광역시   중구   합계   46,581   162,193,595

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[30928642, 36378996, 35397021, 32809601, 47237378, 55219568]
[99800407, 159582920, 73361473, 95410657, 99445192, 110597280]
[177001090, 190180022, 180333715, 163755981, 166944044, 182135643]
[333909472, 341804992, 335014928, 296236859, 312535823, 346403553]
[309718985, 326444689, 310302497, 342917846, 344887522, 330268210]
[202084117, 215885739, 202621433, 177741476, 184440465, 204541617]
[415743118, 422170021, 411547087, 397914495, 407664955, 448483947]
[162330711, 180847120, 159966848, 144254846, 149207178, 165878804]
[11929766, 14597149, 13571679, 18898808, 18433265, 17754738]
[159823010, 172502017, 160756836, 149750560, 149183733, 162193595]
인천광역시 지역별 합계 :  [237971206, 638197929, 1060350495, 1965905627, 1964539749, 1187314847, 2503523623, 962485507, 95185405, 954209751]
인천광역시 고객호수 평균:  [11285, 16297, 30580, 24423, 4028, 27296, 23793, 9255, 3597, 7682]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201507  인천광역시  강화군   합계  65,497   30,928,642
1          201508  인천광역시  강화군   합계  65,866   36,378,996
2          201509  인천광역시  강화군   합계  66,075   35,397,021
3          201510  인천광역시  강화군   합계  66,257   32,809,601
4          201511  인천광역시  강화군   합계  72,050   47,237,378
..            ...    ...  ...  ...      ...          ...
65  201507-201512  인천광역시  부평구   합계    27296   1187314847
66  201507-201512  인천광역시   서구   합계    23793   2503523623
67  201507-201512  인천광역시  연수구   합계     9255    962485507
68  201507-201512  인천광역시  옹진군   합계     3597     95185405
69  201507-201512  인천광역시   중구   합계     7682    954209751

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201507-201512  인천광역시  강화군   합계   11285   237971206
61  201507-201512  인천광역시  계양구   합계   16297   638197929
62  201507-201512  인천광역시   남구   합계   30580  1060350495
63  201507-201512  인천광역시  남동구   합계   24423  1965905627
64  201507-201512  인천광역시   동구   합계    4028  1964539749
65  201507-201512  인천광역시  부평구   합계   27296  1187314847
66  201507-201512  인천광역시   서구   합계   23793  2503523623
67  201507-201512  인천광역시  연수구   합계    9255   962485507
68  201507-201512  인천광역시  옹진군   합계    3597    95185405
69  201507-201512  인천광역시   중구   합계    7682   954209751

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  인천광역시  강화군  일반용   7,095   10,912,373
133  201508  인천광역시  강화군  일반용   7,112   13,522,766
213  201509  인천광역시  강화군  일반용   7,151   12,064,442
293  201510  인천광역시  강화군  일반용   7,191   10,231,244
373  201511  인천광역시  강화군  일반용   7,242   11,439,990
453  201512  인천광역시  강화군  일반용   7,264   13,635,249
61   201507  인천광역시  계양구  일반용  12,387   38,054,993
141  201508  인천광역시  계양구  일반용  12,408   43,146,335
221  201509  인천광역시  계양구  일반용  12,400   38,234,872
301  201510  인천광역시  계양구  일반용  12,420   31,343,413
381  201511  인천광역시  계양구  일반용  12,439   31,433,795
461  201512  인천광역시  계양구  일반용  12,471   36,738,995
69   201507  인천광역시   남구  일반용  20,388   48,339,949
149  201508  인천광역시   남구  일반용  20,412   56,092,787
229  201509  인천광역시   남구  일반용  20,442   51,888,215
309  201510  인천광역시   남구  일반용  20,475   41,748,220
389  201511  인천광역시   남구  일반용  20,539   41,411,481
469  201512  인천광역시   남구  일반용  20,562   48,143,252
77   201507  인천광역시  남동구  일반용  21,481   71,523,853
157  201508  인천광역시  남동구  일반용  21,585   82,123,590
237  201509  인천광역시  남동구  일반용  21,656   73,540,706
317  201510  인천광역시  남동구  일반용  21,660   59,996,369
397  201511  인천광역시  남동구  일반용  21,724   59,873,508
477  201512  인천광역시  남동구  일반용  21,818   70,168,118
85   201507  인천광역시   동구  일반용   3,739    9,676,035
165  201508  인천광역시   동구  일반용   3,743   10,793,554
245  201509  인천광역시   동구  일반용   3,734    9,846,834
325  201510  인천광역시   동구  일반용   3,742    8,355,035
405  201511  인천광역시   동구  일반용   3,742    8,632,986
485  201512  인천광역시   동구  일반용   3,745   10,216,361
93   201507  인천광역시  부평구  일반용  22,052   64,459,756
173  201508  인천광역시  부평구  일반용  22,068   73,120,669
253  201509  인천광역시  부평구  일반용  22,081   66,019,818
333  201510  인천광역시  부평구  일반용  22,079   53,711,103
413  201511  인천광역시  부평구  일반용  22,086   52,850,532
493  201512  인천광역시  부평구  일반용  22,170   61,707,571
101  201507  인천광역시   서구  일반용  19,941   65,835,629
181  201508  인천광역시   서구  일반용  20,059   73,626,522
261  201509  인천광역시   서구  일반용  20,109   67,528,227
341  201510  인천광역시   서구  일반용  20,129   57,030,270
421  201511  인천광역시   서구  일반용  20,156   58,565,480
501  201512  인천광역시   서구  일반용  20,277   69,450,471
109  201507  인천광역시  연수구  일반용   8,103   49,897,961
189  201508  인천광역시  연수구  일반용   8,121   55,813,432
269  201509  인천광역시  연수구  일반용   8,121   50,081,125
349  201510  인천광역시  연수구  일반용   8,143   42,548,817
429  201511  인천광역시  연수구  일반용   8,156   42,319,699
509  201512  인천광역시  연수구  일반용   8,181   48,623,514
117  201507  인천광역시  옹진군  일반용   3,687    6,349,138
197  201508  인천광역시  옹진군  일반용   3,689    7,885,362
277  201509  인천광역시  옹진군  일반용   3,705    7,388,472
357  201510  인천광역시  옹진군  일반용   3,714    6,260,326
437  201511  인천광역시  옹진군  일반용   3,735    6,717,027
517  201512  인천광역시  옹진군  일반용   3,745    7,879,061
125  201507  인천광역시   중구  일반용   9,852   78,729,820
205  201508  인천광역시   중구  일반용   9,876   86,040,468
285  201509  인천광역시   중구  일반용   9,905   76,986,302
365  201510  인천광역시   중구  일반용   9,911   68,710,200
445  201511  인천광역시   중구  일반용   9,925   67,389,533
525  201512  인천광역시   중구  일반용   9,962   74,620,856

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[10912373, 13522766, 12064442, 10231244, 11439990, 13635249]
[38054993, 43146335, 38234872, 31343413, 31433795, 36738995]
[48339949, 56092787, 51888215, 41748220, 41411481, 48143252]
[71523853, 82123590, 73540706, 59996369, 59873508, 70168118]
[9676035, 10793554, 9846834, 8355035, 8632986, 10216361]
[64459756, 73120669, 66019818, 53711103, 52850532, 61707571]
[65835629, 73626522, 67528227, 57030270, 58565480, 69450471]
[49897961, 55813432, 50081125, 42548817, 42319699, 48623514]
[6349138, 7885362, 7388472, 6260326, 6717027, 7879061]
[78729820, 86040468, 76986302, 68710200, 67389533, 74620856]
인천광역시 지역별 일반용 합계 :  [71806064, 218952403, 287623904, 417226144, 57520805, 371869449, 392036599, 289284548, 42479386, 452477179]
인천광역시 고객호수 평균:  [7175, 12420, 20469, 21654, 3740, 22089, 20111, 8137, 3712, 9905]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7184\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201507  인천광역시  강화군  일반용  7,095   10,912,373
1          201508  인천광역시  강화군  일반용  7,112   13,522,766
2          201509  인천광역시  강화군  일반용  7,151   12,064,442
3          201510  인천광역시  강화군  일반용  7,191   10,231,244
4          201511  인천광역시  강화군  일반용  7,242   11,439,990
..            ...    ...  ...  ...     ...          ...
65  201507-201512  인천광역시  부평구  일반용   22089    371869449
66  201507-201512  인천광역시   서구  일반용   20111    392036599
67  201507-201512  인천광역시  연수구  일반용    8137    289284548
68  201507-201512  인천광역시  옹진군  일반용    3712     42479386
69  201507-201512  인천광역시   중구  일반용    9905    452477179

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201507-201512  인천광역시  강화군  일반용    7175   71806064
61  201507-201512  인천광역시  계양구  일반용   12420  218952403
62  201507-201512  인천광역시   남구  일반용   20469  287623904
63  201507-201512  인천광역시  남동구  일반용   21654  417226144
64  201507-201512  인천광역시   동구  일반용    3740   57520805
65  201507-201512  인천광역시  부평구  일반용   22089  371869449
66  201507-201512  인천광역시   서구  일반용   20111  392036599
67  201507-201512  인천광역시  연수구  일반용    8137  289284548
68  201507-201512  인천광역시  옹진군  일반용    3712   42479386
69  201507-201512  인천광역시   중구  일반용    9905  452477179

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201507-201512  인천광역시  강화군  일반용    7175    71806064
60  201507-201512  인천광역시  강화군   합계   11285   237971206
61  201507-201512  인천광역시  계양구  일반용   12420   218952403
61  201507-201512  인천광역시  계양구   합계   16297   638197929
62  201507-201512  인천광역시   남구  일반용   20469   287623904
62  201507-201512  인천광역시   남구   합계   30580  1060350495
63  201507-201512  인천광역시  남동구  일반용   21654   417226144
63  201507-201512  인천광역시  남동구   합계   24423  1965905627
64  201507-201512  인천광역시   동구  일반용    3740    57520805
64  201507-201512  인천광역시   동구   합계    4028  1964539749
65  201507-201512  인천광역시  부평구  일반용   22089   371869449
65  201507-201512  인천광역시  부평구   합계   27296  1187314847
66  201507-201512  인천광역시   서구  일반용   20111   392036599
66  201507-201512  인천광역시   서구   합계   23793  2503523623
67  201507-201512  인천광역시  연수구   합계    9255   962485507
67  201507-201512  인천광역시  연수구  일반용    8137   289284548
68  201507-201512  인천광역시  옹진군   합계    3597    95185405
68  201507-201512  인천광역시  옹진군  일반용    3712    42479386
69  201507-201512  인천광역시   중구  일반용    9905   452477179
69  201507-201512  인천광역시   중구   합계    7682   954209751

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[71806064,
 218952403,
 287623904,
 417226144,
 57520805,
 371869449,
 392036599,
 289284548,
 42479386,
 452477179]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[237971206,
 638197929,
 1060350495,
 1965905627,
 1964539749,
 1187314847,
 2503523623,
 962485507,
 95185405,
 954209751]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[30.17, 34.31, 27.13, 21.22, 2.93, 31.32, 15.66, 30.06, 44.63, 47.42]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   30
1   34
2   27
3   21
4    3
5   31
6   16
7   30
8   45
9   47
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  30
1  계양구  일반용  34
2   남구  일반용  27
3  남동구  일반용  21
4   동구  일반용   3
5  부평구  일반용  31
6   서구  일반용  16
7  연수구  일반용  30
8  옹진군  일반용  45
9   중구  일반용  47

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201507-201512  인천광역시  강화군  일반용    7175    71806064  30
1   201507-201512  인천광역시  강화군   합계   11285   237971206 NaN
2   201507-201512  인천광역시  계양구  일반용   12420   218952403  34
3   201507-201512  인천광역시  계양구   합계   16297   638197929 NaN
4   201507-201512  인천광역시   남구  일반용   20469   287623904  27
5   201507-201512  인천광역시   남구   합계   30580  1060350495 NaN
6   201507-201512  인천광역시  남동구  일반용   21654   417226144  21
7   201507-201512  인천광역시  남동구   합계   24423  1965905627 NaN
8   201507-201512  인천광역시   동구  일반용    3740    57520805   3
9   201507-201512  인천광역시   동구   합계    4028  1964539749 NaN
10  201507-201512  인천광역시  부평구  일반용   22089   371869449  31
11  201507-201512  인천광역시  부평구   합계   27296  1187314847 NaN
12  201507-201512  인천광역시   서구  일반용   20111   392036599  16
13  201507-201512  인천광역시   서구   합계   23793  2503523623 NaN
15  201507-201512  인천광역시  연수구  일반용    8137   289284548  30
14  201507-201512  인천광역시  연수구   합계    9255   962485507 NaN
17  201507-201512  인천광역시  옹진군  일반용    3712    42479386  45
16  201507-201512  인천광역시  옹진군   합계    3597    95185405 NaN
18  201507-201512  인천광역시   중구  일반용    9905   452477179  47
19  201507-201512  인천광역시   중구   합계    7682   954209751 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)