In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별_전력사용량_월별_16하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2016년 07 월 ~ 2016년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,인천광역시,전체(시 / 군 / 구),주택용,"719,439","318,963,163","40,547,073,904",127.1
4,201607,인천광역시,전체(시 / 군 / 구),일반용,"131,560","473,824,587","68,055,225,480",143.6
...,...,...,...,...,...,...,...,...
523,201612,인천광역시,중구,산업용,548,"72,560,052","8,569,013,374",118.1
524,201612,인천광역시,중구,심 야,"1,401","3,275,180","252,974,197",77.2
525,201612,인천광역시,중구,일반용,"10,357","78,657,528","9,954,246,581",126.6
526,201612,인천광역시,중구,주택용,"33,382","13,520,943","1,571,198,846",116.2
527,201612,인천광역시,중구,합계,"50,311","173,461,748","20,901,456,577",120.5

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,인천광역시,전체(시 / 군 / 구),주택용,"719,439","318,963,163","40,547,073,904",127.1
4,201607,인천광역시,전체(시 / 군 / 구),일반용,"131,560","473,824,587","68,055,225,480",143.6
5,201607,인천광역시,전체(시 / 군 / 구),교육용,994,"27,303,692","3,664,385,269",134.2
6,201607,인천광역시,전체(시 / 군 / 구),산업용,"18,638","1,167,332,576","140,962,743,123",120.8
...,...,...,...,...,...,...,...,...
523,201612,인천광역시,중구,산업용,548,"72,560,052","8,569,013,374",118.1
524,201612,인천광역시,중구,심 야,"1,401","3,275,180","252,974,197",77.2
525,201612,인천광역시,중구,일반용,"10,357","78,657,528","9,954,246,581",126.6
526,201612,인천광역시,중구,주택용,"33,382","13,520,943","1,571,198,846",116.2
527,201612,인천광역시,중구,합계,"50,311","173,461,748","20,901,456,577",120.5

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,인천광역시,전체(시 / 군 / 구),주택용,"719,439","318,963,163","40,547,073,904",127.1
4,201607,인천광역시,전체(시 / 군 / 구),일반용,"131,560","473,824,587","68,055,225,480",143.6
5,201607,인천광역시,전체(시 / 군 / 구),교육용,994,"27,303,692","3,664,385,269",134.2
6,201607,인천광역시,전체(시 / 군 / 구),산업용,"18,638","1,167,332,576","140,962,743,123",120.8
7,201607,인천광역시,전체(시 / 군 / 구),농사용,"21,929","9,602,402","478,332,082",49.8
...,...,...,...,...,...,...,...,...
523,201612,인천광역시,중구,산업용,548,"72,560,052","8,569,013,374",118.1
524,201612,인천광역시,중구,심 야,"1,401","3,275,180","252,974,197",77.2
525,201612,인천광역시,중구,일반용,"10,357","78,657,528","9,954,246,581",126.6
526,201612,인천광역시,중구,주택용,"33,382","13,520,943","1,571,198,846",116.2
527,201612,인천광역시,중구,합계,"50,311","173,461,748","20,901,456,577",120.5

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,인천광역시,전체(시 / 군 / 구),주택용,"719,439","318,963,163","40,547,073,904",127.1
4,201607,인천광역시,전체(시 / 군 / 구),일반용,"131,560","473,824,587","68,055,225,480",143.6
5,201607,인천광역시,전체(시 / 군 / 구),교육용,994,"27,303,692","3,664,385,269",134.2
6,201607,인천광역시,전체(시 / 군 / 구),산업용,"18,638","1,167,332,576","140,962,743,123",120.8
7,201607,인천광역시,전체(시 / 군 / 구),농사용,"21,929","9,602,402","478,332,082",49.8
8,201607,인천광역시,전체(시 / 군 / 구),가로등,"53,800","11,212,454","1,411,124,656",125.9
9,201607,인천광역시,전체(시 / 군 / 구),심 야,"17,483","10,385,202","642,316,752",61.8
10,201608,인천광역시,전체(시 / 군 / 구),주택용,"720,894","422,318,226","68,918,709,505",163.2
11,201608,인천광역시,전체(시 / 군 / 구),일반용,"131,874","555,209,639","77,397,515,689",139.4
12,201608,인천광역시,전체(시 / 군 / 구),교육용,996,"29,091,230","4,032,339,240",138.6
13,201608,인천광역시,전체(시 / 군 / 구),산업용,"18,633","1,117,775,877","138,546,613,707",123.9
14,201608,인천광역시,전체(시 / 군 / 구),농사용,"22,054","13,313,302","640,070,424",48.1
15,201608,인천광역시,전체(시 / 군 / 구),가로등,"53,891","11,849,094","1,446,244,206",122.1
16,201608,인천광역시,전체(시 / 군 / 구),심 야,"17,440","9,939,401","622,424,787",62.6
17,201609,인천광역시,전체(시 / 군 / 구),주택용,"722,695","355,262,365","28,631,771,079",80.6
18,201609,인천광역시,전체(시 / 군 / 구),일반용,"132,050","488,378,903","59,931,853,241",122.7
19,201609,인천광역시,전체(시 / 군 / 구),교육용,996,"25,658,822","2,735,322,795",106.6
20,201609,인천광역시,전체(시 / 군 / 구),산업용,"18,676","1,039,984,278","107,596,272,586",103.5
21,201609,인천광역시,전체(시 / 군 / 구),농사용,"22,165","15,805,308","731,258,571",46.3
22,201609,인천광역시,전체(시 / 군 / 구),가로등,"54,054","13,057,818","1,530,093,557",117.2
23,201609,인천광역시,전체(시 / 군 / 구),심 야,"17,374","8,317,076","508,737,804",61.2
24,201610,인천광역시,전체(시 / 군 / 구),주택용,"724,133","290,160,430","30,782,317,176",106.1
25,201610,인천광역시,전체(시 / 군 / 구),일반용,"132,162","400,040,283","46,030,494,929",115.1
26,201610,인천광역시,전체(시 / 군 / 구),교육용,998,"20,944,179","2,520,022,386",120.3
27,201610,인천광역시,전체(시 / 군 / 구),산업용,"18,703","1,074,484,741","105,811,340,693",98.5
28,201610,인천광역시,전체(시 / 군 / 구),농사용,"22,255","11,489,667","569,426,016",49.6
29,201610,인천광역시,전체(시 / 군 / 구),가로등,"54,214","14,103,142","1,587,576,439",112.6
30,201610,인천광역시,전체(시 / 군 / 구),심 야,"17,314","9,338,978","548,715,680",58.8
31,201611,인천광역시,전체(시 / 군 / 구),주택용,"725,986","308,215,970","36,971,972,964",120.0
32,201611,인천광역시,전체(시 / 군 / 구),일반용,"132,580","406,347,619","53,994,234,543",132.9
33,201611,인천광역시,전체(시 / 군 / 구),교육용,996,"30,114,254","3,746,982,005",124.4
34,201611,인천광역시,전체(시 / 군 / 구),산업용,"18,730","1,162,429,001","138,140,120,541",118.8
35,201611,인천광역시,전체(시 / 군 / 구),농사용,"30,005","18,365,902","714,833,482",38.9
36,201611,인천광역시,전체(시 / 군 / 구),가로등,"54,382","15,371,381","1,689,107,603",109.9
37,201611,인천광역시,전체(시 / 군 / 구),심 야,"17,272","21,495,192","1,415,351,769",65.8
38,201612,인천광역시,전체(시 / 군 / 구),주택용,"726,868","322,444,607","37,872,725,252",117.5
39,201612,인천광역시,전체(시 / 군 / 구),일반용,"133,056","469,501,492","64,462,680,863",137.3
40,201612,인천광역시,전체(시 / 군 / 구),교육용,998,"40,220,812","4,290,595,184",106.7
41,201612,인천광역시,전체(시 / 군 / 구),산업용,"18,721","1,203,087,047","145,176,859,397",120.7
42,201612,인천광역시,전체(시 / 군 / 구),농사용,"26,804","15,497,373","643,001,953",41.5
43,201612,인천광역시,전체(시 / 군 / 구),가로등,"54,583","16,411,607","1,760,403,050",107.3
44,201612,인천광역시,전체(시 / 군 / 구),심 야,"17,208","35,693,888","2,722,176,032",76.3
45,합계,합계,합계,합계,"5,825,603","12,010,342,980","1,430,481,366,414",119.1

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_6304\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201607  인천광역시  일반용  131,560   473,824,587
11  201608  인천광역시  일반용  131,874   555,209,639
18  201609  인천광역시  일반용  132,050   488,378,903
25  201610  인천광역시  일반용  132,162   400,040,283
32  201611  인천광역시  일반용  132,580   406,347,619
39  201612  인천광역시  일반용  133,056   469,501,492

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201607  인천광역시  강화군  일반용   7,312   11,813,985
133  201608  인천광역시  강화군  일반용   7,324   14,836,851
213  201609  인천광역시  강화군  일반용   7,373   13,738,899
293  201610  인천광역시  강화군  일반용   7,410   10,944,103
373  201611  인천광역시  강화군  일반용   7,418   12,140,184
453  201612  인천광역시  강화군  일반용   7,445   14,898,223
61   201607  인천광역시  계양구  일반용  12,512   39,565,645
141  201608  인천광역시  계양구  일반용  12,560   46,595,604
221  201609  인천광역시  계양구  일반용  12,560   40,187,616
301  201610  인천광역시  계양구  일반용  12,585   32,336,550
381  201611  인천광역시  계양구  일반용  12,618   32,542,048
461  201612  인천광역시  계양구  일반용  12,679   37,870,083
69   201607  인천광역시   남구  일반용  20,783   49,972,412
149  201608  인천광역시   남구  일반용  20,825   60,373,727
229  201609  인천광역시   남구  일반용  20,845   54,327,414
309  201610  인천광역시   남구  일반용  20,816   42,956,146
389  201611  인천광역시   남구  일반용  20,875   43,495,693
469  201612  인천광역시   남구  일반용  20,930   50,577,014
77   201607  인천광역시  남동구  일반용  22,020   76,742,289
157  201608  인천광역시  남동구  일반용  22,080   90,919,690
237  201609  인천광역시  남동구  일반용  22,087   78,878,545
317  201610  인천광역시  남동구  일반용  22,097   63,243,759
397  201611  인천광역시  남동구  일반용  22,170   63,708,772
477  201612  인천광역시  남동구  일반용  22,257   73,883,273
85   201607  인천광역시   동구  일반용   3,739    9,540,775
165  201608  인천광역시   동구  일반용   3,739   11,219,434
245  201609  인천광역시   동구  일반용   3,748    9,634,613
325  201610  인천광역시   동구  일반용   3,741    8,039,188
405  201611  인천광역시   동구  일반용   3,746    8,678,777
485  201612  인천광역시   동구  일반용   3,748   10,267,510
93   201607  인천광역시  부평구  일반용  22,193   67,185,437
173  201608  인천광역시  부평구  일반용  22,225   78,971,973
253  201609  인천광역시  부평구  일반용  22,219   69,749,929
333  201610  인천광역시  부평구  일반용  22,202   55,745,363
413  201611  인천광역시  부평구  일반용  22,270   55,652,141
493  201612  인천광역시  부평구  일반용  22,326   64,856,719
101  201607  인천광역시   서구  일반용  20,756   71,546,078
181  201608  인천광역시   서구  일반용  20,827   83,772,629
261  201609  인천광역시   서구  일반용  20,858   75,034,704
341  201610  인천광역시   서구  일반용  20,910   62,179,718
421  201611  인천광역시   서구  일반용  20,962   65,496,560
501  201612  인천광역시   서구  일반용  21,036   77,090,167
109  201607  인천광역시  연수구  일반용   8,286   55,523,381
189  201608  인천광역시  연수구  일반용   8,288   64,124,610
269  201609  인천광역시  연수구  일반용   8,314   54,969,428
349  201610  인천광역시  연수구  일반용   8,343   45,507,720
429  201611  인천광역시  연수구  일반용   8,352   45,774,306
509  201612  인천광역시  연수구  일반용   8,397   52,897,027
117  201607  인천광역시  옹진군  일반용   3,791    6,704,149
197  201608  인천광역시  옹진군  일반용   3,826    8,559,648
277  201609  인천광역시  옹진군  일반용   3,844    7,927,746
357  201610  인천광역시  옹진군  일반용   3,868    6,624,443
437  201611  인천광역시  옹진군  일반용   3,883    7,297,647
517  201612  인천광역시  옹진군  일반용   3,881    8,503,948
125  201607  인천광역시   중구  일반용  10,168   85,230,436
205  201608  인천광역시   중구  일반용  10,180   95,835,473
285  201609  인천광역시   중구  일반용  10,202   83,930,009
365  201610  인천광역시   중구  일반용  10,190   72,463,293
445  201611  인천광역시   중구  일반용  10,286   71,561,491
525  201612  인천광역시   중구  일반용  10,357   78,657,528

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201607  인천광역시  강화군   합계   67,573    33,133,526
135  201608  인천광역시  강화군   합계   67,790    39,957,009
215  201609  인천광역시  강화군   합계   68,059    40,323,502
295  201610  인천광역시  강화군   합계   68,253    35,020,904
375  201611  인천광역시  강화군   합계   74,328    47,302,394
455  201612  인천광역시  강화군   합계   72,679    55,890,518
63   201607  인천광역시  계양구   합계   98,416   108,858,351
143  201608  인천광역시  계양구   합계   98,474   128,464,491
223  201609  인천광역시  계양구   합계   98,467   111,970,107
303  201610  인천광역시  계양구   합계   98,656    95,742,418
383  201611  인천광역시  계양구   합계   99,021   101,042,479
463  201612  인천광역시  계양구   합계   98,768   112,076,810
71   201607  인천광역시   남구   합계  186,960   180,985,459
151  201608  인천광역시   남구   합계  187,461   209,719,766
231  201609  인천광역시   남구   합계  188,067   190,250,150
311  201610  인천광역시   남구   합계  188,321   164,535,139
391  201611  인천광역시   남구   합계  188,957   175,328,799
471  201612  인천광역시   남구   합계  189,537   188,676,551
79   201607  인천광역시  남동구   합계  147,988   339,039,152
159  201608  인천광역시  남동구   합계  148,203   366,640,494
239  201609  인천광역시  남동구   합계  148,337   336,970,373
319  201610  인천광역시  남동구   합계  148,445   309,566,406
399  201611  인천광역시  남동구   합계  148,840   332,591,128
479  201612  인천광역시  남동구   합계  149,040   360,055,982
87   201607  인천광역시   동구   합계   24,045   351,514,155
167  201608  인천광역시   동구   합계   24,047   306,674,150
247  201609  인천광역시   동구   합계   24,046   285,724,166
327  201610  인천광역시   동구   합계   24,036   346,426,103
407  201611  인천광역시   동구   합계   24,026   335,754,657
487  201612  인천광역시   동구   합계   23,992   331,003,716
95   201607  인천광역시  부평구   합계  165,653   207,678,688
175  201608  인천광역시  부평구   합계  165,847   234,204,774
255  201609  인천광역시  부평구   합계  165,986   210,117,551
335  201610  인천광역시  부평구   합계  165,972   183,557,429
415  201611  인천광역시  부평구   합계  165,905   191,513,755
495  201612  인천광역시  부평구   합계  165,325   212,284,140
103  201607  인천광역시   서구   합계  146,875   431,435,961
183  201608  인천광역시   서구   합계  147,317   463,364,725
263  201609  인천광역시   서구   합계  147,813   404,818,801
343  201610  인천광역시   서구   합계  148,297   351,430,405
423  201611  인천광역시   서구   합계  148,921   431,869,807
503  201612  인천광역시   서구   합계  149,322   470,013,584
111  201607  인천광역시  연수구   합계   56,111   177,098,697
191  201608  인천광역시  연수구   합계   56,177   203,978,388
271  201609  인천광역시  연수구   합계   56,258   174,339,429
351  201610  인천광역시  연수구   합계   56,372   157,151,915
431  201611  인천광역시  연수구   합계   56,489   164,296,025
511  201612  인천광역시  연수구   합계   56,675   180,715,283
119  201607  인천광역시  옹진군   합계   22,006    14,865,186
199  201608  인천광역시  옹진군   합계   22,054    16,593,174
279  201609  인천광역시  옹진군   합계   22,125    18,316,567
359  201610  인천광역시  옹진군   합계   22,156    16,710,968
439  201611  인천광역시  옹진군   합계   23,161    19,956,326
519  201612  인천광역시  옹진군   합계   22,589    18,678,494
127  201607  인천광역시   중구   합계   48,216   174,014,901
207  201608  인천광역시   중구   합계   48,412   189,899,798
287  201609  인천광역시   중구   합계   48,852   173,633,924
367  201610  인천광역시   중구   합계   49,271   160,419,733
447  201611  인천광역시   중구   합계   50,303   162,683,949
527  201612  인천광역시   중구   합계   50,311   173,461,748

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[33133526, 39957009, 40323502, 35020904, 47302394, 55890518]
[108858351, 128464491, 111970107, 95742418, 101042479, 112076810]
[180985459, 209719766, 190250150, 164535139, 175328799, 188676551]
[339039152, 366640494, 336970373, 309566406, 332591128, 360055982]
[351514155, 306674150, 285724166, 346426103, 335754657, 331003716]
[207678688, 234204774, 210117551, 183557429, 191513755, 212284140]
[431435961, 463364725, 404818801, 351430405, 431869807, 470013584]
[177098697, 203978388, 174339429, 157151915, 164296025, 180715283]
[14865186, 16593174, 18316567, 16710968, 19956326, 18678494]
[174014901, 189899798, 173633924, 160419733, 162683949, 173461748]
인천광역시 지역별 합계 :  [251627853, 658154656, 1109495864, 2044863535, 1957096947, 1239356337, 2552933283, 1057579737, 105120715, 1034114053]
인천광역시 고객호수 평균:  [11630, 16438, 31369, 24745, 4005, 27630, 24681, 9391, 3724, 8204]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201607  인천광역시  강화군   합계  67,573   33,133,526
1          201608  인천광역시  강화군   합계  67,790   39,957,009
2          201609  인천광역시  강화군   합계  68,059   40,323,502
3          201610  인천광역시  강화군   합계  68,253   35,020,904
4          201611  인천광역시  강화군   합계  74,328   47,302,394
..            ...    ...  ...  ...      ...          ...
65  201607-201612  인천광역시  부평구   합계    27630   1239356337
66  201607-201612  인천광역시   서구   합계    24681   2552933283
67  201607-201612  인천광역시  연수구   합계     9391   1057579737
68  201607-201612  인천광역시  옹진군   합계     3724    105120715
69  201607-201612  인천광역시   중구   합계     8204   1034114053

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201607-201612']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201607-201612  인천광역시  강화군   합계   11630   251627853
61  201607-201612  인천광역시  계양구   합계   16438   658154656
62  201607-201612  인천광역시   남구   합계   31369  1109495864
63  201607-201612  인천광역시  남동구   합계   24745  2044863535
64  201607-201612  인천광역시   동구   합계    4005  1957096947
65  201607-201612  인천광역시  부평구   합계   27630  1239356337
66  201607-201612  인천광역시   서구   합계   24681  2552933283
67  201607-201612  인천광역시  연수구   합계    9391  1057579737
68  201607-201612  인천광역시  옹진군   합계    3724   105120715
69  201607-201612  인천광역시   중구   합계    8204  1034114053

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201607  인천광역시  강화군  일반용   7,312   11,813,985
133  201608  인천광역시  강화군  일반용   7,324   14,836,851
213  201609  인천광역시  강화군  일반용   7,373   13,738,899
293  201610  인천광역시  강화군  일반용   7,410   10,944,103
373  201611  인천광역시  강화군  일반용   7,418   12,140,184
453  201612  인천광역시  강화군  일반용   7,445   14,898,223
61   201607  인천광역시  계양구  일반용  12,512   39,565,645
141  201608  인천광역시  계양구  일반용  12,560   46,595,604
221  201609  인천광역시  계양구  일반용  12,560   40,187,616
301  201610  인천광역시  계양구  일반용  12,585   32,336,550
381  201611  인천광역시  계양구  일반용  12,618   32,542,048
461  201612  인천광역시  계양구  일반용  12,679   37,870,083
69   201607  인천광역시   남구  일반용  20,783   49,972,412
149  201608  인천광역시   남구  일반용  20,825   60,373,727
229  201609  인천광역시   남구  일반용  20,845   54,327,414
309  201610  인천광역시   남구  일반용  20,816   42,956,146
389  201611  인천광역시   남구  일반용  20,875   43,495,693
469  201612  인천광역시   남구  일반용  20,930   50,577,014
77   201607  인천광역시  남동구  일반용  22,020   76,742,289
157  201608  인천광역시  남동구  일반용  22,080   90,919,690
237  201609  인천광역시  남동구  일반용  22,087   78,878,545
317  201610  인천광역시  남동구  일반용  22,097   63,243,759
397  201611  인천광역시  남동구  일반용  22,170   63,708,772
477  201612  인천광역시  남동구  일반용  22,257   73,883,273
85   201607  인천광역시   동구  일반용   3,739    9,540,775
165  201608  인천광역시   동구  일반용   3,739   11,219,434
245  201609  인천광역시   동구  일반용   3,748    9,634,613
325  201610  인천광역시   동구  일반용   3,741    8,039,188
405  201611  인천광역시   동구  일반용   3,746    8,678,777
485  201612  인천광역시   동구  일반용   3,748   10,267,510
93   201607  인천광역시  부평구  일반용  22,193   67,185,437
173  201608  인천광역시  부평구  일반용  22,225   78,971,973
253  201609  인천광역시  부평구  일반용  22,219   69,749,929
333  201610  인천광역시  부평구  일반용  22,202   55,745,363
413  201611  인천광역시  부평구  일반용  22,270   55,652,141
493  201612  인천광역시  부평구  일반용  22,326   64,856,719
101  201607  인천광역시   서구  일반용  20,756   71,546,078
181  201608  인천광역시   서구  일반용  20,827   83,772,629
261  201609  인천광역시   서구  일반용  20,858   75,034,704
341  201610  인천광역시   서구  일반용  20,910   62,179,718
421  201611  인천광역시   서구  일반용  20,962   65,496,560
501  201612  인천광역시   서구  일반용  21,036   77,090,167
109  201607  인천광역시  연수구  일반용   8,286   55,523,381
189  201608  인천광역시  연수구  일반용   8,288   64,124,610
269  201609  인천광역시  연수구  일반용   8,314   54,969,428
349  201610  인천광역시  연수구  일반용   8,343   45,507,720
429  201611  인천광역시  연수구  일반용   8,352   45,774,306
509  201612  인천광역시  연수구  일반용   8,397   52,897,027
117  201607  인천광역시  옹진군  일반용   3,791    6,704,149
197  201608  인천광역시  옹진군  일반용   3,826    8,559,648
277  201609  인천광역시  옹진군  일반용   3,844    7,927,746
357  201610  인천광역시  옹진군  일반용   3,868    6,624,443
437  201611  인천광역시  옹진군  일반용   3,883    7,297,647
517  201612  인천광역시  옹진군  일반용   3,881    8,503,948
125  201607  인천광역시   중구  일반용  10,168   85,230,436
205  201608  인천광역시   중구  일반용  10,180   95,835,473
285  201609  인천광역시   중구  일반용  10,202   83,930,009
365  201610  인천광역시   중구  일반용  10,190   72,463,293
445  201611  인천광역시   중구  일반용  10,286   71,561,491
525  201612  인천광역시   중구  일반용  10,357   78,657,528

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[11813985, 14836851, 13738899, 10944103, 12140184, 14898223]
[39565645, 46595604, 40187616, 32336550, 32542048, 37870083]
[49972412, 60373727, 54327414, 42956146, 43495693, 50577014]
[76742289, 90919690, 78878545, 63243759, 63708772, 73883273]
[9540775, 11219434, 9634613, 8039188, 8678777, 10267510]
[67185437, 78971973, 69749929, 55745363, 55652141, 64856719]
[71546078, 83772629, 75034704, 62179718, 65496560, 77090167]
[55523381, 64124610, 54969428, 45507720, 45774306, 52897027]
[6704149, 8559648, 7927746, 6624443, 7297647, 8503948]
[85230436, 95835473, 83930009, 72463293, 71561491, 78657528]
인천광역시 지역별 일반용 합계 :  [78372245, 229097546, 301702406, 447376328, 57380297, 392161562, 435119856, 318796472, 45617581, 487678230]
인천광역시 고객호수 평균:  [7380, 12585, 20845, 22118, 3743, 22239, 20891, 8330, 3848, 10230]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6304\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201607  인천광역시  강화군  일반용  7,312   11,813,985
1          201608  인천광역시  강화군  일반용  7,324   14,836,851
2          201609  인천광역시  강화군  일반용  7,373   13,738,899
3          201610  인천광역시  강화군  일반용  7,410   10,944,103
4          201611  인천광역시  강화군  일반용  7,418   12,140,184
..            ...    ...  ...  ...     ...          ...
65  201607-201612  인천광역시  부평구  일반용   22239    392161562
66  201607-201612  인천광역시   서구  일반용   20891    435119856
67  201607-201612  인천광역시  연수구  일반용    8330    318796472
68  201607-201612  인천광역시  옹진군  일반용    3848     45617581
69  201607-201612  인천광역시   중구  일반용   10230    487678230

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201607-201612']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201607-201612  인천광역시  강화군  일반용    7380   78372245
61  201607-201612  인천광역시  계양구  일반용   12585  229097546
62  201607-201612  인천광역시   남구  일반용   20845  301702406
63  201607-201612  인천광역시  남동구  일반용   22118  447376328
64  201607-201612  인천광역시   동구  일반용    3743   57380297
65  201607-201612  인천광역시  부평구  일반용   22239  392161562
66  201607-201612  인천광역시   서구  일반용   20891  435119856
67  201607-201612  인천광역시  연수구  일반용    8330  318796472
68  201607-201612  인천광역시  옹진군  일반용    3848   45617581
69  201607-201612  인천광역시   중구  일반용   10230  487678230

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201607-201612  인천광역시  강화군  일반용    7380    78372245
60  201607-201612  인천광역시  강화군   합계   11630   251627853
61  201607-201612  인천광역시  계양구  일반용   12585   229097546
61  201607-201612  인천광역시  계양구   합계   16438   658154656
62  201607-201612  인천광역시   남구  일반용   20845   301702406
62  201607-201612  인천광역시   남구   합계   31369  1109495864
63  201607-201612  인천광역시  남동구  일반용   22118   447376328
63  201607-201612  인천광역시  남동구   합계   24745  2044863535
64  201607-201612  인천광역시   동구  일반용    3743    57380297
64  201607-201612  인천광역시   동구   합계    4005  1957096947
65  201607-201612  인천광역시  부평구  일반용   22239   392161562
65  201607-201612  인천광역시  부평구   합계   27630  1239356337
66  201607-201612  인천광역시   서구  일반용   20891   435119856
66  201607-201612  인천광역시   서구   합계   24681  2552933283
67  201607-201612  인천광역시  연수구   합계    9391  1057579737
67  201607-201612  인천광역시  연수구  일반용    8330   318796472
68  201607-201612  인천광역시  옹진군   합계    3724   105120715
68  201607-201612  인천광역시  옹진군  일반용    3848    45617581
69  201607-201612  인천광역시   중구  일반용   10230   487678230
69  201607-201612  인천광역시   중구   합계    8204  1034114053

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[78372245,
 229097546,
 301702406,
 447376328,
 57380297,
 392161562,
 435119856,
 318796472,
 45617581,
 487678230]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[251627853,
 658154656,
 1109495864,
 2044863535,
 1957096947,
 1239356337,
 2552933283,
 1057579737,
 105120715,
 1034114053]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[31.15, 34.81, 27.19, 21.88, 2.93, 31.64, 17.04, 30.14, 43.4, 47.16]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   31
1   35
2   27
3   22
4    3
5   32
6   17
7   30
8   43
9   47
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  31
1  계양구  일반용  35
2   남구  일반용  27
3  남동구  일반용  22
4   동구  일반용   3
5  부평구  일반용  32
6   서구  일반용  17
7  연수구  일반용  30
8  옹진군  일반용  43
9   중구  일반용  47

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201607-201612  인천광역시  강화군  일반용    7380    78372245  31
1   201607-201612  인천광역시  강화군   합계   11630   251627853 NaN
2   201607-201612  인천광역시  계양구  일반용   12585   229097546  35
3   201607-201612  인천광역시  계양구   합계   16438   658154656 NaN
4   201607-201612  인천광역시   남구  일반용   20845   301702406  27
5   201607-201612  인천광역시   남구   합계   31369  1109495864 NaN
6   201607-201612  인천광역시  남동구  일반용   22118   447376328  22
7   201607-201612  인천광역시  남동구   합계   24745  2044863535 NaN
8   201607-201612  인천광역시   동구  일반용    3743    57380297   3
9   201607-201612  인천광역시   동구   합계    4005  1957096947 NaN
10  201607-201612  인천광역시  부평구  일반용   22239   392161562  32
11  201607-201612  인천광역시  부평구   합계   27630  1239356337 NaN
12  201607-201612  인천광역시   서구  일반용   20891   435119856  17
13  201607-201612  인천광역시   서구   합계   24681  2552933283 NaN
15  201607-201612  인천광역시  연수구  일반용    8330   318796472  30
14  201607-201612  인천광역시  연수구   합계    9391  1057579737 NaN
17  201607-201612  인천광역시  옹진군  일반용    3848    45617581  43
16  201607-201612  인천광역시  옹진군   합계    3724   105120715 NaN
18  201607-201612  인천광역시   중구  일반용   10230   487678230  47
19  201607-201612  인천광역시   중구   합계    8204  1034114053 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1607-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)