In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별 전력사용량 월별_14하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 07 월 ~ 2014년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,인천광역시,전체(시 / 군 / 구),주택용,"690,343","304,511,561","38,318,974,236",125.8
4,201407,인천광역시,전체(시 / 군 / 구),일반용,"126,525","444,423,023","64,340,556,989",144.8
...,...,...,...,...,...,...,...,...
523,201412,인천광역시,중구,산업용,518,"58,170,324","7,005,147,344",120.4
524,201412,인천광역시,중구,심 야,"1,488","3,780,202","291,918,797",77.2
525,201412,인천광역시,중구,일반용,"9,636","67,966,139","8,995,038,506",132.3
526,201412,인천광역시,중구,주택용,"28,296","13,148,322","1,615,521,437",122.9
527,201412,인천광역시,중구,합계,"43,962","148,397,711","18,468,237,882",124.5

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,인천광역시,전체(시 / 군 / 구),주택용,"690,343","304,511,561","38,318,974,236",125.8
4,201407,인천광역시,전체(시 / 군 / 구),일반용,"126,525","444,423,023","64,340,556,989",144.8
5,201407,인천광역시,전체(시 / 군 / 구),교육용,975,"26,593,686","3,780,306,091",142.2
6,201407,인천광역시,전체(시 / 군 / 구),산업용,"17,962","1,127,927,405","139,736,908,490",123.9
...,...,...,...,...,...,...,...,...
523,201412,인천광역시,중구,산업용,518,"58,170,324","7,005,147,344",120.4
524,201412,인천광역시,중구,심 야,"1,488","3,780,202","291,918,797",77.2
525,201412,인천광역시,중구,일반용,"9,636","67,966,139","8,995,038,506",132.3
526,201412,인천광역시,중구,주택용,"28,296","13,148,322","1,615,521,437",122.9
527,201412,인천광역시,중구,합계,"43,962","148,397,711","18,468,237,882",124.5

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,인천광역시,전체(시 / 군 / 구),주택용,"690,343","304,511,561","38,318,974,236",125.8
4,201407,인천광역시,전체(시 / 군 / 구),일반용,"126,525","444,423,023","64,340,556,989",144.8
5,201407,인천광역시,전체(시 / 군 / 구),교육용,975,"26,593,686","3,780,306,091",142.2
6,201407,인천광역시,전체(시 / 군 / 구),산업용,"17,962","1,127,927,405","139,736,908,490",123.9
7,201407,인천광역시,전체(시 / 군 / 구),농사용,"19,870","8,159,362","411,148,362",50.4
...,...,...,...,...,...,...,...,...
523,201412,인천광역시,중구,산업용,518,"58,170,324","7,005,147,344",120.4
524,201412,인천광역시,중구,심 야,"1,488","3,780,202","291,918,797",77.2
525,201412,인천광역시,중구,일반용,"9,636","67,966,139","8,995,038,506",132.3
526,201412,인천광역시,중구,주택용,"28,296","13,148,322","1,615,521,437",122.9
527,201412,인천광역시,중구,합계,"43,962","148,397,711","18,468,237,882",124.5

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,인천광역시,전체(시 / 군 / 구),주택용,"690,343","304,511,561","38,318,974,236",125.8
4,201407,인천광역시,전체(시 / 군 / 구),일반용,"126,525","444,423,023","64,340,556,989",144.8
5,201407,인천광역시,전체(시 / 군 / 구),교육용,975,"26,593,686","3,780,306,091",142.2
6,201407,인천광역시,전체(시 / 군 / 구),산업용,"17,962","1,127,927,405","139,736,908,490",123.9
7,201407,인천광역시,전체(시 / 군 / 구),농사용,"19,870","8,159,362","411,148,362",50.4
8,201407,인천광역시,전체(시 / 군 / 구),가로등,"47,053","10,900,740","1,371,700,264",125.8
9,201407,인천광역시,전체(시 / 군 / 구),심 야,"18,673","11,088,185","680,189,084",61.3
10,201408,인천광역시,전체(시 / 군 / 구),주택용,"691,367","339,326,865","47,298,238,595",139.4
11,201408,인천광역시,전체(시 / 군 / 구),일반용,"126,671","472,893,859","66,623,264,842",140.9
12,201408,인천광역시,전체(시 / 군 / 구),교육용,977,"22,387,760","3,206,900,293",143.2
13,201408,인천광역시,전체(시 / 군 / 구),산업용,"17,978","1,042,761,584","128,679,284,151",123.4
14,201408,인천광역시,전체(시 / 군 / 구),농사용,"20,041","11,298,086","544,444,905",48.2
15,201408,인천광역시,전체(시 / 군 / 구),가로등,"47,201","11,839,919","1,432,811,252",121.0
16,201408,인천광역시,전체(시 / 군 / 구),심 야,"18,623","10,603,543","656,113,157",61.9
17,201409,인천광역시,전체(시 / 군 / 구),주택용,"692,774","311,148,049","38,991,489,319",125.3
18,201409,인천광역시,전체(시 / 군 / 구),일반용,"126,843","429,941,080","53,024,588,965",123.3
19,201409,인천광역시,전체(시 / 군 / 구),교육용,978,"23,195,936","2,634,696,760",113.6
20,201409,인천광역시,전체(시 / 군 / 구),산업용,"18,007","1,013,593,730","108,252,998,001",106.8
21,201409,인천광역시,전체(시 / 군 / 구),농사용,"20,178","12,218,773","590,499,465",48.3
22,201409,인천광역시,전체(시 / 군 / 구),가로등,"47,343","12,587,937","1,481,865,853",117.7
23,201409,인천광역시,전체(시 / 군 / 구),심 야,"18,571","9,962,350","609,971,641",61.2
24,201410,인천광역시,전체(시 / 군 / 구),주택용,"693,841","283,396,944","32,475,258,968",114.6
25,201410,인천광역시,전체(시 / 군 / 구),일반용,"126,912","375,769,024","42,934,444,224",114.3
26,201410,인천광역시,전체(시 / 군 / 구),교육용,980,"20,368,205","2,406,220,292",118.1
27,201410,인천광역시,전체(시 / 군 / 구),산업용,"18,026","1,108,923,577","110,829,643,389",99.9
28,201410,인천광역시,전체(시 / 군 / 구),농사용,"20,275","9,703,451","488,532,489",50.3
29,201410,인천광역시,전체(시 / 군 / 구),가로등,"49,238","14,138,076","1,579,068,369",111.7
30,201410,인천광역시,전체(시 / 군 / 구),심 야,"18,499","11,347,701","664,469,695",58.6
31,201411,인천광역시,전체(시 / 군 / 구),주택용,"694,825","300,887,291","36,625,743,746",121.7
32,201411,인천광역시,전체(시 / 군 / 구),일반용,"127,090","381,653,899","49,499,109,180",129.7
33,201411,인천광역시,전체(시 / 군 / 구),교육용,981,"23,717,534","3,098,018,323",130.6
34,201411,인천광역시,전체(시 / 군 / 구),산업용,"18,051","1,060,650,041","124,948,473,432",117.8
35,201411,인천광역시,전체(시 / 군 / 구),농사용,"27,202","15,935,297","630,512,502",39.6
36,201411,인천광역시,전체(시 / 군 / 구),가로등,"53,347","15,505,061","1,692,490,553",109.2
37,201411,인천광역시,전체(시 / 군 / 구),심 야,"18,465","24,280,143","1,591,737,452",65.6
38,201412,인천광역시,전체(시 / 군 / 구),주택용,"695,312","318,234,283","40,536,895,670",127.4
39,201412,인천광역시,전체(시 / 군 / 구),일반용,"127,505","446,928,722","60,941,361,389",136.4
40,201412,인천광역시,전체(시 / 군 / 구),교육용,985,"44,577,106","4,823,930,646",108.2
41,201412,인천광역시,전체(시 / 군 / 구),산업용,"18,076","1,162,002,827","138,568,752,448",119.2
42,201412,인천광역시,전체(시 / 군 / 구),농사용,"24,449","12,509,487","539,769,805",43.1
43,201412,인천광역시,전체(시 / 군 / 구),가로등,"51,426","16,076,809","1,729,007,216",107.5
44,201412,인천광역시,전체(시 / 군 / 구),심 야,"18,445","40,961,545","3,130,508,847",76.4
45,합계,합계,합계,합계,"5,572,883","11,344,930,456","1,362,400,899,350",120.1

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_22204\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201407  인천광역시  일반용  126,525   444,423,023
11  201408  인천광역시  일반용  126,671   472,893,859
18  201409  인천광역시  일반용  126,843   429,941,080
25  201410  인천광역시  일반용  126,912   375,769,024
32  201411  인천광역시  일반용  127,090   381,653,899
39  201412  인천광역시  일반용  127,505   446,928,722

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201407  인천광역시  강화군  일반용   6,915   10,765,346
133  201408  인천광역시  강화군  일반용   6,962   12,831,293
213  201409  인천광역시  강화군  일반용   6,964   11,504,095
293  201410  인천광역시  강화군  일반용   6,968    9,978,836
373  201411  인천광역시  강화군  일반용   6,970   11,340,899
453  201412  인천광역시  강화군  일반용   7,011   13,719,068
61   201407  인천광역시  계양구  일반용  12,253   38,362,848
141  201408  인천광역시  계양구  일반용  12,246   40,209,437
221  201409  인천광역시  계양구  일반용  12,275   36,255,050
301  201410  인천광역시  계양구  일반용  12,271   31,055,050
381  201411  인천광역시  계양구  일반용  12,302   31,037,346
461  201412  인천광역시  계양구  일반용  12,342   38,238,135
69   201407  인천광역시   남구  일반용  20,343   49,580,494
149  201408  인천광역시   남구  일반용  20,335   54,084,815
229  201409  인천광역시   남구  일반용  20,304   49,273,241
309  201410  인천광역시   남구  일반용  20,283   42,345,152
389  201411  인천광역시   남구  일반용  20,311   41,669,889
469  201412  인천광역시   남구  일반용  20,366   50,953,407
77   201407  인천광역시  남동구  일반용  20,858   71,993,867
157  201408  인천광역시  남동구  일반용  20,937   76,653,300
237  201409  인천광역시  남동구  일반용  20,962   69,706,749
317  201410  인천광역시  남동구  일반용  20,957   59,958,434
397  201411  인천광역시  남동구  일반용  21,016   59,113,243
477  201412  인천광역시  남동구  일반용  21,155   72,504,739
85   201407  인천광역시   동구  일반용   3,733    9,785,875
165  201408  인천광역시   동구  일반용   3,736   10,158,962
245  201409  인천광역시   동구  일반용   3,733    9,335,225
325  201410  인천광역시   동구  일반용   3,724    8,351,238
405  201411  인천광역시   동구  일반용   3,723    8,661,023
485  201412  인천광역시   동구  일반용   3,736   11,023,339
93   201407  인천광역시  부평구  일반용  21,924   66,259,314
173  201408  인천광역시  부평구  일반용  21,925   71,010,746
253  201409  인천광역시  부평구  일반용  21,932   63,813,435
333  201410  인천광역시  부평구  일반용  21,944   54,374,069
413  201411  인천광역시  부평구  일반용  21,967   53,577,148
493  201412  인천광역시  부평구  일반용  21,987   65,921,250
101  201407  인천광역시   서구  일반용  19,414   63,698,145
181  201408  인천광역시   서구  일반용  19,394   67,155,431
261  201409  인천광역시   서구  일반용  19,447   62,176,594
341  201410  인천광역시   서구  일반용  19,490   55,653,393
421  201411  인천광역시   서구  일반용  19,528   56,457,064
501  201412  인천광역시   서구  일반용  19,587   68,857,466
109  201407  인천광역시  연수구  일반용   7,953   49,320,186
189  201408  인천광역시  연수구  일반용   7,968   51,363,841
269  201409  인천광역시  연수구  일반용   7,998   46,490,310
349  201410  인천광역시  연수구  일반용   8,005   40,448,630
429  201411  인천광역시  연수구  일반용   8,015   39,714,110
509  201412  인천광역시  연수구  일반용   8,041   49,557,984
117  201407  인천광역시  옹진군  일반용   3,610    6,355,408
197  201408  인천광역시  옹진군  일반용   3,621    7,609,354
277  201409  인천광역시  옹진군  일반용   3,664    7,016,198
357  201410  인천광역시  옹진군  일반용   3,654    6,159,498
437  201411  인천광역시  옹진군  일반용   3,642    6,755,099
517  201412  인천광역시  옹진군  일반용   3,644    8,187,195
125  201407  인천광역시   중구  일반용   9,522   78,301,540
205  201408  인천광역시   중구  일반용   9,547   81,816,680
285  201409  인천광역시   중구  일반용   9,564   74,370,183
365  201410  인천광역시   중구  일반용   9,616   67,444,724
445  201411  인천광역시   중구  일반용   9,616   73,328,078
525  201412  인천광역시   중구  일반용   9,636   67,966,139

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201407  인천광역시  강화군   합계   63,575    30,297,210
135  201408  인천광역시  강화군   합계   63,821    35,446,185
215  201409  인천광역시  강화군   합계   63,976    34,348,770
295  201410  인천광역시  강화군   합계   64,084    32,354,089
375  201411  인천광역시  강화군   합계   69,403    43,634,652
455  201412  인천광역시  강화군   합계   68,167    52,420,452
63   201407  인천광역시  계양구   합계   96,881   108,238,040
143  201408  인천광역시  계양구   합계   96,921   113,372,973
223  201409  인천광역시  계양구   합계   96,994   105,036,074
303  201410  인천광역시  계양구   합계   97,073    96,592,452
383  201411  인천광역시  계양구   합계   97,449   100,763,558
463  201412  인천광역시  계양구   합계   97,204   116,130,614
71   201407  인천광역시   남구   합계  179,830   179,964,163
151  201408  인천광역시   남구   합계  179,953   185,438,926
231  201409  인천광역시   남구   합계  180,275   174,090,582
311  201410  인천광역시   남구   합계  180,356   166,003,609
391  201411  인천광역시   남구   합계  180,641   167,244,159
471  201412  인천광역시   남구   합계  180,646   192,287,723
79   201407  인천광역시  남동구   합계  139,477   339,332,953
159  201408  인천광역시  남동구   합계  139,659   331,737,483
239  201409  인천광역시  남동구   합계  139,900   316,828,986
319  201410  인천광역시  남동구   합계  141,905   308,287,944
399  201411  인천광역시  남동구   합계  146,047   313,331,174
479  201412  인천광역시  남동구   합계  144,246   360,034,603
87   201407  인천광역시   동구   합계   23,990   337,323,665
167  201408  인천광역시   동구   합계   23,981   293,324,346
247  201409  인천광역시   동구   합계   23,983   274,803,698
327  201410  인천광역시   동구   합계   23,980   340,771,466
407  201411  인천광역시   동구   합계   23,988   302,345,456
487  201412  인천광역시   동구   합계   23,997   325,142,593
95   201407  인천광역시  부평구   합계  161,058   209,532,293
175  201408  인천광역시  부평구   합계  161,363   211,073,798
255  201409  인천광역시  부평구   합계  161,566   195,489,574
335  201410  인천광역시  부평구   합계  161,638   183,996,722
415  201411  인천광역시  부평구   합계  161,780   187,891,499
495  201412  인천광역시  부평구   합계  161,863   217,562,425
103  201407  인천광역시   서구   합계  138,309   407,420,395
183  201408  인천광역시   서구   합계  138,544   415,227,575
263  201409  인천광역시   서구   합계  138,996   397,541,053
343  201410  인천광역시   서구   합계  139,423   399,317,638
423  201411  인천광역시   서구   합계  139,862   405,758,489
503  201412  인천광역시   서구   합계  140,049   446,432,965
111  201407  인천광역시  연수구   합계   54,731   154,329,625
191  201408  인천광역시  연수구   합계   54,777   156,144,222
271  201409  인천광역시  연수구   합계   54,858   147,523,817
351  201410  인천광역시  연수구   합계   54,974   136,721,769
431  201411  인천광역시  연수구   합계   54,999   138,271,467
511  201412  인천광역시  연수구   합계   55,059   166,037,090
119  201407  인천광역시  옹진군   합계   20,333    18,305,575
199  201408  인천광역시  옹진군   합계   20,412    14,210,613
279  201409  인천광역시  옹진군   합계   20,537    21,051,382
359  201410  인천광역시  옹진군   합계   20,562    19,864,659
439  201411  인천광역시  옹진군   합계   21,534    17,205,608
519  201412  인천광역시  옹진군   합계   21,005    16,844,603
127  201407  인천광역시   중구   합계   43,217   148,860,043
207  201408  인천광역시   중구   합계   43,427   155,135,495
287  201409  인천광역시   중구   합계   43,609   145,933,919
367  201410  인천광역시   중구   합계   43,776   139,736,630
447  201411  인천광역시   중구   합계   44,258   146,183,204
527  201412  인천광역시   중구   합계   43,962   148,397,711

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[30297210, 35446185, 34348770, 32354089, 43634652, 52420452]
[108238040, 113372973, 105036074, 96592452, 100763558, 116130614]
[179964163, 185438926, 174090582, 166003609, 167244159, 192287723]
[339332953, 331737483, 316828986, 308287944, 313331174, 360034603]
[337323665, 293324346, 274803698, 340771466, 302345456, 325142593]
[209532293, 211073798, 195489574, 183996722, 187891499, 217562425]
[407420395, 415227575, 397541053, 399317638, 405758489, 446432965]
[154329625, 156144222, 147523817, 136721769, 138271467, 166037090]
[18305575, 14210613, 21051382, 19864659, 17205608, 16844603]
[148860043, 155135495, 145933919, 139736630, 146183204, 148397711]
인천광역시 지역별 합계 :  [228501358, 640133711, 1065029162, 1969553143, 1873711224, 1205546311, 2471698115, 899027990, 107482440, 884247002]
인천광역시 고객호수 평균:  [10917, 16181, 30047, 23645, 3997, 26924, 23199, 9149, 3455, 7284]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201407  인천광역시  강화군   합계  63,575   30,297,210
1          201408  인천광역시  강화군   합계  63,821   35,446,185
2          201409  인천광역시  강화군   합계  63,976   34,348,770
3          201410  인천광역시  강화군   합계  64,084   32,354,089
4          201411  인천광역시  강화군   합계  69,403   43,634,652
..            ...    ...  ...  ...      ...          ...
65  201407-201412  인천광역시  부평구   합계    26924   1205546311
66  201407-201412  인천광역시   서구   합계    23199   2471698115
67  201407-201412  인천광역시  연수구   합계     9149    899027990
68  201407-201412  인천광역시  옹진군   합계     3455    107482440
69  201407-201412  인천광역시   중구   합계     7284    884247002

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201407-201412']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201407-201412  인천광역시  강화군   합계   10917   228501358
61  201407-201412  인천광역시  계양구   합계   16181   640133711
62  201407-201412  인천광역시   남구   합계   30047  1065029162
63  201407-201412  인천광역시  남동구   합계   23645  1969553143
64  201407-201412  인천광역시   동구   합계    3997  1873711224
65  201407-201412  인천광역시  부평구   합계   26924  1205546311
66  201407-201412  인천광역시   서구   합계   23199  2471698115
67  201407-201412  인천광역시  연수구   합계    9149   899027990
68  201407-201412  인천광역시  옹진군   합계    3455   107482440
69  201407-201412  인천광역시   중구   합계    7284   884247002

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201407  인천광역시  강화군  일반용   6,915   10,765,346
133  201408  인천광역시  강화군  일반용   6,962   12,831,293
213  201409  인천광역시  강화군  일반용   6,964   11,504,095
293  201410  인천광역시  강화군  일반용   6,968    9,978,836
373  201411  인천광역시  강화군  일반용   6,970   11,340,899
453  201412  인천광역시  강화군  일반용   7,011   13,719,068
61   201407  인천광역시  계양구  일반용  12,253   38,362,848
141  201408  인천광역시  계양구  일반용  12,246   40,209,437
221  201409  인천광역시  계양구  일반용  12,275   36,255,050
301  201410  인천광역시  계양구  일반용  12,271   31,055,050
381  201411  인천광역시  계양구  일반용  12,302   31,037,346
461  201412  인천광역시  계양구  일반용  12,342   38,238,135
69   201407  인천광역시   남구  일반용  20,343   49,580,494
149  201408  인천광역시   남구  일반용  20,335   54,084,815
229  201409  인천광역시   남구  일반용  20,304   49,273,241
309  201410  인천광역시   남구  일반용  20,283   42,345,152
389  201411  인천광역시   남구  일반용  20,311   41,669,889
469  201412  인천광역시   남구  일반용  20,366   50,953,407
77   201407  인천광역시  남동구  일반용  20,858   71,993,867
157  201408  인천광역시  남동구  일반용  20,937   76,653,300
237  201409  인천광역시  남동구  일반용  20,962   69,706,749
317  201410  인천광역시  남동구  일반용  20,957   59,958,434
397  201411  인천광역시  남동구  일반용  21,016   59,113,243
477  201412  인천광역시  남동구  일반용  21,155   72,504,739
85   201407  인천광역시   동구  일반용   3,733    9,785,875
165  201408  인천광역시   동구  일반용   3,736   10,158,962
245  201409  인천광역시   동구  일반용   3,733    9,335,225
325  201410  인천광역시   동구  일반용   3,724    8,351,238
405  201411  인천광역시   동구  일반용   3,723    8,661,023
485  201412  인천광역시   동구  일반용   3,736   11,023,339
93   201407  인천광역시  부평구  일반용  21,924   66,259,314
173  201408  인천광역시  부평구  일반용  21,925   71,010,746
253  201409  인천광역시  부평구  일반용  21,932   63,813,435
333  201410  인천광역시  부평구  일반용  21,944   54,374,069
413  201411  인천광역시  부평구  일반용  21,967   53,577,148
493  201412  인천광역시  부평구  일반용  21,987   65,921,250
101  201407  인천광역시   서구  일반용  19,414   63,698,145
181  201408  인천광역시   서구  일반용  19,394   67,155,431
261  201409  인천광역시   서구  일반용  19,447   62,176,594
341  201410  인천광역시   서구  일반용  19,490   55,653,393
421  201411  인천광역시   서구  일반용  19,528   56,457,064
501  201412  인천광역시   서구  일반용  19,587   68,857,466
109  201407  인천광역시  연수구  일반용   7,953   49,320,186
189  201408  인천광역시  연수구  일반용   7,968   51,363,841
269  201409  인천광역시  연수구  일반용   7,998   46,490,310
349  201410  인천광역시  연수구  일반용   8,005   40,448,630
429  201411  인천광역시  연수구  일반용   8,015   39,714,110
509  201412  인천광역시  연수구  일반용   8,041   49,557,984
117  201407  인천광역시  옹진군  일반용   3,610    6,355,408
197  201408  인천광역시  옹진군  일반용   3,621    7,609,354
277  201409  인천광역시  옹진군  일반용   3,664    7,016,198
357  201410  인천광역시  옹진군  일반용   3,654    6,159,498
437  201411  인천광역시  옹진군  일반용   3,642    6,755,099
517  201412  인천광역시  옹진군  일반용   3,644    8,187,195
125  201407  인천광역시   중구  일반용   9,522   78,301,540
205  201408  인천광역시   중구  일반용   9,547   81,816,680
285  201409  인천광역시   중구  일반용   9,564   74,370,183
365  201410  인천광역시   중구  일반용   9,616   67,444,724
445  201411  인천광역시   중구  일반용   9,616   73,328,078
525  201412  인천광역시   중구  일반용   9,636   67,966,139

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[10765346, 12831293, 11504095, 9978836, 11340899, 13719068]
[38362848, 40209437, 36255050, 31055050, 31037346, 38238135]
[49580494, 54084815, 49273241, 42345152, 41669889, 50953407]
[71993867, 76653300, 69706749, 59958434, 59113243, 72504739]
[9785875, 10158962, 9335225, 8351238, 8661023, 11023339]
[66259314, 71010746, 63813435, 54374069, 53577148, 65921250]
[63698145, 67155431, 62176594, 55653393, 56457064, 68857466]
[49320186, 51363841, 46490310, 40448630, 39714110, 49557984]
[6355408, 7609354, 7016198, 6159498, 6755099, 8187195]
[78301540, 81816680, 74370183, 67444724, 73328078, 67966139]
인천광역시 지역별 일반용 합계 :  [70139537, 215157866, 287906998, 409930332, 57315662, 374955962, 373998093, 276895061, 42082752, 443227344]
인천광역시 고객호수 평균:  [6965, 12281, 20323, 20980, 3730, 21946, 19476, 7996, 3639, 9583]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_22204\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201407  인천광역시  강화군  일반용  6,915   10,765,346
1          201408  인천광역시  강화군  일반용  6,962   12,831,293
2          201409  인천광역시  강화군  일반용  6,964   11,504,095
3          201410  인천광역시  강화군  일반용  6,968    9,978,836
4          201411  인천광역시  강화군  일반용  6,970   11,340,899
..            ...    ...  ...  ...     ...          ...
65  201407-201412  인천광역시  부평구  일반용   21946    374955962
66  201407-201412  인천광역시   서구  일반용   19476    373998093
67  201407-201412  인천광역시  연수구  일반용    7996    276895061
68  201407-201412  인천광역시  옹진군  일반용    3639     42082752
69  201407-201412  인천광역시   중구  일반용    9583    443227344

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201407-201412']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201407-201412  인천광역시  강화군  일반용    6965   70139537
61  201407-201412  인천광역시  계양구  일반용   12281  215157866
62  201407-201412  인천광역시   남구  일반용   20323  287906998
63  201407-201412  인천광역시  남동구  일반용   20980  409930332
64  201407-201412  인천광역시   동구  일반용    3730   57315662
65  201407-201412  인천광역시  부평구  일반용   21946  374955962
66  201407-201412  인천광역시   서구  일반용   19476  373998093
67  201407-201412  인천광역시  연수구  일반용    7996  276895061
68  201407-201412  인천광역시  옹진군  일반용    3639   42082752
69  201407-201412  인천광역시   중구  일반용    9583  443227344

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201407-201412  인천광역시  강화군  일반용    6965    70139537
60  201407-201412  인천광역시  강화군   합계   10917   228501358
61  201407-201412  인천광역시  계양구  일반용   12281   215157866
61  201407-201412  인천광역시  계양구   합계   16181   640133711
62  201407-201412  인천광역시   남구  일반용   20323   287906998
62  201407-201412  인천광역시   남구   합계   30047  1065029162
63  201407-201412  인천광역시  남동구  일반용   20980   409930332
63  201407-201412  인천광역시  남동구   합계   23645  1969553143
64  201407-201412  인천광역시   동구  일반용    3730    57315662
64  201407-201412  인천광역시   동구   합계    3997  1873711224
65  201407-201412  인천광역시  부평구  일반용   21946   374955962
65  201407-201412  인천광역시  부평구   합계   26924  1205546311
66  201407-201412  인천광역시   서구  일반용   19476   373998093
66  201407-201412  인천광역시   서구   합계   23199  2471698115
67  201407-201412  인천광역시  연수구   합계    9149   899027990
67  201407-201412  인천광역시  연수구  일반용    7996   276895061
68  201407-201412  인천광역시  옹진군   합계    3455   107482440
68  201407-201412  인천광역시  옹진군  일반용    3639    42082752
69  201407-201412  인천광역시   중구  일반용    9583   443227344
69  201407-201412  인천광역시   중구   합계    7284   884247002

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[70139537,
 215157866,
 287906998,
 409930332,
 57315662,
 374955962,
 373998093,
 276895061,
 42082752,
 443227344]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[228501358,
 640133711,
 1065029162,
 1969553143,
 1873711224,
 1205546311,
 2471698115,
 899027990,
 107482440,
 884247002]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[30.7, 33.61, 27.03, 20.81, 3.06, 31.1, 15.13, 30.8, 39.15, 50.12]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   31
1   34
2   27
3   21
4    3
5   31
6   15
7   31
8   39
9   50
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  31
1  계양구  일반용  34
2   남구  일반용  27
3  남동구  일반용  21
4   동구  일반용   3
5  부평구  일반용  31
6   서구  일반용  15
7  연수구  일반용  31
8  옹진군  일반용  39
9   중구  일반용  50

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201407-201412  인천광역시  강화군  일반용    6965    70139537  31
1   201407-201412  인천광역시  강화군   합계   10917   228501358 NaN
2   201407-201412  인천광역시  계양구  일반용   12281   215157866  34
3   201407-201412  인천광역시  계양구   합계   16181   640133711 NaN
4   201407-201412  인천광역시   남구  일반용   20323   287906998  27
5   201407-201412  인천광역시   남구   합계   30047  1065029162 NaN
6   201407-201412  인천광역시  남동구  일반용   20980   409930332  21
7   201407-201412  인천광역시  남동구   합계   23645  1969553143 NaN
8   201407-201412  인천광역시   동구  일반용    3730    57315662   3
9   201407-201412  인천광역시   동구   합계    3997  1873711224 NaN
10  201407-201412  인천광역시  부평구  일반용   21946   374955962  31
11  201407-201412  인천광역시  부평구   합계   26924  1205546311 NaN
12  201407-201412  인천광역시   서구  일반용   19476   373998093  15
13  201407-201412  인천광역시   서구   합계   23199  2471698115 NaN
15  201407-201412  인천광역시  연수구  일반용    7996   276895061  31
14  201407-201412  인천광역시  연수구   합계    9149   899027990 NaN
17  201407-201412  인천광역시  옹진군  일반용    3639    42082752  39
16  201407-201412  인천광역시  옹진군   합계    3455   107482440 NaN
18  201407-201412  인천광역시   중구  일반용    9583   443227344  50
19  201407-201412  인천광역시   중구   합계    7284   884247002 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1407-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)