In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별 전력사용량 월별_14상반기.csv' , encoding='utf-8')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 01 월 ~ 2014년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,인천광역시,전체(시 / 군 / 구),주택용,"684,627","333,244,100","44,810,319,281",134.5
4,201401,인천광역시,전체(시 / 군 / 구),일반용,"126,103","485,788,457","63,313,777,416",130.3
...,...,...,...,...,...,...,...,...
522,201406,인천광역시,중구,산업용,512,"51,152,761","6,041,883,687",118.1
523,201406,인천광역시,중구,심 야,"1,507","1,621,251","101,552,124",62.6
524,201406,인천광역시,중구,일반용,"9,472","69,057,038","8,006,647,922",115.9
525,201406,인천광역시,중구,주택용,"27,625","11,661,983","1,326,895,066",113.8
526,201406,인천광역시,중구,합계,"43,040","136,636,391","15,867,302,977",116.1

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,인천광역시,전체(시 / 군 / 구),주택용,"684,627","333,244,100","44,810,319,281",134.5
4,201401,인천광역시,전체(시 / 군 / 구),일반용,"126,103","485,788,457","63,313,777,416",130.3
5,201401,인천광역시,전체(시 / 군 / 구),교육용,980,"31,958,027","3,869,956,940",121.1
6,201401,인천광역시,전체(시 / 군 / 구),산업용,"17,785","1,141,665,523","134,014,178,245",117.4
...,...,...,...,...,...,...,...,...
522,201406,인천광역시,중구,산업용,512,"51,152,761","6,041,883,687",118.1
523,201406,인천광역시,중구,심 야,"1,507","1,621,251","101,552,124",62.6
524,201406,인천광역시,중구,일반용,"9,472","69,057,038","8,006,647,922",115.9
525,201406,인천광역시,중구,주택용,"27,625","11,661,983","1,326,895,066",113.8
526,201406,인천광역시,중구,합계,"43,040","136,636,391","15,867,302,977",116.1

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,인천광역시,전체(시 / 군 / 구),주택용,"684,627","333,244,100","44,810,319,281",134.5
4,201401,인천광역시,전체(시 / 군 / 구),일반용,"126,103","485,788,457","63,313,777,416",130.3
5,201401,인천광역시,전체(시 / 군 / 구),교육용,980,"31,958,027","3,869,956,940",121.1
6,201401,인천광역시,전체(시 / 군 / 구),산업용,"17,785","1,141,665,523","134,014,178,245",117.4
7,201401,인천광역시,전체(시 / 군 / 구),농사용,"19,264","8,193,638","413,063,088",50.4
...,...,...,...,...,...,...,...,...
522,201406,인천광역시,중구,산업용,512,"51,152,761","6,041,883,687",118.1
523,201406,인천광역시,중구,심 야,"1,507","1,621,251","101,552,124",62.6
524,201406,인천광역시,중구,일반용,"9,472","69,057,038","8,006,647,922",115.9
525,201406,인천광역시,중구,주택용,"27,625","11,661,983","1,326,895,066",113.8
526,201406,인천광역시,중구,합계,"43,040","136,636,391","15,867,302,977",116.1

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,인천광역시,전체(시 / 군 / 구),주택용,"684,627","333,244,100","44,810,319,281",134.5
4,201401,인천광역시,전체(시 / 군 / 구),일반용,"126,103","485,788,457","63,313,777,416",130.3
5,201401,인천광역시,전체(시 / 군 / 구),교육용,980,"31,958,027","3,869,956,940",121.1
6,201401,인천광역시,전체(시 / 군 / 구),산업용,"17,785","1,141,665,523","134,014,178,245",117.4
7,201401,인천광역시,전체(시 / 군 / 구),농사용,"19,264","8,193,638","413,063,088",50.4
8,201401,인천광역시,전체(시 / 군 / 구),가로등,"45,922","15,961,054","1,711,743,222",107.2
9,201401,인천광역시,전체(시 / 군 / 구),심 야,"19,073","57,027,699","4,352,943,641",76.3
10,201402,인천광역시,전체(시 / 군 / 구),주택용,"685,578","332,286,796","44,701,753,107",134.5
11,201402,인천광역시,전체(시 / 군 / 구),일반용,"126,170","455,281,279","60,324,542,729",132.5
12,201402,인천광역시,전체(시 / 군 / 구),교육용,973,"31,310,040","3,804,229,768",121.5
13,201402,인천광역시,전체(시 / 군 / 구),산업용,"17,827","1,028,801,411","124,670,677,984",121.2
14,201402,인천광역시,전체(시 / 군 / 구),농사용,"19,253","8,423,582","422,767,650",50.2
15,201402,인천광역시,전체(시 / 군 / 구),가로등,"46,148","15,392,124","1,712,449,130",111.3
16,201402,인천광역시,전체(시 / 군 / 구),심 야,"19,006","56,139,387","4,281,711,531",76.3
17,201403,인천광역시,전체(시 / 군 / 구),주택용,"686,602","288,337,823","34,058,900,806",118.1
18,201403,인천광역시,전체(시 / 군 / 구),일반용,"126,088","402,075,140","48,604,844,000",120.9
19,201403,인천광역시,전체(시 / 군 / 구),교육용,969,"30,234,002","3,084,031,871",102.0
20,201403,인천광역시,전체(시 / 군 / 구),산업용,"17,831","1,092,383,971","107,955,081,381",98.8
21,201403,인천광역시,전체(시 / 군 / 구),농사용,"26,049","7,616,014","391,057,759",51.3
22,201403,인천광역시,전체(시 / 군 / 구),가로등,"46,245","13,504,489","1,534,779,214",113.6
23,201403,인천광역시,전체(시 / 군 / 구),심 야,"18,973","42,684,780","2,876,775,456",67.4
24,201404,인천광역시,전체(시 / 군 / 구),주택용,"687,527","300,249,876","36,465,672,025",121.5
25,201404,인천광역시,전체(시 / 군 / 구),일반용,"126,201","377,249,866","42,952,901,684",113.9
26,201404,인천광역시,전체(시 / 군 / 구),교육용,971,"22,907,908","2,612,871,044",114.1
27,201404,인천광역시,전체(시 / 군 / 구),산업용,"17,870","1,062,987,048","103,858,585,368",97.7
28,201404,인천광역시,전체(시 / 군 / 구),농사용,"23,446","7,660,085","398,515,030",52.0
29,201404,인천광역시,전체(시 / 군 / 구),가로등,"46,579","13,211,213","1,547,191,968",117.1
30,201404,인천광역시,전체(시 / 군 / 구),심 야,"18,903","31,711,052","1,755,175,556",55.3
31,201405,인천광역시,전체(시 / 군 / 구),주택용,"688,323","285,042,351","33,085,909,816",116.1
32,201405,인천광역시,전체(시 / 군 / 구),일반용,"126,071","356,239,507","41,607,969,450",116.8
33,201405,인천광역시,전체(시 / 군 / 구),교육용,975,"20,001,980","2,440,993,962",122.0
34,201405,인천광역시,전체(시 / 군 / 구),산업용,"17,923","1,030,829,370","100,656,127,104",97.6
35,201405,인천광역시,전체(시 / 군 / 구),농사용,"19,588","7,971,169","390,751,495",49.0
36,201405,인천광역시,전체(시 / 군 / 구),가로등,"46,608","12,066,983","1,460,902,136",121.1
37,201405,인천광역시,전체(시 / 군 / 구),심 야,"18,826","21,748,969","1,218,677,531",56.0
38,201406,인천광역시,전체(시 / 군 / 구),주택용,"689,358","293,251,017","35,363,267,192",120.6
39,201406,인천광역시,전체(시 / 군 / 구),일반용,"126,331","389,872,512","50,996,028,022",130.8
40,201406,인천광역시,전체(시 / 군 / 구),교육용,975,"21,735,997","3,156,282,662",145.2
41,201406,인천광역시,전체(시 / 군 / 구),산업용,"17,935","1,066,550,470","125,402,830,048",117.6
42,201406,인천광역시,전체(시 / 군 / 구),농사용,"19,753","8,116,962","398,340,223",49.1
43,201406,인천광역시,전체(시 / 군 / 구),가로등,"46,940","11,113,620","1,396,554,374",125.7
44,201406,인천광역시,전체(시 / 군 / 구),심 야,"18,743","14,290,715","830,208,238",58.1
45,합계,합계,합계,합계,"5,511,312","11,233,118,006","1,278,905,339,147",113.9

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_4064\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201401  인천광역시  일반용  126,103   485,788,457
11  201402  인천광역시  일반용  126,170   455,281,279
18  201403  인천광역시  일반용  126,088   402,075,140
25  201404  인천광역시  일반용  126,201   377,249,866
32  201405  인천광역시  일반용  126,071   356,239,507
39  201406  인천광역시  일반용  126,331   389,872,512

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
52   201401  인천광역시  강화군  일반용   6,846   16,596,815
132  201402  인천광역시  강화군  일반용   6,842   15,963,355
212  201403  인천광역시  강화군  일반용   6,827   13,264,213
292  201404  인천광역시  강화군  일반용   6,832   11,871,170
372  201405  인천광역시  강화군  일반용   6,854   10,581,408
452  201406  인천광역시  강화군  일반용   6,872   10,032,574
60   201401  인천광역시  계양구  일반용  12,270   41,919,293
140  201402  인천광역시  계양구  일반용  12,277   39,200,919
220  201403  인천광역시  계양구  일반용  12,268   34,147,070
300  201404  인천광역시  계양구  일반용  12,285   31,767,574
380  201405  인천광역시  계양구  일반용  12,255   30,182,552
460  201406  인천광역시  계양구  일반용  12,240   33,914,781
68   201401  인천광역시   남구  일반용  20,443   56,397,434
148  201402  인천광역시   남구  일반용  20,439   53,579,796
228  201403  인천광역시   남구  일반용  20,404   46,459,669
308  201404  인천광역시   남구  일반용  20,369   44,085,774
388  201405  인천광역시   남구  일반용  20,342   40,113,531
468  201406  인천광역시   남구  일반용  20,339   43,885,023
76   201401  인천광역시  남동구  일반용  20,742   79,278,126
156  201402  인천광역시  남동구  일반용  20,758   74,079,757
236  201403  인천광역시  남동구  일반용  20,740   64,298,863
316  201404  인천광역시  남동구  일반용  20,740   60,252,183
396  201405  인천광역시  남동구  일반용  20,775   56,757,835
476  201406  인천광역시  남동구  일반용  20,818   63,226,365
84   201401  인천광역시   동구  일반용   3,706   11,346,892
164  201402  인천광역시   동구  일반용   3,693   10,664,483
244  201403  인천광역시   동구  일반용   3,713    9,423,067
324  201404  인천광역시   동구  일반용   3,714    8,566,857
404  201405  인천광역시   동구  일반용   3,712    7,786,616
484  201406  인천광역시   동구  일반용   3,722    8,446,069
92   201401  인천광역시  부평구  일반용  22,055   72,588,287
172  201402  인천광역시  부평구  일반용  22,071   68,292,294
252  201403  인천광역시  부평구  일반용  22,035   58,987,529
332  201404  인천광역시  부평구  일반용  22,022   54,658,022
412  201405  인천광역시  부평구  일반용  21,921   51,871,161
492  201406  인천광역시  부평구  일반용  21,952   57,603,932
100  201401  인천광역시   서구  일반용  19,223   71,434,910
180  201402  인천광역시   서구  일반용  19,241   67,538,482
260  201403  인천광역시   서구  일반용  19,245   59,149,410
340  201404  인천광역시   서구  일반용  19,309   55,559,180
420  201405  인천광역시   서구  일반용  19,263   51,269,140
500  201406  인천광역시   서구  일반용  19,352   56,110,079
108  201401  인천광역시  연수구  일반용   7,914   48,996,334
188  201402  인천광역시  연수구  일반용   7,944   45,310,826
268  201403  인천광역시  연수구  일반용   7,936   41,254,760
348  201404  인천광역시  연수구  일반용   7,971   38,442,705
428  201405  인천광역시  연수구  일반용   7,962   36,943,090
508  201406  인천광역시  연수구  일반용   7,958   41,294,918
116  201401  인천광역시  옹진군  일반용   3,539   10,623,027
196  201402  인천광역시  옹진군  일반용   3,536   10,172,423
276  201403  인천광역시  옹진군  일반용   3,537    8,670,932
356  201404  인천광역시  옹진군  일반용   3,537    8,119,608
436  201405  인천광역시  옹진군  일반용   3,563    6,944,559
516  201406  인천광역시  옹진군  일반용   3,606    6,301,733
124  201401  인천광역시   중구  일반용   9,365   76,607,339
204  201402  인천광역시   중구  일반용   9,369   70,478,944
284  201403  인천광역시   중구  일반용   9,383   66,419,627
364  201404  인천광역시   중구  일반용   9,422   63,926,793
444  201405  인천광역시   중구  일반용   9,424   63,789,615
524  201406  인천광역시   중구  일반용   9,472   69,057,038

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
54   201401  인천광역시  강화군   합계   62,571    57,970,493
134  201402  인천광역시  강화군   합계   62,597    57,451,441
214  201403  인천광역시  강화군   합계   67,733    46,711,079
294  201404  인천광역시  강화군   합계   66,530    41,112,175
374  201405  인천광역시  강화군   합계   63,090    35,735,584
454  201406  인천광역시  강화군   합계   63,396    31,275,966
62   201401  인천광역시  계양구   합계   96,615   122,116,919
142  201402  인천광역시  계양구   합계   96,655   115,928,643
222  201403  인천광역시  계양구   합계   96,973   104,622,426
302  201404  인천광역시  계양구   합계   96,795   100,727,214
382  201405  인천광역시  계양구   합계   96,784    94,688,962
462  201406  인천광역시  계양구   합계   96,838    99,747,582
70   201401  인천광역시   남구   합계  178,957   199,435,392
150  201402  인천광역시   남구   합계  179,113   188,616,564
230  201403  인천광역시   남구   합계  179,265   177,412,182
310  201404  인천광역시   남구   합계  179,458   171,113,178
390  201405  인천광역시   남구   합계  179,600   151,785,334
470  201406  인천광역시   남구   합계  179,701   166,909,290
78   201401  인천광역시  남동구   합계  138,193   370,599,386
158  201402  인천광역시  남동구   합계  138,485   353,914,854
238  201403  인천광역시  남동구   합계  138,719   333,440,829
318  201404  인천광역시  남동구   합계  138,908   326,289,548
398  201405  인천광역시  남동구   합계  139,118   297,259,993
478  201406  인천광역시  남동구   합계  139,350   312,468,429
86   201401  인천광역시   동구   합계   23,962   351,318,369
166  201402  인천광역시   동구   합계   23,963   296,167,710
246  201403  인천광역시   동구   합계   23,967   344,302,312
326  201404  인천광역시   동구   합계   23,942   333,006,603
406  201405  인천광역시   동구   합계   23,949   348,070,313
486  201406  인천광역시   동구   합계   23,959   338,021,296
94   201401  인천광역시  부평구   합계  160,115   228,578,256
174  201402  인천광역시  부평구   합계  160,330   217,607,110
254  201403  인천광역시  부평구   합계  160,443   199,636,302
334  201404  인천광역시  부평구   합계  160,595   192,704,728
414  201405  인천광역시  부평구   합계  160,583   182,999,969
494  201406  인천광역시  부평구   합계  160,885   192,246,663
102  201401  인천광역시   서구   합계  136,707   405,652,048
182  201402  인천광역시   서구   합계  136,913   383,931,850
262  201403  인천광역시   서구   합계  137,246   371,375,638
342  201404  인천광역시   서구   합계  137,510   368,386,071
422  201405  인천광역시   서구   합계  137,599   351,137,944
502  201406  인천광역시   서구   합계  137,931   366,624,168
110  201401  인천광역시  연수구   합계   54,435   163,345,721
190  201402  인천광역시  연수구   합계   54,530   151,922,425
270  201403  인천광역시  연수구   합계   54,570   142,745,951
350  201404  인천광역시  연수구   합계   54,659   132,270,699
430  201405  인천광역시  연수구   합계   54,644   115,493,697
510  201406  인천광역시  연수구   합계   54,681   137,185,678
118  201401  인천광역시  옹진군   합계   19,672    20,137,213
198  201402  인천광역시  옹진군   합계   19,830    19,208,099
278  201403  인천광역시  옹진군   합계   20,846    18,094,846
358  201404  인천광역시  옹진군   합계   20,422    16,876,301
438  201405  인천광역시  옹진군   합계   20,184    24,543,168
518  201406  인천광역시  옹진군   합계   20,254    23,815,830
126  201401  인천광역시   중구   합계   42,527   154,684,701
206  201402  인천광역시   중구   합계   42,539   142,885,923
286  201403  인천광역시   중구   합계   42,995   138,494,654
366  201404  인천광역시   중구   합계   42,678   133,490,531
446  201405  인천광역시   중구   합계   42,763   132,185,365
526  201406  인천광역시   중구   합계   43,040   136,636,391

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[57970493, 57451441, 46711079, 41112175, 35735584, 31275966]
[122116919, 115928643, 104622426, 100727214, 94688962, 99747582]
[199435392, 188616564, 177412182, 171113178, 151785334, 166909290]
[370599386, 353914854, 333440829, 326289548, 297259993, 312468429]
[351318369, 296167710, 344302312, 333006603, 348070313, 338021296]
[228578256, 217607110, 199636302, 192704728, 182999969, 192246663]
[405652048, 383931850, 371375638, 368386071, 351137944, 366624168]
[163345721, 151922425, 142745951, 132270699, 115493697, 137185678]
[20137213, 19208099, 18094846, 16876301, 24543168, 23815830]
[154684701, 142885923, 138494654, 133490531, 132185365, 136636391]
인천광역시 지역별 합계 :  [270256738, 637831746, 1055271940, 1993973039, 2010886603, 1213773028, 2247107719, 842964171, 122675457, 838377565]
인천광역시 고객호수 평균:  [10719, 16129, 29891, 23132, 3992, 26748, 22886, 9097, 3366, 7126]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201401  인천광역시  강화군   합계  62,571   57,970,493
1          201402  인천광역시  강화군   합계  62,597   57,451,441
2          201403  인천광역시  강화군   합계  67,733   46,711,079
3          201404  인천광역시  강화군   합계  66,530   41,112,175
4          201405  인천광역시  강화군   합계  63,090   35,735,584
..            ...    ...  ...  ...      ...          ...
65  201401-201406  인천광역시  부평구   합계    26748   1213773028
66  201401-201406  인천광역시   서구   합계    22886   2247107719
67  201401-201406  인천광역시  연수구   합계     9097    842964171
68  201401-201406  인천광역시  옹진군   합계     3366    122675457
69  201401-201406  인천광역시   중구   합계     7126    838377565

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201401-201406']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201401-201406  인천광역시  강화군   합계   10719   270256738
61  201401-201406  인천광역시  계양구   합계   16129   637831746
62  201401-201406  인천광역시   남구   합계   29891  1055271940
63  201401-201406  인천광역시  남동구   합계   23132  1993973039
64  201401-201406  인천광역시   동구   합계    3992  2010886603
65  201401-201406  인천광역시  부평구   합계   26748  1213773028
66  201401-201406  인천광역시   서구   합계   22886  2247107719
67  201401-201406  인천광역시  연수구   합계    9097   842964171
68  201401-201406  인천광역시  옹진군   합계    3366   122675457
69  201401-201406  인천광역시   중구   합계    7126   838377565

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
52   201401  인천광역시  강화군  일반용   6,846   16,596,815
132  201402  인천광역시  강화군  일반용   6,842   15,963,355
212  201403  인천광역시  강화군  일반용   6,827   13,264,213
292  201404  인천광역시  강화군  일반용   6,832   11,871,170
372  201405  인천광역시  강화군  일반용   6,854   10,581,408
452  201406  인천광역시  강화군  일반용   6,872   10,032,574
60   201401  인천광역시  계양구  일반용  12,270   41,919,293
140  201402  인천광역시  계양구  일반용  12,277   39,200,919
220  201403  인천광역시  계양구  일반용  12,268   34,147,070
300  201404  인천광역시  계양구  일반용  12,285   31,767,574
380  201405  인천광역시  계양구  일반용  12,255   30,182,552
460  201406  인천광역시  계양구  일반용  12,240   33,914,781
68   201401  인천광역시   남구  일반용  20,443   56,397,434
148  201402  인천광역시   남구  일반용  20,439   53,579,796
228  201403  인천광역시   남구  일반용  20,404   46,459,669
308  201404  인천광역시   남구  일반용  20,369   44,085,774
388  201405  인천광역시   남구  일반용  20,342   40,113,531
468  201406  인천광역시   남구  일반용  20,339   43,885,023
76   201401  인천광역시  남동구  일반용  20,742   79,278,126
156  201402  인천광역시  남동구  일반용  20,758   74,079,757
236  201403  인천광역시  남동구  일반용  20,740   64,298,863
316  201404  인천광역시  남동구  일반용  20,740   60,252,183
396  201405  인천광역시  남동구  일반용  20,775   56,757,835
476  201406  인천광역시  남동구  일반용  20,818   63,226,365
84   201401  인천광역시   동구  일반용   3,706   11,346,892
164  201402  인천광역시   동구  일반용   3,693   10,664,483
244  201403  인천광역시   동구  일반용   3,713    9,423,067
324  201404  인천광역시   동구  일반용   3,714    8,566,857
404  201405  인천광역시   동구  일반용   3,712    7,786,616
484  201406  인천광역시   동구  일반용   3,722    8,446,069
92   201401  인천광역시  부평구  일반용  22,055   72,588,287
172  201402  인천광역시  부평구  일반용  22,071   68,292,294
252  201403  인천광역시  부평구  일반용  22,035   58,987,529
332  201404  인천광역시  부평구  일반용  22,022   54,658,022
412  201405  인천광역시  부평구  일반용  21,921   51,871,161
492  201406  인천광역시  부평구  일반용  21,952   57,603,932
100  201401  인천광역시   서구  일반용  19,223   71,434,910
180  201402  인천광역시   서구  일반용  19,241   67,538,482
260  201403  인천광역시   서구  일반용  19,245   59,149,410
340  201404  인천광역시   서구  일반용  19,309   55,559,180
420  201405  인천광역시   서구  일반용  19,263   51,269,140
500  201406  인천광역시   서구  일반용  19,352   56,110,079
108  201401  인천광역시  연수구  일반용   7,914   48,996,334
188  201402  인천광역시  연수구  일반용   7,944   45,310,826
268  201403  인천광역시  연수구  일반용   7,936   41,254,760
348  201404  인천광역시  연수구  일반용   7,971   38,442,705
428  201405  인천광역시  연수구  일반용   7,962   36,943,090
508  201406  인천광역시  연수구  일반용   7,958   41,294,918
116  201401  인천광역시  옹진군  일반용   3,539   10,623,027
196  201402  인천광역시  옹진군  일반용   3,536   10,172,423
276  201403  인천광역시  옹진군  일반용   3,537    8,670,932
356  201404  인천광역시  옹진군  일반용   3,537    8,119,608
436  201405  인천광역시  옹진군  일반용   3,563    6,944,559
516  201406  인천광역시  옹진군  일반용   3,606    6,301,733
124  201401  인천광역시   중구  일반용   9,365   76,607,339
204  201402  인천광역시   중구  일반용   9,369   70,478,944
284  201403  인천광역시   중구  일반용   9,383   66,419,627
364  201404  인천광역시   중구  일반용   9,422   63,926,793
444  201405  인천광역시   중구  일반용   9,424   63,789,615
524  201406  인천광역시   중구  일반용   9,472   69,057,038

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[16596815, 15963355, 13264213, 11871170, 10581408, 10032574]
[41919293, 39200919, 34147070, 31767574, 30182552, 33914781]
[56397434, 53579796, 46459669, 44085774, 40113531, 43885023]
[79278126, 74079757, 64298863, 60252183, 56757835, 63226365]
[11346892, 10664483, 9423067, 8566857, 7786616, 8446069]
[72588287, 68292294, 58987529, 54658022, 51871161, 57603932]
[71434910, 67538482, 59149410, 55559180, 51269140, 56110079]
[48996334, 45310826, 41254760, 38442705, 36943090, 41294918]
[10623027, 10172423, 8670932, 8119608, 6944559, 6301733]
[76607339, 70478944, 66419627, 63926793, 63789615, 69057038]
인천광역시 지역별 일반용 합계 :  [78309535, 211132189, 284521227, 397893129, 56233984, 364001225, 361061201, 252242633, 50832282, 410279356]
인천광역시 고객호수 평균:  [6845, 12265, 20389, 20762, 3710, 22009, 19272, 7947, 3553, 9405]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4064\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201401  인천광역시  강화군  일반용  6,846   16,596,815
1          201402  인천광역시  강화군  일반용  6,842   15,963,355
2          201403  인천광역시  강화군  일반용  6,827   13,264,213
3          201404  인천광역시  강화군  일반용  6,832   11,871,170
4          201405  인천광역시  강화군  일반용  6,854   10,581,408
..            ...    ...  ...  ...     ...          ...
65  201401-201406  인천광역시  부평구  일반용   22009    364001225
66  201401-201406  인천광역시   서구  일반용   19272    361061201
67  201401-201406  인천광역시  연수구  일반용    7947    252242633
68  201401-201406  인천광역시  옹진군  일반용    3553     50832282
69  201401-201406  인천광역시   중구  일반용    9405    410279356

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201401-201406']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201401-201406  인천광역시  강화군  일반용    6845   78309535
61  201401-201406  인천광역시  계양구  일반용   12265  211132189
62  201401-201406  인천광역시   남구  일반용   20389  284521227
63  201401-201406  인천광역시  남동구  일반용   20762  397893129
64  201401-201406  인천광역시   동구  일반용    3710   56233984
65  201401-201406  인천광역시  부평구  일반용   22009  364001225
66  201401-201406  인천광역시   서구  일반용   19272  361061201
67  201401-201406  인천광역시  연수구  일반용    7947  252242633
68  201401-201406  인천광역시  옹진군  일반용    3553   50832282
69  201401-201406  인천광역시   중구  일반용    9405  410279356

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201401-201406  인천광역시  강화군  일반용    6845    78309535
60  201401-201406  인천광역시  강화군   합계   10719   270256738
61  201401-201406  인천광역시  계양구  일반용   12265   211132189
61  201401-201406  인천광역시  계양구   합계   16129   637831746
62  201401-201406  인천광역시   남구  일반용   20389   284521227
62  201401-201406  인천광역시   남구   합계   29891  1055271940
63  201401-201406  인천광역시  남동구  일반용   20762   397893129
63  201401-201406  인천광역시  남동구   합계   23132  1993973039
64  201401-201406  인천광역시   동구  일반용    3710    56233984
64  201401-201406  인천광역시   동구   합계    3992  2010886603
65  201401-201406  인천광역시  부평구  일반용   22009   364001225
65  201401-201406  인천광역시  부평구   합계   26748  1213773028
66  201401-201406  인천광역시   서구  일반용   19272   361061201
66  201401-201406  인천광역시   서구   합계   22886  2247107719
67  201401-201406  인천광역시  연수구   합계    9097   842964171
67  201401-201406  인천광역시  연수구  일반용    7947   252242633
68  201401-201406  인천광역시  옹진군   합계    3366   122675457
68  201401-201406  인천광역시  옹진군  일반용    3553    50832282
69  201401-201406  인천광역시   중구  일반용    9405   410279356
69  201401-201406  인천광역시   중구   합계    7126   838377565

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[78309535,
 211132189,
 284521227,
 397893129,
 56233984,
 364001225,
 361061201,
 252242633,
 50832282,
 410279356]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[270256738,
 637831746,
 1055271940,
 1993973039,
 2010886603,
 1213773028,
 2247107719,
 842964171,
 122675457,
 838377565]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[28.98, 33.1, 26.96, 19.95, 2.8, 29.99, 16.07, 29.92, 41.44, 48.94]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   29
1   33
2   27
3   20
4    3
5   30
6   16
7   30
8   41
9   49
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  29
1  계양구  일반용  33
2   남구  일반용  27
3  남동구  일반용  20
4   동구  일반용   3
5  부평구  일반용  30
6   서구  일반용  16
7  연수구  일반용  30
8  옹진군  일반용  41
9   중구  일반용  49

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201401-201406  인천광역시  강화군  일반용    6845    78309535  29
1   201401-201406  인천광역시  강화군   합계   10719   270256738 NaN
2   201401-201406  인천광역시  계양구  일반용   12265   211132189  33
3   201401-201406  인천광역시  계양구   합계   16129   637831746 NaN
4   201401-201406  인천광역시   남구  일반용   20389   284521227  27
5   201401-201406  인천광역시   남구   합계   29891  1055271940 NaN
6   201401-201406  인천광역시  남동구  일반용   20762   397893129  20
7   201401-201406  인천광역시  남동구   합계   23132  1993973039 NaN
8   201401-201406  인천광역시   동구  일반용    3710    56233984   3
9   201401-201406  인천광역시   동구   합계    3992  2010886603 NaN
10  201401-201406  인천광역시  부평구  일반용   22009   364001225  30
11  201401-201406  인천광역시  부평구   합계   26748  1213773028 NaN
12  201401-201406  인천광역시   서구  일반용   19272   361061201  16
13  201401-201406  인천광역시   서구   합계   22886  2247107719 NaN
15  201401-201406  인천광역시  연수구  일반용    7947   252242633  30
14  201401-201406  인천광역시  연수구   합계    9097   842964171 NaN
17  201401-201406  인천광역시  옹진군  일반용    3553    50832282  41
16  201401-201406  인천광역시  옹진군   합계    3366   122675457 NaN
18  201401-201406  인천광역시   중구  일반용    9405   410279356  49
19  201401-201406  인천광역시   중구   합계    7126   838377565 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1401-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)