In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('울산광역시_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 울산광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,울산광역시,전체(시 / 군 / 구),주택용,"309,776","114,348,950","12,891,646,776",112.7
4,201507,울산광역시,전체(시 / 군 / 구),일반용,"68,808","157,187,934","24,207,785,688",154.0
...,...,...,...,...,...,...,...,...
283,201512,울산광역시,중구,산업용,521,"2,160,720","303,370,460",140.4
284,201512,울산광역시,중구,심 야,740,"1,427,572","108,512,434",76
285,201512,울산광역시,중구,일반용,"13,495","25,441,479","3,666,919,899",144.1
286,201512,울산광역시,중구,주택용,"70,249","25,996,842","3,320,235,406",127.7
287,201512,울산광역시,중구,합계,"90,765","58,130,254","7,743,795,037",133.2

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,울산광역시,전체(시 / 군 / 구),주택용,"309,776","114,348,950","12,891,646,776",112.7
4,201507,울산광역시,전체(시 / 군 / 구),일반용,"68,808","157,187,934","24,207,785,688",154.0
5,201507,울산광역시,전체(시 / 군 / 구),교육용,421,"12,597,403","1,635,891,538",129.9
6,201507,울산광역시,전체(시 / 군 / 구),산업용,"6,135","2,312,654,012","269,482,993,863",116.5
...,...,...,...,...,...,...,...,...
283,201512,울산광역시,중구,산업용,521,"2,160,720","303,370,460",140.4
284,201512,울산광역시,중구,심 야,740,"1,427,572","108,512,434",76
285,201512,울산광역시,중구,일반용,"13,495","25,441,479","3,666,919,899",144.1
286,201512,울산광역시,중구,주택용,"70,249","25,996,842","3,320,235,406",127.7
287,201512,울산광역시,중구,합계,"90,765","58,130,254","7,743,795,037",133.2

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,울산광역시,전체(시 / 군 / 구),주택용,"309,776","114,348,950","12,891,646,776",112.7
4,201507,울산광역시,전체(시 / 군 / 구),일반용,"68,808","157,187,934","24,207,785,688",154.0
5,201507,울산광역시,전체(시 / 군 / 구),교육용,421,"12,597,403","1,635,891,538",129.9
6,201507,울산광역시,전체(시 / 군 / 구),산업용,"6,135","2,312,654,012","269,482,993,863",116.5
7,201507,울산광역시,전체(시 / 군 / 구),농사용,"11,625","5,251,300","274,478,930",52.3
...,...,...,...,...,...,...,...,...
283,201512,울산광역시,중구,산업용,521,"2,160,720","303,370,460",140.4
284,201512,울산광역시,중구,심 야,740,"1,427,572","108,512,434",76
285,201512,울산광역시,중구,일반용,"13,495","25,441,479","3,666,919,899",144.1
286,201512,울산광역시,중구,주택용,"70,249","25,996,842","3,320,235,406",127.7
287,201512,울산광역시,중구,합계,"90,765","58,130,254","7,743,795,037",133.2

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,울산광역시,전체(시 / 군 / 구),주택용,"309,776","114,348,950","12,891,646,776",112.7
4,201507,울산광역시,전체(시 / 군 / 구),일반용,"68,808","157,187,934","24,207,785,688",154.0
5,201507,울산광역시,전체(시 / 군 / 구),교육용,421,"12,597,403","1,635,891,538",129.9
6,201507,울산광역시,전체(시 / 군 / 구),산업용,"6,135","2,312,654,012","269,482,993,863",116.5
7,201507,울산광역시,전체(시 / 군 / 구),농사용,"11,625","5,251,300","274,478,930",52.3
8,201507,울산광역시,전체(시 / 군 / 구),가로등,"30,750","4,218,197","524,297,906",124.3
9,201507,울산광역시,전체(시 / 군 / 구),심 야,"8,149","5,649,562","324,863,927",57.5
10,201508,울산광역시,전체(시 / 군 / 구),주택용,"310,348","149,474,736","20,932,705,520",140.0
11,201508,울산광역시,전체(시 / 군 / 구),일반용,"69,065","191,536,649","27,895,850,420",145.6
12,201508,울산광역시,전체(시 / 군 / 구),교육용,423,"13,265,407","1,678,938,142",126.6
13,201508,울산광역시,전체(시 / 군 / 구),산업용,"6,158","2,238,453,893","232,560,227,815",103.9
14,201508,울산광역시,전체(시 / 군 / 구),농사용,"11,727","7,040,009","349,989,314",49.7
15,201508,울산광역시,전체(시 / 군 / 구),가로등,"30,817","4,506,240","537,245,895",119.2
16,201508,울산광역시,전체(시 / 군 / 구),심 야,"8,115","5,113,362","298,536,662",58.4
17,201509,울산광역시,전체(시 / 군 / 구),주택용,"311,131","126,349,186","15,690,572,255",124.2
18,201509,울산광역시,전체(시 / 군 / 구),일반용,"69,243","170,886,131","22,718,092,195",132.9
19,201509,울산광역시,전체(시 / 군 / 구),교육용,424,"13,060,396","1,388,423,295",106.3
20,201509,울산광역시,전체(시 / 군 / 구),산업용,"6,183","2,205,223,710","190,908,036,090",86.6
21,201509,울산광역시,전체(시 / 군 / 구),농사용,"11,843","7,071,476","350,133,398",49.5
22,201509,울산광역시,전체(시 / 군 / 구),가로등,"30,898","4,779,843","550,041,979",115.1
23,201509,울산광역시,전체(시 / 군 / 구),심 야,"8,088","4,583,293","265,183,072",57.9
24,201510,울산광역시,전체(시 / 군 / 구),주택용,"311,642","112,945,468","12,594,571,065",111.5
25,201510,울산광역시,전체(시 / 군 / 구),일반용,"69,280","142,344,083","17,146,073,220",120.5
26,201510,울산광역시,전체(시 / 군 / 구),교육용,424,"10,653,987","1,111,319,437",104.3
27,201510,울산광역시,전체(시 / 군 / 구),산업용,"6,192","2,185,129,955","188,849,854,999",86.4
28,201510,울산광역시,전체(시 / 군 / 구),농사용,"11,872","5,426,333","284,563,966",52.4
29,201510,울산광역시,전체(시 / 군 / 구),가로등,"30,919","5,243,035","570,805,917",108.9
30,201510,울산광역시,전체(시 / 군 / 구),심 야,"8,026","6,289,988","346,941,347",55.2
31,201511,울산광역시,전체(시 / 군 / 구),주택용,"312,400","120,937,721","14,546,055,481",120.3
32,201511,울산광역시,전체(시 / 군 / 구),일반용,"69,556","145,852,966","19,422,862,990",133.2
33,201511,울산광역시,전체(시 / 군 / 구),교육용,426,"11,700,006","1,361,816,165",116.4
34,201511,울산광역시,전체(시 / 군 / 구),산업용,"6,217","2,139,682,578","233,835,628,335",109.3
35,201511,울산광역시,전체(시 / 군 / 구),농사용,"12,818","6,544,348","323,218,895",49.4
36,201511,울산광역시,전체(시 / 군 / 구),가로등,"30,955","5,793,034","613,184,808",105.8
37,201511,울산광역시,전체(시 / 군 / 구),심 야,"8,016","10,729,119","679,186,912",63.3
38,201512,울산광역시,전체(시 / 군 / 구),주택용,"312,993","125,231,333","15,574,403,197",124.4
39,201512,울산광역시,전체(시 / 군 / 구),일반용,"69,859","159,364,815","22,893,179,024",143.7
40,201512,울산광역시,전체(시 / 군 / 구),교육용,426,"14,703,584","1,661,501,777",113.0
41,201512,울산광역시,전체(시 / 군 / 구),산업용,"6,239","2,305,991,401","252,329,660,012",109.4
42,201512,울산광역시,전체(시 / 군 / 구),농사용,"11,843","6,212,260","324,913,198",52.3
43,201512,울산광역시,전체(시 / 군 / 구),가로등,"31,202","6,529,234","685,632,082",105.0
44,201512,울산광역시,전체(시 / 군 / 구),심 야,"7,995","15,945,623","1,206,354,856",75.7
45,합계,합계,합계,합계,"2,629,427","15,296,502,560","1,611,827,662,363",105.4

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_1940\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분  고객호수(호)      사용량(kWh)
4   201507  울산광역시  일반용  68,808   157,187,934
11  201508  울산광역시  일반용  69,065   191,536,649
18  201509  울산광역시  일반용  69,243   170,886,131
25  201510  울산광역시  일반용  69,280   142,344,083
32  201511  울산광역시  일반용  69,556   145,852,966
39  201512  울산광역시  일반용  69,859   159,364,815

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  울산광역시   남구  일반용  25,008   62,742,179
93   201508  울산광역시   남구  일반용  25,065   77,024,933
133  201509  울산광역시   남구  일반용  25,067   67,522,350
173  201510  울산광역시   남구  일반용  25,060   54,952,255
213  201511  울산광역시   남구  일반용  25,074   55,365,583
253  201512  울산광역시   남구  일반용  25,156   60,868,246
61   201507  울산광역시   동구  일반용   8,132   19,478,618
101  201508  울산광역시   동구  일반용   8,168   22,928,833
141  201509  울산광역시   동구  일반용   8,184   21,510,957
181  201510  울산광역시   동구  일반용   8,170   17,984,761
221  201511  울산광역시   동구  일반용   8,237   17,912,493
261  201512  울산광역시   동구  일반용   8,260   18,925,295
69   201507  울산광역시   북구  일반용   8,132   20,938,887
109  201508  울산광역시   북구  일반용   8,178   25,395,395
149  201509  울산광역시   북구  일반용   8,201   23,113,081
189  201510  울산광역시   북구  일반용   8,216   19,644,812
229  201511  울산광역시   북구  일반용   8,280   20,405,163
269  201512  울산광역시   북구  일반용   8,324   22,370,772
77   201507  울산광역시  울주군  일반용  14,346   28,448,771
117  201508  울산광역시  울주군  일반용  14,438   34,736,357
157  201509  울산광역시  울주군  일반용  14,487   31,313,406
197  201510  울산광역시  울주군  일반용  14,501   26,875,032
237  201511  울산광역시  울주군  일반용  14,560   28,956,637
277  201512  울산광역시  울주군  일반용  14,624   31,759,023
85   201507  울산광역시   중구  일반용  13,190   25,579,479
125  201508  울산광역시   중구  일반용  13,216   31,451,131
165  201509  울산광역시   중구  일반용  13,304   27,426,337
205  201510  울산광역시   중구  일반용  13,333   22,887,223
245  201511  울산광역시   중구  일반용  13,405   23,213,090
285  201512  울산광역시   중구  일반용  13,495   25,441,479

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'울산광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['남구', '동구', '북구', '울주군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55   201507  울산광역시   남구   합계  133,488   1,312,713,984
95   201508  울산광역시   남구   합계  133,565   1,345,347,214
135  201509  울산광역시   남구   합계  133,666   1,282,868,939
175  201510  울산광역시   남구   합계  133,619   1,189,636,381
215  201511  울산광역시   남구   합계  133,738   1,180,097,389
255  201512  울산광역시   남구   합계  133,986   1,276,467,748
63   201507  울산광역시   동구   합계   58,469     163,164,838
103  201508  울산광역시   동구   합계   58,655     150,652,043
143  201509  울산광역시   동구   합계   58,838     149,315,194
183  201510  울산광역시   동구   합계   58,917     143,352,561
223  201511  울산광역시   동구   합계   59,093     144,676,431
263  201512  울산광역시   동구   합계   59,174     152,027,177
71   201507  울산광역시   북구   합계   47,805     208,033,401
111  201508  울산광역시   북구   합계   47,919     198,927,085
151  201509  울산광역시   북구   합계   48,100     187,738,411
191  201510  울산광역시   북구   합계   48,206     199,939,906
231  201511  울산광역시   북구   합계   48,662     196,332,850
271  201512  울산광역시   북구   합계   48,590     215,310,299
79   201507  울산광역시  울주군   합계  106,311     874,286,164
119  201508  울산광역시  울주군   합계  106,682     846,887,098
159  201509  울산광역시  울주군   합계  107,102     853,352,451
199  201510  울산광역시  울주군   합계  107,348     884,425,503
239  201511  울산광역시  울주군   합계  108,396     866,722,082
279  201512  울산광역시  울주군   합계  108,042     932,042,772
87   201507  울산광역시   중구   합계   89,591      53,708,971
127  201508  울산광역시   중구   합계   89,832      67,576,856
167  201509  울산광역시   중구   합계   90,104      58,679,040
207  201510  울산광역시   중구   합계   90,265      50,678,498
247  201511  울산광역시   중구   합계   90,499      53,411,020
287  201512  울산광역시   중구   합계   90,765      58,130,254

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[1312713984, 1345347214, 1282868939, 1189636381, 1180097389, 1276467748]
[163164838, 150652043, 149315194, 143352561, 144676431, 152027177]
[208033401, 198927085, 187738411, 199939906, 196332850, 215310299]
[874286164, 846887098, 853352451, 884425503, 866722082, 932042772]
[53708971, 67576856, 58679040, 50678498, 53411020, 58130254]
울산광역시 지역별 합계 :  [7587131655, 903188244, 1206281952, 5257716070, 342184639]
울산광역시 고객호수 평균:  [22279, 9809, 8035, 17885, 15029]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_1940\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1940\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1940\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1940\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1940\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분   고객호수(호)        사용량(kWh)
0          201507  울산광역시   남구   합계  133,488   1,312,713,984
1          201508  울산광역시   남구   합계  133,565   1,345,347,214
2          201509  울산광역시   남구   합계  133,666   1,282,868,939
3          201510  울산광역시   남구   합계  133,619   1,189,636,381
4          201511  울산광역시   남구   합계  133,738   1,180,097,389
5          201512  울산광역시   남구   합계  133,986   1,276,467,748
6          201507  울산광역시   동구   합계   58,469     163,164,838
7          201508  울산광역시   동구   합계   58,655     150,652,043
8          201509  울산광역시   동구   합계   58,838     149,315,194
9          201510  울산광역시   동구   합계   58,917     143,352,561
10         201511  울산광역시   동구   합계   59,093     144,676,431
11         201512  울산광역시   동구   합계   59,174     152,027,177
12         201507  울산광역시   북구   합계   47,805     208,033,401
13         201508  울산광역시   북구   합계   47,919     198,927,085
14         201509  울산광역시   북구   합계   48,100     187,738,411
15         201510  울산광역시   북구   합계   48,206     199,939,906
16         201511  울산광역시   북구   합계   48,662     196,332,850
17         201512  울산광역시   북구   합계   48,590     215,310,299
18         201507  울산광역시  울주군   합계  106,311     874,286,164
19         201508  울산광역시  울주군   합계  106,682     846,887,098
20         201509  울산광역시  울주군   합계  107,102     853,352,451
21         201510  울산광역시  울주군   합계  107,348     884,425,503
22         201511  울산광역시  울주군   합계  108,396     866,722,082
23         201512  울산광역시  울주군   합계  108,042     932,042,772
24         201507  울산광역시   중구   합계   89,591      53,708,971
25         201508  울산광역시   중구   합계   89,832      67,576,856
26         201509  울산광역시   중구   합계   90,104      58,679,040
27         201510  울산광역시   중구   합계   90,265      50,678,498
28         201511  울산광역시   중구   합계   90,499      53,411,020
29         201512  울산광역시   중구   합계   90,765      58,130,254
30  201507-201512  울산광역시   남구   합계     22279      7587131655
31  201507-201512  울산광역시   동구   합계      9809       903188244
32  201507-201512  울산광역시   북구   합계      8035      1206281952
33  201507-201512  울산광역시  울주군   합계     17885      5257716070
34  201507-201512  울산광역시   중구   합계     15029       342184639

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
30  201507-201512  울산광역시   남구   합계   22279  7587131655
31  201507-201512  울산광역시   동구   합계    9809   903188244
32  201507-201512  울산광역시   북구   합계    8035  1206281952
33  201507-201512  울산광역시  울주군   합계   17885  5257716070
34  201507-201512  울산광역시   중구   합계   15029   342184639

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  울산광역시   남구  일반용  25,008   62,742,179
93   201508  울산광역시   남구  일반용  25,065   77,024,933
133  201509  울산광역시   남구  일반용  25,067   67,522,350
173  201510  울산광역시   남구  일반용  25,060   54,952,255
213  201511  울산광역시   남구  일반용  25,074   55,365,583
253  201512  울산광역시   남구  일반용  25,156   60,868,246
61   201507  울산광역시   동구  일반용   8,132   19,478,618
101  201508  울산광역시   동구  일반용   8,168   22,928,833
141  201509  울산광역시   동구  일반용   8,184   21,510,957
181  201510  울산광역시   동구  일반용   8,170   17,984,761
221  201511  울산광역시   동구  일반용   8,237   17,912,493
261  201512  울산광역시   동구  일반용   8,260   18,925,295
69   201507  울산광역시   북구  일반용   8,132   20,938,887
109  201508  울산광역시   북구  일반용   8,178   25,395,395
149  201509  울산광역시   북구  일반용   8,201   23,113,081
189  201510  울산광역시   북구  일반용   8,216   19,644,812
229  201511  울산광역시   북구  일반용   8,280   20,405,163
269  201512  울산광역시   북구  일반용   8,324   22,370,772
77   201507  울산광역시  울주군  일반용  14,346   28,448,771
117  201508  울산광역시  울주군  일반용  14,438   34,736,357
157  201509  울산광역시  울주군  일반용  14,487   31,313,406
197  201510  울산광역시  울주군  일반용  14,501   26,875,032
237  201511  울산광역시  울주군  일반용  14,560   28,956,637
277  201512  울산광역시  울주군  일반용  14,624   31,759,023
85   201507  울산광역시   중구  일반용  13,190   25,579,479
125  201508  울산광역시   중구  일반용  13,216   31,451,131
165  201509  울산광역시   중구  일반용  13,304   27,426,337
205  201510  울산광역시   중구  일반용  13,333   22,887,223
245  201511  울산광역시   중구  일반용  13,405   23,213,090
285  201512  울산광역시   중구  일반용  13,495   25,441,479

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[62742179, 77024933, 67522350, 54952255, 55365583, 60868246]
[19478618, 22928833, 21510957, 17984761, 17912493, 18925295]
[20938887, 25395395, 23113081, 19644812, 20405163, 22370772]
[28448771, 34736357, 31313406, 26875032, 28956637, 31759023]
[25579479, 31451131, 27426337, 22887223, 23213090, 25441479]
울산광역시 지역별 일반용 합계 :  [378475546, 118740957, 131868110, 182089226, 155998739]
울산광역시 고객호수 평균:  [25071, 8191, 8221, 14492, 13323]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_1940\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1940\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1940\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1940\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1940\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201507  울산광역시   남구  일반용  25,008   62,742,179
1          201508  울산광역시   남구  일반용  25,065   77,024,933
2          201509  울산광역시   남구  일반용  25,067   67,522,350
3          201510  울산광역시   남구  일반용  25,060   54,952,255
4          201511  울산광역시   남구  일반용  25,074   55,365,583
5          201512  울산광역시   남구  일반용  25,156   60,868,246
6          201507  울산광역시   동구  일반용   8,132   19,478,618
7          201508  울산광역시   동구  일반용   8,168   22,928,833
8          201509  울산광역시   동구  일반용   8,184   21,510,957
9          201510  울산광역시   동구  일반용   8,170   17,984,761
10         201511  울산광역시   동구  일반용   8,237   17,912,493
11         201512  울산광역시   동구  일반용   8,260   18,925,295
12         201507  울산광역시   북구  일반용   8,132   20,938,887
13         201508  울산광역시   북구  일반용   8,178   25,395,395
14         201509  울산광역시   북구  일반용   8,201   23,113,081
15         201510  울산광역시   북구  일반용   8,216   19,644,812
16         201511  울산광역시   북구  일반용   8,280   20,405,163
17         201512  울산광역시   북구  일반용   8,324   22,370,772
18         201507  울산광역시  울주군  일반용  14,346   28,448,771
19         201508  울산광역시  울주군  일반용  14,438   34,736,357
20         201509  울산광역시  울주군  일반용  14,487   31,313,406
21         201510  울산광역시  울주군  일반용  14,501   26,875,032
22         201511  울산광역시  울주군  일반용  14,560   28,956,637
23         201512  울산광역시  울주군  일반용  14,624   31,759,023
24         201507  울산광역시   중구  일반용  13,190   25,579,479
25         201508  울산광역시   중구  일반용  13,216   31,451,131
26         201509  울산광역시   중구  일반용  13,304   27,426,337
27         201510  울산광역시   중구  일반용  13,333   22,887,223
28         201511  울산광역시   중구  일반용  13,405   23,213,090
29         201512  울산광역시   중구  일반용  13,495   25,441,479
30  201507-201512  울산광역시   남구  일반용    25071    378475546
31  201507-201512  울산광역시   동구  일반용     8191    118740957
32  201507-201512  울산광역시   북구  일반용     8221    131868110
33  201507-201512  울산광역시  울주군  일반용    14492    182089226
34  201507-201512  울산광역시   중구  일반용    13323    155998739

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
30  201507-201512  울산광역시   남구  일반용   25071  378475546
31  201507-201512  울산광역시   동구  일반용    8191  118740957
32  201507-201512  울산광역시   북구  일반용    8221  131868110
33  201507-201512  울산광역시  울주군  일반용   14492  182089226
34  201507-201512  울산광역시   중구  일반용   13323  155998739

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
30  201507-201512  울산광역시   남구  일반용   25071   378475546
30  201507-201512  울산광역시   남구   합계   22279  7587131655
31  201507-201512  울산광역시   동구  일반용    8191   118740957
31  201507-201512  울산광역시   동구   합계    9809   903188244
32  201507-201512  울산광역시   북구  일반용    8221   131868110
32  201507-201512  울산광역시   북구   합계    8035  1206281952
33  201507-201512  울산광역시  울주군  일반용   14492   182089226
33  201507-201512  울산광역시  울주군   합계   17885  5257716070
34  201507-201512  울산광역시   중구  일반용   13323   155998739
34  201507-201512  울산광역시   중구   합계   15029   342184639

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[378475546, 118740957, 131868110, 182089226, 155998739]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[7587131655, 903188244, 1206281952, 5257716070, 342184639]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[4.99, 13.15, 10.93, 3.46, 45.59]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    5
1   13
2   11
3    3
4   46
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0   남구  일반용   5
1   동구  일반용  13
2   북구  일반용  11
3  울주군  일반용   3
4   중구  일반용  46

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201507-201512  울산광역시   남구  일반용   25071   378475546   5
1  201507-201512  울산광역시   남구   합계   22279  7587131655 NaN
2  201507-201512  울산광역시   동구  일반용    8191   118740957  13
3  201507-201512  울산광역시   동구   합계    9809   903188244 NaN
4  201507-201512  울산광역시   북구  일반용    8221   131868110  11
5  201507-201512  울산광역시   북구   합계    8035  1206281952 NaN
6  201507-201512  울산광역시  울주군  일반용   14492   182089226   3
7  201507-201512  울산광역시  울주군   합계   17885  5257716070 NaN
8  201507-201512  울산광역시   중구  일반용   13323   155998739  46
9  201507-201512  울산광역시   중구   합계   15029   342184639 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)