In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('강원도_계약종별_전력사용량_월별_12하반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 강원도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2012년 07 월 ~ 2012년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,강원도,전체(시 / 군 / 구),주택용,"509,066","149,827,131","15,694,515,060",104.8
4,201207,강원도,전체(시 / 군 / 구),일반용,"120,807","291,064,554","34,534,057,270",118.6
...,...,...,...,...,...,...,...,...
907,201212,강원도,횡성군,산업용,513,"12,721,483","1,480,951,824",116.4
908,201212,강원도,횡성군,심 야,"6,613","20,599,599","1,391,628,834",67.6
909,201212,강원도,횡성군,일반용,"4,249","12,840,546","1,523,258,655",118.6
910,201212,강원도,횡성군,주택용,"19,256","3,675,574","-91,878,179",-25
911,201212,강원도,횡성군,합계,"43,348","56,156,308","4,690,939,247",83.5

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,강원도,전체(시 / 군 / 구),주택용,"509,066","149,827,131","15,694,515,060",104.8
4,201207,강원도,전체(시 / 군 / 구),일반용,"120,807","291,064,554","34,534,057,270",118.6
5,201207,강원도,전체(시 / 군 / 구),교육용,"1,532","19,147,255","2,278,461,199",119.0
6,201207,강원도,전체(시 / 군 / 구),산업용,"11,454","602,175,744","59,179,825,035",98.3
...,...,...,...,...,...,...,...,...
907,201212,강원도,횡성군,산업용,513,"12,721,483","1,480,951,824",116.4
908,201212,강원도,횡성군,심 야,"6,613","20,599,599","1,391,628,834",67.6
909,201212,강원도,횡성군,일반용,"4,249","12,840,546","1,523,258,655",118.6
910,201212,강원도,횡성군,주택용,"19,256","3,675,574","-91,878,179",-25
911,201212,강원도,횡성군,합계,"43,348","56,156,308","4,690,939,247",83.5

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,강원도,전체(시 / 군 / 구),주택용,"509,066","149,827,131","15,694,515,060",104.8
4,201207,강원도,전체(시 / 군 / 구),일반용,"120,807","291,064,554","34,534,057,270",118.6
5,201207,강원도,전체(시 / 군 / 구),교육용,"1,532","19,147,255","2,278,461,199",119.0
6,201207,강원도,전체(시 / 군 / 구),산업용,"11,454","602,175,744","59,179,825,035",98.3
7,201207,강원도,전체(시 / 군 / 구),농사용,"68,541","31,012,645","1,422,250,672",45.9
...,...,...,...,...,...,...,...,...
907,201212,강원도,횡성군,산업용,513,"12,721,483","1,480,951,824",116.4
908,201212,강원도,횡성군,심 야,"6,613","20,599,599","1,391,628,834",67.6
909,201212,강원도,횡성군,일반용,"4,249","12,840,546","1,523,258,655",118.6
910,201212,강원도,횡성군,주택용,"19,256","3,675,574","-91,878,179",-25
911,201212,강원도,횡성군,합계,"43,348","56,156,308","4,690,939,247",83.5

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,강원도,전체(시 / 군 / 구),주택용,"509,066","149,827,131","15,694,515,060",104.8
4,201207,강원도,전체(시 / 군 / 구),일반용,"120,807","291,064,554","34,534,057,270",118.6
5,201207,강원도,전체(시 / 군 / 구),교육용,"1,532","19,147,255","2,278,461,199",119.0
6,201207,강원도,전체(시 / 군 / 구),산업용,"11,454","602,175,744","59,179,825,035",98.3
7,201207,강원도,전체(시 / 군 / 구),농사용,"68,541","31,012,645","1,422,250,672",45.9
8,201207,강원도,전체(시 / 군 / 구),가로등,"89,527","12,815,369","1,336,885,362",104.3
9,201207,강원도,전체(시 / 군 / 구),심 야,"96,598","51,781,406","2,465,864,062",47.6
10,201208,강원도,전체(시 / 군 / 구),주택용,"509,655","172,152,684","21,283,699,920",123.6
11,201208,강원도,전체(시 / 군 / 구),일반용,"121,633","342,276,473","44,891,553,753",131.2
12,201208,강원도,전체(시 / 군 / 구),교육용,"1,534","19,524,336","2,669,725,714",136.7
13,201208,강원도,전체(시 / 군 / 구),산업용,"11,451","557,897,312","57,623,638,877",103.3
14,201208,강원도,전체(시 / 군 / 구),농사용,"69,459","38,327,346","1,730,706,636",45.2
15,201208,강원도,전체(시 / 군 / 구),가로등,"89,864","13,124,619","1,347,010,198",102.6
16,201208,강원도,전체(시 / 군 / 구),심 야,"96,499","43,953,698","2,147,514,835",48.9
17,201209,강원도,전체(시 / 군 / 구),주택용,"510,728","163,008,945","19,123,143,489",117.3
18,201209,강원도,전체(시 / 군 / 구),일반용,"122,343","293,260,549","35,905,559,848",122.4
19,201209,강원도,전체(시 / 군 / 구),교육용,"1,532","20,028,837","2,465,951,586",123.1
20,201209,강원도,전체(시 / 군 / 구),산업용,"11,488","548,144,972","47,263,051,441",86.2
21,201209,강원도,전체(시 / 군 / 구),농사용,"70,792","44,658,159","2,054,858,780",46.0
22,201209,강원도,전체(시 / 군 / 구),가로등,"90,042","13,283,494","1,377,794,892",103.7
23,201209,강원도,전체(시 / 군 / 구),심 야,"96,460","55,126,357","2,761,779,357",50.1
24,201210,강원도,전체(시 / 군 / 구),주택용,"511,444","151,320,376","16,482,377,692",108.9
25,201210,강원도,전체(시 / 군 / 구),일반용,"123,031","262,559,026","29,116,326,660",110.9
26,201210,강원도,전체(시 / 군 / 구),교육용,"1,527","17,473,563","1,956,838,263",112.0
27,201210,강원도,전체(시 / 군 / 구),산업용,"11,588","581,388,466","48,256,848,625",83.0
28,201210,강원도,전체(시 / 군 / 구),농사용,"71,543","37,955,818","1,809,375,651",47.7
29,201210,강원도,전체(시 / 군 / 구),가로등,"90,270","14,305,726","1,404,050,937",98.1
30,201210,강원도,전체(시 / 군 / 구),심 야,"96,493","95,782,343","4,734,349,600",49.4
31,201211,강원도,전체(시 / 군 / 구),주택용,"511,744","163,840,554","19,795,857,284",120.8
32,201211,강원도,전체(시 / 군 / 구),일반용,"124,044","304,571,969","35,326,255,431",116.0
33,201211,강원도,전체(시 / 군 / 구),교육용,"1,516","23,661,893","2,586,337,671",109.3
34,201211,강원도,전체(시 / 군 / 구),산업용,"11,517","581,731,734","59,750,179,141",102.7
35,201211,강원도,전체(시 / 군 / 구),농사용,"94,039","50,291,792","2,065,724,958",41.1
36,201211,강원도,전체(시 / 군 / 구),가로등,"90,458","15,075,375","1,454,009,108",96.4
37,201211,강원도,전체(시 / 군 / 구),심 야,"96,500","183,236,635","10,464,708,055",57.1
38,201212,강원도,전체(시 / 군 / 구),주택용,"511,654","170,872,431","20,500,261,310",120.0
39,201212,강원도,전체(시 / 군 / 구),일반용,"125,310","371,492,917","44,978,933,203",121.1
40,201212,강원도,전체(시 / 군 / 구),교육용,"1,518","35,866,321","3,885,296,670",108.3
41,201212,강원도,전체(시 / 군 / 구),산업용,"11,540","606,718,083","61,116,263,717",100.7
42,201212,강원도,전체(시 / 군 / 구),농사용,"71,492","38,935,609","1,821,669,835",46.8
43,201212,강원도,전체(시 / 군 / 구),가로등,"90,854","15,430,038","1,456,973,393",94.4
44,201212,강원도,전체(시 / 군 / 구),심 야,"96,538","285,785,855","19,390,015,171",67.8
45,합계,합계,합계,합계,"5,445,625","7,490,888,409","747,910,500,361",99.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_1260\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)      사용량(kWh)
4   201207  강원도  일반용  120,807   291,064,554
11  201208  강원도  일반용  121,633   342,276,473
18  201209  강원도  일반용  122,343   293,260,549
25  201210  강원도  일반용  123,031   262,559,026
32  201211  강원도  일반용  124,044   304,571,969
39  201212  강원도  일반용  125,310   371,492,917

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201207  강원도  강릉시  일반용  16,205   34,530,914
197  201208  강원도  강릉시  일반용  16,272   42,030,483
341  201209  강원도  강릉시  일반용  16,344   36,690,466
485  201210  강원도  강릉시  일반용  16,431   31,690,515
629  201211  강원도  강릉시  일반용  16,539   34,694,500
..      ...  ...  ...  ...      ...          ...
333  201208  강원도  횡성군  일반용   4,060    9,221,624
477  201209  강원도  횡성군  일반용   4,090    7,717,793
621  201210  강원도  횡성군  일반용   4,145    6,965,137
765  201211  강원도  횡성군  일반용   4,198    9,319,054
909  201212  강원도  횡성군  일반용   4,249   12,840,546

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'강원도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강릉시',
 '고성군',
 '동해시',
 '삼척시',
 '속초시',
 '양구군',
 '양양군',
 '영월군',
 '원주시',
 '인제군',
 '정선군',
 '철원군',
 '춘천시',
 '태백시',
 '평창군',
 '홍천군',
 '화천군',
 '횡성군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201207  강원도  강릉시   합계  116,209   148,585,668
199  201208  강원도  강릉시   합계  116,448   147,674,991
343  201209  강원도  강릉시   합계  116,810   123,176,569
487  201210  강원도  강릉시   합계  117,059   130,906,118
631  201211  강원도  강릉시   합계  117,473   142,826,670
..      ...  ...  ...  ...       ...           ...
335  201208  강원도  횡성군   합계   42,955    33,594,690
479  201209  강원도  횡성군   합계   43,076    31,929,663
623  201210  강원도  횡성군   합계   43,185    33,725,873
767  201211  강원도  횡성군   합계   45,226    46,211,281
911  201212  강원도  횡성군   합계   43,348    56,156,308

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[148585668, 147674991, 123176569, 130906118, 142826670, 163174865]
[19099362, 20664537, 19910998, 19519132, 22513450, 26619766]
[261267778, 238120290, 247256554, 260237253, 256305184, 266782172]
[93746117, 94337328, 92239063, 93806743, 94589131, 107422616]
[32687596, 37420107, 33948364, 32313295, 36896298, 42775147]
[11593321, 12438840, 12551580, 13360200, 19261963, 22203015]
[19048000, 21859196, 20903303, 19817909, 23404843, 26485303]
[75304030, 77671399, 80439411, 84242439, 93071877, 93334332]
[157288209, 168764596, 157114635, 149939718, 184226139, 218448237]
[18345809, 19984780, 20004923, 21981771, 26597933, 33632866]
[44988966, 43995215, 44363435, 48504246, 55089879, 64916570]
[26442584, 29031935, 27790023, 30269972, 40662932, 52487040]
[105656047, 117970573, 109337099, 100002458, 121640704, 154169660]
[24530177, 25313682, 25504795, 27159276, 29745547, 33398314]
[30770369, 34082028, 31726613, 35808498, 51089266, 65422358]
[44046897, 48924672, 44059652, 43720892, 57898678, 72047142]
[13579384, 15407609, 15254633, 15469525, 20378177, 25625543]
[30843790, 33594690, 31929663, 33725873, 46211281, 56156308]
강원도 지역별 합계 :  [856344881, 128327245, 1529969231, 576140998, 216040807, 91408919, 131518554, 504063488, 1035781534, 140548082, 301858311, 206684486, 708776541, 165651791, 248899132, 310697933, 105714871, 232461605]
강원도 고객호수 평균:  [19483, 4225, 7454, 7839, 6080, 3272, 4389, 5925, 21998, 4961, 5782, 6437, 20866, 4549, 7329, 9988, 3443, 7237]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201207  강원도  강릉시   합계  116,209   148,585,668
1           201208  강원도  강릉시   합계  116,448   147,674,991
2           201209  강원도  강릉시   합계  116,810   123,176,569
3           201210  강원도  강릉시   합계  117,059   130,906,118
4           201211  강원도  강릉시   합계  117,473   142,826,670
..             ...  ...  ...  ...       ...           ...
121  201201-201206  강원도  태백시   합계      4549     165651791
122  201201-201206  강원도  평창군   합계      7329     248899132
123  201201-201206  강원도  홍천군   합계      9988     310697933
124  201201-201206  강원도  화천군   합계      3443     105714871
125  201201-201206  강원도  횡성군   합계      7237     232461605

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201207-201212']
Hap

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201201-201206  강원도  강릉시   합계   19483   856344881
109  201201-201206  강원도  고성군   합계    4225   128327245
110  201201-201206  강원도  동해시   합계    7454  1529969231
111  201201-201206  강원도  삼척시   합계    7839   576140998
112  201201-201206  강원도  속초시   합계    6080   216040807
113  201201-201206  강원도  양구군   합계    3272    91408919
114  201201-201206  강원도  양양군   합계    4389   131518554
115  201201-201206  강원도  영월군   합계    5925   504063488
116  201201-201206  강원도  원주시   합계   21998  1035781534
117  201201-201206  강원도  인제군   합계    4961   140548082
118  201201-201206  강원도  정선군   합계    5782   301858311
119  201201-201206  강원도  철원군   합계    6437   206684486
120  201201-201206  강원도  춘천시   합계   20866   708776541
121  201201-201206  강원도  태백시   합계    4549   165651791
122  201201-201206  강원도  평창군   합계    7329   248899132
123  201201-201206  강원도  홍천군   합계    9988   310697933
124  201201-201206  강원도  화천군   합계    3443   105714871
125  201201-201206  강원도  횡성군   합계    7237   232461605

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201207  강원도  강릉시  일반용  16,205   34,530,914
197  201208  강원도  강릉시  일반용  16,272   42,030,483
341  201209  강원도  강릉시  일반용  16,344   36,690,466
485  201210  강원도  강릉시  일반용  16,431   31,690,515
629  201211  강원도  강릉시  일반용  16,539   34,694,500
..      ...  ...  ...  ...      ...          ...
333  201208  강원도  횡성군  일반용   4,060    9,221,624
477  201209  강원도  횡성군  일반용   4,090    7,717,793
621  201210  강원도  횡성군  일반용   4,145    6,965,137
765  201211  강원도  횡성군  일반용   4,198    9,319,054
909  201212  강원도  횡성군  일반용   4,249   12,840,546

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[34530914, 42030483, 36690466, 31690515, 34694500, 39909152]
[8763807, 10414016, 8666668, 8079070, 8581720, 9859342]
[14140153, 16874020, 15029276, 13247357, 14938390, 17259732]
[10464113, 12724333, 11211553, 9769536, 11157135, 13220358]
[17858591, 21629045, 18072965, 16453786, 17579971, 20318791]
[5132207, 5707863, 5346563, 5147934, 5951598, 7369077]
[9048625, 11411684, 9747224, 8141302, 9336161, 10287685]
[5638030, 6817117, 5978396, 5042743, 5760753, 6667817]
[52897195, 60672571, 51654828, 43650796, 50006005, 61589853]
[9110502, 10396149, 9324538, 9417049, 9660927, 12169216]
[13522182, 15291901, 12406718, 13940360, 18255886, 22263870]
[10126043, 11729883, 10279488, 10546825, 9990606, 15324231]
[46930269, 54169505, 47527890, 39725653, 45021781, 53062219]
[6523538, 7420930, 6740576, 6508699, 7664345, 9384324]
[13760993, 16356095, 12755956, 12939819, 20383121, 26549759]
[17950418, 21051568, 16396309, 14218601, 17719331, 22845189]
[7066411, 8357686, 7713342, 7073844, 8550685, 10571756]
[7600563, 9221624, 7717793, 6965137, 9319054, 12840546]
강원도 지역별 일반용 합계 :  [219546030, 54364623, 91488928, 68547028, 111913149, 34655242, 57972681, 35904856, 320471248, 60078381, 95680917, 67997076, 286437317, 44242412, 102745743, 110181416, 49333724, 53664717]
강원도 고객호수 평균:  [16404, 3184, 6207, 5300, 6980, 2137, 3663, 3566, 21151, 3860, 4506, 4411, 18528, 3898, 5235, 6953, 2743, 4129]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1260\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201207  강원도  강릉시  일반용  16,205   34,530,914
1           201208  강원도  강릉시  일반용  16,272   42,030,483
2           201209  강원도  강릉시  일반용  16,344   36,690,466
3           201210  강원도  강릉시  일반용  16,431   31,690,515
4           201211  강원도  강릉시  일반용  16,539   34,694,500
..             ...  ...  ...  ...      ...          ...
121  201201-201206  강원도  태백시  일반용     3898     44242412
122  201201-201206  강원도  평창군  일반용     5235    102745743
123  201201-201206  강원도  홍천군  일반용     6953    110181416
124  201201-201206  강원도  화천군  일반용     2743     49333724
125  201201-201206  강원도  횡성군  일반용     4129     53664717

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201207-201212']
GyeonGiHap2

                년월   시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201201-201206  강원도  강릉시  일반용   16404  219546030
109  201201-201206  강원도  고성군  일반용    3184   54364623
110  201201-201206  강원도  동해시  일반용    6207   91488928
111  201201-201206  강원도  삼척시  일반용    5300   68547028
112  201201-201206  강원도  속초시  일반용    6980  111913149
113  201201-201206  강원도  양구군  일반용    2137   34655242
114  201201-201206  강원도  양양군  일반용    3663   57972681
115  201201-201206  강원도  영월군  일반용    3566   35904856
116  201201-201206  강원도  원주시  일반용   21151  320471248
117  201201-201206  강원도  인제군  일반용    3860   60078381
118  201201-201206  강원도  정선군  일반용    4506   95680917
119  201201-201206  강원도  철원군  일반용    4411   67997076
120  201201-201206  강원도  춘천시  일반용   18528  286437317
121  201201-201206  강원도  태백시  일반용    3898   44242412
122  201201-201206  강원도  평창군  일반용    5235  102745743
123  201201-201206  강원도  홍천군  일반용    6953  110181416
124  201201-201206  강원도  화천군  일반용    2743   49333724
125  201201-201206  강원도  횡성군  일반용    4129   53664717

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201201-201206  강원도  강릉시  일반용   16404   219546030
108  201201-201206  강원도  강릉시   합계   19483   856344881
109  201201-201206  강원도  고성군  일반용    3184    54364623
109  201201-201206  강원도  고성군   합계    4225   128327245
110  201201-201206  강원도  동해시  일반용    6207    91488928
110  201201-201206  강원도  동해시   합계    7454  1529969231
111  201201-201206  강원도  삼척시   합계    7839   576140998
111  201201-201206  강원도  삼척시  일반용    5300    68547028
112  201201-201206  강원도  속초시   합계    6080   216040807
112  201201-201206  강원도  속초시  일반용    6980   111913149
113  201201-201206  강원도  양구군  일반용    2137    34655242
113  201201-201206  강원도  양구군   합계    3272    91408919
114  201201-201206  강원도  양양군   합계    4389   131518554
114  201201-201206  강원도  양양군  일반용    3663    57972681
115  201201-201206  강원도  영월군  일반용    3566    35904856
115  201201-201206  강원도  영월군   합계    5925   504063488
116  201201-201206  강원도  원주시  일반용   21151   320471248
116  201201-201206  강원도  원주시   합계   21998  1035781534
117  201201-201206  강원도  인제군  일반용    3860    60078381
117  201201-201206  강원도  인제군   합계    4961   140548082
118  201201-201206  강원도  정선군   합계    5782   301858311
118  201201-201206  강원도  정선군  일반용    4506    95680917
119  201201-201206  강원도  철원군   합계    6437   206684486
119  201201-201206  강원도  철원군  일반용    4411    67997076
120  201201-201206  강원도  춘천시  일반용   18528   286437317
120  201201-201206  강원도  춘천시   합계   20866   708776541
121  201201-201206  강원도  태백시   합계    4549   165651791
121  201201-201206  강원도  태백시  일반용    3898    44242412
122  201201-201206  강원도  평창군   합계    7329   248899132
122  201201-201206  강원도  평창군  일반용    5235   102745743
123  201201-201206  강원도  홍천군   합계    9988   310697933
123  201201-201206  강원도  홍천군  일반용    6953   110181416
124  201201-201206  강원도  화천군   합계    3443   105714871
124  201201-201206  강원도  화천군  일반용    2743    49333724
125  201201-201206  강원도  횡성군  일반용    4129    53664717
125  201201-201206  강원도  횡성군   합계    7237   232461605

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[219546030,
 54364623,
 91488928,
 68547028,
 111913149,
 34655242,
 57972681,
 35904856,
 320471248,
 60078381,
 95680917,
 67997076,
 286437317,
 44242412,
 102745743,
 110181416,
 49333724,
 53664717]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[856344881,
 128327245,
 1529969231,
 576140998,
 216040807,
 91408919,
 131518554,
 504063488,
 1035781534,
 140548082,
 301858311,
 206684486,
 708776541,
 165651791,
 248899132,
 310697933,
 105714871,
 232461605]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[25.64, 42.36, 5.98, 11.9, 51.8, 37.91, 44.08, 7.12, 30.94, 42.75, 31.7, 32.9, 40.41, 26.71, 41.28, 35.46, 46.67, 23.09]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    26
1    42
2     6
3    12
4    52
5    38
6    44
7     7
8    31
9    43
10   32
11   33
12   40
13   27
14   41
15   35
16   47
17   23
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강릉시  일반용  26
1   고성군  일반용  42
2   동해시  일반용   6
3   삼척시  일반용  12
4   속초시  일반용  52
5   양구군  일반용  38
6   양양군  일반용  44
7   영월군  일반용   7
8   원주시  일반용  31
9   인제군  일반용  43
10  정선군  일반용  32
11  철원군  일반용  33
12  춘천시  일반용  40
13  태백시  일반용  27
14  평창군  일반용  41
15  홍천군  일반용  35
16  화천군  일반용  47
17  횡성군  일반용  23

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201201-201206  강원도  강릉시  일반용   16404   219546030  26
1   201201-201206  강원도  강릉시   합계   19483   856344881 NaN
2   201201-201206  강원도  고성군  일반용    3184    54364623  42
3   201201-201206  강원도  고성군   합계    4225   128327245 NaN
4   201201-201206  강원도  동해시  일반용    6207    91488928   6
5   201201-201206  강원도  동해시   합계    7454  1529969231 NaN
7   201201-201206  강원도  삼척시  일반용    5300    68547028  12
6   201201-201206  강원도  삼척시   합계    7839   576140998 NaN
9   201201-201206  강원도  속초시  일반용    6980   111913149  52
8   201201-201206  강원도  속초시   합계    6080   216040807 NaN
10  201201-201206  강원도  양구군  일반용    2137    34655242  38
11  201201-201206  강원도  양구군   합계    3272    91408919 NaN
13  201201-201206  강원도  양양군  일반용    3663    57972681  44
12  201201-201206  강원도  양양군   합계    4389   131518554 NaN
14  201201-201206  강원도  영월군  일반용    3566    35904856   7
15  201201-201206  강원도  영월군   합계    5925   504063488 NaN
16  201201-201206  강원도  원주시  일반용   21151   320471248  31
17  201201-201206  강원도  원주시   합계   21998  1035781534 NaN
18  201201-201206  강원도  인제군  일반용    3860    60078381  43
19  201201-201206  강원도  인제군   합계    4961   140548082 NaN
21  201201-201206  강원도  정선군  일반용    4506    95680917  32
20  201201-201206  강원도  정선군   합계    5782   301858311 NaN
23  201201-201206  강원도  철원군  일반용    4411    67997076  33
22  201201-201206  강원도  철원군   합계    6437   206684486 NaN
24  201201-201206  강원도  춘천시  일반용   18528   286437317  40
25  201201-201206  강원도  춘천시   합계   20866   708776541 NaN
27  201201-201206  강원도  태백시  일반용    3898    44242412  27
26  201201-201206  강원도  태백시   합계    4549   165651791 NaN
29  201201-201206  강원도  평창군  일반용    5235   102745743  41
28  201201-201206  강원도  평창군   합계    7329   248899132 NaN
31  201201-201206  강원도  홍천군  일반용    6953   110181416  35
30  201201-201206  강원도  홍천군   합계    9988   310697933 NaN
33  201201-201206  강원도  화천군  일반용    2743    49333724  47
32  201201-201206  강원도  화천군   합계    3443   105714871 NaN
34  201201-201206  강원도  횡성군  일반용    4129    53664717  23
35  201201-201206  강원도  횡성군   합계    7237   232461605 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1207-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)