In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라북도_계약종별_전력사용량_월별_19하반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라북도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2019년 07 월 ~ 2019년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201907,전라북도,전체(시 / 군 / 구),주택용,"659,965","190,102,311","18,155,734,464",95.5
4,201907,전라북도,전체(시 / 군 / 구),일반용,"140,110","300,207,059","45,934,739,239",153.0
...,...,...,...,...,...,...,...,...
715,201912,전라북도,진안군,산업용,857,"2,999,911","435,510,622",145.2
716,201912,전라북도,진안군,심 야,"1,845","2,979,766","221,844,845",74.5
717,201912,전라북도,진안군,일반용,"2,234","4,266,765","588,253,195",137.9
718,201912,전라북도,진안군,주택용,"14,317","2,472,960","278,625,987",112.7
719,201912,전라북도,진안군,합계,"31,261","19,311,153","1,931,756,397",100

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201907,전라북도,전체(시 / 군 / 구),주택용,"659,965","190,102,311","18,155,734,464",95.5
4,201907,전라북도,전체(시 / 군 / 구),일반용,"140,110","300,207,059","45,934,739,239",153.0
5,201907,전라북도,전체(시 / 군 / 구),교육용,"1,241","27,386,396","3,443,924,592",125.8
6,201907,전라북도,전체(시 / 군 / 구),산업용,"15,468","1,070,749,432","124,372,814,491",116.2
...,...,...,...,...,...,...,...,...
715,201912,전라북도,진안군,산업용,857,"2,999,911","435,510,622",145.2
716,201912,전라북도,진안군,심 야,"1,845","2,979,766","221,844,845",74.5
717,201912,전라북도,진안군,일반용,"2,234","4,266,765","588,253,195",137.9
718,201912,전라북도,진안군,주택용,"14,317","2,472,960","278,625,987",112.7
719,201912,전라북도,진안군,합계,"31,261","19,311,153","1,931,756,397",100

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201907,전라북도,전체(시 / 군 / 구),주택용,"659,965","190,102,311","18,155,734,464",95.5
4,201907,전라북도,전체(시 / 군 / 구),일반용,"140,110","300,207,059","45,934,739,239",153.0
5,201907,전라북도,전체(시 / 군 / 구),교육용,"1,241","27,386,396","3,443,924,592",125.8
6,201907,전라북도,전체(시 / 군 / 구),산업용,"15,468","1,070,749,432","124,372,814,491",116.2
7,201907,전라북도,전체(시 / 군 / 구),농사용,"152,625","127,142,591","6,065,497,581",47.7
...,...,...,...,...,...,...,...,...
715,201912,전라북도,진안군,산업용,857,"2,999,911","435,510,622",145.2
716,201912,전라북도,진안군,심 야,"1,845","2,979,766","221,844,845",74.5
717,201912,전라북도,진안군,일반용,"2,234","4,266,765","588,253,195",137.9
718,201912,전라북도,진안군,주택용,"14,317","2,472,960","278,625,987",112.7
719,201912,전라북도,진안군,합계,"31,261","19,311,153","1,931,756,397",100

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201907,전라북도,전체(시 / 군 / 구),주택용,"659,965","190,102,311","18,155,734,464",95.5
4,201907,전라북도,전체(시 / 군 / 구),일반용,"140,110","300,207,059","45,934,739,239",153.0
5,201907,전라북도,전체(시 / 군 / 구),교육용,"1,241","27,386,396","3,443,924,592",125.8
6,201907,전라북도,전체(시 / 군 / 구),산업용,"15,468","1,070,749,432","124,372,814,491",116.2
7,201907,전라북도,전체(시 / 군 / 구),농사용,"152,625","127,142,591","6,065,497,581",47.7
8,201907,전라북도,전체(시 / 군 / 구),가로등,"140,150","15,352,473","1,871,293,113",121.9
9,201907,전라북도,전체(시 / 군 / 구),심 야,"61,364","20,210,096","1,150,370,265",56.9
10,201908,전라북도,전체(시 / 군 / 구),주택용,"661,133","254,813,860","25,626,597,116",100.6
11,201908,전라북도,전체(시 / 군 / 구),일반용,"140,285","367,008,158","53,152,075,084",144.8
12,201908,전라북도,전체(시 / 군 / 구),교육용,"1,241","28,044,324","3,574,156,391",127.4
13,201908,전라북도,전체(시 / 군 / 구),산업용,"15,505","1,004,125,265","116,092,297,110",115.6
14,201908,전라북도,전체(시 / 군 / 구),농사용,"153,893","163,420,235","7,635,193,161",46.7
15,201908,전라북도,전체(시 / 군 / 구),가로등,"140,575","16,112,034","1,889,842,603",117.3
16,201908,전라북도,전체(시 / 군 / 구),심 야,"61,229","17,764,465","1,046,639,613",58.9
17,201909,전라북도,전체(시 / 군 / 구),주택용,"662,108","232,076,233","23,413,373,352",100.9
18,201909,전라북도,전체(시 / 군 / 구),일반용,"140,402","328,936,078","43,205,924,284",131.4
19,201909,전라북도,전체(시 / 군 / 구),교육용,"1,242","29,760,036","3,306,180,619",111.1
20,201909,전라북도,전체(시 / 군 / 구),산업용,"15,527","1,080,894,074","97,627,319,834",90.3
21,201909,전라북도,전체(시 / 군 / 구),농사용,"154,839","159,990,589","7,550,652,943",47.2
22,201909,전라북도,전체(시 / 군 / 구),가로등,"140,916","16,599,690","1,889,767,120",113.8
23,201909,전라북도,전체(시 / 군 / 구),심 야,"61,080","17,375,677","999,836,854",57.5
24,201910,전라북도,전체(시 / 군 / 구),주택용,"662,914","191,866,612","19,145,578,075",99.8
25,201910,전라북도,전체(시 / 군 / 구),일반용,"140,619","272,118,073","32,739,459,962",120.3
26,201910,전라북도,전체(시 / 군 / 구),교육용,"1,240","24,443,230","2,401,723,493",98.3
27,201910,전라북도,전체(시 / 군 / 구),산업용,"15,560","1,139,837,523","100,186,159,191",87.9
28,201910,전라북도,전체(시 / 군 / 구),농사용,"155,301","121,317,597","6,056,119,383",49.9
29,201910,전라북도,전체(시 / 군 / 구),가로등,"141,104","17,753,732","1,911,092,334",107.6
30,201910,전라북도,전체(시 / 군 / 구),심 야,"60,989","25,624,379","1,424,659,080",55.6
31,201911,전라북도,전체(시 / 군 / 구),주택용,"663,977","196,957,072","20,237,087,521",102.7
32,201911,전라북도,전체(시 / 군 / 구),일반용,"141,023","274,213,495","36,655,652,532",133.7
33,201911,전라북도,전체(시 / 군 / 구),교육용,"1,241","27,429,343","2,934,806,313",107.0
34,201911,전라북도,전체(시 / 군 / 구),산업용,"15,572","1,085,898,159","121,215,949,548",111.6
35,201911,전라북도,전체(시 / 군 / 구),농사용,"227,818","165,843,790","7,278,969,036",43.9
36,201911,전라북도,전체(시 / 군 / 구),가로등,"141,436","18,876,452","1,983,407,501",105.1
37,201911,전라북도,전체(시 / 군 / 구),심 야,"60,882","52,417,841","3,309,712,314",63.1
38,201912,전라북도,전체(시 / 군 / 구),주택용,"664,772","206,900,348","21,724,429,923",105.0
39,201912,전라북도,전체(시 / 군 / 구),일반용,"141,641","321,118,265","44,681,080,224",139.1
40,201912,전라북도,전체(시 / 군 / 구),교육용,"1,240","39,970,583","4,088,162,992",102.3
41,201912,전라북도,전체(시 / 군 / 구),산업용,"15,628","1,087,887,255","122,048,443,000",112.2
42,201912,전라북도,전체(시 / 군 / 구),농사용,"191,996","160,923,547","7,371,215,910",45.8
43,201912,전라북도,전체(시 / 군 / 구),가로등,"141,707","19,207,347","1,996,965,351",104.0
44,201912,전라북도,전체(시 / 군 / 구),심 야,"60,755","93,584,864","6,932,783,769",74.1
45,합계,합계,합계,합계,"7,168,313","11,012,260,583","1,154,327,687,281",104.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_7064\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201907  전라북도  일반용  140,110   300,207,059
11  201908  전라북도  일반용  140,285   367,008,158
18  201909  전라북도  일반용  140,402   328,936,078
25  201910  전라북도  일반용  140,619   272,118,073
32  201911  전라북도  일반용  141,023   274,213,495
39  201912  전라북도  일반용  141,641   321,118,265

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53   201907  전라북도  고창군  일반용  4,706    8,326,812
165  201908  전라북도  고창군  일반용  4,732   10,373,590
277  201909  전라북도  고창군  일반용  4,734    9,354,884
389  201910  전라북도  고창군  일반용  4,754    8,038,872
501  201911  전라북도  고창군  일반용  4,742    8,265,659
..      ...   ...  ...  ...     ...          ...
269  201908  전라북도  진안군  일반용  2,198    3,848,185
381  201909  전라북도  진안군  일반용  2,188    3,496,248
493  201910  전라북도  진안군  일반용  2,197    3,180,446
605  201911  전라북도  진안군  일반용  2,205    3,599,083
717  201912  전라북도  진안군  일반용  2,234    4,266,765

[84 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라북도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['고창군',
 '군산시',
 '김제시',
 '남원시',
 '무주군',
 '부안군',
 '순창군',
 '완주군',
 '익산시',
 '임실군',
 '장수군',
 '전주시',
 '정읍시',
 '진안군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55   201907  전라북도  고창군   합계  58,644   44,301,939
167  201908  전라북도  고창군   합계  58,789   50,582,590
279  201909  전라북도  고창군   합계  58,891   48,098,292
391  201910  전라북도  고창군   합계  58,980   43,933,291
503  201911  전라북도  고창군   합계  62,154   50,352,754
..      ...   ...  ...  ...      ...          ...
271  201908  전라북도  진안군   합계  30,925   16,029,705
383  201909  전라북도  진안군   합계  31,042   17,050,409
495  201910  전라북도  진안군   합계  31,161   15,096,053
607  201911  전라북도  진안군   합계  33,557   17,253,983
719  201912  전라북도  진안군   합계  31,261   19,311,153

[84 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[44301939, 50582590, 48098292, 43933291, 50352754, 67873895]
[587361754, 559435676, 658741646, 675874932, 640096605, 637981881]
[78231555, 87439062, 81574197, 76176026, 88740882, 94578562]
[47382166, 55475353, 50788575, 45879286, 49175058, 59049038]
[14565389, 16955858, 16280137, 15064846, 17178111, 21685197]
[38122497, 44940101, 41785943, 35881248, 41526615, 41629963]
[20867355, 23661349, 22978889, 20747564, 24549276, 22410668]
[144348707, 146278274, 136626030, 132811844, 138344373, 150910482]
[249383790, 270551826, 251316479, 231818553, 243563012, 259611919]
[21815523, 25077961, 25591024, 22496030, 25639656, 26676325]
[12985780, 15341306, 14901839, 14543540, 17541401, 21023375]
[354687891, 404670665, 373027447, 342685210, 338143149, 377783161]
[123380424, 134848615, 126871470, 119952723, 129531277, 129066590]
[13715588, 16029705, 17050409, 15096053, 17253983, 19311153]
전라북도 지역별 합계 :  [305142761, 3759492494, 506740284, 307749476, 101729538, 243886367, 135215101, 849319710, 1506245579, 147296519, 96337241, 2190997523, 763651099, 98456891]
전라북도 고객호수 평균:  [10441, 23336, 13108, 13342, 4809, 9116, 6042, 11641, 28531, 5714, 4588, 46510, 16692, 5242]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\51496957.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201907  전라북도  고창군   합계  58,644   44,301,939
1          201908  전라북도  고창군   합계  58,789   50,582,590
2          201909  전라북도  고창군   합계  58,891   48,098,292
3          201910  전라북도  고창군   합계  58,980   43,933,291
4          201911  전라북도  고창군   합계  62,154   50,352,754
..            ...   ...  ...  ...      ...          ...
93  201907-201912  전라북도  임실군   합계     5714    147296519
94  201907-201912  전라북도  장수군   합계     4588     96337241
95  201907-201912  전라북도  전주시   합계    46510   2190997523
96  201907-201912  전라북도  정읍시   합계    16692    763651099
97  201907-201912  전라북도  진안군   합계     5242     98456891

[98 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201907-201912']
Hap

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  201907-201912  전라북도  고창군   합계   10441   305142761
85  201907-201912  전라북도  군산시   합계   23336  3759492494
86  201907-201912  전라북도  김제시   합계   13108   506740284
87  201907-201912  전라북도  남원시   합계   13342   307749476
88  201907-201912  전라북도  무주군   합계    4809   101729538
89  201907-201912  전라북도  부안군   합계    9116   243886367
90  201907-201912  전라북도  순창군   합계    6042   135215101
91  201907-201912  전라북도  완주군   합계   11641   849319710
92  201907-201912  전라북도  익산시   합계   28531  1506245579
93  201907-201912  전라북도  임실군   합계    5714   147296519
94  201907-201912  전라북도  장수군   합계    4588    96337241
95  201907-201912  전라북도  전주시   합계   46510  2190997523
96  201907-201912  전라북도  정읍시   합계   16692   763651099
97  201907-201912  전라북도  진안군   합계    5242    98456891

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53   201907  전라북도  고창군  일반용  4,706    8,326,812
165  201908  전라북도  고창군  일반용  4,732   10,373,590
277  201909  전라북도  고창군  일반용  4,734    9,354,884
389  201910  전라북도  고창군  일반용  4,754    8,038,872
501  201911  전라북도  고창군  일반용  4,742    8,265,659
..      ...   ...  ...  ...     ...          ...
269  201908  전라북도  진안군  일반용  2,198    3,848,185
381  201909  전라북도  진안군  일반용  2,188    3,496,248
493  201910  전라북도  진안군  일반용  2,197    3,180,446
605  201911  전라북도  진안군  일반용  2,205    3,599,083
717  201912  전라북도  진안군  일반용  2,234    4,266,765

[84 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[8326812, 10373590, 9354884, 8038872, 8265659, 9368000]
[48624808, 60711803, 54808801, 45289264, 44677414, 51509600]
[12881349, 15903926, 14434542, 12225770, 12571899, 14178470]
[12765326, 15482406, 13942586, 11743112, 12241654, 14216618]
[5721391, 7125409, 6072975, 5490445, 6506784, 10023099]
[10422046, 13345673, 11912586, 9662826, 10045763, 11432376]
[3495686, 4245755, 3637525, 3185472, 3516676, 4099428]
[20455091, 23914093, 20752192, 17213966, 17672510, 20514784]
[41328019, 50999809, 46279759, 37485037, 36996133, 43511486]
[4332698, 5124302, 4542215, 4027506, 4394979, 5234812]
[2760371, 3417244, 2984120, 2715564, 3048513, 3561072]
[110572050, 133516750, 119670419, 97811030, 95821390, 111863154]
[15338495, 18999213, 17047226, 14048763, 14855038, 17338601]
[3182917, 3848185, 3496248, 3180446, 3599083, 4266765]
전라북도 지역별 일반용 합계 :  [53727817, 305621690, 82195956, 80391702, 40940103, 66821270, 22180542, 120522636, 256600243, 27656512, 18486884, 669254793, 97627336, 21573644]
전라북도 고객호수 평균:  [4743, 20376, 6501, 7523, 2766, 5686, 2312, 7515, 20627, 2285, 1763, 47132, 9242, 2203]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7064\2665167033.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201907  전라북도  고창군  일반용  4,706    8,326,812
1          201908  전라북도  고창군  일반용  4,732   10,373,590
2          201909  전라북도  고창군  일반용  4,734    9,354,884
3          201910  전라북도  고창군  일반용  4,754    8,038,872
4          201911  전라북도  고창군  일반용  4,742    8,265,659
..            ...   ...  ...  ...     ...          ...
93  201907-201912  전라북도  임실군  일반용    2285     27656512
94  201907-201912  전라북도  장수군  일반용    1763     18486884
95  201907-201912  전라북도  전주시  일반용   47132    669254793
96  201907-201912  전라북도  정읍시  일반용    9242     97627336
97  201907-201912  전라북도  진안군  일반용    2203     21573644

[98 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201907-201912']
GyeonGiHap2

               년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
84  201907-201912  전라북도  고창군  일반용    4743   53727817
85  201907-201912  전라북도  군산시  일반용   20376  305621690
86  201907-201912  전라북도  김제시  일반용    6501   82195956
87  201907-201912  전라북도  남원시  일반용    7523   80391702
88  201907-201912  전라북도  무주군  일반용    2766   40940103
89  201907-201912  전라북도  부안군  일반용    5686   66821270
90  201907-201912  전라북도  순창군  일반용    2312   22180542
91  201907-201912  전라북도  완주군  일반용    7515  120522636
92  201907-201912  전라북도  익산시  일반용   20627  256600243
93  201907-201912  전라북도  임실군  일반용    2285   27656512
94  201907-201912  전라북도  장수군  일반용    1763   18486884
95  201907-201912  전라북도  전주시  일반용   47132  669254793
96  201907-201912  전라북도  정읍시  일반용    9242   97627336
97  201907-201912  전라북도  진안군  일반용    2203   21573644

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  201907-201912  전라북도  고창군  일반용    4743    53727817
84  201907-201912  전라북도  고창군   합계   10441   305142761
85  201907-201912  전라북도  군산시  일반용   20376   305621690
85  201907-201912  전라북도  군산시   합계   23336  3759492494
86  201907-201912  전라북도  김제시  일반용    6501    82195956
86  201907-201912  전라북도  김제시   합계   13108   506740284
87  201907-201912  전라북도  남원시  일반용    7523    80391702
87  201907-201912  전라북도  남원시   합계   13342   307749476
88  201907-201912  전라북도  무주군  일반용    2766    40940103
88  201907-201912  전라북도  무주군   합계    4809   101729538
89  201907-201912  전라북도  부안군  일반용    5686    66821270
89  201907-201912  전라북도  부안군   합계    9116   243886367
90  201907-201912  전라북도  순창군  일반용    2312    22180542
90  201907-201912  전라북도  순창군   합계    6042   135215101
91  201907-201912  전라북도  완주군   합계   11641   849319710
91  201907-201912  전라북도  완주군  일반용    7515   120522636
92  201907-201912  전라북도  익산시  일반용   20627   256600243
92  201907-201912  전라북도  익산시   합계   28531  1506245579
93  201907-201912  전라북도  임실군   합계    5714   147296519
93  201907-201912  전라북도  임실군  일반용    2285    27656512
94  201907-201912  전라북도  장수군   합계    4588    96337241
94  201907-201912  전라북도  장수군  일반용    1763    18486884
95  201907-201912  전라북도  전주시   합계   46510  2190997523
95  201907-201912  전라북도  전주시  일반용   47132   669254793
96  201907-201912  전라북도  정읍시   합계   16692   763651099
96  201907-201912  전라북도  정읍시  일반용    9242    97627336
97  201907-201912  전라북도  진안군  일반용    2203    21573644
97  201907-201912  전라북도  진안군   합계    5242    98456891

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[53727817,
 305621690,
 82195956,
 80391702,
 40940103,
 66821270,
 22180542,
 120522636,
 256600243,
 27656512,
 18486884,
 669254793,
 97627336,
 21573644]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[305142761,
 3759492494,
 506740284,
 307749476,
 101729538,
 243886367,
 135215101,
 849319710,
 1506245579,
 147296519,
 96337241,
 2190997523,
 763651099,
 98456891]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[17.61, 8.13, 16.22, 26.12, 40.24, 27.4, 16.4, 14.19, 17.04, 18.78, 19.19, 30.55, 12.78, 21.91]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    18
1     8
2    16
3    26
4    40
5    27
6    16
7    14
8    17
9    19
10   19
11   31
12   13
13   22
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   고창군  일반용  18
1   군산시  일반용   8
2   김제시  일반용  16
3   남원시  일반용  26
4   무주군  일반용  40
5   부안군  일반용  27
6   순창군  일반용  16
7   완주군  일반용  14
8   익산시  일반용  17
9   임실군  일반용  19
10  장수군  일반용  19
11  전주시  일반용  31
12  정읍시  일반용  13
13  진안군  일반용  22

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201907-201912  전라북도  고창군  일반용    4743    53727817  18
1   201907-201912  전라북도  고창군   합계   10441   305142761 NaN
2   201907-201912  전라북도  군산시  일반용   20376   305621690   8
3   201907-201912  전라북도  군산시   합계   23336  3759492494 NaN
4   201907-201912  전라북도  김제시  일반용    6501    82195956  16
5   201907-201912  전라북도  김제시   합계   13108   506740284 NaN
6   201907-201912  전라북도  남원시  일반용    7523    80391702  26
7   201907-201912  전라북도  남원시   합계   13342   307749476 NaN
8   201907-201912  전라북도  무주군  일반용    2766    40940103  40
9   201907-201912  전라북도  무주군   합계    4809   101729538 NaN
10  201907-201912  전라북도  부안군  일반용    5686    66821270  27
11  201907-201912  전라북도  부안군   합계    9116   243886367 NaN
12  201907-201912  전라북도  순창군  일반용    2312    22180542  16
13  201907-201912  전라북도  순창군   합계    6042   135215101 NaN
15  201907-201912  전라북도  완주군  일반용    7515   120522636  14
14  201907-201912  전라북도  완주군   합계   11641   849319710 NaN
16  201907-201912  전라북도  익산시  일반용   20627   256600243  17
17  201907-201912  전라북도  익산시   합계   28531  1506245579 NaN
19  201907-201912  전라북도  임실군  일반용    2285    27656512  19
18  201907-201912  전라북도  임실군   합계    5714   147296519 NaN
21  201907-201912  전라북도  장수군  일반용    1763    18486884  19
20  201907-201912  전라북도  장수군   합계    4588    96337241 NaN
23  201907-201912  전라북도  전주시  일반용   47132   669254793  31
22  201907-201912  전라북도  전주시   합계   46510  2190997523 NaN
25  201907-201912  전라북도  정읍시  일반용    9242    97627336  13
24  201907-201912  전라북도  정읍시   합계   16692   763651099 NaN
26  201907-201912  전라북도  진안군  일반용    2203    21573644  22
27  201907-201912  전라북도  진안군   합계    5242    98456891 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1907-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)