In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('서울특별시_계약종별_전력사용량_월별_16상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 서울특별시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2016년 01 월 ~ 2016년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,서울특별시,전체(시 / 군 / 구),주택용,"2,689,573","1,180,825,360","160,582,522,316",136.0
4,201601,서울특별시,전체(시 / 군 / 구),일반용,"536,845","2,300,587,864","304,846,435,396",132.5
...,...,...,...,...,...,...,...,...
1237,201606,서울특별시,중랑구,산업용,"2,671","5,667,233","697,783,006",123.1
1238,201606,서울특별시,중랑구,심 야,556,"503,764","30,303,430",60.2
1239,201606,서울특별시,중랑구,일반용,"19,410","37,304,806","4,908,502,453",131.6
1240,201606,서울특별시,중랑구,주택용,"129,941","39,757,606","4,683,738,969",117.8
1241,201606,서울특별시,중랑구,합계,"162,596","85,784,989","10,651,452,022",124.2

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,서울특별시,전체(시 / 군 / 구),주택용,"2,689,573","1,180,825,360","160,582,522,316",136.0
4,201601,서울특별시,전체(시 / 군 / 구),일반용,"536,845","2,300,587,864","304,846,435,396",132.5
5,201601,서울특별시,전체(시 / 군 / 구),교육용,"2,662","162,880,103","16,665,585,311",102.3
6,201601,서울특별시,전체(시 / 군 / 구),산업용,"45,904","438,093,989","53,297,366,981",121.7
...,...,...,...,...,...,...,...,...
1237,201606,서울특별시,중랑구,산업용,"2,671","5,667,233","697,783,006",123.1
1238,201606,서울특별시,중랑구,심 야,556,"503,764","30,303,430",60.2
1239,201606,서울특별시,중랑구,일반용,"19,410","37,304,806","4,908,502,453",131.6
1240,201606,서울특별시,중랑구,주택용,"129,941","39,757,606","4,683,738,969",117.8
1241,201606,서울특별시,중랑구,합계,"162,596","85,784,989","10,651,452,022",124.2

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,서울특별시,전체(시 / 군 / 구),주택용,"2,689,573","1,180,825,360","160,582,522,316",136.0
4,201601,서울특별시,전체(시 / 군 / 구),일반용,"536,845","2,300,587,864","304,846,435,396",132.5
5,201601,서울특별시,전체(시 / 군 / 구),교육용,"2,662","162,880,103","16,665,585,311",102.3
6,201601,서울특별시,전체(시 / 군 / 구),산업용,"45,904","438,093,989","53,297,366,981",121.7
7,201601,서울특별시,전체(시 / 군 / 구),농사용,"1,947","1,545,999","75,218,496",48.7
...,...,...,...,...,...,...,...,...
1237,201606,서울특별시,중랑구,산업용,"2,671","5,667,233","697,783,006",123.1
1238,201606,서울특별시,중랑구,심 야,556,"503,764","30,303,430",60.2
1239,201606,서울특별시,중랑구,일반용,"19,410","37,304,806","4,908,502,453",131.6
1240,201606,서울특별시,중랑구,주택용,"129,941","39,757,606","4,683,738,969",117.8
1241,201606,서울특별시,중랑구,합계,"162,596","85,784,989","10,651,452,022",124.2

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,서울특별시,전체(시 / 군 / 구),주택용,"2,689,573","1,180,825,360","160,582,522,316",136.0
4,201601,서울특별시,전체(시 / 군 / 구),일반용,"536,845","2,300,587,864","304,846,435,396",132.5
5,201601,서울특별시,전체(시 / 군 / 구),교육용,"2,662","162,880,103","16,665,585,311",102.3
6,201601,서울특별시,전체(시 / 군 / 구),산업용,"45,904","438,093,989","53,297,366,981",121.7
7,201601,서울특별시,전체(시 / 군 / 구),농사용,"1,947","1,545,999","75,218,496",48.7
8,201601,서울특별시,전체(시 / 군 / 구),가로등,"177,824","34,470,446","3,563,624,986",103.4
9,201601,서울특별시,전체(시 / 군 / 구),심 야,"17,591","33,365,866","2,751,570,525",82.5
10,201602,서울특별시,전체(시 / 군 / 구),주택용,"2,692,624","1,197,875,945","164,573,100,948",137.4
11,201602,서울특별시,전체(시 / 군 / 구),일반용,"537,530","2,301,067,005","303,969,805,579",132.1
12,201602,서울특별시,전체(시 / 군 / 구),교육용,"2,672","167,618,184","17,380,438,452",103.7
13,201602,서울특별시,전체(시 / 군 / 구),산업용,"45,921","438,641,858","52,983,385,777",120.8
14,201602,서울특별시,전체(시 / 군 / 구),농사용,"1,941","1,704,059","83,186,224",48.8
15,201602,서울특별시,전체(시 / 군 / 구),가로등,"178,122","32,713,575","3,495,185,316",106.8
16,201602,서울특별시,전체(시 / 군 / 구),심 야,"17,517","35,296,829","2,920,072,916",82.7
17,201603,서울특별시,전체(시 / 군 / 구),주택용,"2,695,752","1,070,581,592","132,577,628,605",123.8
18,201603,서울특별시,전체(시 / 군 / 구),일반용,"537,609","2,024,712,345","245,164,499,477",121.1
19,201603,서울특별시,전체(시 / 군 / 구),교육용,"2,671","146,615,784","14,505,085,940",98.9
20,201603,서울특별시,전체(시 / 군 / 구),산업용,"45,989","426,965,456","45,931,078,512",107.6
21,201603,서울특별시,전체(시 / 군 / 구),농사용,"2,183","1,502,500","72,548,489",48.3
22,201603,서울특별시,전체(시 / 군 / 구),가로등,"178,216","29,973,895","3,266,250,804",109.0
23,201603,서울특별시,전체(시 / 군 / 구),심 야,"17,442","29,557,272","2,244,554,276",75.9
24,201604,서울특별시,전체(시 / 군 / 구),주택용,"2,699,704","1,059,935,552","129,757,553,253",122.4
25,201604,서울특별시,전체(시 / 군 / 구),일반용,"537,717","1,818,748,072","209,550,955,345",115.2
26,201604,서울특별시,전체(시 / 군 / 구),교육용,"2,667","122,810,284","12,003,838,249",97.7
27,201604,서울특별시,전체(시 / 군 / 구),산업용,"45,969","401,799,493","41,147,210,825",102.4
28,201604,서울특별시,전체(시 / 군 / 구),농사용,"1,943","1,346,054","65,684,857",48.8
29,201604,서울특별시,전체(시 / 군 / 구),가로등,"178,579","28,693,794","3,270,273,661",114.0
30,201604,서울특별시,전체(시 / 군 / 구),심 야,"17,361","24,593,692","1,712,940,830",69.6
31,201605,서울특별시,전체(시 / 군 / 구),주택용,"2,701,827","997,002,150","117,133,613,476",117.5
32,201605,서울특별시,전체(시 / 군 / 구),일반용,"537,443","1,790,739,826","207,580,479,916",115.9
33,201605,서울특별시,전체(시 / 군 / 구),교육용,"2,661","105,865,022","10,951,760,892",103.5
34,201605,서울특별시,전체(시 / 군 / 구),산업용,"46,051","384,312,061","40,333,513,149",104.9
35,201605,서울특별시,전체(시 / 군 / 구),농사용,"1,949","1,255,178","61,823,258",49.3
36,201605,서울특별시,전체(시 / 군 / 구),가로등,"178,377","26,678,065","3,131,149,479",117.4
37,201605,서울특별시,전체(시 / 군 / 구),심 야,"17,255","34,970,261","2,563,982,921",73.3
38,201606,서울특별시,전체(시 / 군 / 구),주택용,"2,704,798","1,046,090,879","130,375,499,294",124.6
39,201606,서울특별시,전체(시 / 군 / 구),일반용,"537,893","2,052,987,168","274,819,308,474",133.9
40,201606,서울특별시,전체(시 / 군 / 구),교육용,"2,659","129,361,344","15,252,479,676",117.9
41,201606,서울특별시,전체(시 / 군 / 구),산업용,"46,073","408,942,245","49,452,086,816",120.9
42,201606,서울특별시,전체(시 / 군 / 구),농사용,"1,970","1,293,952","65,092,665",50.3
43,201606,서울특별시,전체(시 / 군 / 구),가로등,"178,367","24,770,508","3,021,045,953",122.0
44,201606,서울특별시,전체(시 / 군 / 구),심 야,"17,151","52,227,300","3,732,096,444",71.5
45,합계,합계,합계,합계,"20,886,949","22,571,018,826","2,786,931,534,759",123.5

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_2360\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)        사용량(kWh)
4   201601  서울특별시  일반용  536,845   2,300,587,864
11  201602  서울특별시  일반용  537,530   2,301,067,005
18  201603  서울특별시  일반용  537,609   2,024,712,345
25  201604  서울특별시  일반용  537,717   1,818,748,072
32  201605  서울특별시  일반용  537,443   1,790,739,826
39  201606  서울특별시  일반용  537,893   2,052,987,168

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201601  서울특별시  강남구  일반용  49,337   313,404,661
252   201602  서울특별시  강남구  일반용  49,418   315,336,662
451   201603  서울특별시  강남구  일반용  49,494   275,556,961
650   201604  서울특별시  강남구  일반용  49,517   240,222,241
849   201605  서울특별시  강남구  일반용  49,521   234,252,613
...      ...    ...  ...  ...      ...           ...
443   201602  서울특별시  중랑구  일반용  19,352    44,543,987
642   201603  서울특별시  중랑구  일반용  19,364    38,211,666
841   201604  서울특별시  중랑구  일반용  19,391    34,134,617
1040  201605  서울특별시  중랑구  일반용  19,397    32,225,028
1239  201606  서울특별시  중랑구  일반용  19,410    37,304,806

[150 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'서울특별시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강남구',
 '강동구',
 '강북구',
 '강서구',
 '관악구',
 '광진구',
 '구로구',
 '금천구',
 '노원구',
 '도봉구',
 '동대문구',
 '동작구',
 '마포구',
 '서대문구',
 '서초구',
 '성동구',
 '성북구',
 '송파구',
 '양천구',
 '영등포구',
 '용산구',
 '은평구',
 '종로구',
 '중구',
 '중랑구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55    201601  서울특별시  강남구   합계  199,399   433,534,544
254   201602  서울특별시  강남구   합계  199,069   428,904,621
453   201603  서울특별시  강남구   합계  198,941   381,438,627
652   201604  서울특별시  강남구   합계  198,832   338,658,257
851   201605  서울특별시  강남구   합계  198,395   325,236,772
...      ...    ...  ...  ...       ...           ...
445   201602  서울특별시  중랑구   합계  160,800   103,502,307
644   201603  서울특별시  중랑구   합계  161,209    90,270,295
843   201604  서울특별시  중랑구   합계  161,581    84,458,785
1042  201605  서울특별시  중랑구   합계  162,045    78,406,987
1241  201606  서울특별시  중랑구   합계  162,596    85,784,989

[150 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[433534544, 428904621, 381438627, 338658257, 325236772, 375514428]
[136466398, 138214862, 122636810, 114219154, 108747309, 120376844]
[83326405, 86309024, 74744275, 70384496, 65082992, 70797938]
[186187554, 190384771, 168635267, 158644969, 149238714, 162517881]
[150175660, 156260051, 135941792, 129527679, 119237860, 130717294]
[144129495, 144634826, 127063404, 119680830, 116976075, 132572766]
[177447694, 176196540, 154687029, 142846753, 139762286, 148737968]
[149176259, 143371428, 131139986, 119247713, 117598564, 130228815]
[138369208, 140726764, 123465827, 116178092, 108841266, 119046943]
[82043187, 84392477, 73451885, 69997505, 64668951, 70404518]
[130374348, 133962836, 117191208, 108450587, 101654634, 113498466]
[112439240, 113322935, 100674138, 95297812, 91773969, 101760583]
[181583594, 179760378, 163516569, 150898153, 149358661, 166818653]
[110708181, 109566571, 98900699, 91593832, 90370772, 100211393]
[311922091, 316806389, 283210319, 260946339, 253136921, 286037872]
[169372143, 168845981, 156037093, 145254369, 139011456, 151920521]
[132112830, 135603569, 119577629, 111355565, 103956298, 114701759]
[230420948, 231493642, 214415283, 202652622, 199745375, 211902378]
[136487465, 140591698, 126004814, 121382503, 114511055, 122030442]
[232101889, 229195379, 208703868, 192383474, 194150236, 218306626]
[123272255, 125496005, 109418228, 100635889, 96988225, 112610864]
[119180264, 123409083, 108326218, 102597704, 95807235, 102953630]
[159629210, 159209213, 142049402, 128343612, 126840036, 146704529]
[221014435, 214756105, 198408179, 182290247, 189719914, 219515296]
[100294330, 103502307, 90270295, 84458785, 78406987, 85784989]
서울특별시 지역별 합계 :  [2283287249, 740661377, 450645130, 1015609156, 821860336, 785057396, 939678270, 790762765, 746628100, 444958523, 705132079, 615268677, 991936008, 601351448, 1712059931, 930441563, 717307650, 1290630248, 761007977, 1274841472, 668421466, 652274134, 862776002, 1225704176, 542717693]
서울특별시 고객호수 평균:  [33136, 21270, 22126, 32618, 40554, 26627, 21144, 15617, 18017, 16050, 24367, 25489, 24934, 19697, 20956, 15844, 25122, 28778, 20940, 22637, 17461, 31863, 15285, 12741, 26908]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201601  서울특별시  강남구   합계  199,399   433,534,544
1           201602  서울특별시  강남구   합계  199,069   428,904,621
2           201603  서울특별시  강남구   합계  198,941   381,438,627
3           201604  서울특별시  강남구   합계  198,832   338,658,257
4           201605  서울특별시  강남구   합계  198,395   325,236,772
..             ...    ...  ...  ...       ...           ...
170  201601-201606  서울특별시  용산구   합계     17461     668421466
171  201601-201606  서울특별시  은평구   합계     31863     652274134
172  201601-201606  서울특별시  종로구   합계     15285     862776002
173  201601-201606  서울특별시   중구   합계     12741    1225704176
174  201601-201606  서울특별시  중랑구   합계     26908     542717693

[175 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201601-201606']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201601-201606  서울특별시   강남구   합계   33136  2283287249
151  201601-201606  서울특별시   강동구   합계   21270   740661377
152  201601-201606  서울특별시   강북구   합계   22126   450645130
153  201601-201606  서울특별시   강서구   합계   32618  1015609156
154  201601-201606  서울특별시   관악구   합계   40554   821860336
155  201601-201606  서울특별시   광진구   합계   26627   785057396
156  201601-201606  서울특별시   구로구   합계   21144   939678270
157  201601-201606  서울특별시   금천구   합계   15617   790762765
158  201601-201606  서울특별시   노원구   합계   18017   746628100
159  201601-201606  서울특별시   도봉구   합계   16050   444958523
160  201601-201606  서울특별시  동대문구   합계   24367   705132079
161  201601-201606  서울특별시   동작구   합계   25489   615268677
162  201601-201606  서울특별시   마포구   합계   24934   991936008
163  201601-201606  서울특별시  서대문구   합계   19697   601351448
164  201601-201606  서울특별시   서초구   합계   20956  1712059931
165  201601-201606  서울특별시   성동구   합계   15844   930441563
166  201601-201606  서울특별시   성북구   합계   25122   717307650
167  201601-201606  서울특별시   송파구   합계   28778  1290630248
168  201601-201606  서울특별시   양천구   합계   20940   761007977
169  201601-201606  서울특별시  영등포구   합계   22637  1274841472
170  201601-201606  서울특별시   용산구   합계   17461   668421466
171  201601-201606  서울특별시   은평구   합계   31863   652274134
172  201601-201606  서울특별시   종로구   합계   15285   862776002
173  201601-201606  서울특별시    중구   합계   12741  1225704176
174  201601-201606  서울특별시   중랑구   합계   26908   542717693

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201601  서울특별시  강남구  일반용  49,337   313,404,661
252   201602  서울특별시  강남구  일반용  49,418   315,336,662
451   201603  서울특별시  강남구  일반용  49,494   275,556,961
650   201604  서울특별시  강남구  일반용  49,517   240,222,241
849   201605  서울특별시  강남구  일반용  49,521   234,252,613
...      ...    ...  ...  ...      ...           ...
443   201602  서울특별시  중랑구  일반용  19,352    44,543,987
642   201603  서울특별시  중랑구  일반용  19,364    38,211,666
841   201604  서울특별시  중랑구  일반용  19,391    34,134,617
1040  201605  서울특별시  중랑구  일반용  19,397    32,225,028
1239  201606  서울특별시  중랑구  일반용  19,410    37,304,806

[150 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[313404661, 315336662, 275556961, 240222241, 234252613, 277024369]
[66829333, 68059310, 58451991, 51950578, 49642891, 58174582]
[38676711, 40208704, 33947533, 30651512, 28800511, 33135702]
[90933401, 93578369, 80313376, 71994917, 68037513, 78578097]
[67756640, 69695308, 60520404, 56206672, 53396201, 61114973]
[59150797, 59648436, 50973244, 46220632, 45287779, 53280487]
[84072482, 80767600, 70474524, 62510151, 63316744, 68135632]
[91192611, 85122021, 78015579, 69138234, 70818981, 79793518]
[56268082, 57847340, 49223120, 44235289, 42623732, 49430823]
[32478691, 33783450, 28594184, 25690116, 24140546, 27962187]
[60971229, 63455444, 54324448, 48390455, 45665573, 53524957]
[53272863, 53556799, 46881984, 42958497, 42499131, 49228239]
[110365759, 108841730, 98953810, 88618532, 87989968, 98697550]
[51866056, 51814670, 45815691, 41568310, 41290743, 47576851]
[192855728, 195564266, 173795203, 154925943, 149947215, 173401096]
[76008572, 72076907, 54964180, 48537952, 46732417, 53751682]
[50056731, 52156539, 44772785, 40251951, 37829815, 43695885]
[130033042, 129986047, 118670642, 112113488, 113685488, 120577739]
[71650896, 74823113, 66946869, 62945671, 60176864, 65385280]
[153677261, 149693493, 136473755, 122796322, 125278028, 143253817]
[71581562, 72773610, 62612582, 55682397, 54577676, 65511409]
[44915153, 47085596, 39800399, 35884713, 33488752, 38342091]
[115806679, 114135050, 101740167, 90477934, 90986397, 105463263]
[173594469, 166512554, 154677248, 140640948, 148049220, 170642133]
[43168455, 44543987, 38211666, 34134617, 32225028, 37304806]
서울특별시 지역별 일반용 합계 :  [1655797507, 353108685, 205420673, 483435673, 368690198, 314561375, 429277133, 474080944, 299628386, 172649174, 326332106, 288397513, 593467349, 279932321, 1040489451, 352071710, 268763706, 725066446, 401928693, 831172676, 382739236, 239516704, 618609490, 954116572, 229588559]
서울특별시 고객호수 평균:  [49475, 19755, 15957, 22912, 24711, 20536, 17769, 13006, 14847, 12026, 24291, 16601, 27811, 16153, 30021, 15459, 21054, 28304, 16671, 24186, 16530, 20365, 25128, 24554, 19374]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2360\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
0           201601  서울특별시  강남구  일반용  49,337   313,404,661
1           201602  서울특별시  강남구  일반용  49,418   315,336,662
2           201603  서울특별시  강남구  일반용  49,494   275,556,961
3           201604  서울특별시  강남구  일반용  49,517   240,222,241
4           201605  서울특별시  강남구  일반용  49,521   234,252,613
..             ...    ...  ...  ...      ...           ...
170  201601-201606  서울특별시  용산구  일반용    16530     382739236
171  201601-201606  서울특별시  은평구  일반용    20365     239516704
172  201601-201606  서울특별시  종로구  일반용    25128     618609490
173  201601-201606  서울특별시   중구  일반용    24554     954116572
174  201601-201606  서울특별시  중랑구  일반용    19374     229588559

[175 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201601-201606']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201601-201606  서울특별시   강남구  일반용   49475  1655797507
151  201601-201606  서울특별시   강동구  일반용   19755   353108685
152  201601-201606  서울특별시   강북구  일반용   15957   205420673
153  201601-201606  서울특별시   강서구  일반용   22912   483435673
154  201601-201606  서울특별시   관악구  일반용   24711   368690198
155  201601-201606  서울특별시   광진구  일반용   20536   314561375
156  201601-201606  서울특별시   구로구  일반용   17769   429277133
157  201601-201606  서울특별시   금천구  일반용   13006   474080944
158  201601-201606  서울특별시   노원구  일반용   14847   299628386
159  201601-201606  서울특별시   도봉구  일반용   12026   172649174
160  201601-201606  서울특별시  동대문구  일반용   24291   326332106
161  201601-201606  서울특별시   동작구  일반용   16601   288397513
162  201601-201606  서울특별시   마포구  일반용   27811   593467349
163  201601-201606  서울특별시  서대문구  일반용   16153   279932321
164  201601-201606  서울특별시   서초구  일반용   30021  1040489451
165  201601-201606  서울특별시   성동구  일반용   15459   352071710
166  201601-201606  서울특별시   성북구  일반용   21054   268763706
167  201601-201606  서울특별시   송파구  일반용   28304   725066446
168  201601-201606  서울특별시   양천구  일반용   16671   401928693
169  201601-201606  서울특별시  영등포구  일반용   24186   831172676
170  201601-201606  서울특별시   용산구  일반용   16530   382739236
171  201601-201606  서울특별시   은평구  일반용   20365   239516704
172  201601-201606  서울특별시   종로구  일반용   25128   618609490
173  201601-201606  서울특별시    중구  일반용   24554   954116572
174  201601-201606  서울특별시   중랑구  일반용   19374   229588559

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201601-201606  서울특별시   강남구  일반용   49475  1655797507
150  201601-201606  서울특별시   강남구   합계   33136  2283287249
151  201601-201606  서울특별시   강동구   합계   21270   740661377
151  201601-201606  서울특별시   강동구  일반용   19755   353108685
152  201601-201606  서울특별시   강북구  일반용   15957   205420673
152  201601-201606  서울특별시   강북구   합계   22126   450645130
153  201601-201606  서울특별시   강서구  일반용   22912   483435673
153  201601-201606  서울특별시   강서구   합계   32618  1015609156
154  201601-201606  서울특별시   관악구  일반용   24711   368690198
154  201601-201606  서울특별시   관악구   합계   40554   821860336
155  201601-201606  서울특별시   광진구  일반용   20536   314561375
155  201601-201606  서울특별시   광진구   합계   26627   785057396
156  201601-201606  서울특별시   구로구  일반용   17769   429277133
156  201601-201606  서울특별시   구로구   합계   21144   939678270
157  201601-201606  서울특별시   금천구  일반용   13006   474080944
157  201601-201606  서울특별시   금천구   합계   15617   790762765
158  201601-201606  서울특별시   노원구   합계   18017   746628100
158  201601-201606  서울특별시   노원구  일반용   14847   299628386
159  201601-201606  서울특별시   도봉구   합계   16050   444958523
159  201601-201606  서울특별시   도봉구  일반용   12026   172649174
160  201601-201606  서울특별시  동대문구   합계   24367   705132079
160  201601-201606  서울특별시  동대문구  일반용   24291   326332106
161  201601-201606  서울특별시   동작구   합계   25489   615268677
161  201601-201606  서울특별시   동작구  일반용   16601   288397513
162  201601-201606  서울특별시   마포구   합계   24934   991936008
162  201601-201606  서울특별시   마포구  일반용   27811   593467349
163  201601-201606  서울특별시  서대문구   합계   19697   601351448
163  201601-201606  서울특별시  서대문구  일반용   16153   279932321
164  201601-201606  서울특별시   서초구  일반용   30021  1040489451
164  201601-201606  서울특별시   서초구   합계   20956  1712059931
165  201601-201606  서울특별시   성동구   합계   15844   930441563
165  201601-201606  서울특별시   성동구  일반용   15459   352071710
166  201601-201606  서울특별시   성북구   합계   25122   717307650
166  201601-201606  서울특별시   성북구  일반용   21054   268763706
167  201601-201606  서울특별시   송파구   합계   28778  1290630248
167  201601-201606  서울특별시   송파구  일반용   28304   725066446
168  201601-201606  서울특별시   양천구   합계   20940   761007977
168  201601-201606  서울특별시   양천구  일반용   16671   401928693
169  201601-201606  서울특별시  영등포구  일반용   24186   831172676
169  201601-201606  서울특별시  영등포구   합계   22637  1274841472
170  201601-201606  서울특별시   용산구   합계   17461   668421466
170  201601-201606  서울특별시   용산구  일반용   16530   382739236
171  201601-201606  서울특별시   은평구   합계   31863   652274134
171  201601-201606  서울특별시   은평구  일반용   20365   239516704
172  201601-201606  서울특별시   종로구   합계   15285   862776002
172  201601-201606  서울특별시   종로구  일반용   25128   618609490
173  201601-201606  서울특별시    중구   합계   12741  1225704176
173  201601-201606  서울특별시    중구  일반용   24554   954116572
174  201601-201606  서울특별시   중랑구  일반용   19374   229588559
174  201601-201606  서울특별시   중랑구   합계   26908   542717693

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[1655797507,
 353108685,
 205420673,
 483435673,
 368690198,
 314561375,
 429277133,
 474080944,
 299628386,
 172649174,
 326332106,
 288397513,
 593467349,
 279932321,
 1040489451,
 352071710,
 268763706,
 725066446,
 401928693,
 831172676,
 382739236,
 239516704,
 618609490,
 954116572,
 229588559]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[2283287249,
 740661377,
 450645130,
 1015609156,
 821860336,
 785057396,
 939678270,
 790762765,
 746628100,
 444958523,
 705132079,
 615268677,
 991936008,
 601351448,
 1712059931,
 930441563,
 717307650,
 1290630248,
 761007977,
 1274841472,
 668421466,
 652274134,
 862776002,
 1225704176,
 542717693]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[72.52, 47.67, 45.58, 47.6, 44.86, 40.07, 45.68, 59.95, 40.13, 38.8, 46.28, 46.87, 59.83, 46.55, 60.77, 37.84, 37.47, 56.18, 52.82, 65.2, 57.26, 36.72, 71.7, 77.84, 42.3]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    73
1    48
2    46
3    48
4    45
5    40
6    46
7    60
8    40
9    39
10   46
11   47
12   60
13   47
14   61
15   38
16   37
17   56
18   53
19   65
20   57
21   37
22   72
23   78
24   42
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강남구  일반용  73
1    강동구  일반용  48
2    강북구  일반용  46
3    강서구  일반용  48
4    관악구  일반용  45
5    광진구  일반용  40
6    구로구  일반용  46
7    금천구  일반용  60
8    노원구  일반용  40
9    도봉구  일반용  39
10  동대문구  일반용  46
11   동작구  일반용  47
12   마포구  일반용  60
13  서대문구  일반용  47
14   서초구  일반용  61
15   성동구  일반용  38
16   성북구  일반용  37
17   송파구  일반용  56
18   양천구  일반용  53
19  영등포구  일반용  65
20   용산구  일반용  57
21   은평구  일반용  37
22   종로구  일반용  72
23    중구  일반용  78
24   중랑구  일반용  42

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201601-201606  서울특별시   강남구  일반용   49475  1655797507  73
1   201601-201606  서울특별시   강남구   합계   33136  2283287249 NaN
3   201601-201606  서울특별시   강동구  일반용   19755   353108685  48
2   201601-201606  서울특별시   강동구   합계   21270   740661377 NaN
4   201601-201606  서울특별시   강북구  일반용   15957   205420673  46
5   201601-201606  서울특별시   강북구   합계   22126   450645130 NaN
6   201601-201606  서울특별시   강서구  일반용   22912   483435673  48
7   201601-201606  서울특별시   강서구   합계   32618  1015609156 NaN
8   201601-201606  서울특별시   관악구  일반용   24711   368690198  45
9   201601-201606  서울특별시   관악구   합계   40554   821860336 NaN
10  201601-201606  서울특별시   광진구  일반용   20536   314561375  40
11  201601-201606  서울특별시   광진구   합계   26627   785057396 NaN
12  201601-201606  서울특별시   구로구  일반용   17769   429277133  46
13  201601-201606  서울특별시   구로구   합계   21144   939678270 NaN
14  201601-201606  서울특별시   금천구  일반용   13006   474080944  60
15  201601-201606  서울특별시   금천구   합계   15617   790762765 NaN
17  201601-201606  서울특별시   노원구  일반용   14847   299628386  40
16  201601-201606  서울특별시   노원구   합계   18017   746628100 NaN
19  201601-201606  서울특별시   도봉구  일반용   12026   172649174  39
18  201601-201606  서울특별시   도봉구   합계   16050   444958523 NaN
21  201601-201606  서울특별시  동대문구  일반용   24291   326332106  46
20  201601-201606  서울특별시  동대문구   합계   24367   705132079 NaN
23  201601-201606  서울특별시   동작구  일반용   16601   288397513  47
22  201601-201606  서울특별시   동작구   합계   25489   615268677 NaN
25  201601-201606  서울특별시   마포구  일반용   27811   593467349  60
24  201601-201606  서울특별시   마포구   합계   24934   991936008 NaN
27  201601-201606  서울특별시  서대문구  일반용   16153   279932321  47
26  201601-201606  서울특별시  서대문구   합계   19697   601351448 NaN
28  201601-201606  서울특별시   서초구  일반용   30021  1040489451  61
29  201601-201606  서울특별시   서초구   합계   20956  1712059931 NaN
31  201601-201606  서울특별시   성동구  일반용   15459   352071710  38
30  201601-201606  서울특별시   성동구   합계   15844   930441563 NaN
33  201601-201606  서울특별시   성북구  일반용   21054   268763706  37
32  201601-201606  서울특별시   성북구   합계   25122   717307650 NaN
35  201601-201606  서울특별시   송파구  일반용   28304   725066446  56
34  201601-201606  서울특별시   송파구   합계   28778  1290630248 NaN
37  201601-201606  서울특별시   양천구  일반용   16671   401928693  53
36  201601-201606  서울특별시   양천구   합계   20940   761007977 NaN
38  201601-201606  서울특별시  영등포구  일반용   24186   831172676  65
39  201601-201606  서울특별시  영등포구   합계   22637  1274841472 NaN
41  201601-201606  서울특별시   용산구  일반용   16530   382739236  57
40  201601-201606  서울특별시   용산구   합계   17461   668421466 NaN
43  201601-201606  서울특별시   은평구  일반용   20365   239516704  37
42  201601-201606  서울특별시   은평구   합계   31863   652274134 NaN
45  201601-201606  서울특별시   종로구  일반용   25128   618609490  72
44  201601-201606  서울특별시   종로구   합계   15285   862776002 NaN
47  201601-201606  서울특별시    중구  일반용   24554   954116572  78
46  201601-201606  서울특별시    중구   합계   12741  1225704176 NaN
48  201601-201606  서울특별시   중랑구  일반용   19374   229588559  42
49  201601-201606  서울특별시   중랑구   합계   26908   542717693 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1601-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)