In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_16하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2016년 07 월 ~ 2016년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,경상남도,전체(시 / 군 / 구),주택용,"1,124,581","352,419,676","42,660,666,353",121.1
4,201607,경상남도,전체(시 / 군 / 구),일반용,"216,417","531,112,796","79,329,629,426",149.4
...,...,...,...,...,...,...,...,...
907,201612,경상남도,합천군,산업용,984,"6,334,834","820,087,988",129.5
908,201612,경상남도,합천군,심 야,"2,201","4,197,131","315,580,015",75.2
909,201612,경상남도,합천군,일반용,"3,925","6,735,091","940,549,203",139.6
910,201612,경상남도,합천군,주택용,"28,118","4,635,274","553,914,433",119.5
911,201612,경상남도,합천군,합계,"51,758","35,086,537","3,357,285,675",95.7

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,경상남도,전체(시 / 군 / 구),주택용,"1,124,581","352,419,676","42,660,666,353",121.1
4,201607,경상남도,전체(시 / 군 / 구),일반용,"216,417","531,112,796","79,329,629,426",149.4
5,201607,경상남도,전체(시 / 군 / 구),교육용,"1,641","35,228,544","4,600,302,961",130.6
6,201607,경상남도,전체(시 / 군 / 구),산업용,"36,823","1,710,234,652","217,020,473,240",126.9
...,...,...,...,...,...,...,...,...
907,201612,경상남도,합천군,산업용,984,"6,334,834","820,087,988",129.5
908,201612,경상남도,합천군,심 야,"2,201","4,197,131","315,580,015",75.2
909,201612,경상남도,합천군,일반용,"3,925","6,735,091","940,549,203",139.6
910,201612,경상남도,합천군,주택용,"28,118","4,635,274","553,914,433",119.5
911,201612,경상남도,합천군,합계,"51,758","35,086,537","3,357,285,675",95.7

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,경상남도,전체(시 / 군 / 구),주택용,"1,124,581","352,419,676","42,660,666,353",121.1
4,201607,경상남도,전체(시 / 군 / 구),일반용,"216,417","531,112,796","79,329,629,426",149.4
5,201607,경상남도,전체(시 / 군 / 구),교육용,"1,641","35,228,544","4,600,302,961",130.6
6,201607,경상남도,전체(시 / 군 / 구),산업용,"36,823","1,710,234,652","217,020,473,240",126.9
7,201607,경상남도,전체(시 / 군 / 구),농사용,"182,557","119,618,180","6,047,104,655",50.6
...,...,...,...,...,...,...,...,...
907,201612,경상남도,합천군,산업용,984,"6,334,834","820,087,988",129.5
908,201612,경상남도,합천군,심 야,"2,201","4,197,131","315,580,015",75.2
909,201612,경상남도,합천군,일반용,"3,925","6,735,091","940,549,203",139.6
910,201612,경상남도,합천군,주택용,"28,118","4,635,274","553,914,433",119.5
911,201612,경상남도,합천군,합계,"51,758","35,086,537","3,357,285,675",95.7

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,경상남도,전체(시 / 군 / 구),주택용,"1,124,581","352,419,676","42,660,666,353",121.1
4,201607,경상남도,전체(시 / 군 / 구),일반용,"216,417","531,112,796","79,329,629,426",149.4
5,201607,경상남도,전체(시 / 군 / 구),교육용,"1,641","35,228,544","4,600,302,961",130.6
6,201607,경상남도,전체(시 / 군 / 구),산업용,"36,823","1,710,234,652","217,020,473,240",126.9
7,201607,경상남도,전체(시 / 군 / 구),농사용,"182,557","119,618,180","6,047,104,655",50.6
8,201607,경상남도,전체(시 / 군 / 구),가로등,"154,091","19,679,425","2,460,077,310",125.0
9,201607,경상남도,전체(시 / 군 / 구),심 야,"94,159","30,733,222","1,750,978,332",57.0
10,201608,경상남도,전체(시 / 군 / 구),주택용,"1,125,968","453,012,595","68,613,948,442",151.5
11,201608,경상남도,전체(시 / 군 / 구),일반용,"217,270","635,327,689","90,853,490,074",143.0
12,201608,경상남도,전체(시 / 군 / 구),교육용,"1,642","33,743,226","4,527,851,073",134.2
13,201608,경상남도,전체(시 / 군 / 구),산업용,"36,840","1,587,506,780","206,745,096,233",130.2
14,201608,경상남도,전체(시 / 군 / 구),농사용,"183,860","157,583,784","7,605,365,632",48.3
15,201608,경상남도,전체(시 / 군 / 구),가로등,"154,850","20,787,620","2,499,267,361",120.2
16,201608,경상남도,전체(시 / 군 / 구),심 야,"93,912","24,551,785","1,436,076,953",58.5
17,201609,경상남도,전체(시 / 군 / 구),주택용,"1,128,015","391,969,580","28,384,128,354",72.4
18,201609,경상남도,전체(시 / 군 / 구),일반용,"217,719","559,481,480","72,842,789,358",130.2
19,201609,경상남도,전체(시 / 군 / 구),교육용,"1,641","33,577,959","4,012,208,631",119.5
20,201609,경상남도,전체(시 / 군 / 구),산업용,"36,902","1,572,820,881","170,821,850,913",108.6
21,201609,경상남도,전체(시 / 군 / 구),농사용,"184,700","141,247,228","6,926,072,402",49.0
22,201609,경상남도,전체(시 / 군 / 구),가로등,"155,046","21,677,034","2,544,570,432",117.4
23,201609,경상남도,전체(시 / 군 / 구),심 야,"93,688","24,639,313","1,421,805,763",57.7
24,201610,경상남도,전체(시 / 군 / 구),주택용,"1,129,525","332,397,152","34,825,390,109",104.8
25,201610,경상남도,전체(시 / 군 / 구),일반용,"217,794","458,000,994","54,530,454,569",119.1
26,201610,경상남도,전체(시 / 군 / 구),교육용,"1,642","27,619,747","3,166,211,388",114.6
27,201610,경상남도,전체(시 / 군 / 구),산업용,"36,969","1,605,066,405","164,628,541,691",102.6
28,201610,경상남도,전체(시 / 군 / 구),농사용,"185,378","110,638,464","5,814,982,761",52.6
29,201610,경상남도,전체(시 / 군 / 구),가로등,"155,364","22,885,911","2,569,123,092",112.3
30,201610,경상남도,전체(시 / 군 / 구),심 야,"93,580","37,151,943","2,077,497,924",55.9
31,201611,경상남도,전체(시 / 군 / 구),주택용,"1,131,605","350,403,198","41,380,124,590",118.1
32,201611,경상남도,전체(시 / 군 / 구),일반용,"218,382","465,994,950","61,871,461,124",132.8
33,201611,경상남도,전체(시 / 군 / 구),교육용,"1,642","33,891,784","4,093,116,814",120.8
34,201611,경상남도,전체(시 / 군 / 구),산업용,"37,036","1,653,009,704","203,658,459,031",123.2
35,201611,경상남도,전체(시 / 군 / 구),농사용,"211,351","160,772,011","8,128,349,611",50.6
36,201611,경상남도,전체(시 / 군 / 구),가로등,"155,838","24,474,040","2,672,613,422",109.2
37,201611,경상남도,전체(시 / 군 / 구),심 야,"93,451","79,351,751","5,099,729,942",64.3
38,201612,경상남도,전체(시 / 군 / 구),주택용,"1,133,686","363,437,978","42,335,753,156",116.5
39,201612,경상남도,전체(시 / 군 / 구),일반용,"219,002","525,804,546","73,972,416,964",140.7
40,201612,경상남도,전체(시 / 군 / 구),교육용,"1,644","42,879,140","4,821,166,656",112.4
41,201612,경상남도,전체(시 / 군 / 구),산업용,"37,061","1,720,657,960","216,153,091,054",125.6
42,201612,경상남도,전체(시 / 군 / 구),농사용,"187,872","243,097,418","11,743,314,740",48.3
43,201612,경상남도,전체(시 / 군 / 구),가로등,"156,234","25,195,423","2,668,394,997",105.9
44,201612,경상남도,전체(시 / 군 / 구),심 야,"93,315","126,513,142","9,540,577,038",75.4
45,합계,합계,합계,합계,"10,940,693","16,866,197,110","1,978,854,524,571",117.3

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_16248\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201607  경상남도  일반용  216,417   531,112,796
11  201608  경상남도  일반용  217,270   635,327,689
18  201609  경상남도  일반용  217,719   559,481,480
25  201610  경상남도  일반용  217,794   458,000,994
32  201611  경상남도  일반용  218,382   465,994,950
39  201612  경상남도  일반용  219,002   525,804,546

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201607  경상남도  거제시  일반용  17,646   42,676,233
197  201608  경상남도  거제시  일반용  17,761   51,773,022
341  201609  경상남도  거제시  일반용  17,775   44,979,083
485  201610  경상남도  거제시  일반용  17,761   36,721,932
629  201611  경상남도  거제시  일반용  17,792   37,008,029
..      ...   ...  ...  ...      ...          ...
333  201608  경상남도  합천군  일반용   3,879    7,010,740
477  201609  경상남도  합천군  일반용   3,891    6,335,374
621  201610  경상남도  합천군  일반용   3,903    5,331,866
765  201611  경상남도  합천군  일반용   3,913    5,825,104
909  201612  경상남도  합천군  일반용   3,925    6,735,091

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201607  경상남도  거제시   합계  121,863   203,455,757
199  201608  경상남도  거제시   합계  122,189   216,883,222
343  201609  경상남도  거제시   합계  122,362   197,595,602
487  201610  경상남도  거제시   합계  122,425   177,630,574
631  201611  경상남도  거제시   합계  123,969   184,338,717
..      ...   ...  ...  ...       ...           ...
335  201608  경상남도  합천군   합계   51,659    30,757,082
479  201609  경상남도  합천군   합계   51,800    28,976,754
623  201610  경상남도  합천군   합계   51,887    24,874,527
767  201611  경상남도  합천군   합계   53,944    30,706,028
911  201612  경상남도  합천군   합계   51,758    35,086,537

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[203455757, 216883222, 197595602, 177630574, 184338717, 197914598]
[32564329, 36436726, 34740040, 31754080, 35894362, 39344786]
[37908447, 43127620, 40542030, 39463505, 47413977, 51043046]
[422240970, 438104011, 420856886, 392246325, 430327495, 461940725]
[19731980, 25334971, 22319037, 19054891, 22081657, 22443782]
[76417987, 82208244, 78450899, 72588793, 86750332, 116091143]
[107163499, 112692249, 103909852, 99992041, 104100473, 111856009]
[20883066, 25419611, 24204175, 21119207, 26528911, 28843712]
[301003976, 307648980, 286175754, 276416979, 292563623, 308829300]
[30598336, 32856706, 30869306, 29419395, 32707370, 36589524]
[183719645, 204173601, 190219138, 171638695, 194972496, 239596742]
[74492760, 78291197, 72942382, 67125529, 75777013, 90287587]
[910473210, 918109736, 868110117, 841015938, 871888362, 943310788]
[100048522, 108372066, 98531084, 87552681, 88660779, 95031366]
[21820097, 25977214, 24850617, 23375581, 29315727, 31805483]
[212205456, 204427741, 200899637, 200012851, 192067323, 214478315]
[18054862, 21692502, 21220165, 18479024, 21802793, 23092164]
[26243596, 30757082, 28976754, 24874527, 30706028, 35086537]
경상남도 지역별 합계 :  [1177818470, 210734323, 259498625, 2565716412, 130966318, 512507398, 639714123, 146998682, 1772638612, 193040637, 1184320317, 458916468, 5352908151, 578196498, 157144719, 1224091323, 124341510, 176644524]
경상남도 고객호수 평균:  [20436, 9246, 8771, 32736, 8213, 16371, 12455, 6939, 19069, 5696, 31313, 10041, 75849, 13431, 8906, 8875, 6871, 8680]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201607  경상남도  거제시   합계  121,863   203,455,757
1           201608  경상남도  거제시   합계  122,189   216,883,222
2           201609  경상남도  거제시   합계  122,362   197,595,602
3           201610  경상남도  거제시   합계  122,425   177,630,574
4           201611  경상남도  거제시   합계  123,969   184,338,717
..             ...   ...  ...  ...       ...           ...
121  201607-201612  경상남도  통영시   합계     13431     578196498
122  201607-201612  경상남도  하동군   합계      8906     157144719
123  201607-201612  경상남도  함안군   합계      8875    1224091323
124  201607-201612  경상남도  함양군   합계      6871     124341510
125  201607-201612  경상남도  합천군   합계      8680     176644524

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201607-201612']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201607-201612  경상남도  거제시   합계   20436  1177818470
109  201607-201612  경상남도  거창군   합계    9246   210734323
110  201607-201612  경상남도  고성군   합계    8771   259498625
111  201607-201612  경상남도  김해시   합계   32736  2565716412
112  201607-201612  경상남도  남해군   합계    8213   130966318
113  201607-201612  경상남도  밀양시   합계   16371   512507398
114  201607-201612  경상남도  사천시   합계   12455   639714123
115  201607-201612  경상남도  산청군   합계    6939   146998682
116  201607-201612  경상남도  양산시   합계   19069  1772638612
117  201607-201612  경상남도  의령군   합계    5696   193040637
118  201607-201612  경상남도  진주시   합계   31313  1184320317
119  201607-201612  경상남도  창녕군   합계   10041   458916468
120  201607-201612  경상남도  창원시   합계   75849  5352908151
121  201607-201612  경상남도  통영시   합계   13431   578196498
122  201607-201612  경상남도  하동군   합계    8906   157144719
123  201607-201612  경상남도  함안군   합계    8875  1224091323
124  201607-201612  경상남도  함양군   합계    6871   124341510
125  201607-201612  경상남도  합천군   합계    8680   176644524

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201607  경상남도  거제시  일반용  17,646   42,676,233
197  201608  경상남도  거제시  일반용  17,761   51,773,022
341  201609  경상남도  거제시  일반용  17,775   44,979,083
485  201610  경상남도  거제시  일반용  17,761   36,721,932
629  201611  경상남도  거제시  일반용  17,792   37,008,029
..      ...   ...  ...  ...      ...          ...
333  201608  경상남도  합천군  일반용   3,879    7,010,740
477  201609  경상남도  합천군  일반용   3,891    6,335,374
621  201610  경상남도  합천군  일반용   3,903    5,331,866
765  201611  경상남도  합천군  일반용   3,913    5,825,104
909  201612  경상남도  합천군  일반용   3,925    6,735,091

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[42676233, 51773022, 44979083, 36721932, 37008029, 41080810]
[7661648, 9240935, 8231523, 6877126, 7769067, 9012428]
[7607196, 9451639, 8320450, 6971361, 7601640, 8607881]
[83855325, 99192786, 86291209, 70030815, 70401432, 78891850]
[7351610, 10023699, 8622473, 6716763, 6999119, 7810185]
[14728425, 18136069, 16281759, 13151257, 14158818, 16279377]
[18364529, 22795859, 20338015, 16375405, 17001674, 19304627]
[4972460, 6245485, 5533361, 4612799, 5030842, 5555865]
[47996843, 57002299, 49571689, 41648151, 42736044, 47266680]
[3324701, 4109538, 3835524, 3168765, 3369434, 3969628]
[55472759, 65992015, 59759038, 49262877, 49678083, 56320113]
[10778801, 12855307, 11138359, 9124835, 9732012, 11219419]
[175537895, 205518360, 180023784, 147349117, 146563815, 166099207]
[23915219, 30291723, 27658594, 21964299, 21923753, 24280950]
[6126376, 7711718, 6897397, 5645921, 6086485, 6917672]
[10208523, 12090452, 10395730, 8711549, 9384548, 11153845]
[4728454, 5886043, 5268118, 4336156, 4725051, 5298918]
[5805799, 7010740, 6335374, 5331866, 5825104, 6735091]
경상남도 지역별 일반용 합계 :  [254239109, 48792727, 48560167, 488663417, 47523849, 92735705, 114180109, 31950812, 286221706, 21777590, 336484885, 64848733, 1021092178, 150034538, 39385569, 61944647, 30242740, 37043974]
경상남도 고객호수 평균:  [17762, 4958, 4609, 29159, 4682, 9119, 9306, 3431, 17482, 2454, 24914, 5448, 56397, 10998, 4221, 5272, 3645, 3898]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16248\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201607  경상남도  거제시  일반용  17,646   42,676,233
1           201608  경상남도  거제시  일반용  17,761   51,773,022
2           201609  경상남도  거제시  일반용  17,775   44,979,083
3           201610  경상남도  거제시  일반용  17,761   36,721,932
4           201611  경상남도  거제시  일반용  17,792   37,008,029
..             ...   ...  ...  ...      ...          ...
121  201607-201612  경상남도  통영시  일반용    10998    150034538
122  201607-201612  경상남도  하동군  일반용     4221     39385569
123  201607-201612  경상남도  함안군  일반용     5272     61944647
124  201607-201612  경상남도  함양군  일반용     3645     30242740
125  201607-201612  경상남도  합천군  일반용     3898     37043974

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201607-201612']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201607-201612  경상남도  거제시  일반용   17762   254239109
109  201607-201612  경상남도  거창군  일반용    4958    48792727
110  201607-201612  경상남도  고성군  일반용    4609    48560167
111  201607-201612  경상남도  김해시  일반용   29159   488663417
112  201607-201612  경상남도  남해군  일반용    4682    47523849
113  201607-201612  경상남도  밀양시  일반용    9119    92735705
114  201607-201612  경상남도  사천시  일반용    9306   114180109
115  201607-201612  경상남도  산청군  일반용    3431    31950812
116  201607-201612  경상남도  양산시  일반용   17482   286221706
117  201607-201612  경상남도  의령군  일반용    2454    21777590
118  201607-201612  경상남도  진주시  일반용   24914   336484885
119  201607-201612  경상남도  창녕군  일반용    5448    64848733
120  201607-201612  경상남도  창원시  일반용   56397  1021092178
121  201607-201612  경상남도  통영시  일반용   10998   150034538
122  201607-201612  경상남도  하동군  일반용    4221    39385569
123  201607-201612  경상남도  함안군  일반용    5272    61944647
124  201607-201612  경상남도  함양군  일반용    3645    30242740
125  201607-201612  경상남도  합천군  일반용    3898    37043974

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201607-201612  경상남도  거제시  일반용   17762   254239109
108  201607-201612  경상남도  거제시   합계   20436  1177818470
109  201607-201612  경상남도  거창군  일반용    4958    48792727
109  201607-201612  경상남도  거창군   합계    9246   210734323
110  201607-201612  경상남도  고성군  일반용    4609    48560167
110  201607-201612  경상남도  고성군   합계    8771   259498625
111  201607-201612  경상남도  김해시   합계   32736  2565716412
111  201607-201612  경상남도  김해시  일반용   29159   488663417
112  201607-201612  경상남도  남해군   합계    8213   130966318
112  201607-201612  경상남도  남해군  일반용    4682    47523849
113  201607-201612  경상남도  밀양시  일반용    9119    92735705
113  201607-201612  경상남도  밀양시   합계   16371   512507398
114  201607-201612  경상남도  사천시   합계   12455   639714123
114  201607-201612  경상남도  사천시  일반용    9306   114180109
115  201607-201612  경상남도  산청군  일반용    3431    31950812
115  201607-201612  경상남도  산청군   합계    6939   146998682
116  201607-201612  경상남도  양산시  일반용   17482   286221706
116  201607-201612  경상남도  양산시   합계   19069  1772638612
117  201607-201612  경상남도  의령군  일반용    2454    21777590
117  201607-201612  경상남도  의령군   합계    5696   193040637
118  201607-201612  경상남도  진주시   합계   31313  1184320317
118  201607-201612  경상남도  진주시  일반용   24914   336484885
119  201607-201612  경상남도  창녕군   합계   10041   458916468
119  201607-201612  경상남도  창녕군  일반용    5448    64848733
120  201607-201612  경상남도  창원시  일반용   56397  1021092178
120  201607-201612  경상남도  창원시   합계   75849  5352908151
121  201607-201612  경상남도  통영시   합계   13431   578196498
121  201607-201612  경상남도  통영시  일반용   10998   150034538
122  201607-201612  경상남도  하동군   합계    8906   157144719
122  201607-201612  경상남도  하동군  일반용    4221    39385569
123  201607-201612  경상남도  함안군   합계    8875  1224091323
123  201607-201612  경상남도  함안군  일반용    5272    61944647
124  201607-201612  경상남도  함양군   합계    6871   124341510
124  201607-201612  경상남도  함양군  일반용    3645    30242740
125  201607-201612  경상남도  합천군  일반용    3898    37043974
125  201607-201612  경상남도  합천군   합계    8680   176644524

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[254239109,
 48792727,
 48560167,
 488663417,
 47523849,
 92735705,
 114180109,
 31950812,
 286221706,
 21777590,
 336484885,
 64848733,
 1021092178,
 150034538,
 39385569,
 61944647,
 30242740,
 37043974]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1177818470,
 210734323,
 259498625,
 2565716412,
 130966318,
 512507398,
 639714123,
 146998682,
 1772638612,
 193040637,
 1184320317,
 458916468,
 5352908151,
 578196498,
 157144719,
 1224091323,
 124341510,
 176644524]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[21.59, 23.15, 18.71, 19.05, 36.29, 18.09, 17.85, 21.74, 16.15, 11.28, 28.41, 14.13, 19.08, 25.95, 25.06, 5.06, 24.32, 20.97]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    22
1    23
2    19
3    19
4    36
5    18
6    18
7    22
8    16
9    11
10   28
11   14
12   19
13   26
14   25
15    5
16   24
17   21
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  22
1   거창군  일반용  23
2   고성군  일반용  19
3   김해시  일반용  19
4   남해군  일반용  36
5   밀양시  일반용  18
6   사천시  일반용  18
7   산청군  일반용  22
8   양산시  일반용  16
9   의령군  일반용  11
10  진주시  일반용  28
11  창녕군  일반용  14
12  창원시  일반용  19
13  통영시  일반용  26
14  하동군  일반용  25
15  함안군  일반용   5
16  함양군  일반용  24
17  합천군  일반용  21

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201607-201612  경상남도  거제시  일반용   17762   254239109  22
1   201607-201612  경상남도  거제시   합계   20436  1177818470 NaN
2   201607-201612  경상남도  거창군  일반용    4958    48792727  23
3   201607-201612  경상남도  거창군   합계    9246   210734323 NaN
4   201607-201612  경상남도  고성군  일반용    4609    48560167  19
5   201607-201612  경상남도  고성군   합계    8771   259498625 NaN
7   201607-201612  경상남도  김해시  일반용   29159   488663417  19
6   201607-201612  경상남도  김해시   합계   32736  2565716412 NaN
9   201607-201612  경상남도  남해군  일반용    4682    47523849  36
8   201607-201612  경상남도  남해군   합계    8213   130966318 NaN
10  201607-201612  경상남도  밀양시  일반용    9119    92735705  18
11  201607-201612  경상남도  밀양시   합계   16371   512507398 NaN
13  201607-201612  경상남도  사천시  일반용    9306   114180109  18
12  201607-201612  경상남도  사천시   합계   12455   639714123 NaN
14  201607-201612  경상남도  산청군  일반용    3431    31950812  22
15  201607-201612  경상남도  산청군   합계    6939   146998682 NaN
16  201607-201612  경상남도  양산시  일반용   17482   286221706  16
17  201607-201612  경상남도  양산시   합계   19069  1772638612 NaN
18  201607-201612  경상남도  의령군  일반용    2454    21777590  11
19  201607-201612  경상남도  의령군   합계    5696   193040637 NaN
21  201607-201612  경상남도  진주시  일반용   24914   336484885  28
20  201607-201612  경상남도  진주시   합계   31313  1184320317 NaN
23  201607-201612  경상남도  창녕군  일반용    5448    64848733  14
22  201607-201612  경상남도  창녕군   합계   10041   458916468 NaN
24  201607-201612  경상남도  창원시  일반용   56397  1021092178  19
25  201607-201612  경상남도  창원시   합계   75849  5352908151 NaN
27  201607-201612  경상남도  통영시  일반용   10998   150034538  26
26  201607-201612  경상남도  통영시   합계   13431   578196498 NaN
29  201607-201612  경상남도  하동군  일반용    4221    39385569  25
28  201607-201612  경상남도  하동군   합계    8906   157144719 NaN
31  201607-201612  경상남도  함안군  일반용    5272    61944647   5
30  201607-201612  경상남도  함안군   합계    8875  1224091323 NaN
33  201607-201612  경상남도  함양군  일반용    3645    30242740  24
32  201607-201612  경상남도  함양군   합계    6871   124341510 NaN
34  201607-201612  경상남도  합천군  일반용    3898    37043974  21
35  201607-201612  경상남도  합천군   합계    8680   176644524 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1607-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)