In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경기도_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경기도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경기도,전체(시 / 군 / 구),주택용,"2,662,802","1,276,864,573","153,850,997,279",120.5
4,201507,경기도,전체(시 / 군 / 구),일반용,"612,648","2,114,563,515","309,063,189,926",146.2
...,...,...,...,...,...,...,...,...
1531,201512,경기도,화성시,산업용,"16,687","1,090,862,628","135,468,726,530",124.2
1532,201512,경기도,화성시,심 야,"13,183","29,874,294","2,257,529,096",75.6
1533,201512,경기도,화성시,일반용,"35,918","140,843,879","19,243,735,500",136.6
1534,201512,경기도,화성시,주택용,"107,887","68,541,182","8,788,200,571",128.2
1535,201512,경기도,화성시,합계,"219,767","1,368,629,548","168,383,818,907",123

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경기도,전체(시 / 군 / 구),주택용,"2,662,802","1,276,864,573","153,850,997,279",120.5
4,201507,경기도,전체(시 / 군 / 구),일반용,"612,648","2,114,563,515","309,063,189,926",146.2
5,201507,경기도,전체(시 / 군 / 구),교육용,"4,248","112,209,046","15,564,438,273",138.7
6,201507,경기도,전체(시 / 군 / 구),산업용,"115,572","4,689,497,258","588,401,325,135",125.5
...,...,...,...,...,...,...,...,...
1531,201512,경기도,화성시,산업용,"16,687","1,090,862,628","135,468,726,530",124.2
1532,201512,경기도,화성시,심 야,"13,183","29,874,294","2,257,529,096",75.6
1533,201512,경기도,화성시,일반용,"35,918","140,843,879","19,243,735,500",136.6
1534,201512,경기도,화성시,주택용,"107,887","68,541,182","8,788,200,571",128.2
1535,201512,경기도,화성시,합계,"219,767","1,368,629,548","168,383,818,907",123

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경기도,전체(시 / 군 / 구),주택용,"2,662,802","1,276,864,573","153,850,997,279",120.5
4,201507,경기도,전체(시 / 군 / 구),일반용,"612,648","2,114,563,515","309,063,189,926",146.2
5,201507,경기도,전체(시 / 군 / 구),교육용,"4,248","112,209,046","15,564,438,273",138.7
6,201507,경기도,전체(시 / 군 / 구),산업용,"115,572","4,689,497,258","588,401,325,135",125.5
7,201507,경기도,전체(시 / 군 / 구),농사용,"196,451","155,545,077","7,577,694,091",48.7
...,...,...,...,...,...,...,...,...
1531,201512,경기도,화성시,산업용,"16,687","1,090,862,628","135,468,726,530",124.2
1532,201512,경기도,화성시,심 야,"13,183","29,874,294","2,257,529,096",75.6
1533,201512,경기도,화성시,일반용,"35,918","140,843,879","19,243,735,500",136.6
1534,201512,경기도,화성시,주택용,"107,887","68,541,182","8,788,200,571",128.2
1535,201512,경기도,화성시,합계,"219,767","1,368,629,548","168,383,818,907",123

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경기도,전체(시 / 군 / 구),주택용,"2,662,802","1,276,864,573","153,850,997,279",120.5
4,201507,경기도,전체(시 / 군 / 구),일반용,"612,648","2,114,563,515","309,063,189,926",146.2
5,201507,경기도,전체(시 / 군 / 구),교육용,"4,248","112,209,046","15,564,438,273",138.7
6,201507,경기도,전체(시 / 군 / 구),산업용,"115,572","4,689,497,258","588,401,325,135",125.5
7,201507,경기도,전체(시 / 군 / 구),농사용,"196,451","155,545,077","7,577,694,091",48.7
8,201507,경기도,전체(시 / 군 / 구),가로등,"303,636","55,505,218","6,923,226,363",124.7
9,201507,경기도,전체(시 / 군 / 구),심 야,"159,725","89,943,946","5,430,575,895",60.4
10,201508,경기도,전체(시 / 군 / 구),주택용,"2,670,475","1,532,792,253","213,047,983,571",139.0
11,201508,경기도,전체(시 / 군 / 구),일반용,"614,579","2,372,866,419","336,467,857,360",141.8
12,201508,경기도,전체(시 / 군 / 구),교육용,"4,252","107,055,473","15,011,359,316",140.2
13,201508,경기도,전체(시 / 군 / 구),산업용,"115,936","4,914,070,131","590,473,500,707",120.2
14,201508,경기도,전체(시 / 군 / 구),농사용,"197,732","191,426,416","9,078,708,521",47.4
15,201508,경기도,전체(시 / 군 / 구),가로등,"304,608","59,087,198","7,136,283,458",120.8
16,201508,경기도,전체(시 / 군 / 구),심 야,"159,355","85,021,493","5,356,112,511",63.0
17,201509,경기도,전체(시 / 군 / 구),주택용,"2,678,311","1,344,121,683","162,874,375,318",121.2
18,201509,경기도,전체(시 / 군 / 구),일반용,"616,540","2,126,610,509","267,636,815,679",125.9
19,201509,경기도,전체(시 / 군 / 구),교육용,"4,261","117,759,050","13,667,483,929",116.1
20,201509,경기도,전체(시 / 군 / 구),산업용,"116,261","4,682,064,047","473,495,329,501",101.1
21,201509,경기도,전체(시 / 군 / 구),농사용,"198,536","191,631,444","9,066,702,450",47.3
22,201509,경기도,전체(시 / 군 / 구),가로등,"305,420","63,011,935","7,350,816,200",116.7
23,201509,경기도,전체(시 / 군 / 구),심 야,"159,110","80,638,758","4,843,584,479",60.1
24,201510,경기도,전체(시 / 군 / 구),주택용,"2,684,765","1,205,783,740","135,938,717,748",112.7
25,201510,경기도,전체(시 / 군 / 구),일반용,"617,752","1,812,090,269","212,468,380,595",117.3
26,201510,경기도,전체(시 / 군 / 구),교육용,"4,255","91,372,533","10,445,315,335",114.3
27,201510,경기도,전체(시 / 군 / 구),산업용,"116,503","4,543,864,640","440,151,564,706",96.9
28,201510,경기도,전체(시 / 군 / 구),농사용,"198,906","153,827,679","7,744,082,191",50.3
29,201510,경기도,전체(시 / 군 / 구),가로등,"305,894","68,250,566","7,625,799,516",111.7
30,201510,경기도,전체(시 / 군 / 구),심 야,"158,922","116,542,292","6,638,788,170",57.0
31,201511,경기도,전체(시 / 군 / 구),주택용,"2,693,582","1,295,810,400","158,118,627,305",122.0
32,201511,경기도,전체(시 / 군 / 구),일반용,"620,075","1,867,330,049","244,558,306,619",131.0
33,201511,경기도,전체(시 / 군 / 구),교육용,"4,250","107,482,785","13,019,474,082",121.1
34,201511,경기도,전체(시 / 군 / 구),산업용,"116,813","4,657,230,376","539,922,494,334",115.9
35,201511,경기도,전체(시 / 군 / 구),농사용,"268,107","232,989,247","9,903,771,951",42.5
36,201511,경기도,전체(시 / 군 / 구),가로등,"306,588","73,077,393","8,052,072,974",110.2
37,201511,경기도,전체(시 / 군 / 구),심 야,"158,845","237,768,219","15,286,535,779",64.3
38,201512,경기도,전체(시 / 군 / 구),주택용,"2,700,510","1,351,777,771","171,192,077,279",126.6
39,201512,경기도,전체(시 / 군 / 구),일반용,"622,956","2,170,530,604","294,233,453,509",135.6
40,201512,경기도,전체(시 / 군 / 구),교육용,"4,255","151,377,705","17,305,137,951",114.3
41,201512,경기도,전체(시 / 군 / 구),산업용,"117,014","4,919,161,782","592,367,263,621",120.4
42,201512,경기도,전체(시 / 군 / 구),농사용,"206,775","208,758,957","9,936,824,229",47.6
43,201512,경기도,전체(시 / 군 / 구),가로등,"307,392","75,642,733","8,112,219,620",107.2
44,201512,경기도,전체(시 / 군 / 구),심 야,"158,672","388,315,162","29,374,595,982",75.6
45,합계,합계,합계,합계,"24,573,289","52,091,270,344","6,134,713,863,458",117.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_12392\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)        사용량(kWh)
4   201507  경기도  일반용  612,648   2,114,563,515
11  201508  경기도  일반용  614,579   2,372,866,419
18  201509  경기도  일반용  616,540   2,126,610,509
25  201510  경기도  일반용  617,752   1,812,090,269
32  201511  경기도  일반용  620,075   1,867,330,049
39  201512  경기도  일반용  622,956   2,170,530,604

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201507  경기도  가평군  일반용   9,424    20,841,243
301   201508  경기도  가평군  일반용   9,491    25,768,046
549   201509  경기도  가평군  일반용   9,546    22,312,055
797   201510  경기도  가평군  일반용   9,576    18,783,641
1045  201511  경기도  가평군  일반용   9,586    21,800,249
...      ...  ...  ...  ...      ...           ...
541   201508  경기도  화성시  일반용  35,009   146,150,403
789   201509  경기도  화성시  일반용  35,247   135,260,038
1037  201510  경기도  화성시  일반용  35,369   118,143,186
1285  201511  경기도  화성시  일반용  35,643   122,053,968
1533  201512  경기도  화성시  일반용  35,918   140,843,879

[186 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경기도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['가평군',
 '고양시',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시',
 '성남시',
 '수원시',
 '시흥시',
 '안산시',
 '안성시',
 '안양시',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월   시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201507  경기도  가평군   합계   59,853      41,094,401
303   201508  경기도  가평군   합계   60,051      47,725,887
551   201509  경기도  가평군   합계   60,279      43,689,667
799   201510  경기도  가평군   합계   60,405      41,548,450
1047  201511  경기도  가평군   합계   61,557      50,765,898
...      ...  ...  ...  ...       ...             ...
543   201508  경기도  화성시   합계  208,030   1,491,401,194
791   201509  경기도  화성시   합계  209,352   1,284,066,353
1039  201510  경기도  화성시   합계  210,323   1,230,158,224
1287  201511  경기도  화성시   합계  217,540   1,275,750,275
1535  201512  경기도  화성시   합계  219,767   1,368,629,548

[186 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[41094401, 47725887, 43689667, 41548450, 50765898, 59980399]
[349549397, 393640253, 359038520, 320718255, 343416016, 394037044]
[34522263, 38295507, 33450579, 29149343, 30244143, 33571230]
[97236298, 106156675, 96598150, 88976550, 95520105, 104929476]
[170682393, 181930677, 176446211, 160351576, 185906126, 211746571]
[62244334, 70521994, 62813189, 54037525, 56094538, 63159481]
[119979101, 127565216, 120590591, 107585284, 111802975, 124561996]
[242786650, 250641914, 250339586, 223292536, 257950638, 293503054]
[213980160, 235689498, 222604941, 199807750, 222702399, 250619015]
[52165759, 56966092, 55413471, 47703190, 51569882, 56320066]
[349956919, 381185827, 352129125, 303544449, 315778260, 348655124]
[419678875, 463265385, 407236360, 358675015, 364375714, 404785327]
[445216539, 499076274, 447340889, 392554770, 403259717, 443549800]
[331600473, 337692641, 331761341, 302397192, 325357282, 359345991]
[702950612, 723961195, 690792845, 653653900, 656106917, 698755662]
[206517517, 212617244, 208377524, 193240658, 216655995, 236110116]
[210702579, 233402584, 212823499, 184805066, 191630641, 214225267]
[153090277, 154707383, 157819203, 146409885, 172938844, 189470068]
[53795636, 61018758, 56695589, 55643423, 77781514, 88798180]
[96256298, 102823738, 98842412, 93853688, 115260580, 128504653]
[34886883, 39677199, 37865794, 35470023, 46071796, 49871332]
[101674286, 111486415, 103421339, 94281839, 97394247, 106912175]
[743968477, 784480457, 725503305, 699006490, 719919933, 779518467]
[54296262, 59723203, 55432171, 48698386, 53183987, 59760749]
[129477816, 143731762, 130329893, 113339742, 120868274, 136866634]
[376061416, 396488140, 370905050, 364090470, 391294643, 412799769]
[672333606, 674957011, 653749356, 630975795, 647370676, 687267734]
[595843371, 599000735, 579749172, 558355378, 573105415, 626640485]
[181789703, 183806559, 189063111, 176128244, 214424555, 235960796]
[92240817, 98681966, 90948190, 83278623, 87186484, 96708505]
[1157549515, 1491401194, 1284066353, 1230158224, 1275750275, 1368629548]
경기도 지역별 합계 :  [284804702, 2160399485, 199233065, 589417254, 1087063554, 368871061, 712085163, 1518514378, 1345403763, 320138460, 2051249704, 2418016676, 2630997989, 1988154920, 4126221131, 1273519054, 1247589636, 974435660, 393733100, 635541369, 243843027, 615170301, 4452397129, 331094758, 774614121, 2311639488, 3966654178, 3532694556, 1181172968, 549044585, 7807555109]
경기도 고객호수 평균:  [10075, 36477, 2413, 13396, 25851, 8340, 9934, 16796, 28090, 6461, 44964, 45845, 58144, 24418, 47805, 19700, 23877, 13100, 16975, 13401, 7048, 10066, 36146, 5822, 18484, 19197, 24375, 34273, 18003, 7780, 35320]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201507  경기도  가평군   합계  59,853   41,094,401
1           201508  경기도  가평군   합계  60,051   47,725,887
2           201509  경기도  가평군   합계  60,279   43,689,667
3           201510  경기도  가평군   합계  60,405   41,548,450
4           201511  경기도  가평군   합계  61,557   50,765,898
..             ...  ...  ...  ...      ...          ...
212  201507-201512  경기도  파주시   합계    24375   3966654178
213  201507-201512  경기도  평택시   합계    34273   3532694556
214  201507-201512  경기도  포천시   합계    18003   1181172968
215  201507-201512  경기도  하남시   합계     7780    549044585
216  201507-201512  경기도  화성시   합계    35320   7807555109

[217 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201507-201512  경기도   가평군   합계   10075   284804702
187  201507-201512  경기도   고양시   합계   36477  2160399485
188  201507-201512  경기도   과천시   합계    2413   199233065
189  201507-201512  경기도   광명시   합계   13396   589417254
190  201507-201512  경기도   광주시   합계   25851  1087063554
191  201507-201512  경기도   구리시   합계    8340   368871061
192  201507-201512  경기도   군포시   합계    9934   712085163
193  201507-201512  경기도   김포시   합계   16796  1518514378
194  201507-201512  경기도  남양주시   합계   28090  1345403763
195  201507-201512  경기도  동두천시   합계    6461   320138460
196  201507-201512  경기도   부천시   합계   44964  2051249704
197  201507-201512  경기도   성남시   합계   45845  2418016676
198  201507-201512  경기도   수원시   합계   58144  2630997989
199  201507-201512  경기도   시흥시   합계   24418  1988154920
200  201507-201512  경기도   안산시   합계   47805  4126221131
201  201507-201512  경기도   안성시   합계   19700  1273519054
202  201507-201512  경기도   안양시   합계   23877  1247589636
203  201507-201512  경기도   양주시   합계   13100   974435660
204  201507-201512  경기도   양평군   합계   16975   393733100
205  201507-201512  경기도   여주시   합계   13401   635541369
206  201507-201512  경기도   연천군   합계    7048   243843027
207  201507-201512  경기도   오산시   합계   10066   615170301
208  201507-201512  경기도   용인시   합계   36146  4452397129
209  201507-201512  경기도   의왕시   합계    5822   331094758
210  201507-201512  경기도  의정부시   합계   18484   774614121
211  201507-201512  경기도   이천시   합계   19197  2311639488
212  201507-201512  경기도   파주시   합계   24375  3966654178
213  201507-201512  경기도   평택시   합계   34273  3532694556
214  201507-201512  경기도   포천시   합계   18003  1181172968
215  201507-201512  경기도   하남시   합계    7780   549044585
216  201507-201512  경기도   화성시   합계   35320  7807555109

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201507  경기도  가평군  일반용   9,424    20,841,243
301   201508  경기도  가평군  일반용   9,491    25,768,046
549   201509  경기도  가평군  일반용   9,546    22,312,055
797   201510  경기도  가평군  일반용   9,576    18,783,641
1045  201511  경기도  가평군  일반용   9,586    21,800,249
...      ...  ...  ...  ...      ...           ...
541   201508  경기도  화성시  일반용  35,009   146,150,403
789   201509  경기도  화성시  일반용  35,247   135,260,038
1037  201510  경기도  화성시  일반용  35,369   118,143,186
1285  201511  경기도  화성시  일반용  35,643   122,053,968
1533  201512  경기도  화성시  일반용  35,918   140,843,879

[186 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[20841243, 25768046, 22312055, 18783641, 21800249, 24728190]
[160714065, 180880993, 164043732, 145091359, 144814809, 165949219]
[20437774, 21997706, 19802484, 16971015, 17574870, 19995464]
[36232195, 41175619, 35706066, 34904383, 35307869, 41190776]
[44369536, 50310003, 45564557, 38804822, 42495540, 50542261]
[31185495, 35341327, 31503363, 25491160, 25780854, 30054432]
[33269481, 37105929, 34746493, 28879722, 29012363, 32954092]
[49241699, 56243172, 51705927, 43585693, 47279663, 57821537]
[67523616, 77099887, 70157911, 58316635, 62777973, 73406880]
[19258367, 22483333, 19816937, 16225996, 16282505, 18571538]
[109776008, 125415094, 113004776, 91394827, 90853157, 105781515]
[217910144, 237275710, 208296521, 179568170, 177717572, 202394207]
[235094677, 259453150, 230206983, 197073475, 196155096, 224361672]
[55209054, 64104693, 57883196, 47222874, 49841925, 60030700]
[94943191, 110071262, 98678390, 79679423, 81112027, 95320881]
[34376020, 39000552, 35405153, 30579836, 32563738, 37387663]
[99573996, 110783637, 100231598, 83615421, 83889752, 97470512]
[31347354, 35683154, 31591201, 28248783, 31392110, 37850267]
[18749983, 22494086, 19716238, 17000192, 19259538, 22668064]
[25096475, 28308724, 24881380, 21756318, 22944101, 25720525]
[10058954, 11703686, 10133643, 8881581, 10475981, 12502895]
[27579810, 32322798, 29675816, 23980155, 24680823, 28813715]
[178446312, 195061746, 169598066, 151170316, 155990925, 180530417]
[23834869, 25900080, 23499444, 20153927, 21197195, 24635116]
[59641973, 67253175, 59302393, 48744637, 50350784, 59233727]
[46798089, 52786764, 47221052, 40204581, 43244682, 51796033]
[68854775, 78016931, 71308888, 59586891, 63864142, 74669651]
[95600556, 110823519, 99795542, 82277629, 85945113, 101369104]
[35306738, 39720404, 36276739, 31589988, 34871064, 41274955]
[28417200, 32130836, 29283927, 24163633, 25799661, 30660717]
[134873866, 146150403, 135260038, 118143186, 122053968, 140843879]
경기도 지역별 일반용 합계 :  [134233424, 961494177, 116779313, 224516908, 272086719, 179356631, 195968080, 305877691, 409282902, 112638676, 636225377, 1223162324, 1342345053, 334292442, 559805174, 209312962, 575564916, 196112869, 119888101, 148707523, 63756740, 167053117, 1030797782, 139220631, 344526689, 282051201, 416301278, 575811463, 219039888, 170455974, 797325340]
경기도 고객호수 평균:  [9541, 39260, 2250, 11091, 23556, 9920, 8651, 18539, 32545, 6004, 34612, 33486, 50730, 21948, 28710, 13864, 24280, 13124, 11615, 9098, 4918, 9989, 36249, 5582, 20524, 14790, 24693, 32806, 17329, 12376, 35331]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12392\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0           201507  경기도  가평군  일반용  9,424   20,841,243
1           201508  경기도  가평군  일반용  9,491   25,768,046
2           201509  경기도  가평군  일반용  9,546   22,312,055
3           201510  경기도  가평군  일반용  9,576   18,783,641
4           201511  경기도  가평군  일반용  9,586   21,800,249
..             ...  ...  ...  ...     ...          ...
212  201507-201512  경기도  파주시  일반용   24693    416301278
213  201507-201512  경기도  평택시  일반용   32806    575811463
214  201507-201512  경기도  포천시  일반용   17329    219039888
215  201507-201512  경기도  하남시  일반용   12376    170455974
216  201507-201512  경기도  화성시  일반용   35331    797325340

[217 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201507-201512  경기도   가평군  일반용    9541   134233424
187  201507-201512  경기도   고양시  일반용   39260   961494177
188  201507-201512  경기도   과천시  일반용    2250   116779313
189  201507-201512  경기도   광명시  일반용   11091   224516908
190  201507-201512  경기도   광주시  일반용   23556   272086719
191  201507-201512  경기도   구리시  일반용    9920   179356631
192  201507-201512  경기도   군포시  일반용    8651   195968080
193  201507-201512  경기도   김포시  일반용   18539   305877691
194  201507-201512  경기도  남양주시  일반용   32545   409282902
195  201507-201512  경기도  동두천시  일반용    6004   112638676
196  201507-201512  경기도   부천시  일반용   34612   636225377
197  201507-201512  경기도   성남시  일반용   33486  1223162324
198  201507-201512  경기도   수원시  일반용   50730  1342345053
199  201507-201512  경기도   시흥시  일반용   21948   334292442
200  201507-201512  경기도   안산시  일반용   28710   559805174
201  201507-201512  경기도   안성시  일반용   13864   209312962
202  201507-201512  경기도   안양시  일반용   24280   575564916
203  201507-201512  경기도   양주시  일반용   13124   196112869
204  201507-201512  경기도   양평군  일반용   11615   119888101
205  201507-201512  경기도   여주시  일반용    9098   148707523
206  201507-201512  경기도   연천군  일반용    4918    63756740
207  201507-201512  경기도   오산시  일반용    9989   167053117
208  201507-201512  경기도   용인시  일반용   36249  1030797782
209  201507-201512  경기도   의왕시  일반용    5582   139220631
210  201507-201512  경기도  의정부시  일반용   20524   344526689
211  201507-201512  경기도   이천시  일반용   14790   282051201
212  201507-201512  경기도   파주시  일반용   24693   416301278
213  201507-201512  경기도   평택시  일반용   32806   575811463
214  201507-201512  경기도   포천시  일반용   17329   219039888
215  201507-201512  경기도   하남시  일반용   12376   170455974
216  201507-201512  경기도   화성시  일반용   35331   797325340

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
186  201507-201512  경기도  가평군  일반용    9541   134233424
186  201507-201512  경기도  가평군   합계   10075   284804702
187  201507-201512  경기도  고양시  일반용   39260   961494177
187  201507-201512  경기도  고양시   합계   36477  2160399485
188  201507-201512  경기도  과천시  일반용    2250   116779313
..             ...  ...  ...  ...     ...         ...
214  201507-201512  경기도  포천시  일반용   17329   219039888
215  201507-201512  경기도  하남시   합계    7780   549044585
215  201507-201512  경기도  하남시  일반용   12376   170455974
216  201507-201512  경기도  화성시  일반용   35331   797325340
216  201507-201512  경기도  화성시   합계   35320  7807555109

[62 rows x 6 columns]

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[134233424,
 961494177,
 116779313,
 224516908,
 272086719,
 179356631,
 195968080,
 305877691,
 409282902,
 112638676,
 636225377,
 1223162324,
 1342345053,
 334292442,
 559805174,
 209312962,
 575564916,
 196112869,
 119888101,
 148707523,
 63756740,
 167053117,
 1030797782,
 139220631,
 344526689,
 282051201,
 416301278,
 575811463,
 219039888,
 170455974,
 797325340]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[284804702,
 2160399485,
 199233065,
 589417254,
 1087063554,
 368871061,
 712085163,
 1518514378,
 1345403763,
 320138460,
 2051249704,
 2418016676,
 2630997989,
 1988154920,
 4126221131,
 1273519054,
 1247589636,
 974435660,
 393733100,
 635541369,
 243843027,
 615170301,
 4452397129,
 331094758,
 774614121,
 2311639488,
 3966654178,
 3532694556,
 1181172968,
 549044585,
 7807555109]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[47.13, 44.51, 58.61, 38.09, 25.03, 48.62, 27.52, 20.14, 30.42, 35.18, 31.02, 50.59, 51.02, 16.81, 13.57, 16.44, 46.13, 20.13, 30.45, 23.4, 26.15, 27.16, 23.15, 42.05, 44.48, 12.2, 10.5, 16.3, 18.54, 31.05, 10.21]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    47
1    45
2    59
3    38
4    25
5    49
6    28
7    20
8    30
9    35
10   31
11   51
12   51
13   17
14   14
15   16
16   46
17   20
18   30
19   23
20   26
21   27
22   23
23   42
24   44
25   12
26   10
27   16
28   19
29   31
30   10
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    가평군  일반용  47
1    고양시  일반용  45
2    과천시  일반용  59
3    광명시  일반용  38
4    광주시  일반용  25
5    구리시  일반용  49
6    군포시  일반용  28
7    김포시  일반용  20
8   남양주시  일반용  30
9   동두천시  일반용  35
10   부천시  일반용  31
11   성남시  일반용  51
12   수원시  일반용  51
13   시흥시  일반용  17
14   안산시  일반용  14
15   안성시  일반용  16
16   안양시  일반용  46
17   양주시  일반용  20
18   양평군  일반용  30
19   여주시  일반용  23
20   연천군  일반용  26
21   오산시  일반용  27
22   용인시  일반용  23
23   의왕시  일반용  42
24  의정부시  일반용  44
25   이천시  일반용  12
26   파주시  일반용  10
27   평택시  일반용  16
28   포천시  일반용  19
29   하남시  일반용  31
30   화성시  일반용  10

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201507-201512  경기도  가평군  일반용    9541   134233424  47
1   201507-201512  경기도  가평군   합계   10075   284804702 NaN
2   201507-201512  경기도  고양시  일반용   39260   961494177  45
3   201507-201512  경기도  고양시   합계   36477  2160399485 NaN
4   201507-201512  경기도  과천시  일반용    2250   116779313  59
..            ...  ...  ...  ...     ...         ...  ..
56  201507-201512  경기도  포천시   합계   18003  1181172968 NaN
59  201507-201512  경기도  하남시  일반용   12376   170455974  31
58  201507-201512  경기도  하남시   합계    7780   549044585 NaN
60  201507-201512  경기도  화성시  일반용   35331   797325340  10
61  201507-201512  경기도  화성시   합계   35320  7807555109 NaN

[62 rows x 7 columns]

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)