In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라남도_계약종별_전력사용량_월별_17하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2017년 07 월 ~ 2017년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,전라남도,전체(시 / 군 / 구),주택용,"728,869","196,993,495","20,652,308,194",104.8
4,201707,전라남도,전체(시 / 군 / 구),일반용,"144,171","305,191,682","45,691,536,111",149.7
...,...,...,...,...,...,...,...,...
1099,201712,전라남도,화순군,산업용,755,"11,163,733","1,469,146,468",131.6
1100,201712,전라남도,화순군,심 야,"1,781","2,936,466","214,410,906",73
1101,201712,전라남도,화순군,일반용,"4,355","12,827,251","1,703,423,687",132.8
1102,201712,전라남도,화순군,주택용,"25,180","6,523,213","667,384,961",102.3
1103,201712,전라남도,화순군,합계,"49,589","51,300,872","5,028,857,819",98

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,전라남도,전체(시 / 군 / 구),주택용,"728,869","196,993,495","20,652,308,194",104.8
4,201707,전라남도,전체(시 / 군 / 구),일반용,"144,171","305,191,682","45,691,536,111",149.7
5,201707,전라남도,전체(시 / 군 / 구),교육용,"1,329","25,139,542","3,084,954,435",122.7
6,201707,전라남도,전체(시 / 군 / 구),산업용,"20,013","1,942,468,121","210,868,451,554",108.6
...,...,...,...,...,...,...,...,...
1099,201712,전라남도,화순군,산업용,755,"11,163,733","1,469,146,468",131.6
1100,201712,전라남도,화순군,심 야,"1,781","2,936,466","214,410,906",73
1101,201712,전라남도,화순군,일반용,"4,355","12,827,251","1,703,423,687",132.8
1102,201712,전라남도,화순군,주택용,"25,180","6,523,213","667,384,961",102.3
1103,201712,전라남도,화순군,합계,"49,589","51,300,872","5,028,857,819",98

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,전라남도,전체(시 / 군 / 구),주택용,"728,869","196,993,495","20,652,308,194",104.8
4,201707,전라남도,전체(시 / 군 / 구),일반용,"144,171","305,191,682","45,691,536,111",149.7
5,201707,전라남도,전체(시 / 군 / 구),교육용,"1,329","25,139,542","3,084,954,435",122.7
6,201707,전라남도,전체(시 / 군 / 구),산업용,"20,013","1,942,468,121","210,868,451,554",108.6
7,201707,전라남도,전체(시 / 군 / 구),농사용,"267,572","248,196,291","11,611,335,953",46.8
...,...,...,...,...,...,...,...,...
1099,201712,전라남도,화순군,산업용,755,"11,163,733","1,469,146,468",131.6
1100,201712,전라남도,화순군,심 야,"1,781","2,936,466","214,410,906",73
1101,201712,전라남도,화순군,일반용,"4,355","12,827,251","1,703,423,687",132.8
1102,201712,전라남도,화순군,주택용,"25,180","6,523,213","667,384,961",102.3
1103,201712,전라남도,화순군,합계,"49,589","51,300,872","5,028,857,819",98

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,전라남도,전체(시 / 군 / 구),주택용,"728,869","196,993,495","20,652,308,194",104.8
4,201707,전라남도,전체(시 / 군 / 구),일반용,"144,171","305,191,682","45,691,536,111",149.7
5,201707,전라남도,전체(시 / 군 / 구),교육용,"1,329","25,139,542","3,084,954,435",122.7
6,201707,전라남도,전체(시 / 군 / 구),산업용,"20,013","1,942,468,121","210,868,451,554",108.6
7,201707,전라남도,전체(시 / 군 / 구),농사용,"267,572","248,196,291","11,611,335,953",46.8
8,201707,전라남도,전체(시 / 군 / 구),가로등,"148,879","17,703,856","2,192,166,472",123.8
9,201707,전라남도,전체(시 / 군 / 구),심 야,"47,156","18,208,942","1,050,581,470",57.7
10,201708,전라남도,전체(시 / 군 / 구),주택용,"729,803","246,097,894","30,237,357,542",122.9
11,201708,전라남도,전체(시 / 군 / 구),일반용,"144,507","366,152,790","52,499,900,022",143.4
12,201708,전라남도,전체(시 / 군 / 구),교육용,"1,334","24,993,505","3,170,722,351",126.9
13,201708,전라남도,전체(시 / 군 / 구),산업용,"20,090","1,954,325,755","213,551,179,655",109.3
14,201708,전라남도,전체(시 / 군 / 구),농사용,"268,742","300,324,342","13,760,894,365",45.8
15,201708,전라남도,전체(시 / 군 / 구),가로등,"149,570","18,782,337","2,229,644,732",118.7
16,201708,전라남도,전체(시 / 군 / 구),심 야,"47,041","14,654,099","864,257,237",59.0
17,201709,전라남도,전체(시 / 군 / 구),주택용,"730,718","204,974,517","22,014,155,005",107.4
18,201709,전라남도,전체(시 / 군 / 구),일반용,"144,588","319,298,695","42,221,036,840",132.2
19,201709,전라남도,전체(시 / 군 / 구),교육용,"1,334","25,737,266","2,971,043,627",115.4
20,201709,전라남도,전체(시 / 군 / 구),산업용,"20,156","1,967,037,575","174,396,716,640",88.7
21,201709,전라남도,전체(시 / 군 / 구),농사용,"269,765","275,698,566","12,767,966,465",46.3
22,201709,전라남도,전체(시 / 군 / 구),가로등,"150,115","19,590,692","2,255,197,932",115.1
23,201709,전라남도,전체(시 / 군 / 구),심 야,"46,941","15,065,670","878,746,097",58.3
24,201710,전라남도,전체(시 / 군 / 구),주택용,"731,758","182,360,906","18,129,910,640",99.4
25,201710,전라남도,전체(시 / 군 / 구),일반용,"144,686","263,419,847","31,278,666,388",118.7
26,201710,전라남도,전체(시 / 군 / 구),교육용,"1,331","18,904,105","1,913,872,978",101.2
27,201710,전라남도,전체(시 / 군 / 구),산업용,"20,193","1,988,775,926","168,021,169,765",84.5
28,201710,전라남도,전체(시 / 군 / 구),농사용,"270,481","240,351,012","11,366,303,573",47.3
29,201710,전라남도,전체(시 / 군 / 구),가로등,"150,385","20,802,352","2,273,196,910",109.3
30,201710,전라남도,전체(시 / 군 / 구),심 야,"46,830","22,484,889","1,253,592,299",55.8
31,201711,전라남도,전체(시 / 군 / 구),주택용,"733,016","191,369,816","19,797,349,300",103.5
32,201711,전라남도,전체(시 / 군 / 구),일반용,"145,040","274,144,284","35,756,169,231",130.4
33,201711,전라남도,전체(시 / 군 / 구),교육용,"1,332","23,470,166","2,490,802,198",106.1
34,201711,전라남도,전체(시 / 군 / 구),산업용,"20,241","1,763,602,992","195,562,342,007",110.9
35,201711,전라남도,전체(시 / 군 / 구),농사용,"389,192","356,243,086","14,895,025,082",41.8
36,201711,전라남도,전체(시 / 군 / 구),가로등,"150,699","21,943,640","2,343,940,713",106.8
37,201711,전라남도,전체(시 / 군 / 구),심 야,"46,732","45,042,003","2,856,078,406",63.4
38,201712,전라남도,전체(시 / 군 / 구),주택용,"733,844","202,751,199","21,719,824,097",107.1
39,201712,전라남도,전체(시 / 군 / 구),일반용,"145,329","325,727,151","44,619,809,745",137.0
40,201712,전라남도,전체(시 / 군 / 구),교육용,"1,332","34,351,722","3,510,111,273",102.2
41,201712,전라남도,전체(시 / 군 / 구),산업용,"20,238","1,955,701,197","209,245,163,123",107.0
42,201712,전라남도,전체(시 / 군 / 구),농사용,"294,927","311,782,596","14,542,067,241",46.6
43,201712,전라남도,전체(시 / 군 / 구),가로등,"151,002","22,256,907","2,319,375,310",104.2
44,201712,전라남도,전체(시 / 군 / 구),심 야,"46,601","78,320,208","5,873,059,428",75.0
45,합계,합계,합계,합계,"8,327,882","16,850,441,636","1,678,737,982,406",99.6

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_14684\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201707  전라남도  일반용  144,171   305,191,682
11  201708  전라남도  일반용  144,507   366,152,790
18  201709  전라남도  일반용  144,588   319,298,695
25  201710  전라남도  일반용  144,686   263,419,847
32  201711  전라남도  일반용  145,040   274,144,284
39  201712  전라남도  일반용  145,329   325,727,151

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    201707  전라남도  강진군  일반용  2,981    4,927,963
229   201708  전라남도  강진군  일반용  3,006    5,909,214
405   201709  전라남도  강진군  일반용  2,996    5,152,669
581   201710  전라남도  강진군  일반용  3,003    4,385,326
757   201711  전라남도  강진군  일반용  3,016    4,872,339
...      ...   ...  ...  ...     ...          ...
397   201708  전라남도  화순군  일반용  4,304   13,964,524
573   201709  전라남도  화순군  일반용  4,331   12,024,147
749   201710  전라남도  화순군  일반용  4,332   10,107,739
925   201711  전라남도  화순군  일반용  4,337   10,855,269
1101  201712  전라남도  화순군  일반용  4,355   12,827,251

[132 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강진군',
 '고흥군',
 '곡성군',
 '광양시',
 '구례군',
 '나주시',
 '담양군',
 '목포시',
 '무안군',
 '보성군',
 '순천시',
 '신안군',
 '여수시',
 '영광군',
 '영암군',
 '완도군',
 '장성군',
 '장흥군',
 '진도군',
 '함평군',
 '해남군',
 '화순군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55    201707  전라남도  강진군   합계  38,437   22,530,159
231   201708  전라남도  강진군   합계  38,486   26,978,882
407   201709  전라남도  강진군   합계  38,608   24,846,851
583   201710  전라남도  강진군   합계  38,706   22,613,971
759   201711  전라남도  강진군   합계  47,550   32,315,779
...      ...   ...  ...  ...      ...          ...
399   201708  전라남도  화순군   합계  49,097   41,768,800
575   201709  전라남도  화순군   합계  49,313   38,056,042
751   201710  전라남도  화순군   합계  49,395   34,017,935
927   201711  전라남도  화순군   합계  51,281   42,696,088
1103  201712  전라남도  화순군   합계  49,589   51,300,872

[132 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[22530159, 26978882, 24846851, 22613971, 32315779, 30163632]
[32284798, 38576665, 35489689, 29686861, 41355891, 42947132]
[35665491, 35470020, 34084846, 29249265, 34826370, 37526381]
[449826117, 480565767, 458248134, 512144691, 367395035, 467077873]
[13336673, 15587638, 13624011, 12298026, 14660104, 16561424]
[98625897, 108058388, 100688077, 88096195, 99292736, 108090560]
[38032652, 42118594, 40374615, 35393434, 42704417, 45300448]
[81499350, 99558118, 86016856, 71605075, 74225350, 85202154]
[51865518, 58605560, 51596902, 44967155, 58835924, 55279926]
[21698527, 25633655, 24035896, 20823343, 26151567, 29794525]
[160603393, 178887301, 165073454, 140134338, 150939111, 173037033]
[20903021, 26928196, 25666807, 21640196, 24837248, 25858781]
[1295599187, 1313144181, 1299863532, 1285018955, 1196483282, 1297798999]
[54575266, 65981431, 76698011, 73229604, 80109661, 67462627]
[95214273, 87429401, 89238009, 75667150, 88082415, 93122488]
[75192006, 86140018, 86171460, 82063189, 87762449, 75933784]
[47608137, 51893414, 50821662, 45313924, 53693487, 58222286]
[23965674, 28665113, 25783099, 23211550, 31823574, 32804483]
[22796825, 26510743, 24524191, 22688575, 28376293, 27449028]
[27956540, 32457973, 30046890, 25820944, 34928560, 34283161]
[47330179, 54370864, 46453947, 41414661, 64320646, 75673383]
[36792246, 41768800, 38056042, 34017935, 42696088, 51300872]
전라남도 지역별 합계 :  [159449274, 220341036, 206822373, 2735257617, 86067876, 602851853, 243924160, 498106903, 321150985, 148137513, 968674630, 145834249, 7687908136, 418056600, 528753736, 493262906, 307552910, 166253493, 152345655, 185494068, 329563680, 244631983]
전라남도 고객호수 평균:  [6681, 13513, 5773, 12994, 5078, 12954, 7582, 16072, 10871, 8633, 23721, 8456, 25760, 8176, 9360, 8075, 6521, 6649, 6389, 6246, 13548, 8267]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201707  전라남도  강진군   합계  38,437   22,530,159
1           201708  전라남도  강진군   합계  38,486   26,978,882
2           201709  전라남도  강진군   합계  38,608   24,846,851
3           201710  전라남도  강진군   합계  38,706   22,613,971
4           201711  전라남도  강진군   합계  47,550   32,315,779
..             ...   ...  ...  ...      ...          ...
149  201707-201712  전라남도  장흥군   합계     6649    166253493
150  201707-201712  전라남도  진도군   합계     6389    152345655
151  201707-201712  전라남도  함평군   합계     6246    185494068
152  201707-201712  전라남도  해남군   합계    13548    329563680
153  201707-201712  전라남도  화순군   합계     8267    244631983

[154 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201707-201712']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  201707-201712  전라남도  강진군   합계    6681   159449274
133  201707-201712  전라남도  고흥군   합계   13513   220341036
134  201707-201712  전라남도  곡성군   합계    5773   206822373
135  201707-201712  전라남도  광양시   합계   12994  2735257617
136  201707-201712  전라남도  구례군   합계    5078    86067876
137  201707-201712  전라남도  나주시   합계   12954   602851853
138  201707-201712  전라남도  담양군   합계    7582   243924160
139  201707-201712  전라남도  목포시   합계   16072   498106903
140  201707-201712  전라남도  무안군   합계   10871   321150985
141  201707-201712  전라남도  보성군   합계    8633   148137513
142  201707-201712  전라남도  순천시   합계   23721   968674630
143  201707-201712  전라남도  신안군   합계    8456   145834249
144  201707-201712  전라남도  여수시   합계   25760  7687908136
145  201707-201712  전라남도  영광군   합계    8176   418056600
146  201707-201712  전라남도  영암군   합계    9360   528753736
147  201707-201712  전라남도  완도군   합계    8075   493262906
148  201707-201712  전라남도  장성군   합계    6521   307552910
149  201707-201712  전라남도  장흥군   합계    6649   166253493
150  201707-201712  전라남도  진도군   합계    6389   152345655
151  201707-201712  전라남도  함평군   합계    6246   185494068
152  201707-201712  전라남도  해남군   합계   13548   329563680
153  201707-201712  전라남도  화순군   합계    8267   244631983

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    201707  전라남도  강진군  일반용  2,981    4,927,963
229   201708  전라남도  강진군  일반용  3,006    5,909,214
405   201709  전라남도  강진군  일반용  2,996    5,152,669
581   201710  전라남도  강진군  일반용  3,003    4,385,326
757   201711  전라남도  강진군  일반용  3,016    4,872,339
...      ...   ...  ...  ...     ...          ...
397   201708  전라남도  화순군  일반용  4,304   13,964,524
573   201709  전라남도  화순군  일반용  4,331   12,024,147
749   201710  전라남도  화순군  일반용  4,332   10,107,739
925   201711  전라남도  화순군  일반용  4,337   10,855,269
1101  201712  전라남도  화순군  일반용  4,355   12,827,251

[132 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[4927963, 5909214, 5152669, 4385326, 4872339, 5885254]
[8107047, 9813582, 8761423, 7106233, 7639772, 9104454]
[3560141, 4331438, 3781195, 3206841, 3468474, 4121686]
[22991297, 26951223, 23256889, 18801390, 19053196, 22897182]
[5076479, 6060738, 5099149, 4333192, 4836792, 5625734]
[23487757, 25935484, 23169704, 19061397, 20398093, 24477042]
[8124485, 10314272, 9209940, 7865243, 8674743, 10427479]
[41467745, 51485496, 45028717, 35810370, 35458706, 42025523]
[13933052, 16343973, 14063310, 11560699, 12277869, 14859974]
[5726230, 7083664, 6408438, 5238108, 5544681, 6669807]
[45967808, 53836054, 46410615, 38286619, 39367470, 46911633]
[4631166, 5755879, 5266968, 4415305, 4827848, 5577883]
[48113697, 58908876, 52082993, 41888830, 42352746, 49555824]
[8005950, 9662109, 8137789, 7671154, 7825693, 9367876]
[9003245, 10818923, 9488273, 7911386, 8306515, 9894302]
[7460433, 9668931, 8708270, 7266360, 7327770, 8377965]
[7205152, 8471634, 7039886, 6111333, 7012125, 8496389]
[5943867, 7358912, 6410672, 5499669, 5842039, 6862026]
[4326883, 5385486, 4271080, 3586455, 3681584, 4376066]
[4117563, 5052146, 4331478, 3600074, 3903614, 4518559]
[10984910, 13040232, 11195090, 9706124, 10616946, 12867242]
[12028812, 13964524, 12024147, 10107739, 10855269, 12827251]
전라남도 지역별 일반용 합계 :  [31132765, 50532511, 22469775, 133951177, 31032084, 136529477, 54616162, 251276557, 83038877, 36670928, 270780199, 30475049, 292902966, 50670571, 55422644, 48809729, 44336519, 37917185, 25627554, 25523434, 68410544, 71807742]
전라남도 고객호수 평균:  [3003, 5477, 2113, 10821, 2544, 7016, 3706, 18838, 5566, 3579, 19850, 3490, 22306, 4744, 4188, 5354, 3314, 3344, 2841, 2293, 5999, 4324]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14684\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
0           201707  전라남도  강진군  일반용  2,981   4,927,963
1           201708  전라남도  강진군  일반용  3,006   5,909,214
2           201709  전라남도  강진군  일반용  2,996   5,152,669
3           201710  전라남도  강진군  일반용  3,003   4,385,326
4           201711  전라남도  강진군  일반용  3,016   4,872,339
..             ...   ...  ...  ...     ...         ...
149  201707-201712  전라남도  장흥군  일반용    3344    37917185
150  201707-201712  전라남도  진도군  일반용    2841    25627554
151  201707-201712  전라남도  함평군  일반용    2293    25523434
152  201707-201712  전라남도  해남군  일반용    5999    68410544
153  201707-201712  전라남도  화순군  일반용    4324    71807742

[154 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201707-201712']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
132  201707-201712  전라남도  강진군  일반용    3003   31132765
133  201707-201712  전라남도  고흥군  일반용    5477   50532511
134  201707-201712  전라남도  곡성군  일반용    2113   22469775
135  201707-201712  전라남도  광양시  일반용   10821  133951177
136  201707-201712  전라남도  구례군  일반용    2544   31032084
137  201707-201712  전라남도  나주시  일반용    7016  136529477
138  201707-201712  전라남도  담양군  일반용    3706   54616162
139  201707-201712  전라남도  목포시  일반용   18838  251276557
140  201707-201712  전라남도  무안군  일반용    5566   83038877
141  201707-201712  전라남도  보성군  일반용    3579   36670928
142  201707-201712  전라남도  순천시  일반용   19850  270780199
143  201707-201712  전라남도  신안군  일반용    3490   30475049
144  201707-201712  전라남도  여수시  일반용   22306  292902966
145  201707-201712  전라남도  영광군  일반용    4744   50670571
146  201707-201712  전라남도  영암군  일반용    4188   55422644
147  201707-201712  전라남도  완도군  일반용    5354   48809729
148  201707-201712  전라남도  장성군  일반용    3314   44336519
149  201707-201712  전라남도  장흥군  일반용    3344   37917185
150  201707-201712  전라남도  진도군  일반용    2841   25627554
151  201707-201712  전라남도  함평군  일반용    2293   25523434
152  201707-201712  전라남도  해남군  일반용    5999   68410544
153  201707-201712  전라남도  화순군  일반용    4324   71807742

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  201707-201712  전라남도  강진군  일반용    3003    31132765
132  201707-201712  전라남도  강진군   합계    6681   159449274
133  201707-201712  전라남도  고흥군  일반용    5477    50532511
133  201707-201712  전라남도  고흥군   합계   13513   220341036
134  201707-201712  전라남도  곡성군  일반용    2113    22469775
134  201707-201712  전라남도  곡성군   합계    5773   206822373
135  201707-201712  전라남도  광양시  일반용   10821   133951177
135  201707-201712  전라남도  광양시   합계   12994  2735257617
136  201707-201712  전라남도  구례군  일반용    2544    31032084
136  201707-201712  전라남도  구례군   합계    5078    86067876
137  201707-201712  전라남도  나주시  일반용    7016   136529477
137  201707-201712  전라남도  나주시   합계   12954   602851853
138  201707-201712  전라남도  담양군  일반용    3706    54616162
138  201707-201712  전라남도  담양군   합계    7582   243924160
139  201707-201712  전라남도  목포시   합계   16072   498106903
139  201707-201712  전라남도  목포시  일반용   18838   251276557
140  201707-201712  전라남도  무안군   합계   10871   321150985
140  201707-201712  전라남도  무안군  일반용    5566    83038877
141  201707-201712  전라남도  보성군   합계    8633   148137513
141  201707-201712  전라남도  보성군  일반용    3579    36670928
142  201707-201712  전라남도  순천시   합계   23721   968674630
142  201707-201712  전라남도  순천시  일반용   19850   270780199
143  201707-201712  전라남도  신안군   합계    8456   145834249
143  201707-201712  전라남도  신안군  일반용    3490    30475049
144  201707-201712  전라남도  여수시   합계   25760  7687908136
144  201707-201712  전라남도  여수시  일반용   22306   292902966
145  201707-201712  전라남도  영광군   합계    8176   418056600
145  201707-201712  전라남도  영광군  일반용    4744    50670571
146  201707-201712  전라남도  영암군   합계    9360   528753736
146  201707-201712  전라남도  영암군  일반용    4188    55422644
147  201707-201712  전라남도  완도군   합계    8075   493262906
147  201707-201712  전라남도  완도군  일반용    5354    48809729
148  201707-201712  전라남도  장성군  일반용    3314    44336519
148  201707-201712  전라남도  장성군   합계    6521   307552910
149  201707-201712  전라남도  장흥군   합계    6649   166253493
149  201707-201712  전라남도  장흥군  일반용    3344    37917185
150  201707-201712  전라남도  진도군   합계    6389   152345655
150  201707-201712  전라남도  진도군  일반용    2841    25627554
151  201707-201712  전라남도  함평군   합계    6246   185494068
151  201707-201712  전라남도  함평군  일반용    2293    25523434
152  201707-201712  전라남도  해남군   합계   13548   329563680
152  201707-201712  전라남도  해남군  일반용    5999    68410544
153  201707-201712  전라남도  화순군  일반용    4324    71807742
153  201707-201712  전라남도  화순군   합계    8267   244631983

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[31132765,
 50532511,
 22469775,
 133951177,
 31032084,
 136529477,
 54616162,
 251276557,
 83038877,
 36670928,
 270780199,
 30475049,
 292902966,
 50670571,
 55422644,
 48809729,
 44336519,
 37917185,
 25627554,
 25523434,
 68410544,
 71807742]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[159449274,
 220341036,
 206822373,
 2735257617,
 86067876,
 602851853,
 243924160,
 498106903,
 321150985,
 148137513,
 968674630,
 145834249,
 7687908136,
 418056600,
 528753736,
 493262906,
 307552910,
 166253493,
 152345655,
 185494068,
 329563680,
 244631983]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[19.53, 22.93, 10.86, 4.9, 36.06, 22.65, 22.39, 50.45, 25.86, 24.75, 27.95, 20.9, 3.81, 12.12, 10.48, 9.9, 14.42, 22.81, 16.82, 13.76, 20.76, 29.35]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    20
1    23
2    11
3     5
4    36
5    23
6    22
7    50
8    26
9    25
10   28
11   21
12    4
13   12
14   10
15   10
16   14
17   23
18   17
19   14
20   21
21   29
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강진군  일반용  20
1   고흥군  일반용  23
2   곡성군  일반용  11
3   광양시  일반용   5
4   구례군  일반용  36
5   나주시  일반용  23
6   담양군  일반용  22
7   목포시  일반용  50
8   무안군  일반용  26
9   보성군  일반용  25
10  순천시  일반용  28
11  신안군  일반용  21
12  여수시  일반용   4
13  영광군  일반용  12
14  영암군  일반용  10
15  완도군  일반용  10
16  장성군  일반용  14
17  장흥군  일반용  23
18  진도군  일반용  17
19  함평군  일반용  14
20  해남군  일반용  21
21  화순군  일반용  29

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201707-201712  전라남도  강진군  일반용    3003    31132765  20
1   201707-201712  전라남도  강진군   합계    6681   159449274 NaN
2   201707-201712  전라남도  고흥군  일반용    5477    50532511  23
3   201707-201712  전라남도  고흥군   합계   13513   220341036 NaN
4   201707-201712  전라남도  곡성군  일반용    2113    22469775  11
5   201707-201712  전라남도  곡성군   합계    5773   206822373 NaN
6   201707-201712  전라남도  광양시  일반용   10821   133951177   5
7   201707-201712  전라남도  광양시   합계   12994  2735257617 NaN
8   201707-201712  전라남도  구례군  일반용    2544    31032084  36
9   201707-201712  전라남도  구례군   합계    5078    86067876 NaN
10  201707-201712  전라남도  나주시  일반용    7016   136529477  23
11  201707-201712  전라남도  나주시   합계   12954   602851853 NaN
12  201707-201712  전라남도  담양군  일반용    3706    54616162  22
13  201707-201712  전라남도  담양군   합계    7582   243924160 NaN
15  201707-201712  전라남도  목포시  일반용   18838   251276557  50
14  201707-201712  전라남도  목포시   합계   16072   498106903 NaN
17  201707-201712  전라남도  무안군  일반용    5566    83038877  26
16  201707-201712  전라남도  무안군   합계   10871   321150985 NaN
19  201707-201712  전라남도  보성군  일반용    3579    36670928  25
18  201707-201712  전라남도  보성군   합계    8633   148137513 NaN
21  201707-201712  전라남도  순천시  일반용   19850   270780199  28
20  201707-201712  전라남도  순천시   합계   23721   968674630 NaN
23  201707-201712  전라남도  신안군  일반용    3490    30475049  21
22  201707-201712  전라남도  신안군   합계    8456   145834249 NaN
25  201707-201712  전라남도  여수시  일반용   22306   292902966   4
24  201707-201712  전라남도  여수시   합계   25760  7687908136 NaN
27  201707-201712  전라남도  영광군  일반용    4744    50670571  12
26  201707-201712  전라남도  영광군   합계    8176   418056600 NaN
29  201707-201712  전라남도  영암군  일반용    4188    55422644  10
28  201707-201712  전라남도  영암군   합계    9360   528753736 NaN
31  201707-201712  전라남도  완도군  일반용    5354    48809729  10
30  201707-201712  전라남도  완도군   합계    8075   493262906 NaN
32  201707-201712  전라남도  장성군  일반용    3314    44336519  14
33  201707-201712  전라남도  장성군   합계    6521   307552910 NaN
35  201707-201712  전라남도  장흥군  일반용    3344    37917185  23
34  201707-201712  전라남도  장흥군   합계    6649   166253493 NaN
37  201707-201712  전라남도  진도군  일반용    2841    25627554  17
36  201707-201712  전라남도  진도군   합계    6389   152345655 NaN
39  201707-201712  전라남도  함평군  일반용    2293    25523434  14
38  201707-201712  전라남도  함평군   합계    6246   185494068 NaN
41  201707-201712  전라남도  해남군  일반용    5999    68410544  21
40  201707-201712  전라남도  해남군   합계   13548   329563680 NaN
42  201707-201712  전라남도  화순군  일반용    4324    71807742  29
43  201707-201712  전라남도  화순군   합계    8267   244631983 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1707-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)