In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('부산광역시_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 부산광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,부산광역시,전체(시 / 군 / 구),주택용,"933,834","418,866,344","58,263,132,816",139.1
4,201501,부산광역시,전체(시 / 군 / 구),일반용,"182,444","581,157,189","77,711,472,318",133.7
...,...,...,...,...,...,...,...,...
811,201506,부산광역시,해운대구,산업용,987,"21,471,678","2,622,437,371",122.1
812,201506,부산광역시,해운대구,심 야,"1,096","2,407,107","144,778,748",60.1
813,201506,부산광역시,해운대구,일반용,"13,706","65,543,704","9,032,189,194",137.8
814,201506,부산광역시,해운대구,주택용,"71,320","49,562,379","6,144,319,001",124
815,201506,부산광역시,해운대구,합계,"92,174","143,126,564","18,462,537,838",129

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,부산광역시,전체(시 / 군 / 구),주택용,"933,834","418,866,344","58,263,132,816",139.1
4,201501,부산광역시,전체(시 / 군 / 구),일반용,"182,444","581,157,189","77,711,472,318",133.7
5,201501,부산광역시,전체(시 / 군 / 구),교육용,"1,153","45,413,729","5,121,539,460",112.8
6,201501,부산광역시,전체(시 / 군 / 구),산업용,"24,513","723,831,996","90,865,027,627",125.5
...,...,...,...,...,...,...,...,...
811,201506,부산광역시,해운대구,산업용,987,"21,471,678","2,622,437,371",122.1
812,201506,부산광역시,해운대구,심 야,"1,096","2,407,107","144,778,748",60.1
813,201506,부산광역시,해운대구,일반용,"13,706","65,543,704","9,032,189,194",137.8
814,201506,부산광역시,해운대구,주택용,"71,320","49,562,379","6,144,319,001",124
815,201506,부산광역시,해운대구,합계,"92,174","143,126,564","18,462,537,838",129

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,부산광역시,전체(시 / 군 / 구),주택용,"933,834","418,866,344","58,263,132,816",139.1
4,201501,부산광역시,전체(시 / 군 / 구),일반용,"182,444","581,157,189","77,711,472,318",133.7
5,201501,부산광역시,전체(시 / 군 / 구),교육용,"1,153","45,413,729","5,121,539,460",112.8
6,201501,부산광역시,전체(시 / 군 / 구),산업용,"24,513","723,831,996","90,865,027,627",125.5
7,201501,부산광역시,전체(시 / 군 / 구),농사용,"9,637","13,446,105","638,261,728",47.5
...,...,...,...,...,...,...,...,...
811,201506,부산광역시,해운대구,산업용,987,"21,471,678","2,622,437,371",122.1
812,201506,부산광역시,해운대구,심 야,"1,096","2,407,107","144,778,748",60.1
813,201506,부산광역시,해운대구,일반용,"13,706","65,543,704","9,032,189,194",137.8
814,201506,부산광역시,해운대구,주택용,"71,320","49,562,379","6,144,319,001",124
815,201506,부산광역시,해운대구,합계,"92,174","143,126,564","18,462,537,838",129

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,부산광역시,전체(시 / 군 / 구),주택용,"933,834","418,866,344","58,263,132,816",139.1
4,201501,부산광역시,전체(시 / 군 / 구),일반용,"182,444","581,157,189","77,711,472,318",133.7
5,201501,부산광역시,전체(시 / 군 / 구),교육용,"1,153","45,413,729","5,121,539,460",112.8
6,201501,부산광역시,전체(시 / 군 / 구),산업용,"24,513","723,831,996","90,865,027,627",125.5
7,201501,부산광역시,전체(시 / 군 / 구),농사용,"9,637","13,446,105","638,261,728",47.5
8,201501,부산광역시,전체(시 / 군 / 구),가로등,"77,109","16,896,108","1,776,860,613",105.2
9,201501,부산광역시,전체(시 / 군 / 구),심 야,"25,382","63,079,701","4,797,953,494",76.1
10,201502,부산광역시,전체(시 / 군 / 구),주택용,"935,033","412,153,686","56,262,024,705",136.5
11,201502,부산광역시,전체(시 / 군 / 구),일반용,"182,732","548,715,634","74,199,104,720",135.2
12,201502,부산광역시,전체(시 / 군 / 구),교육용,"1,156","42,429,805","4,866,918,883",114.7
13,201502,부산광역시,전체(시 / 군 / 구),산업용,"24,564","644,492,437","82,469,494,434",128.0
14,201502,부산광역시,전체(시 / 군 / 구),농사용,"9,654","12,662,763","599,809,074",47.4
15,201502,부산광역시,전체(시 / 군 / 구),가로등,"77,376","16,517,215","1,800,425,992",109.0
16,201502,부산광역시,전체(시 / 군 / 구),심 야,"25,326","59,844,191","4,549,456,702",76.0
17,201503,부산광역시,전체(시 / 군 / 구),주택용,"935,451","364,421,699","44,182,301,894",121.2
18,201503,부산광역시,전체(시 / 군 / 구),일반용,"182,366","490,690,754","60,715,367,876",123.7
19,201503,부산광역시,전체(시 / 군 / 구),교육용,"1,157","40,999,669","4,190,709,992",102.2
20,201503,부산광역시,전체(시 / 군 / 구),산업용,"24,576","684,234,938","73,008,105,274",106.7
21,201503,부산광역시,전체(시 / 군 / 구),농사용,"9,792","10,332,159","498,551,300",48.3
22,201503,부산광역시,전체(시 / 군 / 구),가로등,"77,418","15,410,469","1,690,943,507",109.7
23,201503,부산광역시,전체(시 / 군 / 구),심 야,"25,266","49,855,037","3,324,736,610",66.7
24,201504,부산광역시,전체(시 / 군 / 구),주택용,"936,015","379,341,317","47,209,195,402",124.5
25,201504,부산광역시,전체(시 / 군 / 구),일반용,"182,518","479,050,404","55,040,446,365",114.9
26,201504,부산광역시,전체(시 / 군 / 구),교육용,"1,157","39,114,496","3,748,083,929",95.8
27,201504,부산광역시,전체(시 / 군 / 구),산업용,"24,596","710,065,593","73,258,521,978",103.2
28,201504,부산광역시,전체(시 / 군 / 구),농사용,"9,732","8,776,874","441,299,187",50.3
29,201504,부산광역시,전체(시 / 군 / 구),가로등,"77,580","14,212,565","1,611,619,482",113.4
30,201504,부산광역시,전체(시 / 군 / 구),심 야,"25,188","40,728,886","2,264,112,196",55.6
31,201505,부산광역시,전체(시 / 군 / 구),주택용,"936,636","348,583,881","40,322,363,028",115.7
32,201505,부산광역시,전체(시 / 군 / 구),일반용,"182,409","455,417,130","53,081,598,899",116.6
33,201505,부산광역시,전체(시 / 군 / 구),교육용,"1,156","30,096,027","3,196,639,608",106.2
34,201505,부산광역시,전체(시 / 군 / 구),산업용,"24,610","672,772,428","69,481,842,257",103.3
35,201505,부산광역시,전체(시 / 군 / 구),농사용,"9,726","7,263,252","380,314,936",52.4
36,201505,부산광역시,전체(시 / 군 / 구),가로등,"77,747","13,633,604","1,575,226,128",115.5
37,201505,부산광역시,전체(시 / 군 / 구),심 야,"25,075","26,695,183","1,515,210,666",56.8
38,201506,부산광역시,전체(시 / 군 / 구),주택용,"937,618","349,098,385","40,739,052,744",116.7
39,201506,부산광역시,전체(시 / 군 / 구),일반용,"182,507","474,991,498","64,621,140,619",136.0
40,201506,부산광역시,전체(시 / 군 / 구),교육용,"1,156","31,971,995","3,936,275,313",123.1
41,201506,부산광역시,전체(시 / 군 / 구),산업용,"24,667","683,903,022","86,147,414,713",126.0
42,201506,부산광역시,전체(시 / 군 / 구),농사용,"9,773","7,296,848","374,797,092",51.4
43,201506,부산광역시,전체(시 / 군 / 구),가로등,"77,969","12,696,666","1,512,877,911",119.2
44,201506,부산광역시,전체(시 / 군 / 구),심 야,"24,959","19,098,774","1,122,188,337",58.8
45,합계,합계,합계,합계,"7,538,733","10,060,260,456","1,203,112,419,809",119.6

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_4140\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201501  부산광역시  일반용  182,444   581,157,189
11  201502  부산광역시  일반용  182,732   548,715,634
18  201503  부산광역시  일반용  182,366   490,690,754
25  201504  부산광역시  일반용  182,518   479,050,404
32  201505  부산광역시  일반용  182,409   455,417,130
39  201506  부산광역시  일반용  182,507   474,991,498

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  부산광역시   강서구  일반용   7,600   24,758,797
181  201502  부산광역시   강서구  일반용   7,712   23,366,364
309  201503  부산광역시   강서구  일반용   7,715   20,979,427
437  201504  부산광역시   강서구  일반용   7,789   20,809,740
565  201505  부산광역시   강서구  일반용   7,783   19,589,707
..      ...    ...   ...  ...      ...          ...
301  201502  부산광역시  해운대구  일반용  13,676   70,718,907
429  201503  부산광역시  해운대구  일반용  13,667   66,225,187
557  201504  부산광역시  해운대구  일반용  13,696   63,398,880
685  201505  부산광역시  해운대구  일반용  13,678   62,857,782
813  201506  부산광역시  해운대구  일반용  13,706   65,543,704

[96 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'부산광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강서구',
 '금정구',
 '기장군',
 '남구',
 '동구',
 '동래구',
 '부산진구',
 '북구',
 '사상구',
 '사하구',
 '서구',
 '수영구',
 '연제구',
 '영도구',
 '중구',
 '해운대구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
55   201501  부산광역시   강서구   합계  43,666   306,913,959
183  201502  부산광역시   강서구   합계  43,970   272,890,904
311  201503  부산광역시   강서구   합계  44,173   285,911,665
439  201504  부산광역시   강서구   합계  44,303   290,709,720
567  201505  부산광역시   강서구   합계  44,350   271,221,352
..      ...    ...   ...  ...      ...           ...
303  201502  부산광역시  해운대구   합계  91,909   155,310,307
431  201503  부산광역시  해운대구   합계  91,933   145,288,854
559  201504  부산광역시  해운대구   합계  92,022   144,027,301
687  201505  부산광역시  해운대구   합계  92,019   139,853,027
815  201506  부산광역시  해운대구   합계  92,174   143,126,564

[96 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[306913959, 272890904, 285911665, 290709720, 271221352, 271322199]
[103430226, 99225731, 88505744, 88705747, 80414851, 81957200]
[99303546, 91514828, 90141000, 90921087, 86013627, 78731888]
[125251287, 118637140, 114190418, 112775077, 107644638, 108952317]
[49905526, 47245459, 42704947, 41540179, 38046953, 39219263]
[89378950, 86055736, 75583807, 73572586, 66826600, 68530975]
[156601848, 149006030, 134751539, 132635941, 124207025, 128499948]
[83016186, 80532557, 71065241, 72245645, 66377687, 68894990]
[174433867, 167081495, 152833180, 157063798, 140170367, 146705675]
[242763567, 216482093, 226055133, 240390302, 227466115, 229197028]
[53474472, 48892068, 47228040, 46669418, 41918147, 45199570]
[54737609, 53244775, 46518506, 46206337, 41980349, 42704391]
[72267130, 69718923, 62188458, 61436325, 56670477, 58728989]
[44133910, 42426947, 38403052, 39269570, 34945685, 35395469]
[41016008, 38550738, 34575141, 33121102, 30704605, 31890722]
[166063081, 155310307, 145288854, 144027301, 139853027, 143126564]
부산광역시 지역별 합계 :  [1698969799, 542239499, 536625976, 687450877, 258662327, 459948654, 825702331, 442132306, 938288382, 1382354238, 283381715, 285391967, 381010302, 234574633, 209858316, 893669134]
부산광역시 고객호수 평균:  [7360, 17560, 7893, 17101, 8986, 16047, 23951, 12647, 13329, 18828, 10375, 11866, 12150, 9820, 6157, 15332]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0           201501  부산광역시   강서구   합계  43,666   306,913,959
1           201502  부산광역시   강서구   합계  43,970   272,890,904
2           201503  부산광역시   강서구   합계  44,173   285,911,665
3           201504  부산광역시   강서구   합계  44,303   290,709,720
4           201505  부산광역시   강서구   합계  44,350   271,221,352
..             ...    ...   ...  ...      ...           ...
107  201501-201506  부산광역시   수영구   합계    11866     285391967
108  201501-201506  부산광역시   연제구   합계    12150     381010302
109  201501-201506  부산광역시   영도구   합계     9820     234574633
110  201501-201506  부산광역시    중구   합계     6157     209858316
111  201501-201506  부산광역시  해운대구   합계    15332     893669134

[112 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201501-201506  부산광역시   강서구   합계    7360  1698969799
97   201501-201506  부산광역시   금정구   합계   17560   542239499
98   201501-201506  부산광역시   기장군   합계    7893   536625976
99   201501-201506  부산광역시    남구   합계   17101   687450877
100  201501-201506  부산광역시    동구   합계    8986   258662327
101  201501-201506  부산광역시   동래구   합계   16047   459948654
102  201501-201506  부산광역시  부산진구   합계   23951   825702331
103  201501-201506  부산광역시    북구   합계   12647   442132306
104  201501-201506  부산광역시   사상구   합계   13329   938288382
105  201501-201506  부산광역시   사하구   합계   18828  1382354238
106  201501-201506  부산광역시    서구   합계   10375   283381715
107  201501-201506  부산광역시   수영구   합계   11866   285391967
108  201501-201506  부산광역시   연제구   합계   12150   381010302
109  201501-201506  부산광역시   영도구   합계    9820   234574633
110  201501-201506  부산광역시    중구   합계    6157   209858316
111  201501-201506  부산광역시  해운대구   합계   15332   893669134

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  부산광역시   강서구  일반용   7,600   24,758,797
181  201502  부산광역시   강서구  일반용   7,712   23,366,364
309  201503  부산광역시   강서구  일반용   7,715   20,979,427
437  201504  부산광역시   강서구  일반용   7,789   20,809,740
565  201505  부산광역시   강서구  일반용   7,783   19,589,707
..      ...    ...   ...  ...      ...          ...
301  201502  부산광역시  해운대구  일반용  13,676   70,718,907
429  201503  부산광역시  해운대구  일반용  13,667   66,225,187
557  201504  부산광역시  해운대구  일반용  13,696   63,398,880
685  201505  부산광역시  해운대구  일반용  13,678   62,857,782
813  201506  부산광역시  해운대구  일반용  13,706   65,543,704

[96 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[24758797, 23366364, 20979427, 20809740, 19589707, 20601643]
[36401479, 34805096, 30108921, 29516278, 27350840, 28959199]
[27052144, 24965092, 25221969, 27214395, 27621861, 18297362]
[34768819, 33181992, 29603874, 28821344, 27695859, 30273390]
[26850878, 25336538, 22888910, 21910413, 20610224, 22055251]
[40674393, 38690533, 33568759, 32494164, 30434915, 32725673]
[74844467, 70811760, 63014416, 61138562, 59474489, 64306979]
[32675499, 31116665, 26801634, 26180253, 24529544, 26453551]
[40582186, 38186276, 33450196, 32492227, 29991215, 32173853]
[39065663, 37498948, 32022112, 31523606, 28787914, 30809965]
[19646178, 18488826, 16949639, 16465910, 15287609, 16166054]
[26977098, 25910843, 22603964, 21998765, 20291257, 21307711]
[35526592, 33874085, 29866726, 28907901, 27047518, 29430176]
[12573133, 12328772, 10752579, 10874536, 9822628, 10294143]
[31634194, 29434937, 26632441, 25303430, 24023768, 25592844]
[77125669, 70718907, 66225187, 63398880, 62857782, 65543704]
부산광역시 지역별 일반용 합계 :  [130105678, 187141813, 150372823, 184345278, 139652214, 208588437, 393590673, 167757146, 206875953, 199708208, 103004216, 139089638, 184652998, 66645791, 162621614, 405870129]
부산광역시 고객호수 평균:  [7731, 15113, 7181, 11809, 7626, 15562, 22869, 10520, 13436, 14185, 6648, 10236, 10889, 5924, 9079, 13681]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_4140\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분 고객호수(호)     사용량(kWh)
0           201501  부산광역시   강서구  일반용  7,600   24,758,797
1           201502  부산광역시   강서구  일반용  7,712   23,366,364
2           201503  부산광역시   강서구  일반용  7,715   20,979,427
3           201504  부산광역시   강서구  일반용  7,789   20,809,740
4           201505  부산광역시   강서구  일반용  7,783   19,589,707
..             ...    ...   ...  ...     ...          ...
107  201501-201506  부산광역시   수영구  일반용   10236    139089638
108  201501-201506  부산광역시   연제구  일반용   10889    184652998
109  201501-201506  부산광역시   영도구  일반용    5924     66645791
110  201501-201506  부산광역시    중구  일반용    9079    162621614
111  201501-201506  부산광역시  해운대구  일반용   13681    405870129

[112 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)   사용량(kWh)
96   201501-201506  부산광역시   강서구  일반용    7731  130105678
97   201501-201506  부산광역시   금정구  일반용   15113  187141813
98   201501-201506  부산광역시   기장군  일반용    7181  150372823
99   201501-201506  부산광역시    남구  일반용   11809  184345278
100  201501-201506  부산광역시    동구  일반용    7626  139652214
101  201501-201506  부산광역시   동래구  일반용   15562  208588437
102  201501-201506  부산광역시  부산진구  일반용   22869  393590673
103  201501-201506  부산광역시    북구  일반용   10520  167757146
104  201501-201506  부산광역시   사상구  일반용   13436  206875953
105  201501-201506  부산광역시   사하구  일반용   14185  199708208
106  201501-201506  부산광역시    서구  일반용    6648  103004216
107  201501-201506  부산광역시   수영구  일반용   10236  139089638
108  201501-201506  부산광역시   연제구  일반용   10889  184652998
109  201501-201506  부산광역시   영도구  일반용    5924   66645791
110  201501-201506  부산광역시    중구  일반용    9079  162621614
111  201501-201506  부산광역시  해운대구  일반용   13681  405870129

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201501-201506  부산광역시   강서구  일반용    7731   130105678
96   201501-201506  부산광역시   강서구   합계    7360  1698969799
97   201501-201506  부산광역시   금정구   합계   17560   542239499
97   201501-201506  부산광역시   금정구  일반용   15113   187141813
98   201501-201506  부산광역시   기장군   합계    7893   536625976
98   201501-201506  부산광역시   기장군  일반용    7181   150372823
99   201501-201506  부산광역시    남구  일반용   11809   184345278
99   201501-201506  부산광역시    남구   합계   17101   687450877
100  201501-201506  부산광역시    동구  일반용    7626   139652214
100  201501-201506  부산광역시    동구   합계    8986   258662327
101  201501-201506  부산광역시   동래구  일반용   15562   208588437
101  201501-201506  부산광역시   동래구   합계   16047   459948654
102  201501-201506  부산광역시  부산진구  일반용   22869   393590673
102  201501-201506  부산광역시  부산진구   합계   23951   825702331
103  201501-201506  부산광역시    북구  일반용   10520   167757146
103  201501-201506  부산광역시    북구   합계   12647   442132306
104  201501-201506  부산광역시   사상구   합계   13329   938288382
104  201501-201506  부산광역시   사상구  일반용   13436   206875953
105  201501-201506  부산광역시   사하구   합계   18828  1382354238
105  201501-201506  부산광역시   사하구  일반용   14185   199708208
106  201501-201506  부산광역시    서구  일반용    6648   103004216
106  201501-201506  부산광역시    서구   합계   10375   283381715
107  201501-201506  부산광역시   수영구   합계   11866   285391967
107  201501-201506  부산광역시   수영구  일반용   10236   139089638
108  201501-201506  부산광역시   연제구   합계   12150   381010302
108  201501-201506  부산광역시   연제구  일반용   10889   184652998
109  201501-201506  부산광역시   영도구   합계    9820   234574633
109  201501-201506  부산광역시   영도구  일반용    5924    66645791
110  201501-201506  부산광역시    중구   합계    6157   209858316
110  201501-201506  부산광역시    중구  일반용    9079   162621614
111  201501-201506  부산광역시  해운대구  일반용   13681   405870129
111  201501-201506  부산광역시  해운대구   합계   15332   893669134

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[130105678,
 187141813,
 150372823,
 184345278,
 139652214,
 208588437,
 393590673,
 167757146,
 206875953,
 199708208,
 103004216,
 139089638,
 184652998,
 66645791,
 162621614,
 405870129]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1698969799,
 542239499,
 536625976,
 687450877,
 258662327,
 459948654,
 825702331,
 442132306,
 938288382,
 1382354238,
 283381715,
 285391967,
 381010302,
 234574633,
 209858316,
 893669134]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[7.66, 34.51, 28.02, 26.82, 53.99, 45.35, 47.67, 37.94, 22.05, 14.45, 36.35, 48.74, 48.46, 28.41, 77.49, 45.42]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0     8
1    35
2    28
3    27
4    54
5    45
6    48
7    38
8    22
9    14
10   36
11   49
12   48
13   28
14   77
15   45
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강서구  일반용   8
1    금정구  일반용  35
2    기장군  일반용  28
3     남구  일반용  27
4     동구  일반용  54
5    동래구  일반용  45
6   부산진구  일반용  48
7     북구  일반용  38
8    사상구  일반용  22
9    사하구  일반용  14
10    서구  일반용  36
11   수영구  일반용  49
12   연제구  일반용  48
13   영도구  일반용  28
14    중구  일반용  77
15  해운대구  일반용  45

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201501-201506  부산광역시   강서구  일반용    7731   130105678   8
1   201501-201506  부산광역시   강서구   합계    7360  1698969799 NaN
3   201501-201506  부산광역시   금정구  일반용   15113   187141813  35
2   201501-201506  부산광역시   금정구   합계   17560   542239499 NaN
5   201501-201506  부산광역시   기장군  일반용    7181   150372823  28
4   201501-201506  부산광역시   기장군   합계    7893   536625976 NaN
6   201501-201506  부산광역시    남구  일반용   11809   184345278  27
7   201501-201506  부산광역시    남구   합계   17101   687450877 NaN
8   201501-201506  부산광역시    동구  일반용    7626   139652214  54
9   201501-201506  부산광역시    동구   합계    8986   258662327 NaN
10  201501-201506  부산광역시   동래구  일반용   15562   208588437  45
11  201501-201506  부산광역시   동래구   합계   16047   459948654 NaN
12  201501-201506  부산광역시  부산진구  일반용   22869   393590673  48
13  201501-201506  부산광역시  부산진구   합계   23951   825702331 NaN
14  201501-201506  부산광역시    북구  일반용   10520   167757146  38
15  201501-201506  부산광역시    북구   합계   12647   442132306 NaN
17  201501-201506  부산광역시   사상구  일반용   13436   206875953  22
16  201501-201506  부산광역시   사상구   합계   13329   938288382 NaN
19  201501-201506  부산광역시   사하구  일반용   14185   199708208  14
18  201501-201506  부산광역시   사하구   합계   18828  1382354238 NaN
20  201501-201506  부산광역시    서구  일반용    6648   103004216  36
21  201501-201506  부산광역시    서구   합계   10375   283381715 NaN
23  201501-201506  부산광역시   수영구  일반용   10236   139089638  49
22  201501-201506  부산광역시   수영구   합계   11866   285391967 NaN
25  201501-201506  부산광역시   연제구  일반용   10889   184652998  48
24  201501-201506  부산광역시   연제구   합계   12150   381010302 NaN
27  201501-201506  부산광역시   영도구  일반용    5924    66645791  28
26  201501-201506  부산광역시   영도구   합계    9820   234574633 NaN
29  201501-201506  부산광역시    중구  일반용    9079   162621614  77
28  201501-201506  부산광역시    중구   합계    6157   209858316 NaN
30  201501-201506  부산광역시  해운대구  일반용   13681   405870129  45
31  201501-201506  부산광역시  해운대구   합계   15332   893669134 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)