In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라북도_계약종별_전력사용량_월별_20상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라북도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2020년 01 월 ~ 2020년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202001,전라북도,전체(시 / 군 / 구),주택용,"666,061","223,237,706","24,812,166,067",111.1
4,202001,전라북도,전체(시 / 군 / 구),일반용,"142,093","361,499,118","48,262,553,963",133.5
...,...,...,...,...,...,...,...,...
715,202006,전라북도,진안군,산업용,902,"2,700,224","381,035,710",141.1
716,202006,전라북도,진안군,심 야,"1,813","976,214","52,962,395",54.3
717,202006,전라북도,진안군,일반용,"2,266","3,226,403","459,228,593",142.3
718,202006,전라북도,진안군,주택용,"14,564","2,250,641","265,108,695",117.8
719,202006,전라북도,진안군,합계,"31,689","13,976,049","1,487,676,250",106.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202001,전라북도,전체(시 / 군 / 구),주택용,"666,061","223,237,706","24,812,166,067",111.1
4,202001,전라북도,전체(시 / 군 / 구),일반용,"142,093","361,499,118","48,262,553,963",133.5
5,202001,전라북도,전체(시 / 군 / 구),교육용,"1,246","37,587,709","3,895,989,484",103.7
6,202001,전라북도,전체(시 / 군 / 구),산업용,"15,656","1,107,130,834","122,532,481,540",110.7
...,...,...,...,...,...,...,...,...
715,202006,전라북도,진안군,산업용,902,"2,700,224","381,035,710",141.1
716,202006,전라북도,진안군,심 야,"1,813","976,214","52,962,395",54.3
717,202006,전라북도,진안군,일반용,"2,266","3,226,403","459,228,593",142.3
718,202006,전라북도,진안군,주택용,"14,564","2,250,641","265,108,695",117.8
719,202006,전라북도,진안군,합계,"31,689","13,976,049","1,487,676,250",106.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202001,전라북도,전체(시 / 군 / 구),주택용,"666,061","223,237,706","24,812,166,067",111.1
4,202001,전라북도,전체(시 / 군 / 구),일반용,"142,093","361,499,118","48,262,553,963",133.5
5,202001,전라북도,전체(시 / 군 / 구),교육용,"1,246","37,587,709","3,895,989,484",103.7
6,202001,전라북도,전체(시 / 군 / 구),산업용,"15,656","1,107,130,834","122,532,481,540",110.7
7,202001,전라북도,전체(시 / 군 / 구),농사용,"154,162","157,404,672","7,631,486,097",48.5
...,...,...,...,...,...,...,...,...
715,202006,전라북도,진안군,산업용,902,"2,700,224","381,035,710",141.1
716,202006,전라북도,진안군,심 야,"1,813","976,214","52,962,395",54.3
717,202006,전라북도,진안군,일반용,"2,266","3,226,403","459,228,593",142.3
718,202006,전라북도,진안군,주택용,"14,564","2,250,641","265,108,695",117.8
719,202006,전라북도,진안군,합계,"31,689","13,976,049","1,487,676,250",106.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202001,전라북도,전체(시 / 군 / 구),주택용,"666,061","223,237,706","24,812,166,067",111.1
4,202001,전라북도,전체(시 / 군 / 구),일반용,"142,093","361,499,118","48,262,553,963",133.5
5,202001,전라북도,전체(시 / 군 / 구),교육용,"1,246","37,587,709","3,895,989,484",103.7
6,202001,전라북도,전체(시 / 군 / 구),산업용,"15,656","1,107,130,834","122,532,481,540",110.7
7,202001,전라북도,전체(시 / 군 / 구),농사용,"154,162","157,404,672","7,631,486,097",48.5
8,202001,전라북도,전체(시 / 군 / 구),가로등,"143,711","19,152,559","1,994,228,604",104.1
9,202001,전라북도,전체(시 / 군 / 구),심 야,"60,665","116,679,675","8,622,025,511",73.9
10,202002,전라북도,전체(시 / 군 / 구),주택용,"666,812","226,650,895","25,464,548,992",112.4
11,202002,전라북도,전체(시 / 군 / 구),일반용,"142,293","349,254,413","47,073,934,799",134.8
12,202002,전라북도,전체(시 / 군 / 구),교육용,"1,246","33,941,441","3,688,034,810",108.7
13,202002,전라북도,전체(시 / 군 / 구),산업용,"15,646","1,001,199,371","114,656,938,738",114.5
14,202002,전라북도,전체(시 / 군 / 구),농사용,"154,046","156,111,161","7,573,591,946",48.5
15,202002,전라북도,전체(시 / 군 / 구),가로등,"144,004","18,145,394","1,987,028,134",109.5
16,202002,전라북도,전체(시 / 군 / 구),심 야,"60,513","117,931,123","8,727,093,413",74.0
17,202003,전라북도,전체(시 / 군 / 구),주택용,"667,512","207,538,917","22,287,435,821",107.4
18,202003,전라북도,전체(시 / 군 / 구),일반용,"142,335","301,695,176","38,838,689,378",128.7
19,202003,전라북도,전체(시 / 군 / 구),교육용,"1,246","26,946,596","2,865,853,681",106.4
20,202003,전라북도,전체(시 / 군 / 구),산업용,"15,666","949,501,952","90,221,520,199",95.0
21,202003,전라북도,전체(시 / 군 / 구),농사용,"227,359","141,918,814","6,923,281,343",48.8
22,202003,전라북도,전체(시 / 군 / 구),가로등,"144,250","17,237,153","1,916,870,454",111.2
23,202003,전라북도,전체(시 / 군 / 구),심 야,"60,380","95,244,311","6,277,119,207",65.9
24,202004,전라북도,전체(시 / 군 / 구),주택용,"668,479","211,698,231","23,564,562,306",111.3
25,202004,전라북도,전체(시 / 군 / 구),일반용,"142,562","280,518,029","33,268,095,700",118.6
26,202004,전라북도,전체(시 / 군 / 구),교육용,"1,245","22,635,142","2,181,491,417",96.4
27,202004,전라북도,전체(시 / 군 / 구),산업용,"15,707","898,986,492","82,894,809,968",92.2
28,202004,전라북도,전체(시 / 군 / 구),농사용,"193,481","133,573,130","6,531,087,949",48.9
29,202004,전라북도,전체(시 / 군 / 구),가로등,"144,745","16,933,986","1,969,697,670",116.3
30,202004,전라북도,전체(시 / 군 / 구),심 야,"60,238","78,054,192","4,196,259,464",53.8
31,202005,전라북도,전체(시 / 군 / 구),주택용,"669,242","198,668,007","21,156,455,317",106.5
32,202005,전라북도,전체(시 / 군 / 구),일반용,"142,554","260,268,498","31,883,309,578",122.5
33,202005,전라북도,전체(시 / 군 / 구),교육용,"1,242","18,524,021","1,885,601,074",101.8
34,202005,전라북도,전체(시 / 군 / 구),산업용,"15,752","879,133,324","80,468,748,650",91.5
35,202005,전라북도,전체(시 / 군 / 구),농사용,"156,807","122,194,222","5,955,713,548",48.7
36,202005,전라북도,전체(시 / 군 / 구),가로등,"144,984","15,747,964","1,899,633,314",120.6
37,202005,전라북도,전체(시 / 군 / 구),심 야,"60,035","52,902,518","2,858,846,128",54.0
38,202006,전라북도,전체(시 / 군 / 구),주택용,"670,416","200,459,152","21,112,829,808",105.3
39,202006,전라북도,전체(시 / 군 / 구),일반용,"142,856","284,697,221","39,048,965,229",137.2
40,202006,전라북도,전체(시 / 군 / 구),교육용,"1,244","22,459,117","2,764,263,648",123.1
41,202006,전라북도,전체(시 / 군 / 구),산업용,"15,786","847,588,043","99,226,281,948",117.1
42,202006,전라북도,전체(시 / 군 / 구),농사용,"157,715","134,846,628","6,300,556,508",46.7
43,202006,전라북도,전체(시 / 군 / 구),가로등,"145,681","15,129,869","1,888,075,267",124.8
44,202006,전라북도,전체(시 / 군 / 구),심 야,"59,794","28,376,297","1,571,119,347",55.4
45,합계,합계,합계,합계,"7,237,467","10,389,403,073","1,068,879,276,019",102.9

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_6784\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   202001  전라북도  일반용  142,093   361,499,118
11  202002  전라북도  일반용  142,293   349,254,413
18  202003  전라북도  일반용  142,335   301,695,176
25  202004  전라북도  일반용  142,562   280,518,029
32  202005  전라북도  일반용  142,554   260,268,498
39  202006  전라북도  일반용  142,856   284,697,221

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53   202001  전라북도  고창군  일반용  4,795   10,664,559
165  202002  전라북도  고창군  일반용  4,782   10,352,712
277  202003  전라북도  고창군  일반용  4,786    8,887,635
389  202004  전라북도  고창군  일반용  4,799    8,587,755
501  202005  전라북도  고창군  일반용  4,800    7,968,019
..      ...   ...  ...  ...     ...          ...
269  202002  전라북도  진안군  일반용  2,257    4,729,075
381  202003  전라북도  진안군  일반용  2,257    3,954,785
493  202004  전라북도  진안군  일반용  2,268    3,518,352
605  202005  전라북도  진안군  일반용  2,261    3,139,257
717  202006  전라북도  진안군  일반용  2,266    3,226,403

[84 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라북도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['고창군',
 '군산시',
 '김제시',
 '남원시',
 '무주군',
 '부안군',
 '순창군',
 '완주군',
 '익산시',
 '임실군',
 '장수군',
 '전주시',
 '정읍시',
 '진안군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55   202001  전라북도  고창군   합계  59,155   58,041,956
167  202002  전라북도  고창군   합계  59,136   57,309,554
279  202003  전라북도  고창군   합계  62,446   52,378,546
391  202004  전라북도  고창군   합계  78,730   51,755,993
503  202005  전라북도  고창군   합계  59,603   46,485,711
..      ...   ...  ...  ...      ...          ...
271  202002  전라북도  진안군   합계  31,267   20,761,164
383  202003  전라북도  진안군   합계  33,620   18,443,360
495  202004  전라북도  진안군   합계  31,434   17,106,386
607  202005  전라북도  진안군   합계  31,519   14,713,795
719  202006  전라북도  진안군   합계  31,689   13,976,049

[84 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[58041956, 57309554, 52378546, 51755993, 46485711, 45503431]
[671168300, 580069864, 484229824, 448237781, 440396116, 396327345]
[100320488, 98187693, 91629309, 84743402, 75774352, 78836382]
[58444716, 57201607, 52715602, 51434139, 46680070, 47772202]
[24942400, 22632353, 18036490, 16291910, 14741241, 14405432]
[45290524, 44626088, 40538873, 38536331, 34285840, 35827040]
[23214040, 23180349, 21622728, 21083330, 19655996, 21042817]
[150000096, 146512727, 149406437, 138454307, 127560164, 136672916]
[275941391, 267411511, 257455877, 244458499, 229797808, 242213837]
[29551263, 29559756, 26628156, 24917367, 22481300, 21572587]
[23963700, 23428264, 20101667, 18326678, 15382521, 13901434]
[404036096, 392643627, 368864646, 354163114, 335680595, 340588988]
[136858946, 139709241, 138031404, 132889965, 123803045, 124915867]
[20918357, 20761164, 18443360, 17106386, 14713795, 13976049]
전라북도 지역별 합계 :  [311475191, 3020429230, 529491626, 314248336, 111049826, 239104696, 129799260, 848606647, 1517278923, 154710429, 115104264, 2195977066, 796208468, 105919111]
전라북도 고객호수 평균:  [10521, 23462, 13305, 13759, 4877, 9176, 6075, 11798, 28711, 5757, 4650, 46838, 16805, 5300]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\4200931704.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          202001  전라북도  고창군   합계  59,155   58,041,956
1          202002  전라북도  고창군   합계  59,136   57,309,554
2          202003  전라북도  고창군   합계  62,446   52,378,546
3          202004  전라북도  고창군   합계  78,730   51,755,993
4          202005  전라북도  고창군   합계  59,603   46,485,711
..            ...   ...  ...  ...      ...          ...
93  202001-202006  전라북도  임실군   합계     5757    154710429
94  202001-202006  전라북도  장수군   합계     4650    115104264
95  202001-202006  전라북도  전주시   합계    46838   2195977066
96  202001-202006  전라북도  정읍시   합계    16805    796208468
97  202001-202006  전라북도  진안군   합계     5300    105919111

[98 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '202001-202006']
Hap

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  202001-202006  전라북도  고창군   합계   10521   311475191
85  202001-202006  전라북도  군산시   합계   23462  3020429230
86  202001-202006  전라북도  김제시   합계   13305   529491626
87  202001-202006  전라북도  남원시   합계   13759   314248336
88  202001-202006  전라북도  무주군   합계    4877   111049826
89  202001-202006  전라북도  부안군   합계    9176   239104696
90  202001-202006  전라북도  순창군   합계    6075   129799260
91  202001-202006  전라북도  완주군   합계   11798   848606647
92  202001-202006  전라북도  익산시   합계   28711  1517278923
93  202001-202006  전라북도  임실군   합계    5757   154710429
94  202001-202006  전라북도  장수군   합계    4650   115104264
95  202001-202006  전라북도  전주시   합계   46838  2195977066
96  202001-202006  전라북도  정읍시   합계   16805   796208468
97  202001-202006  전라북도  진안군   합계    5300   105919111

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53   202001  전라북도  고창군  일반용  4,795   10,664,559
165  202002  전라북도  고창군  일반용  4,782   10,352,712
277  202003  전라북도  고창군  일반용  4,786    8,887,635
389  202004  전라북도  고창군  일반용  4,799    8,587,755
501  202005  전라북도  고창군  일반용  4,800    7,968,019
..      ...   ...  ...  ...     ...          ...
269  202002  전라북도  진안군  일반용  2,257    4,729,075
381  202003  전라북도  진안군  일반용  2,257    3,954,785
493  202004  전라북도  진안군  일반용  2,268    3,518,352
605  202005  전라북도  진안군  일반용  2,261    3,139,257
717  202006  전라북도  진안군  일반용  2,266    3,226,403

[84 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[10664559, 10352712, 8887635, 8587755, 7968019, 8141619]
[57688208, 55630921, 49300319, 46250974, 42698277, 46279654]
[15997308, 15708327, 13722638, 13008450, 11783898, 12287706]
[16288562, 15781329, 13567865, 12732811, 11512229, 12040800]
[12104275, 9808927, 6658304, 5551906, 5004842, 5099870]
[12844884, 12587848, 10797031, 10162182, 9470174, 9579477]
[4586788, 4454711, 3788658, 3511223, 3202029, 3451406]
[22388620, 21919979, 19468022, 18120566, 17403256, 19961561]
[49559054, 48292534, 41950060, 38898544, 35790036, 38799893]
[5811406, 5638507, 4889947, 4516255, 3999072, 4255630]
[4009263, 3914270, 3368773, 3123477, 2708122, 2733200]
[125371387, 121392575, 105003495, 97137832, 91602778, 103833333]
[19308844, 19042698, 16337644, 15397702, 13986509, 15006669]
[4875960, 4729075, 3954785, 3518352, 3139257, 3226403]
전라북도 지역별 일반용 합계 :  [54602299, 297848353, 82508327, 81923596, 44228124, 65441596, 22994815, 119262004, 253290121, 29110817, 19857105, 644341400, 99080066, 23443832]
전라북도 고객호수 평균:  [4796, 20572, 6606, 7586, 2797, 5742, 2346, 7653, 20719, 2337, 1809, 47840, 9382, 2258]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6784\1610350782.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202001-202006'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          202001  전라북도  고창군  일반용  4,795   10,664,559
1          202002  전라북도  고창군  일반용  4,782   10,352,712
2          202003  전라북도  고창군  일반용  4,786    8,887,635
3          202004  전라북도  고창군  일반용  4,799    8,587,755
4          202005  전라북도  고창군  일반용  4,800    7,968,019
..            ...   ...  ...  ...     ...          ...
93  202001-202006  전라북도  임실군  일반용    2337     29110817
94  202001-202006  전라북도  장수군  일반용    1809     19857105
95  202001-202006  전라북도  전주시  일반용   47840    644341400
96  202001-202006  전라북도  정읍시  일반용    9382     99080066
97  202001-202006  전라북도  진안군  일반용    2258     23443832

[98 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '202001-202006']
GyeonGiHap2

               년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
84  202001-202006  전라북도  고창군  일반용    4796   54602299
85  202001-202006  전라북도  군산시  일반용   20572  297848353
86  202001-202006  전라북도  김제시  일반용    6606   82508327
87  202001-202006  전라북도  남원시  일반용    7586   81923596
88  202001-202006  전라북도  무주군  일반용    2797   44228124
89  202001-202006  전라북도  부안군  일반용    5742   65441596
90  202001-202006  전라북도  순창군  일반용    2346   22994815
91  202001-202006  전라북도  완주군  일반용    7653  119262004
92  202001-202006  전라북도  익산시  일반용   20719  253290121
93  202001-202006  전라북도  임실군  일반용    2337   29110817
94  202001-202006  전라북도  장수군  일반용    1809   19857105
95  202001-202006  전라북도  전주시  일반용   47840  644341400
96  202001-202006  전라북도  정읍시  일반용    9382   99080066
97  202001-202006  전라북도  진안군  일반용    2258   23443832

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  202001-202006  전라북도  고창군  일반용    4796    54602299
84  202001-202006  전라북도  고창군   합계   10521   311475191
85  202001-202006  전라북도  군산시  일반용   20572   297848353
85  202001-202006  전라북도  군산시   합계   23462  3020429230
86  202001-202006  전라북도  김제시  일반용    6606    82508327
86  202001-202006  전라북도  김제시   합계   13305   529491626
87  202001-202006  전라북도  남원시  일반용    7586    81923596
87  202001-202006  전라북도  남원시   합계   13759   314248336
88  202001-202006  전라북도  무주군  일반용    2797    44228124
88  202001-202006  전라북도  무주군   합계    4877   111049826
89  202001-202006  전라북도  부안군  일반용    5742    65441596
89  202001-202006  전라북도  부안군   합계    9176   239104696
90  202001-202006  전라북도  순창군  일반용    2346    22994815
90  202001-202006  전라북도  순창군   합계    6075   129799260
91  202001-202006  전라북도  완주군   합계   11798   848606647
91  202001-202006  전라북도  완주군  일반용    7653   119262004
92  202001-202006  전라북도  익산시  일반용   20719   253290121
92  202001-202006  전라북도  익산시   합계   28711  1517278923
93  202001-202006  전라북도  임실군   합계    5757   154710429
93  202001-202006  전라북도  임실군  일반용    2337    29110817
94  202001-202006  전라북도  장수군   합계    4650   115104264
94  202001-202006  전라북도  장수군  일반용    1809    19857105
95  202001-202006  전라북도  전주시   합계   46838  2195977066
95  202001-202006  전라북도  전주시  일반용   47840   644341400
96  202001-202006  전라북도  정읍시   합계   16805   796208468
96  202001-202006  전라북도  정읍시  일반용    9382    99080066
97  202001-202006  전라북도  진안군  일반용    2258    23443832
97  202001-202006  전라북도  진안군   합계    5300   105919111

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[54602299,
 297848353,
 82508327,
 81923596,
 44228124,
 65441596,
 22994815,
 119262004,
 253290121,
 29110817,
 19857105,
 644341400,
 99080066,
 23443832]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[311475191,
 3020429230,
 529491626,
 314248336,
 111049826,
 239104696,
 129799260,
 848606647,
 1517278923,
 154710429,
 115104264,
 2195977066,
 796208468,
 105919111]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[17.53, 9.86, 15.58, 26.07, 39.83, 27.37, 17.72, 14.05, 16.69, 18.82, 17.25, 29.34, 12.44, 22.13]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    18
1    10
2    16
3    26
4    40
5    27
6    18
7    14
8    17
9    19
10   17
11   29
12   12
13   22
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   고창군  일반용  18
1   군산시  일반용  10
2   김제시  일반용  16
3   남원시  일반용  26
4   무주군  일반용  40
5   부안군  일반용  27
6   순창군  일반용  18
7   완주군  일반용  14
8   익산시  일반용  17
9   임실군  일반용  19
10  장수군  일반용  17
11  전주시  일반용  29
12  정읍시  일반용  12
13  진안군  일반용  22

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   202001-202006  전라북도  고창군  일반용    4796    54602299  18
1   202001-202006  전라북도  고창군   합계   10521   311475191 NaN
2   202001-202006  전라북도  군산시  일반용   20572   297848353  10
3   202001-202006  전라북도  군산시   합계   23462  3020429230 NaN
4   202001-202006  전라북도  김제시  일반용    6606    82508327  16
5   202001-202006  전라북도  김제시   합계   13305   529491626 NaN
6   202001-202006  전라북도  남원시  일반용    7586    81923596  26
7   202001-202006  전라북도  남원시   합계   13759   314248336 NaN
8   202001-202006  전라북도  무주군  일반용    2797    44228124  40
9   202001-202006  전라북도  무주군   합계    4877   111049826 NaN
10  202001-202006  전라북도  부안군  일반용    5742    65441596  27
11  202001-202006  전라북도  부안군   합계    9176   239104696 NaN
12  202001-202006  전라북도  순창군  일반용    2346    22994815  18
13  202001-202006  전라북도  순창군   합계    6075   129799260 NaN
15  202001-202006  전라북도  완주군  일반용    7653   119262004  14
14  202001-202006  전라북도  완주군   합계   11798   848606647 NaN
16  202001-202006  전라북도  익산시  일반용   20719   253290121  17
17  202001-202006  전라북도  익산시   합계   28711  1517278923 NaN
19  202001-202006  전라북도  임실군  일반용    2337    29110817  19
18  202001-202006  전라북도  임실군   합계    5757   154710429 NaN
21  202001-202006  전라북도  장수군  일반용    1809    19857105  17
20  202001-202006  전라북도  장수군   합계    4650   115104264 NaN
23  202001-202006  전라북도  전주시  일반용   47840   644341400  29
22  202001-202006  전라북도  전주시   합계   46838  2195977066 NaN
25  202001-202006  전라북도  정읍시  일반용    9382    99080066  12
24  202001-202006  전라북도  정읍시   합계   16805   796208468 NaN
26  202001-202006  전라북도  진안군  일반용    2258    23443832  22
27  202001-202006  전라북도  진안군   합계    5300   105919111 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_2001-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)