In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라남도_계약종별_전력사용량_월별_22상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2022년 01 월 ~ 2022년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,전라남도,전체(시 / 군 / 구),주택용,"775,112","242,642,494","29,412,110,268",121.2
4,202201,전라남도,전체(시 / 군 / 구),일반용,"159,871","399,241,693","54,308,663,275",136.0
...,...,...,...,...,...,...,...,...
1099,202206,전라남도,화순군,산업용,902,"11,111,539","1,548,979,745",139.4
1100,202206,전라남도,화순군,심 야,"1,426","576,662","34,394,926",59.6
1101,202206,전라남도,화순군,일반용,"4,994","11,980,377","1,669,025,474",139.3
1102,202206,전라남도,화순군,주택용,"27,373","6,374,518","733,529,223",115.1
1103,202206,전라남도,화순군,합계,"57,622","39,111,113","4,630,272,753",118.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,전라남도,전체(시 / 군 / 구),주택용,"775,112","242,642,494","29,412,110,268",121.2
4,202201,전라남도,전체(시 / 군 / 구),일반용,"159,871","399,241,693","54,308,663,275",136.0
5,202201,전라남도,전체(시 / 군 / 구),교육용,"1,327","36,840,929","3,851,343,238",104.5
6,202201,전라남도,전체(시 / 군 / 구),산업용,"21,927","1,907,230,349","209,549,611,362",109.9
...,...,...,...,...,...,...,...,...
1099,202206,전라남도,화순군,산업용,902,"11,111,539","1,548,979,745",139.4
1100,202206,전라남도,화순군,심 야,"1,426","576,662","34,394,926",59.6
1101,202206,전라남도,화순군,일반용,"4,994","11,980,377","1,669,025,474",139.3
1102,202206,전라남도,화순군,주택용,"27,373","6,374,518","733,529,223",115.1
1103,202206,전라남도,화순군,합계,"57,622","39,111,113","4,630,272,753",118.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,전라남도,전체(시 / 군 / 구),주택용,"775,112","242,642,494","29,412,110,268",121.2
4,202201,전라남도,전체(시 / 군 / 구),일반용,"159,871","399,241,693","54,308,663,275",136.0
5,202201,전라남도,전체(시 / 군 / 구),교육용,"1,327","36,840,929","3,851,343,238",104.5
6,202201,전라남도,전체(시 / 군 / 구),산업용,"21,927","1,907,230,349","209,549,611,362",109.9
7,202201,전라남도,전체(시 / 군 / 구),농사용,"310,132","407,398,058","19,469,913,457",47.8
...,...,...,...,...,...,...,...,...
1099,202206,전라남도,화순군,산업용,902,"11,111,539","1,548,979,745",139.4
1100,202206,전라남도,화순군,심 야,"1,426","576,662","34,394,926",59.6
1101,202206,전라남도,화순군,일반용,"4,994","11,980,377","1,669,025,474",139.3
1102,202206,전라남도,화순군,주택용,"27,373","6,374,518","733,529,223",115.1
1103,202206,전라남도,화순군,합계,"57,622","39,111,113","4,630,272,753",118.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,전라남도,전체(시 / 군 / 구),주택용,"775,112","242,642,494","29,412,110,268",121.2
4,202201,전라남도,전체(시 / 군 / 구),일반용,"159,871","399,241,693","54,308,663,275",136.0
5,202201,전라남도,전체(시 / 군 / 구),교육용,"1,327","36,840,929","3,851,343,238",104.5
6,202201,전라남도,전체(시 / 군 / 구),산업용,"21,927","1,907,230,349","209,549,611,362",109.9
7,202201,전라남도,전체(시 / 군 / 구),농사용,"310,132","407,398,058","19,469,913,457",47.8
8,202201,전라남도,전체(시 / 군 / 구),가로등,"198,301","21,772,776","2,340,319,232",107.5
9,202201,전라남도,전체(시 / 군 / 구),심 야,"39,450","73,150,061","5,504,915,183",75.3
10,202202,전라남도,전체(시 / 군 / 구),주택용,"776,104","243,252,410","29,711,852,531",122.1
11,202202,전라남도,전체(시 / 군 / 구),일반용,"160,236","392,777,152","52,474,978,093",133.6
12,202202,전라남도,전체(시 / 군 / 구),교육용,"1,328","26,828,854","3,020,566,795",112.6
13,202202,전라남도,전체(시 / 군 / 구),산업용,"21,956","1,710,029,185","186,394,368,549",109.0
14,202202,전라남도,전체(시 / 군 / 구),농사용,"310,336","418,138,637","19,921,228,974",47.6
15,202202,전라남도,전체(시 / 군 / 구),가로등,"198,619","20,559,816","2,345,047,569",114.1
16,202202,전라남도,전체(시 / 군 / 구),심 야,"39,321","75,446,339","5,674,251,821",75.2
17,202203,전라남도,전체(시 / 군 / 구),주택용,"776,733","211,262,938","23,956,256,691",113.4
18,202203,전라남도,전체(시 / 군 / 구),일반용,"160,668","339,406,580","43,337,723,564",127.7
19,202203,전라남도,전체(시 / 군 / 구),교육용,"1,326","28,374,078","3,017,869,259",106.4
20,202203,전라남도,전체(시 / 군 / 구),산업용,"21,990","1,959,217,061","175,779,452,960",89.7
21,202203,전라남도,전체(시 / 군 / 구),농사용,"434,131","387,467,318","18,463,509,739",47.7
22,202203,전라남도,전체(시 / 군 / 구),가로등,"199,071","19,332,010","2,214,274,106",114.5
23,202203,전라남도,전체(시 / 군 / 구),심 야,"39,208","60,260,001","4,030,476,883",66.9
24,202204,전라남도,전체(시 / 군 / 구),주택용,"777,851","216,333,447","25,621,489,761",118.4
25,202204,전라남도,전체(시 / 군 / 구),일반용,"161,088","320,480,371","38,481,131,666",120.1
26,202204,전라남도,전체(시 / 군 / 구),교육용,"1,323","27,841,504","2,687,741,976",96.5
27,202204,전라남도,전체(시 / 군 / 구),산업용,"22,010","1,866,109,100","182,055,646,207",97.6
28,202204,전라남도,전체(시 / 군 / 구),농사용,"336,626","353,825,606","17,807,247,212",50.3
29,202204,전라남도,전체(시 / 군 / 구),가로등,"199,542","19,278,637","2,354,011,369",122.1
30,202204,전라남도,전체(시 / 군 / 구),심 야,"39,088","47,542,008","2,711,624,761",57.0
31,202205,전라남도,전체(시 / 군 / 구),주택용,"778,361","196,480,969","23,329,281,469",118.7
32,202205,전라남도,전체(시 / 군 / 구),일반용,"161,487","294,198,385","37,705,322,310",128.2
33,202205,전라남도,전체(시 / 군 / 구),교육용,"1,322","20,447,740","2,095,745,284",102.5
34,202205,전라남도,전체(시 / 군 / 구),산업용,"22,036","1,937,089,310","186,613,749,716",96.3
35,202205,전라남도,전체(시 / 군 / 구),농사용,"313,612","285,546,273","15,619,680,570",54.7
36,202205,전라남도,전체(시 / 군 / 구),가로등,"200,011","18,370,159","2,385,628,999",129.9
37,202205,전라남도,전체(시 / 군 / 구),심 야,"38,957","27,926,207","1,729,809,149",61.9
38,202206,전라남도,전체(시 / 군 / 구),주택용,"778,995","200,698,167","24,018,261,012",119.7
39,202206,전라남도,전체(시 / 군 / 구),일반용,"161,867","319,631,729","44,958,155,300",140.7
40,202206,전라남도,전체(시 / 군 / 구),교육용,"1,323","23,182,728","2,767,832,526",119.4
41,202206,전라남도,전체(시 / 군 / 구),산업용,"22,068","1,856,970,186","214,135,552,887",115.3
42,202206,전라남도,전체(시 / 군 / 구),농사용,"314,568","310,727,836","16,397,547,133",52.8
43,202206,전라남도,전체(시 / 군 / 구),가로등,"200,462","17,767,262","2,380,281,158",134.0
44,202206,전라남도,전체(시 / 군 / 구),심 야,"38,850","18,899,215","1,195,635,326",63.3
45,합계,합계,합계,합계,"9,218,594","17,359,975,578","1,741,830,109,340",100.3

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_17680\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   202201  전라남도  일반용  159,871   399,241,693
11  202202  전라남도  일반용  160,236   392,777,152
18  202203  전라남도  일반용  160,668   339,406,580
25  202204  전라남도  일반용  161,088   320,480,371
32  202205  전라남도  일반용  161,487   294,198,385
39  202206  전라남도  일반용  161,867   319,631,729

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    202201  전라남도  강진군  일반용  3,315    7,281,971
229   202202  전라남도  강진군  일반용  3,321    7,187,967
405   202203  전라남도  강진군  일반용  3,319    6,058,945
581   202204  전라남도  강진군  일반용  3,324    5,712,744
757   202205  전라남도  강진군  일반용  3,341    5,217,435
...      ...   ...  ...  ...     ...          ...
397   202202  전라남도  화순군  일반용  4,922   14,759,199
573   202203  전라남도  화순군  일반용  4,952   12,935,070
749   202204  전라남도  화순군  일반용  4,974   12,153,330
925   202205  전라남도  화순군  일반용  4,989   11,004,873
1101  202206  전라남도  화순군  일반용  4,994   11,980,377

[132 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강진군',
 '고흥군',
 '곡성군',
 '광양시',
 '구례군',
 '나주시',
 '담양군',
 '목포시',
 '무안군',
 '보성군',
 '순천시',
 '신안군',
 '여수시',
 '영광군',
 '영암군',
 '완도군',
 '장성군',
 '장흥군',
 '진도군',
 '함평군',
 '해남군',
 '화순군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55    202201  전라남도  강진군   합계  42,158   42,182,012
231   202202  전라남도  강진군   합계  42,168   42,894,205
407   202203  전라남도  강진군   합계  51,623   37,369,916
583   202204  전라남도  강진군   합계  42,309   34,012,468
759   202205  전라남도  강진군   합계  42,393   29,230,033
...      ...   ...  ...  ...      ...          ...
399   202202  전라남도  화순군   합계  57,185   55,871,508
575   202203  전라남도  화순군   합계  59,125   47,176,233
751   202204  전라남도  화순군   합계  57,351   44,056,458
927   202205  전라남도  화순군   합계  57,503   37,775,132
1103  202206  전라남도  화순군   합계  57,622   39,111,113

[132 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[42182012, 42894205, 37369916, 34012468, 29230033, 28491775]
[68148269, 65903376, 59738475, 47038289, 36261274, 38057375]
[38554276, 37890773, 37123382, 34962900, 33376458, 36743146]
[396476417, 356675712, 468962700, 456404686, 479198362, 394495824]
[18016494, 17442527, 15150076, 14532274, 12964264, 13919333]
[131103806, 124478645, 116360148, 110637784, 97157751, 111072301]
[57536322, 54865873, 48833377, 44735370, 39894753, 41202625]
[103119147, 101467922, 91721337, 88504784, 74827639, 78939938]
[65664070, 65449114, 59633012, 56636379, 53015566, 57768637]
[31584502, 30692688, 26426466, 25502388, 22285586, 23418972]
[202540839, 192491095, 187269559, 171668522, 175233583, 177725547]
[29092148, 30348722, 27669369, 27215365, 22424008, 23607332]
[1324376342, 1184378862, 1275978401, 1205171047, 1227561992, 1239306808]
[67905109, 65761487, 64497621, 62509463, 66762668, 58570843]
[107199054, 109927401, 103506823, 97026594, 93335353, 104432755]
[87134109, 94859182, 97845391, 106670214, 91775774, 86419622]
[63050028, 55574824, 56991939, 55494880, 51826533, 51175360]
[38719530, 39082522, 35067878, 34095160, 26734424, 27627884]
[34964554, 34474773, 32708784, 31952208, 25817819, 27110381]
[40832978, 40228428, 35853083, 34711289, 29959445, 30962959]
[82089076, 86272754, 79436016, 67872151, 52640626, 57716593]
[57987278, 55871508, 47176233, 44056458, 37775132, 39111113]
전라남도 지역별 합계 :  [214180409, 315147058, 218650935, 2552213701, 92024968, 690810435, 287068320, 538580767, 358166778, 159910602, 1106929145, 160356944, 7456773452, 386007191, 615427980, 564704292, 334113564, 201327398, 187028519, 212548182, 426027216, 281977722]
전라남도 고객호수 평균:  [7308, 14805, 6481, 13930, 5588, 15812, 8827, 16692, 12038, 9216, 25637, 9162, 27826, 9754, 10332, 8746, 7299, 7974, 7211, 7106, 14709, 9608]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           202201  전라남도  강진군   합계  42,158   42,182,012
1           202202  전라남도  강진군   합계  42,168   42,894,205
2           202203  전라남도  강진군   합계  51,623   37,369,916
3           202204  전라남도  강진군   합계  42,309   34,012,468
4           202205  전라남도  강진군   합계  42,393   29,230,033
..             ...   ...  ...  ...      ...          ...
149  202201-202206  전라남도  장흥군   합계     7974    201327398
150  202201-202206  전라남도  진도군   합계     7211    187028519
151  202201-202206  전라남도  함평군   합계     7106    212548182
152  202201-202206  전라남도  해남군   합계    14709    426027216
153  202201-202206  전라남도  화순군   합계     9608    281977722

[154 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '202201-202206']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  202201-202206  전라남도  강진군   합계    7308   214180409
133  202201-202206  전라남도  고흥군   합계   14805   315147058
134  202201-202206  전라남도  곡성군   합계    6481   218650935
135  202201-202206  전라남도  광양시   합계   13930  2552213701
136  202201-202206  전라남도  구례군   합계    5588    92024968
137  202201-202206  전라남도  나주시   합계   15812   690810435
138  202201-202206  전라남도  담양군   합계    8827   287068320
139  202201-202206  전라남도  목포시   합계   16692   538580767
140  202201-202206  전라남도  무안군   합계   12038   358166778
141  202201-202206  전라남도  보성군   합계    9216   159910602
142  202201-202206  전라남도  순천시   합계   25637  1106929145
143  202201-202206  전라남도  신안군   합계    9162   160356944
144  202201-202206  전라남도  여수시   합계   27826  7456773452
145  202201-202206  전라남도  영광군   합계    9754   386007191
146  202201-202206  전라남도  영암군   합계   10332   615427980
147  202201-202206  전라남도  완도군   합계    8746   564704292
148  202201-202206  전라남도  장성군   합계    7299   334113564
149  202201-202206  전라남도  장흥군   합계    7974   201327398
150  202201-202206  전라남도  진도군   합계    7211   187028519
151  202201-202206  전라남도  함평군   합계    7106   212548182
152  202201-202206  전라남도  해남군   합계   14709   426027216
153  202201-202206  전라남도  화순군   합계    9608   281977722

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    202201  전라남도  강진군  일반용  3,315    7,281,971
229   202202  전라남도  강진군  일반용  3,321    7,187,967
405   202203  전라남도  강진군  일반용  3,319    6,058,945
581   202204  전라남도  강진군  일반용  3,324    5,712,744
757   202205  전라남도  강진군  일반용  3,341    5,217,435
...      ...   ...  ...  ...     ...          ...
397   202202  전라남도  화순군  일반용  4,922   14,759,199
573   202203  전라남도  화순군  일반용  4,952   12,935,070
749   202204  전라남도  화순군  일반용  4,974   12,153,330
925   202205  전라남도  화순군  일반용  4,989   11,004,873
1101  202206  전라남도  화순군  일반용  4,994   11,980,377

[132 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[7281971, 7187967, 6058945, 5712744, 5217435, 5277022]
[11163107, 11256216, 9556766, 9085587, 8159683, 8576526]
[5273680, 5339356, 4450283, 4129767, 3601274, 3968060]
[28588933, 27524686, 23938985, 22426533, 21330225, 23674889]
[6533578, 6332983, 5443459, 5095759, 4448799, 4680973]
[30336801, 29350565, 26432657, 24601399, 23300295, 26097270]
[12746724, 12761648, 10783517, 10239478, 9171958, 9862185]
[48039603, 48140362, 42102620, 39609814, 35862919, 39245389]
[18895502, 18582682, 15787335, 14873252, 13411846, 14709263]
[8105537, 8117073, 6924726, 6470918, 5665394, 5865620]
[54526744, 52802824, 45538758, 43724610, 41670429, 46571211]
[7461763, 7573685, 6568769, 6470825, 5705173, 5698899]
[64979602, 63352666, 54323438, 51592059, 48756751, 53269323]
[11180948, 11404828, 9556506, 8867427, 7668882, 7977427]
[13030433, 12870506, 11488145, 10798764, 9117026, 9730737]
[10285209, 10462768, 8875043, 8465987, 7517584, 7797867]
[11482965, 11234695, 9712092, 8822605, 7970642, 8663106]
[7530171, 7404738, 6311322, 6015610, 5421068, 5743994]
[6625248, 6476544, 5726240, 5459230, 4992124, 5319699]
[5687834, 5671159, 4843905, 4649936, 4111418, 4293120]
[14543597, 14170002, 12047999, 11214737, 10092587, 10628772]
[14941743, 14759199, 12935070, 12153330, 11004873, 11980377]
전라남도 지역별 일반용 합계 :  [36736084, 57797885, 26762420, 147484251, 32535551, 160118987, 65565510, 253000707, 96259880, 41149268, 284834576, 39479114, 336273839, 56656018, 67035611, 53404458, 57886105, 38426903, 34599085, 29257372, 72697694, 77774592]
전라남도 고객호수 평균:  [3324, 6034, 2433, 11989, 2723, 8593, 4401, 19861, 6708, 3845, 21787, 4025, 24903, 5087, 4766, 5741, 3878, 3536, 3137, 2545, 6586, 4959]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_17680\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
0           202201  전라남도  강진군  일반용  3,315   7,281,971
1           202202  전라남도  강진군  일반용  3,321   7,187,967
2           202203  전라남도  강진군  일반용  3,319   6,058,945
3           202204  전라남도  강진군  일반용  3,324   5,712,744
4           202205  전라남도  강진군  일반용  3,341   5,217,435
..             ...   ...  ...  ...     ...         ...
149  202201-202206  전라남도  장흥군  일반용    3536    38426903
150  202201-202206  전라남도  진도군  일반용    3137    34599085
151  202201-202206  전라남도  함평군  일반용    2545    29257372
152  202201-202206  전라남도  해남군  일반용    6586    72697694
153  202201-202206  전라남도  화순군  일반용    4959    77774592

[154 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '202201-202206']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
132  202201-202206  전라남도  강진군  일반용    3324   36736084
133  202201-202206  전라남도  고흥군  일반용    6034   57797885
134  202201-202206  전라남도  곡성군  일반용    2433   26762420
135  202201-202206  전라남도  광양시  일반용   11989  147484251
136  202201-202206  전라남도  구례군  일반용    2723   32535551
137  202201-202206  전라남도  나주시  일반용    8593  160118987
138  202201-202206  전라남도  담양군  일반용    4401   65565510
139  202201-202206  전라남도  목포시  일반용   19861  253000707
140  202201-202206  전라남도  무안군  일반용    6708   96259880
141  202201-202206  전라남도  보성군  일반용    3845   41149268
142  202201-202206  전라남도  순천시  일반용   21787  284834576
143  202201-202206  전라남도  신안군  일반용    4025   39479114
144  202201-202206  전라남도  여수시  일반용   24903  336273839
145  202201-202206  전라남도  영광군  일반용    5087   56656018
146  202201-202206  전라남도  영암군  일반용    4766   67035611
147  202201-202206  전라남도  완도군  일반용    5741   53404458
148  202201-202206  전라남도  장성군  일반용    3878   57886105
149  202201-202206  전라남도  장흥군  일반용    3536   38426903
150  202201-202206  전라남도  진도군  일반용    3137   34599085
151  202201-202206  전라남도  함평군  일반용    2545   29257372
152  202201-202206  전라남도  해남군  일반용    6586   72697694
153  202201-202206  전라남도  화순군  일반용    4959   77774592

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  202201-202206  전라남도  강진군  일반용    3324    36736084
132  202201-202206  전라남도  강진군   합계    7308   214180409
133  202201-202206  전라남도  고흥군  일반용    6034    57797885
133  202201-202206  전라남도  고흥군   합계   14805   315147058
134  202201-202206  전라남도  곡성군  일반용    2433    26762420
134  202201-202206  전라남도  곡성군   합계    6481   218650935
135  202201-202206  전라남도  광양시  일반용   11989   147484251
135  202201-202206  전라남도  광양시   합계   13930  2552213701
136  202201-202206  전라남도  구례군  일반용    2723    32535551
136  202201-202206  전라남도  구례군   합계    5588    92024968
137  202201-202206  전라남도  나주시  일반용    8593   160118987
137  202201-202206  전라남도  나주시   합계   15812   690810435
138  202201-202206  전라남도  담양군  일반용    4401    65565510
138  202201-202206  전라남도  담양군   합계    8827   287068320
139  202201-202206  전라남도  목포시   합계   16692   538580767
139  202201-202206  전라남도  목포시  일반용   19861   253000707
140  202201-202206  전라남도  무안군   합계   12038   358166778
140  202201-202206  전라남도  무안군  일반용    6708    96259880
141  202201-202206  전라남도  보성군   합계    9216   159910602
141  202201-202206  전라남도  보성군  일반용    3845    41149268
142  202201-202206  전라남도  순천시   합계   25637  1106929145
142  202201-202206  전라남도  순천시  일반용   21787   284834576
143  202201-202206  전라남도  신안군   합계    9162   160356944
143  202201-202206  전라남도  신안군  일반용    4025    39479114
144  202201-202206  전라남도  여수시   합계   27826  7456773452
144  202201-202206  전라남도  여수시  일반용   24903   336273839
145  202201-202206  전라남도  영광군   합계    9754   386007191
145  202201-202206  전라남도  영광군  일반용    5087    56656018
146  202201-202206  전라남도  영암군   합계   10332   615427980
146  202201-202206  전라남도  영암군  일반용    4766    67035611
147  202201-202206  전라남도  완도군   합계    8746   564704292
147  202201-202206  전라남도  완도군  일반용    5741    53404458
148  202201-202206  전라남도  장성군  일반용    3878    57886105
148  202201-202206  전라남도  장성군   합계    7299   334113564
149  202201-202206  전라남도  장흥군   합계    7974   201327398
149  202201-202206  전라남도  장흥군  일반용    3536    38426903
150  202201-202206  전라남도  진도군   합계    7211   187028519
150  202201-202206  전라남도  진도군  일반용    3137    34599085
151  202201-202206  전라남도  함평군   합계    7106   212548182
151  202201-202206  전라남도  함평군  일반용    2545    29257372
152  202201-202206  전라남도  해남군   합계   14709   426027216
152  202201-202206  전라남도  해남군  일반용    6586    72697694
153  202201-202206  전라남도  화순군  일반용    4959    77774592
153  202201-202206  전라남도  화순군   합계    9608   281977722

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[36736084,
 57797885,
 26762420,
 147484251,
 32535551,
 160118987,
 65565510,
 253000707,
 96259880,
 41149268,
 284834576,
 39479114,
 336273839,
 56656018,
 67035611,
 53404458,
 57886105,
 38426903,
 34599085,
 29257372,
 72697694,
 77774592]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[214180409,
 315147058,
 218650935,
 2552213701,
 92024968,
 690810435,
 287068320,
 538580767,
 358166778,
 159910602,
 1106929145,
 160356944,
 7456773452,
 386007191,
 615427980,
 564704292,
 334113564,
 201327398,
 187028519,
 212548182,
 426027216,
 281977722]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[17.15, 18.34, 12.24, 5.78, 35.36, 23.18, 22.84, 46.98, 26.88, 25.73, 25.73, 24.62, 4.51, 14.68, 10.89, 9.46, 17.33, 19.09, 18.5, 13.77, 17.06, 27.58]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    17
1    18
2    12
3     6
4    35
5    23
6    23
7    47
8    27
9    26
10   26
11   25
12    5
13   15
14   11
15    9
16   17
17   19
18   18
19   14
20   17
21   28
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강진군  일반용  17
1   고흥군  일반용  18
2   곡성군  일반용  12
3   광양시  일반용   6
4   구례군  일반용  35
5   나주시  일반용  23
6   담양군  일반용  23
7   목포시  일반용  47
8   무안군  일반용  27
9   보성군  일반용  26
10  순천시  일반용  26
11  신안군  일반용  25
12  여수시  일반용   5
13  영광군  일반용  15
14  영암군  일반용  11
15  완도군  일반용   9
16  장성군  일반용  17
17  장흥군  일반용  19
18  진도군  일반용  18
19  함평군  일반용  14
20  해남군  일반용  17
21  화순군  일반용  28

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   202201-202206  전라남도  강진군  일반용    3324    36736084  17
1   202201-202206  전라남도  강진군   합계    7308   214180409 NaN
2   202201-202206  전라남도  고흥군  일반용    6034    57797885  18
3   202201-202206  전라남도  고흥군   합계   14805   315147058 NaN
4   202201-202206  전라남도  곡성군  일반용    2433    26762420  12
5   202201-202206  전라남도  곡성군   합계    6481   218650935 NaN
6   202201-202206  전라남도  광양시  일반용   11989   147484251   6
7   202201-202206  전라남도  광양시   합계   13930  2552213701 NaN
8   202201-202206  전라남도  구례군  일반용    2723    32535551  35
9   202201-202206  전라남도  구례군   합계    5588    92024968 NaN
10  202201-202206  전라남도  나주시  일반용    8593   160118987  23
11  202201-202206  전라남도  나주시   합계   15812   690810435 NaN
12  202201-202206  전라남도  담양군  일반용    4401    65565510  23
13  202201-202206  전라남도  담양군   합계    8827   287068320 NaN
15  202201-202206  전라남도  목포시  일반용   19861   253000707  47
14  202201-202206  전라남도  목포시   합계   16692   538580767 NaN
17  202201-202206  전라남도  무안군  일반용    6708    96259880  27
16  202201-202206  전라남도  무안군   합계   12038   358166778 NaN
19  202201-202206  전라남도  보성군  일반용    3845    41149268  26
18  202201-202206  전라남도  보성군   합계    9216   159910602 NaN
21  202201-202206  전라남도  순천시  일반용   21787   284834576  26
20  202201-202206  전라남도  순천시   합계   25637  1106929145 NaN
23  202201-202206  전라남도  신안군  일반용    4025    39479114  25
22  202201-202206  전라남도  신안군   합계    9162   160356944 NaN
25  202201-202206  전라남도  여수시  일반용   24903   336273839   5
24  202201-202206  전라남도  여수시   합계   27826  7456773452 NaN
27  202201-202206  전라남도  영광군  일반용    5087    56656018  15
26  202201-202206  전라남도  영광군   합계    9754   386007191 NaN
29  202201-202206  전라남도  영암군  일반용    4766    67035611  11
28  202201-202206  전라남도  영암군   합계   10332   615427980 NaN
31  202201-202206  전라남도  완도군  일반용    5741    53404458   9
30  202201-202206  전라남도  완도군   합계    8746   564704292 NaN
32  202201-202206  전라남도  장성군  일반용    3878    57886105  17
33  202201-202206  전라남도  장성군   합계    7299   334113564 NaN
35  202201-202206  전라남도  장흥군  일반용    3536    38426903  19
34  202201-202206  전라남도  장흥군   합계    7974   201327398 NaN
37  202201-202206  전라남도  진도군  일반용    3137    34599085  18
36  202201-202206  전라남도  진도군   합계    7211   187028519 NaN
39  202201-202206  전라남도  함평군  일반용    2545    29257372  14
38  202201-202206  전라남도  함평군   합계    7106   212548182 NaN
41  202201-202206  전라남도  해남군  일반용    6586    72697694  17
40  202201-202206  전라남도  해남군   합계   14709   426027216 NaN
42  202201-202206  전라남도  화순군  일반용    4959    77774592  28
43  202201-202206  전라남도  화순군   합계    9608   281977722 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_2201-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)