In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별 전력사용량 월별_14하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 07 월 ~ 2014년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,경상남도,전체(시 / 군 / 구),주택용,"1,078,278","326,921,054","38,192,310,324",116.8
4,201407,경상남도,전체(시 / 군 / 구),일반용,"209,434","472,248,259","71,339,820,004",151.1
...,...,...,...,...,...,...,...,...
907,201412,경상남도,합천군,산업용,959,"6,504,273","848,881,445",130.5
908,201412,경상남도,합천군,심 야,"2,255","4,735,524","355,872,247",75.1
909,201412,경상남도,합천군,일반용,"4,033","6,499,902","903,352,226",139
910,201412,경상남도,합천군,주택용,"27,493","4,590,355","564,431,070",123
911,201412,경상남도,합천군,합계,"47,515","33,014,751","3,258,328,422",98.7

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,경상남도,전체(시 / 군 / 구),주택용,"1,078,278","326,921,054","38,192,310,324",116.8
4,201407,경상남도,전체(시 / 군 / 구),일반용,"209,434","472,248,259","71,339,820,004",151.1
5,201407,경상남도,전체(시 / 군 / 구),교육용,"1,597","30,683,787","4,273,839,614",139.3
6,201407,경상남도,전체(시 / 군 / 구),산업용,"35,621","1,754,749,688","227,140,139,895",129.4
...,...,...,...,...,...,...,...,...
907,201412,경상남도,합천군,산업용,959,"6,504,273","848,881,445",130.5
908,201412,경상남도,합천군,심 야,"2,255","4,735,524","355,872,247",75.1
909,201412,경상남도,합천군,일반용,"4,033","6,499,902","903,352,226",139
910,201412,경상남도,합천군,주택용,"27,493","4,590,355","564,431,070",123
911,201412,경상남도,합천군,합계,"47,515","33,014,751","3,258,328,422",98.7

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,경상남도,전체(시 / 군 / 구),주택용,"1,078,278","326,921,054","38,192,310,324",116.8
4,201407,경상남도,전체(시 / 군 / 구),일반용,"209,434","472,248,259","71,339,820,004",151.1
5,201407,경상남도,전체(시 / 군 / 구),교육용,"1,597","30,683,787","4,273,839,614",139.3
6,201407,경상남도,전체(시 / 군 / 구),산업용,"35,621","1,754,749,688","227,140,139,895",129.4
7,201407,경상남도,전체(시 / 군 / 구),농사용,"164,258","102,613,047","5,175,556,827",50.4
...,...,...,...,...,...,...,...,...
907,201412,경상남도,합천군,산업용,959,"6,504,273","848,881,445",130.5
908,201412,경상남도,합천군,심 야,"2,255","4,735,524","355,872,247",75.1
909,201412,경상남도,합천군,일반용,"4,033","6,499,902","903,352,226",139
910,201412,경상남도,합천군,주택용,"27,493","4,590,355","564,431,070",123
911,201412,경상남도,합천군,합계,"47,515","33,014,751","3,258,328,422",98.7

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,경상남도,전체(시 / 군 / 구),주택용,"1,078,278","326,921,054","38,192,310,324",116.8
4,201407,경상남도,전체(시 / 군 / 구),일반용,"209,434","472,248,259","71,339,820,004",151.1
5,201407,경상남도,전체(시 / 군 / 구),교육용,"1,597","30,683,787","4,273,839,614",139.3
6,201407,경상남도,전체(시 / 군 / 구),산업용,"35,621","1,754,749,688","227,140,139,895",129.4
7,201407,경상남도,전체(시 / 군 / 구),농사용,"164,258","102,613,047","5,175,556,827",50.4
8,201407,경상남도,전체(시 / 군 / 구),가로등,"139,840","18,428,501","2,293,345,117",124.4
9,201407,경상남도,전체(시 / 군 / 구),심 야,"98,223","34,141,304","1,918,534,810",56.2
10,201408,경상남도,전체(시 / 군 / 구),주택용,"1,080,003","374,522,830","49,304,451,616",131.6
11,201408,경상남도,전체(시 / 군 / 구),일반용,"209,950","536,493,999","78,003,729,523",145.4
12,201408,경상남도,전체(시 / 군 / 구),교육용,"1,598","28,126,498","4,034,269,443",143.4
13,201408,경상남도,전체(시 / 군 / 구),산업용,"35,714","1,527,889,687","199,755,079,811",130.7
14,201408,경상남도,전체(시 / 군 / 구),농사용,"165,380","127,557,584","6,269,664,911",49.2
15,201408,경상남도,전체(시 / 군 / 구),가로등,"140,470","19,191,405","2,301,471,446",119.9
16,201408,경상남도,전체(시 / 군 / 구),심 야,"98,008","30,278,873","1,716,343,806",56.7
17,201409,경상남도,전체(시 / 군 / 구),주택용,"1,081,670","343,418,440","41,543,827,627",121.0
18,201409,경상남도,전체(시 / 군 / 구),일반용,"210,119","474,960,738","62,443,591,367",131.5
19,201409,경상남도,전체(시 / 군 / 구),교육용,"1,594","28,485,441","3,385,503,380",118.9
20,201409,경상남도,전체(시 / 군 / 구),산업용,"35,725","1,551,273,440","168,347,362,459",108.5
21,201409,경상남도,전체(시 / 군 / 구),농사용,"166,357","118,817,043","5,891,935,009",49.6
22,201409,경상남도,전체(시 / 군 / 구),가로등,"140,712","20,106,411","2,340,201,661",116.4
23,201409,경상남도,전체(시 / 군 / 구),심 야,"97,773","32,892,622","1,853,025,084",56.3
24,201410,경상남도,전체(시 / 군 / 구),주택용,"1,083,391","316,499,480","35,525,195,153",112.2
25,201410,경상남도,전체(시 / 군 / 구),일반용,"210,241","422,076,786","50,031,115,380",118.5
26,201410,경상남도,전체(시 / 군 / 구),교육용,"1,595","26,365,961","2,929,867,967",111.1
27,201410,경상남도,전체(시 / 군 / 구),산업용,"35,778","1,648,468,126","167,502,531,685",101.6
28,201410,경상남도,전체(시 / 군 / 구),농사용,"167,112","100,621,813","5,271,353,693",52.4
29,201410,경상남도,전체(시 / 군 / 구),가로등,"140,963","21,844,276","2,411,721,523",110.4
30,201410,경상남도,전체(시 / 군 / 구),심 야,"97,729","45,071,682","2,501,832,626",55.5
31,201411,경상남도,전체(시 / 군 / 구),주택용,"1,085,439","341,716,658","41,117,937,198",120.3
32,201411,경상남도,전체(시 / 군 / 구),일반용,"210,631","435,630,642","57,064,059,413",131.0
33,201411,경상남도,전체(시 / 군 / 구),교육용,"1,595","30,746,655","3,652,340,776",118.8
34,201411,경상남도,전체(시 / 군 / 구),산업용,"35,803","1,620,720,712","198,245,483,738",122.3
35,201411,경상남도,전체(시 / 군 / 구),농사용,"192,529","149,778,861","7,346,875,107",49.1
36,201411,경상남도,전체(시 / 군 / 구),가로등,"141,277","23,381,807","2,516,659,169",107.6
37,201411,경상남도,전체(시 / 군 / 구),심 야,"97,703","92,735,024","5,947,368,353",64.1
38,201412,경상남도,전체(시 / 군 / 구),주택용,"1,087,121","358,648,687","45,101,179,569",125.8
39,201412,경상남도,전체(시 / 군 / 구),일반용,"210,972","503,479,273","69,954,890,894",138.9
40,201412,경상남도,전체(시 / 군 / 구),교육용,"1,593","42,795,621","4,894,811,105",114.4
41,201412,경상남도,전체(시 / 군 / 구),산업용,"35,811","1,752,952,874","217,928,515,968",124.3
42,201412,경상남도,전체(시 / 군 / 구),농사용,"169,033","223,358,105","10,791,682,551",48.3
43,201412,경상남도,전체(시 / 군 / 구),가로등,"141,841","24,767,029","2,596,334,654",104.8
44,201412,경상남도,전체(시 / 군 / 구),심 야,"97,646","147,735,203","11,158,868,945",75.5
45,합계,합계,합계,합계,"10,438,127","16,283,195,926","1,922,014,629,201",118

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_10980\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201407  경상남도  일반용  209,434   472,248,259
11  201408  경상남도  일반용  209,950   536,493,999
18  201409  경상남도  일반용  210,119   474,960,738
25  201410  경상남도  일반용  210,241   422,076,786
32  201411  경상남도  일반용  210,631   435,630,642
39  201412  경상남도  일반용  210,972   503,479,273

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201407  경상남도  거제시  일반용  16,497   36,642,793
197  201408  경상남도  거제시  일반용  16,551   43,091,042
341  201409  경상남도  거제시  일반용  16,610   37,960,297
485  201410  경상남도  거제시  일반용  16,647   33,470,367
629  201411  경상남도  거제시  일반용  16,698   34,070,066
..      ...   ...  ...  ...      ...          ...
333  201408  경상남도  합천군  일반용   4,013    6,434,645
477  201409  경상남도  합천군  일반용   4,018    5,603,226
621  201410  경상남도  합천군  일반용   4,012    5,204,801
765  201411  경상남도  합천군  일반용   4,028    5,818,580
909  201412  경상남도  합천군  일반용   4,033    6,499,902

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201407  경상남도  거제시   합계  110,793   184,761,370
199  201408  경상남도  거제시   합계  111,485   179,245,254
343  201409  경상남도  거제시   합계  112,240   169,869,205
487  201410  경상남도  거제시   합계  112,700   161,579,976
631  201411  경상남도  거제시   합계  114,677   166,221,495
..      ...   ...  ...  ...       ...           ...
335  201408  경상남도  합천군   합계   47,550    27,460,276
479  201409  경상남도  합천군   합계   47,627    26,169,839
623  201410  경상남도  합천군   합계   47,700    25,154,758
767  201411  경상남도  합천군   합계   49,715    30,903,776
911  201412  경상남도  합천군   합계   47,515    33,014,751

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[184761370, 179245254, 169869205, 161579976, 166221495, 190350494]
[30878618, 32438226, 32129367, 31238866, 35044986, 38964584]
[48135020, 49930420, 48759695, 47638994, 52872402, 60007519]
[411052490, 407970618, 393353207, 393349424, 413084575, 457759639]
[18222805, 22709499, 20133357, 18459955, 21006975, 22369860]
[72760412, 73903942, 69442383, 70542845, 80437591, 108677670]
[102726603, 102732002, 98750386, 98953462, 102779502, 114478180]
[18632213, 21311304, 20249966, 19470594, 24637839, 27077444]
[292017035, 279574092, 263808733, 271401339, 268124710, 309466209]
[29691813, 30632673, 28780090, 29121087, 32487328, 35535146]
[177181708, 183651201, 172520334, 171331257, 192777733, 236100876]
[63261016, 65395213, 61238555, 59577409, 67550918, 83581431]
[926784150, 854991771, 844841104, 857951439, 866514303, 960921388]
[84449505, 91997980, 86919614, 83926668, 87397166, 100873610]
[19909679, 23236571, 22849743, 22752760, 27674605, 30048537]
[216585106, 177021020, 190184483, 200189551, 203793506, 221400666]
[17223015, 19858814, 19954074, 18307740, 21400949, 23108788]
[25513082, 27460276, 26169839, 25154758, 30903776, 33014751]
경상남도 지역별 합계 :  [1052027794, 200694647, 307344050, 2476569953, 122902451, 475764843, 620420135, 131379360, 1684392118, 186248137, 1133563109, 400604542, 5312004155, 535564543, 146471895, 1209174332, 119853380, 168216482]
경상남도 고객호수 평균:  [18769, 8771, 8276, 31055, 7976, 15516, 11724, 6542, 17101, 5394, 29958, 9535, 75154, 12936, 8270, 8459, 6518, 7984]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201407  경상남도  거제시   합계  110,793   184,761,370
1           201408  경상남도  거제시   합계  111,485   179,245,254
2           201409  경상남도  거제시   합계  112,240   169,869,205
3           201410  경상남도  거제시   합계  112,700   161,579,976
4           201411  경상남도  거제시   합계  114,677   166,221,495
..             ...   ...  ...  ...       ...           ...
121  201407-201412  경상남도  통영시   합계     12936     535564543
122  201407-201412  경상남도  하동군   합계      8270     146471895
123  201407-201412  경상남도  함안군   합계      8459    1209174332
124  201407-201412  경상남도  함양군   합계      6518     119853380
125  201407-201412  경상남도  합천군   합계      7984     168216482

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201407-201412']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201407-201412  경상남도  거제시   합계   18769  1052027794
109  201407-201412  경상남도  거창군   합계    8771   200694647
110  201407-201412  경상남도  고성군   합계    8276   307344050
111  201407-201412  경상남도  김해시   합계   31055  2476569953
112  201407-201412  경상남도  남해군   합계    7976   122902451
113  201407-201412  경상남도  밀양시   합계   15516   475764843
114  201407-201412  경상남도  사천시   합계   11724   620420135
115  201407-201412  경상남도  산청군   합계    6542   131379360
116  201407-201412  경상남도  양산시   합계   17101  1684392118
117  201407-201412  경상남도  의령군   합계    5394   186248137
118  201407-201412  경상남도  진주시   합계   29958  1133563109
119  201407-201412  경상남도  창녕군   합계    9535   400604542
120  201407-201412  경상남도  창원시   합계   75154  5312004155
121  201407-201412  경상남도  통영시   합계   12936   535564543
122  201407-201412  경상남도  하동군   합계    8270   146471895
123  201407-201412  경상남도  함안군   합계    8459  1209174332
124  201407-201412  경상남도  함양군   합계    6518   119853380
125  201407-201412  경상남도  합천군   합계    7984   168216482

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201407  경상남도  거제시  일반용  16,497   36,642,793
197  201408  경상남도  거제시  일반용  16,551   43,091,042
341  201409  경상남도  거제시  일반용  16,610   37,960,297
485  201410  경상남도  거제시  일반용  16,647   33,470,367
629  201411  경상남도  거제시  일반용  16,698   34,070,066
..      ...   ...  ...  ...      ...          ...
333  201408  경상남도  합천군  일반용   4,013    6,434,645
477  201409  경상남도  합천군  일반용   4,018    5,603,226
621  201410  경상남도  합천군  일반용   4,012    5,204,801
765  201411  경상남도  합천군  일반용   4,028    5,818,580
909  201412  경상남도  합천군  일반용   4,033    6,499,902

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[36642793, 43091042, 37960297, 33470367, 34070066, 38473817]
[7218548, 8087019, 7272395, 6705312, 7687823, 9052881]
[6959570, 7975376, 7282003, 6606564, 7119334, 8174267]
[73349308, 82786115, 72748770, 63301217, 65276968, 75741915]
[6811385, 8657660, 7376036, 6521557, 6921087, 7701856]
[13176768, 15212870, 13519951, 11986694, 12823699, 14876614]
[16653837, 19112969, 17159039, 15276555, 15979238, 18383316]
[4375589, 5221039, 4595835, 4174374, 4559767, 5098042]
[40369312, 45695108, 39447112, 36032812, 37023610, 43599568]
[3034562, 3516003, 3121126, 2891652, 3171553, 3618996]
[47693323, 53430419, 48251610, 43304195, 44747632, 52057366]
[9463955, 10787547, 9296295, 8476405, 9130202, 10804692]
[160124896, 178654170, 158320104, 139708768, 140555855, 164081181]
[21431614, 25490096, 23073126, 20369487, 21097110, 23293065]
[5985733, 7091211, 6324467, 5723516, 6138169, 6813331]
[8957777, 9996245, 8901492, 8045058, 8851172, 9989006]
[4522876, 5254465, 4707854, 4277452, 4658777, 5219458]
[5476413, 6434645, 5603226, 5204801, 5818580, 6499902]
경상남도 지역별 일반용 합계 :  [223708382, 46023978, 44117114, 433204293, 43989581, 81596596, 102564954, 28024646, 242167522, 19353892, 289484545, 57959096, 941444974, 134754498, 38076427, 54740750, 28640882, 35037567]
경상남도 고객호수 평균:  [16623, 4942, 4612, 27972, 4681, 8947, 8943, 3481, 15886, 2528, 23538, 5375, 55283, 10393, 4168, 5289, 3538, 4018]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10980\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201407  경상남도  거제시  일반용  16,497   36,642,793
1           201408  경상남도  거제시  일반용  16,551   43,091,042
2           201409  경상남도  거제시  일반용  16,610   37,960,297
3           201410  경상남도  거제시  일반용  16,647   33,470,367
4           201411  경상남도  거제시  일반용  16,698   34,070,066
..             ...   ...  ...  ...      ...          ...
121  201407-201412  경상남도  통영시  일반용    10393    134754498
122  201407-201412  경상남도  하동군  일반용     4168     38076427
123  201407-201412  경상남도  함안군  일반용     5289     54740750
124  201407-201412  경상남도  함양군  일반용     3538     28640882
125  201407-201412  경상남도  합천군  일반용     4018     35037567

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201407-201412']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201407-201412  경상남도  거제시  일반용   16623  223708382
109  201407-201412  경상남도  거창군  일반용    4942   46023978
110  201407-201412  경상남도  고성군  일반용    4612   44117114
111  201407-201412  경상남도  김해시  일반용   27972  433204293
112  201407-201412  경상남도  남해군  일반용    4681   43989581
113  201407-201412  경상남도  밀양시  일반용    8947   81596596
114  201407-201412  경상남도  사천시  일반용    8943  102564954
115  201407-201412  경상남도  산청군  일반용    3481   28024646
116  201407-201412  경상남도  양산시  일반용   15886  242167522
117  201407-201412  경상남도  의령군  일반용    2528   19353892
118  201407-201412  경상남도  진주시  일반용   23538  289484545
119  201407-201412  경상남도  창녕군  일반용    5375   57959096
120  201407-201412  경상남도  창원시  일반용   55283  941444974
121  201407-201412  경상남도  통영시  일반용   10393  134754498
122  201407-201412  경상남도  하동군  일반용    4168   38076427
123  201407-201412  경상남도  함안군  일반용    5289   54740750
124  201407-201412  경상남도  함양군  일반용    3538   28640882
125  201407-201412  경상남도  합천군  일반용    4018   35037567

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201407-201412  경상남도  거제시  일반용   16623   223708382
108  201407-201412  경상남도  거제시   합계   18769  1052027794
109  201407-201412  경상남도  거창군  일반용    4942    46023978
109  201407-201412  경상남도  거창군   합계    8771   200694647
110  201407-201412  경상남도  고성군  일반용    4612    44117114
110  201407-201412  경상남도  고성군   합계    8276   307344050
111  201407-201412  경상남도  김해시   합계   31055  2476569953
111  201407-201412  경상남도  김해시  일반용   27972   433204293
112  201407-201412  경상남도  남해군   합계    7976   122902451
112  201407-201412  경상남도  남해군  일반용    4681    43989581
113  201407-201412  경상남도  밀양시  일반용    8947    81596596
113  201407-201412  경상남도  밀양시   합계   15516   475764843
114  201407-201412  경상남도  사천시   합계   11724   620420135
114  201407-201412  경상남도  사천시  일반용    8943   102564954
115  201407-201412  경상남도  산청군  일반용    3481    28024646
115  201407-201412  경상남도  산청군   합계    6542   131379360
116  201407-201412  경상남도  양산시  일반용   15886   242167522
116  201407-201412  경상남도  양산시   합계   17101  1684392118
117  201407-201412  경상남도  의령군  일반용    2528    19353892
117  201407-201412  경상남도  의령군   합계    5394   186248137
118  201407-201412  경상남도  진주시   합계   29958  1133563109
118  201407-201412  경상남도  진주시  일반용   23538   289484545
119  201407-201412  경상남도  창녕군   합계    9535   400604542
119  201407-201412  경상남도  창녕군  일반용    5375    57959096
120  201407-201412  경상남도  창원시  일반용   55283   941444974
120  201407-201412  경상남도  창원시   합계   75154  5312004155
121  201407-201412  경상남도  통영시   합계   12936   535564543
121  201407-201412  경상남도  통영시  일반용   10393   134754498
122  201407-201412  경상남도  하동군   합계    8270   146471895
122  201407-201412  경상남도  하동군  일반용    4168    38076427
123  201407-201412  경상남도  함안군   합계    8459  1209174332
123  201407-201412  경상남도  함안군  일반용    5289    54740750
124  201407-201412  경상남도  함양군   합계    6518   119853380
124  201407-201412  경상남도  함양군  일반용    3538    28640882
125  201407-201412  경상남도  합천군  일반용    4018    35037567
125  201407-201412  경상남도  합천군   합계    7984   168216482

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[223708382,
 46023978,
 44117114,
 433204293,
 43989581,
 81596596,
 102564954,
 28024646,
 242167522,
 19353892,
 289484545,
 57959096,
 941444974,
 134754498,
 38076427,
 54740750,
 28640882,
 35037567]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1052027794,
 200694647,
 307344050,
 2476569953,
 122902451,
 475764843,
 620420135,
 131379360,
 1684392118,
 186248137,
 1133563109,
 400604542,
 5312004155,
 535564543,
 146471895,
 1209174332,
 119853380,
 168216482]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[21.26, 22.93, 14.35, 17.49, 35.79, 17.15, 16.53, 21.33, 14.38, 10.39, 25.54, 14.47, 17.72, 25.16, 26.0, 4.53, 23.9, 20.83]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    21
1    23
2    14
3    17
4    36
5    17
6    17
7    21
8    14
9    10
10   26
11   14
12   18
13   25
14   26
15    5
16   24
17   21
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  21
1   거창군  일반용  23
2   고성군  일반용  14
3   김해시  일반용  17
4   남해군  일반용  36
5   밀양시  일반용  17
6   사천시  일반용  17
7   산청군  일반용  21
8   양산시  일반용  14
9   의령군  일반용  10
10  진주시  일반용  26
11  창녕군  일반용  14
12  창원시  일반용  18
13  통영시  일반용  25
14  하동군  일반용  26
15  함안군  일반용   5
16  함양군  일반용  24
17  합천군  일반용  21

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201407-201412  경상남도  거제시  일반용   16623   223708382  21
1   201407-201412  경상남도  거제시   합계   18769  1052027794 NaN
2   201407-201412  경상남도  거창군  일반용    4942    46023978  23
3   201407-201412  경상남도  거창군   합계    8771   200694647 NaN
4   201407-201412  경상남도  고성군  일반용    4612    44117114  14
5   201407-201412  경상남도  고성군   합계    8276   307344050 NaN
7   201407-201412  경상남도  김해시  일반용   27972   433204293  17
6   201407-201412  경상남도  김해시   합계   31055  2476569953 NaN
9   201407-201412  경상남도  남해군  일반용    4681    43989581  36
8   201407-201412  경상남도  남해군   합계    7976   122902451 NaN
10  201407-201412  경상남도  밀양시  일반용    8947    81596596  17
11  201407-201412  경상남도  밀양시   합계   15516   475764843 NaN
13  201407-201412  경상남도  사천시  일반용    8943   102564954  17
12  201407-201412  경상남도  사천시   합계   11724   620420135 NaN
14  201407-201412  경상남도  산청군  일반용    3481    28024646  21
15  201407-201412  경상남도  산청군   합계    6542   131379360 NaN
16  201407-201412  경상남도  양산시  일반용   15886   242167522  14
17  201407-201412  경상남도  양산시   합계   17101  1684392118 NaN
18  201407-201412  경상남도  의령군  일반용    2528    19353892  10
19  201407-201412  경상남도  의령군   합계    5394   186248137 NaN
21  201407-201412  경상남도  진주시  일반용   23538   289484545  26
20  201407-201412  경상남도  진주시   합계   29958  1133563109 NaN
23  201407-201412  경상남도  창녕군  일반용    5375    57959096  14
22  201407-201412  경상남도  창녕군   합계    9535   400604542 NaN
24  201407-201412  경상남도  창원시  일반용   55283   941444974  18
25  201407-201412  경상남도  창원시   합계   75154  5312004155 NaN
27  201407-201412  경상남도  통영시  일반용   10393   134754498  25
26  201407-201412  경상남도  통영시   합계   12936   535564543 NaN
29  201407-201412  경상남도  하동군  일반용    4168    38076427  26
28  201407-201412  경상남도  하동군   합계    8270   146471895 NaN
31  201407-201412  경상남도  함안군  일반용    5289    54740750   5
30  201407-201412  경상남도  함안군   합계    8459  1209174332 NaN
33  201407-201412  경상남도  함양군  일반용    3538    28640882  24
32  201407-201412  경상남도  함양군   합계    6518   119853380 NaN
34  201407-201412  경상남도  합천군  일반용    4018    35037567  21
35  201407-201412  경상남도  합천군   합계    7984   168216482 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1407-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)