In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별 전력사용량 월별_14상반기.csv' , encoding='utf-8')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 01 월 ~ 2014년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경상남도,전체(시 / 군 / 구),주택용,"1,067,833","373,443,748","50,257,526,754",134.6
4,201401,경상남도,전체(시 / 군 / 구),일반용,"207,613","550,502,321","73,287,963,710",133.1
...,...,...,...,...,...,...,...,...
907,201406,경상남도,합천군,산업용,956,"6,039,122","744,565,643",123.3
908,201406,경상남도,합천군,심 야,"2,273","1,663,412","88,698,624",53.3
909,201406,경상남도,합천군,일반용,"3,991","5,319,218","716,737,012",134.7
910,201406,경상남도,합천군,주택용,"27,398","4,234,780","478,744,193",113.1
911,201406,경상남도,합천군,합계,"47,152","24,940,322","2,439,905,139",97.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경상남도,전체(시 / 군 / 구),주택용,"1,067,833","373,443,748","50,257,526,754",134.6
4,201401,경상남도,전체(시 / 군 / 구),일반용,"207,613","550,502,321","73,287,963,710",133.1
5,201401,경상남도,전체(시 / 군 / 구),교육용,"1,595","38,191,561","4,630,957,235",121.3
6,201401,경상남도,전체(시 / 군 / 구),산업용,"35,131","1,712,502,127","211,284,408,964",123.4
...,...,...,...,...,...,...,...,...
907,201406,경상남도,합천군,산업용,956,"6,039,122","744,565,643",123.3
908,201406,경상남도,합천군,심 야,"2,273","1,663,412","88,698,624",53.3
909,201406,경상남도,합천군,일반용,"3,991","5,319,218","716,737,012",134.7
910,201406,경상남도,합천군,주택용,"27,398","4,234,780","478,744,193",113.1
911,201406,경상남도,합천군,합계,"47,152","24,940,322","2,439,905,139",97.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경상남도,전체(시 / 군 / 구),주택용,"1,067,833","373,443,748","50,257,526,754",134.6
4,201401,경상남도,전체(시 / 군 / 구),일반용,"207,613","550,502,321","73,287,963,710",133.1
5,201401,경상남도,전체(시 / 군 / 구),교육용,"1,595","38,191,561","4,630,957,235",121.3
6,201401,경상남도,전체(시 / 군 / 구),산업용,"35,131","1,712,502,127","211,284,408,964",123.4
7,201401,경상남도,전체(시 / 군 / 구),농사용,"160,757","279,593,841","12,893,529,660",46.1
...,...,...,...,...,...,...,...,...
907,201406,경상남도,합천군,산업용,956,"6,039,122","744,565,643",123.3
908,201406,경상남도,합천군,심 야,"2,273","1,663,412","88,698,624",53.3
909,201406,경상남도,합천군,일반용,"3,991","5,319,218","716,737,012",134.7
910,201406,경상남도,합천군,주택용,"27,398","4,234,780","478,744,193",113.1
911,201406,경상남도,합천군,합계,"47,152","24,940,322","2,439,905,139",97.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경상남도,전체(시 / 군 / 구),주택용,"1,067,833","373,443,748","50,257,526,754",134.6
4,201401,경상남도,전체(시 / 군 / 구),일반용,"207,613","550,502,321","73,287,963,710",133.1
5,201401,경상남도,전체(시 / 군 / 구),교육용,"1,595","38,191,561","4,630,957,235",121.3
6,201401,경상남도,전체(시 / 군 / 구),산업용,"35,131","1,712,502,127","211,284,408,964",123.4
7,201401,경상남도,전체(시 / 군 / 구),농사용,"160,757","279,593,841","12,893,529,660",46.1
8,201401,경상남도,전체(시 / 군 / 구),가로등,"135,928","24,109,217","2,542,797,987",105.5
9,201401,경상남도,전체(시 / 군 / 구),심 야,"99,265","198,001,972","14,974,870,754",75.6
10,201402,경상남도,전체(시 / 군 / 구),주택용,"1,069,232","373,981,587","50,235,173,805",134.3
11,201402,경상남도,전체(시 / 군 / 구),일반용,"208,027","524,814,833","70,835,231,911",135.0
12,201402,경상남도,전체(시 / 군 / 구),교육용,"1,593","35,759,063","4,406,521,314",123.2
13,201402,경상남도,전체(시 / 군 / 구),산업용,"35,144","1,616,969,025","204,069,655,740",126.2
14,201402,경상남도,전체(시 / 군 / 구),농사용,"160,940","260,236,713","12,082,949,969",46.4
15,201402,경상남도,전체(시 / 군 / 구),가로등,"136,243","22,508,022","2,508,650,679",111.5
16,201402,경상남도,전체(시 / 군 / 구),심 야,"99,145","195,646,870","14,784,247,759",75.6
17,201403,경상남도,전체(시 / 군 / 구),주택용,"1,071,220","328,954,187","39,052,739,510",118.7
18,201403,경상남도,전체(시 / 군 / 구),일반용,"207,887","463,245,428","58,776,165,979",126.9
19,201403,경상남도,전체(시 / 군 / 구),교육용,"1,598","35,783,267","3,848,540,229",107.6
20,201403,경상남도,전체(시 / 군 / 구),산업용,"35,209","1,731,407,285","179,235,712,495",103.5
21,201403,경상남도,전체(시 / 군 / 구),농사용,"185,352","209,628,068","9,915,685,575",47.3
22,201403,경상남도,전체(시 / 군 / 구),가로등,"136,514","20,853,098","2,352,450,299",112.8
23,201403,경상남도,전체(시 / 군 / 구),심 야,"99,051","154,262,400","10,257,891,036",66.5
24,201404,경상남도,전체(시 / 군 / 구),주택용,"1,073,024","341,920,230","41,576,436,135",121.6
25,201404,경상남도,전체(시 / 군 / 구),일반용,"208,312","442,758,641","51,437,472,045",116.2
26,201404,경상남도,전체(시 / 군 / 구),교육용,"1,594","31,814,626","3,354,713,921",105.4
27,201404,경상남도,전체(시 / 군 / 구),산업용,"35,309","1,696,770,222","172,073,189,895",101.4
28,201404,경상남도,전체(시 / 군 / 구),농사용,"162,504","165,077,270","8,083,753,458",49.0
29,201404,경상남도,전체(시 / 군 / 구),가로등,"138,048","20,489,428","2,412,112,527",117.7
30,201404,경상남도,전체(시 / 군 / 구),심 야,"98,930","121,380,475","6,615,329,828",54.5
31,201405,경상남도,전체(시 / 군 / 구),주택용,"1,074,563","320,588,609","36,784,398,040",114.7
32,201405,경상남도,전체(시 / 군 / 구),일반용,"208,569","409,888,736","48,832,664,146",119.1
33,201405,경상남도,전체(시 / 군 / 구),교육용,"1,592","25,733,083","2,988,424,945",116.1
34,201405,경상남도,전체(시 / 군 / 구),산업용,"35,411","1,623,283,328","165,519,825,272",102.0
35,201405,경상남도,전체(시 / 군 / 구),농사용,"163,736","114,213,942","5,989,937,779",52.4
36,201405,경상남도,전체(시 / 군 / 구),가로등,"138,640","19,351,595","2,350,517,828",121.5
37,201405,경상남도,전체(시 / 군 / 구),심 야,"98,691","77,785,567","4,245,723,638",54.6
38,201406,경상남도,전체(시 / 군 / 구),주택용,"1,076,275","321,703,802","37,046,498,928",115.2
39,201406,경상남도,전체(시 / 군 / 구),일반용,"208,941","434,875,918","58,005,695,821",133.4
40,201406,경상남도,전체(시 / 군 / 구),교육용,"1,595","26,588,541","3,539,201,062",133.1
41,201406,경상남도,전체(시 / 군 / 구),산업용,"35,533","1,645,413,284","200,627,212,256",121.9
42,201406,경상남도,전체(시 / 군 / 구),농사용,"164,091","97,740,766","5,012,311,979",51.3
43,201406,경상남도,전체(시 / 군 / 구),가로등,"139,108","18,524,602","2,323,159,553",125.4
44,201406,경상남도,전체(시 / 군 / 구),심 야,"98,457","45,651,954","2,510,579,121",55.0
45,합계,합계,합계,합계,"10,318,200","17,151,949,252","1,893,562,829,541",110.4

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_8180\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201401  경상남도  일반용  207,613   550,502,321
11  201402  경상남도  일반용  208,027   524,814,833
18  201403  경상남도  일반용  207,887   463,245,428
25  201404  경상남도  일반용  208,312   442,758,641
32  201405  경상남도  일반용  208,569   409,888,736
39  201406  경상남도  일반용  208,941   434,875,918

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201401  경상남도  거제시  일반용  16,108   43,055,530
197  201402  경상남도  거제시  일반용  16,189   40,888,634
341  201403  경상남도  거제시  일반용  16,198   36,655,718
485  201404  경상남도  거제시  일반용  16,290   34,949,429
629  201405  경상남도  거제시  일반용  16,325   32,355,278
..      ...   ...  ...  ...      ...          ...
333  201402  경상남도  합천군  일반용   3,984    7,275,381
477  201403  경상남도  합천군  일반용   3,970    6,245,319
621  201404  경상남도  합천군  일반용   3,990    5,912,843
765  201405  경상남도  합천군  일반용   4,000    5,335,714
909  201406  경상남도  합천군  일반용   3,991    5,319,218

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201401  경상남도  거제시   합계  107,705   197,577,467
199  201402  경상남도  거제시   합계  108,062   190,500,425
343  201403  경상남도  거제시   합계  109,806   184,440,235
487  201404  경상남도  거제시   합계  108,903   169,064,524
631  201405  경상남도  거제시   합계  109,428   160,493,806
..      ...   ...  ...  ...       ...           ...
335  201402  경상남도  합천군   합계   46,667    37,020,818
479  201403  경상남도  합천군   합계   48,745    32,063,805
623  201404  경상남도  합천군   합계   46,864    28,783,834
767  201405  경상남도  합천군   합계   47,006    24,971,224
911  201406  경상남도  합천군   합계   47,152    24,940,322

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[197577467, 190500425, 184440235, 169064524, 160493806, 163625140]
[42009597, 40800087, 36433216, 34999285, 30915909, 30421852]
[61997853, 59470801, 56487431, 53307680, 48476908, 43840419]
[470973293, 453281368, 433308299, 428938255, 385559994, 393683019]
[25068892, 24555876, 21547160, 21017233, 19083054, 19356268]
[123499662, 117700973, 104690710, 95205681, 77609498, 70420741]
[117457225, 112629292, 108989134, 105570966, 97922192, 96978002]
[29776307, 28485639, 23873612, 21626386, 18935458, 18699490]
[305463331, 286886460, 286347683, 281556768, 266820302, 272078808]
[40497503, 38667355, 35323550, 32448326, 29957028, 29117188]
[264260249, 251231630, 227081046, 210713690, 183565520, 175990634]
[86494172, 82715024, 75079017, 67971617, 58511281, 57889561]
[989936798, 943742986, 955875223, 918536106, 863821554, 854849301]
[97650878, 91572746, 88122380, 83598345, 76054058, 76715464]
[31975445, 31783346, 27081983, 24935498, 22294923, 23960301]
[230750066, 215104184, 227064570, 222240994, 208569752, 220854501]
[24172849, 23767103, 20324679, 19695704, 17282399, 17077856]
[36783200, 37020818, 32063805, 28783834, 24971224, 24940322]
경상남도 지역별 합계 :  [1065701597, 215579946, 323581092, 2565744228, 130628483, 589127265, 639546811, 141396892, 1699153352, 206010950, 1312842769, 428660672, 5526761968, 513713871, 162031496, 1324584067, 122320590, 184563203]
경상남도 고객호수 평균:  [18166, 8641, 8157, 30621, 7890, 15345, 11594, 6436, 16713, 5308, 29689, 9456, 74939, 12877, 8169, 8313, 6429, 7865]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201401  경상남도  거제시   합계  107,705   197,577,467
1           201402  경상남도  거제시   합계  108,062   190,500,425
2           201403  경상남도  거제시   합계  109,806   184,440,235
3           201404  경상남도  거제시   합계  108,903   169,064,524
4           201405  경상남도  거제시   합계  109,428   160,493,806
..             ...   ...  ...  ...       ...           ...
121  201401-201406  경상남도  통영시   합계     12877     513713871
122  201401-201406  경상남도  하동군   합계      8169     162031496
123  201401-201406  경상남도  함안군   합계      8313    1324584067
124  201401-201406  경상남도  함양군   합계      6429     122320590
125  201401-201406  경상남도  합천군   합계      7865     184563203

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201401-201406']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201401-201406  경상남도  거제시   합계   18166  1065701597
109  201401-201406  경상남도  거창군   합계    8641   215579946
110  201401-201406  경상남도  고성군   합계    8157   323581092
111  201401-201406  경상남도  김해시   합계   30621  2565744228
112  201401-201406  경상남도  남해군   합계    7890   130628483
113  201401-201406  경상남도  밀양시   합계   15345   589127265
114  201401-201406  경상남도  사천시   합계   11594   639546811
115  201401-201406  경상남도  산청군   합계    6436   141396892
116  201401-201406  경상남도  양산시   합계   16713  1699153352
117  201401-201406  경상남도  의령군   합계    5308   206010950
118  201401-201406  경상남도  진주시   합계   29689  1312842769
119  201401-201406  경상남도  창녕군   합계    9456   428660672
120  201401-201406  경상남도  창원시   합계   74939  5526761968
121  201401-201406  경상남도  통영시   합계   12877   513713871
122  201401-201406  경상남도  하동군   합계    8169   162031496
123  201401-201406  경상남도  함안군   합계    8313  1324584067
124  201401-201406  경상남도  함양군   합계    6429   122320590
125  201401-201406  경상남도  합천군   합계    7865   184563203

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201401  경상남도  거제시  일반용  16,108   43,055,530
197  201402  경상남도  거제시  일반용  16,189   40,888,634
341  201403  경상남도  거제시  일반용  16,198   36,655,718
485  201404  경상남도  거제시  일반용  16,290   34,949,429
629  201405  경상남도  거제시  일반용  16,325   32,355,278
..      ...   ...  ...  ...      ...          ...
333  201402  경상남도  합천군  일반용   3,984    7,275,381
477  201403  경상남도  합천군  일반용   3,970    6,245,319
621  201404  경상남도  합천군  일반용   3,990    5,912,843
765  201405  경상남도  합천군  일반용   4,000    5,335,714
909  201406  경상남도  합천군  일반용   3,991    5,319,218

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[43055530, 40888634, 36655718, 34949429, 32355278, 33859812]
[10093221, 9749792, 8284520, 7800421, 6872622, 6949459]
[9253583, 8986242, 7810061, 7491291, 6744772, 6751580]
[79675790, 75588754, 66965155, 64591122, 60945774, 66921597]
[9083859, 8556910, 7550723, 7355175, 6769868, 6663346]
[16702053, 16092347, 13823235, 13176606, 11909188, 12405200]
[20404585, 19619459, 17125675, 16541419, 14875264, 15464374]
[5889396, 5431701, 4770515, 4667922, 4208866, 4163518]
[45876877, 43080594, 38429822, 36585852, 34375011, 36736948]
[4272212, 4266159, 3660392, 3447586, 3079126, 3053409]
[56751578, 54294363, 47830074, 45105351, 41241659, 44131680]
[11743336, 11181837, 9700076, 9259686, 8521935, 8825741]
[179471492, 170293869, 151201595, 144137185, 134815091, 144681671]
[26789651, 25949094, 22725858, 21622254, 19734689, 20097904]
[7661199, 7631392, 6674910, 6714490, 5863360, 6038425]
[10911310, 10397637, 8969096, 8644319, 7987790, 8417070]
[5663773, 5530668, 4822684, 4755690, 4252729, 4394966]
[7202876, 7275381, 6245319, 5912843, 5335714, 5319218]
경상남도 지역별 일반용 합계 :  [221764401, 49750035, 47037529, 414688192, 45979881, 84108629, 104030776, 29131918, 235085104, 21778884, 289354705, 59232611, 924600903, 136919450, 40583776, 55327222, 29420510, 37291351]
경상남도 고객호수 평균:  [16262, 4922, 4518, 27639, 4649, 8794, 8902, 3475, 15626, 2478, 23411, 5320, 55033, 10289, 4164, 5225, 3524, 3988]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8180\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201401  경상남도  거제시  일반용  16,108   43,055,530
1           201402  경상남도  거제시  일반용  16,189   40,888,634
2           201403  경상남도  거제시  일반용  16,198   36,655,718
3           201404  경상남도  거제시  일반용  16,290   34,949,429
4           201405  경상남도  거제시  일반용  16,325   32,355,278
..             ...   ...  ...  ...      ...          ...
121  201401-201406  경상남도  통영시  일반용    10289    136919450
122  201401-201406  경상남도  하동군  일반용     4164     40583776
123  201401-201406  경상남도  함안군  일반용     5225     55327222
124  201401-201406  경상남도  함양군  일반용     3524     29420510
125  201401-201406  경상남도  합천군  일반용     3988     37291351

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201401-201406']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201401-201406  경상남도  거제시  일반용   16262  221764401
109  201401-201406  경상남도  거창군  일반용    4922   49750035
110  201401-201406  경상남도  고성군  일반용    4518   47037529
111  201401-201406  경상남도  김해시  일반용   27639  414688192
112  201401-201406  경상남도  남해군  일반용    4649   45979881
113  201401-201406  경상남도  밀양시  일반용    8794   84108629
114  201401-201406  경상남도  사천시  일반용    8902  104030776
115  201401-201406  경상남도  산청군  일반용    3475   29131918
116  201401-201406  경상남도  양산시  일반용   15626  235085104
117  201401-201406  경상남도  의령군  일반용    2478   21778884
118  201401-201406  경상남도  진주시  일반용   23411  289354705
119  201401-201406  경상남도  창녕군  일반용    5320   59232611
120  201401-201406  경상남도  창원시  일반용   55033  924600903
121  201401-201406  경상남도  통영시  일반용   10289  136919450
122  201401-201406  경상남도  하동군  일반용    4164   40583776
123  201401-201406  경상남도  함안군  일반용    5225   55327222
124  201401-201406  경상남도  함양군  일반용    3524   29420510
125  201401-201406  경상남도  합천군  일반용    3988   37291351

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201401-201406  경상남도  거제시  일반용   16262   221764401
108  201401-201406  경상남도  거제시   합계   18166  1065701597
109  201401-201406  경상남도  거창군  일반용    4922    49750035
109  201401-201406  경상남도  거창군   합계    8641   215579946
110  201401-201406  경상남도  고성군  일반용    4518    47037529
110  201401-201406  경상남도  고성군   합계    8157   323581092
111  201401-201406  경상남도  김해시   합계   30621  2565744228
111  201401-201406  경상남도  김해시  일반용   27639   414688192
112  201401-201406  경상남도  남해군   합계    7890   130628483
112  201401-201406  경상남도  남해군  일반용    4649    45979881
113  201401-201406  경상남도  밀양시  일반용    8794    84108629
113  201401-201406  경상남도  밀양시   합계   15345   589127265
114  201401-201406  경상남도  사천시   합계   11594   639546811
114  201401-201406  경상남도  사천시  일반용    8902   104030776
115  201401-201406  경상남도  산청군  일반용    3475    29131918
115  201401-201406  경상남도  산청군   합계    6436   141396892
116  201401-201406  경상남도  양산시  일반용   15626   235085104
116  201401-201406  경상남도  양산시   합계   16713  1699153352
117  201401-201406  경상남도  의령군  일반용    2478    21778884
117  201401-201406  경상남도  의령군   합계    5308   206010950
118  201401-201406  경상남도  진주시   합계   29689  1312842769
118  201401-201406  경상남도  진주시  일반용   23411   289354705
119  201401-201406  경상남도  창녕군   합계    9456   428660672
119  201401-201406  경상남도  창녕군  일반용    5320    59232611
120  201401-201406  경상남도  창원시  일반용   55033   924600903
120  201401-201406  경상남도  창원시   합계   74939  5526761968
121  201401-201406  경상남도  통영시   합계   12877   513713871
121  201401-201406  경상남도  통영시  일반용   10289   136919450
122  201401-201406  경상남도  하동군   합계    8169   162031496
122  201401-201406  경상남도  하동군  일반용    4164    40583776
123  201401-201406  경상남도  함안군   합계    8313  1324584067
123  201401-201406  경상남도  함안군  일반용    5225    55327222
124  201401-201406  경상남도  함양군   합계    6429   122320590
124  201401-201406  경상남도  함양군  일반용    3524    29420510
125  201401-201406  경상남도  합천군  일반용    3988    37291351
125  201401-201406  경상남도  합천군   합계    7865   184563203

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[221764401,
 49750035,
 47037529,
 414688192,
 45979881,
 84108629,
 104030776,
 29131918,
 235085104,
 21778884,
 289354705,
 59232611,
 924600903,
 136919450,
 40583776,
 55327222,
 29420510,
 37291351]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1065701597,
 215579946,
 323581092,
 2565744228,
 130628483,
 589127265,
 639546811,
 141396892,
 1699153352,
 206010950,
 1312842769,
 428660672,
 5526761968,
 513713871,
 162031496,
 1324584067,
 122320590,
 184563203]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[20.81, 23.08, 14.54, 16.16, 35.2, 14.28, 16.27, 20.6, 13.84, 10.57, 22.04, 13.82, 16.73, 26.65, 25.05, 4.18, 24.05, 20.21]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    21
1    23
2    15
3    16
4    35
5    14
6    16
7    21
8    14
9    11
10   22
11   14
12   17
13   27
14   25
15    4
16   24
17   20
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  21
1   거창군  일반용  23
2   고성군  일반용  15
3   김해시  일반용  16
4   남해군  일반용  35
5   밀양시  일반용  14
6   사천시  일반용  16
7   산청군  일반용  21
8   양산시  일반용  14
9   의령군  일반용  11
10  진주시  일반용  22
11  창녕군  일반용  14
12  창원시  일반용  17
13  통영시  일반용  27
14  하동군  일반용  25
15  함안군  일반용   4
16  함양군  일반용  24
17  합천군  일반용  20

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201401-201406  경상남도  거제시  일반용   16262   221764401  21
1   201401-201406  경상남도  거제시   합계   18166  1065701597 NaN
2   201401-201406  경상남도  거창군  일반용    4922    49750035  23
3   201401-201406  경상남도  거창군   합계    8641   215579946 NaN
4   201401-201406  경상남도  고성군  일반용    4518    47037529  15
5   201401-201406  경상남도  고성군   합계    8157   323581092 NaN
7   201401-201406  경상남도  김해시  일반용   27639   414688192  16
6   201401-201406  경상남도  김해시   합계   30621  2565744228 NaN
9   201401-201406  경상남도  남해군  일반용    4649    45979881  35
8   201401-201406  경상남도  남해군   합계    7890   130628483 NaN
10  201401-201406  경상남도  밀양시  일반용    8794    84108629  14
11  201401-201406  경상남도  밀양시   합계   15345   589127265 NaN
13  201401-201406  경상남도  사천시  일반용    8902   104030776  16
12  201401-201406  경상남도  사천시   합계   11594   639546811 NaN
14  201401-201406  경상남도  산청군  일반용    3475    29131918  21
15  201401-201406  경상남도  산청군   합계    6436   141396892 NaN
16  201401-201406  경상남도  양산시  일반용   15626   235085104  14
17  201401-201406  경상남도  양산시   합계   16713  1699153352 NaN
18  201401-201406  경상남도  의령군  일반용    2478    21778884  11
19  201401-201406  경상남도  의령군   합계    5308   206010950 NaN
21  201401-201406  경상남도  진주시  일반용   23411   289354705  22
20  201401-201406  경상남도  진주시   합계   29689  1312842769 NaN
23  201401-201406  경상남도  창녕군  일반용    5320    59232611  14
22  201401-201406  경상남도  창녕군   합계    9456   428660672 NaN
24  201401-201406  경상남도  창원시  일반용   55033   924600903  17
25  201401-201406  경상남도  창원시   합계   74939  5526761968 NaN
27  201401-201406  경상남도  통영시  일반용   10289   136919450  27
26  201401-201406  경상남도  통영시   합계   12877   513713871 NaN
29  201401-201406  경상남도  하동군  일반용    4164    40583776  25
28  201401-201406  경상남도  하동군   합계    8169   162031496 NaN
31  201401-201406  경상남도  함안군  일반용    5225    55327222   4
30  201401-201406  경상남도  함안군   합계    8313  1324584067 NaN
33  201401-201406  경상남도  함양군  일반용    3524    29420510  24
32  201401-201406  경상남도  함양군   합계    6429   122320590 NaN
34  201401-201406  경상남도  합천군  일반용    3988    37291351  20
35  201401-201406  경상남도  합천군   합계    7865   184563203 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1401-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)