In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_18상반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2018년 01 월 ~ 2018년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,경상남도,전체(시 / 군 / 구),주택용,"1,158,098","408,433,087","46,474,474,622",113.8
4,201801,경상남도,전체(시 / 군 / 구),일반용,"219,668","643,777,385","85,582,355,670",132.9
...,...,...,...,...,...,...,...,...
907,201806,경상남도,합천군,산업용,"1,083","5,775,798","718,504,486",124.4
908,201806,경상남도,합천군,심 야,"2,132","1,373,354","74,188,657",54
909,201806,경상남도,합천군,일반용,"3,888","5,774,819","790,951,901",137
910,201806,경상남도,합천군,주택용,"28,955","4,168,632","447,309,961",107.3
911,201806,경상남도,합천군,합계,"53,692","26,769,439","2,556,265,582",95.5

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,경상남도,전체(시 / 군 / 구),주택용,"1,158,098","408,433,087","46,474,474,622",113.8
4,201801,경상남도,전체(시 / 군 / 구),일반용,"219,668","643,777,385","85,582,355,670",132.9
5,201801,경상남도,전체(시 / 군 / 구),교육용,"1,662","45,124,915","4,883,406,889",108.2
6,201801,경상남도,전체(시 / 군 / 구),산업용,"37,589","1,759,012,641","217,780,013,339",123.8
...,...,...,...,...,...,...,...,...
907,201806,경상남도,합천군,산업용,"1,083","5,775,798","718,504,486",124.4
908,201806,경상남도,합천군,심 야,"2,132","1,373,354","74,188,657",54
909,201806,경상남도,합천군,일반용,"3,888","5,774,819","790,951,901",137
910,201806,경상남도,합천군,주택용,"28,955","4,168,632","447,309,961",107.3
911,201806,경상남도,합천군,합계,"53,692","26,769,439","2,556,265,582",95.5

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,경상남도,전체(시 / 군 / 구),주택용,"1,158,098","408,433,087","46,474,474,622",113.8
4,201801,경상남도,전체(시 / 군 / 구),일반용,"219,668","643,777,385","85,582,355,670",132.9
5,201801,경상남도,전체(시 / 군 / 구),교육용,"1,662","45,124,915","4,883,406,889",108.2
6,201801,경상남도,전체(시 / 군 / 구),산업용,"37,589","1,759,012,641","217,780,013,339",123.8
7,201801,경상남도,전체(시 / 군 / 구),농사용,"197,207","352,292,519","16,464,579,643",46.7
...,...,...,...,...,...,...,...,...
907,201806,경상남도,합천군,산업용,"1,083","5,775,798","718,504,486",124.4
908,201806,경상남도,합천군,심 야,"2,132","1,373,354","74,188,657",54
909,201806,경상남도,합천군,일반용,"3,888","5,774,819","790,951,901",137
910,201806,경상남도,합천군,주택용,"28,955","4,168,632","447,309,961",107.3
911,201806,경상남도,합천군,합계,"53,692","26,769,439","2,556,265,582",95.5

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,경상남도,전체(시 / 군 / 구),주택용,"1,158,098","408,433,087","46,474,474,622",113.8
4,201801,경상남도,전체(시 / 군 / 구),일반용,"219,668","643,777,385","85,582,355,670",132.9
5,201801,경상남도,전체(시 / 군 / 구),교육용,"1,662","45,124,915","4,883,406,889",108.2
6,201801,경상남도,전체(시 / 군 / 구),산업용,"37,589","1,759,012,641","217,780,013,339",123.8
7,201801,경상남도,전체(시 / 군 / 구),농사용,"197,207","352,292,519","16,464,579,643",46.7
8,201801,경상남도,전체(시 / 군 / 구),가로등,"163,004","26,310,716","2,800,505,098",106.4
9,201801,경상남도,전체(시 / 군 / 구),심 야,"90,651","158,421,226","11,937,323,198",75.4
10,201802,경상남도,전체(시 / 군 / 구),주택용,"1,158,535","410,009,567","47,001,979,143",114.6
11,201802,경상남도,전체(시 / 군 / 구),일반용,"219,924","659,018,941","87,405,918,764",132.6
12,201802,경상남도,전체(시 / 군 / 구),교육용,"1,664","44,287,739","4,838,344,600",109.2
13,201802,경상남도,전체(시 / 군 / 구),산업용,"37,620","1,598,388,953","200,209,491,529",125.3
14,201802,경상남도,전체(시 / 군 / 구),농사용,"197,404","355,164,057","16,567,360,565",46.6
15,201802,경상남도,전체(시 / 군 / 구),가로등,"163,296","24,850,243","2,780,941,557",111.9
16,201802,경상남도,전체(시 / 군 / 구),심 야,"90,365","166,431,374","12,531,833,725",75.3
17,201803,경상남도,전체(시 / 군 / 구),주택용,"1,158,855","354,742,370","36,644,042,511",103.3
18,201803,경상남도,전체(시 / 군 / 구),일반용,"219,970","524,417,284","66,913,423,446",127.6
19,201803,경상남도,전체(시 / 군 / 구),교육용,"1,665","37,692,748","3,980,134,557",105.6
20,201803,경상남도,전체(시 / 군 / 구),산업용,"37,658","1,653,958,750","172,759,166,114",104.5
21,201803,경상남도,전체(시 / 군 / 구),농사용,"222,302","251,039,957","12,122,619,774",48.3
22,201803,경상남도,전체(시 / 군 / 구),가로등,"163,768","23,201,604","2,630,114,140",113.4
23,201803,경상남도,전체(시 / 군 / 구),심 야,"90,079","122,887,475","8,167,058,798",66.5
24,201804,경상남도,전체(시 / 군 / 구),주택용,"1,160,156","362,725,993","38,274,442,345",105.5
25,201804,경상남도,전체(시 / 군 / 구),일반용,"220,176","505,691,396","58,728,969,834",116.1
26,201804,경상남도,전체(시 / 군 / 구),교육용,"1,670","34,538,612","3,404,494,918",98.6
27,201804,경상남도,전체(시 / 군 / 구),산업용,"37,684","1,625,524,588","165,981,396,317",102.1
28,201804,경상남도,전체(시 / 군 / 구),농사용,"198,949","198,083,090","9,855,856,817",49.8
29,201804,경상남도,전체(시 / 군 / 구),가로등,"164,309","23,161,634","2,700,435,273",116.6
30,201804,경상남도,전체(시 / 군 / 구),심 야,"89,793","90,828,316","4,940,035,792",54.4
31,201805,경상남도,전체(시 / 군 / 구),주택용,"1,160,967","339,586,822","34,272,229,150",100.9
32,201805,경상남도,전체(시 / 군 / 구),일반용,"220,354","470,659,317","56,475,063,687",120.0
33,201805,경상남도,전체(시 / 군 / 구),교육용,"1,668","28,031,156","2,720,209,809",97.0
34,201805,경상남도,전체(시 / 군 / 구),산업용,"37,746","1,616,525,681","164,557,611,385",101.8
35,201805,경상남도,전체(시 / 군 / 구),농사용,"199,646","131,104,407","6,993,390,533",53.3
36,201805,경상남도,전체(시 / 군 / 구),가로등,"164,877","21,717,728","2,618,057,521",120.5
37,201805,경상남도,전체(시 / 군 / 구),심 야,"89,452","56,707,462","3,104,159,647",54.7
38,201806,경상남도,전체(시 / 군 / 구),주택용,"1,161,480","346,383,563","35,456,247,062",102.4
39,201806,경상남도,전체(시 / 군 / 구),일반용,"220,567","508,484,745","67,877,142,028",133.5
40,201806,경상남도,전체(시 / 군 / 구),교육용,"1,670","30,653,477","3,687,549,804",120.3
41,201806,경상남도,전체(시 / 군 / 구),산업용,"37,850","1,630,759,452","197,769,282,085",121.3
42,201806,경상남도,전체(시 / 군 / 구),농사용,"199,367","121,179,647","6,219,122,752",51.3
43,201806,경상남도,전체(시 / 군 / 구),가로등,"165,419","21,233,326","2,623,399,839",123.6
44,201806,경상남도,전체(시 / 군 / 구),심 야,"89,137","36,053,041","1,997,889,029",55.4
45,합계,합계,합계,합계,"11,253,921","17,819,097,004","1,930,732,073,309",108.4

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_13200\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201801  경상남도  일반용  219,668   643,777,385
11  201802  경상남도  일반용  219,924   659,018,941
18  201803  경상남도  일반용  219,970   524,417,284
25  201804  경상남도  일반용  220,176   505,691,396
32  201805  경상남도  일반용  220,354   470,659,317
39  201806  경상남도  일반용  220,567   508,484,745

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201801  경상남도  거제시  일반용  17,706   47,368,871
197  201802  경상남도  거제시  일반용  17,763   47,818,207
341  201803  경상남도  거제시  일반용  17,751   38,030,630
485  201804  경상남도  거제시  일반용  17,718   36,139,811
629  201805  경상남도  거제시  일반용  17,735   33,911,604
..      ...   ...  ...  ...      ...          ...
333  201802  경상남도  합천군  일반용   3,877    9,050,562
477  201803  경상남도  합천군  일반용   3,874    6,987,095
621  201804  경상남도  합천군  일반용   3,881    6,426,080
765  201805  경상남도  합천군  일반용   3,881    5,662,446
909  201806  경상남도  합천군  일반용   3,888    5,774,819

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201801  경상남도  거제시   합계  124,714   190,801,023
199  201802  경상남도  거제시   합계  124,610   175,258,762
343  201803  경상남도  거제시   합계  125,787   163,174,992
487  201804  경상남도  거제시   합계  124,543   155,721,178
631  201805  경상남도  거제시   합계  124,612   155,015,393
..      ...   ...  ...  ...       ...           ...
335  201802  경상남도  합천군   합계   53,125    43,250,021
479  201803  경상남도  합천군   합계   55,357    34,622,947
623  201804  경상남도  합천군   합계   53,319    31,415,498
767  201805  경상남도  합천군   합계   53,489    26,459,551
911  201806  경상남도  합천군   합계   53,692    26,769,439

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[190801023, 175258762, 163174992, 155721178, 155015393, 163983626]
[45059712, 45547166, 38348282, 36106845, 32563644, 32979028]
[55910216, 55094462, 49256895, 45917676, 40066125, 36798043]
[506503422, 511205713, 440659508, 441747480, 415824386, 423375600]
[26357658, 26822915, 21622054, 20960948, 19180332, 20260756]
[142558204, 142096744, 116979227, 103437413, 85330471, 80885957]
[130343741, 124928801, 116457948, 111865295, 107770057, 108461035]
[37237180, 37543577, 29877946, 26983149, 24120464, 24164507]
[343331222, 324486418, 306661822, 301150050, 293819356, 301962932]
[43720669, 43135078, 36926368, 34461175, 30942497, 30561978]
[292490945, 297400822, 242558690, 221584812, 194265331, 192561583]
[106534114, 104767484, 89325618, 82834880, 72642788, 74062469]
[1024617687, 943535350, 919945586, 878900761, 841795772, 849911981]
[95248645, 92521069, 76582199, 72225761, 64453251, 63403735]
[36456592, 37536697, 29188509, 27798579, 23909737, 26059528]
[246809159, 224986272, 233293764, 225662019, 216809126, 218879591]
[26977699, 28033523, 22457833, 21780110, 19364292, 19665463]
[42414601, 43250021, 34622947, 31415498, 26459551, 26769439]
경상남도 지역별 합계 :  [1003954974, 230604677, 283043417, 2739316109, 135204663, 671288016, 699826877, 179926823, 1871411800, 219747765, 1440862183, 530167353, 5458707137, 464434660, 180949642, 1366439931, 138278920, 204932057]
경상남도 고객호수 평균:  [20804, 9639, 9024, 33984, 8407, 17027, 12943, 7266, 20199, 5898, 32612, 10513, 76162, 13760, 9184, 9137, 7098, 8944]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201801  경상남도  거제시   합계  124,714   190,801,023
1           201802  경상남도  거제시   합계  124,610   175,258,762
2           201803  경상남도  거제시   합계  125,787   163,174,992
3           201804  경상남도  거제시   합계  124,543   155,721,178
4           201805  경상남도  거제시   합계  124,612   155,015,393
..             ...   ...  ...  ...       ...           ...
121  201801-201806  경상남도  통영시   합계     13760     464434660
122  201801-201806  경상남도  하동군   합계      9184     180949642
123  201801-201806  경상남도  함안군   합계      9137    1366439931
124  201801-201806  경상남도  함양군   합계      7098     138278920
125  201801-201806  경상남도  합천군   합계      8944     204932057

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201801-201806']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201801-201806  경상남도  거제시   합계   20804  1003954974
109  201801-201806  경상남도  거창군   합계    9639   230604677
110  201801-201806  경상남도  고성군   합계    9024   283043417
111  201801-201806  경상남도  김해시   합계   33984  2739316109
112  201801-201806  경상남도  남해군   합계    8407   135204663
113  201801-201806  경상남도  밀양시   합계   17027   671288016
114  201801-201806  경상남도  사천시   합계   12943   699826877
115  201801-201806  경상남도  산청군   합계    7266   179926823
116  201801-201806  경상남도  양산시   합계   20199  1871411800
117  201801-201806  경상남도  의령군   합계    5898   219747765
118  201801-201806  경상남도  진주시   합계   32612  1440862183
119  201801-201806  경상남도  창녕군   합계   10513   530167353
120  201801-201806  경상남도  창원시   합계   76162  5458707137
121  201801-201806  경상남도  통영시   합계   13760   464434660
122  201801-201806  경상남도  하동군   합계    9184   180949642
123  201801-201806  경상남도  함안군   합계    9137  1366439931
124  201801-201806  경상남도  함양군   합계    7098   138278920
125  201801-201806  경상남도  합천군   합계    8944   204932057

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201801  경상남도  거제시  일반용  17,706   47,368,871
197  201802  경상남도  거제시  일반용  17,763   47,818,207
341  201803  경상남도  거제시  일반용  17,751   38,030,630
485  201804  경상남도  거제시  일반용  17,718   36,139,811
629  201805  경상남도  거제시  일반용  17,735   33,911,604
..      ...   ...  ...  ...      ...          ...
333  201802  경상남도  합천군  일반용   3,877    9,050,562
477  201803  경상남도  합천군  일반용   3,874    6,987,095
621  201804  경상남도  합천군  일반용   3,881    6,426,080
765  201805  경상남도  합천군  일반용   3,881    5,662,446
909  201806  경상남도  합천군  일반용   3,888    5,774,819

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[47368871, 47818207, 38030630, 36139811, 33911604, 35829199]
[11075873, 11471577, 8804585, 8185722, 7190059, 7471028]
[10731817, 11202307, 8841650, 8514639, 7437294, 7762237]
[96719452, 100714339, 79538152, 78835447, 75061642, 82595887]
[9989086, 10106790, 7998899, 7911383, 7189693, 7275262]
[21210862, 21740948, 16624047, 15918535, 14440800, 15401942]
[24497888, 25387369, 20379431, 19681077, 17895269, 18867457]
[7033691, 7226034, 5756262, 5540637, 4962217, 5047415]
[59208821, 60243563, 48008079, 47700811, 45311790, 49743904]
[4912419, 5160074, 4032636, 3818085, 3362385, 3451566]
[68577681, 69708455, 56113877, 53297984, 49174572, 53374765]
[13672098, 13984729, 11115025, 10435480, 9399199, 9973354]
[200737202, 203640255, 163204949, 156079089, 147050296, 161023988]
[31807565, 32509092, 25576715, 24472173, 22156280, 23097467]
[8382319, 8877462, 6884025, 6735932, 5768690, 5940403]
[12872952, 13331584, 11100673, 10809339, 10023527, 11057653]
[6456880, 6845594, 5420554, 5189172, 4661554, 4796399]
[8521908, 9050562, 6987095, 6426080, 5662446, 5774819]
경상남도 지역별 일반용 합계 :  [239098322, 54198844, 54489944, 513464919, 50471113, 105337134, 126708491, 35566256, 310216968, 24737165, 350247334, 68579885, 1031735779, 159619292, 42588831, 69195728, 33370153, 42422910]
경상남도 고객호수 평균:  [17732, 5012, 4507, 29863, 4694, 9168, 9431, 3436, 18549, 2335, 25268, 5411, 56500, 11290, 4203, 5266, 3558, 3879]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13200\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201801  경상남도  거제시  일반용  17,706   47,368,871
1           201802  경상남도  거제시  일반용  17,763   47,818,207
2           201803  경상남도  거제시  일반용  17,751   38,030,630
3           201804  경상남도  거제시  일반용  17,718   36,139,811
4           201805  경상남도  거제시  일반용  17,735   33,911,604
..             ...   ...  ...  ...      ...          ...
121  201801-201806  경상남도  통영시  일반용    11290    159619292
122  201801-201806  경상남도  하동군  일반용     4203     42588831
123  201801-201806  경상남도  함안군  일반용     5266     69195728
124  201801-201806  경상남도  함양군  일반용     3558     33370153
125  201801-201806  경상남도  합천군  일반용     3879     42422910

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201801-201806']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201801-201806  경상남도  거제시  일반용   17732   239098322
109  201801-201806  경상남도  거창군  일반용    5012    54198844
110  201801-201806  경상남도  고성군  일반용    4507    54489944
111  201801-201806  경상남도  김해시  일반용   29863   513464919
112  201801-201806  경상남도  남해군  일반용    4694    50471113
113  201801-201806  경상남도  밀양시  일반용    9168   105337134
114  201801-201806  경상남도  사천시  일반용    9431   126708491
115  201801-201806  경상남도  산청군  일반용    3436    35566256
116  201801-201806  경상남도  양산시  일반용   18549   310216968
117  201801-201806  경상남도  의령군  일반용    2335    24737165
118  201801-201806  경상남도  진주시  일반용   25268   350247334
119  201801-201806  경상남도  창녕군  일반용    5411    68579885
120  201801-201806  경상남도  창원시  일반용   56500  1031735779
121  201801-201806  경상남도  통영시  일반용   11290   159619292
122  201801-201806  경상남도  하동군  일반용    4203    42588831
123  201801-201806  경상남도  함안군  일반용    5266    69195728
124  201801-201806  경상남도  함양군  일반용    3558    33370153
125  201801-201806  경상남도  합천군  일반용    3879    42422910

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201801-201806  경상남도  거제시  일반용   17732   239098322
108  201801-201806  경상남도  거제시   합계   20804  1003954974
109  201801-201806  경상남도  거창군  일반용    5012    54198844
109  201801-201806  경상남도  거창군   합계    9639   230604677
110  201801-201806  경상남도  고성군  일반용    4507    54489944
110  201801-201806  경상남도  고성군   합계    9024   283043417
111  201801-201806  경상남도  김해시   합계   33984  2739316109
111  201801-201806  경상남도  김해시  일반용   29863   513464919
112  201801-201806  경상남도  남해군   합계    8407   135204663
112  201801-201806  경상남도  남해군  일반용    4694    50471113
113  201801-201806  경상남도  밀양시  일반용    9168   105337134
113  201801-201806  경상남도  밀양시   합계   17027   671288016
114  201801-201806  경상남도  사천시   합계   12943   699826877
114  201801-201806  경상남도  사천시  일반용    9431   126708491
115  201801-201806  경상남도  산청군  일반용    3436    35566256
115  201801-201806  경상남도  산청군   합계    7266   179926823
116  201801-201806  경상남도  양산시  일반용   18549   310216968
116  201801-201806  경상남도  양산시   합계   20199  1871411800
117  201801-201806  경상남도  의령군  일반용    2335    24737165
117  201801-201806  경상남도  의령군   합계    5898   219747765
118  201801-201806  경상남도  진주시   합계   32612  1440862183
118  201801-201806  경상남도  진주시  일반용   25268   350247334
119  201801-201806  경상남도  창녕군   합계   10513   530167353
119  201801-201806  경상남도  창녕군  일반용    5411    68579885
120  201801-201806  경상남도  창원시  일반용   56500  1031735779
120  201801-201806  경상남도  창원시   합계   76162  5458707137
121  201801-201806  경상남도  통영시   합계   13760   464434660
121  201801-201806  경상남도  통영시  일반용   11290   159619292
122  201801-201806  경상남도  하동군   합계    9184   180949642
122  201801-201806  경상남도  하동군  일반용    4203    42588831
123  201801-201806  경상남도  함안군   합계    9137  1366439931
123  201801-201806  경상남도  함안군  일반용    5266    69195728
124  201801-201806  경상남도  함양군   합계    7098   138278920
124  201801-201806  경상남도  함양군  일반용    3558    33370153
125  201801-201806  경상남도  합천군  일반용    3879    42422910
125  201801-201806  경상남도  합천군   합계    8944   204932057

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[239098322,
 54198844,
 54489944,
 513464919,
 50471113,
 105337134,
 126708491,
 35566256,
 310216968,
 24737165,
 350247334,
 68579885,
 1031735779,
 159619292,
 42588831,
 69195728,
 33370153,
 42422910]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1003954974,
 230604677,
 283043417,
 2739316109,
 135204663,
 671288016,
 699826877,
 179926823,
 1871411800,
 219747765,
 1440862183,
 530167353,
 5458707137,
 464434660,
 180949642,
 1366439931,
 138278920,
 204932057]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[23.82, 23.5, 19.25, 18.74, 37.33, 15.69, 18.11, 19.77, 16.58, 11.26, 24.31, 12.94, 18.9, 34.37, 23.54, 5.06, 24.13, 20.7]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    24
1    24
2    19
3    19
4    37
5    16
6    18
7    20
8    17
9    11
10   24
11   13
12   19
13   34
14   24
15    5
16   24
17   21
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  24
1   거창군  일반용  24
2   고성군  일반용  19
3   김해시  일반용  19
4   남해군  일반용  37
5   밀양시  일반용  16
6   사천시  일반용  18
7   산청군  일반용  20
8   양산시  일반용  17
9   의령군  일반용  11
10  진주시  일반용  24
11  창녕군  일반용  13
12  창원시  일반용  19
13  통영시  일반용  34
14  하동군  일반용  24
15  함안군  일반용   5
16  함양군  일반용  24
17  합천군  일반용  21

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201801-201806  경상남도  거제시  일반용   17732   239098322  24
1   201801-201806  경상남도  거제시   합계   20804  1003954974 NaN
2   201801-201806  경상남도  거창군  일반용    5012    54198844  24
3   201801-201806  경상남도  거창군   합계    9639   230604677 NaN
4   201801-201806  경상남도  고성군  일반용    4507    54489944  19
5   201801-201806  경상남도  고성군   합계    9024   283043417 NaN
7   201801-201806  경상남도  김해시  일반용   29863   513464919  19
6   201801-201806  경상남도  김해시   합계   33984  2739316109 NaN
9   201801-201806  경상남도  남해군  일반용    4694    50471113  37
8   201801-201806  경상남도  남해군   합계    8407   135204663 NaN
10  201801-201806  경상남도  밀양시  일반용    9168   105337134  16
11  201801-201806  경상남도  밀양시   합계   17027   671288016 NaN
13  201801-201806  경상남도  사천시  일반용    9431   126708491  18
12  201801-201806  경상남도  사천시   합계   12943   699826877 NaN
14  201801-201806  경상남도  산청군  일반용    3436    35566256  20
15  201801-201806  경상남도  산청군   합계    7266   179926823 NaN
16  201801-201806  경상남도  양산시  일반용   18549   310216968  17
17  201801-201806  경상남도  양산시   합계   20199  1871411800 NaN
18  201801-201806  경상남도  의령군  일반용    2335    24737165  11
19  201801-201806  경상남도  의령군   합계    5898   219747765 NaN
21  201801-201806  경상남도  진주시  일반용   25268   350247334  24
20  201801-201806  경상남도  진주시   합계   32612  1440862183 NaN
23  201801-201806  경상남도  창녕군  일반용    5411    68579885  13
22  201801-201806  경상남도  창녕군   합계   10513   530167353 NaN
24  201801-201806  경상남도  창원시  일반용   56500  1031735779  19
25  201801-201806  경상남도  창원시   합계   76162  5458707137 NaN
27  201801-201806  경상남도  통영시  일반용   11290   159619292  34
26  201801-201806  경상남도  통영시   합계   13760   464434660 NaN
29  201801-201806  경상남도  하동군  일반용    4203    42588831  24
28  201801-201806  경상남도  하동군   합계    9184   180949642 NaN
31  201801-201806  경상남도  함안군  일반용    5266    69195728   5
30  201801-201806  경상남도  함안군   합계    9137  1366439931 NaN
33  201801-201806  경상남도  함양군  일반용    3558    33370153  24
32  201801-201806  경상남도  함양군   합계    7098   138278920 NaN
34  201801-201806  경상남도  합천군  일반용    3879    42422910  21
35  201801-201806  경상남도  합천군   합계    8944   204932057 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1801-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)