In [3]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [4]:
df = pd.read_csv('강원도_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 강원도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,강원도,전체(시 / 군 / 구),주택용,"531,484","185,493,055","25,316,445,616",136.5
4,201501,강원도,전체(시 / 군 / 구),일반용,"133,674","429,343,867","55,142,435,698",128.4
...,...,...,...,...,...,...,...,...
907,201506,강원도,횡성군,산업용,559,"13,808,753","1,854,027,045",134.3
908,201506,강원도,횡성군,심 야,"6,527","4,435,531","238,889,511",53.9
909,201506,강원도,횡성군,일반용,"4,654","9,125,420","1,309,886,283",143.5
910,201506,강원도,횡성군,주택용,"20,745","4,300,774","503,291,450",117
911,201506,강원도,횡성군,합계,"47,182","37,137,317","4,273,231,657",115.1

In [5]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,강원도,전체(시 / 군 / 구),주택용,"531,484","185,493,055","25,316,445,616",136.5
4,201501,강원도,전체(시 / 군 / 구),일반용,"133,674","429,343,867","55,142,435,698",128.4
5,201501,강원도,전체(시 / 군 / 구),교육용,"1,046","36,325,776","3,949,978,057",108.7
6,201501,강원도,전체(시 / 군 / 구),산업용,"12,216","585,592,815","67,086,006,515",114.6
...,...,...,...,...,...,...,...,...
907,201506,강원도,횡성군,산업용,559,"13,808,753","1,854,027,045",134.3
908,201506,강원도,횡성군,심 야,"6,527","4,435,531","238,889,511",53.9
909,201506,강원도,횡성군,일반용,"4,654","9,125,420","1,309,886,283",143.5
910,201506,강원도,횡성군,주택용,"20,745","4,300,774","503,291,450",117
911,201506,강원도,횡성군,합계,"47,182","37,137,317","4,273,231,657",115.1

In [6]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [7]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,강원도,전체(시 / 군 / 구),주택용,"531,484","185,493,055","25,316,445,616",136.5
4,201501,강원도,전체(시 / 군 / 구),일반용,"133,674","429,343,867","55,142,435,698",128.4
5,201501,강원도,전체(시 / 군 / 구),교육용,"1,046","36,325,776","3,949,978,057",108.7
6,201501,강원도,전체(시 / 군 / 구),산업용,"12,216","585,592,815","67,086,006,515",114.6
7,201501,강원도,전체(시 / 군 / 구),농사용,"81,390","46,499,518","2,303,025,754",49.5
...,...,...,...,...,...,...,...,...
907,201506,강원도,횡성군,산업용,559,"13,808,753","1,854,027,045",134.3
908,201506,강원도,횡성군,심 야,"6,527","4,435,531","238,889,511",53.9
909,201506,강원도,횡성군,일반용,"4,654","9,125,420","1,309,886,283",143.5
910,201506,강원도,횡성군,주택용,"20,745","4,300,774","503,291,450",117
911,201506,강원도,횡성군,합계,"47,182","37,137,317","4,273,231,657",115.1

In [8]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,강원도,전체(시 / 군 / 구),주택용,"531,484","185,493,055","25,316,445,616",136.5
4,201501,강원도,전체(시 / 군 / 구),일반용,"133,674","429,343,867","55,142,435,698",128.4
5,201501,강원도,전체(시 / 군 / 구),교육용,"1,046","36,325,776","3,949,978,057",108.7
6,201501,강원도,전체(시 / 군 / 구),산업용,"12,216","585,592,815","67,086,006,515",114.6
7,201501,강원도,전체(시 / 군 / 구),농사용,"81,390","46,499,518","2,303,025,754",49.5
8,201501,강원도,전체(시 / 군 / 구),가로등,"97,380","16,996,873","1,799,269,879",105.9
9,201501,강원도,전체(시 / 군 / 구),심 야,"95,118","316,777,297","23,799,141,527",75.1
10,201502,강원도,전체(시 / 군 / 구),주택용,"531,854","181,370,455","24,190,316,551",133.4
11,201502,강원도,전체(시 / 군 / 구),일반용,"133,749","398,802,339","52,217,139,923",130.9
12,201502,강원도,전체(시 / 군 / 구),교육용,"1,045","31,595,432","3,556,152,110",112.6
13,201502,강원도,전체(시 / 군 / 구),산업용,"12,226","534,452,784","60,992,803,650",114.1
14,201502,강원도,전체(시 / 군 / 구),농사용,"81,298","45,434,429","2,256,426,939",49.7
15,201502,강원도,전체(시 / 군 / 구),가로등,"97,570","15,436,920","1,711,432,413",110.9
16,201502,강원도,전체(시 / 군 / 구),심 야,"95,090","291,744,330","21,905,230,871",75.1
17,201503,강원도,전체(시 / 군 / 구),주택용,"532,549","159,818,214","18,997,187,796",118.9
18,201503,강원도,전체(시 / 군 / 구),일반용,"133,624","334,824,805","40,949,982,462",122.3
19,201503,강원도,전체(시 / 군 / 구),교육용,"1,047","30,352,494","3,125,500,921",103.0
20,201503,강원도,전체(시 / 군 / 구),산업용,"12,225","620,521,169","57,438,991,298",92.6
21,201503,강원도,전체(시 / 군 / 구),농사용,"103,185","42,448,050","2,090,347,248",49.2
22,201503,강원도,전체(시 / 군 / 구),가로등,"97,719","14,546,964","1,620,682,382",111.4
23,201503,강원도,전체(시 / 군 / 구),심 야,"95,064","236,417,958","15,723,438,539",66.5
24,201504,강원도,전체(시 / 군 / 구),주택용,"533,256","166,078,922","20,189,464,619",121.6
25,201504,강원도,전체(시 / 군 / 구),일반용,"133,747","319,318,141","36,381,685,273",113.9
26,201504,강원도,전체(시 / 군 / 구),교육용,"1,046","28,648,059","2,650,819,234",92.5
27,201504,강원도,전체(시 / 군 / 구),산업용,"12,261","615,945,262","56,900,923,393",92.4
28,201504,강원도,전체(시 / 군 / 구),농사용,"82,174","41,949,371","2,092,496,956",49.9
29,201504,강원도,전체(시 / 군 / 구),가로등,"98,061","14,436,162","1,667,876,750",115.5
30,201504,강원도,전체(시 / 군 / 구),심 야,"95,003","190,548,798","10,325,342,204",54.2
31,201505,강원도,전체(시 / 군 / 구),주택용,"533,976","152,902,778","17,320,404,478",113.3
32,201505,강원도,전체(시 / 군 / 구),일반용,"133,968","291,023,453","34,148,944,510",117.3
33,201505,강원도,전체(시 / 군 / 구),교육용,"1,042","20,138,743","2,181,877,202",108.3
34,201505,강원도,전체(시 / 군 / 구),산업용,"12,280","636,216,341","57,143,815,369",89.8
35,201505,강원도,전체(시 / 군 / 구),농사용,"83,016","38,801,160","1,937,175,624",49.9
36,201505,강원도,전체(시 / 군 / 구),가로등,"98,357","13,665,458","1,633,511,073",119.5
37,201505,강원도,전체(시 / 군 / 구),심 야,"94,891","113,067,945","6,133,223,372",54.2
38,201506,강원도,전체(시 / 군 / 구),주택용,"535,190","151,616,264","17,152,333,245",113.1
39,201506,강원도,전체(시 / 군 / 구),일반용,"134,119","296,194,067","40,181,557,403",135.7
40,201506,강원도,전체(시 / 군 / 구),교육용,"1,043","20,067,077","2,529,573,507",126.1
41,201506,강원도,전체(시 / 군 / 구),산업용,"12,322","633,287,884","71,920,180,203",113.6
42,201506,강원도,전체(시 / 군 / 구),농사용,"83,964","42,005,407","2,047,467,583",48.7
43,201506,강원도,전체(시 / 군 / 구),가로등,"98,733","13,458,884","1,638,264,851",121.7
44,201506,강원도,전체(시 / 군 / 구),심 야,"94,798","63,124,427","3,459,393,867",54.8
45,합계,합계,합계,합계,"5,753,800","8,417,290,147","875,808,266,865",104

In [9]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_7940\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)      사용량(kWh)
4   201501  강원도  일반용  133,674   429,343,867
11  201502  강원도  일반용  133,749   398,802,339
18  201503  강원도  일반용  133,624   334,824,805
25  201504  강원도  일반용  133,747   319,318,141
32  201505  강원도  일반용  133,968   291,023,453
39  201506  강원도  일반용  134,119   296,194,067

In [10]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [11]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [12]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  강원도  강릉시  일반용  17,881   46,603,869
197  201502  강원도  강릉시  일반용  17,931   44,952,005
341  201503  강원도  강릉시  일반용  17,932   38,657,091
485  201504  강원도  강릉시  일반용  17,981   38,505,549
629  201505  강원도  강릉시  일반용  18,031   34,541,451
..      ...  ...  ...  ...      ...          ...
333  201502  강원도  횡성군  일반용   4,655   13,853,543
477  201503  강원도  횡성군  일반용   4,648   11,727,206
621  201504  강원도  횡성군  일반용   4,639   10,535,148
765  201505  강원도  횡성군  일반용   4,631    9,313,393
909  201506  강원도  횡성군  일반용   4,654    9,125,420

[108 rows x 6 columns]

In [13]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'강원도'

In [14]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강릉시',
 '고성군',
 '동해시',
 '삼척시',
 '속초시',
 '양구군',
 '양양군',
 '영월군',
 '원주시',
 '인제군',
 '정선군',
 '철원군',
 '춘천시',
 '태백시',
 '평창군',
 '홍천군',
 '화천군',
 '횡성군']

In [15]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201501  강원도  강릉시   합계  122,378   182,407,990
199  201502  강원도  강릉시   합계  122,489   169,713,339
343  201503  강원도  강릉시   합계  122,997   166,113,694
487  201504  강원도  강릉시   합계  122,937   171,199,063
631  201505  강원도  강릉시   합계  123,068   157,665,794
..      ...  ...  ...  ...       ...           ...
335  201502  강원도  횡성군   합계   46,478    59,628,495
479  201503  강원도  횡성군   합계   48,483    52,167,249
623  201504  강원도  횡성군   합계   46,822    47,816,600
767  201505  강원도  횡성군   합계   46,978    39,110,623
911  201506  강원도  횡성군   합계   47,182    37,137,317

[108 rows x 6 columns]

In [16]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[182407990, 169713339, 166113694, 171199063, 157665794, 146884472]
[30022592, 28178140, 25243700, 25259478, 22051916, 19999690]
[257503954, 246995691, 282455442, 262993569, 270870698, 259215418]
[110454730, 98950277, 96940034, 103683196, 107075256, 112232567]
[46763124, 45037434, 38830684, 39041260, 34351238, 32691282]
[25282299, 23974132, 19959033, 18209957, 14432013, 12707743]
[28050439, 26399385, 22941050, 22108425, 19301846, 17636877]
[85417960, 75723813, 97659460, 94281513, 92359096, 89863571]
[241781065, 223027535, 202182665, 189976980, 164872937, 166461634]
[37457187, 34688213, 29296666, 27837005, 22753554, 20411795]
[64854831, 57867830, 56770653, 52316909, 46814712, 42068631]
[55281524, 51198980, 44231465, 39876703, 32647654, 30154638]
[169497790, 158961462, 136984862, 129491670, 112454574, 111598649]
[34152347, 31786314, 29120893, 28407199, 24843944, 23908996]
[74392050, 66084713, 53734292, 47653132, 39702246, 35458940]
[79159569, 73082294, 61741365, 56317583, 48090315, 46132428]
[29290842, 27538642, 22556447, 20454473, 16417462, 15189362]
[65258908, 59628495, 52167249, 47816600, 39110623, 37137317]
강원도 지역별 합계 :  [993984352, 150755516, 1580034772, 629336060, 236715022, 114565177, 136438022, 535305413, 1188302816, 172444420, 320693566, 253390964, 818989007, 172219693, 317025373, 364523554, 131447228, 301119192]
강원도 고객호수 평균:  [20480, 4487, 7733, 8369, 6286, 3479, 4632, 6239, 23415, 5315, 6025, 6725, 21944, 4588, 7823, 10754, 3682, 7844]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [17]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201501  강원도  강릉시   합계  122,378   182,407,990
1           201502  강원도  강릉시   합계  122,489   169,713,339
2           201503  강원도  강릉시   합계  122,997   166,113,694
3           201504  강원도  강릉시   합계  122,937   171,199,063
4           201505  강원도  강릉시   합계  123,068   157,665,794
..             ...  ...  ...  ...       ...           ...
121  201501-201506  강원도  태백시   합계      4588     172219693
122  201501-201506  강원도  평창군   합계      7823     317025373
123  201501-201506  강원도  홍천군   합계     10754     364523554
124  201501-201506  강원도  화천군   합계      3682     131447228
125  201501-201506  강원도  횡성군   합계      7844     301119192

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [18]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201501-201506  강원도  강릉시   합계   20480   993984352
109  201501-201506  강원도  고성군   합계    4487   150755516
110  201501-201506  강원도  동해시   합계    7733  1580034772
111  201501-201506  강원도  삼척시   합계    8369   629336060
112  201501-201506  강원도  속초시   합계    6286   236715022
113  201501-201506  강원도  양구군   합계    3479   114565177
114  201501-201506  강원도  양양군   합계    4632   136438022
115  201501-201506  강원도  영월군   합계    6239   535305413
116  201501-201506  강원도  원주시   합계   23415  1188302816
117  201501-201506  강원도  인제군   합계    5315   172444420
118  201501-201506  강원도  정선군   합계    6025   320693566
119  201501-201506  강원도  철원군   합계    6725   253390964
120  201501-201506  강원도  춘천시   합계   21944   818989007
121  201501-201506  강원도  태백시   합계    4588   172219693
122  201501-201506  강원도  평창군   합계    7823   317025373
123  201501-201506  강원도  홍천군   합계   10754   364523554
124  201501-201506  강원도  화천군   합계    3682   131447228
125  201501-201506  강원도  횡성군   합계    7844   301119192

In [19]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [20]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [21]:
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  강원도  강릉시  일반용  17,881   46,603,869
197  201502  강원도  강릉시  일반용  17,931   44,952,005
341  201503  강원도  강릉시  일반용  17,932   38,657,091
485  201504  강원도  강릉시  일반용  17,981   38,505,549
629  201505  강원도  강릉시  일반용  18,031   34,541,451
..      ...  ...  ...  ...      ...          ...
333  201502  강원도  횡성군  일반용   4,655   13,853,543
477  201503  강원도  횡성군  일반용   4,648   11,727,206
621  201504  강원도  횡성군  일반용   4,639   10,535,148
765  201505  강원도  횡성군  일반용   4,631    9,313,393
909  201506  강원도  횡성군  일반용   4,654    9,125,420

[108 rows x 6 columns]

In [22]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [23]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[46603869, 44952005, 38657091, 38505549, 34541451, 35103857]
[11274992, 10625094, 9413267, 9371658, 8729161, 8513284]
[20329746, 19581060, 16986956, 17105639, 15114997, 15356860]
[16411992, 15512374, 13672753, 13191813, 11511138, 11253627]
[22678104, 21624154, 18539738, 18727413, 17181969, 16919755]
[8526486, 8127261, 6612068, 6174267, 5308479, 5153314]
[10932337, 10342805, 9003066, 8791797, 8262425, 7918527]
[7932982, 7426422, 6195338, 6045246, 5365384, 5396182]
[73567006, 68349412, 56757977, 54115249, 49418158, 52396811]
[13778113, 12759587, 10669028, 10408034, 9020284, 9201740]
[22066909, 19525727, 16216463, 13996861, 13203120, 12840571]
[16766711, 15472222, 12911038, 12017311, 10117079, 10321492]
[65788077, 61563221, 52842932, 50581220, 47498288, 50672005]
[9452013, 9058532, 7619538, 7500362, 6826027, 6546641]
[30581223, 25759286, 19495895, 16896401, 15858756, 14845652]
[24821753, 22559415, 18090854, 16732272, 16512315, 17228614]
[12366502, 11710219, 9413597, 8621901, 7241029, 7399715]
[15465052, 13853543, 11727206, 10535148, 9313393, 9125420]
강원도 지역별 일반용 합계 :  [238363822, 57927456, 104475258, 81553697, 115671133, 39901875, 55250957, 38361554, 354604613, 65836786, 97849651, 77605853, 328945743, 47003113, 123437213, 115945223, 56752963, 70019762]
강원도 고객호수 평균:  [17960, 3657, 6787, 6017, 7602, 2376, 3865, 3965, 22787, 4270, 4853, 4659, 19705, 4085, 5860, 7671, 3043, 4645]

In [24]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [25]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [26]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [27]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7940\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201501  강원도  강릉시  일반용  17,881   46,603,869
1           201502  강원도  강릉시  일반용  17,931   44,952,005
2           201503  강원도  강릉시  일반용  17,932   38,657,091
3           201504  강원도  강릉시  일반용  17,981   38,505,549
4           201505  강원도  강릉시  일반용  18,031   34,541,451
..             ...  ...  ...  ...      ...          ...
121  201501-201506  강원도  태백시  일반용     4085     47003113
122  201501-201506  강원도  평창군  일반용     5860    123437213
123  201501-201506  강원도  홍천군  일반용     7671    115945223
124  201501-201506  강원도  화천군  일반용     3043     56752963
125  201501-201506  강원도  횡성군  일반용     4645     70019762

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [28]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

                년월   시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201501-201506  강원도  강릉시  일반용   17960  238363822
109  201501-201506  강원도  고성군  일반용    3657   57927456
110  201501-201506  강원도  동해시  일반용    6787  104475258
111  201501-201506  강원도  삼척시  일반용    6017   81553697
112  201501-201506  강원도  속초시  일반용    7602  115671133
113  201501-201506  강원도  양구군  일반용    2376   39901875
114  201501-201506  강원도  양양군  일반용    3865   55250957
115  201501-201506  강원도  영월군  일반용    3965   38361554
116  201501-201506  강원도  원주시  일반용   22787  354604613
117  201501-201506  강원도  인제군  일반용    4270   65836786
118  201501-201506  강원도  정선군  일반용    4853   97849651
119  201501-201506  강원도  철원군  일반용    4659   77605853
120  201501-201506  강원도  춘천시  일반용   19705  328945743
121  201501-201506  강원도  태백시  일반용    4085   47003113
122  201501-201506  강원도  평창군  일반용    5860  123437213
123  201501-201506  강원도  홍천군  일반용    7671  115945223
124  201501-201506  강원도  화천군  일반용    3043   56752963
125  201501-201506  강원도  횡성군  일반용    4645   70019762

In [29]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201501-201506  강원도  강릉시  일반용   17960   238363822
108  201501-201506  강원도  강릉시   합계   20480   993984352
109  201501-201506  강원도  고성군  일반용    3657    57927456
109  201501-201506  강원도  고성군   합계    4487   150755516
110  201501-201506  강원도  동해시  일반용    6787   104475258
110  201501-201506  강원도  동해시   합계    7733  1580034772
111  201501-201506  강원도  삼척시   합계    8369   629336060
111  201501-201506  강원도  삼척시  일반용    6017    81553697
112  201501-201506  강원도  속초시   합계    6286   236715022
112  201501-201506  강원도  속초시  일반용    7602   115671133
113  201501-201506  강원도  양구군  일반용    2376    39901875
113  201501-201506  강원도  양구군   합계    3479   114565177
114  201501-201506  강원도  양양군   합계    4632   136438022
114  201501-201506  강원도  양양군  일반용    3865    55250957
115  201501-201506  강원도  영월군  일반용    3965    38361554
115  201501-201506  강원도  영월군   합계    6239   535305413
116  201501-201506  강원도  원주시  일반용   22787   354604613
116  201501-201506  강원도  원주시   합계   23415  1188302816
117  201501-201506  강원도  인제군  일반용    4270    65836786
117  201501-201506  강원도  인제군   합계    5315   172444420
118  201501-201506  강원도  정선군   합계    6025   320693566
118  201501-201506  강원도  정선군  일반용    4853    97849651
119  201501-201506  강원도  철원군   합계    6725   253390964
119  201501-201506  강원도  철원군  일반용    4659    77605853
120  201501-201506  강원도  춘천시  일반용   19705   328945743
120  201501-201506  강원도  춘천시   합계   21944   818989007
121  201501-201506  강원도  태백시   합계    4588   172219693
121  201501-201506  강원도  태백시  일반용    4085    47003113
122  201501-201506  강원도  평창군   합계    7823   317025373
122  201501-201506  강원도  평창군  일반용    5860   123437213
123  201501-201506  강원도  홍천군   합계   10754   364523554
123  201501-201506  강원도  홍천군  일반용    7671   115945223
124  201501-201506  강원도  화천군   합계    3682   131447228
124  201501-201506  강원도  화천군  일반용    3043    56752963
125  201501-201506  강원도  횡성군  일반용    4645    70019762
125  201501-201506  강원도  횡성군   합계    7844   301119192

In [30]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[238363822,
 57927456,
 104475258,
 81553697,
 115671133,
 39901875,
 55250957,
 38361554,
 354604613,
 65836786,
 97849651,
 77605853,
 328945743,
 47003113,
 123437213,
 115945223,
 56752963,
 70019762]

In [31]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[993984352,
 150755516,
 1580034772,
 629336060,
 236715022,
 114565177,
 136438022,
 535305413,
 1188302816,
 172444420,
 320693566,
 253390964,
 818989007,
 172219693,
 317025373,
 364523554,
 131447228,
 301119192]

In [32]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[23.98, 38.42, 6.61, 12.96, 48.87, 34.83, 40.5, 7.17, 29.84, 38.18, 30.51, 30.63, 40.16, 27.29, 38.94, 31.81, 43.18, 23.25]

In [33]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    24
1    38
2     7
3    13
4    49
5    35
6    40
7     7
8    30
9    38
10   31
11   31
12   40
13   27
14   39
15   32
16   43
17   23
dtype: float64

In [34]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강릉시  일반용  24
1   고성군  일반용  38
2   동해시  일반용   7
3   삼척시  일반용  13
4   속초시  일반용  49
5   양구군  일반용  35
6   양양군  일반용  40
7   영월군  일반용   7
8   원주시  일반용  30
9   인제군  일반용  38
10  정선군  일반용  31
11  철원군  일반용  31
12  춘천시  일반용  40
13  태백시  일반용  27
14  평창군  일반용  39
15  홍천군  일반용  32
16  화천군  일반용  43
17  횡성군  일반용  23

In [35]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201501-201506  강원도  강릉시  일반용   17960   238363822  24
1   201501-201506  강원도  강릉시   합계   20480   993984352 NaN
2   201501-201506  강원도  고성군  일반용    3657    57927456  38
3   201501-201506  강원도  고성군   합계    4487   150755516 NaN
4   201501-201506  강원도  동해시  일반용    6787   104475258   7
5   201501-201506  강원도  동해시   합계    7733  1580034772 NaN
7   201501-201506  강원도  삼척시  일반용    6017    81553697  13
6   201501-201506  강원도  삼척시   합계    8369   629336060 NaN
9   201501-201506  강원도  속초시  일반용    7602   115671133  49
8   201501-201506  강원도  속초시   합계    6286   236715022 NaN
10  201501-201506  강원도  양구군  일반용    2376    39901875  35
11  201501-201506  강원도  양구군   합계    3479   114565177 NaN
13  201501-201506  강원도  양양군  일반용    3865    55250957  40
12  201501-201506  강원도  양양군   합계    4632   136438022 NaN
14  201501-201506  강원도  영월군  일반용    3965    38361554   7
15  201501-201506  강원도  영월군   합계    6239   535305413 NaN
16  201501-201506  강원도  원주시  일반용   22787   354604613  30
17  201501-201506  강원도  원주시   합계   23415  1188302816 NaN
18  201501-201506  강원도  인제군  일반용    4270    65836786  38
19  201501-201506  강원도  인제군   합계    5315   172444420 NaN
21  201501-201506  강원도  정선군  일반용    4853    97849651  31
20  201501-201506  강원도  정선군   합계    6025   320693566 NaN
23  201501-201506  강원도  철원군  일반용    4659    77605853  31
22  201501-201506  강원도  철원군   합계    6725   253390964 NaN
24  201501-201506  강원도  춘천시  일반용   19705   328945743  40
25  201501-201506  강원도  춘천시   합계   21944   818989007 NaN
27  201501-201506  강원도  태백시  일반용    4085    47003113  27
26  201501-201506  강원도  태백시   합계    4588   172219693 NaN
29  201501-201506  강원도  평창군  일반용    5860   123437213  39
28  201501-201506  강원도  평창군   합계    7823   317025373 NaN
31  201501-201506  강원도  홍천군  일반용    7671   115945223  32
30  201501-201506  강원도  홍천군   합계   10754   364523554 NaN
33  201501-201506  강원도  화천군  일반용    3043    56752963  43
32  201501-201506  강원도  화천군   합계    3682   131447228 NaN
34  201501-201506  강원도  횡성군  일반용    4645    70019762  23
35  201501-201506  강원도  횡성군   합계    7844   301119192 NaN

In [36]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [37]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [38]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [39]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [40]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [41]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [42]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [43]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [44]:
# SEOUL

In [45]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)