In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상북도_계약종별 전력사용량 월별_14상반기.csv' , encoding='utf-8')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상북도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 01 월 ~ 2014년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경상북도,전체(시 / 군 / 구),주택용,"1,038,096","293,137,437","37,790,130,725",128.9
4,201401,경상북도,전체(시 / 군 / 구),일반용,"199,974","480,934,930","63,211,847,653",131.4
...,...,...,...,...,...,...,...,...
1147,201406,경상북도,포항시,산업용,"2,571","1,030,455,612","107,209,980,877",104
1148,201406,경상북도,포항시,심 야,"5,059","3,546,625","194,884,561",54.9
1149,201406,경상북도,포항시,일반용,"36,963","70,008,248","9,391,167,745",134.1
1150,201406,경상북도,포항시,주택용,"172,920","51,479,239","5,921,832,451",115
1151,201406,경상북도,포항시,합계,"243,044","1,179,261,636","124,790,362,650",105.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경상북도,전체(시 / 군 / 구),주택용,"1,038,096","293,137,437","37,790,130,725",128.9
4,201401,경상북도,전체(시 / 군 / 구),일반용,"199,974","480,934,930","63,211,847,653",131.4
5,201401,경상북도,전체(시 / 군 / 구),교육용,"1,432","52,762,376","5,823,944,063",110.4
6,201401,경상북도,전체(시 / 군 / 구),산업용,"28,940","2,944,671,927","326,859,887,310",111.0
...,...,...,...,...,...,...,...,...
1147,201406,경상북도,포항시,산업용,"2,571","1,030,455,612","107,209,980,877",104
1148,201406,경상북도,포항시,심 야,"5,059","3,546,625","194,884,561",54.9
1149,201406,경상북도,포항시,일반용,"36,963","70,008,248","9,391,167,745",134.1
1150,201406,경상북도,포항시,주택용,"172,920","51,479,239","5,921,832,451",115
1151,201406,경상북도,포항시,합계,"243,044","1,179,261,636","124,790,362,650",105.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경상북도,전체(시 / 군 / 구),주택용,"1,038,096","293,137,437","37,790,130,725",128.9
4,201401,경상북도,전체(시 / 군 / 구),일반용,"199,974","480,934,930","63,211,847,653",131.4
5,201401,경상북도,전체(시 / 군 / 구),교육용,"1,432","52,762,376","5,823,944,063",110.4
6,201401,경상북도,전체(시 / 군 / 구),산업용,"28,940","2,944,671,927","326,859,887,310",111.0
7,201401,경상북도,전체(시 / 군 / 구),농사용,"275,379","144,581,385","6,958,823,024",48.1
...,...,...,...,...,...,...,...,...
1147,201406,경상북도,포항시,산업용,"2,571","1,030,455,612","107,209,980,877",104
1148,201406,경상북도,포항시,심 야,"5,059","3,546,625","194,884,561",54.9
1149,201406,경상북도,포항시,일반용,"36,963","70,008,248","9,391,167,745",134.1
1150,201406,경상북도,포항시,주택용,"172,920","51,479,239","5,921,832,451",115
1151,201406,경상북도,포항시,합계,"243,044","1,179,261,636","124,790,362,650",105.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,경상북도,전체(시 / 군 / 구),주택용,"1,038,096","293,137,437","37,790,130,725",128.9
4,201401,경상북도,전체(시 / 군 / 구),일반용,"199,974","480,934,930","63,211,847,653",131.4
5,201401,경상북도,전체(시 / 군 / 구),교육용,"1,432","52,762,376","5,823,944,063",110.4
6,201401,경상북도,전체(시 / 군 / 구),산업용,"28,940","2,944,671,927","326,859,887,310",111.0
7,201401,경상북도,전체(시 / 군 / 구),농사용,"275,379","144,581,385","6,958,823,024",48.1
8,201401,경상북도,전체(시 / 군 / 구),가로등,"152,429","24,609,463","2,535,001,572",103.0
9,201401,경상북도,전체(시 / 군 / 구),심 야,"83,662","223,838,785","16,838,938,023",75.2
10,201402,경상북도,전체(시 / 군 / 구),주택용,"1,040,087","295,651,806","38,282,016,137",129.5
11,201402,경상북도,전체(시 / 군 / 구),일반용,"200,341","462,078,626","61,965,918,719",134.1
12,201402,경상북도,전체(시 / 군 / 구),교육용,"1,442","50,968,601","5,746,100,371",112.7
13,201402,경상북도,전체(시 / 군 / 구),산업용,"29,041","2,644,586,051","304,390,911,744",115.1
14,201402,경상북도,전체(시 / 군 / 구),농사용,"274,783","142,452,214","6,878,877,459",48.3
15,201402,경상북도,전체(시 / 군 / 구),가로등,"152,830","22,634,671","2,514,011,054",111.1
16,201402,경상북도,전체(시 / 군 / 구),심 야,"83,594","223,133,842","16,783,949,719",75.2
17,201403,경상북도,전체(시 / 군 / 구),주택용,"1,041,848","258,398,795","29,504,534,637",114.2
18,201403,경상북도,전체(시 / 군 / 구),일반용,"200,426","403,230,117","50,552,268,913",125.4
19,201403,경상북도,전체(시 / 군 / 구),교육용,"1,451","50,824,072","4,882,857,460",96.1
20,201403,경상북도,전체(시 / 군 / 구),산업용,"29,064","2,984,214,547","274,636,955,822",92.0
21,201403,경상북도,전체(시 / 군 / 구),농사용,"342,234","120,204,760","5,935,983,384",49.4
22,201403,경상북도,전체(시 / 군 / 구),가로등,"153,081","21,328,070","2,394,645,437",112.3
23,201403,경상북도,전체(시 / 군 / 구),심 야,"83,495","177,212,096","11,730,085,402",66.2
24,201404,경상북도,전체(시 / 군 / 구),주택용,"1,043,997","269,411,976","31,476,218,840",116.8
25,201404,경상북도,전체(시 / 군 / 구),일반용,"200,818","377,009,493","43,703,176,868",115.9
26,201404,경상북도,전체(시 / 군 / 구),교육용,"1,449","45,509,641","4,263,560,357",93.7
27,201404,경상북도,전체(시 / 군 / 구),산업용,"29,153","2,923,207,754","267,877,975,400",91.6
28,201404,경상북도,전체(시 / 군 / 구),농사용,"277,457","108,482,417","5,456,453,267",50.3
29,201404,경상북도,전체(시 / 군 / 구),가로등,"153,486","20,788,555","2,443,805,188",117.6
30,201404,경상북도,전체(시 / 군 / 구),심 야,"83,405","136,140,647","7,373,155,056",54.2
31,201405,경상북도,전체(시 / 군 / 구),주택용,"1,045,984","253,656,457","28,318,352,665",111.6
32,201405,경상북도,전체(시 / 군 / 구),일반용,"201,066","346,807,043","41,462,613,071",119.6
33,201405,경상북도,전체(시 / 군 / 구),교육용,"1,452","38,468,856","3,806,398,136",98.9
34,201405,경상북도,전체(시 / 군 / 구),산업용,"29,198","2,876,731,111","260,769,219,326",90.6
35,201405,경상북도,전체(시 / 군 / 구),농사용,"279,973","105,600,889","5,297,756,532",50.2
36,201405,경상북도,전체(시 / 군 / 구),가로등,"153,520","19,181,532","2,366,708,478",123.4
37,201405,경상북도,전체(시 / 군 / 구),심 야,"83,292","86,675,361","4,686,590,637",54.1
38,201406,경상북도,전체(시 / 군 / 구),주택용,"1,048,222","255,373,250","28,576,029,138",111.9
39,201406,경상북도,전체(시 / 군 / 구),일반용,"201,410","360,888,324","48,584,736,242",134.6
40,201406,경상북도,전체(시 / 군 / 구),교육용,"1,456","38,671,914","4,616,703,858",119.4
41,201406,경상북도,전체(시 / 군 / 구),산업용,"29,274","2,878,374,207","314,034,123,853",109.1
42,201406,경상북도,전체(시 / 군 / 구),농사용,"282,711","130,590,149","6,078,379,304",46.5
43,201406,경상북도,전체(시 / 군 / 구),가로등,"154,750","18,165,274","2,344,363,684",129.1
44,201406,경상북도,전체(시 / 군 / 구),심 야,"83,145","49,318,930","2,713,162,356",55.0
45,합계,NaN,NaN,NaN,"10,798,847","23,360,508,351","2,392,467,170,884",102.4

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_1504\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201401  경상북도  일반용  199,974   480,934,930
11  201402  경상북도  일반용  200,341   462,078,626
18  201403  경상북도  일반용  200,426   403,230,117
25  201404  경상북도  일반용  200,818   377,009,493
32  201405  경상북도  일반용  201,066   346,807,043
39  201406  경상북도  일반용  201,410   360,888,324

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53    201401  경상북도  경산시  일반용  15,354   38,376,651
237   201402  경상북도  경산시  일반용  15,415   37,133,389
421   201403  경상북도  경산시  일반용  15,388   32,378,361
605   201404  경상북도  경산시  일반용  15,464   31,035,064
789   201405  경상북도  경산시  일반용  15,497   28,724,233
...      ...   ...  ...  ...      ...          ...
413   201402  경상북도  포항시  일반용  36,756   85,927,118
597   201403  경상북도  포항시  일반용  36,824   75,890,533
781   201404  경상북도  포항시  일반용  36,824   71,584,696
965   201405  경상북도  포항시  일반용  36,851   65,308,677
1149  201406  경상북도  포항시  일반용  36,963   70,008,248

[138 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상북도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['경산시',
 '경주시',
 '고령군',
 '구미시',
 '군위군',
 '김천시',
 '문경시',
 '봉화군',
 '상주시',
 '성주군',
 '안동시',
 '영덕군',
 '영양군',
 '영주시',
 '영천시',
 '예천군',
 '울릉군',
 '울진군',
 '의성군',
 '청도군',
 '청송군',
 '칠곡군',
 '포항시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월    시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201401  경상북도  경산시   합계  139,186     249,180,648
239   201402  경상북도  경산시   합계  139,416     235,316,802
423   201403  경상북도  경산시   합계  139,558     227,999,734
607   201404  경상북도  경산시   합계  139,831     224,975,512
791   201405  경상북도  경산시   합계  140,074     207,228,397
...      ...   ...  ...  ...       ...             ...
415   201402  경상북도  포항시   합계  241,215   1,075,405,821
599   201403  경상북도  포항시   합계  245,414   1,269,510,158
783   201404  경상북도  포항시   합계  242,083   1,205,683,463
967   201405  경상북도  포항시   합계  242,425   1,165,085,852
1151  201406  경상북도  포항시   합계  243,044   1,179,261,636

[138 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[249180648, 235316802, 227999734, 224975512, 207228397, 211514837]
[366404359, 343221669, 341865143, 331713405, 301236223, 293001360]
[103723082, 100063765, 103726936, 103610312, 96834684, 94697161]
[883923064, 814852045, 864192294, 844039133, 852532445, 855546791]
[30300470, 29590323, 27418346, 25882777, 23260459, 22661535]
[175872724, 167405409, 163317091, 159318349, 151036808, 150810097]
[56997749, 55905756, 50429313, 47808192, 42746661, 41249001]
[164243623, 149822905, 157016085, 158463795, 159809158, 154406297]
[67438831, 65864558, 56269708, 51843321, 47578045, 47035351]
[82399201, 78942666, 75132849, 73497659, 67288985, 68069947]
[103918027, 99131564, 87362158, 80766513, 71689491, 72395255]
[29179830, 28320955, 24728735, 23526674, 20769940, 20210769]
[11685155, 11817705, 9908235, 8927287, 7556268, 6456103]
[115536348, 108331750, 109973423, 104052876, 101275700, 97899813]
[129175227, 123785448, 117787024, 117574871, 105225266, 105836859]
[29892988, 29371185, 24453654, 22427692, 20068548, 20562767]
[4837471, 4462064, 4595322, 4909393, 4427830, 4196448]
[41804465, 43872843, 39215300, 41237221, 48248726, 51103434]
[38913379, 38510439, 33759031, 32756521, 29851707, 32707578]
[44426059, 42305147, 37462809, 35581550, 31810247, 31392715]
[18695310, 18168310, 15838874, 14845893, 12456093, 11975359]
[185294228, 177036682, 173450235, 167108074, 159103716, 158390935]
[1230694065, 1075405821, 1269510158, 1205683463, 1165085852, 1179261636]
경상북도 지역별 합계 :  [1356215930, 1977442159, 602655940, 5115085772, 159113910, 967760478, 295136672, 943761863, 336029814, 445331307, 515263008, 146736903, 56350753, 637069910, 699384695, 146776834, 27428528, 265481989, 206498655, 222978527, 91979839, 1020383870, 7125640995]
경상북도 고객호수 평균:  [23289, 30297, 4798, 30401, 4485, 15928, 9744, 6557, 15574, 7805, 18893, 6489, 3833, 12747, 13459, 8763, 1237, 7921, 10931, 8574, 5807, 11999, 40424]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201401  경상북도  경산시   합계  139,186   249,180,648
1           201402  경상북도  경산시   합계  139,416   235,316,802
2           201403  경상북도  경산시   합계  139,558   227,999,734
3           201404  경상북도  경산시   합계  139,831   224,975,512
4           201405  경상북도  경산시   합계  140,074   207,228,397
..             ...   ...  ...  ...       ...           ...
156  201401-201406  경상북도  의성군   합계     10931     206498655
157  201401-201406  경상북도  청도군   합계      8574     222978527
158  201401-201406  경상북도  청송군   합계      5807      91979839
159  201401-201406  경상북도  칠곡군   합계     11999    1020383870
160  201401-201406  경상북도  포항시   합계     40424    7125640995

[161 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201401-201406']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
138  201401-201406  경상북도  경산시   합계   23289  1356215930
139  201401-201406  경상북도  경주시   합계   30297  1977442159
140  201401-201406  경상북도  고령군   합계    4798   602655940
141  201401-201406  경상북도  구미시   합계   30401  5115085772
142  201401-201406  경상북도  군위군   합계    4485   159113910
143  201401-201406  경상북도  김천시   합계   15928   967760478
144  201401-201406  경상북도  문경시   합계    9744   295136672
145  201401-201406  경상북도  봉화군   합계    6557   943761863
146  201401-201406  경상북도  상주시   합계   15574   336029814
147  201401-201406  경상북도  성주군   합계    7805   445331307
148  201401-201406  경상북도  안동시   합계   18893   515263008
149  201401-201406  경상북도  영덕군   합계    6489   146736903
150  201401-201406  경상북도  영양군   합계    3833    56350753
151  201401-201406  경상북도  영주시   합계   12747   637069910
152  201401-201406  경상북도  영천시   합계   13459   699384695
153  201401-201406  경상북도  예천군   합계    8763   146776834
154  201401-201406  경상북도  울릉군   합계    1237    27428528
155  201401-201406  경상북도  울진군   합계    7921   265481989
156  201401-201406  경상북도  의성군   합계   10931   206498655
157  201401-201406  경상북도  청도군   합계    8574   222978527
158  201401-201406  경상북도  청송군   합계    5807    91979839
159  201401-201406  경상북도  칠곡군   합계   11999  1020383870
160  201401-201406  경상북도  포항시   합계   40424  7125640995

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53    201401  경상북도  경산시  일반용  15,354   38,376,651
237   201402  경상북도  경산시  일반용  15,415   37,133,389
421   201403  경상북도  경산시  일반용  15,388   32,378,361
605   201404  경상북도  경산시  일반용  15,464   31,035,064
789   201405  경상북도  경산시  일반용  15,497   28,724,233
...      ...   ...  ...  ...      ...          ...
413   201402  경상북도  포항시  일반용  36,756   85,927,118
597   201403  경상북도  포항시  일반용  36,824   75,890,533
781   201404  경상북도  포항시  일반용  36,824   71,584,696
965   201405  경상북도  포항시  일반용  36,851   65,308,677
1149  201406  경상북도  포항시  일반용  36,963   70,008,248

[138 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[38376651, 37133389, 32378361, 31035064, 28724233, 30935628]
[62824152, 58539661, 51879423, 50340232, 45661685, 47386357]
[5230702, 5084202, 4338267, 4045777, 3613540, 3782665]
[66544173, 63969826, 55497763, 51752945, 48005434, 53078716]
[4751525, 4659298, 4101745, 3727759, 3218033, 3250164]
[20330767, 19712513, 17061347, 15657556, 14200518, 15366999]
[14404420, 13805129, 11841966, 10827971, 9688286, 9867971]
[4588922, 4444048, 3844836, 3717217, 3260528, 2897533]
[15210400, 14695099, 12823008, 11757478, 10776166, 11289141]
[7156244, 7021149, 5978045, 5541407, 4961519, 5089933]
[33516509, 32003233, 27690890, 25486130, 22728713, 23599911]
[11151045, 10640709, 9378301, 8836297, 7769554, 7590091]
[2632123, 2585402, 2219091, 2117645, 1895180, 1806570]
[17618398, 17190500, 14571766, 13713083, 12250662, 12807160]
[16860539, 16359653, 14158514, 13442959, 12138661, 12479034]
[6753947, 6644447, 5773592, 5216472, 4669515, 4756849]
[2941450, 2739371, 2816158, 3030249, 2602676, 2412146]
[14864424, 14241096, 12493427, 11224023, 10119683, 10779786]
[7523740, 7249036, 6181542, 5767275, 4980093, 5067687]
[7391258, 7197965, 6295373, 6049747, 5505204, 5523864]
[5583999, 5341843, 4543388, 4184649, 3541208, 3551947]
[25180407, 24893939, 21472781, 17952862, 21187275, 17559924]
[89499135, 85927118, 75890533, 71584696, 65308677, 70008248]
경상북도 지역별 일반용 합계 :  [198583326, 316631510, 26095153, 338848857, 23708524, 102329700, 70435743, 22753084, 76551292, 35748297, 165025386, 55365997, 13256011, 88151569, 85439360, 33814822, 16542050, 73722439, 36769373, 37963411, 26747034, 128247188, 458218407]
경상북도 고객호수 평균:  [15440, 23054, 2824, 25731, 1978, 9248, 6248, 2961, 7481, 3734, 12448, 4925, 1640, 8862, 7546, 3313, 1526, 5010, 4192, 3618, 2728, 9329, 36829]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1504\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201401  경상북도  경산시  일반용  15,354   38,376,651
1           201402  경상북도  경산시  일반용  15,415   37,133,389
2           201403  경상북도  경산시  일반용  15,388   32,378,361
3           201404  경상북도  경산시  일반용  15,464   31,035,064
4           201405  경상북도  경산시  일반용  15,497   28,724,233
..             ...   ...  ...  ...      ...          ...
156  201401-201406  경상북도  의성군  일반용     4192     36769373
157  201401-201406  경상북도  청도군  일반용     3618     37963411
158  201401-201406  경상북도  청송군  일반용     2728     26747034
159  201401-201406  경상북도  칠곡군  일반용     9329    128247188
160  201401-201406  경상북도  포항시  일반용    36829    458218407

[161 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201401-201406']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
138  201401-201406  경상북도  경산시  일반용   15440  198583326
139  201401-201406  경상북도  경주시  일반용   23054  316631510
140  201401-201406  경상북도  고령군  일반용    2824   26095153
141  201401-201406  경상북도  구미시  일반용   25731  338848857
142  201401-201406  경상북도  군위군  일반용    1978   23708524
143  201401-201406  경상북도  김천시  일반용    9248  102329700
144  201401-201406  경상북도  문경시  일반용    6248   70435743
145  201401-201406  경상북도  봉화군  일반용    2961   22753084
146  201401-201406  경상북도  상주시  일반용    7481   76551292
147  201401-201406  경상북도  성주군  일반용    3734   35748297
148  201401-201406  경상북도  안동시  일반용   12448  165025386
149  201401-201406  경상북도  영덕군  일반용    4925   55365997
150  201401-201406  경상북도  영양군  일반용    1640   13256011
151  201401-201406  경상북도  영주시  일반용    8862   88151569
152  201401-201406  경상북도  영천시  일반용    7546   85439360
153  201401-201406  경상북도  예천군  일반용    3313   33814822
154  201401-201406  경상북도  울릉군  일반용    1526   16542050
155  201401-201406  경상북도  울진군  일반용    5010   73722439
156  201401-201406  경상북도  의성군  일반용    4192   36769373
157  201401-201406  경상북도  청도군  일반용    3618   37963411
158  201401-201406  경상북도  청송군  일반용    2728   26747034
159  201401-201406  경상북도  칠곡군  일반용    9329  128247188
160  201401-201406  경상북도  포항시  일반용   36829  458218407

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
138  201401-201406  경상북도  경산시  일반용   15440   198583326
138  201401-201406  경상북도  경산시   합계   23289  1356215930
139  201401-201406  경상북도  경주시  일반용   23054   316631510
139  201401-201406  경상북도  경주시   합계   30297  1977442159
140  201401-201406  경상북도  고령군  일반용    2824    26095153
140  201401-201406  경상북도  고령군   합계    4798   602655940
141  201401-201406  경상북도  구미시  일반용   25731   338848857
141  201401-201406  경상북도  구미시   합계   30401  5115085772
142  201401-201406  경상북도  군위군  일반용    1978    23708524
142  201401-201406  경상북도  군위군   합계    4485   159113910
143  201401-201406  경상북도  김천시  일반용    9248   102329700
143  201401-201406  경상북도  김천시   합계   15928   967760478
144  201401-201406  경상북도  문경시  일반용    6248    70435743
144  201401-201406  경상북도  문경시   합계    9744   295136672
145  201401-201406  경상북도  봉화군  일반용    2961    22753084
145  201401-201406  경상북도  봉화군   합계    6557   943761863
146  201401-201406  경상북도  상주시   합계   15574   336029814
146  201401-201406  경상북도  상주시  일반용    7481    76551292
147  201401-201406  경상북도  성주군   합계    7805   445331307
147  201401-201406  경상북도  성주군  일반용    3734    35748297
148  201401-201406  경상북도  안동시   합계   18893   515263008
148  201401-201406  경상북도  안동시  일반용   12448   165025386
149  201401-201406  경상북도  영덕군   합계    6489   146736903
149  201401-201406  경상북도  영덕군  일반용    4925    55365997
150  201401-201406  경상북도  영양군   합계    3833    56350753
150  201401-201406  경상북도  영양군  일반용    1640    13256011
151  201401-201406  경상북도  영주시   합계   12747   637069910
151  201401-201406  경상북도  영주시  일반용    8862    88151569
152  201401-201406  경상북도  영천시  일반용    7546    85439360
152  201401-201406  경상북도  영천시   합계   13459   699384695
153  201401-201406  경상북도  예천군   합계    8763   146776834
153  201401-201406  경상북도  예천군  일반용    3313    33814822
154  201401-201406  경상북도  울릉군   합계    1237    27428528
154  201401-201406  경상북도  울릉군  일반용    1526    16542050
155  201401-201406  경상북도  울진군  일반용    5010    73722439
155  201401-201406  경상북도  울진군   합계    7921   265481989
156  201401-201406  경상북도  의성군   합계   10931   206498655
156  201401-201406  경상북도  의성군  일반용    4192    36769373
157  201401-201406  경상북도  청도군   합계    8574   222978527
157  201401-201406  경상북도  청도군  일반용    3618    37963411
158  201401-201406  경상북도  청송군   합계    5807    91979839
158  201401-201406  경상북도  청송군  일반용    2728    26747034
159  201401-201406  경상북도  칠곡군   합계   11999  1020383870
159  201401-201406  경상북도  칠곡군  일반용    9329   128247188
160  201401-201406  경상북도  포항시  일반용   36829   458218407
160  201401-201406  경상북도  포항시   합계   40424  7125640995

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[198583326,
 316631510,
 26095153,
 338848857,
 23708524,
 102329700,
 70435743,
 22753084,
 76551292,
 35748297,
 165025386,
 55365997,
 13256011,
 88151569,
 85439360,
 33814822,
 16542050,
 73722439,
 36769373,
 37963411,
 26747034,
 128247188,
 458218407]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1356215930,
 1977442159,
 602655940,
 5115085772,
 159113910,
 967760478,
 295136672,
 943761863,
 336029814,
 445331307,
 515263008,
 146736903,
 56350753,
 637069910,
 699384695,
 146776834,
 27428528,
 265481989,
 206498655,
 222978527,
 91979839,
 1020383870,
 7125640995]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[14.64, 16.01, 4.33, 6.62, 14.9, 10.57, 23.87, 2.41, 22.78, 8.03, 32.03, 37.73, 23.52, 13.84, 12.22, 23.04, 60.31, 27.77, 17.81, 17.03, 29.08, 12.57, 6.43]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    15
1    16
2     4
3     7
4    15
5    11
6    24
7     2
8    23
9     8
10   32
11   38
12   24
13   14
14   12
15   23
16   60
17   28
18   18
19   17
20   29
21   13
22    6
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   경산시  일반용  15
1   경주시  일반용  16
2   고령군  일반용   4
3   구미시  일반용   7
4   군위군  일반용  15
5   김천시  일반용  11
6   문경시  일반용  24
7   봉화군  일반용   2
8   상주시  일반용  23
9   성주군  일반용   8
10  안동시  일반용  32
11  영덕군  일반용  38
12  영양군  일반용  24
13  영주시  일반용  14
14  영천시  일반용  12
15  예천군  일반용  23
16  울릉군  일반용  60
17  울진군  일반용  28
18  의성군  일반용  18
19  청도군  일반용  17
20  청송군  일반용  29
21  칠곡군  일반용  13
22  포항시  일반용   6

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201401-201406  경상북도  경산시  일반용   15440   198583326  15
1   201401-201406  경상북도  경산시   합계   23289  1356215930 NaN
2   201401-201406  경상북도  경주시  일반용   23054   316631510  16
3   201401-201406  경상북도  경주시   합계   30297  1977442159 NaN
4   201401-201406  경상북도  고령군  일반용    2824    26095153   4
5   201401-201406  경상북도  고령군   합계    4798   602655940 NaN
6   201401-201406  경상북도  구미시  일반용   25731   338848857   7
7   201401-201406  경상북도  구미시   합계   30401  5115085772 NaN
8   201401-201406  경상북도  군위군  일반용    1978    23708524  15
9   201401-201406  경상북도  군위군   합계    4485   159113910 NaN
10  201401-201406  경상북도  김천시  일반용    9248   102329700  11
11  201401-201406  경상북도  김천시   합계   15928   967760478 NaN
12  201401-201406  경상북도  문경시  일반용    6248    70435743  24
13  201401-201406  경상북도  문경시   합계    9744   295136672 NaN
14  201401-201406  경상북도  봉화군  일반용    2961    22753084   2
15  201401-201406  경상북도  봉화군   합계    6557   943761863 NaN
17  201401-201406  경상북도  상주시  일반용    7481    76551292  23
16  201401-201406  경상북도  상주시   합계   15574   336029814 NaN
19  201401-201406  경상북도  성주군  일반용    3734    35748297   8
18  201401-201406  경상북도  성주군   합계    7805   445331307 NaN
21  201401-201406  경상북도  안동시  일반용   12448   165025386  32
20  201401-201406  경상북도  안동시   합계   18893   515263008 NaN
23  201401-201406  경상북도  영덕군  일반용    4925    55365997  38
22  201401-201406  경상북도  영덕군   합계    6489   146736903 NaN
25  201401-201406  경상북도  영양군  일반용    1640    13256011  24
24  201401-201406  경상북도  영양군   합계    3833    56350753 NaN
27  201401-201406  경상북도  영주시  일반용    8862    88151569  14
26  201401-201406  경상북도  영주시   합계   12747   637069910 NaN
28  201401-201406  경상북도  영천시  일반용    7546    85439360  12
29  201401-201406  경상북도  영천시   합계   13459   699384695 NaN
31  201401-201406  경상북도  예천군  일반용    3313    33814822  23
30  201401-201406  경상북도  예천군   합계    8763   146776834 NaN
33  201401-201406  경상북도  울릉군  일반용    1526    16542050  60
32  201401-201406  경상북도  울릉군   합계    1237    27428528 NaN
34  201401-201406  경상북도  울진군  일반용    5010    73722439  28
35  201401-201406  경상북도  울진군   합계    7921   265481989 NaN
37  201401-201406  경상북도  의성군  일반용    4192    36769373  18
36  201401-201406  경상북도  의성군   합계   10931   206498655 NaN
39  201401-201406  경상북도  청도군  일반용    3618    37963411  17
38  201401-201406  경상북도  청도군   합계    8574   222978527 NaN
41  201401-201406  경상북도  청송군  일반용    2728    26747034  29
40  201401-201406  경상북도  청송군   합계    5807    91979839 NaN
43  201401-201406  경상북도  칠곡군  일반용    9329   128247188  13
42  201401-201406  경상북도  칠곡군   합계   11999  1020383870 NaN
44  201401-201406  경상북도  포항시  일반용   36829   458218407   6
45  201401-201406  경상북도  포항시   합계   40424  7125640995 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1401-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)