In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_17하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2017년 07 월 ~ 2017년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,경상남도,전체(시 / 군 / 구),주택용,"1,149,061","376,232,868","40,944,228,655",108.8
4,201707,경상남도,전체(시 / 군 / 구),일반용,"217,806","565,359,543","83,473,060,873",147.6
...,...,...,...,...,...,...,...,...
907,201712,경상남도,합천군,산업용,"1,042","6,351,158","814,187,574",128.2
908,201712,경상남도,합천군,심 야,"2,162","4,228,852","317,337,702",75
909,201712,경상남도,합천군,일반용,"3,848","7,258,495","998,990,133",137.6
910,201712,경상남도,합천군,주택용,"28,835","4,677,164","516,301,242",110.4
911,201712,경상남도,합천군,합계,"52,954","37,343,465","3,431,036,462",91.9

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,경상남도,전체(시 / 군 / 구),주택용,"1,149,061","376,232,868","40,944,228,655",108.8
4,201707,경상남도,전체(시 / 군 / 구),일반용,"217,806","565,359,543","83,473,060,873",147.6
5,201707,경상남도,전체(시 / 군 / 구),교육용,"1,652","38,182,479","4,576,244,592",119.9
6,201707,경상남도,전체(시 / 군 / 구),산업용,"37,449","1,711,867,779","219,621,444,209",128.3
...,...,...,...,...,...,...,...,...
907,201712,경상남도,합천군,산업용,"1,042","6,351,158","814,187,574",128.2
908,201712,경상남도,합천군,심 야,"2,162","4,228,852","317,337,702",75
909,201712,경상남도,합천군,일반용,"3,848","7,258,495","998,990,133",137.6
910,201712,경상남도,합천군,주택용,"28,835","4,677,164","516,301,242",110.4
911,201712,경상남도,합천군,합계,"52,954","37,343,465","3,431,036,462",91.9

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,경상남도,전체(시 / 군 / 구),주택용,"1,149,061","376,232,868","40,944,228,655",108.8
4,201707,경상남도,전체(시 / 군 / 구),일반용,"217,806","565,359,543","83,473,060,873",147.6
5,201707,경상남도,전체(시 / 군 / 구),교육용,"1,652","38,182,479","4,576,244,592",119.9
6,201707,경상남도,전체(시 / 군 / 구),산업용,"37,449","1,711,867,779","219,621,444,209",128.3
7,201707,경상남도,전체(시 / 군 / 구),농사용,"191,682","134,207,102","6,638,792,025",49.5
...,...,...,...,...,...,...,...,...
907,201712,경상남도,합천군,산업용,"1,042","6,351,158","814,187,574",128.2
908,201712,경상남도,합천군,심 야,"2,162","4,228,852","317,337,702",75
909,201712,경상남도,합천군,일반용,"3,848","7,258,495","998,990,133",137.6
910,201712,경상남도,합천군,주택용,"28,835","4,677,164","516,301,242",110.4
911,201712,경상남도,합천군,합계,"52,954","37,343,465","3,431,036,462",91.9

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,경상남도,전체(시 / 군 / 구),주택용,"1,149,061","376,232,868","40,944,228,655",108.8
4,201707,경상남도,전체(시 / 군 / 구),일반용,"217,806","565,359,543","83,473,060,873",147.6
5,201707,경상남도,전체(시 / 군 / 구),교육용,"1,652","38,182,479","4,576,244,592",119.9
6,201707,경상남도,전체(시 / 군 / 구),산업용,"37,449","1,711,867,779","219,621,444,209",128.3
7,201707,경상남도,전체(시 / 군 / 구),농사용,"191,682","134,207,102","6,638,792,025",49.5
8,201707,경상남도,전체(시 / 군 / 구),가로등,"159,557","20,658,660","2,529,002,112",122.4
9,201707,경상남도,전체(시 / 군 / 구),심 야,"91,655","26,560,518","1,532,009,377",57.7
10,201708,경상남도,전체(시 / 군 / 구),주택용,"1,150,605","468,685,857","59,232,415,661",126.4
11,201708,경상남도,전체(시 / 군 / 구),일반용,"218,269","654,808,473","93,604,037,112",142.9
12,201708,경상남도,전체(시 / 군 / 구),교육용,"1,653","35,972,315","4,560,937,375",126.8
13,201708,경상남도,전체(시 / 군 / 구),산업용,"37,500","1,591,864,608","207,178,241,369",130.1
14,201708,경상남도,전체(시 / 군 / 구),농사용,"192,800","165,862,284","7,991,543,508",48.2
15,201708,경상남도,전체(시 / 군 / 구),가로등,"160,092","21,601,053","2,549,329,019",118.0
16,201708,경상남도,전체(시 / 군 / 구),심 야,"91,421","22,188,280","1,307,442,435",58.9
17,201709,경상남도,전체(시 / 군 / 구),주택용,"1,152,280","385,192,375","42,058,504,777",109.2
18,201709,경상남도,전체(시 / 군 / 구),일반용,"218,432","568,785,785","74,235,186,764",130.5
19,201709,경상남도,전체(시 / 군 / 구),교육용,"1,657","35,546,516","3,939,008,745",110.8
20,201709,경상남도,전체(시 / 군 / 구),산업용,"37,520","1,700,991,270","180,317,220,447",106.0
21,201709,경상남도,전체(시 / 군 / 구),농사용,"193,641","143,935,936","7,133,704,963",49.6
22,201709,경상남도,전체(시 / 군 / 구),가로등,"160,746","22,505,270","2,588,750,342",115.0
23,201709,경상남도,전체(시 / 군 / 구),심 야,"91,203","22,698,339","1,306,351,383",57.6
24,201710,경상남도,전체(시 / 군 / 구),주택용,"1,153,979","334,258,258","33,057,067,631",98.9
25,201710,경상남도,전체(시 / 군 / 구),일반용,"218,446","463,675,935","54,877,431,647",118.4
26,201710,경상남도,전체(시 / 군 / 구),교육용,"1,654","25,996,899","2,624,755,861",101.0
27,201710,경상남도,전체(시 / 군 / 구),산업용,"37,552","1,459,618,533","150,967,107,085",103.4
28,201710,경상남도,전체(시 / 군 / 구),농사용,"194,246","115,414,978","6,115,575,144",53.0
29,201710,경상남도,전체(시 / 군 / 구),가로등,"161,175","23,623,475","2,602,841,195",110.2
30,201710,경상남도,전체(시 / 군 / 구),심 야,"91,053","34,282,072","1,911,941,434",55.8
31,201711,경상남도,전체(시 / 군 / 구),주택용,"1,155,978","353,024,101","36,528,379,062",103.5
32,201711,경상남도,전체(시 / 군 / 구),일반용,"218,606","474,790,278","62,954,195,306",132.6
33,201711,경상남도,전체(시 / 군 / 구),교육용,"1,659","33,130,805","3,589,674,262",108.3
34,201711,경상남도,전체(시 / 군 / 구),산업용,"37,550","1,648,243,401","200,788,680,064",121.8
35,201711,경상남도,전체(시 / 군 / 구),농사용,"220,653","180,208,826","8,722,604,213",48.4
36,201711,경상남도,전체(시 / 군 / 구),가로등,"161,526","25,131,710","2,722,589,405",108.3
37,201711,경상남도,전체(시 / 군 / 구),심 야,"90,976","71,548,222","4,598,536,673",64.3
38,201712,경상남도,전체(시 / 군 / 구),주택용,"1,156,960","376,929,578","40,673,935,022",107.9
39,201712,경상남도,전체(시 / 군 / 구),일반용,"219,231","565,482,270","78,131,846,088",138.2
40,201712,경상남도,전체(시 / 군 / 구),교육용,"1,662","48,855,095","5,039,523,409",103.2
41,201712,경상남도,전체(시 / 군 / 구),산업용,"37,563","1,723,930,597","212,647,981,019",123.4
42,201712,경상남도,전체(시 / 군 / 구),농사용,"197,024","272,022,294","13,149,350,228",48.3
43,201712,경상남도,전체(시 / 군 / 구),가로등,"162,021","25,991,887","2,740,325,339",105.4
44,201712,경상남도,전체(시 / 군 / 구),심 야,"90,847","126,243,441","9,518,483,718",75.4
45,합계,합계,합계,합계,"11,167,042","17,096,109,965","1,981,280,279,548",115.9

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_9020\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201707  경상남도  일반용  217,806   565,359,543
11  201708  경상남도  일반용  218,269   654,808,473
18  201709  경상남도  일반용  218,432   568,785,785
25  201710  경상남도  일반용  218,446   463,675,935
32  201711  경상남도  일반용  218,606   474,790,278
39  201712  경상남도  일반용  219,231   565,482,270

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201707  경상남도  거제시  일반용  17,661   43,245,556
197  201708  경상남도  거제시  일반용  17,667   51,055,296
341  201709  경상남도  거제시  일반용  17,698   44,025,557
485  201710  경상남도  거제시  일반용  17,688   35,603,866
629  201711  경상남도  거제시  일반용  17,680   35,450,993
..      ...   ...  ...  ...      ...          ...
333  201708  경상남도  합천군  일반용   3,826    7,305,051
477  201709  경상남도  합천군  일반용   3,828    6,264,548
621  201710  경상남도  합천군  일반용   3,844    5,372,541
765  201711  경상남도  합천군  일반용   3,845    5,998,258
909  201712  경상남도  합천군  일반용   3,848    7,258,495

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201707  경상남도  거제시   합계  124,079   202,904,210
199  201708  경상남도  거제시   합계  124,342   202,338,301
343  201709  경상남도  거제시   합계  124,460   185,025,907
487  201710  경상남도  거제시   합계  124,561   149,594,768
631  201711  경상남도  거제시   합계  126,024   157,930,226
..      ...   ...  ...  ...       ...           ...
335  201708  경상남도  합천군   합계   52,914    31,531,700
479  201709  경상남도  합천군   합계   52,999    28,675,589
623  201710  경상남도  합천군   합계   53,054    25,373,485
767  201711  경상남도  합천군   합계   55,195    33,081,115
911  201712  경상남도  합천군   합계   52,954    37,343,465

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[202904210, 202338301, 185025907, 149594768, 157930226, 173834400]
[34154282, 37100031, 34915185, 31727964, 37347885, 41654208]
[41346688, 42386113, 41333156, 38068765, 40606445, 50237402]
[436540673, 456854195, 448943741, 374228255, 435310006, 479665009]
[19895267, 25519434, 21864037, 19128401, 22258900, 23089127]
[83508799, 88717162, 83905730, 73432813, 90023632, 120798515]
[111275982, 117662593, 112735425, 96816147, 110448410, 121437041]
[23612027, 27416241, 25228829, 22074720, 29136670, 32649258]
[320487731, 322257914, 320182958, 271921354, 294795029, 330110807]
[31209726, 33927773, 32055946, 27884032, 33840649, 39586742]
[197870360, 216937499, 200635762, 174370733, 205160132, 257808059]
[77787595, 81023757, 75024680, 65299117, 77845219, 93729905]
[923640805, 932645387, 916526423, 782108552, 871236287, 953373117]
[79043899, 86871519, 77460440, 64277715, 69204275, 81145174]
[26678283, 26656678, 24878847, 25547285, 29004944, 36272070]
[215386043, 208587582, 228590815, 195678512, 225679740, 241558795]
[19399778, 22548991, 21672021, 19337532, 23167779, 25162068]
[28326801, 31531700, 28675589, 25373485, 33081115, 37343465]
경상남도 지역별 합계 :  [1071627812, 216899555, 253978569, 2631541879, 131755166, 540386651, 670375598, 160117745, 1859755793, 198504868, 1252782545, 470710273, 5379530571, 458003022, 169038107, 1315481487, 131288169, 184332155]
경상남도 고객호수 평균:  [20783, 9538, 8966, 33632, 8354, 16750, 12781, 7165, 19929, 5843, 32159, 10357, 76183, 13658, 9108, 9062, 7039, 8884]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201707  경상남도  거제시   합계  124,079   202,904,210
1           201708  경상남도  거제시   합계  124,342   202,338,301
2           201709  경상남도  거제시   합계  124,460   185,025,907
3           201710  경상남도  거제시   합계  124,561   149,594,768
4           201711  경상남도  거제시   합계  126,024   157,930,226
..             ...   ...  ...  ...       ...           ...
121  201707-201712  경상남도  통영시   합계     13658     458003022
122  201707-201712  경상남도  하동군   합계      9108     169038107
123  201707-201712  경상남도  함안군   합계      9062    1315481487
124  201707-201712  경상남도  함양군   합계      7039     131288169
125  201707-201712  경상남도  합천군   합계      8884     184332155

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201707-201712']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201707-201712  경상남도  거제시   합계   20783  1071627812
109  201707-201712  경상남도  거창군   합계    9538   216899555
110  201707-201712  경상남도  고성군   합계    8966   253978569
111  201707-201712  경상남도  김해시   합계   33632  2631541879
112  201707-201712  경상남도  남해군   합계    8354   131755166
113  201707-201712  경상남도  밀양시   합계   16750   540386651
114  201707-201712  경상남도  사천시   합계   12781   670375598
115  201707-201712  경상남도  산청군   합계    7165   160117745
116  201707-201712  경상남도  양산시   합계   19929  1859755793
117  201707-201712  경상남도  의령군   합계    5843   198504868
118  201707-201712  경상남도  진주시   합계   32159  1252782545
119  201707-201712  경상남도  창녕군   합계   10357   470710273
120  201707-201712  경상남도  창원시   합계   76183  5379530571
121  201707-201712  경상남도  통영시   합계   13658   458003022
122  201707-201712  경상남도  하동군   합계    9108   169038107
123  201707-201712  경상남도  함안군   합계    9062  1315481487
124  201707-201712  경상남도  함양군   합계    7039   131288169
125  201707-201712  경상남도  합천군   합계    8884   184332155

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201707  경상남도  거제시  일반용  17,661   43,245,556
197  201708  경상남도  거제시  일반용  17,667   51,055,296
341  201709  경상남도  거제시  일반용  17,698   44,025,557
485  201710  경상남도  거제시  일반용  17,688   35,603,866
629  201711  경상남도  거제시  일반용  17,680   35,450,993
..      ...   ...  ...  ...      ...          ...
333  201708  경상남도  합천군  일반용   3,826    7,305,051
477  201709  경상남도  합천군  일반용   3,828    6,264,548
621  201710  경상남도  합천군  일반용   3,844    5,372,541
765  201711  경상남도  합천군  일반용   3,845    5,998,258
909  201712  경상남도  합천군  일반용   3,848    7,258,495

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[43245556, 51055296, 44025557, 35603866, 35450993, 40980892]
[8072877, 9357960, 8027705, 6887687, 7903550, 9700734]
[8001001, 9610956, 8419019, 7089421, 7553740, 9273588]
[89163927, 102062221, 87818964, 70944071, 71359827, 85763939]
[7775937, 10172859, 8390789, 6990272, 7233695, 8241783]
[16779816, 19634814, 17155465, 14061003, 15374975, 18598063]
[19737223, 24077838, 21454336, 17186195, 17908938, 21340206]
[5126544, 6335569, 5424286, 4642327, 5143787, 6084462]
[53243097, 60428636, 52521511, 43288493, 44552106, 52637209]
[3592963, 4180938, 3725475, 3261118, 3448920, 4158299]
[60951417, 69908347, 60762632, 49588531, 50644658, 60815392]
[10946795, 12615774, 10988587, 9324769, 9862734, 11872206]
[184878368, 210078062, 183032751, 147567671, 148941745, 177825312]
[25449838, 31746849, 28267108, 23127240, 23098306, 26759819]
[6339844, 7861613, 6744550, 5633910, 6083419, 7223799]
[11088565, 12410221, 10500880, 8682268, 9427487, 11272016]
[4958033, 5965469, 5261622, 4424552, 4803140, 5676056]
[6007742, 7305051, 6264548, 5372541, 5998258, 7258495]
경상남도 지역별 일반용 합계 :  [250362160, 49950513, 49947725, 507112949, 48805335, 101604136, 121704736, 32756975, 306671052, 22367713, 352670977, 65610865, 1052323909, 158449160, 39887135, 63381437, 31088872, 38206635]
경상남도 고객호수 평균:  [17687, 4960, 4492, 29640, 4643, 9050, 9345, 3389, 18323, 2306, 25047, 5393, 56250, 11157, 4165, 5230, 3546, 3833]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9020\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201707  경상남도  거제시  일반용  17,661   43,245,556
1           201708  경상남도  거제시  일반용  17,667   51,055,296
2           201709  경상남도  거제시  일반용  17,698   44,025,557
3           201710  경상남도  거제시  일반용  17,688   35,603,866
4           201711  경상남도  거제시  일반용  17,680   35,450,993
..             ...   ...  ...  ...      ...          ...
121  201707-201712  경상남도  통영시  일반용    11157    158449160
122  201707-201712  경상남도  하동군  일반용     4165     39887135
123  201707-201712  경상남도  함안군  일반용     5230     63381437
124  201707-201712  경상남도  함양군  일반용     3546     31088872
125  201707-201712  경상남도  합천군  일반용     3833     38206635

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201707-201712']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201707-201712  경상남도  거제시  일반용   17687   250362160
109  201707-201712  경상남도  거창군  일반용    4960    49950513
110  201707-201712  경상남도  고성군  일반용    4492    49947725
111  201707-201712  경상남도  김해시  일반용   29640   507112949
112  201707-201712  경상남도  남해군  일반용    4643    48805335
113  201707-201712  경상남도  밀양시  일반용    9050   101604136
114  201707-201712  경상남도  사천시  일반용    9345   121704736
115  201707-201712  경상남도  산청군  일반용    3389    32756975
116  201707-201712  경상남도  양산시  일반용   18323   306671052
117  201707-201712  경상남도  의령군  일반용    2306    22367713
118  201707-201712  경상남도  진주시  일반용   25047   352670977
119  201707-201712  경상남도  창녕군  일반용    5393    65610865
120  201707-201712  경상남도  창원시  일반용   56250  1052323909
121  201707-201712  경상남도  통영시  일반용   11157   158449160
122  201707-201712  경상남도  하동군  일반용    4165    39887135
123  201707-201712  경상남도  함안군  일반용    5230    63381437
124  201707-201712  경상남도  함양군  일반용    3546    31088872
125  201707-201712  경상남도  합천군  일반용    3833    38206635

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201707-201712  경상남도  거제시  일반용   17687   250362160
108  201707-201712  경상남도  거제시   합계   20783  1071627812
109  201707-201712  경상남도  거창군  일반용    4960    49950513
109  201707-201712  경상남도  거창군   합계    9538   216899555
110  201707-201712  경상남도  고성군  일반용    4492    49947725
110  201707-201712  경상남도  고성군   합계    8966   253978569
111  201707-201712  경상남도  김해시   합계   33632  2631541879
111  201707-201712  경상남도  김해시  일반용   29640   507112949
112  201707-201712  경상남도  남해군   합계    8354   131755166
112  201707-201712  경상남도  남해군  일반용    4643    48805335
113  201707-201712  경상남도  밀양시  일반용    9050   101604136
113  201707-201712  경상남도  밀양시   합계   16750   540386651
114  201707-201712  경상남도  사천시   합계   12781   670375598
114  201707-201712  경상남도  사천시  일반용    9345   121704736
115  201707-201712  경상남도  산청군  일반용    3389    32756975
115  201707-201712  경상남도  산청군   합계    7165   160117745
116  201707-201712  경상남도  양산시  일반용   18323   306671052
116  201707-201712  경상남도  양산시   합계   19929  1859755793
117  201707-201712  경상남도  의령군  일반용    2306    22367713
117  201707-201712  경상남도  의령군   합계    5843   198504868
118  201707-201712  경상남도  진주시   합계   32159  1252782545
118  201707-201712  경상남도  진주시  일반용   25047   352670977
119  201707-201712  경상남도  창녕군   합계   10357   470710273
119  201707-201712  경상남도  창녕군  일반용    5393    65610865
120  201707-201712  경상남도  창원시  일반용   56250  1052323909
120  201707-201712  경상남도  창원시   합계   76183  5379530571
121  201707-201712  경상남도  통영시   합계   13658   458003022
121  201707-201712  경상남도  통영시  일반용   11157   158449160
122  201707-201712  경상남도  하동군   합계    9108   169038107
122  201707-201712  경상남도  하동군  일반용    4165    39887135
123  201707-201712  경상남도  함안군   합계    9062  1315481487
123  201707-201712  경상남도  함안군  일반용    5230    63381437
124  201707-201712  경상남도  함양군   합계    7039   131288169
124  201707-201712  경상남도  함양군  일반용    3546    31088872
125  201707-201712  경상남도  합천군  일반용    3833    38206635
125  201707-201712  경상남도  합천군   합계    8884   184332155

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[250362160,
 49950513,
 49947725,
 507112949,
 48805335,
 101604136,
 121704736,
 32756975,
 306671052,
 22367713,
 352670977,
 65610865,
 1052323909,
 158449160,
 39887135,
 63381437,
 31088872,
 38206635]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1071627812,
 216899555,
 253978569,
 2631541879,
 131755166,
 540386651,
 670375598,
 160117745,
 1859755793,
 198504868,
 1252782545,
 470710273,
 5379530571,
 458003022,
 169038107,
 1315481487,
 131288169,
 184332155]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[23.36, 23.03, 19.67, 19.27, 37.04, 18.8, 18.15, 20.46, 16.49, 11.27, 28.15, 13.94, 19.56, 34.6, 23.6, 4.82, 23.68, 20.73]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    23
1    23
2    20
3    19
4    37
5    19
6    18
7    20
8    16
9    11
10   28
11   14
12   20
13   35
14   24
15    5
16   24
17   21
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  23
1   거창군  일반용  23
2   고성군  일반용  20
3   김해시  일반용  19
4   남해군  일반용  37
5   밀양시  일반용  19
6   사천시  일반용  18
7   산청군  일반용  20
8   양산시  일반용  16
9   의령군  일반용  11
10  진주시  일반용  28
11  창녕군  일반용  14
12  창원시  일반용  20
13  통영시  일반용  35
14  하동군  일반용  24
15  함안군  일반용   5
16  함양군  일반용  24
17  합천군  일반용  21

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201707-201712  경상남도  거제시  일반용   17687   250362160  23
1   201707-201712  경상남도  거제시   합계   20783  1071627812 NaN
2   201707-201712  경상남도  거창군  일반용    4960    49950513  23
3   201707-201712  경상남도  거창군   합계    9538   216899555 NaN
4   201707-201712  경상남도  고성군  일반용    4492    49947725  20
5   201707-201712  경상남도  고성군   합계    8966   253978569 NaN
7   201707-201712  경상남도  김해시  일반용   29640   507112949  19
6   201707-201712  경상남도  김해시   합계   33632  2631541879 NaN
9   201707-201712  경상남도  남해군  일반용    4643    48805335  37
8   201707-201712  경상남도  남해군   합계    8354   131755166 NaN
10  201707-201712  경상남도  밀양시  일반용    9050   101604136  19
11  201707-201712  경상남도  밀양시   합계   16750   540386651 NaN
13  201707-201712  경상남도  사천시  일반용    9345   121704736  18
12  201707-201712  경상남도  사천시   합계   12781   670375598 NaN
14  201707-201712  경상남도  산청군  일반용    3389    32756975  20
15  201707-201712  경상남도  산청군   합계    7165   160117745 NaN
16  201707-201712  경상남도  양산시  일반용   18323   306671052  16
17  201707-201712  경상남도  양산시   합계   19929  1859755793 NaN
18  201707-201712  경상남도  의령군  일반용    2306    22367713  11
19  201707-201712  경상남도  의령군   합계    5843   198504868 NaN
21  201707-201712  경상남도  진주시  일반용   25047   352670977  28
20  201707-201712  경상남도  진주시   합계   32159  1252782545 NaN
23  201707-201712  경상남도  창녕군  일반용    5393    65610865  14
22  201707-201712  경상남도  창녕군   합계   10357   470710273 NaN
24  201707-201712  경상남도  창원시  일반용   56250  1052323909  20
25  201707-201712  경상남도  창원시   합계   76183  5379530571 NaN
27  201707-201712  경상남도  통영시  일반용   11157   158449160  35
26  201707-201712  경상남도  통영시   합계   13658   458003022 NaN
29  201707-201712  경상남도  하동군  일반용    4165    39887135  24
28  201707-201712  경상남도  하동군   합계    9108   169038107 NaN
31  201707-201712  경상남도  함안군  일반용    5230    63381437   5
30  201707-201712  경상남도  함안군   합계    9062  1315481487 NaN
33  201707-201712  경상남도  함양군  일반용    3546    31088872  24
32  201707-201712  경상남도  함양군   합계    7039   131288169 NaN
34  201707-201712  경상남도  합천군  일반용    3833    38206635  21
35  201707-201712  경상남도  합천군   합계    8884   184332155 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1707-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)