In [2]:
import pandas as pd

In [4]:
price = pd.read_csv(".\실거래가\강원도\원주시.csv", encoding='cp949')
price

,시군구,번지,지목,용도지역,도로조건,계약년월,계약일,계약면적(㎡),거래금액(만원),지분구분,해제사유발생일,거래유형,중개사소재지
0,강원도 원주시 부론면 법천리,7**,답,생산관리지역,8m미만,202106,1,324.0,"1,120",,NaN,-,-
1,강원도 원주시 부론면 법천리,7**,답,생산관리지역,12m미만,202106,1,317.0,"1,149",,NaN,-,-
2,강원도 원주시 부론면 법천리,7**,답,생산관리지역,-,202106,1,393.0,"1,255",,NaN,-,-
3,강원도 원주시 부론면 법천리,7**,답,생산관리지역,8m미만,202106,1,519.0,"1,794",,NaN,-,-
4,강원도 원주시 귀래면 운남리,2**,전,생산관리지역,-,202106,1,1445.0,"10,000",,NaN,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7242,강원도 원주시 부론면 정산리,1**,전,생산관리지역,-,202205,31,1478.0,"7,100",,NaN,중개거래,강원 원주시
7243,강원도 원주시 지정면 가곡리,산1**,임야,계획관리지역,8m미만,202205,31,338.0,"7,140",,NaN,직거래,-
7244,강원도 원주시 신림면 성남리,2**,답,계획관리지역,12m미만,202206,1,990.0,"23,000",,NaN,중개거래,강원 원주시
7245,강원도 원주시 지정면 신평리,1***,대,제1종일반주거지역,12m미만,202206,1,397.7,"26,657",,NaN,중개거래,강원 원주시
7246,강원도 원주시 문막읍 동화리,8*,도로,계획관리지역,8m미만,202206,1,316.0,"7,000",,NaN,중개거래,강원 원주시

In [8]:
price = price[['지목','용도지역','거래금액(만원)']]

In [12]:
price = price[price.isin({'지목' : ['전','답','임야']})['지목']]

In [13]:
price = price[~price.isin({'용도지역' : ['자연녹지지역','개발제한구역','농림지역','용도미지정','보전관리지역']})['용도지역']]

In [14]:
price

      지목    용도지역 거래금액(만원)
0      답  생산관리지역    1,120
1      답  생산관리지역    1,149
2      답  생산관리지역    1,255
3      답  생산관리지역    1,794
4      전  생산관리지역   10,000
...   ..     ...      ...
7234   전  생산관리지역      250
7241   전  생산관리지역    7,100
7242   전  생산관리지역    7,100
7243  임야  계획관리지역    7,140
7244   답  계획관리지역   23,000

[3381 rows x 3 columns]

## 전체 데이터에 적용

In [36]:
price = pd.read_csv('실거래가_raw.csv')

In [53]:
price

,Source.Name,시군구,번지,지목,용도지역,도로조건,계약년월,계약일,계약면적(㎡),거래금액(만원),지분구분,해제사유발생일,거래유형,중개사소재지
0,가평군.csv,경기도 가평군 가평읍 하색리,산1**,임야,농림지역,-,202106,1.0,4.0,1200.0,,NaN,-,-
1,가평군.csv,경기도 가평군 청평면 호명리,3**,임야,자연녹지지역,8m미만,202106,1.0,280.0,1500.0,,NaN,-,-
2,가평군.csv,경기도 가평군 상면 항사리,2**,답,농림지역,8m미만,202106,1.0,1442.0,10607.0,,20211104.0,-,-
3,가평군.csv,경기도 가평군 설악면 신천리,5**,답,생산녹지지역,12m미만,202106,1.0,730.0,110000.0,지분,20211025.0,-,-
4,가평군.csv,경기도 가평군 조종면 상판리,1**,전,계획관리지역,12m미만,202106,1.0,1315.0,12000.0,,NaN,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
585099,횡성군.csv,강원도 횡성군 우천면 용둔리,2*,전,계획관리지역,8m미만,202205,31.0,95.0,809.0,,NaN,중개거래,강원 횡성군
585100,횡성군.csv,강원도 횡성군 우천면 용둔리,1*,전,계획관리지역,8m미만,202205,31.0,102.0,912.0,,NaN,중개거래,강원 횡성군
585101,횡성군.csv,강원도 횡성군 둔내면 둔방내리,2**,전,제1종일반주거지역,25m미만,202206,1.0,484.0,10500.0,,NaN,직거래,-
585102,횡성군.csv,강원도 횡성군 청일면 유평리,2**,전,계획관리지역,8m미만,202206,1.0,2235.0,15500.0,,NaN,중개거래,강원 횡성군
585103,횡성군.csv,강원도 횡성군 둔내면 삽교리,1***,임야,계획관리지역,-,202206,1.0,208.0,2000.0,,NaN,중개거래,서울 송파구

In [41]:
def make_mean(df):
    df = df[['Source.Name','지목','용도지역','거래금액(만원)']]
    df = df[df.isin({'지목' : ['전','답','임야']})['지목']]
    df = df[~df.isin({'용도지역' : ['자연녹지지역','개발제한구역','농림지역','용도미지정','보전관리지역']})['용도지역']]
    df['Source.Name'] = df['Source.Name'].apply(lambda x : x[:-4])
    df.rename(columns={'Source.Name':'시군'}, inplace=True)
    df = df.groupby('시군').mean()
    df = df.reset_index()
    return df

In [42]:
price_mean = make_mean(price)
price_mean

      시군      거래금액(만원)
0    가평군  15387.633759
1    경산시  16654.888506
2    경주시  14113.901760
3    계룡시  14780.884422
4    고령군  17663.963365
..   ...           ...
104  홍천군   5884.744025
105  화성시  22948.540878
106  화순군   8033.240032
107  화천군   5156.828758
108  횡성군   6909.686655

[109 rows x 2 columns]

In [44]:
price_mean.to_csv('실거래가_평균.csv', encoding='utf-8-sig')

## 데이터셋 병합

In [48]:
data = pd.read_csv('https://raw.githubusercontent.com/BigDataFinalPJ/bae_data/master/%EA%B0%80%EC%A4%91%EC%B9%981.csv?token=GHSAT0AAAAAABWZKYJ3GS2JT7E4AWACBM7IYXMUGPQ',
           encoding='cp949')

In [49]:
final = pd.merge(data, price_mean, on='시군')

In [50]:
final

      시군   평균기온(°C)     지진위험도     태풍위험도  기업갯수      거래금액(만원)
0    가평군  10.923333 -0.225015  0.532135    24  15387.633759
1    경산시  13.855000 -0.225015  0.992162   192  16654.888506
2    경주시  12.903778  0.921960  0.532135    98  14113.901760
3    계룡시  10.216667 -0.225015 -0.418695    19  14780.884422
4    고령군  12.822222  0.218245  0.992162    17  17663.963365
..   ...        ...       ...       ...   ...           ...
104  홍천군   9.058889 -0.225015  0.992162    28   5884.744025
105  화성시  12.516667 -0.225015 -0.418695   355  22948.540878
106  화순군  13.072500 -0.225015  1.022939    61   8033.240032
107  화천군   9.272130 -0.225015  0.532135    14   5156.828758
108  횡성군  10.080000 -0.225015 -0.418695    14   6909.686655

[109 rows x 6 columns]

In [51]:
final.to_csv('가중치_실거래가추가.csv', encoding='utf-8-sig')