In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경기도_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경기도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경기도,전체(시 / 군 / 구),주택용,"2,624,776","1,453,916,824","198,843,153,313",136.8
4,201501,경기도,전체(시 / 군 / 구),일반용,"606,817","2,491,127,427","323,376,461,281",129.8
...,...,...,...,...,...,...,...,...
1531,201506,경기도,화성시,산업용,"16,225","1,032,815,797","120,850,153,265",117
1532,201506,경기도,화성시,심 야,"13,275","9,469,683","544,617,787",57.5
1533,201506,경기도,화성시,일반용,"34,622","121,463,412","16,309,919,242",134.3
1534,201506,경기도,화성시,주택용,"102,760","61,039,975","7,463,967,888",122.3
1535,201506,경기도,화성시,합계,"204,948","1,248,008,141","147,073,061,559",117.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경기도,전체(시 / 군 / 구),주택용,"2,624,776","1,453,916,824","198,843,153,313",136.8
4,201501,경기도,전체(시 / 군 / 구),일반용,"606,817","2,491,127,427","323,376,461,281",129.8
5,201501,경기도,전체(시 / 군 / 구),교육용,"4,224","164,490,621","18,158,469,440",110.4
6,201501,경기도,전체(시 / 군 / 구),산업용,"113,664","4,997,455,612","588,953,163,679",117.9
...,...,...,...,...,...,...,...,...
1531,201506,경기도,화성시,산업용,"16,225","1,032,815,797","120,850,153,265",117
1532,201506,경기도,화성시,심 야,"13,275","9,469,683","544,617,787",57.5
1533,201506,경기도,화성시,일반용,"34,622","121,463,412","16,309,919,242",134.3
1534,201506,경기도,화성시,주택용,"102,760","61,039,975","7,463,967,888",122.3
1535,201506,경기도,화성시,합계,"204,948","1,248,008,141","147,073,061,559",117.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경기도,전체(시 / 군 / 구),주택용,"2,624,776","1,453,916,824","198,843,153,313",136.8
4,201501,경기도,전체(시 / 군 / 구),일반용,"606,817","2,491,127,427","323,376,461,281",129.8
5,201501,경기도,전체(시 / 군 / 구),교육용,"4,224","164,490,621","18,158,469,440",110.4
6,201501,경기도,전체(시 / 군 / 구),산업용,"113,664","4,997,455,612","588,953,163,679",117.9
7,201501,경기도,전체(시 / 군 / 구),농사용,"191,164","243,641,898","11,492,858,772",47.2
...,...,...,...,...,...,...,...,...
1531,201506,경기도,화성시,산업용,"16,225","1,032,815,797","120,850,153,265",117
1532,201506,경기도,화성시,심 야,"13,275","9,469,683","544,617,787",57.5
1533,201506,경기도,화성시,일반용,"34,622","121,463,412","16,309,919,242",134.3
1534,201506,경기도,화성시,주택용,"102,760","61,039,975","7,463,967,888",122.3
1535,201506,경기도,화성시,합계,"204,948","1,248,008,141","147,073,061,559",117.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경기도,전체(시 / 군 / 구),주택용,"2,624,776","1,453,916,824","198,843,153,313",136.8
4,201501,경기도,전체(시 / 군 / 구),일반용,"606,817","2,491,127,427","323,376,461,281",129.8
5,201501,경기도,전체(시 / 군 / 구),교육용,"4,224","164,490,621","18,158,469,440",110.4
6,201501,경기도,전체(시 / 군 / 구),산업용,"113,664","4,997,455,612","588,953,163,679",117.9
7,201501,경기도,전체(시 / 군 / 구),농사용,"191,164","243,641,898","11,492,858,772",47.2
8,201501,경기도,전체(시 / 군 / 구),가로등,"297,128","75,966,923","8,165,514,274",107.5
9,201501,경기도,전체(시 / 군 / 구),심 야,"161,865","588,189,947","44,520,516,420",75.7
10,201502,경기도,전체(시 / 군 / 구),주택용,"2,629,806","1,418,448,100","188,613,086,324",133.0
11,201502,경기도,전체(시 / 군 / 구),일반용,"607,620","2,309,562,890","304,282,714,949",131.7
12,201502,경기도,전체(시 / 군 / 구),교육용,"4,243","147,791,488","16,886,759,584",114.3
13,201502,경기도,전체(시 / 군 / 구),산업용,"113,994","4,654,338,153","548,685,004,822",117.9
14,201502,경기도,전체(시 / 군 / 구),농사용,"191,139","235,374,413","11,085,355,448",47.1
15,201502,경기도,전체(시 / 군 / 구),가로등,"297,919","71,093,573","8,000,478,666",112.5
16,201502,경기도,전체(시 / 군 / 구),심 야,"161,596","543,995,536","41,158,676,246",75.7
17,201503,경기도,전체(시 / 군 / 구),주택용,"2,633,700","1,249,694,738","148,816,448,420",119.1
18,201503,경기도,전체(시 / 군 / 구),일반용,"607,695","2,031,222,056","245,381,739,067",120.8
19,201503,경기도,전체(시 / 군 / 구),교육용,"4,248","139,991,415","14,450,769,492",103.2
20,201503,경기도,전체(시 / 군 / 구),산업용,"114,152","4,668,977,253","465,532,599,704",99.7
21,201503,경기도,전체(시 / 군 / 구),농사용,"259,901","193,536,264","9,251,376,016",47.8
22,201503,경기도,전체(시 / 군 / 구),가로등,"298,340","64,877,036","7,435,166,845",114.6
23,201503,경기도,전체(시 / 군 / 구),심 야,"161,333","435,109,526","29,102,897,136",66.9
24,201504,경기도,전체(시 / 군 / 구),주택용,"2,640,827","1,301,460,905","158,749,261,472",122.0
25,201504,경기도,전체(시 / 군 / 구),일반용,"609,125","1,911,664,095","217,189,786,593",113.6
26,201504,경기도,전체(시 / 군 / 구),교육용,"4,245","122,456,499","12,088,261,501",98.7
27,201504,경기도,전체(시 / 군 / 구),산업용,"114,531","4,687,511,914","455,198,415,727",97.1
28,201504,경기도,전체(시 / 군 / 구),농사용,"200,262","173,685,076","8,345,495,747",48.0
29,201504,경기도,전체(시 / 군 / 구),가로등,"298,781","63,707,755","7,527,418,976",118.2
30,201504,경기도,전체(시 / 군 / 구),심 야,"161,065","337,184,894","18,539,591,954",55.0
31,201505,경기도,전체(시 / 군 / 구),주택용,"2,647,446","1,212,828,539","140,328,992,771",115.7
32,201505,경기도,전체(시 / 군 / 구),일반용,"609,622","1,765,493,770","205,580,691,542",116.4
33,201505,경기도,전체(시 / 군 / 구),교육용,"4,244","90,693,916","10,414,874,291",114.8
34,201505,경기도,전체(시 / 군 / 구),산업용,"114,848","4,507,133,174","436,598,639,862",96.9
35,201505,경기도,전체(시 / 군 / 구),농사용,"194,040","159,262,979","7,457,786,259",46.8
36,201505,경기도,전체(시 / 군 / 구),가로등,"299,256","58,940,890","7,191,203,544",122.0
37,201505,경기도,전체(시 / 군 / 구),심 야,"160,654","198,691,682","11,058,216,211",55.7
38,201506,경기도,전체(시 / 군 / 구),주택용,"2,655,607","1,243,018,224","149,475,625,084",120.3
39,201506,경기도,전체(시 / 군 / 구),일반용,"611,122","1,900,484,512","255,895,097,485",134.6
40,201506,경기도,전체(시 / 군 / 구),교육용,"4,244","97,979,846","13,061,806,830",133.3
41,201506,경기도,전체(시 / 군 / 구),산업용,"115,316","4,605,335,404","556,369,080,520",120.8
42,201506,경기도,전체(시 / 군 / 구),농사용,"195,228","164,299,367","7,635,309,110",46.5
43,201506,경기도,전체(시 / 군 / 구),가로등,"302,469","56,465,741","7,081,014,224",125.4
44,201506,경기도,전체(시 / 군 / 구),심 야,"160,209","119,630,916","6,851,524,724",57.3
45,합계,합계,합계,합계,"24,188,465","52,956,731,791","5,924,831,304,325",111.9

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_10768\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)        사용량(kWh)
4   201501  경기도  일반용  606,817   2,491,127,427
11  201502  경기도  일반용  607,620   2,309,562,890
18  201503  경기도  일반용  607,695   2,031,222,056
25  201504  경기도  일반용  609,125   1,911,664,095
32  201505  경기도  일반용  609,622   1,765,493,770
39  201506  경기도  일반용  611,122   1,900,484,512

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201501  경기도  가평군  일반용   9,229    30,952,511
301   201502  경기도  가평군  일반용   9,281    28,834,465
549   201503  경기도  가평군  일반용   9,268    24,216,540
797   201504  경기도  가평군  일반용   9,321    21,369,228
1045  201505  경기도  가평군  일반용   9,321    19,461,218
...      ...  ...  ...  ...      ...           ...
541   201502  경기도  화성시  일반용  33,897   142,602,112
789   201503  경기도  화성시  일반용  34,014   127,902,396
1037  201504  경기도  화성시  일반용  34,226   123,018,768
1285  201505  경기도  화성시  일반용  34,395   112,946,141
1533  201506  경기도  화성시  일반용  34,622   121,463,412

[186 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경기도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['가평군',
 '고양시',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시',
 '성남시',
 '수원시',
 '시흥시',
 '안산시',
 '안성시',
 '안양시',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월   시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201501  경기도  가평군   합계   58,800      75,425,055
303   201502  경기도  가평군   합계   58,942      70,301,517
551   201503  경기도  가평군   합계   60,072      59,657,837
799   201504  경기도  가평군   합계   59,173      51,556,858
1047  201505  경기도  가평군   합계   59,298      43,572,202
...      ...  ...  ...  ...       ...             ...
543   201502  경기도  화성시   합계  201,268   1,289,478,483
791   201503  경기도  화성시   합계  207,411   1,274,081,832
1039  201504  경기도  화성시   합계  209,640   1,270,546,300
1287  201505  경기도  화성시   합계  203,856   1,217,464,612
1535  201506  경기도  화성시   합계  204,948   1,248,008,141

[186 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[75425055, 70301517, 59657837, 51556858, 43572202, 40392367]
[456827951, 428575354, 373889461, 358543033, 321007475, 324853758]
[36841218, 34241156, 31744840, 30611266, 29651671, 31224507]
[111125929, 103708337, 95365040, 93866309, 88754351, 91041480]
[240620760, 232261915, 194681752, 191341927, 164137542, 166274152]
[72218686, 67467409, 59480794, 57902046, 54127307, 57483722]
[141310063, 130998691, 119252966, 115678077, 106843954, 112636045]
[317604970, 308609921, 263991587, 265770234, 231923010, 234999375]
[286565798, 273723408, 235699240, 230479092, 203755393, 206739015]
[69841051, 63879824, 54332337, 55672987, 47947769, 49969439]
[391686066, 375759134, 334240384, 332178039, 305000068, 323461576]
[442438393, 406346022, 380547063, 366602141, 352139941, 383947289]
[487738255, 460281998, 419614785, 409062406, 384767953, 410754065]
[394795566, 373822539, 343286471, 340530451, 304595513, 316850021]
[753907667, 695885670, 691589664, 677864272, 638148537, 662651842]
[266202855, 250692386, 229921360, 223267196, 196966264, 201092249]
[238236833, 224195584, 202484463, 196799879, 183160071, 194927279]
[207725074, 203389499, 173542333, 177162184, 151899263, 152622533]
[116112789, 107587330, 89425571, 78383360, 61677207, 55637650]
[141725236, 132528995, 115382326, 109945514, 98142808, 96297177]
[57705425, 54090593, 46620295, 43640548, 37378323, 36036624]
[115243942, 108033589, 101737509, 99047752, 93187288, 92668687]
[820365502, 763968378, 735468919, 718657964, 690356600, 700653486]
[66578265, 62895724, 56301944, 54671051, 49214408, 51265053]
[157904244, 145607573, 127976832, 123305715, 113260107, 121139516]
[416550744, 381972070, 376404585, 362250127, 355722826, 354289968]
[722572966, 666136317, 663095486, 653946296, 628527508, 625450027]
[666564581, 604056308, 627202000, 598410320, 567475950, 572211661]
[266718852, 259651069, 214366249, 221015678, 189423286, 184766526]
[106623666, 100457360, 92022363, 88962116, 82815743, 86868780]
[1369010850, 1289478483, 1274081832, 1270546300, 1217464612, 1248008141]
경기도 지역별 합계 :  [340905836, 2263697032, 194314658, 583861446, 1189318048, 368679964, 726719796, 1622899097, 1436961946, 341643407, 2062325267, 2332020849, 2572219462, 2073880561, 4120047652, 1368142310, 1239804109, 1066340886, 508823907, 694022056, 275471808, 609918767, 4429470849, 340926445, 789193987, 2247190320, 3959728600, 3635920820, 1335941660, 557750028, 7668590218]
경기도 고객호수 평균:  [9883, 36009, 2390, 13342, 24825, 8287, 9845, 16366, 27530, 6366, 44564, 45621, 57412, 24083, 47587, 19404, 23757, 12952, 16511, 13168, 6933, 9789, 35416, 5756, 18230, 18871, 23926, 33525, 17747, 7692, 34100]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201501  경기도  가평군   합계  58,800   75,425,055
1           201502  경기도  가평군   합계  58,942   70,301,517
2           201503  경기도  가평군   합계  60,072   59,657,837
3           201504  경기도  가평군   합계  59,173   51,556,858
4           201505  경기도  가평군   합계  59,298   43,572,202
..             ...  ...  ...  ...      ...          ...
212  201501-201506  경기도  파주시   합계    23926   3959728600
213  201501-201506  경기도  평택시   합계    33525   3635920820
214  201501-201506  경기도  포천시   합계    17747   1335941660
215  201501-201506  경기도  하남시   합계     7692    557750028
216  201501-201506  경기도  화성시   합계    34100   7668590218

[217 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201501-201506  경기도   가평군   합계    9883   340905836
187  201501-201506  경기도   고양시   합계   36009  2263697032
188  201501-201506  경기도   과천시   합계    2390   194314658
189  201501-201506  경기도   광명시   합계   13342   583861446
190  201501-201506  경기도   광주시   합계   24825  1189318048
191  201501-201506  경기도   구리시   합계    8287   368679964
192  201501-201506  경기도   군포시   합계    9845   726719796
193  201501-201506  경기도   김포시   합계   16366  1622899097
194  201501-201506  경기도  남양주시   합계   27530  1436961946
195  201501-201506  경기도  동두천시   합계    6366   341643407
196  201501-201506  경기도   부천시   합계   44564  2062325267
197  201501-201506  경기도   성남시   합계   45621  2332020849
198  201501-201506  경기도   수원시   합계   57412  2572219462
199  201501-201506  경기도   시흥시   합계   24083  2073880561
200  201501-201506  경기도   안산시   합계   47587  4120047652
201  201501-201506  경기도   안성시   합계   19404  1368142310
202  201501-201506  경기도   안양시   합계   23757  1239804109
203  201501-201506  경기도   양주시   합계   12952  1066340886
204  201501-201506  경기도   양평군   합계   16511   508823907
205  201501-201506  경기도   여주시   합계   13168   694022056
206  201501-201506  경기도   연천군   합계    6933   275471808
207  201501-201506  경기도   오산시   합계    9789   609918767
208  201501-201506  경기도   용인시   합계   35416  4429470849
209  201501-201506  경기도   의왕시   합계    5756   340926445
210  201501-201506  경기도  의정부시   합계   18230   789193987
211  201501-201506  경기도   이천시   합계   18871  2247190320
212  201501-201506  경기도   파주시   합계   23926  3959728600
213  201501-201506  경기도   평택시   합계   33525  3635920820
214  201501-201506  경기도   포천시   합계   17747  1335941660
215  201501-201506  경기도   하남시   합계    7692   557750028
216  201501-201506  경기도   화성시   합계   34100  7668590218

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201501  경기도  가평군  일반용   9,229    30,952,511
301   201502  경기도  가평군  일반용   9,281    28,834,465
549   201503  경기도  가평군  일반용   9,268    24,216,540
797   201504  경기도  가평군  일반용   9,321    21,369,228
1045  201505  경기도  가평군  일반용   9,321    19,461,218
...      ...  ...  ...  ...      ...           ...
541   201502  경기도  화성시  일반용  33,897   142,602,112
789   201503  경기도  화성시  일반용  34,014   127,902,396
1037  201504  경기도  화성시  일반용  34,226   123,018,768
1285  201505  경기도  화성시  일반용  34,395   112,946,141
1533  201506  경기도  화성시  일반용  34,622   121,463,412

[186 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[30952511, 28834465, 24216540, 21369228, 19461218, 19500610]
[194024017, 178716025, 157218142, 148913235, 139261084, 143075493]
[21993185, 20007746, 18807803, 17805499, 17191792, 18238858]
[41243540, 38577426, 34881929, 34148042, 32936508, 31942220]
[60708019, 57398337, 47093938, 44580320, 39042810, 40854461]
[36094811, 33391494, 28629881, 26773343, 25118410, 27910945]
[39554157, 36540104, 31734943, 30268788, 27449178, 29955168]
[61660656, 58708420, 49594012, 46004593, 40807121, 43523034]
[89116047, 84160775, 69409269, 66020785, 58604703, 61953834]
[23264246, 22157096, 18417972, 17406832, 15511403, 17756559]
[126396788, 118555550, 101324248, 95888352, 88803820, 97101396]
[222008490, 201078863, 187013339, 175946296, 172185947, 194152041]
[252542580, 232818455, 212052470, 200752519, 191945090, 210833089]
[71520491, 67380963, 56476986, 53145916, 46384432, 49508931]
[115280249, 107379959, 91632213, 86287290, 78073004, 84170776]
[44301293, 41749288, 36505242, 34545693, 31018912, 31991429]
[110318758, 102414051, 91063215, 85260936, 79742479, 88171424]
[43298020, 40111667, 34104764, 31346924, 27168459, 28706335]
[27955074, 26036711, 21403867, 20042582, 17392054, 17401218]
[28971730, 27601126, 24170961, 23311140, 22110821, 23295260]
[14933536, 14055352, 11533953, 10513917, 8885116, 9229641]
[34288399, 32235125, 26799996, 25562149, 23270223, 24633931]
[204216245, 189663153, 169200584, 159943223, 150412904, 160973585]
[26204634, 24201429, 21726386, 21345981, 19682970, 21322795]
[69430746, 64887145, 54565873, 51388860, 47604109, 53433119]
[60316594, 55727141, 46274460, 42928910, 39406223, 42316156]
[88185762, 82728843, 69158608, 66442475, 58152201, 62055688]
[113318732, 98856029, 101077631, 87538487, 79176189, 85912326]
[49089641, 46467463, 38529918, 36303368, 31957776, 33033095]
[36801182, 34520577, 28700517, 26859644, 23790673, 26067683]
[153137294, 142602112, 127902396, 123018768, 112946141, 121463412]
경기도 지역별 일반용 합계 :  [144334572, 961207996, 114044883, 213729665, 289677885, 177918884, 195502338, 300297836, 429265413, 114514108, 628070154, 1152384976, 1300944203, 344417719, 562823491, 220111857, 556970863, 204736169, 130231506, 149461038, 69151515, 166789823, 1034409694, 134484195, 341309852, 286969484, 426723577, 565879394, 235381261, 176740276, 781070123]
경기도 고객호수 평균:  [9300, 38921, 2209, 11058, 23026, 9872, 8642, 18004, 31660, 5963, 34550, 33199, 50104, 21763, 28630, 13665, 24281, 12928, 11264, 8997, 4904, 9797, 35682, 5522, 20238, 14658, 24334, 31956, 17176, 12209, 34143]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10768\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0           201501  경기도  가평군  일반용  9,229   30,952,511
1           201502  경기도  가평군  일반용  9,281   28,834,465
2           201503  경기도  가평군  일반용  9,268   24,216,540
3           201504  경기도  가평군  일반용  9,321   21,369,228
4           201505  경기도  가평군  일반용  9,321   19,461,218
..             ...  ...  ...  ...     ...          ...
212  201501-201506  경기도  파주시  일반용   24334    426723577
213  201501-201506  경기도  평택시  일반용   31956    565879394
214  201501-201506  경기도  포천시  일반용   17176    235381261
215  201501-201506  경기도  하남시  일반용   12209    176740276
216  201501-201506  경기도  화성시  일반용   34143    781070123

[217 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201501-201506  경기도   가평군  일반용    9300   144334572
187  201501-201506  경기도   고양시  일반용   38921   961207996
188  201501-201506  경기도   과천시  일반용    2209   114044883
189  201501-201506  경기도   광명시  일반용   11058   213729665
190  201501-201506  경기도   광주시  일반용   23026   289677885
191  201501-201506  경기도   구리시  일반용    9872   177918884
192  201501-201506  경기도   군포시  일반용    8642   195502338
193  201501-201506  경기도   김포시  일반용   18004   300297836
194  201501-201506  경기도  남양주시  일반용   31660   429265413
195  201501-201506  경기도  동두천시  일반용    5963   114514108
196  201501-201506  경기도   부천시  일반용   34550   628070154
197  201501-201506  경기도   성남시  일반용   33199  1152384976
198  201501-201506  경기도   수원시  일반용   50104  1300944203
199  201501-201506  경기도   시흥시  일반용   21763   344417719
200  201501-201506  경기도   안산시  일반용   28630   562823491
201  201501-201506  경기도   안성시  일반용   13665   220111857
202  201501-201506  경기도   안양시  일반용   24281   556970863
203  201501-201506  경기도   양주시  일반용   12928   204736169
204  201501-201506  경기도   양평군  일반용   11264   130231506
205  201501-201506  경기도   여주시  일반용    8997   149461038
206  201501-201506  경기도   연천군  일반용    4904    69151515
207  201501-201506  경기도   오산시  일반용    9797   166789823
208  201501-201506  경기도   용인시  일반용   35682  1034409694
209  201501-201506  경기도   의왕시  일반용    5522   134484195
210  201501-201506  경기도  의정부시  일반용   20238   341309852
211  201501-201506  경기도   이천시  일반용   14658   286969484
212  201501-201506  경기도   파주시  일반용   24334   426723577
213  201501-201506  경기도   평택시  일반용   31956   565879394
214  201501-201506  경기도   포천시  일반용   17176   235381261
215  201501-201506  경기도   하남시  일반용   12209   176740276
216  201501-201506  경기도   화성시  일반용   34143   781070123

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
186  201501-201506  경기도  가평군  일반용    9300   144334572
186  201501-201506  경기도  가평군   합계    9883   340905836
187  201501-201506  경기도  고양시  일반용   38921   961207996
187  201501-201506  경기도  고양시   합계   36009  2263697032
188  201501-201506  경기도  과천시  일반용    2209   114044883
..             ...  ...  ...  ...     ...         ...
214  201501-201506  경기도  포천시  일반용   17176   235381261
215  201501-201506  경기도  하남시   합계    7692   557750028
215  201501-201506  경기도  하남시  일반용   12209   176740276
216  201501-201506  경기도  화성시  일반용   34143   781070123
216  201501-201506  경기도  화성시   합계   34100  7668590218

[62 rows x 6 columns]

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[144334572,
 961207996,
 114044883,
 213729665,
 289677885,
 177918884,
 195502338,
 300297836,
 429265413,
 114514108,
 628070154,
 1152384976,
 1300944203,
 344417719,
 562823491,
 220111857,
 556970863,
 204736169,
 130231506,
 149461038,
 69151515,
 166789823,
 1034409694,
 134484195,
 341309852,
 286969484,
 426723577,
 565879394,
 235381261,
 176740276,
 781070123]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[340905836,
 2263697032,
 194314658,
 583861446,
 1189318048,
 368679964,
 726719796,
 1622899097,
 1436961946,
 341643407,
 2062325267,
 2332020849,
 2572219462,
 2073880561,
 4120047652,
 1368142310,
 1239804109,
 1066340886,
 508823907,
 694022056,
 275471808,
 609918767,
 4429470849,
 340926445,
 789193987,
 2247190320,
 3959728600,
 3635920820,
 1335941660,
 557750028,
 7668590218]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[42.34, 42.46, 58.69, 36.61, 24.36, 48.26, 26.9, 18.5, 29.87, 33.52, 30.45, 49.42, 50.58, 16.61, 13.66, 16.09, 44.92, 19.2, 25.59, 21.54, 25.1, 27.35, 23.35, 39.45, 43.25, 12.77, 10.78, 15.56, 17.62, 31.69, 10.19]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    42
1    42
2    59
3    37
4    24
5    48
6    27
7    18
8    30
9    34
10   30
11   49
12   51
13   17
14   14
15   16
16   45
17   19
18   26
19   22
20   25
21   27
22   23
23   39
24   43
25   13
26   11
27   16
28   18
29   32
30   10
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    가평군  일반용  42
1    고양시  일반용  42
2    과천시  일반용  59
3    광명시  일반용  37
4    광주시  일반용  24
5    구리시  일반용  48
6    군포시  일반용  27
7    김포시  일반용  18
8   남양주시  일반용  30
9   동두천시  일반용  34
10   부천시  일반용  30
11   성남시  일반용  49
12   수원시  일반용  51
13   시흥시  일반용  17
14   안산시  일반용  14
15   안성시  일반용  16
16   안양시  일반용  45
17   양주시  일반용  19
18   양평군  일반용  26
19   여주시  일반용  22
20   연천군  일반용  25
21   오산시  일반용  27
22   용인시  일반용  23
23   의왕시  일반용  39
24  의정부시  일반용  43
25   이천시  일반용  13
26   파주시  일반용  11
27   평택시  일반용  16
28   포천시  일반용  18
29   하남시  일반용  32
30   화성시  일반용  10

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201501-201506  경기도  가평군  일반용    9300   144334572  42
1   201501-201506  경기도  가평군   합계    9883   340905836 NaN
2   201501-201506  경기도  고양시  일반용   38921   961207996  42
3   201501-201506  경기도  고양시   합계   36009  2263697032 NaN
4   201501-201506  경기도  과천시  일반용    2209   114044883  59
..            ...  ...  ...  ...     ...         ...  ..
56  201501-201506  경기도  포천시   합계   17747  1335941660 NaN
59  201501-201506  경기도  하남시  일반용   12209   176740276  32
58  201501-201506  경기도  하남시   합계    7692   557750028 NaN
60  201501-201506  경기도  화성시  일반용   34143   781070123  10
61  201501-201506  경기도  화성시   합계   34100  7668590218 NaN

[62 rows x 7 columns]

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)