In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('부산광역시_계약종별_전력사용량_월별_18상반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 부산광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2018년 01 월 ~ 2018년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,부산광역시,전체(시 / 군 / 구),주택용,"952,240","425,745,586","48,665,579,089",114.3
4,201801,부산광역시,전체(시 / 군 / 구),일반용,"186,765","627,811,751","84,094,226,460",133.9
...,...,...,...,...,...,...,...,...
811,201806,부산광역시,해운대구,산업용,941,"21,108,123","2,517,177,681",119.3
812,201806,부산광역시,해운대구,심 야,944,"2,112,204","130,465,817",61.8
813,201806,부산광역시,해운대구,일반용,"14,207","71,164,046","9,631,482,171",135.3
814,201806,부산광역시,해운대구,주택용,"72,360","50,380,488","5,464,262,154",108.5
815,201806,부산광역시,해운대구,합계,"93,613","149,035,761","18,227,539,943",122.3

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,부산광역시,전체(시 / 군 / 구),주택용,"952,240","425,745,586","48,665,579,089",114.3
4,201801,부산광역시,전체(시 / 군 / 구),일반용,"186,765","627,811,751","84,094,226,460",133.9
5,201801,부산광역시,전체(시 / 군 / 구),교육용,"1,175","49,161,289","5,194,079,994",105.7
6,201801,부산광역시,전체(시 / 군 / 구),산업용,"25,079","785,788,309","98,237,620,503",125.0
...,...,...,...,...,...,...,...,...
811,201806,부산광역시,해운대구,산업용,941,"21,108,123","2,517,177,681",119.3
812,201806,부산광역시,해운대구,심 야,944,"2,112,204","130,465,817",61.8
813,201806,부산광역시,해운대구,일반용,"14,207","71,164,046","9,631,482,171",135.3
814,201806,부산광역시,해운대구,주택용,"72,360","50,380,488","5,464,262,154",108.5
815,201806,부산광역시,해운대구,합계,"93,613","149,035,761","18,227,539,943",122.3

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,부산광역시,전체(시 / 군 / 구),주택용,"952,240","425,745,586","48,665,579,089",114.3
4,201801,부산광역시,전체(시 / 군 / 구),일반용,"186,765","627,811,751","84,094,226,460",133.9
5,201801,부산광역시,전체(시 / 군 / 구),교육용,"1,175","49,161,289","5,194,079,994",105.7
6,201801,부산광역시,전체(시 / 군 / 구),산업용,"25,079","785,788,309","98,237,620,503",125.0
7,201801,부산광역시,전체(시 / 군 / 구),농사용,"10,947","13,555,520","652,701,486",48.2
...,...,...,...,...,...,...,...,...
811,201806,부산광역시,해운대구,산업용,941,"21,108,123","2,517,177,681",119.3
812,201806,부산광역시,해운대구,심 야,944,"2,112,204","130,465,817",61.8
813,201806,부산광역시,해운대구,일반용,"14,207","71,164,046","9,631,482,171",135.3
814,201806,부산광역시,해운대구,주택용,"72,360","50,380,488","5,464,262,154",108.5
815,201806,부산광역시,해운대구,합계,"93,613","149,035,761","18,227,539,943",122.3

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,부산광역시,전체(시 / 군 / 구),주택용,"952,240","425,745,586","48,665,579,089",114.3
4,201801,부산광역시,전체(시 / 군 / 구),일반용,"186,765","627,811,751","84,094,226,460",133.9
5,201801,부산광역시,전체(시 / 군 / 구),교육용,"1,175","49,161,289","5,194,079,994",105.7
6,201801,부산광역시,전체(시 / 군 / 구),산업용,"25,079","785,788,309","98,237,620,503",125.0
7,201801,부산광역시,전체(시 / 군 / 구),농사용,"10,947","13,555,520","652,701,486",48.2
8,201801,부산광역시,전체(시 / 군 / 구),가로등,"81,745","17,376,799","1,835,613,707",105.6
9,201801,부산광역시,전체(시 / 군 / 구),심 야,"21,863","47,249,542","3,582,358,536",75.8
10,201802,부산광역시,전체(시 / 군 / 구),주택용,"953,102","431,682,483","49,779,686,076",115.3
11,201802,부산광역시,전체(시 / 군 / 구),일반용,"186,786","630,554,645","84,133,378,676",133.4
12,201802,부산광역시,전체(시 / 군 / 구),교육용,"1,176","50,773,962","5,326,133,576",104.9
13,201802,부산광역시,전체(시 / 군 / 구),산업용,"25,091","705,827,864","89,817,127,080",127.3
14,201802,부산광역시,전체(시 / 군 / 구),농사용,"10,970","14,573,427","697,571,960",47.9
15,201802,부산광역시,전체(시 / 군 / 구),가로등,"81,959","16,402,038","1,792,013,131",109.3
16,201802,부산광역시,전체(시 / 군 / 구),심 야,"21,793","49,056,992","3,715,943,607",75.7
17,201803,부산광역시,전체(시 / 군 / 구),주택용,"953,326","369,304,248","37,935,533,084",102.7
18,201803,부산광역시,전체(시 / 군 / 구),일반용,"186,634","513,456,866","64,239,756,428",125.1
19,201803,부산광역시,전체(시 / 군 / 구),교육용,"1,174","41,051,386","4,217,693,042",102.7
20,201803,부산광역시,전체(시 / 군 / 구),산업용,"25,082","727,439,750","77,048,490,249",105.9
21,201803,부산광역시,전체(시 / 군 / 구),농사용,"11,116","10,301,406","510,091,490",49.5
22,201803,부산광역시,전체(시 / 군 / 구),가로등,"82,079","16,159,891","1,767,396,436",109.4
23,201803,부산광역시,전체(시 / 군 / 구),심 야,"21,702","36,408,397","2,419,878,029",66.5
24,201804,부산광역시,전체(시 / 군 / 구),주택용,"954,391","380,517,071","39,669,346,060",104.3
25,201804,부산광역시,전체(시 / 군 / 구),일반용,"186,597","493,412,027","57,539,159,178",116.6
26,201804,부산광역시,전체(시 / 군 / 구),교육용,"1,173","37,751,043","3,573,265,306",94.7
27,201804,부산광역시,전체(시 / 군 / 구),산업용,"25,110","712,849,930","73,973,575,311",103.8
28,201804,부산광역시,전체(시 / 군 / 구),농사용,"11,063","8,518,252","431,874,834",50.7
29,201804,부산광역시,전체(시 / 군 / 구),가로등,"82,226","14,752,388","1,670,296,234",113.2
30,201804,부산광역시,전체(시 / 군 / 구),심 야,"21,613","27,304,772","1,525,451,683",55.9
31,201805,부산광역시,전체(시 / 군 / 구),주택용,"954,769","354,429,747","35,231,041,713",99.4
32,201805,부산광역시,전체(시 / 군 / 구),일반용,"186,602","470,331,290","55,737,733,463",118.5
33,201805,부산광역시,전체(시 / 군 / 구),교육용,"1,166","30,943,632","2,888,853,412",93.4
34,201805,부산광역시,전체(시 / 군 / 구),산업용,"25,117","698,614,414","72,292,296,171",103.5
35,201805,부산광역시,전체(시 / 군 / 구),농사용,"11,074","7,633,921","391,649,203",51.3
36,201805,부산광역시,전체(시 / 군 / 구),가로등,"82,337","13,919,049","1,611,152,964",115.8
37,201805,부산광역시,전체(시 / 군 / 구),심 야,"21,501","18,849,941","1,078,697,144",57.2
38,201806,부산광역시,전체(시 / 군 / 구),주택용,"954,704","361,222,257","36,484,312,871",101.0
39,201806,부산광역시,전체(시 / 군 / 구),일반용,"186,664","512,500,167","68,879,042,288",134.4
40,201806,부산광역시,전체(시 / 군 / 구),교육용,"1,165","34,045,017","3,818,620,435",112.2
41,201806,부산광역시,전체(시 / 군 / 구),산업용,"25,110","703,573,092","86,916,015,510",123.5
42,201806,부산광역시,전체(시 / 군 / 구),농사용,"11,094","7,493,390","385,906,049",51.5
43,201806,부산광역시,전체(시 / 군 / 구),가로등,"82,442","13,178,557","1,561,379,876",118.5
44,201806,부산광역시,전체(시 / 군 / 구),심 야,"21,360","15,141,773","908,232,479",60.0
45,합계,합계,합계,합계,"7,689,082","10,496,663,881","1,212,230,774,823",115.5

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_2380\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201801  부산광역시  일반용  186,765   627,811,751
11  201802  부산광역시  일반용  186,786   630,554,645
18  201803  부산광역시  일반용  186,634   513,456,866
25  201804  부산광역시  일반용  186,597   493,412,027
32  201805  부산광역시  일반용  186,602   470,331,290
39  201806  부산광역시  일반용  186,664   512,500,167

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201801  부산광역시   강서구  일반용   9,359   41,639,568
181  201802  부산광역시   강서구  일반용   9,331   41,975,525
309  201803  부산광역시   강서구  일반용   9,337   36,844,996
437  201804  부산광역시   강서구  일반용   9,352   35,764,007
565  201805  부산광역시   강서구  일반용   9,403   34,401,591
..      ...    ...   ...  ...      ...          ...
301  201802  부산광역시  해운대구  일반용  14,169   80,201,445
429  201803  부산광역시  해운대구  일반용  14,185   68,946,105
557  201804  부산광역시  해운대구  일반용  14,191   65,667,818
685  201805  부산광역시  해운대구  일반용  14,193   65,433,819
813  201806  부산광역시  해운대구  일반용  14,207   71,164,046

[96 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'부산광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강서구',
 '금정구',
 '기장군',
 '남구',
 '동구',
 '동래구',
 '부산진구',
 '북구',
 '사상구',
 '사하구',
 '서구',
 '수영구',
 '연제구',
 '영도구',
 '중구',
 '해운대구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
55   201801  부산광역시   강서구   합계  51,180   360,096,653
183  201802  부산광역시   강서구   합계  51,487   330,240,057
311  201803  부산광역시   강서구   합계  51,631   329,820,268
439  201804  부산광역시   강서구   합계  51,752   322,419,323
567  201805  부산광역시   강서구   합계  51,874   321,052,312
..      ...    ...   ...  ...      ...           ...
303  201802  부산광역시  해운대구   합계  93,600   167,584,922
431  201803  부산광역시  해운대구   합계  93,616   148,310,733
559  201804  부산광역시  해운대구   합계  93,692   145,720,525
687  201805  부산광역시  해운대구   합계  93,665   140,587,025
815  201806  부산광역시  해운대구   합계  93,613   149,035,761

[96 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[360096653, 330240057, 329820268, 322419323, 321052312, 335179709]
[106990956, 107885708, 90298037, 88834522, 82455532, 86180915]
[112918128, 108881187, 101202107, 107450156, 98006079, 89654207]
[129791595, 128390687, 116299134, 114904821, 110931502, 113060863]
[51002949, 50847688, 42442404, 40507728, 37663006, 39381300]
[90356237, 91036514, 75754699, 74146266, 68825329, 71900070]
[164151471, 162386861, 138008042, 133612911, 126722350, 134242056]
[84365583, 85576557, 70614044, 70501456, 65346713, 69128453]
[167825738, 166294216, 143628174, 144119245, 134731680, 138854919]
[256394343, 231201340, 230905260, 212639230, 203907140, 205981445]
[54298300, 51287537, 46988250, 44956451, 42117523, 44076304]
[56685298, 58141784, 47222173, 46437952, 42660490, 44782099]
[73257698, 73418819, 61280398, 60007408, 56373510, 59615467]
[46244442, 46098111, 38901998, 38060965, 34769169, 35162066]
[39373103, 39599423, 32446223, 30786524, 28572634, 30918619]
[172936302, 167584922, 148310733, 145720525, 140587025, 149035761]
부산광역시 지역별 합계 :  [1998808322, 562645670, 618111864, 713378602, 261845075, 472019115, 859123691, 445532806, 895453972, 1341028758, 283724365, 295929796, 383953300, 239236751, 201696526, 924175268]
부산광역시 고객호수 평균:  [8608, 18461, 8938, 17209, 8937, 15772, 23728, 12916, 13771, 19322, 10125, 12461, 11787, 9678, 6266, 15599]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0           201801  부산광역시   강서구   합계  51,180   360,096,653
1           201802  부산광역시   강서구   합계  51,487   330,240,057
2           201803  부산광역시   강서구   합계  51,631   329,820,268
3           201804  부산광역시   강서구   합계  51,752   322,419,323
4           201805  부산광역시   강서구   합계  51,874   321,052,312
..             ...    ...   ...  ...      ...           ...
107  201801-201806  부산광역시   수영구   합계    12461     295929796
108  201801-201806  부산광역시   연제구   합계    11787     383953300
109  201801-201806  부산광역시   영도구   합계     9678     239236751
110  201801-201806  부산광역시    중구   합계     6266     201696526
111  201801-201806  부산광역시  해운대구   합계    15599     924175268

[112 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201801-201806']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201801-201806  부산광역시   강서구   합계    8608  1998808322
97   201801-201806  부산광역시   금정구   합계   18461   562645670
98   201801-201806  부산광역시   기장군   합계    8938   618111864
99   201801-201806  부산광역시    남구   합계   17209   713378602
100  201801-201806  부산광역시    동구   합계    8937   261845075
101  201801-201806  부산광역시   동래구   합계   15772   472019115
102  201801-201806  부산광역시  부산진구   합계   23728   859123691
103  201801-201806  부산광역시    북구   합계   12916   445532806
104  201801-201806  부산광역시   사상구   합계   13771   895453972
105  201801-201806  부산광역시   사하구   합계   19322  1341028758
106  201801-201806  부산광역시    서구   합계   10125   283724365
107  201801-201806  부산광역시   수영구   합계   12461   295929796
108  201801-201806  부산광역시   연제구   합계   11787   383953300
109  201801-201806  부산광역시   영도구   합계    9678   239236751
110  201801-201806  부산광역시    중구   합계    6266   201696526
111  201801-201806  부산광역시  해운대구   합계   15599   924175268

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201801  부산광역시   강서구  일반용   9,359   41,639,568
181  201802  부산광역시   강서구  일반용   9,331   41,975,525
309  201803  부산광역시   강서구  일반용   9,337   36,844,996
437  201804  부산광역시   강서구  일반용   9,352   35,764,007
565  201805  부산광역시   강서구  일반용   9,403   34,401,591
..      ...    ...   ...  ...      ...          ...
301  201802  부산광역시  해운대구  일반용  14,169   80,201,445
429  201803  부산광역시  해운대구  일반용  14,185   68,946,105
557  201804  부산광역시  해운대구  일반용  14,191   65,667,818
685  201805  부산광역시  해운대구  일반용  14,193   65,433,819
813  201806  부산광역시  해운대구  일반용  14,207   71,164,046

[96 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[41639568, 41975525, 36844996, 35764007, 34401591, 36587019]
[38494072, 39380085, 31221203, 30262145, 28246970, 30585633]
[29549420, 29896154, 23427073, 23192827, 22362359, 23720054]
[37003233, 38118857, 30834505, 29862316, 28734291, 31141242]
[28669405, 28674055, 23251141, 21952526, 20855589, 22576968]
[42236593, 42455091, 33848107, 32386912, 30466121, 33610369]
[78135440, 79025108, 63955919, 61206682, 58815261, 65147930]
[33114663, 33746288, 26337895, 25408911, 23826885, 26444994]
[41647868, 42096954, 33375672, 31814606, 29892298, 32586940]
[40178943, 41313143, 32465964, 31932163, 29822480, 32504477]
[21663218, 21204872, 18230170, 17387236, 16466761, 17696474]
[28905957, 29659339, 23449509, 22590557, 20868993, 22740451]
[37528019, 37463108, 30340115, 28765084, 27140056, 29927110]
[14337907, 14641806, 11758074, 11446538, 10533430, 11220426]
[30772892, 30702815, 25170418, 23771699, 22464386, 24846034]
[83934553, 80201445, 68946105, 65667818, 65433819, 71164046]
부산광역시 지역별 일반용 합계 :  [227212706, 198190108, 152147887, 195694444, 145979684, 215003193, 406286340, 168879636, 211414338, 208217170, 112648731, 148214806, 191163492, 73938181, 157728244, 435347786]
부산광역시 고객호수 평균:  [9366, 15563, 7935, 11928, 7413, 15686, 23023, 10591, 13239, 14426, 6413, 10690, 11219, 6072, 8928, 14178]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2380\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분 고객호수(호)     사용량(kWh)
0           201801  부산광역시   강서구  일반용  9,359   41,639,568
1           201802  부산광역시   강서구  일반용  9,331   41,975,525
2           201803  부산광역시   강서구  일반용  9,337   36,844,996
3           201804  부산광역시   강서구  일반용  9,352   35,764,007
4           201805  부산광역시   강서구  일반용  9,403   34,401,591
..             ...    ...   ...  ...     ...          ...
107  201801-201806  부산광역시   수영구  일반용   10690    148214806
108  201801-201806  부산광역시   연제구  일반용   11219    191163492
109  201801-201806  부산광역시   영도구  일반용    6072     73938181
110  201801-201806  부산광역시    중구  일반용    8928    157728244
111  201801-201806  부산광역시  해운대구  일반용   14178    435347786

[112 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201801-201806']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)   사용량(kWh)
96   201801-201806  부산광역시   강서구  일반용    9366  227212706
97   201801-201806  부산광역시   금정구  일반용   15563  198190108
98   201801-201806  부산광역시   기장군  일반용    7935  152147887
99   201801-201806  부산광역시    남구  일반용   11928  195694444
100  201801-201806  부산광역시    동구  일반용    7413  145979684
101  201801-201806  부산광역시   동래구  일반용   15686  215003193
102  201801-201806  부산광역시  부산진구  일반용   23023  406286340
103  201801-201806  부산광역시    북구  일반용   10591  168879636
104  201801-201806  부산광역시   사상구  일반용   13239  211414338
105  201801-201806  부산광역시   사하구  일반용   14426  208217170
106  201801-201806  부산광역시    서구  일반용    6413  112648731
107  201801-201806  부산광역시   수영구  일반용   10690  148214806
108  201801-201806  부산광역시   연제구  일반용   11219  191163492
109  201801-201806  부산광역시   영도구  일반용    6072   73938181
110  201801-201806  부산광역시    중구  일반용    8928  157728244
111  201801-201806  부산광역시  해운대구  일반용   14178  435347786

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201801-201806  부산광역시   강서구  일반용    9366   227212706
96   201801-201806  부산광역시   강서구   합계    8608  1998808322
97   201801-201806  부산광역시   금정구   합계   18461   562645670
97   201801-201806  부산광역시   금정구  일반용   15563   198190108
98   201801-201806  부산광역시   기장군   합계    8938   618111864
98   201801-201806  부산광역시   기장군  일반용    7935   152147887
99   201801-201806  부산광역시    남구  일반용   11928   195694444
99   201801-201806  부산광역시    남구   합계   17209   713378602
100  201801-201806  부산광역시    동구  일반용    7413   145979684
100  201801-201806  부산광역시    동구   합계    8937   261845075
101  201801-201806  부산광역시   동래구  일반용   15686   215003193
101  201801-201806  부산광역시   동래구   합계   15772   472019115
102  201801-201806  부산광역시  부산진구  일반용   23023   406286340
102  201801-201806  부산광역시  부산진구   합계   23728   859123691
103  201801-201806  부산광역시    북구  일반용   10591   168879636
103  201801-201806  부산광역시    북구   합계   12916   445532806
104  201801-201806  부산광역시   사상구   합계   13771   895453972
104  201801-201806  부산광역시   사상구  일반용   13239   211414338
105  201801-201806  부산광역시   사하구   합계   19322  1341028758
105  201801-201806  부산광역시   사하구  일반용   14426   208217170
106  201801-201806  부산광역시    서구  일반용    6413   112648731
106  201801-201806  부산광역시    서구   합계   10125   283724365
107  201801-201806  부산광역시   수영구   합계   12461   295929796
107  201801-201806  부산광역시   수영구  일반용   10690   148214806
108  201801-201806  부산광역시   연제구   합계   11787   383953300
108  201801-201806  부산광역시   연제구  일반용   11219   191163492
109  201801-201806  부산광역시   영도구   합계    9678   239236751
109  201801-201806  부산광역시   영도구  일반용    6072    73938181
110  201801-201806  부산광역시    중구   합계    6266   201696526
110  201801-201806  부산광역시    중구  일반용    8928   157728244
111  201801-201806  부산광역시  해운대구  일반용   14178   435347786
111  201801-201806  부산광역시  해운대구   합계   15599   924175268

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[227212706,
 198190108,
 152147887,
 195694444,
 145979684,
 215003193,
 406286340,
 168879636,
 211414338,
 208217170,
 112648731,
 148214806,
 191163492,
 73938181,
 157728244,
 435347786]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1998808322,
 562645670,
 618111864,
 713378602,
 261845075,
 472019115,
 859123691,
 445532806,
 895453972,
 1341028758,
 283724365,
 295929796,
 383953300,
 239236751,
 201696526,
 924175268]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[11.37, 35.22, 24.61, 27.43, 55.75, 45.55, 47.29, 37.91, 23.61, 15.53, 39.7, 50.08, 49.79, 30.91, 78.2, 47.11]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    11
1    35
2    25
3    27
4    56
5    46
6    47
7    38
8    24
9    16
10   40
11   50
12   50
13   31
14   78
15   47
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강서구  일반용  11
1    금정구  일반용  35
2    기장군  일반용  25
3     남구  일반용  27
4     동구  일반용  56
5    동래구  일반용  46
6   부산진구  일반용  47
7     북구  일반용  38
8    사상구  일반용  24
9    사하구  일반용  16
10    서구  일반용  40
11   수영구  일반용  50
12   연제구  일반용  50
13   영도구  일반용  31
14    중구  일반용  78
15  해운대구  일반용  47

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201801-201806  부산광역시   강서구  일반용    9366   227212706  11
1   201801-201806  부산광역시   강서구   합계    8608  1998808322 NaN
3   201801-201806  부산광역시   금정구  일반용   15563   198190108  35
2   201801-201806  부산광역시   금정구   합계   18461   562645670 NaN
5   201801-201806  부산광역시   기장군  일반용    7935   152147887  25
4   201801-201806  부산광역시   기장군   합계    8938   618111864 NaN
6   201801-201806  부산광역시    남구  일반용   11928   195694444  27
7   201801-201806  부산광역시    남구   합계   17209   713378602 NaN
8   201801-201806  부산광역시    동구  일반용    7413   145979684  56
9   201801-201806  부산광역시    동구   합계    8937   261845075 NaN
10  201801-201806  부산광역시   동래구  일반용   15686   215003193  46
11  201801-201806  부산광역시   동래구   합계   15772   472019115 NaN
12  201801-201806  부산광역시  부산진구  일반용   23023   406286340  47
13  201801-201806  부산광역시  부산진구   합계   23728   859123691 NaN
14  201801-201806  부산광역시    북구  일반용   10591   168879636  38
15  201801-201806  부산광역시    북구   합계   12916   445532806 NaN
17  201801-201806  부산광역시   사상구  일반용   13239   211414338  24
16  201801-201806  부산광역시   사상구   합계   13771   895453972 NaN
19  201801-201806  부산광역시   사하구  일반용   14426   208217170  16
18  201801-201806  부산광역시   사하구   합계   19322  1341028758 NaN
20  201801-201806  부산광역시    서구  일반용    6413   112648731  40
21  201801-201806  부산광역시    서구   합계   10125   283724365 NaN
23  201801-201806  부산광역시   수영구  일반용   10690   148214806  50
22  201801-201806  부산광역시   수영구   합계   12461   295929796 NaN
25  201801-201806  부산광역시   연제구  일반용   11219   191163492  50
24  201801-201806  부산광역시   연제구   합계   11787   383953300 NaN
27  201801-201806  부산광역시   영도구  일반용    6072    73938181  31
26  201801-201806  부산광역시   영도구   합계    9678   239236751 NaN
29  201801-201806  부산광역시    중구  일반용    8928   157728244  78
28  201801-201806  부산광역시    중구   합계    6266   201696526 NaN
30  201801-201806  부산광역시  해운대구  일반용   14178   435347786  47
31  201801-201806  부산광역시  해운대구   합계   15599   924175268 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1801-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)