In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별_전력사용량_월별_17하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2017년 07 월 ~ 2017년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,인천광역시,전체(시 / 군 / 구),주택용,"738,891","345,336,197","39,507,387,224",114.4
4,201707,인천광역시,전체(시 / 군 / 구),일반용,"133,402","518,859,712","73,906,693,817",142.4
...,...,...,...,...,...,...,...,...
523,201712,인천광역시,중구,산업용,549,"74,929,247","8,798,545,538",117.4
524,201712,인천광역시,중구,심 야,"1,362","3,465,219","268,842,909",77.6
525,201712,인천광역시,중구,일반용,"10,498","95,023,520","11,691,155,877",123
526,201712,인천광역시,중구,주택용,"36,590","14,510,416","1,590,955,147",109.6
527,201712,인천광역시,중구,합계,"53,968","194,347,890","22,963,244,649",118.2

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,인천광역시,전체(시 / 군 / 구),주택용,"738,891","345,336,197","39,507,387,224",114.4
4,201707,인천광역시,전체(시 / 군 / 구),일반용,"133,402","518,859,712","73,906,693,817",142.4
5,201707,인천광역시,전체(시 / 군 / 구),교육용,"1,010","30,292,766","3,632,464,013",119.9
6,201707,인천광역시,전체(시 / 군 / 구),산업용,"18,893","1,189,898,690","145,809,921,742",122.5
...,...,...,...,...,...,...,...,...
523,201712,인천광역시,중구,산업용,549,"74,929,247","8,798,545,538",117.4
524,201712,인천광역시,중구,심 야,"1,362","3,465,219","268,842,909",77.6
525,201712,인천광역시,중구,일반용,"10,498","95,023,520","11,691,155,877",123
526,201712,인천광역시,중구,주택용,"36,590","14,510,416","1,590,955,147",109.6
527,201712,인천광역시,중구,합계,"53,968","194,347,890","22,963,244,649",118.2

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,인천광역시,전체(시 / 군 / 구),주택용,"738,891","345,336,197","39,507,387,224",114.4
4,201707,인천광역시,전체(시 / 군 / 구),일반용,"133,402","518,859,712","73,906,693,817",142.4
5,201707,인천광역시,전체(시 / 군 / 구),교육용,"1,010","30,292,766","3,632,464,013",119.9
6,201707,인천광역시,전체(시 / 군 / 구),산업용,"18,893","1,189,898,690","145,809,921,742",122.5
7,201707,인천광역시,전체(시 / 군 / 구),농사용,"22,911","11,328,988","541,098,930",47.8
...,...,...,...,...,...,...,...,...
523,201712,인천광역시,중구,산업용,549,"74,929,247","8,798,545,538",117.4
524,201712,인천광역시,중구,심 야,"1,362","3,465,219","268,842,909",77.6
525,201712,인천광역시,중구,일반용,"10,498","95,023,520","11,691,155,877",123
526,201712,인천광역시,중구,주택용,"36,590","14,510,416","1,590,955,147",109.6
527,201712,인천광역시,중구,합계,"53,968","194,347,890","22,963,244,649",118.2

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,인천광역시,전체(시 / 군 / 구),주택용,"738,891","345,336,197","39,507,387,224",114.4
4,201707,인천광역시,전체(시 / 군 / 구),일반용,"133,402","518,859,712","73,906,693,817",142.4
5,201707,인천광역시,전체(시 / 군 / 구),교육용,"1,010","30,292,766","3,632,464,013",119.9
6,201707,인천광역시,전체(시 / 군 / 구),산업용,"18,893","1,189,898,690","145,809,921,742",122.5
7,201707,인천광역시,전체(시 / 군 / 구),농사용,"22,911","11,328,988","541,098,930",47.8
8,201707,인천광역시,전체(시 / 군 / 구),가로등,"58,739","11,625,092","1,460,761,564",125.7
9,201707,인천광역시,전체(시 / 군 / 구),심 야,"16,841","10,308,387","651,220,020",63.2
10,201708,인천광역시,전체(시 / 군 / 구),주택용,"739,878","418,798,229","54,661,094,322",130.5
11,201708,인천광역시,전체(시 / 군 / 구),일반용,"133,600","574,796,285","80,300,869,668",139.7
12,201708,인천광역시,전체(시 / 군 / 구),교육용,"1,012","27,987,230","3,487,909,665",124.6
13,201708,인천광역시,전체(시 / 군 / 구),산업용,"18,911","1,169,018,895","143,498,145,681",122.8
14,201708,인천광역시,전체(시 / 군 / 구),농사용,"23,007","13,926,412","662,156,377",47.5
15,201708,인천광역시,전체(시 / 군 / 구),가로등,"61,976","12,122,100","1,482,584,313",122.3
16,201708,인천광역시,전체(시 / 군 / 구),심 야,"16,755","9,314,813","589,440,022",63.3
17,201709,인천광역시,전체(시 / 군 / 구),주택용,"741,480","333,842,970","36,250,813,306",108.6
18,201709,인천광역시,전체(시 / 군 / 구),일반용,"133,662","493,647,443","61,025,642,409",123.6
19,201709,인천광역시,전체(시 / 군 / 구),교육용,"1,015","26,424,910","2,955,314,823",111.8
20,201709,인천광역시,전체(시 / 군 / 구),산업용,"18,929","1,152,396,098","116,527,963,505",101.1
21,201709,인천광역시,전체(시 / 군 / 구),농사용,"23,103","14,643,078","704,208,154",48.1
22,201709,인천광역시,전체(시 / 군 / 구),가로등,"62,073","13,471,229","1,582,892,328",117.5
23,201709,인천광역시,전체(시 / 군 / 구),심 야,"16,704","8,708,249","523,280,991",60.1
24,201710,인천광역시,전체(시 / 군 / 구),주택용,"742,290","295,911,405","29,599,432,992",100.0
25,201710,인천광역시,전체(시 / 군 / 구),일반용,"133,581","412,393,331","47,098,127,244",114.2
26,201710,인천광역시,전체(시 / 군 / 구),교육용,"1,015","19,179,225","1,504,950,027",78.5
27,201710,인천광역시,전체(시 / 군 / 구),산업용,"18,943","1,057,598,786","102,692,586,064",97.1
28,201710,인천광역시,전체(시 / 군 / 구),농사용,"23,194","11,498,149","582,514,856",50.7
29,201710,인천광역시,전체(시 / 군 / 구),가로등,"62,145","14,537,128","1,642,193,679",113.0
30,201710,인천광역시,전체(시 / 군 / 구),심 야,"16,632","9,714,563","570,097,339",58.7
31,201711,인천광역시,전체(시 / 군 / 구),주택용,"743,671","314,621,962","33,061,141,113",105.1
32,201711,인천광역시,전체(시 / 군 / 구),일반용,"133,821","429,787,494","56,893,185,773",132.4
33,201711,인천광역시,전체(시 / 군 / 구),교육용,"1,015","31,470,536","3,755,376,881",119.3
34,201711,인천광역시,전체(시 / 군 / 구),산업용,"18,984","1,149,748,823","136,657,768,897",118.9
35,201711,인천광역시,전체(시 / 군 / 구),농사용,"31,008","19,210,201","752,923,119",39.2
36,201711,인천광역시,전체(시 / 군 / 구),가로등,"62,334","15,930,278","1,748,301,842",109.7
37,201711,인천광역시,전체(시 / 군 / 구),심 야,"16,560","19,006,818","1,251,422,899",65.8
38,201712,인천광역시,전체(시 / 군 / 구),주택용,"744,457","341,336,366","37,636,553,549",110.3
39,201712,인천광역시,전체(시 / 군 / 구),일반용,"134,396","535,048,465","71,339,808,538",133.3
40,201712,인천광역시,전체(시 / 군 / 구),교육용,"1,015","48,167,948","4,445,172,461",92.3
41,201712,인천광역시,전체(시 / 군 / 구),산업용,"19,016","1,221,386,538","144,655,932,118",118.4
42,201712,인천광역시,전체(시 / 군 / 구),농사용,"27,756","16,652,229","697,516,726",41.9
43,201712,인천광역시,전체(시 / 군 / 구),가로등,"62,501","17,007,618","1,826,987,802",107.4
44,201712,인천광역시,전체(시 / 군 / 구),심 야,"16,504","37,293,187","2,844,719,541",76.3
45,합계,합계,합계,합계,"5,993,630","12,404,248,823","1,451,018,576,334",117

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_1944\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201707  인천광역시  일반용  133,402   518,859,712
11  201708  인천광역시  일반용  133,600   574,796,285
18  201709  인천광역시  일반용  133,662   493,647,443
25  201710  인천광역시  일반용  133,581   412,393,331
32  201711  인천광역시  일반용  133,821   429,787,494
39  201712  인천광역시  일반용  134,396   535,048,465

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53   201707  인천광역시  강화군  일반용   7,403    12,485,774
133  201708  인천광역시  강화군  일반용   7,467    15,272,191
213  201709  인천광역시  강화군  일반용   7,473    13,090,579
293  201710  인천광역시  강화군  일반용   7,492    11,225,868
373  201711  인천광역시  강화군  일반용   7,546    12,534,716
453  201712  인천광역시  강화군  일반용   7,554    16,523,943
61   201707  인천광역시  계양구  일반용  12,568    41,443,555
141  201708  인천광역시  계양구  일반용  12,581    45,818,379
221  201709  인천광역시  계양구  일반용  12,566    38,653,590
301  201710  인천광역시  계양구  일반용  12,543    31,922,817
381  201711  인천광역시  계양구  일반용  12,575    32,832,903
461  201712  인천광역시  계양구  일반용  12,612    41,619,723
69   201707  인천광역시   남구  일반용  20,904    52,687,179
149  201708  인천광역시   남구  일반용  20,928    60,672,699
229  201709  인천광역시   남구  일반용  20,964    51,787,647
309  201710  인천광역시   남구  일반용  20,933    42,586,382
389  201711  인천광역시   남구  일반용  20,928    44,262,616
469  201712  인천광역시   남구  일반용  21,021    56,863,334
77   201707  인천광역시  남동구  일반용  22,366    81,336,488
157  201708  인천광역시  남동구  일반용  22,394    91,062,462
237  201709  인천광역시  남동구  일반용  22,384    77,671,563
317  201710  인천광역시  남동구  일반용  22,419    63,727,975
397  201711  인천광역시  남동구  일반용  22,470    65,938,398
477  201712  인천광역시  남동구  일반용  22,587    83,255,080
85   201707  인천광역시   동구  일반용   3,687     9,405,070
165  201708  인천광역시   동구  일반용   3,680    10,474,077
245  201709  인천광역시   동구  일반용   3,667     8,904,317
325  201710  인천광역시   동구  일반용   3,663     7,272,968
405  201711  인천광역시   동구  일반용   3,645     8,272,306
485  201712  인천광역시   동구  일반용   3,668    10,745,874
93   201707  인천광역시  부평구  일반용  22,197    70,440,220
173  201708  인천광역시  부평구  일반용  22,177    78,530,920
253  201709  인천광역시  부평구  일반용  22,088    66,759,732
333  201710  인천광역시  부평구  일반용  22,021    54,528,802
413  201711  인천광역시  부평구  일반용  21,957    56,329,552
493  201712  인천광역시  부평구  일반용  21,995    71,236,626
101  201707  인천광역시   서구  일반용  21,459    80,422,356
181  201708  인천광역시   서구  일반용  21,528    89,747,352
261  201709  인천광역시   서구  일반용  21,644    78,020,078
341  201710  인천광역시   서구  일반용  21,672    65,428,226
421  201711  인천광역시   서구  일반용  21,769    69,894,454
501  201712  인천광역시   서구  일반용  21,940    87,272,727
109  201707  인천광역시  연수구  일반용   8,491    62,956,845
189  201708  인천광역시  연수구  일반용   8,493    67,939,052
269  201709  인천광역시  연수구  일반용   8,523    58,422,936
349  201710  인천광역시  연수구  일반용   8,509    47,996,911
429  201711  인천광역시  연수구  일반용   8,595    50,567,666
509  201712  인천광역시  연수구  일반용   8,668    63,044,297
117  201707  인천광역시  옹진군  일반용   3,845     7,404,963
197  201708  인천광역시  옹진군  일반용   3,853     9,204,485
277  201709  인천광역시  옹진군  일반용   3,837     8,139,513
357  201710  인천광역시  옹진군  일반용   3,845     7,146,005
437  201711  인천광역시  옹진군  일반용   3,847     7,438,560
517  201712  인천광역시  옹진군  일반용   3,853     9,463,341
125  201707  인천광역시   중구  일반용  10,482   100,277,262
205  201708  인천광역시   중구  일반용  10,499   106,074,668
285  201709  인천광역시   중구  일반용  10,516    92,197,488
365  201710  인천광역시   중구  일반용  10,484    80,557,377
445  201711  인천광역시   중구  일반용  10,489    81,716,323
525  201712  인천광역시   중구  일반용  10,498    95,023,520

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201707  인천광역시  강화군   합계   73,116    36,092,951
135  201708  인천광역시  강화군   합계   73,307    42,195,897
215  201709  인천광역시  강화군   합계   73,577    39,727,773
295  201710  인천광역시  강화군   합계   73,725    36,073,401
375  201711  인천광역시  강화군   합계   79,873    47,418,696
455  201712  인천광역시  강화군   합계   78,232    60,441,395
63   201707  인천광역시  계양구   합계   98,925   114,151,122
143  201708  인천광역시  계양구   합계   98,932   125,822,109
223  201709  인천광역시  계양구   합계   98,914   108,572,404
303  201710  인천광역시  계양구   합계   98,925    94,764,077
383  201711  인천광역시  계양구   합계   99,259   102,158,947
463  201712  인천광역시  계양구   합계   99,017   120,531,715
71   201707  인천광역시   남구   합계  192,528   189,782,895
151  201708  인천광역시   남구   합계  192,909   205,932,077
231  201709  인천광역시   남구   합계  193,410   185,931,289
311  201710  인천광역시   남구   합계  193,597   161,836,571
391  201711  인천광역시   남구   합계  193,946   164,424,320
471  201712  인천광역시   남구   합계  194,219   183,804,837
79   201707  인천광역시  남동구   합계  150,399   346,626,543
159  201708  인천광역시  남동구   합계  150,481   365,931,337
239  201709  인천광역시  남동구   합계  150,956   342,203,514
319  201710  인천광역시  남동구   합계  151,207   283,571,844
399  201711  인천광역시  남동구   합계  151,627   330,855,765
479  201712  인천광역시  남동구   합계  151,841   373,677,027
87   201707  인천광역시   동구   합계   23,890   346,071,146
167  201708  인천광역시   동구   합계   26,952   340,738,455
247  201709  인천광역시   동구   합계   26,971   323,827,893
327  201710  인천광역시   동구   합계   26,962   317,181,604
407  201711  인천광역시   동구   합계   26,957   319,155,774
487  201712  인천광역시   동구   합계   26,999   340,025,487
95   201707  인천광역시  부평구   합계  166,032   211,858,823
175  201708  인천광역시  부평구   합계  165,742   229,284,145
255  201709  인천광역시  부평구   합계  165,279   200,660,583
335  201710  인천광역시  부평구   합계  164,791   172,737,514
415  201711  인천광역시  부평구   합계  164,549   188,722,443
495  201712  인천광역시  부평구   합계  164,201   218,879,581
103  201707  인천광역시   서구   합계  153,263   456,609,260
183  201708  인천광역시   서구   합계  153,697   477,614,283
263  201709  인천광역시   서구   합계  154,260   455,030,899
343  201710  인천광역시   서구   합계  154,723   408,558,845
423  201711  인천광역시   서구   합계  155,348   450,956,414
503  201712  인천광역시   서구   합계  155,815   498,204,285
111  201707  인천광역시  연수구   합계   57,372   201,133,930
191  201708  인천광역시  연수구   합계   57,445   214,106,732
271  201709  인천광역시  연수구   합계   57,548   182,264,833
351  201710  인천광역시  연수구   합계   57,620   161,582,424
431  201711  인천광역시  연수구   합계   57,862   177,673,304
511  201712  인천광역시  연수구   합계   57,984   208,182,449
119  201707  인천광역시  옹진군   합계   22,667    17,074,315
199  201708  인천광역시  옹진군   합계   22,792    15,396,371
279  201709  인천광역시  옹진군   합계   22,838    14,786,469
359  201710  인천광역시  옹진군   합계   22,920    12,890,810
439  201711  인천광역시  옹진군   합계   23,914    17,858,348
519  201712  인천광역시  옹진군   합계   23,369    18,797,685
127  201707  인천광역시   중구   합계   52,495   198,248,847
207  201708  인천광역시   중구   합계   52,882   208,942,558
287  201709  인천광역시   중구   합계   53,213   190,128,320
367  201710  인천광역시   중구   합계   53,330   171,635,497
447  201711  인천광역시   중구   합계   54,058   180,552,101
527  201712  인천광역시   중구   합계   53,968   194,347,890

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[36092951, 42195897, 39727773, 36073401, 47418696, 60441395]
[114151122, 125822109, 108572404, 94764077, 102158947, 120531715]
[189782895, 205932077, 185931289, 161836571, 164424320, 183804837]
[346626543, 365931337, 342203514, 283571844, 330855765, 373677027]
[346071146, 340738455, 323827893, 317181604, 319155774, 340025487]
[211858823, 229284145, 200660583, 172737514, 188722443, 218879581]
[456609260, 477614283, 455030899, 408558845, 450956414, 498204285]
[201133930, 214106732, 182264833, 161582424, 177673304, 208182449]
[17074315, 15396371, 14786469, 12890810, 17858348, 18797685]
[198248847, 208942558, 190128320, 171635497, 180552101, 194347890]
인천광역시 지역별 합계 :  [261950113, 666000374, 1091711989, 2042866030, 1987000359, 1222143089, 2746973986, 1144943672, 96803998, 1143855213]
인천광역시 고객호수 평균:  [12550, 16499, 32239, 25180, 4409, 27516, 25752, 9606, 3847, 8887]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201707  인천광역시  강화군   합계  73,116   36,092,951
1          201708  인천광역시  강화군   합계  73,307   42,195,897
2          201709  인천광역시  강화군   합계  73,577   39,727,773
3          201710  인천광역시  강화군   합계  73,725   36,073,401
4          201711  인천광역시  강화군   합계  79,873   47,418,696
..            ...    ...  ...  ...      ...          ...
65  201707-201712  인천광역시  부평구   합계    27516   1222143089
66  201707-201712  인천광역시   서구   합계    25752   2746973986
67  201707-201712  인천광역시  연수구   합계     9606   1144943672
68  201707-201712  인천광역시  옹진군   합계     3847     96803998
69  201707-201712  인천광역시   중구   합계     8887   1143855213

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201707-201712']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201707-201712  인천광역시  강화군   합계   12550   261950113
61  201707-201712  인천광역시  계양구   합계   16499   666000374
62  201707-201712  인천광역시   남구   합계   32239  1091711989
63  201707-201712  인천광역시  남동구   합계   25180  2042866030
64  201707-201712  인천광역시   동구   합계    4409  1987000359
65  201707-201712  인천광역시  부평구   합계   27516  1222143089
66  201707-201712  인천광역시   서구   합계   25752  2746973986
67  201707-201712  인천광역시  연수구   합계    9606  1144943672
68  201707-201712  인천광역시  옹진군   합계    3847    96803998
69  201707-201712  인천광역시   중구   합계    8887  1143855213

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53   201707  인천광역시  강화군  일반용   7,403    12,485,774
133  201708  인천광역시  강화군  일반용   7,467    15,272,191
213  201709  인천광역시  강화군  일반용   7,473    13,090,579
293  201710  인천광역시  강화군  일반용   7,492    11,225,868
373  201711  인천광역시  강화군  일반용   7,546    12,534,716
453  201712  인천광역시  강화군  일반용   7,554    16,523,943
61   201707  인천광역시  계양구  일반용  12,568    41,443,555
141  201708  인천광역시  계양구  일반용  12,581    45,818,379
221  201709  인천광역시  계양구  일반용  12,566    38,653,590
301  201710  인천광역시  계양구  일반용  12,543    31,922,817
381  201711  인천광역시  계양구  일반용  12,575    32,832,903
461  201712  인천광역시  계양구  일반용  12,612    41,619,723
69   201707  인천광역시   남구  일반용  20,904    52,687,179
149  201708  인천광역시   남구  일반용  20,928    60,672,699
229  201709  인천광역시   남구  일반용  20,964    51,787,647
309  201710  인천광역시   남구  일반용  20,933    42,586,382
389  201711  인천광역시   남구  일반용  20,928    44,262,616
469  201712  인천광역시   남구  일반용  21,021    56,863,334
77   201707  인천광역시  남동구  일반용  22,366    81,336,488
157  201708  인천광역시  남동구  일반용  22,394    91,062,462
237  201709  인천광역시  남동구  일반용  22,384    77,671,563
317  201710  인천광역시  남동구  일반용  22,419    63,727,975
397  201711  인천광역시  남동구  일반용  22,470    65,938,398
477  201712  인천광역시  남동구  일반용  22,587    83,255,080
85   201707  인천광역시   동구  일반용   3,687     9,405,070
165  201708  인천광역시   동구  일반용   3,680    10,474,077
245  201709  인천광역시   동구  일반용   3,667     8,904,317
325  201710  인천광역시   동구  일반용   3,663     7,272,968
405  201711  인천광역시   동구  일반용   3,645     8,272,306
485  201712  인천광역시   동구  일반용   3,668    10,745,874
93   201707  인천광역시  부평구  일반용  22,197    70,440,220
173  201708  인천광역시  부평구  일반용  22,177    78,530,920
253  201709  인천광역시  부평구  일반용  22,088    66,759,732
333  201710  인천광역시  부평구  일반용  22,021    54,528,802
413  201711  인천광역시  부평구  일반용  21,957    56,329,552
493  201712  인천광역시  부평구  일반용  21,995    71,236,626
101  201707  인천광역시   서구  일반용  21,459    80,422,356
181  201708  인천광역시   서구  일반용  21,528    89,747,352
261  201709  인천광역시   서구  일반용  21,644    78,020,078
341  201710  인천광역시   서구  일반용  21,672    65,428,226
421  201711  인천광역시   서구  일반용  21,769    69,894,454
501  201712  인천광역시   서구  일반용  21,940    87,272,727
109  201707  인천광역시  연수구  일반용   8,491    62,956,845
189  201708  인천광역시  연수구  일반용   8,493    67,939,052
269  201709  인천광역시  연수구  일반용   8,523    58,422,936
349  201710  인천광역시  연수구  일반용   8,509    47,996,911
429  201711  인천광역시  연수구  일반용   8,595    50,567,666
509  201712  인천광역시  연수구  일반용   8,668    63,044,297
117  201707  인천광역시  옹진군  일반용   3,845     7,404,963
197  201708  인천광역시  옹진군  일반용   3,853     9,204,485
277  201709  인천광역시  옹진군  일반용   3,837     8,139,513
357  201710  인천광역시  옹진군  일반용   3,845     7,146,005
437  201711  인천광역시  옹진군  일반용   3,847     7,438,560
517  201712  인천광역시  옹진군  일반용   3,853     9,463,341
125  201707  인천광역시   중구  일반용  10,482   100,277,262
205  201708  인천광역시   중구  일반용  10,499   106,074,668
285  201709  인천광역시   중구  일반용  10,516    92,197,488
365  201710  인천광역시   중구  일반용  10,484    80,557,377
445  201711  인천광역시   중구  일반용  10,489    81,716,323
525  201712  인천광역시   중구  일반용  10,498    95,023,520

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[12485774, 15272191, 13090579, 11225868, 12534716, 16523943]
[41443555, 45818379, 38653590, 31922817, 32832903, 41619723]
[52687179, 60672699, 51787647, 42586382, 44262616, 56863334]
[81336488, 91062462, 77671563, 63727975, 65938398, 83255080]
[9405070, 10474077, 8904317, 7272968, 8272306, 10745874]
[70440220, 78530920, 66759732, 54528802, 56329552, 71236626]
[80422356, 89747352, 78020078, 65428226, 69894454, 87272727]
[62956845, 67939052, 58422936, 47996911, 50567666, 63044297]
[7404963, 9204485, 8139513, 7146005, 7438560, 9463341]
[100277262, 106074668, 92197488, 80557377, 81716323, 95023520]
인천광역시 지역별 일반용 합계 :  [81133071, 232290967, 308859857, 462991966, 55074612, 397825852, 470785193, 350927707, 48796867, 555846638]
인천광역시 고객호수 평균:  [7489, 12574, 20946, 22436, 3668, 22072, 21668, 8546, 3846, 10494]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1944\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201707  인천광역시  강화군  일반용  7,403   12,485,774
1          201708  인천광역시  강화군  일반용  7,467   15,272,191
2          201709  인천광역시  강화군  일반용  7,473   13,090,579
3          201710  인천광역시  강화군  일반용  7,492   11,225,868
4          201711  인천광역시  강화군  일반용  7,546   12,534,716
..            ...    ...  ...  ...     ...          ...
65  201707-201712  인천광역시  부평구  일반용   22072    397825852
66  201707-201712  인천광역시   서구  일반용   21668    470785193
67  201707-201712  인천광역시  연수구  일반용    8546    350927707
68  201707-201712  인천광역시  옹진군  일반용    3846     48796867
69  201707-201712  인천광역시   중구  일반용   10494    555846638

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201707-201712']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201707-201712  인천광역시  강화군  일반용    7489   81133071
61  201707-201712  인천광역시  계양구  일반용   12574  232290967
62  201707-201712  인천광역시   남구  일반용   20946  308859857
63  201707-201712  인천광역시  남동구  일반용   22436  462991966
64  201707-201712  인천광역시   동구  일반용    3668   55074612
65  201707-201712  인천광역시  부평구  일반용   22072  397825852
66  201707-201712  인천광역시   서구  일반용   21668  470785193
67  201707-201712  인천광역시  연수구  일반용    8546  350927707
68  201707-201712  인천광역시  옹진군  일반용    3846   48796867
69  201707-201712  인천광역시   중구  일반용   10494  555846638

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201707-201712  인천광역시  강화군  일반용    7489    81133071
60  201707-201712  인천광역시  강화군   합계   12550   261950113
61  201707-201712  인천광역시  계양구  일반용   12574   232290967
61  201707-201712  인천광역시  계양구   합계   16499   666000374
62  201707-201712  인천광역시   남구  일반용   20946   308859857
62  201707-201712  인천광역시   남구   합계   32239  1091711989
63  201707-201712  인천광역시  남동구  일반용   22436   462991966
63  201707-201712  인천광역시  남동구   합계   25180  2042866030
64  201707-201712  인천광역시   동구  일반용    3668    55074612
64  201707-201712  인천광역시   동구   합계    4409  1987000359
65  201707-201712  인천광역시  부평구  일반용   22072   397825852
65  201707-201712  인천광역시  부평구   합계   27516  1222143089
66  201707-201712  인천광역시   서구  일반용   21668   470785193
66  201707-201712  인천광역시   서구   합계   25752  2746973986
67  201707-201712  인천광역시  연수구   합계    9606  1144943672
67  201707-201712  인천광역시  연수구  일반용    8546   350927707
68  201707-201712  인천광역시  옹진군   합계    3847    96803998
68  201707-201712  인천광역시  옹진군  일반용    3846    48796867
69  201707-201712  인천광역시   중구  일반용   10494   555846638
69  201707-201712  인천광역시   중구   합계    8887  1143855213

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[81133071,
 232290967,
 308859857,
 462991966,
 55074612,
 397825852,
 470785193,
 350927707,
 48796867,
 555846638]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[261950113,
 666000374,
 1091711989,
 2042866030,
 1987000359,
 1222143089,
 2746973986,
 1144943672,
 96803998,
 1143855213]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[30.97, 34.88, 28.29, 22.66, 2.77, 32.55, 17.14, 30.65, 50.41, 48.59]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   31
1   35
2   28
3   23
4    3
5   33
6   17
7   31
8   50
9   49
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  31
1  계양구  일반용  35
2   남구  일반용  28
3  남동구  일반용  23
4   동구  일반용   3
5  부평구  일반용  33
6   서구  일반용  17
7  연수구  일반용  31
8  옹진군  일반용  50
9   중구  일반용  49

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201707-201712  인천광역시  강화군  일반용    7489    81133071  31
1   201707-201712  인천광역시  강화군   합계   12550   261950113 NaN
2   201707-201712  인천광역시  계양구  일반용   12574   232290967  35
3   201707-201712  인천광역시  계양구   합계   16499   666000374 NaN
4   201707-201712  인천광역시   남구  일반용   20946   308859857  28
5   201707-201712  인천광역시   남구   합계   32239  1091711989 NaN
6   201707-201712  인천광역시  남동구  일반용   22436   462991966  23
7   201707-201712  인천광역시  남동구   합계   25180  2042866030 NaN
8   201707-201712  인천광역시   동구  일반용    3668    55074612   3
9   201707-201712  인천광역시   동구   합계    4409  1987000359 NaN
10  201707-201712  인천광역시  부평구  일반용   22072   397825852  33
11  201707-201712  인천광역시  부평구   합계   27516  1222143089 NaN
12  201707-201712  인천광역시   서구  일반용   21668   470785193  17
13  201707-201712  인천광역시   서구   합계   25752  2746973986 NaN
15  201707-201712  인천광역시  연수구  일반용    8546   350927707  31
14  201707-201712  인천광역시  연수구   합계    9606  1144943672 NaN
17  201707-201712  인천광역시  옹진군  일반용    3846    48796867  50
16  201707-201712  인천광역시  옹진군   합계    3847    96803998 NaN
18  201707-201712  인천광역시   중구  일반용   10494   555846638  49
19  201707-201712  인천광역시   중구   합계    8887  1143855213 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1707-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)