In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('서울특별시_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 서울특별시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,서울특별시,전체(시 / 군 / 구),주택용,"2,666,056","1,208,344,479","167,976,525,984",139.0
4,201501,서울특별시,전체(시 / 군 / 구),일반용,"532,597","2,360,472,686","310,247,945,274",131.4
...,...,...,...,...,...,...,...,...
1237,201506,서울특별시,중랑구,산업용,"2,606","5,480,078","696,961,175",127.2
1238,201506,서울특별시,중랑구,심 야,606,"552,685","33,250,438",60.2
1239,201506,서울특별시,중랑구,일반용,"19,121","36,255,520","4,775,291,171",131.7
1240,201506,서울특별시,중랑구,주택용,"127,558","39,653,197","4,671,644,427",117.8
1241,201506,서울특별시,중랑구,합계,"159,849","84,426,238","10,503,623,304",124.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,서울특별시,전체(시 / 군 / 구),주택용,"2,666,056","1,208,344,479","167,976,525,984",139.0
4,201501,서울특별시,전체(시 / 군 / 구),일반용,"532,597","2,360,472,686","310,247,945,274",131.4
5,201501,서울특별시,전체(시 / 군 / 구),교육용,"2,663","173,915,642","18,506,071,885",106.4
6,201501,서울특별시,전체(시 / 군 / 구),산업용,"45,927","462,259,628","55,439,286,753",119.9
...,...,...,...,...,...,...,...,...
1237,201506,서울특별시,중랑구,산업용,"2,606","5,480,078","696,961,175",127.2
1238,201506,서울특별시,중랑구,심 야,606,"552,685","33,250,438",60.2
1239,201506,서울특별시,중랑구,일반용,"19,121","36,255,520","4,775,291,171",131.7
1240,201506,서울특별시,중랑구,주택용,"127,558","39,653,197","4,671,644,427",117.8
1241,201506,서울특별시,중랑구,합계,"159,849","84,426,238","10,503,623,304",124.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,서울특별시,전체(시 / 군 / 구),주택용,"2,666,056","1,208,344,479","167,976,525,984",139.0
4,201501,서울특별시,전체(시 / 군 / 구),일반용,"532,597","2,360,472,686","310,247,945,274",131.4
5,201501,서울특별시,전체(시 / 군 / 구),교육용,"2,663","173,915,642","18,506,071,885",106.4
6,201501,서울특별시,전체(시 / 군 / 구),산업용,"45,927","462,259,628","55,439,286,753",119.9
7,201501,서울특별시,전체(시 / 군 / 구),농사용,"1,906","1,670,429","80,668,859",48.3
...,...,...,...,...,...,...,...,...
1237,201506,서울특별시,중랑구,산업용,"2,606","5,480,078","696,961,175",127.2
1238,201506,서울특별시,중랑구,심 야,606,"552,685","33,250,438",60.2
1239,201506,서울특별시,중랑구,일반용,"19,121","36,255,520","4,775,291,171",131.7
1240,201506,서울특별시,중랑구,주택용,"127,558","39,653,197","4,671,644,427",117.8
1241,201506,서울특별시,중랑구,합계,"159,849","84,426,238","10,503,623,304",124.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,서울특별시,전체(시 / 군 / 구),주택용,"2,666,056","1,208,344,479","167,976,525,984",139.0
4,201501,서울특별시,전체(시 / 군 / 구),일반용,"532,597","2,360,472,686","310,247,945,274",131.4
5,201501,서울특별시,전체(시 / 군 / 구),교육용,"2,663","173,915,642","18,506,071,885",106.4
6,201501,서울특별시,전체(시 / 군 / 구),산업용,"45,927","462,259,628","55,439,286,753",119.9
7,201501,서울특별시,전체(시 / 군 / 구),농사용,"1,906","1,670,429","80,668,859",48.3
8,201501,서울특별시,전체(시 / 군 / 구),가로등,"176,990","35,471,366","3,655,911,036",103.1
9,201501,서울특별시,전체(시 / 군 / 구),심 야,"18,653","38,982,349","3,179,090,118",81.6
10,201502,서울특별시,전체(시 / 군 / 구),주택용,"2,668,970","1,174,628,181","159,374,612,662",135.7
11,201502,서울특별시,전체(시 / 군 / 구),일반용,"532,849","2,182,562,500","291,008,026,490",133.3
12,201502,서울특별시,전체(시 / 군 / 구),교육용,"2,664","157,314,879","17,059,416,092",108.4
13,201502,서울특별시,전체(시 / 군 / 구),산업용,"45,973","437,381,355","53,742,034,957",122.9
14,201502,서울특별시,전체(시 / 군 / 구),농사용,"1,901","1,589,073","77,630,990",48.9
15,201502,서울특별시,전체(시 / 군 / 구),가로등,"177,208","33,558,309","3,612,479,312",107.6
16,201502,서울특별시,전체(시 / 군 / 구),심 야,"18,586","36,531,696","2,976,416,056",81.5
17,201503,서울특별시,전체(시 / 군 / 구),주택용,"2,670,597","1,038,607,536","126,513,934,634",121.8
18,201503,서울특별시,전체(시 / 군 / 구),일반용,"532,210","1,945,697,613","234,755,280,679",120.7
19,201503,서울특별시,전체(시 / 군 / 구),교육용,"2,660","142,599,525","13,865,971,223",97.2
20,201503,서울특별시,전체(시 / 군 / 구),산업용,"45,981","403,283,677","43,620,913,936",108.2
21,201503,서울특별시,전체(시 / 군 / 구),농사용,"2,115","1,414,074","68,326,828",48.3
22,201503,서울특별시,전체(시 / 군 / 구),가로등,"177,326","30,415,048","3,319,705,119",109.1
23,201503,서울특별시,전체(시 / 군 / 구),심 야,"18,515","30,908,796","2,247,832,269",72.7
24,201504,서울특별시,전체(시 / 군 / 구),주택용,"2,673,448","1,073,072,340","133,187,373,646",124.1
25,201504,서울특별시,전체(시 / 군 / 구),일반용,"531,861","1,850,441,810","210,992,865,411",114.0
26,201504,서울특별시,전체(시 / 군 / 구),교육용,"2,658","127,591,033","12,039,730,531",94.4
27,201504,서울특별시,전체(시 / 군 / 구),산업용,"46,002","402,754,695","41,470,590,826",103.0
28,201504,서울특별시,전체(시 / 군 / 구),농사용,"1,919","1,335,669","65,353,096",48.9
29,201504,서울특별시,전체(시 / 군 / 구),가로등,"177,429","29,013,546","3,297,256,156",113.6
30,201504,서울특별시,전체(시 / 군 / 구),심 야,"18,436","27,821,189","1,960,113,723",70.5
31,201505,서울특별시,전체(시 / 군 / 구),주택용,"2,674,129","999,897,891","118,152,490,409",118.2
32,201505,서울특별시,전체(시 / 군 / 구),일반용,"531,477","1,775,263,322","204,296,087,934",115.1
33,201505,서울특별시,전체(시 / 군 / 구),교육용,"2,653","104,102,835","10,615,289,493",102.0
34,201505,서울특별시,전체(시 / 군 / 구),산업용,"46,117","382,777,164","41,543,324,900",108.5
35,201505,서울특별시,전체(시 / 군 / 구),농사용,"1,932","1,261,565","63,790,686",50.6
36,201505,서울특별시,전체(시 / 군 / 구),가로등,"177,393","26,770,024","3,136,236,734",117.2
37,201505,서울특별시,전체(시 / 군 / 구),심 야,"18,318","34,148,893","2,453,335,362",71.8
38,201506,서울특별시,전체(시 / 군 / 구),주택용,"2,675,704","1,041,745,162","129,971,877,981",124.8
39,201506,서울특별시,전체(시 / 군 / 구),일반용,"531,647","1,992,249,953","268,078,176,254",134.6
40,201506,서울특별시,전체(시 / 군 / 구),교육용,"2,647","121,184,385","14,429,575,956",119.1
41,201506,서울특별시,전체(시 / 군 / 구),산업용,"46,135","405,439,664","48,466,979,958",119.5
42,201506,서울특별시,전체(시 / 군 / 구),농사용,"1,943","1,343,394","68,425,465",50.9
43,201506,서울특별시,전체(시 / 군 / 구),가로등,"177,352","25,302,593","3,060,360,310",121.0
44,201506,서울특별시,전체(시 / 군 / 구),심 야,"18,213","50,105,441","3,603,177,175",71.9
45,합계,합계,합계,합계,"20,699,760","22,371,231,409","2,762,280,493,162",123.5

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_11212\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)        사용량(kWh)
4   201501  서울특별시  일반용  532,597   2,360,472,686
11  201502  서울특별시  일반용  532,849   2,182,562,500
18  201503  서울특별시  일반용  532,210   1,945,697,613
25  201504  서울특별시  일반용  531,861   1,850,441,810
32  201505  서울특별시  일반용  531,477   1,775,263,322
39  201506  서울특별시  일반용  531,647   1,992,249,953

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201501  서울특별시  강남구  일반용  48,781   329,536,155
252   201502  서울특별시  강남구  일반용  48,713   303,661,846
451   201503  서울특별시  강남구  일반용  48,641   267,826,466
650   201504  서울특별시  강남구  일반용  48,651   249,947,955
849   201505  서울특별시  강남구  일반용  48,664   237,085,256
...      ...    ...  ...  ...      ...           ...
443   201502  서울특별시  중랑구  일반용  19,197    43,125,844
642   201503  서울특별시  중랑구  일반용  19,145    36,381,420
841   201504  서울특별시  중랑구  일반용  19,135    34,825,857
1040  201505  서울특별시  중랑구  일반용  19,079    32,647,575
1239  201506  서울특별시  중랑구  일반용  19,121    36,255,520

[150 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'서울특별시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강남구',
 '강동구',
 '강북구',
 '강서구',
 '관악구',
 '광진구',
 '구로구',
 '금천구',
 '노원구',
 '도봉구',
 '동대문구',
 '동작구',
 '마포구',
 '서대문구',
 '서초구',
 '성동구',
 '성북구',
 '송파구',
 '양천구',
 '영등포구',
 '용산구',
 '은평구',
 '종로구',
 '중구',
 '중랑구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55    201501  서울특별시  강남구   합계  199,264   447,969,825
254   201502  서울특별시  강남구   합계  199,291   416,343,967
453   201503  서울특별시  강남구   합계  199,318   370,912,824
652   201504  서울특별시  강남구   합계  199,535   347,789,112
851   201505  서울특별시  강남구   합계  199,519   328,075,592
...      ...    ...  ...  ...       ...           ...
445   201502  서울특별시  중랑구   합계  159,337   100,918,511
644   201503  서울특별시  중랑구   합계  159,483    86,819,958
843   201504  서울특별시  중랑구   합계  159,676    86,184,955
1042  201505  서울특별시  중랑구   합계  159,728    79,235,738
1241  201506  서울특별시  중랑구   합계  159,849    84,426,238

[150 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[447969825, 416343967, 370912824, 347789112, 328075592, 369404491]
[142496884, 134881784, 119199254, 116472464, 109769014, 119244860]
[86975488, 82897424, 71605786, 71392984, 65194261, 69388184]
[189466857, 180502349, 158589849, 157274399, 146926306, 156534047]
[157871894, 152054373, 130309674, 130798030, 119511301, 126512854]
[147442844, 139940725, 122914901, 121741278, 117033273, 129814266]
[181183317, 169927908, 151703916, 146083487, 138253440, 151089366]
[150828894, 138937428, 128136545, 121826543, 115961266, 128416088]
[144161787, 136563497, 119619061, 118532981, 109391671, 117247767]
[85795787, 82463505, 70780230, 71442954, 65219069, 69889413]
[136735891, 123862624, 112754439, 110794027, 102241730, 111410493]
[117459160, 111413495, 98252102, 97592671, 91699142, 99406960]
[182768569, 170952447, 156243554, 151348231, 146065168, 159803958]
[112671969, 104287302, 95439885, 92116448, 87867058, 96716050]
[322365740, 304609128, 268733482, 264267705, 251430135, 280350988]
[176292811, 166651493, 150334360, 149699718, 140749406, 151122073]
[138300971, 131605801, 115850855, 114233792, 104806026, 113674864]
[235267619, 222607442, 201147197, 199643163, 196354048, 204253615]
[140272032, 134066597, 120513935, 121660043, 113646467, 119062880]
[237472766, 218825651, 204250311, 196955619, 192271258, 214941701]
[126867885, 119682879, 105197071, 102692593, 96791030, 109505028]
[122515111, 118523113, 102723419, 103640226, 95741186, 101467901]
[164453148, 152632325, 136584776, 130928045, 124357703, 142013631]
[228467884, 208414225, 194308885, 186918814, 185630406, 211672876]
[105011446, 100918511, 86819958, 86184955, 79235738, 84426238]
서울특별시 지역별 합계 :  [2280495811, 742064260, 447454127, 989293807, 817058126, 778887287, 938241434, 784106764, 745516764, 445590958, 697799204, 615823530, 967181927, 589098712, 1691757178, 934849861, 718472309, 1259273084, 749221954, 1264717306, 660736486, 644610956, 850969628, 1215413090, 542596846]
서울특별시 고객호수 평균:  [33238, 21425, 21758, 32068, 39812, 25968, 20757, 15248, 17746, 15807, 24323, 25341, 24983, 19615, 20680, 15732, 25167, 28699, 20761, 22235, 17452, 31744, 15134, 12702, 26587]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201501  서울특별시  강남구   합계  199,264   447,969,825
1           201502  서울특별시  강남구   합계  199,291   416,343,967
2           201503  서울특별시  강남구   합계  199,318   370,912,824
3           201504  서울특별시  강남구   합계  199,535   347,789,112
4           201505  서울특별시  강남구   합계  199,519   328,075,592
..             ...    ...  ...  ...       ...           ...
170  201501-201506  서울특별시  용산구   합계     17452     660736486
171  201501-201506  서울특별시  은평구   합계     31744     644610956
172  201501-201506  서울특별시  종로구   합계     15134     850969628
173  201501-201506  서울특별시   중구   합계     12702    1215413090
174  201501-201506  서울특별시  중랑구   합계     26587     542596846

[175 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201501-201506  서울특별시   강남구   합계   33238  2280495811
151  201501-201506  서울특별시   강동구   합계   21425   742064260
152  201501-201506  서울특별시   강북구   합계   21758   447454127
153  201501-201506  서울특별시   강서구   합계   32068   989293807
154  201501-201506  서울특별시   관악구   합계   39812   817058126
155  201501-201506  서울특별시   광진구   합계   25968   778887287
156  201501-201506  서울특별시   구로구   합계   20757   938241434
157  201501-201506  서울특별시   금천구   합계   15248   784106764
158  201501-201506  서울특별시   노원구   합계   17746   745516764
159  201501-201506  서울특별시   도봉구   합계   15807   445590958
160  201501-201506  서울특별시  동대문구   합계   24323   697799204
161  201501-201506  서울특별시   동작구   합계   25341   615823530
162  201501-201506  서울특별시   마포구   합계   24983   967181927
163  201501-201506  서울특별시  서대문구   합계   19615   589098712
164  201501-201506  서울특별시   서초구   합계   20680  1691757178
165  201501-201506  서울특별시   성동구   합계   15732   934849861
166  201501-201506  서울특별시   성북구   합계   25167   718472309
167  201501-201506  서울특별시   송파구   합계   28699  1259273084
168  201501-201506  서울특별시   양천구   합계   20761   749221954
169  201501-201506  서울특별시  영등포구   합계   22235  1264717306
170  201501-201506  서울특별시   용산구   합계   17452   660736486
171  201501-201506  서울특별시   은평구   합계   31744   644610956
172  201501-201506  서울특별시   종로구   합계   15134   850969628
173  201501-201506  서울특별시    중구   합계   12702  1215413090
174  201501-201506  서울특별시   중랑구   합계   26587   542596846

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201501  서울특별시  강남구  일반용  48,781   329,536,155
252   201502  서울특별시  강남구  일반용  48,713   303,661,846
451   201503  서울특별시  강남구  일반용  48,641   267,826,466
650   201504  서울특별시  강남구  일반용  48,651   249,947,955
849   201505  서울특별시  강남구  일반용  48,664   237,085,256
...      ...    ...  ...  ...      ...           ...
443   201502  서울특별시  중랑구  일반용  19,197    43,125,844
642   201503  서울특별시  중랑구  일반용  19,145    36,381,420
841   201504  서울특별시  중랑구  일반용  19,135    34,825,857
1040  201505  서울특별시  중랑구  일반용  19,079    32,647,575
1239  201506  서울특별시  중랑구  일반용  19,121    36,255,520

[150 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[329536155, 303661846, 267826466, 249947955, 237085256, 272832204]
[69397317, 64815125, 55505726, 52423165, 49928356, 56778035]
[40550431, 37818477, 32150641, 31023903, 28711100, 31888047]
[92327234, 87373891, 74312462, 71349458, 66927948, 74242772]
[70978980, 67486699, 57988835, 56999433, 53687509, 58377997]
[61276735, 56913531, 49249292, 47226360, 45860510, 51344329]
[85223686, 77358063, 70453143, 64692321, 62531166, 71095769]
[90039533, 80275847, 76456049, 70034915, 69008117, 78092650]
[59304348, 55018745, 47643897, 45164686, 42836064, 48113799]
[34398352, 32500897, 27365462, 26338039, 24344699, 27219016]
[64525565, 59663053, 51804928, 49455780, 46022482, 52012974]
[55337453, 51684015, 45134150, 43833810, 42223199, 47280125]
[110044830, 101496950, 93336744, 88196732, 85545119, 94193762]
[53983879, 49631858, 44365495, 42297146, 40694458, 45730243]
[200553726, 187223122, 164494605, 157586525, 150268757, 170717048]
[63345968, 58906453, 51585072, 48900474, 46062508, 51503512]
[53180898, 49983488, 42852440, 41167989, 38268421, 42635731]
[132529501, 123142674, 112261090, 111387294, 109661216, 112825542]
[73830932, 69953587, 63409655, 62382998, 58896586, 62441495]
[156864220, 142143347, 134008799, 126116836, 123557250, 140233163]
[73401234, 68298468, 59489763, 56353622, 54052642, 63065777]
[47090465, 44639757, 37370618, 36136047, 33394432, 36703467]
[118133726, 108137268, 97702442, 91920361, 88113897, 101708190]
[179084402, 161309495, 152548419, 144680104, 144934055, 164958786]
[45533116, 43125844, 36381420, 34825857, 32647575, 36255520]
서울특별시 지역별 일반용 합계 :  [1660889882, 348847724, 202142599, 466533765, 365519453, 311870757, 431354148, 463907111, 298081539, 172166465, 323484782, 285492752, 572814137, 276703079, 1030843783, 320303987, 268088967, 701807317, 390915253, 822923615, 374661506, 235334786, 605715884, 947515261, 228769332]
서울특별시 고객호수 평균:  [48695, 19702, 15747, 22411, 24762, 20119, 17539, 12938, 14723, 11878, 24169, 16497, 27119, 15975, 29718, 15401, 21045, 28213, 16588, 24023, 16114, 20145, 24802, 24631, 19140]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11212\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
0           201501  서울특별시  강남구  일반용  48,781   329,536,155
1           201502  서울특별시  강남구  일반용  48,713   303,661,846
2           201503  서울특별시  강남구  일반용  48,641   267,826,466
3           201504  서울특별시  강남구  일반용  48,651   249,947,955
4           201505  서울특별시  강남구  일반용  48,664   237,085,256
..             ...    ...  ...  ...      ...           ...
170  201501-201506  서울특별시  용산구  일반용    16114     374661506
171  201501-201506  서울특별시  은평구  일반용    20145     235334786
172  201501-201506  서울특별시  종로구  일반용    24802     605715884
173  201501-201506  서울특별시   중구  일반용    24631     947515261
174  201501-201506  서울특별시  중랑구  일반용    19140     228769332

[175 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201501-201506  서울특별시   강남구  일반용   48695  1660889882
151  201501-201506  서울특별시   강동구  일반용   19702   348847724
152  201501-201506  서울특별시   강북구  일반용   15747   202142599
153  201501-201506  서울특별시   강서구  일반용   22411   466533765
154  201501-201506  서울특별시   관악구  일반용   24762   365519453
155  201501-201506  서울특별시   광진구  일반용   20119   311870757
156  201501-201506  서울특별시   구로구  일반용   17539   431354148
157  201501-201506  서울특별시   금천구  일반용   12938   463907111
158  201501-201506  서울특별시   노원구  일반용   14723   298081539
159  201501-201506  서울특별시   도봉구  일반용   11878   172166465
160  201501-201506  서울특별시  동대문구  일반용   24169   323484782
161  201501-201506  서울특별시   동작구  일반용   16497   285492752
162  201501-201506  서울특별시   마포구  일반용   27119   572814137
163  201501-201506  서울특별시  서대문구  일반용   15975   276703079
164  201501-201506  서울특별시   서초구  일반용   29718  1030843783
165  201501-201506  서울특별시   성동구  일반용   15401   320303987
166  201501-201506  서울특별시   성북구  일반용   21045   268088967
167  201501-201506  서울특별시   송파구  일반용   28213   701807317
168  201501-201506  서울특별시   양천구  일반용   16588   390915253
169  201501-201506  서울특별시  영등포구  일반용   24023   822923615
170  201501-201506  서울특별시   용산구  일반용   16114   374661506
171  201501-201506  서울특별시   은평구  일반용   20145   235334786
172  201501-201506  서울특별시   종로구  일반용   24802   605715884
173  201501-201506  서울특별시    중구  일반용   24631   947515261
174  201501-201506  서울특별시   중랑구  일반용   19140   228769332

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201501-201506  서울특별시   강남구  일반용   48695  1660889882
150  201501-201506  서울특별시   강남구   합계   33238  2280495811
151  201501-201506  서울특별시   강동구   합계   21425   742064260
151  201501-201506  서울특별시   강동구  일반용   19702   348847724
152  201501-201506  서울특별시   강북구  일반용   15747   202142599
152  201501-201506  서울특별시   강북구   합계   21758   447454127
153  201501-201506  서울특별시   강서구  일반용   22411   466533765
153  201501-201506  서울특별시   강서구   합계   32068   989293807
154  201501-201506  서울특별시   관악구  일반용   24762   365519453
154  201501-201506  서울특별시   관악구   합계   39812   817058126
155  201501-201506  서울특별시   광진구  일반용   20119   311870757
155  201501-201506  서울특별시   광진구   합계   25968   778887287
156  201501-201506  서울특별시   구로구  일반용   17539   431354148
156  201501-201506  서울특별시   구로구   합계   20757   938241434
157  201501-201506  서울특별시   금천구  일반용   12938   463907111
157  201501-201506  서울특별시   금천구   합계   15248   784106764
158  201501-201506  서울특별시   노원구   합계   17746   745516764
158  201501-201506  서울특별시   노원구  일반용   14723   298081539
159  201501-201506  서울특별시   도봉구   합계   15807   445590958
159  201501-201506  서울특별시   도봉구  일반용   11878   172166465
160  201501-201506  서울특별시  동대문구   합계   24323   697799204
160  201501-201506  서울특별시  동대문구  일반용   24169   323484782
161  201501-201506  서울특별시   동작구   합계   25341   615823530
161  201501-201506  서울특별시   동작구  일반용   16497   285492752
162  201501-201506  서울특별시   마포구   합계   24983   967181927
162  201501-201506  서울특별시   마포구  일반용   27119   572814137
163  201501-201506  서울특별시  서대문구   합계   19615   589098712
163  201501-201506  서울특별시  서대문구  일반용   15975   276703079
164  201501-201506  서울특별시   서초구  일반용   29718  1030843783
164  201501-201506  서울특별시   서초구   합계   20680  1691757178
165  201501-201506  서울특별시   성동구   합계   15732   934849861
165  201501-201506  서울특별시   성동구  일반용   15401   320303987
166  201501-201506  서울특별시   성북구   합계   25167   718472309
166  201501-201506  서울특별시   성북구  일반용   21045   268088967
167  201501-201506  서울특별시   송파구   합계   28699  1259273084
167  201501-201506  서울특별시   송파구  일반용   28213   701807317
168  201501-201506  서울특별시   양천구   합계   20761   749221954
168  201501-201506  서울특별시   양천구  일반용   16588   390915253
169  201501-201506  서울특별시  영등포구  일반용   24023   822923615
169  201501-201506  서울특별시  영등포구   합계   22235  1264717306
170  201501-201506  서울특별시   용산구   합계   17452   660736486
170  201501-201506  서울특별시   용산구  일반용   16114   374661506
171  201501-201506  서울특별시   은평구   합계   31744   644610956
171  201501-201506  서울특별시   은평구  일반용   20145   235334786
172  201501-201506  서울특별시   종로구   합계   15134   850969628
172  201501-201506  서울특별시   종로구  일반용   24802   605715884
173  201501-201506  서울특별시    중구   합계   12702  1215413090
173  201501-201506  서울특별시    중구  일반용   24631   947515261
174  201501-201506  서울특별시   중랑구  일반용   19140   228769332
174  201501-201506  서울특별시   중랑구   합계   26587   542596846

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[1660889882,
 348847724,
 202142599,
 466533765,
 365519453,
 311870757,
 431354148,
 463907111,
 298081539,
 172166465,
 323484782,
 285492752,
 572814137,
 276703079,
 1030843783,
 320303987,
 268088967,
 701807317,
 390915253,
 822923615,
 374661506,
 235334786,
 605715884,
 947515261,
 228769332]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[2280495811,
 742064260,
 447454127,
 989293807,
 817058126,
 778887287,
 938241434,
 784106764,
 745516764,
 445590958,
 697799204,
 615823530,
 967181927,
 589098712,
 1691757178,
 934849861,
 718472309,
 1259273084,
 749221954,
 1264717306,
 660736486,
 644610956,
 850969628,
 1215413090,
 542596846]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[72.83, 47.01, 45.18, 47.16, 44.74, 40.04, 45.97, 59.16, 39.98, 38.64, 46.36, 46.36, 59.23, 46.97, 60.93, 34.26, 37.31, 55.73, 52.18, 65.07, 56.7, 36.51, 71.18, 77.96, 42.16]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    73
1    47
2    45
3    47
4    45
5    40
6    46
7    59
8    40
9    39
10   46
11   46
12   59
13   47
14   61
15   34
16   37
17   56
18   52
19   65
20   57
21   37
22   71
23   78
24   42
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강남구  일반용  73
1    강동구  일반용  47
2    강북구  일반용  45
3    강서구  일반용  47
4    관악구  일반용  45
5    광진구  일반용  40
6    구로구  일반용  46
7    금천구  일반용  59
8    노원구  일반용  40
9    도봉구  일반용  39
10  동대문구  일반용  46
11   동작구  일반용  46
12   마포구  일반용  59
13  서대문구  일반용  47
14   서초구  일반용  61
15   성동구  일반용  34
16   성북구  일반용  37
17   송파구  일반용  56
18   양천구  일반용  52
19  영등포구  일반용  65
20   용산구  일반용  57
21   은평구  일반용  37
22   종로구  일반용  71
23    중구  일반용  78
24   중랑구  일반용  42

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201501-201506  서울특별시   강남구  일반용   48695  1660889882  73
1   201501-201506  서울특별시   강남구   합계   33238  2280495811 NaN
3   201501-201506  서울특별시   강동구  일반용   19702   348847724  47
2   201501-201506  서울특별시   강동구   합계   21425   742064260 NaN
4   201501-201506  서울특별시   강북구  일반용   15747   202142599  45
5   201501-201506  서울특별시   강북구   합계   21758   447454127 NaN
6   201501-201506  서울특별시   강서구  일반용   22411   466533765  47
7   201501-201506  서울특별시   강서구   합계   32068   989293807 NaN
8   201501-201506  서울특별시   관악구  일반용   24762   365519453  45
9   201501-201506  서울특별시   관악구   합계   39812   817058126 NaN
10  201501-201506  서울특별시   광진구  일반용   20119   311870757  40
11  201501-201506  서울특별시   광진구   합계   25968   778887287 NaN
12  201501-201506  서울특별시   구로구  일반용   17539   431354148  46
13  201501-201506  서울특별시   구로구   합계   20757   938241434 NaN
14  201501-201506  서울특별시   금천구  일반용   12938   463907111  59
15  201501-201506  서울특별시   금천구   합계   15248   784106764 NaN
17  201501-201506  서울특별시   노원구  일반용   14723   298081539  40
16  201501-201506  서울특별시   노원구   합계   17746   745516764 NaN
19  201501-201506  서울특별시   도봉구  일반용   11878   172166465  39
18  201501-201506  서울특별시   도봉구   합계   15807   445590958 NaN
21  201501-201506  서울특별시  동대문구  일반용   24169   323484782  46
20  201501-201506  서울특별시  동대문구   합계   24323   697799204 NaN
23  201501-201506  서울특별시   동작구  일반용   16497   285492752  46
22  201501-201506  서울특별시   동작구   합계   25341   615823530 NaN
25  201501-201506  서울특별시   마포구  일반용   27119   572814137  59
24  201501-201506  서울특별시   마포구   합계   24983   967181927 NaN
27  201501-201506  서울특별시  서대문구  일반용   15975   276703079  47
26  201501-201506  서울특별시  서대문구   합계   19615   589098712 NaN
28  201501-201506  서울특별시   서초구  일반용   29718  1030843783  61
29  201501-201506  서울특별시   서초구   합계   20680  1691757178 NaN
31  201501-201506  서울특별시   성동구  일반용   15401   320303987  34
30  201501-201506  서울특별시   성동구   합계   15732   934849861 NaN
33  201501-201506  서울특별시   성북구  일반용   21045   268088967  37
32  201501-201506  서울특별시   성북구   합계   25167   718472309 NaN
35  201501-201506  서울특별시   송파구  일반용   28213   701807317  56
34  201501-201506  서울특별시   송파구   합계   28699  1259273084 NaN
37  201501-201506  서울특별시   양천구  일반용   16588   390915253  52
36  201501-201506  서울특별시   양천구   합계   20761   749221954 NaN
38  201501-201506  서울특별시  영등포구  일반용   24023   822923615  65
39  201501-201506  서울특별시  영등포구   합계   22235  1264717306 NaN
41  201501-201506  서울특별시   용산구  일반용   16114   374661506  57
40  201501-201506  서울특별시   용산구   합계   17452   660736486 NaN
43  201501-201506  서울특별시   은평구  일반용   20145   235334786  37
42  201501-201506  서울특별시   은평구   합계   31744   644610956 NaN
45  201501-201506  서울특별시   종로구  일반용   24802   605715884  71
44  201501-201506  서울특별시   종로구   합계   15134   850969628 NaN
47  201501-201506  서울특별시    중구  일반용   24631   947515261  78
46  201501-201506  서울특별시    중구   합계   12702  1215413090 NaN
48  201501-201506  서울특별시   중랑구  일반용   19140   228769332  42
49  201501-201506  서울특별시   중랑구   합계   26587   542596846 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)