In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('제주특별자치도_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 제주특별자치도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,제주특별자치도,전체(시 / 군 / 구),주택용,"220,212","64,667,522","9,213,935,159",142.5
4,201501,제주특별자치도,전체(시 / 군 / 구),일반용,"50,077","145,072,534","19,487,328,750",134.3
...,...,...,...,...,...,...,...,...
139,201506,제주특별자치도,제주시,산업용,"2,087","31,699,800","3,798,094,993",119.8
140,201506,제주특별자치도,제주시,심 야,"5,122","4,172,693","231,159,366",55.4
141,201506,제주특별자치도,제주시,일반용,"36,784","84,145,659","11,516,408,040",136.9
142,201506,제주특별자치도,제주시,주택용,"162,728","38,785,905","4,407,325,919",113.6
143,201506,제주특별자치도,제주시,합계,"234,148","201,678,282","22,531,107,395",111.7

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,제주특별자치도,전체(시 / 군 / 구),주택용,"220,212","64,667,522","9,213,935,159",142.5
4,201501,제주특별자치도,전체(시 / 군 / 구),일반용,"50,077","145,072,534","19,487,328,750",134.3
5,201501,제주특별자치도,전체(시 / 군 / 구),교육용,328,"11,267,744","1,256,416,016",111.5
6,201501,제주특별자치도,전체(시 / 군 / 구),산업용,"3,141","45,128,341","5,679,339,395",125.8
...,...,...,...,...,...,...,...,...
139,201506,제주특별자치도,제주시,산업용,"2,087","31,699,800","3,798,094,993",119.8
140,201506,제주특별자치도,제주시,심 야,"5,122","4,172,693","231,159,366",55.4
141,201506,제주특별자치도,제주시,일반용,"36,784","84,145,659","11,516,408,040",136.9
142,201506,제주특별자치도,제주시,주택용,"162,728","38,785,905","4,407,325,919",113.6
143,201506,제주특별자치도,제주시,합계,"234,148","201,678,282","22,531,107,395",111.7

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,제주특별자치도,전체(시 / 군 / 구),주택용,"220,212","64,667,522","9,213,935,159",142.5
4,201501,제주특별자치도,전체(시 / 군 / 구),일반용,"50,077","145,072,534","19,487,328,750",134.3
5,201501,제주특별자치도,전체(시 / 군 / 구),교육용,328,"11,267,744","1,256,416,016",111.5
6,201501,제주특별자치도,전체(시 / 군 / 구),산업용,"3,141","45,128,341","5,679,339,395",125.8
7,201501,제주특별자치도,전체(시 / 군 / 구),농사용,"40,786","127,807,208","5,889,671,948",46.1
...,...,...,...,...,...,...,...,...
139,201506,제주특별자치도,제주시,산업용,"2,087","31,699,800","3,798,094,993",119.8
140,201506,제주특별자치도,제주시,심 야,"5,122","4,172,693","231,159,366",55.4
141,201506,제주특별자치도,제주시,일반용,"36,784","84,145,659","11,516,408,040",136.9
142,201506,제주특별자치도,제주시,주택용,"162,728","38,785,905","4,407,325,919",113.6
143,201506,제주특별자치도,제주시,합계,"234,148","201,678,282","22,531,107,395",111.7

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,제주특별자치도,전체(시 / 군 / 구),주택용,"220,212","64,667,522","9,213,935,159",142.5
4,201501,제주특별자치도,전체(시 / 군 / 구),일반용,"50,077","145,072,534","19,487,328,750",134.3
5,201501,제주특별자치도,전체(시 / 군 / 구),교육용,328,"11,267,744","1,256,416,016",111.5
6,201501,제주특별자치도,전체(시 / 군 / 구),산업용,"3,141","45,128,341","5,679,339,395",125.8
7,201501,제주특별자치도,전체(시 / 군 / 구),농사용,"40,786","127,807,208","5,889,671,948",46.1
8,201501,제주특별자치도,전체(시 / 군 / 구),가로등,"18,695","4,861,938","492,884,744",101.4
9,201501,제주특별자치도,전체(시 / 군 / 구),심 야,"7,687","20,062,193","1,504,955,797",75.0
10,201502,제주특별자치도,전체(시 / 군 / 구),주택용,"221,536","63,786,277","8,982,087,914",140.8
11,201502,제주특별자치도,전체(시 / 군 / 구),일반용,"50,572","142,458,581","19,209,143,898",134.8
12,201502,제주특별자치도,전체(시 / 군 / 구),교육용,332,"10,485,860","1,193,854,397",113.9
13,201502,제주특별자치도,전체(시 / 군 / 구),산업용,"3,149","43,818,065","5,518,866,359",125.9
14,201502,제주특별자치도,전체(시 / 군 / 구),농사용,"40,877","136,717,283","6,252,847,744",45.7
15,201502,제주특별자치도,전체(시 / 군 / 구),가로등,"18,830","4,395,908","486,064,470",110.6
16,201502,제주특별자치도,전체(시 / 군 / 구),심 야,"7,677","20,018,029","1,500,734,239",75.0
17,201503,제주특별자치도,전체(시 / 군 / 구),주택용,"222,394","56,962,521","7,052,166,065",123.8
18,201503,제주특별자치도,전체(시 / 군 / 구),일반용,"50,555","126,748,779","15,726,912,476",124.1
19,201503,제주특별자치도,전체(시 / 군 / 구),교육용,332,"10,446,691","1,025,731,158",98.2
20,201503,제주특별자치도,전체(시 / 군 / 구),산업용,"3,162","40,904,725","4,584,966,318",112.1
21,201503,제주특별자치도,전체(시 / 군 / 구),농사용,"40,972","122,154,892","5,566,214,825",45.6
22,201503,제주특별자치도,전체(시 / 군 / 구),가로등,"18,915","4,135,894","460,339,084",111.3
23,201503,제주특별자치도,전체(시 / 군 / 구),심 야,"7,665","16,675,961","1,087,736,655",65.2
24,201504,제주특별자치도,전체(시 / 군 / 구),주택용,"223,153","58,260,165","7,367,101,974",126.5
25,201504,제주특별자치도,전체(시 / 군 / 구),일반용,"50,766","125,864,729","14,477,166,485",115.0
26,201504,제주특별자치도,전체(시 / 군 / 구),교육용,332,"9,660,524","927,011,756",96.0
27,201504,제주특별자치도,전체(시 / 군 / 구),산업용,"3,157","43,399,773","4,575,045,923",105.4
28,201504,제주특별자치도,전체(시 / 군 / 구),농사용,"41,208","126,412,713","5,667,612,419",44.8
29,201504,제주특별자치도,전체(시 / 군 / 구),가로등,"18,968","3,866,389","464,073,998",120.0
30,201504,제주특별자치도,전체(시 / 군 / 구),심 야,"7,648","13,907,731","759,849,915",54.6
31,201505,제주특별자치도,전체(시 / 군 / 구),주택용,"223,848","53,016,926","6,197,920,436",116.9
32,201505,제주특별자치도,전체(시 / 군 / 구),일반용,"50,968","118,288,533","13,989,659,335",118.3
33,201505,제주특별자치도,전체(시 / 군 / 구),교육용,332,"8,300,007","844,915,612",101.8
34,201505,제주특별자치도,전체(시 / 군 / 구),산업용,"3,082","41,396,645","4,427,657,882",107.0
35,201505,제주특별자치도,전체(시 / 군 / 구),농사용,"41,405","110,429,062","5,042,884,724",45.7
36,201505,제주특별자치도,전체(시 / 군 / 구),가로등,"19,020","3,546,359","446,002,132",125.8
37,201505,제주특별자치도,전체(시 / 군 / 구),심 야,"7,633","9,397,958","525,096,653",55.9
38,201506,제주특별자치도,전체(시 / 군 / 구),주택용,"224,683","51,917,313","5,934,733,028",114.3
39,201506,제주특별자치도,전체(시 / 군 / 구),일반용,"51,337","120,688,301","16,560,893,645",137.2
40,201506,제주특별자치도,전체(시 / 군 / 구),교육용,333,"8,376,040","1,050,316,558",125.4
41,201506,제주특별자치도,전체(시 / 군 / 구),산업용,"3,027","43,208,628","5,334,097,503",123.4
42,201506,제주특별자치도,전체(시 / 군 / 구),농사용,"41,564","99,216,103","4,637,086,652",46.7
43,201506,제주특별자치도,전체(시 / 군 / 구),가로등,"19,173","3,335,620","442,861,668",132.8
44,201506,제주특별자치도,전체(시 / 군 / 구),심 야,"7,596","6,682,133","382,743,092",57.3
45,합계,합계,합계,합계,"2,067,127","2,277,748,598","222,226,928,801",97.6

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_5536\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월       시구 계약구분  고객호수(호)      사용량(kWh)
4   201501  제주특별자치도  일반용  50,077   145,072,534
11  201502  제주특별자치도  일반용  50,572   142,458,581
18  201503  제주특별자치도  일반용  50,555   126,748,779
25  201504  제주특별자치도  일반용  50,766   125,864,729
32  201505  제주특별자치도  일반용  50,968   118,288,533
39  201506  제주특별자치도  일반용  51,337   120,688,301

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201501  제주특별자치도  서귀포시  일반용  14,155    43,404,967
69   201502  제주특별자치도  서귀포시  일반용  14,337    42,336,520
85   201503  제주특별자치도  서귀포시  일반용  14,306    38,204,420
101  201504  제주특별자치도  서귀포시  일반용  14,357    37,930,994
117  201505  제주특별자치도  서귀포시  일반용  14,386    36,231,685
133  201506  제주특별자치도  서귀포시  일반용  14,553    36,542,642
61   201501  제주특별자치도   제주시  일반용  35,922   101,667,567
77   201502  제주특별자치도   제주시  일반용  36,235   100,122,061
93   201503  제주특별자치도   제주시  일반용  36,249    88,544,359
109  201504  제주특별자치도   제주시  일반용  36,409    87,933,735
125  201505  제주특별자치도   제주시  일반용  36,582    82,056,848
141  201506  제주특별자치도   제주시  일반용  36,784    84,145,659

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'제주특별자치도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['서귀포시', '제주시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
55   201501  제주특별자치도  서귀포시   합계  110,960   171,331,428
71   201502  제주특별자치도  서귀포시   합계  111,944   177,320,026
87   201503  제주특별자치도  서귀포시   합계  112,206   158,978,928
103  201504  제주특별자치도  서귀포시   합계  112,708   160,973,350
119  201505  제주특별자치도  서귀포시   합계  112,902   142,481,923
135  201506  제주특별자치도  서귀포시   합계  113,565   131,745,856
63   201501  제주특별자치도   제주시   합계  229,966   247,536,052
79   201502  제주특별자치도   제주시   합계  231,029   244,359,977
95   201503  제주특별자치도   제주시   합계  231,789   219,050,535
111  201504  제주특별자치도   제주시   합계  232,524   220,398,674
127  201505  제주특별자치도   제주시   합계  233,386   201,893,567
143  201506  제주특별자치도   제주시   합계  234,148   201,678,282

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[171331428, 177320026, 158978928, 160973350, 142481923, 131745856]
[247536052, 244359977, 219050535, 220398674, 201893567, 201678282]
제주특별자치도 지역별 합계 :  [942831511, 1334917087]
제주특별자치도 고객호수 평균:  [18730, 38690]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_5536\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5536\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
0          201501  제주특별자치도  서귀포시   합계  110,960   171,331,428
1          201502  제주특별자치도  서귀포시   합계  111,944   177,320,026
2          201503  제주특별자치도  서귀포시   합계  112,206   158,978,928
3          201504  제주특별자치도  서귀포시   합계  112,708   160,973,350
4          201505  제주특별자치도  서귀포시   합계  112,902   142,481,923
5          201506  제주특별자치도  서귀포시   합계  113,565   131,745,856
6          201501  제주특별자치도   제주시   합계  229,966   247,536,052
7          201502  제주특별자치도   제주시   합계  231,029   244,359,977
8          201503  제주특별자치도   제주시   합계  231,789   219,050,535
9          201504  제주특별자치도   제주시   합계  232,524   220,398,674
10         201505  제주특별자치도   제주시   합계  233,386   201,893,567
11         201506  제주특별자치도   제주시   합계  234,148   201,678,282
12  201501-201506  제주특별자치도  서귀포시   합계     18730     942831511
13  201501-201506  제주특별자치도   제주시   합계     38690    1334917087

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201501-201506  제주특별자치도  서귀포시   합계   18730   942831511
13  201501-201506  제주특별자치도   제주시   합계   38690  1334917087

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201501  제주특별자치도  서귀포시  일반용  14,155    43,404,967
69   201502  제주특별자치도  서귀포시  일반용  14,337    42,336,520
85   201503  제주특별자치도  서귀포시  일반용  14,306    38,204,420
101  201504  제주특별자치도  서귀포시  일반용  14,357    37,930,994
117  201505  제주특별자치도  서귀포시  일반용  14,386    36,231,685
133  201506  제주특별자치도  서귀포시  일반용  14,553    36,542,642
61   201501  제주특별자치도   제주시  일반용  35,922   101,667,567
77   201502  제주특별자치도   제주시  일반용  36,235   100,122,061
93   201503  제주특별자치도   제주시  일반용  36,249    88,544,359
109  201504  제주특별자치도   제주시  일반용  36,409    87,933,735
125  201505  제주특별자치도   제주시  일반용  36,582    82,056,848
141  201506  제주특별자치도   제주시  일반용  36,784    84,145,659

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[43404967, 42336520, 38204420, 37930994, 36231685, 36542642]
[101667567, 100122061, 88544359, 87933735, 82056848, 84145659]
제주특별자치도 지역별 일반용 합계 :  [234651228, 544470229]
제주특별자치도 고객호수 평균:  [14349, 36363]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_5536\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5536\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0          201501  제주특별자치도  서귀포시  일반용  14,155    43,404,967
1          201502  제주특별자치도  서귀포시  일반용  14,337    42,336,520
2          201503  제주특별자치도  서귀포시  일반용  14,306    38,204,420
3          201504  제주특별자치도  서귀포시  일반용  14,357    37,930,994
4          201505  제주특별자치도  서귀포시  일반용  14,386    36,231,685
5          201506  제주특별자치도  서귀포시  일반용  14,553    36,542,642
6          201501  제주특별자치도   제주시  일반용  35,922   101,667,567
7          201502  제주특별자치도   제주시  일반용  36,235   100,122,061
8          201503  제주특별자치도   제주시  일반용  36,249    88,544,359
9          201504  제주특별자치도   제주시  일반용  36,409    87,933,735
10         201505  제주특별자치도   제주시  일반용  36,582    82,056,848
11         201506  제주특별자치도   제주시  일반용  36,784    84,145,659
12  201501-201506  제주특별자치도  서귀포시  일반용    14349     234651228
13  201501-201506  제주특별자치도   제주시  일반용    36363     544470229

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

               년월       시구   시군구 계약구분 고객호수(호)   사용량(kWh)
12  201501-201506  제주특별자치도  서귀포시  일반용   14349  234651228
13  201501-201506  제주특별자치도   제주시  일반용   36363  544470229

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201501-201506  제주특별자치도  서귀포시  일반용   14349   234651228
12  201501-201506  제주특별자치도  서귀포시   합계   18730   942831511
13  201501-201506  제주특별자치도   제주시  일반용   36363   544470229
13  201501-201506  제주특별자치도   제주시   합계   38690  1334917087

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[234651228, 544470229]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[942831511, 1334917087]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[24.89, 40.79]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   25
1   41
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0  서귀포시  일반용  25
1   제주시  일반용  41

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201501-201506  제주특별자치도  서귀포시  일반용   14349   234651228  25
1  201501-201506  제주특별자치도  서귀포시   합계   18730   942831511 NaN
2  201501-201506  제주특별자치도   제주시  일반용   36363   544470229  41
3  201501-201506  제주특별자치도   제주시   합계   38690  1334917087 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)