In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('제주특별자치도_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 제주특별자치도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,제주특별자치도,전체(시 / 군 / 구),주택용,"225,605","54,488,264","6,285,237,489",115.4
4,201507,제주특별자치도,전체(시 / 군 / 구),일반용,"51,697","130,222,278","19,716,064,880",151.4
...,...,...,...,...,...,...,...,...
139,201512,제주특별자치도,제주시,산업용,"2,211","33,437,251","4,141,428,817",123.9
140,201512,제주특별자치도,제주시,심 야,"5,089","9,687,002","724,410,132",74.8
141,201512,제주특별자치도,제주시,일반용,"39,036","92,211,776","13,031,356,638",141.3
142,201512,제주특별자치도,제주시,주택용,"166,671","45,207,370","5,786,246,567",128
143,201512,제주특별자치도,제주시,합계,"241,256","227,327,533","26,493,314,553",116.5

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,제주특별자치도,전체(시 / 군 / 구),주택용,"225,605","54,488,264","6,285,237,489",115.4
4,201507,제주특별자치도,전체(시 / 군 / 구),일반용,"51,697","130,222,278","19,716,064,880",151.4
5,201507,제주특별자치도,전체(시 / 군 / 구),교육용,334,"9,480,189","1,241,819,353",131.0
6,201507,제주특별자치도,전체(시 / 군 / 구),산업용,"3,010","44,989,767","5,926,648,985",131.7
...,...,...,...,...,...,...,...,...
139,201512,제주특별자치도,제주시,산업용,"2,211","33,437,251","4,141,428,817",123.9
140,201512,제주특별자치도,제주시,심 야,"5,089","9,687,002","724,410,132",74.8
141,201512,제주특별자치도,제주시,일반용,"39,036","92,211,776","13,031,356,638",141.3
142,201512,제주특별자치도,제주시,주택용,"166,671","45,207,370","5,786,246,567",128
143,201512,제주특별자치도,제주시,합계,"241,256","227,327,533","26,493,314,553",116.5

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,제주특별자치도,전체(시 / 군 / 구),주택용,"225,605","54,488,264","6,285,237,489",115.4
4,201507,제주특별자치도,전체(시 / 군 / 구),일반용,"51,697","130,222,278","19,716,064,880",151.4
5,201507,제주특별자치도,전체(시 / 군 / 구),교육용,334,"9,480,189","1,241,819,353",131.0
6,201507,제주특별자치도,전체(시 / 군 / 구),산업용,"3,010","44,989,767","5,926,648,985",131.7
7,201507,제주특별자치도,전체(시 / 군 / 구),농사용,"41,621","91,906,698","4,386,975,634",47.7
...,...,...,...,...,...,...,...,...
139,201512,제주특별자치도,제주시,산업용,"2,211","33,437,251","4,141,428,817",123.9
140,201512,제주특별자치도,제주시,심 야,"5,089","9,687,002","724,410,132",74.8
141,201512,제주특별자치도,제주시,일반용,"39,036","92,211,776","13,031,356,638",141.3
142,201512,제주특별자치도,제주시,주택용,"166,671","45,207,370","5,786,246,567",128
143,201512,제주특별자치도,제주시,합계,"241,256","227,327,533","26,493,314,553",116.5

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,제주특별자치도,전체(시 / 군 / 구),주택용,"225,605","54,488,264","6,285,237,489",115.4
4,201507,제주특별자치도,전체(시 / 군 / 구),일반용,"51,697","130,222,278","19,716,064,880",151.4
5,201507,제주특별자치도,전체(시 / 군 / 구),교육용,334,"9,480,189","1,241,819,353",131.0
6,201507,제주특별자치도,전체(시 / 군 / 구),산업용,"3,010","44,989,767","5,926,648,985",131.7
7,201507,제주특별자치도,전체(시 / 군 / 구),농사용,"41,621","91,906,698","4,386,975,634",47.7
8,201507,제주특별자치도,전체(시 / 군 / 구),가로등,"19,318","3,400,794","439,529,674",129.2
9,201507,제주특별자치도,전체(시 / 군 / 구),심 야,"7,581","6,276,322","370,445,782",59.0
10,201508,제주특별자치도,전체(시 / 군 / 구),주택용,"226,272","69,208,980","9,862,011,998",142.5
11,201508,제주특별자치도,전체(시 / 군 / 구),일반용,"52,028","163,347,058","23,219,356,477",142.1
12,201508,제주특별자치도,전체(시 / 군 / 구),교육용,334,"10,615,916","1,334,651,112",125.7
13,201508,제주특별자치도,전체(시 / 군 / 구),산업용,"3,023","45,901,574","5,869,374,158",127.9
14,201508,제주특별자치도,전체(시 / 군 / 구),농사용,"41,726","99,735,598","4,705,894,111",47.2
15,201508,제주특별자치도,전체(시 / 군 / 구),가로등,"19,554","3,720,123","451,766,557",121.4
16,201508,제주특별자치도,전체(시 / 군 / 구),심 야,"7,577","6,009,755","370,073,314",61.6
17,201509,제주특별자치도,전체(시 / 군 / 구),주택용,"227,102","57,720,432","6,815,408,891",118.1
18,201509,제주특별자치도,전체(시 / 군 / 구),일반용,"52,483","141,564,366","18,167,171,881",128.3
19,201509,제주특별자치도,전체(시 / 군 / 구),교육용,335,"10,329,655","1,075,265,631",104.1
20,201509,제주특별자치도,전체(시 / 군 / 구),산업용,"3,027","43,932,800","4,960,516,605",112.9
21,201509,제주특별자치도,전체(시 / 군 / 구),농사용,"41,827","98,385,558","4,571,385,671",46.5
22,201509,제주특별자치도,전체(시 / 군 / 구),가로등,"19,787","4,036,536","466,526,310",115.6
23,201509,제주특별자치도,전체(시 / 군 / 구),심 야,"7,569","4,994,817","294,035,731",58.9
24,201510,제주특별자치도,전체(시 / 군 / 구),주택용,"228,256","51,601,996","5,721,343,618",110.9
25,201510,제주특별자치도,전체(시 / 군 / 구),일반용,"53,259","122,621,327","14,437,193,155",117.7
26,201510,제주특별자치도,전체(시 / 군 / 구),교육용,334,"8,695,835","869,211,996",100.0
27,201510,제주특별자치도,전체(시 / 군 / 구),산업용,"3,055","42,953,770","4,497,611,977",104.7
28,201510,제주특별자치도,전체(시 / 군 / 구),농사용,"41,929","93,787,794","4,306,695,563",45.9
29,201510,제주특별자치도,전체(시 / 군 / 구),가로등,"19,813","4,486,635","479,005,907",106.8
30,201510,제주특별자치도,전체(시 / 군 / 구),심 야,"7,559","5,267,038","299,836,860",56.9
31,201511,제주특별자치도,전체(시 / 군 / 구),주택용,"229,414","55,378,327","6,556,344,515",118.4
32,201511,제주특별자치도,전체(시 / 군 / 구),일반용,"53,935","122,725,427","16,371,007,354",133.4
33,201511,제주특별자치도,전체(시 / 군 / 구),교육용,335,"9,074,556","1,038,214,140",114.4
34,201511,제주특별자치도,전체(시 / 군 / 구),산업용,"3,119","46,059,981","5,517,910,027",119.8
35,201511,제주특별자치도,전체(시 / 군 / 구),농사용,"42,124","99,481,131","4,620,507,780",46.4
36,201511,제주특별자치도,전체(시 / 군 / 구),가로등,"19,995","4,852,063","502,727,700",103.6
37,201511,제주특별자치도,전체(시 / 군 / 구),심 야,"7,549","8,272,376","543,310,723",65.7
38,201512,제주특별자치도,전체(시 / 군 / 구),주택용,"230,592","60,311,173","7,707,058,264",127.8
39,201512,제주특별자치도,전체(시 / 군 / 구),일반용,"54,533","133,260,587","18,825,567,503",141.3
40,201512,제주특별자치도,전체(시 / 군 / 구),교육용,336,"10,663,927","1,217,036,472",114.1
41,201512,제주특별자치도,전체(시 / 군 / 구),산업용,"3,184","45,862,072","5,833,862,352",127.2
42,201512,제주특별자치도,전체(시 / 군 / 구),농사용,"42,315","107,585,619","5,109,242,415",47.5
43,201512,제주특별자치도,전체(시 / 군 / 구),가로등,"20,141","5,112,386","508,959,753",99.6
44,201512,제주특별자치도,전체(시 / 군 / 구),심 야,"7,543","13,483,120","1,010,530,324",74.9
45,합계,합계,합계,합계,"2,121,130","2,151,804,620","226,503,338,642",105.3

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_13372\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월       시구 계약구분  고객호수(호)      사용량(kWh)
4   201507  제주특별자치도  일반용  51,697   130,222,278
11  201508  제주특별자치도  일반용  52,028   163,347,058
18  201509  제주특별자치도  일반용  52,483   141,564,366
25  201510  제주특별자치도  일반용  53,259   122,621,327
32  201511  제주특별자치도  일반용  53,935   122,725,427
39  201512  제주특별자치도  일반용  54,533   133,260,587

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201507  제주특별자치도  서귀포시  일반용  14,664    39,982,537
69   201508  제주특별자치도  서귀포시  일반용  14,772    50,207,521
85   201509  제주특별자치도  서귀포시  일반용  14,866    44,277,785
101  201510  제주특별자치도  서귀포시  일반용  15,154    38,177,748
117  201511  제주특별자치도  서귀포시  일반용  15,326    37,967,067
133  201512  제주특별자치도  서귀포시  일반용  15,497    41,048,811
61   201507  제주특별자치도   제주시  일반용  37,033    90,239,741
77   201508  제주특별자치도   제주시  일반용  37,256   113,139,537
93   201509  제주특별자치도   제주시  일반용  37,617    97,286,581
109  201510  제주특별자치도   제주시  일반용  38,105    84,443,579
125  201511  제주특별자치도   제주시  일반용  38,609    84,758,360
141  201512  제주특별자치도   제주시  일반용  39,036    92,211,776

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'제주특별자치도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['서귀포시', '제주시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
55   201507  제주특별자치도  서귀포시   합계  114,092   129,934,531
71   201508  제주특별자치도  서귀포시   합계  114,651   147,800,963
87   201509  제주특별자치도  서귀포시   합계  115,237   137,978,163
103  201510  제주특별자치도  서귀포시   합계  115,872   127,422,135
119  201511  제주특별자치도  서귀포시   합계  116,681   134,242,165
135  201512  제주특별자치도  서귀포시   합계  117,388   148,951,351
63   201507  제주특별자치도   제주시   합계  235,074   210,829,781
79   201508  제주특별자치도   제주시   합계  235,863   250,738,041
95   201509  제주특별자치도   제주시   합계  236,893   222,986,001
111  201510  제주특별자치도   제주시   합계  238,333   201,992,260
127  201511  제주특별자치도   제주시   합계  239,790   211,601,696
143  201512  제주특별자치도   제주시   합계  241,256   227,327,533

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[129934531, 147800963, 137978163, 127422135, 134242165, 148951351]
[210829781, 250738041, 222986001, 201992260, 211601696, 227327533]
제주특별자치도 지역별 합계 :  [826329308, 1325475312]
제주특별자치도 고객호수 평균:  [19275, 39644]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_13372\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13372\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
0          201507  제주특별자치도  서귀포시   합계  114,092   129,934,531
1          201508  제주특별자치도  서귀포시   합계  114,651   147,800,963
2          201509  제주특별자치도  서귀포시   합계  115,237   137,978,163
3          201510  제주특별자치도  서귀포시   합계  115,872   127,422,135
4          201511  제주특별자치도  서귀포시   합계  116,681   134,242,165
5          201512  제주특별자치도  서귀포시   합계  117,388   148,951,351
6          201507  제주특별자치도   제주시   합계  235,074   210,829,781
7          201508  제주특별자치도   제주시   합계  235,863   250,738,041
8          201509  제주특별자치도   제주시   합계  236,893   222,986,001
9          201510  제주특별자치도   제주시   합계  238,333   201,992,260
10         201511  제주특별자치도   제주시   합계  239,790   211,601,696
11         201512  제주특별자치도   제주시   합계  241,256   227,327,533
12  201507-201512  제주특별자치도  서귀포시   합계     19275     826329308
13  201507-201512  제주특별자치도   제주시   합계     39644    1325475312

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201507-201512  제주특별자치도  서귀포시   합계   19275   826329308
13  201507-201512  제주특별자치도   제주시   합계   39644  1325475312

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201507  제주특별자치도  서귀포시  일반용  14,664    39,982,537
69   201508  제주특별자치도  서귀포시  일반용  14,772    50,207,521
85   201509  제주특별자치도  서귀포시  일반용  14,866    44,277,785
101  201510  제주특별자치도  서귀포시  일반용  15,154    38,177,748
117  201511  제주특별자치도  서귀포시  일반용  15,326    37,967,067
133  201512  제주특별자치도  서귀포시  일반용  15,497    41,048,811
61   201507  제주특별자치도   제주시  일반용  37,033    90,239,741
77   201508  제주특별자치도   제주시  일반용  37,256   113,139,537
93   201509  제주특별자치도   제주시  일반용  37,617    97,286,581
109  201510  제주특별자치도   제주시  일반용  38,105    84,443,579
125  201511  제주특별자치도   제주시  일반용  38,609    84,758,360
141  201512  제주특별자치도   제주시  일반용  39,036    92,211,776

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[39982537, 50207521, 44277785, 38177748, 37967067, 41048811]
[90239741, 113139537, 97286581, 84443579, 84758360, 92211776]
제주특별자치도 지역별 일반용 합계 :  [251661469, 562079574]
제주특별자치도 고객호수 평균:  [15046, 37942]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_13372\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13372\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0          201507  제주특별자치도  서귀포시  일반용  14,664    39,982,537
1          201508  제주특별자치도  서귀포시  일반용  14,772    50,207,521
2          201509  제주특별자치도  서귀포시  일반용  14,866    44,277,785
3          201510  제주특별자치도  서귀포시  일반용  15,154    38,177,748
4          201511  제주특별자치도  서귀포시  일반용  15,326    37,967,067
5          201512  제주특별자치도  서귀포시  일반용  15,497    41,048,811
6          201507  제주특별자치도   제주시  일반용  37,033    90,239,741
7          201508  제주특별자치도   제주시  일반용  37,256   113,139,537
8          201509  제주특별자치도   제주시  일반용  37,617    97,286,581
9          201510  제주특별자치도   제주시  일반용  38,105    84,443,579
10         201511  제주특별자치도   제주시  일반용  38,609    84,758,360
11         201512  제주특별자치도   제주시  일반용  39,036    92,211,776
12  201507-201512  제주특별자치도  서귀포시  일반용    15046     251661469
13  201507-201512  제주특별자치도   제주시  일반용    37942     562079574

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

               년월       시구   시군구 계약구분 고객호수(호)   사용량(kWh)
12  201507-201512  제주특별자치도  서귀포시  일반용   15046  251661469
13  201507-201512  제주특별자치도   제주시  일반용   37942  562079574

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201507-201512  제주특별자치도  서귀포시  일반용   15046   251661469
12  201507-201512  제주특별자치도  서귀포시   합계   19275   826329308
13  201507-201512  제주특별자치도   제주시  일반용   37942   562079574
13  201507-201512  제주특별자치도   제주시   합계   39644  1325475312

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[251661469, 562079574]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[826329308, 1325475312]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[30.46, 42.41]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   30
1   42
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0  서귀포시  일반용  30
1   제주시  일반용  42

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201507-201512  제주특별자치도  서귀포시  일반용   15046   251661469  30
1  201507-201512  제주특별자치도  서귀포시   합계   19275   826329308 NaN
2  201507-201512  제주특별자치도   제주시  일반용   37942   562079574  42
3  201507-201512  제주특별자치도   제주시   합계   39644  1325475312 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)