In [2]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [3]:
df = pd.read_csv('서울특별시_계약종별_전력사용량_월별_18상반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 서울특별시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2018년 01 월 ~ 2018년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,서울특별시,전체(시 / 군 / 구),주택용,"2,773,175","1,218,264,077","141,151,881,578",115.9
4,201801,서울특별시,전체(시 / 군 / 구),일반용,"541,001","2,523,458,088","331,252,172,843",131.3
...,...,...,...,...,...,...,...,...
1234,201806,서울특별시,중랑구,산업용,"2,709","5,479,743","703,116,644",128.3
1235,201806,서울특별시,중랑구,심 야,481,"401,369","25,254,835",62.9
1236,201806,서울특별시,중랑구,일반용,"19,593","36,467,246","4,836,689,571",132.6
1237,201806,서울특별시,중랑구,주택용,"135,096","39,844,635","4,039,788,763",101.4
1238,201806,서울특별시,중랑구,합계,"168,191","84,806,650","9,911,413,400",116.9

In [4]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,서울특별시,전체(시 / 군 / 구),주택용,"2,773,175","1,218,264,077","141,151,881,578",115.9
4,201801,서울특별시,전체(시 / 군 / 구),일반용,"541,001","2,523,458,088","331,252,172,843",131.3
5,201801,서울특별시,전체(시 / 군 / 구),교육용,"2,691","196,353,359","18,960,723,763",96.6
6,201801,서울특별시,전체(시 / 군 / 구),산업용,"45,730","473,720,351","58,107,271,919",122.7
...,...,...,...,...,...,...,...,...
1234,201806,서울특별시,중랑구,산업용,"2,709","5,479,743","703,116,644",128.3
1235,201806,서울특별시,중랑구,심 야,481,"401,369","25,254,835",62.9
1236,201806,서울특별시,중랑구,일반용,"19,593","36,467,246","4,836,689,571",132.6
1237,201806,서울특별시,중랑구,주택용,"135,096","39,844,635","4,039,788,763",101.4
1238,201806,서울특별시,중랑구,합계,"168,191","84,806,650","9,911,413,400",116.9

In [5]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [6]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,서울특별시,전체(시 / 군 / 구),주택용,"2,773,175","1,218,264,077","141,151,881,578",115.9
4,201801,서울특별시,전체(시 / 군 / 구),일반용,"541,001","2,523,458,088","331,252,172,843",131.3
5,201801,서울특별시,전체(시 / 군 / 구),교육용,"2,691","196,353,359","18,960,723,763",96.6
6,201801,서울특별시,전체(시 / 군 / 구),산업용,"45,730","473,720,351","58,107,271,919",122.7
7,201801,서울특별시,전체(시 / 군 / 구),농사용,"1,874","1,751,442","84,035,697",48.0
...,...,...,...,...,...,...,...,...
1234,201806,서울특별시,중랑구,산업용,"2,709","5,479,743","703,116,644",128.3
1235,201806,서울특별시,중랑구,심 야,481,"401,369","25,254,835",62.9
1236,201806,서울특별시,중랑구,일반용,"19,593","36,467,246","4,836,689,571",132.6
1237,201806,서울특별시,중랑구,주택용,"135,096","39,844,635","4,039,788,763",101.4
1238,201806,서울특별시,중랑구,합계,"168,191","84,806,650","9,911,413,400",116.9

In [7]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,서울특별시,전체(시 / 군 / 구),주택용,"2,773,175","1,218,264,077","141,151,881,578",115.9
4,201801,서울특별시,전체(시 / 군 / 구),일반용,"541,001","2,523,458,088","331,252,172,843",131.3
5,201801,서울특별시,전체(시 / 군 / 구),교육용,"2,691","196,353,359","18,960,723,763",96.6
6,201801,서울특별시,전체(시 / 군 / 구),산업용,"45,730","473,720,351","58,107,271,919",122.7
7,201801,서울특별시,전체(시 / 군 / 구),농사용,"1,874","1,751,442","84,035,697",48.0
8,201801,서울특별시,전체(시 / 군 / 구),가로등,"187,886","32,726,126","3,409,150,331",104.2
9,201801,서울특별시,전체(시 / 군 / 구),심 야,"15,695","30,828,345","2,537,249,852",82.3
10,201802,서울특별시,전체(시 / 군 / 구),주택용,"2,776,339","1,230,801,297","143,578,212,057",116.7
11,201802,서울특별시,전체(시 / 군 / 구),일반용,"541,293","2,506,813,144","328,566,905,573",131.1
12,201802,서울특별시,전체(시 / 군 / 구),교육용,"2,697","196,619,691","18,833,076,992",95.8
13,201802,서울특별시,전체(시 / 군 / 구),산업용,"45,731","472,135,611","57,264,045,888",121.3
14,201802,서울특별시,전체(시 / 군 / 구),농사용,"1,871","1,781,012","85,842,899",48.2
15,201802,서울특별시,전체(시 / 군 / 구),가로등,"187,822","30,589,606","3,331,527,432",108.9
16,201802,서울특별시,전체(시 / 군 / 구),심 야,"15,644","31,199,345","2,565,019,988",82.2
17,201803,서울특별시,전체(시 / 군 / 구),주택용,"2,780,142","1,045,250,724","108,694,942,599",104.0
18,201803,서울특별시,전체(시 / 군 / 구),일반용,"541,059","2,003,844,844","244,202,335,986",121.9
19,201803,서울특별시,전체(시 / 군 / 구),교육용,"2,700","149,267,066","14,347,700,373",96.1
20,201803,서울특별시,전체(시 / 군 / 구),산업용,"45,725","405,237,135","45,167,817,248",111.5
21,201803,서울특별시,전체(시 / 군 / 구),농사용,"2,135","1,497,645","72,076,176",48.1
22,201803,서울특별시,전체(시 / 군 / 구),가로등,"187,663","27,981,415","3,084,528,635",110.2
23,201803,서울특별시,전체(시 / 군 / 구),심 야,"15,573","24,744,778","1,871,413,032",75.6
24,201804,서울특별시,전체(시 / 군 / 구),주택용,"2,784,504","1,064,942,184","111,545,591,569",104.7
25,201804,서울특별시,전체(시 / 군 / 구),일반용,"540,781","1,854,105,659","215,030,442,895",116.0
26,201804,서울특별시,전체(시 / 군 / 구),교육용,"2,703","128,615,375","11,535,230,326",89.7
27,201804,서울특별시,전체(시 / 군 / 구),산업용,"45,686","406,314,870","42,418,190,938",104.4
28,201804,서울특별시,전체(시 / 군 / 구),농사용,"1,874","1,342,366","65,886,440",49.1
29,201804,서울특별시,전체(시 / 군 / 구),가로등,"188,025","26,772,290","3,066,610,917",114.5
30,201804,서울특별시,전체(시 / 군 / 구),심 야,"15,507","21,874,499","1,587,189,819",72.6
31,201805,서울특별시,전체(시 / 군 / 구),주택용,"2,787,470","1,000,318,832","100,990,154,309",101.0
32,201805,서울특별시,전체(시 / 군 / 구),일반용,"540,382","1,808,146,916","211,550,334,268",117.0
33,201805,서울특별시,전체(시 / 군 / 구),교육용,"2,692","111,460,997","9,933,591,070",89.1
34,201805,서울특별시,전체(시 / 군 / 구),산업용,"45,712","389,893,555","41,275,377,198",105.9
35,201805,서울특별시,전체(시 / 군 / 구),농사용,"1,868","1,260,772","62,903,890",49.9
36,201805,서울특별시,전체(시 / 군 / 구),가로등,"188,404","24,536,105","2,901,002,192",118.2
37,201805,서울특별시,전체(시 / 군 / 구),심 야,"15,424","31,328,496","2,346,900,351",74.9
38,201806,서울특별시,전체(시 / 군 / 구),주택용,"2,789,706","1,053,725,376","111,511,710,875",105.8
39,201806,서울특별시,전체(시 / 군 / 구),일반용,"540,465","2,025,479,686","271,178,053,282",133.9
40,201806,서울특별시,전체(시 / 군 / 구),교육용,"2,687","128,037,081","13,817,827,933",107.9
41,201806,서울특별시,전체(시 / 군 / 구),산업용,"45,662","404,810,366","49,222,176,568",121.6
42,201806,서울특별시,전체(시 / 군 / 구),농사용,"1,870","1,272,550","64,799,864",50.9
43,201806,서울특별시,전체(시 / 군 / 구),가로등,"188,626","23,305,850","2,847,166,435",122.2
44,201806,서울특별시,전체(시 / 군 / 구),심 야,"15,336","49,611,014","3,613,246,216",72.8
45,합계,합계,합계,합계,"21,459,830","23,162,019,940","2,733,732,318,216",118

In [8]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_9040\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)        사용량(kWh)
4   201801  서울특별시  일반용  541,001   2,523,458,088
11  201802  서울특별시  일반용  541,293   2,506,813,144
18  201803  서울특별시  일반용  541,059   2,003,844,844
25  201804  서울특별시  일반용  540,781   1,854,105,659
32  201805  서울특별시  일반용  540,382   1,808,146,916
39  201806  서울특별시  일반용  540,465   2,025,479,686

In [9]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [11]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201801  서울특별시  강남구  일반용  49,676   334,894,212
252   201802  서울특별시  강남구  일반용  49,689   337,504,938
451   201803  서울특별시  강남구  일반용  49,663   261,587,989
650   201804  서울특별시  강남구  일반용  49,623   238,032,697
848   201805  서울특별시  강남구  일반용  49,502   228,747,089
...      ...    ...  ...  ...      ...           ...
443   201802  서울특별시  중랑구  일반용  19,545    47,869,375
642   201803  서울특별시  중랑구  일반용  19,510    36,891,007
840   201804  서울특별시  중랑구  일반용  19,545    34,528,746
1038  201805  서울특별시  중랑구  일반용  19,553    32,371,114
1236  201806  서울특별시  중랑구  일반용  19,593    36,467,246

[150 rows x 6 columns]

In [12]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'서울특별시'

In [13]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강남구',
 '강동구',
 '강북구',
 '강서구',
 '관악구',
 '광진구',
 '구로구',
 '금천구',
 '노원구',
 '도봉구',
 '동대문구',
 '동작구',
 '마포구',
 '서대문구',
 '서초구',
 '성동구',
 '성북구',
 '송파구',
 '양천구',
 '영등포구',
 '용산구',
 '은평구',
 '종로구',
 '중구',
 '중랑구']

In [14]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55    201801  서울특별시  강남구   합계  197,946   450,177,270
254   201802  서울특별시  강남구   합계  197,920   451,230,089
453   201803  서울특별시  강남구   합계  197,874   361,240,752
652   201804  서울특별시  강남구   합계  197,780   334,575,169
850   201805  서울특별시  강남구   합계  197,222   320,213,237
...      ...    ...  ...  ...       ...           ...
445   201802  서울특별시  중랑구   합계  167,177   109,323,713
644   201803  서울특별시  중랑구   합계  167,440    87,516,156
842   201804  서울특별시  중랑구   합계  167,800    84,888,762
1040  201805  서울특별시  중랑구   합계  168,023    78,578,289
1238  201806  서울특별시  중랑구   합계  168,191    84,806,650

[150 rows x 6 columns]

In [15]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[450177270, 451230089, 361240752, 334575169, 320213237, 357361243]
[143678150, 144535565, 117962301, 112807379, 107320762, 117554527]
[89449522, 91684941, 73571462, 71288005, 65882574, 70672316]
[230096094, 232734811, 193663444, 184318711, 180843909, 189846168]
[162359973, 167823745, 133628610, 130639657, 121546792, 131794054]
[153202091, 154770264, 124671866, 122829192, 118818609, 131800553]
[187018714, 185138868, 146045360, 139136754, 133456682, 145024702]
[158695466, 152726375, 126870837, 119500034, 116475689, 126129574]
[146086911, 146407724, 119201160, 114873106, 107248614, 116781205]
[86372137, 88165656, 70702352, 68882875, 63516586, 68216343]
[139368158, 141041083, 113008317, 108599477, 101302973, 111424790]
[120191329, 121008007, 98513443, 96011919, 91325858, 100378898]
[202369252, 197291697, 161733735, 153712279, 150980925, 165473410]
[119018148, 115923310, 97554246, 92274668, 89932905, 98221110]
[312283498, 315359012, 253372716, 243365875, 232297776, 258604076]
[201936616, 201639509, 169399751, 167374814, 160143870, 171547738]
[139694273, 142025524, 115173029, 110903574, 103114687, 112305803]
[253685643, 250817893, 209494978, 204064744, 199809419, 220144182]
[152401478, 153366205, 133603899, 130106590, 124313901, 129570962]
[249179012, 241676650, 206527814, 194921151, 193825058, 213113581]
[134742745, 135129784, 108424732, 103599522, 99836397, 112891205]
[131805446, 134584613, 109660534, 107353684, 99886551, 106409021]
[171019971, 169434488, 136159703, 128289234, 124307777, 139778251]
[235416246, 226100180, 190122410, 179650068, 181965833, 206391561]
[106853645, 109323713, 87516156, 84888762, 78578289, 84806650]
서울특별시 지역별 합계 :  [2274797760, 743858684, 462548820, 1211503137, 847792831, 806092575, 935821080, 800397975, 750598720, 445855949, 714744798, 627429454, 1031561298, 612924387, 1615282953, 1072042298, 723216890, 1338016859, 823363035, 1299243266, 694624385, 689699849, 868989424, 1219646298, 551967215]
서울특별시 고객호수 평균:  [32917, 21783, 24558, 33659, 43311, 27799, 22077, 16662, 18187, 16658, 25147, 26469, 24823, 19691, 21647, 16333, 25225, 29321, 20683, 22965, 17761, 31993, 15632, 12862, 27932]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201801  서울특별시  강남구   합계  197,946   450,177,270
1           201802  서울특별시  강남구   합계  197,920   451,230,089
2           201803  서울특별시  강남구   합계  197,874   361,240,752
3           201804  서울특별시  강남구   합계  197,780   334,575,169
4           201805  서울특별시  강남구   합계  197,222   320,213,237
..             ...    ...  ...  ...       ...           ...
170  201801-201806  서울특별시  용산구   합계     17761     694624385
171  201801-201806  서울특별시  은평구   합계     31993     689699849
172  201801-201806  서울특별시  종로구   합계     15632     868989424
173  201801-201806  서울특별시   중구   합계     12862    1219646298
174  201801-201806  서울특별시  중랑구   합계     27932     551967215

[175 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [17]:
Hap = Hap.loc[Hap['년월'] == '201801-201806']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201801-201806  서울특별시   강남구   합계   32917  2274797760
151  201801-201806  서울특별시   강동구   합계   21783   743858684
152  201801-201806  서울특별시   강북구   합계   24558   462548820
153  201801-201806  서울특별시   강서구   합계   33659  1211503137
154  201801-201806  서울특별시   관악구   합계   43311   847792831
155  201801-201806  서울특별시   광진구   합계   27799   806092575
156  201801-201806  서울특별시   구로구   합계   22077   935821080
157  201801-201806  서울특별시   금천구   합계   16662   800397975
158  201801-201806  서울특별시   노원구   합계   18187   750598720
159  201801-201806  서울특별시   도봉구   합계   16658   445855949
160  201801-201806  서울특별시  동대문구   합계   25147   714744798
161  201801-201806  서울특별시   동작구   합계   26469   627429454
162  201801-201806  서울특별시   마포구   합계   24823  1031561298
163  201801-201806  서울특별시  서대문구   합계   19691   612924387
164  201801-201806  서울특별시   서초구   합계   21647  1615282953
165  201801-201806  서울특별시   성동구   합계   16333  1072042298
166  201801-201806  서울특별시   성북구   합계   25225   723216890
167  201801-201806  서울특별시   송파구   합계   29321  1338016859
168  201801-201806  서울특별시   양천구   합계   20683   823363035
169  201801-201806  서울특별시  영등포구   합계   22965  1299243266
170  201801-201806  서울특별시   용산구   합계   17761   694624385
171  201801-201806  서울특별시   은평구   합계   31993   689699849
172  201801-201806  서울특별시   종로구   합계   15632   868989424
173  201801-201806  서울특별시    중구   합계   12862  1219646298
174  201801-201806  서울특별시   중랑구   합계   27932   551967215

In [18]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [19]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [20]:
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201801  서울특별시  강남구  일반용  49,676   334,894,212
252   201802  서울특별시  강남구  일반용  49,689   337,504,938
451   201803  서울특별시  강남구  일반용  49,663   261,587,989
650   201804  서울특별시  강남구  일반용  49,623   238,032,697
848   201805  서울특별시  강남구  일반용  49,502   228,747,089
...      ...    ...  ...  ...      ...           ...
443   201802  서울특별시  중랑구  일반용  19,545    47,869,375
642   201803  서울특별시  중랑구  일반용  19,510    36,891,007
840   201804  서울특별시  중랑구  일반용  19,545    34,528,746
1038  201805  서울특별시  중랑구  일반용  19,553    32,371,114
1236  201806  서울특별시  중랑구  일반용  19,593    36,467,246

[150 rows x 6 columns]

In [21]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [22]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[334894212, 337504938, 261587989, 238032697, 228747089, 259952214]
[72622583, 73747206, 57020216, 52329437, 50053437, 57531183]
[41976156, 43308829, 33110802, 30853410, 28748822, 32248315]
[126022910, 128278830, 102462894, 93181550, 94385772, 101517427]
[74641303, 76652117, 60261077, 58111718, 55416122, 61823546]
[62733820, 64340290, 49476441, 46262634, 44729745, 51290946]
[90770799, 87152784, 66072712, 60180076, 58612706, 66096770]
[98799589, 92755170, 77372135, 70796380, 71130138, 78198082]
[61600783, 61898586, 48212625, 44374013, 42812545, 48594116]
[35820917, 36564953, 28016235, 25657391, 23859916, 27081409]
[65559755, 66995904, 51207291, 47253602, 43911676, 50145470]
[58295685, 58774171, 46435813, 44120800, 42644534, 48528322]
[125401332, 121764448, 100314381, 92372502, 90476395, 98707219]
[56386558, 55815403, 44805683, 41565723, 40984231, 46372520]
[202178837, 205465295, 159784428, 149225736, 142420915, 160403570]
[71064363, 70455573, 56634910, 51217571, 49385674, 55452218]
[54960959, 56642932, 43857261, 40701881, 37861363, 42581410]
[147047757, 144116874, 117831781, 110076556, 110864832, 125143583]
[85870745, 86510212, 76443421, 72283582, 70004497, 73807832]
[167286338, 159991519, 135448114, 125223524, 125679010, 139073977]
[80030696, 79744671, 62850962, 58393289, 57227484, 65659238]
[53484616, 55336575, 42191686, 39064469, 36129891, 40146671]
[124214898, 120933139, 97520950, 90376137, 88448529, 99595430]
[184952261, 174193350, 148034030, 137922235, 141240479, 159060972]
[46840216, 47869375, 36891007, 34528746, 32371114, 36467246]
서울특별시 지역별 일반용 합계 :  [1660719139, 363304062, 210246334, 645849383, 386905883, 318833876, 428885847, 489051494, 307492668, 177000821, 325073698, 298799325, 629036277, 285930118, 1019478781, 354210309, 276605806, 755081383, 464920289, 852702482, 403906340, 266353908, 621089083, 945403327, 234967704]
서울특별시 고객호수 평균:  [49614, 19758, 16177, 23633, 24655, 20844, 17994, 13140, 14702, 12205, 23767, 16599, 29263, 16098, 30390, 15894, 20995, 28162, 16595, 23740, 17097, 20330, 25423, 24202, 19542]

In [23]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [24]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [25]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9040\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
0           201801  서울특별시  강남구  일반용  49,676   334,894,212
1           201802  서울특별시  강남구  일반용  49,689   337,504,938
2           201803  서울특별시  강남구  일반용  49,663   261,587,989
3           201804  서울특별시  강남구  일반용  49,623   238,032,697
4           201805  서울특별시  강남구  일반용  49,502   228,747,089
..             ...    ...  ...  ...      ...           ...
170  201801-201806  서울특별시  용산구  일반용    17097     403906340
171  201801-201806  서울특별시  은평구  일반용    20330     266353908
172  201801-201806  서울특별시  종로구  일반용    25423     621089083
173  201801-201806  서울특별시   중구  일반용    24202     945403327
174  201801-201806  서울특별시  중랑구  일반용    19542     234967704

[175 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [27]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201801-201806']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201801-201806  서울특별시   강남구  일반용   49614  1660719139
151  201801-201806  서울특별시   강동구  일반용   19758   363304062
152  201801-201806  서울특별시   강북구  일반용   16177   210246334
153  201801-201806  서울특별시   강서구  일반용   23633   645849383
154  201801-201806  서울특별시   관악구  일반용   24655   386905883
155  201801-201806  서울특별시   광진구  일반용   20844   318833876
156  201801-201806  서울특별시   구로구  일반용   17994   428885847
157  201801-201806  서울특별시   금천구  일반용   13140   489051494
158  201801-201806  서울특별시   노원구  일반용   14702   307492668
159  201801-201806  서울특별시   도봉구  일반용   12205   177000821
160  201801-201806  서울특별시  동대문구  일반용   23767   325073698
161  201801-201806  서울특별시   동작구  일반용   16599   298799325
162  201801-201806  서울특별시   마포구  일반용   29263   629036277
163  201801-201806  서울특별시  서대문구  일반용   16098   285930118
164  201801-201806  서울특별시   서초구  일반용   30390  1019478781
165  201801-201806  서울특별시   성동구  일반용   15894   354210309
166  201801-201806  서울특별시   성북구  일반용   20995   276605806
167  201801-201806  서울특별시   송파구  일반용   28162   755081383
168  201801-201806  서울특별시   양천구  일반용   16595   464920289
169  201801-201806  서울특별시  영등포구  일반용   23740   852702482
170  201801-201806  서울특별시   용산구  일반용   17097   403906340
171  201801-201806  서울특별시   은평구  일반용   20330   266353908
172  201801-201806  서울특별시   종로구  일반용   25423   621089083
173  201801-201806  서울특별시    중구  일반용   24202   945403327
174  201801-201806  서울특별시   중랑구  일반용   19542   234967704

In [28]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201801-201806  서울특별시   강남구  일반용   49614  1660719139
150  201801-201806  서울특별시   강남구   합계   32917  2274797760
151  201801-201806  서울특별시   강동구   합계   21783   743858684
151  201801-201806  서울특별시   강동구  일반용   19758   363304062
152  201801-201806  서울특별시   강북구  일반용   16177   210246334
152  201801-201806  서울특별시   강북구   합계   24558   462548820
153  201801-201806  서울특별시   강서구  일반용   23633   645849383
153  201801-201806  서울특별시   강서구   합계   33659  1211503137
154  201801-201806  서울특별시   관악구  일반용   24655   386905883
154  201801-201806  서울특별시   관악구   합계   43311   847792831
155  201801-201806  서울특별시   광진구  일반용   20844   318833876
155  201801-201806  서울특별시   광진구   합계   27799   806092575
156  201801-201806  서울특별시   구로구  일반용   17994   428885847
156  201801-201806  서울특별시   구로구   합계   22077   935821080
157  201801-201806  서울특별시   금천구  일반용   13140   489051494
157  201801-201806  서울특별시   금천구   합계   16662   800397975
158  201801-201806  서울특별시   노원구   합계   18187   750598720
158  201801-201806  서울특별시   노원구  일반용   14702   307492668
159  201801-201806  서울특별시   도봉구   합계   16658   445855949
159  201801-201806  서울특별시   도봉구  일반용   12205   177000821
160  201801-201806  서울특별시  동대문구   합계   25147   714744798
160  201801-201806  서울특별시  동대문구  일반용   23767   325073698
161  201801-201806  서울특별시   동작구   합계   26469   627429454
161  201801-201806  서울특별시   동작구  일반용   16599   298799325
162  201801-201806  서울특별시   마포구   합계   24823  1031561298
162  201801-201806  서울특별시   마포구  일반용   29263   629036277
163  201801-201806  서울특별시  서대문구   합계   19691   612924387
163  201801-201806  서울특별시  서대문구  일반용   16098   285930118
164  201801-201806  서울특별시   서초구  일반용   30390  1019478781
164  201801-201806  서울특별시   서초구   합계   21647  1615282953
165  201801-201806  서울특별시   성동구   합계   16333  1072042298
165  201801-201806  서울특별시   성동구  일반용   15894   354210309
166  201801-201806  서울특별시   성북구   합계   25225   723216890
166  201801-201806  서울특별시   성북구  일반용   20995   276605806
167  201801-201806  서울특별시   송파구   합계   29321  1338016859
167  201801-201806  서울특별시   송파구  일반용   28162   755081383
168  201801-201806  서울특별시   양천구   합계   20683   823363035
168  201801-201806  서울특별시   양천구  일반용   16595   464920289
169  201801-201806  서울특별시  영등포구  일반용   23740   852702482
169  201801-201806  서울특별시  영등포구   합계   22965  1299243266
170  201801-201806  서울특별시   용산구   합계   17761   694624385
170  201801-201806  서울특별시   용산구  일반용   17097   403906340
171  201801-201806  서울특별시   은평구   합계   31993   689699849
171  201801-201806  서울특별시   은평구  일반용   20330   266353908
172  201801-201806  서울특별시   종로구   합계   15632   868989424
172  201801-201806  서울특별시   종로구  일반용   25423   621089083
173  201801-201806  서울특별시    중구   합계   12862  1219646298
173  201801-201806  서울특별시    중구  일반용   24202   945403327
174  201801-201806  서울특별시   중랑구  일반용   19542   234967704
174  201801-201806  서울특별시   중랑구   합계   27932   551967215

In [29]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[1660719139,
 363304062,
 210246334,
 645849383,
 386905883,
 318833876,
 428885847,
 489051494,
 307492668,
 177000821,
 325073698,
 298799325,
 629036277,
 285930118,
 1019478781,
 354210309,
 276605806,
 755081383,
 464920289,
 852702482,
 403906340,
 266353908,
 621089083,
 945403327,
 234967704]

In [30]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[2274797760,
 743858684,
 462548820,
 1211503137,
 847792831,
 806092575,
 935821080,
 800397975,
 750598720,
 445855949,
 714744798,
 627429454,
 1031561298,
 612924387,
 1615282953,
 1072042298,
 723216890,
 1338016859,
 823363035,
 1299243266,
 694624385,
 689699849,
 868989424,
 1219646298,
 551967215]

In [31]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[73.01, 48.84, 45.45, 53.31, 45.64, 39.55, 45.83, 61.1, 40.97, 39.7, 45.48, 47.62, 60.98, 46.65, 63.11, 33.04, 38.25, 56.43, 56.47, 65.63, 58.15, 38.62, 71.47, 77.51, 42.57]

In [32]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    73
1    49
2    45
3    53
4    46
5    40
6    46
7    61
8    41
9    40
10   45
11   48
12   61
13   47
14   63
15   33
16   38
17   56
18   56
19   66
20   58
21   39
22   71
23   78
24   43
dtype: float64

In [33]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강남구  일반용  73
1    강동구  일반용  49
2    강북구  일반용  45
3    강서구  일반용  53
4    관악구  일반용  46
5    광진구  일반용  40
6    구로구  일반용  46
7    금천구  일반용  61
8    노원구  일반용  41
9    도봉구  일반용  40
10  동대문구  일반용  45
11   동작구  일반용  48
12   마포구  일반용  61
13  서대문구  일반용  47
14   서초구  일반용  63
15   성동구  일반용  33
16   성북구  일반용  38
17   송파구  일반용  56
18   양천구  일반용  56
19  영등포구  일반용  66
20   용산구  일반용  58
21   은평구  일반용  39
22   종로구  일반용  71
23    중구  일반용  78
24   중랑구  일반용  43

In [34]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201801-201806  서울특별시   강남구  일반용   49614  1660719139  73
1   201801-201806  서울특별시   강남구   합계   32917  2274797760 NaN
3   201801-201806  서울특별시   강동구  일반용   19758   363304062  49
2   201801-201806  서울특별시   강동구   합계   21783   743858684 NaN
4   201801-201806  서울특별시   강북구  일반용   16177   210246334  45
5   201801-201806  서울특별시   강북구   합계   24558   462548820 NaN
6   201801-201806  서울특별시   강서구  일반용   23633   645849383  53
7   201801-201806  서울특별시   강서구   합계   33659  1211503137 NaN
8   201801-201806  서울특별시   관악구  일반용   24655   386905883  46
9   201801-201806  서울특별시   관악구   합계   43311   847792831 NaN
10  201801-201806  서울특별시   광진구  일반용   20844   318833876  40
11  201801-201806  서울특별시   광진구   합계   27799   806092575 NaN
12  201801-201806  서울특별시   구로구  일반용   17994   428885847  46
13  201801-201806  서울특별시   구로구   합계   22077   935821080 NaN
14  201801-201806  서울특별시   금천구  일반용   13140   489051494  61
15  201801-201806  서울특별시   금천구   합계   16662   800397975 NaN
17  201801-201806  서울특별시   노원구  일반용   14702   307492668  41
16  201801-201806  서울특별시   노원구   합계   18187   750598720 NaN
19  201801-201806  서울특별시   도봉구  일반용   12205   177000821  40
18  201801-201806  서울특별시   도봉구   합계   16658   445855949 NaN
21  201801-201806  서울특별시  동대문구  일반용   23767   325073698  45
20  201801-201806  서울특별시  동대문구   합계   25147   714744798 NaN
23  201801-201806  서울특별시   동작구  일반용   16599   298799325  48
22  201801-201806  서울특별시   동작구   합계   26469   627429454 NaN
25  201801-201806  서울특별시   마포구  일반용   29263   629036277  61
24  201801-201806  서울특별시   마포구   합계   24823  1031561298 NaN
27  201801-201806  서울특별시  서대문구  일반용   16098   285930118  47
26  201801-201806  서울특별시  서대문구   합계   19691   612924387 NaN
28  201801-201806  서울특별시   서초구  일반용   30390  1019478781  63
29  201801-201806  서울특별시   서초구   합계   21647  1615282953 NaN
31  201801-201806  서울특별시   성동구  일반용   15894   354210309  33
30  201801-201806  서울특별시   성동구   합계   16333  1072042298 NaN
33  201801-201806  서울특별시   성북구  일반용   20995   276605806  38
32  201801-201806  서울특별시   성북구   합계   25225   723216890 NaN
35  201801-201806  서울특별시   송파구  일반용   28162   755081383  56
34  201801-201806  서울특별시   송파구   합계   29321  1338016859 NaN
37  201801-201806  서울특별시   양천구  일반용   16595   464920289  56
36  201801-201806  서울특별시   양천구   합계   20683   823363035 NaN
38  201801-201806  서울특별시  영등포구  일반용   23740   852702482  66
39  201801-201806  서울특별시  영등포구   합계   22965  1299243266 NaN
41  201801-201806  서울특별시   용산구  일반용   17097   403906340  58
40  201801-201806  서울특별시   용산구   합계   17761   694624385 NaN
43  201801-201806  서울특별시   은평구  일반용   20330   266353908  39
42  201801-201806  서울특별시   은평구   합계   31993   689699849 NaN
45  201801-201806  서울특별시   종로구  일반용   25423   621089083  71
44  201801-201806  서울특별시   종로구   합계   15632   868989424 NaN
47  201801-201806  서울특별시    중구  일반용   24202   945403327  78
46  201801-201806  서울특별시    중구   합계   12862  1219646298 NaN
48  201801-201806  서울특별시   중랑구  일반용   19542   234967704  43
49  201801-201806  서울특별시   중랑구   합계   27932   551967215 NaN

In [35]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [36]:
Final.to_csv("{}_일반용_전력사용량_1801-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [37]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [38]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [39]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [40]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [41]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [42]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [43]:
# SEOUL

In [44]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)