In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('제주특별자치도_계약종별_전력사용량_월별_22상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 제주특별자치도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2022년 01 월 ~ 2022년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,제주특별자치도,전체(시 / 군 / 구),주택용,"307,305","91,002,129","11,674,534,974",128.3
4,202201,제주특별자치도,전체(시 / 군 / 구),일반용,"86,041","212,361,517","28,599,575,385",134.7
...,...,...,...,...,...,...,...,...
139,202206,제주특별자치도,제주시,산업용,"2,494","41,694,577","5,209,552,357",124.9
140,202206,제주특별자치도,제주시,심 야,"4,245","3,443,415","233,234,601",67.7
141,202206,제주특별자치도,제주시,일반용,"61,166","126,178,580","17,698,342,437",140.3
142,202206,제주특별자치도,제주시,주택용,"220,298","52,684,312","6,398,254,141",121.4
143,202206,제주특별자치도,제주시,합계,"340,204","275,897,191","32,931,808,651",119.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,제주특별자치도,전체(시 / 군 / 구),주택용,"307,305","91,002,129","11,674,534,974",128.3
4,202201,제주특별자치도,전체(시 / 군 / 구),일반용,"86,041","212,361,517","28,599,575,385",134.7
5,202201,제주특별자치도,전체(시 / 군 / 구),교육용,349,"13,510,235","1,462,081,480",108.2
6,202201,제주특별자치도,전체(시 / 군 / 구),산업용,"3,792","57,808,185","7,261,398,163",125.6
...,...,...,...,...,...,...,...,...
139,202206,제주특별자치도,제주시,산업용,"2,494","41,694,577","5,209,552,357",124.9
140,202206,제주특별자치도,제주시,심 야,"4,245","3,443,415","233,234,601",67.7
141,202206,제주특별자치도,제주시,일반용,"61,166","126,178,580","17,698,342,437",140.3
142,202206,제주특별자치도,제주시,주택용,"220,298","52,684,312","6,398,254,141",121.4
143,202206,제주특별자치도,제주시,합계,"340,204","275,897,191","32,931,808,651",119.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,제주특별자치도,전체(시 / 군 / 구),주택용,"307,305","91,002,129","11,674,534,974",128.3
4,202201,제주특별자치도,전체(시 / 군 / 구),일반용,"86,041","212,361,517","28,599,575,385",134.7
5,202201,제주특별자치도,전체(시 / 군 / 구),교육용,349,"13,510,235","1,462,081,480",108.2
6,202201,제주특별자치도,전체(시 / 군 / 구),산업용,"3,792","57,808,185","7,261,398,163",125.6
7,202201,제주특별자치도,전체(시 / 군 / 구),농사용,"49,784","159,793,103","7,472,879,726",46.8
...,...,...,...,...,...,...,...,...
139,202206,제주특별자치도,제주시,산업용,"2,494","41,694,577","5,209,552,357",124.9
140,202206,제주특별자치도,제주시,심 야,"4,245","3,443,415","233,234,601",67.7
141,202206,제주특별자치도,제주시,일반용,"61,166","126,178,580","17,698,342,437",140.3
142,202206,제주특별자치도,제주시,주택용,"220,298","52,684,312","6,398,254,141",121.4
143,202206,제주특별자치도,제주시,합계,"340,204","275,897,191","32,931,808,651",119.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,제주특별자치도,전체(시 / 군 / 구),주택용,"307,305","91,002,129","11,674,534,974",128.3
4,202201,제주특별자치도,전체(시 / 군 / 구),일반용,"86,041","212,361,517","28,599,575,385",134.7
5,202201,제주특별자치도,전체(시 / 군 / 구),교육용,349,"13,510,235","1,462,081,480",108.2
6,202201,제주특별자치도,전체(시 / 군 / 구),산업용,"3,792","57,808,185","7,261,398,163",125.6
7,202201,제주특별자치도,전체(시 / 군 / 구),농사용,"49,784","159,793,103","7,472,879,726",46.8
8,202201,제주특별자치도,전체(시 / 군 / 구),가로등,"50,883","4,754,753","487,609,274",102.6
9,202201,제주특별자치도,전체(시 / 군 / 구),심 야,"6,401","14,123,812","1,057,685,627",74.9
10,202202,제주특별자치도,전체(시 / 군 / 구),주택용,"307,840","91,727,830","11,885,109,821",129.6
11,202202,제주특별자치도,전체(시 / 군 / 구),일반용,"86,333","210,989,321","28,441,849,172",134.8
12,202202,제주특별자치도,전체(시 / 군 / 구),교육용,350,"11,698,073","1,273,287,769",108.8
13,202202,제주특별자치도,전체(시 / 군 / 구),산업용,"3,799","52,098,697","6,689,489,795",128.4
14,202202,제주특별자치도,전체(시 / 군 / 구),농사용,"49,869","175,211,639","8,116,042,496",46.3
15,202202,제주특별자치도,전체(시 / 군 / 구),가로등,"51,026","4,326,011","481,954,448",111.4
16,202202,제주특별자치도,전체(시 / 군 / 구),심 야,"6,381","14,808,760","1,111,989,445",75.1
17,202203,제주특별자치도,전체(시 / 군 / 구),주택용,"308,254","80,510,791","9,591,177,172",119.1
18,202203,제주특별자치도,전체(시 / 군 / 구),일반용,"86,657","183,543,160","23,112,240,424",125.9
19,202203,제주특별자치도,전체(시 / 군 / 구),교육용,351,"11,484,876","1,146,631,851",99.8
20,202203,제주특별자치도,전체(시 / 군 / 구),산업용,"3,800","52,911,457","5,934,819,876",112.2
21,202203,제주특별자치도,전체(시 / 군 / 구),농사용,"49,964","157,763,206","7,291,615,777",46.2
22,202203,제주특별자치도,전체(시 / 군 / 구),가로등,"51,172","4,044,493","450,952,440",111.5
23,202203,제주특별자치도,전체(시 / 군 / 구),심 야,"6,353","11,811,250","779,074,865",66.0
24,202204,제주특별자치도,전체(시 / 군 / 구),주택용,"308,756","78,844,091","9,639,858,251",122.3
25,202204,제주특별자치도,전체(시 / 군 / 구),일반용,"87,188","180,816,916","21,689,509,646",120.0
26,202204,제주특별자치도,전체(시 / 군 / 구),교육용,350,"10,461,861","1,019,220,936",97.4
27,202204,제주특별자치도,전체(시 / 군 / 구),산업용,"3,783","57,098,746","6,195,283,929",108.5
28,202204,제주특별자치도,전체(시 / 군 / 구),농사용,"50,110","154,378,248","7,559,201,709",49.0
29,202204,제주특별자치도,전체(시 / 군 / 구),가로등,"51,345","3,790,257","467,536,915",123.4
30,202204,제주특별자치도,전체(시 / 군 / 구),심 야,"6,336","9,691,794","581,331,661",60.0
31,202205,제주특별자치도,전체(시 / 군 / 구),주택용,"309,189","70,831,434","8,520,322,798",120.3
32,202205,제주특별자치도,전체(시 / 군 / 구),일반용,"87,342","174,946,642","21,801,974,262",124.6
33,202205,제주특별자치도,전체(시 / 군 / 구),교육용,347,"9,255,451","931,658,727",100.7
34,202205,제주특별자치도,전체(시 / 군 / 구),산업용,"3,746","55,942,896","6,186,228,420",110.6
35,202205,제주특별자치도,전체(시 / 군 / 구),농사용,"50,245","130,932,268","7,039,713,519",53.8
36,202205,제주특별자치도,전체(시 / 군 / 구),가로등,"51,483","3,471,456","463,800,045",133.6
37,202205,제주특별자치도,전체(시 / 군 / 구),심 야,"6,321","6,798,132","449,169,636",66.1
38,202206,제주특별자치도,전체(시 / 군 / 구),주택용,"309,480","73,214,715","8,945,071,332",122.2
39,202206,제주특별자치도,전체(시 / 군 / 구),일반용,"87,625","191,177,554","26,775,077,118",140.1
40,202206,제주특별자치도,전체(시 / 군 / 구),교육용,347,"10,655,492","1,279,204,418",120.1
41,202206,제주특별자치도,전체(시 / 군 / 구),산업용,"3,712","57,326,477","7,219,831,494",125.9
42,202206,제주특별자치도,전체(시 / 군 / 구),농사용,"50,282","116,609,968","6,362,674,515",54.6
43,202206,제주특별자치도,전체(시 / 군 / 구),가로등,"53,334","3,220,470","451,360,660",140.2
44,202206,제주특별자치도,전체(시 / 군 / 구),심 야,"6,313","6,094,333","430,211,831",70.6
45,합계,합계,합계,합계,"3,044,338","3,021,842,499","308,330,241,802",102

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_19364\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월       시구 계약구분  고객호수(호)      사용량(kWh)
4   202201  제주특별자치도  일반용  86,041   212,361,517
11  202202  제주특별자치도  일반용  86,333   210,989,321
18  202203  제주특별자치도  일반용  86,657   183,543,160
25  202204  제주특별자치도  일반용  87,188   180,816,916
32  202205  제주특별자치도  일반용  87,342   174,946,642
39  202206  제주특별자치도  일반용  87,625   191,177,554

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   202201  제주특별자치도  서귀포시  일반용  25,879    71,272,643
69   202202  제주특별자치도  서귀포시  일반용  25,970    70,375,885
85   202203  제주특별자치도  서귀포시  일반용  26,106    59,917,368
101  202204  제주특별자치도  서귀포시  일반용  26,322    61,183,782
117  202205  제주특별자치도  서귀포시  일반용  26,362    59,488,271
133  202206  제주특별자치도  서귀포시  일반용  26,459    64,998,974
61   202201  제주특별자치도   제주시  일반용  60,162   141,088,874
77   202202  제주특별자치도   제주시  일반용  60,363   140,613,436
93   202203  제주특별자치도   제주시  일반용  60,551   123,625,792
109  202204  제주특별자치도   제주시  일반용  60,866   119,633,134
125  202205  제주특별자치도   제주시  일반용  60,980   115,458,371
141  202206  제주특별자치도   제주시  일반용  61,166   126,178,580

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'제주특별자치도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['서귀포시', '제주시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
55   202201  제주특별자치도  서귀포시   합계  169,083   235,970,974
71   202202  제주특별자치도  서귀포시   합계  169,473   247,996,771
87   202203  제주특별자치도  서귀포시   합계  169,858   219,438,140
103  202204  제주특별자치도  서귀포시   합계  170,397   216,066,207
119  202205  제주특별자치도  서귀포시   합계  170,685   191,378,889
135  202206  제주특별자치도  서귀포시   합계  170,889   182,401,818
63   202201  제주특별자치도   제주시   합계  335,472   317,382,760
79   202202  제주특별자치도   제주시   합계  336,125   312,863,560
95   202203  제주특별자치도   제주시   합계  336,693   282,631,093
111  202204  제주특별자치도   제주시   합계  337,471   279,015,706
127  202205  제주특별자치도   제주시   합계  337,988   260,799,390
143  202206  제주특별자치도   제주시   합계  340,204   275,897,191

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[235970974, 247996771, 219438140, 216066207, 191378889, 182401818]
[317382760, 312863560, 282631093, 279015706, 260799390, 275897191]
제주특별자치도 지역별 합계 :  [1293252799, 1728589700]
제주특별자치도 고객호수 평균:  [28344, 56220]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_19364\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19364\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
0          202201  제주특별자치도  서귀포시   합계  169,083   235,970,974
1          202202  제주특별자치도  서귀포시   합계  169,473   247,996,771
2          202203  제주특별자치도  서귀포시   합계  169,858   219,438,140
3          202204  제주특별자치도  서귀포시   합계  170,397   216,066,207
4          202205  제주특별자치도  서귀포시   합계  170,685   191,378,889
5          202206  제주특별자치도  서귀포시   합계  170,889   182,401,818
6          202201  제주특별자치도   제주시   합계  335,472   317,382,760
7          202202  제주특별자치도   제주시   합계  336,125   312,863,560
8          202203  제주특별자치도   제주시   합계  336,693   282,631,093
9          202204  제주특별자치도   제주시   합계  337,471   279,015,706
10         202205  제주특별자치도   제주시   합계  337,988   260,799,390
11         202206  제주특별자치도   제주시   합계  340,204   275,897,191
12  202201-202206  제주특별자치도  서귀포시   합계     28344    1293252799
13  202201-202206  제주특별자치도   제주시   합계     56220    1728589700

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '202201-202206']
Hap

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  202201-202206  제주특별자치도  서귀포시   합계   28344  1293252799
13  202201-202206  제주특별자치도   제주시   합계   56220  1728589700

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   202201  제주특별자치도  서귀포시  일반용  25,879    71,272,643
69   202202  제주특별자치도  서귀포시  일반용  25,970    70,375,885
85   202203  제주특별자치도  서귀포시  일반용  26,106    59,917,368
101  202204  제주특별자치도  서귀포시  일반용  26,322    61,183,782
117  202205  제주특별자치도  서귀포시  일반용  26,362    59,488,271
133  202206  제주특별자치도  서귀포시  일반용  26,459    64,998,974
61   202201  제주특별자치도   제주시  일반용  60,162   141,088,874
77   202202  제주특별자치도   제주시  일반용  60,363   140,613,436
93   202203  제주특별자치도   제주시  일반용  60,551   123,625,792
109  202204  제주특별자치도   제주시  일반용  60,866   119,633,134
125  202205  제주특별자치도   제주시  일반용  60,980   115,458,371
141  202206  제주특별자치도   제주시  일반용  61,166   126,178,580

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[71272643, 70375885, 59917368, 61183782, 59488271, 64998974]
[141088874, 140613436, 123625792, 119633134, 115458371, 126178580]
제주특별자치도 지역별 일반용 합계 :  [387236923, 766598187]
제주특별자치도 고객호수 평균:  [26183, 60681]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_19364\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19364\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0          202201  제주특별자치도  서귀포시  일반용  25,879    71,272,643
1          202202  제주특별자치도  서귀포시  일반용  25,970    70,375,885
2          202203  제주특별자치도  서귀포시  일반용  26,106    59,917,368
3          202204  제주특별자치도  서귀포시  일반용  26,322    61,183,782
4          202205  제주특별자치도  서귀포시  일반용  26,362    59,488,271
5          202206  제주특별자치도  서귀포시  일반용  26,459    64,998,974
6          202201  제주특별자치도   제주시  일반용  60,162   141,088,874
7          202202  제주특별자치도   제주시  일반용  60,363   140,613,436
8          202203  제주특별자치도   제주시  일반용  60,551   123,625,792
9          202204  제주특별자치도   제주시  일반용  60,866   119,633,134
10         202205  제주특별자치도   제주시  일반용  60,980   115,458,371
11         202206  제주특별자치도   제주시  일반용  61,166   126,178,580
12  202201-202206  제주특별자치도  서귀포시  일반용    26183     387236923
13  202201-202206  제주특별자치도   제주시  일반용    60681     766598187

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '202201-202206']
GyeonGiHap2

               년월       시구   시군구 계약구분 고객호수(호)   사용량(kWh)
12  202201-202206  제주특별자치도  서귀포시  일반용   26183  387236923
13  202201-202206  제주특별자치도   제주시  일반용   60681  766598187

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  202201-202206  제주특별자치도  서귀포시  일반용   26183   387236923
12  202201-202206  제주특별자치도  서귀포시   합계   28344  1293252799
13  202201-202206  제주특별자치도   제주시  일반용   60681   766598187
13  202201-202206  제주특별자치도   제주시   합계   56220  1728589700

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[387236923, 766598187]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1293252799, 1728589700]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[29.94, 44.35]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   30
1   44
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0  서귀포시  일반용  30
1   제주시  일반용  44

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  202201-202206  제주특별자치도  서귀포시  일반용   26183   387236923  30
1  202201-202206  제주특별자치도  서귀포시   합계   28344  1293252799 NaN
2  202201-202206  제주특별자치도   제주시  일반용   60681   766598187  44
3  202201-202206  제주특별자치도   제주시   합계   56220  1728589700 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_2201-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)