In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경기도_계약종별_전력사용량_월별_16상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2016년 07 월 ~ 2016년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,전라남도,전체(시 / 군 / 구),주택용,"716,716","188,464,511","22,097,856,786",117.3
4,201607,전라남도,전체(시 / 군 / 구),일반용,"142,524","284,902,931","43,090,713,852",151.2
...,...,...,...,...,...,...,...,...
1099,201612,전라남도,화순군,산업용,752,"11,258,496","1,510,174,784",134.1
1100,201612,전라남도,화순군,심 야,"1,845","2,821,164","206,231,092",73.1
1101,201612,전라남도,화순군,일반용,"4,317","11,961,614","1,617,697,236",135.2
1102,201612,전라남도,화순군,주택용,"24,569","6,366,639","705,775,779",110.9
1103,201612,전라남도,화순군,합계,"48,075","46,894,833","4,856,124,236",103.6

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,전라남도,전체(시 / 군 / 구),주택용,"716,716","188,464,511","22,097,856,786",117.3
4,201607,전라남도,전체(시 / 군 / 구),일반용,"142,524","284,902,931","43,090,713,852",151.2
5,201607,전라남도,전체(시 / 군 / 구),교육용,"1,325","23,790,276","3,139,316,425",132.0
6,201607,전라남도,전체(시 / 군 / 구),산업용,"19,412","1,873,926,453","204,454,728,306",109.1
...,...,...,...,...,...,...,...,...
1099,201612,전라남도,화순군,산업용,752,"11,258,496","1,510,174,784",134.1
1100,201612,전라남도,화순군,심 야,"1,845","2,821,164","206,231,092",73.1
1101,201612,전라남도,화순군,일반용,"4,317","11,961,614","1,617,697,236",135.2
1102,201612,전라남도,화순군,주택용,"24,569","6,366,639","705,775,779",110.9
1103,201612,전라남도,화순군,합계,"48,075","46,894,833","4,856,124,236",103.6

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,전라남도,전체(시 / 군 / 구),주택용,"716,716","188,464,511","22,097,856,786",117.3
4,201607,전라남도,전체(시 / 군 / 구),일반용,"142,524","284,902,931","43,090,713,852",151.2
5,201607,전라남도,전체(시 / 군 / 구),교육용,"1,325","23,790,276","3,139,316,425",132.0
6,201607,전라남도,전체(시 / 군 / 구),산업용,"19,412","1,873,926,453","204,454,728,306",109.1
7,201607,전라남도,전체(시 / 군 / 구),농사용,"256,591","221,964,452","10,518,765,492",47.4
...,...,...,...,...,...,...,...,...
1099,201612,전라남도,화순군,산업용,752,"11,258,496","1,510,174,784",134.1
1100,201612,전라남도,화순군,심 야,"1,845","2,821,164","206,231,092",73.1
1101,201612,전라남도,화순군,일반용,"4,317","11,961,614","1,617,697,236",135.2
1102,201612,전라남도,화순군,주택용,"24,569","6,366,639","705,775,779",110.9
1103,201612,전라남도,화순군,합계,"48,075","46,894,833","4,856,124,236",103.6

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201607,전라남도,전체(시 / 군 / 구),주택용,"716,716","188,464,511","22,097,856,786",117.3
4,201607,전라남도,전체(시 / 군 / 구),일반용,"142,524","284,902,931","43,090,713,852",151.2
5,201607,전라남도,전체(시 / 군 / 구),교육용,"1,325","23,790,276","3,139,316,425",132.0
6,201607,전라남도,전체(시 / 군 / 구),산업용,"19,412","1,873,926,453","204,454,728,306",109.1
7,201607,전라남도,전체(시 / 군 / 구),농사용,"256,591","221,964,452","10,518,765,492",47.4
8,201607,전라남도,전체(시 / 군 / 구),가로등,"141,397","17,702,659","2,197,100,716",124.1
9,201607,전라남도,전체(시 / 군 / 구),심 야,"48,571","20,413,583","1,160,106,184",56.8
10,201608,전라남도,전체(시 / 군 / 구),주택용,"717,182","238,703,851","34,487,722,285",144.5
11,201608,전라남도,전체(시 / 군 / 구),일반용,"143,088","352,015,384","50,590,761,835",143.7
12,201608,전라남도,전체(시 / 군 / 구),교육용,"1,328","23,192,139","3,118,633,287",134.5
13,201608,전라남도,전체(시 / 군 / 구),산업용,"19,474","1,914,598,269","209,655,763,721",109.5
14,201608,전라남도,전체(시 / 군 / 구),농사용,"257,868","292,400,324","13,280,491,346",45.4
15,201608,전라남도,전체(시 / 군 / 구),가로등,"142,012","19,287,333","2,275,096,285",118.0
16,201608,전라남도,전체(시 / 군 / 구),심 야,"48,452","15,934,881","921,475,200",57.8
17,201609,전라남도,전체(시 / 군 / 구),주택용,"717,950","211,443,630","15,560,996,721",73.6
18,201609,전라남도,전체(시 / 군 / 구),일반용,"143,440","315,415,512","41,628,932,016",132.0
19,201609,전라남도,전체(시 / 군 / 구),교육용,"1,327","25,119,483","3,045,932,167",121.3
20,201609,전라남도,전체(시 / 군 / 구),산업용,"19,570","1,941,676,833","170,102,755,252",87.6
21,201609,전라남도,전체(시 / 군 / 구),농사용,"259,039","276,985,037","12,599,429,106",45.5
22,201609,전라남도,전체(시 / 군 / 구),가로등,"142,278","19,640,801","2,267,639,397",115.5
23,201609,전라남도,전체(시 / 군 / 구),심 야,"48,325","15,159,199","877,836,567",57.9
24,201610,전라남도,전체(시 / 군 / 구),주택용,"718,714","181,112,536","18,647,389,789",103.0
25,201610,전라남도,전체(시 / 군 / 구),일반용,"143,698","256,558,229","30,594,560,097",119.2
26,201610,전라남도,전체(시 / 군 / 구),교육용,"1,325","19,655,199","2,227,668,156",113.3
27,201610,전라남도,전체(시 / 군 / 구),산업용,"19,644","2,056,739,973","180,769,298,910",87.9
28,201610,전라남도,전체(시 / 군 / 구),농사용,"259,740","225,829,044","10,696,061,737",47.4
29,201610,전라남도,전체(시 / 군 / 구),가로등,"142,841","20,367,725","2,242,584,034",110.1
30,201610,전라남도,전체(시 / 군 / 구),심 야,"48,236","22,453,037","1,251,626,043",55.7
31,201611,전라남도,전체(시 / 군 / 구),주택용,"719,484","191,001,902","22,471,104,998",117.6
32,201611,전라남도,전체(시 / 군 / 구),일반용,"144,046","265,792,666","34,716,100,500",130.6
33,201611,전라남도,전체(시 / 군 / 구),교육용,"1,324","23,355,956","2,753,476,349",117.9
34,201611,전라남도,전체(시 / 군 / 구),산업용,"19,688","1,868,511,315","207,715,617,027",111.2
35,201611,전라남도,전체(시 / 군 / 구),농사용,"375,868","315,602,665","13,342,862,826",42.3
36,201611,전라남도,전체(시 / 군 / 구),가로등,"143,043","21,465,285","2,311,123,809",107.7
37,201611,전라남도,전체(시 / 군 / 구),심 야,"48,159","48,297,109","3,074,086,443",63.6
38,201612,전라남도,전체(시 / 군 / 구),주택용,"720,286","197,017,720","22,803,050,514",115.7
39,201612,전라남도,전체(시 / 군 / 구),일반용,"144,562","299,469,815","41,774,540,693",139.5
40,201612,전라남도,전체(시 / 군 / 구),교육용,"1,323","30,422,005","3,404,734,022",111.9
41,201612,전라남도,전체(시 / 군 / 구),산업용,"19,721","2,000,561,957","219,979,928,640",110.0
42,201612,전라남도,전체(시 / 군 / 구),농사용,"283,442","269,346,040","12,666,741,611",47.0
43,201612,전라남도,전체(시 / 군 / 구),가로등,"147,321","22,453,717","2,338,502,827",104.1
44,201612,전라남도,전체(시 / 군 / 구),심 야,"48,024","77,492,594","5,814,863,708",75.0
45,합계,합계,합계,합계,"8,138,358","16,706,244,030","1,688,667,975,679",101.1

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_8616\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201607  전라남도  일반용  142,524   284,902,931
11  201608  전라남도  일반용  143,088   352,015,384
18  201609  전라남도  일반용  143,440   315,415,512
25  201610  전라남도  일반용  143,698   256,558,229
32  201611  전라남도  일반용  144,046   265,792,666
39  201612  전라남도  일반용  144,562   299,469,815

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    201607  전라남도  강진군  일반용  2,965    4,669,394
229   201608  전라남도  강진군  일반용  2,982    5,827,487
405   201609  전라남도  강진군  일반용  2,981    5,058,471
581   201610  전라남도  강진군  일반용  2,989    4,210,019
757   201611  전라남도  강진군  일반용  3,002    4,627,729
...      ...   ...  ...  ...     ...          ...
397   201608  전라남도  화순군  일반용  4,275   13,802,400
573   201609  전라남도  화순군  일반용  4,265   12,232,397
749   201610  전라남도  화순군  일반용  4,275   10,111,471
925   201611  전라남도  화순군  일반용  4,305   10,566,236
1101  201612  전라남도  화순군  일반용  4,317   11,961,614

[132 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강진군',
 '고흥군',
 '곡성군',
 '광양시',
 '구례군',
 '나주시',
 '담양군',
 '목포시',
 '무안군',
 '보성군',
 '순천시',
 '신안군',
 '여수시',
 '영광군',
 '영암군',
 '완도군',
 '장성군',
 '장흥군',
 '진도군',
 '함평군',
 '해남군',
 '화순군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55    201607  전라남도  강진군   합계  37,649   21,173,520
231   201608  전라남도  강진군   합계  37,709   26,459,241
407   201609  전라남도  강진군   합계  37,761   24,001,846
583   201610  전라남도  강진군   합계  37,815   21,356,083
759   201611  전라남도  강진군   합계  46,440   29,681,419
...      ...   ...  ...  ...      ...          ...
399   201608  전라남도  화순군   합계  47,796   41,521,345
575   201609  전라남도  화순군   합계  47,906   38,288,795
751   201610  전라남도  화순군   합계  47,966   34,827,520
927   201611  전라남도  화순군   합계  49,783   40,971,280
1103  201612  전라남도  화순군   합계  48,075   46,894,833

[132 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[21173520, 26459241, 24001846, 21356083, 29681419, 27387005]
[29927819, 37360569, 35640592, 29010356, 38002489, 37187337]
[35353321, 36200895, 32866163, 31632822, 34651311, 37587529]
[422279013, 476819316, 524213893, 622745752, 458385970, 481507897]
[12747698, 15750624, 14073213, 12156207, 14412880, 15605999]
[90222212, 101524115, 94300458, 84189912, 93793945, 97973787]
[36859357, 40302432, 39256385, 35585038, 40551107, 44287319]
[78083295, 96549376, 88389024, 72391998, 74985944, 82359176]
[46278289, 56626851, 52324582, 43633669, 54427402, 50715634]
[20516683, 25095318, 23831585, 20216217, 25197021, 27748467]
[146613073, 172518985, 161589943, 143579457, 150719572, 158717222]
[19030164, 23968497, 24625123, 20405686, 23160560, 22595138]
[1227345237, 1254653375, 1220855374, 1211345453, 1192788236, 1274083461]
[52165169, 58323100, 54733239, 55510186, 68654729, 97999157]
[120771338, 118439674, 117242096, 108747343, 111810302, 116507125]
[73985534, 83555302, 83595142, 78965931, 84236603, 72202332]
[47409799, 52731631, 48750952, 46671288, 53199450, 53732407]
[22562709, 27222392, 25505267, 22394830, 30176065, 27253548]
[20811980, 25073941, 24811606, 21553991, 25496834, 25662843]
[25484218, 30312976, 28143370, 24719417, 32780059, 31649208]
[45168219, 55122226, 48401847, 41076587, 55943720, 67106424]
[36376218, 41521345, 38288795, 34827520, 40971280, 46894833]
전라남도 지역별 합계 :  [150059114, 207129162, 208292041, 2985951841, 84746621, 562004429, 236841638, 492758813, 304006427, 142605291, 933738252, 133785168, 7381071136, 387385580, 693517878, 476540844, 302495527, 155114811, 143411195, 173089248, 312819023, 238879991]
전라남도 고객호수 평균:  [6534, 13292, 5310, 12737, 4981, 12574, 7429, 15927, 10595, 8500, 23149, 8247, 25312, 7985, 9192, 7905, 6328, 6463, 6134, 6140, 13284, 8034]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\4267072144.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201607  전라남도  강진군   합계  37,649   21,173,520
1           201608  전라남도  강진군   합계  37,709   26,459,241
2           201609  전라남도  강진군   합계  37,761   24,001,846
3           201610  전라남도  강진군   합계  37,815   21,356,083
4           201611  전라남도  강진군   합계  46,440   29,681,419
..             ...   ...  ...  ...      ...          ...
149  201607-201612  전라남도  장흥군   합계     6463    155114811
150  201607-201612  전라남도  진도군   합계     6134    143411195
151  201607-201612  전라남도  함평군   합계     6140    173089248
152  201607-201612  전라남도  해남군   합계    13284    312819023
153  201607-201612  전라남도  화순군   합계     8034    238879991

[154 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201601-201606']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  201607-201612  전라남도  강진군   합계    6534   150059114
133  201607-201612  전라남도  고흥군   합계   13292   207129162
134  201607-201612  전라남도  곡성군   합계    5310   208292041
135  201607-201612  전라남도  광양시   합계   12737  2985951841
136  201607-201612  전라남도  구례군   합계    4981    84746621
137  201607-201612  전라남도  나주시   합계   12574   562004429
138  201607-201612  전라남도  담양군   합계    7429   236841638
139  201607-201612  전라남도  목포시   합계   15927   492758813
140  201607-201612  전라남도  무안군   합계   10595   304006427
141  201607-201612  전라남도  보성군   합계    8500   142605291
142  201607-201612  전라남도  순천시   합계   23149   933738252
143  201607-201612  전라남도  신안군   합계    8247   133785168
144  201607-201612  전라남도  여수시   합계   25312  7381071136
145  201607-201612  전라남도  영광군   합계    7985   387385580
146  201607-201612  전라남도  영암군   합계    9192   693517878
147  201607-201612  전라남도  완도군   합계    7905   476540844
148  201607-201612  전라남도  장성군   합계    6328   302495527
149  201607-201612  전라남도  장흥군   합계    6463   155114811
150  201607-201612  전라남도  진도군   합계    6134   143411195
151  201607-201612  전라남도  함평군   합계    6140   173089248
152  201607-201612  전라남도  해남군   합계   13284   312819023
153  201607-201612  전라남도  화순군   합계    8034   238879991

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    201607  전라남도  강진군  일반용  2,965    4,669,394
229   201608  전라남도  강진군  일반용  2,982    5,827,487
405   201609  전라남도  강진군  일반용  2,981    5,058,471
581   201610  전라남도  강진군  일반용  2,989    4,210,019
757   201611  전라남도  강진군  일반용  3,002    4,627,729
...      ...   ...  ...  ...     ...          ...
397   201608  전라남도  화순군  일반용  4,275   13,802,400
573   201609  전라남도  화순군  일반용  4,265   12,232,397
749   201610  전라남도  화순군  일반용  4,275   10,111,471
925   201611  전라남도  화순군  일반용  4,305   10,566,236
1101  201612  전라남도  화순군  일반용  4,317   11,961,614

[132 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[4669394, 5827487, 5058471, 4210019, 4627729, 5282311]
[7481458, 9308265, 8622804, 6995088, 7353488, 8400769]
[3427901, 4271687, 3928430, 3184248, 3409942, 3899638]
[20443680, 25260406, 21988698, 17970483, 18274387, 20623075]
[4948555, 6133646, 5336846, 4401764, 5008110, 5351030]
[20259654, 23771561, 20835172, 17695988, 18459038, 21410239]
[7575436, 9464969, 8578600, 6885417, 7421982, 8500462]
[40048455, 50031050, 46584087, 36382666, 35779850, 40209508]
[11880486, 14691586, 13171464, 10876056, 11586699, 13797486]
[5476535, 6956711, 6400317, 5172046, 5575925, 6266156]
[43313015, 53046448, 46244196, 37699717, 38109079, 42735316]
[4400830, 5406316, 5195817, 4208231, 4713242, 5303192]
[45198261, 57146432, 50117517, 40314280, 40936901, 45409255]
[7593261, 9385090, 8784474, 7132444, 7826819, 8748561]
[8728620, 10593942, 10104538, 8226798, 8350132, 9189772]
[7293237, 9311995, 8761710, 7113219, 7226313, 7826279]
[7333301, 8631920, 7392098, 6357072, 7224955, 8257206]
[5398214, 6927751, 6270815, 5215770, 5533309, 6176257]
[3781464, 4679645, 4360433, 3518305, 3756977, 4212457]
[3913606, 4865252, 4434074, 3615461, 3926298, 4391921]
[10057281, 12500825, 11012554, 9271686, 10125255, 11517311]
[11680287, 13802400, 12232397, 10111471, 10566236, 11961614]
전라남도 지역별 일반용 합계 :  [29675411, 48161872, 22121846, 124560729, 31179951, 122431652, 48426866, 249035616, 76003777, 35847690, 261147771, 29227628, 279122646, 49470649, 55193802, 47532753, 45196552, 35522116, 24309281, 25146612, 64484912, 70354405]
전라남도 고객호수 평균:  [2987, 5484, 2149, 10794, 2541, 6775, 3694, 18946, 5433, 3620, 19549, 3473, 22012, 4609, 4270, 5297, 3261, 3260, 2793, 2310, 6010, 4283]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_8616\1068522883.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201607-201612'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
0           201607  전라남도  강진군  일반용  2,965   4,669,394
1           201608  전라남도  강진군  일반용  2,982   5,827,487
2           201609  전라남도  강진군  일반용  2,981   5,058,471
3           201610  전라남도  강진군  일반용  2,989   4,210,019
4           201611  전라남도  강진군  일반용  3,002   4,627,729
..             ...   ...  ...  ...     ...         ...
149  201607-201612  전라남도  장흥군  일반용    3260    35522116
150  201607-201612  전라남도  진도군  일반용    2793    24309281
151  201607-201612  전라남도  함평군  일반용    2310    25146612
152  201607-201612  전라남도  해남군  일반용    6010    64484912
153  201607-201612  전라남도  화순군  일반용    4283    70354405

[154 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201601-201606']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
132  201607-201612  전라남도  강진군  일반용    2987   29675411
133  201607-201612  전라남도  고흥군  일반용    5484   48161872
134  201607-201612  전라남도  곡성군  일반용    2149   22121846
135  201607-201612  전라남도  광양시  일반용   10794  124560729
136  201607-201612  전라남도  구례군  일반용    2541   31179951
137  201607-201612  전라남도  나주시  일반용    6775  122431652
138  201607-201612  전라남도  담양군  일반용    3694   48426866
139  201607-201612  전라남도  목포시  일반용   18946  249035616
140  201607-201612  전라남도  무안군  일반용    5433   76003777
141  201607-201612  전라남도  보성군  일반용    3620   35847690
142  201607-201612  전라남도  순천시  일반용   19549  261147771
143  201607-201612  전라남도  신안군  일반용    3473   29227628
144  201607-201612  전라남도  여수시  일반용   22012  279122646
145  201607-201612  전라남도  영광군  일반용    4609   49470649
146  201607-201612  전라남도  영암군  일반용    4270   55193802
147  201607-201612  전라남도  완도군  일반용    5297   47532753
148  201607-201612  전라남도  장성군  일반용    3261   45196552
149  201607-201612  전라남도  장흥군  일반용    3260   35522116
150  201607-201612  전라남도  진도군  일반용    2793   24309281
151  201607-201612  전라남도  함평군  일반용    2310   25146612
152  201607-201612  전라남도  해남군  일반용    6010   64484912
153  201607-201612  전라남도  화순군  일반용    4283   70354405

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  201607-201612  전라남도  강진군  일반용    2987    29675411
132  201607-201612  전라남도  강진군   합계    6534   150059114
133  201607-201612  전라남도  고흥군  일반용    5484    48161872
133  201607-201612  전라남도  고흥군   합계   13292   207129162
134  201607-201612  전라남도  곡성군  일반용    2149    22121846
134  201607-201612  전라남도  곡성군   합계    5310   208292041
135  201607-201612  전라남도  광양시  일반용   10794   124560729
135  201607-201612  전라남도  광양시   합계   12737  2985951841
136  201607-201612  전라남도  구례군  일반용    2541    31179951
136  201607-201612  전라남도  구례군   합계    4981    84746621
137  201607-201612  전라남도  나주시  일반용    6775   122431652
137  201607-201612  전라남도  나주시   합계   12574   562004429
138  201607-201612  전라남도  담양군  일반용    3694    48426866
138  201607-201612  전라남도  담양군   합계    7429   236841638
139  201607-201612  전라남도  목포시   합계   15927   492758813
139  201607-201612  전라남도  목포시  일반용   18946   249035616
140  201607-201612  전라남도  무안군   합계   10595   304006427
140  201607-201612  전라남도  무안군  일반용    5433    76003777
141  201607-201612  전라남도  보성군   합계    8500   142605291
141  201607-201612  전라남도  보성군  일반용    3620    35847690
142  201607-201612  전라남도  순천시   합계   23149   933738252
142  201607-201612  전라남도  순천시  일반용   19549   261147771
143  201607-201612  전라남도  신안군   합계    8247   133785168
143  201607-201612  전라남도  신안군  일반용    3473    29227628
144  201607-201612  전라남도  여수시   합계   25312  7381071136
144  201607-201612  전라남도  여수시  일반용   22012   279122646
145  201607-201612  전라남도  영광군   합계    7985   387385580
145  201607-201612  전라남도  영광군  일반용    4609    49470649
146  201607-201612  전라남도  영암군   합계    9192   693517878
146  201607-201612  전라남도  영암군  일반용    4270    55193802
147  201607-201612  전라남도  완도군   합계    7905   476540844
147  201607-201612  전라남도  완도군  일반용    5297    47532753
148  201607-201612  전라남도  장성군  일반용    3261    45196552
148  201607-201612  전라남도  장성군   합계    6328   302495527
149  201607-201612  전라남도  장흥군   합계    6463   155114811
149  201607-201612  전라남도  장흥군  일반용    3260    35522116
150  201607-201612  전라남도  진도군   합계    6134   143411195
150  201607-201612  전라남도  진도군  일반용    2793    24309281
151  201607-201612  전라남도  함평군   합계    6140   173089248
151  201607-201612  전라남도  함평군  일반용    2310    25146612
152  201607-201612  전라남도  해남군   합계   13284   312819023
152  201607-201612  전라남도  해남군  일반용    6010    64484912
153  201607-201612  전라남도  화순군  일반용    4283    70354405
153  201607-201612  전라남도  화순군   합계    8034   238879991

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[29675411,
 48161872,
 22121846,
 124560729,
 31179951,
 122431652,
 48426866,
 249035616,
 76003777,
 35847690,
 261147771,
 29227628,
 279122646,
 49470649,
 55193802,
 47532753,
 45196552,
 35522116,
 24309281,
 25146612,
 64484912,
 70354405]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[150059114,
 207129162,
 208292041,
 2985951841,
 84746621,
 562004429,
 236841638,
 492758813,
 304006427,
 142605291,
 933738252,
 133785168,
 7381071136,
 387385580,
 693517878,
 476540844,
 302495527,
 155114811,
 143411195,
 173089248,
 312819023,
 238879991]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[19.78, 23.25, 10.62, 4.17, 36.79, 21.78, 20.45, 50.54, 25.0, 25.14, 27.97, 21.85, 3.78, 12.77, 7.96, 9.97, 14.94, 22.9, 16.95, 14.53, 20.61, 29.45]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    20
1    23
2    11
3     4
4    37
5    22
6    20
7    51
8    25
9    25
10   28
11   22
12    4
13   13
14    8
15   10
16   15
17   23
18   17
19   15
20   21
21   29
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강진군  일반용  20
1   고흥군  일반용  23
2   곡성군  일반용  11
3   광양시  일반용   4
4   구례군  일반용  37
5   나주시  일반용  22
6   담양군  일반용  20
7   목포시  일반용  51
8   무안군  일반용  25
9   보성군  일반용  25
10  순천시  일반용  28
11  신안군  일반용  22
12  여수시  일반용   4
13  영광군  일반용  13
14  영암군  일반용   8
15  완도군  일반용  10
16  장성군  일반용  15
17  장흥군  일반용  23
18  진도군  일반용  17
19  함평군  일반용  15
20  해남군  일반용  21
21  화순군  일반용  29

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201607-201612  전라남도  강진군  일반용    2987    29675411  20
1   201607-201612  전라남도  강진군   합계    6534   150059114 NaN
2   201607-201612  전라남도  고흥군  일반용    5484    48161872  23
3   201607-201612  전라남도  고흥군   합계   13292   207129162 NaN
4   201607-201612  전라남도  곡성군  일반용    2149    22121846  11
5   201607-201612  전라남도  곡성군   합계    5310   208292041 NaN
6   201607-201612  전라남도  광양시  일반용   10794   124560729   4
7   201607-201612  전라남도  광양시   합계   12737  2985951841 NaN
8   201607-201612  전라남도  구례군  일반용    2541    31179951  37
9   201607-201612  전라남도  구례군   합계    4981    84746621 NaN
10  201607-201612  전라남도  나주시  일반용    6775   122431652  22
11  201607-201612  전라남도  나주시   합계   12574   562004429 NaN
12  201607-201612  전라남도  담양군  일반용    3694    48426866  20
13  201607-201612  전라남도  담양군   합계    7429   236841638 NaN
15  201607-201612  전라남도  목포시  일반용   18946   249035616  51
14  201607-201612  전라남도  목포시   합계   15927   492758813 NaN
17  201607-201612  전라남도  무안군  일반용    5433    76003777  25
16  201607-201612  전라남도  무안군   합계   10595   304006427 NaN
19  201607-201612  전라남도  보성군  일반용    3620    35847690  25
18  201607-201612  전라남도  보성군   합계    8500   142605291 NaN
21  201607-201612  전라남도  순천시  일반용   19549   261147771  28
20  201607-201612  전라남도  순천시   합계   23149   933738252 NaN
23  201607-201612  전라남도  신안군  일반용    3473    29227628  22
22  201607-201612  전라남도  신안군   합계    8247   133785168 NaN
25  201607-201612  전라남도  여수시  일반용   22012   279122646   4
24  201607-201612  전라남도  여수시   합계   25312  7381071136 NaN
27  201607-201612  전라남도  영광군  일반용    4609    49470649  13
26  201607-201612  전라남도  영광군   합계    7985   387385580 NaN
29  201607-201612  전라남도  영암군  일반용    4270    55193802   8
28  201607-201612  전라남도  영암군   합계    9192   693517878 NaN
31  201607-201612  전라남도  완도군  일반용    5297    47532753  10
30  201607-201612  전라남도  완도군   합계    7905   476540844 NaN
32  201607-201612  전라남도  장성군  일반용    3261    45196552  15
33  201607-201612  전라남도  장성군   합계    6328   302495527 NaN
35  201607-201612  전라남도  장흥군  일반용    3260    35522116  23
34  201607-201612  전라남도  장흥군   합계    6463   155114811 NaN
37  201607-201612  전라남도  진도군  일반용    2793    24309281  17
36  201607-201612  전라남도  진도군   합계    6134   143411195 NaN
39  201607-201612  전라남도  함평군  일반용    2310    25146612  15
38  201607-201612  전라남도  함평군   합계    6140   173089248 NaN
41  201607-201612  전라남도  해남군  일반용    6010    64484912  21
40  201607-201612  전라남도  해남군   합계   13284   312819023 NaN
42  201607-201612  전라남도  화순군  일반용    4283    70354405  29
43  201607-201612  전라남도  화순군   합계    8034   238879991 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1601-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)