In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('서울특별시_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 서울특별시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,서울특별시,전체(시 / 군 / 구),주택용,"2,676,832","1,099,738,961","142,475,386,879",129.6
4,201507,서울특별시,전체(시 / 군 / 구),일반용,"532,047","2,226,503,579","322,840,438,338",145.0
...,...,...,...,...,...,...,...,...
1237,201512,서울특별시,중랑구,산업용,"2,629","6,377,074","806,634,091",126.5
1238,201512,서울특별시,중랑구,심 야,577,"623,072","50,681,637",81.3
1239,201512,서울특별시,중랑구,일반용,"19,259","37,435,673","5,213,739,731",139.3
1240,201512,서울특별시,중랑구,주택용,"127,813","41,989,701","5,207,789,453",124
1241,201512,서울특별시,중랑구,합계,"160,277","90,171,651","11,702,323,698",129.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,서울특별시,전체(시 / 군 / 구),주택용,"2,676,832","1,099,738,961","142,475,386,879",129.6
4,201507,서울특별시,전체(시 / 군 / 구),일반용,"532,047","2,226,503,579","322,840,438,338",145.0
5,201507,서울특별시,전체(시 / 군 / 구),교육용,"2,649","135,735,749","17,173,860,823",126.5
6,201507,서울특별시,전체(시 / 군 / 구),산업용,"46,143","431,038,396","56,411,422,627",130.9
...,...,...,...,...,...,...,...,...
1237,201512,서울특별시,중랑구,산업용,"2,629","6,377,074","806,634,091",126.5
1238,201512,서울특별시,중랑구,심 야,577,"623,072","50,681,637",81.3
1239,201512,서울특별시,중랑구,일반용,"19,259","37,435,673","5,213,739,731",139.3
1240,201512,서울특별시,중랑구,주택용,"127,813","41,989,701","5,207,789,453",124
1241,201512,서울특별시,중랑구,합계,"160,277","90,171,651","11,702,323,698",129.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,서울특별시,전체(시 / 군 / 구),주택용,"2,676,832","1,099,738,961","142,475,386,879",129.6
4,201507,서울특별시,전체(시 / 군 / 구),일반용,"532,047","2,226,503,579","322,840,438,338",145.0
5,201507,서울특별시,전체(시 / 군 / 구),교육용,"2,649","135,735,749","17,173,860,823",126.5
6,201507,서울특별시,전체(시 / 군 / 구),산업용,"46,143","431,038,396","56,411,422,627",130.9
7,201507,서울특별시,전체(시 / 군 / 구),농사용,"1,949","1,366,588","68,821,986",50.4
...,...,...,...,...,...,...,...,...
1237,201512,서울특별시,중랑구,산업용,"2,629","6,377,074","806,634,091",126.5
1238,201512,서울특별시,중랑구,심 야,577,"623,072","50,681,637",81.3
1239,201512,서울특별시,중랑구,일반용,"19,259","37,435,673","5,213,739,731",139.3
1240,201512,서울특별시,중랑구,주택용,"127,813","41,989,701","5,207,789,453",124
1241,201512,서울특별시,중랑구,합계,"160,277","90,171,651","11,702,323,698",129.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,서울특별시,전체(시 / 군 / 구),주택용,"2,676,832","1,099,738,961","142,475,386,879",129.6
4,201507,서울특별시,전체(시 / 군 / 구),일반용,"532,047","2,226,503,579","322,840,438,338",145.0
5,201507,서울특별시,전체(시 / 군 / 구),교육용,"2,649","135,735,749","17,173,860,823",126.5
6,201507,서울특별시,전체(시 / 군 / 구),산업용,"46,143","431,038,396","56,411,422,627",130.9
7,201507,서울특별시,전체(시 / 군 / 구),농사용,"1,949","1,366,588","68,821,986",50.4
8,201507,서울특별시,전체(시 / 군 / 구),가로등,"177,656","24,576,947","2,961,608,519",120.5
9,201507,서울특별시,전체(시 / 군 / 구),심 야,"18,112","63,211,391","4,569,409,212",72.3
10,201508,서울특별시,전체(시 / 군 / 구),주택용,"2,678,071","1,328,130,146","203,774,838,880",153.4
11,201508,서울특별시,전체(시 / 군 / 구),일반용,"532,756","2,455,892,442","344,292,258,509",140.2
12,201508,서울특별시,전체(시 / 군 / 구),교육용,"2,649","132,524,126","16,728,793,977",126.2
13,201508,서울특별시,전체(시 / 군 / 구),산업용,"46,139","459,675,866","59,767,493,520",130.0
14,201508,서울특별시,전체(시 / 군 / 구),농사용,"1,953","1,456,136","71,882,356",49.4
15,201508,서울특별시,전체(시 / 군 / 구),가로등,"177,482","26,027,078","3,035,116,940",116.6
16,201508,서울특별시,전체(시 / 군 / 구),심 야,"18,026","68,152,697","4,986,624,855",73.2
17,201509,서울특별시,전체(시 / 군 / 구),주택용,"2,680,872","1,146,190,108","148,015,789,554",129.1
18,201509,서울특별시,전체(시 / 군 / 구),일반용,"532,924","2,203,098,215","269,775,599,971",122.5
19,201509,서울특별시,전체(시 / 군 / 구),교육용,"2,653","137,371,198","14,427,742,187",105.0
20,201509,서울특별시,전체(시 / 군 / 구),산업용,"46,177","438,877,629","47,119,576,128",107.4
21,201509,서울특별시,전체(시 / 군 / 구),농사용,"1,958","1,408,397","68,676,009",48.8
22,201509,서울특별시,전체(시 / 군 / 구),가로등,"177,526","27,968,372","3,150,543,583",112.6
23,201509,서울특별시,전체(시 / 군 / 구),심 야,"17,940","51,735,881","3,694,121,079",71.4
24,201510,서울특별시,전체(시 / 군 / 구),주택용,"2,682,052","998,797,672","116,260,585,008",116.4
25,201510,서울특별시,전체(시 / 군 / 구),일반용,"532,713","1,824,445,103","208,101,507,106",114.1
26,201510,서울특별시,전체(시 / 군 / 구),교육용,"2,653","106,898,639","10,812,153,661",101.1
27,201510,서울특별시,전체(시 / 군 / 구),산업용,"46,136","384,693,785","40,405,037,158",105.0
28,201510,서울특별시,전체(시 / 군 / 구),농사용,"1,958","1,252,414","62,477,833",49.9
29,201510,서울특별시,전체(시 / 군 / 구),가로등,"177,501","29,957,409","3,230,152,159",107.8
30,201510,서울특별시,전체(시 / 군 / 구),심 야,"17,847","28,960,545","2,123,485,868",73.3
31,201511,서울특별시,전체(시 / 군 / 구),주택용,"2,685,103","1,051,814,646","130,576,887,356",124.1
32,201511,서울특별시,전체(시 / 군 / 구),일반용,"533,593","1,780,400,815","235,838,784,266",132.5
33,201511,서울특별시,전체(시 / 군 / 구),교육용,"2,652","115,663,364","12,997,696,905",112.4
34,201511,서울특별시,전체(시 / 군 / 구),산업용,"46,043","394,754,033","47,554,544,920",120.5
35,201511,서울특별시,전체(시 / 군 / 구),농사용,"2,198","1,333,621","64,876,565",48.6
36,201511,서울특별시,전체(시 / 군 / 구),가로등,"177,600","32,574,844","3,420,701,495",105.0
37,201511,서울특별시,전체(시 / 군 / 구),심 야,"17,758","19,234,583","1,526,504,018",79.4
38,201512,서울특별시,전체(시 / 군 / 구),주택용,"2,686,500","1,100,125,059","141,829,673,970",128.9
39,201512,서울특별시,전체(시 / 군 / 구),일반용,"535,157","2,041,063,419","280,869,709,881",137.6
40,201512,서울특별시,전체(시 / 군 / 구),교육용,"2,656","156,433,121","17,180,371,833",109.8
41,201512,서울특별시,전체(시 / 군 / 구),산업용,"45,901","419,047,576","52,884,054,699",126.2
42,201512,서울특별시,전체(시 / 군 / 구),농사용,"1,952","1,355,967","67,013,382",49.4
43,201512,서울특별시,전체(시 / 군 / 구),가로등,"177,674","33,703,532","3,461,136,771",102.7
44,201512,서울특별시,전체(시 / 군 / 구),심 야,"17,688","26,992,997","2,221,000,731",82.3
45,합계,합계,합계,합계,"20,765,849","23,010,183,046","2,976,898,361,517",129.4

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_12852\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)        사용량(kWh)
4   201507  서울특별시  일반용  532,047   2,226,503,579
11  201508  서울특별시  일반용  532,756   2,455,892,442
18  201509  서울특별시  일반용  532,924   2,203,098,215
25  201510  서울특별시  일반용  532,713   1,824,445,103
32  201511  서울특별시  일반용  533,593   1,780,400,815
39  201512  서울특별시  일반용  535,157   2,041,063,419

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201507  서울특별시  강남구  일반용  48,791   308,127,305
252   201508  서울특별시  강남구  일반용  48,874   337,322,029
451   201509  서울특별시  강남구  일반용  48,920   300,399,989
650   201510  서울특별시  강남구  일반용  48,924   241,667,522
849   201511  서울특별시  강남구  일반용  49,052   238,061,623
...      ...    ...  ...  ...      ...           ...
443   201508  서울특별시  중랑구  일반용  19,157    45,860,056
642   201509  서울특별시  중랑구  일반용  19,148    41,171,453
841   201510  서울특별시  중랑구  일반용  19,112    33,296,751
1040  201511  서울특별시  중랑구  일반용  19,173    33,052,258
1239  201512  서울특별시  중랑구  일반용  19,259    37,435,673

[150 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'서울특별시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강남구',
 '강동구',
 '강북구',
 '강서구',
 '관악구',
 '광진구',
 '구로구',
 '금천구',
 '노원구',
 '도봉구',
 '동대문구',
 '동작구',
 '마포구',
 '서대문구',
 '서초구',
 '성동구',
 '성북구',
 '송파구',
 '양천구',
 '영등포구',
 '용산구',
 '은평구',
 '종로구',
 '중구',
 '중랑구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55    201507  서울특별시  강남구   합계  199,642   416,361,513
254   201508  서울특별시  강남구   합계  199,681   464,214,861
453   201509  서울특별시  강남구   합계  199,703   407,082,697
652   201510  서울특별시  강남구   합계  199,705   334,499,707
851   201511  서울특별시  강남구   합계  200,011   338,031,343
...      ...    ...  ...  ...       ...           ...
445   201508  서울특별시  중랑구   합계  159,930   105,818,743
644   201509  서울특별시  중랑구   합계  160,100    94,721,908
843   201510  서울특별시  중랑구   합계  160,164    79,765,999
1042  201511  서울특별시  중랑구   합계  160,150    82,304,206
1241  201512  서울특별시  중랑구   합계  160,277    90,171,651

[150 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[416361513, 464214861, 407082697, 334499707, 338031343, 388646187]
[130054974, 147101850, 129807148, 110765190, 112687581, 123765324]
[74037549, 85949817, 78469220, 66170495, 68312374, 74942180]
[170489032, 194605355, 176375368, 149351903, 152969362, 168205613]
[137947545, 161646446, 146826711, 121882959, 124456906, 136001436]
[142901499, 164877165, 145227636, 119022633, 119840581, 131133590]
[154189910, 176827611, 157174897, 138966033, 142018310, 160735495]
[141853877, 152387833, 136280225, 117179361, 119466918, 135300793]
[126043659, 143320731, 128164806, 110261609, 114226067, 125701906]
[74376614, 84815267, 76605077, 65211979, 68283445, 74626171]
[121862376, 139506297, 126306763, 104095303, 105835231, 118096633]
[107864080, 124295599, 111180825, 93333221, 94480492, 103402235]
[175922927, 197239483, 175516959, 150406846, 150199726, 165226477]
[104976757, 117989346, 105223659, 89600412, 90752895, 101487726]
[313362975, 350880147, 311157002, 258488012, 257271989, 283046377]
[161869563, 177462636, 164774041, 141129816, 143618252, 156299125]
[120105048, 136620382, 124921244, 104961093, 108910800, 120919707]
[224310031, 253775844, 224108721, 196601115, 190394625, 217115498]
[130614283, 149810486, 139546116, 119729379, 117570951, 125193093]
[239391771, 259608856, 230696476, 194686493, 189128352, 211804134]
[121051066, 138391576, 123121509, 99681290, 99954890, 111291815]
[109766556, 125823789, 114951633, 97515374, 99799335, 108249122]
[157544943, 171423942, 153714905, 126213149, 126118588, 144108551]
[234298792, 247464429, 224694254, 185486196, 179142687, 203250832]
[90974271, 105818743, 94721908, 79765999, 82304206, 90171651]
서울특별시 지역별 합계 :  [2348836308, 754182067, 447881635, 1011996633, 828762003, 823003104, 929912256, 802469007, 747718778, 443918553, 715702603, 634556452, 1014512418, 610030795, 1774206502, 945153433, 716438274, 1306305834, 782464308, 1325316082, 693492146, 656105809, 879124078, 1274337190, 543756778]
서울특별시 고객호수 평균:  [33292, 21264, 21924, 32298, 40085, 26199, 20931, 15394, 17839, 15920, 24267, 25376, 24938, 19588, 20769, 15766, 25060, 28757, 20823, 22461, 17462, 31785, 15213, 12725, 26679]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201507  서울특별시  강남구   합계  199,642   416,361,513
1           201508  서울특별시  강남구   합계  199,681   464,214,861
2           201509  서울특별시  강남구   합계  199,703   407,082,697
3           201510  서울특별시  강남구   합계  199,705   334,499,707
4           201511  서울특별시  강남구   합계  200,011   338,031,343
..             ...    ...  ...  ...       ...           ...
170  201507-201512  서울특별시  용산구   합계     17462     693492146
171  201507-201512  서울특별시  은평구   합계     31785     656105809
172  201507-201512  서울특별시  종로구   합계     15213     879124078
173  201507-201512  서울특별시   중구   합계     12725    1274337190
174  201507-201512  서울특별시  중랑구   합계     26679     543756778

[175 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201507-201512  서울특별시   강남구   합계   33292  2348836308
151  201507-201512  서울특별시   강동구   합계   21264   754182067
152  201507-201512  서울특별시   강북구   합계   21924   447881635
153  201507-201512  서울특별시   강서구   합계   32298  1011996633
154  201507-201512  서울특별시   관악구   합계   40085   828762003
155  201507-201512  서울특별시   광진구   합계   26199   823003104
156  201507-201512  서울특별시   구로구   합계   20931   929912256
157  201507-201512  서울특별시   금천구   합계   15394   802469007
158  201507-201512  서울특별시   노원구   합계   17839   747718778
159  201507-201512  서울특별시   도봉구   합계   15920   443918553
160  201507-201512  서울특별시  동대문구   합계   24267   715702603
161  201507-201512  서울특별시   동작구   합계   25376   634556452
162  201507-201512  서울특별시   마포구   합계   24938  1014512418
163  201507-201512  서울특별시  서대문구   합계   19588   610030795
164  201507-201512  서울특별시   서초구   합계   20769  1774206502
165  201507-201512  서울특별시   성동구   합계   15766   945153433
166  201507-201512  서울특별시   성북구   합계   25060   716438274
167  201507-201512  서울특별시   송파구   합계   28757  1306305834
168  201507-201512  서울특별시   양천구   합계   20823   782464308
169  201507-201512  서울특별시  영등포구   합계   22461  1325316082
170  201507-201512  서울특별시   용산구   합계   17462   693492146
171  201507-201512  서울특별시   은평구   합계   31785   656105809
172  201507-201512  서울특별시   종로구   합계   15213   879124078
173  201507-201512  서울특별시    중구   합계   12725  1274337190
174  201507-201512  서울특별시   중랑구   합계   26679   543756778

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201507  서울특별시  강남구  일반용  48,791   308,127,305
252   201508  서울특별시  강남구  일반용  48,874   337,322,029
451   201509  서울특별시  강남구  일반용  48,920   300,399,989
650   201510  서울특별시  강남구  일반용  48,924   241,667,522
849   201511  서울특별시  강남구  일반용  49,052   238,061,623
...      ...    ...  ...  ...      ...           ...
443   201508  서울특별시  중랑구  일반용  19,157    45,860,056
642   201509  서울특별시  중랑구  일반용  19,148    41,171,453
841   201510  서울특별시  중랑구  일반용  19,112    33,296,751
1040  201511  서울특별시  중랑구  일반용  19,173    33,052,258
1239  201512  서울특별시  중랑구  일반용  19,259    37,435,673

[150 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[308127305, 337322029, 300399989, 241667522, 238061623, 277856730]
[63719912, 71890469, 63603729, 51376356, 50865396, 58369027]
[35166296, 40550694, 37052732, 29919389, 29736077, 33763866]
[83678249, 94263821, 85599752, 69022640, 68783199, 79272864]
[65821436, 76179685, 68917989, 55876081, 54755358, 60110042]
[57187999, 65424613, 57367460, 46448122, 45473676, 52058958]
[70470800, 82401662, 72017311, 64095999, 63070046, 74203898]
[87771719, 92780556, 81307641, 70429623, 70031711, 81300504]
[53749670, 59805599, 53781707, 43911333, 43480177, 49031065]
[30317899, 34163181, 31186159, 24887135, 24837896, 28323213]
[58459076, 66098019, 59742441, 47601164, 46507469, 53842360]
[53427436, 60548535, 54211790, 44049934, 42695713, 47570503]
[105157302, 115156294, 104612932, 90036828, 87594950, 98357693]
[51113967, 56875344, 50576572, 41701636, 40638188, 46219297]
[193754169, 212235340, 190700689, 155486545, 151476395, 172212056]
[57581426, 63445543, 57773400, 47641040, 47646701, 58878722]
[47136167, 53338888, 48862084, 39268903, 38736758, 43919349]
[127172587, 139939522, 123045360, 109860438, 101316479, 119298123]
[69207134, 77897751, 74387585, 63597150, 60665741, 65087764]
[157709853, 167589766, 150035525, 126563081, 121620788, 139354071]
[71067845, 79389597, 70867528, 56218631, 55219688, 63365512]
[41272420, 47656475, 43212764, 34716318, 34196579, 38785557]
[113814618, 123134333, 109709164, 90713735, 89816489, 103359821]
[183362948, 191944670, 172954459, 146058749, 140121460, 159086751]
[40255346, 45860056, 41171453, 33296751, 33052258, 37435673]
서울특별시 지역별 일반용 합계 :  [1703435198, 359824889, 206189054, 480620525, 381660591, 323960828, 426259716, 483621754, 303759551, 173715483, 332250529, 302503911, 600915999, 287125004, 1075865194, 332966832, 271262149, 720632509, 410843125, 862873084, 396128801, 239840113, 630548160, 993529037, 231071537]
서울특별시 고객호수 평균:  [48952, 19659, 15822, 22564, 24688, 20194, 17580, 12895, 14754, 11904, 24180, 16508, 27364, 16019, 29799, 15333, 20967, 28162, 16569, 24076, 16304, 20219, 24979, 24533, 19165]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12852\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
0           201507  서울특별시  강남구  일반용  48,791   308,127,305
1           201508  서울특별시  강남구  일반용  48,874   337,322,029
2           201509  서울특별시  강남구  일반용  48,920   300,399,989
3           201510  서울특별시  강남구  일반용  48,924   241,667,522
4           201511  서울특별시  강남구  일반용  49,052   238,061,623
..             ...    ...  ...  ...      ...           ...
170  201507-201512  서울특별시  용산구  일반용    16304     396128801
171  201507-201512  서울특별시  은평구  일반용    20219     239840113
172  201507-201512  서울특별시  종로구  일반용    24979     630548160
173  201507-201512  서울특별시   중구  일반용    24533     993529037
174  201507-201512  서울특별시  중랑구  일반용    19165     231071537

[175 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201507-201512  서울특별시   강남구  일반용   48952  1703435198
151  201507-201512  서울특별시   강동구  일반용   19659   359824889
152  201507-201512  서울특별시   강북구  일반용   15822   206189054
153  201507-201512  서울특별시   강서구  일반용   22564   480620525
154  201507-201512  서울특별시   관악구  일반용   24688   381660591
155  201507-201512  서울특별시   광진구  일반용   20194   323960828
156  201507-201512  서울특별시   구로구  일반용   17580   426259716
157  201507-201512  서울특별시   금천구  일반용   12895   483621754
158  201507-201512  서울특별시   노원구  일반용   14754   303759551
159  201507-201512  서울특별시   도봉구  일반용   11904   173715483
160  201507-201512  서울특별시  동대문구  일반용   24180   332250529
161  201507-201512  서울특별시   동작구  일반용   16508   302503911
162  201507-201512  서울특별시   마포구  일반용   27364   600915999
163  201507-201512  서울특별시  서대문구  일반용   16019   287125004
164  201507-201512  서울특별시   서초구  일반용   29799  1075865194
165  201507-201512  서울특별시   성동구  일반용   15333   332966832
166  201507-201512  서울특별시   성북구  일반용   20967   271262149
167  201507-201512  서울특별시   송파구  일반용   28162   720632509
168  201507-201512  서울특별시   양천구  일반용   16569   410843125
169  201507-201512  서울특별시  영등포구  일반용   24076   862873084
170  201507-201512  서울특별시   용산구  일반용   16304   396128801
171  201507-201512  서울특별시   은평구  일반용   20219   239840113
172  201507-201512  서울특별시   종로구  일반용   24979   630548160
173  201507-201512  서울특별시    중구  일반용   24533   993529037
174  201507-201512  서울특별시   중랑구  일반용   19165   231071537

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201507-201512  서울특별시   강남구  일반용   48952  1703435198
150  201507-201512  서울특별시   강남구   합계   33292  2348836308
151  201507-201512  서울특별시   강동구   합계   21264   754182067
151  201507-201512  서울특별시   강동구  일반용   19659   359824889
152  201507-201512  서울특별시   강북구  일반용   15822   206189054
152  201507-201512  서울특별시   강북구   합계   21924   447881635
153  201507-201512  서울특별시   강서구  일반용   22564   480620525
153  201507-201512  서울특별시   강서구   합계   32298  1011996633
154  201507-201512  서울특별시   관악구  일반용   24688   381660591
154  201507-201512  서울특별시   관악구   합계   40085   828762003
155  201507-201512  서울특별시   광진구  일반용   20194   323960828
155  201507-201512  서울특별시   광진구   합계   26199   823003104
156  201507-201512  서울특별시   구로구  일반용   17580   426259716
156  201507-201512  서울특별시   구로구   합계   20931   929912256
157  201507-201512  서울특별시   금천구  일반용   12895   483621754
157  201507-201512  서울특별시   금천구   합계   15394   802469007
158  201507-201512  서울특별시   노원구   합계   17839   747718778
158  201507-201512  서울특별시   노원구  일반용   14754   303759551
159  201507-201512  서울특별시   도봉구   합계   15920   443918553
159  201507-201512  서울특별시   도봉구  일반용   11904   173715483
160  201507-201512  서울특별시  동대문구   합계   24267   715702603
160  201507-201512  서울특별시  동대문구  일반용   24180   332250529
161  201507-201512  서울특별시   동작구   합계   25376   634556452
161  201507-201512  서울특별시   동작구  일반용   16508   302503911
162  201507-201512  서울특별시   마포구   합계   24938  1014512418
162  201507-201512  서울특별시   마포구  일반용   27364   600915999
163  201507-201512  서울특별시  서대문구   합계   19588   610030795
163  201507-201512  서울특별시  서대문구  일반용   16019   287125004
164  201507-201512  서울특별시   서초구  일반용   29799  1075865194
164  201507-201512  서울특별시   서초구   합계   20769  1774206502
165  201507-201512  서울특별시   성동구   합계   15766   945153433
165  201507-201512  서울특별시   성동구  일반용   15333   332966832
166  201507-201512  서울특별시   성북구   합계   25060   716438274
166  201507-201512  서울특별시   성북구  일반용   20967   271262149
167  201507-201512  서울특별시   송파구   합계   28757  1306305834
167  201507-201512  서울특별시   송파구  일반용   28162   720632509
168  201507-201512  서울특별시   양천구   합계   20823   782464308
168  201507-201512  서울특별시   양천구  일반용   16569   410843125
169  201507-201512  서울특별시  영등포구  일반용   24076   862873084
169  201507-201512  서울특별시  영등포구   합계   22461  1325316082
170  201507-201512  서울특별시   용산구   합계   17462   693492146
170  201507-201512  서울특별시   용산구  일반용   16304   396128801
171  201507-201512  서울특별시   은평구   합계   31785   656105809
171  201507-201512  서울특별시   은평구  일반용   20219   239840113
172  201507-201512  서울특별시   종로구   합계   15213   879124078
172  201507-201512  서울특별시   종로구  일반용   24979   630548160
173  201507-201512  서울특별시    중구   합계   12725  1274337190
173  201507-201512  서울특별시    중구  일반용   24533   993529037
174  201507-201512  서울특별시   중랑구  일반용   19165   231071537
174  201507-201512  서울특별시   중랑구   합계   26679   543756778

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[1703435198,
 359824889,
 206189054,
 480620525,
 381660591,
 323960828,
 426259716,
 483621754,
 303759551,
 173715483,
 332250529,
 302503911,
 600915999,
 287125004,
 1075865194,
 332966832,
 271262149,
 720632509,
 410843125,
 862873084,
 396128801,
 239840113,
 630548160,
 993529037,
 231071537]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[2348836308,
 754182067,
 447881635,
 1011996633,
 828762003,
 823003104,
 929912256,
 802469007,
 747718778,
 443918553,
 715702603,
 634556452,
 1014512418,
 610030795,
 1774206502,
 945153433,
 716438274,
 1306305834,
 782464308,
 1325316082,
 693492146,
 656105809,
 879124078,
 1274337190,
 543756778]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[72.52, 47.71, 46.04, 47.49, 46.05, 39.36, 45.84, 60.27, 40.62, 39.13, 46.42, 47.67, 59.23, 47.07, 60.64, 35.23, 37.86, 55.17, 52.51, 65.11, 57.12, 36.56, 71.72, 77.96, 42.5]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    73
1    48
2    46
3    47
4    46
5    39
6    46
7    60
8    41
9    39
10   46
11   48
12   59
13   47
14   61
15   35
16   38
17   55
18   53
19   65
20   57
21   37
22   72
23   78
24   42
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강남구  일반용  73
1    강동구  일반용  48
2    강북구  일반용  46
3    강서구  일반용  47
4    관악구  일반용  46
5    광진구  일반용  39
6    구로구  일반용  46
7    금천구  일반용  60
8    노원구  일반용  41
9    도봉구  일반용  39
10  동대문구  일반용  46
11   동작구  일반용  48
12   마포구  일반용  59
13  서대문구  일반용  47
14   서초구  일반용  61
15   성동구  일반용  35
16   성북구  일반용  38
17   송파구  일반용  55
18   양천구  일반용  53
19  영등포구  일반용  65
20   용산구  일반용  57
21   은평구  일반용  37
22   종로구  일반용  72
23    중구  일반용  78
24   중랑구  일반용  42

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201507-201512  서울특별시   강남구  일반용   48952  1703435198  73
1   201507-201512  서울특별시   강남구   합계   33292  2348836308 NaN
3   201507-201512  서울특별시   강동구  일반용   19659   359824889  48
2   201507-201512  서울특별시   강동구   합계   21264   754182067 NaN
4   201507-201512  서울특별시   강북구  일반용   15822   206189054  46
5   201507-201512  서울특별시   강북구   합계   21924   447881635 NaN
6   201507-201512  서울특별시   강서구  일반용   22564   480620525  47
7   201507-201512  서울특별시   강서구   합계   32298  1011996633 NaN
8   201507-201512  서울특별시   관악구  일반용   24688   381660591  46
9   201507-201512  서울특별시   관악구   합계   40085   828762003 NaN
10  201507-201512  서울특별시   광진구  일반용   20194   323960828  39
11  201507-201512  서울특별시   광진구   합계   26199   823003104 NaN
12  201507-201512  서울특별시   구로구  일반용   17580   426259716  46
13  201507-201512  서울특별시   구로구   합계   20931   929912256 NaN
14  201507-201512  서울특별시   금천구  일반용   12895   483621754  60
15  201507-201512  서울특별시   금천구   합계   15394   802469007 NaN
17  201507-201512  서울특별시   노원구  일반용   14754   303759551  41
16  201507-201512  서울특별시   노원구   합계   17839   747718778 NaN
19  201507-201512  서울특별시   도봉구  일반용   11904   173715483  39
18  201507-201512  서울특별시   도봉구   합계   15920   443918553 NaN
21  201507-201512  서울특별시  동대문구  일반용   24180   332250529  46
20  201507-201512  서울특별시  동대문구   합계   24267   715702603 NaN
23  201507-201512  서울특별시   동작구  일반용   16508   302503911  48
22  201507-201512  서울특별시   동작구   합계   25376   634556452 NaN
25  201507-201512  서울특별시   마포구  일반용   27364   600915999  59
24  201507-201512  서울특별시   마포구   합계   24938  1014512418 NaN
27  201507-201512  서울특별시  서대문구  일반용   16019   287125004  47
26  201507-201512  서울특별시  서대문구   합계   19588   610030795 NaN
28  201507-201512  서울특별시   서초구  일반용   29799  1075865194  61
29  201507-201512  서울특별시   서초구   합계   20769  1774206502 NaN
31  201507-201512  서울특별시   성동구  일반용   15333   332966832  35
30  201507-201512  서울특별시   성동구   합계   15766   945153433 NaN
33  201507-201512  서울특별시   성북구  일반용   20967   271262149  38
32  201507-201512  서울특별시   성북구   합계   25060   716438274 NaN
35  201507-201512  서울특별시   송파구  일반용   28162   720632509  55
34  201507-201512  서울특별시   송파구   합계   28757  1306305834 NaN
37  201507-201512  서울특별시   양천구  일반용   16569   410843125  53
36  201507-201512  서울특별시   양천구   합계   20823   782464308 NaN
38  201507-201512  서울특별시  영등포구  일반용   24076   862873084  65
39  201507-201512  서울특별시  영등포구   합계   22461  1325316082 NaN
41  201507-201512  서울특별시   용산구  일반용   16304   396128801  57
40  201507-201512  서울특별시   용산구   합계   17462   693492146 NaN
43  201507-201512  서울특별시   은평구  일반용   20219   239840113  37
42  201507-201512  서울특별시   은평구   합계   31785   656105809 NaN
45  201507-201512  서울특별시   종로구  일반용   24979   630548160  72
44  201507-201512  서울특별시   종로구   합계   15213   879124078 NaN
47  201507-201512  서울특별시    중구  일반용   24533   993529037  78
46  201507-201512  서울특별시    중구   합계   12725  1274337190 NaN
48  201507-201512  서울특별시   중랑구  일반용   19165   231071537  42
49  201507-201512  서울특별시   중랑구   합계   26679   543756778 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)