In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상북도_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상북도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경상북도,전체(시 / 군 / 구),주택용,"1,064,490","303,071,417","39,635,136,205",130.8
4,201501,경상북도,전체(시 / 군 / 구),일반용,"203,561","507,071,727","66,670,904,775",131.5
...,...,...,...,...,...,...,...,...
1147,201506,경상북도,포항시,산업용,"2,624","938,614,339","100,623,768,470",107.2
1148,201506,경상북도,포항시,심 야,"4,932","3,162,244","172,841,915",54.7
1149,201506,경상북도,포항시,일반용,"37,463","71,591,701","9,752,445,167",136.2
1150,201506,경상북도,포항시,주택용,"176,299","50,807,477","5,755,216,594",113.3
1151,201506,경상북도,포항시,합계,"248,471","1,089,811,354","118,553,712,784",108.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경상북도,전체(시 / 군 / 구),주택용,"1,064,490","303,071,417","39,635,136,205",130.8
4,201501,경상북도,전체(시 / 군 / 구),일반용,"203,561","507,071,727","66,670,904,775",131.5
5,201501,경상북도,전체(시 / 군 / 구),교육용,"1,461","58,053,512","6,260,034,625",107.8
6,201501,경상북도,전체(시 / 군 / 구),산업용,"29,940","2,937,633,997","327,573,357,743",111.5
...,...,...,...,...,...,...,...,...
1147,201506,경상북도,포항시,산업용,"2,624","938,614,339","100,623,768,470",107.2
1148,201506,경상북도,포항시,심 야,"4,932","3,162,244","172,841,915",54.7
1149,201506,경상북도,포항시,일반용,"37,463","71,591,701","9,752,445,167",136.2
1150,201506,경상북도,포항시,주택용,"176,299","50,807,477","5,755,216,594",113.3
1151,201506,경상북도,포항시,합계,"248,471","1,089,811,354","118,553,712,784",108.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경상북도,전체(시 / 군 / 구),주택용,"1,064,490","303,071,417","39,635,136,205",130.8
4,201501,경상북도,전체(시 / 군 / 구),일반용,"203,561","507,071,727","66,670,904,775",131.5
5,201501,경상북도,전체(시 / 군 / 구),교육용,"1,461","58,053,512","6,260,034,625",107.8
6,201501,경상북도,전체(시 / 군 / 구),산업용,"29,940","2,937,633,997","327,573,357,743",111.5
7,201501,경상북도,전체(시 / 군 / 구),농사용,"286,572","162,222,565","7,829,913,727",48.3
...,...,...,...,...,...,...,...,...
1147,201506,경상북도,포항시,산업용,"2,624","938,614,339","100,623,768,470",107.2
1148,201506,경상북도,포항시,심 야,"4,932","3,162,244","172,841,915",54.7
1149,201506,경상북도,포항시,일반용,"37,463","71,591,701","9,752,445,167",136.2
1150,201506,경상북도,포항시,주택용,"176,299","50,807,477","5,755,216,594",113.3
1151,201506,경상북도,포항시,합계,"248,471","1,089,811,354","118,553,712,784",108.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경상북도,전체(시 / 군 / 구),주택용,"1,064,490","303,071,417","39,635,136,205",130.8
4,201501,경상북도,전체(시 / 군 / 구),일반용,"203,561","507,071,727","66,670,904,775",131.5
5,201501,경상북도,전체(시 / 군 / 구),교육용,"1,461","58,053,512","6,260,034,625",107.8
6,201501,경상북도,전체(시 / 군 / 구),산업용,"29,940","2,937,633,997","327,573,357,743",111.5
7,201501,경상북도,전체(시 / 군 / 구),농사용,"286,572","162,222,565","7,829,913,727",48.3
8,201501,경상북도,전체(시 / 군 / 구),가로등,"159,054","25,516,835","2,623,394,445",102.8
9,201501,경상북도,전체(시 / 군 / 구),심 야,"82,721","229,325,341","17,227,009,398",75.1
10,201502,경상북도,전체(시 / 군 / 구),주택용,"1,066,170","296,521,051","37,982,525,009",128.1
11,201502,경상북도,전체(시 / 군 / 구),일반용,"203,383","480,073,171","63,853,035,232",133.0
12,201502,경상북도,전체(시 / 군 / 구),교육용,"1,465","52,009,391","5,720,938,282",110.0
13,201502,경상북도,전체(시 / 군 / 구),산업용,"29,963","2,587,975,295","292,628,324,452",113.1
14,201502,경상북도,전체(시 / 군 / 구),농사용,"286,165","153,290,322","7,466,497,746",48.7
15,201502,경상북도,전체(시 / 군 / 구),가로등,"161,057","23,236,111","2,565,139,949",110.4
16,201502,경상북도,전체(시 / 군 / 구),심 야,"82,644","213,654,761","16,042,712,704",75.1
17,201503,경상북도,전체(시 / 군 / 구),주택용,"1,068,279","262,896,548","30,044,720,542",114.3
18,201503,경상북도,전체(시 / 군 / 구),일반용,"202,866","408,389,303","51,246,555,159",125.5
19,201503,경상북도,전체(시 / 군 / 구),교육용,"1,467","55,806,578","5,124,602,129",91.8
20,201503,경상북도,전체(시 / 군 / 구),산업용,"29,997","2,778,509,120","259,504,261,045",93.4
21,201503,경상북도,전체(시 / 군 / 구),농사용,"353,983","128,678,545","6,397,326,587",49.7
22,201503,경상북도,전체(시 / 군 / 구),가로등,"161,281","21,987,609","2,439,569,695",111.0
23,201503,경상북도,전체(시 / 군 / 구),심 야,"82,547","177,350,583","11,723,386,340",66.1
24,201504,경상북도,전체(시 / 군 / 구),주택용,"1,071,073","274,669,016","32,269,844,943",117.5
25,201504,경상북도,전체(시 / 군 / 구),일반용,"203,139","398,569,392","45,826,231,165",115.0
26,201504,경상북도,전체(시 / 군 / 구),교육용,"1,462","50,718,321","4,565,277,217",90.0
27,201504,경상북도,전체(시 / 군 / 구),산업용,"30,045","2,816,296,661","259,827,527,357",92.3
28,201504,경상북도,전체(시 / 군 / 구),농사용,"288,911","118,561,766","5,982,046,104",50.5
29,201504,경상북도,전체(시 / 군 / 구),가로등,"161,737","21,023,042","2,475,521,108",117.8
30,201504,경상북도,전체(시 / 군 / 구),심 야,"82,461","141,362,351","7,661,086,397",54.2
31,201505,경상북도,전체(시 / 군 / 구),주택용,"1,073,396","255,289,553","28,348,421,103",111.0
32,201505,경상북도,전체(시 / 군 / 구),일반용,"203,374","359,038,247","42,930,557,306",119.6
33,201505,경상북도,전체(시 / 군 / 구),교육용,"1,461","39,581,797","3,872,457,121",97.8
34,201505,경상북도,전체(시 / 군 / 구),산업용,"30,140","2,796,102,134","253,886,418,678",90.8
35,201505,경상북도,전체(시 / 군 / 구),농사용,"291,485","114,766,033","5,763,942,657",50.2
36,201505,경상북도,전체(시 / 군 / 구),가로등,"162,026","19,805,013","2,419,104,813",122.1
37,201505,경상북도,전체(시 / 군 / 구),심 야,"82,303","83,626,352","4,547,803,887",54.4
38,201506,경상북도,전체(시 / 군 / 구),주택용,"1,076,303","255,251,334","28,050,674,719",109.9
39,201506,경상북도,전체(시 / 군 / 구),일반용,"203,206","373,344,608","50,787,197,094",136.0
40,201506,경상북도,전체(시 / 군 / 구),교육용,"1,461","42,224,091","5,064,895,592",120.0
41,201506,경상북도,전체(시 / 군 / 구),산업용,"30,241","2,794,162,941","315,449,090,440",112.9
42,201506,경상북도,전체(시 / 군 / 구),농사용,"294,898","148,956,324","6,891,140,778",46.3
43,201506,경상북도,전체(시 / 군 / 구),가로등,"162,649","18,848,970","2,402,741,608",127.5
44,201506,경상북도,전체(시 / 군 / 구),심 야,"82,169","45,770,156","2,522,545,939",55.1
45,합계,합계,합계,합계,"11,093,006","23,031,241,884","2,372,103,871,815",103

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_2392\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201501  경상북도  일반용  203,561   507,071,727
11  201502  경상북도  일반용  203,383   480,073,171
18  201503  경상북도  일반용  202,866   408,389,303
25  201504  경상북도  일반용  203,139   398,569,392
32  201505  경상북도  일반용  203,374   359,038,247
39  201506  경상북도  일반용  203,206   373,344,608

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53    201501  경상북도  경산시  일반용  15,782   40,773,676
237   201502  경상북도  경산시  일반용  15,787   39,084,659
421   201503  경상북도  경산시  일반용  15,752   33,312,411
605   201504  경상북도  경산시  일반용  15,783   32,836,094
789   201505  경상북도  경산시  일반용  15,819   30,326,404
...      ...   ...  ...  ...      ...          ...
413   201502  경상북도  포항시  일반용  37,560   87,464,688
597   201503  경상북도  포항시  일반용  37,517   75,334,126
781   201504  경상북도  포항시  일반용  37,554   74,589,512
965   201505  경상북도  포항시  일반용  37,564   67,856,827
1149  201506  경상북도  포항시  일반용  37,463   71,591,701

[138 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상북도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['경산시',
 '경주시',
 '고령군',
 '구미시',
 '군위군',
 '김천시',
 '문경시',
 '봉화군',
 '상주시',
 '성주군',
 '안동시',
 '영덕군',
 '영양군',
 '영주시',
 '영천시',
 '예천군',
 '울릉군',
 '울진군',
 '의성군',
 '청도군',
 '청송군',
 '칠곡군',
 '포항시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월    시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201501  경상북도  경산시   합계  143,033     253,473,818
239   201502  경상북도  경산시   합계  143,393     236,036,696
423   201503  경상북도  경산시   합계  143,645     222,947,499
607   201504  경상북도  경산시   합계  144,103     227,194,117
791   201505  경상북도  경산시   합계  144,448     209,039,137
...      ...   ...  ...  ...       ...             ...
415   201502  경상북도  포항시   합계  246,534   1,016,002,594
599   201503  경상북도  포항시   합계  250,463   1,137,415,415
783   201504  경상북도  포항시   합계  247,385   1,184,654,881
967   201505  경상북도  포항시   합계  247,884   1,096,155,011
1151  201506  경상북도  포항시   합계  248,471   1,089,811,354

[138 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[253473818, 236036696, 222947499, 227194117, 209039137, 212047362]
[392783834, 371500205, 336226386, 344687292, 313424708, 344720837]
[111001320, 101569818, 103316588, 104502900, 93827873, 96214578]
[854276060, 777558709, 809008290, 799036542, 804718149, 816969079]
[31798235, 30237568, 27009192, 26675344, 23657056, 23914314]
[183780420, 171845617, 170426382, 167681611, 160394549, 162096053]
[60014485, 55271205, 50015722, 47982228, 41282098, 40657413]
[164678234, 146743740, 156739931, 122780459, 201774234, 153252169]
[71508865, 67884182, 58882004, 55231290, 49735341, 48715258]
[88471223, 84274663, 76783480, 78884599, 70665998, 71104115]
[107971022, 100923347, 88207683, 83482206, 71842265, 74408090]
[29856605, 27995784, 23460187, 23610338, 20345817, 19751084]
[12589880, 11670317, 10011719, 9205274, 7372016, 6771560]
[124531284, 114240346, 112392576, 103900488, 104522752, 104597436]
[137070272, 131956518, 119983486, 124847550, 110081246, 114273521]
[31700894, 30364638, 25679064, 23791955, 20473376, 21503591]
[4814665, 4524837, 4159046, 4907511, 4645871, 4406519]
[44000314, 42886374, 44667655, 34507437, 34269079, 35126911]
[39546524, 38083350, 33033953, 32356625, 29489592, 33193186]
[48747533, 44532352, 37611869, 37239064, 32770822, 32542040]
[19145832, 17847511, 15384123, 15007378, 12518920, 12452150]
[192608256, 182809731, 170256036, 169033460, 155203219, 160029804]
[1218525819, 1016002594, 1137415415, 1184654881, 1096155011, 1089811354]
경상북도 지역별 합계 :  [1360738629, 2103343262, 610433077, 4861566829, 163291709, 1016224632, 295223151, 945968767, 351956940, 470184078, 526834613, 145019815, 57620766, 664184882, 738212593, 153513518, 27458449, 235457770, 205703230, 233443680, 92355914, 1029940506, 6742565074]
경상북도 고객호수 평균:  [23986, 30955, 4913, 31875, 4580, 16477, 9914, 6641, 15873, 7996, 19404, 6611, 3886, 13035, 13796, 8868, 1263, 8206, 11074, 8858, 5939, 12674, 41307]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201501  경상북도  경산시   합계  143,033   253,473,818
1           201502  경상북도  경산시   합계  143,393   236,036,696
2           201503  경상북도  경산시   합계  143,645   222,947,499
3           201504  경상북도  경산시   합계  144,103   227,194,117
4           201505  경상북도  경산시   합계  144,448   209,039,137
..             ...   ...  ...  ...       ...           ...
156  201501-201506  경상북도  의성군   합계     11074     205703230
157  201501-201506  경상북도  청도군   합계      8858     233443680
158  201501-201506  경상북도  청송군   합계      5939      92355914
159  201501-201506  경상북도  칠곡군   합계     12674    1029940506
160  201501-201506  경상북도  포항시   합계     41307    6742565074

[161 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
138  201501-201506  경상북도  경산시   합계   23986  1360738629
139  201501-201506  경상북도  경주시   합계   30955  2103343262
140  201501-201506  경상북도  고령군   합계    4913   610433077
141  201501-201506  경상북도  구미시   합계   31875  4861566829
142  201501-201506  경상북도  군위군   합계    4580   163291709
143  201501-201506  경상북도  김천시   합계   16477  1016224632
144  201501-201506  경상북도  문경시   합계    9914   295223151
145  201501-201506  경상북도  봉화군   합계    6641   945968767
146  201501-201506  경상북도  상주시   합계   15873   351956940
147  201501-201506  경상북도  성주군   합계    7996   470184078
148  201501-201506  경상북도  안동시   합계   19404   526834613
149  201501-201506  경상북도  영덕군   합계    6611   145019815
150  201501-201506  경상북도  영양군   합계    3886    57620766
151  201501-201506  경상북도  영주시   합계   13035   664184882
152  201501-201506  경상북도  영천시   합계   13796   738212593
153  201501-201506  경상북도  예천군   합계    8868   153513518
154  201501-201506  경상북도  울릉군   합계    1263    27458449
155  201501-201506  경상북도  울진군   합계    8206   235457770
156  201501-201506  경상북도  의성군   합계   11074   205703230
157  201501-201506  경상북도  청도군   합계    8858   233443680
158  201501-201506  경상북도  청송군   합계    5939    92355914
159  201501-201506  경상북도  칠곡군   합계   12674  1029940506
160  201501-201506  경상북도  포항시   합계   41307  6742565074

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53    201501  경상북도  경산시  일반용  15,782   40,773,676
237   201502  경상북도  경산시  일반용  15,787   39,084,659
421   201503  경상북도  경산시  일반용  15,752   33,312,411
605   201504  경상북도  경산시  일반용  15,783   32,836,094
789   201505  경상북도  경산시  일반용  15,819   30,326,404
...      ...   ...  ...  ...      ...          ...
413   201502  경상북도  포항시  일반용  37,560   87,464,688
597   201503  경상북도  포항시  일반용  37,517   75,334,126
781   201504  경상북도  포항시  일반용  37,554   74,589,512
965   201505  경상북도  포항시  일반용  37,564   67,856,827
1149  201506  경상북도  포항시  일반용  37,463   71,591,701

[138 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[40773676, 39084659, 33312411, 32836094, 30326404, 32012745]
[62873195, 58711190, 50115086, 49947812, 46092102, 46555799]
[5684995, 5499591, 4562389, 4479503, 3935185, 4048364]
[70864852, 67027409, 56407611, 54196698, 49711303, 54267831]
[5020894, 4859910, 4189590, 4284415, 3926040, 4011756]
[23656186, 22492246, 19267902, 18296185, 16222239, 17032868]
[15166972, 14210083, 12123250, 11455155, 10054190, 9968458]
[5095393, 4641379, 3970565, 3975753, 3431598, 3272483]
[16376138, 15616572, 13331631, 12779279, 11385336, 11663121]
[7678309, 7266157, 6113778, 5899370, 5272675, 5324701]
[35490615, 33288017, 28200219, 27030259, 23718352, 24732088]
[11414756, 10717763, 8766534, 8709921, 7622726, 7456869]
[2911402, 2699665, 2251226, 2223697, 1870009, 1766177]
[18958412, 17928219, 14989084, 14529789, 12729164, 13056613]
[18104904, 17197839, 14530397, 14110676, 12515976, 13010925]
[7735582, 7491524, 6314187, 6004353, 5179507, 5235742]
[2922388, 2779714, 2562715, 3050951, 2876812, 2639117]
[16077108, 14922828, 13008305, 12355380, 10764483, 10524125]
[7736953, 7319292, 6187621, 5942521, 5124456, 5134731]
[8019846, 7566942, 6549216, 6400829, 5742143, 5776598]
[5528437, 5195753, 4404903, 4210441, 3607710, 3491732]
[26932982, 26091731, 21896557, 21260799, 19073010, 20770064]
[92047732, 87464688, 75334126, 74589512, 67856827, 71591701]
경상북도 지역별 일반용 합계 :  [208345989, 314295184, 28210027, 352475704, 26292605, 116967626, 72978108, 24387171, 81152077, 37554990, 172459550, 54688569, 13722176, 92191281, 89470717, 37960895, 16831697, 77652229, 37445574, 40055574, 26438976, 136025143, 468884586]
경상북도 고객호수 평균:  [15792, 23410, 2911, 26128, 1985, 9413, 6184, 2855, 7472, 3739, 12644, 4879, 1581, 9101, 7647, 3206, 1574, 5129, 4052, 3608, 2660, 9725, 37552]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2392\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201501  경상북도  경산시  일반용  15,782   40,773,676
1           201502  경상북도  경산시  일반용  15,787   39,084,659
2           201503  경상북도  경산시  일반용  15,752   33,312,411
3           201504  경상북도  경산시  일반용  15,783   32,836,094
4           201505  경상북도  경산시  일반용  15,819   30,326,404
..             ...   ...  ...  ...      ...          ...
156  201501-201506  경상북도  의성군  일반용     4052     37445574
157  201501-201506  경상북도  청도군  일반용     3608     40055574
158  201501-201506  경상북도  청송군  일반용     2660     26438976
159  201501-201506  경상북도  칠곡군  일반용     9725    136025143
160  201501-201506  경상북도  포항시  일반용    37552    468884586

[161 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
138  201501-201506  경상북도  경산시  일반용   15792  208345989
139  201501-201506  경상북도  경주시  일반용   23410  314295184
140  201501-201506  경상북도  고령군  일반용    2911   28210027
141  201501-201506  경상북도  구미시  일반용   26128  352475704
142  201501-201506  경상북도  군위군  일반용    1985   26292605
143  201501-201506  경상북도  김천시  일반용    9413  116967626
144  201501-201506  경상북도  문경시  일반용    6184   72978108
145  201501-201506  경상북도  봉화군  일반용    2855   24387171
146  201501-201506  경상북도  상주시  일반용    7472   81152077
147  201501-201506  경상북도  성주군  일반용    3739   37554990
148  201501-201506  경상북도  안동시  일반용   12644  172459550
149  201501-201506  경상북도  영덕군  일반용    4879   54688569
150  201501-201506  경상북도  영양군  일반용    1581   13722176
151  201501-201506  경상북도  영주시  일반용    9101   92191281
152  201501-201506  경상북도  영천시  일반용    7647   89470717
153  201501-201506  경상북도  예천군  일반용    3206   37960895
154  201501-201506  경상북도  울릉군  일반용    1574   16831697
155  201501-201506  경상북도  울진군  일반용    5129   77652229
156  201501-201506  경상북도  의성군  일반용    4052   37445574
157  201501-201506  경상북도  청도군  일반용    3608   40055574
158  201501-201506  경상북도  청송군  일반용    2660   26438976
159  201501-201506  경상북도  칠곡군  일반용    9725  136025143
160  201501-201506  경상북도  포항시  일반용   37552  468884586

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
138  201501-201506  경상북도  경산시  일반용   15792   208345989
138  201501-201506  경상북도  경산시   합계   23986  1360738629
139  201501-201506  경상북도  경주시  일반용   23410   314295184
139  201501-201506  경상북도  경주시   합계   30955  2103343262
140  201501-201506  경상북도  고령군  일반용    2911    28210027
140  201501-201506  경상북도  고령군   합계    4913   610433077
141  201501-201506  경상북도  구미시  일반용   26128   352475704
141  201501-201506  경상북도  구미시   합계   31875  4861566829
142  201501-201506  경상북도  군위군  일반용    1985    26292605
142  201501-201506  경상북도  군위군   합계    4580   163291709
143  201501-201506  경상북도  김천시  일반용    9413   116967626
143  201501-201506  경상북도  김천시   합계   16477  1016224632
144  201501-201506  경상북도  문경시  일반용    6184    72978108
144  201501-201506  경상북도  문경시   합계    9914   295223151
145  201501-201506  경상북도  봉화군  일반용    2855    24387171
145  201501-201506  경상북도  봉화군   합계    6641   945968767
146  201501-201506  경상북도  상주시   합계   15873   351956940
146  201501-201506  경상북도  상주시  일반용    7472    81152077
147  201501-201506  경상북도  성주군   합계    7996   470184078
147  201501-201506  경상북도  성주군  일반용    3739    37554990
148  201501-201506  경상북도  안동시   합계   19404   526834613
148  201501-201506  경상북도  안동시  일반용   12644   172459550
149  201501-201506  경상북도  영덕군   합계    6611   145019815
149  201501-201506  경상북도  영덕군  일반용    4879    54688569
150  201501-201506  경상북도  영양군   합계    3886    57620766
150  201501-201506  경상북도  영양군  일반용    1581    13722176
151  201501-201506  경상북도  영주시   합계   13035   664184882
151  201501-201506  경상북도  영주시  일반용    9101    92191281
152  201501-201506  경상북도  영천시  일반용    7647    89470717
152  201501-201506  경상북도  영천시   합계   13796   738212593
153  201501-201506  경상북도  예천군   합계    8868   153513518
153  201501-201506  경상북도  예천군  일반용    3206    37960895
154  201501-201506  경상북도  울릉군   합계    1263    27458449
154  201501-201506  경상북도  울릉군  일반용    1574    16831697
155  201501-201506  경상북도  울진군  일반용    5129    77652229
155  201501-201506  경상북도  울진군   합계    8206   235457770
156  201501-201506  경상북도  의성군   합계   11074   205703230
156  201501-201506  경상북도  의성군  일반용    4052    37445574
157  201501-201506  경상북도  청도군   합계    8858   233443680
157  201501-201506  경상북도  청도군  일반용    3608    40055574
158  201501-201506  경상북도  청송군   합계    5939    92355914
158  201501-201506  경상북도  청송군  일반용    2660    26438976
159  201501-201506  경상북도  칠곡군   합계   12674  1029940506
159  201501-201506  경상북도  칠곡군  일반용    9725   136025143
160  201501-201506  경상북도  포항시  일반용   37552   468884586
160  201501-201506  경상북도  포항시   합계   41307  6742565074

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[208345989,
 314295184,
 28210027,
 352475704,
 26292605,
 116967626,
 72978108,
 24387171,
 81152077,
 37554990,
 172459550,
 54688569,
 13722176,
 92191281,
 89470717,
 37960895,
 16831697,
 77652229,
 37445574,
 40055574,
 26438976,
 136025143,
 468884586]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1360738629,
 2103343262,
 610433077,
 4861566829,
 163291709,
 1016224632,
 295223151,
 945968767,
 351956940,
 470184078,
 526834613,
 145019815,
 57620766,
 664184882,
 738212593,
 153513518,
 27458449,
 235457770,
 205703230,
 233443680,
 92355914,
 1029940506,
 6742565074]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[15.31, 14.94, 4.62, 7.25, 16.1, 11.51, 24.72, 2.58, 23.06, 7.99, 32.74, 37.71, 23.81, 13.88, 12.12, 24.73, 61.3, 32.98, 18.2, 17.16, 28.63, 13.21, 6.95]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    15
1    15
2     5
3     7
4    16
5    12
6    25
7     3
8    23
9     8
10   33
11   38
12   24
13   14
14   12
15   25
16   61
17   33
18   18
19   17
20   29
21   13
22    7
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   경산시  일반용  15
1   경주시  일반용  15
2   고령군  일반용   5
3   구미시  일반용   7
4   군위군  일반용  16
5   김천시  일반용  12
6   문경시  일반용  25
7   봉화군  일반용   3
8   상주시  일반용  23
9   성주군  일반용   8
10  안동시  일반용  33
11  영덕군  일반용  38
12  영양군  일반용  24
13  영주시  일반용  14
14  영천시  일반용  12
15  예천군  일반용  25
16  울릉군  일반용  61
17  울진군  일반용  33
18  의성군  일반용  18
19  청도군  일반용  17
20  청송군  일반용  29
21  칠곡군  일반용  13
22  포항시  일반용   7

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201501-201506  경상북도  경산시  일반용   15792   208345989  15
1   201501-201506  경상북도  경산시   합계   23986  1360738629 NaN
2   201501-201506  경상북도  경주시  일반용   23410   314295184  15
3   201501-201506  경상북도  경주시   합계   30955  2103343262 NaN
4   201501-201506  경상북도  고령군  일반용    2911    28210027   5
5   201501-201506  경상북도  고령군   합계    4913   610433077 NaN
6   201501-201506  경상북도  구미시  일반용   26128   352475704   7
7   201501-201506  경상북도  구미시   합계   31875  4861566829 NaN
8   201501-201506  경상북도  군위군  일반용    1985    26292605  16
9   201501-201506  경상북도  군위군   합계    4580   163291709 NaN
10  201501-201506  경상북도  김천시  일반용    9413   116967626  12
11  201501-201506  경상북도  김천시   합계   16477  1016224632 NaN
12  201501-201506  경상북도  문경시  일반용    6184    72978108  25
13  201501-201506  경상북도  문경시   합계    9914   295223151 NaN
14  201501-201506  경상북도  봉화군  일반용    2855    24387171   3
15  201501-201506  경상북도  봉화군   합계    6641   945968767 NaN
17  201501-201506  경상북도  상주시  일반용    7472    81152077  23
16  201501-201506  경상북도  상주시   합계   15873   351956940 NaN
19  201501-201506  경상북도  성주군  일반용    3739    37554990   8
18  201501-201506  경상북도  성주군   합계    7996   470184078 NaN
21  201501-201506  경상북도  안동시  일반용   12644   172459550  33
20  201501-201506  경상북도  안동시   합계   19404   526834613 NaN
23  201501-201506  경상북도  영덕군  일반용    4879    54688569  38
22  201501-201506  경상북도  영덕군   합계    6611   145019815 NaN
25  201501-201506  경상북도  영양군  일반용    1581    13722176  24
24  201501-201506  경상북도  영양군   합계    3886    57620766 NaN
27  201501-201506  경상북도  영주시  일반용    9101    92191281  14
26  201501-201506  경상북도  영주시   합계   13035   664184882 NaN
28  201501-201506  경상북도  영천시  일반용    7647    89470717  12
29  201501-201506  경상북도  영천시   합계   13796   738212593 NaN
31  201501-201506  경상북도  예천군  일반용    3206    37960895  25
30  201501-201506  경상북도  예천군   합계    8868   153513518 NaN
33  201501-201506  경상북도  울릉군  일반용    1574    16831697  61
32  201501-201506  경상북도  울릉군   합계    1263    27458449 NaN
34  201501-201506  경상북도  울진군  일반용    5129    77652229  33
35  201501-201506  경상북도  울진군   합계    8206   235457770 NaN
37  201501-201506  경상북도  의성군  일반용    4052    37445574  18
36  201501-201506  경상북도  의성군   합계   11074   205703230 NaN
39  201501-201506  경상북도  청도군  일반용    3608    40055574  17
38  201501-201506  경상북도  청도군   합계    8858   233443680 NaN
41  201501-201506  경상북도  청송군  일반용    2660    26438976  29
40  201501-201506  경상북도  청송군   합계    5939    92355914 NaN
43  201501-201506  경상북도  칠곡군  일반용    9725   136025143  13
42  201501-201506  경상북도  칠곡군   합계   12674  1029940506 NaN
44  201501-201506  경상북도  포항시  일반용   37552   468884586   7
45  201501-201506  경상북도  포항시   합계   41307  6742565074 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)