In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라북도_계약종별_전력사용량_월별_17하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라북도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2017년 07 월 ~ 2017년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,전라북도,전체(시 / 군 / 구),주택용,"636,916","198,214,604","20,598,474,314",103.9
4,201707,전라북도,전체(시 / 군 / 구),일반용,"135,503","306,687,627","45,846,704,636",149.5
...,...,...,...,...,...,...,...,...
715,201712,전라북도,진안군,산업용,716,"3,189,441","437,970,540",137.3
716,201712,전라북도,진안군,심 야,"1,964","3,698,123","277,382,394",75
717,201712,전라북도,진안군,일반용,"2,053","4,224,026","573,424,995",135.8
718,201712,전라북도,진안군,주택용,"13,718","2,464,393","274,470,261",111.4
719,201712,전라북도,진안군,합계,"29,292","19,685,921","1,935,137,652",98.3

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,전라북도,전체(시 / 군 / 구),주택용,"636,916","198,214,604","20,598,474,314",103.9
4,201707,전라북도,전체(시 / 군 / 구),일반용,"135,503","306,687,627","45,846,704,636",149.5
5,201707,전라북도,전체(시 / 군 / 구),교육용,"1,223","28,956,230","3,538,530,582",122.2
6,201707,전라북도,전체(시 / 군 / 구),산업용,"14,627","1,141,856,200","133,032,060,739",116.5
...,...,...,...,...,...,...,...,...
715,201712,전라북도,진안군,산업용,716,"3,189,441","437,970,540",137.3
716,201712,전라북도,진안군,심 야,"1,964","3,698,123","277,382,394",75
717,201712,전라북도,진안군,일반용,"2,053","4,224,026","573,424,995",135.8
718,201712,전라북도,진안군,주택용,"13,718","2,464,393","274,470,261",111.4
719,201712,전라북도,진안군,합계,"29,292","19,685,921","1,935,137,652",98.3

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,전라북도,전체(시 / 군 / 구),주택용,"636,916","198,214,604","20,598,474,314",103.9
4,201707,전라북도,전체(시 / 군 / 구),일반용,"135,503","306,687,627","45,846,704,636",149.5
5,201707,전라북도,전체(시 / 군 / 구),교육용,"1,223","28,956,230","3,538,530,582",122.2
6,201707,전라북도,전체(시 / 군 / 구),산업용,"14,627","1,141,856,200","133,032,060,739",116.5
7,201707,전라북도,전체(시 / 군 / 구),농사용,"140,923","115,783,906","5,551,368,805",47.9
...,...,...,...,...,...,...,...,...
715,201712,전라북도,진안군,산업용,716,"3,189,441","437,970,540",137.3
716,201712,전라북도,진안군,심 야,"1,964","3,698,123","277,382,394",75
717,201712,전라북도,진안군,일반용,"2,053","4,224,026","573,424,995",135.8
718,201712,전라북도,진안군,주택용,"13,718","2,464,393","274,470,261",111.4
719,201712,전라북도,진안군,합계,"29,292","19,685,921","1,935,137,652",98.3

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,전라북도,전체(시 / 군 / 구),주택용,"636,916","198,214,604","20,598,474,314",103.9
4,201707,전라북도,전체(시 / 군 / 구),일반용,"135,503","306,687,627","45,846,704,636",149.5
5,201707,전라북도,전체(시 / 군 / 구),교육용,"1,223","28,956,230","3,538,530,582",122.2
6,201707,전라북도,전체(시 / 군 / 구),산업용,"14,627","1,141,856,200","133,032,060,739",116.5
7,201707,전라북도,전체(시 / 군 / 구),농사용,"140,923","115,783,906","5,551,368,805",47.9
8,201707,전라북도,전체(시 / 군 / 구),가로등,"132,454","14,925,330","1,816,919,587",121.7
9,201707,전라북도,전체(시 / 군 / 구),심 야,"65,950","21,587,116","1,258,074,281",58.3
10,201708,전라북도,전체(시 / 군 / 구),주택용,"637,731","249,005,163","30,222,085,359",121.4
11,201708,전라북도,전체(시 / 군 / 구),일반용,"135,822","356,446,058","51,412,982,870",144.2
12,201708,전라북도,전체(시 / 군 / 구),교육용,"1,221","29,028,796","3,637,945,919",125.3
13,201708,전라북도,전체(시 / 군 / 구),산업용,"14,659","1,153,467,488","134,349,630,435",116.5
14,201708,전라북도,전체(시 / 군 / 구),농사용,"142,104","142,269,992","6,715,678,985",47.2
15,201708,전라북도,전체(시 / 군 / 구),가로등,"132,673","15,658,676","1,832,521,402",117.0
16,201708,전라북도,전체(시 / 군 / 구),심 야,"65,781","17,801,825","1,066,354,448",59.9
17,201709,전라북도,전체(시 / 군 / 구),주택용,"638,998","204,606,147","21,593,309,388",105.5
18,201709,전라북도,전체(시 / 군 / 구),일반용,"135,889","303,569,798","40,509,897,888",133.4
19,201709,전라북도,전체(시 / 군 / 구),교육용,"1,219","27,200,566","3,060,128,012",112.5
20,201709,전라북도,전체(시 / 군 / 구),산업용,"14,698","1,176,350,876","109,773,214,061",93.3
21,201709,전라북도,전체(시 / 군 / 구),농사용,"143,089","127,860,718","6,158,005,135",48.2
22,201709,전라북도,전체(시 / 군 / 구),가로등,"132,916","16,527,749","1,869,006,836",113.1
23,201709,전라북도,전체(시 / 군 / 구),심 야,"65,599","19,098,199","1,099,696,400",57.6
24,201710,전라북도,전체(시 / 군 / 구),주택용,"639,993","182,552,519","17,926,730,464",98.2
25,201710,전라북도,전체(시 / 군 / 구),일반용,"135,846","251,980,288","30,566,906,479",121.3
26,201710,전라북도,전체(시 / 군 / 구),교육용,"1,217","21,489,194","2,106,927,098",98.0
27,201710,전라북도,전체(시 / 군 / 구),산업용,"14,747","1,101,501,757","99,041,929,201",89.9
28,201710,전라북도,전체(시 / 군 / 구),농사용,"143,638","104,990,826","5,308,589,032",50.6
29,201710,전라북도,전체(시 / 군 / 구),가로등,"133,018","17,609,552","1,883,679,424",107.0
30,201710,전라북도,전체(시 / 군 / 구),심 야,"65,436","30,201,959","1,667,664,638",55.2
31,201711,전라북도,전체(시 / 군 / 구),주택용,"641,052","193,757,732","19,852,321,456",102.5
32,201711,전라북도,전체(시 / 군 / 구),일반용,"136,124","270,136,980","35,822,730,363",132.6
33,201711,전라북도,전체(시 / 군 / 구),교육용,"1,217","29,211,797","3,072,398,237",105.2
34,201711,전라북도,전체(시 / 군 / 구),산업용,"14,771","1,114,999,567","127,785,820,550",114.6
35,201711,전라북도,전체(시 / 군 / 구),농사용,"210,753","162,410,301","7,020,799,199",43.2
36,201711,전라북도,전체(시 / 군 / 구),가로등,"133,157","18,608,748","1,943,371,916",104.4
37,201711,전라북도,전체(시 / 군 / 구),심 야,"65,374","65,627,492","4,146,549,369",63.2
38,201712,전라북도,전체(시 / 군 / 구),주택용,"642,074","205,348,071","21,811,012,526",106.2
39,201712,전라북도,전체(시 / 군 / 구),일반용,"136,645","332,522,172","45,294,138,868",136.2
40,201712,전라북도,전체(시 / 군 / 구),교육용,"1,218","43,117,190","4,254,187,858",98.7
41,201712,전라북도,전체(시 / 군 / 구),산업용,"14,811","1,175,224,755","132,475,632,335",112.7
42,201712,전라북도,전체(시 / 군 / 구),농사용,"185,084","165,991,146","7,408,112,562",44.6
43,201712,전라북도,전체(시 / 군 / 구),가로등,"133,567","19,228,724","1,955,665,204",101.7
44,201712,전라북도,전체(시 / 군 / 구),심 야,"65,276","119,114,253","8,837,606,110",74.2
45,합계,합계,합계,합계,"6,905,013","11,292,528,087","1,205,125,362,971",106.7

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_15048\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201707  전라북도  일반용  135,503   306,687,627
11  201708  전라북도  일반용  135,822   356,446,058
18  201709  전라북도  일반용  135,889   303,569,798
25  201710  전라북도  일반용  135,846   251,980,288
32  201711  전라북도  일반용  136,124   270,136,980
39  201712  전라북도  일반용  136,645   332,522,172

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
53   201707  전라북도  고창군  일반용  4,473   8,166,557
165  201708  전라북도  고창군  일반용  4,477   9,816,680
277  201709  전라북도  고창군  일반용  4,486   8,502,870
389  201710  전라북도  고창군  일반용  4,503   7,270,424
501  201711  전라북도  고창군  일반용  4,515   7,786,598
..      ...   ...  ...  ...     ...         ...
269  201708  전라북도  진안군  일반용  2,023   3,670,695
381  201709  전라북도  진안군  일반용  2,031   3,303,492
493  201710  전라북도  진안군  일반용  2,039   2,970,899
605  201711  전라북도  진안군  일반용  2,043   3,448,721
717  201712  전라북도  진안군  일반용  2,053   4,224,026

[84 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라북도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['고창군',
 '군산시',
 '김제시',
 '남원시',
 '무주군',
 '부안군',
 '순창군',
 '완주군',
 '익산시',
 '임실군',
 '장수군',
 '전주시',
 '정읍시',
 '진안군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55   201707  전라북도  고창군   합계  55,245   41,950,086
167  201708  전라북도  고창군   합계  55,348   46,808,186
279  201709  전라북도  고창군   합계  55,512   43,407,156
391  201710  전라북도  고창군   합계  55,596   40,191,777
503  201711  전라북도  고창군   합계  58,828   49,463,069
..      ...   ...  ...  ...      ...          ...
271  201708  전라북도  진안군   합계  28,862   15,053,112
383  201709  전라북도  진안군   합계  29,051   15,124,695
495  201710  전라북도  진안군   합계  29,141   14,171,611
607  201711  전라북도  진안군   합계  31,507   17,471,916
719  201712  전라북도  진안군   합계  29,292   19,685,921

[84 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[41950086, 46808186, 43407156, 40191777, 49463069, 69383931]
[662857412, 709071336, 712703872, 678973558, 659471279, 724543392]
[72438646, 79831376, 74728074, 65004159, 85677369, 94212741]
[45871908, 52349718, 46843671, 41896733, 48744678, 62537662]
[14230824, 15394552, 14824437, 13874798, 17724032, 23522704]
[37735407, 43227943, 38328196, 33401293, 42877816, 44471877]
[20928314, 22499175, 21581706, 18712330, 25105405, 23328333]
[137125234, 138576705, 134247252, 114866596, 140018910, 151051644]
[254619466, 268895298, 248315606, 218678711, 248310878, 269890134]
[22320476, 24364903, 23374781, 21104922, 24068423, 30327017]
[13822051, 15101255, 14619798, 14713048, 19005941, 24073654]
[373214151, 406278197, 367938079, 326031167, 346480284, 390220100]
[117533095, 126226242, 119176730, 108705392, 130332617, 133297201]
[13363943, 15053112, 15124695, 14171611, 17471916, 19685921]
전라북도 지역별 합계 :  [291204205, 4147620849, 471892365, 298244370, 99571347, 240042532, 132155263, 815886341, 1508710093, 145560522, 101335747, 2210161978, 735271277, 94871198]
전라북도 고객호수 평균:  [9865, 22907, 12522, 12751, 4542, 8780, 5764, 11078, 27885, 5436, 4336, 44934, 16097, 4904]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201707  전라북도  고창군   합계  55,245   41,950,086
1          201708  전라북도  고창군   합계  55,348   46,808,186
2          201709  전라북도  고창군   합계  55,512   43,407,156
3          201710  전라북도  고창군   합계  55,596   40,191,777
4          201711  전라북도  고창군   합계  58,828   49,463,069
..            ...   ...  ...  ...      ...          ...
93  201707-201712  전라북도  임실군   합계     5436    145560522
94  201707-201712  전라북도  장수군   합계     4336    101335747
95  201707-201712  전라북도  전주시   합계    44934   2210161978
96  201707-201712  전라북도  정읍시   합계    16097    735271277
97  201707-201712  전라북도  진안군   합계     4904     94871198

[98 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201707-201712']
Hap

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  201707-201712  전라북도  고창군   합계    9865   291204205
85  201707-201712  전라북도  군산시   합계   22907  4147620849
86  201707-201712  전라북도  김제시   합계   12522   471892365
87  201707-201712  전라북도  남원시   합계   12751   298244370
88  201707-201712  전라북도  무주군   합계    4542    99571347
89  201707-201712  전라북도  부안군   합계    8780   240042532
90  201707-201712  전라북도  순창군   합계    5764   132155263
91  201707-201712  전라북도  완주군   합계   11078   815886341
92  201707-201712  전라북도  익산시   합계   27885  1508710093
93  201707-201712  전라북도  임실군   합계    5436   145560522
94  201707-201712  전라북도  장수군   합계    4336   101335747
95  201707-201712  전라북도  전주시   합계   44934  2210161978
96  201707-201712  전라북도  정읍시   합계   16097   735271277
97  201707-201712  전라북도  진안군   합계    4904    94871198

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
53   201707  전라북도  고창군  일반용  4,473   8,166,557
165  201708  전라북도  고창군  일반용  4,477   9,816,680
277  201709  전라북도  고창군  일반용  4,486   8,502,870
389  201710  전라북도  고창군  일반용  4,503   7,270,424
501  201711  전라북도  고창군  일반용  4,515   7,786,598
..      ...   ...  ...  ...     ...         ...
269  201708  전라북도  진안군  일반용  2,023   3,670,695
381  201709  전라북도  진안군  일반용  2,031   3,303,492
493  201710  전라북도  진안군  일반용  2,039   2,970,899
605  201711  전라북도  진안군  일반용  2,043   3,448,721
717  201712  전라북도  진안군  일반용  2,053   4,224,026

[84 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[8166557, 9816680, 8502870, 7270424, 7786598, 9192759]
[51228580, 59627024, 51719953, 43076576, 44187890, 53347257]
[12981944, 15285049, 13290956, 11070320, 12028220, 14833309]
[12728770, 15542614, 13145274, 11294813, 12582312, 15532529]
[5956633, 6644789, 5853196, 5265937, 7089332, 11327676]
[10577509, 13140888, 10976217, 9201652, 9871250, 11794218]
[3546106, 4057873, 3356194, 2985745, 3435479, 4094815]
[18759617, 20720147, 17482200, 14823512, 16698424, 20200382]
[42088694, 49781329, 42668880, 34905707, 36745932, 45170976]
[4432686, 5034850, 4203116, 3778276, 4469179, 5462437]
[2746721, 3233222, 2836180, 2654818, 2951204, 3755416]
[114583125, 131715858, 110941724, 89656201, 94301024, 115982244]
[15717462, 18175040, 15289546, 13025408, 14541415, 17604128]
[3173223, 3670695, 3303492, 2970899, 3448721, 4224026]
전라북도 지역별 일반용 합계 :  [50735888, 303187280, 79489798, 80826312, 42137563, 65561734, 21476212, 108684282, 251361518, 27380544, 18177561, 657180176, 94352999, 20791056]
전라북도 고객호수 평균:  [4491, 20257, 6294, 7233, 2614, 5504, 2229, 6966, 20361, 2232, 1638, 45145, 8970, 2033]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_15048\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
0          201707  전라북도  고창군  일반용  4,473   8,166,557
1          201708  전라북도  고창군  일반용  4,477   9,816,680
2          201709  전라북도  고창군  일반용  4,486   8,502,870
3          201710  전라북도  고창군  일반용  4,503   7,270,424
4          201711  전라북도  고창군  일반용  4,515   7,786,598
..            ...   ...  ...  ...     ...         ...
93  201707-201712  전라북도  임실군  일반용    2232    27380544
94  201707-201712  전라북도  장수군  일반용    1638    18177561
95  201707-201712  전라북도  전주시  일반용   45145   657180176
96  201707-201712  전라북도  정읍시  일반용    8970    94352999
97  201707-201712  전라북도  진안군  일반용    2033    20791056

[98 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201707-201712']
GyeonGiHap2

               년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
84  201707-201712  전라북도  고창군  일반용    4491   50735888
85  201707-201712  전라북도  군산시  일반용   20257  303187280
86  201707-201712  전라북도  김제시  일반용    6294   79489798
87  201707-201712  전라북도  남원시  일반용    7233   80826312
88  201707-201712  전라북도  무주군  일반용    2614   42137563
89  201707-201712  전라북도  부안군  일반용    5504   65561734
90  201707-201712  전라북도  순창군  일반용    2229   21476212
91  201707-201712  전라북도  완주군  일반용    6966  108684282
92  201707-201712  전라북도  익산시  일반용   20361  251361518
93  201707-201712  전라북도  임실군  일반용    2232   27380544
94  201707-201712  전라북도  장수군  일반용    1638   18177561
95  201707-201712  전라북도  전주시  일반용   45145  657180176
96  201707-201712  전라북도  정읍시  일반용    8970   94352999
97  201707-201712  전라북도  진안군  일반용    2033   20791056

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  201707-201712  전라북도  고창군  일반용    4491    50735888
84  201707-201712  전라북도  고창군   합계    9865   291204205
85  201707-201712  전라북도  군산시  일반용   20257   303187280
85  201707-201712  전라북도  군산시   합계   22907  4147620849
86  201707-201712  전라북도  김제시  일반용    6294    79489798
86  201707-201712  전라북도  김제시   합계   12522   471892365
87  201707-201712  전라북도  남원시  일반용    7233    80826312
87  201707-201712  전라북도  남원시   합계   12751   298244370
88  201707-201712  전라북도  무주군  일반용    2614    42137563
88  201707-201712  전라북도  무주군   합계    4542    99571347
89  201707-201712  전라북도  부안군  일반용    5504    65561734
89  201707-201712  전라북도  부안군   합계    8780   240042532
90  201707-201712  전라북도  순창군  일반용    2229    21476212
90  201707-201712  전라북도  순창군   합계    5764   132155263
91  201707-201712  전라북도  완주군   합계   11078   815886341
91  201707-201712  전라북도  완주군  일반용    6966   108684282
92  201707-201712  전라북도  익산시  일반용   20361   251361518
92  201707-201712  전라북도  익산시   합계   27885  1508710093
93  201707-201712  전라북도  임실군   합계    5436   145560522
93  201707-201712  전라북도  임실군  일반용    2232    27380544
94  201707-201712  전라북도  장수군   합계    4336   101335747
94  201707-201712  전라북도  장수군  일반용    1638    18177561
95  201707-201712  전라북도  전주시   합계   44934  2210161978
95  201707-201712  전라북도  전주시  일반용   45145   657180176
96  201707-201712  전라북도  정읍시   합계   16097   735271277
96  201707-201712  전라북도  정읍시  일반용    8970    94352999
97  201707-201712  전라북도  진안군  일반용    2033    20791056
97  201707-201712  전라북도  진안군   합계    4904    94871198

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[50735888,
 303187280,
 79489798,
 80826312,
 42137563,
 65561734,
 21476212,
 108684282,
 251361518,
 27380544,
 18177561,
 657180176,
 94352999,
 20791056]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[291204205,
 4147620849,
 471892365,
 298244370,
 99571347,
 240042532,
 132155263,
 815886341,
 1508710093,
 145560522,
 101335747,
 2210161978,
 735271277,
 94871198]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[17.42, 7.31, 16.84, 27.1, 42.32, 27.31, 16.25, 13.32, 16.66, 18.81, 17.94, 29.73, 12.83, 21.92]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    17
1     7
2    17
3    27
4    42
5    27
6    16
7    13
8    17
9    19
10   18
11   30
12   13
13   22
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   고창군  일반용  17
1   군산시  일반용   7
2   김제시  일반용  17
3   남원시  일반용  27
4   무주군  일반용  42
5   부안군  일반용  27
6   순창군  일반용  16
7   완주군  일반용  13
8   익산시  일반용  17
9   임실군  일반용  19
10  장수군  일반용  18
11  전주시  일반용  30
12  정읍시  일반용  13
13  진안군  일반용  22

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201707-201712  전라북도  고창군  일반용    4491    50735888  17
1   201707-201712  전라북도  고창군   합계    9865   291204205 NaN
2   201707-201712  전라북도  군산시  일반용   20257   303187280   7
3   201707-201712  전라북도  군산시   합계   22907  4147620849 NaN
4   201707-201712  전라북도  김제시  일반용    6294    79489798  17
5   201707-201712  전라북도  김제시   합계   12522   471892365 NaN
6   201707-201712  전라북도  남원시  일반용    7233    80826312  27
7   201707-201712  전라북도  남원시   합계   12751   298244370 NaN
8   201707-201712  전라북도  무주군  일반용    2614    42137563  42
9   201707-201712  전라북도  무주군   합계    4542    99571347 NaN
10  201707-201712  전라북도  부안군  일반용    5504    65561734  27
11  201707-201712  전라북도  부안군   합계    8780   240042532 NaN
12  201707-201712  전라북도  순창군  일반용    2229    21476212  16
13  201707-201712  전라북도  순창군   합계    5764   132155263 NaN
15  201707-201712  전라북도  완주군  일반용    6966   108684282  13
14  201707-201712  전라북도  완주군   합계   11078   815886341 NaN
16  201707-201712  전라북도  익산시  일반용   20361   251361518  17
17  201707-201712  전라북도  익산시   합계   27885  1508710093 NaN
19  201707-201712  전라북도  임실군  일반용    2232    27380544  19
18  201707-201712  전라북도  임실군   합계    5436   145560522 NaN
21  201707-201712  전라북도  장수군  일반용    1638    18177561  18
20  201707-201712  전라북도  장수군   합계    4336   101335747 NaN
23  201707-201712  전라북도  전주시  일반용   45145   657180176  30
22  201707-201712  전라북도  전주시   합계   44934  2210161978 NaN
25  201707-201712  전라북도  정읍시  일반용    8970    94352999  13
24  201707-201712  전라북도  정읍시   합계   16097   735271277 NaN
26  201707-201712  전라북도  진안군  일반용    2033    20791056  22
27  201707-201712  전라북도  진안군   합계    4904    94871198 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1707-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)