In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라남도_계약종별 전력사용량 월별_14하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 07 월 ~ 2014년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,전라남도,전체(시 / 군 / 구),주택용,"698,524","176,181,691","20,108,138,092",114.1
4,201407,전라남도,전체(시 / 군 / 구),일반용,"136,762","255,775,326","39,193,275,099",153.2
...,...,...,...,...,...,...,...,...
1099,201412,전라남도,화순군,산업용,738,"13,849,212","1,779,678,629",128.5
1100,201412,전라남도,화순군,심 야,"1,923","3,244,683","237,489,750",73.2
1101,201412,전라남도,화순군,일반용,"4,094","11,709,948","1,578,609,403",134.8
1102,201412,전라남도,화순군,주택용,"23,953","6,326,777","739,870,795",116.9
1103,201412,전라남도,화순군,합계,"45,931","48,028,570","5,064,273,203",105.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,전라남도,전체(시 / 군 / 구),주택용,"698,524","176,181,691","20,108,138,092",114.1
4,201407,전라남도,전체(시 / 군 / 구),일반용,"136,762","255,775,326","39,193,275,099",153.2
5,201407,전라남도,전체(시 / 군 / 구),교육용,"1,317","20,008,651","2,840,794,589",142.0
6,201407,전라남도,전체(시 / 군 / 구),산업용,"18,742","1,884,819,454","206,747,310,631",109.7
...,...,...,...,...,...,...,...,...
1099,201412,전라남도,화순군,산업용,738,"13,849,212","1,779,678,629",128.5
1100,201412,전라남도,화순군,심 야,"1,923","3,244,683","237,489,750",73.2
1101,201412,전라남도,화순군,일반용,"4,094","11,709,948","1,578,609,403",134.8
1102,201412,전라남도,화순군,주택용,"23,953","6,326,777","739,870,795",116.9
1103,201412,전라남도,화순군,합계,"45,931","48,028,570","5,064,273,203",105.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,전라남도,전체(시 / 군 / 구),주택용,"698,524","176,181,691","20,108,138,092",114.1
4,201407,전라남도,전체(시 / 군 / 구),일반용,"136,762","255,775,326","39,193,275,099",153.2
5,201407,전라남도,전체(시 / 군 / 구),교육용,"1,317","20,008,651","2,840,794,589",142.0
6,201407,전라남도,전체(시 / 군 / 구),산업용,"18,742","1,884,819,454","206,747,310,631",109.7
7,201407,전라남도,전체(시 / 군 / 구),농사용,"237,099","200,399,706","9,364,598,342",46.7
...,...,...,...,...,...,...,...,...
1099,201412,전라남도,화순군,산업용,738,"13,849,212","1,779,678,629",128.5
1100,201412,전라남도,화순군,심 야,"1,923","3,244,683","237,489,750",73.2
1101,201412,전라남도,화순군,일반용,"4,094","11,709,948","1,578,609,403",134.8
1102,201412,전라남도,화순군,주택용,"23,953","6,326,777","739,870,795",116.9
1103,201412,전라남도,화순군,합계,"45,931","48,028,570","5,064,273,203",105.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,전라남도,전체(시 / 군 / 구),주택용,"698,524","176,181,691","20,108,138,092",114.1
4,201407,전라남도,전체(시 / 군 / 구),일반용,"136,762","255,775,326","39,193,275,099",153.2
5,201407,전라남도,전체(시 / 군 / 구),교육용,"1,317","20,008,651","2,840,794,589",142.0
6,201407,전라남도,전체(시 / 군 / 구),산업용,"18,742","1,884,819,454","206,747,310,631",109.7
7,201407,전라남도,전체(시 / 군 / 구),농사용,"237,099","200,399,706","9,364,598,342",46.7
8,201407,전라남도,전체(시 / 군 / 구),가로등,"133,277","15,339,355","1,937,361,229",126.3
9,201407,전라남도,전체(시 / 군 / 구),심 야,"50,501","21,394,625","1,209,442,799",56.5
10,201408,전라남도,전체(시 / 군 / 구),주택용,"699,041","198,865,512","25,221,231,469",126.8
11,201408,전라남도,전체(시 / 군 / 구),일반용,"137,212","295,157,232","43,360,588,950",146.9
12,201408,전라남도,전체(시 / 군 / 구),교육용,"1,315","19,568,961","2,802,812,889",143.2
13,201408,전라남도,전체(시 / 군 / 구),산업용,"18,784","1,800,920,591","191,976,460,730",106.6
14,201408,전라남도,전체(시 / 군 / 구),농사용,"238,438","242,755,351","11,214,654,959",46.2
15,201408,전라남도,전체(시 / 군 / 구),가로등,"133,899","16,064,403","1,952,432,123",121.5
16,201408,전라남도,전체(시 / 군 / 구),심 야,"50,412","19,434,116","1,107,428,730",57.0
17,201409,전라남도,전체(시 / 군 / 구),주택용,"699,469","188,475,130","22,669,446,004",120.3
18,201409,전라남도,전체(시 / 군 / 구),일반용,"137,254","266,843,847","35,844,540,157",134.3
19,201409,전라남도,전체(시 / 군 / 구),교육용,"1,320","19,119,312","2,427,656,196",127.0
20,201409,전라남도,전체(시 / 군 / 구),산업용,"18,812","1,871,751,210","163,130,118,136",87.2
21,201409,전라남도,전체(시 / 군 / 구),농사용,"239,475","230,608,345","10,696,972,373",46.4
22,201409,전라남도,전체(시 / 군 / 구),가로등,"134,249","17,047,573","2,000,510,352",117.3
23,201409,전라남도,전체(시 / 군 / 구),심 야,"50,350","20,467,794","1,158,400,952",56.6
24,201410,전라남도,전체(시 / 군 / 구),주택용,"700,249","172,176,362","19,034,322,146",110.6
25,201410,전라남도,전체(시 / 군 / 구),일반용,"137,337","236,858,190","28,193,671,938",119.0
26,201410,전라남도,전체(시 / 군 / 구),교육용,"1,319","18,192,524","2,040,356,173",112.2
27,201410,전라남도,전체(시 / 군 / 구),산업용,"18,815","2,098,839,115","183,967,708,999",87.7
28,201410,전라남도,전체(시 / 군 / 구),농사용,"240,262","203,479,326","9,571,595,072",47.0
29,201410,전라남도,전체(시 / 군 / 구),가로등,"134,435","18,458,542","2,035,610,504",110.3
30,201410,전라남도,전체(시 / 군 / 구),심 야,"50,317","26,207,309","1,457,388,780",55.6
31,201411,전라남도,전체(시 / 군 / 구),주택용,"700,885","186,741,041","22,276,884,773",119.3
32,201411,전라남도,전체(시 / 군 / 구),일반용,"137,930","247,931,277","32,061,285,345",129.3
33,201411,전라남도,전체(시 / 군 / 구),교육용,"1,317","20,699,916","2,429,602,654",117.4
34,201411,전라남도,전체(시 / 군 / 구),산업용,"18,850","1,781,563,968","195,952,097,253",110.0
35,201411,전라남도,전체(시 / 군 / 구),농사용,"355,586","277,631,766","11,969,934,808",43.1
36,201411,전라남도,전체(시 / 군 / 구),가로등,"135,022","19,587,432","2,152,476,946",109.9
37,201411,전라남도,전체(시 / 군 / 구),심 야,"50,272","53,397,122","3,397,005,733",63.6
38,201412,전라남도,전체(시 / 군 / 구),주택용,"701,407","195,477,581","24,405,405,045",124.9
39,201412,전라남도,전체(시 / 군 / 구),일반용,"138,163","285,881,106","39,478,040,420",138.1
40,201412,전라남도,전체(시 / 군 / 구),교육용,"1,315","29,114,351","3,360,322,557",115.4
41,201412,전라남도,전체(시 / 군 / 구),산업용,"18,866","1,900,887,068","206,274,304,423",108.5
42,201412,전라남도,전체(시 / 군 / 구),농사용,"263,504","248,959,929","11,705,937,497",47.0
43,201412,전라남도,전체(시 / 군 / 구),가로등,"135,195","20,207,407","2,095,633,437",103.7
44,201412,전라남도,전체(시 / 군 / 구),심 야,"50,214","88,331,242","6,629,721,042",75.1
45,합계,합계,합계,합계,"7,827,512","15,911,620,759","1,607,453,480,346",101

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_21780\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201407  전라남도  일반용  136,762   255,775,326
11  201408  전라남도  일반용  137,212   295,157,232
18  201409  전라남도  일반용  137,254   266,843,847
25  201410  전라남도  일반용  137,337   236,858,190
32  201411  전라남도  일반용  137,930   247,931,277
39  201412  전라남도  일반용  138,163   285,881,106

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    201407  전라남도  강진군  일반용  2,906    4,231,827
229   201408  전라남도  강진군  일반용  2,892    4,817,754
405   201409  전라남도  강진군  일반용  2,891    4,299,855
581   201410  전라남도  강진군  일반용  2,875    3,885,818
757   201411  전라남도  강진군  일반용  2,878    4,319,633
...      ...   ...  ...  ...     ...          ...
397   201408  전라남도  화순군  일반용  4,152   12,535,281
573   201409  전라남도  화순군  일반용  4,140   11,470,014
749   201410  전라남도  화순군  일반용  4,123    9,898,425
925   201411  전라남도  화순군  일반용  4,136   10,320,890
1101  201412  전라남도  화순군  일반용  4,094   11,709,948

[132 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강진군',
 '고흥군',
 '곡성군',
 '광양시',
 '구례군',
 '나주시',
 '담양군',
 '목포시',
 '무안군',
 '보성군',
 '순천시',
 '신안군',
 '여수시',
 '영광군',
 '영암군',
 '완도군',
 '장성군',
 '장흥군',
 '진도군',
 '함평군',
 '해남군',
 '화순군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55    201407  전라남도  강진군   합계  36,572   19,725,160
231   201408  전라남도  강진군   합계  36,604   22,827,845
407   201409  전라남도  강진군   합계  36,655   21,429,527
583   201410  전라남도  강진군   합계  36,696   19,675,619
759   201411  전라남도  강진군   합계  45,187   25,733,543
...      ...   ...  ...  ...      ...          ...
399   201408  전라남도  화순군   합계  45,688   39,547,180
575   201409  전라남도  화순군   합계  45,759   37,846,811
751   201410  전라남도  화순군   합계  45,796   35,966,250
927   201411  전라남도  화순군   합계  47,609   41,692,856
1103  201412  전라남도  화순군   합계  45,931   48,028,570

[132 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[19725160, 22827845, 21429527, 19675619, 25733543, 25776715]
[25966159, 30915765, 28862844, 25478779, 33055741, 37138484]
[34498077, 33467970, 31667541, 32415454, 34100987, 37074475]
[471666745, 446361414, 512605382, 612418070, 555714570, 514086051]
[11049991, 12851452, 11952653, 11150440, 13285384, 15167450]
[78355184, 82932905, 77163269, 72636774, 81563263, 89563045]
[34752732, 35211758, 36030512, 34110916, 38727947, 43311150]
[72977704, 82951459, 76640417, 68971582, 72243714, 81435192]
[41953575, 45241002, 42742180, 39973738, 48726491, 47216425]
[18753598, 22217508, 21355692, 19169722, 22997660, 25846310]
[144556269, 153700392, 137185726, 139092937, 145473384, 159998429]
[17107102, 20326278, 21216937, 18160130, 21494089, 21164712]
[1181292071, 1164472310, 1162261333, 1256093296, 1006251728, 1177255109]
[41373027, 44012648, 44808658, 50538780, 63153427, 52355739]
[126826113, 115801487, 116991212, 116933564, 119822546, 127199913]
[67778131, 75215257, 75107298, 72435307, 77534005, 69037009]
[44392035, 46838645, 47986340, 45752198, 51180547, 51987973]
[20962657, 24251985, 22358619, 20303280, 26126525, 26231074]
[19136575, 21894309, 21267351, 19982866, 24067733, 23486072]
[24181247, 26837385, 25551156, 23677745, 30335271, 30203682]
[40629863, 44889212, 41281753, 39273921, 54271111, 65295105]
[35984793, 39547180, 37846811, 35966250, 41692856, 48028570]
전라남도 지역별 합계 :  [135168409, 181417772, 203224504, 3112852232, 75457370, 482214440, 222145015, 455220068, 265853411, 130340490, 880007137, 119469248, 6947625847, 296242279, 723574835, 437107007, 288137738, 140234140, 129834906, 160786486, 285640965, 239066460]
전라남도 고객호수 평균:  [6345, 12781, 4928, 12259, 4769, 11806, 7082, 15598, 10255, 8280, 22167, 7949, 24581, 7757, 8730, 7565, 6011, 6250, 5868, 5939, 12824, 7676]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201407  전라남도  강진군   합계  36,572   19,725,160
1           201408  전라남도  강진군   합계  36,604   22,827,845
2           201409  전라남도  강진군   합계  36,655   21,429,527
3           201410  전라남도  강진군   합계  36,696   19,675,619
4           201411  전라남도  강진군   합계  45,187   25,733,543
..             ...   ...  ...  ...      ...          ...
149  201407-201412  전라남도  장흥군   합계     6250    140234140
150  201407-201412  전라남도  진도군   합계     5868    129834906
151  201407-201412  전라남도  함평군   합계     5939    160786486
152  201407-201412  전라남도  해남군   합계    12824    285640965
153  201407-201412  전라남도  화순군   합계     7676    239066460

[154 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201407-201412']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  201407-201412  전라남도  강진군   합계    6345   135168409
133  201407-201412  전라남도  고흥군   합계   12781   181417772
134  201407-201412  전라남도  곡성군   합계    4928   203224504
135  201407-201412  전라남도  광양시   합계   12259  3112852232
136  201407-201412  전라남도  구례군   합계    4769    75457370
137  201407-201412  전라남도  나주시   합계   11806   482214440
138  201407-201412  전라남도  담양군   합계    7082   222145015
139  201407-201412  전라남도  목포시   합계   15598   455220068
140  201407-201412  전라남도  무안군   합계   10255   265853411
141  201407-201412  전라남도  보성군   합계    8280   130340490
142  201407-201412  전라남도  순천시   합계   22167   880007137
143  201407-201412  전라남도  신안군   합계    7949   119469248
144  201407-201412  전라남도  여수시   합계   24581  6947625847
145  201407-201412  전라남도  영광군   합계    7757   296242279
146  201407-201412  전라남도  영암군   합계    8730   723574835
147  201407-201412  전라남도  완도군   합계    7565   437107007
148  201407-201412  전라남도  장성군   합계    6011   288137738
149  201407-201412  전라남도  장흥군   합계    6250   140234140
150  201407-201412  전라남도  진도군   합계    5868   129834906
151  201407-201412  전라남도  함평군   합계    5939   160786486
152  201407-201412  전라남도  해남군   합계   12824   285640965
153  201407-201412  전라남도  화순군   합계    7676   239066460

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    201407  전라남도  강진군  일반용  2,906    4,231,827
229   201408  전라남도  강진군  일반용  2,892    4,817,754
405   201409  전라남도  강진군  일반용  2,891    4,299,855
581   201410  전라남도  강진군  일반용  2,875    3,885,818
757   201411  전라남도  강진군  일반용  2,878    4,319,633
...      ...   ...  ...  ...     ...          ...
397   201408  전라남도  화순군  일반용  4,152   12,535,281
573   201409  전라남도  화순군  일반용  4,140   11,470,014
749   201410  전라남도  화순군  일반용  4,123    9,898,425
925   201411  전라남도  화순군  일반용  4,136   10,320,890
1101  201412  전라남도  화순군  일반용  4,094   11,709,948

[132 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[4231827, 4817754, 4299855, 3885818, 4319633, 5060070]
[6827526, 7909213, 7299728, 6485053, 6937785, 7997598]
[3113499, 3603810, 3295887, 3103055, 3287407, 3778526]
[19581384, 22298080, 20036810, 17802541, 18566553, 21640553]
[3918073, 4737377, 4176356, 3795959, 4238955, 4727791]
[13683078, 15921978, 14049048, 13196425, 14732785, 18475962]
[6597521, 7749071, 7035317, 6333895, 6911594, 7855970]
[37734536, 43867542, 39899645, 34609045, 34416494, 39294861]
[9997310, 11390827, 10292264, 9213396, 9859883, 11592291]
[4946418, 5841859, 5342324, 4782043, 5173699, 5950459]
[40087417, 45628191, 40909371, 35660947, 36498855, 41588327]
[3792649, 4468156, 4191459, 3834364, 4299495, 4841100]
[41395991, 48010513, 43185377, 37713545, 38516132, 43752789]
[6840526, 7796122, 7317778, 6684814, 7176955, 8306733]
[8106140, 9470088, 8587631, 7731950, 7845598, 9320146]
[6401794, 7716881, 7138434, 6362495, 6703042, 7360163]
[6437265, 7137358, 6329615, 5871548, 6638301, 7946976]
[4857464, 5555065, 5302352, 4619329, 4887551, 5586823]
[3185509, 3853436, 3477355, 3043712, 3264414, 3663525]
[3567768, 4119125, 3754365, 3437449, 3713793, 4177459]
[9399829, 10729505, 9452862, 8792382, 9621463, 11253036]
[11071802, 12535281, 11470014, 9898425, 10320890, 11709948]
전라남도 지역별 일반용 합계 :  [26614957, 43456903, 20182184, 119925921, 25594511, 90059276, 42483368, 229822123, 62345971, 32036802, 240373108, 25427223, 252574347, 44122928, 51061553, 41682809, 40361063, 30808584, 20487951, 22769959, 59249077, 67006360]
전라남도 고객호수 평균:  [2887, 5395, 2080, 10403, 2397, 6205, 3543, 18562, 5105, 3569, 18373, 3108, 21003, 4464, 4085, 5046, 3113, 3165, 2721, 2265, 5822, 4127]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21780\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
0           201407  전라남도  강진군  일반용  2,906   4,231,827
1           201408  전라남도  강진군  일반용  2,892   4,817,754
2           201409  전라남도  강진군  일반용  2,891   4,299,855
3           201410  전라남도  강진군  일반용  2,875   3,885,818
4           201411  전라남도  강진군  일반용  2,878   4,319,633
..             ...   ...  ...  ...     ...         ...
149  201407-201412  전라남도  장흥군  일반용    3165    30808584
150  201407-201412  전라남도  진도군  일반용    2721    20487951
151  201407-201412  전라남도  함평군  일반용    2265    22769959
152  201407-201412  전라남도  해남군  일반용    5822    59249077
153  201407-201412  전라남도  화순군  일반용    4127    67006360

[154 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201407-201412']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
132  201407-201412  전라남도  강진군  일반용    2887   26614957
133  201407-201412  전라남도  고흥군  일반용    5395   43456903
134  201407-201412  전라남도  곡성군  일반용    2080   20182184
135  201407-201412  전라남도  광양시  일반용   10403  119925921
136  201407-201412  전라남도  구례군  일반용    2397   25594511
137  201407-201412  전라남도  나주시  일반용    6205   90059276
138  201407-201412  전라남도  담양군  일반용    3543   42483368
139  201407-201412  전라남도  목포시  일반용   18562  229822123
140  201407-201412  전라남도  무안군  일반용    5105   62345971
141  201407-201412  전라남도  보성군  일반용    3569   32036802
142  201407-201412  전라남도  순천시  일반용   18373  240373108
143  201407-201412  전라남도  신안군  일반용    3108   25427223
144  201407-201412  전라남도  여수시  일반용   21003  252574347
145  201407-201412  전라남도  영광군  일반용    4464   44122928
146  201407-201412  전라남도  영암군  일반용    4085   51061553
147  201407-201412  전라남도  완도군  일반용    5046   41682809
148  201407-201412  전라남도  장성군  일반용    3113   40361063
149  201407-201412  전라남도  장흥군  일반용    3165   30808584
150  201407-201412  전라남도  진도군  일반용    2721   20487951
151  201407-201412  전라남도  함평군  일반용    2265   22769959
152  201407-201412  전라남도  해남군  일반용    5822   59249077
153  201407-201412  전라남도  화순군  일반용    4127   67006360

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  201407-201412  전라남도  강진군  일반용    2887    26614957
132  201407-201412  전라남도  강진군   합계    6345   135168409
133  201407-201412  전라남도  고흥군  일반용    5395    43456903
133  201407-201412  전라남도  고흥군   합계   12781   181417772
134  201407-201412  전라남도  곡성군  일반용    2080    20182184
134  201407-201412  전라남도  곡성군   합계    4928   203224504
135  201407-201412  전라남도  광양시  일반용   10403   119925921
135  201407-201412  전라남도  광양시   합계   12259  3112852232
136  201407-201412  전라남도  구례군  일반용    2397    25594511
136  201407-201412  전라남도  구례군   합계    4769    75457370
137  201407-201412  전라남도  나주시  일반용    6205    90059276
137  201407-201412  전라남도  나주시   합계   11806   482214440
138  201407-201412  전라남도  담양군  일반용    3543    42483368
138  201407-201412  전라남도  담양군   합계    7082   222145015
139  201407-201412  전라남도  목포시   합계   15598   455220068
139  201407-201412  전라남도  목포시  일반용   18562   229822123
140  201407-201412  전라남도  무안군   합계   10255   265853411
140  201407-201412  전라남도  무안군  일반용    5105    62345971
141  201407-201412  전라남도  보성군   합계    8280   130340490
141  201407-201412  전라남도  보성군  일반용    3569    32036802
142  201407-201412  전라남도  순천시   합계   22167   880007137
142  201407-201412  전라남도  순천시  일반용   18373   240373108
143  201407-201412  전라남도  신안군   합계    7949   119469248
143  201407-201412  전라남도  신안군  일반용    3108    25427223
144  201407-201412  전라남도  여수시   합계   24581  6947625847
144  201407-201412  전라남도  여수시  일반용   21003   252574347
145  201407-201412  전라남도  영광군   합계    7757   296242279
145  201407-201412  전라남도  영광군  일반용    4464    44122928
146  201407-201412  전라남도  영암군   합계    8730   723574835
146  201407-201412  전라남도  영암군  일반용    4085    51061553
147  201407-201412  전라남도  완도군   합계    7565   437107007
147  201407-201412  전라남도  완도군  일반용    5046    41682809
148  201407-201412  전라남도  장성군  일반용    3113    40361063
148  201407-201412  전라남도  장성군   합계    6011   288137738
149  201407-201412  전라남도  장흥군   합계    6250   140234140
149  201407-201412  전라남도  장흥군  일반용    3165    30808584
150  201407-201412  전라남도  진도군   합계    5868   129834906
150  201407-201412  전라남도  진도군  일반용    2721    20487951
151  201407-201412  전라남도  함평군   합계    5939   160786486
151  201407-201412  전라남도  함평군  일반용    2265    22769959
152  201407-201412  전라남도  해남군   합계   12824   285640965
152  201407-201412  전라남도  해남군  일반용    5822    59249077
153  201407-201412  전라남도  화순군  일반용    4127    67006360
153  201407-201412  전라남도  화순군   합계    7676   239066460

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[26614957,
 43456903,
 20182184,
 119925921,
 25594511,
 90059276,
 42483368,
 229822123,
 62345971,
 32036802,
 240373108,
 25427223,
 252574347,
 44122928,
 51061553,
 41682809,
 40361063,
 30808584,
 20487951,
 22769959,
 59249077,
 67006360]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[135168409,
 181417772,
 203224504,
 3112852232,
 75457370,
 482214440,
 222145015,
 455220068,
 265853411,
 130340490,
 880007137,
 119469248,
 6947625847,
 296242279,
 723574835,
 437107007,
 288137738,
 140234140,
 129834906,
 160786486,
 285640965,
 239066460]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[19.69, 23.95, 9.93, 3.85, 33.92, 18.68, 19.12, 50.49, 23.45, 24.58, 27.31, 21.28, 3.64, 14.89, 7.06, 9.54, 14.01, 21.97, 15.78, 14.16, 20.74, 28.03]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    20
1    24
2    10
3     4
4    34
5    19
6    19
7    50
8    23
9    25
10   27
11   21
12    4
13   15
14    7
15   10
16   14
17   22
18   16
19   14
20   21
21   28
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강진군  일반용  20
1   고흥군  일반용  24
2   곡성군  일반용  10
3   광양시  일반용   4
4   구례군  일반용  34
5   나주시  일반용  19
6   담양군  일반용  19
7   목포시  일반용  50
8   무안군  일반용  23
9   보성군  일반용  25
10  순천시  일반용  27
11  신안군  일반용  21
12  여수시  일반용   4
13  영광군  일반용  15
14  영암군  일반용   7
15  완도군  일반용  10
16  장성군  일반용  14
17  장흥군  일반용  22
18  진도군  일반용  16
19  함평군  일반용  14
20  해남군  일반용  21
21  화순군  일반용  28

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201407-201412  전라남도  강진군  일반용    2887    26614957  20
1   201407-201412  전라남도  강진군   합계    6345   135168409 NaN
2   201407-201412  전라남도  고흥군  일반용    5395    43456903  24
3   201407-201412  전라남도  고흥군   합계   12781   181417772 NaN
4   201407-201412  전라남도  곡성군  일반용    2080    20182184  10
5   201407-201412  전라남도  곡성군   합계    4928   203224504 NaN
6   201407-201412  전라남도  광양시  일반용   10403   119925921   4
7   201407-201412  전라남도  광양시   합계   12259  3112852232 NaN
8   201407-201412  전라남도  구례군  일반용    2397    25594511  34
9   201407-201412  전라남도  구례군   합계    4769    75457370 NaN
10  201407-201412  전라남도  나주시  일반용    6205    90059276  19
11  201407-201412  전라남도  나주시   합계   11806   482214440 NaN
12  201407-201412  전라남도  담양군  일반용    3543    42483368  19
13  201407-201412  전라남도  담양군   합계    7082   222145015 NaN
15  201407-201412  전라남도  목포시  일반용   18562   229822123  50
14  201407-201412  전라남도  목포시   합계   15598   455220068 NaN
17  201407-201412  전라남도  무안군  일반용    5105    62345971  23
16  201407-201412  전라남도  무안군   합계   10255   265853411 NaN
19  201407-201412  전라남도  보성군  일반용    3569    32036802  25
18  201407-201412  전라남도  보성군   합계    8280   130340490 NaN
21  201407-201412  전라남도  순천시  일반용   18373   240373108  27
20  201407-201412  전라남도  순천시   합계   22167   880007137 NaN
23  201407-201412  전라남도  신안군  일반용    3108    25427223  21
22  201407-201412  전라남도  신안군   합계    7949   119469248 NaN
25  201407-201412  전라남도  여수시  일반용   21003   252574347   4
24  201407-201412  전라남도  여수시   합계   24581  6947625847 NaN
27  201407-201412  전라남도  영광군  일반용    4464    44122928  15
26  201407-201412  전라남도  영광군   합계    7757   296242279 NaN
29  201407-201412  전라남도  영암군  일반용    4085    51061553   7
28  201407-201412  전라남도  영암군   합계    8730   723574835 NaN
31  201407-201412  전라남도  완도군  일반용    5046    41682809  10
30  201407-201412  전라남도  완도군   합계    7565   437107007 NaN
32  201407-201412  전라남도  장성군  일반용    3113    40361063  14
33  201407-201412  전라남도  장성군   합계    6011   288137738 NaN
35  201407-201412  전라남도  장흥군  일반용    3165    30808584  22
34  201407-201412  전라남도  장흥군   합계    6250   140234140 NaN
37  201407-201412  전라남도  진도군  일반용    2721    20487951  16
36  201407-201412  전라남도  진도군   합계    5868   129834906 NaN
39  201407-201412  전라남도  함평군  일반용    2265    22769959  14
38  201407-201412  전라남도  함평군   합계    5939   160786486 NaN
41  201407-201412  전라남도  해남군  일반용    5822    59249077  21
40  201407-201412  전라남도  해남군   합계   12824   285640965 NaN
42  201407-201412  전라남도  화순군  일반용    4127    67006360  28
43  201407-201412  전라남도  화순군   합계    7676   239066460 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1407-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)