In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라북도_계약종별 전력사용량 월별_19상반기.csv' , encoding='cp949')

df

#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라북도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2019년 01 월 ~ 2019년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201901,전라북도,전체(시 / 군 / 구),주택용,"653,328","222,107,191","24,718,884,767",111.3
4,201901,전라북도,전체(시 / 군 / 구),일반용,"139,462","376,943,246","50,024,292,007",132.7
...,...,...,...,...,...,...,...,...
715,201906,전라북도,진안군,산업용,823,"2,842,981","384,567,318",135.3
716,201906,전라북도,진안군,심 야,"1,871","1,036,726","59,097,435",57
717,201906,전라북도,진안군,일반용,"2,190","3,105,309","440,530,215",141.9
718,201906,전라북도,진안군,주택용,"14,111","2,172,213","251,109,861",115.6
719,201906,전라북도,진안군,합계,"30,604","13,816,670","1,450,455,530",105

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201901,전라북도,전체(시 / 군 / 구),주택용,"653,328","222,107,191","24,718,884,767",111.3
4,201901,전라북도,전체(시 / 군 / 구),일반용,"139,462","376,943,246","50,024,292,007",132.7
5,201901,전라북도,전체(시 / 군 / 구),교육용,"1,232","42,054,792","4,255,857,589",101.2
6,201901,전라북도,전체(시 / 군 / 구),산업용,"15,290","1,102,520,299","124,091,849,993",112.6
...,...,...,...,...,...,...,...,...
715,201906,전라북도,진안군,산업용,823,"2,842,981","384,567,318",135.3
716,201906,전라북도,진안군,심 야,"1,871","1,036,726","59,097,435",57
717,201906,전라북도,진안군,일반용,"2,190","3,105,309","440,530,215",141.9
718,201906,전라북도,진안군,주택용,"14,111","2,172,213","251,109,861",115.6
719,201906,전라북도,진안군,합계,"30,604","13,816,670","1,450,455,530",105

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201901,전라북도,전체(시 / 군 / 구),주택용,"653,328","222,107,191","24,718,884,767",111.3
4,201901,전라북도,전체(시 / 군 / 구),일반용,"139,462","376,943,246","50,024,292,007",132.7
5,201901,전라북도,전체(시 / 군 / 구),교육용,"1,232","42,054,792","4,255,857,589",101.2
6,201901,전라북도,전체(시 / 군 / 구),산업용,"15,290","1,102,520,299","124,091,849,993",112.6
7,201901,전라북도,전체(시 / 군 / 구),농사용,"147,998","161,834,808","7,794,212,366",48.2
...,...,...,...,...,...,...,...,...
715,201906,전라북도,진안군,산업용,823,"2,842,981","384,567,318",135.3
716,201906,전라북도,진안군,심 야,"1,871","1,036,726","59,097,435",57
717,201906,전라북도,진안군,일반용,"2,190","3,105,309","440,530,215",141.9
718,201906,전라북도,진안군,주택용,"14,111","2,172,213","251,109,861",115.6
719,201906,전라북도,진안군,합계,"30,604","13,816,670","1,450,455,530",105

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201901,전라북도,전체(시 / 군 / 구),주택용,"653,328","222,107,191","24,718,884,767",111.3
4,201901,전라북도,전체(시 / 군 / 구),일반용,"139,462","376,943,246","50,024,292,007",132.7
5,201901,전라북도,전체(시 / 군 / 구),교육용,"1,232","42,054,792","4,255,857,589",101.2
6,201901,전라북도,전체(시 / 군 / 구),산업용,"15,290","1,102,520,299","124,091,849,993",112.6
7,201901,전라북도,전체(시 / 군 / 구),농사용,"147,998","161,834,808","7,794,212,366",48.2
8,201901,전라북도,전체(시 / 군 / 구),가로등,"137,859","19,857,266","2,042,310,746",102.8
9,201901,전라북도,전체(시 / 군 / 구),심 야,"62,259","134,057,239","9,917,129,251",74.0
10,201902,전라북도,전체(시 / 군 / 구),주택용,"654,586","221,958,037","24,775,569,201",111.6
11,201902,전라북도,전체(시 / 군 / 구),일반용,"139,483","359,804,778","47,937,463,242",133.2
12,201902,전라북도,전체(시 / 군 / 구),교육용,"1,231","35,494,232","3,805,199,039",107.2
13,201902,전라북도,전체(시 / 군 / 구),산업용,"15,290","968,210,143","109,615,756,628",113.2
14,201902,전라북도,전체(시 / 군 / 구),농사용,"147,816","160,962,299","7,729,880,488",48.0
15,201902,전라북도,전체(시 / 군 / 구),가로등,"138,089","18,543,840","2,034,958,394",109.7
16,201902,전라북도,전체(시 / 군 / 구),심 야,"62,119","133,914,180","9,906,222,211",74.0
17,201903,전라북도,전체(시 / 군 / 구),주택용,"656,057","191,712,885","19,367,886,654",101.0
18,201903,전라북도,전체(시 / 군 / 구),일반용,"139,330","301,008,787","38,510,244,349",127.9
19,201903,전라북도,전체(시 / 군 / 구),교육용,"1,228","34,503,362","3,533,473,162",102.4
20,201903,전라북도,전체(시 / 군 / 구),산업용,"15,313","1,151,433,057","103,024,561,515",89.5
21,201903,전라북도,전체(시 / 군 / 구),농사용,"220,769","134,896,208","6,574,623,151",48.7
22,201903,전라북도,전체(시 / 군 / 구),가로등,"138,258","17,385,548","1,919,713,559",110.4
23,201903,전라북도,전체(시 / 군 / 구),심 야,"61,983","103,150,188","6,759,262,180",65.5
24,201904,전라북도,전체(시 / 군 / 구),주택용,"657,160","201,768,989","21,462,264,205",106.4
25,201904,전라북도,전체(시 / 군 / 구),일반용,"139,564","295,012,853","34,341,912,815",116.4
26,201904,전라북도,전체(시 / 군 / 구),교육용,"1,226","34,511,370","3,108,356,897",90.1
27,201904,전라북도,전체(시 / 군 / 구),산업용,"15,377","1,122,789,586","101,156,441,248",90.1
28,201904,전라북도,전체(시 / 군 / 구),농사용,"187,121","128,044,424","6,260,576,885",48.9
29,201904,전라북도,전체(시 / 군 / 구),가로등,"138,834","17,060,931","1,970,580,631",115.5
30,201904,전라북도,전체(시 / 군 / 구),심 야,"61,851","88,140,705","4,716,879,205",53.5
31,201905,전라북도,전체(시 / 군 / 구),주택용,"657,614","187,616,755","19,040,175,513",101.5
32,201905,전라북도,전체(시 / 군 / 구),일반용,"139,722","262,394,468","32,098,949,506",122.3
33,201905,전라북도,전체(시 / 군 / 구),교육용,"1,225","24,858,586","2,374,950,670",95.5
34,201905,전라북도,전체(시 / 군 / 구),산업용,"15,466","1,127,405,580","100,884,286,061",89.5
35,201905,전라북도,전체(시 / 군 / 구),농사용,"150,650","117,303,841","5,658,038,982",48.2
36,201905,전라북도,전체(시 / 군 / 구),가로등,"139,347","16,145,689","1,924,524,909",119.2
37,201905,전라북도,전체(시 / 군 / 구),심 야,"61,676","52,637,410","2,836,913,440",53.9
38,201906,전라북도,전체(시 / 군 / 구),주택용,"658,692","187,059,540","19,110,339,190",102.2
39,201906,전라북도,전체(시 / 군 / 구),일반용,"139,893","274,971,458","37,635,382,277",136.9
40,201906,전라북도,전체(시 / 군 / 구),교육용,"1,236","24,274,294","2,758,951,149",113.7
41,201906,전라북도,전체(시 / 군 / 구),산업용,"15,438","1,041,038,673","115,444,183,640",110.9
42,201906,전라북도,전체(시 / 군 / 구),농사용,"151,643","128,634,875","5,944,965,779",46.2
43,201906,전라북도,전체(시 / 군 / 구),가로등,"139,784","15,595,128","1,922,556,400",123.3
44,201906,전라북도,전체(시 / 군 / 구),심 야,"61,513","28,814,165","1,587,541,810",55.1
45,합계,합계,합계,합계,"7,084,012","11,268,431,705","1,130,578,121,704",100.3

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_21684\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201901  전라북도  일반용  139,462   376,943,246
11  201902  전라북도  일반용  139,483   359,804,778
18  201903  전라북도  일반용  139,330   301,008,787
25  201904  전라북도  일반용  139,564   295,012,853
32  201905  전라북도  일반용  139,722   262,394,468
39  201906  전라북도  일반용  139,893   274,971,458

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53   201901  전라북도  고창군  일반용  4,639   10,314,575
165  201902  전라북도  고창군  일반용  4,645   10,267,412
277  201903  전라북도  고창군  일반용  4,647    8,786,112
389  201904  전라북도  고창군  일반용  4,655    8,664,020
501  201905  전라북도  고창군  일반용  4,661    7,773,149
..      ...   ...  ...  ...     ...          ...
269  201902  전라북도  진안군  일반용  2,149    4,756,079
381  201903  전라북도  진안군  일반용  2,145    4,029,086
493  201904  전라북도  진안군  일반용  2,185    3,936,644
605  201905  전라북도  진안군  일반용  2,201    3,309,036
717  201906  전라북도  진안군  일반용  2,190    3,105,309

[84 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라북도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['고창군',
 '군산시',
 '김제시',
 '남원시',
 '무주군',
 '부안군',
 '순창군',
 '완주군',
 '익산시',
 '임실군',
 '장수군',
 '전주시',
 '정읍시',
 '진안군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55   201901  전라북도  고창군   합계  57,702   60,373,381
167  201902  전라북도  고창군   합계  57,759   59,663,191
279  201903  전라북도  고창군   합계  61,041   51,362,772
391  201904  전라북도  고창군   합계  77,215   51,159,757
503  201905  전라북도  고창군   합계  58,189   44,955,709
..      ...   ...  ...  ...      ...          ...
271  201902  전라북도  진안군   합계  30,172   21,311,963
383  201903  전라북도  진안군   합계  32,501   18,362,991
495  201904  전라북도  진안군   합계  30,336   17,679,131
607  201905  전라북도  진안군   합계  30,444   14,879,635
719  201906  전라북도  진안군   합계  30,604   13,816,670

[84 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[60373381, 59663191, 51362772, 51159757, 44955709, 43603084]
[649899639, 582268474, 704605335, 675509135, 681450438, 590588149]
[102714276, 97278007, 86983618, 86048795, 78786162, 76804104]
[60660100, 58983129, 51762785, 52337848, 46624740, 46868037]
[25803665, 22798340, 18559413, 16998467, 14850685, 14348915]
[47443737, 45170561, 41113462, 40814310, 35439458, 35132118]
[24454666, 23008951, 22045496, 21632401, 20118612, 20331287]
[161667235, 144747846, 147255585, 143804995, 134018858, 133816930]
[291335846, 266892011, 255227476, 250700411, 236483253, 236742818]
[31264256, 29044963, 26543390, 24995605, 22344849, 21572353]
[25156535, 24870124, 20274582, 19203996, 15291706, 13592551]
[412068254, 387604117, 360794800, 358399717, 325743704, 335842209]
[144400458, 135245832, 129198330, 128044290, 117374520, 117328908]
[22132793, 21311963, 18362991, 17679131, 14879635, 13816670]
전라북도 지역별 합계 :  [311117894, 3884321170, 528614962, 317236639, 113359485, 245113646, 131591413, 865311449, 1537381815, 155765416, 118389494, 2180452801, 771592338, 108183183]
전라북도 고객호수 평균:  [10287, 23171, 12879, 13095, 4693, 8997, 5952, 11460, 28366, 5609, 4506, 46152, 16487, 5118]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\1362649055.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201901  전라북도  고창군   합계  57,702   60,373,381
1          201902  전라북도  고창군   합계  57,759   59,663,191
2          201903  전라북도  고창군   합계  61,041   51,362,772
3          201904  전라북도  고창군   합계  77,215   51,159,757
4          201905  전라북도  고창군   합계  58,189   44,955,709
..            ...   ...  ...  ...      ...          ...
93  201901-201906  전라북도  임실군   합계     5609    155765416
94  201901-201906  전라북도  장수군   합계     4506    118389494
95  201901-201906  전라북도  전주시   합계    46152   2180452801
96  201901-201906  전라북도  정읍시   합계    16487    771592338
97  201901-201906  전라북도  진안군   합계     5118    108183183

[98 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201901-201906']
Hap

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  201901-201906  전라북도  고창군   합계   10287   311117894
85  201901-201906  전라북도  군산시   합계   23171  3884321170
86  201901-201906  전라북도  김제시   합계   12879   528614962
87  201901-201906  전라북도  남원시   합계   13095   317236639
88  201901-201906  전라북도  무주군   합계    4693   113359485
89  201901-201906  전라북도  부안군   합계    8997   245113646
90  201901-201906  전라북도  순창군   합계    5952   131591413
91  201901-201906  전라북도  완주군   합계   11460   865311449
92  201901-201906  전라북도  익산시   합계   28366  1537381815
93  201901-201906  전라북도  임실군   합계    5609   155765416
94  201901-201906  전라북도  장수군   합계    4506   118389494
95  201901-201906  전라북도  전주시   합계   46152  2180452801
96  201901-201906  전라북도  정읍시   합계   16487   771592338
97  201901-201906  전라북도  진안군   합계    5118   108183183

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53   201901  전라북도  고창군  일반용  4,639   10,314,575
165  201902  전라북도  고창군  일반용  4,645   10,267,412
277  201903  전라북도  고창군  일반용  4,647    8,786,112
389  201904  전라북도  고창군  일반용  4,655    8,664,020
501  201905  전라북도  고창군  일반용  4,661    7,773,149
..      ...   ...  ...  ...     ...          ...
269  201902  전라북도  진안군  일반용  2,149    4,756,079
381  201903  전라북도  진안군  일반용  2,145    4,029,086
493  201904  전라북도  진안군  일반용  2,185    3,936,644
605  201905  전라북도  진안군  일반용  2,201    3,309,036
717  201906  전라북도  진안군  일반용  2,190    3,105,309

[84 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[10314575, 10267412, 8786112, 8664020, 7773149, 7769767]
[61082266, 58809802, 49485694, 48792621, 42849308, 44622652]
[16164520, 15749286, 13112209, 13028384, 11384790, 11814682]
[17176432, 16978382, 13662211, 13630951, 11892618, 12121971]
[12360941, 9720374, 7243923, 6090132, 5371963, 5328197]
[13340980, 12916510, 11033474, 10840301, 9686565, 9661752]
[4685886, 4508837, 3728940, 3699465, 3229973, 3282105]
[23162221, 21577195, 18878133, 18537544, 17020345, 18238218]
[51970145, 50055037, 41676489, 40832451, 35734293, 37724997]
[6106833, 5785335, 4815044, 4598293, 3977369, 4060673]
[4126967, 3968944, 3380444, 3214716, 2752890, 2653448]
[131615829, 125487762, 105193307, 103201325, 93502097, 100293285]
[19849115, 19223823, 15983721, 15946006, 13910072, 14294402]
[4986536, 4756079, 4029086, 3936644, 3309036, 3105309]
전라북도 지역별 일반용 합계 :  [53575035, 305642343, 81253871, 85462565, 46115530, 67479582, 23135206, 117413656, 257993412, 29343547, 20097409, 659293605, 99207139, 24122690]
전라북도 고객호수 평균:  [4654, 20280, 6445, 7439, 2731, 5615, 2300, 7393, 20610, 2263, 1730, 46765, 9175, 2170]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_21684\2798360716.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201901-201906'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201901  전라북도  고창군  일반용  4,639   10,314,575
1          201902  전라북도  고창군  일반용  4,645   10,267,412
2          201903  전라북도  고창군  일반용  4,647    8,786,112
3          201904  전라북도  고창군  일반용  4,655    8,664,020
4          201905  전라북도  고창군  일반용  4,661    7,773,149
..            ...   ...  ...  ...     ...          ...
93  201901-201906  전라북도  임실군  일반용    2263     29343547
94  201901-201906  전라북도  장수군  일반용    1730     20097409
95  201901-201906  전라북도  전주시  일반용   46765    659293605
96  201901-201906  전라북도  정읍시  일반용    9175     99207139
97  201901-201906  전라북도  진안군  일반용    2170     24122690

[98 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201901-201906']
GyeonGiHap2

               년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
84  201901-201906  전라북도  고창군  일반용    4654   53575035
85  201901-201906  전라북도  군산시  일반용   20280  305642343
86  201901-201906  전라북도  김제시  일반용    6445   81253871
87  201901-201906  전라북도  남원시  일반용    7439   85462565
88  201901-201906  전라북도  무주군  일반용    2731   46115530
89  201901-201906  전라북도  부안군  일반용    5615   67479582
90  201901-201906  전라북도  순창군  일반용    2300   23135206
91  201901-201906  전라북도  완주군  일반용    7393  117413656
92  201901-201906  전라북도  익산시  일반용   20610  257993412
93  201901-201906  전라북도  임실군  일반용    2263   29343547
94  201901-201906  전라북도  장수군  일반용    1730   20097409
95  201901-201906  전라북도  전주시  일반용   46765  659293605
96  201901-201906  전라북도  정읍시  일반용    9175   99207139
97  201901-201906  전라북도  진안군  일반용    2170   24122690

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  201901-201906  전라북도  고창군  일반용    4654    53575035
84  201901-201906  전라북도  고창군   합계   10287   311117894
85  201901-201906  전라북도  군산시  일반용   20280   305642343
85  201901-201906  전라북도  군산시   합계   23171  3884321170
86  201901-201906  전라북도  김제시  일반용    6445    81253871
86  201901-201906  전라북도  김제시   합계   12879   528614962
87  201901-201906  전라북도  남원시  일반용    7439    85462565
87  201901-201906  전라북도  남원시   합계   13095   317236639
88  201901-201906  전라북도  무주군  일반용    2731    46115530
88  201901-201906  전라북도  무주군   합계    4693   113359485
89  201901-201906  전라북도  부안군  일반용    5615    67479582
89  201901-201906  전라북도  부안군   합계    8997   245113646
90  201901-201906  전라북도  순창군  일반용    2300    23135206
90  201901-201906  전라북도  순창군   합계    5952   131591413
91  201901-201906  전라북도  완주군   합계   11460   865311449
91  201901-201906  전라북도  완주군  일반용    7393   117413656
92  201901-201906  전라북도  익산시  일반용   20610   257993412
92  201901-201906  전라북도  익산시   합계   28366  1537381815
93  201901-201906  전라북도  임실군   합계    5609   155765416
93  201901-201906  전라북도  임실군  일반용    2263    29343547
94  201901-201906  전라북도  장수군   합계    4506   118389494
94  201901-201906  전라북도  장수군  일반용    1730    20097409
95  201901-201906  전라북도  전주시   합계   46152  2180452801
95  201901-201906  전라북도  전주시  일반용   46765   659293605
96  201901-201906  전라북도  정읍시   합계   16487   771592338
96  201901-201906  전라북도  정읍시  일반용    9175    99207139
97  201901-201906  전라북도  진안군  일반용    2170    24122690
97  201901-201906  전라북도  진안군   합계    5118   108183183

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[53575035,
 305642343,
 81253871,
 85462565,
 46115530,
 67479582,
 23135206,
 117413656,
 257993412,
 29343547,
 20097409,
 659293605,
 99207139,
 24122690]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[311117894,
 3884321170,
 528614962,
 317236639,
 113359485,
 245113646,
 131591413,
 865311449,
 1537381815,
 155765416,
 118389494,
 2180452801,
 771592338,
 108183183]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[17.22, 7.87, 15.37, 26.94, 40.68, 27.53, 17.58, 13.57, 16.78, 18.84, 16.98, 30.24, 12.86, 22.3]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    17
1     8
2    15
3    27
4    41
5    28
6    18
7    14
8    17
9    19
10   17
11   30
12   13
13   22
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   고창군  일반용  17
1   군산시  일반용   8
2   김제시  일반용  15
3   남원시  일반용  27
4   무주군  일반용  41
5   부안군  일반용  28
6   순창군  일반용  18
7   완주군  일반용  14
8   익산시  일반용  17
9   임실군  일반용  19
10  장수군  일반용  17
11  전주시  일반용  30
12  정읍시  일반용  13
13  진안군  일반용  22

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201901-201906  전라북도  고창군  일반용    4654    53575035  17
1   201901-201906  전라북도  고창군   합계   10287   311117894 NaN
2   201901-201906  전라북도  군산시  일반용   20280   305642343   8
3   201901-201906  전라북도  군산시   합계   23171  3884321170 NaN
4   201901-201906  전라북도  김제시  일반용    6445    81253871  15
5   201901-201906  전라북도  김제시   합계   12879   528614962 NaN
6   201901-201906  전라북도  남원시  일반용    7439    85462565  27
7   201901-201906  전라북도  남원시   합계   13095   317236639 NaN
8   201901-201906  전라북도  무주군  일반용    2731    46115530  41
9   201901-201906  전라북도  무주군   합계    4693   113359485 NaN
10  201901-201906  전라북도  부안군  일반용    5615    67479582  28
11  201901-201906  전라북도  부안군   합계    8997   245113646 NaN
12  201901-201906  전라북도  순창군  일반용    2300    23135206  18
13  201901-201906  전라북도  순창군   합계    5952   131591413 NaN
15  201901-201906  전라북도  완주군  일반용    7393   117413656  14
14  201901-201906  전라북도  완주군   합계   11460   865311449 NaN
16  201901-201906  전라북도  익산시  일반용   20610   257993412  17
17  201901-201906  전라북도  익산시   합계   28366  1537381815 NaN
19  201901-201906  전라북도  임실군  일반용    2263    29343547  19
18  201901-201906  전라북도  임실군   합계    5609   155765416 NaN
21  201901-201906  전라북도  장수군  일반용    1730    20097409  17
20  201901-201906  전라북도  장수군   합계    4506   118389494 NaN
23  201901-201906  전라북도  전주시  일반용   46765   659293605  30
22  201901-201906  전라북도  전주시   합계   46152  2180452801 NaN
25  201901-201906  전라북도  정읍시  일반용    9175    99207139  13
24  201901-201906  전라북도  정읍시   합계   16487   771592338 NaN
26  201901-201906  전라북도  진안군  일반용    2170    24122690  22
27  201901-201906  전라북도  진안군   합계    5118   108183183 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1901-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)