In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라남도_계약종별_전력사용량_월별_12하반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2012년 07 월 ~ 2012년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,전라남도,전체(시 / 군 / 구),주택용,"679,449","173,541,014","18,502,171,019",106.6
4,201207,전라남도,전체(시 / 군 / 구),일반용,"127,218","255,895,142","30,078,301,491",117.5
...,...,...,...,...,...,...,...,...
1099,201212,전라남도,화순군,산업용,704,"13,626,852","1,616,447,679",118.6
1100,201212,전라남도,화순군,심 야,"1,997","3,873,030","257,377,182",66.5
1101,201212,전라남도,화순군,일반용,"3,948","11,339,942","1,401,484,221",123.6
1102,201212,전라남도,화순군,주택용,"23,499","6,407,536","738,214,820",115.2
1103,201212,전라남도,화순군,합계,"43,924","44,298,522","4,512,379,211",101.9

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,전라남도,전체(시 / 군 / 구),주택용,"679,449","173,541,014","18,502,171,019",106.6
4,201207,전라남도,전체(시 / 군 / 구),일반용,"127,218","255,895,142","30,078,301,491",117.5
5,201207,전라남도,전체(시 / 군 / 구),교육용,"1,923","18,937,805","2,449,026,383",129.3
6,201207,전라남도,전체(시 / 군 / 구),산업용,"18,182","1,692,395,986","155,861,768,747",92.1
...,...,...,...,...,...,...,...,...
1099,201212,전라남도,화순군,산업용,704,"13,626,852","1,616,447,679",118.6
1100,201212,전라남도,화순군,심 야,"1,997","3,873,030","257,377,182",66.5
1101,201212,전라남도,화순군,일반용,"3,948","11,339,942","1,401,484,221",123.6
1102,201212,전라남도,화순군,주택용,"23,499","6,407,536","738,214,820",115.2
1103,201212,전라남도,화순군,합계,"43,924","44,298,522","4,512,379,211",101.9

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,전라남도,전체(시 / 군 / 구),주택용,"679,449","173,541,014","18,502,171,019",106.6
4,201207,전라남도,전체(시 / 군 / 구),일반용,"127,218","255,895,142","30,078,301,491",117.5
5,201207,전라남도,전체(시 / 군 / 구),교육용,"1,923","18,937,805","2,449,026,383",129.3
6,201207,전라남도,전체(시 / 군 / 구),산업용,"18,182","1,692,395,986","155,861,768,747",92.1
7,201207,전라남도,전체(시 / 군 / 구),농사용,"214,528","171,733,528","7,193,749,721",41.9
...,...,...,...,...,...,...,...,...
1099,201212,전라남도,화순군,산업용,704,"13,626,852","1,616,447,679",118.6
1100,201212,전라남도,화순군,심 야,"1,997","3,873,030","257,377,182",66.5
1101,201212,전라남도,화순군,일반용,"3,948","11,339,942","1,401,484,221",123.6
1102,201212,전라남도,화순군,주택용,"23,499","6,407,536","738,214,820",115.2
1103,201212,전라남도,화순군,합계,"43,924","44,298,522","4,512,379,211",101.9

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,전라남도,전체(시 / 군 / 구),주택용,"679,449","173,541,014","18,502,171,019",106.6
4,201207,전라남도,전체(시 / 군 / 구),일반용,"127,218","255,895,142","30,078,301,491",117.5
5,201207,전라남도,전체(시 / 군 / 구),교육용,"1,923","18,937,805","2,449,026,383",129.3
6,201207,전라남도,전체(시 / 군 / 구),산업용,"18,182","1,692,395,986","155,861,768,747",92.1
7,201207,전라남도,전체(시 / 군 / 구),농사용,"214,528","171,733,528","7,193,749,721",41.9
8,201207,전라남도,전체(시 / 군 / 구),가로등,"113,386","15,882,798","1,705,805,338",107.4
9,201207,전라남도,전체(시 / 군 / 구),심 야,"52,167","24,228,550","1,176,134,548",48.5
10,201208,전라남도,전체(시 / 군 / 구),주택용,"679,531","215,121,236","29,035,906,691",135.0
11,201208,전라남도,전체(시 / 군 / 구),일반용,"128,503","319,663,390","41,888,723,697",131.0
12,201208,전라남도,전체(시 / 군 / 구),교육용,"1,924","20,888,702","2,972,444,877",142.3
13,201208,전라남도,전체(시 / 군 / 구),산업용,"18,207","1,657,179,568","163,452,838,568",98.6
14,201208,전라남도,전체(시 / 군 / 구),농사용,"217,147","216,424,938","8,966,790,761",41.4
15,201208,전라남도,전체(시 / 군 / 구),가로등,"120,480","16,632,155","1,722,056,573",103.5
16,201208,전라남도,전체(시 / 군 / 구),심 야,"52,099","20,229,320","1,016,197,029",50.2
17,201209,전라남도,전체(시 / 군 / 구),주택용,"680,785","191,307,542","22,866,740,800",119.5
18,201209,전라남도,전체(시 / 군 / 구),일반용,"128,584","271,122,005","33,768,721,190",124.6
19,201209,전라남도,전체(시 / 군 / 구),교육용,"1,922","21,050,209","2,702,487,010",128.4
20,201209,전라남도,전체(시 / 군 / 구),산업용,"18,180","1,653,626,872","135,199,997,490",81.8
21,201209,전라남도,전체(시 / 군 / 구),농사용,"218,584","189,663,271","8,274,628,326",43.6
22,201209,전라남도,전체(시 / 군 / 구),가로등,"118,927","16,495,584","1,740,983,013",105.5
23,201209,전라남도,전체(시 / 군 / 구),심 야,"52,040","20,202,100","1,037,671,521",51.4
24,201210,전라남도,전체(시 / 군 / 구),주택용,"681,998","171,877,099","18,371,736,576",106.9
25,201210,전라남도,전체(시 / 군 / 구),일반용,"128,696","219,602,898","24,615,782,575",112.1
26,201210,전라남도,전체(시 / 군 / 구),교육용,"1,923","16,358,584","2,055,804,582",125.7
27,201210,전라남도,전체(시 / 군 / 구),산업용,"18,212","1,702,484,403","137,592,903,545",80.8
28,201210,전라남도,전체(시 / 군 / 구),농사용,"219,452","162,643,184","7,421,543,451",45.6
29,201210,전라남도,전체(시 / 군 / 구),가로등,"121,628","17,877,382","1,779,122,371",99.5
30,201210,전라남도,전체(시 / 군 / 구),심 야,"52,002","33,711,760","1,683,372,667",49.9
31,201211,전라남도,전체(시 / 군 / 구),주택용,"683,165","185,416,293","21,353,145,172",115.2
32,201211,전라남도,전체(시 / 군 / 구),일반용,"129,191","238,863,750","28,577,992,739",119.6
33,201211,전라남도,전체(시 / 군 / 구),교육용,"1,920","20,829,826","2,562,800,505",123.0
34,201211,전라남도,전체(시 / 군 / 구),산업용,"18,241","1,688,879,027","174,486,412,415",103.3
35,201211,전라남도,전체(시 / 군 / 구),농사용,"337,207","251,080,840","9,531,910,682",38.0
36,201211,전라남도,전체(시 / 군 / 구),가로등,"121,778","19,038,386","1,844,311,348",96.9
37,201211,전라남도,전체(시 / 군 / 구),심 야,"51,965","67,037,655","3,848,527,820",57.4
38,201212,전라남도,전체(시 / 군 / 구),주택용,"683,971","194,029,848","23,733,092,101",122.3
39,201212,전라남도,전체(시 / 군 / 구),일반용,"129,975","278,134,896","35,341,088,235",127.1
40,201212,전라남도,전체(시 / 군 / 구),교육용,"1,923","29,517,658","3,498,219,376",118.5
41,201212,전라남도,전체(시 / 군 / 구),산업용,"18,222","1,607,185,371","153,355,417,680",95.4
42,201212,전라남도,전체(시 / 군 / 구),농사용,"243,295","220,561,949","9,215,605,399",41.8
43,201212,전라남도,전체(시 / 군 / 구),가로등,"121,953","22,579,731","1,924,738,095",85.2
44,201212,전라남도,전체(시 / 군 / 구),심 야,"51,943","108,130,219","7,338,486,250",67.9
45,합계,합계,합계,합계,"7,462,426","14,438,062,474","1,341,745,158,377",92.9

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_12680\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201207  전라남도  일반용  127,218   255,895,142
11  201208  전라남도  일반용  128,503   319,663,390
18  201209  전라남도  일반용  128,584   271,122,005
25  201210  전라남도  일반용  128,696   219,602,898
32  201211  전라남도  일반용  129,191   238,863,750
39  201212  전라남도  일반용  129,975   278,134,896

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    201207  전라남도  강진군  일반용  2,717    4,138,480
229   201208  전라남도  강진군  일반용  2,783    5,110,175
405   201209  전라남도  강진군  일반용  2,777    4,424,609
581   201210  전라남도  강진군  일반용  2,769    3,876,419
757   201211  전라남도  강진군  일반용  2,784    4,439,319
...      ...   ...  ...  ...     ...          ...
397   201208  전라남도  화순군  일반용  3,855   12,124,340
573   201209  전라남도  화순군  일반용  3,860   10,373,933
749   201210  전라남도  화순군  일반용  3,879    8,913,509
925   201211  전라남도  화순군  일반용  3,934    9,775,505
1101  201212  전라남도  화순군  일반용  3,948   11,339,942

[132 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강진군',
 '고흥군',
 '곡성군',
 '광양시',
 '구례군',
 '나주시',
 '담양군',
 '목포시',
 '무안군',
 '보성군',
 '순천시',
 '신안군',
 '여수시',
 '영광군',
 '영암군',
 '완도군',
 '장성군',
 '장흥군',
 '진도군',
 '함평군',
 '해남군',
 '화순군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55    201207  전라남도  강진군   합계  32,925   18,093,276
231   201208  전라남도  강진군   합계  37,108   21,809,656
407   201209  전라남도  강진군   합계  35,436   19,284,134
583   201210  전라남도  강진군   합계  35,456   17,561,106
759   201211  전라남도  강진군   합계  44,104   24,252,525
...      ...   ...  ...  ...      ...          ...
399   201208  전라남도  화순군   합계  43,646   40,034,585
575   201209  전라남도  화순군   합계  43,803   36,834,415
751   201210  전라남도  화순군   합계  43,887   33,777,251
927   201211  전라남도  화순군   합계  45,736   39,499,493
1103  201212  전라남도  화순군   합계  43,924   44,298,522

[132 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[18093276, 21809656, 19284134, 17561106, 24252525, 23330111]
[24824492, 31378557, 29228219, 24736283, 33274035, 40121106]
[31136544, 31714727, 31264268, 30440020, 35110293, 36551923]
[465608865, 447697679, 468330785, 517196410, 498185176, 463599260]
[10336529, 12701717, 10765186, 10147396, 12358997, 14171223]
[69194994, 76933827, 65497277, 66292396, 76604372, 79651521]
[33300416, 35015185, 36758356, 31223008, 39184217, 43322082]
[73869506, 91033850, 82127948, 68143155, 74341855, 83962566]
[37156791, 43708151, 38433924, 35396386, 46992360, 47504033]
[17316343, 21492324, 20080759, 17703473, 21108518, 24484267]
[137978217, 155502271, 141402286, 129351317, 142110498, 154648989]
[14281900, 17344915, 17030975, 15369185, 20704149, 22019918]
[1020368225, 1058277631, 1008471982, 984908306, 985824386, 950810521]
[49883080, 42874874, 40279389, 41014486, 59020680, 49739191]
[115212407, 109122177, 109262857, 104485180, 112467842, 124922851]
[61002836, 69970483, 63937728, 60847274, 66382148, 59125214]
[44238917, 47483304, 45626592, 44961589, 51171622, 52634424]
[17497089, 22124625, 19474383, 17290164, 24778240, 27034957]
[16836251, 20980705, 19027497, 17657206, 23334655, 22466010]
[21379844, 25185902, 23130495, 21021479, 28677488, 28380473]
[37166663, 43752164, 37218128, 35032240, 55762228, 67360510]
[35931638, 40034585, 36834415, 33777251, 39499493, 44298522]
전라남도 지역별 합계 :  [124330808, 183562692, 196217775, 2860618175, 70481048, 434174387, 218803264, 473478880, 249191645, 122185684, 860993578, 106751042, 6008661051, 282811700, 675473314, 381265683, 286116448, 128199458, 120302324, 147775681, 276291933, 230375904]
전라남도 고객호수 평균:  [6128, 12137, 4616, 11821, 4533, 11012, 6734, 15060, 9783, 8153, 21146, 7563, 23527, 7557, 8062, 7220, 5738, 6053, 5710, 5723, 11658, 7345]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201207  전라남도  강진군   합계  32,925   18,093,276
1           201208  전라남도  강진군   합계  37,108   21,809,656
2           201209  전라남도  강진군   합계  35,436   19,284,134
3           201210  전라남도  강진군   합계  35,456   17,561,106
4           201211  전라남도  강진군   합계  44,104   24,252,525
..             ...   ...  ...  ...      ...          ...
149  201207-201212  전라남도  장흥군   합계     6053    128199458
150  201207-201212  전라남도  진도군   합계     5710    120302324
151  201207-201212  전라남도  함평군   합계     5723    147775681
152  201207-201212  전라남도  해남군   합계    11658    276291933
153  201207-201212  전라남도  화순군   합계     7345    230375904

[154 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201207-201212']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  201207-201212  전라남도  강진군   합계    6128   124330808
133  201207-201212  전라남도  고흥군   합계   12137   183562692
134  201207-201212  전라남도  곡성군   합계    4616   196217775
135  201207-201212  전라남도  광양시   합계   11821  2860618175
136  201207-201212  전라남도  구례군   합계    4533    70481048
137  201207-201212  전라남도  나주시   합계   11012   434174387
138  201207-201212  전라남도  담양군   합계    6734   218803264
139  201207-201212  전라남도  목포시   합계   15060   473478880
140  201207-201212  전라남도  무안군   합계    9783   249191645
141  201207-201212  전라남도  보성군   합계    8153   122185684
142  201207-201212  전라남도  순천시   합계   21146   860993578
143  201207-201212  전라남도  신안군   합계    7563   106751042
144  201207-201212  전라남도  여수시   합계   23527  6008661051
145  201207-201212  전라남도  영광군   합계    7557   282811700
146  201207-201212  전라남도  영암군   합계    8062   675473314
147  201207-201212  전라남도  완도군   합계    7220   381265683
148  201207-201212  전라남도  장성군   합계    5738   286116448
149  201207-201212  전라남도  장흥군   합계    6053   128199458
150  201207-201212  전라남도  진도군   합계    5710   120302324
151  201207-201212  전라남도  함평군   합계    5723   147775681
152  201207-201212  전라남도  해남군   합계   11658   276291933
153  201207-201212  전라남도  화순군   합계    7345   230375904

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53    201207  전라남도  강진군  일반용  2,717    4,138,480
229   201208  전라남도  강진군  일반용  2,783    5,110,175
405   201209  전라남도  강진군  일반용  2,777    4,424,609
581   201210  전라남도  강진군  일반용  2,769    3,876,419
757   201211  전라남도  강진군  일반용  2,784    4,439,319
...      ...   ...  ...  ...     ...          ...
397   201208  전라남도  화순군  일반용  3,855   12,124,340
573   201209  전라남도  화순군  일반용  3,860   10,373,933
749   201210  전라남도  화순군  일반용  3,879    8,913,509
925   201211  전라남도  화순군  일반용  3,934    9,775,505
1101  201212  전라남도  화순군  일반용  3,948   11,339,942

[132 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[4138480, 5110175, 4424609, 3876419, 4439319, 5224707]
[6487050, 8259594, 7379898, 6046737, 6593158, 7704818]
[3006720, 3708659, 3319544, 2801316, 3067175, 3561642]
[19524675, 24103996, 20894118, 16688169, 18261057, 21470119]
[4141844, 5098813, 4116069, 3608822, 4093091, 4658788]
[10728224, 13356756, 11695989, 9596548, 10668714, 12485096]
[5992800, 7587903, 6672370, 5562020, 6338076, 7346310]
[38380993, 48175406, 43186232, 33659576, 35097497, 40858824]
[9044448, 11228185, 9771375, 8022181, 8995428, 10744156]
[4723319, 6000621, 5344413, 4492777, 4910693, 5706074]
[39362811, 48114031, 41415334, 33651548, 35845218, 41676582]
[3407598, 4328412, 4062021, 3303146, 3875440, 4494199]
[49559732, 63518924, 47104437, 36116025, 38300711, 43903346]
[6289292, 7799294, 7151783, 6025925, 6656861, 7850760]
[8096620, 9741941, 8849753, 7302483, 7863560, 9209723]
[5987249, 7934019, 6858513, 5732323, 6084979, 7089829]
[7070942, 8415750, 7131962, 6341238, 7644200, 9040384]
[4452933, 5896384, 4890732, 4018983, 4483592, 5331414]
[2828629, 3715447, 3347619, 2589339, 3039073, 3526957]
[3409393, 4284097, 3700234, 3115390, 3507339, 3979320]
[9059772, 11160643, 9431067, 8138424, 9323064, 10931906]
[10201618, 12124340, 10373933, 8913509, 9775505, 11339942]
전라남도 지역별 일반용 합계 :  [27213709, 42471255, 19465056, 120942134, 25717427, 68531327, 39499479, 239358528, 57805773, 31177897, 240065524, 23470816, 278503175, 41773915, 51064080, 39686912, 45644476, 29074038, 19047064, 21995773, 58044876, 62728847]
전라남도 고객호수 평균:  [2772, 5142, 1913, 9525, 2121, 5444, 3227, 18111, 4617, 3339, 16843, 2845, 20105, 4194, 3828, 4711, 2948, 2965, 2486, 2080, 5586, 3883]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12680\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
0           201207  전라남도  강진군  일반용  2,717   4,138,480
1           201208  전라남도  강진군  일반용  2,783   5,110,175
2           201209  전라남도  강진군  일반용  2,777   4,424,609
3           201210  전라남도  강진군  일반용  2,769   3,876,419
4           201211  전라남도  강진군  일반용  2,784   4,439,319
..             ...   ...  ...  ...     ...         ...
149  201207-201212  전라남도  장흥군  일반용    2965    29074038
150  201207-201212  전라남도  진도군  일반용    2486    19047064
151  201207-201212  전라남도  함평군  일반용    2080    21995773
152  201207-201212  전라남도  해남군  일반용    5586    58044876
153  201207-201212  전라남도  화순군  일반용    3883    62728847

[154 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201207-201212']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
132  201207-201212  전라남도  강진군  일반용    2772   27213709
133  201207-201212  전라남도  고흥군  일반용    5142   42471255
134  201207-201212  전라남도  곡성군  일반용    1913   19465056
135  201207-201212  전라남도  광양시  일반용    9525  120942134
136  201207-201212  전라남도  구례군  일반용    2121   25717427
137  201207-201212  전라남도  나주시  일반용    5444   68531327
138  201207-201212  전라남도  담양군  일반용    3227   39499479
139  201207-201212  전라남도  목포시  일반용   18111  239358528
140  201207-201212  전라남도  무안군  일반용    4617   57805773
141  201207-201212  전라남도  보성군  일반용    3339   31177897
142  201207-201212  전라남도  순천시  일반용   16843  240065524
143  201207-201212  전라남도  신안군  일반용    2845   23470816
144  201207-201212  전라남도  여수시  일반용   20105  278503175
145  201207-201212  전라남도  영광군  일반용    4194   41773915
146  201207-201212  전라남도  영암군  일반용    3828   51064080
147  201207-201212  전라남도  완도군  일반용    4711   39686912
148  201207-201212  전라남도  장성군  일반용    2948   45644476
149  201207-201212  전라남도  장흥군  일반용    2965   29074038
150  201207-201212  전라남도  진도군  일반용    2486   19047064
151  201207-201212  전라남도  함평군  일반용    2080   21995773
152  201207-201212  전라남도  해남군  일반용    5586   58044876
153  201207-201212  전라남도  화순군  일반용    3883   62728847

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
132  201207-201212  전라남도  강진군  일반용    2772    27213709
132  201207-201212  전라남도  강진군   합계    6128   124330808
133  201207-201212  전라남도  고흥군  일반용    5142    42471255
133  201207-201212  전라남도  고흥군   합계   12137   183562692
134  201207-201212  전라남도  곡성군  일반용    1913    19465056
134  201207-201212  전라남도  곡성군   합계    4616   196217775
135  201207-201212  전라남도  광양시  일반용    9525   120942134
135  201207-201212  전라남도  광양시   합계   11821  2860618175
136  201207-201212  전라남도  구례군  일반용    2121    25717427
136  201207-201212  전라남도  구례군   합계    4533    70481048
137  201207-201212  전라남도  나주시  일반용    5444    68531327
137  201207-201212  전라남도  나주시   합계   11012   434174387
138  201207-201212  전라남도  담양군  일반용    3227    39499479
138  201207-201212  전라남도  담양군   합계    6734   218803264
139  201207-201212  전라남도  목포시   합계   15060   473478880
139  201207-201212  전라남도  목포시  일반용   18111   239358528
140  201207-201212  전라남도  무안군   합계    9783   249191645
140  201207-201212  전라남도  무안군  일반용    4617    57805773
141  201207-201212  전라남도  보성군   합계    8153   122185684
141  201207-201212  전라남도  보성군  일반용    3339    31177897
142  201207-201212  전라남도  순천시   합계   21146   860993578
142  201207-201212  전라남도  순천시  일반용   16843   240065524
143  201207-201212  전라남도  신안군   합계    7563   106751042
143  201207-201212  전라남도  신안군  일반용    2845    23470816
144  201207-201212  전라남도  여수시   합계   23527  6008661051
144  201207-201212  전라남도  여수시  일반용   20105   278503175
145  201207-201212  전라남도  영광군   합계    7557   282811700
145  201207-201212  전라남도  영광군  일반용    4194    41773915
146  201207-201212  전라남도  영암군   합계    8062   675473314
146  201207-201212  전라남도  영암군  일반용    3828    51064080
147  201207-201212  전라남도  완도군   합계    7220   381265683
147  201207-201212  전라남도  완도군  일반용    4711    39686912
148  201207-201212  전라남도  장성군  일반용    2948    45644476
148  201207-201212  전라남도  장성군   합계    5738   286116448
149  201207-201212  전라남도  장흥군   합계    6053   128199458
149  201207-201212  전라남도  장흥군  일반용    2965    29074038
150  201207-201212  전라남도  진도군   합계    5710   120302324
150  201207-201212  전라남도  진도군  일반용    2486    19047064
151  201207-201212  전라남도  함평군   합계    5723   147775681
151  201207-201212  전라남도  함평군  일반용    2080    21995773
152  201207-201212  전라남도  해남군   합계   11658   276291933
152  201207-201212  전라남도  해남군  일반용    5586    58044876
153  201207-201212  전라남도  화순군  일반용    3883    62728847
153  201207-201212  전라남도  화순군   합계    7345   230375904

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[27213709,
 42471255,
 19465056,
 120942134,
 25717427,
 68531327,
 39499479,
 239358528,
 57805773,
 31177897,
 240065524,
 23470816,
 278503175,
 41773915,
 51064080,
 39686912,
 45644476,
 29074038,
 19047064,
 21995773,
 58044876,
 62728847]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[124330808,
 183562692,
 196217775,
 2860618175,
 70481048,
 434174387,
 218803264,
 473478880,
 249191645,
 122185684,
 860993578,
 106751042,
 6008661051,
 282811700,
 675473314,
 381265683,
 286116448,
 128199458,
 120302324,
 147775681,
 276291933,
 230375904]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[21.89, 23.14, 9.92, 4.23, 36.49, 15.78, 18.05, 50.55, 23.2, 25.52, 27.88, 21.99, 4.64, 14.77, 7.56, 10.41, 15.95, 22.68, 15.83, 14.88, 21.01, 27.23]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    22
1    23
2    10
3     4
4    36
5    16
6    18
7    51
8    23
9    26
10   28
11   22
12    5
13   15
14    8
15   10
16   16
17   23
18   16
19   15
20   21
21   27
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강진군  일반용  22
1   고흥군  일반용  23
2   곡성군  일반용  10
3   광양시  일반용   4
4   구례군  일반용  36
5   나주시  일반용  16
6   담양군  일반용  18
7   목포시  일반용  51
8   무안군  일반용  23
9   보성군  일반용  26
10  순천시  일반용  28
11  신안군  일반용  22
12  여수시  일반용   5
13  영광군  일반용  15
14  영암군  일반용   8
15  완도군  일반용  10
16  장성군  일반용  16
17  장흥군  일반용  23
18  진도군  일반용  16
19  함평군  일반용  15
20  해남군  일반용  21
21  화순군  일반용  27

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201207-201212  전라남도  강진군  일반용    2772    27213709  22
1   201207-201212  전라남도  강진군   합계    6128   124330808 NaN
2   201207-201212  전라남도  고흥군  일반용    5142    42471255  23
3   201207-201212  전라남도  고흥군   합계   12137   183562692 NaN
4   201207-201212  전라남도  곡성군  일반용    1913    19465056  10
5   201207-201212  전라남도  곡성군   합계    4616   196217775 NaN
6   201207-201212  전라남도  광양시  일반용    9525   120942134   4
7   201207-201212  전라남도  광양시   합계   11821  2860618175 NaN
8   201207-201212  전라남도  구례군  일반용    2121    25717427  36
9   201207-201212  전라남도  구례군   합계    4533    70481048 NaN
10  201207-201212  전라남도  나주시  일반용    5444    68531327  16
11  201207-201212  전라남도  나주시   합계   11012   434174387 NaN
12  201207-201212  전라남도  담양군  일반용    3227    39499479  18
13  201207-201212  전라남도  담양군   합계    6734   218803264 NaN
15  201207-201212  전라남도  목포시  일반용   18111   239358528  51
14  201207-201212  전라남도  목포시   합계   15060   473478880 NaN
17  201207-201212  전라남도  무안군  일반용    4617    57805773  23
16  201207-201212  전라남도  무안군   합계    9783   249191645 NaN
19  201207-201212  전라남도  보성군  일반용    3339    31177897  26
18  201207-201212  전라남도  보성군   합계    8153   122185684 NaN
21  201207-201212  전라남도  순천시  일반용   16843   240065524  28
20  201207-201212  전라남도  순천시   합계   21146   860993578 NaN
23  201207-201212  전라남도  신안군  일반용    2845    23470816  22
22  201207-201212  전라남도  신안군   합계    7563   106751042 NaN
25  201207-201212  전라남도  여수시  일반용   20105   278503175   5
24  201207-201212  전라남도  여수시   합계   23527  6008661051 NaN
27  201207-201212  전라남도  영광군  일반용    4194    41773915  15
26  201207-201212  전라남도  영광군   합계    7557   282811700 NaN
29  201207-201212  전라남도  영암군  일반용    3828    51064080   8
28  201207-201212  전라남도  영암군   합계    8062   675473314 NaN
31  201207-201212  전라남도  완도군  일반용    4711    39686912  10
30  201207-201212  전라남도  완도군   합계    7220   381265683 NaN
32  201207-201212  전라남도  장성군  일반용    2948    45644476  16
33  201207-201212  전라남도  장성군   합계    5738   286116448 NaN
35  201207-201212  전라남도  장흥군  일반용    2965    29074038  23
34  201207-201212  전라남도  장흥군   합계    6053   128199458 NaN
37  201207-201212  전라남도  진도군  일반용    2486    19047064  16
36  201207-201212  전라남도  진도군   합계    5710   120302324 NaN
39  201207-201212  전라남도  함평군  일반용    2080    21995773  15
38  201207-201212  전라남도  함평군   합계    5723   147775681 NaN
41  201207-201212  전라남도  해남군  일반용    5586    58044876  21
40  201207-201212  전라남도  해남군   합계   11658   276291933 NaN
42  201207-201212  전라남도  화순군  일반용    3883    62728847  27
43  201207-201212  전라남도  화순군   합계    7345   230375904 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1207-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)