In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경상남도,전체(시 / 군 / 구),주택용,"1,099,958","326,532,725","36,319,215,339",111.2
4,201507,경상남도,전체(시 / 군 / 구),일반용,"212,784","470,849,620","72,041,447,546",153.0
...,...,...,...,...,...,...,...,...
907,201512,경상남도,합천군,산업용,952,"6,178,349","802,544,922",129.9
908,201512,경상남도,합천군,심 야,"2,232","4,144,698","311,293,446",75.1
909,201512,경상남도,합천군,일반용,"3,920","6,330,671","899,796,272",142.1
910,201512,경상남도,합천군,주택용,"27,806","4,676,305","574,205,977",122.8
911,201512,경상남도,합천군,합계,"48,428","32,633,408","3,241,187,696",99.3

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경상남도,전체(시 / 군 / 구),주택용,"1,099,958","326,532,725","36,319,215,339",111.2
4,201507,경상남도,전체(시 / 군 / 구),일반용,"212,784","470,849,620","72,041,447,546",153.0
5,201507,경상남도,전체(시 / 군 / 구),교육용,"1,611","28,830,012","4,099,528,639",142.2
6,201507,경상남도,전체(시 / 군 / 구),산업용,"36,343","1,727,402,791","225,424,232,975",130.5
...,...,...,...,...,...,...,...,...
907,201512,경상남도,합천군,산업용,952,"6,178,349","802,544,922",129.9
908,201512,경상남도,합천군,심 야,"2,232","4,144,698","311,293,446",75.1
909,201512,경상남도,합천군,일반용,"3,920","6,330,671","899,796,272",142.1
910,201512,경상남도,합천군,주택용,"27,806","4,676,305","574,205,977",122.8
911,201512,경상남도,합천군,합계,"48,428","32,633,408","3,241,187,696",99.3

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경상남도,전체(시 / 군 / 구),주택용,"1,099,958","326,532,725","36,319,215,339",111.2
4,201507,경상남도,전체(시 / 군 / 구),일반용,"212,784","470,849,620","72,041,447,546",153.0
5,201507,경상남도,전체(시 / 군 / 구),교육용,"1,611","28,830,012","4,099,528,639",142.2
6,201507,경상남도,전체(시 / 군 / 구),산업용,"36,343","1,727,402,791","225,424,232,975",130.5
7,201507,경상남도,전체(시 / 군 / 구),농사용,"172,848","103,207,184","5,303,597,617",51.4
...,...,...,...,...,...,...,...,...
907,201512,경상남도,합천군,산업용,952,"6,178,349","802,544,922",129.9
908,201512,경상남도,합천군,심 야,"2,232","4,144,698","311,293,446",75.1
909,201512,경상남도,합천군,일반용,"3,920","6,330,671","899,796,272",142.1
910,201512,경상남도,합천군,주택용,"27,806","4,676,305","574,205,977",122.8
911,201512,경상남도,합천군,합계,"48,428","32,633,408","3,241,187,696",99.3

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경상남도,전체(시 / 군 / 구),주택용,"1,099,958","326,532,725","36,319,215,339",111.2
4,201507,경상남도,전체(시 / 군 / 구),일반용,"212,784","470,849,620","72,041,447,546",153.0
5,201507,경상남도,전체(시 / 군 / 구),교육용,"1,611","28,830,012","4,099,528,639",142.2
6,201507,경상남도,전체(시 / 군 / 구),산업용,"36,343","1,727,402,791","225,424,232,975",130.5
7,201507,경상남도,전체(시 / 군 / 구),농사용,"172,848","103,207,184","5,303,597,617",51.4
8,201507,경상남도,전체(시 / 군 / 구),가로등,"145,116","19,147,632","2,372,638,047",123.9
9,201507,경상남도,전체(시 / 군 / 구),심 야,"96,386","33,976,683","1,908,435,017",56.2
10,201508,경상남도,전체(시 / 군 / 구),주택용,"1,101,583","407,592,005","53,573,444,975",131.4
11,201508,경상남도,전체(시 / 군 / 구),일반용,"213,381","573,575,001","83,141,082,849",145.0
12,201508,경상남도,전체(시 / 군 / 구),교육용,"1,617","28,908,845","4,116,738,388",142.4
13,201508,경상남도,전체(시 / 군 / 구),산업용,"36,354","1,569,519,173","202,668,898,572",129.1
14,201508,경상남도,전체(시 / 군 / 구),농사용,"174,093","135,027,346","6,651,656,970",49.3
15,201508,경상남도,전체(시 / 군 / 구),가로등,"146,892","20,386,814","2,428,893,036",119.1
16,201508,경상남도,전체(시 / 군 / 구),심 야,"96,198","28,474,935","1,635,192,552",57.4
17,201509,경상남도,전체(시 / 군 / 구),주택용,"1,103,440","350,519,290","40,304,794,019",115.0
18,201509,경상남도,전체(시 / 군 / 구),일반용,"213,943","503,531,766","66,610,838,310",132.3
19,201509,경상남도,전체(시 / 군 / 구),교육용,"1,621","30,427,624","3,611,911,244",118.7
20,201509,경상남도,전체(시 / 군 / 구),산업용,"36,403","1,590,250,310","171,778,497,056",108.0
21,201509,경상남도,전체(시 / 군 / 구),농사용,"175,335","127,707,154","6,369,238,398",49.9
22,201509,경상남도,전체(시 / 군 / 구),가로등,"147,359","21,540,062","2,490,209,842",115.6
23,201509,경상남도,전체(시 / 군 / 구),심 야,"96,041","28,468,164","1,613,652,727",56.7
24,201510,경상남도,전체(시 / 군 / 구),주택용,"1,105,527","321,108,559","35,613,944,673",110.9
25,201510,경상남도,전체(시 / 군 / 구),일반용,"214,145","425,885,109","51,113,105,063",120.0
26,201510,경상남도,전체(시 / 군 / 구),교육용,"1,621","25,184,463","2,909,367,262",115.5
27,201510,경상남도,전체(시 / 군 / 구),산업용,"36,433","1,636,074,844","165,510,586,311",101.2
28,201510,경상남도,전체(시 / 군 / 구),농사용,"176,134","110,168,847","5,770,937,344",52.4
29,201510,경상남도,전체(시 / 군 / 구),가로등,"147,552","23,063,124","2,549,428,243",110.5
30,201510,경상남도,전체(시 / 군 / 구),심 야,"95,861","42,920,324","2,386,411,761",55.6
31,201511,경상남도,전체(시 / 군 / 구),주택용,"1,107,927","344,413,819","41,003,697,534",119.1
32,201511,경상남도,전체(시 / 군 / 구),일반용,"214,192","441,100,935","60,753,270,346",137.7
33,201511,경상남도,전체(시 / 군 / 구),교육용,"1,618","29,786,845","3,625,013,678",121.7
34,201511,경상남도,전체(시 / 군 / 구),산업용,"36,516","1,634,397,477","198,283,700,550",121.3
35,201511,경상남도,전체(시 / 군 / 구),농사용,"201,788","156,765,994","7,751,568,783",49.4
36,201511,경상남도,전체(시 / 군 / 구),가로등,"147,945","25,015,130","2,692,676,889",107.6
37,201511,경상남도,전체(시 / 군 / 구),심 야,"95,846","78,647,472","5,039,686,162",64.1
38,201512,경상남도,전체(시 / 군 / 구),주택용,"1,109,555","359,420,887","44,388,988,933",123.5
39,201512,경상남도,전체(시 / 군 / 구),일반용,"214,811","488,260,967","66,984,643,044",137.2
40,201512,경상남도,전체(시 / 군 / 구),교육용,"1,621","38,587,857","4,596,581,615",119.1
41,201512,경상남도,전체(시 / 군 / 구),산업용,"36,566","1,717,737,233","212,767,720,690",123.9
42,201512,경상남도,전체(시 / 군 / 구),농사용,"178,600","216,660,895","10,699,124,120",49.4
43,201512,경상남도,전체(시 / 군 / 구),가로등,"148,373","25,928,297","2,741,738,355",105.7
44,201512,경상남도,전체(시 / 군 / 구),심 야,"95,706","123,782,873","9,349,770,520",75.5
45,합계,합계,합계,합계,"10,677,643","16,390,787,087","1,930,996,105,994",117.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_1404\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201507  경상남도  일반용  212,784   470,849,620
11  201508  경상남도  일반용  213,381   573,575,001
18  201509  경상남도  일반용  213,943   503,531,766
25  201510  경상남도  일반용  214,145   425,885,109
32  201511  경상남도  일반용  214,192   441,100,935
39  201512  경상남도  일반용  214,811   488,260,967

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  경상남도  거제시  일반용  17,192   37,361,017
197  201508  경상남도  거제시  일반용  17,214   46,594,145
341  201509  경상남도  거제시  일반용  17,270   41,288,801
485  201510  경상남도  거제시  일반용  17,272   34,726,629
629  201511  경상남도  거제시  일반용  17,333   36,037,800
..      ...   ...  ...  ...      ...          ...
333  201508  경상남도  합천군  일반용   3,925    6,685,406
477  201509  경상남도  합천군  일반용   3,939    5,792,555
621  201510  경상남도  합천군  일반용   3,941    5,209,846
765  201511  경상남도  합천군  일반용   3,915    5,693,888
909  201512  경상남도  합천군  일반용   3,920    6,330,671

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201507  경상남도  거제시   합계  117,820   185,389,376
199  201508  경상남도  거제시   합계  118,208   191,275,814
343  201509  경상남도  거제시   합계  118,731   179,520,660
487  201510  경상남도  거제시   합계  119,149   165,899,789
631  201511  경상남도  거제시   합계  120,863   176,984,449
..      ...   ...  ...  ...       ...           ...
335  201508  경상남도  합천군   합계   48,348    28,960,741
479  201509  경상남도  합천군   합계   48,511    26,936,572
623  201510  경상남도  합천군   합계   48,573    25,155,085
767  201511  경상남도  합천군   합계   50,589    30,497,411
911  201512  경상남도  합천군   합계   48,428    32,633,408

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[185389376, 191275814, 179520660, 165899789, 176984449, 193598107]
[30322505, 33745765, 32403512, 30863474, 35302527, 37802690]
[50176584, 52327774, 48166453, 44126809, 52545926, 58515075]
[409439061, 417017854, 413771873, 379122293, 412100085, 442526684]
[18250190, 23514943, 20528506, 18939231, 21110755, 21544495]
[74057985, 76609619, 73851716, 72163201, 82017329, 105262817]
[102346222, 106266370, 100358910, 94573392, 104183919, 109967992]
[19905736, 23184770, 22626176, 20627489, 25978101, 27279035]
[286925090, 293059259, 279756151, 271300262, 277940827, 296411207]
[28713308, 30946115, 29499236, 29054363, 32514872, 35006516]
[178919649, 194994921, 183254625, 170767077, 191744429, 230140257]
[66258229, 69899634, 64645667, 61323538, 68203811, 81928027]
[891000021, 877322255, 849873997, 864242673, 840209660, 914223023]
[95735224, 104366082, 98295333, 94231158, 96946709, 104593801]
[21561282, 24345299, 23503956, 23900036, 27981580, 30275706]
[208874210, 195300045, 184972542, 199957809, 212385195, 225670546]
[17116883, 20346859, 20478485, 18157591, 21480087, 22999623]
[24955092, 28960741, 26936572, 25155085, 30497411, 32633408]
경상남도 지역별 합계 :  [1092668195, 200440473, 305858621, 2473977850, 123888120, 483962667, 617696805, 139601307, 1705392796, 185734410, 1149820958, 412258906, 5236871629, 594168307, 151567859, 1227160347, 120579528, 169138309]
경상남도 고객호수 평균:  [19849, 8968, 8515, 31905, 8087, 15925, 12066, 6706, 18009, 5535, 30550, 9768, 75451, 13153, 8632, 8668, 6679, 8127]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201507  경상남도  거제시   합계  117,820   185,389,376
1           201508  경상남도  거제시   합계  118,208   191,275,814
2           201509  경상남도  거제시   합계  118,731   179,520,660
3           201510  경상남도  거제시   합계  119,149   165,899,789
4           201511  경상남도  거제시   합계  120,863   176,984,449
..             ...   ...  ...  ...       ...           ...
121  201507-201512  경상남도  통영시   합계     13153     594168307
122  201507-201512  경상남도  하동군   합계      8632     151567859
123  201507-201512  경상남도  함안군   합계      8668    1227160347
124  201507-201512  경상남도  함양군   합계      6679     120579528
125  201507-201512  경상남도  합천군   합계      8127     169138309

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201507-201512  경상남도  거제시   합계   19849  1092668195
109  201507-201512  경상남도  거창군   합계    8968   200440473
110  201507-201512  경상남도  고성군   합계    8515   305858621
111  201507-201512  경상남도  김해시   합계   31905  2473977850
112  201507-201512  경상남도  남해군   합계    8087   123888120
113  201507-201512  경상남도  밀양시   합계   15925   483962667
114  201507-201512  경상남도  사천시   합계   12066   617696805
115  201507-201512  경상남도  산청군   합계    6706   139601307
116  201507-201512  경상남도  양산시   합계   18009  1705392796
117  201507-201512  경상남도  의령군   합계    5535   185734410
118  201507-201512  경상남도  진주시   합계   30550  1149820958
119  201507-201512  경상남도  창녕군   합계    9768   412258906
120  201507-201512  경상남도  창원시   합계   75451  5236871629
121  201507-201512  경상남도  통영시   합계   13153   594168307
122  201507-201512  경상남도  하동군   합계    8632   151567859
123  201507-201512  경상남도  함안군   합계    8668  1227160347
124  201507-201512  경상남도  함양군   합계    6679   120579528
125  201507-201512  경상남도  합천군   합계    8127   169138309

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  경상남도  거제시  일반용  17,192   37,361,017
197  201508  경상남도  거제시  일반용  17,214   46,594,145
341  201509  경상남도  거제시  일반용  17,270   41,288,801
485  201510  경상남도  거제시  일반용  17,272   34,726,629
629  201511  경상남도  거제시  일반용  17,333   36,037,800
..      ...   ...  ...  ...      ...          ...
333  201508  경상남도  합천군  일반용   3,925    6,685,406
477  201509  경상남도  합천군  일반용   3,939    5,792,555
621  201510  경상남도  합천군  일반용   3,941    5,209,846
765  201511  경상남도  합천군  일반용   3,915    5,693,888
909  201512  경상남도  합천군  일반용   3,920    6,330,671

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[37361017, 46594145, 41288801, 34726629, 36037800, 38915525]
[7180515, 8743712, 7513254, 6727725, 7637983, 8756106]
[7029165, 8608486, 7675606, 6751522, 7291591, 7998086]
[72834411, 88856647, 76269119, 63468334, 65663486, 71985401]
[6761461, 9320853, 7620521, 6631007, 6896134, 7420698]
[13031411, 16248103, 14516376, 12295196, 13228437, 14663371]
[16622270, 20464883, 18415605, 15547041, 16215402, 18015276]
[4375076, 5616194, 4806962, 4259881, 4621607, 5098534]
[41357302, 50011164, 43659872, 37423703, 38778229, 43326917]
[3055934, 3711098, 3309753, 2910504, 3129197, 3458760]
[48972825, 58610440, 51903336, 44127962, 45720056, 50841025]
[9395927, 11427183, 9745665, 8528858, 9047717, 10217371]
[156089797, 187137710, 165261202, 137947423, 140282067, 155745549]
[21713203, 27509687, 24791527, 21057017, 21645166, 23203026]
[5853583, 7425450, 6520886, 5691564, 6152052, 6671297]
[9213381, 11007951, 9557209, 8350191, 8516790, 10591733]
[4535191, 5595889, 4883517, 4230706, 4543333, 5021621]
[5467151, 6685406, 5792555, 5209846, 5693888, 6330671]
경상남도 지역별 일반용 합계 :  [234923917, 46559295, 45354456, 439077398, 44650674, 83982894, 105280477, 28778254, 254557187, 19575246, 300175644, 58362721, 942463748, 139919626, 38314832, 57237255, 28810257, 35179517]
경상남도 고객호수 평균:  [17281, 4921, 4620, 28622, 4715, 8995, 9068, 3420, 16609, 2506, 24111, 5380, 55928, 10706, 4168, 5332, 3561, 3926]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_1404\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201507  경상남도  거제시  일반용  17,192   37,361,017
1           201508  경상남도  거제시  일반용  17,214   46,594,145
2           201509  경상남도  거제시  일반용  17,270   41,288,801
3           201510  경상남도  거제시  일반용  17,272   34,726,629
4           201511  경상남도  거제시  일반용  17,333   36,037,800
..             ...   ...  ...  ...      ...          ...
121  201507-201512  경상남도  통영시  일반용    10706    139919626
122  201507-201512  경상남도  하동군  일반용     4168     38314832
123  201507-201512  경상남도  함안군  일반용     5332     57237255
124  201507-201512  경상남도  함양군  일반용     3561     28810257
125  201507-201512  경상남도  합천군  일반용     3926     35179517

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201507-201512  경상남도  거제시  일반용   17281  234923917
109  201507-201512  경상남도  거창군  일반용    4921   46559295
110  201507-201512  경상남도  고성군  일반용    4620   45354456
111  201507-201512  경상남도  김해시  일반용   28622  439077398
112  201507-201512  경상남도  남해군  일반용    4715   44650674
113  201507-201512  경상남도  밀양시  일반용    8995   83982894
114  201507-201512  경상남도  사천시  일반용    9068  105280477
115  201507-201512  경상남도  산청군  일반용    3420   28778254
116  201507-201512  경상남도  양산시  일반용   16609  254557187
117  201507-201512  경상남도  의령군  일반용    2506   19575246
118  201507-201512  경상남도  진주시  일반용   24111  300175644
119  201507-201512  경상남도  창녕군  일반용    5380   58362721
120  201507-201512  경상남도  창원시  일반용   55928  942463748
121  201507-201512  경상남도  통영시  일반용   10706  139919626
122  201507-201512  경상남도  하동군  일반용    4168   38314832
123  201507-201512  경상남도  함안군  일반용    5332   57237255
124  201507-201512  경상남도  함양군  일반용    3561   28810257
125  201507-201512  경상남도  합천군  일반용    3926   35179517

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201507-201512  경상남도  거제시  일반용   17281   234923917
108  201507-201512  경상남도  거제시   합계   19849  1092668195
109  201507-201512  경상남도  거창군  일반용    4921    46559295
109  201507-201512  경상남도  거창군   합계    8968   200440473
110  201507-201512  경상남도  고성군  일반용    4620    45354456
110  201507-201512  경상남도  고성군   합계    8515   305858621
111  201507-201512  경상남도  김해시   합계   31905  2473977850
111  201507-201512  경상남도  김해시  일반용   28622   439077398
112  201507-201512  경상남도  남해군   합계    8087   123888120
112  201507-201512  경상남도  남해군  일반용    4715    44650674
113  201507-201512  경상남도  밀양시  일반용    8995    83982894
113  201507-201512  경상남도  밀양시   합계   15925   483962667
114  201507-201512  경상남도  사천시   합계   12066   617696805
114  201507-201512  경상남도  사천시  일반용    9068   105280477
115  201507-201512  경상남도  산청군  일반용    3420    28778254
115  201507-201512  경상남도  산청군   합계    6706   139601307
116  201507-201512  경상남도  양산시  일반용   16609   254557187
116  201507-201512  경상남도  양산시   합계   18009  1705392796
117  201507-201512  경상남도  의령군  일반용    2506    19575246
117  201507-201512  경상남도  의령군   합계    5535   185734410
118  201507-201512  경상남도  진주시   합계   30550  1149820958
118  201507-201512  경상남도  진주시  일반용   24111   300175644
119  201507-201512  경상남도  창녕군   합계    9768   412258906
119  201507-201512  경상남도  창녕군  일반용    5380    58362721
120  201507-201512  경상남도  창원시  일반용   55928   942463748
120  201507-201512  경상남도  창원시   합계   75451  5236871629
121  201507-201512  경상남도  통영시   합계   13153   594168307
121  201507-201512  경상남도  통영시  일반용   10706   139919626
122  201507-201512  경상남도  하동군   합계    8632   151567859
122  201507-201512  경상남도  하동군  일반용    4168    38314832
123  201507-201512  경상남도  함안군   합계    8668  1227160347
123  201507-201512  경상남도  함안군  일반용    5332    57237255
124  201507-201512  경상남도  함양군   합계    6679   120579528
124  201507-201512  경상남도  함양군  일반용    3561    28810257
125  201507-201512  경상남도  합천군  일반용    3926    35179517
125  201507-201512  경상남도  합천군   합계    8127   169138309

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[234923917,
 46559295,
 45354456,
 439077398,
 44650674,
 83982894,
 105280477,
 28778254,
 254557187,
 19575246,
 300175644,
 58362721,
 942463748,
 139919626,
 38314832,
 57237255,
 28810257,
 35179517]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1092668195,
 200440473,
 305858621,
 2473977850,
 123888120,
 483962667,
 617696805,
 139601307,
 1705392796,
 185734410,
 1149820958,
 412258906,
 5236871629,
 594168307,
 151567859,
 1227160347,
 120579528,
 169138309]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[21.5, 23.23, 14.83, 17.75, 36.04, 17.35, 17.04, 20.61, 14.93, 10.54, 26.11, 14.16, 18.0, 23.55, 25.28, 4.66, 23.89, 20.8]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    22
1    23
2    15
3    18
4    36
5    17
6    17
7    21
8    15
9    11
10   26
11   14
12   18
13   24
14   25
15    5
16   24
17   21
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  22
1   거창군  일반용  23
2   고성군  일반용  15
3   김해시  일반용  18
4   남해군  일반용  36
5   밀양시  일반용  17
6   사천시  일반용  17
7   산청군  일반용  21
8   양산시  일반용  15
9   의령군  일반용  11
10  진주시  일반용  26
11  창녕군  일반용  14
12  창원시  일반용  18
13  통영시  일반용  24
14  하동군  일반용  25
15  함안군  일반용   5
16  함양군  일반용  24
17  합천군  일반용  21

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201507-201512  경상남도  거제시  일반용   17281   234923917  22
1   201507-201512  경상남도  거제시   합계   19849  1092668195 NaN
2   201507-201512  경상남도  거창군  일반용    4921    46559295  23
3   201507-201512  경상남도  거창군   합계    8968   200440473 NaN
4   201507-201512  경상남도  고성군  일반용    4620    45354456  15
5   201507-201512  경상남도  고성군   합계    8515   305858621 NaN
7   201507-201512  경상남도  김해시  일반용   28622   439077398  18
6   201507-201512  경상남도  김해시   합계   31905  2473977850 NaN
9   201507-201512  경상남도  남해군  일반용    4715    44650674  36
8   201507-201512  경상남도  남해군   합계    8087   123888120 NaN
10  201507-201512  경상남도  밀양시  일반용    8995    83982894  17
11  201507-201512  경상남도  밀양시   합계   15925   483962667 NaN
13  201507-201512  경상남도  사천시  일반용    9068   105280477  17
12  201507-201512  경상남도  사천시   합계   12066   617696805 NaN
14  201507-201512  경상남도  산청군  일반용    3420    28778254  21
15  201507-201512  경상남도  산청군   합계    6706   139601307 NaN
16  201507-201512  경상남도  양산시  일반용   16609   254557187  15
17  201507-201512  경상남도  양산시   합계   18009  1705392796 NaN
18  201507-201512  경상남도  의령군  일반용    2506    19575246  11
19  201507-201512  경상남도  의령군   합계    5535   185734410 NaN
21  201507-201512  경상남도  진주시  일반용   24111   300175644  26
20  201507-201512  경상남도  진주시   합계   30550  1149820958 NaN
23  201507-201512  경상남도  창녕군  일반용    5380    58362721  14
22  201507-201512  경상남도  창녕군   합계    9768   412258906 NaN
24  201507-201512  경상남도  창원시  일반용   55928   942463748  18
25  201507-201512  경상남도  창원시   합계   75451  5236871629 NaN
27  201507-201512  경상남도  통영시  일반용   10706   139919626  24
26  201507-201512  경상남도  통영시   합계   13153   594168307 NaN
29  201507-201512  경상남도  하동군  일반용    4168    38314832  25
28  201507-201512  경상남도  하동군   합계    8632   151567859 NaN
31  201507-201512  경상남도  함안군  일반용    5332    57237255   5
30  201507-201512  경상남도  함안군   합계    8668  1227160347 NaN
33  201507-201512  경상남도  함양군  일반용    3561    28810257  24
32  201507-201512  경상남도  함양군   합계    6679   120579528 NaN
34  201507-201512  경상남도  합천군  일반용    3926    35179517  21
35  201507-201512  경상남도  합천군   합계    8127   169138309 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)