In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('부산광역시_계약종별 전력사용량 월별_14하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 부산광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 07 월 ~ 2014년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,부산광역시,전체(시 / 군 / 구),주택용,"929,492","353,153,301","42,640,100,812",120.7
4,201407,부산광역시,전체(시 / 군 / 구),일반용,"181,245","520,457,546","77,107,849,267",148.2
...,...,...,...,...,...,...,...,...
811,201412,부산광역시,해운대구,산업용,991,"22,128,264","2,703,664,714",122.2
812,201412,부산광역시,해운대구,심 야,"1,121","3,311,149","255,768,053",77.2
813,201412,부산광역시,해운대구,일반용,"13,629","71,951,449","9,856,884,773",137
814,201412,부산광역시,해운대구,주택용,"71,099","52,469,428","6,901,842,951",131.5
815,201412,부산광역시,해운대구,합계,"91,845","155,376,871","20,341,774,379",130.9

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,부산광역시,전체(시 / 군 / 구),주택용,"929,492","353,153,301","42,640,100,812",120.7
4,201407,부산광역시,전체(시 / 군 / 구),일반용,"181,245","520,457,546","77,107,849,267",148.2
5,201407,부산광역시,전체(시 / 군 / 구),교육용,"1,140","34,498,120","4,627,300,773",134.1
6,201407,부산광역시,전체(시 / 군 / 구),산업용,"24,228","725,872,637","94,257,985,345",129.9
...,...,...,...,...,...,...,...,...
811,201412,부산광역시,해운대구,산업용,991,"22,128,264","2,703,664,714",122.2
812,201412,부산광역시,해운대구,심 야,"1,121","3,311,149","255,768,053",77.2
813,201412,부산광역시,해운대구,일반용,"13,629","71,951,449","9,856,884,773",137
814,201412,부산광역시,해운대구,주택용,"71,099","52,469,428","6,901,842,951",131.5
815,201412,부산광역시,해운대구,합계,"91,845","155,376,871","20,341,774,379",130.9

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,부산광역시,전체(시 / 군 / 구),주택용,"929,492","353,153,301","42,640,100,812",120.7
4,201407,부산광역시,전체(시 / 군 / 구),일반용,"181,245","520,457,546","77,107,849,267",148.2
5,201407,부산광역시,전체(시 / 군 / 구),교육용,"1,140","34,498,120","4,627,300,773",134.1
6,201407,부산광역시,전체(시 / 군 / 구),산업용,"24,228","725,872,637","94,257,985,345",129.9
7,201407,부산광역시,전체(시 / 군 / 구),농사용,"9,446","6,389,720","329,061,130",51.5
...,...,...,...,...,...,...,...,...
811,201412,부산광역시,해운대구,산업용,991,"22,128,264","2,703,664,714",122.2
812,201412,부산광역시,해운대구,심 야,"1,121","3,311,149","255,768,053",77.2
813,201412,부산광역시,해운대구,일반용,"13,629","71,951,449","9,856,884,773",137
814,201412,부산광역시,해운대구,주택용,"71,099","52,469,428","6,901,842,951",131.5
815,201412,부산광역시,해운대구,합계,"91,845","155,376,871","20,341,774,379",130.9

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,부산광역시,전체(시 / 군 / 구),주택용,"929,492","353,153,301","42,640,100,812",120.7
4,201407,부산광역시,전체(시 / 군 / 구),일반용,"181,245","520,457,546","77,107,849,267",148.2
5,201407,부산광역시,전체(시 / 군 / 구),교육용,"1,140","34,498,120","4,627,300,773",134.1
6,201407,부산광역시,전체(시 / 군 / 구),산업용,"24,228","725,872,637","94,257,985,345",129.9
7,201407,부산광역시,전체(시 / 군 / 구),농사용,"9,446","6,389,720","329,061,130",51.5
8,201407,부산광역시,전체(시 / 군 / 구),가로등,"76,093","12,253,521","1,447,615,925",118.1
9,201407,부산광역시,전체(시 / 군 / 구),심 야,"25,773","19,137,900","1,161,231,159",60.7
10,201408,부산광역시,전체(시 / 군 / 구),주택용,"929,883","399,525,912","54,109,026,829",135.4
11,201408,부산광역시,전체(시 / 군 / 구),일반용,"181,594","582,890,384","83,109,372,776",142.6
12,201408,부산광역시,전체(시 / 군 / 구),교육용,"1,143","35,071,500","4,662,792,609",133.0
13,201408,부산광역시,전체(시 / 군 / 구),산업용,"24,266","684,404,543","87,794,265,347",128.3
14,201408,부산광역시,전체(시 / 군 / 구),농사용,"9,477","7,796,251","377,981,775",48.5
15,201408,부산광역시,전체(시 / 군 / 구),가로등,"76,229","12,754,035","1,475,405,373",115.7
16,201408,부산광역시,전체(시 / 군 / 구),심 야,"25,680","17,202,437","1,063,452,695",61.8
17,201409,부산광역시,전체(시 / 군 / 구),주택용,"930,379","369,191,696","45,756,384,207",123.9
18,201409,부산광역시,전체(시 / 군 / 구),일반용,"181,515","518,324,313","65,383,695,639",126.1
19,201409,부산광역시,전체(시 / 군 / 구),교육용,"1,144","33,104,411","3,765,426,749",113.7
20,201409,부산광역시,전체(시 / 군 / 구),산업용,"24,296","683,276,076","73,933,313,702",108.2
21,201409,부산광역시,전체(시 / 군 / 구),농사용,"9,520","9,960,210","420,803,693",42.2
22,201409,부산광역시,전체(시 / 군 / 구),가로등,"76,315","13,471,436","1,519,670,578",112.8
23,201409,부산광역시,전체(시 / 군 / 구),심 야,"25,592","16,995,685","1,017,506,982",59.9
24,201410,부산광역시,전체(시 / 군 / 구),주택용,"931,463","340,703,840","38,942,844,147",114.3
25,201410,부산광역시,전체(시 / 군 / 구),일반용,"181,378","464,848,468","53,341,782,610",114.8
26,201410,부산광역시,전체(시 / 군 / 구),교육용,"1,148","31,103,157","3,180,346,001",102.3
27,201410,부산광역시,전체(시 / 군 / 구),산업용,"24,342","700,035,767","71,758,659,078",102.5
28,201410,부산광역시,전체(시 / 군 / 구),농사용,"9,525","6,660,021","340,063,370",51.1
29,201410,부산광역시,전체(시 / 군 / 구),가로등,"76,361","14,455,312","1,567,101,782",108.4
30,201410,부산광역시,전체(시 / 군 / 구),심 야,"25,530","18,346,123","1,057,969,771",57.7
31,201411,부산광역시,전체(시 / 군 / 구),주택용,"932,291","366,225,341","44,852,229,430",122.5
32,201411,부산광역시,전체(시 / 군 / 구),일반용,"181,422","454,879,089","59,685,255,650",131.2
33,201411,부산광역시,전체(시 / 군 / 구),교육용,"1,148","32,815,710","3,699,723,519",112.7
34,201411,부산광역시,전체(시 / 군 / 구),산업용,"24,402","685,883,791","84,379,421,863",123.0
35,201411,부산광역시,전체(시 / 군 / 구),농사용,"9,690","7,737,007","392,383,295",50.7
36,201411,부산광역시,전체(시 / 군 / 구),가로등,"76,551","15,669,368","1,668,688,161",106.5
37,201411,부산광역시,전체(시 / 군 / 구),심 야,"25,498","29,988,047","1,960,969,713",65.4
38,201412,부산광역시,전체(시 / 군 / 구),주택용,"933,401","384,652,594","49,351,597,333",128.3
39,201412,부산광역시,전체(시 / 군 / 구),일반용,"181,920","518,609,737","71,789,497,766",138.4
40,201412,부산광역시,전체(시 / 군 / 구),교육용,"1,149","45,453,908","5,101,707,934",112.2
41,201412,부산광역시,전체(시 / 군 / 구),산업용,"24,455","707,283,887","89,558,687,392",126.6
42,201412,부산광역시,전체(시 / 군 / 구),농사용,"9,625","9,843,483","494,729,209",50.3
43,201412,부산광역시,전체(시 / 군 / 구),가로등,"76,743","16,558,520","1,733,751,825",104.7
44,201412,부산광역시,전체(시 / 군 / 구),심 야,"25,444","47,936,200","3,648,576,296",76.1
45,합계,합계,합계,합계,"7,497,936","9,955,421,004","1,234,466,229,510",124

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_10188\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201407  부산광역시  일반용  181,245   520,457,546
11  201408  부산광역시  일반용  181,594   582,890,384
18  201409  부산광역시  일반용  181,515   518,324,313
25  201410  부산광역시  일반용  181,378   464,848,468
32  201411  부산광역시  일반용  181,422   454,879,089
39  201412  부산광역시  일반용  181,920   518,609,737

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201407  부산광역시   강서구  일반용   7,421   20,708,486
181  201408  부산광역시   강서구  일반용   7,473   22,895,054
309  201409  부산광역시   강서구  일반용   7,479   20,409,712
437  201410  부산광역시   강서구  일반용   7,462   18,615,793
565  201411  부산광역시   강서구  일반용   7,497   19,267,709
..      ...    ...   ...  ...      ...          ...
301  201408  부산광역시  해운대구  일반용  13,651   83,945,584
429  201409  부산광역시  해운대구  일반용  13,651   73,475,977
557  201410  부산광역시  해운대구  일반용  13,622   65,042,588
685  201411  부산광역시  해운대구  일반용  13,615   62,575,342
813  201412  부산광역시  해운대구  일반용  13,629   71,951,449

[96 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'부산광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강서구',
 '금정구',
 '기장군',
 '남구',
 '동구',
 '동래구',
 '부산진구',
 '북구',
 '사상구',
 '사하구',
 '서구',
 '수영구',
 '연제구',
 '영도구',
 '중구',
 '해운대구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
55   201407  부산광역시   강서구   합계  42,793   287,289,182
183  201408  부산광역시   강서구   합계  42,977   275,104,567
311  201409  부산광역시   강서구   합계  43,073   268,315,473
439  201410  부산광역시   강서구   합계  43,161   274,370,638
567  201411  부산광역시   강서구   합계  43,369   270,547,226
..      ...    ...   ...  ...      ...           ...
303  201408  부산광역시  해운대구   합계  91,731   167,824,597
431  201409  부산광역시  해운대구   합계  91,750   152,662,185
559  201410  부산광역시  해운대구   합계  91,773   141,343,221
687  201411  부산광역시  해운대구   합계  91,836   141,146,653
815  201412  부산광역시  해운대구   합계  91,845   155,376,871

[96 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[287289182, 275104567, 268315473, 274370638, 270547226, 289704411]
[85713499, 93099475, 84899381, 79494738, 83403735, 94627461]
[73214735, 77125824, 87152853, 81982627, 84902957, 88334287]
[113265929, 120763339, 112417261, 107711724, 109255943, 118492277]
[42733363, 46054187, 42068635, 38456121, 38961516, 44558436]
[74522673, 82529352, 74953675, 67804861, 70638417, 79669423]
[138384261, 151918114, 137000240, 124498746, 125787446, 141466242]
[71338526, 78511886, 71915796, 65837343, 68814719, 75383102]
[155005308, 151794533, 145777400, 144334872, 149878220, 166245243]
[245967733, 240296367, 233770351, 240294708, 235849335, 236016758]
[46902051, 51282985, 47600460, 44162053, 45357226, 50436969]
[45183058, 51737931, 47279252, 42338424, 43797932, 48573348]
[63699336, 69637537, 62911877, 55867551, 57973472, 65549367]
[36977155, 39965988, 37559645, 34670474, 35387235, 40071402]
[36378390, 41998380, 38039343, 32984587, 31496321, 35832732]
[155187546, 167824597, 152662185, 141343221, 141146653, 155376871]
부산광역시 지역별 합계 :  [1665331497, 521238289, 492713283, 681906473, 252832258, 450118401, 819055049, 431801372, 913035576, 1432195252, 285741744, 278909945, 375639140, 224631899, 216729753, 913541073]
부산광역시 고객호수 평균:  [7193, 17329, 7736, 17095, 8969, 15966, 23936, 12596, 13268, 18736, 10376, 11799, 12068, 9812, 6095, 15295]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0           201407  부산광역시   강서구   합계  42,793   287,289,182
1           201408  부산광역시   강서구   합계  42,977   275,104,567
2           201409  부산광역시   강서구   합계  43,073   268,315,473
3           201410  부산광역시   강서구   합계  43,161   274,370,638
4           201411  부산광역시   강서구   합계  43,369   270,547,226
..             ...    ...   ...  ...      ...           ...
107  201407-201412  부산광역시   수영구   합계    11799     278909945
108  201407-201412  부산광역시   연제구   합계    12068     375639140
109  201407-201412  부산광역시   영도구   합계     9812     224631899
110  201407-201412  부산광역시    중구   합계     6095     216729753
111  201407-201412  부산광역시  해운대구   합계    15295     913541073

[112 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201407-201412']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201407-201412  부산광역시   강서구   합계    7193  1665331497
97   201407-201412  부산광역시   금정구   합계   17329   521238289
98   201407-201412  부산광역시   기장군   합계    7736   492713283
99   201407-201412  부산광역시    남구   합계   17095   681906473
100  201407-201412  부산광역시    동구   합계    8969   252832258
101  201407-201412  부산광역시   동래구   합계   15966   450118401
102  201407-201412  부산광역시  부산진구   합계   23936   819055049
103  201407-201412  부산광역시    북구   합계   12596   431801372
104  201407-201412  부산광역시   사상구   합계   13268   913035576
105  201407-201412  부산광역시   사하구   합계   18736  1432195252
106  201407-201412  부산광역시    서구   합계   10376   285741744
107  201407-201412  부산광역시   수영구   합계   11799   278909945
108  201407-201412  부산광역시   연제구   합계   12068   375639140
109  201407-201412  부산광역시   영도구   합계    9812   224631899
110  201407-201412  부산광역시    중구   합계    6095   216729753
111  201407-201412  부산광역시  해운대구   합계   15295   913541073

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201407  부산광역시   강서구  일반용   7,421   20,708,486
181  201408  부산광역시   강서구  일반용   7,473   22,895,054
309  201409  부산광역시   강서구  일반용   7,479   20,409,712
437  201410  부산광역시   강서구  일반용   7,462   18,615,793
565  201411  부산광역시   강서구  일반용   7,497   19,267,709
..      ...    ...   ...  ...      ...          ...
301  201408  부산광역시  해운대구  일반용  13,651   83,945,584
429  201409  부산광역시  해운대구  일반용  13,651   73,475,977
557  201410  부산광역시  해운대구  일반용  13,622   65,042,588
685  201411  부산광역시  해운대구  일반용  13,615   62,575,342
813  201412  부산광역시  해운대구  일반용  13,629   71,951,449

[96 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[20708486, 22895054, 20409712, 18615793, 19267709, 22602391]
[31226623, 35119127, 30934566, 27148049, 27594278, 31857736]
[17115183, 19284931, 17562828, 25194567, 23620412, 23575111]
[29540318, 33604545, 30585604, 27463251, 27853607, 31602341]
[25087700, 27424394, 24224934, 21333727, 20401581, 24030083]
[36133186, 40639964, 35936272, 31180657, 30595796, 35461283]
[70759689, 79162899, 69777994, 60509691, 57742782, 65764737]
[28817986, 32425916, 28757267, 24997278, 25108869, 28718064]
[35807923, 39466504, 35062871, 31123035, 31043140, 36258318]
[32787082, 38157570, 34908876, 30766711, 30599577, 34602200]
[17691964, 19795873, 17719106, 15690259, 15612456, 17612874]
[23860977, 27565849, 24713070, 21635480, 21115812, 23689199]
[32984626, 36440184, 31857080, 27643193, 27420224, 32025946]
[10867913, 12359777, 11293676, 9996290, 9907257, 11105653]
[29799242, 34602213, 31104480, 26507899, 24420247, 27752352]
[77268648, 83945584, 73475977, 65042588, 62575342, 71951449]
부산광역시 지역별 일반용 합계 :  [124499145, 183880379, 126353032, 180649666, 142502419, 209947158, 403717792, 168825380, 208761791, 201822016, 104122532, 142580387, 188371253, 65530566, 174186433, 434259588]
부산광역시 고객호수 평균:  [7484, 15088, 7040, 11826, 7601, 15512, 22780, 10489, 13422, 14164, 6649, 10095, 10742, 5909, 9072, 13633]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10188\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분 고객호수(호)     사용량(kWh)
0           201407  부산광역시   강서구  일반용  7,421   20,708,486
1           201408  부산광역시   강서구  일반용  7,473   22,895,054
2           201409  부산광역시   강서구  일반용  7,479   20,409,712
3           201410  부산광역시   강서구  일반용  7,462   18,615,793
4           201411  부산광역시   강서구  일반용  7,497   19,267,709
..             ...    ...   ...  ...     ...          ...
107  201407-201412  부산광역시   수영구  일반용   10095    142580387
108  201407-201412  부산광역시   연제구  일반용   10742    188371253
109  201407-201412  부산광역시   영도구  일반용    5909     65530566
110  201407-201412  부산광역시    중구  일반용    9072    174186433
111  201407-201412  부산광역시  해운대구  일반용   13633    434259588

[112 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201407-201412']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)   사용량(kWh)
96   201407-201412  부산광역시   강서구  일반용    7484  124499145
97   201407-201412  부산광역시   금정구  일반용   15088  183880379
98   201407-201412  부산광역시   기장군  일반용    7040  126353032
99   201407-201412  부산광역시    남구  일반용   11826  180649666
100  201407-201412  부산광역시    동구  일반용    7601  142502419
101  201407-201412  부산광역시   동래구  일반용   15512  209947158
102  201407-201412  부산광역시  부산진구  일반용   22780  403717792
103  201407-201412  부산광역시    북구  일반용   10489  168825380
104  201407-201412  부산광역시   사상구  일반용   13422  208761791
105  201407-201412  부산광역시   사하구  일반용   14164  201822016
106  201407-201412  부산광역시    서구  일반용    6649  104122532
107  201407-201412  부산광역시   수영구  일반용   10095  142580387
108  201407-201412  부산광역시   연제구  일반용   10742  188371253
109  201407-201412  부산광역시   영도구  일반용    5909   65530566
110  201407-201412  부산광역시    중구  일반용    9072  174186433
111  201407-201412  부산광역시  해운대구  일반용   13633  434259588

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201407-201412  부산광역시   강서구  일반용    7484   124499145
96   201407-201412  부산광역시   강서구   합계    7193  1665331497
97   201407-201412  부산광역시   금정구   합계   17329   521238289
97   201407-201412  부산광역시   금정구  일반용   15088   183880379
98   201407-201412  부산광역시   기장군   합계    7736   492713283
98   201407-201412  부산광역시   기장군  일반용    7040   126353032
99   201407-201412  부산광역시    남구  일반용   11826   180649666
99   201407-201412  부산광역시    남구   합계   17095   681906473
100  201407-201412  부산광역시    동구  일반용    7601   142502419
100  201407-201412  부산광역시    동구   합계    8969   252832258
101  201407-201412  부산광역시   동래구  일반용   15512   209947158
101  201407-201412  부산광역시   동래구   합계   15966   450118401
102  201407-201412  부산광역시  부산진구  일반용   22780   403717792
102  201407-201412  부산광역시  부산진구   합계   23936   819055049
103  201407-201412  부산광역시    북구  일반용   10489   168825380
103  201407-201412  부산광역시    북구   합계   12596   431801372
104  201407-201412  부산광역시   사상구   합계   13268   913035576
104  201407-201412  부산광역시   사상구  일반용   13422   208761791
105  201407-201412  부산광역시   사하구   합계   18736  1432195252
105  201407-201412  부산광역시   사하구  일반용   14164   201822016
106  201407-201412  부산광역시    서구  일반용    6649   104122532
106  201407-201412  부산광역시    서구   합계   10376   285741744
107  201407-201412  부산광역시   수영구   합계   11799   278909945
107  201407-201412  부산광역시   수영구  일반용   10095   142580387
108  201407-201412  부산광역시   연제구   합계   12068   375639140
108  201407-201412  부산광역시   연제구  일반용   10742   188371253
109  201407-201412  부산광역시   영도구   합계    9812   224631899
109  201407-201412  부산광역시   영도구  일반용    5909    65530566
110  201407-201412  부산광역시    중구   합계    6095   216729753
110  201407-201412  부산광역시    중구  일반용    9072   174186433
111  201407-201412  부산광역시  해운대구  일반용   13633   434259588
111  201407-201412  부산광역시  해운대구   합계   15295   913541073

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[124499145,
 183880379,
 126353032,
 180649666,
 142502419,
 209947158,
 403717792,
 168825380,
 208761791,
 201822016,
 104122532,
 142580387,
 188371253,
 65530566,
 174186433,
 434259588]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1665331497,
 521238289,
 492713283,
 681906473,
 252832258,
 450118401,
 819055049,
 431801372,
 913035576,
 1432195252,
 285741744,
 278909945,
 375639140,
 224631899,
 216729753,
 913541073]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[7.48, 35.28, 25.64, 26.49, 56.36, 46.64, 49.29, 39.1, 22.86, 14.09, 36.44, 51.12, 50.15, 29.17, 80.37, 47.54]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0     7
1    35
2    26
3    26
4    56
5    47
6    49
7    39
8    23
9    14
10   36
11   51
12   50
13   29
14   80
15   48
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강서구  일반용   7
1    금정구  일반용  35
2    기장군  일반용  26
3     남구  일반용  26
4     동구  일반용  56
5    동래구  일반용  47
6   부산진구  일반용  49
7     북구  일반용  39
8    사상구  일반용  23
9    사하구  일반용  14
10    서구  일반용  36
11   수영구  일반용  51
12   연제구  일반용  50
13   영도구  일반용  29
14    중구  일반용  80
15  해운대구  일반용  48

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201407-201412  부산광역시   강서구  일반용    7484   124499145   7
1   201407-201412  부산광역시   강서구   합계    7193  1665331497 NaN
3   201407-201412  부산광역시   금정구  일반용   15088   183880379  35
2   201407-201412  부산광역시   금정구   합계   17329   521238289 NaN
5   201407-201412  부산광역시   기장군  일반용    7040   126353032  26
4   201407-201412  부산광역시   기장군   합계    7736   492713283 NaN
6   201407-201412  부산광역시    남구  일반용   11826   180649666  26
7   201407-201412  부산광역시    남구   합계   17095   681906473 NaN
8   201407-201412  부산광역시    동구  일반용    7601   142502419  56
9   201407-201412  부산광역시    동구   합계    8969   252832258 NaN
10  201407-201412  부산광역시   동래구  일반용   15512   209947158  47
11  201407-201412  부산광역시   동래구   합계   15966   450118401 NaN
12  201407-201412  부산광역시  부산진구  일반용   22780   403717792  49
13  201407-201412  부산광역시  부산진구   합계   23936   819055049 NaN
14  201407-201412  부산광역시    북구  일반용   10489   168825380  39
15  201407-201412  부산광역시    북구   합계   12596   431801372 NaN
17  201407-201412  부산광역시   사상구  일반용   13422   208761791  23
16  201407-201412  부산광역시   사상구   합계   13268   913035576 NaN
19  201407-201412  부산광역시   사하구  일반용   14164   201822016  14
18  201407-201412  부산광역시   사하구   합계   18736  1432195252 NaN
20  201407-201412  부산광역시    서구  일반용    6649   104122532  36
21  201407-201412  부산광역시    서구   합계   10376   285741744 NaN
23  201407-201412  부산광역시   수영구  일반용   10095   142580387  51
22  201407-201412  부산광역시   수영구   합계   11799   278909945 NaN
25  201407-201412  부산광역시   연제구  일반용   10742   188371253  50
24  201407-201412  부산광역시   연제구   합계   12068   375639140 NaN
27  201407-201412  부산광역시   영도구  일반용    5909    65530566  29
26  201407-201412  부산광역시   영도구   합계    9812   224631899 NaN
29  201407-201412  부산광역시    중구  일반용    9072   174186433  80
28  201407-201412  부산광역시    중구   합계    6095   216729753 NaN
30  201407-201412  부산광역시  해운대구  일반용   13633   434259588  48
31  201407-201412  부산광역시  해운대구   합계   15295   913541073 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1407-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)