In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('부산광역시_계약종별 전력사용량 월별_14상반기.csv' , encoding='utf-8')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 부산광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 01 월 ~ 2014년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,부산광역시,전체(시 / 군 / 구),주택용,"924,279","411,410,097","56,884,158,097",138.3
4,201401,부산광역시,전체(시 / 군 / 구),일반용,"180,319","561,325,666","74,896,988,521",133.4
...,...,...,...,...,...,...,...,...
811,201406,부산광역시,해운대구,산업용,994,"20,436,989","2,456,919,651",120.2
812,201406,부산광역시,해운대구,심 야,"1,142","2,759,794","166,414,098",60.3
813,201406,부산광역시,해운대구,일반용,"13,571","66,651,411","8,858,200,276",132.9
814,201406,부산광역시,해운대구,주택용,"71,039","49,363,234","6,232,508,932",126.3
815,201406,부산광역시,해운대구,합계,"91,695","143,372,897","18,222,873,561",127.1

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,부산광역시,전체(시 / 군 / 구),주택용,"924,279","411,410,097","56,884,158,097",138.3
4,201401,부산광역시,전체(시 / 군 / 구),일반용,"180,319","561,325,666","74,896,988,521",133.4
5,201401,부산광역시,전체(시 / 군 / 구),교육용,"1,141","43,256,422","5,030,386,012",116.3
6,201401,부산광역시,전체(시 / 군 / 구),산업용,"23,930","705,998,482","88,524,550,546",125.4
...,...,...,...,...,...,...,...,...
811,201406,부산광역시,해운대구,산업용,994,"20,436,989","2,456,919,651",120.2
812,201406,부산광역시,해운대구,심 야,"1,142","2,759,794","166,414,098",60.3
813,201406,부산광역시,해운대구,일반용,"13,571","66,651,411","8,858,200,276",132.9
814,201406,부산광역시,해운대구,주택용,"71,039","49,363,234","6,232,508,932",126.3
815,201406,부산광역시,해운대구,합계,"91,695","143,372,897","18,222,873,561",127.1

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,부산광역시,전체(시 / 군 / 구),주택용,"924,279","411,410,097","56,884,158,097",138.3
4,201401,부산광역시,전체(시 / 군 / 구),일반용,"180,319","561,325,666","74,896,988,521",133.4
5,201401,부산광역시,전체(시 / 군 / 구),교육용,"1,141","43,256,422","5,030,386,012",116.3
6,201401,부산광역시,전체(시 / 군 / 구),산업용,"23,930","705,998,482","88,524,550,546",125.4
7,201401,부산광역시,전체(시 / 군 / 구),농사용,"9,169","12,138,929","565,052,613",46.5
...,...,...,...,...,...,...,...,...
811,201406,부산광역시,해운대구,산업용,994,"20,436,989","2,456,919,651",120.2
812,201406,부산광역시,해운대구,심 야,"1,142","2,759,794","166,414,098",60.3
813,201406,부산광역시,해운대구,일반용,"13,571","66,651,411","8,858,200,276",132.9
814,201406,부산광역시,해운대구,주택용,"71,039","49,363,234","6,232,508,932",126.3
815,201406,부산광역시,해운대구,합계,"91,695","143,372,897","18,222,873,561",127.1

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,부산광역시,전체(시 / 군 / 구),주택용,"924,279","411,410,097","56,884,158,097",138.3
4,201401,부산광역시,전체(시 / 군 / 구),일반용,"180,319","561,325,666","74,896,988,521",133.4
5,201401,부산광역시,전체(시 / 군 / 구),교육용,"1,141","43,256,422","5,030,386,012",116.3
6,201401,부산광역시,전체(시 / 군 / 구),산업용,"23,930","705,998,482","88,524,550,546",125.4
7,201401,부산광역시,전체(시 / 군 / 구),농사용,"9,169","12,138,929","565,052,613",46.5
8,201401,부산광역시,전체(시 / 군 / 구),가로등,"74,575","16,740,748","1,755,453,706",104.9
9,201401,부산광역시,전체(시 / 군 / 구),심 야,"26,314","66,471,242","5,059,769,152",76.1
10,201402,부산광역시,전체(시 / 군 / 구),주택용,"925,670","412,074,772","57,040,701,728",138.4
11,201402,부산광역시,전체(시 / 군 / 구),일반용,"180,353","533,907,219","72,271,527,093",135.4
12,201402,부산광역시,전체(시 / 군 / 구),교육용,"1,136","40,487,789","4,795,732,205",118.4
13,201402,부산광역시,전체(시 / 군 / 구),산업용,"23,987","662,689,707","84,805,249,121",128.0
14,201402,부산광역시,전체(시 / 군 / 구),농사용,"9,181","11,564,198","546,572,456",47.3
15,201402,부산광역시,전체(시 / 군 / 구),가로등,"74,880","16,036,568","1,746,187,255",108.9
16,201402,부산광역시,전체(시 / 군 / 구),심 야,"26,244","64,700,120","4,921,555,398",76.1
17,201403,부산광역시,전체(시 / 군 / 구),주택용,"926,658","361,046,002","43,973,206,942",121.8
18,201403,부산광역시,전체(시 / 군 / 구),일반용,"180,414","485,624,956","60,143,821,684",123.8
19,201403,부산광역시,전체(시 / 군 / 구),교육용,"1,140","40,240,448","4,261,428,016",105.9
20,201403,부산광역시,전체(시 / 군 / 구),산업용,"24,042","711,610,784","74,727,156,578",105.0
21,201403,부산광역시,전체(시 / 군 / 구),농사용,"9,332","9,391,567","455,654,065",48.5
22,201403,부산광역시,전체(시 / 군 / 구),가로등,"75,156","15,139,062","1,640,830,835",108.4
23,201403,부산광역시,전체(시 / 군 / 구),심 야,"26,190","52,800,977","3,518,425,530",66.6
24,201404,부산광역시,전체(시 / 군 / 구),주택용,"927,523","375,111,378","46,818,103,617",124.8
25,201404,부산광역시,전체(시 / 군 / 구),일반용,"180,557","465,683,769","53,530,626,346",115.0
26,201404,부산광역시,전체(시 / 군 / 구),교육용,"1,142","36,620,699","3,650,199,056",99.7
27,201404,부산광역시,전체(시 / 군 / 구),산업용,"24,084","724,796,213","73,736,019,260",101.7
28,201404,부산광역시,전체(시 / 군 / 구),농사용,"9,261","7,638,363","384,538,105",50.3
29,201404,부산광역시,전체(시 / 군 / 구),가로등,"75,555","14,149,440","1,596,967,986",112.9
30,201404,부산광역시,전체(시 / 군 / 구),심 야,"26,101","41,837,647","2,324,995,151",55.6
31,201405,부산광역시,전체(시 / 군 / 구),주택용,"928,297","346,918,001","40,523,713,827",116.8
32,201405,부산광역시,전체(시 / 군 / 구),일반용,"180,738","441,001,128","51,530,399,413",116.8
33,201405,부산광역시,전체(시 / 군 / 구),교육용,"1,137","29,702,911","3,234,291,637",108.9
34,201405,부산광역시,전체(시 / 군 / 구),산업용,"24,133","685,856,883","70,290,000,477",102.5
35,201405,부산광역시,전체(시 / 군 / 구),농사용,"9,331","6,815,042","347,356,094",51.0
36,201405,부산광역시,전체(시 / 군 / 구),가로등,"75,696","13,386,974","1,543,343,075",115.3
37,201405,부산광역시,전체(시 / 군 / 구),심 야,"25,980","28,457,452","1,593,602,889",56.0
38,201406,부산광역시,전체(시 / 군 / 구),주택용,"928,722","348,783,822","41,246,176,142",118.3
39,201406,부산광역시,전체(시 / 군 / 구),일반용,"180,990","463,685,562","61,817,159,997",133.3
40,201406,부산광역시,전체(시 / 군 / 구),교육용,"1,137","30,872,556","3,772,975,292",122.2
41,201406,부산광역시,전체(시 / 군 / 구),산업용,"24,162","688,906,542","84,128,741,718",122.1
42,201406,부산광역시,전체(시 / 군 / 구),농사용,"9,361","6,855,506","345,480,770",50.4
43,201406,부산광역시,전체(시 / 군 / 구),가로등,"75,925","12,656,548","1,502,573,552",118.7
44,201406,부산광역시,전체(시 / 군 / 구),심 야,"25,862","21,065,098","1,235,191,597",58.6
45,합계,합계,합계,합계,"7,459,804","10,025,457,289","1,192,716,863,554",119

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_11000\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201401  부산광역시  일반용  180,319   561,325,666
11  201402  부산광역시  일반용  180,353   533,907,219
18  201403  부산광역시  일반용  180,414   485,624,956
25  201404  부산광역시  일반용  180,557   465,683,769
32  201405  부산광역시  일반용  180,738   441,001,128
39  201406  부산광역시  일반용  180,990   463,685,562

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201401  부산광역시   강서구  일반용   7,285   23,223,877
181  201402  부산광역시   강서구  일반용   7,274   21,906,453
309  201403  부산광역시   강서구  일반용   7,282   20,155,634
437  201404  부산광역시   강서구  일반용   7,309   18,828,429
565  201405  부산광역시   강서구  일반용   7,358   17,646,863
..      ...    ...   ...  ...      ...          ...
301  201402  부산광역시  해운대구  일반용  13,444   70,561,377
429  201403  부산광역시  해운대구  일반용  13,458   66,121,404
557  201404  부산광역시  해운대구  일반용  13,481   62,621,954
685  201405  부산광역시  해운대구  일반용  13,532   62,320,195
813  201406  부산광역시  해운대구  일반용  13,571   66,651,411

[96 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'부산광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강서구',
 '금정구',
 '기장군',
 '남구',
 '동구',
 '동래구',
 '부산진구',
 '북구',
 '사상구',
 '사하구',
 '서구',
 '수영구',
 '연제구',
 '영도구',
 '중구',
 '해운대구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
55   201401  부산광역시   강서구   합계  41,566   280,256,336
183  201402  부산광역시   강서구   합계  41,720   266,152,112
311  201403  부산광역시   강서구   합계  41,994   283,205,987
439  201404  부산광역시   강서구   합계  42,131   277,089,479
567  201405  부산광역시   강서구   합계  42,359   266,804,025
..      ...    ...   ...  ...      ...           ...
303  201402  부산광역시  해운대구   합계  91,481   156,648,769
431  201403  부산광역시  해운대구   합계  91,642   146,593,955
559  201404  부산광역시  해운대구   합계  91,738   143,588,339
687  201405  부산광역시  해운대구   합계  91,760   139,301,177
815  201406  부산광역시  해운대구   합계  91,695   143,372,897

[96 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[280256336, 266152112, 283205987, 277089479, 266804025, 265590024]
[101479934, 98633493, 90194673, 87489125, 80275649, 81749458]
[86742486, 86665650, 90819961, 97093156, 77526641, 69162236]
[121853266, 117231523, 113959433, 112997967, 106845306, 106834111]
[49986930, 48283590, 43770220, 41893895, 38649223, 39141763]
[87254394, 85115140, 76040958, 73839019, 68331378, 70283723]
[154641750, 147906902, 134646745, 131260739, 123336229, 127872467]
[82099656, 80323457, 70512501, 70155300, 64911949, 67481546]
[175337579, 167526355, 159794442, 158685594, 142911101, 148050514]
[252206816, 234975904, 237996246, 250856859, 237390721, 240593644]
[52237744, 47840420, 45198743, 43686568, 41988336, 42984812]
[52950679, 51876938, 45788163, 44801272, 41058453, 42250835]
[71469926, 69365165, 62511705, 60817137, 56709115, 58868762]
[46127571, 44862538, 40461556, 38785484, 35661438, 36482015]
[39539230, 38052417, 34358508, 32797576, 30437650, 32106827]
[163157289, 156648769, 146593955, 143588339, 139301177, 143372897]
부산광역시 지역별 합계 :  [1639097963, 539822332, 508010130, 679721606, 261725621, 460864612, 819664832, 435484409, 952305585, 1454020190, 273936623, 278726340, 379741810, 242380602, 207292208, 892662426]
부산광역시 고객호수 평균:  [7006, 17301, 7566, 17152, 8942, 15883, 23796, 12524, 13169, 18666, 10369, 11693, 11998, 9821, 6053, 15271]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0           201401  부산광역시   강서구   합계  41,566   280,256,336
1           201402  부산광역시   강서구   합계  41,720   266,152,112
2           201403  부산광역시   강서구   합계  41,994   283,205,987
3           201404  부산광역시   강서구   합계  42,131   277,089,479
4           201405  부산광역시   강서구   합계  42,359   266,804,025
..             ...    ...   ...  ...      ...           ...
107  201401-201406  부산광역시   수영구   합계    11693     278726340
108  201401-201406  부산광역시   연제구   합계    11998     379741810
109  201401-201406  부산광역시   영도구   합계     9821     242380602
110  201401-201406  부산광역시    중구   합계     6053     207292208
111  201401-201406  부산광역시  해운대구   합계    15271     892662426

[112 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201401-201406']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201401-201406  부산광역시   강서구   합계    7006  1639097963
97   201401-201406  부산광역시   금정구   합계   17301   539822332
98   201401-201406  부산광역시   기장군   합계    7566   508010130
99   201401-201406  부산광역시    남구   합계   17152   679721606
100  201401-201406  부산광역시    동구   합계    8942   261725621
101  201401-201406  부산광역시   동래구   합계   15883   460864612
102  201401-201406  부산광역시  부산진구   합계   23796   819664832
103  201401-201406  부산광역시    북구   합계   12524   435484409
104  201401-201406  부산광역시   사상구   합계   13169   952305585
105  201401-201406  부산광역시   사하구   합계   18666  1454020190
106  201401-201406  부산광역시    서구   합계   10369   273936623
107  201401-201406  부산광역시   수영구   합계   11693   278726340
108  201401-201406  부산광역시   연제구   합계   11998   379741810
109  201401-201406  부산광역시   영도구   합계    9821   242380602
110  201401-201406  부산광역시    중구   합계    6053   207292208
111  201401-201406  부산광역시  해운대구   합계   15271   892662426

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구   시군구 계약구분  고객호수(호)     사용량(kWh)
53   201401  부산광역시   강서구  일반용   7,285   23,223,877
181  201402  부산광역시   강서구  일반용   7,274   21,906,453
309  201403  부산광역시   강서구  일반용   7,282   20,155,634
437  201404  부산광역시   강서구  일반용   7,309   18,828,429
565  201405  부산광역시   강서구  일반용   7,358   17,646,863
..      ...    ...   ...  ...      ...          ...
301  201402  부산광역시  해운대구  일반용  13,444   70,561,377
429  201403  부산광역시  해운대구  일반용  13,458   66,121,404
557  201404  부산광역시  해운대구  일반용  13,481   62,621,954
685  201405  부산광역시  해운대구  일반용  13,532   62,320,195
813  201406  부산광역시  해운대구  일반용  13,571   66,651,411

[96 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[23223877, 21906453, 20155634, 18828429, 17646863, 18521876]
[35213560, 33582521, 29980117, 28323949, 26409127, 28404364]
[23818861, 23073780, 23490931, 25556683, 24149684, 15723806]
[31624513, 30350324, 28009221, 27412237, 25021809, 26987758]
[26887714, 25602999, 23582464, 22045760, 20761867, 21940558]
[39100514, 37254371, 33461336, 31569787, 29969436, 32492790]
[73295342, 69614764, 62795654, 60104076, 57946767, 62859750]
[32058052, 30649695, 26787107, 25532173, 23896938, 26047870]
[39746568, 37672204, 33456747, 31868471, 29786785, 32180950]
[37715772, 35755678, 31303315, 30382370, 28061125, 30129864]
[18938201, 17968503, 16516840, 15858723, 14924768, 15734573]
[26454289, 25234337, 22529573, 21384199, 19913557, 21291606]
[34938225, 33238113, 30123281, 28420167, 26711157, 29009789]
[12826056, 12512919, 10973323, 10718284, 9745783, 10097673]
[30291045, 28929181, 26338009, 25056507, 23735267, 25610924]
[75193077, 70561377, 66121404, 62621954, 62320195, 66651411]
부산광역시 지역별 일반용 합계 :  [120283132, 181913638, 135813745, 169405862, 140821362, 203848234, 386616353, 164971835, 204711725, 193348124, 99941608, 136807561, 182440732, 66874038, 159960933, 403469418]
부산광역시 고객호수 평균:  [7308, 15050, 6893, 11821, 7591, 15479, 22594, 10478, 13361, 14190, 6663, 9982, 10683, 5918, 9055, 13489]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_11000\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구   시군구 계약구분 고객호수(호)     사용량(kWh)
0           201401  부산광역시   강서구  일반용  7,285   23,223,877
1           201402  부산광역시   강서구  일반용  7,274   21,906,453
2           201403  부산광역시   강서구  일반용  7,282   20,155,634
3           201404  부산광역시   강서구  일반용  7,309   18,828,429
4           201405  부산광역시   강서구  일반용  7,358   17,646,863
..             ...    ...   ...  ...     ...          ...
107  201401-201406  부산광역시   수영구  일반용    9982    136807561
108  201401-201406  부산광역시   연제구  일반용   10683    182440732
109  201401-201406  부산광역시   영도구  일반용    5918     66874038
110  201401-201406  부산광역시    중구  일반용    9055    159960933
111  201401-201406  부산광역시  해운대구  일반용   13489    403469418

[112 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201401-201406']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)   사용량(kWh)
96   201401-201406  부산광역시   강서구  일반용    7308  120283132
97   201401-201406  부산광역시   금정구  일반용   15050  181913638
98   201401-201406  부산광역시   기장군  일반용    6893  135813745
99   201401-201406  부산광역시    남구  일반용   11821  169405862
100  201401-201406  부산광역시    동구  일반용    7591  140821362
101  201401-201406  부산광역시   동래구  일반용   15479  203848234
102  201401-201406  부산광역시  부산진구  일반용   22594  386616353
103  201401-201406  부산광역시    북구  일반용   10478  164971835
104  201401-201406  부산광역시   사상구  일반용   13361  204711725
105  201401-201406  부산광역시   사하구  일반용   14190  193348124
106  201401-201406  부산광역시    서구  일반용    6663   99941608
107  201401-201406  부산광역시   수영구  일반용    9982  136807561
108  201401-201406  부산광역시   연제구  일반용   10683  182440732
109  201401-201406  부산광역시   영도구  일반용    5918   66874038
110  201401-201406  부산광역시    중구  일반용    9055  159960933
111  201401-201406  부산광역시  해운대구  일반용   13489  403469418

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
96   201401-201406  부산광역시   강서구  일반용    7308   120283132
96   201401-201406  부산광역시   강서구   합계    7006  1639097963
97   201401-201406  부산광역시   금정구   합계   17301   539822332
97   201401-201406  부산광역시   금정구  일반용   15050   181913638
98   201401-201406  부산광역시   기장군   합계    7566   508010130
98   201401-201406  부산광역시   기장군  일반용    6893   135813745
99   201401-201406  부산광역시    남구  일반용   11821   169405862
99   201401-201406  부산광역시    남구   합계   17152   679721606
100  201401-201406  부산광역시    동구  일반용    7591   140821362
100  201401-201406  부산광역시    동구   합계    8942   261725621
101  201401-201406  부산광역시   동래구  일반용   15479   203848234
101  201401-201406  부산광역시   동래구   합계   15883   460864612
102  201401-201406  부산광역시  부산진구  일반용   22594   386616353
102  201401-201406  부산광역시  부산진구   합계   23796   819664832
103  201401-201406  부산광역시    북구  일반용   10478   164971835
103  201401-201406  부산광역시    북구   합계   12524   435484409
104  201401-201406  부산광역시   사상구   합계   13169   952305585
104  201401-201406  부산광역시   사상구  일반용   13361   204711725
105  201401-201406  부산광역시   사하구   합계   18666  1454020190
105  201401-201406  부산광역시   사하구  일반용   14190   193348124
106  201401-201406  부산광역시    서구  일반용    6663    99941608
106  201401-201406  부산광역시    서구   합계   10369   273936623
107  201401-201406  부산광역시   수영구   합계   11693   278726340
107  201401-201406  부산광역시   수영구  일반용    9982   136807561
108  201401-201406  부산광역시   연제구   합계   11998   379741810
108  201401-201406  부산광역시   연제구  일반용   10683   182440732
109  201401-201406  부산광역시   영도구   합계    9821   242380602
109  201401-201406  부산광역시   영도구  일반용    5918    66874038
110  201401-201406  부산광역시    중구   합계    6053   207292208
110  201401-201406  부산광역시    중구  일반용    9055   159960933
111  201401-201406  부산광역시  해운대구  일반용   13489   403469418
111  201401-201406  부산광역시  해운대구   합계   15271   892662426

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[120283132,
 181913638,
 135813745,
 169405862,
 140821362,
 203848234,
 386616353,
 164971835,
 204711725,
 193348124,
 99941608,
 136807561,
 182440732,
 66874038,
 159960933,
 403469418]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1639097963,
 539822332,
 508010130,
 679721606,
 261725621,
 460864612,
 819664832,
 435484409,
 952305585,
 1454020190,
 273936623,
 278726340,
 379741810,
 242380602,
 207292208,
 892662426]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[7.34, 33.7, 26.73, 24.92, 53.8, 44.23, 47.17, 37.88, 21.5, 13.3, 36.48, 49.08, 48.04, 27.59, 77.17, 45.2]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0     7
1    34
2    27
3    25
4    54
5    44
6    47
7    38
8    22
9    13
10   36
11   49
12   48
13   28
14   77
15   45
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강서구  일반용   7
1    금정구  일반용  34
2    기장군  일반용  27
3     남구  일반용  25
4     동구  일반용  54
5    동래구  일반용  44
6   부산진구  일반용  47
7     북구  일반용  38
8    사상구  일반용  22
9    사하구  일반용  13
10    서구  일반용  36
11   수영구  일반용  49
12   연제구  일반용  48
13   영도구  일반용  28
14    중구  일반용  77
15  해운대구  일반용  45

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201401-201406  부산광역시   강서구  일반용    7308   120283132   7
1   201401-201406  부산광역시   강서구   합계    7006  1639097963 NaN
3   201401-201406  부산광역시   금정구  일반용   15050   181913638  34
2   201401-201406  부산광역시   금정구   합계   17301   539822332 NaN
5   201401-201406  부산광역시   기장군  일반용    6893   135813745  27
4   201401-201406  부산광역시   기장군   합계    7566   508010130 NaN
6   201401-201406  부산광역시    남구  일반용   11821   169405862  25
7   201401-201406  부산광역시    남구   합계   17152   679721606 NaN
8   201401-201406  부산광역시    동구  일반용    7591   140821362  54
9   201401-201406  부산광역시    동구   합계    8942   261725621 NaN
10  201401-201406  부산광역시   동래구  일반용   15479   203848234  44
11  201401-201406  부산광역시   동래구   합계   15883   460864612 NaN
12  201401-201406  부산광역시  부산진구  일반용   22594   386616353  47
13  201401-201406  부산광역시  부산진구   합계   23796   819664832 NaN
14  201401-201406  부산광역시    북구  일반용   10478   164971835  38
15  201401-201406  부산광역시    북구   합계   12524   435484409 NaN
17  201401-201406  부산광역시   사상구  일반용   13361   204711725  22
16  201401-201406  부산광역시   사상구   합계   13169   952305585 NaN
19  201401-201406  부산광역시   사하구  일반용   14190   193348124  13
18  201401-201406  부산광역시   사하구   합계   18666  1454020190 NaN
20  201401-201406  부산광역시    서구  일반용    6663    99941608  36
21  201401-201406  부산광역시    서구   합계   10369   273936623 NaN
23  201401-201406  부산광역시   수영구  일반용    9982   136807561  49
22  201401-201406  부산광역시   수영구   합계   11693   278726340 NaN
25  201401-201406  부산광역시   연제구  일반용   10683   182440732  48
24  201401-201406  부산광역시   연제구   합계   11998   379741810 NaN
27  201401-201406  부산광역시   영도구  일반용    5918    66874038  28
26  201401-201406  부산광역시   영도구   합계    9821   242380602 NaN
29  201401-201406  부산광역시    중구  일반용    9055   159960933  77
28  201401-201406  부산광역시    중구   합계    6053   207292208 NaN
30  201401-201406  부산광역시  해운대구  일반용   13489   403469418  45
31  201401-201406  부산광역시  해운대구   합계   15271   892662426 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1401-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)