In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경기도_계약종별_전력사용량_월별_18상반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경기도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2018년 01 월 ~ 2018년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,경기도,전체(시 / 군 / 구),주택용,"2,884,195","1,587,348,586","183,677,390,430",115.7
4,201801,경기도,전체(시 / 군 / 구),일반용,"655,199","2,909,561,265","375,316,359,371",129.0
...,...,...,...,...,...,...,...,...
1531,201806,경기도,화성시,산업용,"19,434","1,213,094,617","137,897,165,454",113.7
1532,201806,경기도,화성시,심 야,"12,600","8,380,877","489,039,907",58.4
1533,201806,경기도,화성시,일반용,"42,052","169,287,997","21,820,569,772",128.9
1534,201806,경기도,화성시,주택용,"130,519","84,289,114","9,004,738,169",106.8
1535,201806,경기도,화성시,합계,"250,022","1,503,000,718","171,456,323,536",114.1

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,경기도,전체(시 / 군 / 구),주택용,"2,884,195","1,587,348,586","183,677,390,430",115.7
4,201801,경기도,전체(시 / 군 / 구),일반용,"655,199","2,909,561,265","375,316,359,371",129.0
5,201801,경기도,전체(시 / 군 / 구),교육용,"4,445","195,350,301","18,874,888,550",96.6
6,201801,경기도,전체(시 / 군 / 구),산업용,"125,306","5,867,652,691","688,391,065,601",117.3
...,...,...,...,...,...,...,...,...
1531,201806,경기도,화성시,산업용,"19,434","1,213,094,617","137,897,165,454",113.7
1532,201806,경기도,화성시,심 야,"12,600","8,380,877","489,039,907",58.4
1533,201806,경기도,화성시,일반용,"42,052","169,287,997","21,820,569,772",128.9
1534,201806,경기도,화성시,주택용,"130,519","84,289,114","9,004,738,169",106.8
1535,201806,경기도,화성시,합계,"250,022","1,503,000,718","171,456,323,536",114.1

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,경기도,전체(시 / 군 / 구),주택용,"2,884,195","1,587,348,586","183,677,390,430",115.7
4,201801,경기도,전체(시 / 군 / 구),일반용,"655,199","2,909,561,265","375,316,359,371",129.0
5,201801,경기도,전체(시 / 군 / 구),교육용,"4,445","195,350,301","18,874,888,550",96.6
6,201801,경기도,전체(시 / 군 / 구),산업용,"125,306","5,867,652,691","688,391,065,601",117.3
7,201801,경기도,전체(시 / 군 / 구),농사용,"215,270","270,805,975","12,832,831,947",47.4
...,...,...,...,...,...,...,...,...
1531,201806,경기도,화성시,산업용,"19,434","1,213,094,617","137,897,165,454",113.7
1532,201806,경기도,화성시,심 야,"12,600","8,380,877","489,039,907",58.4
1533,201806,경기도,화성시,일반용,"42,052","169,287,997","21,820,569,772",128.9
1534,201806,경기도,화성시,주택용,"130,519","84,289,114","9,004,738,169",106.8
1535,201806,경기도,화성시,합계,"250,022","1,503,000,718","171,456,323,536",114.1

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,경기도,전체(시 / 군 / 구),주택용,"2,884,195","1,587,348,586","183,677,390,430",115.7
4,201801,경기도,전체(시 / 군 / 구),일반용,"655,199","2,909,561,265","375,316,359,371",129.0
5,201801,경기도,전체(시 / 군 / 구),교육용,"4,445","195,350,301","18,874,888,550",96.6
6,201801,경기도,전체(시 / 군 / 구),산업용,"125,306","5,867,652,691","688,391,065,601",117.3
7,201801,경기도,전체(시 / 군 / 구),농사용,"215,270","270,805,975","12,832,831,947",47.4
8,201801,경기도,전체(시 / 군 / 구),가로등,"331,620","82,174,385","8,906,431,443",108.4
9,201801,경기도,전체(시 / 군 / 구),심 야,"150,209","503,070,105","37,974,757,155",75.5
10,201802,경기도,전체(시 / 군 / 구),주택용,"2,888,325","1,612,259,759","187,879,581,082",116.5
11,201802,경기도,전체(시 / 군 / 구),일반용,"656,959","2,936,728,765","377,795,196,106",128.6
12,201802,경기도,전체(시 / 군 / 구),교육용,"4,448","185,951,163","18,043,352,101",97.0
13,201802,경기도,전체(시 / 군 / 구),산업용,"125,623","5,551,902,779","648,408,483,865",116.8
14,201802,경기도,전체(시 / 군 / 구),농사용,"215,284","284,911,550","13,439,351,071",47.2
15,201802,경기도,전체(시 / 군 / 구),가로등,"341,744","78,449,478","8,822,782,546",112.5
16,201802,경기도,전체(시 / 군 / 구),심 야,"149,828","533,096,015","40,266,146,749",75.5
17,201803,경기도,전체(시 / 군 / 구),주택용,"2,891,399","1,375,481,427","143,637,835,567",104.4
18,201803,경기도,전체(시 / 군 / 구),일반용,"657,466","2,325,411,197","281,028,586,293",120.9
19,201803,경기도,전체(시 / 군 / 구),교육용,"4,465","149,276,533","15,434,892,165",103.4
20,201803,경기도,전체(시 / 군 / 구),산업용,"125,847","5,479,425,157","542,105,571,632",98.9
21,201803,경기도,전체(시 / 군 / 구),농사용,"281,429","212,785,680","10,300,520,663",48.4
22,201803,경기도,전체(시 / 군 / 구),가로등,"334,882","71,418,982","8,150,384,702",114.1
23,201803,경기도,전체(시 / 군 / 구),심 야,"149,427","379,707,409","25,488,827,117",67.1
24,201804,경기도,전체(시 / 군 / 구),주택용,"2,896,063","1,409,456,513","148,793,447,113",105.6
25,201804,경기도,전체(시 / 군 / 구),일반용,"659,313","2,130,803,066","243,548,561,029",114.3
26,201804,경기도,전체(시 / 군 / 구),교육용,"4,469","123,536,649","11,793,524,086",95.5
27,201804,경기도,전체(시 / 군 / 구),산업용,"126,254","5,378,550,162","518,648,676,082",96.4
28,201804,경기도,전체(시 / 군 / 구),농사용,"228,745","184,363,588","9,037,535,349",49.0
29,201804,경기도,전체(시 / 군 / 구),가로등,"335,926","70,549,533","8,281,509,619",117.4
30,201804,경기도,전체(시 / 군 / 구),심 야,"148,993","265,878,531","14,619,311,699",55.0
31,201805,경기도,전체(시 / 군 / 구),주택용,"2,901,186","1,321,112,346","134,425,114,260",101.8
32,201805,경기도,전체(시 / 군 / 구),일반용,"660,330","2,027,990,371","235,631,707,686",116.2
33,201805,경기도,전체(시 / 군 / 구),교육용,"4,464","99,602,819","9,640,792,295",96.8
34,201805,경기도,전체(시 / 군 / 구),산업용,"126,665","5,406,290,688","517,639,716,526",95.7
35,201805,경기도,전체(시 / 군 / 구),농사용,"217,932","175,555,215","8,372,805,223",47.7
36,201805,경기도,전체(시 / 군 / 구),가로등,"339,596","65,560,009","7,905,334,327",120.6
37,201805,경기도,전체(시 / 군 / 구),심 야,"148,437","174,671,833","9,797,473,264",56.1
38,201806,경기도,전체(시 / 군 / 구),주택용,"2,907,154","1,368,677,697","144,185,755,812",105.3
39,201806,경기도,전체(시 / 군 / 구),일반용,"662,125","2,208,162,479","291,111,079,041",131.8
40,201806,경기도,전체(시 / 군 / 구),교육용,"4,463","108,699,214","12,825,285,448",118.0
41,201806,경기도,전체(시 / 군 / 구),산업용,"126,919","5,443,599,809","630,144,405,592",115.8
42,201806,경기도,전체(시 / 군 / 구),농사용,"218,694","182,995,313","8,618,265,952",47.1
43,201806,경기도,전체(시 / 군 / 구),가로등,"344,267","62,714,805","7,783,064,978",124.1
44,201806,경기도,전체(시 / 군 / 구),심 야,"147,956","112,655,442","6,555,459,945",58.2
45,합계,합계,합계,합계,"26,403,321","60,914,195,284","6,626,134,061,482",108.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_14928\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)        사용량(kWh)
4   201801  경기도  일반용  655,199   2,909,561,265
11  201802  경기도  일반용  656,959   2,936,728,765
18  201803  경기도  일반용  657,466   2,325,411,197
25  201804  경기도  일반용  659,313   2,130,803,066
32  201805  경기도  일반용  660,330   2,027,990,371
39  201806  경기도  일반용  662,125   2,208,162,479

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201801  경기도  가평군  일반용   9,989    36,597,265
301   201802  경기도  가평군  일반용  10,014    36,898,942
549   201803  경기도  가평군  일반용  10,014    28,170,181
797   201804  경기도  가평군  일반용  10,046    23,966,986
1045  201805  경기도  가평군  일반용  10,091    21,807,974
...      ...  ...  ...  ...      ...           ...
541   201802  경기도  화성시  일반용  41,109   208,069,754
789   201803  경기도  화성시  일반용  41,228   176,270,488
1037  201804  경기도  화성시  일반용  41,477   163,841,210
1285  201805  경기도  화성시  일반용  41,730   158,775,791
1533  201806  경기도  화성시  일반용  42,052   169,287,997

[186 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경기도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['가평군',
 '고양시',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시',
 '성남시',
 '수원시',
 '시흥시',
 '안산시',
 '안성시',
 '안양시',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월   시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201801  경기도  가평군   합계   64,358      80,461,088
303   201802  경기도  가평군   합계   64,416      80,854,534
551   201803  경기도  가평군   합계   65,433      63,280,273
799   201804  경기도  가평군   합계   64,505      53,392,462
1047  201805  경기도  가평군   합계   64,644      46,430,750
...      ...  ...  ...  ...       ...             ...
543   201802  경기도  화성시   합계  244,633   1,615,696,323
791   201803  경기도  화성시   합계  251,504   1,548,201,309
1039  201804  경기도  화성시   합계  254,020   1,502,795,067
1287  201805  경기도  화성시   합계  248,750   1,492,871,165
1535  201806  경기도  화성시   합계  250,022   1,503,000,718

[186 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[80461088, 80854534, 63280273, 53392462, 46430750, 45058405]
[480671813, 483770076, 380422330, 355776413, 325746409, 340928822]
[36769824, 36277031, 31206183, 29372195, 28285743, 30224413]
[114924673, 112761880, 91772039, 86944866, 81536181, 88088225]
[273522068, 280500650, 224115213, 212607585, 192225953, 195192054]
[78041121, 79551269, 63782164, 60744712, 57824782, 62351612]
[147437947, 145500872, 122291114, 116727357, 110927596, 117025460]
[379738056, 396131067, 316363924, 307797945, 278040165, 283193133]
[323712809, 333012277, 267670266, 252134087, 229619908, 235132244]
[68730779, 68552409, 58334955, 53988200, 50753045, 51987496]
[406247012, 406656169, 341375103, 330930815, 313953578, 328752789]
[482996171, 461979960, 404205881, 385488592, 384102278, 415157106]
[531051348, 523303872, 444294961, 427171239, 409419010, 440351796]
[430958129, 420575841, 366912246, 354704415, 334719806, 339327424]
[790597234, 738484223, 696128821, 670212232, 657470593, 671907264]
[300161470, 295952412, 257584240, 240727118, 228406285, 232179108]
[253578194, 249830238, 210374655, 199084233, 189522808, 200837050]
[227200717, 228241971, 181907650, 176539601, 158171709, 157954100]
[123456133, 126819684, 95703971, 79252758, 66275486, 62002626]
[152184229, 153481130, 129804373, 116582144, 105796418, 105264886]
[61763603, 63601996, 51281770, 45813583, 40742649, 40272490]
[123531642, 122340878, 103975787, 95995527, 96086392, 101148283]
[900907225, 871405675, 805920378, 773339821, 761418328, 774425529]
[73090558, 73459268, 60711365, 57887208, 53936563, 56368069]
[170731130, 170551849, 136243725, 128739414, 120408507, 128542756]
[586029112, 558136657, 561127873, 545409456, 558838416, 564435978]
[831356042, 801829420, 778248179, 743913971, 751930736, 758460400]
[888240066, 846646424, 845400834, 815046902, 827168510, 840858766]
[289671788, 300813980, 239213550, 232438910, 209751234, 203192709]
[136839077, 136579474, 115651253, 111579214, 108402278, 113883048]
[1671362250, 1615696323, 1548201309, 1502795067, 1492871165, 1503000718]
경기도 지역별 합계 :  [369477512, 2367315863, 192135389, 576027864, 1378163523, 402295660, 759910346, 1961264290, 1641281591, 352346884, 2127915466, 2533929988, 2775592226, 2247197861, 4224800367, 1555010633, 1303227178, 1130015748, 553510658, 763113180, 303476091, 643078509, 4887416956, 375453031, 855217381, 3373977492, 4665738748, 5063361502, 1475082171, 722934344, 9333926832]
경기도 고객호수 평균:  [10781, 39108, 2554, 13224, 30097, 8901, 10354, 19824, 30967, 6851, 47259, 44573, 61157, 25837, 48580, 21010, 23153, 14041, 18879, 14950, 7443, 11524, 39964, 6008, 19507, 21439, 27041, 38761, 19363, 8805, 41456]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201801  경기도  가평군   합계  64,358   80,461,088
1           201802  경기도  가평군   합계  64,416   80,854,534
2           201803  경기도  가평군   합계  65,433   63,280,273
3           201804  경기도  가평군   합계  64,505   53,392,462
4           201805  경기도  가평군   합계  64,644   46,430,750
..             ...  ...  ...  ...      ...          ...
212  201801-201806  경기도  파주시   합계    27041   4665738748
213  201801-201806  경기도  평택시   합계    38761   5063361502
214  201801-201806  경기도  포천시   합계    19363   1475082171
215  201801-201806  경기도  하남시   합계     8805    722934344
216  201801-201806  경기도  화성시   합계    41456   9333926832

[217 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201801-201806']
Hap

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201801-201806  경기도   가평군   합계   10781   369477512
187  201801-201806  경기도   고양시   합계   39108  2367315863
188  201801-201806  경기도   과천시   합계    2554   192135389
189  201801-201806  경기도   광명시   합계   13224   576027864
190  201801-201806  경기도   광주시   합계   30097  1378163523
191  201801-201806  경기도   구리시   합계    8901   402295660
192  201801-201806  경기도   군포시   합계   10354   759910346
193  201801-201806  경기도   김포시   합계   19824  1961264290
194  201801-201806  경기도  남양주시   합계   30967  1641281591
195  201801-201806  경기도  동두천시   합계    6851   352346884
196  201801-201806  경기도   부천시   합계   47259  2127915466
197  201801-201806  경기도   성남시   합계   44573  2533929988
198  201801-201806  경기도   수원시   합계   61157  2775592226
199  201801-201806  경기도   시흥시   합계   25837  2247197861
200  201801-201806  경기도   안산시   합계   48580  4224800367
201  201801-201806  경기도   안성시   합계   21010  1555010633
202  201801-201806  경기도   안양시   합계   23153  1303227178
203  201801-201806  경기도   양주시   합계   14041  1130015748
204  201801-201806  경기도   양평군   합계   18879   553510658
205  201801-201806  경기도   여주시   합계   14950   763113180
206  201801-201806  경기도   연천군   합계    7443   303476091
207  201801-201806  경기도   오산시   합계   11524   643078509
208  201801-201806  경기도   용인시   합계   39964  4887416956
209  201801-201806  경기도   의왕시   합계    6008   375453031
210  201801-201806  경기도  의정부시   합계   19507   855217381
211  201801-201806  경기도   이천시   합계   21439  3373977492
212  201801-201806  경기도   파주시   합계   27041  4665738748
213  201801-201806  경기도   평택시   합계   38761  5063361502
214  201801-201806  경기도   포천시   합계   19363  1475082171
215  201801-201806  경기도   하남시   합계    8805   722934344
216  201801-201806  경기도   화성시   합계   41456  9333926832

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201801  경기도  가평군  일반용   9,989    36,597,265
301   201802  경기도  가평군  일반용  10,014    36,898,942
549   201803  경기도  가평군  일반용  10,014    28,170,181
797   201804  경기도  가평군  일반용  10,046    23,966,986
1045  201805  경기도  가평군  일반용  10,091    21,807,974
...      ...  ...  ...  ...      ...           ...
541   201802  경기도  화성시  일반용  41,109   208,069,754
789   201803  경기도  화성시  일반용  41,228   176,270,488
1037  201804  경기도  화성시  일반용  41,477   163,841,210
1285  201805  경기도  화성시  일반용  41,730   158,775,791
1533  201806  경기도  화성시  일반용  42,052   169,287,997

[186 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[36597265, 36898942, 28170181, 23966986, 21807974, 22687345]
[211712390, 212531082, 160688811, 147312363, 139147524, 152725159]
[23143572, 22835817, 19561674, 17849967, 17303313, 18355601]
[46987254, 46794154, 32989760, 30070072, 28524965, 32042120]
[73555598, 76039442, 59299440, 54783820, 51155386, 54397927]
[38971839, 39887535, 30365271, 27892913, 26648484, 30339162]
[43704506, 44590596, 35627347, 32569532, 30766513, 33884071]
[85588668, 88081520, 67189174, 60603681, 56378539, 60462933]
[111902410, 117667246, 89230164, 80614906, 74074126, 80020999]
[24441357, 25387352, 19497519, 17321962, 15864443, 17794053]
[133044641, 135815452, 105673884, 97518267, 92279771, 102234349]
[254199256, 242425760, 208630925, 194763850, 197497112, 217747680]
[277201275, 273034383, 226643552, 210176395, 207616598, 227259694]
[85355250, 86834397, 65526378, 59593305, 54404379, 58310148]
[124973127, 129137358, 99692310, 90142074, 83429692, 90311806]
[51089031, 52160667, 41739344, 37759747, 35106949, 37569872]
[120521861, 119444915, 96270987, 88546812, 85759031, 94631995]
[52408566, 52889585, 35607942, 32319541, 29069767, 31165112]
[33702541, 34781246, 26218858, 22637380, 20111754, 20697866]
[33762327, 34534736, 28124149, 25298328, 23675140, 26125158]
[16449721, 17052075, 12272404, 10902600, 9541152, 10314654]
[39190476, 40789803, 30877999, 28406241, 26357795, 28759764]
[238465411, 235975842, 191254055, 175863016, 170300685, 184434849]
[33233750, 32814976, 27256935, 25096123, 24071688, 25911753]
[79452663, 80366660, 60430117, 54734818, 51231455, 57558898]
[72674335, 72658550, 56717110, 50377294, 46895321, 51497592]
[110237191, 115368098, 91633305, 83667431, 78545372, 85117247]
[145125083, 152345112, 118460171, 110547433, 101847164, 111942700]
[54510896, 56771499, 43047384, 38303417, 34338213, 36510300]
[52180017, 52744211, 40443559, 37321582, 35464275, 38063675]
[205178988, 208069754, 176270488, 163841210, 158775791, 169287997]
경기도 지역별 일반용 합계 :  [170128693, 1024117329, 119049944, 217408325, 369231613, 194105204, 221142565, 418304515, 553509851, 120306686, 666566364, 1315264583, 1421931897, 410023857, 617686367, 255425610, 605175601, 233460513, 158149645, 171519838, 76532606, 194382078, 1196293858, 168385225, 383774611, 350820202, 564568644, 740267663, 263481709, 256217319, 1081424228]
경기도 고객호수 평균:  [10049, 40683, 2353, 11242, 25584, 10449, 9024, 21291, 35859, 6159, 36117, 33662, 53246, 23371, 28999, 14829, 24039, 13798, 12448, 9793, 4970, 11036, 39404, 5823, 21557, 16375, 26807, 36769, 17698, 13709, 41409]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14928\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201801  경기도  가평군  일반용   9,989   36,597,265
1           201802  경기도  가평군  일반용  10,014   36,898,942
2           201803  경기도  가평군  일반용  10,014   28,170,181
3           201804  경기도  가평군  일반용  10,046   23,966,986
4           201805  경기도  가평군  일반용  10,091   21,807,974
..             ...  ...  ...  ...      ...          ...
212  201801-201806  경기도  파주시  일반용    26807    564568644
213  201801-201806  경기도  평택시  일반용    36769    740267663
214  201801-201806  경기도  포천시  일반용    17698    263481709
215  201801-201806  경기도  하남시  일반용    13709    256217319
216  201801-201806  경기도  화성시  일반용    41409   1081424228

[217 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201801-201806']
GyeonGiHap2

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201801-201806  경기도   가평군  일반용   10049   170128693
187  201801-201806  경기도   고양시  일반용   40683  1024117329
188  201801-201806  경기도   과천시  일반용    2353   119049944
189  201801-201806  경기도   광명시  일반용   11242   217408325
190  201801-201806  경기도   광주시  일반용   25584   369231613
191  201801-201806  경기도   구리시  일반용   10449   194105204
192  201801-201806  경기도   군포시  일반용    9024   221142565
193  201801-201806  경기도   김포시  일반용   21291   418304515
194  201801-201806  경기도  남양주시  일반용   35859   553509851
195  201801-201806  경기도  동두천시  일반용    6159   120306686
196  201801-201806  경기도   부천시  일반용   36117   666566364
197  201801-201806  경기도   성남시  일반용   33662  1315264583
198  201801-201806  경기도   수원시  일반용   53246  1421931897
199  201801-201806  경기도   시흥시  일반용   23371   410023857
200  201801-201806  경기도   안산시  일반용   28999   617686367
201  201801-201806  경기도   안성시  일반용   14829   255425610
202  201801-201806  경기도   안양시  일반용   24039   605175601
203  201801-201806  경기도   양주시  일반용   13798   233460513
204  201801-201806  경기도   양평군  일반용   12448   158149645
205  201801-201806  경기도   여주시  일반용    9793   171519838
206  201801-201806  경기도   연천군  일반용    4970    76532606
207  201801-201806  경기도   오산시  일반용   11036   194382078
208  201801-201806  경기도   용인시  일반용   39404  1196293858
209  201801-201806  경기도   의왕시  일반용    5823   168385225
210  201801-201806  경기도  의정부시  일반용   21557   383774611
211  201801-201806  경기도   이천시  일반용   16375   350820202
212  201801-201806  경기도   파주시  일반용   26807   564568644
213  201801-201806  경기도   평택시  일반용   36769   740267663
214  201801-201806  경기도   포천시  일반용   17698   263481709
215  201801-201806  경기도   하남시  일반용   13709   256217319
216  201801-201806  경기도   화성시  일반용   41409  1081424228

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
186  201801-201806  경기도  가평군  일반용   10049   170128693
186  201801-201806  경기도  가평군   합계   10781   369477512
187  201801-201806  경기도  고양시  일반용   40683  1024117329
187  201801-201806  경기도  고양시   합계   39108  2367315863
188  201801-201806  경기도  과천시  일반용    2353   119049944
..             ...  ...  ...  ...     ...         ...
214  201801-201806  경기도  포천시  일반용   17698   263481709
215  201801-201806  경기도  하남시   합계    8805   722934344
215  201801-201806  경기도  하남시  일반용   13709   256217319
216  201801-201806  경기도  화성시  일반용   41409  1081424228
216  201801-201806  경기도  화성시   합계   41456  9333926832

[62 rows x 6 columns]

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[170128693,
 1024117329,
 119049944,
 217408325,
 369231613,
 194105204,
 221142565,
 418304515,
 553509851,
 120306686,
 666566364,
 1315264583,
 1421931897,
 410023857,
 617686367,
 255425610,
 605175601,
 233460513,
 158149645,
 171519838,
 76532606,
 194382078,
 1196293858,
 168385225,
 383774611,
 350820202,
 564568644,
 740267663,
 263481709,
 256217319,
 1081424228]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[369477512,
 2367315863,
 192135389,
 576027864,
 1378163523,
 402295660,
 759910346,
 1961264290,
 1641281591,
 352346884,
 2127915466,
 2533929988,
 2775592226,
 2247197861,
 4224800367,
 1555010633,
 1303227178,
 1130015748,
 553510658,
 763113180,
 303476091,
 643078509,
 4887416956,
 375453031,
 855217381,
 3373977492,
 4665738748,
 5063361502,
 1475082171,
 722934344,
 9333926832]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[46.05, 43.26, 61.96, 37.74, 26.79, 48.25, 29.1, 21.33, 33.72, 34.14, 31.32, 51.91, 51.23, 18.25, 14.62, 16.43, 46.44, 20.66, 28.57, 22.48, 25.22, 30.23, 24.48, 44.85, 44.87, 10.4, 12.1, 14.62, 17.86, 35.44, 11.59]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    46
1    43
2    62
3    38
4    27
5    48
6    29
7    21
8    34
9    34
10   31
11   52
12   51
13   18
14   15
15   16
16   46
17   21
18   29
19   22
20   25
21   30
22   24
23   45
24   45
25   10
26   12
27   15
28   18
29   35
30   12
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    가평군  일반용  46
1    고양시  일반용  43
2    과천시  일반용  62
3    광명시  일반용  38
4    광주시  일반용  27
5    구리시  일반용  48
6    군포시  일반용  29
7    김포시  일반용  21
8   남양주시  일반용  34
9   동두천시  일반용  34
10   부천시  일반용  31
11   성남시  일반용  52
12   수원시  일반용  51
13   시흥시  일반용  18
14   안산시  일반용  15
15   안성시  일반용  16
16   안양시  일반용  46
17   양주시  일반용  21
18   양평군  일반용  29
19   여주시  일반용  22
20   연천군  일반용  25
21   오산시  일반용  30
22   용인시  일반용  24
23   의왕시  일반용  45
24  의정부시  일반용  45
25   이천시  일반용  10
26   파주시  일반용  12
27   평택시  일반용  15
28   포천시  일반용  18
29   하남시  일반용  35
30   화성시  일반용  12

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201801-201806  경기도  가평군  일반용   10049   170128693  46
1   201801-201806  경기도  가평군   합계   10781   369477512 NaN
2   201801-201806  경기도  고양시  일반용   40683  1024117329  43
3   201801-201806  경기도  고양시   합계   39108  2367315863 NaN
4   201801-201806  경기도  과천시  일반용    2353   119049944  62
..            ...  ...  ...  ...     ...         ...  ..
56  201801-201806  경기도  포천시   합계   19363  1475082171 NaN
59  201801-201806  경기도  하남시  일반용   13709   256217319  35
58  201801-201806  경기도  하남시   합계    8805   722934344 NaN
60  201801-201806  경기도  화성시  일반용   41409  1081424228  12
61  201801-201806  경기도  화성시   합계   41456  9333926832 NaN

[62 rows x 7 columns]

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1801-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)