In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경기도_계약종별_전력사용량_월별_17상반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경기도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2017년 01 월 ~ 2017년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201701,경기도,전체(시 / 군 / 구),주택용,"2,797,971","1,474,742,446","168,577,107,215",114.3
4,201701,경기도,전체(시 / 군 / 구),일반용,"642,930","2,555,150,983","335,846,786,813",131.4
...,...,...,...,...,...,...,...,...
1531,201706,경기도,화성시,산업용,"18,310","1,155,938,912","134,022,711,938",115.9
1532,201706,경기도,화성시,심 야,"12,850","8,398,571","513,678,061",61.2
1533,201706,경기도,화성시,일반용,"39,150","143,258,296","19,013,051,813",132.7
1534,201706,경기도,화성시,주택용,"121,384","71,522,924","7,625,131,759",106.6
1535,201706,경기도,화성시,합계,"234,064","1,405,703,367","163,301,171,467",116.2

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201701,경기도,전체(시 / 군 / 구),주택용,"2,797,971","1,474,742,446","168,577,107,215",114.3
4,201701,경기도,전체(시 / 군 / 구),일반용,"642,930","2,555,150,983","335,846,786,813",131.4
5,201701,경기도,전체(시 / 군 / 구),교육용,"4,359","158,438,277","15,568,660,871",98.3
6,201701,경기도,전체(시 / 군 / 구),산업용,"121,270","5,320,020,341","620,945,307,019",116.7
...,...,...,...,...,...,...,...,...
1531,201706,경기도,화성시,산업용,"18,310","1,155,938,912","134,022,711,938",115.9
1532,201706,경기도,화성시,심 야,"12,850","8,398,571","513,678,061",61.2
1533,201706,경기도,화성시,일반용,"39,150","143,258,296","19,013,051,813",132.7
1534,201706,경기도,화성시,주택용,"121,384","71,522,924","7,625,131,759",106.6
1535,201706,경기도,화성시,합계,"234,064","1,405,703,367","163,301,171,467",116.2

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201701,경기도,전체(시 / 군 / 구),주택용,"2,797,971","1,474,742,446","168,577,107,215",114.3
4,201701,경기도,전체(시 / 군 / 구),일반용,"642,930","2,555,150,983","335,846,786,813",131.4
5,201701,경기도,전체(시 / 군 / 구),교육용,"4,359","158,438,277","15,568,660,871",98.3
6,201701,경기도,전체(시 / 군 / 구),산업용,"121,270","5,320,020,341","620,945,307,019",116.7
7,201701,경기도,전체(시 / 군 / 구),농사용,"207,480","238,627,619","11,428,634,252",47.9
...,...,...,...,...,...,...,...,...
1531,201706,경기도,화성시,산업용,"18,310","1,155,938,912","134,022,711,938",115.9
1532,201706,경기도,화성시,심 야,"12,850","8,398,571","513,678,061",61.2
1533,201706,경기도,화성시,일반용,"39,150","143,258,296","19,013,051,813",132.7
1534,201706,경기도,화성시,주택용,"121,384","71,522,924","7,625,131,759",106.6
1535,201706,경기도,화성시,합계,"234,064","1,405,703,367","163,301,171,467",116.2

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201701,경기도,전체(시 / 군 / 구),주택용,"2,797,971","1,474,742,446","168,577,107,215",114.3
4,201701,경기도,전체(시 / 군 / 구),일반용,"642,930","2,555,150,983","335,846,786,813",131.4
5,201701,경기도,전체(시 / 군 / 구),교육용,"4,359","158,438,277","15,568,660,871",98.3
6,201701,경기도,전체(시 / 군 / 구),산업용,"121,270","5,320,020,341","620,945,307,019",116.7
7,201701,경기도,전체(시 / 군 / 구),농사용,"207,480","238,627,619","11,428,634,252",47.9
8,201701,경기도,전체(시 / 군 / 구),가로등,"319,536","80,297,121","8,654,804,481",107.8
9,201701,경기도,전체(시 / 군 / 구),심 야,"154,390","470,274,433","35,529,675,679",75.6
10,201702,경기도,전체(시 / 군 / 구),주택용,"2,804,344","1,499,222,691","172,787,517,478",115.3
11,201702,경기도,전체(시 / 군 / 구),일반용,"642,664","2,608,752,749","341,495,300,434",130.9
12,201702,경기도,전체(시 / 군 / 구),교육용,"4,401","161,085,899","15,955,512,673",99.0
13,201702,경기도,전체(시 / 군 / 구),산업용,"121,661","5,104,867,247","610,103,340,059",119.5
14,201702,경기도,전체(시 / 군 / 구),농사용,"207,542","256,635,203","12,192,422,397",47.5
15,201702,경기도,전체(시 / 군 / 구),가로등,"320,150","76,231,544","8,572,147,853",112.4
16,201702,경기도,전체(시 / 군 / 구),심 야,"154,046","521,798,090","39,418,864,206",75.5
17,201703,경기도,전체(시 / 군 / 구),주택용,"2,811,285","1,299,030,612","132,568,644,913",102.1
18,201703,경기도,전체(시 / 군 / 구),일반용,"641,901","2,224,844,226","269,305,128,912",121.0
19,201703,경기도,전체(시 / 군 / 구),교육용,"4,411","148,212,405","14,378,564,026",97.0
20,201703,경기도,전체(시 / 군 / 구),산업용,"122,009","5,211,220,748","517,383,980,981",99.3
21,201703,경기도,전체(시 / 군 / 구),농사용,"272,634","205,445,946","9,938,720,117",48.4
22,201703,경기도,전체(시 / 군 / 구),가로등,"320,725","69,531,522","7,903,143,945",113.7
23,201703,경기도,전체(시 / 군 / 구),심 야,"153,733","392,734,811","26,280,347,676",66.9
24,201704,경기도,전체(시 / 군 / 구),주택용,"2,819,940","1,352,654,839","143,048,424,116",105.8
25,201704,경기도,전체(시 / 군 / 구),일반용,"642,690","2,026,772,983","230,801,339,026",113.9
26,201704,경기도,전체(시 / 군 / 구),교육용,"4,408","122,842,724","11,379,045,609",92.6
27,201704,경기도,전체(시 / 군 / 구),산업용,"122,430","5,039,624,694","484,965,684,511",96.2
28,201704,경기도,전체(시 / 군 / 구),농사용,"220,713","183,360,543","8,898,056,108",48.5
29,201704,경기도,전체(시 / 군 / 구),가로등,"321,448","68,915,021","8,065,979,679",117.0
30,201704,경기도,전체(시 / 군 / 구),심 야,"153,420","300,557,818","16,492,589,187",54.9
31,201705,경기도,전체(시 / 군 / 구),주택용,"2,827,233","1,255,883,318","127,538,231,371",101.6
32,201705,경기도,전체(시 / 군 / 구),일반용,"642,652","1,874,702,039","220,005,532,078",117.4
33,201705,경기도,전체(시 / 군 / 구),교육용,"4,410","90,880,715","8,715,837,542",95.9
34,201705,경기도,전체(시 / 군 / 구),산업용,"122,763","4,906,070,810","475,400,948,015",96.9
35,201705,경기도,전체(시 / 군 / 구),농사용,"210,587","172,227,008","8,067,349,938",46.8
36,201705,경기도,전체(시 / 군 / 구),가로등,"323,625","63,614,327","7,685,800,778",120.8
37,201705,경기도,전체(시 / 군 / 구),심 야,"152,951","168,340,474","9,443,361,984",56.1
38,201706,경기도,전체(시 / 군 / 구),주택용,"2,836,922","1,280,728,362","133,486,049,107",104.2
39,201706,경기도,전체(시 / 군 / 구),일반용,"643,982","2,048,073,544","275,650,222,474",134.6
40,201706,경기도,전체(시 / 군 / 구),교육용,"4,412","105,084,120","12,305,602,680",117.1
41,201706,경기도,전체(시 / 군 / 구),산업용,"123,101","5,090,599,396","603,022,586,531",118.5
42,201706,경기도,전체(시 / 군 / 구),농사용,"211,957","178,038,690","8,283,567,968",46.5
43,201706,경기도,전체(시 / 군 / 구),가로등,"323,804","61,193,934","7,594,513,290",124.1
44,201706,경기도,전체(시 / 군 / 구),심 야,"152,535","109,531,792","6,386,094,310",58.3
45,합계,합계,합계,합계,"25,695,425","56,576,862,064","6,182,071,428,302",109.3

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_13740\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)        사용량(kWh)
4   201701  경기도  일반용  642,930   2,555,150,983
11  201702  경기도  일반용  642,664   2,608,752,749
18  201703  경기도  일반용  641,901   2,224,844,226
25  201704  경기도  일반용  642,690   2,026,772,983
32  201705  경기도  일반용  642,652   1,874,702,039
39  201706  경기도  일반용  643,982   2,048,073,544

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201701  경기도  가평군  일반용   9,821    31,833,929
301   201702  경기도  가평군  일반용   9,799    32,844,747
549   201703  경기도  가평군  일반용   9,766    27,113,311
797   201704  경기도  가평군  일반용   9,775    23,704,846
1045  201705  경기도  가평군  일반용   9,814    21,226,525
...      ...  ...  ...  ...      ...           ...
541   201702  경기도  화성시  일반용  38,373   174,517,489
789   201703  경기도  화성시  일반용  38,506   157,832,463
1037  201704  경기도  화성시  일반용  38,695   143,733,043
1285  201705  경기도  화성시  일반용  38,873   132,542,602
1533  201706  경기도  화성시  일반용  39,150   143,258,296

[186 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경기도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['가평군',
 '고양시',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시',
 '성남시',
 '수원시',
 '시흥시',
 '안산시',
 '안성시',
 '안양시',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월   시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201701  경기도  가평군   합계   62,189      72,410,228
303   201702  경기도  가평군   합계   62,227      75,248,355
551   201703  경기도  가평군   합계   63,322      62,444,608
799   201704  경기도  가평군   합계   62,412      54,815,551
1047  201705  경기도  가평군   합계   62,554      45,225,271
...      ...  ...  ...  ...       ...             ...
543   201702  경기도  화성시   합계  228,831   1,475,108,049
791   201703  경기도  화성시   합계  235,736   1,470,561,868
1039  201704  경기도  화성시   합계  238,128   1,415,362,767
1287  201705  경기도  화성시   합계  232,525   1,360,448,419
1535  201706  경기도  화성시   합계  234,064   1,405,703,367

[186 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[72410228, 75248355, 62444608, 54815551, 45225271, 43236095]
[444125027, 456501331, 380297515, 355119414, 317743108, 332655998]
[36458039, 36352502, 32845285, 30781793, 29022814, 31242586]
[104166053, 107207526, 93485311, 87010477, 81224954, 86548568]
[248312784, 252188830, 217155022, 204086194, 173965079, 180561851]
[70180247, 71008063, 61173661, 58679520, 54511222, 58509217]
[135297731, 136469742, 122233839, 114807079, 105174277, 113765511]
[338734560, 344053748, 304499925, 291322192, 249199872, 265063804]
[289580164, 296779561, 256624010, 243420378, 213595001, 219131079]
[61885976, 63741996, 56259990, 54997819, 48255662, 50179707]
[380956401, 383033508, 341440954, 324658390, 299013139, 319767819]
[443125667, 434673799, 395754176, 375235517, 368381197, 402182433]
[491053148, 492214134, 438797940, 420737093, 396197235, 426737695]
[393620314, 394591663, 367879066, 346794789, 313958056, 330810519]
[728673661, 723378605, 704796136, 673222341, 648045051, 679547199]
[273219874, 276853514, 253439175, 236353622, 213818959, 219961385]
[236997661, 236837188, 209834593, 198205903, 186393293, 199068677]
[212834174, 210720445, 181936601, 174499853, 150299230, 154275251]
[109310348, 116030523, 92978255, 81072267, 63191556, 59350159]
[140382278, 144373788, 124993520, 116251090, 101200387, 98934573]
[57729808, 59794659, 50766436, 46605323, 40147222, 40314302]
[111806572, 113407320, 104715427, 99715512, 92879788, 97930807]
[841037068, 819500511, 787354678, 753590626, 725520446, 744284641]
[67215784, 67631151, 59647141, 56781806, 51012912, 54365661]
[154963359, 157069745, 134438417, 126032231, 116630651, 124261096]
[482995174, 465762387, 466742833, 448766085, 448040350, 459382019]
[760845293, 728885935, 736935797, 712651508, 699933789, 702394669]
[699689935, 695342574, 689569250, 656539764, 642303195, 672786491]
[268525471, 273783419, 241081650, 230465019, 195527682, 194422217]
[122039073, 120048852, 110337191, 106146699, 100858874, 105874442]
[1519379348, 1475108049, 1470561868, 1415362767, 1360448419, 1405703367]
경기도 지역별 합계 :  [353380108, 2286442393, 196703019, 559642889, 1276269760, 374061930, 727748179, 1792874101, 1519130193, 335321150, 2048870211, 2419352789, 2665737245, 2147654407, 4157662993, 1473646529, 1267337315, 1084565554, 521933108, 726135636, 295357750, 620455426, 4671287970, 356654455, 813395499, 2771688848, 4341646991, 4056231209, 1403805458, 665305131, 8646563818]
경기도 고객호수 평균:  [10432, 38037, 2501, 13445, 28492, 8660, 10148, 18365, 29587, 6696, 46380, 45561, 60270, 25297, 48212, 20405, 23832, 13589, 18130, 14250, 7313, 10993, 38458, 5894, 19334, 20629, 25862, 36951, 18786, 8425, 38814]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201701  경기도  가평군   합계  62,189   72,410,228
1           201702  경기도  가평군   합계  62,227   75,248,355
2           201703  경기도  가평군   합계  63,322   62,444,608
3           201704  경기도  가평군   합계  62,412   54,815,551
4           201705  경기도  가평군   합계  62,554   45,225,271
..             ...  ...  ...  ...      ...          ...
212  201701-201706  경기도  파주시   합계    25862   4341646991
213  201701-201706  경기도  평택시   합계    36951   4056231209
214  201701-201706  경기도  포천시   합계    18786   1403805458
215  201701-201706  경기도  하남시   합계     8425    665305131
216  201701-201706  경기도  화성시   합계    38814   8646563818

[217 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201701-201706']
Hap

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201701-201706  경기도   가평군   합계   10432   353380108
187  201701-201706  경기도   고양시   합계   38037  2286442393
188  201701-201706  경기도   과천시   합계    2501   196703019
189  201701-201706  경기도   광명시   합계   13445   559642889
190  201701-201706  경기도   광주시   합계   28492  1276269760
191  201701-201706  경기도   구리시   합계    8660   374061930
192  201701-201706  경기도   군포시   합계   10148   727748179
193  201701-201706  경기도   김포시   합계   18365  1792874101
194  201701-201706  경기도  남양주시   합계   29587  1519130193
195  201701-201706  경기도  동두천시   합계    6696   335321150
196  201701-201706  경기도   부천시   합계   46380  2048870211
197  201701-201706  경기도   성남시   합계   45561  2419352789
198  201701-201706  경기도   수원시   합계   60270  2665737245
199  201701-201706  경기도   시흥시   합계   25297  2147654407
200  201701-201706  경기도   안산시   합계   48212  4157662993
201  201701-201706  경기도   안성시   합계   20405  1473646529
202  201701-201706  경기도   안양시   합계   23832  1267337315
203  201701-201706  경기도   양주시   합계   13589  1084565554
204  201701-201706  경기도   양평군   합계   18130   521933108
205  201701-201706  경기도   여주시   합계   14250   726135636
206  201701-201706  경기도   연천군   합계    7313   295357750
207  201701-201706  경기도   오산시   합계   10993   620455426
208  201701-201706  경기도   용인시   합계   38458  4671287970
209  201701-201706  경기도   의왕시   합계    5894   356654455
210  201701-201706  경기도  의정부시   합계   19334   813395499
211  201701-201706  경기도   이천시   합계   20629  2771688848
212  201701-201706  경기도   파주시   합계   25862  4341646991
213  201701-201706  경기도   평택시   합계   36951  4056231209
214  201701-201706  경기도   포천시   합계   18786  1403805458
215  201701-201706  경기도   하남시   합계    8425   665305131
216  201701-201706  경기도   화성시   합계   38814  8646563818

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201701  경기도  가평군  일반용   9,821    31,833,929
301   201702  경기도  가평군  일반용   9,799    32,844,747
549   201703  경기도  가평군  일반용   9,766    27,113,311
797   201704  경기도  가평군  일반용   9,775    23,704,846
1045  201705  경기도  가평군  일반용   9,814    21,226,525
...      ...  ...  ...  ...      ...           ...
541   201702  경기도  화성시  일반용  38,373   174,517,489
789   201703  경기도  화성시  일반용  38,506   157,832,463
1037  201704  경기도  화성시  일반용  38,695   143,733,043
1285  201705  경기도  화성시  일반용  38,873   132,542,602
1533  201706  경기도  화성시  일반용  39,150   143,258,296

[186 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[31833929, 32844747, 27113311, 23704846, 21226525, 21572697]
[192039326, 199735144, 157722141, 144703116, 135177573, 148228914]
[22838452, 23035028, 21013567, 19132387, 18262686, 19673172]
[39455531, 40033127, 33495243, 30086295, 28257802, 31719965]
[62576739, 63976078, 53520020, 48676153, 42246517, 44897234]
[34193424, 35072762, 29162513, 26790819, 24901760, 28178413]
[38069534, 39975991, 34296478, 31013196, 27881728, 31369116]
[70794628, 72697752, 61360176, 53958306, 47709839, 51841645]
[92494575, 96949431, 80303728, 72862175, 63414143, 68700137]
[22088657, 23486711, 18021231, 17761821, 15098549, 17064111]
[121704063, 124562412, 104594651, 95284461, 88251800, 97547447]
[226380150, 221997631, 201640562, 185407511, 186116481, 207513573]
[252907383, 252484046, 225014594, 207491481, 200071473, 219917663]
[72556707, 75453446, 62538607, 56422119, 49689212, 53786741]
[110355960, 114778514, 96729567, 87068696, 78937682, 85971132]
[45706928, 46926433, 40465621, 36645007, 33136252, 34911895]
[109782129, 110770160, 96081884, 87427033, 81986201, 90607861]
[44479043, 44954947, 31733813, 28671989, 25116297, 27042978]
[29441115, 30951175, 25110271, 22558675, 19015657, 19554288]
[29582362, 30196650, 26589293, 25090815, 23517635, 25227783]
[14879456, 15446104, 12271824, 11040200, 9309551, 9874112]
[34115571, 35918475, 30343640, 27584672, 24891259, 27120100]
[212072100, 214469360, 187953920, 170673027, 160756559, 174617533]
[29719603, 29671841, 26244491, 23940534, 22423097, 24378265]
[70136457, 72669247, 59878049, 53891124, 49707126, 55579596]
[64513499, 64914015, 54258263, 48470798, 44393671, 48203413]
[93118528, 97753697, 81196804, 72884320, 64207485, 69265350]
[123428989, 127402813, 108769797, 101488955, 91150423, 101026716]
[48461454, 50608582, 41924553, 37787649, 33078066, 34297427]
[44209917, 44498941, 37663151, 34521760, 32226388, 35125971]
[171214774, 174517489, 157832463, 143733043, 132542602, 143258296]
경기도 지역별 일반용 합계 :  [158296055, 977606214, 123955292, 203047963, 315892741, 178299691, 202606043, 358362346, 474724189, 113521080, 631944834, 1229055908, 1357886640, 370446832, 573841551, 237792136, 576655268, 201999067, 146631181, 160204538, 72821247, 179973717, 1120542499, 156377831, 361861599, 324753659, 478426184, 653267693, 246157731, 228246128, 923098667]
경기도 고객호수 평균:  [9805, 40142, 2298, 11256, 24964, 10379, 8861, 19810, 34533, 6098, 35585, 33989, 52622, 22735, 28951, 14403, 24533, 13365, 12064, 9515, 4954, 10548, 37914, 5753, 21227, 15719, 26004, 35348, 17483, 13270, 38662]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13740\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0           201701  경기도  가평군  일반용  9,821   31,833,929
1           201702  경기도  가평군  일반용  9,799   32,844,747
2           201703  경기도  가평군  일반용  9,766   27,113,311
3           201704  경기도  가평군  일반용  9,775   23,704,846
4           201705  경기도  가평군  일반용  9,814   21,226,525
..             ...  ...  ...  ...     ...          ...
212  201701-201706  경기도  파주시  일반용   26004    478426184
213  201701-201706  경기도  평택시  일반용   35348    653267693
214  201701-201706  경기도  포천시  일반용   17483    246157731
215  201701-201706  경기도  하남시  일반용   13270    228246128
216  201701-201706  경기도  화성시  일반용   38662    923098667

[217 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201701-201706']
GyeonGiHap2

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201701-201706  경기도   가평군  일반용    9805   158296055
187  201701-201706  경기도   고양시  일반용   40142   977606214
188  201701-201706  경기도   과천시  일반용    2298   123955292
189  201701-201706  경기도   광명시  일반용   11256   203047963
190  201701-201706  경기도   광주시  일반용   24964   315892741
191  201701-201706  경기도   구리시  일반용   10379   178299691
192  201701-201706  경기도   군포시  일반용    8861   202606043
193  201701-201706  경기도   김포시  일반용   19810   358362346
194  201701-201706  경기도  남양주시  일반용   34533   474724189
195  201701-201706  경기도  동두천시  일반용    6098   113521080
196  201701-201706  경기도   부천시  일반용   35585   631944834
197  201701-201706  경기도   성남시  일반용   33989  1229055908
198  201701-201706  경기도   수원시  일반용   52622  1357886640
199  201701-201706  경기도   시흥시  일반용   22735   370446832
200  201701-201706  경기도   안산시  일반용   28951   573841551
201  201701-201706  경기도   안성시  일반용   14403   237792136
202  201701-201706  경기도   안양시  일반용   24533   576655268
203  201701-201706  경기도   양주시  일반용   13365   201999067
204  201701-201706  경기도   양평군  일반용   12064   146631181
205  201701-201706  경기도   여주시  일반용    9515   160204538
206  201701-201706  경기도   연천군  일반용    4954    72821247
207  201701-201706  경기도   오산시  일반용   10548   179973717
208  201701-201706  경기도   용인시  일반용   37914  1120542499
209  201701-201706  경기도   의왕시  일반용    5753   156377831
210  201701-201706  경기도  의정부시  일반용   21227   361861599
211  201701-201706  경기도   이천시  일반용   15719   324753659
212  201701-201706  경기도   파주시  일반용   26004   478426184
213  201701-201706  경기도   평택시  일반용   35348   653267693
214  201701-201706  경기도   포천시  일반용   17483   246157731
215  201701-201706  경기도   하남시  일반용   13270   228246128
216  201701-201706  경기도   화성시  일반용   38662   923098667

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
186  201701-201706  경기도  가평군  일반용    9805   158296055
186  201701-201706  경기도  가평군   합계   10432   353380108
187  201701-201706  경기도  고양시  일반용   40142   977606214
187  201701-201706  경기도  고양시   합계   38037  2286442393
188  201701-201706  경기도  과천시  일반용    2298   123955292
..             ...  ...  ...  ...     ...         ...
214  201701-201706  경기도  포천시  일반용   17483   246157731
215  201701-201706  경기도  하남시   합계    8425   665305131
215  201701-201706  경기도  하남시  일반용   13270   228246128
216  201701-201706  경기도  화성시  일반용   38662   923098667
216  201701-201706  경기도  화성시   합계   38814  8646563818

[62 rows x 6 columns]

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[158296055,
 977606214,
 123955292,
 203047963,
 315892741,
 178299691,
 202606043,
 358362346,
 474724189,
 113521080,
 631944834,
 1229055908,
 1357886640,
 370446832,
 573841551,
 237792136,
 576655268,
 201999067,
 146631181,
 160204538,
 72821247,
 179973717,
 1120542499,
 156377831,
 361861599,
 324753659,
 478426184,
 653267693,
 246157731,
 228246128,
 923098667]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[353380108,
 2286442393,
 196703019,
 559642889,
 1276269760,
 374061930,
 727748179,
 1792874101,
 1519130193,
 335321150,
 2048870211,
 2419352789,
 2665737245,
 2147654407,
 4157662993,
 1473646529,
 1267337315,
 1084565554,
 521933108,
 726135636,
 295357750,
 620455426,
 4671287970,
 356654455,
 813395499,
 2771688848,
 4341646991,
 4056231209,
 1403805458,
 665305131,
 8646563818]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[44.79, 42.76, 63.02, 36.28, 24.75, 47.67, 27.84, 19.99, 31.25, 33.85, 30.84, 50.8, 50.94, 17.25, 13.8, 16.14, 45.5, 18.62, 28.09, 22.06, 24.66, 29.01, 23.99, 43.85, 44.49, 11.72, 11.02, 16.11, 17.54, 34.31, 10.68]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    45
1    43
2    63
3    36
4    25
5    48
6    28
7    20
8    31
9    34
10   31
11   51
12   51
13   17
14   14
15   16
16   46
17   19
18   28
19   22
20   25
21   29
22   24
23   44
24   44
25   12
26   11
27   16
28   18
29   34
30   11
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    가평군  일반용  45
1    고양시  일반용  43
2    과천시  일반용  63
3    광명시  일반용  36
4    광주시  일반용  25
5    구리시  일반용  48
6    군포시  일반용  28
7    김포시  일반용  20
8   남양주시  일반용  31
9   동두천시  일반용  34
10   부천시  일반용  31
11   성남시  일반용  51
12   수원시  일반용  51
13   시흥시  일반용  17
14   안산시  일반용  14
15   안성시  일반용  16
16   안양시  일반용  46
17   양주시  일반용  19
18   양평군  일반용  28
19   여주시  일반용  22
20   연천군  일반용  25
21   오산시  일반용  29
22   용인시  일반용  24
23   의왕시  일반용  44
24  의정부시  일반용  44
25   이천시  일반용  12
26   파주시  일반용  11
27   평택시  일반용  16
28   포천시  일반용  18
29   하남시  일반용  34
30   화성시  일반용  11

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201701-201706  경기도  가평군  일반용    9805   158296055  45
1   201701-201706  경기도  가평군   합계   10432   353380108 NaN
2   201701-201706  경기도  고양시  일반용   40142   977606214  43
3   201701-201706  경기도  고양시   합계   38037  2286442393 NaN
4   201701-201706  경기도  과천시  일반용    2298   123955292  63
..            ...  ...  ...  ...     ...         ...  ..
56  201701-201706  경기도  포천시   합계   18786  1403805458 NaN
59  201701-201706  경기도  하남시  일반용   13270   228246128  34
58  201701-201706  경기도  하남시   합계    8425   665305131 NaN
60  201701-201706  경기도  화성시  일반용   38662   923098667  11
61  201701-201706  경기도  화성시   합계   38814  8646563818 NaN

[62 rows x 7 columns]

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1701-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)