In [3]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [4]:
df = pd.read_csv('경기도_계약종별_전력사용량_월별_12하반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경기도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2012년 07 월 ~ 2012년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,경기도,전체(시 / 군 / 구),주택용,"2,432,020","1,255,547,544","149,690,978,453",119.2
4,201207,경기도,전체(시 / 군 / 구),일반용,"566,917","2,198,611,349","226,055,253,405",102.8
...,...,...,...,...,...,...,...,...
1531,201212,경기도,화성시,산업용,"13,940","936,322,662","98,387,023,060",105.1
1532,201212,경기도,화성시,심 야,"13,661","40,680,906","2,780,632,579",68.4
1533,201212,경기도,화성시,일반용,"30,459","117,474,913","14,538,269,313",123.8
1534,201212,경기도,화성시,주택용,"88,521","60,864,167","7,760,202,443",127.5
1535,201212,경기도,화성시,합계,"186,814","1,192,820,310","125,925,424,169",105.6

In [5]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,경기도,전체(시 / 군 / 구),주택용,"2,432,020","1,255,547,544","149,690,978,453",119.2
4,201207,경기도,전체(시 / 군 / 구),일반용,"566,917","2,198,611,349","226,055,253,405",102.8
5,201207,경기도,전체(시 / 군 / 구),교육용,"7,245","114,302,998","13,962,587,613",122.2
6,201207,경기도,전체(시 / 군 / 구),산업용,"105,082","4,409,916,597","452,852,497,221",102.7
...,...,...,...,...,...,...,...,...
1531,201212,경기도,화성시,산업용,"13,940","936,322,662","98,387,023,060",105.1
1532,201212,경기도,화성시,심 야,"13,661","40,680,906","2,780,632,579",68.4
1533,201212,경기도,화성시,일반용,"30,459","117,474,913","14,538,269,313",123.8
1534,201212,경기도,화성시,주택용,"88,521","60,864,167","7,760,202,443",127.5
1535,201212,경기도,화성시,합계,"186,814","1,192,820,310","125,925,424,169",105.6

In [6]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [7]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,경기도,전체(시 / 군 / 구),주택용,"2,432,020","1,255,547,544","149,690,978,453",119.2
4,201207,경기도,전체(시 / 군 / 구),일반용,"566,917","2,198,611,349","226,055,253,405",102.8
5,201207,경기도,전체(시 / 군 / 구),교육용,"7,245","114,302,998","13,962,587,613",122.2
6,201207,경기도,전체(시 / 군 / 구),산업용,"105,082","4,409,916,597","452,852,497,221",102.7
7,201207,경기도,전체(시 / 군 / 구),농사용,"174,673","127,318,655","5,679,052,420",44.6
...,...,...,...,...,...,...,...,...
1531,201212,경기도,화성시,산업용,"13,940","936,322,662","98,387,023,060",105.1
1532,201212,경기도,화성시,심 야,"13,661","40,680,906","2,780,632,579",68.4
1533,201212,경기도,화성시,일반용,"30,459","117,474,913","14,538,269,313",123.8
1534,201212,경기도,화성시,주택용,"88,521","60,864,167","7,760,202,443",127.5
1535,201212,경기도,화성시,합계,"186,814","1,192,820,310","125,925,424,169",105.6

In [8]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,경기도,전체(시 / 군 / 구),주택용,"2,432,020","1,255,547,544","149,690,978,453",119.2
4,201207,경기도,전체(시 / 군 / 구),일반용,"566,917","2,198,611,349","226,055,253,405",102.8
5,201207,경기도,전체(시 / 군 / 구),교육용,"7,245","114,302,998","13,962,587,613",122.2
6,201207,경기도,전체(시 / 군 / 구),산업용,"105,082","4,409,916,597","452,852,497,221",102.7
7,201207,경기도,전체(시 / 군 / 구),농사용,"174,673","127,318,655","5,679,052,420",44.6
8,201207,경기도,전체(시 / 군 / 구),가로등,"266,819","51,218,663","5,730,343,515",111.9
9,201207,경기도,전체(시 / 군 / 구),심 야,"168,771","99,637,209","5,109,312,093",51.3
10,201208,경기도,전체(시 / 군 / 구),주택용,"2,440,359","1,549,287,100","239,631,184,767",154.7
11,201208,경기도,전체(시 / 군 / 구),일반용,"568,368","1,984,928,328","288,682,214,892",145.4
12,201208,경기도,전체(시 / 군 / 구),교육용,"7,257","111,883,651","15,397,230,048",137.6
13,201208,경기도,전체(시 / 군 / 구),산업용,"105,246","4,392,583,484","490,456,405,567",111.7
14,201208,경기도,전체(시 / 군 / 구),농사용,"176,021","163,341,301","7,017,930,665",43.0
15,201208,경기도,전체(시 / 군 / 구),가로등,"267,934","54,287,218","5,713,391,485",105.2
16,201208,경기도,전체(시 / 군 / 구),심 야,"168,436","94,970,706","5,046,110,993",53.1
17,201209,경기도,전체(시 / 군 / 구),주택용,"2,448,533","1,341,316,275","175,003,688,304",130.5
18,201209,경기도,전체(시 / 군 / 구),일반용,"569,428","1,935,315,426","224,022,000,674",115.8
19,201209,경기도,전체(시 / 군 / 구),교육용,"7,253","111,168,984","13,437,851,172",120.9
20,201209,경기도,전체(시 / 군 / 구),산업용,"105,431","4,266,790,435","398,850,782,999",93.5
21,201209,경기도,전체(시 / 군 / 구),농사용,"177,209","151,782,150","6,946,161,923",45.8
22,201209,경기도,전체(시 / 군 / 구),가로등,"268,534","57,455,446","6,064,512,642",105.6
23,201209,경기도,전체(시 / 군 / 구),심 야,"168,313","100,003,854","5,292,533,606",52.9
24,201210,경기도,전체(시 / 군 / 구),주택용,"2,456,065","1,194,420,742","135,377,583,927",113.3
25,201210,경기도,전체(시 / 군 / 구),일반용,"570,216","1,623,660,090","173,033,060,999",106.6
26,201210,경기도,전체(시 / 군 / 구),교육용,"7,252","90,569,841","10,587,960,787",116.9
27,201210,경기도,전체(시 / 군 / 구),산업용,"105,604","4,132,456,236","374,547,957,414",90.6
28,201210,경기도,전체(시 / 군 / 구),농사용,"177,852","128,608,973","6,031,441,387",46.9
29,201210,경기도,전체(시 / 군 / 구),가로등,"269,390","62,512,160","6,305,559,147",100.9
30,201210,경기도,전체(시 / 군 / 구),심 야,"168,322","162,525,365","8,254,168,758",50.8
31,201211,경기도,전체(시 / 군 / 구),주택용,"2,463,819","1,283,208,538","156,084,994,139",121.6
32,201211,경기도,전체(시 / 군 / 구),일반용,"572,219","1,769,263,513","211,130,571,862",119.3
33,201211,경기도,전체(시 / 군 / 구),교육용,"7,264","118,083,457","14,045,250,802",118.9
34,201211,경기도,전체(시 / 군 / 구),산업용,"105,908","4,422,098,553","474,145,970,237",107.2
35,201211,경기도,전체(시 / 군 / 구),농사용,"249,243","204,402,990","7,981,411,244",39.0
36,201211,경기도,전체(시 / 군 / 구),가로등,"270,441","68,404,728","6,728,897,030",98.4
37,201211,경기도,전체(시 / 군 / 구),심 야,"168,285","338,675,278","19,654,400,323",58.0
38,201212,경기도,전체(시 / 군 / 구),주택용,"2,470,756","1,345,612,537","169,912,941,547",126.3
39,201212,경기도,전체(시 / 군 / 구),일반용,"575,012","2,158,344,329","263,218,420,619",122.0
40,201212,경기도,전체(시 / 군 / 구),교육용,"7,278","172,093,549","19,250,763,611",111.9
41,201212,경기도,전체(시 / 군 / 구),산업용,"106,126","4,721,191,293","501,001,592,444",106.1
42,201212,경기도,전체(시 / 군 / 구),농사용,"186,119","201,421,314","8,536,268,173",42.4
43,201212,경기도,전체(시 / 군 / 구),가로등,"271,407","70,886,679","6,829,668,965",96.3
44,201212,경기도,전체(시 / 군 / 구),심 야,"168,223","549,609,341","37,504,294,995",68.2
45,합계,합계,합계,합계,"22,576,650","49,389,716,879","5,350,805,202,867",108.3

In [9]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_6564\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)        사용량(kWh)
4   201207  경기도  일반용  566,917   2,198,611,349
11  201208  경기도  일반용  568,368   1,984,928,328
18  201209  경기도  일반용  569,428   1,935,315,426
25  201210  경기도  일반용  570,216   1,623,660,090
32  201211  경기도  일반용  572,219   1,769,263,513
39  201212  경기도  일반용  575,012   2,158,344,329

In [10]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [11]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [12]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201207  경기도  가평군  일반용   7,891    18,740,590
301   201208  경기도  가평군  일반용   8,001    22,827,836
549   201209  경기도  가평군  일반용   8,067    19,561,033
797   201210  경기도  가평군  일반용   8,126    16,827,707
1045  201211  경기도  가평군  일반용   8,225    20,085,789
...      ...  ...  ...  ...      ...           ...
541   201208  경기도  화성시  일반용  29,770   112,389,768
789   201209  경기도  화성시  일반용  29,957   101,165,817
1037  201210  경기도  화성시  일반용  30,045    85,909,566
1285  201211  경기도  화성시  일반용  30,201    96,079,072
1533  201212  경기도  화성시  일반용  30,459   117,474,913

[186 rows x 6 columns]

In [13]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경기도'

In [14]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['가평군',
 '고양시',
 '과천시',
 '광명시',
 '광주시',
 '구리시',
 '군포시',
 '김포시',
 '남양주시',
 '동두천시',
 '부천시',
 '성남시',
 '수원시',
 '시흥시',
 '안산시',
 '안성시',
 '안양시',
 '양주시',
 '양평군',
 '여주시',
 '연천군',
 '오산시',
 '용인시',
 '의왕시',
 '의정부시',
 '이천시',
 '파주시',
 '평택시',
 '포천시',
 '하남시',
 '화성시']

In [15]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월   시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201207  경기도  가평군   합계   53,913      37,552,828
303   201208  경기도  가평군   합계   54,194      43,464,970
551   201209  경기도  가평군   합계   54,479      40,811,728
799   201210  경기도  가평군   합계   54,625      39,947,658
1047  201211  경기도  가평군   합계   56,020      51,943,449
...      ...  ...  ...  ...       ...             ...
543   201208  경기도  화성시   합계  176,329   1,059,017,731
791   201209  경기도  화성시   합계  177,296   1,013,474,193
1039  201210  경기도  화성시   합계  178,030     995,093,637
1287  201211  경기도  화성시   합계  184,678   1,097,076,991
1535  201212  경기도  화성시   합계  186,814   1,192,820,310

[186 rows x 6 columns]

In [16]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[37552828, 43464970, 40811728, 39947658, 51943449, 65350382]
[341961458, 392441216, 348331000, 304588960, 343932374, 407832988]
[35805805, 40858493, 34601264, 31276887, 32786206, 36776361]
[99467074, 112094853, 96958729, 88025418, 96046488, 107626265]
[158750131, 171175623, 165328535, 151132771, 187062303, 220110334]
[64802292, 73813621, 63708070, 53727499, 58450737, 67072101]
[121412416, 133246119, 121749615, 107414902, 117094033, 134007751]
[200017128, 210560740, 207579907, 184839878, 231033754, 268089630]
[195618599, 217158659, 203027758, 184185753, 211580646, 250964677]
[289541702, -191690349, 48668537, 51431278, 49000337, 56238715]
[355486206, 397812705, 351983023, 305362375, 334561469, 378863880]
[409636395, 458932162, 390712212, 339468953, 364806546, 415771409]
[415677024, 473137608, 412395107, 360359003, 388149601, 440553420]
[322918563, 345510393, 329626345, 301829220, 342067084, 383139268]
[684333101, 708724528, 676466720, 628711071, 673010996, 720909798]
[193668179, 206060032, 194266084, 182542102, 216167090, 239934966]
[213829532, 241155640, 214393117, 185673500, 201036382, 228932009]
[148756858, 148935825, 152165771, 142090487, 176811040, 200967329]
[46757321, 54831102, 51514255, 54735516, 79959062, 101191859]
[86023171, 92624916, 88003414, 84951855, 110997024, 126538415]
[32444050, 36210170, 35913995, 34898869, 47217872, 54847144]
[96252831, 106482059, 100172270, 91008012, 97319567, 108038256]
[715800389, 766011962, 700813844, 661172724, 703497985, 787790258]
[53965200, 60347886, 54735908, 47633030, 53707966, 62271601]
[129977168, 147224842, 129986188, 112159198, 124368782, 151289066]
[336133610, 355018903, 327636553, 318842209, 346672496, 379408951]
[615186748, 638712248, 599023211, 580577058, 611713243, 663086033]
[559505590, 580138705, 548532719, 527012538, 558129131, 628736602]
[168940273, 177718244, 176028930, 167022500, 212927572, 242068230]
[86027006, 93550182, 85223568, 77038546, 85008831, 97931034]
[1040304367, 1059017731, 1013474193, 995093637, 1097076991, 1192820310]
경기도 지역별 합계 :  [279071015, 2139087996, 212105016, 600218827, 1053559697, 381574320, 734924836, 1302121037, 1262536092, 303190220, 2124069658, 2379327677, 2490271763, 2025090873, 4092156214, 1232638453, 1285020180, 969727310, 388989115, 589138795, 241532100, 599272995, 4335087162, 332661591, 795005244, 2063712722, 3708298541, 3402055285, 1144705749, 524779167, 6397787229]
경기도 고객호수 평균:  [9115, 34248, 2263, 12962, 21234, 8153, 9202, 14836, 25097, 6037, 42988, 44607, 53986, 22900, 45032, 17952, 23019, 12349, 15024, 12245, 6638, 8877, 31839, 5478, 17089, 16985, 22356, 30420, 16729, 7498, 29956]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [17]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201207  경기도  가평군   합계  53,913   37,552,828
1           201208  경기도  가평군   합계  54,194   43,464,970
2           201209  경기도  가평군   합계  54,479   40,811,728
3           201210  경기도  가평군   합계  54,625   39,947,658
4           201211  경기도  가평군   합계  56,020   51,943,449
..             ...  ...  ...  ...      ...          ...
212  201207-201212  경기도  파주시   합계    22356   3708298541
213  201207-201212  경기도  평택시   합계    30420   3402055285
214  201207-201212  경기도  포천시   합계    16729   1144705749
215  201207-201212  경기도  하남시   합계     7498    524779167
216  201207-201212  경기도  화성시   합계    29956   6397787229

[217 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [18]:
Hap = Hap.loc[Hap['년월'] == '201207-201212']
Hap

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201207-201212  경기도   가평군   합계    9115   279071015
187  201207-201212  경기도   고양시   합계   34248  2139087996
188  201207-201212  경기도   과천시   합계    2263   212105016
189  201207-201212  경기도   광명시   합계   12962   600218827
190  201207-201212  경기도   광주시   합계   21234  1053559697
191  201207-201212  경기도   구리시   합계    8153   381574320
192  201207-201212  경기도   군포시   합계    9202   734924836
193  201207-201212  경기도   김포시   합계   14836  1302121037
194  201207-201212  경기도  남양주시   합계   25097  1262536092
195  201207-201212  경기도  동두천시   합계    6037   303190220
196  201207-201212  경기도   부천시   합계   42988  2124069658
197  201207-201212  경기도   성남시   합계   44607  2379327677
198  201207-201212  경기도   수원시   합계   53986  2490271763
199  201207-201212  경기도   시흥시   합계   22900  2025090873
200  201207-201212  경기도   안산시   합계   45032  4092156214
201  201207-201212  경기도   안성시   합계   17952  1232638453
202  201207-201212  경기도   안양시   합계   23019  1285020180
203  201207-201212  경기도   양주시   합계   12349   969727310
204  201207-201212  경기도   양평군   합계   15024   388989115
205  201207-201212  경기도   여주시   합계   12245   589138795
206  201207-201212  경기도   연천군   합계    6638   241532100
207  201207-201212  경기도   오산시   합계    8877   599272995
208  201207-201212  경기도   용인시   합계   31839  4335087162
209  201207-201212  경기도   의왕시   합계    5478   332661591
210  201207-201212  경기도  의정부시   합계   17089   795005244
211  201207-201212  경기도   이천시   합계   16985  2063712722
212  201207-201212  경기도   파주시   합계   22356  3708298541
213  201207-201212  경기도   평택시   합계   30420  3402055285
214  201207-201212  경기도   포천시   합계   16729  1144705749
215  201207-201212  경기도   하남시   합계    7498   524779167
216  201207-201212  경기도   화성시   합계   29956  6397787229

In [19]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [20]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [21]:
df_3

          년월   시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201207  경기도  가평군  일반용   7,891    18,740,590
301   201208  경기도  가평군  일반용   8,001    22,827,836
549   201209  경기도  가평군  일반용   8,067    19,561,033
797   201210  경기도  가평군  일반용   8,126    16,827,707
1045  201211  경기도  가평군  일반용   8,225    20,085,789
...      ...  ...  ...  ...      ...           ...
541   201208  경기도  화성시  일반용  29,770   112,389,768
789   201209  경기도  화성시  일반용  29,957   101,165,817
1037  201210  경기도  화성시  일반용  30,045    85,909,566
1285  201211  경기도  화성시  일반용  30,201    96,079,072
1533  201212  경기도  화성시  일반용  30,459   117,474,913

[186 rows x 6 columns]

In [22]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [23]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[18740590, 22827836, 19561033, 16827707, 20085789, 24276221]
[156678183, 177277123, 156935061, 130080055, 139280036, 165467640]
[22056359, 23974640, 20584042, 18520741, 19423027, 22203112]
[37661894, 43174534, 36063815, 31121429, 32732506, 39227030]
[40167689, 46958554, 41377820, 34843058, 40546173, 50959486]
[31094638, 35366780, 30199682, 24168300, 26130705, 31587228]
[28499160, 33445757, 30225129, 24101022, 25950629, 31808869]
[38406848, 44604444, 39037590, 32356259, 37753993, 49081601]
[62286448, 71738827, 63818372, 52274931, 58972034, 72392528]
[260320739, -222385141, 18360233, 22549068, 15424754, 18711288]
[111676313, 131608554, 113279918, 91616781, 96559551, 118673477]
[204569890, 224354972, 190127545, 158054676, 168048101, 198472150]
[214566041, 239749354, 205945699, 173188699, 184813889, 220075827]
[54985001, 64583833, 55568940, 45238976, 51255796, 64257956]
[96469910, 112100912, 95819232, 77456112, 84197655, 103978243]
[31750653, 36217062, 31528085, 27616708, 31253551, 37505883]
[96993459, 109406781, 95364370, 78247749, 82529845, 99374474]
[30782353, 31645044, 30107499, 26870217, 31736159, 39468426]
[16574001, 20114112, 17320685, 15111475, 17982646, 22180517]
[23300993, 26168531, 22629656, 19786567, 22345936, 25994732]
[9703171, 11411077, 9865392, 8734761, 10921457, 13422613]
[24731991, 30317627, 26356366, 20877676, 22741707, 28392931]
[162950493, 181761596, 157447487, 136025394, 149009723, 180308943]
[18734437, 21332017, 18897173, 18334296, 19719173, 23827055]
[60021075, 69036502, 58334536, 46462074, 51061604, 64149484]
[38093865, 43568436, 38044552, 32283547, 37826706, 47130849]
[61169728, 70655250, 62220379, 51490149, 59405554, 74882055]
[86621410, 102571012, 88661936, 72176497, 76380054, 100634020]
[33040989, 38528437, 34253375, 29839590, 34759399, 42296977]
[26468996, 30424097, 26214007, 21496010, 24336289, 30127801]
[99494032, 112389768, 101165817, 85909566, 96079072, 117474913]
경기도 지역별 일반용 합계 :  [122319176, 925718098, 126761921, 219981208, 254852780, 178547333, 174030566, 241240735, 381483140, 112980941, 663414594, 1143627334, 1238339509, 335890502, 570022064, 195871942, 561916678, 190609698, 109283436, 140226415, 64058471, 153418298, 967503636, 120844151, 349065275, 236947955, 379823115, 527044929, 212718767, 159067200, 612513168]
경기도 고객호수 평균:  [8101, 37155, 2070, 10689, 21072, 9790, 8095, 16069, 28182, 5757, 33853, 32056, 46988, 21059, 27471, 12772, 23739, 12449, 9989, 8343, 4795, 9032, 32319, 5211, 19149, 13678, 23115, 28837, 16547, 11959, 30007]

In [24]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [25]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [26]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [27]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_6564\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0           201207  경기도  가평군  일반용  7,891   18,740,590
1           201208  경기도  가평군  일반용  8,001   22,827,836
2           201209  경기도  가평군  일반용  8,067   19,561,033
3           201210  경기도  가평군  일반용  8,126   16,827,707
4           201211  경기도  가평군  일반용  8,225   20,085,789
..             ...  ...  ...  ...     ...          ...
212  201207-201212  경기도  파주시  일반용   23115    379823115
213  201207-201212  경기도  평택시  일반용   28837    527044929
214  201207-201212  경기도  포천시  일반용   16547    212718767
215  201207-201212  경기도  하남시  일반용   11959    159067200
216  201207-201212  경기도  화성시  일반용   30007    612513168

[217 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [28]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201207-201212']
GyeonGiHap2

                년월   시구   시군구 계약구분 고객호수(호)    사용량(kWh)
186  201207-201212  경기도   가평군  일반용    8101   122319176
187  201207-201212  경기도   고양시  일반용   37155   925718098
188  201207-201212  경기도   과천시  일반용    2070   126761921
189  201207-201212  경기도   광명시  일반용   10689   219981208
190  201207-201212  경기도   광주시  일반용   21072   254852780
191  201207-201212  경기도   구리시  일반용    9790   178547333
192  201207-201212  경기도   군포시  일반용    8095   174030566
193  201207-201212  경기도   김포시  일반용   16069   241240735
194  201207-201212  경기도  남양주시  일반용   28182   381483140
195  201207-201212  경기도  동두천시  일반용    5757   112980941
196  201207-201212  경기도   부천시  일반용   33853   663414594
197  201207-201212  경기도   성남시  일반용   32056  1143627334
198  201207-201212  경기도   수원시  일반용   46988  1238339509
199  201207-201212  경기도   시흥시  일반용   21059   335890502
200  201207-201212  경기도   안산시  일반용   27471   570022064
201  201207-201212  경기도   안성시  일반용   12772   195871942
202  201207-201212  경기도   안양시  일반용   23739   561916678
203  201207-201212  경기도   양주시  일반용   12449   190609698
204  201207-201212  경기도   양평군  일반용    9989   109283436
205  201207-201212  경기도   여주시  일반용    8343   140226415
206  201207-201212  경기도   연천군  일반용    4795    64058471
207  201207-201212  경기도   오산시  일반용    9032   153418298
208  201207-201212  경기도   용인시  일반용   32319   967503636
209  201207-201212  경기도   의왕시  일반용    5211   120844151
210  201207-201212  경기도  의정부시  일반용   19149   349065275
211  201207-201212  경기도   이천시  일반용   13678   236947955
212  201207-201212  경기도   파주시  일반용   23115   379823115
213  201207-201212  경기도   평택시  일반용   28837   527044929
214  201207-201212  경기도   포천시  일반용   16547   212718767
215  201207-201212  경기도   하남시  일반용   11959   159067200
216  201207-201212  경기도   화성시  일반용   30007   612513168

In [29]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
186  201207-201212  경기도  가평군  일반용    8101   122319176
186  201207-201212  경기도  가평군   합계    9115   279071015
187  201207-201212  경기도  고양시  일반용   37155   925718098
187  201207-201212  경기도  고양시   합계   34248  2139087996
188  201207-201212  경기도  과천시  일반용    2070   126761921
..             ...  ...  ...  ...     ...         ...
214  201207-201212  경기도  포천시  일반용   16547   212718767
215  201207-201212  경기도  하남시   합계    7498   524779167
215  201207-201212  경기도  하남시  일반용   11959   159067200
216  201207-201212  경기도  화성시  일반용   30007   612513168
216  201207-201212  경기도  화성시   합계   29956  6397787229

[62 rows x 6 columns]

In [30]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[122319176,
 925718098,
 126761921,
 219981208,
 254852780,
 178547333,
 174030566,
 241240735,
 381483140,
 112980941,
 663414594,
 1143627334,
 1238339509,
 335890502,
 570022064,
 195871942,
 561916678,
 190609698,
 109283436,
 140226415,
 64058471,
 153418298,
 967503636,
 120844151,
 349065275,
 236947955,
 379823115,
 527044929,
 212718767,
 159067200,
 612513168]

In [31]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[279071015,
 2139087996,
 212105016,
 600218827,
 1053559697,
 381574320,
 734924836,
 1302121037,
 1262536092,
 303190220,
 2124069658,
 2379327677,
 2490271763,
 2025090873,
 4092156214,
 1232638453,
 1285020180,
 969727310,
 388989115,
 589138795,
 241532100,
 599272995,
 4335087162,
 332661591,
 795005244,
 2063712722,
 3708298541,
 3402055285,
 1144705749,
 524779167,
 6397787229]

In [32]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[43.83, 43.28, 59.76, 36.65, 24.19, 46.79, 23.68, 18.53, 30.22, 37.26, 31.23, 48.07, 49.73, 16.59, 13.93, 15.89, 43.73, 19.66, 28.09, 23.8, 26.52, 25.6, 22.32, 36.33, 43.91, 11.48, 10.24, 15.49, 18.58, 30.31, 9.57]

In [33]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    44
1    43
2    60
3    37
4    24
5    47
6    24
7    19
8    30
9    37
10   31
11   48
12   50
13   17
14   14
15   16
16   44
17   20
18   28
19   24
20   27
21   26
22   22
23   36
24   44
25   11
26   10
27   15
28   19
29   30
30   10
dtype: float64

In [34]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    가평군  일반용  44
1    고양시  일반용  43
2    과천시  일반용  60
3    광명시  일반용  37
4    광주시  일반용  24
5    구리시  일반용  47
6    군포시  일반용  24
7    김포시  일반용  19
8   남양주시  일반용  30
9   동두천시  일반용  37
10   부천시  일반용  31
11   성남시  일반용  48
12   수원시  일반용  50
13   시흥시  일반용  17
14   안산시  일반용  14
15   안성시  일반용  16
16   안양시  일반용  44
17   양주시  일반용  20
18   양평군  일반용  28
19   여주시  일반용  24
20   연천군  일반용  27
21   오산시  일반용  26
22   용인시  일반용  22
23   의왕시  일반용  36
24  의정부시  일반용  44
25   이천시  일반용  11
26   파주시  일반용  10
27   평택시  일반용  15
28   포천시  일반용  19
29   하남시  일반용  30
30   화성시  일반용  10

In [35]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201207-201212  경기도  가평군  일반용    8101   122319176  44
1   201207-201212  경기도  가평군   합계    9115   279071015 NaN
2   201207-201212  경기도  고양시  일반용   37155   925718098  43
3   201207-201212  경기도  고양시   합계   34248  2139087996 NaN
4   201207-201212  경기도  과천시  일반용    2070   126761921  60
..            ...  ...  ...  ...     ...         ...  ..
56  201207-201212  경기도  포천시   합계   16729  1144705749 NaN
59  201207-201212  경기도  하남시  일반용   11959   159067200  30
58  201207-201212  경기도  하남시   합계    7498   524779167 NaN
60  201207-201212  경기도  화성시  일반용   30007   612513168  10
61  201207-201212  경기도  화성시   합계   29956  6397787229 NaN

[62 rows x 7 columns]

In [36]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [37]:
Final.to_csv("{}_일반용_전력사용량_1207-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [38]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [39]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [40]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [41]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [42]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [43]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [44]:
# SEOUL

In [45]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)