In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_16상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2016년 01 월 ~ 2016년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,경상남도,전체(시 / 군 / 구),주택용,"1,111,804","385,954,785","51,153,797,273",132.5
4,201601,경상남도,전체(시 / 군 / 구),일반용,"215,352","567,063,953","76,576,865,299",135.0
...,...,...,...,...,...,...,...,...
907,201606,경상남도,합천군,산업용,968,"5,718,373","721,880,778",126.2
908,201606,경상남도,합천군,심 야,"2,217","1,487,783","80,384,911",54
909,201606,경상남도,합천군,일반용,"3,882","5,446,627","744,723,983",136.7
910,201606,경상남도,합천군,주택용,"27,943","4,175,210","482,135,920",115.5
911,201606,경상남도,합천군,합계,"51,248","26,080,632","2,551,359,545",97.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,경상남도,전체(시 / 군 / 구),주택용,"1,111,804","385,954,785","51,153,797,273",132.5
4,201601,경상남도,전체(시 / 군 / 구),일반용,"215,352","567,063,953","76,576,865,299",135.0
5,201601,경상남도,전체(시 / 군 / 구),교육용,"1,628","37,664,882","4,233,078,042",112.4
6,201601,경상남도,전체(시 / 군 / 구),산업용,"36,597","1,748,470,282","213,649,462,951",122.2
...,...,...,...,...,...,...,...,...
907,201606,경상남도,합천군,산업용,968,"5,718,373","721,880,778",126.2
908,201606,경상남도,합천군,심 야,"2,217","1,487,783","80,384,911",54
909,201606,경상남도,합천군,일반용,"3,882","5,446,627","744,723,983",136.7
910,201606,경상남도,합천군,주택용,"27,943","4,175,210","482,135,920",115.5
911,201606,경상남도,합천군,합계,"51,248","26,080,632","2,551,359,545",97.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,경상남도,전체(시 / 군 / 구),주택용,"1,111,804","385,954,785","51,153,797,273",132.5
4,201601,경상남도,전체(시 / 군 / 구),일반용,"215,352","567,063,953","76,576,865,299",135.0
5,201601,경상남도,전체(시 / 군 / 구),교육용,"1,628","37,664,882","4,233,078,042",112.4
6,201601,경상남도,전체(시 / 군 / 구),산업용,"36,597","1,748,470,282","213,649,462,951",122.2
7,201601,경상남도,전체(시 / 군 / 구),농사용,"178,953","314,184,457","14,660,802,461",46.7
...,...,...,...,...,...,...,...,...
907,201606,경상남도,합천군,산업용,968,"5,718,373","721,880,778",126.2
908,201606,경상남도,합천군,심 야,"2,217","1,487,783","80,384,911",54
909,201606,경상남도,합천군,일반용,"3,882","5,446,627","744,723,983",136.7
910,201606,경상남도,합천군,주택용,"27,943","4,175,210","482,135,920",115.5
911,201606,경상남도,합천군,합계,"51,248","26,080,632","2,551,359,545",97.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,경상남도,전체(시 / 군 / 구),주택용,"1,111,804","385,954,785","51,153,797,273",132.5
4,201601,경상남도,전체(시 / 군 / 구),일반용,"215,352","567,063,953","76,576,865,299",135.0
5,201601,경상남도,전체(시 / 군 / 구),교육용,"1,628","37,664,882","4,233,078,042",112.4
6,201601,경상남도,전체(시 / 군 / 구),산업용,"36,597","1,748,470,282","213,649,462,951",122.2
7,201601,경상남도,전체(시 / 군 / 구),농사용,"178,953","314,184,457","14,660,802,461",46.7
8,201601,경상남도,전체(시 / 군 / 구),가로등,"148,896","26,150,294","2,788,861,878",106.6
9,201601,경상남도,전체(시 / 군 / 구),심 야,"95,591","166,858,290","12,591,806,237",75.5
10,201602,경상남도,전체(시 / 군 / 구),주택용,"1,113,868","393,466,294","53,062,083,842",134.9
11,201602,경상남도,전체(시 / 군 / 구),일반용,"215,642","587,365,947","78,896,313,405",134.3
12,201602,경상남도,전체(시 / 군 / 구),교육용,"1,633","38,912,456","4,463,201,666",114.7
13,201602,경상남도,전체(시 / 군 / 구),산업용,"36,636","1,603,028,687","199,080,285,499",124.2
14,201602,경상남도,전체(시 / 군 / 구),농사용,"179,287","329,945,546","15,354,102,747",46.5
15,201602,경상남도,전체(시 / 군 / 구),가로등,"153,513","24,933,836","2,769,354,711",111.1
16,201602,경상남도,전체(시 / 군 / 구),심 야,"95,427","185,312,692","13,981,667,573",75.4
17,201603,경상남도,전체(시 / 군 / 구),주택용,"1,115,419","350,832,725","42,451,174,892",121.0
18,201603,경상남도,전체(시 / 군 / 구),일반용,"215,751","506,574,866","64,198,919,672",126.7
19,201603,경상남도,전체(시 / 군 / 구),교육용,"1,633","37,393,535","3,995,387,771",106.8
20,201603,경상남도,전체(시 / 군 / 구),산업용,"36,679","1,754,151,890","181,139,860,699",103.3
21,201603,경상남도,전체(시 / 군 / 구),농사용,"203,782","245,055,757","11,714,185,761",47.8
22,201603,경상남도,전체(시 / 군 / 구),가로등,"151,833","23,462,922","2,663,871,579",113.5
23,201603,경상남도,전체(시 / 군 / 구),심 야,"95,240","144,452,622","9,641,266,342",66.7
24,201604,경상남도,전체(시 / 군 / 구),주택용,"1,117,804","352,601,636","42,539,093,132",120.6
25,201604,경상남도,전체(시 / 군 / 구),일반용,"216,204","474,943,442","55,295,706,959",116.4
26,201604,경상남도,전체(시 / 군 / 구),교육용,"1,638","33,076,140","3,482,112,820",105.3
27,201604,경상남도,전체(시 / 군 / 구),산업용,"36,741","1,688,090,744","169,773,977,780",100.6
28,201604,경상남도,전체(시 / 군 / 구),농사용,"181,193","183,928,566","9,149,204,939",49.7
29,201604,경상남도,전체(시 / 군 / 구),가로등,"152,528","22,893,405","2,688,684,902",117.4
30,201604,경상남도,전체(시 / 군 / 구),심 야,"95,002","108,576,408","5,918,171,704",54.5
31,201605,경상남도,전체(시 / 군 / 구),주택용,"1,119,980","327,956,202","37,281,315,071",113.7
32,201605,경상남도,전체(시 / 군 / 구),일반용,"216,196","437,561,799","52,631,202,007",120.3
33,201605,경상남도,전체(시 / 군 / 구),교육용,"1,644","26,485,513","3,079,306,302",116.3
34,201605,경상남도,전체(시 / 군 / 구),산업용,"36,779","1,632,584,813","165,851,852,500",101.6
35,201605,경상남도,전체(시 / 군 / 구),농사용,"182,149","125,136,123","6,654,220,459",53.2
36,201605,경상남도,전체(시 / 군 / 구),가로등,"153,125","21,209,049","2,581,403,028",121.7
37,201605,경상남도,전체(시 / 군 / 구),심 야,"94,751","67,163,562","3,671,620,190",54.7
38,201606,경상남도,전체(시 / 군 / 구),주택용,"1,122,639","330,126,637","37,895,434,050",114.8
39,201606,경상남도,전체(시 / 군 / 구),일반용,"216,130","476,176,683","64,370,009,559",135.2
40,201606,경상남도,전체(시 / 군 / 구),교육용,"1,641","29,881,661","3,944,050,335",132.0
41,201606,경상남도,전체(시 / 군 / 구),산업용,"36,798","1,651,936,457","204,297,899,031",123.7
42,201606,경상남도,전체(시 / 군 / 구),농사용,"182,380","109,146,881","5,631,989,197",51.6
43,201606,경상남도,전체(시 / 군 / 구),가로등,"153,649","20,222,992","2,544,746,931",125.8
44,201606,경상남도,전체(시 / 군 / 구),심 야,"94,472","40,344,082","2,232,048,049",55.3
45,합계,합계,합계,합계,"10,818,607","17,631,279,513","1,940,580,399,245",110.1

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_5956\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201601  경상남도  일반용  215,352   567,063,953
11  201602  경상남도  일반용  215,642   587,365,947
18  201603  경상남도  일반용  215,751   506,574,866
25  201604  경상남도  일반용  216,204   474,943,442
32  201605  경상남도  일반용  216,196   437,561,799
39  201606  경상남도  일반용  216,130   476,176,683

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201601  경상남도  거제시  일반용  17,467   45,598,070
197  201602  경상남도  거제시  일반용  17,542   47,366,841
341  201603  경상남도  거제시  일반용  17,539   41,135,143
485  201604  경상남도  거제시  일반용  17,578   39,368,586
629  201605  경상남도  거제시  일반용  17,575   36,290,847
..      ...   ...  ...  ...      ...          ...
333  201602  경상남도  합천군  일반용   3,876    7,931,913
477  201603  경상남도  합천군  일반용   3,870    6,744,250
621  201604  경상남도  합천군  일반용   3,891    6,123,644
765  201605  경상남도  합천군  일반용   3,893    5,429,202
909  201606  경상남도  합천군  일반용   3,882    5,446,627

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201601  경상남도  거제시   합계  120,189   212,184,437
199  201602  경상남도  거제시   합계  120,568   198,929,875
343  201603  경상남도  거제시   합계  122,113   196,840,465
487  201604  경상남도  거제시   합계  121,049   187,586,788
631  201605  경상남도  거제시   합계  121,356   179,118,476
..      ...   ...  ...  ...       ...           ...
335  201602  경상남도  합천군   합계   52,781    40,420,938
479  201603  경상남도  합천군   합계   52,920    35,084,373
623  201604  경상남도  합천군   합계   50,984    30,439,319
767  201605  경상남도  합천군   합계   51,009    25,926,922
911  201606  경상남도  합천군   합계   51,248    26,080,632

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[212184437, 198929875, 196840465, 187586788, 179118476, 183992880]
[41622537, 42781636, 38648192, 35159891, 31295000, 31416187]
[63333619, 61972760, 58608307, 51508945, 44477044, 37579689]
[471921244, 477595264, 449218648, 431288131, 391465925, 408989309]
[24678464, 25655152, 22059871, 21120760, 18907380, 19761744]
[131155184, 135366153, 116321080, 99961857, 80869624, 75334441]
[119032965, 115919735, 112679216, 105725939, 98707587, 101618027]
[31820739, 32633034, 28047902, 24261720, 20999015, 21067268]
[313450813, 297301319, 299438255, 288458812, 274363859, 288386612]
[40089904, 39846008, 36725569, 32596024, 29647903, 28930856]
[272208950, 281887274, 241551919, 216774129, 183331611, 176964501]
[96993075, 98304601, 85959518, 77870693, 67290353, 67012962]
[985980338, 926591654, 953956795, 893242971, 840932105, 852367951]
[115496675, 109653932, 103224541, 95609499, 92163167, 92496803]
[32953072, 34446261, 30226237, 26793759, 24351710, 22480932]
[230170088, 218524736, 231595096, 225691181, 216869043, 205889607]
[24553347, 25135126, 21738333, 20019923, 17380337, 17464992]
[38701492, 40420938, 35084373, 30439319, 25926922, 26080632]
경상남도 지역별 합계 :  [1158652921, 220923443, 317480364, 2630478521, 132183371, 639008339, 653683469, 158829678, 1761399670, 207836264, 1372718384, 493431202, 5453071814, 608644617, 171251971, 1328739751, 126292058, 196653676]
경상남도 고객호수 평균:  [20192, 9097, 8635, 32305, 8144, 16240, 12243, 6794, 18549, 5587, 30980, 9912, 75688, 13270, 8788, 8785, 6761, 8538]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201601  경상남도  거제시   합계  120,189   212,184,437
1           201602  경상남도  거제시   합계  120,568   198,929,875
2           201603  경상남도  거제시   합계  122,113   196,840,465
3           201604  경상남도  거제시   합계  121,049   187,586,788
4           201605  경상남도  거제시   합계  121,356   179,118,476
..             ...   ...  ...  ...       ...           ...
121  201601-201606  경상남도  통영시   합계     13270     608644617
122  201601-201606  경상남도  하동군   합계      8788     171251971
123  201601-201606  경상남도  함안군   합계      8785    1328739751
124  201601-201606  경상남도  함양군   합계      6761     126292058
125  201601-201606  경상남도  합천군   합계      8538     196653676

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201601-201606']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201601-201606  경상남도  거제시   합계   20192  1158652921
109  201601-201606  경상남도  거창군   합계    9097   220923443
110  201601-201606  경상남도  고성군   합계    8635   317480364
111  201601-201606  경상남도  김해시   합계   32305  2630478521
112  201601-201606  경상남도  남해군   합계    8144   132183371
113  201601-201606  경상남도  밀양시   합계   16240   639008339
114  201601-201606  경상남도  사천시   합계   12243   653683469
115  201601-201606  경상남도  산청군   합계    6794   158829678
116  201601-201606  경상남도  양산시   합계   18549  1761399670
117  201601-201606  경상남도  의령군   합계    5587   207836264
118  201601-201606  경상남도  진주시   합계   30980  1372718384
119  201601-201606  경상남도  창녕군   합계    9912   493431202
120  201601-201606  경상남도  창원시   합계   75688  5453071814
121  201601-201606  경상남도  통영시   합계   13270   608644617
122  201601-201606  경상남도  하동군   합계    8788   171251971
123  201601-201606  경상남도  함안군   합계    8785  1328739751
124  201601-201606  경상남도  함양군   합계    6761   126292058
125  201601-201606  경상남도  합천군   합계    8538   196653676

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201601  경상남도  거제시  일반용  17,467   45,598,070
197  201602  경상남도  거제시  일반용  17,542   47,366,841
341  201603  경상남도  거제시  일반용  17,539   41,135,143
485  201604  경상남도  거제시  일반용  17,578   39,368,586
629  201605  경상남도  거제시  일반용  17,575   36,290,847
..      ...   ...  ...  ...      ...          ...
333  201602  경상남도  합천군  일반용   3,876    7,931,913
477  201603  경상남도  합천군  일반용   3,870    6,744,250
621  201604  경상남도  합천군  일반용   3,891    6,123,644
765  201605  경상남도  합천군  일반용   3,893    5,429,202
909  201606  경상남도  합천군  일반용   3,882    5,446,627

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[45598070, 47366841, 41135143, 39368586, 36290847, 38134870]
[10093535, 10539217, 8847717, 7904220, 6857426, 7073189]
[9386966, 9820325, 8424176, 8039786, 7276579, 7400372]
[83849014, 87157165, 74687699, 70625912, 65510697, 74308734]
[9186945, 9391666, 8029192, 7617332, 6916677, 6943850]
[17095263, 17676784, 15065973, 14122601, 12564342, 13465027]
[20935363, 21999101, 18656360, 17393014, 15434573, 16577695]
[5907650, 6159998, 5356573, 5035438, 4499387, 4577259]
[50286786, 51031959, 44305440, 41924009, 39261389, 43133209]
[4180225, 4394231, 3739615, 3463211, 3070164, 3111297]
[58736489, 61035617, 52735274, 49175490, 45139230, 49534469]
[11995803, 12926917, 10871646, 10012183, 9143249, 9631244]
[179843211, 185276881, 160764596, 149808502, 140737565, 155529325]
[27657953, 28806421, 24935490, 23221871, 20854756, 21853626]
[7732754, 8235980, 7130605, 6795112, 5657665, 5699534]
[11401327, 11535930, 9887875, 9451566, 8615935, 9316041]
[5738387, 6079001, 5257242, 4860965, 4302116, 4440315]
[7438212, 7931913, 6744250, 6123644, 5429202, 5446627]
경상남도 지역별 일반용 합계 :  [247894357, 51315304, 50348204, 456139221, 48085662, 89989990, 110996106, 31536305, 269942792, 21958743, 316356569, 64581042, 971960080, 147330117, 41251650, 60208674, 30678026, 39113848]
경상남도 고객호수 평균:  [17553, 4936, 4625, 28860, 4681, 9077, 9160, 3419, 17023, 2464, 24620, 5362, 56279, 10828, 4219, 5279, 3602, 3885]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5956\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201601  경상남도  거제시  일반용  17,467   45,598,070
1           201602  경상남도  거제시  일반용  17,542   47,366,841
2           201603  경상남도  거제시  일반용  17,539   41,135,143
3           201604  경상남도  거제시  일반용  17,578   39,368,586
4           201605  경상남도  거제시  일반용  17,575   36,290,847
..             ...   ...  ...  ...      ...          ...
121  201601-201606  경상남도  통영시  일반용    10828    147330117
122  201601-201606  경상남도  하동군  일반용     4219     41251650
123  201601-201606  경상남도  함안군  일반용     5279     60208674
124  201601-201606  경상남도  함양군  일반용     3602     30678026
125  201601-201606  경상남도  합천군  일반용     3885     39113848

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201601-201606']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201601-201606  경상남도  거제시  일반용   17553  247894357
109  201601-201606  경상남도  거창군  일반용    4936   51315304
110  201601-201606  경상남도  고성군  일반용    4625   50348204
111  201601-201606  경상남도  김해시  일반용   28860  456139221
112  201601-201606  경상남도  남해군  일반용    4681   48085662
113  201601-201606  경상남도  밀양시  일반용    9077   89989990
114  201601-201606  경상남도  사천시  일반용    9160  110996106
115  201601-201606  경상남도  산청군  일반용    3419   31536305
116  201601-201606  경상남도  양산시  일반용   17023  269942792
117  201601-201606  경상남도  의령군  일반용    2464   21958743
118  201601-201606  경상남도  진주시  일반용   24620  316356569
119  201601-201606  경상남도  창녕군  일반용    5362   64581042
120  201601-201606  경상남도  창원시  일반용   56279  971960080
121  201601-201606  경상남도  통영시  일반용   10828  147330117
122  201601-201606  경상남도  하동군  일반용    4219   41251650
123  201601-201606  경상남도  함안군  일반용    5279   60208674
124  201601-201606  경상남도  함양군  일반용    3602   30678026
125  201601-201606  경상남도  합천군  일반용    3885   39113848

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201601-201606  경상남도  거제시  일반용   17553   247894357
108  201601-201606  경상남도  거제시   합계   20192  1158652921
109  201601-201606  경상남도  거창군  일반용    4936    51315304
109  201601-201606  경상남도  거창군   합계    9097   220923443
110  201601-201606  경상남도  고성군  일반용    4625    50348204
110  201601-201606  경상남도  고성군   합계    8635   317480364
111  201601-201606  경상남도  김해시   합계   32305  2630478521
111  201601-201606  경상남도  김해시  일반용   28860   456139221
112  201601-201606  경상남도  남해군   합계    8144   132183371
112  201601-201606  경상남도  남해군  일반용    4681    48085662
113  201601-201606  경상남도  밀양시  일반용    9077    89989990
113  201601-201606  경상남도  밀양시   합계   16240   639008339
114  201601-201606  경상남도  사천시   합계   12243   653683469
114  201601-201606  경상남도  사천시  일반용    9160   110996106
115  201601-201606  경상남도  산청군  일반용    3419    31536305
115  201601-201606  경상남도  산청군   합계    6794   158829678
116  201601-201606  경상남도  양산시  일반용   17023   269942792
116  201601-201606  경상남도  양산시   합계   18549  1761399670
117  201601-201606  경상남도  의령군  일반용    2464    21958743
117  201601-201606  경상남도  의령군   합계    5587   207836264
118  201601-201606  경상남도  진주시   합계   30980  1372718384
118  201601-201606  경상남도  진주시  일반용   24620   316356569
119  201601-201606  경상남도  창녕군   합계    9912   493431202
119  201601-201606  경상남도  창녕군  일반용    5362    64581042
120  201601-201606  경상남도  창원시  일반용   56279   971960080
120  201601-201606  경상남도  창원시   합계   75688  5453071814
121  201601-201606  경상남도  통영시   합계   13270   608644617
121  201601-201606  경상남도  통영시  일반용   10828   147330117
122  201601-201606  경상남도  하동군   합계    8788   171251971
122  201601-201606  경상남도  하동군  일반용    4219    41251650
123  201601-201606  경상남도  함안군   합계    8785  1328739751
123  201601-201606  경상남도  함안군  일반용    5279    60208674
124  201601-201606  경상남도  함양군   합계    6761   126292058
124  201601-201606  경상남도  함양군  일반용    3602    30678026
125  201601-201606  경상남도  합천군  일반용    3885    39113848
125  201601-201606  경상남도  합천군   합계    8538   196653676

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[247894357,
 51315304,
 50348204,
 456139221,
 48085662,
 89989990,
 110996106,
 31536305,
 269942792,
 21958743,
 316356569,
 64581042,
 971960080,
 147330117,
 41251650,
 60208674,
 30678026,
 39113848]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1158652921,
 220923443,
 317480364,
 2630478521,
 132183371,
 639008339,
 653683469,
 158829678,
 1761399670,
 207836264,
 1372718384,
 493431202,
 5453071814,
 608644617,
 171251971,
 1328739751,
 126292058,
 196653676]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[21.4, 23.23, 15.86, 17.34, 36.38, 14.08, 16.98, 19.86, 15.33, 10.57, 23.05, 13.09, 17.82, 24.21, 24.09, 4.53, 24.29, 19.89]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    21
1    23
2    16
3    17
4    36
5    14
6    17
7    20
8    15
9    11
10   23
11   13
12   18
13   24
14   24
15    5
16   24
17   20
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  21
1   거창군  일반용  23
2   고성군  일반용  16
3   김해시  일반용  17
4   남해군  일반용  36
5   밀양시  일반용  14
6   사천시  일반용  17
7   산청군  일반용  20
8   양산시  일반용  15
9   의령군  일반용  11
10  진주시  일반용  23
11  창녕군  일반용  13
12  창원시  일반용  18
13  통영시  일반용  24
14  하동군  일반용  24
15  함안군  일반용   5
16  함양군  일반용  24
17  합천군  일반용  20

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201601-201606  경상남도  거제시  일반용   17553   247894357  21
1   201601-201606  경상남도  거제시   합계   20192  1158652921 NaN
2   201601-201606  경상남도  거창군  일반용    4936    51315304  23
3   201601-201606  경상남도  거창군   합계    9097   220923443 NaN
4   201601-201606  경상남도  고성군  일반용    4625    50348204  16
5   201601-201606  경상남도  고성군   합계    8635   317480364 NaN
7   201601-201606  경상남도  김해시  일반용   28860   456139221  17
6   201601-201606  경상남도  김해시   합계   32305  2630478521 NaN
9   201601-201606  경상남도  남해군  일반용    4681    48085662  36
8   201601-201606  경상남도  남해군   합계    8144   132183371 NaN
10  201601-201606  경상남도  밀양시  일반용    9077    89989990  14
11  201601-201606  경상남도  밀양시   합계   16240   639008339 NaN
13  201601-201606  경상남도  사천시  일반용    9160   110996106  17
12  201601-201606  경상남도  사천시   합계   12243   653683469 NaN
14  201601-201606  경상남도  산청군  일반용    3419    31536305  20
15  201601-201606  경상남도  산청군   합계    6794   158829678 NaN
16  201601-201606  경상남도  양산시  일반용   17023   269942792  15
17  201601-201606  경상남도  양산시   합계   18549  1761399670 NaN
18  201601-201606  경상남도  의령군  일반용    2464    21958743  11
19  201601-201606  경상남도  의령군   합계    5587   207836264 NaN
21  201601-201606  경상남도  진주시  일반용   24620   316356569  23
20  201601-201606  경상남도  진주시   합계   30980  1372718384 NaN
23  201601-201606  경상남도  창녕군  일반용    5362    64581042  13
22  201601-201606  경상남도  창녕군   합계    9912   493431202 NaN
24  201601-201606  경상남도  창원시  일반용   56279   971960080  18
25  201601-201606  경상남도  창원시   합계   75688  5453071814 NaN
27  201601-201606  경상남도  통영시  일반용   10828   147330117  24
26  201601-201606  경상남도  통영시   합계   13270   608644617 NaN
29  201601-201606  경상남도  하동군  일반용    4219    41251650  24
28  201601-201606  경상남도  하동군   합계    8788   171251971 NaN
31  201601-201606  경상남도  함안군  일반용    5279    60208674   5
30  201601-201606  경상남도  함안군   합계    8785  1328739751 NaN
33  201601-201606  경상남도  함양군  일반용    3602    30678026  24
32  201601-201606  경상남도  함양군   합계    6761   126292058 NaN
34  201601-201606  경상남도  합천군  일반용    3885    39113848  20
35  201601-201606  경상남도  합천군   합계    8538   196653676 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1601-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)