In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('대전광역시_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 대전광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,대전광역시,전체(시 / 군 / 구),주택용,"401,463","178,051,055","23,053,927,420",129.5
4,201501,대전광역시,전체(시 / 군 / 구),일반용,"75,968","313,620,417","41,443,575,955",132.1
...,...,...,...,...,...,...,...,...
283,201506,대전광역시,중구,산업용,576,"2,943,077","390,358,080",132.6
284,201506,대전광역시,중구,심 야,"3,976","2,212,747","128,921,016",58.3
285,201506,대전광역시,중구,일반용,"15,659","41,075,132","5,644,334,091",137.4
286,201506,대전광역시,중구,주택용,"70,518","25,055,718","2,817,251,050",112.4
287,201506,대전광역시,중구,합계,"98,888","73,866,810","9,302,456,587",125.9

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,대전광역시,전체(시 / 군 / 구),주택용,"401,463","178,051,055","23,053,927,420",129.5
4,201501,대전광역시,전체(시 / 군 / 구),일반용,"75,968","313,620,417","41,443,575,955",132.1
5,201501,대전광역시,전체(시 / 군 / 구),교육용,605,"40,004,040","4,167,626,524",104.2
6,201501,대전광역시,전체(시 / 군 / 구),산업용,"5,183","286,480,493","33,712,806,392",117.7
...,...,...,...,...,...,...,...,...
283,201506,대전광역시,중구,산업용,576,"2,943,077","390,358,080",132.6
284,201506,대전광역시,중구,심 야,"3,976","2,212,747","128,921,016",58.3
285,201506,대전광역시,중구,일반용,"15,659","41,075,132","5,644,334,091",137.4
286,201506,대전광역시,중구,주택용,"70,518","25,055,718","2,817,251,050",112.4
287,201506,대전광역시,중구,합계,"98,888","73,866,810","9,302,456,587",125.9

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,대전광역시,전체(시 / 군 / 구),주택용,"401,463","178,051,055","23,053,927,420",129.5
4,201501,대전광역시,전체(시 / 군 / 구),일반용,"75,968","313,620,417","41,443,575,955",132.1
5,201501,대전광역시,전체(시 / 군 / 구),교육용,605,"40,004,040","4,167,626,524",104.2
6,201501,대전광역시,전체(시 / 군 / 구),산업용,"5,183","286,480,493","33,712,806,392",117.7
7,201501,대전광역시,전체(시 / 군 / 구),농사용,"6,042","3,136,865","154,232,385",49.2
...,...,...,...,...,...,...,...,...
283,201506,대전광역시,중구,산업용,576,"2,943,077","390,358,080",132.6
284,201506,대전광역시,중구,심 야,"3,976","2,212,747","128,921,016",58.3
285,201506,대전광역시,중구,일반용,"15,659","41,075,132","5,644,334,091",137.4
286,201506,대전광역시,중구,주택용,"70,518","25,055,718","2,817,251,050",112.4
287,201506,대전광역시,중구,합계,"98,888","73,866,810","9,302,456,587",125.9

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,대전광역시,전체(시 / 군 / 구),주택용,"401,463","178,051,055","23,053,927,420",129.5
4,201501,대전광역시,전체(시 / 군 / 구),일반용,"75,968","313,620,417","41,443,575,955",132.1
5,201501,대전광역시,전체(시 / 군 / 구),교육용,605,"40,004,040","4,167,626,524",104.2
6,201501,대전광역시,전체(시 / 군 / 구),산업용,"5,183","286,480,493","33,712,806,392",117.7
7,201501,대전광역시,전체(시 / 군 / 구),농사용,"6,042","3,136,865","154,232,385",49.2
8,201501,대전광역시,전체(시 / 군 / 구),가로등,"14,938","7,373,809","788,988,613",107.0
9,201501,대전광역시,전체(시 / 군 / 구),심 야,"19,115","46,850,681","3,527,548,084",75.3
10,201502,대전광역시,전체(시 / 군 / 구),주택용,"402,169","175,089,542","22,307,093,630",127.4
11,201502,대전광역시,전체(시 / 군 / 구),일반용,"76,047","296,421,923","39,342,234,420",132.7
12,201502,대전광역시,전체(시 / 군 / 구),교육용,606,"35,148,521","3,748,312,387",106.6
13,201502,대전광역시,전체(시 / 군 / 구),산업용,"5,190","255,133,737","30,215,554,305",118.4
14,201502,대전광역시,전체(시 / 군 / 구),농사용,"6,039","3,216,070","156,554,033",48.7
15,201502,대전광역시,전체(시 / 군 / 구),가로등,"14,961","6,945,351","772,812,310",111.3
16,201502,대전광역시,전체(시 / 군 / 구),심 야,"19,079","43,770,067","3,295,232,514",75.3
17,201503,대전광역시,전체(시 / 군 / 구),주택용,"402,754","153,100,082","17,329,129,020",113.2
18,201503,대전광역시,전체(시 / 군 / 구),일반용,"75,981","259,577,013","31,635,351,842",121.9
19,201503,대전광역시,전체(시 / 군 / 구),교육용,606,"32,643,753","3,089,959,006",94.7
20,201503,대전광역시,전체(시 / 군 / 구),산업용,"5,201","272,432,238","26,468,625,217",97.2
21,201503,대전광역시,전체(시 / 군 / 구),농사용,"7,585","2,632,346","133,123,323",50.6
22,201503,대전광역시,전체(시 / 군 / 구),가로등,"14,976","6,179,774","704,196,221",114.0
23,201503,대전광역시,전체(시 / 군 / 구),심 야,"19,023","34,549,553","2,261,768,352",65.5
24,201504,대전광역시,전체(시 / 군 / 구),주택용,"403,415","160,480,902","18,668,347,787",116.3
25,201504,대전광역시,전체(시 / 군 / 구),일반용,"76,019","251,163,545","28,385,280,056",113.0
26,201504,대전광역시,전체(시 / 군 / 구),교육용,609,"30,251,651","2,754,215,880",91.0
27,201504,대전광역시,전체(시 / 군 / 구),산업용,"5,205","269,993,391","25,960,254,094",96.2
28,201504,대전광역시,전체(시 / 군 / 구),농사용,"6,115","2,140,487","113,581,698",53.1
29,201504,대전광역시,전체(시 / 군 / 구),가로등,"15,013","6,177,243","721,481,957",116.8
30,201504,대전광역시,전체(시 / 군 / 구),심 야,"18,986","26,329,642","1,439,472,978",54.7
31,201505,대전광역시,전체(시 / 군 / 구),주택용,"403,985","147,959,271","16,139,481,112",109.1
32,201505,대전광역시,전체(시 / 군 / 구),일반용,"76,047","235,508,303","27,081,767,470",115.0
33,201505,대전광역시,전체(시 / 군 / 구),교육용,609,"24,975,560","2,415,873,769",96.7
34,201505,대전광역시,전체(시 / 군 / 구),산업용,"5,199","266,672,390","25,334,806,294",95.0
35,201505,대전광역시,전체(시 / 군 / 구),농사용,"6,138","1,843,265","101,014,181",54.8
36,201505,대전광역시,전체(시 / 군 / 구),가로등,"15,029","5,842,392","699,990,900",119.8
37,201505,대전광역시,전체(시 / 군 / 구),심 야,"18,908","15,441,680","873,908,511",56.6
38,201506,대전광역시,전체(시 / 군 / 구),주택용,"404,854","151,011,959","16,803,403,904",111.3
39,201506,대전광역시,전체(시 / 군 / 구),일반용,"76,071","256,272,309","33,902,324,918",132.3
40,201506,대전광역시,전체(시 / 군 / 구),교육용,609,"27,822,630","3,194,615,584",114.8
41,201506,대전광역시,전체(시 / 군 / 구),산업용,"5,201","282,347,982","33,840,039,874",119.9
42,201506,대전광역시,전체(시 / 군 / 구),농사용,"6,194","2,150,277","112,436,071",52.3
43,201506,대전광역시,전체(시 / 군 / 구),가로등,"15,061","5,726,438","701,281,528",122.5
44,201506,대전광역시,전체(시 / 군 / 구),심 야,"18,837","10,156,030","618,625,055",60.9
45,합계,합계,합계,합계,"3,151,635","4,632,624,677","528,170,855,574",114

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_10136\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분  고객호수(호)      사용량(kWh)
4   201501  대전광역시  일반용  75,968   313,620,417
11  201502  대전광역시  일반용  76,047   296,421,923
18  201503  대전광역시  일반용  75,981   259,577,013
25  201504  대전광역시  일반용  76,019   251,163,545
32  201505  대전광역시  일반용  76,047   235,508,303
39  201506  대전광역시  일반용  76,071   256,272,309

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  대전광역시  대덕구  일반용  12,079   32,986,142
93   201502  대전광역시  대덕구  일반용  12,083   31,810,848
133  201503  대전광역시  대덕구  일반용  12,075   26,782,180
173  201504  대전광역시  대덕구  일반용  12,081   26,537,144
213  201505  대전광역시  대덕구  일반용  12,104   24,685,170
253  201506  대전광역시  대덕구  일반용  12,098   26,430,937
61   201501  대전광역시   동구  일반용  14,037   37,547,442
101  201502  대전광역시   동구  일반용  14,030   36,136,149
141  201503  대전광역시   동구  일반용  14,004   29,921,207
181  201504  대전광역시   동구  일반용  13,984   28,981,852
221  201505  대전광역시   동구  일반용  14,016   26,410,505
261  201506  대전광역시   동구  일반용  14,029   28,888,227
69   201501  대전광역시   서구  일반용  20,104   94,916,785
109  201502  대전광역시   서구  일반용  20,109   90,333,015
149  201503  대전광역시   서구  일반용  20,116   78,038,799
189  201504  대전광역시   서구  일반용  20,111   75,659,671
229  201505  대전광역시   서구  일반용  20,079   70,143,580
269  201506  대전광역시   서구  일반용  20,063   76,046,573
77   201501  대전광역시  유성구  일반용  14,017   98,453,136
117  201502  대전광역시  유성구  일반용  14,094   91,218,151
157  201503  대전광역시  유성구  일반용  14,079   84,388,719
197  201504  대전광역시  유성구  일반용  14,153   81,026,792
237  201505  대전광역시  유성구  일반용  14,178   77,737,463
277  201506  대전광역시  유성구  일반용  14,222   83,831,440
85   201501  대전광역시   중구  일반용  15,731   49,716,912
125  201502  대전광역시   중구  일반용  15,731   46,923,760
165  201503  대전광역시   중구  일반용  15,707   40,446,108
205  201504  대전광역시   중구  일반용  15,690   38,958,086
245  201505  대전광역시   중구  일반용  15,670   36,531,585
285  201506  대전광역시   중구  일반용  15,659   41,075,132

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'대전광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['대덕구', '동구', '서구', '유성구', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201501  대전광역시  대덕구   합계   76,954   251,591,502
95   201502  대전광역시  대덕구   합계   77,007   226,236,782
135  201503  대전광역시  대덕구   합계   77,181   233,428,958
175  201504  대전광역시  대덕구   합계   77,142   233,066,704
215  201505  대전광역시  대덕구   합계   77,208   224,421,042
255  201506  대전광역시  대덕구   합계   77,259   234,889,873
63   201501  대전광역시   동구   합계  108,416    93,360,458
103  201502  대전광역시   동구   합계  108,546    89,609,625
143  201503  대전광역시   동구   합계  108,832    75,951,208
183  201504  대전광역시   동구   합계  108,645    73,820,967
223  201505  대전광역시   동구   합계  108,692    64,167,213
263  201506  대전광역시   동구   합계  108,753    65,676,053
71   201501  대전광역시   서구   합계  148,953   177,443,507
111  201502  대전광역시   서구   합계  149,166   170,195,241
151  201503  대전광역시   서구   합계  149,717   147,426,351
191  201504  대전광역시   서구   합계  149,598   145,424,136
231  201505  대전광역시   서구   합계  149,733   131,989,589
271  201506  대전광역시   서구   합계  150,030   137,390,283
79   201501  대전광역시  유성구   합계   90,470   253,947,059
119  201502  대전광역시  유성구   합계   90,825   234,885,380
159  201503  대전광역시  유성구   합계   91,598   223,694,489
199  201504  대전광역시  유성구   합계   91,246   216,281,422
239  201505  대전광역시  유성구   합계   91,492   208,329,124
279  201506  대전광역시  유성구   합계   91,897   223,664,606
87   201501  대전광역시   중구   합계   98,521    99,174,834
127  201502  대전광역시   중구   합계   98,547    94,798,183
167  201503  대전광역시   중구   합계   98,798    80,613,753
207  201504  대전광역시   중구   합계   98,731    77,943,632
247  201505  대전광역시   중구   합계   98,790    69,335,893
287  201506  대전광역시   중구   합계   98,888    73,866,810

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[251591502, 226236782, 233428958, 233066704, 224421042, 234889873]
[93360458, 89609625, 75951208, 73820967, 64167213, 65676053]
[177443507, 170195241, 147426351, 145424136, 131989589, 137390283]
[253947059, 234885380, 223694489, 216281422, 208329124, 223664606]
[99174834, 94798183, 80613753, 77943632, 69335893, 73866810]
대전광역시 지역별 합계 :  [1403634861, 462585524, 909869107, 1360802080, 495733105]
대전광역시 고객호수 평균:  [12854, 18107, 24922, 15209, 16452]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_10136\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10136\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10136\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10136\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10136\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0          201501  대전광역시  대덕구   합계   76,954   251,591,502
1          201502  대전광역시  대덕구   합계   77,007   226,236,782
2          201503  대전광역시  대덕구   합계   77,181   233,428,958
3          201504  대전광역시  대덕구   합계   77,142   233,066,704
4          201505  대전광역시  대덕구   합계   77,208   224,421,042
5          201506  대전광역시  대덕구   합계   77,259   234,889,873
6          201501  대전광역시   동구   합계  108,416    93,360,458
7          201502  대전광역시   동구   합계  108,546    89,609,625
8          201503  대전광역시   동구   합계  108,832    75,951,208
9          201504  대전광역시   동구   합계  108,645    73,820,967
10         201505  대전광역시   동구   합계  108,692    64,167,213
11         201506  대전광역시   동구   합계  108,753    65,676,053
12         201501  대전광역시   서구   합계  148,953   177,443,507
13         201502  대전광역시   서구   합계  149,166   170,195,241
14         201503  대전광역시   서구   합계  149,717   147,426,351
15         201504  대전광역시   서구   합계  149,598   145,424,136
16         201505  대전광역시   서구   합계  149,733   131,989,589
17         201506  대전광역시   서구   합계  150,030   137,390,283
18         201501  대전광역시  유성구   합계   90,470   253,947,059
19         201502  대전광역시  유성구   합계   90,825   234,885,380
20         201503  대전광역시  유성구   합계   91,598   223,694,489
21         201504  대전광역시  유성구   합계   91,246   216,281,422
22         201505  대전광역시  유성구   합계   91,492   208,329,124
23         201506  대전광역시  유성구   합계   91,897   223,664,606
24         201501  대전광역시   중구   합계   98,521    99,174,834
25         201502  대전광역시   중구   합계   98,547    94,798,183
26         201503  대전광역시   중구   합계   98,798    80,613,753
27         201504  대전광역시   중구   합계   98,731    77,943,632
28         201505  대전광역시   중구   합계   98,790    69,335,893
29         201506  대전광역시   중구   합계   98,888    73,866,810
30  201501-201506  대전광역시  대덕구   합계     12854    1403634861
31  201501-201506  대전광역시   동구   합계     18107     462585524
32  201501-201506  대전광역시   서구   합계     24922     909869107
33  201501-201506  대전광역시  유성구   합계     15209    1360802080
34  201501-201506  대전광역시   중구   합계     16452     495733105

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
30  201501-201506  대전광역시  대덕구   합계   12854  1403634861
31  201501-201506  대전광역시   동구   합계   18107   462585524
32  201501-201506  대전광역시   서구   합계   24922   909869107
33  201501-201506  대전광역시  유성구   합계   15209  1360802080
34  201501-201506  대전광역시   중구   합계   16452   495733105

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  대전광역시  대덕구  일반용  12,079   32,986,142
93   201502  대전광역시  대덕구  일반용  12,083   31,810,848
133  201503  대전광역시  대덕구  일반용  12,075   26,782,180
173  201504  대전광역시  대덕구  일반용  12,081   26,537,144
213  201505  대전광역시  대덕구  일반용  12,104   24,685,170
253  201506  대전광역시  대덕구  일반용  12,098   26,430,937
61   201501  대전광역시   동구  일반용  14,037   37,547,442
101  201502  대전광역시   동구  일반용  14,030   36,136,149
141  201503  대전광역시   동구  일반용  14,004   29,921,207
181  201504  대전광역시   동구  일반용  13,984   28,981,852
221  201505  대전광역시   동구  일반용  14,016   26,410,505
261  201506  대전광역시   동구  일반용  14,029   28,888,227
69   201501  대전광역시   서구  일반용  20,104   94,916,785
109  201502  대전광역시   서구  일반용  20,109   90,333,015
149  201503  대전광역시   서구  일반용  20,116   78,038,799
189  201504  대전광역시   서구  일반용  20,111   75,659,671
229  201505  대전광역시   서구  일반용  20,079   70,143,580
269  201506  대전광역시   서구  일반용  20,063   76,046,573
77   201501  대전광역시  유성구  일반용  14,017   98,453,136
117  201502  대전광역시  유성구  일반용  14,094   91,218,151
157  201503  대전광역시  유성구  일반용  14,079   84,388,719
197  201504  대전광역시  유성구  일반용  14,153   81,026,792
237  201505  대전광역시  유성구  일반용  14,178   77,737,463
277  201506  대전광역시  유성구  일반용  14,222   83,831,440
85   201501  대전광역시   중구  일반용  15,731   49,716,912
125  201502  대전광역시   중구  일반용  15,731   46,923,760
165  201503  대전광역시   중구  일반용  15,707   40,446,108
205  201504  대전광역시   중구  일반용  15,690   38,958,086
245  201505  대전광역시   중구  일반용  15,670   36,531,585
285  201506  대전광역시   중구  일반용  15,659   41,075,132

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[32986142, 31810848, 26782180, 26537144, 24685170, 26430937]
[37547442, 36136149, 29921207, 28981852, 26410505, 28888227]
[94916785, 90333015, 78038799, 75659671, 70143580, 76046573]
[98453136, 91218151, 84388719, 81026792, 77737463, 83831440]
[49716912, 46923760, 40446108, 38958086, 36531585, 41075132]
대전광역시 지역별 일반용 합계 :  [169232421, 187885382, 485138423, 516655701, 253651583]
대전광역시 고객호수 평균:  [12086, 14016, 20097, 14123, 15698]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_10136\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10136\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10136\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10136\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10136\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201501  대전광역시  대덕구  일반용  12,079   32,986,142
1          201502  대전광역시  대덕구  일반용  12,083   31,810,848
2          201503  대전광역시  대덕구  일반용  12,075   26,782,180
3          201504  대전광역시  대덕구  일반용  12,081   26,537,144
4          201505  대전광역시  대덕구  일반용  12,104   24,685,170
5          201506  대전광역시  대덕구  일반용  12,098   26,430,937
6          201501  대전광역시   동구  일반용  14,037   37,547,442
7          201502  대전광역시   동구  일반용  14,030   36,136,149
8          201503  대전광역시   동구  일반용  14,004   29,921,207
9          201504  대전광역시   동구  일반용  13,984   28,981,852
10         201505  대전광역시   동구  일반용  14,016   26,410,505
11         201506  대전광역시   동구  일반용  14,029   28,888,227
12         201501  대전광역시   서구  일반용  20,104   94,916,785
13         201502  대전광역시   서구  일반용  20,109   90,333,015
14         201503  대전광역시   서구  일반용  20,116   78,038,799
15         201504  대전광역시   서구  일반용  20,111   75,659,671
16         201505  대전광역시   서구  일반용  20,079   70,143,580
17         201506  대전광역시   서구  일반용  20,063   76,046,573
18         201501  대전광역시  유성구  일반용  14,017   98,453,136
19         201502  대전광역시  유성구  일반용  14,094   91,218,151
20         201503  대전광역시  유성구  일반용  14,079   84,388,719
21         201504  대전광역시  유성구  일반용  14,153   81,026,792
22         201505  대전광역시  유성구  일반용  14,178   77,737,463
23         201506  대전광역시  유성구  일반용  14,222   83,831,440
24         201501  대전광역시   중구  일반용  15,731   49,716,912
25         201502  대전광역시   중구  일반용  15,731   46,923,760
26         201503  대전광역시   중구  일반용  15,707   40,446,108
27         201504  대전광역시   중구  일반용  15,690   38,958,086
28         201505  대전광역시   중구  일반용  15,670   36,531,585
29         201506  대전광역시   중구  일반용  15,659   41,075,132
30  201501-201506  대전광역시  대덕구  일반용    12086    169232421
31  201501-201506  대전광역시   동구  일반용    14016    187885382
32  201501-201506  대전광역시   서구  일반용    20097    485138423
33  201501-201506  대전광역시  유성구  일반용    14123    516655701
34  201501-201506  대전광역시   중구  일반용    15698    253651583

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
30  201501-201506  대전광역시  대덕구  일반용   12086  169232421
31  201501-201506  대전광역시   동구  일반용   14016  187885382
32  201501-201506  대전광역시   서구  일반용   20097  485138423
33  201501-201506  대전광역시  유성구  일반용   14123  516655701
34  201501-201506  대전광역시   중구  일반용   15698  253651583

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
30  201501-201506  대전광역시  대덕구  일반용   12086   169232421
30  201501-201506  대전광역시  대덕구   합계   12854  1403634861
31  201501-201506  대전광역시   동구  일반용   14016   187885382
31  201501-201506  대전광역시   동구   합계   18107   462585524
32  201501-201506  대전광역시   서구  일반용   20097   485138423
32  201501-201506  대전광역시   서구   합계   24922   909869107
33  201501-201506  대전광역시  유성구  일반용   14123   516655701
33  201501-201506  대전광역시  유성구   합계   15209  1360802080
34  201501-201506  대전광역시   중구  일반용   15698   253651583
34  201501-201506  대전광역시   중구   합계   16452   495733105

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[169232421, 187885382, 485138423, 516655701, 253651583]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1403634861, 462585524, 909869107, 1360802080, 495733105]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[12.06, 40.62, 53.32, 37.97, 51.17]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   12
1   41
2   53
3   38
4   51
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  대덕구  일반용  12
1   동구  일반용  41
2   서구  일반용  53
3  유성구  일반용  38
4   중구  일반용  51

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201501-201506  대전광역시  대덕구  일반용   12086   169232421  12
1  201501-201506  대전광역시  대덕구   합계   12854  1403634861 NaN
2  201501-201506  대전광역시   동구  일반용   14016   187885382  41
3  201501-201506  대전광역시   동구   합계   18107   462585524 NaN
4  201501-201506  대전광역시   서구  일반용   20097   485138423  53
5  201501-201506  대전광역시   서구   합계   24922   909869107 NaN
6  201501-201506  대전광역시  유성구  일반용   14123   516655701  38
7  201501-201506  대전광역시  유성구   합계   15209  1360802080 NaN
8  201501-201506  대전광역시   중구  일반용   15698   253651583  51
9  201501-201506  대전광역시   중구   합계   16452   495733105 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)