In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상북도_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상북도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경상북도,전체(시 / 군 / 구),주택용,"1,080,072","254,852,271","27,361,440,973",107.4
4,201507,경상북도,전체(시 / 군 / 구),일반용,"203,647","385,587,087","59,545,884,047",154.4
...,...,...,...,...,...,...,...,...
1147,201512,경상북도,포항시,산업용,"2,683","839,993,330","89,713,874,846",106.8
1148,201512,경상북도,포항시,심 야,"4,858","9,177,678","689,595,225",75.1
1149,201512,경상북도,포항시,일반용,"37,913","79,161,709","11,153,227,066",140.9
1150,201512,경상북도,포항시,주택용,"178,543","55,674,430","6,740,524,418",121.1
1151,201512,경상북도,포항시,합계,"251,756","1,014,500,824","110,862,309,857",109.3

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경상북도,전체(시 / 군 / 구),주택용,"1,080,072","254,852,271","27,361,440,973",107.4
4,201507,경상북도,전체(시 / 군 / 구),일반용,"203,647","385,587,087","59,545,884,047",154.4
5,201507,경상북도,전체(시 / 군 / 구),교육용,"1,463","43,330,955","5,510,221,990",127.2
6,201507,경상북도,전체(시 / 군 / 구),산업용,"30,301","2,730,896,270","318,549,020,664",116.6
...,...,...,...,...,...,...,...,...
1147,201512,경상북도,포항시,산업용,"2,683","839,993,330","89,713,874,846",106.8
1148,201512,경상북도,포항시,심 야,"4,858","9,177,678","689,595,225",75.1
1149,201512,경상북도,포항시,일반용,"37,913","79,161,709","11,153,227,066",140.9
1150,201512,경상북도,포항시,주택용,"178,543","55,674,430","6,740,524,418",121.1
1151,201512,경상북도,포항시,합계,"251,756","1,014,500,824","110,862,309,857",109.3

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경상북도,전체(시 / 군 / 구),주택용,"1,080,072","254,852,271","27,361,440,973",107.4
4,201507,경상북도,전체(시 / 군 / 구),일반용,"203,647","385,587,087","59,545,884,047",154.4
5,201507,경상북도,전체(시 / 군 / 구),교육용,"1,463","43,330,955","5,510,221,990",127.2
6,201507,경상북도,전체(시 / 군 / 구),산업용,"30,301","2,730,896,270","318,549,020,664",116.6
7,201507,경상북도,전체(시 / 군 / 구),농사용,"297,646","137,709,349","6,717,674,336",48.8
...,...,...,...,...,...,...,...,...
1147,201512,경상북도,포항시,산업용,"2,683","839,993,330","89,713,874,846",106.8
1148,201512,경상북도,포항시,심 야,"4,858","9,177,678","689,595,225",75.1
1149,201512,경상북도,포항시,일반용,"37,913","79,161,709","11,153,227,066",140.9
1150,201512,경상북도,포항시,주택용,"178,543","55,674,430","6,740,524,418",121.1
1151,201512,경상북도,포항시,합계,"251,756","1,014,500,824","110,862,309,857",109.3

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,경상북도,전체(시 / 군 / 구),주택용,"1,080,072","254,852,271","27,361,440,973",107.4
4,201507,경상북도,전체(시 / 군 / 구),일반용,"203,647","385,587,087","59,545,884,047",154.4
5,201507,경상북도,전체(시 / 군 / 구),교육용,"1,463","43,330,955","5,510,221,990",127.2
6,201507,경상북도,전체(시 / 군 / 구),산업용,"30,301","2,730,896,270","318,549,020,664",116.6
7,201507,경상북도,전체(시 / 군 / 구),농사용,"297,646","137,709,349","6,717,674,336",48.8
8,201507,경상북도,전체(시 / 군 / 구),가로등,"163,176","18,808,720","2,349,630,973",124.9
9,201507,경상북도,전체(시 / 군 / 구),심 야,"81,978","35,846,556","2,026,817,958",56.5
10,201508,경상북도,전체(시 / 군 / 구),주택용,"1,082,609","323,242,830","41,685,891,296",129.0
11,201508,경상북도,전체(시 / 군 / 구),일반용,"204,293","470,801,049","68,496,708,992",145.5
12,201508,경상북도,전체(시 / 군 / 구),교육용,"1,467","42,281,490","5,407,098,102",127.9
13,201508,경상북도,전체(시 / 군 / 구),산업용,"30,365","2,609,251,162","297,910,294,110",114.2
14,201508,경상북도,전체(시 / 군 / 구),농사용,"300,166","184,785,241","8,611,057,730",46.6
15,201508,경상북도,전체(시 / 군 / 구),가로등,"166,214","20,199,117","2,399,444,894",118.8
16,201508,경상북도,전체(시 / 군 / 구),심 야,"81,827","30,184,378","1,747,477,588",57.9
17,201509,경상북도,전체(시 / 군 / 구),주택용,"1,085,834","273,344,174","30,956,325,725",113.3
18,201509,경상북도,전체(시 / 군 / 구),일반용,"204,701","405,841,787","54,601,324,008",134.5
19,201509,경상북도,전체(시 / 군 / 구),교육용,"1,468","44,490,694","4,584,252,613",103.0
20,201509,경상북도,전체(시 / 군 / 구),산업용,"30,427","2,653,946,690","249,186,189,424",93.9
21,201509,경상북도,전체(시 / 군 / 구),농사용,"302,911","183,855,927","8,652,924,838",47.1
22,201509,경상북도,전체(시 / 군 / 구),가로등,"166,630","21,195,286","2,423,903,323",114.4
23,201509,경상북도,전체(시 / 군 / 구),심 야,"81,686","31,693,211","1,807,652,617",57.0
24,201510,경상북도,전체(시 / 군 / 구),주택용,"1,088,411","252,582,695","26,494,872,818",104.9
25,201510,경상북도,전체(시 / 군 / 구),일반용,"204,928","352,760,725","42,894,958,630",121.6
26,201510,경상북도,전체(시 / 군 / 구),교육용,"1,467","40,621,348","3,958,540,598",97.4
27,201510,경상북도,전체(시 / 군 / 구),산업용,"30,513","2,760,283,057","250,202,500,659",90.6
28,201510,경상북도,전체(시 / 군 / 구),농사용,"303,903","139,607,197","6,997,677,971",50.1
29,201510,경상북도,전체(시 / 군 / 구),가로등,"167,118","23,240,576","2,490,503,787",107.2
30,201510,경상북도,전체(시 / 군 / 구),심 야,"81,585","53,401,249","2,934,984,875",55.0
31,201511,경상북도,전체(시 / 군 / 구),주택용,"1,091,328","274,318,115","31,844,337,949",116.1
32,201511,경상북도,전체(시 / 군 / 구),일반용,"205,464","380,188,830","50,105,741,168",131.8
33,201511,경상북도,전체(시 / 군 / 구),교육용,"1,471","47,984,983","5,208,412,527",108.5
34,201511,경상북도,전체(시 / 군 / 구),산업용,"30,615","2,587,860,746","289,662,880,868",111.9
35,201511,경상북도,전체(시 / 군 / 구),농사용,"372,004","189,338,449","8,354,285,565",44.1
36,201511,경상북도,전체(시 / 군 / 구),가로등,"167,549","24,727,481","2,585,948,161",104.6
37,201511,경상북도,전체(시 / 군 / 구),심 야,"81,537","99,256,225","6,313,474,361",63.6
38,201512,경상북도,전체(시 / 군 / 구),주택용,"1,094,463","284,858,010","34,137,774,030",119.8
39,201512,경상북도,전체(시 / 군 / 구),일반용,"206,221","430,284,467","60,109,680,671",139.7
40,201512,경상북도,전체(시 / 군 / 구),교육용,"1,477","60,240,196","6,406,435,745",106.3
41,201512,경상북도,전체(시 / 군 / 구),산업용,"30,698","2,693,426,798","304,626,396,188",113.1
42,201512,경상북도,전체(시 / 군 / 구),농사용,"302,357","149,370,849","7,422,519,776",49.7
43,201512,경상북도,전체(시 / 군 / 구),가로등,"168,112","26,672,130","2,697,214,061",101.1
44,201512,경상북도,전체(시 / 군 / 구),심 야,"81,437","152,424,043","11,463,414,654",75.2
45,합계,합계,합계,합계,"11,311,539","21,925,592,413","2,357,443,791,263",107.5

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_2948\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201507  경상북도  일반용  203,647   385,587,087
11  201508  경상북도  일반용  204,293   470,801,049
18  201509  경상북도  일반용  204,701   405,841,787
25  201510  경상북도  일반용  204,928   352,760,725
32  201511  경상북도  일반용  205,464   380,188,830
39  201512  경상북도  일반용  206,221   430,284,467

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53    201507  경상북도  경산시  일반용  15,895   32,736,092
237   201508  경상북도  경산시  일반용  15,947   39,310,862
421   201509  경상북도  경산시  일반용  15,983   34,717,193
605   201510  경상북도  경산시  일반용  16,000   29,884,899
789   201511  경상북도  경산시  일반용  16,095   31,021,496
...      ...   ...  ...  ...      ...          ...
413   201508  경상북도  포항시  일반용  37,655   93,109,019
597   201509  경상북도  포항시  일반용  37,668   79,415,867
781   201510  경상북도  포항시  일반용  37,703   67,009,727
965   201511  경상북도  포항시  일반용  37,760   70,155,505
1149  201512  경상북도  포항시  일반용  37,913   79,161,709

[138 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상북도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['경산시',
 '경주시',
 '고령군',
 '구미시',
 '군위군',
 '김천시',
 '문경시',
 '봉화군',
 '상주시',
 '성주군',
 '안동시',
 '영덕군',
 '영양군',
 '영주시',
 '영천시',
 '예천군',
 '울릉군',
 '울진군',
 '의성군',
 '청도군',
 '청송군',
 '칠곡군',
 '포항시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월    시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55    201507  경상북도  경산시   합계  145,665     211,454,722
239   201508  경상북도  경산시   합계  146,011     218,395,420
423   201509  경상북도  경산시   합계  146,427     214,961,844
607   201510  경상북도  경산시   합계  146,834     203,162,125
791   201511  경상북도  경산시   합계  147,303     218,609,887
...      ...   ...  ...  ...       ...             ...
415   201508  경상북도  포항시   합계  249,685   1,007,963,751
599   201509  경상북도  포항시   합계  250,209   1,011,809,281
783   201510  경상북도  포항시   합계  250,808   1,117,016,758
967   201511  경상북도  포항시   합계  255,086     925,179,699
1151  201512  경상북도  포항시   합계  251,756   1,014,500,824

[138 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[211454722, 218395420, 214961844, 203162125, 218609887, 234059866]
[329639474, 307840303, 318883802, 299420960, 334094527, 338440191]
[98508916, 90941370, 93798263, 93930794, 95680981, 102994553]
[860798812, 886680511, 815687447, 796300933, 781669039, 803408537]
[24062884, 25751787, 24995985, 23519122, 26202591, 27557205]
[163530419, 173825261, 164925831, 161267859, 171405281, 179187999]
[41520074, 45304860, 44297380, 42518931, 47031158, 52240056]
[146527543, 149607524, 161781465, 164097221, 162794812, 167227551]
[48539460, 56983957, 52719049, 49121451, 68349673, 65186691]
[70632515, 69653606, 71135078, 69019937, 77506941, 82322284]
[73635745, 85111299, 78359865, 72350667, 85302776, 92830297]
[18871739, 22653201, 21554558, 20569681, 24036069, 25653658]
[6285322, 7475652, 10229040, 8858234, 9234227, 9943765]
[104682474, 110980728, 108391837, 110598543, 118083641, 126753778]
[114594199, 113891702, 114835892, 108331753, 119235815, 126782307]
[19663331, 24246850, 22297134, 19611301, 29607501, 26797663]
[4050102, 5056347, 4405764, 4361542, 4659861, 4840695]
[27610031, 31311976, 35196377, 30917424, 49420723, 45692027]
[30324669, 35404821, 32881748, 29385703, 34474791, 35317197]
[32928893, 37442195, 35839751, 34711136, 41723537, 45441277]
[11413029, 12861174, 13015612, 12576715, 14994072, 16756063]
[162066656, 161360972, 162364766, 150848057, 164377227, 173342009]
[1005690199, 1007963751, 1011809281, 1117016758, 925179699, 1014500824]
경상북도 지역별 합계 :  [1300643864, 1928319257, 575854877, 4944545279, 152089574, 1014142650, 272912459, 952036116, 340900281, 440270361, 487590649, 133338906, 52026240, 679491001, 697671668, 142223780, 27374311, 220148558, 197788929, 228086789, 81616665, 974359687, 6082160512]
경상북도 고객호수 평균:  [24445, 31465, 5008, 32868, 4695, 16878, 10081, 6821, 16100, 8144, 19736, 6707, 3970, 13250, 14046, 8998, 1277, 8453, 11291, 9018, 6089, 13004, 41854]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201507  경상북도  경산시   합계  145,665   211,454,722
1           201508  경상북도  경산시   합계  146,011   218,395,420
2           201509  경상북도  경산시   합계  146,427   214,961,844
3           201510  경상북도  경산시   합계  146,834   203,162,125
4           201511  경상북도  경산시   합계  147,303   218,609,887
..             ...   ...  ...  ...       ...           ...
156  201507-201512  경상북도  의성군   합계     11291     197788929
157  201507-201512  경상북도  청도군   합계      9018     228086789
158  201507-201512  경상북도  청송군   합계      6089      81616665
159  201507-201512  경상북도  칠곡군   합계     13004     974359687
160  201507-201512  경상북도  포항시   합계     41854    6082160512

[161 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
138  201507-201512  경상북도  경산시   합계   24445  1300643864
139  201507-201512  경상북도  경주시   합계   31465  1928319257
140  201507-201512  경상북도  고령군   합계    5008   575854877
141  201507-201512  경상북도  구미시   합계   32868  4944545279
142  201507-201512  경상북도  군위군   합계    4695   152089574
143  201507-201512  경상북도  김천시   합계   16878  1014142650
144  201507-201512  경상북도  문경시   합계   10081   272912459
145  201507-201512  경상북도  봉화군   합계    6821   952036116
146  201507-201512  경상북도  상주시   합계   16100   340900281
147  201507-201512  경상북도  성주군   합계    8144   440270361
148  201507-201512  경상북도  안동시   합계   19736   487590649
149  201507-201512  경상북도  영덕군   합계    6707   133338906
150  201507-201512  경상북도  영양군   합계    3970    52026240
151  201507-201512  경상북도  영주시   합계   13250   679491001
152  201507-201512  경상북도  영천시   합계   14046   697671668
153  201507-201512  경상북도  예천군   합계    8998   142223780
154  201507-201512  경상북도  울릉군   합계    1277    27374311
155  201507-201512  경상북도  울진군   합계    8453   220148558
156  201507-201512  경상북도  의성군   합계   11291   197788929
157  201507-201512  경상북도  청도군   합계    9018   228086789
158  201507-201512  경상북도  청송군   합계    6089    81616665
159  201507-201512  경상북도  칠곡군   합계   13004   974359687
160  201507-201512  경상북도  포항시   합계   41854  6082160512

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53    201507  경상북도  경산시  일반용  15,895   32,736,092
237   201508  경상북도  경산시  일반용  15,947   39,310,862
421   201509  경상북도  경산시  일반용  15,983   34,717,193
605   201510  경상북도  경산시  일반용  16,000   29,884,899
789   201511  경상북도  경산시  일반용  16,095   31,021,496
...      ...   ...  ...  ...      ...          ...
413   201508  경상북도  포항시  일반용  37,655   93,109,019
597   201509  경상북도  포항시  일반용  37,668   79,415,867
781   201510  경상북도  포항시  일반용  37,703   67,009,727
965   201511  경상북도  포항시  일반용  37,760   70,155,505
1149  201512  경상북도  포항시  일반용  37,913   79,161,709

[138 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[32736092, 39310862, 34717193, 29884899, 31021496, 34394898]
[48124363, 60710413, 50835553, 44228825, 47313299, 51924788]
[4147338, 5122082, 4463135, 3920552, 4244152, 4802546]
[56947913, 67678540, 58325817, 48656938, 51302841, 58254635]
[4089462, 4600796, 3777870, 3526090, 3761511, 4219177]
[18276045, 21588917, 19307915, 16933229, 18500425, 21510530]
[10642407, 12666491, 11197601, 10221865, 10901960, 12663808]
[3341176, 3976029, 3567413, 3306424, 3648763, 4055083]
[12328608, 14482974, 12368460, 11048221, 12190966, 14034432]
[5511007, 6898941, 5627303, 5038718, 5650587, 6473450]
[26077225, 31046205, 26642325, 23873802, 26099872, 30462813]
[7298106, 9727264, 8056159, 7357551, 8273004, 9335910]
[1752375, 2095995, 1946185, 1766705, 2015907, 2308423]
[13510729, 15843275, 13973775, 12426238, 13849539, 16153715]
[13236706, 16232467, 14080982, 12448102, 13679519, 15454713]
[5472466, 6482804, 5609223, 5061438, 5655699, 6585329]
[2348097, 3045645, 2568863, 2580304, 2828130, 2857569]
[10625996, 13118528, 11347679, 10628042, 12151761, 14449262]
[5241993, 6374569, 5536546, 4925850, 5613300, 6410960]
[5773463, 7103160, 6413508, 5589539, 6168057, 6779710]
[3416234, 4181837, 3633310, 3365066, 4090277, 4622697]
[21309920, 25404236, 22429105, 18962600, 21072260, 23368310]
[73379366, 93109019, 79415867, 67009727, 70155505, 79161709]
경상북도 지역별 일반용 합계 :  [202065440, 303137241, 26699805, 341166684, 23974906, 116117061, 68294132, 21894888, 76453661, 35200006, 164202242, 50047994, 11885590, 85757271, 85132489, 34866959, 16228608, 72321268, 34103218, 37827437, 23309421, 132546431, 462231193]
경상북도 고객호수 평균:  [16009, 23477, 2964, 26327, 2000, 9705, 6244, 2858, 7474, 3836, 12743, 4922, 1558, 9213, 7644, 3173, 1609, 5171, 4050, 3628, 2612, 9957, 37695]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2948\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201507  경상북도  경산시  일반용  15,895   32,736,092
1           201508  경상북도  경산시  일반용  15,947   39,310,862
2           201509  경상북도  경산시  일반용  15,983   34,717,193
3           201510  경상북도  경산시  일반용  16,000   29,884,899
4           201511  경상북도  경산시  일반용  16,095   31,021,496
..             ...   ...  ...  ...      ...          ...
156  201507-201512  경상북도  의성군  일반용     4050     34103218
157  201507-201512  경상북도  청도군  일반용     3628     37827437
158  201507-201512  경상북도  청송군  일반용     2612     23309421
159  201507-201512  경상북도  칠곡군  일반용     9957    132546431
160  201507-201512  경상북도  포항시  일반용    37695    462231193

[161 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
138  201507-201512  경상북도  경산시  일반용   16009  202065440
139  201507-201512  경상북도  경주시  일반용   23477  303137241
140  201507-201512  경상북도  고령군  일반용    2964   26699805
141  201507-201512  경상북도  구미시  일반용   26327  341166684
142  201507-201512  경상북도  군위군  일반용    2000   23974906
143  201507-201512  경상북도  김천시  일반용    9705  116117061
144  201507-201512  경상북도  문경시  일반용    6244   68294132
145  201507-201512  경상북도  봉화군  일반용    2858   21894888
146  201507-201512  경상북도  상주시  일반용    7474   76453661
147  201507-201512  경상북도  성주군  일반용    3836   35200006
148  201507-201512  경상북도  안동시  일반용   12743  164202242
149  201507-201512  경상북도  영덕군  일반용    4922   50047994
150  201507-201512  경상북도  영양군  일반용    1558   11885590
151  201507-201512  경상북도  영주시  일반용    9213   85757271
152  201507-201512  경상북도  영천시  일반용    7644   85132489
153  201507-201512  경상북도  예천군  일반용    3173   34866959
154  201507-201512  경상북도  울릉군  일반용    1609   16228608
155  201507-201512  경상북도  울진군  일반용    5171   72321268
156  201507-201512  경상북도  의성군  일반용    4050   34103218
157  201507-201512  경상북도  청도군  일반용    3628   37827437
158  201507-201512  경상북도  청송군  일반용    2612   23309421
159  201507-201512  경상북도  칠곡군  일반용    9957  132546431
160  201507-201512  경상북도  포항시  일반용   37695  462231193

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
138  201507-201512  경상북도  경산시  일반용   16009   202065440
138  201507-201512  경상북도  경산시   합계   24445  1300643864
139  201507-201512  경상북도  경주시  일반용   23477   303137241
139  201507-201512  경상북도  경주시   합계   31465  1928319257
140  201507-201512  경상북도  고령군  일반용    2964    26699805
140  201507-201512  경상북도  고령군   합계    5008   575854877
141  201507-201512  경상북도  구미시  일반용   26327   341166684
141  201507-201512  경상북도  구미시   합계   32868  4944545279
142  201507-201512  경상북도  군위군  일반용    2000    23974906
142  201507-201512  경상북도  군위군   합계    4695   152089574
143  201507-201512  경상북도  김천시  일반용    9705   116117061
143  201507-201512  경상북도  김천시   합계   16878  1014142650
144  201507-201512  경상북도  문경시  일반용    6244    68294132
144  201507-201512  경상북도  문경시   합계   10081   272912459
145  201507-201512  경상북도  봉화군  일반용    2858    21894888
145  201507-201512  경상북도  봉화군   합계    6821   952036116
146  201507-201512  경상북도  상주시   합계   16100   340900281
146  201507-201512  경상북도  상주시  일반용    7474    76453661
147  201507-201512  경상북도  성주군   합계    8144   440270361
147  201507-201512  경상북도  성주군  일반용    3836    35200006
148  201507-201512  경상북도  안동시   합계   19736   487590649
148  201507-201512  경상북도  안동시  일반용   12743   164202242
149  201507-201512  경상북도  영덕군   합계    6707   133338906
149  201507-201512  경상북도  영덕군  일반용    4922    50047994
150  201507-201512  경상북도  영양군   합계    3970    52026240
150  201507-201512  경상북도  영양군  일반용    1558    11885590
151  201507-201512  경상북도  영주시   합계   13250   679491001
151  201507-201512  경상북도  영주시  일반용    9213    85757271
152  201507-201512  경상북도  영천시  일반용    7644    85132489
152  201507-201512  경상북도  영천시   합계   14046   697671668
153  201507-201512  경상북도  예천군   합계    8998   142223780
153  201507-201512  경상북도  예천군  일반용    3173    34866959
154  201507-201512  경상북도  울릉군   합계    1277    27374311
154  201507-201512  경상북도  울릉군  일반용    1609    16228608
155  201507-201512  경상북도  울진군  일반용    5171    72321268
155  201507-201512  경상북도  울진군   합계    8453   220148558
156  201507-201512  경상북도  의성군   합계   11291   197788929
156  201507-201512  경상북도  의성군  일반용    4050    34103218
157  201507-201512  경상북도  청도군   합계    9018   228086789
157  201507-201512  경상북도  청도군  일반용    3628    37827437
158  201507-201512  경상북도  청송군   합계    6089    81616665
158  201507-201512  경상북도  청송군  일반용    2612    23309421
159  201507-201512  경상북도  칠곡군   합계   13004   974359687
159  201507-201512  경상북도  칠곡군  일반용    9957   132546431
160  201507-201512  경상북도  포항시  일반용   37695   462231193
160  201507-201512  경상북도  포항시   합계   41854  6082160512

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[202065440,
 303137241,
 26699805,
 341166684,
 23974906,
 116117061,
 68294132,
 21894888,
 76453661,
 35200006,
 164202242,
 50047994,
 11885590,
 85757271,
 85132489,
 34866959,
 16228608,
 72321268,
 34103218,
 37827437,
 23309421,
 132546431,
 462231193]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1300643864,
 1928319257,
 575854877,
 4944545279,
 152089574,
 1014142650,
 272912459,
 952036116,
 340900281,
 440270361,
 487590649,
 133338906,
 52026240,
 679491001,
 697671668,
 142223780,
 27374311,
 220148558,
 197788929,
 228086789,
 81616665,
 974359687,
 6082160512]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[15.54, 15.72, 4.64, 6.9, 15.76, 11.45, 25.02, 2.3, 22.43, 8.0, 33.68, 37.53, 22.85, 12.62, 12.2, 24.52, 59.28, 32.85, 17.24, 16.58, 28.56, 13.6, 7.6]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    16
1    16
2     5
3     7
4    16
5    11
6    25
7     2
8    22
9     8
10   34
11   38
12   23
13   13
14   12
15   25
16   59
17   33
18   17
19   17
20   29
21   14
22    8
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   경산시  일반용  16
1   경주시  일반용  16
2   고령군  일반용   5
3   구미시  일반용   7
4   군위군  일반용  16
5   김천시  일반용  11
6   문경시  일반용  25
7   봉화군  일반용   2
8   상주시  일반용  22
9   성주군  일반용   8
10  안동시  일반용  34
11  영덕군  일반용  38
12  영양군  일반용  23
13  영주시  일반용  13
14  영천시  일반용  12
15  예천군  일반용  25
16  울릉군  일반용  59
17  울진군  일반용  33
18  의성군  일반용  17
19  청도군  일반용  17
20  청송군  일반용  29
21  칠곡군  일반용  14
22  포항시  일반용   8

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201507-201512  경상북도  경산시  일반용   16009   202065440  16
1   201507-201512  경상북도  경산시   합계   24445  1300643864 NaN
2   201507-201512  경상북도  경주시  일반용   23477   303137241  16
3   201507-201512  경상북도  경주시   합계   31465  1928319257 NaN
4   201507-201512  경상북도  고령군  일반용    2964    26699805   5
5   201507-201512  경상북도  고령군   합계    5008   575854877 NaN
6   201507-201512  경상북도  구미시  일반용   26327   341166684   7
7   201507-201512  경상북도  구미시   합계   32868  4944545279 NaN
8   201507-201512  경상북도  군위군  일반용    2000    23974906  16
9   201507-201512  경상북도  군위군   합계    4695   152089574 NaN
10  201507-201512  경상북도  김천시  일반용    9705   116117061  11
11  201507-201512  경상북도  김천시   합계   16878  1014142650 NaN
12  201507-201512  경상북도  문경시  일반용    6244    68294132  25
13  201507-201512  경상북도  문경시   합계   10081   272912459 NaN
14  201507-201512  경상북도  봉화군  일반용    2858    21894888   2
15  201507-201512  경상북도  봉화군   합계    6821   952036116 NaN
17  201507-201512  경상북도  상주시  일반용    7474    76453661  22
16  201507-201512  경상북도  상주시   합계   16100   340900281 NaN
19  201507-201512  경상북도  성주군  일반용    3836    35200006   8
18  201507-201512  경상북도  성주군   합계    8144   440270361 NaN
21  201507-201512  경상북도  안동시  일반용   12743   164202242  34
20  201507-201512  경상북도  안동시   합계   19736   487590649 NaN
23  201507-201512  경상북도  영덕군  일반용    4922    50047994  38
22  201507-201512  경상북도  영덕군   합계    6707   133338906 NaN
25  201507-201512  경상북도  영양군  일반용    1558    11885590  23
24  201507-201512  경상북도  영양군   합계    3970    52026240 NaN
27  201507-201512  경상북도  영주시  일반용    9213    85757271  13
26  201507-201512  경상북도  영주시   합계   13250   679491001 NaN
28  201507-201512  경상북도  영천시  일반용    7644    85132489  12
29  201507-201512  경상북도  영천시   합계   14046   697671668 NaN
31  201507-201512  경상북도  예천군  일반용    3173    34866959  25
30  201507-201512  경상북도  예천군   합계    8998   142223780 NaN
33  201507-201512  경상북도  울릉군  일반용    1609    16228608  59
32  201507-201512  경상북도  울릉군   합계    1277    27374311 NaN
34  201507-201512  경상북도  울진군  일반용    5171    72321268  33
35  201507-201512  경상북도  울진군   합계    8453   220148558 NaN
37  201507-201512  경상북도  의성군  일반용    4050    34103218  17
36  201507-201512  경상북도  의성군   합계   11291   197788929 NaN
39  201507-201512  경상북도  청도군  일반용    3628    37827437  17
38  201507-201512  경상북도  청도군   합계    9018   228086789 NaN
41  201507-201512  경상북도  청송군  일반용    2612    23309421  29
40  201507-201512  경상북도  청송군   합계    6089    81616665 NaN
43  201507-201512  경상북도  칠곡군  일반용    9957   132546431  14
42  201507-201512  경상북도  칠곡군   합계   13004   974359687 NaN
44  201507-201512  경상북도  포항시  일반용   37695   462231193   8
45  201507-201512  경상북도  포항시   합계   41854  6082160512 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)