In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('제주특별자치도_계약종별 전력사용량 월별_14하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 제주특별자치도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 07 월 ~ 2014년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,제주특별자치도,전체(시 / 군 / 구),주택용,"216,017","52,128,400","6,122,398,994",117.4
4,201407,제주특별자치도,전체(시 / 군 / 구),일반용,"48,297","124,701,946","18,645,472,159",149.5
...,...,...,...,...,...,...,...,...
139,201412,제주특별자치도,제주시,산업용,"2,164","31,285,417","3,916,021,740",125.2
140,201412,제주특별자치도,제주시,심 야,"5,202","11,010,764","824,593,780",74.9
141,201412,제주특별자치도,제주시,일반용,"35,618","91,147,882","12,642,389,811",138.7
142,201412,제주특별자치도,제주시,주택용,"159,033","44,583,969","5,780,857,588",129.7
143,201412,제주특별자치도,제주시,합계,"228,649","224,403,119","25,953,474,474",115.7

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,제주특별자치도,전체(시 / 군 / 구),주택용,"216,017","52,128,400","6,122,398,994",117.4
4,201407,제주특별자치도,전체(시 / 군 / 구),일반용,"48,297","124,701,946","18,645,472,159",149.5
5,201407,제주특별자치도,전체(시 / 군 / 구),교육용,325,"8,776,736","1,167,888,855",133.1
6,201407,제주특별자치도,전체(시 / 군 / 구),산업용,"2,928","41,764,750","5,477,401,065",131.1
...,...,...,...,...,...,...,...,...
139,201412,제주특별자치도,제주시,산업용,"2,164","31,285,417","3,916,021,740",125.2
140,201412,제주특별자치도,제주시,심 야,"5,202","11,010,764","824,593,780",74.9
141,201412,제주특별자치도,제주시,일반용,"35,618","91,147,882","12,642,389,811",138.7
142,201412,제주특별자치도,제주시,주택용,"159,033","44,583,969","5,780,857,588",129.7
143,201412,제주특별자치도,제주시,합계,"228,649","224,403,119","25,953,474,474",115.7

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,제주특별자치도,전체(시 / 군 / 구),주택용,"216,017","52,128,400","6,122,398,994",117.4
4,201407,제주특별자치도,전체(시 / 군 / 구),일반용,"48,297","124,701,946","18,645,472,159",149.5
5,201407,제주특별자치도,전체(시 / 군 / 구),교육용,325,"8,776,736","1,167,888,855",133.1
6,201407,제주특별자치도,전체(시 / 군 / 구),산업용,"2,928","41,764,750","5,477,401,065",131.1
7,201407,제주특별자치도,전체(시 / 군 / 구),농사용,"39,886","92,155,557","4,380,070,554",47.5
...,...,...,...,...,...,...,...,...
139,201412,제주특별자치도,제주시,산업용,"2,164","31,285,417","3,916,021,740",125.2
140,201412,제주특별자치도,제주시,심 야,"5,202","11,010,764","824,593,780",74.9
141,201412,제주특별자치도,제주시,일반용,"35,618","91,147,882","12,642,389,811",138.7
142,201412,제주특별자치도,제주시,주택용,"159,033","44,583,969","5,780,857,588",129.7
143,201412,제주특별자치도,제주시,합계,"228,649","224,403,119","25,953,474,474",115.7

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,제주특별자치도,전체(시 / 군 / 구),주택용,"216,017","52,128,400","6,122,398,994",117.4
4,201407,제주특별자치도,전체(시 / 군 / 구),일반용,"48,297","124,701,946","18,645,472,159",149.5
5,201407,제주특별자치도,전체(시 / 군 / 구),교육용,325,"8,776,736","1,167,888,855",133.1
6,201407,제주특별자치도,전체(시 / 군 / 구),산업용,"2,928","41,764,750","5,477,401,065",131.1
7,201407,제주특별자치도,전체(시 / 군 / 구),농사용,"39,886","92,155,557","4,380,070,554",47.5
8,201407,제주특별자치도,전체(시 / 군 / 구),가로등,"18,087","3,305,676","427,970,210",129.5
9,201407,제주특별자치도,전체(시 / 군 / 구),심 야,"7,732","6,234,665","366,724,112",58.8
10,201408,제주특별자치도,전체(시 / 군 / 구),주택용,"216,515","61,298,570","8,373,414,536",136.6
11,201408,제주특별자치도,전체(시 / 군 / 구),일반용,"48,655","144,703,670","20,740,515,965",143.3
12,201408,제주특별자치도,전체(시 / 군 / 구),교육용,326,"9,647,150","1,226,861,072",127.2
13,201408,제주특별자치도,전체(시 / 군 / 구),산업용,"2,937","43,510,058","5,557,252,365",127.7
14,201408,제주특별자치도,전체(시 / 군 / 구),농사용,"40,020","95,450,009","4,508,724,399",47.2
15,201408,제주특별자치도,전체(시 / 군 / 구),가로등,"18,148","3,573,091","433,350,167",121.3
16,201408,제주특별자치도,전체(시 / 군 / 구),심 야,"7,723","5,883,357","356,583,640",60.6
17,201409,제주특별자치도,전체(시 / 군 / 구),주택용,"217,154","55,780,098","6,891,059,324",123.5
18,201409,제주특별자치도,전체(시 / 군 / 구),일반용,"48,793","130,340,375","16,601,557,712",127.4
19,201409,제주특별자치도,전체(시 / 군 / 구),교육용,326,"9,346,418","978,637,059",104.7
20,201409,제주특별자치도,전체(시 / 군 / 구),산업용,"2,955","40,783,844","4,586,960,277",112.5
21,201409,제주특별자치도,전체(시 / 군 / 구),농사용,"40,147","95,991,482","4,456,396,691",46.4
22,201409,제주특별자치도,전체(시 / 군 / 구),가로등,"18,243","3,866,264","446,297,424",115.4
23,201409,제주특별자치도,전체(시 / 군 / 구),심 야,"7,712","5,284,556","312,886,105",59.2
24,201410,제주특별자치도,전체(시 / 군 / 구),주택용,"217,805","50,173,618","5,634,037,584",112.3
25,201410,제주특별자치도,전체(시 / 군 / 구),일반용,"49,006","117,059,444","13,628,917,275",116.4
26,201410,제주특별자치도,전체(시 / 군 / 구),교육용,327,"8,399,080","828,399,271",98.6
27,201410,제주특별자치도,전체(시 / 군 / 구),산업용,"2,980","41,872,613","4,358,599,603",104.1
28,201410,제주특별자치도,전체(시 / 군 / 구),농사용,"40,292","90,805,694","4,169,315,833",45.9
29,201410,제주특별자치도,전체(시 / 군 / 구),가로등,"18,355","4,303,268","457,943,695",106.4
30,201410,제주특별자치도,전체(시 / 군 / 구),심 야,"7,710","5,546,924","315,768,253",56.9
31,201411,제주특별자치도,전체(시 / 군 / 구),주택용,"218,386","53,887,388","6,419,555,036",119.1
32,201411,제주특별자치도,전체(시 / 군 / 구),일반용,"49,318","117,545,312","15,475,391,264",131.7
33,201411,제주특별자치도,전체(시 / 군 / 구),교육용,328,"8,899,389","1,005,424,270",113.0
34,201411,제주특별자치도,전체(시 / 군 / 구),산업용,"3,037","43,165,662","5,176,965,779",119.9
35,201411,제주특별자치도,전체(시 / 군 / 구),농사용,"40,482","96,506,401","4,479,761,526",46.4
36,201411,제주특별자치도,전체(시 / 군 / 구),가로등,"18,452","4,652,468","481,062,206",103.4
37,201411,제주특별자치도,전체(시 / 군 / 구),심 야,"7,707","9,586,788","624,447,167",65.1
38,201412,제주특별자치도,전체(시 / 군 / 구),주택용,"219,082","58,875,661","7,621,366,520",129.4
39,201412,제주특별자치도,전체(시 / 군 / 구),일반용,"49,672","129,643,924","18,016,874,477",139.0
40,201412,제주특별자치도,전체(시 / 군 / 구),교육용,328,"11,078,578","1,246,938,333",112.6
41,201412,제주특별자치도,전체(시 / 군 / 구),산업용,"3,116","42,482,881","5,477,776,634",128.9
42,201412,제주특별자치도,전체(시 / 군 / 구),농사용,"40,646","105,306,512","4,943,194,276",46.9
43,201412,제주특별자치도,전체(시 / 군 / 구),가로등,"18,528","4,878,015","484,543,431",99.3
44,201412,제주특별자치도,전체(시 / 군 / 구),심 야,"7,700","15,259,498","1,144,411,423",75.0
45,합계,합계,합계,합계,"2,016,183","2,054,455,790","214,049,116,541",104.2

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_2716\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월       시구 계약구분  고객호수(호)      사용량(kWh)
4   201407  제주특별자치도  일반용  48,297   124,701,946
11  201408  제주특별자치도  일반용  48,655   144,703,670
18  201409  제주특별자치도  일반용  48,793   130,340,375
25  201410  제주특별자치도  일반용  49,006   117,059,444
32  201411  제주특별자치도  일반용  49,318   117,545,312
39  201412  제주특별자치도  일반용  49,672   129,643,924

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201407  제주특별자치도  서귀포시  일반용  13,720    37,787,506
69   201408  제주특별자치도  서귀포시  일반용  13,835    43,544,638
85   201409  제주특별자치도  서귀포시  일반용  13,814    39,522,840
101  201410  제주특별자치도  서귀포시  일반용  13,894    35,452,089
117  201411  제주특별자치도  서귀포시  일반용  13,978    35,089,705
133  201412  제주특별자치도  서귀포시  일반용  14,054    38,496,042
61   201407  제주특별자치도   제주시  일반용  34,577    86,914,440
77   201408  제주특별자치도   제주시  일반용  34,820   101,159,032
93   201409  제주특별자치도   제주시  일반용  34,979    90,817,535
109  201410  제주특별자치도   제주시  일반용  35,112    81,607,355
125  201411  제주특별자치도   제주시  일반용  35,340    82,455,607
141  201412  제주특별자치도   제주시  일반용  35,618    91,147,882

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'제주특별자치도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['서귀포시', '제주시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
55   201407  제주특별자치도  서귀포시   합계  108,297   126,021,205
71   201408  제주특별자치도  서귀포시   합계  108,773   135,380,658
87   201409  제주특별자치도  서귀포시   합계  109,086   130,069,199
103  201410  제주특별자치도  서귀포시   합계  109,570   121,333,073
119  201411  제주특별자치도  서귀포시   합계  109,945   128,432,150
135  201412  제주특별자치도  서귀포시   합계  110,423   143,121,950
63   201407  제주특별자치도   제주시   합계  224,975   203,046,525
79   201408  제주특별자치도   제주시   합계  225,551   228,685,247
95   201409  제주특별자치도   제주시   합계  226,244   211,323,838
111  201410  제주특별자치도   제주시   합계  226,905   196,827,568
127  201411  제주특별자치도   제주시   합계  227,765   205,811,258
143  201412  제주특별자치도   제주시   합계  228,649   224,403,119

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[126021205, 135380658, 130069199, 121333073, 128432150, 143121950]
[203046525, 228685247, 211323838, 196827568, 205811258, 224403119]
제주특별자치도 지역별 합계 :  [784358235, 1270097555]
제주특별자치도 고객호수 평균:  [18224, 37780]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_2716\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2716\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
0          201407  제주특별자치도  서귀포시   합계  108,297   126,021,205
1          201408  제주특별자치도  서귀포시   합계  108,773   135,380,658
2          201409  제주특별자치도  서귀포시   합계  109,086   130,069,199
3          201410  제주특별자치도  서귀포시   합계  109,570   121,333,073
4          201411  제주특별자치도  서귀포시   합계  109,945   128,432,150
5          201412  제주특별자치도  서귀포시   합계  110,423   143,121,950
6          201407  제주특별자치도   제주시   합계  224,975   203,046,525
7          201408  제주특별자치도   제주시   합계  225,551   228,685,247
8          201409  제주특별자치도   제주시   합계  226,244   211,323,838
9          201410  제주특별자치도   제주시   합계  226,905   196,827,568
10         201411  제주특별자치도   제주시   합계  227,765   205,811,258
11         201412  제주특별자치도   제주시   합계  228,649   224,403,119
12  201407-201412  제주특별자치도  서귀포시   합계     18224     784358235
13  201407-201412  제주특별자치도   제주시   합계     37780    1270097555

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201407-201412']
Hap

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201407-201412  제주특별자치도  서귀포시   합계   18224   784358235
13  201407-201412  제주특별자치도   제주시   합계   37780  1270097555

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201407  제주특별자치도  서귀포시  일반용  13,720    37,787,506
69   201408  제주특별자치도  서귀포시  일반용  13,835    43,544,638
85   201409  제주특별자치도  서귀포시  일반용  13,814    39,522,840
101  201410  제주특별자치도  서귀포시  일반용  13,894    35,452,089
117  201411  제주특별자치도  서귀포시  일반용  13,978    35,089,705
133  201412  제주특별자치도  서귀포시  일반용  14,054    38,496,042
61   201407  제주특별자치도   제주시  일반용  34,577    86,914,440
77   201408  제주특별자치도   제주시  일반용  34,820   101,159,032
93   201409  제주특별자치도   제주시  일반용  34,979    90,817,535
109  201410  제주특별자치도   제주시  일반용  35,112    81,607,355
125  201411  제주특별자치도   제주시  일반용  35,340    82,455,607
141  201412  제주특별자치도   제주시  일반용  35,618    91,147,882

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[37787506, 43544638, 39522840, 35452089, 35089705, 38496042]
[86914440, 101159032, 90817535, 81607355, 82455607, 91147882]
제주특별자치도 지역별 일반용 합계 :  [229892820, 534101851]
제주특별자치도 고객호수 평균:  [13882, 35074]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_2716\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2716\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0          201407  제주특별자치도  서귀포시  일반용  13,720    37,787,506
1          201408  제주특별자치도  서귀포시  일반용  13,835    43,544,638
2          201409  제주특별자치도  서귀포시  일반용  13,814    39,522,840
3          201410  제주특별자치도  서귀포시  일반용  13,894    35,452,089
4          201411  제주특별자치도  서귀포시  일반용  13,978    35,089,705
5          201412  제주특별자치도  서귀포시  일반용  14,054    38,496,042
6          201407  제주특별자치도   제주시  일반용  34,577    86,914,440
7          201408  제주특별자치도   제주시  일반용  34,820   101,159,032
8          201409  제주특별자치도   제주시  일반용  34,979    90,817,535
9          201410  제주특별자치도   제주시  일반용  35,112    81,607,355
10         201411  제주특별자치도   제주시  일반용  35,340    82,455,607
11         201412  제주특별자치도   제주시  일반용  35,618    91,147,882
12  201407-201412  제주특별자치도  서귀포시  일반용    13882     229892820
13  201407-201412  제주특별자치도   제주시  일반용    35074     534101851

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201407-201412']
GyeonGiHap2

               년월       시구   시군구 계약구분 고객호수(호)   사용량(kWh)
12  201407-201412  제주특별자치도  서귀포시  일반용   13882  229892820
13  201407-201412  제주특별자치도   제주시  일반용   35074  534101851

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201407-201412  제주특별자치도  서귀포시  일반용   13882   229892820
12  201407-201412  제주특별자치도  서귀포시   합계   18224   784358235
13  201407-201412  제주특별자치도   제주시  일반용   35074   534101851
13  201407-201412  제주특별자치도   제주시   합계   37780  1270097555

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[229892820, 534101851]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[784358235, 1270097555]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[29.31, 42.05]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   29
1   42
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0  서귀포시  일반용  29
1   제주시  일반용  42

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201407-201412  제주특별자치도  서귀포시  일반용   13882   229892820  29
1  201407-201412  제주특별자치도  서귀포시   합계   18224   784358235 NaN
2  201407-201412  제주특별자치도   제주시  일반용   35074   534101851  42
3  201407-201412  제주특별자치도   제주시   합계   37780  1270097555 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1407-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)