In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('울산광역시_계약종별 전력사용량 월별_14상반기.csv' , encoding='utf-8')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 울산광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 01 월 ~ 2014년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,울산광역시,전체(시 / 군 / 구),주택용,"294,862","130,242,345","17,284,408,701",132.7
4,201401,울산광역시,전체(시 / 군 / 구),일반용,"66,514","178,290,138","24,149,000,254",135.4
...,...,...,...,...,...,...,...,...
283,201406,울산광역시,중구,산업용,516,"1,940,023","276,607,292",142.6
284,201406,울산광역시,중구,심 야,818,"552,249","33,808,769",61.2
285,201406,울산광역시,중구,일반용,"12,730","23,450,116","3,125,891,317",133.3
286,201406,울산광역시,중구,주택용,"67,770","22,797,763","2,782,073,436",122
287,201406,울산광역시,중구,합계,"87,217","50,629,717","6,464,531,959",127.7

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,울산광역시,전체(시 / 군 / 구),주택용,"294,862","130,242,345","17,284,408,701",132.7
4,201401,울산광역시,전체(시 / 군 / 구),일반용,"66,514","178,290,138","24,149,000,254",135.4
5,201401,울산광역시,전체(시 / 군 / 구),교육용,406,"14,217,956","1,633,545,259",114.9
6,201401,울산광역시,전체(시 / 군 / 구),산업용,"5,901","2,222,532,029","239,070,073,651",107.6
...,...,...,...,...,...,...,...,...
283,201406,울산광역시,중구,산업용,516,"1,940,023","276,607,292",142.6
284,201406,울산광역시,중구,심 야,818,"552,249","33,808,769",61.2
285,201406,울산광역시,중구,일반용,"12,730","23,450,116","3,125,891,317",133.3
286,201406,울산광역시,중구,주택용,"67,770","22,797,763","2,782,073,436",122
287,201406,울산광역시,중구,합계,"87,217","50,629,717","6,464,531,959",127.7

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,울산광역시,전체(시 / 군 / 구),주택용,"294,862","130,242,345","17,284,408,701",132.7
4,201401,울산광역시,전체(시 / 군 / 구),일반용,"66,514","178,290,138","24,149,000,254",135.4
5,201401,울산광역시,전체(시 / 군 / 구),교육용,406,"14,217,956","1,633,545,259",114.9
6,201401,울산광역시,전체(시 / 군 / 구),산업용,"5,901","2,222,532,029","239,070,073,651",107.6
7,201401,울산광역시,전체(시 / 군 / 구),농사용,"10,358","8,299,751","404,209,129",48.7
...,...,...,...,...,...,...,...,...
283,201406,울산광역시,중구,산업용,516,"1,940,023","276,607,292",142.6
284,201406,울산광역시,중구,심 야,818,"552,249","33,808,769",61.2
285,201406,울산광역시,중구,일반용,"12,730","23,450,116","3,125,891,317",133.3
286,201406,울산광역시,중구,주택용,"67,770","22,797,763","2,782,073,436",122
287,201406,울산광역시,중구,합계,"87,217","50,629,717","6,464,531,959",127.7

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,울산광역시,전체(시 / 군 / 구),주택용,"294,862","130,242,345","17,284,408,701",132.7
4,201401,울산광역시,전체(시 / 군 / 구),일반용,"66,514","178,290,138","24,149,000,254",135.4
5,201401,울산광역시,전체(시 / 군 / 구),교육용,406,"14,217,956","1,633,545,259",114.9
6,201401,울산광역시,전체(시 / 군 / 구),산업용,"5,901","2,222,532,029","239,070,073,651",107.6
7,201401,울산광역시,전체(시 / 군 / 구),농사용,"10,358","8,299,751","404,209,129",48.7
8,201401,울산광역시,전체(시 / 군 / 구),가로등,"29,330","5,498,886","569,723,738",103.6
9,201401,울산광역시,전체(시 / 군 / 구),심 야,"8,641","26,373,865","1,990,698,925",75.5
10,201402,울산광역시,전체(시 / 군 / 구),주택용,"295,504","131,221,087","17,799,157,171",135.6
11,201402,울산광역시,전체(시 / 군 / 구),일반용,"66,559","171,220,780","23,474,414,169",137.1
12,201402,울산광역시,전체(시 / 군 / 구),교육용,416,"13,426,895","1,582,976,217",117.9
13,201402,울산광역시,전체(시 / 군 / 구),산업용,"5,918","2,014,621,200","223,887,732,532",111.1
14,201402,울산광역시,전체(시 / 군 / 구),농사용,"10,377","8,127,118","397,209,520",48.9
15,201402,울산광역시,전체(시 / 군 / 구),가로등,"29,412","5,141,719","565,071,613",109.9
16,201402,울산광역시,전체(시 / 군 / 구),심 야,"8,626","25,977,664","1,957,130,066",75.3
17,201403,울산광역시,전체(시 / 군 / 구),주택용,"296,124","116,559,215","14,087,938,962",120.9
18,201403,울산광역시,전체(시 / 군 / 구),일반용,"66,590","154,651,457","19,858,768,601",128.4
19,201403,울산광역시,전체(시 / 군 / 구),교육용,422,"13,474,668","1,367,250,576",101.5
20,201403,울산광역시,전체(시 / 군 / 구),산업용,"5,921","2,248,137,748","194,707,181,755",86.6
21,201403,울산광역시,전체(시 / 군 / 구),농사용,"11,371","6,863,422","338,149,382",49.3
22,201403,울산광역시,전체(시 / 군 / 구),가로등,"29,439","4,691,143","525,103,913",111.9
23,201403,울산광역시,전체(시 / 군 / 구),심 야,"8,617","21,428,813","1,436,641,486",67.0
24,201404,울산광역시,전체(시 / 군 / 구),주택용,"297,018","120,621,890","15,069,461,248",124.9
25,201404,울산광역시,전체(시 / 군 / 구),일반용,"66,735","146,454,756","17,205,368,535",117.5
26,201404,울산광역시,전체(시 / 군 / 구),교육용,425,"11,547,327","1,175,048,282",101.8
27,201404,울산광역시,전체(시 / 군 / 구),산업용,"5,938","2,187,498,835","192,292,877,304",87.9
28,201404,울산광역시,전체(시 / 군 / 구),농사용,"10,525","6,363,430","315,139,879",49.5
29,201404,울산광역시,전체(시 / 군 / 구),가로등,"29,515","4,575,143","535,467,025",117.0
30,201404,울산광역시,전체(시 / 군 / 구),심 야,"8,588","16,878,092","922,536,268",54.7
31,201405,울산광역시,전체(시 / 군 / 구),주택용,"297,834","112,672,619","13,137,817,365",116.6
32,201405,울산광역시,전체(시 / 군 / 구),일반용,"66,948","137,324,277","16,491,088,357",120.1
33,201405,울산광역시,전체(시 / 군 / 구),교육용,423,"10,082,039","1,085,560,993",107.7
34,201405,울산광역시,전체(시 / 군 / 구),산업용,"5,937","2,206,581,997","191,055,263,102",86.6
35,201405,울산광역시,전체(시 / 군 / 구),농사용,"10,623","5,566,338","283,556,130",50.9
36,201405,울산광역시,전체(시 / 군 / 구),가로등,"29,614","4,293,019","523,075,547",121.8
37,201405,울산광역시,전체(시 / 군 / 구),심 야,"8,558","11,141,816","609,412,447",54.7
38,201406,울산광역시,전체(시 / 군 / 구),주택용,"298,434","114,389,621","13,522,808,744",118.2
39,201406,울산광역시,전체(시 / 군 / 구),일반용,"67,133","146,462,082","19,559,984,383",133.5
40,201406,울산광역시,전체(시 / 군 / 구),교육용,421,"10,747,415","1,330,603,287",123.8
41,201406,울산광역시,전체(시 / 군 / 구),산업용,"5,947","2,158,054,201","233,390,349,117",108.1
42,201406,울산광역시,전체(시 / 군 / 구),농사용,"10,720","5,937,650","296,066,211",49.9
43,201406,울산광역시,전체(시 / 군 / 구),가로등,"29,694","4,034,627","510,294,653",126.5
44,201406,울산광역시,전체(시 / 군 / 구),심 야,"8,529","6,875,960","389,350,292",56.6
45,합계,합계,합계,합계,"2,510,867","14,949,101,033","1,506,787,514,789",100.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_19068\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분  고객호수(호)      사용량(kWh)
4   201401  울산광역시  일반용  66,514   178,290,138
11  201402  울산광역시  일반용  66,559   171,220,780
18  201403  울산광역시  일반용  66,590   154,651,457
25  201404  울산광역시  일반용  66,735   146,454,756
32  201405  울산광역시  일반용  66,948   137,324,277
39  201406  울산광역시  일반용  67,133   146,462,082

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201401  울산광역시   남구  일반용  24,667   71,757,513
93   201402  울산광역시   남구  일반용  24,690   69,067,843
133  201403  울산광역시   남구  일반용  24,688   62,655,347
173  201404  울산광역시   남구  일반용  24,699   58,357,840
213  201405  울산광역시   남구  일반용  24,731   54,987,287
253  201406  울산광역시   남구  일반용  24,745   58,967,526
61   201401  울산광역시   동구  일반용   7,879   21,302,136
101  201402  울산광역시   동구  일반용   7,900   20,370,529
141  201403  울산광역시   동구  일반용   7,916   18,719,225
181  201404  울산광역시   동구  일반용   7,963   18,215,925
221  201405  울산광역시   동구  일반용   7,995   17,231,874
261  201406  울산광역시   동구  일반용   7,996   18,336,114
69   201401  울산광역시   북구  일반용   7,692   23,967,589
109  201402  울산광역시   북구  일반용   7,687   22,747,319
149  201403  울산광역시   북구  일반용   7,715   20,480,514
189  201404  울산광역시   북구  일반용   7,745   19,673,379
229  201405  울산광역시   북구  일반용   7,818   18,322,099
269  201406  울산광역시   북구  일반용   7,865   19,550,881
77   201401  울산광역시  울주군  일반용  13,661   33,418,328
117  201402  울산광역시  울주군  일반용  13,645   32,366,370
157  201403  울산광역시  울주군  일반용  13,632   28,965,819
197  201404  울산광역시  울주군  일반용  13,672   27,592,955
237  201405  울산광역시  울주군  일반용  13,726   25,199,123
277  201406  울산광역시  울주군  일반용  13,797   26,157,445
85   201401  울산광역시   중구  일반용  12,615   27,844,572
125  201402  울산광역시   중구  일반용  12,637   26,668,719
165  201403  울산광역시   중구  일반용  12,639   23,830,552
205  201404  울산광역시   중구  일반용  12,656   22,614,657
245  201405  울산광역시   중구  일반용  12,678   21,583,894
285  201406  울산광역시   중구  일반용  12,730   23,450,116

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'울산광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['남구', '동구', '북구', '울주군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)        사용량(kWh)
55   201401  울산광역시   남구   합계  130,260   1,257,549,697
95   201402  울산광역시   남구   합계  130,394   1,145,549,029
135  201403  울산광역시   남구   합계  130,555   1,257,683,980
175  201404  울산광역시   남구   합계  130,822   1,246,196,214
215  201405  울산광역시   남구   합계  130,990   1,255,493,387
255  201406  울산광역시   남구   합계  131,125   1,226,533,100
63   201401  울산광역시   동구   합계   54,329     151,576,799
103  201402  울산광역시   동구   합계   54,500     148,013,751
143  201403  울산광역시   동구   합계   54,734     150,873,844
183  201404  울산광역시   동구   합계   54,998     143,997,299
223  201405  울산광역시   동구   합계   55,248     139,919,270
263  201406  울산광역시   동구   합계   55,336     145,876,683
71   201401  울산광역시   북구   합계   45,094     220,369,790
111  201402  울산광역시   북구   합계   45,213     207,027,903
151  201403  울산광역시   북구   합계   45,517     212,766,171
191  201404  울산광역시   북구   합계   45,395     204,704,004
231  201405  울산광역시   북구   합계   45,707     192,626,564
271  201406  울산광역시   북구   합계   45,873     198,522,869
79   201401  울산광역시  울주군   합계   99,886     894,176,966
119  201402  울산광역시  울주군   합계  100,116     808,576,013
159  201403  울산광역시  울주군   합계  100,996     890,283,597
199  201404  울산광역시  울주군   합계  100,717     846,136,031
239  201405  울산광역시  울주군   합계  100,978     850,730,707
279  201406  울산광역시  울주군   합계  101,327     824,939,187
87   201401  울산광역시   중구   합계   86,443      61,781,718
127  201402  울산광역시   중구   합계   86,589      60,569,767
167  201403  울산광역시   중구   합계   86,682      54,198,874
207  201404  울산광역시   중구   합계   86,812      52,905,925
247  201405  울산광역시   중구   합계   87,014      48,892,177
287  201406  울산광역시   중구   합계   87,217      50,629,717

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[1257549697, 1145549029, 1257683980, 1246196214, 1255493387, 1226533100]
[151576799, 148013751, 150873844, 143997299, 139919270, 145876683]
[220369790, 207027903, 212766171, 204704004, 192626564, 198522869]
[894176966, 808576013, 890283597, 846136031, 850730707, 824939187]
[61781718, 60569767, 54198874, 52905925, 48892177, 50629717]
울산광역시 지역별 합계 :  [7389005407, 880257646, 1236017301, 5114842501, 328978178]
울산광역시 고객호수 평균:  [21781, 9142, 7577, 16778, 14465]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_19068\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19068\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19068\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19068\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19068\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분   고객호수(호)        사용량(kWh)
0          201401  울산광역시   남구   합계  130,260   1,257,549,697
1          201402  울산광역시   남구   합계  130,394   1,145,549,029
2          201403  울산광역시   남구   합계  130,555   1,257,683,980
3          201404  울산광역시   남구   합계  130,822   1,246,196,214
4          201405  울산광역시   남구   합계  130,990   1,255,493,387
5          201406  울산광역시   남구   합계  131,125   1,226,533,100
6          201401  울산광역시   동구   합계   54,329     151,576,799
7          201402  울산광역시   동구   합계   54,500     148,013,751
8          201403  울산광역시   동구   합계   54,734     150,873,844
9          201404  울산광역시   동구   합계   54,998     143,997,299
10         201405  울산광역시   동구   합계   55,248     139,919,270
11         201406  울산광역시   동구   합계   55,336     145,876,683
12         201401  울산광역시   북구   합계   45,094     220,369,790
13         201402  울산광역시   북구   합계   45,213     207,027,903
14         201403  울산광역시   북구   합계   45,517     212,766,171
15         201404  울산광역시   북구   합계   45,395     204,704,004
16         201405  울산광역시   북구   합계   45,707     192,626,564
17         201406  울산광역시   북구   합계   45,873     198,522,869
18         201401  울산광역시  울주군   합계   99,886     894,176,966
19         201402  울산광역시  울주군   합계  100,116     808,576,013
20         201403  울산광역시  울주군   합계  100,996     890,283,597
21         201404  울산광역시  울주군   합계  100,717     846,136,031
22         201405  울산광역시  울주군   합계  100,978     850,730,707
23         201406  울산광역시  울주군   합계  101,327     824,939,187
24         201401  울산광역시   중구   합계   86,443      61,781,718
25         201402  울산광역시   중구   합계   86,589      60,569,767
26         201403  울산광역시   중구   합계   86,682      54,198,874
27         201404  울산광역시   중구   합계   86,812      52,905,925
28         201405  울산광역시   중구   합계   87,014      48,892,177
29         201406  울산광역시   중구   합계   87,217      50,629,717
30  201401-201406  울산광역시   남구   합계     21781      7389005407
31  201401-201406  울산광역시   동구   합계      9142       880257646
32  201401-201406  울산광역시   북구   합계      7577      1236017301
33  201401-201406  울산광역시  울주군   합계     16778      5114842501
34  201401-201406  울산광역시   중구   합계     14465       328978178

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201401-201406']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
30  201401-201406  울산광역시   남구   합계   21781  7389005407
31  201401-201406  울산광역시   동구   합계    9142   880257646
32  201401-201406  울산광역시   북구   합계    7577  1236017301
33  201401-201406  울산광역시  울주군   합계   16778  5114842501
34  201401-201406  울산광역시   중구   합계   14465   328978178

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201401  울산광역시   남구  일반용  24,667   71,757,513
93   201402  울산광역시   남구  일반용  24,690   69,067,843
133  201403  울산광역시   남구  일반용  24,688   62,655,347
173  201404  울산광역시   남구  일반용  24,699   58,357,840
213  201405  울산광역시   남구  일반용  24,731   54,987,287
253  201406  울산광역시   남구  일반용  24,745   58,967,526
61   201401  울산광역시   동구  일반용   7,879   21,302,136
101  201402  울산광역시   동구  일반용   7,900   20,370,529
141  201403  울산광역시   동구  일반용   7,916   18,719,225
181  201404  울산광역시   동구  일반용   7,963   18,215,925
221  201405  울산광역시   동구  일반용   7,995   17,231,874
261  201406  울산광역시   동구  일반용   7,996   18,336,114
69   201401  울산광역시   북구  일반용   7,692   23,967,589
109  201402  울산광역시   북구  일반용   7,687   22,747,319
149  201403  울산광역시   북구  일반용   7,715   20,480,514
189  201404  울산광역시   북구  일반용   7,745   19,673,379
229  201405  울산광역시   북구  일반용   7,818   18,322,099
269  201406  울산광역시   북구  일반용   7,865   19,550,881
77   201401  울산광역시  울주군  일반용  13,661   33,418,328
117  201402  울산광역시  울주군  일반용  13,645   32,366,370
157  201403  울산광역시  울주군  일반용  13,632   28,965,819
197  201404  울산광역시  울주군  일반용  13,672   27,592,955
237  201405  울산광역시  울주군  일반용  13,726   25,199,123
277  201406  울산광역시  울주군  일반용  13,797   26,157,445
85   201401  울산광역시   중구  일반용  12,615   27,844,572
125  201402  울산광역시   중구  일반용  12,637   26,668,719
165  201403  울산광역시   중구  일반용  12,639   23,830,552
205  201404  울산광역시   중구  일반용  12,656   22,614,657
245  201405  울산광역시   중구  일반용  12,678   21,583,894
285  201406  울산광역시   중구  일반용  12,730   23,450,116

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[71757513, 69067843, 62655347, 58357840, 54987287, 58967526]
[21302136, 20370529, 18719225, 18215925, 17231874, 18336114]
[23967589, 22747319, 20480514, 19673379, 18322099, 19550881]
[33418328, 32366370, 28965819, 27592955, 25199123, 26157445]
[27844572, 26668719, 23830552, 22614657, 21583894, 23450116]
울산광역시 지역별 일반용 합계 :  [375793356, 114175803, 124741781, 173700040, 145992510]
울산광역시 고객호수 평균:  [24703, 7941, 7753, 13688, 12659]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_19068\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19068\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19068\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19068\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_19068\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201401  울산광역시   남구  일반용  24,667   71,757,513
1          201402  울산광역시   남구  일반용  24,690   69,067,843
2          201403  울산광역시   남구  일반용  24,688   62,655,347
3          201404  울산광역시   남구  일반용  24,699   58,357,840
4          201405  울산광역시   남구  일반용  24,731   54,987,287
5          201406  울산광역시   남구  일반용  24,745   58,967,526
6          201401  울산광역시   동구  일반용   7,879   21,302,136
7          201402  울산광역시   동구  일반용   7,900   20,370,529
8          201403  울산광역시   동구  일반용   7,916   18,719,225
9          201404  울산광역시   동구  일반용   7,963   18,215,925
10         201405  울산광역시   동구  일반용   7,995   17,231,874
11         201406  울산광역시   동구  일반용   7,996   18,336,114
12         201401  울산광역시   북구  일반용   7,692   23,967,589
13         201402  울산광역시   북구  일반용   7,687   22,747,319
14         201403  울산광역시   북구  일반용   7,715   20,480,514
15         201404  울산광역시   북구  일반용   7,745   19,673,379
16         201405  울산광역시   북구  일반용   7,818   18,322,099
17         201406  울산광역시   북구  일반용   7,865   19,550,881
18         201401  울산광역시  울주군  일반용  13,661   33,418,328
19         201402  울산광역시  울주군  일반용  13,645   32,366,370
20         201403  울산광역시  울주군  일반용  13,632   28,965,819
21         201404  울산광역시  울주군  일반용  13,672   27,592,955
22         201405  울산광역시  울주군  일반용  13,726   25,199,123
23         201406  울산광역시  울주군  일반용  13,797   26,157,445
24         201401  울산광역시   중구  일반용  12,615   27,844,572
25         201402  울산광역시   중구  일반용  12,637   26,668,719
26         201403  울산광역시   중구  일반용  12,639   23,830,552
27         201404  울산광역시   중구  일반용  12,656   22,614,657
28         201405  울산광역시   중구  일반용  12,678   21,583,894
29         201406  울산광역시   중구  일반용  12,730   23,450,116
30  201401-201406  울산광역시   남구  일반용    24703    375793356
31  201401-201406  울산광역시   동구  일반용     7941    114175803
32  201401-201406  울산광역시   북구  일반용     7753    124741781
33  201401-201406  울산광역시  울주군  일반용    13688    173700040
34  201401-201406  울산광역시   중구  일반용    12659    145992510

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201401-201406']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
30  201401-201406  울산광역시   남구  일반용   24703  375793356
31  201401-201406  울산광역시   동구  일반용    7941  114175803
32  201401-201406  울산광역시   북구  일반용    7753  124741781
33  201401-201406  울산광역시  울주군  일반용   13688  173700040
34  201401-201406  울산광역시   중구  일반용   12659  145992510

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
30  201401-201406  울산광역시   남구  일반용   24703   375793356
30  201401-201406  울산광역시   남구   합계   21781  7389005407
31  201401-201406  울산광역시   동구  일반용    7941   114175803
31  201401-201406  울산광역시   동구   합계    9142   880257646
32  201401-201406  울산광역시   북구  일반용    7753   124741781
32  201401-201406  울산광역시   북구   합계    7577  1236017301
33  201401-201406  울산광역시  울주군  일반용   13688   173700040
33  201401-201406  울산광역시  울주군   합계   16778  5114842501
34  201401-201406  울산광역시   중구  일반용   12659   145992510
34  201401-201406  울산광역시   중구   합계   14465   328978178

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[375793356, 114175803, 124741781, 173700040, 145992510]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[7389005407, 880257646, 1236017301, 5114842501, 328978178]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[5.09, 12.97, 10.09, 3.4, 44.38]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    5
1   13
2   10
3    3
4   44
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0   남구  일반용   5
1   동구  일반용  13
2   북구  일반용  10
3  울주군  일반용   3
4   중구  일반용  44

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201401-201406  울산광역시   남구  일반용   24703   375793356   5
1  201401-201406  울산광역시   남구   합계   21781  7389005407 NaN
2  201401-201406  울산광역시   동구  일반용    7941   114175803  13
3  201401-201406  울산광역시   동구   합계    9142   880257646 NaN
4  201401-201406  울산광역시   북구  일반용    7753   124741781  10
5  201401-201406  울산광역시   북구   합계    7577  1236017301 NaN
6  201401-201406  울산광역시  울주군  일반용   13688   173700040   3
7  201401-201406  울산광역시  울주군   합계   16778  5114842501 NaN
8  201401-201406  울산광역시   중구  일반용   12659   145992510  44
9  201401-201406  울산광역시   중구   합계   14465   328978178 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1401-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)