In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('제주특별자치도_계약종별_전력사용량_월별_17하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 제주특별자치도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2017년 07 월 ~ 2017년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,제주특별자치도,전체(시 / 군 / 구),주택용,"262,961","71,549,577","8,418,068,536",117.7
4,201707,제주특별자치도,전체(시 / 군 / 구),일반용,"64,419","174,886,532","25,367,265,749",145.0
...,...,...,...,...,...,...,...,...
139,201712,제주특별자치도,제주시,산업용,"2,363","37,663,029","4,655,145,001",123.6
140,201712,제주특별자치도,제주시,심 야,"4,796","10,103,103","756,569,462",74.9
141,201712,제주특별자치도,제주시,일반용,"46,938","109,727,607","15,171,621,433",138.3
142,201712,제주특별자치도,제주시,주택용,"194,376","50,680,878","5,639,354,275",111.3
143,201712,제주특별자치도,제주시,합계,"279,901","259,127,590","29,278,882,922",113

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,제주특별자치도,전체(시 / 군 / 구),주택용,"262,961","71,549,577","8,418,068,536",117.7
4,201707,제주특별자치도,전체(시 / 군 / 구),일반용,"64,419","174,886,532","25,367,265,749",145.0
5,201707,제주특별자치도,전체(시 / 군 / 구),교육용,338,"11,957,340","1,388,624,000",116.1
6,201707,제주특별자치도,전체(시 / 군 / 구),산업용,"3,189","50,053,994","6,492,326,456",129.7
...,...,...,...,...,...,...,...,...
139,201712,제주특별자치도,제주시,산업용,"2,363","37,663,029","4,655,145,001",123.6
140,201712,제주특별자치도,제주시,심 야,"4,796","10,103,103","756,569,462",74.9
141,201712,제주특별자치도,제주시,일반용,"46,938","109,727,607","15,171,621,433",138.3
142,201712,제주특별자치도,제주시,주택용,"194,376","50,680,878","5,639,354,275",111.3
143,201712,제주특별자치도,제주시,합계,"279,901","259,127,590","29,278,882,922",113

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,제주특별자치도,전체(시 / 군 / 구),주택용,"262,961","71,549,577","8,418,068,536",117.7
4,201707,제주특별자치도,전체(시 / 군 / 구),일반용,"64,419","174,886,532","25,367,265,749",145.0
5,201707,제주특별자치도,전체(시 / 군 / 구),교육용,338,"11,957,340","1,388,624,000",116.1
6,201707,제주특별자치도,전체(시 / 군 / 구),산업용,"3,189","50,053,994","6,492,326,456",129.7
7,201707,제주특별자치도,전체(시 / 군 / 구),농사용,"44,432","100,384,929","4,764,510,978",47.5
...,...,...,...,...,...,...,...,...
139,201712,제주특별자치도,제주시,산업용,"2,363","37,663,029","4,655,145,001",123.6
140,201712,제주특별자치도,제주시,심 야,"4,796","10,103,103","756,569,462",74.9
141,201712,제주특별자치도,제주시,일반용,"46,938","109,727,607","15,171,621,433",138.3
142,201712,제주특별자치도,제주시,주택용,"194,376","50,680,878","5,639,354,275",111.3
143,201712,제주특별자치도,제주시,합계,"279,901","259,127,590","29,278,882,922",113

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,제주특별자치도,전체(시 / 군 / 구),주택용,"262,961","71,549,577","8,418,068,536",117.7
4,201707,제주특별자치도,전체(시 / 군 / 구),일반용,"64,419","174,886,532","25,367,265,749",145.0
5,201707,제주특별자치도,전체(시 / 군 / 구),교육용,338,"11,957,340","1,388,624,000",116.1
6,201707,제주특별자치도,전체(시 / 군 / 구),산업용,"3,189","50,053,994","6,492,326,456",129.7
7,201707,제주특별자치도,전체(시 / 군 / 구),농사용,"44,432","100,384,929","4,764,510,978",47.5
8,201707,제주특별자치도,전체(시 / 군 / 구),가로등,"22,843","3,602,826","465,911,497",129.3
9,201707,제주특별자치도,전체(시 / 군 / 구),심 야,"7,201","6,757,019","446,868,972",66.1
10,201708,제주특별자치도,전체(시 / 군 / 구),주택용,"264,434","96,319,684","13,914,372,742",144.5
11,201708,제주특별자치도,전체(시 / 군 / 구),일반용,"64,967","209,197,616","29,374,718,542",140.4
12,201708,제주특별자치도,전체(시 / 군 / 구),교육용,338,"13,164,016","1,512,109,610",114.9
13,201708,제주특별자치도,전체(시 / 군 / 구),산업용,"3,198","52,507,761","6,707,331,723",127.7
14,201708,제주특별자치도,전체(시 / 군 / 구),농사용,"44,491","108,541,065","5,093,398,386",46.9
15,201708,제주특별자치도,전체(시 / 군 / 구),가로등,"23,044","3,910,855","475,952,644",121.7
16,201708,제주특별자치도,전체(시 / 군 / 구),심 야,"7,179","6,364,403","428,734,952",67.4
17,201709,제주특별자치도,전체(시 / 군 / 구),주택용,"266,261","74,599,753","8,916,014,844",119.5
18,201709,제주특별자치도,전체(시 / 군 / 구),일반용,"65,155","177,704,216","22,473,977,448",126.5
19,201709,제주특별자치도,전체(시 / 군 / 구),교육용,342,"12,447,849","1,303,521,262",104.7
20,201709,제주특별자치도,전체(시 / 군 / 구),산업용,"3,226","52,265,241","5,838,957,463",111.7
21,201709,제주특별자치도,전체(시 / 군 / 구),농사용,"44,573","104,619,534","4,857,924,720",46.4
22,201709,제주특별자치도,전체(시 / 군 / 구),가로등,"23,462","4,237,982","490,816,563",115.8
23,201709,제주특별자치도,전체(시 / 군 / 구),심 야,"7,160","4,979,020","323,440,524",65.0
24,201710,제주특별자치도,전체(시 / 군 / 구),주택용,"268,269","59,636,793","5,954,683,629",99.8
25,201710,제주특별자치도,전체(시 / 군 / 구),일반용,"65,521","144,489,208","16,846,828,505",116.6
26,201710,제주특별자치도,전체(시 / 군 / 구),교육용,341,"9,054,146","873,988,021",96.5
27,201710,제주특별자치도,전체(시 / 군 / 구),산업용,"3,273","47,272,516","4,902,840,319",103.7
28,201710,제주특별자치도,전체(시 / 군 / 구),농사용,"44,625","96,220,823","4,438,515,643",46.1
29,201710,제주특별자치도,전체(시 / 군 / 구),가로등,"23,651","4,707,765","502,403,778",106.7
30,201710,제주특별자치도,전체(시 / 군 / 구),심 야,"7,152","4,852,943","318,554,480",65.6
31,201711,제주특별자치도,전체(시 / 군 / 구),주택용,"270,179","62,188,625","6,459,324,392",103.9
32,201711,제주특별자치도,전체(시 / 군 / 구),일반용,"66,005","144,343,441","19,290,041,297",133.6
33,201711,제주특별자치도,전체(시 / 군 / 구),교육용,342,"10,019,177","1,071,696,609",107.0
34,201711,제주특별자치도,전체(시 / 군 / 구),산업용,"3,326","50,812,677","6,105,543,315",120.2
35,201711,제주특별자치도,전체(시 / 군 / 구),농사용,"44,847","102,578,964","4,779,305,663",46.6
36,201711,제주특별자치도,전체(시 / 군 / 구),가로등,"23,773","5,065,320","525,189,716",103.7
37,201711,제주특별자치도,전체(시 / 군 / 구),심 야,"7,138","8,322,632","555,139,166",66.7
38,201712,제주특별자치도,전체(시 / 군 / 구),주택용,"271,738","68,643,570","7,610,936,334",110.9
39,201712,제주특별자치도,전체(시 / 군 / 구),일반용,"66,475","164,571,657","22,735,945,946",138.2
40,201712,제주특별자치도,전체(시 / 군 / 구),교육용,342,"12,742,196","1,362,736,131",106.9
41,201712,제주특별자치도,전체(시 / 군 / 구),산업용,"3,401","51,891,778","6,544,069,068",126.1
42,201712,제주특별자치도,전체(시 / 군 / 구),농사용,"45,058","119,804,825","5,625,267,955",47.0
43,201712,제주특별자치도,전체(시 / 군 / 구),가로등,"23,900","5,355,248","533,110,844",99.5
44,201712,제주특별자치도,전체(시 / 군 / 구),심 야,"7,123","14,130,797","1,064,911,513",75.4
45,합계,합계,합계,합계,"2,469,692","2,526,756,313","267,155,879,935",105.7

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_14364\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월       시구 계약구분  고객호수(호)      사용량(kWh)
4   201707  제주특별자치도  일반용  64,419   174,886,532
11  201708  제주특별자치도  일반용  64,967   209,197,616
18  201709  제주특별자치도  일반용  65,155   177,704,216
25  201710  제주특별자치도  일반용  65,521   144,489,208
32  201711  제주특별자치도  일반용  66,005   144,343,441
39  201712  제주특별자치도  일반용  66,475   164,571,657

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201707  제주특별자치도  서귀포시  일반용  18,725    56,928,273
69   201708  제주특별자치도  서귀포시  일반용  18,884    68,445,048
85   201709  제주특별자치도  서귀포시  일반용  19,087    58,981,697
101  201710  제주특별자치도  서귀포시  일반용  19,246    49,347,608
117  201711  제주특별자치도  서귀포시  일반용  19,431    48,848,308
133  201712  제주특별자치도  서귀포시  일반용  19,537    54,844,050
61   201707  제주특별자치도   제주시  일반용  45,694   117,958,259
77   201708  제주특별자치도   제주시  일반용  46,083   140,752,568
93   201709  제주특별자치도   제주시  일반용  46,068   118,722,519
109  201710  제주특별자치도   제주시  일반용  46,275    95,141,600
125  201711  제주특별자치도   제주시  일반용  46,574    95,495,133
141  201712  제주특별자치도   제주시  일반용  46,938   109,727,607

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'제주특별자치도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['서귀포시', '제주시']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
55   201707  제주특별자치도  서귀포시   합계  133,465   160,250,367
71   201708  제주특별자치도  서귀포시   합계  134,258   182,739,573
87   201709  제주특별자치도  서귀포시   합계  135,240   166,079,349
103  201710  제주특별자치도  서귀포시   합계  136,065   144,731,714
119  201711  제주특별자치도  서귀포시   합계  137,187   151,803,904
135  201712  제주특별자치도  서귀포시   합계  138,136   178,012,481
63   201707  제주특별자치도   제주시   합계  271,918   258,941,850
79   201708  제주특별자치도   제주시   합계  273,393   307,265,827
95   201709  제주특별자치도   제주시   합계  274,939   264,774,246
111  201710  제주특별자치도   제주시   합계  276,767   221,502,480
127  201711  제주특별자치도   제주시   합계  278,423   231,526,932
143  201712  제주특별자치도   제주시   합계  279,901   259,127,590

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[160250367, 182739573, 166079349, 144731714, 151803904, 178012481]
[258941850, 307265827, 264774246, 221502480, 231526932, 259127590]
제주특별자치도 지역별 합계 :  [983617388, 1543138925]
제주특별자치도 고객호수 평균:  [22620, 45981]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_14364\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14364\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분   고객호수(호)      사용량(kWh)
0          201707  제주특별자치도  서귀포시   합계  133,465   160,250,367
1          201708  제주특별자치도  서귀포시   합계  134,258   182,739,573
2          201709  제주특별자치도  서귀포시   합계  135,240   166,079,349
3          201710  제주특별자치도  서귀포시   합계  136,065   144,731,714
4          201711  제주특별자치도  서귀포시   합계  137,187   151,803,904
5          201712  제주특별자치도  서귀포시   합계  138,136   178,012,481
6          201707  제주특별자치도   제주시   합계  271,918   258,941,850
7          201708  제주특별자치도   제주시   합계  273,393   307,265,827
8          201709  제주특별자치도   제주시   합계  274,939   264,774,246
9          201710  제주특별자치도   제주시   합계  276,767   221,502,480
10         201711  제주특별자치도   제주시   합계  278,423   231,526,932
11         201712  제주특별자치도   제주시   합계  279,901   259,127,590
12  201707-201712  제주특별자치도  서귀포시   합계     22620     983617388
13  201707-201712  제주특별자치도   제주시   합계     45981    1543138925

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201707-201712']
Hap

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201707-201712  제주특별자치도  서귀포시   합계   22620   983617388
13  201707-201712  제주특별자치도   제주시   합계   45981  1543138925

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
53   201707  제주특별자치도  서귀포시  일반용  18,725    56,928,273
69   201708  제주특별자치도  서귀포시  일반용  18,884    68,445,048
85   201709  제주특별자치도  서귀포시  일반용  19,087    58,981,697
101  201710  제주특별자치도  서귀포시  일반용  19,246    49,347,608
117  201711  제주특별자치도  서귀포시  일반용  19,431    48,848,308
133  201712  제주특별자치도  서귀포시  일반용  19,537    54,844,050
61   201707  제주특별자치도   제주시  일반용  45,694   117,958,259
77   201708  제주특별자치도   제주시  일반용  46,083   140,752,568
93   201709  제주특별자치도   제주시  일반용  46,068   118,722,519
109  201710  제주특별자치도   제주시  일반용  46,275    95,141,600
125  201711  제주특별자치도   제주시  일반용  46,574    95,495,133
141  201712  제주특별자치도   제주시  일반용  46,938   109,727,607

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[56928273, 68445048, 58981697, 49347608, 48848308, 54844050]
[117958259, 140752568, 118722519, 95141600, 95495133, 109727607]
제주특별자치도 지역별 일반용 합계 :  [337394984, 677797686]
제주특별자치도 고객호수 평균:  [19151, 46272]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_14364\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_14364\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월       시구   시군구 계약구분  고객호수(호)      사용량(kWh)
0          201707  제주특별자치도  서귀포시  일반용  18,725    56,928,273
1          201708  제주특별자치도  서귀포시  일반용  18,884    68,445,048
2          201709  제주특별자치도  서귀포시  일반용  19,087    58,981,697
3          201710  제주특별자치도  서귀포시  일반용  19,246    49,347,608
4          201711  제주특별자치도  서귀포시  일반용  19,431    48,848,308
5          201712  제주특별자치도  서귀포시  일반용  19,537    54,844,050
6          201707  제주특별자치도   제주시  일반용  45,694   117,958,259
7          201708  제주특별자치도   제주시  일반용  46,083   140,752,568
8          201709  제주특별자치도   제주시  일반용  46,068   118,722,519
9          201710  제주특별자치도   제주시  일반용  46,275    95,141,600
10         201711  제주특별자치도   제주시  일반용  46,574    95,495,133
11         201712  제주특별자치도   제주시  일반용  46,938   109,727,607
12  201707-201712  제주특별자치도  서귀포시  일반용    19151     337394984
13  201707-201712  제주특별자치도   제주시  일반용    46272     677797686

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201707-201712']
GyeonGiHap2

               년월       시구   시군구 계약구분 고객호수(호)   사용량(kWh)
12  201707-201712  제주특별자치도  서귀포시  일반용   19151  337394984
13  201707-201712  제주특별자치도   제주시  일반용   46272  677797686

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)
12  201707-201712  제주특별자치도  서귀포시  일반용   19151   337394984
12  201707-201712  제주특별자치도  서귀포시   합계   22620   983617388
13  201707-201712  제주특별자치도   제주시  일반용   46272   677797686
13  201707-201712  제주특별자치도   제주시   합계   45981  1543138925

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[337394984, 677797686]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[983617388, 1543138925]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[34.3, 43.92]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   34
1   44
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0  서귀포시  일반용  34
1   제주시  일반용  44

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

              년월       시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0  201707-201712  제주특별자치도  서귀포시  일반용   19151   337394984  34
1  201707-201712  제주특별자치도  서귀포시   합계   22620   983617388 NaN
2  201707-201712  제주특별자치도   제주시  일반용   46272   677797686  44
3  201707-201712  제주특별자치도   제주시   합계   45981  1543138925 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1707-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)