In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별_전력사용량_월별_16상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2016년 01 월 ~ 2016년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,인천광역시,전체(시 / 군 / 구),주택용,"710,840","342,893,758","45,660,169,929",133.2
4,201601,인천광역시,전체(시 / 군 / 구),일반용,"130,479","503,412,953","66,216,338,469",131.5
...,...,...,...,...,...,...,...,...
523,201606,인천광역시,중구,산업용,545,"66,732,132","7,837,293,146",117.4
524,201606,인천광역시,중구,심 야,"1,427","1,333,748","82,945,318",62.2
525,201606,인천광역시,중구,일반용,"10,128","74,632,466","9,333,694,612",125.1
526,201606,인천광역시,중구,주택용,"31,395","12,114,063","1,375,685,023",113.6
527,201606,인천광역시,중구,합계,"47,951","158,352,822","19,068,076,011",120.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,인천광역시,전체(시 / 군 / 구),주택용,"710,840","342,893,758","45,660,169,929",133.2
4,201601,인천광역시,전체(시 / 군 / 구),일반용,"130,479","503,412,953","66,216,338,469",131.5
5,201601,인천광역시,전체(시 / 군 / 구),교육용,999,"33,980,611","3,721,592,072",109.5
6,201601,인천광역시,전체(시 / 군 / 구),산업용,"18,479","1,204,660,375","140,202,344,784",116.4
...,...,...,...,...,...,...,...,...
523,201606,인천광역시,중구,산업용,545,"66,732,132","7,837,293,146",117.4
524,201606,인천광역시,중구,심 야,"1,427","1,333,748","82,945,318",62.2
525,201606,인천광역시,중구,일반용,"10,128","74,632,466","9,333,694,612",125.1
526,201606,인천광역시,중구,주택용,"31,395","12,114,063","1,375,685,023",113.6
527,201606,인천광역시,중구,합계,"47,951","158,352,822","19,068,076,011",120.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,인천광역시,전체(시 / 군 / 구),주택용,"710,840","342,893,758","45,660,169,929",133.2
4,201601,인천광역시,전체(시 / 군 / 구),일반용,"130,479","503,412,953","66,216,338,469",131.5
5,201601,인천광역시,전체(시 / 군 / 구),교육용,999,"33,980,611","3,721,592,072",109.5
6,201601,인천광역시,전체(시 / 군 / 구),산업용,"18,479","1,204,660,375","140,202,344,784",116.4
7,201601,인천광역시,전체(시 / 군 / 구),농사용,"21,421","11,160,514","532,804,207",47.7
...,...,...,...,...,...,...,...,...
523,201606,인천광역시,중구,산업용,545,"66,732,132","7,837,293,146",117.4
524,201606,인천광역시,중구,심 야,"1,427","1,333,748","82,945,318",62.2
525,201606,인천광역시,중구,일반용,"10,128","74,632,466","9,333,694,612",125.1
526,201606,인천광역시,중구,주택용,"31,395","12,114,063","1,375,685,023",113.6
527,201606,인천광역시,중구,합계,"47,951","158,352,822","19,068,076,011",120.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201601,인천광역시,전체(시 / 군 / 구),주택용,"710,840","342,893,758","45,660,169,929",133.2
4,201601,인천광역시,전체(시 / 군 / 구),일반용,"130,479","503,412,953","66,216,338,469",131.5
5,201601,인천광역시,전체(시 / 군 / 구),교육용,999,"33,980,611","3,721,592,072",109.5
6,201601,인천광역시,전체(시 / 군 / 구),산업용,"18,479","1,204,660,375","140,202,344,784",116.4
7,201601,인천광역시,전체(시 / 군 / 구),농사용,"21,421","11,160,514","532,804,207",47.7
8,201601,인천광역시,전체(시 / 군 / 구),가로등,"52,984","16,816,421","1,802,041,453",107.2
9,201601,인천광역시,전체(시 / 군 / 구),심 야,"17,787","47,169,875","3,594,192,099",76.2
10,201602,인천광역시,전체(시 / 군 / 구),주택용,"711,833","347,842,062","46,773,859,432",134.5
11,201602,인천광역시,전체(시 / 군 / 구),일반용,"130,618","507,069,163","66,581,624,618",131.3
12,201602,인천광역시,전체(시 / 군 / 구),교육용,997,"33,415,673","3,622,908,189",108.4
13,201602,인천광역시,전체(시 / 군 / 구),산업용,"18,485","1,054,979,205","127,583,921,159",120.9
14,201602,인천광역시,전체(시 / 군 / 구),농사용,"21,401","11,435,982","539,964,541",47.2
15,201602,인천광역시,전체(시 / 군 / 구),가로등,"53,022","15,652,450","1,733,348,950",110.7
16,201602,인천광역시,전체(시 / 군 / 구),심 야,"17,736","52,516,035","3,997,928,345",76.1
17,201603,인천광역시,전체(시 / 군 / 구),주택용,"712,707","310,360,240","37,474,509,663",120.7
18,201603,인천광역시,전체(시 / 군 / 구),일반용,"130,705","442,749,085","53,360,952,409",120.5
19,201603,인천광역시,전체(시 / 군 / 구),교육용,998,"33,802,032","3,350,186,131",99.1
20,201603,인천광역시,전체(시 / 군 / 구),산업용,"18,516","1,180,880,682","115,585,110,896",97.9
21,201603,인천광역시,전체(시 / 군 / 구),농사용,"28,920","10,936,261","516,385,793",47.2
22,201603,인천광역시,전체(시 / 군 / 구),가로등,"53,268","14,227,234","1,612,534,659",113.3
23,201603,인천광역시,전체(시 / 군 / 구),심 야,"17,709","40,545,710","2,743,245,087",67.7
24,201604,인천광역시,전체(시 / 군 / 구),주택용,"714,617","309,553,497","37,177,594,855",120.1
25,201604,인천광역시,전체(시 / 군 / 구),일반용,"130,869","396,115,025","45,366,067,725",114.5
26,201604,인천광역시,전체(시 / 군 / 구),교육용,998,"22,466,098","2,647,452,561",117.8
27,201604,인천광역시,전체(시 / 군 / 구),산업용,"18,532","1,122,394,492","108,212,541,855",96.4
28,201604,인천광역시,전체(시 / 군 / 구),농사용,"26,014","10,776,937","522,847,673",48.5
29,201604,인천광역시,전체(시 / 군 / 구),가로등,"53,385","13,620,523","1,596,994,654",117.2
30,201604,인천광역시,전체(시 / 군 / 구),심 야,"17,671","28,843,052","1,601,564,880",55.5
31,201605,인천광역시,전체(시 / 군 / 구),주택용,"715,673","289,990,499","33,026,130,853",113.9
32,201605,인천광역시,전체(시 / 군 / 구),일반용,"130,957","379,804,318","44,263,016,146",116.5
33,201605,인천광역시,전체(시 / 군 / 구),교육용,998,"20,600,214","2,497,825,431",121.3
34,201605,인천광역시,전체(시 / 군 / 구),산업용,"18,550","1,113,616,820","107,417,579,130",96.5
35,201605,인천광역시,전체(시 / 군 / 구),농사용,"21,710","9,728,698","467,830,128",48.1
36,201605,인천광역시,전체(시 / 군 / 구),가로등,"53,476","12,109,945","1,477,906,385",122.0
37,201605,인천광역시,전체(시 / 군 / 구),심 야,"17,615","18,360,066","1,045,964,740",57.0
38,201606,인천광역시,전체(시 / 군 / 구),주택용,"717,405","297,318,864","35,041,735,312",117.9
39,201606,인천광역시,전체(시 / 군 / 구),일반용,"131,201","419,236,533","56,429,964,903",134.6
40,201606,인천광역시,전체(시 / 군 / 구),교육용,994,"24,736,062","3,563,124,703",144.0
41,201606,인천광역시,전체(시 / 군 / 구),산업용,"18,602","1,126,410,309","134,437,100,339",119.4
42,201606,인천광역시,전체(시 / 군 / 구),농사용,"21,834","9,527,773","465,770,713",48.9
43,201606,인천광역시,전체(시 / 군 / 구),가로등,"53,655","11,386,888","1,434,685,553",126.0
44,201606,인천광역시,전체(시 / 군 / 구),심 야,"17,556","12,410,927","728,034,196",58.7
45,합계,합계,합계,합계,"5,752,216","11,865,513,861","1,346,627,695,620",113.5

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_7372\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201601  인천광역시  일반용  130,479   503,412,953
11  201602  인천광역시  일반용  130,618   507,069,163
18  201603  인천광역시  일반용  130,705   442,749,085
25  201604  인천광역시  일반용  130,869   396,115,025
32  201605  인천광역시  일반용  130,957   379,804,318
39  201606  인천광역시  일반용  131,201   419,236,533

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201601  인천광역시  강화군  일반용   7,304   17,040,226
133  201602  인천광역시  강화군  일반용   7,287   17,949,994
213  201603  인천광역시  강화군  일반용   7,288   14,810,949
293  201604  인천광역시  강화군  일반용   7,298   12,921,854
373  201605  인천광역시  강화군  일반용   7,297   11,131,825
453  201606  인천광역시  강화군  일반용   7,295   11,052,909
61   201601  인천광역시  계양구  일반용  12,503   41,915,284
141  201602  인천광역시  계양구  일반용  12,520   42,370,935
221  201603  인천광역시  계양구  일반용  12,502   36,483,952
301  201604  인천광역시  계양구  일반용  12,491   32,362,238
381  201605  인천광역시  계양구  일반용  12,471   30,934,821
461  201606  인천광역시  계양구  일반용  12,487   35,027,966
69   201601  인천광역시   남구  일반용  20,604   55,410,439
149  201602  인천광역시   남구  일반용  20,611   57,148,959
229  201603  인천광역시   남구  일반용  20,636   49,133,687
309  201604  인천광역시   남구  일반용  20,627   44,080,806
389  201605  인천광역시   남구  일반용  20,585   40,180,492
469  201606  인천광역시   남구  일반용  20,703   44,409,103
77   201601  인천광역시  남동구  일반용  21,882   81,028,150
157  201602  인천광역시  남동구  일반용  21,913   81,669,562
237  201603  인천광역시  남동구  일반용  21,921   70,291,573
317  201604  인천광역시  남동구  일반용  21,950   62,613,402
397  201605  인천광역시  남동구  일반용  21,993   59,834,990
477  201606  인천광역시  남동구  일반용  22,026   67,786,067
85   201601  인천광역시   동구  일반용   3,752   11,733,648
165  201602  인천광역시   동구  일반용   3,761   11,599,867
245  201603  인천광역시   동구  일반용   3,761    9,920,043
325  201604  인천광역시   동구  일반용   3,750    8,413,594
405  201605  인천광역시   동구  일반용   3,751    7,711,191
485  201606  인천광역시   동구  일반용   3,732    8,470,589
93   201601  인천광역시  부평구  일반용  22,201   70,979,557
173  201602  인천광역시  부평구  일반용  22,241   71,873,627
253  201603  인천광역시  부평구  일반용  22,225   61,940,374
333  201604  인천광역시  부평구  일반용  22,204   54,815,107
413  201605  인천광역시  부평구  일반용  22,184   51,889,697
493  201606  인천광역시  부평구  일반용  22,165   58,899,105
101  201601  인천광역시   서구  일반용  20,320   79,569,403
181  201602  인천광역시   서구  일반용  20,377   82,048,500
261  201603  인천광역시   서구  일반용  20,377   71,666,426
341  201604  인천광역시   서구  일반용  20,493   63,620,212
421  201605  인천광역시   서구  일반용  20,580   58,876,946
501  201606  인천광역시   서구  일반용  20,620   64,149,332
109  201601  인천광역시  연수구  일반용   8,199   54,859,889
189  201602  인천광역시  연수구  일반용   8,214   53,473,173
269  201603  인천광역시  연수구  일반용   8,242   47,146,842
349  201604  인천광역시  연수구  일반용   8,238   42,378,712
429  201605  인천광역시  연수구  일반용   8,259   42,976,660
509  201606  인천광역시  연수구  일반용   8,267   48,311,756
117  201601  인천광역시  옹진군  일반용   3,747    9,099,241
197  201602  인천광역시  옹진군  일반용   3,733    9,935,276
277  201603  인천광역시  옹진군  일반용   3,748    8,187,465
357  201604  인천광역시  옹진군  일반용   3,765    7,646,660
437  201605  인천광역시  옹진군  일반용   3,762    6,724,601
517  201606  인천광역시  옹진군  일반용   3,778    6,497,240
125  201601  인천광역시   중구  일반용   9,967   81,777,116
205  201602  인천광역시   중구  일반용   9,961   78,999,270
285  201603  인천광역시   중구  일반용  10,005   73,167,774
365  201604  인천광역시   중구  일반용  10,053   67,262,440
445  201605  인천광역시   중구  일반용  10,075   69,543,095
525  201606  인천광역시   중구  일반용  10,128   74,632,466

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201601  인천광역시  강화군   합계   66,593    58,556,282
135  201602  인천광역시  강화군   합계   66,544    62,196,040
215  201603  인천광역시  강화군   합계   72,441    52,181,352
295  201604  인천광역시  강화군   합계   71,036    44,680,784
375  201605  인천광역시  강화군   합계   67,128    36,794,101
455  201606  인천광역시  강화군   합계   67,377    33,200,188
63   201601  인천광역시  계양구   합계   97,949   119,829,203
143  201602  인천광역시  계양구   합계   98,005   120,264,537
223  201603  인천광역시  계양구   합계   98,355   108,768,524
303  201604  인천광역시  계양구   합계   98,134    99,701,275
383  201605  인천광역시  계양구   합계   98,182    94,615,576
463  201606  인천광역시  계양구   합계   98,326   100,648,242
71   201601  인천광역시   남구   합계  184,820   196,745,785
151  201602  인천광역시   남구   합계  185,064   191,060,343
231  201603  인천광역시   남구   합계  185,329   187,156,592
311  201604  인천광역시   남구   합계  185,683   174,115,845
391  201605  인천광역시   남구   합계  185,855   166,138,910
471  201606  인천광역시   남구   합계  186,367   171,009,957
79   201601  인천광역시  남동구   합계  147,159   367,874,443
159  201602  인천광역시  남동구   합계  147,178   365,603,341
239  201603  인천광역시  남동구   합계  147,413   347,230,300
319  201604  인천광역시  남동구   합계  147,602   319,253,433
399  201605  인천광역시  남동구   합계  147,796   299,234,850
479  201606  인천광역시  남동구   합계  147,860   315,337,376
87   201601  인천광역시   동구   합계   24,123   353,041,741
167  201602  인천광역시   동구   합계   24,069   250,318,086
247  201603  인천광역시   동구   합계   24,044   342,425,821
327  201604  인천광역시   동구   합계   24,032   336,576,630
407  201605  인천광역시   동구   합계   24,024   348,404,542
487  201606  인천광역시   동구   합계   24,026   339,840,132
95   201601  인천광역시  부평구   합계  164,103   222,767,485
175  201602  인천광역시  부평구   합계  164,335   217,582,290
255  201603  인천광역시  부평구   합계  164,470   203,955,665
335  201604  인천광역시  부평구   합계  164,873   187,398,773
415  201605  인천광역시  부평구   합계  164,942   178,601,076
495  201606  인천광역시  부평구   합계  165,314   192,061,896
103  201601  인천광역시   서구   합계  144,155   467,739,339
183  201602  인천광역시   서구   합계  144,618   457,138,760
263  201603  인천광역시   서구   합계  144,913   446,797,051
343  201604  인천광역시   서구   합계  145,362   427,510,393
423  201605  인천광역시   서구   합계  145,800   406,815,646
503  201606  인천광역시   서구   합계  146,228   417,084,069
111  201601  인천광역시  연수구   합계   55,651   181,465,090
191  201602  인천광역시  연수구   합계   55,680   170,279,201
271  201603  인천광역시  연수구   합계   55,739   163,734,092
351  201604  인천광역시  연수구   합계   55,815   145,581,051
431  201605  인천광역시  연수구   합계   55,838   147,752,414
511  201606  인천광역시  연수구   합계   55,900   159,192,950
119  201601  인천광역시  옹진군   합계   21,686    20,276,978
199  201602  인천광역시  옹진군   합계   21,681    23,810,893
279  201603  인천광역시  옹진군   합계   22,637    19,946,525
359  201604  인천광역시  옹진군   합계   22,141    18,806,920
439  201605  인천광역시  옹진군   합계   21,812    13,538,843
519  201606  인천광역시  옹진군   합계   21,898    14,299,724
127  201601  인천광역시   중구   합계   46,750   171,798,161
207  201602  인천광역시   중구   합계   46,918   164,657,079
287  201603  인천광역시   중구   합계   47,482   161,305,322
367  201604  인천광역시   중구   합계   47,408   150,144,520
447  201605  인천광역시   중구   합계   47,602   152,314,602
527  201606  인천광역시   중구   합계   47,951   158,352,822

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[58556282, 62196040, 52181352, 44680784, 36794101, 33200188]
[119829203, 120264537, 108768524, 99701275, 94615576, 100648242]
[196745785, 191060343, 187156592, 174115845, 166138910, 171009957]
[367874443, 365603341, 347230300, 319253433, 299234850, 315337376]
[353041741, 250318086, 342425821, 336576630, 348404542, 339840132]
[222767485, 217582290, 203955665, 187398773, 178601076, 192061896]
[467739339, 457138760, 446797051, 427510393, 406815646, 417084069]
[181465090, 170279201, 163734092, 145581051, 147752414, 159192950]
[20276978, 23810893, 19946525, 18806920, 13538843, 14299724]
[171798161, 164657079, 161305322, 150144520, 152314602, 158352822]
인천광역시 지역별 합계 :  [287608747, 643827357, 1086227432, 2014533743, 1970606952, 1202367185, 2623085258, 968004798, 110679883, 958572506]
인천광역시 고객호수 평균:  [11419, 16359, 30919, 24583, 4008, 27445, 24196, 9295, 3662, 7891]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\4171278030.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201601  인천광역시  강화군   합계  66,593   58,556,282
1          201602  인천광역시  강화군   합계  66,544   62,196,040
2          201603  인천광역시  강화군   합계  72,441   52,181,352
3          201604  인천광역시  강화군   합계  71,036   44,680,784
4          201605  인천광역시  강화군   합계  67,128   36,794,101
..            ...    ...  ...  ...      ...          ...
65  201601-201606  인천광역시  부평구   합계    27445   1202367185
66  201601-201606  인천광역시   서구   합계    24196   2623085258
67  201601-201606  인천광역시  연수구   합계     9295    968004798
68  201601-201606  인천광역시  옹진군   합계     3662    110679883
69  201601-201606  인천광역시   중구   합계     7891    958572506

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201601-201606']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201601-201606  인천광역시  강화군   합계   11419   287608747
61  201601-201606  인천광역시  계양구   합계   16359   643827357
62  201601-201606  인천광역시   남구   합계   30919  1086227432
63  201601-201606  인천광역시  남동구   합계   24583  2014533743
64  201601-201606  인천광역시   동구   합계    4008  1970606952
65  201601-201606  인천광역시  부평구   합계   27445  1202367185
66  201601-201606  인천광역시   서구   합계   24196  2623085258
67  201601-201606  인천광역시  연수구   합계    9295   968004798
68  201601-201606  인천광역시  옹진군   합계    3662   110679883
69  201601-201606  인천광역시   중구   합계    7891   958572506

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201601  인천광역시  강화군  일반용   7,304   17,040,226
133  201602  인천광역시  강화군  일반용   7,287   17,949,994
213  201603  인천광역시  강화군  일반용   7,288   14,810,949
293  201604  인천광역시  강화군  일반용   7,298   12,921,854
373  201605  인천광역시  강화군  일반용   7,297   11,131,825
453  201606  인천광역시  강화군  일반용   7,295   11,052,909
61   201601  인천광역시  계양구  일반용  12,503   41,915,284
141  201602  인천광역시  계양구  일반용  12,520   42,370,935
221  201603  인천광역시  계양구  일반용  12,502   36,483,952
301  201604  인천광역시  계양구  일반용  12,491   32,362,238
381  201605  인천광역시  계양구  일반용  12,471   30,934,821
461  201606  인천광역시  계양구  일반용  12,487   35,027,966
69   201601  인천광역시   남구  일반용  20,604   55,410,439
149  201602  인천광역시   남구  일반용  20,611   57,148,959
229  201603  인천광역시   남구  일반용  20,636   49,133,687
309  201604  인천광역시   남구  일반용  20,627   44,080,806
389  201605  인천광역시   남구  일반용  20,585   40,180,492
469  201606  인천광역시   남구  일반용  20,703   44,409,103
77   201601  인천광역시  남동구  일반용  21,882   81,028,150
157  201602  인천광역시  남동구  일반용  21,913   81,669,562
237  201603  인천광역시  남동구  일반용  21,921   70,291,573
317  201604  인천광역시  남동구  일반용  21,950   62,613,402
397  201605  인천광역시  남동구  일반용  21,993   59,834,990
477  201606  인천광역시  남동구  일반용  22,026   67,786,067
85   201601  인천광역시   동구  일반용   3,752   11,733,648
165  201602  인천광역시   동구  일반용   3,761   11,599,867
245  201603  인천광역시   동구  일반용   3,761    9,920,043
325  201604  인천광역시   동구  일반용   3,750    8,413,594
405  201605  인천광역시   동구  일반용   3,751    7,711,191
485  201606  인천광역시   동구  일반용   3,732    8,470,589
93   201601  인천광역시  부평구  일반용  22,201   70,979,557
173  201602  인천광역시  부평구  일반용  22,241   71,873,627
253  201603  인천광역시  부평구  일반용  22,225   61,940,374
333  201604  인천광역시  부평구  일반용  22,204   54,815,107
413  201605  인천광역시  부평구  일반용  22,184   51,889,697
493  201606  인천광역시  부평구  일반용  22,165   58,899,105
101  201601  인천광역시   서구  일반용  20,320   79,569,403
181  201602  인천광역시   서구  일반용  20,377   82,048,500
261  201603  인천광역시   서구  일반용  20,377   71,666,426
341  201604  인천광역시   서구  일반용  20,493   63,620,212
421  201605  인천광역시   서구  일반용  20,580   58,876,946
501  201606  인천광역시   서구  일반용  20,620   64,149,332
109  201601  인천광역시  연수구  일반용   8,199   54,859,889
189  201602  인천광역시  연수구  일반용   8,214   53,473,173
269  201603  인천광역시  연수구  일반용   8,242   47,146,842
349  201604  인천광역시  연수구  일반용   8,238   42,378,712
429  201605  인천광역시  연수구  일반용   8,259   42,976,660
509  201606  인천광역시  연수구  일반용   8,267   48,311,756
117  201601  인천광역시  옹진군  일반용   3,747    9,099,241
197  201602  인천광역시  옹진군  일반용   3,733    9,935,276
277  201603  인천광역시  옹진군  일반용   3,748    8,187,465
357  201604  인천광역시  옹진군  일반용   3,765    7,646,660
437  201605  인천광역시  옹진군  일반용   3,762    6,724,601
517  201606  인천광역시  옹진군  일반용   3,778    6,497,240
125  201601  인천광역시   중구  일반용   9,967   81,777,116
205  201602  인천광역시   중구  일반용   9,961   78,999,270
285  201603  인천광역시   중구  일반용  10,005   73,167,774
365  201604  인천광역시   중구  일반용  10,053   67,262,440
445  201605  인천광역시   중구  일반용  10,075   69,543,095
525  201606  인천광역시   중구  일반용  10,128   74,632,466

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[17040226, 17949994, 14810949, 12921854, 11131825, 11052909]
[41915284, 42370935, 36483952, 32362238, 30934821, 35027966]
[55410439, 57148959, 49133687, 44080806, 40180492, 44409103]
[81028150, 81669562, 70291573, 62613402, 59834990, 67786067]
[11733648, 11599867, 9920043, 8413594, 7711191, 8470589]
[70979557, 71873627, 61940374, 54815107, 51889697, 58899105]
[79569403, 82048500, 71666426, 63620212, 58876946, 64149332]
[54859889, 53473173, 47146842, 42378712, 42976660, 48311756]
[9099241, 9935276, 8187465, 7646660, 6724601, 6497240]
[81777116, 78999270, 73167774, 67262440, 69543095, 74632466]
인천광역시 지역별 일반용 합계 :  [84907757, 219095196, 290363486, 423223744, 57848932, 370397467, 419930819, 289147032, 48090483, 445382161]
인천광역시 고객호수 평균:  [7294, 12495, 20627, 21947, 3751, 22203, 20461, 8236, 3755, 10031]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_7372\2328676442.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201601-201606'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201601  인천광역시  강화군  일반용  7,304   17,040,226
1          201602  인천광역시  강화군  일반용  7,287   17,949,994
2          201603  인천광역시  강화군  일반용  7,288   14,810,949
3          201604  인천광역시  강화군  일반용  7,298   12,921,854
4          201605  인천광역시  강화군  일반용  7,297   11,131,825
..            ...    ...  ...  ...     ...          ...
65  201601-201606  인천광역시  부평구  일반용   22203    370397467
66  201601-201606  인천광역시   서구  일반용   20461    419930819
67  201601-201606  인천광역시  연수구  일반용    8236    289147032
68  201601-201606  인천광역시  옹진군  일반용    3755     48090483
69  201601-201606  인천광역시   중구  일반용   10031    445382161

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201601-201606']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201601-201606  인천광역시  강화군  일반용    7294   84907757
61  201601-201606  인천광역시  계양구  일반용   12495  219095196
62  201601-201606  인천광역시   남구  일반용   20627  290363486
63  201601-201606  인천광역시  남동구  일반용   21947  423223744
64  201601-201606  인천광역시   동구  일반용    3751   57848932
65  201601-201606  인천광역시  부평구  일반용   22203  370397467
66  201601-201606  인천광역시   서구  일반용   20461  419930819
67  201601-201606  인천광역시  연수구  일반용    8236  289147032
68  201601-201606  인천광역시  옹진군  일반용    3755   48090483
69  201601-201606  인천광역시   중구  일반용   10031  445382161

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201601-201606  인천광역시  강화군  일반용    7294    84907757
60  201601-201606  인천광역시  강화군   합계   11419   287608747
61  201601-201606  인천광역시  계양구  일반용   12495   219095196
61  201601-201606  인천광역시  계양구   합계   16359   643827357
62  201601-201606  인천광역시   남구  일반용   20627   290363486
62  201601-201606  인천광역시   남구   합계   30919  1086227432
63  201601-201606  인천광역시  남동구  일반용   21947   423223744
63  201601-201606  인천광역시  남동구   합계   24583  2014533743
64  201601-201606  인천광역시   동구  일반용    3751    57848932
64  201601-201606  인천광역시   동구   합계    4008  1970606952
65  201601-201606  인천광역시  부평구  일반용   22203   370397467
65  201601-201606  인천광역시  부평구   합계   27445  1202367185
66  201601-201606  인천광역시   서구  일반용   20461   419930819
66  201601-201606  인천광역시   서구   합계   24196  2623085258
67  201601-201606  인천광역시  연수구   합계    9295   968004798
67  201601-201606  인천광역시  연수구  일반용    8236   289147032
68  201601-201606  인천광역시  옹진군   합계    3662   110679883
68  201601-201606  인천광역시  옹진군  일반용    3755    48090483
69  201601-201606  인천광역시   중구  일반용   10031   445382161
69  201601-201606  인천광역시   중구   합계    7891   958572506

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[84907757,
 219095196,
 290363486,
 423223744,
 57848932,
 370397467,
 419930819,
 289147032,
 48090483,
 445382161]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[287608747,
 643827357,
 1086227432,
 2014533743,
 1970606952,
 1202367185,
 2623085258,
 968004798,
 110679883,
 958572506]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[29.52, 34.03, 26.73, 21.01, 2.94, 30.81, 16.01, 29.87, 43.45, 46.46]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   30
1   34
2   27
3   21
4    3
5   31
6   16
7   30
8   43
9   46
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  30
1  계양구  일반용  34
2   남구  일반용  27
3  남동구  일반용  21
4   동구  일반용   3
5  부평구  일반용  31
6   서구  일반용  16
7  연수구  일반용  30
8  옹진군  일반용  43
9   중구  일반용  46

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201601-201606  인천광역시  강화군  일반용    7294    84907757  30
1   201601-201606  인천광역시  강화군   합계   11419   287608747 NaN
2   201601-201606  인천광역시  계양구  일반용   12495   219095196  34
3   201601-201606  인천광역시  계양구   합계   16359   643827357 NaN
4   201601-201606  인천광역시   남구  일반용   20627   290363486  27
5   201601-201606  인천광역시   남구   합계   30919  1086227432 NaN
6   201601-201606  인천광역시  남동구  일반용   21947   423223744  21
7   201601-201606  인천광역시  남동구   합계   24583  2014533743 NaN
8   201601-201606  인천광역시   동구  일반용    3751    57848932   3
9   201601-201606  인천광역시   동구   합계    4008  1970606952 NaN
10  201601-201606  인천광역시  부평구  일반용   22203   370397467  31
11  201601-201606  인천광역시  부평구   합계   27445  1202367185 NaN
12  201601-201606  인천광역시   서구  일반용   20461   419930819  16
13  201601-201606  인천광역시   서구   합계   24196  2623085258 NaN
15  201601-201606  인천광역시  연수구  일반용    8236   289147032  30
14  201601-201606  인천광역시  연수구   합계    9295   968004798 NaN
17  201601-201606  인천광역시  옹진군  일반용    3755    48090483  43
16  201601-201606  인천광역시  옹진군   합계    3662   110679883 NaN
18  201601-201606  인천광역시   중구  일반용   10031   445382161  46
19  201601-201606  인천광역시   중구   합계    7891   958572506 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1601-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)