In [36]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [37]:
df = pd.read_csv('강원도_계약종별_전력사용량_월별_15하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 강원도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 07 월 ~ 2015년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,강원도,전체(시 / 군 / 구),주택용,"536,281","150,659,855","16,715,574,070",110.9
4,201507,강원도,전체(시 / 군 / 구),일반용,"134,453","313,717,483","47,497,302,799",151.4
...,...,...,...,...,...,...,...,...
907,201512,강원도,횡성군,산업용,578,"14,322,194","1,860,920,223",129.9
908,201512,강원도,횡성군,심 야,"6,524","15,145,409","1,133,190,285",74.8
909,201512,강원도,횡성군,일반용,"4,733","13,135,197","1,733,589,059",132
910,201512,강원도,횡성군,주택용,"21,296","4,753,892","602,813,563",126.8
911,201512,강원도,횡성군,합계,"48,225","54,258,037","5,776,990,153",106.5

In [38]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,강원도,전체(시 / 군 / 구),주택용,"536,281","150,659,855","16,715,574,070",110.9
4,201507,강원도,전체(시 / 군 / 구),일반용,"134,453","313,717,483","47,497,302,799",151.4
5,201507,강원도,전체(시 / 군 / 구),교육용,"1,046","20,100,927","2,858,707,945",142.2
6,201507,강원도,전체(시 / 군 / 구),산업용,"12,356","624,538,663","72,544,540,252",116.2
...,...,...,...,...,...,...,...,...
907,201512,강원도,횡성군,산업용,578,"14,322,194","1,860,920,223",129.9
908,201512,강원도,횡성군,심 야,"6,524","15,145,409","1,133,190,285",74.8
909,201512,강원도,횡성군,일반용,"4,733","13,135,197","1,733,589,059",132
910,201512,강원도,횡성군,주택용,"21,296","4,753,892","602,813,563",126.8
911,201512,강원도,횡성군,합계,"48,225","54,258,037","5,776,990,153",106.5

In [39]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [40]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,강원도,전체(시 / 군 / 구),주택용,"536,281","150,659,855","16,715,574,070",110.9
4,201507,강원도,전체(시 / 군 / 구),일반용,"134,453","313,717,483","47,497,302,799",151.4
5,201507,강원도,전체(시 / 군 / 구),교육용,"1,046","20,100,927","2,858,707,945",142.2
6,201507,강원도,전체(시 / 군 / 구),산업용,"12,356","624,538,663","72,544,540,252",116.2
7,201507,강원도,전체(시 / 군 / 구),농사용,"84,966","41,485,013","2,067,970,468",49.8
...,...,...,...,...,...,...,...,...
907,201512,강원도,횡성군,산업용,578,"14,322,194","1,860,920,223",129.9
908,201512,강원도,횡성군,심 야,"6,524","15,145,409","1,133,190,285",74.8
909,201512,강원도,횡성군,일반용,"4,733","13,135,197","1,733,589,059",132
910,201512,강원도,횡성군,주택용,"21,296","4,753,892","602,813,563",126.8
911,201512,강원도,횡성군,합계,"48,225","54,258,037","5,776,990,153",106.5

In [41]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201507,강원도,전체(시 / 군 / 구),주택용,"536,281","150,659,855","16,715,574,070",110.9
4,201507,강원도,전체(시 / 군 / 구),일반용,"134,453","313,717,483","47,497,302,799",151.4
5,201507,강원도,전체(시 / 군 / 구),교육용,"1,046","20,100,927","2,858,707,945",142.2
6,201507,강원도,전체(시 / 군 / 구),산업용,"12,356","624,538,663","72,544,540,252",116.2
7,201507,강원도,전체(시 / 군 / 구),농사용,"84,966","41,485,013","2,067,970,468",49.8
8,201507,강원도,전체(시 / 군 / 구),가로등,"99,147","12,864,031","1,552,335,913",120.7
9,201507,강원도,전체(시 / 군 / 구),심 야,"94,681","46,186,486","2,572,228,182",55.7
10,201508,강원도,전체(시 / 군 / 구),주택용,"537,617","177,075,645","21,857,687,796",123.4
11,201508,강원도,전체(시 / 군 / 구),일반용,"134,858","372,174,951","53,353,265,376",143.4
12,201508,강원도,전체(시 / 군 / 구),교육용,"1,046","20,032,641","2,849,884,004",142.3
13,201508,강원도,전체(시 / 군 / 구),산업용,"12,411","611,891,274","68,802,820,961",112.4
14,201508,강원도,전체(시 / 군 / 구),농사용,"85,733","50,030,213","2,453,165,611",49.0
15,201508,강원도,전체(시 / 군 / 구),가로등,"99,539","13,938,942","1,624,792,809",116.6
16,201508,강원도,전체(시 / 군 / 구),심 야,"94,570","41,022,475","2,291,436,886",55.9
17,201509,강원도,전체(시 / 군 / 구),주택용,"539,159","161,083,401","18,262,209,078",113.4
18,201509,강원도,전체(시 / 군 / 구),일반용,"135,478","324,905,003","42,901,245,385",132.0
19,201509,강원도,전체(시 / 군 / 구),교육용,"1,046","21,709,411","2,658,029,273",122.4
20,201509,강원도,전체(시 / 군 / 구),산업용,"12,435","623,787,954","57,869,626,913",92.8
21,201509,강원도,전체(시 / 군 / 구),농사용,"86,454","56,085,931","2,720,375,851",48.5
22,201509,강원도,전체(시 / 군 / 구),가로등,"99,821","14,493,988","1,653,235,795",114.1
23,201509,강원도,전체(시 / 군 / 구),심 야,"94,561","43,317,900","2,421,872,230",55.9
24,201510,강원도,전체(시 / 군 / 구),주택용,"540,310","150,796,992","16,611,153,861",110.2
25,201510,강원도,전체(시 / 군 / 구),일반용,"135,764","286,099,248","33,798,762,683",118.1
26,201510,강원도,전체(시 / 군 / 구),교육용,"1,043","18,540,060","2,097,497,316",113.1
27,201510,강원도,전체(시 / 군 / 구),산업용,"12,466","650,034,319","59,149,090,885",91.0
28,201510,강원도,전체(시 / 군 / 구),농사용,"86,765","49,904,802","2,499,093,526",50.1
29,201510,강원도,전체(시 / 군 / 구),가로등,"100,028","15,389,692","1,672,530,351",108.7
30,201510,강원도,전체(시 / 군 / 구),심 야,"94,504","73,025,521","4,017,062,795",55.0
31,201511,강원도,전체(시 / 군 / 구),주택용,"541,904","164,025,728","19,651,157,941",119.8
32,201511,강원도,전체(시 / 군 / 구),일반용,"136,317","313,814,571","40,773,428,420",129.9
33,201511,강원도,전체(시 / 군 / 구),교육용,"1,046","23,617,425","2,686,570,961",113.8
34,201511,강원도,전체(시 / 군 / 구),산업용,"12,506","589,781,419","66,281,245,326",112.4
35,201511,강원도,전체(시 / 군 / 구),농사용,"109,019","68,008,471","2,908,784,868",42.8
36,201511,강원도,전체(시 / 군 / 구),가로등,"100,166","16,063,597","2,551,217,936",158.8
37,201511,강원도,전체(시 / 군 / 구),심 야,"94,530","139,821,988","8,803,394,195",63.0
38,201512,강원도,전체(시 / 군 / 구),주택용,"542,959","171,321,446","21,327,325,820",124.5
39,201512,강원도,전체(시 / 군 / 구),일반용,"136,858","377,719,618","50,595,957,053",134.0
40,201512,강원도,전체(시 / 군 / 구),교육용,"1,046","33,420,041","3,708,630,245",111.0
41,201512,강원도,전체(시 / 군 / 구),산업용,"12,532","629,579,532","71,619,907,010",113.8
42,201512,강원도,전체(시 / 군 / 구),농사용,"86,937","46,112,191","2,352,458,436",51.0
43,201512,강원도,전체(시 / 군 / 구),가로등,"100,414","16,518,922","892,806,931",54.0
44,201512,강원도,전체(시 / 군 / 구),심 야,"94,516","214,629,782","16,118,127,908",75.1
45,합계,합계,합계,합계,"5,839,288","7,789,327,552","857,644,512,064",110.1

In [42]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_2580\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)      사용량(kWh)
4   201507  강원도  일반용  134,453   313,717,483
11  201508  강원도  일반용  134,858   372,174,951
18  201509  강원도  일반용  135,478   324,905,003
25  201510  강원도  일반용  135,764   286,099,248
32  201511  강원도  일반용  136,317   313,814,571
39  201512  강원도  일반용  136,858   377,719,618

In [43]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [44]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [45]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  강원도  강릉시  일반용  18,046   35,334,097
197  201508  강원도  강릉시  일반용  18,118   43,967,374
341  201509  강원도  강릉시  일반용  18,183   39,983,753
485  201510  강원도  강릉시  일반용  18,206   34,026,270
629  201511  강원도  강릉시  일반용  18,249   36,495,774
..      ...  ...  ...  ...      ...          ...
333  201508  강원도  횡성군  일반용   4,679   10,827,713
477  201509  강원도  횡성군  일반용   4,706    9,403,778
621  201510  강원도  횡성군  일반용   4,728    8,732,765
765  201511  강원도  횡성군  일반용   4,727    9,741,295
909  201512  강원도  횡성군  일반용   4,733   13,135,197

[108 rows x 6 columns]

In [46]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'강원도'

In [47]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강릉시',
 '고성군',
 '동해시',
 '삼척시',
 '속초시',
 '양구군',
 '양양군',
 '영월군',
 '원주시',
 '인제군',
 '정선군',
 '철원군',
 '춘천시',
 '태백시',
 '평창군',
 '홍천군',
 '화천군',
 '횡성군']

In [48]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201507  강원도  강릉시   합계  123,636   148,039,407
199  201508  강원도  강릉시   합계  123,971   161,289,014
343  201509  강원도  강릉시   합계  124,375   156,729,077
487  201510  강원도  강릉시   합계  124,577   148,384,879
631  201511  강원도  강릉시   합계  125,107   153,192,195
..      ...  ...  ...  ...       ...           ...
335  201508  강원도  횡성군   합계   47,620    39,140,473
479  201509  강원도  횡성군   합계   47,816    36,792,215
623  201510  강원도  횡성군   합계   47,993    37,623,708
767  201511  강원도  횡성군   합계   50,115    45,770,650
911  201512  강원도  횡성군   합계   48,225    54,258,037

[108 rows x 6 columns]

In [49]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[148039407, 161289014, 156729077, 148384879, 153192195, 169113964]
[19866692, 22788118, 21475084, 20442844, 23730101, 26855134]
[255057632, 261848014, 266164477, 278281241, 228971780, 254254972]
[104104196, 103681614, 107996453, 113877692, 115106534, 129738620]
[33273009, 39894385, 36159686, 33183964, 36811523, 41688261]
[12195087, 13488664, 13326018, 13861967, 19327251, 20411847]
[17319152, 20865223, 19483997, 18495037, 21938971, 24173532]
[89421288, 88726178, 85630122, 91249899, 94355767, 97387682]
[169784013, 179460484, 170858118, 161548750, 185889530, 213506388]
[19315310, 21281632, 20819633, 21973763, 26758919, 31344865]
[40093492, 42212797, 39555829, 41959876, 44863482, 55590519]
[28652962, 31584940, 29294739, 29923042, 43684226, 44775594]
[115464894, 128354669, 118190000, 107513067, 124130263, 143766857]
[23751418, 23747350, 23906617, 24821805, 26632623, 29649222]
[35465517, 38868921, 35938630, 39371981, 48292922, 64167216]
[46533267, 52441263, 47124311, 45572655, 56186837, 65897201]
[14530951, 16492402, 15938582, 15704464, 19489625, 22721621]
[36684171, 39140473, 36792215, 37623708, 45770650, 54258037]
강원도 지역별 합계 :  [936748536, 135157973, 1544578116, 674505109, 221010828, 92610834, 122275912, 546770936, 1081047283, 141494122, 264275995, 207915503, 737419750, 152509035, 262105187, 313755534, 104877645, 250269254]
강원도 고객호수 평균:  [20741, 4570, 7819, 8501, 6322, 3545, 4703, 6346, 23804, 5405, 6103, 6830, 22193, 4595, 7961, 10974, 3749, 8032]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [50]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1527473725.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201507  강원도  강릉시   합계  123,636   148,039,407
1           201508  강원도  강릉시   합계  123,971   161,289,014
2           201509  강원도  강릉시   합계  124,375   156,729,077
3           201510  강원도  강릉시   합계  124,577   148,384,879
4           201511  강원도  강릉시   합계  125,107   153,192,195
..             ...  ...  ...  ...       ...           ...
121  201507-201512  강원도  태백시   합계      4595     152509035
122  201507-201512  강원도  평창군   합계      7961     262105187
123  201507-201512  강원도  홍천군   합계     10974     313755534
124  201507-201512  강원도  화천군   합계      3749     104877645
125  201507-201512  강원도  횡성군   합계      8032     250269254

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [51]:
Hap = Hap.loc[Hap['년월'] == '201507-201512']
Hap

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201507-201512  강원도  강릉시   합계   20741   936748536
109  201507-201512  강원도  고성군   합계    4570   135157973
110  201507-201512  강원도  동해시   합계    7819  1544578116
111  201507-201512  강원도  삼척시   합계    8501   674505109
112  201507-201512  강원도  속초시   합계    6322   221010828
113  201507-201512  강원도  양구군   합계    3545    92610834
114  201507-201512  강원도  양양군   합계    4703   122275912
115  201507-201512  강원도  영월군   합계    6346   546770936
116  201507-201512  강원도  원주시   합계   23804  1081047283
117  201507-201512  강원도  인제군   합계    5405   141494122
118  201507-201512  강원도  정선군   합계    6103   264275995
119  201507-201512  강원도  철원군   합계    6830   207915503
120  201507-201512  강원도  춘천시   합계   22193   737419750
121  201507-201512  강원도  태백시   합계    4595   152509035
122  201507-201512  강원도  평창군   합계    7961   262105187
123  201507-201512  강원도  홍천군   합계   10974   313755534
124  201507-201512  강원도  화천군   합계    3749   104877645
125  201507-201512  강원도  횡성군   합계    8032   250269254

In [52]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [53]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [54]:
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201507  강원도  강릉시  일반용  18,046   35,334,097
197  201508  강원도  강릉시  일반용  18,118   43,967,374
341  201509  강원도  강릉시  일반용  18,183   39,983,753
485  201510  강원도  강릉시  일반용  18,206   34,026,270
629  201511  강원도  강릉시  일반용  18,249   36,495,774
..      ...  ...  ...  ...      ...          ...
333  201508  강원도  횡성군  일반용   4,679   10,827,713
477  201509  강원도  횡성군  일반용   4,706    9,403,778
621  201510  강원도  횡성군  일반용   4,728    8,732,765
765  201511  강원도  횡성군  일반용   4,727    9,741,295
909  201512  강원도  횡성군  일반용   4,733   13,135,197

[108 rows x 6 columns]

In [55]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [56]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[35334097, 43967374, 39983753, 34026270, 36495774, 40829361]
[9127393, 11744464, 9846788, 8714346, 9238901, 10438213]
[15725809, 19669933, 18274722, 14723788, 15885329, 18178362]
[11584039, 14372373, 12657787, 11619568, 12548753, 14454479]
[18081703, 23241653, 19859267, 17217931, 18079046, 19998313]
[5324697, 6236576, 5721777, 5352385, 5983780, 7184024]
[8122575, 10767950, 9266563, 8035229, 8801328, 9570182]
[5615572, 6964688, 6170669, 5266638, 5828872, 6408487]
[57208566, 65329192, 57111180, 48446991, 52967075, 63517722]
[9357222, 11044664, 9535132, 9100684, 10569226, 12522521]
[13686567, 15603701, 12586803, 12595744, 14890075, 21769889]
[11127669, 12686206, 10933795, 10221307, 11848272, 14634008]
[54605894, 61985966, 55606615, 47553299, 50037562, 57203952]
[6493576, 7497546, 6817211, 6412712, 6979665, 7877921]
[16000501, 18285811, 14743901, 15267069, 18388707, 28380511]
[19514796, 23119160, 18199303, 15579771, 17411253, 22067312]
[7381524, 8829981, 8185959, 7232751, 8119658, 9549164]
[9425283, 10827713, 9403778, 8732765, 9741295, 13135197]
강원도 지역별 일반용 합계 :  [230636629, 59110105, 102457943, 77236999, 116477913, 35803239, 54563827, 36254926, 344580726, 62129449, 91132779, 71451257, 326993288, 42078631, 111066500, 115891595, 49299037, 61266031]
강원도 고객호수 평균:  [18186, 3739, 6812, 6175, 7682, 2437, 3941, 4038, 23208, 4331, 4893, 4687, 19874, 4094, 5926, 7804, 3080, 4708]

In [57]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [58]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [59]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [60]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_2580\1277283340.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201507-201512'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201507  강원도  강릉시  일반용  18,046   35,334,097
1           201508  강원도  강릉시  일반용  18,118   43,967,374
2           201509  강원도  강릉시  일반용  18,183   39,983,753
3           201510  강원도  강릉시  일반용  18,206   34,026,270
4           201511  강원도  강릉시  일반용  18,249   36,495,774
..             ...  ...  ...  ...      ...          ...
121  201507-201512  강원도  태백시  일반용     4094     42078631
122  201507-201512  강원도  평창군  일반용     5926    111066500
123  201507-201512  강원도  홍천군  일반용     7804    115891595
124  201507-201512  강원도  화천군  일반용     3080     49299037
125  201507-201512  강원도  횡성군  일반용     4708     61266031

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [61]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201507-201512']
GyeonGiHap2

                년월   시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201507-201512  강원도  강릉시  일반용   18186  230636629
109  201507-201512  강원도  고성군  일반용    3739   59110105
110  201507-201512  강원도  동해시  일반용    6812  102457943
111  201507-201512  강원도  삼척시  일반용    6175   77236999
112  201507-201512  강원도  속초시  일반용    7682  116477913
113  201507-201512  강원도  양구군  일반용    2437   35803239
114  201507-201512  강원도  양양군  일반용    3941   54563827
115  201507-201512  강원도  영월군  일반용    4038   36254926
116  201507-201512  강원도  원주시  일반용   23208  344580726
117  201507-201512  강원도  인제군  일반용    4331   62129449
118  201507-201512  강원도  정선군  일반용    4893   91132779
119  201507-201512  강원도  철원군  일반용    4687   71451257
120  201507-201512  강원도  춘천시  일반용   19874  326993288
121  201507-201512  강원도  태백시  일반용    4094   42078631
122  201507-201512  강원도  평창군  일반용    5926  111066500
123  201507-201512  강원도  홍천군  일반용    7804  115891595
124  201507-201512  강원도  화천군  일반용    3080   49299037
125  201507-201512  강원도  횡성군  일반용    4708   61266031

In [62]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201507-201512  강원도  강릉시  일반용   18186   230636629
108  201507-201512  강원도  강릉시   합계   20741   936748536
109  201507-201512  강원도  고성군  일반용    3739    59110105
109  201507-201512  강원도  고성군   합계    4570   135157973
110  201507-201512  강원도  동해시  일반용    6812   102457943
110  201507-201512  강원도  동해시   합계    7819  1544578116
111  201507-201512  강원도  삼척시   합계    8501   674505109
111  201507-201512  강원도  삼척시  일반용    6175    77236999
112  201507-201512  강원도  속초시   합계    6322   221010828
112  201507-201512  강원도  속초시  일반용    7682   116477913
113  201507-201512  강원도  양구군  일반용    2437    35803239
113  201507-201512  강원도  양구군   합계    3545    92610834
114  201507-201512  강원도  양양군   합계    4703   122275912
114  201507-201512  강원도  양양군  일반용    3941    54563827
115  201507-201512  강원도  영월군  일반용    4038    36254926
115  201507-201512  강원도  영월군   합계    6346   546770936
116  201507-201512  강원도  원주시  일반용   23208   344580726
116  201507-201512  강원도  원주시   합계   23804  1081047283
117  201507-201512  강원도  인제군  일반용    4331    62129449
117  201507-201512  강원도  인제군   합계    5405   141494122
118  201507-201512  강원도  정선군   합계    6103   264275995
118  201507-201512  강원도  정선군  일반용    4893    91132779
119  201507-201512  강원도  철원군   합계    6830   207915503
119  201507-201512  강원도  철원군  일반용    4687    71451257
120  201507-201512  강원도  춘천시  일반용   19874   326993288
120  201507-201512  강원도  춘천시   합계   22193   737419750
121  201507-201512  강원도  태백시   합계    4595   152509035
121  201507-201512  강원도  태백시  일반용    4094    42078631
122  201507-201512  강원도  평창군   합계    7961   262105187
122  201507-201512  강원도  평창군  일반용    5926   111066500
123  201507-201512  강원도  홍천군   합계   10974   313755534
123  201507-201512  강원도  홍천군  일반용    7804   115891595
124  201507-201512  강원도  화천군   합계    3749   104877645
124  201507-201512  강원도  화천군  일반용    3080    49299037
125  201507-201512  강원도  횡성군  일반용    4708    61266031
125  201507-201512  강원도  횡성군   합계    8032   250269254

In [63]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[230636629,
 59110105,
 102457943,
 77236999,
 116477913,
 35803239,
 54563827,
 36254926,
 344580726,
 62129449,
 91132779,
 71451257,
 326993288,
 42078631,
 111066500,
 115891595,
 49299037,
 61266031]

In [64]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[936748536,
 135157973,
 1544578116,
 674505109,
 221010828,
 92610834,
 122275912,
 546770936,
 1081047283,
 141494122,
 264275995,
 207915503,
 737419750,
 152509035,
 262105187,
 313755534,
 104877645,
 250269254]

In [65]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[24.62, 43.73, 6.63, 11.45, 52.7, 38.66, 44.62, 6.63, 31.87, 43.91, 34.48, 34.37, 44.34, 27.59, 42.37, 36.94, 47.01, 24.48]

In [66]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    25
1    44
2     7
3    11
4    53
5    39
6    45
7     7
8    32
9    44
10   34
11   34
12   44
13   28
14   42
15   37
16   47
17   24
dtype: float64

In [67]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강릉시  일반용  25
1   고성군  일반용  44
2   동해시  일반용   7
3   삼척시  일반용  11
4   속초시  일반용  53
5   양구군  일반용  39
6   양양군  일반용  45
7   영월군  일반용   7
8   원주시  일반용  32
9   인제군  일반용  44
10  정선군  일반용  34
11  철원군  일반용  34
12  춘천시  일반용  44
13  태백시  일반용  28
14  평창군  일반용  42
15  홍천군  일반용  37
16  화천군  일반용  47
17  횡성군  일반용  24

In [68]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201507-201512  강원도  강릉시  일반용   18186   230636629  25
1   201507-201512  강원도  강릉시   합계   20741   936748536 NaN
2   201507-201512  강원도  고성군  일반용    3739    59110105  44
3   201507-201512  강원도  고성군   합계    4570   135157973 NaN
4   201507-201512  강원도  동해시  일반용    6812   102457943   7
5   201507-201512  강원도  동해시   합계    7819  1544578116 NaN
7   201507-201512  강원도  삼척시  일반용    6175    77236999  11
6   201507-201512  강원도  삼척시   합계    8501   674505109 NaN
9   201507-201512  강원도  속초시  일반용    7682   116477913  53
8   201507-201512  강원도  속초시   합계    6322   221010828 NaN
10  201507-201512  강원도  양구군  일반용    2437    35803239  39
11  201507-201512  강원도  양구군   합계    3545    92610834 NaN
13  201507-201512  강원도  양양군  일반용    3941    54563827  45
12  201507-201512  강원도  양양군   합계    4703   122275912 NaN
14  201507-201512  강원도  영월군  일반용    4038    36254926   7
15  201507-201512  강원도  영월군   합계    6346   546770936 NaN
16  201507-201512  강원도  원주시  일반용   23208   344580726  32
17  201507-201512  강원도  원주시   합계   23804  1081047283 NaN
18  201507-201512  강원도  인제군  일반용    4331    62129449  44
19  201507-201512  강원도  인제군   합계    5405   141494122 NaN
21  201507-201512  강원도  정선군  일반용    4893    91132779  34
20  201507-201512  강원도  정선군   합계    6103   264275995 NaN
23  201507-201512  강원도  철원군  일반용    4687    71451257  34
22  201507-201512  강원도  철원군   합계    6830   207915503 NaN
24  201507-201512  강원도  춘천시  일반용   19874   326993288  44
25  201507-201512  강원도  춘천시   합계   22193   737419750 NaN
27  201507-201512  강원도  태백시  일반용    4094    42078631  28
26  201507-201512  강원도  태백시   합계    4595   152509035 NaN
29  201507-201512  강원도  평창군  일반용    5926   111066500  42
28  201507-201512  강원도  평창군   합계    7961   262105187 NaN
31  201507-201512  강원도  홍천군  일반용    7804   115891595  37
30  201507-201512  강원도  홍천군   합계   10974   313755534 NaN
33  201507-201512  강원도  화천군  일반용    3080    49299037  47
32  201507-201512  강원도  화천군   합계    3749   104877645 NaN
34  201507-201512  강원도  횡성군  일반용    4708    61266031  24
35  201507-201512  강원도  횡성군   합계    8032   250269254 NaN

In [69]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [70]:
Final.to_csv("{}_일반용_전력사용량_1507-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [71]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [72]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [73]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [74]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [75]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [76]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [77]:
# SEOUL

In [78]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)