In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,인천광역시,전체(시 / 군 / 구),주택용,"696,441","343,242,174","46,552,370,696",135.6
4,201501,인천광역시,전체(시 / 군 / 구),일반용,"127,906","508,689,890","66,539,928,264",130.8
...,...,...,...,...,...,...,...,...
523,201506,인천광역시,중구,산업용,520,"62,582,198","7,510,994,824",120
524,201506,인천광역시,중구,심 야,"1,459","1,364,164","85,767,960",62.9
525,201506,인천광역시,중구,일반용,"9,795","70,077,511","8,816,191,927",125.8
526,201506,인천광역시,중구,주택용,"29,348","12,366,780","1,416,688,280",114.6
527,201506,인천광역시,중구,합계,"45,207","149,777,630","18,243,091,024",121.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,인천광역시,전체(시 / 군 / 구),주택용,"696,441","343,242,174","46,552,370,696",135.6
4,201501,인천광역시,전체(시 / 군 / 구),일반용,"127,906","508,689,890","66,539,928,264",130.8
5,201501,인천광역시,전체(시 / 군 / 구),교육용,988,"33,273,762","3,927,052,485",118.0
6,201501,인천광역시,전체(시 / 군 / 구),산업용,"18,119","1,203,392,321","142,558,268,489",118.5
...,...,...,...,...,...,...,...,...
523,201506,인천광역시,중구,산업용,520,"62,582,198","7,510,994,824",120
524,201506,인천광역시,중구,심 야,"1,459","1,364,164","85,767,960",62.9
525,201506,인천광역시,중구,일반용,"9,795","70,077,511","8,816,191,927",125.8
526,201506,인천광역시,중구,주택용,"29,348","12,366,780","1,416,688,280",114.6
527,201506,인천광역시,중구,합계,"45,207","149,777,630","18,243,091,024",121.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,인천광역시,전체(시 / 군 / 구),주택용,"696,441","343,242,174","46,552,370,696",135.6
4,201501,인천광역시,전체(시 / 군 / 구),일반용,"127,906","508,689,890","66,539,928,264",130.8
5,201501,인천광역시,전체(시 / 군 / 구),교육용,988,"33,273,762","3,927,052,485",118.0
6,201501,인천광역시,전체(시 / 군 / 구),산업용,"18,119","1,203,392,321","142,558,268,489",118.5
7,201501,인천광역시,전체(시 / 군 / 구),농사용,"20,359","9,834,500","492,004,303",50.0
...,...,...,...,...,...,...,...,...
523,201506,인천광역시,중구,산업용,520,"62,582,198","7,510,994,824",120
524,201506,인천광역시,중구,심 야,"1,459","1,364,164","85,767,960",62.9
525,201506,인천광역시,중구,일반용,"9,795","70,077,511","8,816,191,927",125.8
526,201506,인천광역시,중구,주택용,"29,348","12,366,780","1,416,688,280",114.6
527,201506,인천광역시,중구,합계,"45,207","149,777,630","18,243,091,024",121.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,인천광역시,전체(시 / 군 / 구),주택용,"696,441","343,242,174","46,552,370,696",135.6
4,201501,인천광역시,전체(시 / 군 / 구),일반용,"127,906","508,689,890","66,539,928,264",130.8
5,201501,인천광역시,전체(시 / 군 / 구),교육용,988,"33,273,762","3,927,052,485",118.0
6,201501,인천광역시,전체(시 / 군 / 구),산업용,"18,119","1,203,392,321","142,558,268,489",118.5
7,201501,인천광역시,전체(시 / 군 / 구),농사용,"20,359","9,834,500","492,004,303",50.0
8,201501,인천광역시,전체(시 / 군 / 구),가로등,"51,509","16,879,235","1,805,749,764",107.0
9,201501,인천광역시,전체(시 / 군 / 구),심 야,"18,415","55,672,505","4,241,811,732",76.2
10,201502,인천광역시,전체(시 / 군 / 구),주택용,"697,585","335,992,396","44,800,389,534",133.3
11,201502,인천광역시,전체(시 / 군 / 구),일반용,"128,020","472,229,123","62,383,291,045",132.1
12,201502,인천광역시,전체(시 / 군 / 구),교육용,992,"31,241,409","3,720,208,174",119.1
13,201502,인천광역시,전체(시 / 군 / 구),산업용,"18,156","1,028,706,211","125,095,852,641",121.6
14,201502,인천광역시,전체(시 / 군 / 구),농사용,"20,376","9,277,421","469,387,853",50.6
15,201502,인천광역시,전체(시 / 군 / 구),가로등,"51,636","15,656,816","1,737,154,139",111.0
16,201502,인천광역시,전체(시 / 군 / 구),심 야,"18,365","51,259,526","3,906,285,951",76.2
17,201503,인천광역시,전체(시 / 군 / 구),주택용,"698,631","295,094,065","34,887,600,443",118.2
18,201503,인천광역시,전체(시 / 군 / 구),일반용,"128,036","415,370,687","50,028,678,992",120.4
19,201503,인천광역시,전체(시 / 군 / 구),교육용,994,"34,168,881","3,267,745,723",95.6
20,201503,인천광역시,전체(시 / 군 / 구),산업용,"18,176","1,150,295,590","113,068,725,294",98.3
21,201503,인천광역시,전체(시 / 군 / 구),농사용,"27,358","9,148,363","458,641,997",50.1
22,201503,인천광역시,전체(시 / 군 / 구),가로등,"51,735","13,867,665","1,571,794,025",113.3
23,201503,인천광역시,전체(시 / 군 / 구),심 야,"18,328","41,823,329","2,817,227,722",67.4
24,201504,인천광역시,전체(시 / 군 / 구),주택용,"700,157","306,656,401","37,227,397,062",121.4
25,201504,인천광역시,전체(시 / 군 / 구),일반용,"128,191","391,893,729","44,529,322,030",113.6
26,201504,인천광역시,전체(시 / 군 / 구),교육용,991,"23,531,471","2,624,077,499",111.5
27,201504,인천광역시,전체(시 / 군 / 구),산업용,"18,202","1,136,480,428","109,660,494,556",96.5
28,201504,인천광역시,전체(시 / 군 / 구),농사용,"24,678","9,082,162","470,640,870",51.8
29,201504,인천광역시,전체(시 / 군 / 구),가로등,"51,860","13,486,958","1,575,352,475",116.8
30,201504,인천광역시,전체(시 / 군 / 구),심 야,"18,296","32,150,098","1,782,195,822",55.4
31,201505,인천광역시,전체(시 / 군 / 구),주택용,"701,240","284,945,814","32,616,294,332",114.5
32,201505,인천광역시,전체(시 / 군 / 구),일반용,"128,262","366,175,433","42,381,037,816",115.7
33,201505,인천광역시,전체(시 / 군 / 구),교육용,992,"19,006,871","2,353,201,864",123.8
34,201505,인천광역시,전체(시 / 군 / 구),산업용,"18,230","1,086,145,250","105,182,144,419",96.8
35,201505,인천광역시,전체(시 / 군 / 구),농사용,"20,641","8,478,657","420,528,483",49.6
36,201505,인천광역시,전체(시 / 군 / 구),가로등,"52,020","12,298,080","1,488,015,024",121.0
37,201505,인천광역시,전체(시 / 군 / 구),심 야,"18,232","19,700,902","1,102,170,672",55.9
38,201506,인천광역시,전체(시 / 군 / 구),주택용,"702,839","293,554,415","35,181,899,134",119.8
39,201506,인천광역시,전체(시 / 군 / 구),일반용,"128,520","394,699,080","53,597,624,965",135.8
40,201506,인천광역시,전체(시 / 군 / 구),교육용,992,"23,047,386","3,340,595,625",144.9
41,201506,인천광역시,전체(시 / 군 / 구),산업용,"18,274","1,112,292,892","134,126,768,246",120.6
42,201506,인천광역시,전체(시 / 군 / 구),농사용,"20,765","8,797,599","442,917,007",50.3
43,201506,인천광역시,전체(시 / 군 / 구),가로등,"51,872","11,382,846","1,426,863,531",125.4
44,201506,인천광역시,전체(시 / 군 / 구),심 야,"18,175","13,159,600","767,889,822",58.4
45,합계,합계,합계,합계,"5,635,554","11,642,081,941","1,326,627,600,520",114

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_5172\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201501  인천광역시  일반용  127,906   508,689,890
11  201502  인천광역시  일반용  128,020   472,229,123
18  201503  인천광역시  일반용  128,036   415,370,687
25  201504  인천광역시  일반용  128,191   391,893,729
32  201505  인천광역시  일반용  128,262   366,175,433
39  201506  인천광역시  일반용  128,520   394,699,080

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  인천광역시  강화군  일반용   7,034   17,652,861
133  201502  인천광역시  강화군  일반용   7,030   16,296,939
213  201503  인천광역시  강화군  일반용   7,011   13,593,558
293  201504  인천광역시  강화군  일반용   7,031   12,464,954
373  201505  인천광역시  강화군  일반용   7,068   10,756,613
453  201506  인천광역시  강화군  일반용   7,089   10,121,824
61   201501  인천광역시  계양구  일반용  12,388   43,050,443
141  201502  인천광역시  계양구  일반용  12,403   40,497,574
221  201503  인천광역시  계양구  일반용  12,390   34,878,349
301  201504  인천광역시  계양구  일반용  12,387   32,738,093
381  201505  인천광역시  계양구  일반용  12,381   30,689,973
461  201506  인천광역시  계양구  일반용  12,386   33,681,563
69   201501  인천광역시   남구  일반용  20,433   58,322,811
149  201502  인천광역시   남구  일반용  20,491   54,910,404
229  201503  인천광역시   남구  일반용  20,503   47,096,469
309  201504  인천광역시   남구  일반용  20,487   44,885,027
389  201505  인천광역시   남구  일반용  20,450   40,015,284
469  201506  인천광역시   남구  일반용  20,420   43,063,244
77   201501  인천광역시  남동구  일반용  21,151   81,238,036
157  201502  인천광역시  남동구  일반용  21,180   75,651,288
237  201503  인천광역시  남동구  일반용  21,184   65,644,969
317  201504  인천광역시  남동구  일반용  21,235   62,026,188
397  201505  인천광역시  남동구  일반용  21,248   57,618,132
477  201506  인천광역시  남동구  일반용  21,349   62,892,689
85   201501  인천광역시   동구  일반용   3,749   12,093,816
165  201502  인천광역시   동구  일반용   3,743   11,095,373
245  201503  인천광역시   동구  일반용   3,736    9,902,621
325  201504  인천광역시   동구  일반용   3,737    9,044,777
405  201505  인천광역시   동구  일반용   3,730    8,077,867
485  201506  인천광역시   동구  일반용   3,743    8,712,888
93   201501  인천광역시  부평구  일반용  22,070   74,337,135
173  201502  인천광역시  부평구  일반용  22,069   69,060,948
253  201503  인천광역시  부평구  일반용  22,048   59,662,809
333  201504  인천광역시  부평구  일반용  22,053   55,950,535
413  201505  인천광역시  부평구  일반용  22,042   51,923,100
493  201506  인천광역시  부평구  일반용  22,046   56,974,089
101  201501  인천광역시   서구  일반용  19,663   77,771,014
181  201502  인천광역시   서구  일반용  19,673   72,784,312
261  201503  인천광역시   서구  일반용  19,730   62,857,940
341  201504  인천광역시   서구  일반용  19,774   60,073,910
421  201505  인천광역시   서구  일반용  19,813   54,907,499
501  201506  인천광역시   서구  일반용  19,925   59,429,494
109  201501  인천광역시  연수구  일반용   8,057   53,602,601
189  201502  인천광역시  연수구  일반용   8,076   49,406,188
269  201503  인천광역시  연수구  일반용   8,081   44,454,087
349  201504  인천광역시  연수구  일반용   8,098   41,620,375
429  201505  인천광역시  연수구  일반용   8,089   40,005,271
509  201506  인천광역시  연수구  일반용   8,085   43,457,534
117  201501  인천광역시  옹진군  일반용   3,663    9,936,946
197  201502  인천광역시  옹진군  일반용   3,653    9,316,004
277  201503  인천광역시  옹진군  일반용   3,657    7,909,768
357  201504  인천광역시  옹진군  일반용   3,662    7,688,537
437  201505  인천광역시  옹진군  일반용   3,676    6,629,755
517  201506  인천광역시  옹진군  일반용   3,682    6,288,244
125  201501  인천광역시   중구  일반용   9,698   80,684,227
205  201502  인천광역시   중구  일반용   9,702   73,210,093
285  201503  인천광역시   중구  일반용   9,696   69,370,117
365  201504  인천광역시   중구  일반용   9,727   65,401,333
445  201505  인천광역시   중구  일반용   9,765   65,551,939
525  201506  인천광역시   중구  일반용   9,795   70,077,511

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201501  인천광역시  강화군   합계   64,464    61,337,376
135  201502  인천광역시  강화군   합계   64,547    56,386,669
215  201503  인천광역시  강화군   합계   69,911    48,759,080
295  201504  인천광역시  강화군   합계   68,676    43,520,740
375  201505  인천광역시  강화군   합계   65,226    35,458,992
455  201506  인천광역시  강화군   합계   65,411    31,327,174
63   201501  인천광역시  계양구   합계   97,270   123,937,343
143  201502  인천광역시  계양구   합계   97,300   117,655,010
223  201503  인천광역시  계양구   합계   97,535   105,501,559
303  201504  인천광역시  계양구   합계   97,350   102,227,088
383  201505  인천광역시  계양구   합계   97,400    94,885,568
463  201506  인천광역시  계양구   합계   97,548    99,253,787
71   201501  인천광역시   남구   합계  181,102   201,785,089
151  201502  인천광역시   남구   합계  181,497   185,605,823
231  201503  인천광역시   남구   합계  181,916   179,908,984
311  201504  인천광역시   남구   합계  182,225   185,901,383
391  201505  인천광역시   남구   합계  182,532   158,826,023
471  201506  인천광역시   남구   합계  182,492   166,762,699
79   201501  인천광역시  남동구   합계  144,322   377,552,910
159  201502  인천광역시  남동구   합계  144,459   359,125,750
239  201503  인천광역시  남동구   합계  144,602   325,305,584
319  201504  인천광역시  남동구   합계  144,768   326,297,845
399  201505  인천광역시  남동구   합계  144,897   293,057,953
479  201506  인천광역시  남동구   합계  145,518   313,967,033
87   201501  인천광역시   동구   합계   24,017   353,264,944
167  201502  인천광역시   동구   합계   24,024   248,859,344
247  201503  인천광역시   동구   합계   24,034   365,289,535
327  201504  인천광역시   동구   합계   24,045   345,973,835
407  201505  인천광역시   동구   합계   24,051   357,528,320
487  201506  인천광역시   동구   합계   24,191   345,453,989
95   201501  인천광역시  부평구   합계  161,904   231,178,942
175  201502  인천광역시  부평구   합계  162,135   214,215,171
255  201503  인천광역시  부평구   합계  162,363   200,111,218
335  201504  인천광역시  부평구   합계  162,687   194,395,309
415  201505  인천광역시  부평구   합계  162,851   178,343,834
495  201506  인천광역시  부평구   합계  163,128   189,570,015
103  201501  인천광역시   서구   합계  140,440   465,257,402
183  201502  인천광역시   서구   합계  140,689   435,154,764
263  201503  인천광역시   서구   합계  141,034   416,005,132
343  201504  인천광역시   서구   합계  141,335   411,715,180
423  201505  인천광역시   서구   합계  141,525   384,423,775
503  201506  인천광역시   서구   합계  141,718   395,466,299
111  201501  인천광역시  연수구   합계   55,111   172,865,939
191  201502  인천광역시  연수구   합계   55,120   160,205,751
271  201503  인천광역시  연수구   합계   55,159   153,515,955
351  201504  인천광역시  연수구   합계   55,205   143,952,841
431  201505  인천광역시  연수구   합계   55,275   138,331,948
511  201506  인천광역시  연수구   합계   55,316   151,023,003
119  201501  인천광역시  옹진군   합계   20,710    19,837,393
199  201502  인천광역시  옹진군   합계   20,772    17,775,553
279  201503  인천광역시  옹진군   합계   21,692    18,211,539
359  201504  인천광역시  옹진군   합계   21,188    16,951,845
439  201505  인천광역시  옹진군   합계   20,875    14,395,822
519  201506  인천광역시  옹진군   합계   20,908    14,332,189
127  201501  인천광역시   중구   합계   44,397   163,967,049
207  201502  인천광역시   중구   합계   44,587   149,379,067
287  201503  인천광역시   중구   합계   45,012   147,159,994
367  201504  인천광역시   중구   합계   44,896   142,345,181
447  201505  인천광역시   중구   합계   44,985   141,498,772
527  201506  인천광역시   중구   합계   45,207   149,777,630

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[61337376, 56386669, 48759080, 43520740, 35458992, 31327174]
[123937343, 117655010, 105501559, 102227088, 94885568, 99253787]
[201785089, 185605823, 179908984, 185901383, 158826023, 166762699]
[377552910, 359125750, 325305584, 326297845, 293057953, 313967033]
[353264944, 248859344, 365289535, 345973835, 357528320, 345453989]
[231178942, 214215171, 200111218, 194395309, 178343834, 189570015]
[465257402, 435154764, 416005132, 411715180, 384423775, 395466299]
[172865939, 160205751, 153515955, 143952841, 138331948, 151023003]
[19837393, 17775553, 18211539, 16951845, 14395822, 14332189]
[163967049, 149379067, 147159994, 142345181, 141498772, 149777630]
인천광역시 지역별 합계 :  [276790031, 643460355, 1078790001, 1995307075, 2016369967, 1207814489, 2508022552, 919895437, 101504341, 894127693]
인천광역시 고객호수 평균:  [11062, 16233, 30326, 24126, 4010, 27085, 23520, 9199, 3504, 7474]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201501  인천광역시  강화군   합계  64,464   61,337,376
1          201502  인천광역시  강화군   합계  64,547   56,386,669
2          201503  인천광역시  강화군   합계  69,911   48,759,080
3          201504  인천광역시  강화군   합계  68,676   43,520,740
4          201505  인천광역시  강화군   합계  65,226   35,458,992
..            ...    ...  ...  ...      ...          ...
65  201501-201506  인천광역시  부평구   합계    27085   1207814489
66  201501-201506  인천광역시   서구   합계    23520   2508022552
67  201501-201506  인천광역시  연수구   합계     9199    919895437
68  201501-201506  인천광역시  옹진군   합계     3504    101504341
69  201501-201506  인천광역시   중구   합계     7474    894127693

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201501-201506  인천광역시  강화군   합계   11062   276790031
61  201501-201506  인천광역시  계양구   합계   16233   643460355
62  201501-201506  인천광역시   남구   합계   30326  1078790001
63  201501-201506  인천광역시  남동구   합계   24126  1995307075
64  201501-201506  인천광역시   동구   합계    4010  2016369967
65  201501-201506  인천광역시  부평구   합계   27085  1207814489
66  201501-201506  인천광역시   서구   합계   23520  2508022552
67  201501-201506  인천광역시  연수구   합계    9199   919895437
68  201501-201506  인천광역시  옹진군   합계    3504   101504341
69  201501-201506  인천광역시   중구   합계    7474   894127693

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  인천광역시  강화군  일반용   7,034   17,652,861
133  201502  인천광역시  강화군  일반용   7,030   16,296,939
213  201503  인천광역시  강화군  일반용   7,011   13,593,558
293  201504  인천광역시  강화군  일반용   7,031   12,464,954
373  201505  인천광역시  강화군  일반용   7,068   10,756,613
453  201506  인천광역시  강화군  일반용   7,089   10,121,824
61   201501  인천광역시  계양구  일반용  12,388   43,050,443
141  201502  인천광역시  계양구  일반용  12,403   40,497,574
221  201503  인천광역시  계양구  일반용  12,390   34,878,349
301  201504  인천광역시  계양구  일반용  12,387   32,738,093
381  201505  인천광역시  계양구  일반용  12,381   30,689,973
461  201506  인천광역시  계양구  일반용  12,386   33,681,563
69   201501  인천광역시   남구  일반용  20,433   58,322,811
149  201502  인천광역시   남구  일반용  20,491   54,910,404
229  201503  인천광역시   남구  일반용  20,503   47,096,469
309  201504  인천광역시   남구  일반용  20,487   44,885,027
389  201505  인천광역시   남구  일반용  20,450   40,015,284
469  201506  인천광역시   남구  일반용  20,420   43,063,244
77   201501  인천광역시  남동구  일반용  21,151   81,238,036
157  201502  인천광역시  남동구  일반용  21,180   75,651,288
237  201503  인천광역시  남동구  일반용  21,184   65,644,969
317  201504  인천광역시  남동구  일반용  21,235   62,026,188
397  201505  인천광역시  남동구  일반용  21,248   57,618,132
477  201506  인천광역시  남동구  일반용  21,349   62,892,689
85   201501  인천광역시   동구  일반용   3,749   12,093,816
165  201502  인천광역시   동구  일반용   3,743   11,095,373
245  201503  인천광역시   동구  일반용   3,736    9,902,621
325  201504  인천광역시   동구  일반용   3,737    9,044,777
405  201505  인천광역시   동구  일반용   3,730    8,077,867
485  201506  인천광역시   동구  일반용   3,743    8,712,888
93   201501  인천광역시  부평구  일반용  22,070   74,337,135
173  201502  인천광역시  부평구  일반용  22,069   69,060,948
253  201503  인천광역시  부평구  일반용  22,048   59,662,809
333  201504  인천광역시  부평구  일반용  22,053   55,950,535
413  201505  인천광역시  부평구  일반용  22,042   51,923,100
493  201506  인천광역시  부평구  일반용  22,046   56,974,089
101  201501  인천광역시   서구  일반용  19,663   77,771,014
181  201502  인천광역시   서구  일반용  19,673   72,784,312
261  201503  인천광역시   서구  일반용  19,730   62,857,940
341  201504  인천광역시   서구  일반용  19,774   60,073,910
421  201505  인천광역시   서구  일반용  19,813   54,907,499
501  201506  인천광역시   서구  일반용  19,925   59,429,494
109  201501  인천광역시  연수구  일반용   8,057   53,602,601
189  201502  인천광역시  연수구  일반용   8,076   49,406,188
269  201503  인천광역시  연수구  일반용   8,081   44,454,087
349  201504  인천광역시  연수구  일반용   8,098   41,620,375
429  201505  인천광역시  연수구  일반용   8,089   40,005,271
509  201506  인천광역시  연수구  일반용   8,085   43,457,534
117  201501  인천광역시  옹진군  일반용   3,663    9,936,946
197  201502  인천광역시  옹진군  일반용   3,653    9,316,004
277  201503  인천광역시  옹진군  일반용   3,657    7,909,768
357  201504  인천광역시  옹진군  일반용   3,662    7,688,537
437  201505  인천광역시  옹진군  일반용   3,676    6,629,755
517  201506  인천광역시  옹진군  일반용   3,682    6,288,244
125  201501  인천광역시   중구  일반용   9,698   80,684,227
205  201502  인천광역시   중구  일반용   9,702   73,210,093
285  201503  인천광역시   중구  일반용   9,696   69,370,117
365  201504  인천광역시   중구  일반용   9,727   65,401,333
445  201505  인천광역시   중구  일반용   9,765   65,551,939
525  201506  인천광역시   중구  일반용   9,795   70,077,511

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[17652861, 16296939, 13593558, 12464954, 10756613, 10121824]
[43050443, 40497574, 34878349, 32738093, 30689973, 33681563]
[58322811, 54910404, 47096469, 44885027, 40015284, 43063244]
[81238036, 75651288, 65644969, 62026188, 57618132, 62892689]
[12093816, 11095373, 9902621, 9044777, 8077867, 8712888]
[74337135, 69060948, 59662809, 55950535, 51923100, 56974089]
[77771014, 72784312, 62857940, 60073910, 54907499, 59429494]
[53602601, 49406188, 44454087, 41620375, 40005271, 43457534]
[9936946, 9316004, 7909768, 7688537, 6629755, 6288244]
[80684227, 73210093, 69370117, 65401333, 65551939, 70077511]
인천광역시 지역별 일반용 합계 :  [80886749, 215535995, 288293239, 405071302, 58927342, 367908616, 387824169, 272546056, 47769254, 424295220]
인천광역시 고객호수 평균:  [7043, 12389, 20464, 21224, 3739, 22054, 19763, 8081, 3665, 9730]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5172\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201501  인천광역시  강화군  일반용  7,034   17,652,861
1          201502  인천광역시  강화군  일반용  7,030   16,296,939
2          201503  인천광역시  강화군  일반용  7,011   13,593,558
3          201504  인천광역시  강화군  일반용  7,031   12,464,954
4          201505  인천광역시  강화군  일반용  7,068   10,756,613
..            ...    ...  ...  ...     ...          ...
65  201501-201506  인천광역시  부평구  일반용   22054    367908616
66  201501-201506  인천광역시   서구  일반용   19763    387824169
67  201501-201506  인천광역시  연수구  일반용    8081    272546056
68  201501-201506  인천광역시  옹진군  일반용    3665     47769254
69  201501-201506  인천광역시   중구  일반용    9730    424295220

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201501-201506  인천광역시  강화군  일반용    7043   80886749
61  201501-201506  인천광역시  계양구  일반용   12389  215535995
62  201501-201506  인천광역시   남구  일반용   20464  288293239
63  201501-201506  인천광역시  남동구  일반용   21224  405071302
64  201501-201506  인천광역시   동구  일반용    3739   58927342
65  201501-201506  인천광역시  부평구  일반용   22054  367908616
66  201501-201506  인천광역시   서구  일반용   19763  387824169
67  201501-201506  인천광역시  연수구  일반용    8081  272546056
68  201501-201506  인천광역시  옹진군  일반용    3665   47769254
69  201501-201506  인천광역시   중구  일반용    9730  424295220

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201501-201506  인천광역시  강화군  일반용    7043    80886749
60  201501-201506  인천광역시  강화군   합계   11062   276790031
61  201501-201506  인천광역시  계양구  일반용   12389   215535995
61  201501-201506  인천광역시  계양구   합계   16233   643460355
62  201501-201506  인천광역시   남구  일반용   20464   288293239
62  201501-201506  인천광역시   남구   합계   30326  1078790001
63  201501-201506  인천광역시  남동구  일반용   21224   405071302
63  201501-201506  인천광역시  남동구   합계   24126  1995307075
64  201501-201506  인천광역시   동구  일반용    3739    58927342
64  201501-201506  인천광역시   동구   합계    4010  2016369967
65  201501-201506  인천광역시  부평구  일반용   22054   367908616
65  201501-201506  인천광역시  부평구   합계   27085  1207814489
66  201501-201506  인천광역시   서구  일반용   19763   387824169
66  201501-201506  인천광역시   서구   합계   23520  2508022552
67  201501-201506  인천광역시  연수구   합계    9199   919895437
67  201501-201506  인천광역시  연수구  일반용    8081   272546056
68  201501-201506  인천광역시  옹진군   합계    3504   101504341
68  201501-201506  인천광역시  옹진군  일반용    3665    47769254
69  201501-201506  인천광역시   중구  일반용    9730   424295220
69  201501-201506  인천광역시   중구   합계    7474   894127693

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[80886749,
 215535995,
 288293239,
 405071302,
 58927342,
 367908616,
 387824169,
 272546056,
 47769254,
 424295220]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[276790031,
 643460355,
 1078790001,
 1995307075,
 2016369967,
 1207814489,
 2508022552,
 919895437,
 101504341,
 894127693]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[29.22, 33.5, 26.72, 20.3, 2.92, 30.46, 15.46, 29.63, 47.06, 47.45]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   29
1   34
2   27
3   20
4    3
5   30
6   15
7   30
8   47
9   47
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  29
1  계양구  일반용  34
2   남구  일반용  27
3  남동구  일반용  20
4   동구  일반용   3
5  부평구  일반용  30
6   서구  일반용  15
7  연수구  일반용  30
8  옹진군  일반용  47
9   중구  일반용  47

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201501-201506  인천광역시  강화군  일반용    7043    80886749  29
1   201501-201506  인천광역시  강화군   합계   11062   276790031 NaN
2   201501-201506  인천광역시  계양구  일반용   12389   215535995  34
3   201501-201506  인천광역시  계양구   합계   16233   643460355 NaN
4   201501-201506  인천광역시   남구  일반용   20464   288293239  27
5   201501-201506  인천광역시   남구   합계   30326  1078790001 NaN
6   201501-201506  인천광역시  남동구  일반용   21224   405071302  20
7   201501-201506  인천광역시  남동구   합계   24126  1995307075 NaN
8   201501-201506  인천광역시   동구  일반용    3739    58927342   3
9   201501-201506  인천광역시   동구   합계    4010  2016369967 NaN
10  201501-201506  인천광역시  부평구  일반용   22054   367908616  30
11  201501-201506  인천광역시  부평구   합계   27085  1207814489 NaN
12  201501-201506  인천광역시   서구  일반용   19763   387824169  15
13  201501-201506  인천광역시   서구   합계   23520  2508022552 NaN
15  201501-201506  인천광역시  연수구  일반용    8081   272546056  30
14  201501-201506  인천광역시  연수구   합계    9199   919895437 NaN
17  201501-201506  인천광역시  옹진군  일반용    3665    47769254  47
16  201501-201506  인천광역시  옹진군   합계    3504   101504341 NaN
18  201501-201506  인천광역시   중구  일반용    9730   424295220  47
19  201501-201506  인천광역시   중구   합계    7474   894127693 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)