In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('서울특별시_계약종별 전력사용량 월별_14상반기.csv' , encoding='utf-8')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 서울특별시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 01 월 ~ 2014년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,서울특별시,전체(시 / 군 / 구),주택용,"2,629,638","1,187,067,950","164,730,814,861",138.8
4,201401,서울특별시,전체(시 / 군 / 구),일반용,"527,799","2,282,315,396","299,673,221,064",131.3
...,...,...,...,...,...,...,...,...
1237,201406,서울특별시,중랑구,산업용,"2,548","5,409,174","682,319,203",126.1
1238,201406,서울특별시,중랑구,심 야,647,"513,116","32,279,677",62.9
1239,201406,서울특별시,중랑구,일반용,"19,155","36,772,620","4,733,447,032",128.7
1240,201406,서울특별시,중랑구,주택용,"125,324","40,183,434","4,840,039,785",120.4
1241,201406,서울특별시,중랑구,합계,"157,606","85,296,197","10,609,094,017",124.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,서울특별시,전체(시 / 군 / 구),주택용,"2,629,638","1,187,067,950","164,730,814,861",138.8
4,201401,서울특별시,전체(시 / 군 / 구),일반용,"527,799","2,282,315,396","299,673,221,064",131.3
5,201401,서울특별시,전체(시 / 군 / 구),교육용,"2,573","162,796,405","17,781,771,565",109.2
6,201401,서울특별시,전체(시 / 군 / 구),산업용,"45,686","444,682,227","51,966,122,164",116.9
...,...,...,...,...,...,...,...,...
1237,201406,서울특별시,중랑구,산업용,"2,548","5,409,174","682,319,203",126.1
1238,201406,서울특별시,중랑구,심 야,647,"513,116","32,279,677",62.9
1239,201406,서울특별시,중랑구,일반용,"19,155","36,772,620","4,733,447,032",128.7
1240,201406,서울특별시,중랑구,주택용,"125,324","40,183,434","4,840,039,785",120.4
1241,201406,서울특별시,중랑구,합계,"157,606","85,296,197","10,609,094,017",124.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,서울특별시,전체(시 / 군 / 구),주택용,"2,629,638","1,187,067,950","164,730,814,861",138.8
4,201401,서울특별시,전체(시 / 군 / 구),일반용,"527,799","2,282,315,396","299,673,221,064",131.3
5,201401,서울특별시,전체(시 / 군 / 구),교육용,"2,573","162,796,405","17,781,771,565",109.2
6,201401,서울특별시,전체(시 / 군 / 구),산업용,"45,686","444,682,227","51,966,122,164",116.9
7,201401,서울특별시,전체(시 / 군 / 구),농사용,"1,879","1,623,978","78,355,151",48.2
...,...,...,...,...,...,...,...,...
1237,201406,서울특별시,중랑구,산업용,"2,548","5,409,174","682,319,203",126.1
1238,201406,서울특별시,중랑구,심 야,647,"513,116","32,279,677",62.9
1239,201406,서울특별시,중랑구,일반용,"19,155","36,772,620","4,733,447,032",128.7
1240,201406,서울특별시,중랑구,주택용,"125,324","40,183,434","4,840,039,785",120.4
1241,201406,서울특별시,중랑구,합계,"157,606","85,296,197","10,609,094,017",124.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201401,서울특별시,전체(시 / 군 / 구),주택용,"2,629,638","1,187,067,950","164,730,814,861",138.8
4,201401,서울특별시,전체(시 / 군 / 구),일반용,"527,799","2,282,315,396","299,673,221,064",131.3
5,201401,서울특별시,전체(시 / 군 / 구),교육용,"2,573","162,796,405","17,781,771,565",109.2
6,201401,서울특별시,전체(시 / 군 / 구),산업용,"45,686","444,682,227","51,966,122,164",116.9
7,201401,서울특별시,전체(시 / 군 / 구),농사용,"1,879","1,623,978","78,355,151",48.2
8,201401,서울특별시,전체(시 / 군 / 구),가로등,"175,521","35,975,413","3,700,211,372",102.9
9,201401,서울특별시,전체(시 / 군 / 구),심 야,"19,510","41,112,213","3,309,772,420",80.5
10,201402,서울특별시,전체(시 / 군 / 구),주택용,"2,632,295","1,174,713,281","161,928,152,064",137.8
11,201402,서울특별시,전체(시 / 군 / 구),일반용,"527,687","2,146,410,552","286,282,336,824",133.4
12,201402,서울특별시,전체(시 / 군 / 구),교육용,"2,597","152,311,413","16,848,078,837",110.6
13,201402,서울특별시,전체(시 / 군 / 구),산업용,"45,756","426,308,679","50,478,900,200",118.4
14,201402,서울특별시,전체(시 / 군 / 구),농사용,"1,876","1,586,004","80,056,228",50.5
15,201402,서울특별시,전체(시 / 군 / 구),가로등,"175,612","33,833,964","3,636,472,729",107.5
16,201402,서울특별시,전체(시 / 군 / 구),심 야,"19,462","39,806,649","3,214,142,493",80.7
17,201403,서울특별시,전체(시 / 군 / 구),주택용,"2,635,553","1,029,038,500","125,909,727,968",122.4
18,201403,서울특별시,전체(시 / 군 / 구),일반용,"527,567","1,918,287,239","232,193,908,171",121.0
19,201403,서울특별시,전체(시 / 군 / 구),교육용,"2,615","134,368,862","13,537,416,744",100.7
20,201403,서울특별시,전체(시 / 군 / 구),산업용,"45,791","401,914,864","42,468,373,833",105.7
21,201403,서울특별시,전체(시 / 군 / 구),농사용,"2,072","1,389,595","66,938,142",48.2
22,201403,서울특별시,전체(시 / 군 / 구),가로등,"175,774","30,849,277","3,355,538,510",108.8
23,201403,서울특별시,전체(시 / 군 / 구),심 야,"19,413","32,070,659","2,311,540,649",72.1
24,201404,서울특별시,전체(시 / 군 / 구),주택용,"2,639,055","1,066,274,547","133,178,041,553",124.9
25,201404,서울특별시,전체(시 / 군 / 구),일반용,"527,792","1,820,400,391","206,899,089,346",113.7
26,201404,서울특별시,전체(시 / 군 / 구),교육용,"2,620","120,097,168","11,676,177,745",97.2
27,201404,서울특별시,전체(시 / 군 / 구),산업용,"45,812","401,064,413","39,775,795,562",99.2
28,201404,서울특별시,전체(시 / 군 / 구),농사용,"1,881","1,309,320","63,741,637",48.7
29,201404,서울특별시,전체(시 / 군 / 구),가로등,"175,735","29,462,653","3,335,754,309",113.2
30,201404,서울특별시,전체(시 / 군 / 구),심 야,"19,326","27,579,008","1,877,935,400",68.1
31,201405,서울특별시,전체(시 / 군 / 구),주택용,"2,642,048","1,004,895,714","120,699,069,726",120.1
32,201405,서울특별시,전체(시 / 군 / 구),일반용,"527,634","1,756,379,717","201,640,580,489",114.8
33,201405,서울특별시,전체(시 / 군 / 구),교육용,"2,624","103,098,326","10,624,682,066",103.1
34,201405,서울특별시,전체(시 / 군 / 구),산업용,"45,960","380,016,583","38,747,808,563",102.0
35,201405,서울특별시,전체(시 / 군 / 구),농사용,"1,894","1,250,539","62,025,114",49.6
36,201405,서울특별시,전체(시 / 군 / 구),가로등,"175,871","27,121,795","3,166,066,887",116.7
37,201405,서울특별시,전체(시 / 군 / 구),심 야,"19,220","32,264,885","2,346,941,607",72.7
38,201406,서울특별시,전체(시 / 군 / 구),주택용,"2,645,336","1,058,558,959","135,003,955,743",127.5
39,201406,서울특별시,전체(시 / 군 / 구),일반용,"527,957","1,995,690,041","260,070,816,527",130.3
40,201406,서울특별시,전체(시 / 군 / 구),교육용,"2,633","116,942,611","13,648,960,165",116.7
41,201406,서울특별시,전체(시 / 군 / 구),산업용,"45,983","403,882,922","47,163,472,305",116.8
42,201406,서울특별시,전체(시 / 군 / 구),농사용,"1,903","1,297,459","66,443,886",51.2
43,201406,서울특별시,전체(시 / 군 / 구),가로등,"175,933","25,771,471","3,105,097,666",120.5
44,201406,서울특별시,전체(시 / 군 / 구),심 야,"19,149","47,074,358","3,461,566,617",73.5
45,합계,NaN,NaN,NaN,"20,463,042","22,098,896,000","2,720,165,874,902",123.1

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_18860\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)        사용량(kWh)
4   201401  서울특별시  일반용  527,799   2,282,315,396
11  201402  서울특별시  일반용  527,687   2,146,410,552
18  201403  서울특별시  일반용  527,567   1,918,287,239
25  201404  서울특별시  일반용  527,792   1,820,400,391
32  201405  서울특별시  일반용  527,634   1,756,379,717
39  201406  서울특별시  일반용  527,957   1,995,690,041

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201401  서울특별시  강남구  일반용  47,781   319,929,448
252   201402  서울특별시  강남구  일반용  47,888   299,012,984
451   201403  서울특별시  강남구  일반용  47,930   266,391,897
650   201404  서울특별시  강남구  일반용  48,041   247,491,843
849   201405  서울특별시  강남구  일반용  48,025   237,099,055
...      ...    ...  ...  ...      ...           ...
443   201402  서울특별시  중랑구  일반용  19,226    42,261,544
642   201403  서울특별시  중랑구  일반용  19,208    36,077,443
841   201404  서울특별시  중랑구  일반용  19,213    34,264,252
1040  201405  서울특별시  중랑구  일반용  19,164    31,956,443
1239  201406  서울특별시  중랑구  일반용  19,155    36,772,620

[150 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'서울특별시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강남구',
 '강동구',
 '강북구',
 '강서구',
 '관악구',
 '광진구',
 '구로구',
 '금천구',
 '노원구',
 '도봉구',
 '동대문구',
 '동작구',
 '마포구',
 '서대문구',
 '서초구',
 '성동구',
 '성북구',
 '송파구',
 '양천구',
 '영등포구',
 '용산구',
 '은평구',
 '종로구',
 '중구',
 '중랑구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55    201401  서울특별시  강남구   합계  197,093   423,343,057
254   201402  서울특별시  강남구   합계  197,341   398,376,981
453   201403  서울특별시  강남구   합계  197,525   357,464,560
652   201404  서울특별시  강남구   합계  197,773   337,755,625
851   201405  서울특별시  강남구   합계  197,907   324,663,732
...      ...    ...  ...  ...       ...           ...
445   201402  서울특별시  중랑구   합계  157,223    99,717,189
644   201403  서울특별시  중랑구   합계  157,444    85,731,293
843   201404  서울특별시  중랑구   합계  157,460    84,663,863
1042  201405  서울특별시  중랑구   합계  157,506    78,260,306
1241  201406  서울특별시  중랑구   합계  157,606    85,296,197

[150 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[423343057, 398376981, 357464560, 337755625, 324663732, 371218067]
[137985604, 132495609, 116762626, 114428771, 108888382, 119878063]
[85111960, 82829729, 71381217, 70745480, 65333391, 70669564]
[183947003, 176489466, 156428664, 153920076, 145086514, 156576477]
[153955591, 150087083, 129391883, 129233445, 119391230, 130202881]
[145923978, 139908221, 121696034, 121704900, 117126561, 131174013]
[172832180, 169511473, 148892220, 144427945, 138005204, 147300015]
[149170307, 140012561, 126846792, 120212094, 116226761, 127584754]
[141075695, 136182164, 119099338, 117132067, 109607161, 120583628]
[84877556, 82303605, 70881158, 70549207, 65542117, 70624129]
[132884634, 128267775, 112160065, 109382372, 102143022, 112881495]
[114471930, 110333786, 97342422, 97107454, 92008997, 102238665]
[173826815, 165154704, 150311237, 145364895, 140913751, 154720465]
[109334223, 103346343, 93557107, 91316802, 88313738, 97700027]
[314648788, 301246316, 269204357, 262679851, 249424925, 280541481]
[169857056, 162151913, 149672922, 147075872, 138919961, 148721549]
[136449534, 131733218, 115424845, 113945073, 105615707, 115692545]
[223227080, 215523729, 194318363, 196857747, 191441488, 203428735]
[137161913, 132864573, 120110634, 119377562, 112282755, 119540457]
[235733393, 220543624, 204100472, 196910928, 192838762, 213854821]
[123467815, 117993607, 103794567, 101444427, 96682643, 110524778]
[120376285, 117877103, 102747836, 103226833, 96057280, 102961515]
[158551432, 150088938, 134275613, 128156045, 122677839, 140721512]
[225229890, 209930832, 196322771, 188568166, 187575332, 214581988]
[102129863, 99717189, 85731293, 84663863, 78260306, 85296197]
서울특별시 지역별 합계 :  [2212822022, 730439055, 446071341, 972448200, 812262113, 777533707, 920969037, 780053269, 743680053, 444777772, 697719363, 613503254, 930291867, 583568240, 1677745718, 916399273, 718860922, 1224797142, 741337894, 1263982000, 653907837, 643246852, 834471379, 1222208979, 535798711]
서울특별시 고객호수 평균:  [32933, 21263, 21502, 31562, 39076, 25617, 20388, 14801, 17494, 15574, 24227, 24874, 24816, 19417, 20426, 15758, 25226, 28471, 20483, 21889, 17362, 31372, 15040, 12600, 26234]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\3113513837.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201401  서울특별시  강남구   합계  197,093   423,343,057
1           201402  서울특별시  강남구   합계  197,341   398,376,981
2           201403  서울특별시  강남구   합계  197,525   357,464,560
3           201404  서울특별시  강남구   합계  197,773   337,755,625
4           201405  서울특별시  강남구   합계  197,907   324,663,732
..             ...    ...  ...  ...       ...           ...
170  201401-201406  서울특별시  용산구   합계     17362     653907837
171  201401-201406  서울특별시  은평구   합계     31372     643246852
172  201401-201406  서울특별시  종로구   합계     15040     834471379
173  201401-201406  서울특별시   중구   합계     12600    1222208979
174  201401-201406  서울특별시  중랑구   합계     26234     535798711

[175 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201401-201406']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201401-201406  서울특별시   강남구   합계   32933  2212822022
151  201401-201406  서울특별시   강동구   합계   21263   730439055
152  201401-201406  서울특별시   강북구   합계   21502   446071341
153  201401-201406  서울특별시   강서구   합계   31562   972448200
154  201401-201406  서울특별시   관악구   합계   39076   812262113
155  201401-201406  서울특별시   광진구   합계   25617   777533707
156  201401-201406  서울특별시   구로구   합계   20388   920969037
157  201401-201406  서울특별시   금천구   합계   14801   780053269
158  201401-201406  서울특별시   노원구   합계   17494   743680053
159  201401-201406  서울특별시   도봉구   합계   15574   444777772
160  201401-201406  서울특별시  동대문구   합계   24227   697719363
161  201401-201406  서울특별시   동작구   합계   24874   613503254
162  201401-201406  서울특별시   마포구   합계   24816   930291867
163  201401-201406  서울특별시  서대문구   합계   19417   583568240
164  201401-201406  서울특별시   서초구   합계   20426  1677745718
165  201401-201406  서울특별시   성동구   합계   15758   916399273
166  201401-201406  서울특별시   성북구   합계   25226   718860922
167  201401-201406  서울특별시   송파구   합계   28471  1224797142
168  201401-201406  서울특별시   양천구   합계   20483   741337894
169  201401-201406  서울특별시  영등포구   합계   21889  1263982000
170  201401-201406  서울특별시   용산구   합계   17362   653907837
171  201401-201406  서울특별시   은평구   합계   31372   643246852
172  201401-201406  서울특별시   종로구   합계   15040   834471379
173  201401-201406  서울특별시    중구   합계   12600  1222208979
174  201401-201406  서울특별시   중랑구   합계   26234   535798711

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201401  서울특별시  강남구  일반용  47,781   319,929,448
252   201402  서울특별시  강남구  일반용  47,888   299,012,984
451   201403  서울특별시  강남구  일반용  47,930   266,391,897
650   201404  서울특별시  강남구  일반용  48,041   247,491,843
849   201405  서울특별시  강남구  일반용  48,025   237,099,055
...      ...    ...  ...  ...      ...           ...
443   201402  서울특별시  중랑구  일반용  19,226    42,261,544
642   201403  서울특별시  중랑구  일반용  19,208    36,077,443
841   201404  서울특별시  중랑구  일반용  19,213    34,264,252
1040  201405  서울특별시  중랑구  일반용  19,164    31,956,443
1239  201406  서울특별시  중랑구  일반용  19,155    36,772,620

[150 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[319929448, 299012984, 266391897, 247491843, 237099055, 275562593]
[66598546, 63249452, 54518995, 51512555, 49176732, 57215350]
[39578607, 37574655, 32193748, 30750096, 28660722, 32590155]
[90491042, 85550019, 73979288, 70136118, 66074014, 74942552]
[69291445, 66271343, 57866938, 56769900, 53844016, 61123484]
[60139636, 56651499, 48920813, 47102100, 45448595, 52803808]
[81949913, 76050403, 67869044, 62786162, 61510666, 65490716]
[87855731, 80717109, 74035131, 68189263, 68157976, 76146773]
[57656381, 54409445, 47272156, 44909080, 42794004, 49528631]
[33781253, 31974648, 27137116, 25462890, 24103717, 27431860]
[62998542, 60106097, 52075756, 48941158, 45669780, 52590171]
[53796055, 50631072, 44980409, 43808674, 42243389, 48816792]
[103413086, 97020967, 88930422, 83543923, 81092883, 90126548]
[51659538, 48354775, 43296090, 42012673, 40884392, 46774365]
[194535185, 184988754, 165679696, 156971214, 148713097, 171526008]
[58216831, 55045092, 48611789, 45508872, 43154300, 49265004]
[51955199, 49481467, 42765420, 41035435, 38219898, 43776008]
[121681327, 115634502, 104740561, 104697085, 104756583, 112034609]
[70774872, 67814378, 62171191, 59958108, 56666608, 61294334]
[155378439, 143550841, 133668555, 126007188, 124483095, 139789811]
[71420192, 67142117, 59114755, 56261499, 54362556, 64356266]
[45722515, 43662007, 37365388, 35717400, 33310310, 37747808]
[112558210, 105822983, 95023676, 89687316, 86672086, 100590263]
[176427394, 163432399, 153600962, 146875587, 147324800, 167393512]
[44506009, 42261544, 36077443, 34264252, 31956443, 36772620]
서울특별시 지역별 일반용 합계 :  [1645487820, 342271630, 201347983, 461173033, 365167126, 311066451, 415656904, 455101983, 296569697, 169891484, 322381504, 284276391, 544127829, 272981833, 1022413954, 299801888, 267233427, 663544667, 378679491, 822877929, 372657385, 233525428, 590354534, 955054654, 225838311]
서울특별시 고객호수 평균:  [47948, 19657, 15666, 22056, 24670, 20047, 17250, 12854, 14526, 11761, 24015, 16320, 26192, 15905, 29463, 15452, 21027, 28152, 16542, 23991, 15745, 19936, 24808, 24547, 19199]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18860\1244831749.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201401-201406'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
0           201401  서울특별시  강남구  일반용  47,781   319,929,448
1           201402  서울특별시  강남구  일반용  47,888   299,012,984
2           201403  서울특별시  강남구  일반용  47,930   266,391,897
3           201404  서울특별시  강남구  일반용  48,041   247,491,843
4           201405  서울특별시  강남구  일반용  48,025   237,099,055
..             ...    ...  ...  ...      ...           ...
170  201401-201406  서울특별시  용산구  일반용    15745     372657385
171  201401-201406  서울특별시  은평구  일반용    19936     233525428
172  201401-201406  서울특별시  종로구  일반용    24808     590354534
173  201401-201406  서울특별시   중구  일반용    24547     955054654
174  201401-201406  서울특별시  중랑구  일반용    19199     225838311

[175 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201401-201406']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201401-201406  서울특별시   강남구  일반용   47948  1645487820
151  201401-201406  서울특별시   강동구  일반용   19657   342271630
152  201401-201406  서울특별시   강북구  일반용   15666   201347983
153  201401-201406  서울특별시   강서구  일반용   22056   461173033
154  201401-201406  서울특별시   관악구  일반용   24670   365167126
155  201401-201406  서울특별시   광진구  일반용   20047   311066451
156  201401-201406  서울특별시   구로구  일반용   17250   415656904
157  201401-201406  서울특별시   금천구  일반용   12854   455101983
158  201401-201406  서울특별시   노원구  일반용   14526   296569697
159  201401-201406  서울특별시   도봉구  일반용   11761   169891484
160  201401-201406  서울특별시  동대문구  일반용   24015   322381504
161  201401-201406  서울특별시   동작구  일반용   16320   284276391
162  201401-201406  서울특별시   마포구  일반용   26192   544127829
163  201401-201406  서울특별시  서대문구  일반용   15905   272981833
164  201401-201406  서울특별시   서초구  일반용   29463  1022413954
165  201401-201406  서울특별시   성동구  일반용   15452   299801888
166  201401-201406  서울특별시   성북구  일반용   21027   267233427
167  201401-201406  서울특별시   송파구  일반용   28152   663544667
168  201401-201406  서울특별시   양천구  일반용   16542   378679491
169  201401-201406  서울특별시  영등포구  일반용   23991   822877929
170  201401-201406  서울특별시   용산구  일반용   15745   372657385
171  201401-201406  서울특별시   은평구  일반용   19936   233525428
172  201401-201406  서울특별시   종로구  일반용   24808   590354534
173  201401-201406  서울특별시    중구  일반용   24547   955054654
174  201401-201406  서울특별시   중랑구  일반용   19199   225838311

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201401-201406  서울특별시   강남구  일반용   47948  1645487820
150  201401-201406  서울특별시   강남구   합계   32933  2212822022
151  201401-201406  서울특별시   강동구   합계   21263   730439055
151  201401-201406  서울특별시   강동구  일반용   19657   342271630
152  201401-201406  서울특별시   강북구  일반용   15666   201347983
152  201401-201406  서울특별시   강북구   합계   21502   446071341
153  201401-201406  서울특별시   강서구  일반용   22056   461173033
153  201401-201406  서울특별시   강서구   합계   31562   972448200
154  201401-201406  서울특별시   관악구  일반용   24670   365167126
154  201401-201406  서울특별시   관악구   합계   39076   812262113
155  201401-201406  서울특별시   광진구  일반용   20047   311066451
155  201401-201406  서울특별시   광진구   합계   25617   777533707
156  201401-201406  서울특별시   구로구  일반용   17250   415656904
156  201401-201406  서울특별시   구로구   합계   20388   920969037
157  201401-201406  서울특별시   금천구  일반용   12854   455101983
157  201401-201406  서울특별시   금천구   합계   14801   780053269
158  201401-201406  서울특별시   노원구   합계   17494   743680053
158  201401-201406  서울특별시   노원구  일반용   14526   296569697
159  201401-201406  서울특별시   도봉구   합계   15574   444777772
159  201401-201406  서울특별시   도봉구  일반용   11761   169891484
160  201401-201406  서울특별시  동대문구   합계   24227   697719363
160  201401-201406  서울특별시  동대문구  일반용   24015   322381504
161  201401-201406  서울특별시   동작구   합계   24874   613503254
161  201401-201406  서울특별시   동작구  일반용   16320   284276391
162  201401-201406  서울특별시   마포구   합계   24816   930291867
162  201401-201406  서울특별시   마포구  일반용   26192   544127829
163  201401-201406  서울특별시  서대문구   합계   19417   583568240
163  201401-201406  서울특별시  서대문구  일반용   15905   272981833
164  201401-201406  서울특별시   서초구  일반용   29463  1022413954
164  201401-201406  서울특별시   서초구   합계   20426  1677745718
165  201401-201406  서울특별시   성동구   합계   15758   916399273
165  201401-201406  서울특별시   성동구  일반용   15452   299801888
166  201401-201406  서울특별시   성북구   합계   25226   718860922
166  201401-201406  서울특별시   성북구  일반용   21027   267233427
167  201401-201406  서울특별시   송파구   합계   28471  1224797142
167  201401-201406  서울특별시   송파구  일반용   28152   663544667
168  201401-201406  서울특별시   양천구   합계   20483   741337894
168  201401-201406  서울특별시   양천구  일반용   16542   378679491
169  201401-201406  서울특별시  영등포구  일반용   23991   822877929
169  201401-201406  서울특별시  영등포구   합계   21889  1263982000
170  201401-201406  서울특별시   용산구   합계   17362   653907837
170  201401-201406  서울특별시   용산구  일반용   15745   372657385
171  201401-201406  서울특별시   은평구   합계   31372   643246852
171  201401-201406  서울특별시   은평구  일반용   19936   233525428
172  201401-201406  서울특별시   종로구   합계   15040   834471379
172  201401-201406  서울특별시   종로구  일반용   24808   590354534
173  201401-201406  서울특별시    중구   합계   12600  1222208979
173  201401-201406  서울특별시    중구  일반용   24547   955054654
174  201401-201406  서울특별시   중랑구  일반용   19199   225838311
174  201401-201406  서울특별시   중랑구   합계   26234   535798711

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[1645487820,
 342271630,
 201347983,
 461173033,
 365167126,
 311066451,
 415656904,
 455101983,
 296569697,
 169891484,
 322381504,
 284276391,
 544127829,
 272981833,
 1022413954,
 299801888,
 267233427,
 663544667,
 378679491,
 822877929,
 372657385,
 233525428,
 590354534,
 955054654,
 225838311]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[2212822022,
 730439055,
 446071341,
 972448200,
 812262113,
 777533707,
 920969037,
 780053269,
 743680053,
 444777772,
 697719363,
 613503254,
 930291867,
 583568240,
 1677745718,
 916399273,
 718860922,
 1224797142,
 741337894,
 1263982000,
 653907837,
 643246852,
 834471379,
 1222208979,
 535798711]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[74.36, 46.86, 45.14, 47.42, 44.96, 40.01, 45.13, 58.34, 39.88, 38.2, 46.21, 46.34, 58.49, 46.78, 60.94, 32.72, 37.17, 54.18, 51.08, 65.1, 56.99, 36.3, 70.75, 78.14, 42.15]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    74
1    47
2    45
3    47
4    45
5    40
6    45
7    58
8    40
9    38
10   46
11   46
12   58
13   47
14   61
15   33
16   37
17   54
18   51
19   65
20   57
21   36
22   71
23   78
24   42
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강남구  일반용  74
1    강동구  일반용  47
2    강북구  일반용  45
3    강서구  일반용  47
4    관악구  일반용  45
5    광진구  일반용  40
6    구로구  일반용  45
7    금천구  일반용  58
8    노원구  일반용  40
9    도봉구  일반용  38
10  동대문구  일반용  46
11   동작구  일반용  46
12   마포구  일반용  58
13  서대문구  일반용  47
14   서초구  일반용  61
15   성동구  일반용  33
16   성북구  일반용  37
17   송파구  일반용  54
18   양천구  일반용  51
19  영등포구  일반용  65
20   용산구  일반용  57
21   은평구  일반용  36
22   종로구  일반용  71
23    중구  일반용  78
24   중랑구  일반용  42

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201401-201406  서울특별시   강남구  일반용   47948  1645487820  74
1   201401-201406  서울특별시   강남구   합계   32933  2212822022 NaN
3   201401-201406  서울특별시   강동구  일반용   19657   342271630  47
2   201401-201406  서울특별시   강동구   합계   21263   730439055 NaN
4   201401-201406  서울특별시   강북구  일반용   15666   201347983  45
5   201401-201406  서울특별시   강북구   합계   21502   446071341 NaN
6   201401-201406  서울특별시   강서구  일반용   22056   461173033  47
7   201401-201406  서울특별시   강서구   합계   31562   972448200 NaN
8   201401-201406  서울특별시   관악구  일반용   24670   365167126  45
9   201401-201406  서울특별시   관악구   합계   39076   812262113 NaN
10  201401-201406  서울특별시   광진구  일반용   20047   311066451  40
11  201401-201406  서울특별시   광진구   합계   25617   777533707 NaN
12  201401-201406  서울특별시   구로구  일반용   17250   415656904  45
13  201401-201406  서울특별시   구로구   합계   20388   920969037 NaN
14  201401-201406  서울특별시   금천구  일반용   12854   455101983  58
15  201401-201406  서울특별시   금천구   합계   14801   780053269 NaN
17  201401-201406  서울특별시   노원구  일반용   14526   296569697  40
16  201401-201406  서울특별시   노원구   합계   17494   743680053 NaN
19  201401-201406  서울특별시   도봉구  일반용   11761   169891484  38
18  201401-201406  서울특별시   도봉구   합계   15574   444777772 NaN
21  201401-201406  서울특별시  동대문구  일반용   24015   322381504  46
20  201401-201406  서울특별시  동대문구   합계   24227   697719363 NaN
23  201401-201406  서울특별시   동작구  일반용   16320   284276391  46
22  201401-201406  서울특별시   동작구   합계   24874   613503254 NaN
25  201401-201406  서울특별시   마포구  일반용   26192   544127829  58
24  201401-201406  서울특별시   마포구   합계   24816   930291867 NaN
27  201401-201406  서울특별시  서대문구  일반용   15905   272981833  47
26  201401-201406  서울특별시  서대문구   합계   19417   583568240 NaN
28  201401-201406  서울특별시   서초구  일반용   29463  1022413954  61
29  201401-201406  서울특별시   서초구   합계   20426  1677745718 NaN
31  201401-201406  서울특별시   성동구  일반용   15452   299801888  33
30  201401-201406  서울특별시   성동구   합계   15758   916399273 NaN
33  201401-201406  서울특별시   성북구  일반용   21027   267233427  37
32  201401-201406  서울특별시   성북구   합계   25226   718860922 NaN
35  201401-201406  서울특별시   송파구  일반용   28152   663544667  54
34  201401-201406  서울특별시   송파구   합계   28471  1224797142 NaN
37  201401-201406  서울특별시   양천구  일반용   16542   378679491  51
36  201401-201406  서울특별시   양천구   합계   20483   741337894 NaN
38  201401-201406  서울특별시  영등포구  일반용   23991   822877929  65
39  201401-201406  서울특별시  영등포구   합계   21889  1263982000 NaN
41  201401-201406  서울특별시   용산구  일반용   15745   372657385  57
40  201401-201406  서울특별시   용산구   합계   17362   653907837 NaN
43  201401-201406  서울특별시   은평구  일반용   19936   233525428  36
42  201401-201406  서울특별시   은평구   합계   31372   643246852 NaN
45  201401-201406  서울특별시   종로구  일반용   24808   590354534  71
44  201401-201406  서울특별시   종로구   합계   15040   834471379 NaN
47  201401-201406  서울특별시    중구  일반용   24547   955054654  78
46  201401-201406  서울특별시    중구   합계   12600  1222208979 NaN
48  201401-201406  서울특별시   중랑구  일반용   19199   225838311  42
49  201401-201406  서울특별시   중랑구   합계   26234   535798711 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1401-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)