In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('서울특별시_계약종별 전력사용량 월별_14하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 서울특별시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2014년 07 월 ~ 2014년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,서울특별시,전체(시 / 군 / 구),주택용,"2,649,152","1,121,937,944","154,343,846,678",137.6
4,201407,서울특별시,전체(시 / 군 / 구),일반용,"528,237","2,283,973,463","326,971,315,111",143.2
...,...,...,...,...,...,...,...,...
1237,201412,서울특별시,중랑구,산업용,"2,553","6,625,624","827,878,055",125
1238,201412,서울특별시,중랑구,심 야,631,"722,969","58,180,232",80.5
1239,201412,서울특별시,중랑구,일반용,"19,135","39,590,685","5,403,715,768",136.5
1240,201412,서울특별시,중랑구,주택용,"126,629","42,923,190","5,406,056,713",125.9
1241,201412,서울특별시,중랑구,합계,"158,890","93,944,534","12,148,384,601",129.3

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,서울특별시,전체(시 / 군 / 구),주택용,"2,649,152","1,121,937,944","154,343,846,678",137.6
4,201407,서울특별시,전체(시 / 군 / 구),일반용,"528,237","2,283,973,463","326,971,315,111",143.2
5,201407,서울특별시,전체(시 / 군 / 구),교육용,"2,637","139,144,370","17,381,180,459",124.9
6,201407,서울특별시,전체(시 / 군 / 구),산업용,"46,000","437,838,420","55,450,274,677",126.6
...,...,...,...,...,...,...,...,...
1237,201412,서울특별시,중랑구,산업용,"2,553","6,625,624","827,878,055",125
1238,201412,서울특별시,중랑구,심 야,631,"722,969","58,180,232",80.5
1239,201412,서울특별시,중랑구,일반용,"19,135","39,590,685","5,403,715,768",136.5
1240,201412,서울특별시,중랑구,주택용,"126,629","42,923,190","5,406,056,713",125.9
1241,201412,서울특별시,중랑구,합계,"158,890","93,944,534","12,148,384,601",129.3

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,서울특별시,전체(시 / 군 / 구),주택용,"2,649,152","1,121,937,944","154,343,846,678",137.6
4,201407,서울특별시,전체(시 / 군 / 구),일반용,"528,237","2,283,973,463","326,971,315,111",143.2
5,201407,서울특별시,전체(시 / 군 / 구),교육용,"2,637","139,144,370","17,381,180,459",124.9
6,201407,서울특별시,전체(시 / 군 / 구),산업용,"46,000","437,838,420","55,450,274,677",126.6
7,201407,서울특별시,전체(시 / 군 / 구),농사용,"1,901","1,308,214","66,815,522",51.1
...,...,...,...,...,...,...,...,...
1237,201412,서울특별시,중랑구,산업용,"2,553","6,625,624","827,878,055",125
1238,201412,서울특별시,중랑구,심 야,631,"722,969","58,180,232",80.5
1239,201412,서울특별시,중랑구,일반용,"19,135","39,590,685","5,403,715,768",136.5
1240,201412,서울특별시,중랑구,주택용,"126,629","42,923,190","5,406,056,713",125.9
1241,201412,서울특별시,중랑구,합계,"158,890","93,944,534","12,148,384,601",129.3

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201407,서울특별시,전체(시 / 군 / 구),주택용,"2,649,152","1,121,937,944","154,343,846,678",137.6
4,201407,서울특별시,전체(시 / 군 / 구),일반용,"528,237","2,283,973,463","326,971,315,111",143.2
5,201407,서울특별시,전체(시 / 군 / 구),교육용,"2,637","139,144,370","17,381,180,459",124.9
6,201407,서울특별시,전체(시 / 군 / 구),산업용,"46,000","437,838,420","55,450,274,677",126.6
7,201407,서울특별시,전체(시 / 군 / 구),농사용,"1,901","1,308,214","66,815,522",51.1
8,201407,서울특별시,전체(시 / 군 / 구),가로등,"176,232","25,052,793","3,006,006,232",120.0
9,201407,서울특별시,전체(시 / 군 / 구),심 야,"19,049","62,986,863","4,618,987,360",73.3
10,201408,서울특별시,전체(시 / 군 / 구),주택용,"2,652,034","1,233,458,597","185,058,599,703",150.0
11,201408,서울특별시,전체(시 / 군 / 구),일반용,"528,897","2,362,338,932","331,577,447,068",140.4
12,201408,서울특별시,전체(시 / 군 / 구),교육용,"2,647","128,381,964","16,261,664,839",126.7
13,201408,서울특별시,전체(시 / 군 / 구),산업용,"46,084","448,389,560","55,354,691,985",123.5
14,201408,서울특별시,전체(시 / 군 / 구),농사용,"1,902","1,460,689","72,001,502",49.3
15,201408,서울특별시,전체(시 / 군 / 구),가로등,"176,293","26,402,551","3,065,246,230",116.1
16,201408,서울특별시,전체(시 / 군 / 구),심 야,"18,980","60,400,364","4,379,976,521",72.5
17,201409,서울특별시,전체(시 / 군 / 구),주택용,"2,655,354","1,114,598,375","148,182,655,363",132.9
18,201409,서울특별시,전체(시 / 군 / 구),일반용,"528,702","2,103,977,552","256,308,640,098",121.8
19,201409,서울특별시,전체(시 / 군 / 구),교육용,"2,648","122,824,507","13,166,667,756",107.2
20,201409,서울특별시,전체(시 / 군 / 구),산업용,"46,093","425,746,369","46,368,942,786",108.9
21,201409,서울특별시,전체(시 / 군 / 구),농사용,"1,899","1,350,718","65,796,642",48.7
22,201409,서울특별시,전체(시 / 군 / 구),가로등,"176,417","28,418,557","3,191,852,949",112.3
23,201409,서울특별시,전체(시 / 군 / 구),심 야,"18,908","47,761,104","3,466,517,966",72.6
24,201410,서울특별시,전체(시 / 군 / 구),주택용,"2,658,390","1,009,580,607","121,014,012,288",119.9
25,201410,서울특별시,전체(시 / 군 / 구),일반용,"528,553","1,830,788,883","207,235,250,976",113.2
26,201410,서울특별시,전체(시 / 군 / 구),교육용,"2,651","107,366,640","10,713,067,461",99.8
27,201410,서울특별시,전체(시 / 군 / 구),산업용,"46,071","391,450,311","40,231,360,313",102.8
28,201410,서울특별시,전체(시 / 군 / 구),농사용,"1,899","1,211,114","60,239,641",49.7
29,201410,서울특별시,전체(시 / 군 / 구),가로등,"176,579","30,673,680","3,293,690,295",107.4
30,201410,서울특별시,전체(시 / 군 / 구),심 야,"18,831","25,674,887","1,919,589,732",74.8
31,201411,서울특별시,전체(시 / 군 / 구),주택용,"2,661,867","1,061,203,380","133,219,467,798",125.5
32,201411,서울특별시,전체(시 / 군 / 구),일반용,"529,165","1,780,649,567","233,810,002,323",131.3
33,201411,서울특별시,전체(시 / 군 / 구),교육용,"2,656","115,061,097","12,853,565,752",111.7
34,201411,서울특별시,전체(시 / 군 / 구),산업용,"45,999","391,308,611","46,271,567,847",118.2
35,201411,서울특별시,전체(시 / 군 / 구),농사용,"2,116","1,289,121","62,988,485",48.9
36,201411,서울특별시,전체(시 / 군 / 구),가로등,"176,738","33,430,280","3,500,008,774",104.7
37,201411,서울특별시,전체(시 / 군 / 구),심 야,"18,770","21,013,120","1,647,358,443",78.4
38,201412,서울특별시,전체(시 / 군 / 구),주택용,"2,664,158","1,123,393,152","147,676,190,979",131.5
39,201412,서울특별시,전체(시 / 군 / 구),일반용,"531,120","2,148,281,075","290,443,146,125",135.2
40,201412,서울특별시,전체(시 / 군 / 구),교육용,"2,662","170,572,934","18,346,670,938",107.6
41,201412,서울특별시,전체(시 / 군 / 구),산업용,"45,926","432,053,994","53,501,308,097",123.8
42,201412,서울특별시,전체(시 / 군 / 구),농사용,"1,902","1,365,172","66,733,968",48.9
43,201412,서울특별시,전체(시 / 군 / 구),가로등,"176,736","35,039,998","3,580,764,958",102.2
44,201412,서울특별시,전체(시 / 군 / 구),심 야,"18,719","30,797,518","2,574,349,725",83.6
45,합계,합계,합계,합계,"20,591,574","22,919,957,047","2,960,380,462,365",129.2

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_18032\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)        사용량(kWh)
4   201407  서울특별시  일반용  528,237   2,283,973,463
11  201408  서울특별시  일반용  528,897   2,362,338,932
18  201409  서울특별시  일반용  528,702   2,103,977,552
25  201410  서울특별시  일반용  528,553   1,830,788,883
32  201411  서울특별시  일반용  529,165   1,780,649,567
39  201412  서울특별시  일반용  531,120   2,148,281,075

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201407  서울특별시  강남구  일반용  48,134   317,288,867
252   201408  서울특별시  강남구  일반용  48,313   327,157,997
451   201409  서울특별시  강남구  일반용  48,354   287,544,573
650   201410  서울특별시  강남구  일반용  48,395   247,137,079
849   201411  서울특별시  강남구  일반용  48,506   241,641,030
...      ...    ...  ...  ...      ...           ...
443   201408  서울특별시  중랑구  일반용  19,119    44,281,378
642   201409  서울특별시  중랑구  일반용  19,092    39,363,988
841   201410  서울특별시  중랑구  일반용  19,071    33,327,637
1040  201411  서울특별시  중랑구  일반용  19,078    33,239,422
1239  201412  서울특별시  중랑구  일반용  19,135    39,590,685

[150 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'서울특별시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강남구',
 '강동구',
 '강북구',
 '강서구',
 '관악구',
 '광진구',
 '구로구',
 '금천구',
 '노원구',
 '도봉구',
 '동대문구',
 '동작구',
 '마포구',
 '서대문구',
 '서초구',
 '성동구',
 '성북구',
 '송파구',
 '양천구',
 '영등포구',
 '용산구',
 '은평구',
 '종로구',
 '중구',
 '중랑구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

          년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55    201407  서울특별시  강남구   합계  198,182   426,429,379
254   201408  서울특별시  강남구   합계  198,338   440,612,957
453   201409  서울특별시  강남구   합계  198,408   387,865,406
652   201410  서울특별시  강남구   합계  198,525   334,893,609
851   201411  서울특별시  강남구   합계  198,793   331,439,593
...      ...    ...  ...  ...       ...           ...
445   201408  서울특별시  중랑구   합계  157,990   100,714,534
644   201409  서울특별시  중랑구   합계  158,166    91,286,883
843   201410  서울특별시  중랑구   합계  158,342    80,190,884
1042  201411  서울특별시  중랑구   합계  158,739    83,135,292
1241  201412  서울특별시  중랑구   합계  158,890    93,944,534

[150 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[426429379, 440612957, 387865406, 334893609, 331439593, 404583304]
[132419171, 139509634, 126138698, 111992504, 113861923, 130622739]
[76120177, 83020760, 75927679, 66675729, 68837158, 77881018]
[172380267, 183895103, 168752037, 149424753, 152071054, 172890475]
[141761036, 155001827, 139831464, 123124980, 125286082, 141331166]
[146817870, 156002969, 141348936, 120012565, 120570580, 136953115]
[163209687, 168129603, 152638819, 139732589, 143288157, 170240336]
[144396583, 145226764, 131102518, 118889042, 120493142, 144608856]
[130030748, 138098375, 125207061, 111931095, 115695090, 131283039]
[76093940, 81751375, 74290807, 66256026, 69139028, 77515402]
[124567161, 134388982, 121079147, 105282649, 106861718, 123178908]
[111710681, 118347598, 107191779, 94854136, 96325030, 109041923]
[174367414, 183464685, 165823605, 147142081, 146133877, 169308502]
[107971066, 112014524, 101516688, 90326813, 90110756, 106351543]
[315036578, 332568408, 298861921, 261821613, 259506385, 295987022]
[164188882, 170612006, 156793673, 143670561, 144715438, 163871481]
[123729991, 131798818, 121155639, 106857922, 110755863, 127203234]
[232613858, 236588667, 212551045, 196435782, 192975795, 219352704]
[130913973, 142855012, 131968685, 118268948, 115776037, 125376487]
[244227392, 248205489, 221462903, 194239657, 189328464, 222047710]
[123836274, 130716177, 117370849, 100717379, 99874461, 116880454]
[110805545, 121193510, 110459311, 98174828, 100135744, 110189246]
[160182138, 163217795, 145792878, 126092635, 125677988, 151832391]
[245564252, 242897085, 218258751, 189737342, 181960521, 219028254]
[92868004, 100714534, 91286883, 80190884, 83135292, 93944534]
서울특별시 지역별 합계 :  [2325824248, 754544669, 448462521, 999413689, 826336555, 821706035, 937239191, 804716905, 752245408, 445046578, 715358565, 637471147, 986240164, 608291390, 1763781927, 943852041, 721501467, 1290517851, 765159142, 1319511615, 689395594, 650958184, 872795825, 1297446205, 542140131]
서울특별시 고객호수 평균:  [33090, 21387, 21629, 31821, 39423, 25836, 20564, 15065, 17618, 15707, 24337, 25101, 24936, 19578, 20572, 15764, 25188, 28599, 20627, 22050, 17409, 31562, 15079, 12650, 26385]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\527191269.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201407  서울특별시  강남구   합계  198,182   426,429,379
1           201408  서울특별시  강남구   합계  198,338   440,612,957
2           201409  서울특별시  강남구   합계  198,408   387,865,406
3           201410  서울특별시  강남구   합계  198,525   334,893,609
4           201411  서울특별시  강남구   합계  198,793   331,439,593
..             ...    ...  ...  ...       ...           ...
170  201407-201412  서울특별시  용산구   합계     17409     689395594
171  201407-201412  서울특별시  은평구   합계     31562     650958184
172  201407-201412  서울특별시  종로구   합계     15079     872795825
173  201407-201412  서울특별시   중구   합계     12650    1297446205
174  201407-201412  서울특별시  중랑구   합계     26385     542140131

[175 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201407-201412']
Hap

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201407-201412  서울특별시   강남구   합계   33090  2325824248
151  201407-201412  서울특별시   강동구   합계   21387   754544669
152  201407-201412  서울특별시   강북구   합계   21629   448462521
153  201407-201412  서울특별시   강서구   합계   31821   999413689
154  201407-201412  서울특별시   관악구   합계   39423   826336555
155  201407-201412  서울특별시   광진구   합계   25836   821706035
156  201407-201412  서울특별시   구로구   합계   20564   937239191
157  201407-201412  서울특별시   금천구   합계   15065   804716905
158  201407-201412  서울특별시   노원구   합계   17618   752245408
159  201407-201412  서울특별시   도봉구   합계   15707   445046578
160  201407-201412  서울특별시  동대문구   합계   24337   715358565
161  201407-201412  서울특별시   동작구   합계   25101   637471147
162  201407-201412  서울특별시   마포구   합계   24936   986240164
163  201407-201412  서울특별시  서대문구   합계   19578   608291390
164  201407-201412  서울특별시   서초구   합계   20572  1763781927
165  201407-201412  서울특별시   성동구   합계   15764   943852041
166  201407-201412  서울특별시   성북구   합계   25188   721501467
167  201407-201412  서울특별시   송파구   합계   28599  1290517851
168  201407-201412  서울특별시   양천구   합계   20627   765159142
169  201407-201412  서울특별시  영등포구   합계   22050  1319511615
170  201407-201412  서울특별시   용산구   합계   17409   689395594
171  201407-201412  서울특별시   은평구   합계   31562   650958184
172  201407-201412  서울특별시   종로구   합계   15079   872795825
173  201407-201412  서울특별시    중구   합계   12650  1297446205
174  201407-201412  서울특별시   중랑구   합계   26385   542140131

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

          년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
53    201407  서울특별시  강남구  일반용  48,134   317,288,867
252   201408  서울특별시  강남구  일반용  48,313   327,157,997
451   201409  서울특별시  강남구  일반용  48,354   287,544,573
650   201410  서울특별시  강남구  일반용  48,395   247,137,079
849   201411  서울특별시  강남구  일반용  48,506   241,641,030
...      ...    ...  ...  ...      ...           ...
443   201408  서울특별시  중랑구  일반용  19,119    44,281,378
642   201409  서울특별시  중랑구  일반용  19,092    39,363,988
841   201410  서울특별시  중랑구  일반용  19,071    33,327,637
1040  201411  서울특별시  중랑구  일반용  19,078    33,239,422
1239  201412  서울특별시  중랑구  일반용  19,135    39,590,685

[150 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[317288867, 327157997, 287544573, 247137079, 241641030, 300108580]
[65131680, 68655380, 61069780, 51293571, 50505788, 61344059]
[36329118, 39573194, 35602710, 29983383, 29741125, 35339483]
[84924837, 90251466, 81315398, 68524865, 67394802, 81648652]
[68453140, 74359103, 66401303, 56664560, 55241528, 62850181]
[59545263, 62675755, 55567385, 46910382, 46067129, 55352762]
[76772571, 77883784, 68877708, 63968999, 63183610, 80326799]
[87902324, 87086126, 77514112, 69205350, 68834105, 86502923]
[55445874, 58563274, 52369320, 44703057, 43934093, 52175381]
[30785195, 33093941, 29543682, 25012631, 24867392, 29698812]
[59606818, 64120563, 56739743, 47895422, 47051853, 56319915]
[55063478, 57911171, 51773364, 44364762, 42758554, 50440974]
[103323630, 108834127, 97881549, 87444171, 84063932, 99910425]
[53049366, 54806453, 49207760, 42310133, 41118071, 49364763]
[194504726, 203530790, 180101955, 157313086, 152520770, 181373875]
[56317376, 58935123, 52981773, 46348673, 46234375, 57189999]
[48690855, 52121945, 46925328, 39797410, 39366790, 46730949]
[134364698, 131006610, 115796891, 108454436, 102134888, 121978413]
[68524287, 74785082, 69705336, 61941390, 58466935, 64208794]
[162084119, 162678323, 144546114, 126527950, 121512877, 146955182]
[73883899, 76741239, 68340068, 57134300, 55170319, 67268577]
[42698232, 46771791, 41832861, 35229720, 34682564, 40614762]
[115802102, 117397411, 103884476, 90325098, 88813459, 108822346]
[192305686, 189116906, 169090375, 148970818, 142104156, 172163784]
[41175322, 44281378, 39363988, 33327637, 33239422, 39590685]
서울특별시 지역별 일반용 합계 :  [1720878126, 358000258, 206569013, 474060020, 383969815, 326118676, 431013471, 477044940, 307190999, 173001653, 331734314, 302312303, 581457834, 289856546, 1069345202, 318007319, 273633277, 713735936, 397631824, 864304565, 398538402, 241829930, 625044892, 1013751725, 230978432]
서울특별시 고객호수 평균:  [48402, 19625, 15665, 22207, 24681, 20079, 17330, 12884, 14637, 11809, 24029, 16370, 26628, 15950, 29580, 15425, 20977, 28077, 16500, 23925, 15919, 20010, 24737, 24552, 19104]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_18032\422212722.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201407-201412'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월     시구  시군구 계약구분  고객호수(호)      사용량(kWh)
0           201407  서울특별시  강남구  일반용  48,134   317,288,867
1           201408  서울특별시  강남구  일반용  48,313   327,157,997
2           201409  서울특별시  강남구  일반용  48,354   287,544,573
3           201410  서울특별시  강남구  일반용  48,395   247,137,079
4           201411  서울특별시  강남구  일반용  48,506   241,641,030
..             ...    ...  ...  ...      ...           ...
170  201407-201412  서울특별시  용산구  일반용    15919     398538402
171  201407-201412  서울특별시  은평구  일반용    20010     241829930
172  201407-201412  서울특별시  종로구  일반용    24737     625044892
173  201407-201412  서울특별시   중구  일반용    24552    1013751725
174  201407-201412  서울특별시  중랑구  일반용    19104     230978432

[175 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201407-201412']
GyeonGiHap2

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201407-201412  서울특별시   강남구  일반용   48402  1720878126
151  201407-201412  서울특별시   강동구  일반용   19625   358000258
152  201407-201412  서울특별시   강북구  일반용   15665   206569013
153  201407-201412  서울특별시   강서구  일반용   22207   474060020
154  201407-201412  서울특별시   관악구  일반용   24681   383969815
155  201407-201412  서울특별시   광진구  일반용   20079   326118676
156  201407-201412  서울특별시   구로구  일반용   17330   431013471
157  201407-201412  서울특별시   금천구  일반용   12884   477044940
158  201407-201412  서울특별시   노원구  일반용   14637   307190999
159  201407-201412  서울특별시   도봉구  일반용   11809   173001653
160  201407-201412  서울특별시  동대문구  일반용   24029   331734314
161  201407-201412  서울특별시   동작구  일반용   16370   302312303
162  201407-201412  서울특별시   마포구  일반용   26628   581457834
163  201407-201412  서울특별시  서대문구  일반용   15950   289856546
164  201407-201412  서울특별시   서초구  일반용   29580  1069345202
165  201407-201412  서울특별시   성동구  일반용   15425   318007319
166  201407-201412  서울특별시   성북구  일반용   20977   273633277
167  201407-201412  서울특별시   송파구  일반용   28077   713735936
168  201407-201412  서울특별시   양천구  일반용   16500   397631824
169  201407-201412  서울특별시  영등포구  일반용   23925   864304565
170  201407-201412  서울특별시   용산구  일반용   15919   398538402
171  201407-201412  서울특별시   은평구  일반용   20010   241829930
172  201407-201412  서울특별시   종로구  일반용   24737   625044892
173  201407-201412  서울특별시    중구  일반용   24552  1013751725
174  201407-201412  서울특별시   중랑구  일반용   19104   230978432

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)
150  201407-201412  서울특별시   강남구  일반용   48402  1720878126
150  201407-201412  서울특별시   강남구   합계   33090  2325824248
151  201407-201412  서울특별시   강동구   합계   21387   754544669
151  201407-201412  서울특별시   강동구  일반용   19625   358000258
152  201407-201412  서울특별시   강북구  일반용   15665   206569013
152  201407-201412  서울특별시   강북구   합계   21629   448462521
153  201407-201412  서울특별시   강서구  일반용   22207   474060020
153  201407-201412  서울특별시   강서구   합계   31821   999413689
154  201407-201412  서울특별시   관악구  일반용   24681   383969815
154  201407-201412  서울특별시   관악구   합계   39423   826336555
155  201407-201412  서울특별시   광진구  일반용   20079   326118676
155  201407-201412  서울특별시   광진구   합계   25836   821706035
156  201407-201412  서울특별시   구로구  일반용   17330   431013471
156  201407-201412  서울특별시   구로구   합계   20564   937239191
157  201407-201412  서울특별시   금천구  일반용   12884   477044940
157  201407-201412  서울특별시   금천구   합계   15065   804716905
158  201407-201412  서울특별시   노원구   합계   17618   752245408
158  201407-201412  서울특별시   노원구  일반용   14637   307190999
159  201407-201412  서울특별시   도봉구   합계   15707   445046578
159  201407-201412  서울특별시   도봉구  일반용   11809   173001653
160  201407-201412  서울특별시  동대문구   합계   24337   715358565
160  201407-201412  서울특별시  동대문구  일반용   24029   331734314
161  201407-201412  서울특별시   동작구   합계   25101   637471147
161  201407-201412  서울특별시   동작구  일반용   16370   302312303
162  201407-201412  서울특별시   마포구   합계   24936   986240164
162  201407-201412  서울특별시   마포구  일반용   26628   581457834
163  201407-201412  서울특별시  서대문구   합계   19578   608291390
163  201407-201412  서울특별시  서대문구  일반용   15950   289856546
164  201407-201412  서울특별시   서초구  일반용   29580  1069345202
164  201407-201412  서울특별시   서초구   합계   20572  1763781927
165  201407-201412  서울특별시   성동구   합계   15764   943852041
165  201407-201412  서울특별시   성동구  일반용   15425   318007319
166  201407-201412  서울특별시   성북구   합계   25188   721501467
166  201407-201412  서울특별시   성북구  일반용   20977   273633277
167  201407-201412  서울특별시   송파구   합계   28599  1290517851
167  201407-201412  서울특별시   송파구  일반용   28077   713735936
168  201407-201412  서울특별시   양천구   합계   20627   765159142
168  201407-201412  서울특별시   양천구  일반용   16500   397631824
169  201407-201412  서울특별시  영등포구  일반용   23925   864304565
169  201407-201412  서울특별시  영등포구   합계   22050  1319511615
170  201407-201412  서울특별시   용산구   합계   17409   689395594
170  201407-201412  서울특별시   용산구  일반용   15919   398538402
171  201407-201412  서울특별시   은평구   합계   31562   650958184
171  201407-201412  서울특별시   은평구  일반용   20010   241829930
172  201407-201412  서울특별시   종로구   합계   15079   872795825
172  201407-201412  서울특별시   종로구  일반용   24737   625044892
173  201407-201412  서울특별시    중구   합계   12650  1297446205
173  201407-201412  서울특별시    중구  일반용   24552  1013751725
174  201407-201412  서울특별시   중랑구  일반용   19104   230978432
174  201407-201412  서울특별시   중랑구   합계   26385   542140131

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[1720878126,
 358000258,
 206569013,
 474060020,
 383969815,
 326118676,
 431013471,
 477044940,
 307190999,
 173001653,
 331734314,
 302312303,
 581457834,
 289856546,
 1069345202,
 318007319,
 273633277,
 713735936,
 397631824,
 864304565,
 398538402,
 241829930,
 625044892,
 1013751725,
 230978432]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[2325824248,
 754544669,
 448462521,
 999413689,
 826336555,
 821706035,
 937239191,
 804716905,
 752245408,
 445046578,
 715358565,
 637471147,
 986240164,
 608291390,
 1763781927,
 943852041,
 721501467,
 1290517851,
 765159142,
 1319511615,
 689395594,
 650958184,
 872795825,
 1297446205,
 542140131]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[73.99, 47.45, 46.06, 47.43, 46.47, 39.69, 45.99, 59.28, 40.84, 38.87, 46.37, 47.42, 58.96, 47.65, 60.63, 33.69, 37.93, 55.31, 51.97, 65.5, 57.81, 37.15, 71.61, 78.13, 42.6]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    74
1    47
2    46
3    47
4    46
5    40
6    46
7    59
8    41
9    39
10   46
11   47
12   59
13   48
14   61
15   34
16   38
17   55
18   52
19   66
20   58
21   37
22   72
23   78
24   43
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

     시군구 계약구분  비율
0    강남구  일반용  74
1    강동구  일반용  47
2    강북구  일반용  46
3    강서구  일반용  47
4    관악구  일반용  46
5    광진구  일반용  40
6    구로구  일반용  46
7    금천구  일반용  59
8    노원구  일반용  41
9    도봉구  일반용  39
10  동대문구  일반용  46
11   동작구  일반용  47
12   마포구  일반용  59
13  서대문구  일반용  48
14   서초구  일반용  61
15   성동구  일반용  34
16   성북구  일반용  38
17   송파구  일반용  55
18   양천구  일반용  52
19  영등포구  일반용  66
20   용산구  일반용  58
21   은평구  일반용  37
22   종로구  일반용  72
23    중구  일반용  78
24   중랑구  일반용  43

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구   시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201407-201412  서울특별시   강남구  일반용   48402  1720878126  74
1   201407-201412  서울특별시   강남구   합계   33090  2325824248 NaN
3   201407-201412  서울특별시   강동구  일반용   19625   358000258  47
2   201407-201412  서울특별시   강동구   합계   21387   754544669 NaN
4   201407-201412  서울특별시   강북구  일반용   15665   206569013  46
5   201407-201412  서울특별시   강북구   합계   21629   448462521 NaN
6   201407-201412  서울특별시   강서구  일반용   22207   474060020  47
7   201407-201412  서울특별시   강서구   합계   31821   999413689 NaN
8   201407-201412  서울특별시   관악구  일반용   24681   383969815  46
9   201407-201412  서울특별시   관악구   합계   39423   826336555 NaN
10  201407-201412  서울특별시   광진구  일반용   20079   326118676  40
11  201407-201412  서울특별시   광진구   합계   25836   821706035 NaN
12  201407-201412  서울특별시   구로구  일반용   17330   431013471  46
13  201407-201412  서울특별시   구로구   합계   20564   937239191 NaN
14  201407-201412  서울특별시   금천구  일반용   12884   477044940  59
15  201407-201412  서울특별시   금천구   합계   15065   804716905 NaN
17  201407-201412  서울특별시   노원구  일반용   14637   307190999  41
16  201407-201412  서울특별시   노원구   합계   17618   752245408 NaN
19  201407-201412  서울특별시   도봉구  일반용   11809   173001653  39
18  201407-201412  서울특별시   도봉구   합계   15707   445046578 NaN
21  201407-201412  서울특별시  동대문구  일반용   24029   331734314  46
20  201407-201412  서울특별시  동대문구   합계   24337   715358565 NaN
23  201407-201412  서울특별시   동작구  일반용   16370   302312303  47
22  201407-201412  서울특별시   동작구   합계   25101   637471147 NaN
25  201407-201412  서울특별시   마포구  일반용   26628   581457834  59
24  201407-201412  서울특별시   마포구   합계   24936   986240164 NaN
27  201407-201412  서울특별시  서대문구  일반용   15950   289856546  48
26  201407-201412  서울특별시  서대문구   합계   19578   608291390 NaN
28  201407-201412  서울특별시   서초구  일반용   29580  1069345202  61
29  201407-201412  서울특별시   서초구   합계   20572  1763781927 NaN
31  201407-201412  서울특별시   성동구  일반용   15425   318007319  34
30  201407-201412  서울특별시   성동구   합계   15764   943852041 NaN
33  201407-201412  서울특별시   성북구  일반용   20977   273633277  38
32  201407-201412  서울특별시   성북구   합계   25188   721501467 NaN
35  201407-201412  서울특별시   송파구  일반용   28077   713735936  55
34  201407-201412  서울특별시   송파구   합계   28599  1290517851 NaN
37  201407-201412  서울특별시   양천구  일반용   16500   397631824  52
36  201407-201412  서울특별시   양천구   합계   20627   765159142 NaN
38  201407-201412  서울특별시  영등포구  일반용   23925   864304565  66
39  201407-201412  서울특별시  영등포구   합계   22050  1319511615 NaN
41  201407-201412  서울특별시   용산구  일반용   15919   398538402  58
40  201407-201412  서울특별시   용산구   합계   17409   689395594 NaN
43  201407-201412  서울특별시   은평구  일반용   20010   241829930  37
42  201407-201412  서울특별시   은평구   합계   31562   650958184 NaN
45  201407-201412  서울특별시   종로구  일반용   24737   625044892  72
44  201407-201412  서울특별시   종로구   합계   15079   872795825 NaN
47  201407-201412  서울특별시    중구  일반용   24552  1013751725  78
46  201407-201412  서울특별시    중구   합계   12650  1297446205 NaN
48  201407-201412  서울특별시   중랑구  일반용   19104   230978432  43
49  201407-201412  서울특별시   중랑구   합계   26385   542140131 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1407-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)