In [5]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [6]:
df = pd.read_csv('강원도_계약종별_전력사용량_월별_19하반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 강원도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2019년 07 월 ~ 2019년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201907,강원도,전체(시 / 군 / 구),주택용,"600,817","166,026,328","15,711,090,342",94.6
4,201907,강원도,전체(시 / 군 / 구),일반용,"146,145","368,475,620","55,310,089,495",150.1
...,...,...,...,...,...,...,...,...
907,201912,강원도,횡성군,산업용,740,"18,582,657","2,515,168,627",135.4
908,201912,강원도,횡성군,심 야,"6,254","14,157,755","1,057,459,102",74.7
909,201912,강원도,횡성군,일반용,"5,173","13,326,720","1,755,531,950",131.7
910,201912,강원도,횡성군,주택용,"25,519","5,453,432","612,156,235",112.3
911,201912,강원도,횡성군,합계,"57,241","59,732,405","6,453,741,076",108

In [7]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,강원도,전체(시 / 군 / 구),주택용,"577,557","195,758,936","22,479,624,624",114.8
4,201801,강원도,전체(시 / 군 / 구),일반용,"142,476","490,016,414","63,445,653,968",129.5
5,201801,강원도,전체(시 / 군 / 구),교육용,"1,064","40,893,826","4,013,385,797",98.1
6,201801,강원도,전체(시 / 군 / 구),산업용,"13,316","583,013,251","68,524,411,231",117.5
...,...,...,...,...,...,...,...,...
907,201806,강원도,횡성군,산업용,683,"16,994,072","2,227,837,431",131.1
908,201806,강원도,횡성군,심 야,"6,370","4,421,467","237,793,841",53.8
909,201806,강원도,횡성군,일반용,"4,945","8,218,949","1,176,439,924",143.1
910,201806,강원도,횡성군,주택용,"23,900","4,609,625","500,759,208",108.6
911,201806,강원도,횡성군,합계,"53,836","40,672,946","4,552,481,992",111.9

In [8]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [9]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,강원도,전체(시 / 군 / 구),주택용,"577,557","195,758,936","22,479,624,624",114.8
4,201801,강원도,전체(시 / 군 / 구),일반용,"142,476","490,016,414","63,445,653,968",129.5
5,201801,강원도,전체(시 / 군 / 구),교육용,"1,064","40,893,826","4,013,385,797",98.1
6,201801,강원도,전체(시 / 군 / 구),산업용,"13,316","583,013,251","68,524,411,231",117.5
7,201801,강원도,전체(시 / 군 / 구),농사용,"97,639","56,533,792","2,808,580,572",49.7
...,...,...,...,...,...,...,...,...
907,201806,강원도,횡성군,산업용,683,"16,994,072","2,227,837,431",131.1
908,201806,강원도,횡성군,심 야,"6,370","4,421,467","237,793,841",53.8
909,201806,강원도,횡성군,일반용,"4,945","8,218,949","1,176,439,924",143.1
910,201806,강원도,횡성군,주택용,"23,900","4,609,625","500,759,208",108.6
911,201806,강원도,횡성군,합계,"53,836","40,672,946","4,552,481,992",111.9

In [10]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201801,강원도,전체(시 / 군 / 구),주택용,"577,557","195,758,936","22,479,624,624",114.8
4,201801,강원도,전체(시 / 군 / 구),일반용,"142,476","490,016,414","63,445,653,968",129.5
5,201801,강원도,전체(시 / 군 / 구),교육용,"1,064","40,893,826","4,013,385,797",98.1
6,201801,강원도,전체(시 / 군 / 구),산업용,"13,316","583,013,251","68,524,411,231",117.5
7,201801,강원도,전체(시 / 군 / 구),농사용,"97,639","56,533,792","2,808,580,572",49.7
8,201801,강원도,전체(시 / 군 / 구),가로등,"110,811","18,480,777","2,011,990,399",108.9
9,201801,강원도,전체(시 / 군 / 구),심 야,"92,239","283,641,627","21,253,280,608",74.9
10,201802,강원도,전체(시 / 군 / 구),주택용,"578,969","200,027,227","23,274,518,261",116.4
11,201802,강원도,전체(시 / 군 / 구),일반용,"142,608","504,821,616","64,952,273,074",128.7
12,201802,강원도,전체(시 / 군 / 구),교육용,"1,065","39,587,191","3,946,808,614",99.7
13,201802,강원도,전체(시 / 군 / 구),산업용,"13,340","551,599,238","64,032,697,705",116.1
14,201802,강원도,전체(시 / 군 / 구),농사용,"97,651","59,938,093","2,949,450,515",49.2
15,201802,강원도,전체(시 / 군 / 구),가로등,"111,381","18,094,343","2,049,817,640",113.3
16,201802,강원도,전체(시 / 군 / 구),심 야,"92,171","300,677,323","22,536,322,129",75.0
17,201803,강원도,전체(시 / 군 / 구),주택용,"580,193","171,650,494","17,898,554,481",104.3
18,201803,강원도,전체(시 / 군 / 구),일반용,"142,598","388,541,345","47,552,126,634",122.4
19,201803,강원도,전체(시 / 군 / 구),교육용,"1,063","33,299,713","3,351,726,452",100.7
20,201803,강원도,전체(시 / 군 / 구),산업용,"13,354","600,729,214","57,477,992,330",95.7
21,201803,강원도,전체(시 / 군 / 구),농사용,"120,129","52,053,807","2,609,994,574",50.1
22,201803,강원도,전체(시 / 군 / 구),가로등,"111,724","17,072,443","1,940,073,352",113.6
23,201803,강원도,전체(시 / 군 / 구),심 야,"92,067","221,846,562","14,802,402,946",66.7
24,201804,강원도,전체(시 / 군 / 구),주택용,"581,589","172,478,031","18,038,443,854",104.6
25,201804,강원도,전체(시 / 군 / 구),일반용,"142,407","343,873,872","39,698,341,012",115.4
26,201804,강원도,전체(시 / 군 / 구),교육용,"1,054","28,057,437","2,621,262,811",93.4
27,201804,강원도,전체(시 / 군 / 구),산업용,"13,371","596,955,880","56,249,516,502",94.2
28,201804,강원도,전체(시 / 군 / 구),농사용,"98,626","49,967,162","2,503,793,776",50.1
29,201804,강원도,전체(시 / 군 / 구),가로등,"112,162","19,018,912","2,154,558,145",113.3
30,201804,강원도,전체(시 / 군 / 구),심 야,"91,951","159,942,871","8,653,212,758",54.1
31,201805,강원도,전체(시 / 군 / 구),주택용,"582,861","160,822,654","16,202,852,494",100.7
32,201805,강원도,전체(시 / 군 / 구),일반용,"142,491","316,206,078","37,570,397,581",118.8
33,201805,강원도,전체(시 / 군 / 구),교육용,"1,057","21,238,812","2,063,340,073",97.1
34,201805,강원도,전체(시 / 군 / 구),산업용,"13,381","597,656,694","56,133,308,141",93.9
35,201805,강원도,전체(시 / 군 / 구),농사용,"99,418","46,083,759","2,204,069,617",47.8
36,201805,강원도,전체(시 / 군 / 구),가로등,"112,641","15,221,513","1,834,801,309",120.5
37,201805,강원도,전체(시 / 군 / 구),심 야,"91,755","105,628,245","5,734,364,472",54.3
38,201806,강원도,전체(시 / 군 / 구),주택용,"584,322","162,508,412","16,523,066,479",101.7
39,201806,강원도,전체(시 / 군 / 구),일반용,"142,815","334,050,672","44,990,672,809",134.7
40,201806,강원도,전체(시 / 군 / 구),교육용,"1,057","20,924,086","2,406,417,812",115.0
41,201806,강원도,전체(시 / 군 / 구),산업용,"13,414","601,239,070","67,785,824,642",112.7
42,201806,강원도,전체(시 / 군 / 구),농사용,"100,196","49,561,565","2,490,463,974",50.2
43,201806,강원도,전체(시 / 군 / 구),가로등,"113,079","16,437,214","1,956,551,776",119.0
44,201806,강원도,전체(시 / 군 / 구),심 야,"91,579","65,660,329","3,605,006,718",54.9
45,합계,합계,합계,합계,"6,264,641","8,711,810,500","905,331,952,661",103.9

In [11]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_9500\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)      사용량(kWh)
4   201801  강원도  일반용  142,476   490,016,414
11  201802  강원도  일반용  142,608   504,821,616
18  201803  강원도  일반용  142,598   388,541,345
25  201804  강원도  일반용  142,407   343,873,872
32  201805  강원도  일반용  142,491   316,206,078
39  201806  강원도  일반용  142,815   334,050,672

In [12]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [13]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [14]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201801  강원도  강릉시  일반용  19,468   56,863,381
197  201802  강원도  강릉시  일반용  19,558   66,610,603
341  201803  강원도  강릉시  일반용  19,666   50,102,144
485  201804  강원도  강릉시  일반용  19,564   43,719,193
629  201805  강원도  강릉시  일반용  19,535   40,086,409
..      ...  ...  ...  ...      ...          ...
333  201802  강원도  횡성군  일반용   4,968   13,572,670
477  201803  강원도  횡성군  일반용   4,930   10,378,633
621  201804  강원도  횡성군  일반용   4,933    8,620,874
765  201805  강원도  횡성군  일반용   4,938    7,819,647
909  201806  강원도  횡성군  일반용   4,945    8,218,949

[108 rows x 6 columns]

In [15]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'강원도'

In [16]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강릉시',
 '고성군',
 '동해시',
 '삼척시',
 '속초시',
 '양구군',
 '양양군',
 '영월군',
 '원주시',
 '인제군',
 '정선군',
 '철원군',
 '춘천시',
 '태백시',
 '평창군',
 '홍천군',
 '화천군',
 '횡성군']

In [17]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201801  강원도  강릉시   합계  131,694   179,457,107
199  201802  강원도  강릉시   합계  132,003   192,253,540
343  201803  강원도  강릉시   합계  132,682   168,549,416
487  201804  강원도  강릉시   합계  132,527   155,199,524
631  201805  강원도  강릉시   합계  132,651   153,905,432
..      ...  ...  ...  ...       ...           ...
335  201802  강원도  횡성군   합계   53,174    67,456,931
479  201803  강원도  횡성군   합계   55,202    54,904,693
623  201804  강원도  횡성군   합계   53,407    47,990,767
767  201805  강원도  횡성군   합계   53,609    42,203,832
911  201806  강원도  횡성군   합계   53,836    40,672,946

[108 rows x 6 columns]

In [18]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[179457107, 192253540, 168549416, 155199524, 153905432, 154605955]
[32299932, 32946222, 27775931, 25256722, 22194221, 21873569]
[235049606, 216806047, 227503566, 232605828, 233725629, 225792342]
[123028981, 125151720, 127327821, 114208169, 99952389, 109207496]
[50927740, 52139075, 43035384, 40413405, 36617021, 36920055]
[26539384, 27606901, 21705089, 19134508, 15921430, 14612271]
[31288333, 31793046, 26602491, 23793204, 21388421, 20953732]
[84350186, 83624661, 98428217, 98954116, 95114163, 93473982]
[259020993, 256540548, 217516943, 195032529, 173335122, 175847095]
[39278595, 41652017, 32095271, 28226410, 24169735, 22497792]
[73961122, 64923138, 60018873, 54258196, 50523113, 45721583]
[56885191, 59884457, 46025467, 40304840, 34830238, 33039489]
[181413140, 180807642, 149297407, 137775591, 124438783, 125654086]
[33630393, 33293784, 28988667, 27843037, 24922650, 24063612]
[83622640, 92826672, 65861296, 49658791, 42702236, 38600358]
[81345252, 83127266, 65097059, 58538813, 49449910, 50386079]
[30201344, 31911364, 24459987, 21099715, 17463430, 16458906]
[66038684, 67456931, 54904693, 47990767, 42203832, 40672946]
강원도 지역별 합계 :  [1003970974, 162346597, 1371483018, 698876576, 260052680, 125519583, 155819227, 553945325, 1277293230, 187919820, 349406025, 270969682, 899386649, 172742143, 373271993, 387944379, 141594746, 319267853]
강원도 고객호수 평균:  [22068, 4817, 8142, 9126, 6639, 3820, 5033, 6743, 26150, 5746, 6437, 7131, 23829, 4644, 8670, 11911, 4149, 8953]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [19]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\2921283212.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201801  강원도  강릉시   합계  131,694   179,457,107
1           201802  강원도  강릉시   합계  132,003   192,253,540
2           201803  강원도  강릉시   합계  132,682   168,549,416
3           201804  강원도  강릉시   합계  132,527   155,199,524
4           201805  강원도  강릉시   합계  132,651   153,905,432
..             ...  ...  ...  ...       ...           ...
121  201801-201806  강원도  태백시   합계      4644     172742143
122  201801-201806  강원도  평창군   합계      8670     373271993
123  201801-201806  강원도  홍천군   합계     11911     387944379
124  201801-201806  강원도  화천군   합계      4149     141594746
125  201801-201806  강원도  횡성군   합계      8953     319267853

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [20]:
Hap = Hap.loc[Hap['년월'] == '201907-201912']
Hap

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201801-201806  강원도  강릉시   합계   22068  1003970974
109  201801-201806  강원도  고성군   합계    4817   162346597
110  201801-201806  강원도  동해시   합계    8142  1371483018
111  201801-201806  강원도  삼척시   합계    9126   698876576
112  201801-201806  강원도  속초시   합계    6639   260052680
113  201801-201806  강원도  양구군   합계    3820   125519583
114  201801-201806  강원도  양양군   합계    5033   155819227
115  201801-201806  강원도  영월군   합계    6743   553945325
116  201801-201806  강원도  원주시   합계   26150  1277293230
117  201801-201806  강원도  인제군   합계    5746   187919820
118  201801-201806  강원도  정선군   합계    6437   349406025
119  201801-201806  강원도  철원군   합계    7131   270969682
120  201801-201806  강원도  춘천시   합계   23829   899386649
121  201801-201806  강원도  태백시   합계    4644   172742143
122  201801-201806  강원도  평창군   합계    8670   373271993
123  201801-201806  강원도  홍천군   합계   11911   387944379
124  201801-201806  강원도  화천군   합계    4149   141594746
125  201801-201806  강원도  횡성군   합계    8953   319267853

In [21]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [22]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [23]:
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201801  강원도  강릉시  일반용  19,468   56,863,381
197  201802  강원도  강릉시  일반용  19,558   66,610,603
341  201803  강원도  강릉시  일반용  19,666   50,102,144
485  201804  강원도  강릉시  일반용  19,564   43,719,193
629  201805  강원도  강릉시  일반용  19,535   40,086,409
..      ...  ...  ...  ...      ...          ...
333  201802  강원도  횡성군  일반용   4,968   13,572,670
477  201803  강원도  횡성군  일반용   4,930   10,378,633
621  201804  강원도  횡성군  일반용   4,933    8,620,874
765  201805  강원도  횡성군  일반용   4,938    7,819,647
909  201806  강원도  횡성군  일반용   4,945    8,218,949

[108 rows x 6 columns]

In [24]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [25]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[56863381, 66610603, 50102144, 43719193, 40086409, 42260195]
[12961681, 13392033, 11057108, 10107991, 9290242, 9821730]
[21540022, 21977365, 18033595, 16663843, 15329576, 15644456]
[17069898, 17443446, 14358907, 13690452, 12489244, 12982839]
[26092441, 26865745, 21673480, 20310088, 19053974, 20018454]
[9971145, 10424686, 7895451, 7082184, 6163468, 6293708]
[13220697, 13715517, 11088165, 9800366, 9084912, 9237101]
[8526956, 8830106, 6928943, 6293555, 5675999, 5926158]
[86018578, 86865815, 67110256, 60174366, 55202383, 59524722]
[15967405, 16621532, 12443358, 10900568, 9846697, 10068160]
[27801959, 20443914, 17785365, 15290101, 13526260, 14178615]
[18427676, 19333170, 14089141, 12362890, 10771505, 11549227]
[75651946, 76035195, 62185833, 58117510, 55254175, 60159460]
[9842697, 10161065, 7970520, 7519195, 6664346, 6702808]
[35708422, 41241770, 25161363, 16213293, 15036973, 14537124]
[26975054, 26684316, 19654686, 17546932, 16915193, 18738508]
[13644410, 14602668, 10624397, 9460471, 7995075, 8188458]
[13732046, 13572670, 10378633, 8620874, 7819647, 8218949]
강원도 지역별 일반용 합계 :  [299641925, 66630785, 109188857, 88034786, 134014182, 47830642, 66146758, 42181717, 414896120, 75847720, 109026214, 86533609, 387404119, 48860631, 147898945, 126514689, 64515479, 62342819]
강원도 고객호수 평균:  [19557, 3904, 6979, 6404, 8078, 2677, 4165, 4124, 25023, 4456, 4986, 4748, 20556, 4115, 6500, 8080, 3258, 4949]

In [26]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [27]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [28]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [29]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201907-201912'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_9500\3263883619.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201801-201806'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201801  강원도  강릉시  일반용  19,468   56,863,381
1           201802  강원도  강릉시  일반용  19,558   66,610,603
2           201803  강원도  강릉시  일반용  19,666   50,102,144
3           201804  강원도  강릉시  일반용  19,564   43,719,193
4           201805  강원도  강릉시  일반용  19,535   40,086,409
..             ...  ...  ...  ...      ...          ...
121  201801-201806  강원도  태백시  일반용     4115     48860631
122  201801-201806  강원도  평창군  일반용     6500    147898945
123  201801-201806  강원도  홍천군  일반용     8080    126514689
124  201801-201806  강원도  화천군  일반용     3258     64515479
125  201801-201806  강원도  횡성군  일반용     4949     62342819

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [30]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201907-201912']
GyeonGiHap2

                년월   시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201801-201806  강원도  강릉시  일반용   19557  299641925
109  201801-201806  강원도  고성군  일반용    3904   66630785
110  201801-201806  강원도  동해시  일반용    6979  109188857
111  201801-201806  강원도  삼척시  일반용    6404   88034786
112  201801-201806  강원도  속초시  일반용    8078  134014182
113  201801-201806  강원도  양구군  일반용    2677   47830642
114  201801-201806  강원도  양양군  일반용    4165   66146758
115  201801-201806  강원도  영월군  일반용    4124   42181717
116  201801-201806  강원도  원주시  일반용   25023  414896120
117  201801-201806  강원도  인제군  일반용    4456   75847720
118  201801-201806  강원도  정선군  일반용    4986  109026214
119  201801-201806  강원도  철원군  일반용    4748   86533609
120  201801-201806  강원도  춘천시  일반용   20556  387404119
121  201801-201806  강원도  태백시  일반용    4115   48860631
122  201801-201806  강원도  평창군  일반용    6500  147898945
123  201801-201806  강원도  홍천군  일반용    8080  126514689
124  201801-201806  강원도  화천군  일반용    3258   64515479
125  201801-201806  강원도  횡성군  일반용    4949   62342819

In [31]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201801-201806  강원도  강릉시  일반용   19557   299641925
108  201801-201806  강원도  강릉시   합계   22068  1003970974
109  201801-201806  강원도  고성군  일반용    3904    66630785
109  201801-201806  강원도  고성군   합계    4817   162346597
110  201801-201806  강원도  동해시  일반용    6979   109188857
110  201801-201806  강원도  동해시   합계    8142  1371483018
111  201801-201806  강원도  삼척시   합계    9126   698876576
111  201801-201806  강원도  삼척시  일반용    6404    88034786
112  201801-201806  강원도  속초시   합계    6639   260052680
112  201801-201806  강원도  속초시  일반용    8078   134014182
113  201801-201806  강원도  양구군  일반용    2677    47830642
113  201801-201806  강원도  양구군   합계    3820   125519583
114  201801-201806  강원도  양양군   합계    5033   155819227
114  201801-201806  강원도  양양군  일반용    4165    66146758
115  201801-201806  강원도  영월군  일반용    4124    42181717
115  201801-201806  강원도  영월군   합계    6743   553945325
116  201801-201806  강원도  원주시  일반용   25023   414896120
116  201801-201806  강원도  원주시   합계   26150  1277293230
117  201801-201806  강원도  인제군  일반용    4456    75847720
117  201801-201806  강원도  인제군   합계    5746   187919820
118  201801-201806  강원도  정선군   합계    6437   349406025
118  201801-201806  강원도  정선군  일반용    4986   109026214
119  201801-201806  강원도  철원군   합계    7131   270969682
119  201801-201806  강원도  철원군  일반용    4748    86533609
120  201801-201806  강원도  춘천시  일반용   20556   387404119
120  201801-201806  강원도  춘천시   합계   23829   899386649
121  201801-201806  강원도  태백시   합계    4644   172742143
121  201801-201806  강원도  태백시  일반용    4115    48860631
122  201801-201806  강원도  평창군   합계    8670   373271993
122  201801-201806  강원도  평창군  일반용    6500   147898945
123  201801-201806  강원도  홍천군   합계   11911   387944379
123  201801-201806  강원도  홍천군  일반용    8080   126514689
124  201801-201806  강원도  화천군   합계    4149   141594746
124  201801-201806  강원도  화천군  일반용    3258    64515479
125  201801-201806  강원도  횡성군  일반용    4949    62342819
125  201801-201806  강원도  횡성군   합계    8953   319267853

In [32]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[299641925,
 66630785,
 109188857,
 88034786,
 134014182,
 47830642,
 66146758,
 42181717,
 414896120,
 75847720,
 109026214,
 86533609,
 387404119,
 48860631,
 147898945,
 126514689,
 64515479,
 62342819]

In [33]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1003970974,
 162346597,
 1371483018,
 698876576,
 260052680,
 125519583,
 155819227,
 553945325,
 1277293230,
 187919820,
 349406025,
 270969682,
 899386649,
 172742143,
 373271993,
 387944379,
 141594746,
 319267853]

In [34]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[29.85, 41.04, 7.96, 12.6, 51.53, 38.11, 42.45, 7.61, 32.48, 40.36, 31.2, 31.93, 43.07, 28.29, 39.62, 32.61, 45.56, 19.53]

In [35]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    30
1    41
2     8
3    13
4    52
5    38
6    42
7     8
8    32
9    40
10   31
11   32
12   43
13   28
14   40
15   33
16   46
17   20
dtype: float64

In [36]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강릉시  일반용  30
1   고성군  일반용  41
2   동해시  일반용   8
3   삼척시  일반용  13
4   속초시  일반용  52
5   양구군  일반용  38
6   양양군  일반용  42
7   영월군  일반용   8
8   원주시  일반용  32
9   인제군  일반용  40
10  정선군  일반용  31
11  철원군  일반용  32
12  춘천시  일반용  43
13  태백시  일반용  28
14  평창군  일반용  40
15  홍천군  일반용  33
16  화천군  일반용  46
17  횡성군  일반용  20

In [37]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201801-201806  강원도  강릉시  일반용   19557   299641925  30
1   201801-201806  강원도  강릉시   합계   22068  1003970974 NaN
2   201801-201806  강원도  고성군  일반용    3904    66630785  41
3   201801-201806  강원도  고성군   합계    4817   162346597 NaN
4   201801-201806  강원도  동해시  일반용    6979   109188857   8
5   201801-201806  강원도  동해시   합계    8142  1371483018 NaN
7   201801-201806  강원도  삼척시  일반용    6404    88034786  13
6   201801-201806  강원도  삼척시   합계    9126   698876576 NaN
9   201801-201806  강원도  속초시  일반용    8078   134014182  52
8   201801-201806  강원도  속초시   합계    6639   260052680 NaN
10  201801-201806  강원도  양구군  일반용    2677    47830642  38
11  201801-201806  강원도  양구군   합계    3820   125519583 NaN
13  201801-201806  강원도  양양군  일반용    4165    66146758  42
12  201801-201806  강원도  양양군   합계    5033   155819227 NaN
14  201801-201806  강원도  영월군  일반용    4124    42181717   8
15  201801-201806  강원도  영월군   합계    6743   553945325 NaN
16  201801-201806  강원도  원주시  일반용   25023   414896120  32
17  201801-201806  강원도  원주시   합계   26150  1277293230 NaN
18  201801-201806  강원도  인제군  일반용    4456    75847720  40
19  201801-201806  강원도  인제군   합계    5746   187919820 NaN
21  201801-201806  강원도  정선군  일반용    4986   109026214  31
20  201801-201806  강원도  정선군   합계    6437   349406025 NaN
23  201801-201806  강원도  철원군  일반용    4748    86533609  32
22  201801-201806  강원도  철원군   합계    7131   270969682 NaN
24  201801-201806  강원도  춘천시  일반용   20556   387404119  43
25  201801-201806  강원도  춘천시   합계   23829   899386649 NaN
27  201801-201806  강원도  태백시  일반용    4115    48860631  28
26  201801-201806  강원도  태백시   합계    4644   172742143 NaN
29  201801-201806  강원도  평창군  일반용    6500   147898945  40
28  201801-201806  강원도  평창군   합계    8670   373271993 NaN
31  201801-201806  강원도  홍천군  일반용    8080   126514689  33
30  201801-201806  강원도  홍천군   합계   11911   387944379 NaN
33  201801-201806  강원도  화천군  일반용    3258    64515479  46
32  201801-201806  강원도  화천군   합계    4149   141594746 NaN
34  201801-201806  강원도  횡성군  일반용    4949    62342819  20
35  201801-201806  강원도  횡성군   합계    8953   319267853 NaN

In [38]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [39]:
Final.to_csv("{}_일반용_전력사용량_1907-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [40]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [41]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [42]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [43]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [44]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [45]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [46]:
# SEOUL

In [47]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)