In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('전라북도_계약종별_전력사용량_월별_22상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 전라북도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2022년 01 월 ~ 2022년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,전라북도,전체(시 / 군 / 구),주택용,"686,565","238,834,399","28,097,544,670",117.6
4,202201,전라북도,전체(시 / 군 / 구),일반용,"147,881","394,404,696","51,634,181,393",130.9
...,...,...,...,...,...,...,...,...
715,202206,전라북도,진안군,산업용,991,"2,686,812","381,111,537",141.8
716,202206,전라북도,진안군,심 야,"1,660","836,039","52,077,337",62.3
717,202206,전라북도,진안군,일반용,"2,266","3,412,421","513,452,558",150.5
718,202206,전라북도,진안군,주택용,"15,970","2,255,231","305,469,737",135.4
719,202206,전라북도,진안군,합계,"34,141","14,610,991","1,647,560,895",112.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,전라북도,전체(시 / 군 / 구),주택용,"686,565","238,834,399","28,097,544,670",117.6
4,202201,전라북도,전체(시 / 군 / 구),일반용,"147,881","394,404,696","51,634,181,393",130.9
5,202201,전라북도,전체(시 / 군 / 구),교육용,"1,226","41,636,226","4,229,173,759",101.6
6,202201,전라북도,전체(시 / 군 / 구),산업용,"16,435","1,015,728,920","115,599,468,256",113.8
...,...,...,...,...,...,...,...,...
715,202206,전라북도,진안군,산업용,991,"2,686,812","381,111,537",141.8
716,202206,전라북도,진안군,심 야,"1,660","836,039","52,077,337",62.3
717,202206,전라북도,진안군,일반용,"2,266","3,412,421","513,452,558",150.5
718,202206,전라북도,진안군,주택용,"15,970","2,255,231","305,469,737",135.4
719,202206,전라북도,진안군,합계,"34,141","14,610,991","1,647,560,895",112.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,전라북도,전체(시 / 군 / 구),주택용,"686,565","238,834,399","28,097,544,670",117.6
4,202201,전라북도,전체(시 / 군 / 구),일반용,"147,881","394,404,696","51,634,181,393",130.9
5,202201,전라북도,전체(시 / 군 / 구),교육용,"1,226","41,636,226","4,229,173,759",101.6
6,202201,전라북도,전체(시 / 군 / 구),산업용,"16,435","1,015,728,920","115,599,468,256",113.8
7,202201,전라북도,전체(시 / 군 / 구),농사용,"166,351","188,396,157","9,120,553,446",48.4
...,...,...,...,...,...,...,...,...
715,202206,전라북도,진안군,산업용,991,"2,686,812","381,111,537",141.8
716,202206,전라북도,진안군,심 야,"1,660","836,039","52,077,337",62.3
717,202206,전라북도,진안군,일반용,"2,266","3,412,421","513,452,558",150.5
718,202206,전라북도,진안군,주택용,"15,970","2,255,231","305,469,737",135.4
719,202206,전라북도,진안군,합계,"34,141","14,610,991","1,647,560,895",112.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,202201,전라북도,전체(시 / 군 / 구),주택용,"686,565","238,834,399","28,097,544,670",117.6
4,202201,전라북도,전체(시 / 군 / 구),일반용,"147,881","394,404,696","51,634,181,393",130.9
5,202201,전라북도,전체(시 / 군 / 구),교육용,"1,226","41,636,226","4,229,173,759",101.6
6,202201,전라북도,전체(시 / 군 / 구),산업용,"16,435","1,015,728,920","115,599,468,256",113.8
7,202201,전라북도,전체(시 / 군 / 구),농사용,"166,351","188,396,157","9,120,553,446",48.4
8,202201,전라북도,전체(시 / 군 / 구),가로등,"161,591","18,787,082","1,970,150,239",104.9
9,202201,전라북도,전체(시 / 군 / 구),심 야,"56,677","111,524,963","8,290,415,144",74.3
10,202202,전라북도,전체(시 / 군 / 구),주택용,"687,357","241,050,005","28,717,628,659",119.1
11,202202,전라북도,전체(시 / 군 / 구),일반용,"148,069","387,544,596","51,463,585,066",132.8
12,202202,전라북도,전체(시 / 군 / 구),교육용,"1,229","37,083,203","3,912,852,768",105.5
13,202202,전라북도,전체(시 / 군 / 구),산업용,"16,465","916,107,433","106,460,521,613",116.2
14,202202,전라북도,전체(시 / 군 / 구),농사용,"166,208","189,164,216","9,141,630,753",48.3
15,202202,전라북도,전체(시 / 군 / 구),가로등,"161,638","17,480,095","1,958,685,444",112.1
16,202202,전라북도,전체(시 / 군 / 구),심 야,"56,500","116,472,168","8,657,487,720",74.3
17,202203,전라북도,전체(시 / 군 / 구),주택용,"687,683","208,741,405","22,900,655,293",109.7
18,202203,전라북도,전체(시 / 군 / 구),일반용,"148,340","328,115,109","41,632,840,097",126.9
19,202203,전라북도,전체(시 / 군 / 구),교육용,"1,227","36,957,545","3,746,873,874",101.4
20,202203,전라북도,전체(시 / 군 / 구),산업용,"16,464","1,008,096,208","94,589,123,460",93.8
21,202203,전라북도,전체(시 / 군 / 구),농사용,"232,802","162,663,623","7,961,249,322",48.9
22,202203,전라북도,전체(시 / 군 / 구),가로등,"161,821","16,599,686","1,863,125,692",112.2
23,202203,전라북도,전체(시 / 군 / 구),심 야,"56,367","91,962,126","6,080,548,441",66.1
24,202204,전라북도,전체(시 / 군 / 구),주택용,"688,357","215,415,939","24,781,423,213",115.0
25,202204,전라북도,전체(시 / 군 / 구),일반용,"148,686","304,255,295","36,817,883,660",121.0
26,202204,전라북도,전체(시 / 군 / 구),교육용,"1,227","32,997,211","3,124,811,329",94.7
27,202204,전라북도,전체(시 / 군 / 구),산업용,"16,551","968,577,952","97,158,391,384",100.3
28,202204,전라북도,전체(시 / 군 / 구),농사용,"212,907","148,466,003","7,771,080,033",52.3
29,202204,전라북도,전체(시 / 군 / 구),가로등,"162,306","16,239,515","1,962,638,421",120.9
30,202204,전라북도,전체(시 / 군 / 구),심 야,"56,226","70,191,532","3,955,855,945",56.4
31,202205,전라북도,전체(시 / 군 / 구),주택용,"688,943","194,113,820","22,516,692,210",116.0
32,202205,전라북도,전체(시 / 군 / 구),일반용,"148,932","276,881,040","35,832,572,229",129.4
33,202205,전라북도,전체(시 / 군 / 구),교육용,"1,227","23,318,292","2,351,470,095",100.8
34,202205,전라북도,전체(시 / 군 / 구),산업용,"16,592","985,440,428","98,479,029,321",99.9
35,202205,전라북도,전체(시 / 군 / 구),농사용,"168,805","136,571,089","7,576,794,828",55.5
36,202205,전라북도,전체(시 / 군 / 구),가로등,"162,585","15,415,117","1,986,698,708",128.9
37,202205,전라북도,전체(시 / 군 / 구),심 야,"56,104","38,418,127","2,346,745,105",61.1
38,202206,전라북도,전체(시 / 군 / 구),주택용,"689,381","197,973,878","23,142,026,386",116.9
39,202206,전라북도,전체(시 / 군 / 구),일반용,"149,286","305,111,127","43,358,027,176",142.1
40,202206,전라북도,전체(시 / 군 / 구),교육용,"1,227","26,419,269","3,150,611,706",119.3
41,202206,전라북도,전체(시 / 군 / 구),산업용,"16,609","999,059,899","121,322,602,313",121.4
42,202206,전라북도,전체(시 / 군 / 구),농사용,"169,712","154,215,841","8,252,006,663",53.5
43,202206,전라북도,전체(시 / 군 / 구),가로등,"162,965","14,826,393","1,980,988,362",133.6
44,202206,전라북도,전체(시 / 군 / 구),심 야,"55,961","24,344,719","1,520,048,560",62.4
45,합계,합계,합계,합계,"7,553,485","10,915,602,347","1,157,416,692,756",106

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_16124\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   202201  전라북도  일반용  147,881   394,404,696
11  202202  전라북도  일반용  148,069   387,544,596
18  202203  전라북도  일반용  148,340   328,115,109
25  202204  전라북도  일반용  148,686   304,255,295
32  202205  전라북도  일반용  148,932   276,881,040
39  202206  전라북도  일반용  149,286   305,111,127

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53   202201  전라북도  고창군  일반용  4,966   11,623,117
165  202202  전라북도  고창군  일반용  4,965   11,588,267
277  202203  전라북도  고창군  일반용  4,963   10,014,409
389  202204  전라북도  고창군  일반용  4,979    9,455,253
501  202205  전라북도  고창군  일반용  5,002    8,346,809
..      ...   ...  ...  ...     ...          ...
269  202202  전라북도  진안군  일반용  2,255    5,340,714
381  202203  전라북도  진안군  일반용  2,257    4,532,343
493  202204  전라북도  진안군  일반용  2,261    3,999,821
605  202205  전라북도  진안군  일반용  2,265    3,403,054
717  202206  전라북도  진안군  일반용  2,266    3,412,421

[84 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'전라북도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['고창군',
 '군산시',
 '김제시',
 '남원시',
 '무주군',
 '부안군',
 '순창군',
 '완주군',
 '익산시',
 '임실군',
 '장수군',
 '전주시',
 '정읍시',
 '진안군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
55   202201  전라북도  고창군   합계  62,062   66,384,400
167  202202  전라북도  고창군   합계  62,092   63,954,454
279  202203  전라북도  고창군   합계  65,320   56,835,809
391  202204  전라북도  고창군   합계  81,723   55,602,861
503  202205  전라북도  고창군   합계  62,526   48,044,085
..      ...   ...  ...  ...      ...          ...
271  202202  전라북도  진안군   합계  33,836   22,748,269
383  202203  전라북도  진안군   합계  36,197   19,495,869
495  202204  전라북도  진안군   합계  33,938   17,804,696
607  202205  전라북도  진안군   합계  34,034   14,994,320
719  202206  전라북도  진안군   합계  34,141   14,610,991

[84 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[66384400, 63954454, 56835809, 55602861, 48044085, 49665349]
[533822798, 482482963, 511350947, 484257218, 488363036, 494222983]
[112135743, 109466903, 100365824, 94958234, 84921158, 87525269]
[64596939, 64385019, 58687576, 55535727, 50462238, 52506298]
[27241682, 23948854, 19618559, 17171782, 15020803, 15380050]
[49122619, 47855551, 42864661, 40177015, 36139268, 37815294]
[26025817, 25246868, 23141069, 21953306, 20656242, 21974749]
[169611534, 160161082, 158825225, 143336070, 140024026, 146505086]
[290794128, 279252204, 269251007, 258341121, 242121993, 253977986]
[31712441, 30923338, 28103774, 25504413, 22650860, 23292260]
[27019195, 26535845, 21768738, 19572532, 15351319, 14057038]
[417222478, 403165224, 383140652, 367499314, 345058108, 356935512]
[170650990, 164775142, 159685992, 154429158, 146350457, 153482261]
[22971679, 22748269, 19495869, 17804696, 14994320, 14610991]
전라북도 지역별 합계 :  [340486958, 2994499945, 589373131, 346173797, 118381730, 253974408, 138998051, 918463023, 1593738439, 162187086, 124304667, 2273021288, 949374000, 112625824]
전라북도 고객호수 평균:  [11010, 24027, 15458, 14422, 5186, 9532, 6307, 12535, 29214, 6096, 5010, 47700, 17596, 5720]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\3338217208.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          202201  전라북도  고창군   합계  62,062   66,384,400
1          202202  전라북도  고창군   합계  62,092   63,954,454
2          202203  전라북도  고창군   합계  65,320   56,835,809
3          202204  전라북도  고창군   합계  81,723   55,602,861
4          202205  전라북도  고창군   합계  62,526   48,044,085
..            ...   ...  ...  ...      ...          ...
93  202201-202206  전라북도  임실군   합계     6096    162187086
94  202201-202206  전라북도  장수군   합계     5010    124304667
95  202201-202206  전라북도  전주시   합계    47700   2273021288
96  202201-202206  전라북도  정읍시   합계    17596    949374000
97  202201-202206  전라북도  진안군   합계     5720    112625824

[98 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '202201-202206']
Hap

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  202201-202206  전라북도  고창군   합계   11010   340486958
85  202201-202206  전라북도  군산시   합계   24027  2994499945
86  202201-202206  전라북도  김제시   합계   15458   589373131
87  202201-202206  전라북도  남원시   합계   14422   346173797
88  202201-202206  전라북도  무주군   합계    5186   118381730
89  202201-202206  전라북도  부안군   합계    9532   253974408
90  202201-202206  전라북도  순창군   합계    6307   138998051
91  202201-202206  전라북도  완주군   합계   12535   918463023
92  202201-202206  전라북도  익산시   합계   29214  1593738439
93  202201-202206  전라북도  임실군   합계    6096   162187086
94  202201-202206  전라북도  장수군   합계    5010   124304667
95  202201-202206  전라북도  전주시   합계   47700  2273021288
96  202201-202206  전라북도  정읍시   합계   17596   949374000
97  202201-202206  전라북도  진안군   합계    5720   112625824

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
53   202201  전라북도  고창군  일반용  4,966   11,623,117
165  202202  전라북도  고창군  일반용  4,965   11,588,267
277  202203  전라북도  고창군  일반용  4,963   10,014,409
389  202204  전라북도  고창군  일반용  4,979    9,455,253
501  202205  전라북도  고창군  일반용  5,002    8,346,809
..      ...   ...  ...  ...     ...          ...
269  202202  전라북도  진안군  일반용  2,255    5,340,714
381  202203  전라북도  진안군  일반용  2,257    4,532,343
493  202204  전라북도  진안군  일반용  2,261    3,999,821
605  202205  전라북도  진안군  일반용  2,265    3,403,054
717  202206  전라북도  진안군  일반용  2,266    3,412,421

[84 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[11623117, 11588267, 10014409, 9455253, 8346809, 8848250]
[62214562, 62060179, 53273087, 50235678, 45439760, 50081217]
[17011284, 17109671, 14611450, 13680275, 12032929, 13161471]
[17771691, 17393542, 14658328, 13474765, 11912835, 12788684]
[13497781, 10217621, 7498073, 5906915, 5264966, 5411528]
[14205416, 14187440, 12062609, 11152719, 9858432, 10437518]
[5427015, 5300193, 4352368, 3861305, 3387951, 3620543]
[26479784, 25500423, 22037623, 20182519, 18802620, 21066260]
[52896736, 53006706, 44437513, 41522851, 37141395, 41054894]
[6634274, 6472877, 5441580, 4760686, 4138426, 4475982]
[4453253, 4343574, 3762192, 3257122, 2823183, 2803676]
[135575461, 133697995, 113698515, 106052566, 99474868, 111824733]
[21227256, 21325394, 17735019, 16712820, 14853812, 16123950]
[5387066, 5340714, 4532343, 3999821, 3403054, 3412421]
전라북도 지역별 일반용 합계 :  [59876105, 323304483, 87607080, 87999845, 47796884, 71904134, 25949375, 134069229, 270060095, 31923825, 21443000, 700324138, 107978251, 26075419]
전라북도 고객호수 평균:  [4982, 21619, 7026, 7923, 2858, 5921, 2417, 8147, 21407, 2455, 1877, 49842, 9794, 2259]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_16124\1768384352.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'202201-202206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월    시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          202201  전라북도  고창군  일반용  4,966   11,623,117
1          202202  전라북도  고창군  일반용  4,965   11,588,267
2          202203  전라북도  고창군  일반용  4,963   10,014,409
3          202204  전라북도  고창군  일반용  4,979    9,455,253
4          202205  전라북도  고창군  일반용  5,002    8,346,809
..            ...   ...  ...  ...     ...          ...
93  202201-202206  전라북도  임실군  일반용    2455     31923825
94  202201-202206  전라북도  장수군  일반용    1877     21443000
95  202201-202206  전라북도  전주시  일반용   49842    700324138
96  202201-202206  전라북도  정읍시  일반용    9794    107978251
97  202201-202206  전라북도  진안군  일반용    2259     26075419

[98 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '202201-202206']
GyeonGiHap2

               년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
84  202201-202206  전라북도  고창군  일반용    4982   59876105
85  202201-202206  전라북도  군산시  일반용   21619  323304483
86  202201-202206  전라북도  김제시  일반용    7026   87607080
87  202201-202206  전라북도  남원시  일반용    7923   87999845
88  202201-202206  전라북도  무주군  일반용    2858   47796884
89  202201-202206  전라북도  부안군  일반용    5921   71904134
90  202201-202206  전라북도  순창군  일반용    2417   25949375
91  202201-202206  전라북도  완주군  일반용    8147  134069229
92  202201-202206  전라북도  익산시  일반용   21407  270060095
93  202201-202206  전라북도  임실군  일반용    2455   31923825
94  202201-202206  전라북도  장수군  일반용    1877   21443000
95  202201-202206  전라북도  전주시  일반용   49842  700324138
96  202201-202206  전라북도  정읍시  일반용    9794  107978251
97  202201-202206  전라북도  진안군  일반용    2259   26075419

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
84  202201-202206  전라북도  고창군  일반용    4982    59876105
84  202201-202206  전라북도  고창군   합계   11010   340486958
85  202201-202206  전라북도  군산시  일반용   21619   323304483
85  202201-202206  전라북도  군산시   합계   24027  2994499945
86  202201-202206  전라북도  김제시  일반용    7026    87607080
86  202201-202206  전라북도  김제시   합계   15458   589373131
87  202201-202206  전라북도  남원시  일반용    7923    87999845
87  202201-202206  전라북도  남원시   합계   14422   346173797
88  202201-202206  전라북도  무주군  일반용    2858    47796884
88  202201-202206  전라북도  무주군   합계    5186   118381730
89  202201-202206  전라북도  부안군  일반용    5921    71904134
89  202201-202206  전라북도  부안군   합계    9532   253974408
90  202201-202206  전라북도  순창군  일반용    2417    25949375
90  202201-202206  전라북도  순창군   합계    6307   138998051
91  202201-202206  전라북도  완주군   합계   12535   918463023
91  202201-202206  전라북도  완주군  일반용    8147   134069229
92  202201-202206  전라북도  익산시  일반용   21407   270060095
92  202201-202206  전라북도  익산시   합계   29214  1593738439
93  202201-202206  전라북도  임실군   합계    6096   162187086
93  202201-202206  전라북도  임실군  일반용    2455    31923825
94  202201-202206  전라북도  장수군   합계    5010   124304667
94  202201-202206  전라북도  장수군  일반용    1877    21443000
95  202201-202206  전라북도  전주시   합계   47700  2273021288
95  202201-202206  전라북도  전주시  일반용   49842   700324138
96  202201-202206  전라북도  정읍시   합계   17596   949374000
96  202201-202206  전라북도  정읍시  일반용    9794   107978251
97  202201-202206  전라북도  진안군  일반용    2259    26075419
97  202201-202206  전라북도  진안군   합계    5720   112625824

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[59876105,
 323304483,
 87607080,
 87999845,
 47796884,
 71904134,
 25949375,
 134069229,
 270060095,
 31923825,
 21443000,
 700324138,
 107978251,
 26075419]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[340486958,
 2994499945,
 589373131,
 346173797,
 118381730,
 253974408,
 138998051,
 918463023,
 1593738439,
 162187086,
 124304667,
 2273021288,
 949374000,
 112625824]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[17.59, 10.8, 14.86, 25.42, 40.38, 28.31, 18.67, 14.6, 16.95, 19.68, 17.25, 30.81, 11.37, 23.15]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    18
1    11
2    15
3    25
4    40
5    28
6    19
7    15
8    17
9    20
10   17
11   31
12   11
13   23
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   고창군  일반용  18
1   군산시  일반용  11
2   김제시  일반용  15
3   남원시  일반용  25
4   무주군  일반용  40
5   부안군  일반용  28
6   순창군  일반용  19
7   완주군  일반용  15
8   익산시  일반용  17
9   임실군  일반용  20
10  장수군  일반용  17
11  전주시  일반용  31
12  정읍시  일반용  11
13  진안군  일반용  23

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   202201-202206  전라북도  고창군  일반용    4982    59876105  18
1   202201-202206  전라북도  고창군   합계   11010   340486958 NaN
2   202201-202206  전라북도  군산시  일반용   21619   323304483  11
3   202201-202206  전라북도  군산시   합계   24027  2994499945 NaN
4   202201-202206  전라북도  김제시  일반용    7026    87607080  15
5   202201-202206  전라북도  김제시   합계   15458   589373131 NaN
6   202201-202206  전라북도  남원시  일반용    7923    87999845  25
7   202201-202206  전라북도  남원시   합계   14422   346173797 NaN
8   202201-202206  전라북도  무주군  일반용    2858    47796884  40
9   202201-202206  전라북도  무주군   합계    5186   118381730 NaN
10  202201-202206  전라북도  부안군  일반용    5921    71904134  28
11  202201-202206  전라북도  부안군   합계    9532   253974408 NaN
12  202201-202206  전라북도  순창군  일반용    2417    25949375  19
13  202201-202206  전라북도  순창군   합계    6307   138998051 NaN
15  202201-202206  전라북도  완주군  일반용    8147   134069229  15
14  202201-202206  전라북도  완주군   합계   12535   918463023 NaN
16  202201-202206  전라북도  익산시  일반용   21407   270060095  17
17  202201-202206  전라북도  익산시   합계   29214  1593738439 NaN
19  202201-202206  전라북도  임실군  일반용    2455    31923825  20
18  202201-202206  전라북도  임실군   합계    6096   162187086 NaN
21  202201-202206  전라북도  장수군  일반용    1877    21443000  17
20  202201-202206  전라북도  장수군   합계    5010   124304667 NaN
23  202201-202206  전라북도  전주시  일반용   49842   700324138  31
22  202201-202206  전라북도  전주시   합계   47700  2273021288 NaN
25  202201-202206  전라북도  정읍시  일반용    9794   107978251  11
24  202201-202206  전라북도  정읍시   합계   17596   949374000 NaN
26  202201-202206  전라북도  진안군  일반용    2259    26075419  23
27  202201-202206  전라북도  진안군   합계    5720   112625824 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_2201-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)