In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_12하반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2012년 07 월 ~ 2012년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,경상남도,전체(시 / 군 / 구),주택용,"1,031,233","320,611,159","35,313,117,450",110.1
4,201207,경상남도,전체(시 / 군 / 구),일반용,"195,290","450,134,032","53,297,228,656",118.4
...,...,...,...,...,...,...,...,...
907,201212,경상남도,합천군,산업용,959,"6,992,997","806,887,253",115.4
908,201212,경상남도,합천군,심 야,"2,293","5,666,838","383,634,428",67.7
909,201212,경상남도,합천군,일반용,"3,693","6,416,625","826,169,873",128.8
910,201212,경상남도,합천군,주택용,"26,927","4,768,680","575,344,029",120.7
911,201212,경상남도,합천군,합계,"45,411","32,894,796","3,066,374,974",93.2

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,경상남도,전체(시 / 군 / 구),주택용,"1,031,233","320,611,159","35,313,117,450",110.1
4,201207,경상남도,전체(시 / 군 / 구),일반용,"195,290","450,134,032","53,297,228,656",118.4
5,201207,경상남도,전체(시 / 군 / 구),교육용,"2,749","31,607,955","4,066,165,235",128.6
6,201207,경상남도,전체(시 / 군 / 구),산업용,"33,843","1,672,173,344","179,535,524,180",107.4
...,...,...,...,...,...,...,...,...
907,201212,경상남도,합천군,산업용,959,"6,992,997","806,887,253",115.4
908,201212,경상남도,합천군,심 야,"2,293","5,666,838","383,634,428",67.7
909,201212,경상남도,합천군,일반용,"3,693","6,416,625","826,169,873",128.8
910,201212,경상남도,합천군,주택용,"26,927","4,768,680","575,344,029",120.7
911,201212,경상남도,합천군,합계,"45,411","32,894,796","3,066,374,974",93.2

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,경상남도,전체(시 / 군 / 구),주택용,"1,031,233","320,611,159","35,313,117,450",110.1
4,201207,경상남도,전체(시 / 군 / 구),일반용,"195,290","450,134,032","53,297,228,656",118.4
5,201207,경상남도,전체(시 / 군 / 구),교육용,"2,749","31,607,955","4,066,165,235",128.6
6,201207,경상남도,전체(시 / 군 / 구),산업용,"33,843","1,672,173,344","179,535,524,180",107.4
7,201207,경상남도,전체(시 / 군 / 구),농사용,"145,084","92,489,329","4,159,453,655",45.0
...,...,...,...,...,...,...,...,...
907,201212,경상남도,합천군,산업용,959,"6,992,997","806,887,253",115.4
908,201212,경상남도,합천군,심 야,"2,293","5,666,838","383,634,428",67.7
909,201212,경상남도,합천군,일반용,"3,693","6,416,625","826,169,873",128.8
910,201212,경상남도,합천군,주택용,"26,927","4,768,680","575,344,029",120.7
911,201212,경상남도,합천군,합계,"45,411","32,894,796","3,066,374,974",93.2

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,경상남도,전체(시 / 군 / 구),주택용,"1,031,233","320,611,159","35,313,117,450",110.1
4,201207,경상남도,전체(시 / 군 / 구),일반용,"195,290","450,134,032","53,297,228,656",118.4
5,201207,경상남도,전체(시 / 군 / 구),교육용,"2,749","31,607,955","4,066,165,235",128.6
6,201207,경상남도,전체(시 / 군 / 구),산업용,"33,843","1,672,173,344","179,535,524,180",107.4
7,201207,경상남도,전체(시 / 군 / 구),농사용,"145,084","92,489,329","4,159,453,655",45.0
8,201207,경상남도,전체(시 / 군 / 구),가로등,"125,826","17,409,073","1,844,257,826",105.9
9,201207,경상남도,전체(시 / 군 / 구),심 야,"100,843","39,074,396","1,901,472,181",48.7
10,201208,경상남도,전체(시 / 군 / 구),주택용,"1,034,030","408,699,846","58,858,369,683",144.0
11,201208,경상남도,전체(시 / 군 / 구),일반용,"196,276","553,309,052","72,353,570,957",130.8
12,201208,경상남도,전체(시 / 군 / 구),교육용,"2,750","33,566,569","4,628,715,236",137.9
13,201208,경상남도,전체(시 / 군 / 구),산업용,"33,899","1,570,826,810","185,082,859,597",117.8
14,201208,경상남도,전체(시 / 군 / 구),농사용,"147,494","119,964,743","5,268,045,768",43.9
15,201208,경상남도,전체(시 / 군 / 구),가로등,"126,472","18,528,363","1,937,106,166",104.5
16,201208,경상남도,전체(시 / 군 / 구),심 야,"100,737","30,977,579","1,568,253,006",50.6
17,201209,경상남도,전체(시 / 군 / 구),주택용,"1,036,454","357,309,135","44,322,625,255",124.0
18,201209,경상남도,전체(시 / 군 / 구),일반용,"196,574","485,348,299","58,704,067,432",121.0
19,201209,경상남도,전체(시 / 군 / 구),교육용,"2,738","33,600,311","4,044,015,997",120.4
20,201209,경상남도,전체(시 / 군 / 구),산업용,"33,962","1,575,476,229","157,083,409,886",99.7
21,201209,경상남도,전체(시 / 군 / 구),농사용,"149,144","111,524,403","5,097,544,670",45.7
22,201209,경상남도,전체(시 / 군 / 구),가로등,"126,726","19,257,007","2,017,842,876",104.8
23,201209,경상남도,전체(시 / 군 / 구),심 야,"100,627","32,653,434","1,679,431,951",51.4
24,201210,경상남도,전체(시 / 군 / 구),주택용,"1,039,174","312,295,715","33,886,651,776",108.5
25,201210,경상남도,전체(시 / 군 / 구),일반용,"196,875","389,259,749","44,034,004,061",113.1
26,201210,경상남도,전체(시 / 군 / 구),교육용,"2,736","25,753,766","3,115,482,556",121.0
27,201210,경상남도,전체(시 / 군 / 구),산업용,"34,036","1,493,340,216","144,213,606,238",96.6
28,201210,경상남도,전체(시 / 군 / 구),농사용,"149,919","91,450,519","4,442,556,349",48.6
29,201210,경상남도,전체(시 / 군 / 구),가로등,"127,147","20,687,572","2,056,262,756",99.4
30,201210,경상남도,전체(시 / 군 / 구),심 야,"100,596","54,981,116","2,753,844,267",50.1
31,201211,경상남도,전체(시 / 군 / 구),주택용,"1,042,156","336,265,859","39,332,164,600",117.0
32,201211,경상남도,전체(시 / 군 / 구),일반용,"197,571","419,220,504","49,754,474,215",118.7
33,201211,경상남도,전체(시 / 군 / 구),교육용,"2,731","32,658,597","4,026,295,252",123.3
34,201211,경상남도,전체(시 / 군 / 구),산업용,"34,080","1,609,506,362","183,060,835,058",113.7
35,201211,경상남도,전체(시 / 군 / 구),농사용,"175,442","126,034,754","5,681,518,562",45.1
36,201211,경상남도,전체(시 / 군 / 구),가로등,"127,697","22,230,929","2,145,590,933",96.5
37,201211,경상남도,전체(시 / 군 / 구),심 야,"100,622","112,690,596","6,530,995,973",58.0
38,201212,경상남도,전체(시 / 군 / 구),주택용,"1,044,755","354,869,649","44,017,211,471",124.0
39,201212,경상남도,전체(시 / 군 / 구),일반용,"198,687","495,666,103","62,845,787,416",126.8
40,201212,경상남도,전체(시 / 군 / 구),교육용,"2,730","45,132,480","5,255,779,912",116.5
41,201212,경상남도,전체(시 / 군 / 구),산업용,"34,142","1,661,399,958","188,404,959,610",113.4
42,201212,경상남도,전체(시 / 군 / 구),농사용,"151,372","195,202,641","8,584,638,439",44.0
43,201212,경상남도,전체(시 / 군 / 구),가로등,"128,335","22,904,161","2,154,129,670",94.0
44,201212,경상남도,전체(시 / 군 / 구),심 야,"100,631","180,454,914","12,290,737,441",68.1
45,합계,합계,합계,합계,"9,914,185","15,976,547,228","1,731,350,604,218",108.4

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_13576\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201207  경상남도  일반용  195,290   450,134,032
11  201208  경상남도  일반용  196,276   553,309,052
18  201209  경상남도  일반용  196,574   485,348,299
25  201210  경상남도  일반용  196,875   389,259,749
32  201211  경상남도  일반용  197,571   419,220,504
39  201212  경상남도  일반용  198,687   495,666,103

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201207  경상남도  거제시  일반용  14,899   32,513,783
197  201208  경상남도  거제시  일반용  14,950   41,251,207
341  201209  경상남도  거제시  일반용  14,968   36,498,980
485  201210  경상남도  거제시  일반용  15,019   29,126,853
629  201211  경상남도  거제시  일반용  15,098   30,647,873
..      ...   ...  ...  ...      ...          ...
333  201208  경상남도  합천군  일반용   3,626    6,185,046
477  201209  경상남도  합천군  일반용   3,625    5,558,800
621  201210  경상남도  합천군  일반용   3,634    4,815,663
765  201211  경상남도  합천군  일반용   3,658    5,479,589
909  201212  경상남도  합천군  일반용   3,693    6,416,625

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201207  경상남도  거제시   합계  100,275   172,237,662
199  201208  경상남도  거제시   합계  100,864   183,070,874
343  201209  경상남도  거제시   합계  101,222   170,274,584
487  201210  경상남도  거제시   합계  101,802   152,423,928
631  201211  경상남도  거제시   합계  103,726   165,945,029
..      ...   ...  ...  ...       ...           ...
335  201208  경상남도  합천군   합계   45,121    26,880,348
479  201209  경상남도  합천군   합계   45,308    25,817,955
623  201210  경상남도  합천군   합계   45,280    23,861,632
767  201211  경상남도  합천군   합계   47,516    29,065,430
911  201212  경상남도  합천군   합계   45,411    32,894,796

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[172237662, 183070874, 170274584, 152423928, 165945029, 183776274]
[28813788, 32096848, 31944712, 29040460, 33741377, 37134159]
[42132427, 46505625, 44413703, 42275274, 47210629, 55521009]
[390238727, 410334392, 400080104, 356819064, 408602450, 444851072]
[18014766, 22768031, 19928637, 17954548, 21524401, 22959730]
[63886849, 70501477, 66369982, 61359726, 73258957, 98098140]
[97961172, 104328940, 96470884, 90239992, 98409656, 105427651]
[16029596, 19444525, 18530935, 16543273, 21843910, 24604314]
[272622047, 275964757, 265334628, 248412474, 269578084, 288066795]
[29730468, 31927099, 30810481, 29482793, 32453428, 35869181]
[172710858, 191410780, 175914112, 138624082, 164913392, 205293950]
[46799529, 52453192, 49579776, 43817358, 53462325, 69183306]
[915046859, 943754572, 891065564, 824015985, 891998060, 967805491]
[100241552, 106977830, 95998055, 88160164, 96470531, 111888237]
[19114651, 23511370, 22276903, 21864644, 24908349, 29554805]
[197936420, 174213053, 190500219, 185583112, 204149317, 219556114]
[16622706, 19729249, 19857584, 17290144, 21072276, 23144882]
[23359211, 26880348, 25817955, 23861632, 29065430, 32894796]
경상남도 지역별 합계 :  [1027728351, 192771344, 278058667, 2410925809, 123150113, 433475131, 592838295, 116996553, 1619978785, 190273450, 1048867174, 315295486, 5433686531, 599736369, 141230722, 1171938235, 117716841, 161879372]
경상남도 고객호수 평균:  [16963, 8337, 7877, 28812, 7693, 14693, 11338, 6098, 15115, 5067, 28831, 9148, 73288, 12540, 7862, 7910, 6219, 7593]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201207  경상남도  거제시   합계  100,275   172,237,662
1           201208  경상남도  거제시   합계  100,864   183,070,874
2           201209  경상남도  거제시   합계  101,222   170,274,584
3           201210  경상남도  거제시   합계  101,802   152,423,928
4           201211  경상남도  거제시   합계  103,726   165,945,029
..             ...   ...  ...  ...       ...           ...
121  201207-201212  경상남도  통영시   합계     12540     599736369
122  201207-201212  경상남도  하동군   합계      7862     141230722
123  201207-201212  경상남도  함안군   합계      7910    1171938235
124  201207-201212  경상남도  함양군   합계      6219     117716841
125  201207-201212  경상남도  합천군   합계      7593     161879372

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201207-201212']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201207-201212  경상남도  거제시   합계   16963  1027728351
109  201207-201212  경상남도  거창군   합계    8337   192771344
110  201207-201212  경상남도  고성군   합계    7877   278058667
111  201207-201212  경상남도  김해시   합계   28812  2410925809
112  201207-201212  경상남도  남해군   합계    7693   123150113
113  201207-201212  경상남도  밀양시   합계   14693   433475131
114  201207-201212  경상남도  사천시   합계   11338   592838295
115  201207-201212  경상남도  산청군   합계    6098   116996553
116  201207-201212  경상남도  양산시   합계   15115  1619978785
117  201207-201212  경상남도  의령군   합계    5067   190273450
118  201207-201212  경상남도  진주시   합계   28831  1048867174
119  201207-201212  경상남도  창녕군   합계    9148   315295486
120  201207-201212  경상남도  창원시   합계   73288  5433686531
121  201207-201212  경상남도  통영시   합계   12540   599736369
122  201207-201212  경상남도  하동군   합계    7862   141230722
123  201207-201212  경상남도  함안군   합계    7910  1171938235
124  201207-201212  경상남도  함양군   합계    6219   117716841
125  201207-201212  경상남도  합천군   합계    7593   161879372

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201207  경상남도  거제시  일반용  14,899   32,513,783
197  201208  경상남도  거제시  일반용  14,950   41,251,207
341  201209  경상남도  거제시  일반용  14,968   36,498,980
485  201210  경상남도  거제시  일반용  15,019   29,126,853
629  201211  경상남도  거제시  일반용  15,098   30,647,873
..      ...   ...  ...  ...      ...          ...
333  201208  경상남도  합천군  일반용   3,626    6,185,046
477  201209  경상남도  합천군  일반용   3,625    5,558,800
621  201210  경상남도  합천군  일반용   3,634    4,815,663
765  201211  경상남도  합천군  일반용   3,658    5,479,589
909  201212  경상남도  합천군  일반용   3,693    6,416,625

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[32513783, 41251207, 36498980, 29126853, 30647873, 36127602]
[6962648, 8507989, 7446649, 6468987, 7620007, 9017185]
[6890353, 8656141, 7650386, 6267432, 7005898, 8176148]
[65700187, 81768633, 72634771, 56764780, 60378393, 72026286]
[6409502, 9007281, 7292359, 5858680, 6529993, 7576641]
[12578833, 15947967, 13861417, 11078210, 12222822, 14272092]
[16307586, 20288425, 17767355, 14495208, 15697919, 18256172]
[3959064, 5120070, 4502638, 3731202, 4220330, 4872436]
[38730472, 46959084, 40927240, 33608996, 35647100, 42315062]
[2781720, 3511530, 3103914, 2589111, 2954840, 3527570]
[47991736, 57862260, 50834345, 41582087, 43833255, 52158420]
[9118357, 11213662, 9570978, 8292617, 8797818, 10786017]
[155856452, 187636889, 163964420, 129420541, 139284392, 165150812]
[21190556, 26983687, 24195647, 18939227, 20486751, 23539511]
[5416652, 6890091, 6056745, 5035586, 5711615, 6636904]
[8348726, 10165644, 8747014, 7192571, 8153193, 9539079]
[4324410, 5353446, 4734641, 3991998, 4548716, 5271541]
[5052995, 6185046, 5558800, 4815663, 5479589, 6416625]
경상남도 지역별 일반용 합계 :  [206166298, 46023465, 44646358, 409273050, 42674456, 79961341, 102812665, 26405740, 238187954, 18468685, 294262103, 57779449, 941313506, 135335379, 35747593, 52146227, 28224752, 33508718]
경상남도 고객호수 평균:  [15021, 4581, 4223, 25827, 4342, 8259, 8548, 3126, 14571, 2168, 22490, 5066, 53260, 9819, 3933, 4702, 3295, 3641]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_13576\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201207  경상남도  거제시  일반용  14,899   32,513,783
1           201208  경상남도  거제시  일반용  14,950   41,251,207
2           201209  경상남도  거제시  일반용  14,968   36,498,980
3           201210  경상남도  거제시  일반용  15,019   29,126,853
4           201211  경상남도  거제시  일반용  15,098   30,647,873
..             ...   ...  ...  ...      ...          ...
121  201207-201212  경상남도  통영시  일반용     9819    135335379
122  201207-201212  경상남도  하동군  일반용     3933     35747593
123  201207-201212  경상남도  함안군  일반용     4702     52146227
124  201207-201212  경상남도  함양군  일반용     3295     28224752
125  201207-201212  경상남도  합천군  일반용     3641     33508718

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201207-201212']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201207-201212  경상남도  거제시  일반용   15021  206166298
109  201207-201212  경상남도  거창군  일반용    4581   46023465
110  201207-201212  경상남도  고성군  일반용    4223   44646358
111  201207-201212  경상남도  김해시  일반용   25827  409273050
112  201207-201212  경상남도  남해군  일반용    4342   42674456
113  201207-201212  경상남도  밀양시  일반용    8259   79961341
114  201207-201212  경상남도  사천시  일반용    8548  102812665
115  201207-201212  경상남도  산청군  일반용    3126   26405740
116  201207-201212  경상남도  양산시  일반용   14571  238187954
117  201207-201212  경상남도  의령군  일반용    2168   18468685
118  201207-201212  경상남도  진주시  일반용   22490  294262103
119  201207-201212  경상남도  창녕군  일반용    5066   57779449
120  201207-201212  경상남도  창원시  일반용   53260  941313506
121  201207-201212  경상남도  통영시  일반용    9819  135335379
122  201207-201212  경상남도  하동군  일반용    3933   35747593
123  201207-201212  경상남도  함안군  일반용    4702   52146227
124  201207-201212  경상남도  함양군  일반용    3295   28224752
125  201207-201212  경상남도  합천군  일반용    3641   33508718

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201207-201212  경상남도  거제시  일반용   15021   206166298
108  201207-201212  경상남도  거제시   합계   16963  1027728351
109  201207-201212  경상남도  거창군  일반용    4581    46023465
109  201207-201212  경상남도  거창군   합계    8337   192771344
110  201207-201212  경상남도  고성군  일반용    4223    44646358
110  201207-201212  경상남도  고성군   합계    7877   278058667
111  201207-201212  경상남도  김해시   합계   28812  2410925809
111  201207-201212  경상남도  김해시  일반용   25827   409273050
112  201207-201212  경상남도  남해군   합계    7693   123150113
112  201207-201212  경상남도  남해군  일반용    4342    42674456
113  201207-201212  경상남도  밀양시  일반용    8259    79961341
113  201207-201212  경상남도  밀양시   합계   14693   433475131
114  201207-201212  경상남도  사천시   합계   11338   592838295
114  201207-201212  경상남도  사천시  일반용    8548   102812665
115  201207-201212  경상남도  산청군  일반용    3126    26405740
115  201207-201212  경상남도  산청군   합계    6098   116996553
116  201207-201212  경상남도  양산시  일반용   14571   238187954
116  201207-201212  경상남도  양산시   합계   15115  1619978785
117  201207-201212  경상남도  의령군  일반용    2168    18468685
117  201207-201212  경상남도  의령군   합계    5067   190273450
118  201207-201212  경상남도  진주시   합계   28831  1048867174
118  201207-201212  경상남도  진주시  일반용   22490   294262103
119  201207-201212  경상남도  창녕군   합계    9148   315295486
119  201207-201212  경상남도  창녕군  일반용    5066    57779449
120  201207-201212  경상남도  창원시  일반용   53260   941313506
120  201207-201212  경상남도  창원시   합계   73288  5433686531
121  201207-201212  경상남도  통영시   합계   12540   599736369
121  201207-201212  경상남도  통영시  일반용    9819   135335379
122  201207-201212  경상남도  하동군   합계    7862   141230722
122  201207-201212  경상남도  하동군  일반용    3933    35747593
123  201207-201212  경상남도  함안군   합계    7910  1171938235
123  201207-201212  경상남도  함안군  일반용    4702    52146227
124  201207-201212  경상남도  함양군   합계    6219   117716841
124  201207-201212  경상남도  함양군  일반용    3295    28224752
125  201207-201212  경상남도  합천군  일반용    3641    33508718
125  201207-201212  경상남도  합천군   합계    7593   161879372

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[206166298,
 46023465,
 44646358,
 409273050,
 42674456,
 79961341,
 102812665,
 26405740,
 238187954,
 18468685,
 294262103,
 57779449,
 941313506,
 135335379,
 35747593,
 52146227,
 28224752,
 33508718]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1027728351,
 192771344,
 278058667,
 2410925809,
 123150113,
 433475131,
 592838295,
 116996553,
 1619978785,
 190273450,
 1048867174,
 315295486,
 5433686531,
 599736369,
 141230722,
 1171938235,
 117716841,
 161879372]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[20.06, 23.87, 16.06, 16.98, 34.65, 18.45, 17.34, 22.57, 14.7, 9.71, 28.06, 18.33, 17.32, 22.57, 25.31, 4.45, 23.98, 20.7]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    20
1    24
2    16
3    17
4    35
5    18
6    17
7    23
8    15
9    10
10   28
11   18
12   17
13   23
14   25
15    4
16   24
17   21
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  20
1   거창군  일반용  24
2   고성군  일반용  16
3   김해시  일반용  17
4   남해군  일반용  35
5   밀양시  일반용  18
6   사천시  일반용  17
7   산청군  일반용  23
8   양산시  일반용  15
9   의령군  일반용  10
10  진주시  일반용  28
11  창녕군  일반용  18
12  창원시  일반용  17
13  통영시  일반용  23
14  하동군  일반용  25
15  함안군  일반용   4
16  함양군  일반용  24
17  합천군  일반용  21

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201207-201212  경상남도  거제시  일반용   15021   206166298  20
1   201207-201212  경상남도  거제시   합계   16963  1027728351 NaN
2   201207-201212  경상남도  거창군  일반용    4581    46023465  24
3   201207-201212  경상남도  거창군   합계    8337   192771344 NaN
4   201207-201212  경상남도  고성군  일반용    4223    44646358  16
5   201207-201212  경상남도  고성군   합계    7877   278058667 NaN
7   201207-201212  경상남도  김해시  일반용   25827   409273050  17
6   201207-201212  경상남도  김해시   합계   28812  2410925809 NaN
9   201207-201212  경상남도  남해군  일반용    4342    42674456  35
8   201207-201212  경상남도  남해군   합계    7693   123150113 NaN
10  201207-201212  경상남도  밀양시  일반용    8259    79961341  18
11  201207-201212  경상남도  밀양시   합계   14693   433475131 NaN
13  201207-201212  경상남도  사천시  일반용    8548   102812665  17
12  201207-201212  경상남도  사천시   합계   11338   592838295 NaN
14  201207-201212  경상남도  산청군  일반용    3126    26405740  23
15  201207-201212  경상남도  산청군   합계    6098   116996553 NaN
16  201207-201212  경상남도  양산시  일반용   14571   238187954  15
17  201207-201212  경상남도  양산시   합계   15115  1619978785 NaN
18  201207-201212  경상남도  의령군  일반용    2168    18468685  10
19  201207-201212  경상남도  의령군   합계    5067   190273450 NaN
21  201207-201212  경상남도  진주시  일반용   22490   294262103  28
20  201207-201212  경상남도  진주시   합계   28831  1048867174 NaN
23  201207-201212  경상남도  창녕군  일반용    5066    57779449  18
22  201207-201212  경상남도  창녕군   합계    9148   315295486 NaN
24  201207-201212  경상남도  창원시  일반용   53260   941313506  17
25  201207-201212  경상남도  창원시   합계   73288  5433686531 NaN
27  201207-201212  경상남도  통영시  일반용    9819   135335379  23
26  201207-201212  경상남도  통영시   합계   12540   599736369 NaN
29  201207-201212  경상남도  하동군  일반용    3933    35747593  25
28  201207-201212  경상남도  하동군   합계    7862   141230722 NaN
31  201207-201212  경상남도  함안군  일반용    4702    52146227   4
30  201207-201212  경상남도  함안군   합계    7910  1171938235 NaN
33  201207-201212  경상남도  함양군  일반용    3295    28224752  24
32  201207-201212  경상남도  함양군   합계    6219   117716841 NaN
34  201207-201212  경상남도  합천군  일반용    3641    33508718  21
35  201207-201212  경상남도  합천군   합계    7593   161879372 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1207-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)