In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_17상반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2017년 01 월 ~ 2017년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201701,경상남도,전체(시 / 군 / 구),주택용,"1,136,752","387,629,910","43,537,738,939",112.3
4,201701,경상남도,전체(시 / 군 / 구),일반용,"218,305","587,956,161","79,698,375,045",135.6
...,...,...,...,...,...,...,...,...
907,201706,경상남도,합천군,산업용,"1,013","6,014,079","751,190,482",124.9
908,201706,경상남도,합천군,심 야,"2,176","1,400,882","75,752,316",54.1
909,201706,경상남도,합천군,일반용,"3,800","5,530,944","759,896,970",137.4
910,201706,경상남도,합천군,주택용,"28,583","4,160,068","433,143,764",104.1
911,201706,경상남도,합천군,합계,"52,416","27,960,097","2,588,991,708",92.6

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201701,경상남도,전체(시 / 군 / 구),주택용,"1,136,752","387,629,910","43,537,738,939",112.3
4,201701,경상남도,전체(시 / 군 / 구),일반용,"218,305","587,956,161","79,698,375,045",135.6
5,201701,경상남도,전체(시 / 군 / 구),교육용,"1,642","39,088,283","4,101,335,290",104.9
6,201701,경상남도,전체(시 / 군 / 구),산업용,"37,118","1,680,202,309","210,161,660,867",125.1
...,...,...,...,...,...,...,...,...
907,201706,경상남도,합천군,산업용,"1,013","6,014,079","751,190,482",124.9
908,201706,경상남도,합천군,심 야,"2,176","1,400,882","75,752,316",54.1
909,201706,경상남도,합천군,일반용,"3,800","5,530,944","759,896,970",137.4
910,201706,경상남도,합천군,주택용,"28,583","4,160,068","433,143,764",104.1
911,201706,경상남도,합천군,합계,"52,416","27,960,097","2,588,991,708",92.6

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201701,경상남도,전체(시 / 군 / 구),주택용,"1,136,752","387,629,910","43,537,738,939",112.3
4,201701,경상남도,전체(시 / 군 / 구),일반용,"218,305","587,956,161","79,698,375,045",135.6
5,201701,경상남도,전체(시 / 군 / 구),교육용,"1,642","39,088,283","4,101,335,290",104.9
6,201701,경상남도,전체(시 / 군 / 구),산업용,"37,118","1,680,202,309","210,161,660,867",125.1
7,201701,경상남도,전체(시 / 군 / 구),농사용,"188,200","316,283,837","14,891,331,902",47.1
...,...,...,...,...,...,...,...,...
907,201706,경상남도,합천군,산업용,"1,013","6,014,079","751,190,482",124.9
908,201706,경상남도,합천군,심 야,"2,176","1,400,882","75,752,316",54.1
909,201706,경상남도,합천군,일반용,"3,800","5,530,944","759,896,970",137.4
910,201706,경상남도,합천군,주택용,"28,583","4,160,068","433,143,764",104.1
911,201706,경상남도,합천군,합계,"52,416","27,960,097","2,588,991,708",92.6

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201701,경상남도,전체(시 / 군 / 구),주택용,"1,136,752","387,629,910","43,537,738,939",112.3
4,201701,경상남도,전체(시 / 군 / 구),일반용,"218,305","587,956,161","79,698,375,045",135.6
5,201701,경상남도,전체(시 / 군 / 구),교육용,"1,642","39,088,283","4,101,335,290",104.9
6,201701,경상남도,전체(시 / 군 / 구),산업용,"37,118","1,680,202,309","210,161,660,867",125.1
7,201701,경상남도,전체(시 / 군 / 구),농사용,"188,200","316,283,837","14,891,331,902",47.1
8,201701,경상남도,전체(시 / 군 / 구),가로등,"156,811","26,211,435","2,789,009,808",106.4
9,201701,경상남도,전체(시 / 군 / 구),심 야,"93,164","155,563,104","11,723,239,982",75.4
10,201702,경상남도,전체(시 / 군 / 구),주택용,"1,138,472","391,670,504","44,455,075,186",113.5
11,201702,경상남도,전체(시 / 군 / 구),일반용,"218,138","595,800,766","80,336,752,202",134.8
12,201702,경상남도,전체(시 / 군 / 구),교육용,"1,655","38,331,785","4,163,625,245",108.6
13,201702,경상남도,전체(시 / 군 / 구),산업용,"37,171","1,668,956,379","209,619,362,966",125.6
14,201702,경상남도,전체(시 / 군 / 구),농사용,"188,475","328,406,346","15,399,258,417",46.9
15,201702,경상남도,전체(시 / 군 / 구),가로등,"157,226","25,048,061","2,779,448,437",111.0
16,201702,경상남도,전체(시 / 군 / 구),심 야,"92,950","168,678,237","12,714,500,548",75.4
17,201703,경상남도,전체(시 / 군 / 구),주택용,"1,140,856","340,261,198","34,575,646,731",101.6
18,201703,경상남도,전체(시 / 군 / 구),일반용,"217,832","507,894,717","64,770,638,040",127.5
19,201703,경상남도,전체(시 / 군 / 구),교육용,"1,665","37,653,555","3,839,631,193",102.0
20,201703,경상남도,전체(시 / 군 / 구),산업용,"37,179","1,707,952,571","178,261,349,736",104.4
21,201703,경상남도,전체(시 / 군 / 구),농사용,"212,979","247,115,378","11,908,030,457",48.2
22,201703,경상남도,전체(시 / 군 / 구),가로등,"157,508","23,512,974","2,640,577,804",112.3
23,201703,경상남도,전체(시 / 군 / 구),심 야,"92,707","127,628,496","8,459,407,849",66.3
24,201704,경상남도,전체(시 / 군 / 구),주택용,"1,143,408","360,004,097","38,075,832,778",105.8
25,201704,경상남도,전체(시 / 군 / 구),일반용,"217,678","497,089,384","57,511,228,542",115.7
26,201704,경상남도,전체(시 / 군 / 구),교육용,"1,658","35,370,619","3,293,568,292",93.1
27,201704,경상남도,전체(시 / 군 / 구),산업용,"37,244","1,663,865,786","168,591,824,455",101.3
28,201704,경상남도,전체(시 / 군 / 구),농사용,"190,353","194,307,136","9,661,938,747",49.7
29,201704,경상남도,전체(시 / 군 / 구),가로등,"157,987","23,030,099","2,681,133,301",116.4
30,201704,경상남도,전체(시 / 군 / 구),심 야,"92,468","105,413,929","5,739,632,311",54.4
31,201705,경상남도,전체(시 / 군 / 구),주택용,"1,144,913","330,370,196","33,251,957,977",100.7
32,201705,경상남도,전체(시 / 군 / 구),일반용,"217,520","450,766,822","54,266,541,020",120.4
33,201705,경상남도,전체(시 / 군 / 구),교육용,"1,655","25,782,706","2,495,617,684",96.8
34,201705,경상남도,전체(시 / 군 / 구),산업용,"37,270","1,580,253,663","162,017,652,776",102.5
35,201705,경상남도,전체(시 / 군 / 구),농사용,"190,872","121,101,466","6,515,272,767",53.8
36,201705,경상남도,전체(시 / 군 / 구),가로등,"158,243","21,640,047","2,603,273,852",120.3
37,201705,경상남도,전체(시 / 군 / 구),심 야,"92,155","57,291,609","3,134,714,269",54.7
38,201706,경상남도,전체(시 / 군 / 구),주택용,"1,147,201","332,570,874","33,743,945,190",101.5
39,201706,경상남도,전체(시 / 군 / 구),일반용,"217,779","488,219,583","66,033,231,953",135.3
40,201706,경상남도,전체(시 / 군 / 구),교육용,"1,652","30,520,414","3,612,430,087",118.4
41,201706,경상남도,전체(시 / 군 / 구),산업용,"37,349","1,655,013,705","205,105,975,054",123.9
42,201706,경상남도,전체(시 / 군 / 구),농사용,"190,926","120,949,728","6,090,234,966",50.4
43,201706,경상남도,전체(시 / 군 / 구),가로등,"158,671","21,277,976","2,608,045,110",122.6
44,201706,경상남도,전체(시 / 군 / 구),심 야,"91,932","35,063,186","1,941,759,838",55.4
45,합계,합계,합계,합계,"11,055,739","17,551,749,031","1,909,801,807,613",108.8

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_12716\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201701  경상남도  일반용  218,305   587,956,161
11  201702  경상남도  일반용  218,138   595,800,766
18  201703  경상남도  일반용  217,832   507,894,717
25  201704  경상남도  일반용  217,678   497,089,384
32  201705  경상남도  일반용  217,520   450,766,822
39  201706  경상남도  일반용  217,779   488,219,583

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201701  경상남도  거제시  일반용  17,789   46,473,708
197  201702  경상남도  거제시  일반용  17,781   47,300,559
341  201703  경상남도  거제시  일반용  17,798   40,375,699
485  201704  경상남도  거제시  일반용  17,734   39,741,147
629  201705  경상남도  거제시  일반용  17,661   35,981,418
..      ...   ...  ...  ...      ...          ...
333  201702  경상남도  합천군  일반용   3,844    7,996,151
477  201703  경상남도  합천군  일반용   3,821    6,532,816
621  201704  경상남도  합천군  일반용   3,803    6,318,385
765  201705  경상남도  합천군  일반용   3,808    5,390,652
909  201706  경상남도  합천군  일반용   3,800    5,530,944

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201701  경상남도  거제시   합계  123,093   206,708,965
199  201702  경상남도  거제시   합계  123,282   205,243,477
343  201703  경상남도  거제시   합계  124,764   192,215,468
487  201704  경상남도  거제시   합계  123,560   185,575,317
631  201705  경상남도  거제시   합계  123,634   163,609,341
..      ...   ...  ...  ...       ...           ...
335  201702  경상남도  합천군   합계   51,788    41,339,627
479  201703  경상남도  합천군   합계   53,978    34,246,701
623  201704  경상남도  합천군   합계   52,024    32,093,731
767  201705  경상남도  합천군   합계   52,199    26,470,507
911  201706  경상남도  합천군   합계   52,416    27,960,097

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[206708965, 205243477, 192215468, 185575317, 163609341, 174193066]
[42412181, 43240847, 37412985, 36179909, 31550385, 32483110]
[56434740, 58365350, 51277514, 49158518, 42475970, 41854869]
[479489901, 482180217, 442551949, 439065278, 392236617, 418082104]
[24872280, 25458578, 21214537, 21425254, 18959277, 19722510]
[132637471, 136343263, 116363969, 104089216, 80747192, 79205039]
[116758893, 117828216, 111074686, 107345391, 97793540, 102573371]
[33034241, 33277976, 27965914, 26004370, 22160821, 22696881]
[313503843, 310382058, 302554488, 297712349, 281298882, 299441612]
[40282230, 40373162, 35551568, 33461983, 29618265, 29912192]
[271217351, 272835839, 238637651, 222283767, 183633778, 184646302]
[98517902, 99048209, 87552691, 80545017, 67697125, 71577403]
[955244297, 956279930, 922515320, 887605415, 824474818, 850982700]
[100969190, 98442842, 86251604, 81932556, 73530632, 71030818]
[32868384, 34361939, 28948599, 30163969, 24175074, 24608901]
[223702640, 236865982, 234389249, 223296903, 208767919, 214134793]
[24753737, 25024566, 21293996, 21142107, 18006366, 18509698]
[39526793, 41339627, 34246701, 32093731, 26470507, 27960097]
경상남도 지역별 합계 :  [1127545634, 223279417, 299566961, 2653606066, 131652436, 649386150, 653374097, 165140203, 1804893232, 209199400, 1373254688, 504938347, 5397102480, 512157642, 175126866, 1341157486, 128730470, 201637456]
경상남도 고객호수 평균:  [20618, 9371, 8839, 33211, 8260, 16617, 12595, 7042, 19513, 5749, 31816, 10218, 76045, 13561, 9000, 8968, 6947, 8726]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\1605161548.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201701  경상남도  거제시   합계  123,093   206,708,965
1           201702  경상남도  거제시   합계  123,282   205,243,477
2           201703  경상남도  거제시   합계  124,764   192,215,468
3           201704  경상남도  거제시   합계  123,560   185,575,317
4           201705  경상남도  거제시   합계  123,634   163,609,341
..             ...   ...  ...  ...       ...           ...
121  201701-201706  경상남도  통영시   합계     13561     512157642
122  201701-201706  경상남도  하동군   합계      9000     175126866
123  201701-201706  경상남도  함안군   합계      8968    1341157486
124  201701-201706  경상남도  함양군   합계      6947     128730470
125  201701-201706  경상남도  합천군   합계      8726     201637456

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201701-201706']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201701-201706  경상남도  거제시   합계   20618  1127545634
109  201701-201706  경상남도  거창군   합계    9371   223279417
110  201701-201706  경상남도  고성군   합계    8839   299566961
111  201701-201706  경상남도  김해시   합계   33211  2653606066
112  201701-201706  경상남도  남해군   합계    8260   131652436
113  201701-201706  경상남도  밀양시   합계   16617   649386150
114  201701-201706  경상남도  사천시   합계   12595   653374097
115  201701-201706  경상남도  산청군   합계    7042   165140203
116  201701-201706  경상남도  양산시   합계   19513  1804893232
117  201701-201706  경상남도  의령군   합계    5749   209199400
118  201701-201706  경상남도  진주시   합계   31816  1373254688
119  201701-201706  경상남도  창녕군   합계   10218   504938347
120  201701-201706  경상남도  창원시   합계   76045  5397102480
121  201701-201706  경상남도  통영시   합계   13561   512157642
122  201701-201706  경상남도  하동군   합계    9000   175126866
123  201701-201706  경상남도  함안군   합계    8968  1341157486
124  201701-201706  경상남도  함양군   합계    6947   128730470
125  201701-201706  경상남도  합천군   합계    8726   201637456

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201701  경상남도  거제시  일반용  17,789   46,473,708
197  201702  경상남도  거제시  일반용  17,781   47,300,559
341  201703  경상남도  거제시  일반용  17,798   40,375,699
485  201704  경상남도  거제시  일반용  17,734   39,741,147
629  201705  경상남도  거제시  일반용  17,661   35,981,418
..      ...   ...  ...  ...      ...          ...
333  201702  경상남도  합천군  일반용   3,844    7,996,151
477  201703  경상남도  합천군  일반용   3,821    6,532,816
621  201704  경상남도  합천군  일반용   3,803    6,318,385
765  201705  경상남도  합천군  일반용   3,808    5,390,652
909  201706  경상남도  합천군  일반용   3,800    5,530,944

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[46473708, 47300559, 40375699, 39741147, 35981418, 37963019]
[10250021, 10568404, 8649732, 8324162, 6967487, 7245743]
[9791925, 10096250, 8502364, 8298545, 7149786, 7243779]
[87589003, 88072507, 74717915, 73997673, 68969874, 76293674]
[9218320, 9449143, 7889358, 7868436, 7135392, 7024937]
[18406842, 18663028, 15846637, 15553337, 13493083, 14661239]
[21967819, 22443338, 18791485, 18508922, 16184477, 17302387]
[6331777, 6457535, 5444631, 5380645, 4658085, 4697937]
[52860650, 53290532, 45783754, 45063365, 41612272, 45437911]
[4468345, 4568472, 3842858, 3791454, 3174167, 3283233]
[62795019, 63392369, 54734877, 53078296, 47665660, 52185277]
[12638513, 12739534, 10909654, 10549561, 9354564, 9632530]
[183824618, 184677948, 158808785, 154510756, 142552209, 157450186]
[28150742, 29965389, 25062072, 24366923, 21774129, 22391117]
[7894371, 8166244, 6990757, 6937969, 5649319, 5811662]
[11721131, 11834713, 9851447, 9705921, 8708542, 9557343]
[5883582, 6118650, 5159876, 5093887, 4345706, 4506665]
[7689775, 7996151, 6532816, 6318385, 5390652, 5530944]
경상남도 지역별 일반용 합계 :  [247835550, 52005549, 51082649, 469640646, 48585586, 96624166, 115198428, 32970610, 284048484, 23128529, 333851498, 65824356, 981824502, 151710372, 41450322, 61379097, 31108366, 39458723]
경상남도 고객호수 평균:  [17746, 4910, 4542, 29415, 4651, 9029, 9304, 3368, 17868, 2353, 25017, 5423, 56412, 11054, 4145, 5250, 3556, 3823]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12716\3530786540.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201701-201706'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201701  경상남도  거제시  일반용  17,789   46,473,708
1           201702  경상남도  거제시  일반용  17,781   47,300,559
2           201703  경상남도  거제시  일반용  17,798   40,375,699
3           201704  경상남도  거제시  일반용  17,734   39,741,147
4           201705  경상남도  거제시  일반용  17,661   35,981,418
..             ...   ...  ...  ...      ...          ...
121  201701-201706  경상남도  통영시  일반용    11054    151710372
122  201701-201706  경상남도  하동군  일반용     4145     41450322
123  201701-201706  경상남도  함안군  일반용     5250     61379097
124  201701-201706  경상남도  함양군  일반용     3556     31108366
125  201701-201706  경상남도  합천군  일반용     3823     39458723

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201701-201706']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201701-201706  경상남도  거제시  일반용   17746  247835550
109  201701-201706  경상남도  거창군  일반용    4910   52005549
110  201701-201706  경상남도  고성군  일반용    4542   51082649
111  201701-201706  경상남도  김해시  일반용   29415  469640646
112  201701-201706  경상남도  남해군  일반용    4651   48585586
113  201701-201706  경상남도  밀양시  일반용    9029   96624166
114  201701-201706  경상남도  사천시  일반용    9304  115198428
115  201701-201706  경상남도  산청군  일반용    3368   32970610
116  201701-201706  경상남도  양산시  일반용   17868  284048484
117  201701-201706  경상남도  의령군  일반용    2353   23128529
118  201701-201706  경상남도  진주시  일반용   25017  333851498
119  201701-201706  경상남도  창녕군  일반용    5423   65824356
120  201701-201706  경상남도  창원시  일반용   56412  981824502
121  201701-201706  경상남도  통영시  일반용   11054  151710372
122  201701-201706  경상남도  하동군  일반용    4145   41450322
123  201701-201706  경상남도  함안군  일반용    5250   61379097
124  201701-201706  경상남도  함양군  일반용    3556   31108366
125  201701-201706  경상남도  합천군  일반용    3823   39458723

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201701-201706  경상남도  거제시  일반용   17746   247835550
108  201701-201706  경상남도  거제시   합계   20618  1127545634
109  201701-201706  경상남도  거창군  일반용    4910    52005549
109  201701-201706  경상남도  거창군   합계    9371   223279417
110  201701-201706  경상남도  고성군  일반용    4542    51082649
110  201701-201706  경상남도  고성군   합계    8839   299566961
111  201701-201706  경상남도  김해시   합계   33211  2653606066
111  201701-201706  경상남도  김해시  일반용   29415   469640646
112  201701-201706  경상남도  남해군   합계    8260   131652436
112  201701-201706  경상남도  남해군  일반용    4651    48585586
113  201701-201706  경상남도  밀양시  일반용    9029    96624166
113  201701-201706  경상남도  밀양시   합계   16617   649386150
114  201701-201706  경상남도  사천시   합계   12595   653374097
114  201701-201706  경상남도  사천시  일반용    9304   115198428
115  201701-201706  경상남도  산청군  일반용    3368    32970610
115  201701-201706  경상남도  산청군   합계    7042   165140203
116  201701-201706  경상남도  양산시  일반용   17868   284048484
116  201701-201706  경상남도  양산시   합계   19513  1804893232
117  201701-201706  경상남도  의령군  일반용    2353    23128529
117  201701-201706  경상남도  의령군   합계    5749   209199400
118  201701-201706  경상남도  진주시   합계   31816  1373254688
118  201701-201706  경상남도  진주시  일반용   25017   333851498
119  201701-201706  경상남도  창녕군   합계   10218   504938347
119  201701-201706  경상남도  창녕군  일반용    5423    65824356
120  201701-201706  경상남도  창원시  일반용   56412   981824502
120  201701-201706  경상남도  창원시   합계   76045  5397102480
121  201701-201706  경상남도  통영시   합계   13561   512157642
121  201701-201706  경상남도  통영시  일반용   11054   151710372
122  201701-201706  경상남도  하동군   합계    9000   175126866
122  201701-201706  경상남도  하동군  일반용    4145    41450322
123  201701-201706  경상남도  함안군   합계    8968  1341157486
123  201701-201706  경상남도  함안군  일반용    5250    61379097
124  201701-201706  경상남도  함양군   합계    6947   128730470
124  201701-201706  경상남도  함양군  일반용    3556    31108366
125  201701-201706  경상남도  합천군  일반용    3823    39458723
125  201701-201706  경상남도  합천군   합계    8726   201637456

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[247835550,
 52005549,
 51082649,
 469640646,
 48585586,
 96624166,
 115198428,
 32970610,
 284048484,
 23128529,
 333851498,
 65824356,
 981824502,
 151710372,
 41450322,
 61379097,
 31108366,
 39458723]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1127545634,
 223279417,
 299566961,
 2653606066,
 131652436,
 649386150,
 653374097,
 165140203,
 1804893232,
 209199400,
 1373254688,
 504938347,
 5397102480,
 512157642,
 175126866,
 1341157486,
 128730470,
 201637456]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[21.98, 23.29, 17.05, 17.7, 36.9, 14.88, 17.63, 19.97, 15.74, 11.06, 24.31, 13.04, 18.19, 29.62, 23.67, 4.58, 24.17, 19.57]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    22
1    23
2    17
3    18
4    37
5    15
6    18
7    20
8    16
9    11
10   24
11   13
12   18
13   30
14   24
15    5
16   24
17   20
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  22
1   거창군  일반용  23
2   고성군  일반용  17
3   김해시  일반용  18
4   남해군  일반용  37
5   밀양시  일반용  15
6   사천시  일반용  18
7   산청군  일반용  20
8   양산시  일반용  16
9   의령군  일반용  11
10  진주시  일반용  24
11  창녕군  일반용  13
12  창원시  일반용  18
13  통영시  일반용  30
14  하동군  일반용  24
15  함안군  일반용   5
16  함양군  일반용  24
17  합천군  일반용  20

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201701-201706  경상남도  거제시  일반용   17746   247835550  22
1   201701-201706  경상남도  거제시   합계   20618  1127545634 NaN
2   201701-201706  경상남도  거창군  일반용    4910    52005549  23
3   201701-201706  경상남도  거창군   합계    9371   223279417 NaN
4   201701-201706  경상남도  고성군  일반용    4542    51082649  17
5   201701-201706  경상남도  고성군   합계    8839   299566961 NaN
7   201701-201706  경상남도  김해시  일반용   29415   469640646  18
6   201701-201706  경상남도  김해시   합계   33211  2653606066 NaN
9   201701-201706  경상남도  남해군  일반용    4651    48585586  37
8   201701-201706  경상남도  남해군   합계    8260   131652436 NaN
10  201701-201706  경상남도  밀양시  일반용    9029    96624166  15
11  201701-201706  경상남도  밀양시   합계   16617   649386150 NaN
13  201701-201706  경상남도  사천시  일반용    9304   115198428  18
12  201701-201706  경상남도  사천시   합계   12595   653374097 NaN
14  201701-201706  경상남도  산청군  일반용    3368    32970610  20
15  201701-201706  경상남도  산청군   합계    7042   165140203 NaN
16  201701-201706  경상남도  양산시  일반용   17868   284048484  16
17  201701-201706  경상남도  양산시   합계   19513  1804893232 NaN
18  201701-201706  경상남도  의령군  일반용    2353    23128529  11
19  201701-201706  경상남도  의령군   합계    5749   209199400 NaN
21  201701-201706  경상남도  진주시  일반용   25017   333851498  24
20  201701-201706  경상남도  진주시   합계   31816  1373254688 NaN
23  201701-201706  경상남도  창녕군  일반용    5423    65824356  13
22  201701-201706  경상남도  창녕군   합계   10218   504938347 NaN
24  201701-201706  경상남도  창원시  일반용   56412   981824502  18
25  201701-201706  경상남도  창원시   합계   76045  5397102480 NaN
27  201701-201706  경상남도  통영시  일반용   11054   151710372  30
26  201701-201706  경상남도  통영시   합계   13561   512157642 NaN
29  201701-201706  경상남도  하동군  일반용    4145    41450322  24
28  201701-201706  경상남도  하동군   합계    9000   175126866 NaN
31  201701-201706  경상남도  함안군  일반용    5250    61379097   5
30  201701-201706  경상남도  함안군   합계    8968  1341157486 NaN
33  201701-201706  경상남도  함양군  일반용    3556    31108366  24
32  201701-201706  경상남도  함양군   합계    6947   128730470 NaN
34  201701-201706  경상남도  합천군  일반용    3823    39458723  20
35  201701-201706  경상남도  합천군   합계    8726   201637456 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1701-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)