In [3]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [4]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_12상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2012년 01 월 ~ 2012년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,경상남도,전체(시 / 군 / 구),주택용,"1,016,960","376,746,193","49,138,896,605",130.4
4,201201,경상남도,전체(시 / 군 / 구),일반용,"190,671","541,163,825","62,471,441,822",115.4
...,...,...,...,...,...,...,...,...
907,201206,경상남도,합천군,산업용,956,"6,485,842","598,652,778",92.3
908,201206,경상남도,합천군,심 야,"2,295","1,811,191","84,651,485",46.7
909,201206,경상남도,합천군,일반용,"3,619","5,028,787","551,967,131",109.8
910,201206,경상남도,합천군,주택용,"26,846","4,283,274","442,336,079",103.3
911,201206,경상남도,합천군,합계,"44,540","23,686,693","1,982,867,705",83.7

In [5]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,경상남도,전체(시 / 군 / 구),주택용,"1,016,960","376,746,193","49,138,896,605",130.4
4,201201,경상남도,전체(시 / 군 / 구),일반용,"190,671","541,163,825","62,471,441,822",115.4
5,201201,경상남도,전체(시 / 군 / 구),교육용,"2,768","41,456,462","4,607,332,649",111.1
6,201201,경상남도,전체(시 / 군 / 구),산업용,"33,413","1,628,175,832","178,049,900,550",109.4
...,...,...,...,...,...,...,...,...
907,201206,경상남도,합천군,산업용,956,"6,485,842","598,652,778",92.3
908,201206,경상남도,합천군,심 야,"2,295","1,811,191","84,651,485",46.7
909,201206,경상남도,합천군,일반용,"3,619","5,028,787","551,967,131",109.8
910,201206,경상남도,합천군,주택용,"26,846","4,283,274","442,336,079",103.3
911,201206,경상남도,합천군,합계,"44,540","23,686,693","1,982,867,705",83.7

In [6]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [7]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,경상남도,전체(시 / 군 / 구),주택용,"1,016,960","376,746,193","49,138,896,605",130.4
4,201201,경상남도,전체(시 / 군 / 구),일반용,"190,671","541,163,825","62,471,441,822",115.4
5,201201,경상남도,전체(시 / 군 / 구),교육용,"2,768","41,456,462","4,607,332,649",111.1
6,201201,경상남도,전체(시 / 군 / 구),산업용,"33,413","1,628,175,832","178,049,900,550",109.4
7,201201,경상남도,전체(시 / 군 / 구),농사용,"138,034","202,018,158","8,322,020,622",41.2
...,...,...,...,...,...,...,...,...
907,201206,경상남도,합천군,산업용,956,"6,485,842","598,652,778",92.3
908,201206,경상남도,합천군,심 야,"2,295","1,811,191","84,651,485",46.7
909,201206,경상남도,합천군,일반용,"3,619","5,028,787","551,967,131",109.8
910,201206,경상남도,합천군,주택용,"26,846","4,283,274","442,336,079",103.3
911,201206,경상남도,합천군,합계,"44,540","23,686,693","1,982,867,705",83.7

In [8]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,경상남도,전체(시 / 군 / 구),주택용,"1,016,960","376,746,193","49,138,896,605",130.4
4,201201,경상남도,전체(시 / 군 / 구),일반용,"190,671","541,163,825","62,471,441,822",115.4
5,201201,경상남도,전체(시 / 군 / 구),교육용,"2,768","41,456,462","4,607,332,649",111.1
6,201201,경상남도,전체(시 / 군 / 구),산업용,"33,413","1,628,175,832","178,049,900,550",109.4
7,201201,경상남도,전체(시 / 군 / 구),농사용,"138,034","202,018,158","8,322,020,622",41.2
8,201201,경상남도,전체(시 / 군 / 구),가로등,"121,372","23,336,264","2,090,822,111",89.6
9,201201,경상남도,전체(시 / 군 / 구),심 야,"101,752","231,620,767","15,031,243,159",64.9
10,201202,경상남도,전체(시 / 군 / 구),주택용,"1,018,534","379,441,385","49,725,911,656",131.1
11,201202,경상남도,전체(시 / 군 / 구),일반용,"192,530","533,242,916","62,623,838,948",117.4
12,201202,경상남도,전체(시 / 군 / 구),교육용,"2,768","40,976,856","4,717,124,194",115.1
13,201202,경상남도,전체(시 / 군 / 구),산업용,"33,463","1,715,068,047","182,832,821,313",106.6
14,201202,경상남도,전체(시 / 군 / 구),농사용,"138,257","201,946,768","8,394,156,415",41.6
15,201202,경상남도,전체(시 / 군 / 구),가로등,"121,755","21,956,180","2,060,154,246",93.8
16,201202,경상남도,전체(시 / 군 / 구),심 야,"101,701","237,349,925","15,384,806,919",64.8
17,201203,경상남도,전체(시 / 군 / 구),주택용,"1,020,538","343,045,648","40,585,701,338",118.3
18,201203,경상남도,전체(시 / 군 / 구),일반용,"193,253","472,201,606","51,696,030,353",109.5
19,201203,경상남도,전체(시 / 군 / 구),교육용,"2,763","40,232,942","4,101,130,884",101.9
20,201203,경상남도,전체(시 / 군 / 구),산업용,"33,582","1,736,505,311","154,679,152,449",89.1
21,201203,경상남도,전체(시 / 군 / 구),농사용,"163,299","169,712,622","7,191,859,076",42.4
22,201203,경상남도,전체(시 / 군 / 구),가로등,"121,596","20,495,442","1,967,255,449",96.0
23,201203,경상남도,전체(시 / 군 / 구),심 야,"101,606","194,090,334","11,152,556,032",57.5
24,201204,경상남도,전체(시 / 군 / 구),주택용,"1,023,640","345,906,376","40,836,786,204",118.1
25,201204,경상남도,전체(시 / 군 / 구),일반용,"193,901","440,100,836","43,976,244,221",99.9
26,201204,경상남도,전체(시 / 군 / 구),교육용,"2,751","36,029,730","3,640,872,819",101.1
27,201204,경상남도,전체(시 / 군 / 구),산업용,"33,695","1,647,354,069","144,758,193,853",87.9
28,201204,경상남도,전체(시 / 군 / 구),농사용,"140,251","137,337,075","6,018,180,300",43.8
29,201204,경상남도,전체(시 / 군 / 구),가로등,"122,094","19,858,822","1,991,097,487",100.3
30,201204,경상남도,전체(시 / 군 / 구),심 야,"101,478","158,436,597","7,462,274,892",47.1
31,201205,경상남도,전체(시 / 군 / 구),주택용,"1,026,173","317,325,548","34,440,133,674",108.5
32,201205,경상남도,전체(시 / 군 / 구),일반용,"194,262","394,392,694","41,103,845,830",104.2
33,201205,경상남도,전체(시 / 군 / 구),교육용,"2,746","27,968,929","3,190,102,035",114.1
34,201205,경상남도,전체(시 / 군 / 구),산업용,"33,753","1,605,697,999","142,742,028,195",88.9
35,201205,경상남도,전체(시 / 군 / 구),농사용,"141,869","88,810,182","4,192,817,383",47.2
36,201205,경상남도,전체(시 / 군 / 구),가로등,"123,805","18,471,168","1,911,948,017",103.5
37,201205,경상남도,전체(시 / 군 / 구),심 야,"101,330","88,781,557","4,188,809,135",47.2
38,201206,경상남도,전체(시 / 군 / 구),주택용,"1,028,807","314,815,515","33,929,732,798",107.8
39,201206,경상남도,전체(시 / 군 / 구),일반용,"194,863","415,466,695","42,459,120,658",102.2
40,201206,경상남도,전체(시 / 군 / 구),교육용,"2,743","27,191,651","3,162,066,729",116.3
41,201206,경상남도,전체(시 / 군 / 구),산업용,"33,773","1,648,675,822","145,035,961,762",88.0
42,201206,경상남도,전체(시 / 군 / 구),농사용,"143,575","85,167,915","3,909,266,385",45.9
43,201206,경상남도,전체(시 / 군 / 구),가로등,"125,240","17,941,018","1,911,214,657",106.5
44,201206,경상남도,전체(시 / 군 / 구),심 야,"101,137","51,886,504","2,472,779,925",47.7
45,합계,합계,합계,합계,"9,722,501","17,038,400,185","1,630,157,633,749",95.7

In [9]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_12628\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201201  경상남도  일반용  190,671   541,163,825
11  201202  경상남도  일반용  192,530   533,242,916
18  201203  경상남도  일반용  193,253   472,201,606
25  201204  경상남도  일반용  193,901   440,100,836
32  201205  경상남도  일반용  194,262   394,392,694
39  201206  경상남도  일반용  194,863   415,466,695

In [10]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [11]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [12]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201201  경상남도  거제시  일반용  14,526   39,449,220
197  201202  경상남도  거제시  일반용  14,561   38,750,934
341  201203  경상남도  거제시  일반용  14,633   34,822,238
485  201204  경상남도  거제시  일반용  14,712   32,906,339
629  201205  경상남도  거제시  일반용  14,755   29,327,911
..      ...   ...  ...  ...      ...          ...
333  201202  경상남도  합천군  일반용   3,507    7,331,165
477  201203  경상남도  합천군  일반용   3,602    6,527,442
621  201204  경상남도  합천군  일반용   3,621    5,944,553
765  201205  경상남도  합천군  일반용   3,623    4,954,172
909  201206  경상남도  합천군  일반용   3,619    5,028,787

[108 rows x 6 columns]

In [13]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [14]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [15]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분  고객호수(호)      사용량(kWh)
55   201201  경상남도  거제시   합계  96,953   181,620,357
199  201202  경상남도  거제시   합계  97,544   186,877,998
343  201203  경상남도  거제시   합계  99,651   178,405,458
487  201204  경상남도  거제시   합계  98,569   165,001,215
631  201205  경상남도  거제시   합계  99,066   157,218,589
..      ...   ...  ...  ...      ...           ...
335  201202  경상남도  합천군   합계  43,995    34,743,222
479  201203  경상남도  합천군   합계  46,130    31,739,697
623  201204  경상남도  합천군   합계  44,200    28,786,636
767  201205  경상남도  합천군   합계  44,365    23,201,366
911  201206  경상남도  합천군   합계  44,540    23,686,693

[108 rows x 6 columns]

In [16]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[181620357, 186877998, 178405458, 165001215, 157218589, 155696079]
[40121367, 41142736, 36265566, 33991131, 28424136, 28083052]
[55228614, 55009884, 54120969, 53795171, 42736058, 43590812]
[473449436, 472016824, 445306093, 424048578, 386524698, 386575052]
[25244297, 25541858, 22837136, 21688472, 18507918, 18854919]
[104567528, 106714938, 95526346, 85347450, 69056486, 64514656]
[113457153, 113701586, 108137469, 102580530, 95025661, 95053206]
[27258943, 26816158, 23411774, 20973044, 17079511, 16476840]
[286084460, 289240849, 283413664, 268690211, 259931409, 263977128]
[37610531, 37578561, 35627359, 32569173, 29381115, 29572646]
[240524209, 240044374, 219082579, 203815495, 173808238, 169405856]
[68283444, 68829336, 61809281, 55646804, 44345904, 42986772]
[1017478475, 1033120373, 994726592, 928613572, 878183020, 881821591]
[120111813, 117191222, 109541986, 99768879, 90749497, 91908764]
[31415272, 31808946, 27757381, 26997485, 22903406, 22623882]
[153705153, 216348030, 217990116, 202782282, 178266883, 204087708]
[33684613, 33255182, 30584439, 29927377, 26104182, 22229464]
[34671836, 34743222, 31739697, 28786636, 23201366, 23686693]
경상남도 지역별 합계 :  [1024819696, 208027988, 304481508, 2587920681, 132674600, 525727404, 627955605, 132016270, 1651337721, 202339385, 1246680751, 341901541, 5733943623, 629272161, 163506372, 1173180172, 175785257, 176829450]
경상남도 고객호수 평균:  [16431, 8140, 7730, 27999, 7596, 14474, 11161, 5938, 14462, 4966, 28417, 8982, 72410, 12402, 7692, 7755, 6085, 7421]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [17]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)      사용량(kWh)
0           201201  경상남도  거제시   합계  96,953   181,620,357
1           201202  경상남도  거제시   합계  97,544   186,877,998
2           201203  경상남도  거제시   합계  99,651   178,405,458
3           201204  경상남도  거제시   합계  98,569   165,001,215
4           201205  경상남도  거제시   합계  99,066   157,218,589
..             ...   ...  ...  ...      ...           ...
121  201201-201206  경상남도  통영시   합계    12402     629272161
122  201201-201206  경상남도  하동군   합계     7692     163506372
123  201201-201206  경상남도  함안군   합계     7755    1173180172
124  201201-201206  경상남도  함양군   합계     6085     175785257
125  201201-201206  경상남도  합천군   합계     7421     176829450

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [18]:
Hap = Hap.loc[Hap['년월'] == '201201-201206']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201201-201206  경상남도  거제시   합계   16431  1024819696
109  201201-201206  경상남도  거창군   합계    8140   208027988
110  201201-201206  경상남도  고성군   합계    7730   304481508
111  201201-201206  경상남도  김해시   합계   27999  2587920681
112  201201-201206  경상남도  남해군   합계    7596   132674600
113  201201-201206  경상남도  밀양시   합계   14474   525727404
114  201201-201206  경상남도  사천시   합계   11161   627955605
115  201201-201206  경상남도  산청군   합계    5938   132016270
116  201201-201206  경상남도  양산시   합계   14462  1651337721
117  201201-201206  경상남도  의령군   합계    4966   202339385
118  201201-201206  경상남도  진주시   합계   28417  1246680751
119  201201-201206  경상남도  창녕군   합계    8982   341901541
120  201201-201206  경상남도  창원시   합계   72410  5733943623
121  201201-201206  경상남도  통영시   합계   12402   629272161
122  201201-201206  경상남도  하동군   합계    7692   163506372
123  201201-201206  경상남도  함안군   합계    7755  1173180172
124  201201-201206  경상남도  함양군   합계    6085   175785257
125  201201-201206  경상남도  합천군   합계    7421   176829450

In [19]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [20]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [21]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201201  경상남도  거제시  일반용  14,526   39,449,220
197  201202  경상남도  거제시  일반용  14,561   38,750,934
341  201203  경상남도  거제시  일반용  14,633   34,822,238
485  201204  경상남도  거제시  일반용  14,712   32,906,339
629  201205  경상남도  거제시  일반용  14,755   29,327,911
..      ...   ...  ...  ...      ...          ...
333  201202  경상남도  합천군  일반용   3,507    7,331,165
477  201203  경상남도  합천군  일반용   3,602    6,527,442
621  201204  경상남도  합천군  일반용   3,621    5,944,553
765  201205  경상남도  합천군  일반용   3,623    4,954,172
909  201206  경상남도  합천군  일반용   3,619    5,028,787

[108 rows x 6 columns]

In [22]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [23]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[39449220, 38750934, 34822238, 32906339, 29327911, 30527419]
[9817053, 9962436, 8671547, 7999598, 6626707, 6712188]
[8566332, 8630823, 7762608, 7686073, 6837046, 6940304]
[78999512, 77201504, 68013705, 63027536, 56747580, 60870133]
[8324444, 8441041, 7421471, 6951634, 6090343, 6244988]
[16155286, 15888596, 13838174, 12861879, 11290476, 11840903]
[19841386, 19984803, 17729067, 16574656, 14592373, 15186213]
[5261230, 5208926, 4632755, 4360678, 3759393, 3755733]
[45726452, 44981511, 39761354, 36708962, 33638762, 35575688]
[3924621, 3821519, 3328122, 3275146, 2718166, 2751468]
[57500751, 57011138, 50379837, 46989468, 41518894, 44040665]
[11974531, 11702326, 10327292, 9395268, 8214884, 8282189]
[177962556, 174495459, 154399246, 143449079, 131692110, 140563281]
[27025147, 26949363, 24101749, 22347360, 19452974, 20162347]
[7121892, 7102232, 6370660, 6242718, 5224593, 5148984]
[10281755, 10067932, 8923935, 8345035, 7424952, 7639912]
[5705199, 5711208, 5190404, 5034854, 4281358, 4195493]
[7526458, 7331165, 6527442, 5944553, 4954172, 5028787]
경상남도 지역별 일반용 합계 :  [205784061, 49789529, 46423186, 404859970, 43473921, 81875314, 103908498, 26978715, 236392729, 19819042, 297440753, 59896490, 922561731, 140038940, 37211079, 52683521, 30118516, 37312577]
경상남도 고객호수 평균:  [14668, 4495, 4133, 25491, 4188, 8118, 8427, 2997, 14205, 2119, 22093, 4945, 52657, 9574, 3792, 4583, 3203, 3550]

In [24]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [25]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [26]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [27]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12628\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201201  경상남도  거제시  일반용  14,526   39,449,220
1           201202  경상남도  거제시  일반용  14,561   38,750,934
2           201203  경상남도  거제시  일반용  14,633   34,822,238
3           201204  경상남도  거제시  일반용  14,712   32,906,339
4           201205  경상남도  거제시  일반용  14,755   29,327,911
..             ...   ...  ...  ...      ...          ...
121  201201-201206  경상남도  통영시  일반용     9574    140038940
122  201201-201206  경상남도  하동군  일반용     3792     37211079
123  201201-201206  경상남도  함안군  일반용     4583     52683521
124  201201-201206  경상남도  함양군  일반용     3203     30118516
125  201201-201206  경상남도  합천군  일반용     3550     37312577

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [28]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201201-201206']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201201-201206  경상남도  거제시  일반용   14668  205784061
109  201201-201206  경상남도  거창군  일반용    4495   49789529
110  201201-201206  경상남도  고성군  일반용    4133   46423186
111  201201-201206  경상남도  김해시  일반용   25491  404859970
112  201201-201206  경상남도  남해군  일반용    4188   43473921
113  201201-201206  경상남도  밀양시  일반용    8118   81875314
114  201201-201206  경상남도  사천시  일반용    8427  103908498
115  201201-201206  경상남도  산청군  일반용    2997   26978715
116  201201-201206  경상남도  양산시  일반용   14205  236392729
117  201201-201206  경상남도  의령군  일반용    2119   19819042
118  201201-201206  경상남도  진주시  일반용   22093  297440753
119  201201-201206  경상남도  창녕군  일반용    4945   59896490
120  201201-201206  경상남도  창원시  일반용   52657  922561731
121  201201-201206  경상남도  통영시  일반용    9574  140038940
122  201201-201206  경상남도  하동군  일반용    3792   37211079
123  201201-201206  경상남도  함안군  일반용    4583   52683521
124  201201-201206  경상남도  함양군  일반용    3203   30118516
125  201201-201206  경상남도  합천군  일반용    3550   37312577

In [29]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201201-201206  경상남도  거제시  일반용   14668   205784061
108  201201-201206  경상남도  거제시   합계   16431  1024819696
109  201201-201206  경상남도  거창군  일반용    4495    49789529
109  201201-201206  경상남도  거창군   합계    8140   208027988
110  201201-201206  경상남도  고성군  일반용    4133    46423186
110  201201-201206  경상남도  고성군   합계    7730   304481508
111  201201-201206  경상남도  김해시   합계   27999  2587920681
111  201201-201206  경상남도  김해시  일반용   25491   404859970
112  201201-201206  경상남도  남해군   합계    7596   132674600
112  201201-201206  경상남도  남해군  일반용    4188    43473921
113  201201-201206  경상남도  밀양시  일반용    8118    81875314
113  201201-201206  경상남도  밀양시   합계   14474   525727404
114  201201-201206  경상남도  사천시   합계   11161   627955605
114  201201-201206  경상남도  사천시  일반용    8427   103908498
115  201201-201206  경상남도  산청군  일반용    2997    26978715
115  201201-201206  경상남도  산청군   합계    5938   132016270
116  201201-201206  경상남도  양산시  일반용   14205   236392729
116  201201-201206  경상남도  양산시   합계   14462  1651337721
117  201201-201206  경상남도  의령군  일반용    2119    19819042
117  201201-201206  경상남도  의령군   합계    4966   202339385
118  201201-201206  경상남도  진주시   합계   28417  1246680751
118  201201-201206  경상남도  진주시  일반용   22093   297440753
119  201201-201206  경상남도  창녕군   합계    8982   341901541
119  201201-201206  경상남도  창녕군  일반용    4945    59896490
120  201201-201206  경상남도  창원시  일반용   52657   922561731
120  201201-201206  경상남도  창원시   합계   72410  5733943623
121  201201-201206  경상남도  통영시   합계   12402   629272161
121  201201-201206  경상남도  통영시  일반용    9574   140038940
122  201201-201206  경상남도  하동군   합계    7692   163506372
122  201201-201206  경상남도  하동군  일반용    3792    37211079
123  201201-201206  경상남도  함안군   합계    7755  1173180172
123  201201-201206  경상남도  함안군  일반용    4583    52683521
124  201201-201206  경상남도  함양군   합계    6085   175785257
124  201201-201206  경상남도  함양군  일반용    3203    30118516
125  201201-201206  경상남도  합천군  일반용    3550    37312577
125  201201-201206  경상남도  합천군   합계    7421   176829450

In [30]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[205784061,
 49789529,
 46423186,
 404859970,
 43473921,
 81875314,
 103908498,
 26978715,
 236392729,
 19819042,
 297440753,
 59896490,
 922561731,
 140038940,
 37211079,
 52683521,
 30118516,
 37312577]

In [31]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1024819696,
 208027988,
 304481508,
 2587920681,
 132674600,
 525727404,
 627955605,
 132016270,
 1651337721,
 202339385,
 1246680751,
 341901541,
 5733943623,
 629272161,
 163506372,
 1173180172,
 175785257,
 176829450]

In [32]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[20.08, 23.93, 15.25, 15.64, 32.77, 15.57, 16.55, 20.44, 14.32, 9.79, 23.86, 17.52, 16.09, 22.25, 22.76, 4.49, 17.13, 21.1]

In [33]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    20
1    24
2    15
3    16
4    33
5    16
6    17
7    20
8    14
9    10
10   24
11   18
12   16
13   22
14   23
15    4
16   17
17   21
dtype: float64

In [34]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  20
1   거창군  일반용  24
2   고성군  일반용  15
3   김해시  일반용  16
4   남해군  일반용  33
5   밀양시  일반용  16
6   사천시  일반용  17
7   산청군  일반용  20
8   양산시  일반용  14
9   의령군  일반용  10
10  진주시  일반용  24
11  창녕군  일반용  18
12  창원시  일반용  16
13  통영시  일반용  22
14  하동군  일반용  23
15  함안군  일반용   4
16  함양군  일반용  17
17  합천군  일반용  21

In [35]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201201-201206  경상남도  거제시  일반용   14668   205784061  20
1   201201-201206  경상남도  거제시   합계   16431  1024819696 NaN
2   201201-201206  경상남도  거창군  일반용    4495    49789529  24
3   201201-201206  경상남도  거창군   합계    8140   208027988 NaN
4   201201-201206  경상남도  고성군  일반용    4133    46423186  15
5   201201-201206  경상남도  고성군   합계    7730   304481508 NaN
7   201201-201206  경상남도  김해시  일반용   25491   404859970  16
6   201201-201206  경상남도  김해시   합계   27999  2587920681 NaN
9   201201-201206  경상남도  남해군  일반용    4188    43473921  33
8   201201-201206  경상남도  남해군   합계    7596   132674600 NaN
10  201201-201206  경상남도  밀양시  일반용    8118    81875314  16
11  201201-201206  경상남도  밀양시   합계   14474   525727404 NaN
13  201201-201206  경상남도  사천시  일반용    8427   103908498  17
12  201201-201206  경상남도  사천시   합계   11161   627955605 NaN
14  201201-201206  경상남도  산청군  일반용    2997    26978715  20
15  201201-201206  경상남도  산청군   합계    5938   132016270 NaN
16  201201-201206  경상남도  양산시  일반용   14205   236392729  14
17  201201-201206  경상남도  양산시   합계   14462  1651337721 NaN
18  201201-201206  경상남도  의령군  일반용    2119    19819042  10
19  201201-201206  경상남도  의령군   합계    4966   202339385 NaN
21  201201-201206  경상남도  진주시  일반용   22093   297440753  24
20  201201-201206  경상남도  진주시   합계   28417  1246680751 NaN
23  201201-201206  경상남도  창녕군  일반용    4945    59896490  18
22  201201-201206  경상남도  창녕군   합계    8982   341901541 NaN
24  201201-201206  경상남도  창원시  일반용   52657   922561731  16
25  201201-201206  경상남도  창원시   합계   72410  5733943623 NaN
27  201201-201206  경상남도  통영시  일반용    9574   140038940  22
26  201201-201206  경상남도  통영시   합계   12402   629272161 NaN
29  201201-201206  경상남도  하동군  일반용    3792    37211079  23
28  201201-201206  경상남도  하동군   합계    7692   163506372 NaN
31  201201-201206  경상남도  함안군  일반용    4583    52683521   4
30  201201-201206  경상남도  함안군   합계    7755  1173180172 NaN
33  201201-201206  경상남도  함양군  일반용    3203    30118516  17
32  201201-201206  경상남도  함양군   합계    6085   175785257 NaN
34  201201-201206  경상남도  합천군  일반용    3550    37312577  21
35  201201-201206  경상남도  합천군   합계    7421   176829450 NaN

In [36]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [37]:
Final.to_csv("{}_일반용_전력사용량_1201-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [38]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [39]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [40]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [41]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [42]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [43]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [44]:
# SEOUL

In [45]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)