In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('경상남도_계약종별_전력사용량_월별_15상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 경상남도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2015년 01 월 ~ 2015년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경상남도,전체(시 / 군 / 구),주택용,"1,088,480","386,267,482","52,501,146,302",135.9
4,201501,경상남도,전체(시 / 군 / 구),일반용,"211,557","579,326,501","77,180,162,639",133.2
...,...,...,...,...,...,...,...,...
907,201506,경상남도,합천군,산업용,963,"6,238,848","794,859,153",127.4
908,201506,경상남도,합천군,심 야,"2,246","1,555,290","84,146,899",54.1
909,201506,경상남도,합천군,일반용,"3,910","5,394,955","734,440,066",136.1
910,201506,경상남도,합천군,주택용,"27,618","4,132,409","467,030,610",113
911,201506,경상남도,합천군,합계,"47,944","25,519,586","2,520,683,610",98.8

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경상남도,전체(시 / 군 / 구),주택용,"1,088,480","386,267,482","52,501,146,302",135.9
4,201501,경상남도,전체(시 / 군 / 구),일반용,"211,557","579,326,501","77,180,162,639",133.2
5,201501,경상남도,전체(시 / 군 / 구),교육용,"1,592","39,205,445","4,617,914,889",117.8
6,201501,경상남도,전체(시 / 군 / 구),산업용,"35,928","1,757,495,823","217,359,246,030",123.7
...,...,...,...,...,...,...,...,...
907,201506,경상남도,합천군,산업용,963,"6,238,848","794,859,153",127.4
908,201506,경상남도,합천군,심 야,"2,246","1,555,290","84,146,899",54.1
909,201506,경상남도,합천군,일반용,"3,910","5,394,955","734,440,066",136.1
910,201506,경상남도,합천군,주택용,"27,618","4,132,409","467,030,610",113
911,201506,경상남도,합천군,합계,"47,944","25,519,586","2,520,683,610",98.8

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경상남도,전체(시 / 군 / 구),주택용,"1,088,480","386,267,482","52,501,146,302",135.9
4,201501,경상남도,전체(시 / 군 / 구),일반용,"211,557","579,326,501","77,180,162,639",133.2
5,201501,경상남도,전체(시 / 군 / 구),교육용,"1,592","39,205,445","4,617,914,889",117.8
6,201501,경상남도,전체(시 / 군 / 구),산업용,"35,928","1,757,495,823","217,359,246,030",123.7
7,201501,경상남도,전체(시 / 군 / 구),농사용,"169,230","317,397,368","14,651,389,160",46.2
...,...,...,...,...,...,...,...,...
907,201506,경상남도,합천군,산업용,963,"6,238,848","794,859,153",127.4
908,201506,경상남도,합천군,심 야,"2,246","1,555,290","84,146,899",54.1
909,201506,경상남도,합천군,일반용,"3,910","5,394,955","734,440,066",136.1
910,201506,경상남도,합천군,주택용,"27,618","4,132,409","467,030,610",113
911,201506,경상남도,합천군,합계,"47,944","25,519,586","2,520,683,610",98.8

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201501,경상남도,전체(시 / 군 / 구),주택용,"1,088,480","386,267,482","52,501,146,302",135.9
4,201501,경상남도,전체(시 / 군 / 구),일반용,"211,557","579,326,501","77,180,162,639",133.2
5,201501,경상남도,전체(시 / 군 / 구),교육용,"1,592","39,205,445","4,617,914,889",117.8
6,201501,경상남도,전체(시 / 군 / 구),산업용,"35,928","1,757,495,823","217,359,246,030",123.7
7,201501,경상남도,전체(시 / 군 / 구),농사용,"169,230","317,397,368","14,651,389,160",46.2
8,201501,경상남도,전체(시 / 군 / 구),가로등,"142,249","25,144,821","2,659,911,604",105.8
9,201501,경상남도,전체(시 / 군 / 구),심 야,"97,527","194,825,067","14,711,796,261",75.5
10,201502,경상남도,전체(시 / 군 / 구),주택용,"1,090,328","379,510,176","50,591,562,489",133.3
11,201502,경상남도,전체(시 / 군 / 구),일반용,"211,912","554,623,039","74,758,088,569",134.8
12,201502,경상남도,전체(시 / 군 / 구),교육용,"1,600","37,153,860","4,426,959,997",119.2
13,201502,경상남도,전체(시 / 군 / 구),산업용,"35,966","1,596,046,858","200,400,560,174",125.6
14,201502,경상남도,전체(시 / 군 / 구),농사용,"169,400","295,366,490","13,729,051,619",46.5
15,201502,경상남도,전체(시 / 군 / 구),가로등,"142,663","23,679,422","2,640,976,274",111.5
16,201502,경상남도,전체(시 / 군 / 구),심 야,"97,399","185,022,551","13,963,590,184",75.5
17,201503,경상남도,전체(시 / 군 / 구),주택용,"1,091,978","337,126,857","40,196,298,666",119.2
18,201503,경상남도,전체(시 / 군 / 구),일반용,"211,663","476,862,574","60,284,881,317",126.4
19,201503,경상남도,전체(시 / 군 / 구),교육용,"1,609","37,209,290","3,850,429,948",103.5
20,201503,경상남도,전체(시 / 군 / 구),산업용,"36,007","1,701,119,157","176,987,343,892",104.0
21,201503,경상남도,전체(시 / 군 / 구),농사용,"193,709","235,966,351","11,164,448,654",47.3
22,201503,경상남도,전체(시 / 군 / 구),가로등,"142,890","22,104,887","2,499,636,821",113.1
23,201503,경상남도,전체(시 / 군 / 구),심 야,"97,203","153,840,776","10,219,705,192",66.4
24,201504,경상남도,전체(시 / 군 / 구),주택용,"1,094,288","350,458,689","42,781,331,881",122.1
25,201504,경상남도,전체(시 / 군 / 구),일반용,"211,950","466,790,225","53,963,249,870",115.6
26,201504,경상남도,전체(시 / 군 / 구),교육용,"1,612","34,251,822","3,444,180,959",100.6
27,201504,경상남도,전체(시 / 군 / 구),산업용,"36,123","1,709,072,533","173,818,751,554",101.7
28,201504,경상남도,전체(시 / 군 / 구),농사용,"170,900","184,828,133","9,016,438,213",48.8
29,201504,경상남도,전체(시 / 군 / 구),가로등,"143,222","21,631,543","2,535,757,041",117.2
30,201504,경상남도,전체(시 / 군 / 구),심 야,"97,085","121,671,406","6,626,450,006",54.5
31,201505,경상남도,전체(시 / 군 / 구),주택용,"1,096,178","325,427,937","37,410,476,064",115.0
32,201505,경상남도,전체(시 / 군 / 구),일반용,"212,054","428,528,149","51,066,700,917",119.2
33,201505,경상남도,전체(시 / 군 / 구),교육용,"1,608","25,956,869","2,970,126,659",114.4
34,201505,경상남도,전체(시 / 군 / 구),산업용,"36,198","1,631,482,870","165,599,884,838",101.5
35,201505,경상남도,전체(시 / 군 / 구),농사용,"172,054","125,341,176","6,571,010,884",52.4
36,201505,경상남도,전체(시 / 군 / 구),가로등,"143,693","20,297,951","2,457,539,571",121.1
37,201505,경상남도,전체(시 / 군 / 구),심 야,"96,829","75,126,014","4,107,070,450",54.7
38,201506,경상남도,전체(시 / 군 / 구),주택용,"1,098,152","324,541,283","37,203,117,711",114.6
39,201506,경상남도,전체(시 / 군 / 구),일반용,"212,454","447,417,350","60,717,789,090",135.7
40,201506,경상남도,전체(시 / 군 / 구),교육용,"1,609","27,667,102","3,677,430,759",132.9
41,201506,경상남도,전체(시 / 군 / 구),산업용,"36,309","1,663,889,904","209,194,893,820",125.7
42,201506,경상남도,전체(시 / 군 / 구),농사용,"172,697","103,510,660","5,329,335,295",51.5
43,201506,경상남도,전체(시 / 군 / 구),가로등,"144,339","19,567,155","2,441,722,441",124.8
44,201506,경상남도,전체(시 / 군 / 구),심 야,"96,619","42,784,491","2,363,059,491",55.2
45,합계,합계,합계,합계,"10,546,863","17,485,538,057","1,932,691,418,195",110.5

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_10752\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월    시구 계약구분   고객호수(호)      사용량(kWh)
4   201501  경상남도  일반용  211,557   579,326,501
11  201502  경상남도  일반용  211,912   554,623,039
18  201503  경상남도  일반용  211,663   476,862,574
25  201504  경상남도  일반용  211,950   466,790,225
32  201505  경상남도  일반용  212,054   428,528,149
39  201506  경상남도  일반용  212,454   447,417,350

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  경상남도  거제시  일반용  16,836   45,199,521
197  201502  경상남도  거제시  일반용  16,933   43,850,037
341  201503  경상남도  거제시  일반용  16,973   37,765,485
485  201504  경상남도  거제시  일반용  17,048   37,513,077
629  201505  경상남도  거제시  일반용  17,106   34,439,758
..      ...   ...  ...  ...      ...          ...
333  201502  경상남도  합천군  일반용   4,034    7,715,069
477  201503  경상남도  합천군  일반용   3,959    6,539,271
621  201504  경상남도  합천군  일반용   3,943    6,208,482
765  201505  경상남도  합천군  일반용   3,926    5,538,960
909  201506  경상남도  합천군  일반용   3,910    5,394,955

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'경상남도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['거제시',
 '거창군',
 '고성군',
 '김해시',
 '남해군',
 '밀양시',
 '사천시',
 '산청군',
 '양산시',
 '의령군',
 '진주시',
 '창녕군',
 '창원시',
 '통영시',
 '하동군',
 '함안군',
 '함양군',
 '합천군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201501  경상남도  거제시   합계  114,196   200,251,376
199  201502  경상남도  거제시   합계  114,793   181,445,649
343  201503  경상남도  거제시   합계  116,751   176,840,772
487  201504  경상남도  거제시   합계  116,042   176,321,459
631  201505  경상남도  거제시   합계  116,737   161,379,317
..      ...   ...  ...  ...       ...           ...
335  201502  경상남도  합천군   합계   47,470    38,268,310
479  201503  경상남도  합천군   합계   49,515    33,218,369
623  201504  경상남도  합천군   합계   47,576    30,461,908
767  201505  경상남도  합천군   합계   47,696    25,512,775
911  201506  경상남도  합천군   합계   47,944    25,519,586

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[200251376, 181445649, 176840772, 176321459, 161379317, 171117388]
[43523460, 41475158, 37606692, 35792535, 31163685, 30803109]
[66287337, 61130017, 57513329, 57277203, 49917432, 45734562]
[489199662, 479630591, 425050099, 440419949, 392389613, 402986599]
[25812427, 24739247, 21730423, 21680908, 19181310, 19225715]
[132666933, 123957260, 110619728, 100607753, 81889324, 72990685]
[122637377, 114224843, 109807224, 107556211, 98393177, 99460157]
[32286939, 31030214, 26111235, 23810958, 20510505, 20193987]
[317463920, 293203095, 291311707, 290019624, 272243052, 281904913]
[41575125, 38209524, 35608382, 33362465, 29216065, 28484234]
[276721773, 264761508, 234444966, 220065688, 184660371, 170933969]
[95551193, 87815835, 78528228, 74150991, 63307574, 62359647]
[1012389204, 926680008, 952083869, 923566991, 864309654, 859270983]
[113432083, 103588257, 98268911, 99040791, 91212370, 91345147]
[33421174, 32512022, 28969460, 27065478, 22911158, 21726699]
[231486518, 203907359, 225587147, 207194160, 206404184, 208253287]
[25528989, 24823499, 20929351, 20309279, 17559400, 17067278]
[39427017, 38268310, 33218369, 30461908, 25512775, 25519586]
경상남도 지역별 합계 :  [1067355961, 220364639, 337859880, 2629676513, 132370030, 622731683, 652078989, 153943838, 1746146311, 206455795, 1351588275, 461713468, 5538300709, 596887559, 166605991, 1282832655, 126217796, 192407965]
경상남도 고객호수 평균:  [19327, 8834, 8359, 31456, 8024, 15766, 11863, 6592, 17460, 5449, 30320, 9649, 75376, 13023, 8353, 8548, 6568, 7990]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\3184527758.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201501  경상남도  거제시   합계  114,196   200,251,376
1           201502  경상남도  거제시   합계  114,793   181,445,649
2           201503  경상남도  거제시   합계  116,751   176,840,772
3           201504  경상남도  거제시   합계  116,042   176,321,459
4           201505  경상남도  거제시   합계  116,737   161,379,317
..             ...   ...  ...  ...       ...           ...
121  201501-201506  경상남도  통영시   합계     13023     596887559
122  201501-201506  경상남도  하동군   합계      8353     166605991
123  201501-201506  경상남도  함안군   합계      8548    1282832655
124  201501-201506  경상남도  함양군   합계      6568     126217796
125  201501-201506  경상남도  합천군   합계      7990     192407965

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201501-201506']
Hap

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201501-201506  경상남도  거제시   합계   19327  1067355961
109  201501-201506  경상남도  거창군   합계    8834   220364639
110  201501-201506  경상남도  고성군   합계    8359   337859880
111  201501-201506  경상남도  김해시   합계   31456  2629676513
112  201501-201506  경상남도  남해군   합계    8024   132370030
113  201501-201506  경상남도  밀양시   합계   15766   622731683
114  201501-201506  경상남도  사천시   합계   11863   652078989
115  201501-201506  경상남도  산청군   합계    6592   153943838
116  201501-201506  경상남도  양산시   합계   17460  1746146311
117  201501-201506  경상남도  의령군   합계    5449   206455795
118  201501-201506  경상남도  진주시   합계   30320  1351588275
119  201501-201506  경상남도  창녕군   합계    9649   461713468
120  201501-201506  경상남도  창원시   합계   75376  5538300709
121  201501-201506  경상남도  통영시   합계   13023   596887559
122  201501-201506  경상남도  하동군   합계    8353   166605991
123  201501-201506  경상남도  함안군   합계    8548  1282832655
124  201501-201506  경상남도  함양군   합계    6568   126217796
125  201501-201506  경상남도  합천군   합계    7990   192407965

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201501  경상남도  거제시  일반용  16,836   45,199,521
197  201502  경상남도  거제시  일반용  16,933   43,850,037
341  201503  경상남도  거제시  일반용  16,973   37,765,485
485  201504  경상남도  거제시  일반용  17,048   37,513,077
629  201505  경상남도  거제시  일반용  17,106   34,439,758
..      ...   ...  ...  ...      ...          ...
333  201502  경상남도  합천군  일반용   4,034    7,715,069
477  201503  경상남도  합천군  일반용   3,959    6,539,271
621  201504  경상남도  합천군  일반용   3,943    6,208,482
765  201505  경상남도  합천군  일반용   3,926    5,538,960
909  201506  경상남도  합천군  일반용   3,910    5,394,955

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[45199521, 43850037, 37765485, 37513077, 34439758, 35453657]
[10535016, 10209381, 8565311, 8186918, 7089692, 7066716]
[9499302, 9343405, 8043337, 7931124, 6977077, 7032093]
[86116531, 82496929, 69667712, 68540085, 64034040, 68853033]
[9447013, 8900267, 7696469, 7647551, 6917556, 6765450]
[17284282, 16592828, 13989358, 13684827, 12149656, 12510758]
[21390433, 20819298, 17840149, 17362596, 15393898, 15841147]
[6011048, 5767128, 4957664, 4859356, 4393554, 4348969]
[49555143, 47235769, 40266072, 39824766, 37199925, 39236920]
[4523162, 4322805, 3628662, 3560404, 3092993, 3001684]
[59409115, 57016778, 49295462, 48166296, 44480819, 46039523]
[12653645, 11889021, 10419925, 9923617, 8962256, 8900417]
[186258829, 176445777, 153704809, 149239470, 138278544, 147156822]
[28353418, 27318583, 23380766, 23010599, 20786794, 20746824]
[8019697, 7962954, 6735039, 6837817, 5812142, 5672692]
[11151320, 10786703, 9227879, 9181764, 8471150, 8931726]
[6098056, 5950307, 5139204, 5111476, 4509335, 4463964]
[7820970, 7715069, 6539271, 6208482, 5538960, 5394955]
경상남도 지역별 일반용 합계 :  [234221535, 51653034, 48826338, 439708330, 47374306, 86211709, 108647521, 30337719, 253318595, 22129710, 304407993, 62748881, 951084251, 143596984, 41040341, 57750542, 31272342, 39217707]
경상남도 고객호수 평균:  [17008, 4929, 4603, 28273, 4679, 8965, 8999, 3379, 16213, 2532, 23749, 5388, 55740, 10526, 4147, 5271, 3556, 3968]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_10752\2656733255.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201501-201506'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월    시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201501  경상남도  거제시  일반용  16,836   45,199,521
1           201502  경상남도  거제시  일반용  16,933   43,850,037
2           201503  경상남도  거제시  일반용  16,973   37,765,485
3           201504  경상남도  거제시  일반용  17,048   37,513,077
4           201505  경상남도  거제시  일반용  17,106   34,439,758
..             ...   ...  ...  ...      ...          ...
121  201501-201506  경상남도  통영시  일반용    10526    143596984
122  201501-201506  경상남도  하동군  일반용     4147     41040341
123  201501-201506  경상남도  함안군  일반용     5271     57750542
124  201501-201506  경상남도  함양군  일반용     3556     31272342
125  201501-201506  경상남도  합천군  일반용     3968     39217707

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201501-201506']
GyeonGiHap2

                년월    시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201501-201506  경상남도  거제시  일반용   17008  234221535
109  201501-201506  경상남도  거창군  일반용    4929   51653034
110  201501-201506  경상남도  고성군  일반용    4603   48826338
111  201501-201506  경상남도  김해시  일반용   28273  439708330
112  201501-201506  경상남도  남해군  일반용    4679   47374306
113  201501-201506  경상남도  밀양시  일반용    8965   86211709
114  201501-201506  경상남도  사천시  일반용    8999  108647521
115  201501-201506  경상남도  산청군  일반용    3379   30337719
116  201501-201506  경상남도  양산시  일반용   16213  253318595
117  201501-201506  경상남도  의령군  일반용    2532   22129710
118  201501-201506  경상남도  진주시  일반용   23749  304407993
119  201501-201506  경상남도  창녕군  일반용    5388   62748881
120  201501-201506  경상남도  창원시  일반용   55740  951084251
121  201501-201506  경상남도  통영시  일반용   10526  143596984
122  201501-201506  경상남도  하동군  일반용    4147   41040341
123  201501-201506  경상남도  함안군  일반용    5271   57750542
124  201501-201506  경상남도  함양군  일반용    3556   31272342
125  201501-201506  경상남도  합천군  일반용    3968   39217707

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201501-201506  경상남도  거제시  일반용   17008   234221535
108  201501-201506  경상남도  거제시   합계   19327  1067355961
109  201501-201506  경상남도  거창군  일반용    4929    51653034
109  201501-201506  경상남도  거창군   합계    8834   220364639
110  201501-201506  경상남도  고성군  일반용    4603    48826338
110  201501-201506  경상남도  고성군   합계    8359   337859880
111  201501-201506  경상남도  김해시   합계   31456  2629676513
111  201501-201506  경상남도  김해시  일반용   28273   439708330
112  201501-201506  경상남도  남해군   합계    8024   132370030
112  201501-201506  경상남도  남해군  일반용    4679    47374306
113  201501-201506  경상남도  밀양시  일반용    8965    86211709
113  201501-201506  경상남도  밀양시   합계   15766   622731683
114  201501-201506  경상남도  사천시   합계   11863   652078989
114  201501-201506  경상남도  사천시  일반용    8999   108647521
115  201501-201506  경상남도  산청군  일반용    3379    30337719
115  201501-201506  경상남도  산청군   합계    6592   153943838
116  201501-201506  경상남도  양산시  일반용   16213   253318595
116  201501-201506  경상남도  양산시   합계   17460  1746146311
117  201501-201506  경상남도  의령군  일반용    2532    22129710
117  201501-201506  경상남도  의령군   합계    5449   206455795
118  201501-201506  경상남도  진주시   합계   30320  1351588275
118  201501-201506  경상남도  진주시  일반용   23749   304407993
119  201501-201506  경상남도  창녕군   합계    9649   461713468
119  201501-201506  경상남도  창녕군  일반용    5388    62748881
120  201501-201506  경상남도  창원시  일반용   55740   951084251
120  201501-201506  경상남도  창원시   합계   75376  5538300709
121  201501-201506  경상남도  통영시   합계   13023   596887559
121  201501-201506  경상남도  통영시  일반용   10526   143596984
122  201501-201506  경상남도  하동군   합계    8353   166605991
122  201501-201506  경상남도  하동군  일반용    4147    41040341
123  201501-201506  경상남도  함안군   합계    8548  1282832655
123  201501-201506  경상남도  함안군  일반용    5271    57750542
124  201501-201506  경상남도  함양군   합계    6568   126217796
124  201501-201506  경상남도  함양군  일반용    3556    31272342
125  201501-201506  경상남도  합천군  일반용    3968    39217707
125  201501-201506  경상남도  합천군   합계    7990   192407965

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[234221535,
 51653034,
 48826338,
 439708330,
 47374306,
 86211709,
 108647521,
 30337719,
 253318595,
 22129710,
 304407993,
 62748881,
 951084251,
 143596984,
 41040341,
 57750542,
 31272342,
 39217707]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[1067355961,
 220364639,
 337859880,
 2629676513,
 132370030,
 622731683,
 652078989,
 153943838,
 1746146311,
 206455795,
 1351588275,
 461713468,
 5538300709,
 596887559,
 166605991,
 1282832655,
 126217796,
 192407965]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[21.94, 23.44, 14.45, 16.72, 35.79, 13.84, 16.66, 19.71, 14.51, 10.72, 22.52, 13.59, 17.17, 24.06, 24.63, 4.5, 24.78, 20.38]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    22
1    23
2    14
3    17
4    36
5    14
6    17
7    20
8    15
9    11
10   23
11   14
12   17
13   24
14   25
15    4
16   25
17   20
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   거제시  일반용  22
1   거창군  일반용  23
2   고성군  일반용  14
3   김해시  일반용  17
4   남해군  일반용  36
5   밀양시  일반용  14
6   사천시  일반용  17
7   산청군  일반용  20
8   양산시  일반용  15
9   의령군  일반용  11
10  진주시  일반용  23
11  창녕군  일반용  14
12  창원시  일반용  17
13  통영시  일반용  24
14  하동군  일반용  25
15  함안군  일반용   4
16  함양군  일반용  25
17  합천군  일반용  20

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월    시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201501-201506  경상남도  거제시  일반용   17008   234221535  22
1   201501-201506  경상남도  거제시   합계   19327  1067355961 NaN
2   201501-201506  경상남도  거창군  일반용    4929    51653034  23
3   201501-201506  경상남도  거창군   합계    8834   220364639 NaN
4   201501-201506  경상남도  고성군  일반용    4603    48826338  14
5   201501-201506  경상남도  고성군   합계    8359   337859880 NaN
7   201501-201506  경상남도  김해시  일반용   28273   439708330  17
6   201501-201506  경상남도  김해시   합계   31456  2629676513 NaN
9   201501-201506  경상남도  남해군  일반용    4679    47374306  36
8   201501-201506  경상남도  남해군   합계    8024   132370030 NaN
10  201501-201506  경상남도  밀양시  일반용    8965    86211709  14
11  201501-201506  경상남도  밀양시   합계   15766   622731683 NaN
13  201501-201506  경상남도  사천시  일반용    8999   108647521  17
12  201501-201506  경상남도  사천시   합계   11863   652078989 NaN
14  201501-201506  경상남도  산청군  일반용    3379    30337719  20
15  201501-201506  경상남도  산청군   합계    6592   153943838 NaN
16  201501-201506  경상남도  양산시  일반용   16213   253318595  15
17  201501-201506  경상남도  양산시   합계   17460  1746146311 NaN
18  201501-201506  경상남도  의령군  일반용    2532    22129710  11
19  201501-201506  경상남도  의령군   합계    5449   206455795 NaN
21  201501-201506  경상남도  진주시  일반용   23749   304407993  23
20  201501-201506  경상남도  진주시   합계   30320  1351588275 NaN
23  201501-201506  경상남도  창녕군  일반용    5388    62748881  14
22  201501-201506  경상남도  창녕군   합계    9649   461713468 NaN
24  201501-201506  경상남도  창원시  일반용   55740   951084251  17
25  201501-201506  경상남도  창원시   합계   75376  5538300709 NaN
27  201501-201506  경상남도  통영시  일반용   10526   143596984  24
26  201501-201506  경상남도  통영시   합계   13023   596887559 NaN
29  201501-201506  경상남도  하동군  일반용    4147    41040341  25
28  201501-201506  경상남도  하동군   합계    8353   166605991 NaN
31  201501-201506  경상남도  함안군  일반용    5271    57750542   4
30  201501-201506  경상남도  함안군   합계    8548  1282832655 NaN
33  201501-201506  경상남도  함양군  일반용    3556    31272342  25
32  201501-201506  경상남도  함양군   합계    6568   126217796 NaN
34  201501-201506  경상남도  합천군  일반용    3968    39217707  20
35  201501-201506  경상남도  합천군   합계    7990   192407965 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1501-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)