In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별_전력사용량_월별_12하반기.csv', encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2012년 07 월 ~ 2012년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,인천광역시,전체(시 / 군 / 구),주택용,"670,436","295,382,310","34,706,106,897",117.5
4,201207,인천광역시,전체(시 / 군 / 구),일반용,"122,620","422,319,450","48,872,240,162",115.7
...,...,...,...,...,...,...,...,...
523,201212,인천광역시,중구,산업용,488,"53,555,413","5,607,925,534",104.7
524,201212,인천광역시,중구,심 야,"1,545","4,968,281","344,835,416",69.4
525,201212,인천광역시,중구,일반용,"9,158","73,432,909","8,186,816,144",111.5
526,201212,인천광역시,중구,주택용,"26,909","12,362,595","1,493,253,534",120.8
527,201212,인천광역시,중구,합계,"41,616","149,188,480","16,126,977,759",108.1

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,인천광역시,전체(시 / 군 / 구),주택용,"670,436","295,382,310","34,706,106,897",117.5
4,201207,인천광역시,전체(시 / 군 / 구),일반용,"122,620","422,319,450","48,872,240,162",115.7
5,201207,인천광역시,전체(시 / 군 / 구),교육용,"1,663","24,128,937","3,344,798,937",138.6
6,201207,인천광역시,전체(시 / 군 / 구),산업용,"17,094","1,057,423,323","109,202,462,877",103.3
...,...,...,...,...,...,...,...,...
523,201212,인천광역시,중구,산업용,488,"53,555,413","5,607,925,534",104.7
524,201212,인천광역시,중구,심 야,"1,545","4,968,281","344,835,416",69.4
525,201212,인천광역시,중구,일반용,"9,158","73,432,909","8,186,816,144",111.5
526,201212,인천광역시,중구,주택용,"26,909","12,362,595","1,493,253,534",120.8
527,201212,인천광역시,중구,합계,"41,616","149,188,480","16,126,977,759",108.1

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,인천광역시,전체(시 / 군 / 구),주택용,"670,436","295,382,310","34,706,106,897",117.5
4,201207,인천광역시,전체(시 / 군 / 구),일반용,"122,620","422,319,450","48,872,240,162",115.7
5,201207,인천광역시,전체(시 / 군 / 구),교육용,"1,663","24,128,937","3,344,798,937",138.6
6,201207,인천광역시,전체(시 / 군 / 구),산업용,"17,094","1,057,423,323","109,202,462,877",103.3
7,201207,인천광역시,전체(시 / 군 / 구),농사용,"18,027","8,279,776","357,576,687",43.2
...,...,...,...,...,...,...,...,...
523,201212,인천광역시,중구,산업용,488,"53,555,413","5,607,925,534",104.7
524,201212,인천광역시,중구,심 야,"1,545","4,968,281","344,835,416",69.4
525,201212,인천광역시,중구,일반용,"9,158","73,432,909","8,186,816,144",111.5
526,201212,인천광역시,중구,주택용,"26,909","12,362,595","1,493,253,534",120.8
527,201212,인천광역시,중구,합계,"41,616","149,188,480","16,126,977,759",108.1

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201207,인천광역시,전체(시 / 군 / 구),주택용,"670,436","295,382,310","34,706,106,897",117.5
4,201207,인천광역시,전체(시 / 군 / 구),일반용,"122,620","422,319,450","48,872,240,162",115.7
5,201207,인천광역시,전체(시 / 군 / 구),교육용,"1,663","24,128,937","3,344,798,937",138.6
6,201207,인천광역시,전체(시 / 군 / 구),산업용,"17,094","1,057,423,323","109,202,462,877",103.3
7,201207,인천광역시,전체(시 / 군 / 구),농사용,"18,027","8,279,776","357,576,687",43.2
8,201207,인천광역시,전체(시 / 군 / 구),가로등,"43,093","10,023,374","1,084,458,092",108.2
9,201207,인천광역시,전체(시 / 군 / 구),심 야,"19,975","12,309,628","626,070,058",50.9
10,201208,인천광역시,전체(시 / 군 / 구),주택용,"671,721","374,984,552","59,045,501,623",157.5
11,201208,인천광역시,전체(시 / 군 / 구),일반용,"122,822","486,442,903","62,307,408,754",128.1
12,201208,인천광역시,전체(시 / 군 / 구),교육용,"1,664","24,383,622","3,516,260,262",144.2
13,201208,인천광역시,전체(시 / 군 / 구),산업용,"17,169","1,025,403,341","114,948,854,037",112.1
14,201208,인천광역시,전체(시 / 군 / 구),농사용,"18,228","9,742,038","434,204,975",44.6
15,201208,인천광역시,전체(시 / 군 / 구),가로등,"43,194","10,691,410","1,127,667,643",105.5
16,201208,인천광역시,전체(시 / 군 / 구),심 야,"19,931","11,825,487","627,431,817",53.1
17,201209,인천광역시,전체(시 / 군 / 구),주택용,"673,378","315,387,486","39,678,762,150",125.8
18,201209,인천광역시,전체(시 / 군 / 구),일반용,"123,050","419,315,847","48,215,705,952",115.0
19,201209,인천광역시,전체(시 / 군 / 구),교육용,"1,664","21,595,054","2,610,069,395",120.9
20,201209,인천광역시,전체(시 / 군 / 구),산업용,"17,192","1,014,996,187","95,556,626,680",94.1
21,201209,인천광역시,전체(시 / 군 / 구),농사용,"18,386","11,996,364","542,544,105",45.2
22,201209,인천광역시,전체(시 / 군 / 구),가로등,"43,549","11,739,833","1,237,548,777",105.4
23,201209,인천광역시,전체(시 / 군 / 구),심 야,"19,846","11,270,964","597,448,498",53.0
24,201210,인천광역시,전체(시 / 군 / 구),주택용,"674,424","282,472,581","31,777,154,908",112.5
25,201210,인천광역시,전체(시 / 군 / 구),일반용,"123,080","349,674,050","37,079,529,501",106.0
26,201210,인천광역시,전체(시 / 군 / 구),교육용,"1,666","19,037,081","2,387,203,953",125.4
27,201210,인천광역시,전체(시 / 군 / 구),산업용,"17,207","1,014,021,854","91,584,618,186",90.3
28,201210,인천광역시,전체(시 / 군 / 구),농사용,"18,486","8,471,827","407,456,907",48.1
29,201210,인천광역시,전체(시 / 군 / 구),가로등,"43,662","12,839,108","1,295,692,976",100.9
30,201210,인천광역시,전체(시 / 군 / 구),심 야,"19,826","14,805,585","767,407,176",51.8
31,201211,인천광역시,전체(시 / 군 / 구),주택용,"675,249","300,982,751","36,054,743,594",119.8
32,201211,인천광역시,전체(시 / 군 / 구),일반용,"123,522","374,788,368","45,059,104,303",120.2
33,201211,인천광역시,전체(시 / 군 / 구),교육용,"1,663","27,546,767","3,466,720,794",125.8
34,201211,인천광역시,전체(시 / 군 / 구),산업용,"17,258","1,088,038,232","119,038,606,354",109.4
35,201211,인천광역시,전체(시 / 군 / 구),농사용,"25,566","13,595,340","509,788,094",37.5
36,201211,인천광역시,전체(시 / 군 / 구),가로등,"43,743","14,382,284","1,403,550,525",97.6
37,201211,인천광역시,전체(시 / 군 / 구),심 야,"19,803","31,465,544","1,844,630,215",58.6
38,201212,인천광역시,전체(시 / 군 / 구),주택용,"675,780","317,189,342","39,674,781,090",125.1
39,201212,인천광역시,전체(시 / 군 / 구),일반용,"124,024","458,908,479","56,051,260,987",122.1
40,201212,인천광역시,전체(시 / 군 / 구),교육용,"1,666","43,187,255","4,778,687,785",110.7
41,201212,인천광역시,전체(시 / 군 / 구),산업용,"17,298","1,157,233,532","122,684,691,279",106.0
42,201212,인천광역시,전체(시 / 군 / 구),농사용,"22,905","10,553,454","433,891,362",41.1
43,201212,인천광역시,전체(시 / 군 / 구),가로등,"43,972","15,194,201","1,460,849,702",96.1
44,201212,인천광역시,전체(시 / 군 / 구),심 야,"19,780","54,058,717","3,704,200,770",68.5
45,합계,합계,합계,합계,"5,395,282","11,188,088,238","1,230,104,318,839",109.9

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_5976\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201207  인천광역시  일반용  122,620   422,319,450
11  201208  인천광역시  일반용  122,822   486,442,903
18  201209  인천광역시  일반용  123,050   419,315,847
25  201210  인천광역시  일반용  123,080   349,674,050
32  201211  인천광역시  일반용  123,522   374,788,368
39  201212  인천광역시  일반용  124,024   458,908,479

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201207  인천광역시  강화군  일반용   6,572   10,180,520
133  201208  인천광역시  강화군  일반용   6,576   12,879,858
213  201209  인천광역시  강화군  일반용   6,607   11,485,242
293  201210  인천광역시  강화군  일반용   6,609    9,452,453
373  201211  인천광역시  강화군  일반용   6,640   11,179,321
453  201212  인천광역시  강화군  일반용   6,683   14,805,777
61   201207  인천광역시  계양구  일반용  11,988   38,077,183
141  201208  인천광역시  계양구  일반용  12,024   43,751,384
221  201209  인천광역시  계양구  일반용  12,020   37,594,488
301  201210  인천광역시  계양구  일반용  12,015   31,001,400
381  201211  인천광역시  계양구  일반용  12,065   32,925,478
461  201212  인천광역시  계양구  일반용  12,126   40,517,221
69   201207  인천광역시   남구  일반용  20,345   49,957,993
149  201208  인천광역시   남구  일반용  20,339   58,638,189
229  201209  인천광역시   남구  일반용  20,380   51,522,823
309  201210  인천광역시   남구  일반용  20,404   41,272,217
389  201211  인천광역시   남구  일반용  20,456   43,926,405
469  201212  인천광역시   남구  일반용  20,503   53,969,786
77   201207  인천광역시  남동구  일반용  20,191   71,807,550
157  201208  인천광역시  남동구  일반용  20,231   83,265,987
237  201209  인천광역시  남동구  일반용  20,225   71,166,817
317  201210  인천광역시  남동구  일반용  20,219   58,074,380
397  201211  인천광역시  남동구  일반용  20,266   62,100,668
477  201212  인천광역시  남동구  일반용  20,365   76,091,183
85   201207  인천광역시   동구  일반용   3,734    9,064,870
165  201208  인천광역시   동구  일반용   3,726   10,365,952
245  201209  인천광역시   동구  일반용   3,733    8,937,415
325  201210  인천광역시   동구  일반용   3,731    7,571,051
405  201211  인천광역시   동구  일반용   3,742    8,737,441
485  201212  인천광역시   동구  일반용   3,745   10,905,756
93   201207  인천광역시  부평구  일반용  21,806   67,822,255
173  201208  인천광역시  부평구  일반용  21,796   76,834,951
253  201209  인천광역시  부평구  일반용  21,795   65,884,436
333  201210  인천광역시  부평구  일반용  21,769   53,183,270
413  201211  인천광역시  부평구  일반용  21,829   56,346,349
493  201212  인천광역시  부평구  일반용  21,914   69,535,803
101  201207  인천광역시   서구  일반용  18,221   52,961,344
181  201208  인천광역시   서구  일반용  18,244   61,789,327
261  201209  인천광역시   서구  일반용  18,361   54,060,986
341  201210  인천광역시   서구  일반용  18,326   45,058,281
421  201211  인천광역시   서구  일반용  18,455   50,989,934
501  201212  인천광역시   서구  일반용  18,586   63,793,835
109  201207  인천광역시  연수구  일반용   7,638   41,372,368
189  201208  인천광역시  연수구  일반용   7,656   48,395,026
269  201209  인천광역시  연수구  일반용   7,659   41,046,781
349  201210  인천광역시  연수구  일반용   7,673   35,809,126
429  201211  인천광역시  연수구  일반용   7,685   37,584,476
509  201212  인천광역시  연수구  일반용   7,692   46,929,804
117  201207  인천광역시  옹진군  일반용   3,127    5,899,742
197  201208  인천광역시  옹진군  일반용   3,173    7,532,038
277  201209  인천광역시  옹진군  일반용   3,191    6,755,437
357  201210  인천광역시  옹진군  일반용   3,213    5,736,229
437  201211  인천광역시  옹진군  일반용   3,246    7,106,989
517  201212  인천광역시  옹진군  일반용   3,252    8,926,405
125  201207  인천광역시   중구  일반용   8,998   75,175,625
205  201208  인천광역시   중구  일반용   9,057   82,990,191
285  201209  인천광역시   중구  일반용   9,079   70,861,422
365  201210  인천광역시   중구  일반용   9,121   62,515,643
445  201211  인천광역시   중구  일반용   9,138   63,891,307
525  201212  인천광역시   중구  일반용   9,158   73,432,909

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201207  인천광역시  강화군   합계   60,114    29,317,057
135  201208  인천광역시  강화군   합계   60,318    34,719,594
215  201209  인천광역시  강화군   합계   60,539    34,923,330
295  201210  인천광역시  강화군   합계   60,652    31,797,355
375  201211  인천광역시  강화군   합계   66,037    44,051,878
455  201212  인천광역시  강화군   합계   64,879    56,181,592
63   201207  인천광역시  계양구   합계   95,406   107,125,909
143  201208  인천광역시  계양구   합계   95,508   122,677,014
223  201209  인천광역시  계양구   합계   95,675   107,938,641
303  201210  인천광역시  계양구   합계   95,722    96,110,713
383  201211  인천광역시  계양구   합계   96,032   104,698,094
463  201212  인천광역시  계양구   합계   95,915   120,614,801
71   201207  인천광역시   남구   합계  178,034   180,031,346
151  201208  인천광역시   남구   합계  178,145   198,065,426
231  201209  인천광역시   남구   합계  178,662   178,283,529
311  201210  인천광역시   남구   합계  178,887   160,338,459
391  201211  인천광역시   남구   합계  179,044   176,135,149
471  201212  인천광역시   남구   합계  179,117   197,070,606
79   201207  인천광역시  남동구   합계  135,153   326,093,163
159  201208  인천광역시  남동구   합계  135,484   345,381,164
239  201209  인천광역시  남동구   합계  135,793   321,914,890
319  201210  인천광역시  남동구   합계  135,902   291,166,391
399  201211  인천광역시  남동구   합계  136,058   324,646,427
479  201212  인천광역시  남동구   합계  136,275   361,758,907
87   201207  인천광역시   동구   합계   23,779   334,814,751
167  201208  인천광역시   동구   합계   23,770   325,401,875
247  201209  인천광역시   동구   합계   23,838   321,618,479
327  201210  인천광역시   동구   합계   23,839   342,006,991
407  201211  인천광역시   동구   합계   23,870   354,366,494
487  201212  인천광역시   동구   합계   23,841   368,219,606
95   201207  인천광역시  부평구   합계  157,118   208,265,322
175  201208  인천광역시  부평구   합계  157,251   231,908,442
255  201209  인천광역시  부평구   합계  157,484   205,454,822
335  201210  인천광역시  부평구   합계  157,593   185,400,853
415  201211  인천광역시  부평구   합계  157,708   202,131,220
495  201212  인천광역시  부평구   합계  157,862   228,895,367
103  201207  인천광역시   서구   합계  130,896   355,518,053
183  201208  인천광역시   서구   합계  131,442   365,494,444
263  201209  인천광역시   서구   합계  132,034   353,082,803
343  201210  인천광역시   서구   합계  132,363   333,080,610
423  201211  인천광역시   서구   합계  133,041   362,901,703
503  201212  인천광역시   서구   합계  133,327   397,638,364
111  201207  인천광역시  연수구   합계   53,564   132,705,556
191  201208  인천광역시  연수구   합계   53,676   154,655,792
271  201209  인천광역시  연수구   합계   53,710   131,619,145
351  201210  인천광역시  연수구   합계   53,786   121,890,936
431  201211  인천광역시  연수구   합계   53,815   131,401,376
511  201212  인천광역시  연수구   합계   53,868   156,548,931
119  201207  인천광역시  옹진군   합계   17,778    12,683,651
199  201208  인천광역시  옹진군   합계   17,914    12,362,018
279  201209  인천광역시  옹진군   합계   17,984    12,038,150
359  201210  인천광역시  옹진군   합계   18,085    11,009,225
439  201211  인천광역시  옹진군   합계   19,207    16,986,822
519  201212  인천광역시  옹진군   합계   18,725    20,208,326
127  201207  인천광역시   중구   합계   41,066   143,311,990
207  201208  인천광역시   중구   합계   41,221   152,807,584
287  201209  인천광역시   중구   합계   41,346   139,427,946
367  201210  인천광역시   중구   합계   41,522   128,520,553
447  201211  인천광역시   중구   합계   41,992   133,480,123
527  201212  인천광역시   중구   합계   41,616   149,188,480

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[29317057, 34719594, 34923330, 31797355, 44051878, 56181592]
[107125909, 122677014, 107938641, 96110713, 104698094, 120614801]
[180031346, 198065426, 178283529, 160338459, 176135149, 197070606]
[326093163, 345381164, 321914890, 291166391, 324646427, 361758907]
[334814751, 325401875, 321618479, 342006991, 354366494, 368219606]
[208265322, 231908442, 205454822, 185400853, 202131220, 228895367]
[355518053, 365494444, 353082803, 333080610, 362901703, 397638364]
[132705556, 154655792, 131619145, 121890936, 131401376, 156548931]
[12683651, 12362018, 12038150, 11009225, 16986822, 20208326]
[143311990, 152807584, 139427946, 128520553, 133480123, 149188480]
인천광역시 지역별 합계 :  [230990806, 659165172, 1089924515, 1970960942, 2046428196, 1262056026, 2167715977, 828821736, 85288192, 846736676]
인천광역시 고객호수 평균:  [10348, 15951, 29774, 22629, 3970, 26250, 22030, 8956, 3047, 6910]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\1519304569.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201207  인천광역시  강화군   합계  60,114   29,317,057
1          201208  인천광역시  강화군   합계  60,318   34,719,594
2          201209  인천광역시  강화군   합계  60,539   34,923,330
3          201210  인천광역시  강화군   합계  60,652   31,797,355
4          201211  인천광역시  강화군   합계  66,037   44,051,878
..            ...    ...  ...  ...      ...          ...
65  201207-201212  인천광역시  부평구   합계    26250   1262056026
66  201207-201212  인천광역시   서구   합계    22030   2167715977
67  201207-201212  인천광역시  연수구   합계     8956    828821736
68  201207-201212  인천광역시  옹진군   합계     3047     85288192
69  201207-201212  인천광역시   중구   합계     6910    846736676

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201207-201212']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201207-201212  인천광역시  강화군   합계   10348   230990806
61  201207-201212  인천광역시  계양구   합계   15951   659165172
62  201207-201212  인천광역시   남구   합계   29774  1089924515
63  201207-201212  인천광역시  남동구   합계   22629  1970960942
64  201207-201212  인천광역시   동구   합계    3970  2046428196
65  201207-201212  인천광역시  부평구   합계   26250  1262056026
66  201207-201212  인천광역시   서구   합계   22030  2167715977
67  201207-201212  인천광역시  연수구   합계    8956   828821736
68  201207-201212  인천광역시  옹진군   합계    3047    85288192
69  201207-201212  인천광역시   중구   합계    6910   846736676

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201207  인천광역시  강화군  일반용   6,572   10,180,520
133  201208  인천광역시  강화군  일반용   6,576   12,879,858
213  201209  인천광역시  강화군  일반용   6,607   11,485,242
293  201210  인천광역시  강화군  일반용   6,609    9,452,453
373  201211  인천광역시  강화군  일반용   6,640   11,179,321
453  201212  인천광역시  강화군  일반용   6,683   14,805,777
61   201207  인천광역시  계양구  일반용  11,988   38,077,183
141  201208  인천광역시  계양구  일반용  12,024   43,751,384
221  201209  인천광역시  계양구  일반용  12,020   37,594,488
301  201210  인천광역시  계양구  일반용  12,015   31,001,400
381  201211  인천광역시  계양구  일반용  12,065   32,925,478
461  201212  인천광역시  계양구  일반용  12,126   40,517,221
69   201207  인천광역시   남구  일반용  20,345   49,957,993
149  201208  인천광역시   남구  일반용  20,339   58,638,189
229  201209  인천광역시   남구  일반용  20,380   51,522,823
309  201210  인천광역시   남구  일반용  20,404   41,272,217
389  201211  인천광역시   남구  일반용  20,456   43,926,405
469  201212  인천광역시   남구  일반용  20,503   53,969,786
77   201207  인천광역시  남동구  일반용  20,191   71,807,550
157  201208  인천광역시  남동구  일반용  20,231   83,265,987
237  201209  인천광역시  남동구  일반용  20,225   71,166,817
317  201210  인천광역시  남동구  일반용  20,219   58,074,380
397  201211  인천광역시  남동구  일반용  20,266   62,100,668
477  201212  인천광역시  남동구  일반용  20,365   76,091,183
85   201207  인천광역시   동구  일반용   3,734    9,064,870
165  201208  인천광역시   동구  일반용   3,726   10,365,952
245  201209  인천광역시   동구  일반용   3,733    8,937,415
325  201210  인천광역시   동구  일반용   3,731    7,571,051
405  201211  인천광역시   동구  일반용   3,742    8,737,441
485  201212  인천광역시   동구  일반용   3,745   10,905,756
93   201207  인천광역시  부평구  일반용  21,806   67,822,255
173  201208  인천광역시  부평구  일반용  21,796   76,834,951
253  201209  인천광역시  부평구  일반용  21,795   65,884,436
333  201210  인천광역시  부평구  일반용  21,769   53,183,270
413  201211  인천광역시  부평구  일반용  21,829   56,346,349
493  201212  인천광역시  부평구  일반용  21,914   69,535,803
101  201207  인천광역시   서구  일반용  18,221   52,961,344
181  201208  인천광역시   서구  일반용  18,244   61,789,327
261  201209  인천광역시   서구  일반용  18,361   54,060,986
341  201210  인천광역시   서구  일반용  18,326   45,058,281
421  201211  인천광역시   서구  일반용  18,455   50,989,934
501  201212  인천광역시   서구  일반용  18,586   63,793,835
109  201207  인천광역시  연수구  일반용   7,638   41,372,368
189  201208  인천광역시  연수구  일반용   7,656   48,395,026
269  201209  인천광역시  연수구  일반용   7,659   41,046,781
349  201210  인천광역시  연수구  일반용   7,673   35,809,126
429  201211  인천광역시  연수구  일반용   7,685   37,584,476
509  201212  인천광역시  연수구  일반용   7,692   46,929,804
117  201207  인천광역시  옹진군  일반용   3,127    5,899,742
197  201208  인천광역시  옹진군  일반용   3,173    7,532,038
277  201209  인천광역시  옹진군  일반용   3,191    6,755,437
357  201210  인천광역시  옹진군  일반용   3,213    5,736,229
437  201211  인천광역시  옹진군  일반용   3,246    7,106,989
517  201212  인천광역시  옹진군  일반용   3,252    8,926,405
125  201207  인천광역시   중구  일반용   8,998   75,175,625
205  201208  인천광역시   중구  일반용   9,057   82,990,191
285  201209  인천광역시   중구  일반용   9,079   70,861,422
365  201210  인천광역시   중구  일반용   9,121   62,515,643
445  201211  인천광역시   중구  일반용   9,138   63,891,307
525  201212  인천광역시   중구  일반용   9,158   73,432,909

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[10180520, 12879858, 11485242, 9452453, 11179321, 14805777]
[38077183, 43751384, 37594488, 31001400, 32925478, 40517221]
[49957993, 58638189, 51522823, 41272217, 43926405, 53969786]
[71807550, 83265987, 71166817, 58074380, 62100668, 76091183]
[9064870, 10365952, 8937415, 7571051, 8737441, 10905756]
[67822255, 76834951, 65884436, 53183270, 56346349, 69535803]
[52961344, 61789327, 54060986, 45058281, 50989934, 63793835]
[41372368, 48395026, 41046781, 35809126, 37584476, 46929804]
[5899742, 7532038, 6755437, 5736229, 7106989, 8926405]
[75175625, 82990191, 70861422, 62515643, 63891307, 73432909]
인천광역시 지역별 일반용 합계 :  [69983171, 223867154, 299287413, 422506585, 55582485, 389607064, 328653707, 251137581, 41956840, 428867097]
인천광역시 고객호수 평균:  [6614, 12039, 20404, 20249, 3735, 21818, 18365, 7667, 3200, 9091]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_5976\2741594792.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201207-201212'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201207  인천광역시  강화군  일반용  6,572   10,180,520
1          201208  인천광역시  강화군  일반용  6,576   12,879,858
2          201209  인천광역시  강화군  일반용  6,607   11,485,242
3          201210  인천광역시  강화군  일반용  6,609    9,452,453
4          201211  인천광역시  강화군  일반용  6,640   11,179,321
..            ...    ...  ...  ...     ...          ...
65  201207-201212  인천광역시  부평구  일반용   21818    389607064
66  201207-201212  인천광역시   서구  일반용   18365    328653707
67  201207-201212  인천광역시  연수구  일반용    7667    251137581
68  201207-201212  인천광역시  옹진군  일반용    3200     41956840
69  201207-201212  인천광역시   중구  일반용    9091    428867097

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201207-201212']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201207-201212  인천광역시  강화군  일반용    6614   69983171
61  201207-201212  인천광역시  계양구  일반용   12039  223867154
62  201207-201212  인천광역시   남구  일반용   20404  299287413
63  201207-201212  인천광역시  남동구  일반용   20249  422506585
64  201207-201212  인천광역시   동구  일반용    3735   55582485
65  201207-201212  인천광역시  부평구  일반용   21818  389607064
66  201207-201212  인천광역시   서구  일반용   18365  328653707
67  201207-201212  인천광역시  연수구  일반용    7667  251137581
68  201207-201212  인천광역시  옹진군  일반용    3200   41956840
69  201207-201212  인천광역시   중구  일반용    9091  428867097

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201207-201212  인천광역시  강화군  일반용    6614    69983171
60  201207-201212  인천광역시  강화군   합계   10348   230990806
61  201207-201212  인천광역시  계양구  일반용   12039   223867154
61  201207-201212  인천광역시  계양구   합계   15951   659165172
62  201207-201212  인천광역시   남구  일반용   20404   299287413
62  201207-201212  인천광역시   남구   합계   29774  1089924515
63  201207-201212  인천광역시  남동구  일반용   20249   422506585
63  201207-201212  인천광역시  남동구   합계   22629  1970960942
64  201207-201212  인천광역시   동구  일반용    3735    55582485
64  201207-201212  인천광역시   동구   합계    3970  2046428196
65  201207-201212  인천광역시  부평구  일반용   21818   389607064
65  201207-201212  인천광역시  부평구   합계   26250  1262056026
66  201207-201212  인천광역시   서구  일반용   18365   328653707
66  201207-201212  인천광역시   서구   합계   22030  2167715977
67  201207-201212  인천광역시  연수구   합계    8956   828821736
67  201207-201212  인천광역시  연수구  일반용    7667   251137581
68  201207-201212  인천광역시  옹진군   합계    3047    85288192
68  201207-201212  인천광역시  옹진군  일반용    3200    41956840
69  201207-201212  인천광역시   중구  일반용    9091   428867097
69  201207-201212  인천광역시   중구   합계    6910   846736676

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[69983171,
 223867154,
 299287413,
 422506585,
 55582485,
 389607064,
 328653707,
 251137581,
 41956840,
 428867097]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[230990806,
 659165172,
 1089924515,
 1970960942,
 2046428196,
 1262056026,
 2167715977,
 828821736,
 85288192,
 846736676]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[30.3, 33.96, 27.46, 21.44, 2.72, 30.87, 15.16, 30.3, 49.19, 50.65]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   30
1   34
2   27
3   21
4    3
5   31
6   15
7   30
8   49
9   51
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  30
1  계양구  일반용  34
2   남구  일반용  27
3  남동구  일반용  21
4   동구  일반용   3
5  부평구  일반용  31
6   서구  일반용  15
7  연수구  일반용  30
8  옹진군  일반용  49
9   중구  일반용  51

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201207-201212  인천광역시  강화군  일반용    6614    69983171  30
1   201207-201212  인천광역시  강화군   합계   10348   230990806 NaN
2   201207-201212  인천광역시  계양구  일반용   12039   223867154  34
3   201207-201212  인천광역시  계양구   합계   15951   659165172 NaN
4   201207-201212  인천광역시   남구  일반용   20404   299287413  27
5   201207-201212  인천광역시   남구   합계   29774  1089924515 NaN
6   201207-201212  인천광역시  남동구  일반용   20249   422506585  21
7   201207-201212  인천광역시  남동구   합계   22629  1970960942 NaN
8   201207-201212  인천광역시   동구  일반용    3735    55582485   3
9   201207-201212  인천광역시   동구   합계    3970  2046428196 NaN
10  201207-201212  인천광역시  부평구  일반용   21818   389607064  31
11  201207-201212  인천광역시  부평구   합계   26250  1262056026 NaN
12  201207-201212  인천광역시   서구  일반용   18365   328653707  15
13  201207-201212  인천광역시   서구   합계   22030  2167715977 NaN
15  201207-201212  인천광역시  연수구  일반용    7667   251137581  30
14  201207-201212  인천광역시  연수구   합계    8956   828821736 NaN
17  201207-201212  인천광역시  옹진군  일반용    3200    41956840  49
16  201207-201212  인천광역시  옹진군   합계    3047    85288192 NaN
18  201207-201212  인천광역시   중구  일반용    9091   428867097  51
19  201207-201212  인천광역시   중구   합계    6910   846736676 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1207-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)