In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('인천광역시_계약종별_전력사용량_월별_12상반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 인천광역시, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2012년 01 월 ~ 2012년 06월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,인천광역시,전체(시 / 군 / 구),주택용,"662,914","324,372,831","42,069,256,183",129.7
4,201201,인천광역시,전체(시 / 군 / 구),일반용,"121,876","498,914,126","40,229,596,931",80.6
...,...,...,...,...,...,...,...,...
522,201206,인천광역시,중구,산업용,466,"51,123,826","4,209,640,444",82.3
523,201206,인천광역시,중구,심 야,"1,583","1,735,671","92,620,770",53.4
524,201206,인천광역시,중구,일반용,"8,986","68,044,920","5,844,497,648",85.9
525,201206,인천광역시,중구,주택용,"26,534","9,038,761","1,005,441,217",111.2
526,201206,인천광역시,중구,합계,"40,931","132,976,565","11,462,670,158",86.2

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,인천광역시,전체(시 / 군 / 구),주택용,"662,914","324,372,831","42,069,256,183",129.7
4,201201,인천광역시,전체(시 / 군 / 구),일반용,"121,876","498,914,126","40,229,596,931",80.6
5,201201,인천광역시,전체(시 / 군 / 구),교육용,"1,635","32,113,381","3,482,211,965",108.4
6,201201,인천광역시,전체(시 / 군 / 구),산업용,"16,939","1,123,990,657","100,598,052,858",89.5
...,...,...,...,...,...,...,...,...
522,201206,인천광역시,중구,산업용,466,"51,123,826","4,209,640,444",82.3
523,201206,인천광역시,중구,심 야,"1,583","1,735,671","92,620,770",53.4
524,201206,인천광역시,중구,일반용,"8,986","68,044,920","5,844,497,648",85.9
525,201206,인천광역시,중구,주택용,"26,534","9,038,761","1,005,441,217",111.2
526,201206,인천광역시,중구,합계,"40,931","132,976,565","11,462,670,158",86.2

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,인천광역시,전체(시 / 군 / 구),주택용,"662,914","324,372,831","42,069,256,183",129.7
4,201201,인천광역시,전체(시 / 군 / 구),일반용,"121,876","498,914,126","40,229,596,931",80.6
5,201201,인천광역시,전체(시 / 군 / 구),교육용,"1,635","32,113,381","3,482,211,965",108.4
6,201201,인천광역시,전체(시 / 군 / 구),산업용,"16,939","1,123,990,657","100,598,052,858",89.5
7,201201,인천광역시,전체(시 / 군 / 구),농사용,"17,401","7,594,893","345,792,991",45.5
...,...,...,...,...,...,...,...,...
522,201206,인천광역시,중구,산업용,466,"51,123,826","4,209,640,444",82.3
523,201206,인천광역시,중구,심 야,"1,583","1,735,671","92,620,770",53.4
524,201206,인천광역시,중구,일반용,"8,986","68,044,920","5,844,497,648",85.9
525,201206,인천광역시,중구,주택용,"26,534","9,038,761","1,005,441,217",111.2
526,201206,인천광역시,중구,합계,"40,931","132,976,565","11,462,670,158",86.2

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201201,인천광역시,전체(시 / 군 / 구),주택용,"662,914","324,372,831","42,069,256,183",129.7
4,201201,인천광역시,전체(시 / 군 / 구),일반용,"121,876","498,914,126","40,229,596,931",80.6
5,201201,인천광역시,전체(시 / 군 / 구),교육용,"1,635","32,113,381","3,482,211,965",108.4
6,201201,인천광역시,전체(시 / 군 / 구),산업용,"16,939","1,123,990,657","100,598,052,858",89.5
7,201201,인천광역시,전체(시 / 군 / 구),농사용,"17,401","7,594,893","345,792,991",45.5
8,201201,인천광역시,전체(시 / 군 / 구),가로등,"41,797","15,129,259","1,386,157,690",91.6
9,201201,인천광역시,전체(시 / 군 / 구),심 야,"20,315","68,077,200","4,443,120,988",65.3
10,201202,인천광역시,전체(시 / 군 / 구),주택용,"664,166","326,771,981","42,496,169,373",130.0
11,201202,인천광역시,전체(시 / 군 / 구),일반용,"121,883","489,619,376","56,181,625,655",114.7
12,201202,인천광역시,전체(시 / 군 / 구),교육용,"1,639","35,241,948","3,942,950,097",111.9
13,201202,인천광역시,전체(시 / 군 / 구),산업용,"16,945","1,126,149,159","115,094,786,119",102.2
14,201202,인천광역시,전체(시 / 군 / 구),농사용,"17,377","7,648,116","351,324,342",45.9
15,201202,인천광역시,전체(시 / 군 / 구),가로등,"42,152","14,412,759","1,363,811,624",94.6
16,201202,인천광역시,전체(시 / 군 / 구),심 야,"20,256","70,633,107","4,612,442,619",65.3
17,201203,인천광역시,전체(시 / 군 / 구),주택용,"665,458","294,381,137","34,362,846,019",116.7
18,201203,인천광역시,전체(시 / 군 / 구),일반용,"121,920","428,232,835","44,410,748,086",103.7
19,201203,인천광역시,전체(시 / 군 / 구),교육용,"1,643","34,145,436","3,194,732,093",93.6
20,201203,인천광역시,전체(시 / 군 / 구),산업용,"16,991","1,104,673,439","94,104,900,961",85.2
21,201203,인천광역시,전체(시 / 군 / 구),농사용,"24,351","7,261,295","336,496,619",46.3
22,201203,인천광역시,전체(시 / 군 / 구),가로등,"42,346","13,122,955","1,264,475,218",96.4
23,201203,인천광역시,전체(시 / 군 / 구),심 야,"20,205","56,385,796","3,277,942,804",58.1
24,201204,인천광역시,전체(시 / 군 / 구),주택용,"666,614","300,346,875","35,589,338,098",118.5
25,201204,인천광역시,전체(시 / 군 / 구),일반용,"122,078","395,936,909","38,158,548,853",96.4
26,201204,인천광역시,전체(시 / 군 / 구),교육용,"1,652","23,862,454","2,636,415,057",110.5
27,201204,인천광역시,전체(시 / 군 / 구),산업용,"17,024","1,061,674,140","88,546,920,171",83.4
28,201204,인천광역시,전체(시 / 군 / 구),농사용,"21,918","7,011,282","328,374,256",46.8
29,201204,인천광역시,전체(시 / 군 / 구),가로등,"42,396","12,394,941","1,241,267,400",100.1
30,201204,인천광역시,전체(시 / 군 / 구),심 야,"20,162","46,155,991","2,206,525,023",47.8
31,201205,인천광역시,전체(시 / 군 / 구),주택용,"667,519","276,925,412","30,703,771,410",110.9
32,201205,인천광역시,전체(시 / 군 / 구),일반용,"122,181","357,837,034","35,764,641,477",99.9
33,201205,인천광역시,전체(시 / 군 / 구),교육용,"1,656","19,791,220","2,402,060,169",121.4
34,201205,인천광역시,전체(시 / 군 / 구),산업용,"17,054","1,060,069,673","88,511,823,130",83.5
35,201205,인천광역시,전체(시 / 군 / 구),농사용,"17,701","6,610,771","309,894,623",46.9
36,201205,인천광역시,전체(시 / 군 / 구),가로등,"42,543","11,039,641","1,153,461,879",104.5
37,201205,인천광역시,전체(시 / 군 / 구),심 야,"20,110","25,453,655","1,227,957,666",48.2
38,201206,인천광역시,전체(시 / 군 / 구),주택용,"668,768","283,471,937","31,969,291,893",112.8
39,201206,인천광역시,전체(시 / 군 / 구),일반용,"122,312","381,498,853","37,303,269,079",97.8
40,201206,인천광역시,전체(시 / 군 / 구),교육용,"1,658","22,758,921","2,544,224,645",111.8
41,201206,인천광역시,전체(시 / 군 / 구),산업용,"17,078","1,057,856,146","88,843,636,918",84.0
42,201206,인천광역시,전체(시 / 군 / 구),농사용,"17,861","7,487,215","339,839,493",45.4
43,201206,인천광역시,전체(시 / 군 / 구),가로등,"42,841","10,566,948","1,133,677,266",107.3
44,201206,인천광역시,전체(시 / 군 / 구),심 야,"20,042","16,236,311","806,817,299",49.7
45,합계,합계,합계,합계,"5,331,377","11,463,858,015","1,089,271,197,040",95

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_12688\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월     시구 계약구분   고객호수(호)      사용량(kWh)
4   201201  인천광역시  일반용  121,876   498,914,126
11  201202  인천광역시  일반용  121,883   489,619,376
18  201203  인천광역시  일반용  121,920   428,232,835
25  201204  인천광역시  일반용  122,078   395,936,909
32  201205  인천광역시  일반용  122,181   357,837,034
39  201206  인천광역시  일반용  122,312   381,498,853

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201201  인천광역시  강화군  일반용   6,482   16,247,775
132  201202  인천광역시  강화군  일반용   6,497   16,283,821
212  201203  인천광역시  강화군  일반용   6,519   13,881,789
292  201204  인천광역시  강화군  일반용   6,521   12,453,946
372  201205  인천광역시  강화군  일반용   6,527   10,037,127
452  201206  인천광역시  강화군  일반용   6,530   10,044,633
61   201201  인천광역시  계양구  일반용  11,973   46,301,482
140  201202  인천광역시  계양구  일반용  11,976   44,930,362
220  201203  인천광역시  계양구  일반용  11,970   38,711,865
300  201204  인천광역시  계양구  일반용  11,984   35,904,583
380  201205  인천광역시  계양구  일반용  11,987   32,680,206
460  201206  인천광역시  계양구  일반용  11,978   34,714,775
69   201201  인천광역시   남구  일반용  20,355   60,279,399
148  201202  인천광역시   남구  일반용  20,356   60,911,186
228  201203  인천광역시   남구  일반용  20,362   52,149,820
308  201204  인천광역시   남구  일반용  20,376   48,958,762
388  201205  인천광역시   남구  일반용  20,360   42,470,432
468  201206  인천광역시   남구  일반용  20,327   44,686,574
77   201201  인천광역시  남동구  일반용  20,147   83,660,584
156  201202  인천광역시  남동구  일반용  20,104   82,497,324
236  201203  인천광역시  남동구  일반용  20,104   71,161,297
316  201204  인천광역시  남동구  일반용  20,119   66,225,586
396  201205  인천광역시  남동구  일반용  20,154   60,358,475
476  201206  인천광역시  남동구  일반용  20,145   64,641,784
84   201201  인천광역시   동구  일반용   3,691   11,294,723
164  201202  인천광역시   동구  일반용   3,701   11,295,341
244  201203  인천광역시   동구  일반용   3,695    9,647,561
324  201204  인천광역시   동구  일반용   3,708    8,727,849
404  201205  인천광역시   동구  일반용   3,714    7,529,711
484  201206  인천광역시   동구  일반용   3,712    8,092,382
92   201201  인천광역시  부평구  일반용  21,815   78,539,207
172  201202  인천광역시  부평구  일반용  21,836   76,889,958
252  201203  인천광역시  부평구  일반용  21,845   66,363,355
332  201204  인천광역시  부평구  일반용  21,822   61,186,040
412  201205  인천광역시  부평구  일반용  21,744   55,708,868
492  201206  인천광역시  부평구  일반용  21,768   60,838,717
100  201201  인천광역시   서구  일반용  17,863   68,459,230
180  201202  인천광역시   서구  일반용  17,851   67,366,098
260  201203  인천광역시   서구  일반용  17,877   57,894,961
340  201204  인천광역시   서구  일반용  17,956   53,415,320
420  201205  인천광역시   서구  일반용  18,020   45,807,877
500  201206  인천광역시   서구  일반용  18,141   48,168,492
108  201201  인천광역시  연수구  일반용   7,633   48,097,690
188  201202  인천광역시  연수구  일반용   7,639   46,308,035
268  201203  인천광역시  연수구  일반용   7,630   40,991,340
348  201204  인천광역시  연수구  일반용   7,641   37,739,247
428  201205  인천광역시  연수구  일반용   7,646   34,005,379
508  201206  인천광역시  연수구  일반용   7,646   36,312,970
116  201201  인천광역시  옹진군  일반용   2,938    8,786,020
196  201202  인천광역시  옹진군  일반용   2,950    8,987,042
276  201203  인천광역시  옹진군  일반용   2,962    7,841,410
356  201204  인천광역시  옹진군  일반용   2,993    7,459,657
436  201205  인천광역시  옹진군  일반용   3,039    6,125,455
516  201206  인천광역시  옹진군  일반용   3,079    5,953,606
124  201201  인천광역시   중구  일반용   8,979   77,248,016
204  201202  인천광역시   중구  일반용   8,973   74,150,209
284  201203  인천광역시   중구  일반용   8,956   69,589,437
364  201204  인천광역시   중구  일반용   8,958   63,865,919
444  201205  인천광역시   중구  일반용   8,990   63,113,504
524  201206  인천광역시   중구  일반용   8,986   68,044,920

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'인천광역시'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강화군', '계양구', '남구', '남동구', '동구', '부평구', '서구', '연수구', '옹진군', '중구']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월     시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201201  인천광역시  강화군   합계   59,107    61,078,035
134  201202  인천광역시  강화군   합계   59,136    62,110,203
214  201203  인천광역시  강화군   합계   64,388    52,526,603
294  201204  인천광역시  강화군   합계   63,284    46,672,280
374  201205  인천광역시  강화군   합계   59,490    35,061,609
454  201206  인천광역시  강화군   합계   59,902    31,935,674
63   201201  인천광역시  계양구   합계   94,875   127,145,423
142  201202  인천광역시  계양구   합계   94,938   124,822,394
222  201203  인천광역시  계양구   합계   95,181   112,933,812
302  201204  인천광역시  계양구   합계   95,124   106,962,528
382  201205  인천광역시  계양구   합계   95,222    97,872,660
462  201206  인천광역시  계양구   합계   95,330   100,996,442
71   201201  인천광역시   남구   합계  176,976   205,364,773
150  201202  인천광역시   남구   합계  177,217   207,547,806
230  201203  인천광역시   남구   합계  177,533   191,543,944
310  201204  인천광역시   남구   합계  177,688   181,348,498
390  201205  인천광역시   남구   합계  177,685   167,148,712
470  201206  인천광역시   남구   합계  177,623   169,267,534
79   201201  인천광역시  남동구   합계  134,039   372,617,188
158  201202  인천광역시  남동구   합계  134,196   372,919,457
238  201203  인천광역시  남동구   합계  134,417   343,254,488
318  201204  인천광역시  남동구   합계  134,569   325,119,454
398  201205  인천광역시  남동구   합계  134,805   302,515,749
478  201206  인천광역시  남동구   합계  134,952   310,672,580
86   201201  인천광역시   동구   합계   23,649   348,886,462
166  201202  인천광역시   동구   합계   23,674   359,503,658
246  201203  인천광역시   동구   합계   23,676   356,206,971
326  201204  인천광역시   동구   합계   23,704   350,445,791
406  201205  인천광역시   동구   합계   23,693   367,010,387
486  201206  인천광역시   동구   합계   23,688   357,436,891
94   201201  인천광역시  부평구   합계  155,557   234,632,833
174  201202  인천광역시  부평구   합계  155,624   234,407,415
254  201203  인천광역시  부평구   합계  156,017   214,058,151
334  201204  인천광역시  부평구   합계  156,252   201,670,873
414  201205  인천광역시  부평구   합계  156,418   187,384,672
494  201206  인천광역시  부평구   합계  156,800   197,264,790
102  201201  인천광역시   서구   합계  127,419   403,255,623
182  201202  인천광역시   서구   합계  128,250   397,505,773
262  201203  인천광역시   서구   합계  128,828   378,734,887
342  201204  인천광역시   서구   합계  129,108   362,149,032
422  201205  인천광역시   서구   합계  129,571   339,707,033
502  201206  인천광역시   서구   합계  130,133   344,550,074
110  201201  인천광역시  연수구   합계   53,315   149,701,314
190  201202  인천광역시  연수구   합계   53,369   147,405,337
270  201203  인천광역시  연수구   합계   53,432   133,165,804
350  201204  인천광역시  연수구   합계   53,462   121,801,316
430  201205  인천광역시  연수구   합계   53,501   115,253,889
510  201206  인천광역시  연수구   합계   53,529   120,025,482
118  201201  인천광역시  옹진군   합계   17,341    18,012,074
198  201202  인천광역시  옹진군   합계   17,357    19,351,919
278  201203  인천광역시  옹진군   합계   18,308    15,871,356
358  201204  인천광역시  옹진군   합계   17,851    19,198,761
438  201205  인천광역시  옹진군   합계   17,552    16,871,955
518  201206  인천광역시  옹진군   합계   17,672    14,750,299
126  201201  인천광역시   중구   합계   40,599   149,498,622
206  201202  인천광역시   중구   합계   40,657   144,902,484
286  201203  인천광역시   중구   합계   41,134   139,906,877
366  201204  인천광역시   중구   합계   40,802   132,014,059
446  201205  인천광역시   중구   합계   40,827   128,900,740
526  201206  인천광역시   중구   합계   40,931   132,976,565

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[61078035, 62110203, 52526603, 46672280, 35061609, 31935674]
[127145423, 124822394, 112933812, 106962528, 97872660, 100996442]
[205364773, 207547806, 191543944, 181348498, 167148712, 169267534]
[372617188, 372919457, 343254488, 325119454, 302515749, 310672580]
[348886462, 359503658, 356206971, 350445791, 367010387, 357436891]
[234632833, 234407415, 214058151, 201670873, 187384672, 197264790]
[403255623, 397505773, 378734887, 362149032, 339707033, 344550074]
[149701314, 147405337, 133165804, 121801316, 115253889, 120025482]
[18012074, 19351919, 15871356, 19198761, 16871955, 14750299]
[149498622, 144902484, 139906877, 132014059, 128900740, 132976565]
인천광역시 지역별 합계 :  [289384404, 670733259, 1122221267, 2027098916, 2139490160, 1269418734, 2225902422, 787353142, 104056364, 828199347]
인천광역시 고객호수 평균:  [10147, 15851, 29575, 22416, 3946, 26018, 21480, 8905, 2946, 6804]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\659731433.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0          201201  인천광역시  강화군   합계  59,107   61,078,035
1          201202  인천광역시  강화군   합계  59,136   62,110,203
2          201203  인천광역시  강화군   합계  64,388   52,526,603
3          201204  인천광역시  강화군   합계  63,284   46,672,280
4          201205  인천광역시  강화군   합계  59,490   35,061,609
..            ...    ...  ...  ...      ...          ...
65  201201-201206  인천광역시  부평구   합계    26018   1269418734
66  201201-201206  인천광역시   서구   합계    21480   2225902422
67  201201-201206  인천광역시  연수구   합계     8905    787353142
68  201201-201206  인천광역시  옹진군   합계     2946    104056364
69  201201-201206  인천광역시   중구   합계     6804    828199347

[70 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201201-201206']
Hap

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201201-201206  인천광역시  강화군   합계   10147   289384404
61  201201-201206  인천광역시  계양구   합계   15851   670733259
62  201201-201206  인천광역시   남구   합계   29575  1122221267
63  201201-201206  인천광역시  남동구   합계   22416  2027098916
64  201201-201206  인천광역시   동구   합계    3946  2139490160
65  201201-201206  인천광역시  부평구   합계   26018  1269418734
66  201201-201206  인천광역시   서구   합계   21480  2225902422
67  201201-201206  인천광역시  연수구   합계    8905   787353142
68  201201-201206  인천광역시  옹진군   합계    2946   104056364
69  201201-201206  인천광역시   중구   합계    6804   828199347

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월     시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201201  인천광역시  강화군  일반용   6,482   16,247,775
132  201202  인천광역시  강화군  일반용   6,497   16,283,821
212  201203  인천광역시  강화군  일반용   6,519   13,881,789
292  201204  인천광역시  강화군  일반용   6,521   12,453,946
372  201205  인천광역시  강화군  일반용   6,527   10,037,127
452  201206  인천광역시  강화군  일반용   6,530   10,044,633
61   201201  인천광역시  계양구  일반용  11,973   46,301,482
140  201202  인천광역시  계양구  일반용  11,976   44,930,362
220  201203  인천광역시  계양구  일반용  11,970   38,711,865
300  201204  인천광역시  계양구  일반용  11,984   35,904,583
380  201205  인천광역시  계양구  일반용  11,987   32,680,206
460  201206  인천광역시  계양구  일반용  11,978   34,714,775
69   201201  인천광역시   남구  일반용  20,355   60,279,399
148  201202  인천광역시   남구  일반용  20,356   60,911,186
228  201203  인천광역시   남구  일반용  20,362   52,149,820
308  201204  인천광역시   남구  일반용  20,376   48,958,762
388  201205  인천광역시   남구  일반용  20,360   42,470,432
468  201206  인천광역시   남구  일반용  20,327   44,686,574
77   201201  인천광역시  남동구  일반용  20,147   83,660,584
156  201202  인천광역시  남동구  일반용  20,104   82,497,324
236  201203  인천광역시  남동구  일반용  20,104   71,161,297
316  201204  인천광역시  남동구  일반용  20,119   66,225,586
396  201205  인천광역시  남동구  일반용  20,154   60,358,475
476  201206  인천광역시  남동구  일반용  20,145   64,641,784
84   201201  인천광역시   동구  일반용   3,691   11,294,723
164  201202  인천광역시   동구  일반용   3,701   11,295,341
244  201203  인천광역시   동구  일반용   3,695    9,647,561
324  201204  인천광역시   동구  일반용   3,708    8,727,849
404  201205  인천광역시   동구  일반용   3,714    7,529,711
484  201206  인천광역시   동구  일반용   3,712    8,092,382
92   201201  인천광역시  부평구  일반용  21,815   78,539,207
172  201202  인천광역시  부평구  일반용  21,836   76,889,958
252  201203  인천광역시  부평구  일반용  21,845   66,363,355
332  201204  인천광역시  부평구  일반용  21,822   61,186,040
412  201205  인천광역시  부평구  일반용  21,744   55,708,868
492  201206  인천광역시  부평구  일반용  21,768   60,838,717
100  201201  인천광역시   서구  일반용  17,863   68,459,230
180  201202  인천광역시   서구  일반용  17,851   67,366,098
260  201203  인천광역시   서구  일반용  17,877   57,894,961
340  201204  인천광역시   서구  일반용  17,956   53,415,320
420  201205  인천광역시   서구  일반용  18,020   45,807,877
500  201206  인천광역시   서구  일반용  18,141   48,168,492
108  201201  인천광역시  연수구  일반용   7,633   48,097,690
188  201202  인천광역시  연수구  일반용   7,639   46,308,035
268  201203  인천광역시  연수구  일반용   7,630   40,991,340
348  201204  인천광역시  연수구  일반용   7,641   37,739,247
428  201205  인천광역시  연수구  일반용   7,646   34,005,379
508  201206  인천광역시  연수구  일반용   7,646   36,312,970
116  201201  인천광역시  옹진군  일반용   2,938    8,786,020
196  201202  인천광역시  옹진군  일반용   2,950    8,987,042
276  201203  인천광역시  옹진군  일반용   2,962    7,841,410
356  201204  인천광역시  옹진군  일반용   2,993    7,459,657
436  201205  인천광역시  옹진군  일반용   3,039    6,125,455
516  201206  인천광역시  옹진군  일반용   3,079    5,953,606
124  201201  인천광역시   중구  일반용   8,979   77,248,016
204  201202  인천광역시   중구  일반용   8,973   74,150,209
284  201203  인천광역시   중구  일반용   8,956   69,589,437
364  201204  인천광역시   중구  일반용   8,958   63,865,919
444  201205  인천광역시   중구  일반용   8,990   63,113,504
524  201206  인천광역시   중구  일반용   8,986   68,044,920

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[16247775, 16283821, 13881789, 12453946, 10037127, 10044633]
[46301482, 44930362, 38711865, 35904583, 32680206, 34714775]
[60279399, 60911186, 52149820, 48958762, 42470432, 44686574]
[83660584, 82497324, 71161297, 66225586, 60358475, 64641784]
[11294723, 11295341, 9647561, 8727849, 7529711, 8092382]
[78539207, 76889958, 66363355, 61186040, 55708868, 60838717]
[68459230, 67366098, 57894961, 53415320, 45807877, 48168492]
[48097690, 46308035, 40991340, 37739247, 34005379, 36312970]
[8786020, 8987042, 7841410, 7459657, 6125455, 5953606]
[77248016, 74150209, 69589437, 63865919, 63113504, 68044920]
인천광역시 지역별 일반용 합계 :  [78949091, 233243273, 309456173, 428545050, 56587567, 399526145, 341111978, 243454661, 45153190, 416012005]
인천광역시 고객호수 평균:  [6512, 11978, 20356, 20128, 3703, 21805, 17951, 7639, 2993, 8973]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12688\3843526984.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201201-201206'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

               년월     시구  시군구 계약구분 고객호수(호)     사용량(kWh)
0          201201  인천광역시  강화군  일반용  6,482   16,247,775
1          201202  인천광역시  강화군  일반용  6,497   16,283,821
2          201203  인천광역시  강화군  일반용  6,519   13,881,789
3          201204  인천광역시  강화군  일반용  6,521   12,453,946
4          201205  인천광역시  강화군  일반용  6,527   10,037,127
..            ...    ...  ...  ...     ...          ...
65  201201-201206  인천광역시  부평구  일반용   21805    399526145
66  201201-201206  인천광역시   서구  일반용   17951    341111978
67  201201-201206  인천광역시  연수구  일반용    7639    243454661
68  201201-201206  인천광역시  옹진군  일반용    2993     45153190
69  201201-201206  인천광역시   중구  일반용    8973    416012005

[70 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201201-201206']
GyeonGiHap2

               년월     시구  시군구 계약구분 고객호수(호)   사용량(kWh)
60  201201-201206  인천광역시  강화군  일반용    6512   78949091
61  201201-201206  인천광역시  계양구  일반용   11978  233243273
62  201201-201206  인천광역시   남구  일반용   20356  309456173
63  201201-201206  인천광역시  남동구  일반용   20128  428545050
64  201201-201206  인천광역시   동구  일반용    3703   56587567
65  201201-201206  인천광역시  부평구  일반용   21805  399526145
66  201201-201206  인천광역시   서구  일반용   17951  341111978
67  201201-201206  인천광역시  연수구  일반용    7639  243454661
68  201201-201206  인천광역시  옹진군  일반용    2993   45153190
69  201201-201206  인천광역시   중구  일반용    8973  416012005

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)
60  201201-201206  인천광역시  강화군  일반용    6512    78949091
60  201201-201206  인천광역시  강화군   합계   10147   289384404
61  201201-201206  인천광역시  계양구  일반용   11978   233243273
61  201201-201206  인천광역시  계양구   합계   15851   670733259
62  201201-201206  인천광역시   남구  일반용   20356   309456173
62  201201-201206  인천광역시   남구   합계   29575  1122221267
63  201201-201206  인천광역시  남동구  일반용   20128   428545050
63  201201-201206  인천광역시  남동구   합계   22416  2027098916
64  201201-201206  인천광역시   동구  일반용    3703    56587567
64  201201-201206  인천광역시   동구   합계    3946  2139490160
65  201201-201206  인천광역시  부평구  일반용   21805   399526145
65  201201-201206  인천광역시  부평구   합계   26018  1269418734
66  201201-201206  인천광역시   서구  일반용   17951   341111978
66  201201-201206  인천광역시   서구   합계   21480  2225902422
67  201201-201206  인천광역시  연수구   합계    8905   787353142
67  201201-201206  인천광역시  연수구  일반용    7639   243454661
68  201201-201206  인천광역시  옹진군   합계    2946   104056364
68  201201-201206  인천광역시  옹진군  일반용    2993    45153190
69  201201-201206  인천광역시   중구  일반용    8973   416012005
69  201201-201206  인천광역시   중구   합계    6804   828199347

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[78949091,
 233243273,
 309456173,
 428545050,
 56587567,
 399526145,
 341111978,
 243454661,
 45153190,
 416012005]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[289384404,
 670733259,
 1122221267,
 2027098916,
 2139490160,
 1269418734,
 2225902422,
 787353142,
 104056364,
 828199347]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[27.28, 34.77, 27.58, 21.14, 2.64, 31.47, 15.32, 30.92, 43.39, 50.23]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0   27
1   35
2   28
3   21
4    3
5   31
6   15
7   31
8   43
9   50
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

   시군구 계약구분  비율
0  강화군  일반용  27
1  계양구  일반용  35
2   남구  일반용  28
3  남동구  일반용  21
4   동구  일반용   3
5  부평구  일반용  31
6   서구  일반용  15
7  연수구  일반용  31
8  옹진군  일반용  43
9   중구  일반용  50

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월     시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201201-201206  인천광역시  강화군  일반용    6512    78949091  27
1   201201-201206  인천광역시  강화군   합계   10147   289384404 NaN
2   201201-201206  인천광역시  계양구  일반용   11978   233243273  35
3   201201-201206  인천광역시  계양구   합계   15851   670733259 NaN
4   201201-201206  인천광역시   남구  일반용   20356   309456173  28
5   201201-201206  인천광역시   남구   합계   29575  1122221267 NaN
6   201201-201206  인천광역시  남동구  일반용   20128   428545050  21
7   201201-201206  인천광역시  남동구   합계   22416  2027098916 NaN
8   201201-201206  인천광역시   동구  일반용    3703    56587567   3
9   201201-201206  인천광역시   동구   합계    3946  2139490160 NaN
10  201201-201206  인천광역시  부평구  일반용   21805   399526145  31
11  201201-201206  인천광역시  부평구   합계   26018  1269418734 NaN
12  201201-201206  인천광역시   서구  일반용   17951   341111978  15
13  201201-201206  인천광역시   서구   합계   21480  2225902422 NaN
15  201201-201206  인천광역시  연수구  일반용    7639   243454661  31
14  201201-201206  인천광역시  연수구   합계    8905   787353142 NaN
17  201201-201206  인천광역시  옹진군  일반용    2993    45153190  43
16  201201-201206  인천광역시  옹진군   합계    2946   104056364 NaN
18  201201-201206  인천광역시   중구  일반용    8973   416012005  50
19  201201-201206  인천광역시   중구   합계    6804   828199347 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1201-06.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)