In [1]:
import pandas as pd
import re

pd.options.display.float_format = '{:.0f}'.format

### 1. 꼭 read_csv 21상반기, 19하반기와 같이 맞추어 주세요!!! 또한 지역(전라북도, 남도) 맞추기!!!!!

In [2]:
df = pd.read_csv('강원도_계약종별_전력사용량_월별_17하반기.csv' , encoding='cp949')

df
#exchng=  pd.read_csv('지역별_전력거래량_20220803093050.csv' , encoding='cp949')

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,"시도 : 강원도, 시군구 : 전체(시 / 군 / 구)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,기간 : 2017년 07 월 ~ 2017년 12월,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,강원도,전체(시 / 군 / 구),주택용,"568,375","164,665,062","16,956,417,507",103.0
4,201707,강원도,전체(시 / 군 / 구),일반용,"139,200","362,944,730","53,587,076,905",147.6
...,...,...,...,...,...,...,...,...
907,201712,강원도,횡성군,산업용,663,"16,678,335","2,212,342,242",132.6
908,201712,강원도,횡성군,심 야,"6,404","17,187,321","1,286,687,514",74.9
909,201712,강원도,횡성군,일반용,"4,946","13,522,897","1,759,974,956",130.1
910,201712,강원도,횡성군,주택용,"23,378","5,120,889","574,959,424",112.3
911,201712,강원도,횡성군,합계,"47,025","60,673,290","6,332,117,379",104.4

In [3]:
df = df.drop([0,1 , 46] , axis = 0)
#0,1 , 10은 지우는게 맞다
df

,계약종별 전력사용량 월별( 20220804 현재 ),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
2,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,강원도,전체(시 / 군 / 구),주택용,"568,375","164,665,062","16,956,417,507",103.0
4,201707,강원도,전체(시 / 군 / 구),일반용,"139,200","362,944,730","53,587,076,905",147.6
5,201707,강원도,전체(시 / 군 / 구),교육용,"1,066","23,414,972","2,930,337,295",125.1
6,201707,강원도,전체(시 / 군 / 구),산업용,"13,192","606,606,453","71,347,867,602",117.6
...,...,...,...,...,...,...,...,...
907,201712,강원도,횡성군,산업용,663,"16,678,335","2,212,342,242",132.6
908,201712,강원도,횡성군,심 야,"6,404","17,187,321","1,286,687,514",74.9
909,201712,강원도,횡성군,일반용,"4,946","13,522,897","1,759,974,956",130.1
910,201712,강원도,횡성군,주택용,"23,378","5,120,889","574,959,424",112.3
911,201712,강원도,횡성군,합계,"47,025","60,673,290","6,332,117,379",104.4

In [4]:
a= df.loc[2].tolist()
a
df = df.drop([2] , axis = 0)

In [5]:
df.columns = a
df

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,강원도,전체(시 / 군 / 구),주택용,"568,375","164,665,062","16,956,417,507",103.0
4,201707,강원도,전체(시 / 군 / 구),일반용,"139,200","362,944,730","53,587,076,905",147.6
5,201707,강원도,전체(시 / 군 / 구),교육용,"1,066","23,414,972","2,930,337,295",125.1
6,201707,강원도,전체(시 / 군 / 구),산업용,"13,192","606,606,453","71,347,867,602",117.6
7,201707,강원도,전체(시 / 군 / 구),농사용,"95,786","48,958,256","2,461,669,980",50.3
...,...,...,...,...,...,...,...,...
907,201712,강원도,횡성군,산업용,663,"16,678,335","2,212,342,242",132.6
908,201712,강원도,횡성군,심 야,"6,404","17,187,321","1,286,687,514",74.9
909,201712,강원도,횡성군,일반용,"4,946","13,522,897","1,759,974,956",130.1
910,201712,강원도,횡성군,주택용,"23,378","5,120,889","574,959,424",112.3
911,201712,강원도,횡성군,합계,"47,025","60,673,290","6,332,117,379",104.4

In [6]:
df_2 = df.loc[:45]
df_2

,년월,시구,시군구,계약구분,고객호수(호),사용량(kWh),전기요금(원),평균판매단가(원/kWh)
3,201707,강원도,전체(시 / 군 / 구),주택용,"568,375","164,665,062","16,956,417,507",103.0
4,201707,강원도,전체(시 / 군 / 구),일반용,"139,200","362,944,730","53,587,076,905",147.6
5,201707,강원도,전체(시 / 군 / 구),교육용,"1,066","23,414,972","2,930,337,295",125.1
6,201707,강원도,전체(시 / 군 / 구),산업용,"13,192","606,606,453","71,347,867,602",117.6
7,201707,강원도,전체(시 / 군 / 구),농사용,"95,786","48,958,256","2,461,669,980",50.3
8,201707,강원도,전체(시 / 군 / 구),가로등,"113,902","16,834,204","2,004,772,099",119.1
9,201707,강원도,전체(시 / 군 / 구),심 야,"92,777","42,857,009","2,426,935,029",56.6
10,201708,강원도,전체(시 / 군 / 구),주택용,"570,029","190,395,168","21,457,924,477",112.7
11,201708,강원도,전체(시 / 군 / 구),일반용,"139,501","404,506,524","58,178,009,410",143.8
12,201708,강원도,전체(시 / 군 / 구),교육용,"1,065","22,672,357","2,931,365,886",129.3
13,201708,강원도,전체(시 / 군 / 구),산업용,"13,229","581,564,103","68,951,143,500",118.6
14,201708,강원도,전체(시 / 군 / 구),농사용,"96,539","56,714,184","2,816,060,480",49.7
15,201708,강원도,전체(시 / 군 / 구),가로등,"108,830","16,611,348","1,961,405,560",118.1
16,201708,강원도,전체(시 / 군 / 구),심 야,"92,622","37,487,551","2,131,217,667",56.9
17,201709,강원도,전체(시 / 군 / 구),주택용,"572,961","167,494,522","17,178,099,671",102.6
18,201709,강원도,전체(시 / 군 / 구),일반용,"139,613","344,197,788","45,417,211,484",132.0
19,201709,강원도,전체(시 / 군 / 구),교육용,"1,064","21,894,812","2,523,821,548",115.3
20,201709,강원도,전체(시 / 군 / 구),산업용,"13,231","586,710,393","57,461,521,182",97.9
21,201709,강원도,전체(시 / 군 / 구),농사용,"97,212","60,558,343","2,994,326,336",49.4
22,201709,강원도,전체(시 / 군 / 구),가로등,"108,768","17,099,726","1,947,185,174",113.9
23,201709,강원도,전체(시 / 군 / 구),심 야,"92,652","44,864,306","2,514,650,881",56.1
24,201710,강원도,전체(시 / 군 / 구),주택용,"572,699","156,255,323","15,398,393,517",98.5
25,201710,강원도,전체(시 / 군 / 구),일반용,"139,612","305,938,084","36,061,340,496",117.9
26,201710,강원도,전체(시 / 군 / 구),교육용,"1,060","18,624,321","1,826,204,043",98.1
27,201710,강원도,전체(시 / 군 / 구),산업용,"13,225","611,076,093","55,788,791,391",91.3
28,201710,강원도,전체(시 / 군 / 구),농사용,"97,404","53,205,323","2,695,333,120",50.7
29,201710,강원도,전체(시 / 군 / 구),가로등,"108,653","17,540,448","1,939,007,614",110.5
30,201710,강원도,전체(시 / 군 / 구),심 야,"92,474","66,000,487","3,641,937,041",55.2
31,201711,강원도,전체(시 / 군 / 구),주택용,"574,332","168,936,625","17,528,866,251",103.8
32,201711,강원도,전체(시 / 군 / 구),일반용,"140,751","353,176,831","45,580,767,095",129.1
33,201711,강원도,전체(시 / 군 / 구),교육용,"1,062","26,015,381","2,801,043,995",107.7
34,201711,강원도,전체(시 / 군 / 구),산업용,"13,267","639,040,996","73,653,376,648",115.3
35,201711,강원도,전체(시 / 군 / 구),농사용,"120,016","69,742,288","3,094,741,856",44.4
36,201711,강원도,전체(시 / 군 / 구),가로등,"106,507","17,893,000","1,957,998,035",109.4
37,201711,강원도,전체(시 / 군 / 구),심 야,"92,407","138,639,318","8,764,194,790",63.2
38,201712,강원도,전체(시 / 군 / 구),주택용,"575,932","180,481,726","19,536,044,199",108.2
39,201712,강원도,전체(시 / 군 / 구),일반용,"141,689","440,185,005","57,887,326,803",131.5
40,201712,강원도,전체(시 / 군 / 구),교육용,"1,062","40,018,660","3,926,639,138",98.1
41,201712,강원도,전체(시 / 군 / 구),산업용,"13,290","635,258,893","73,174,204,496",115.2
42,201712,강원도,전체(시 / 군 / 구),농사용,"97,653","53,946,859","2,730,805,671",50.6
43,201712,강원도,전체(시 / 군 / 구),가로등,"104,217","17,939,170","1,942,034,943",108.3
44,201712,강원도,전체(시 / 군 / 구),심 야,"92,339","233,960,523","17,545,010,311",75.0
45,합계,합계,합계,합계,"6,171,265","8,062,927,165","887,653,081,126",110.1

In [7]:
GyeonGi  = df_2.loc[(df_2['계약구분'] == '일반용')]
#SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
GyeonGi

C:\Users\user\AppData\Local\Temp\ipykernel_12732\730399353.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GyeonGi.drop(['시군구' , '전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)

        년월   시구 계약구분   고객호수(호)      사용량(kWh)
4   201707  강원도  일반용  139,200   362,944,730
11  201708  강원도  일반용  139,501   404,506,524
18  201709  강원도  일반용  139,613   344,197,788
25  201710  강원도  일반용  139,612   305,938,084
32  201711  강원도  일반용  140,751   353,176,831
39  201712  강원도  일반용  141,689   440,185,005

In [8]:
#SEOUL1.to_csv("서울특별시_계약종별_전국_전력사용량_2022.csv" , mode = 'w' , encoding= 'cp949')

In [9]:
#df_2.to_csv("서울특별시_계약종별_전국_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [10]:
df_3 = df.loc[48:]
df_3 = df_3.loc[(df_3['계약구분'] == '일반용')]
df_3 = df_3.sort_values(by=['시군구' , '년월'])
df_3.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201707  강원도  강릉시  일반용  18,943   43,425,484
197  201708  강원도  강릉시  일반용  19,008   48,944,405
341  201709  강원도  강릉시  일반용  19,037   44,957,328
485  201710  강원도  강릉시  일반용  19,013   38,686,334
629  201711  강원도  강릉시  일반용  19,153   41,116,450
..      ...  ...  ...  ...      ...          ...
333  201708  강원도  횡성군  일반용   4,771    9,827,696
477  201709  강원도  횡성군  일반용   4,787    8,340,281
621  201710  강원도  횡성군  일반용   4,802    7,635,482
765  201711  강원도  횡성군  일반용   4,879   10,217,647
909  201712  강원도  횡성군  일반용   4,946   13,522,897

[108 rows x 6 columns]

In [11]:
a = df_3.loc[: , "시구"]
b = a[:1].tolist()
for i in b:
    City = i
City

'강원도'

In [12]:

SIGUNGU = list(set(df_3.loc[: , '시군구'].tolist()))
SIGUNGU.sort()
SIGUNGU

['강릉시',
 '고성군',
 '동해시',
 '삼척시',
 '속초시',
 '양구군',
 '양양군',
 '영월군',
 '원주시',
 '인제군',
 '정선군',
 '철원군',
 '춘천시',
 '태백시',
 '평창군',
 '홍천군',
 '화천군',
 '횡성군']

In [13]:
df_4 = df.loc[48:]
df_4 = df_4.loc[(df_4['계약구분'] == '합계')]
df_4 = df_4.sort_values(by=['시군구' , '년월'])
df_4.drop(['전기요금(원)',   '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
df_4

         년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
55   201707  강원도  강릉시   합계  129,687   156,001,523
199  201708  강원도  강릉시   합계  130,055   163,335,439
343  201709  강원도  강릉시   합계  130,486   158,143,303
487  201710  강원도  강릉시   합계  130,421   153,297,761
631  201711  강원도  강릉시   합계  131,070   171,109,543
..      ...  ...  ...  ...       ...           ...
335  201708  강원도  횡성군   합계   51,806    41,238,167
479  201709  강원도  횡성군   합계   52,085    39,364,339
623  201710  강원도  횡성군   합계   52,237    36,860,991
767  201711  강원도  횡성군   합계   51,722    50,246,839
911  201712  강원도  횡성군   합계   47,025    60,673,290

[108 rows x 6 columns]

In [14]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_4['사용량(kWh)'].loc[(df_4['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_4['고객호수(호)'].loc[(df_4['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//36) #6개월 치로 나눠야하나?!




print("{} 지역별 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)

[156001523, 163335439, 158143303, 153297761, 171109543, 185695935]
[22835404, 24695314, 22970196, 21399600, 24871065, 28702533]
[221303715, 222780159, 201455297, 228993738, 228581415, 222264978]
[126619909, 112484016, 119994101, 124387405, 126681892, 144452449]
[38888238, 43505971, 38356897, 35766829, 38958526, 45108178]
[14217519, 15274661, 14481944, 14300426, 20246802, 23449245]
[20475989, 23304492, 22039870, 20642042, 24170849, 27576969]
[82044953, 82266704, 89985226, 90567065, 100083534, 100976979]
[186085568, 197826912, 182811359, 161232783, 198820548, 237349114]
[22673246, 23816436, 22340591, 22572888, 28002824, 35140709]
[43067940, 44525539, 44883381, 48029942, 59187989, 70105826]
[31629111, 33370034, 31209639, 30633910, 45235718, 51801508]
[131735946, 143301760, 125533334, 113838415, 133117933, 163759750]
[22989416, 23955090, 24185298, 23003159, 27367970, 31151748]
[37827374, 40074017, 38161140, 40364103, 55960492, 73786013]
[52316917, 55899279, 49977178, 46732300, 60146288, 73276513]
[16634401, 18297245, 16926797, 16016722, 20654212, 26519099]
[38933517, 41238167, 39364339, 36860991, 50246839, 60673290]
강원도 지역별 합계 :  [987583504, 145474112, 1325379302, 754619772, 240584639, 101970597, 138210211, 545924461, 1164126284, 154546694, 309800617, 223879920, 811287138, 152652681, 286173139, 338348475, 115048476, 267317143]
강원도 고객호수 평균:  [21742, 4759, 8103, 9181, 6542, 3761, 4968, 6680, 25686, 5669, 6331, 7074, 23514, 4629, 8452, 11736, 4076, 8511]

### 2. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [15]:
Hap = df_4.copy()
Hap.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
Hap

C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\3264182707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  Hap = Hap.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '합계' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분   고객호수(호)      사용량(kWh)
0           201707  강원도  강릉시   합계  129,687   156,001,523
1           201708  강원도  강릉시   합계  130,055   163,335,439
2           201709  강원도  강릉시   합계  130,486   158,143,303
3           201710  강원도  강릉시   합계  130,421   153,297,761
4           201711  강원도  강릉시   합계  131,070   171,109,543
..             ...  ...  ...  ...       ...           ...
121  201707-201712  강원도  태백시   합계      4629     152652681
122  201707-201712  강원도  평창군   합계      8452     286173139
123  201707-201712  강원도  홍천군   합계     11736     338348475
124  201707-201712  강원도  화천군   합계      4076     115048476
125  201707-201712  강원도  횡성군   합계      8511     267317143

[126 rows x 6 columns]

### 3. 날짜 변경!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [16]:
Hap = Hap.loc[Hap['년월'] == '201707-201712']
Hap

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201707-201712  강원도  강릉시   합계   21742   987583504
109  201707-201712  강원도  고성군   합계    4759   145474112
110  201707-201712  강원도  동해시   합계    8103  1325379302
111  201707-201712  강원도  삼척시   합계    9181   754619772
112  201707-201712  강원도  속초시   합계    6542   240584639
113  201707-201712  강원도  양구군   합계    3761   101970597
114  201707-201712  강원도  양양군   합계    4968   138210211
115  201707-201712  강원도  영월군   합계    6680   545924461
116  201707-201712  강원도  원주시   합계   25686  1164126284
117  201707-201712  강원도  인제군   합계    5669   154546694
118  201707-201712  강원도  정선군   합계    6331   309800617
119  201707-201712  강원도  철원군   합계    7074   223879920
120  201707-201712  강원도  춘천시   합계   23514   811287138
121  201707-201712  강원도  태백시   합계    4629   152652681
122  201707-201712  강원도  평창군   합계    8452   286173139
123  201707-201712  강원도  홍천군   합계   11736   338348475
124  201707-201712  강원도  화천군   합계    4076   115048476
125  201707-201712  강원도  횡성군   합계    8511   267317143

In [17]:
# SIGUNGU = SIGUNGU[:1]
# SIGUNGU
#for i in SIGUNGU:
#print('{}'.format(i))
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [18]:
a = (df_3.columns).tolist()

a

['년월', '시구', '시군구', '계약구분', '고객호수(호)', '사용량(kWh)']

In [19]:
df_3

         년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
53   201707  강원도  강릉시  일반용  18,943   43,425,484
197  201708  강원도  강릉시  일반용  19,008   48,944,405
341  201709  강원도  강릉시  일반용  19,037   44,957,328
485  201710  강원도  강릉시  일반용  19,013   38,686,334
629  201711  강원도  강릉시  일반용  19,153   41,116,450
..      ...  ...  ...  ...      ...          ...
333  201708  강원도  횡성군  일반용   4,771    9,827,696
477  201709  강원도  횡성군  일반용   4,787    8,340,281
621  201710  강원도  횡성군  일반용   4,802    7,635,482
765  201711  강원도  횡성군  일반용   4,879   10,217,647
909  201712  강원도  횡성군  일반용   4,946   13,522,897

[108 rows x 6 columns]

In [20]:
# GyeonGiHap = pd.DataFrame([] , columns = a)
# GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{가평군}')]
# GyeonGiHap

In [21]:
sum2 , sum3 =[] , []
for k in SIGUNGU:
    GyeonGiHap = pd.DataFrame([] , columns = a)
    HOSU = pd.DataFrame([], columns = a)
    GyeonGiHap['사용량']= df_3['사용량(kWh)'].loc[(df_3['시군구'] == '{}'.format(k))]
    HOSU['고객호수']= df_3['고객호수(호)'].loc[(df_3['시군구'] == '{}'.format(k))]
    #경기합 데이터프레임의 사용량 열에 기군구가 가평군인 사용량 데이터만 뽑아내기
    # GyeonGiHap = GyeonGiHap['사용량']

    b = GyeonGiHap['사용량'].tolist()
    c = HOSU['고객호수'].tolist()


    #각지역별 사용량 리스트화
    int_list  , int_list2=[] , []
    for i in b:
        i = re.sub("," , "" , i)
        #콤마 없애기
        int_list.append(int(i))
        #int_list에 각지역별 사용량 int로 저장
    print(int_list)
    sum=0
    for i in c:
        i = re.sub("," , "" , i)
        int_list2.append(int(i))

    for j in int_list:

        sum+= j
    sum2.append(sum)
    sum = 0
    for j in int_list2: #고객호수 추출하여 더하기

        sum+= j
    sum3.append(sum//6) #6개월 치로 나눠야하나?!




print("{} 지역별 일반용 합계 : ".format(City) , sum2)
print("{} 고객호수 평균: ".format(City) , sum3)
# GyeonGiHap['합계'] = sum
#
# GyeonGiHap

[43425484, 48944405, 44957328, 38686334, 41116450, 49112503]
[11135166, 12617538, 10506312, 9219159, 9931262, 11716753]
[16623331, 18997858, 16994065, 14845429, 16005975, 19328817]
[13900882, 15710681, 13760277, 12098051, 13027848, 15377082]
[22302265, 25767875, 21293468, 19196536, 19737305, 22999150]
[6746005, 7340792, 6291112, 5776264, 6947975, 8736058]
[9837567, 11811847, 10215708, 8991921, 9831838, 11463493]
[6330098, 7488626, 6413413, 5553705, 6159424, 7483772]
[67300027, 73980442, 62233386, 53033691, 60722105, 77372814]
[11172803, 12537235, 10041404, 9425994, 11458111, 14198545]
[14727905, 15857590, 12993306, 13171809, 19839038, 25943939]
[13143910, 14010627, 11771226, 10706000, 13301845, 17055054]
[63595212, 69778840, 59433400, 51994029, 56410775, 68244533]
[6507169, 7276494, 6675407, 6177444, 7043077, 8624765]
[16753479, 18284808, 15106930, 15615517, 22632810, 32489254]
[21794334, 24040302, 18563169, 16277336, 19784579, 24701831]
[8910395, 10232868, 8607596, 7533383, 9008767, 11813745]
[8738698, 9827696, 8340281, 7635482, 10217647, 13522897]
강원도 지역별 일반용 합계 :  [266242504, 65126190, 102795475, 83874821, 131296599, 41838206, 62152374, 39429038, 394642465, 68834092, 102533587, 79988662, 369456789, 42304356, 120882798, 125161551, 56106754, 58282701]
강원도 고객호수 평균:  [19068, 3840, 6926, 6300, 7930, 2595, 4124, 4098, 24687, 4380, 4942, 4661, 20320, 4069, 6170, 7964, 3153, 4824]

In [22]:
# df_3 = df_3.loc[(df_3['시군구'] == '가평군')]
#
# df_3

In [23]:
# GyeonGiHap = df_3.copy()
# GyeonGiHap.reset_index(drop=True , inplace = True)
# GyeonGiHap.append({'년월' : '202107-202112'  , '시구' : '경기도' , '시군구' : '가평군' , '계약구분' : '일반용' , '사용량(kWh)' : sum}, ignore_index=True)

In [24]:
# a=[]
# for i in SIGUNGU:
#     a.append(i)
#
# print(a)

### 4. 년월 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [25]:
GyeonGiHap2 = df_3.copy()
GyeonGiHap2.reset_index(drop=True , inplace = True)
for i in range(len(SIGUNGU)):
    GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
GyeonGiHap2

C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기
C:\Users\user\AppData\Local\Temp\ipykernel_12732\1372743769.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  GyeonGiHap2 = GyeonGiHap2.append({'년월' :'201707-201712'  , '시구' : '{}'.format(City) , '시군구' : '{}'.format(SIGUNGU[i]) , '계약구분' : '일반용' , '고객호수(호)' : sum3[i] ,  '사용량(kWh)' : sum2[i]} , ignore_index=True) #년월 파일마다 수정하기

                년월   시구  시군구 계약구분  고객호수(호)     사용량(kWh)
0           201707  강원도  강릉시  일반용  18,943   43,425,484
1           201708  강원도  강릉시  일반용  19,008   48,944,405
2           201709  강원도  강릉시  일반용  19,037   44,957,328
3           201710  강원도  강릉시  일반용  19,013   38,686,334
4           201711  강원도  강릉시  일반용  19,153   41,116,450
..             ...  ...  ...  ...      ...          ...
121  201707-201712  강원도  태백시  일반용     4069     42304356
122  201707-201712  강원도  평창군  일반용     6170    120882798
123  201707-201712  강원도  홍천군  일반용     7964    125161551
124  201707-201712  강원도  화천군  일반용     3153     56106754
125  201707-201712  강원도  횡성군  일반용     4824     58282701

[126 rows x 6 columns]

### 5. 날짜 체크!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

In [26]:
GyeonGiHap2 = GyeonGiHap2.loc[GyeonGiHap2['년월'] == '201707-201712']
GyeonGiHap2

                년월   시구  시군구 계약구분 고객호수(호)   사용량(kWh)
108  201707-201712  강원도  강릉시  일반용   19068  266242504
109  201707-201712  강원도  고성군  일반용    3840   65126190
110  201707-201712  강원도  동해시  일반용    6926  102795475
111  201707-201712  강원도  삼척시  일반용    6300   83874821
112  201707-201712  강원도  속초시  일반용    7930  131296599
113  201707-201712  강원도  양구군  일반용    2595   41838206
114  201707-201712  강원도  양양군  일반용    4124   62152374
115  201707-201712  강원도  영월군  일반용    4098   39429038
116  201707-201712  강원도  원주시  일반용   24687  394642465
117  201707-201712  강원도  인제군  일반용    4380   68834092
118  201707-201712  강원도  정선군  일반용    4942  102533587
119  201707-201712  강원도  철원군  일반용    4661   79988662
120  201707-201712  강원도  춘천시  일반용   20320  369456789
121  201707-201712  강원도  태백시  일반용    4069   42304356
122  201707-201712  강원도  평창군  일반용    6170  120882798
123  201707-201712  강원도  홍천군  일반용    7964  125161551
124  201707-201712  강원도  화천군  일반용    3153   56106754
125  201707-201712  강원도  횡성군  일반용    4824   58282701

In [27]:
Final = pd.concat([GyeonGiHap2 , Hap])
Final = Final.sort_values('시군구')
Final

                년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)
108  201707-201712  강원도  강릉시  일반용   19068   266242504
108  201707-201712  강원도  강릉시   합계   21742   987583504
109  201707-201712  강원도  고성군  일반용    3840    65126190
109  201707-201712  강원도  고성군   합계    4759   145474112
110  201707-201712  강원도  동해시  일반용    6926   102795475
110  201707-201712  강원도  동해시   합계    8103  1325379302
111  201707-201712  강원도  삼척시   합계    9181   754619772
111  201707-201712  강원도  삼척시  일반용    6300    83874821
112  201707-201712  강원도  속초시   합계    6542   240584639
112  201707-201712  강원도  속초시  일반용    7930   131296599
113  201707-201712  강원도  양구군  일반용    2595    41838206
113  201707-201712  강원도  양구군   합계    3761   101970597
114  201707-201712  강원도  양양군   합계    4968   138210211
114  201707-201712  강원도  양양군  일반용    4124    62152374
115  201707-201712  강원도  영월군  일반용    4098    39429038
115  201707-201712  강원도  영월군   합계    6680   545924461
116  201707-201712  강원도  원주시  일반용   24687   394642465
116  201707-201712  강원도  원주시   합계   25686  1164126284
117  201707-201712  강원도  인제군  일반용    4380    68834092
117  201707-201712  강원도  인제군   합계    5669   154546694
118  201707-201712  강원도  정선군   합계    6331   309800617
118  201707-201712  강원도  정선군  일반용    4942   102533587
119  201707-201712  강원도  철원군   합계    7074   223879920
119  201707-201712  강원도  철원군  일반용    4661    79988662
120  201707-201712  강원도  춘천시  일반용   20320   369456789
120  201707-201712  강원도  춘천시   합계   23514   811287138
121  201707-201712  강원도  태백시   합계    4629   152652681
121  201707-201712  강원도  태백시  일반용    4069    42304356
122  201707-201712  강원도  평창군   합계    8452   286173139
122  201707-201712  강원도  평창군  일반용    6170   120882798
123  201707-201712  강원도  홍천군   합계   11736   338348475
123  201707-201712  강원도  홍천군  일반용    7964   125161551
124  201707-201712  강원도  화천군   합계    4076   115048476
124  201707-201712  강원도  화천군  일반용    3153    56106754
125  201707-201712  강원도  횡성군  일반용    4824    58282701
125  201707-201712  강원도  횡성군   합계    8511   267317143

In [28]:
# Final['일반용 전기의 비율'] = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']) // (Final['사용량(kWh)'].loc[Final['계약구분'] == '합계'])
# Final
ex = (Final['사용량(kWh)'].loc[Final['계약구분'] == '일반용']).tolist()


ex

[266242504,
 65126190,
 102795475,
 83874821,
 131296599,
 41838206,
 62152374,
 39429038,
 394642465,
 68834092,
 102533587,
 79988662,
 369456789,
 42304356,
 120882798,
 125161551,
 56106754,
 58282701]

In [29]:
ex_2 =(Final['사용량(kWh)'].loc[Final['계약구분'] == '합계']).tolist()
ex_2

[987583504,
 145474112,
 1325379302,
 754619772,
 240584639,
 101970597,
 138210211,
 545924461,
 1164126284,
 154546694,
 309800617,
 223879920,
 811287138,
 152652681,
 286173139,
 338348475,
 115048476,
 267317143]

In [30]:
Rate = []
ilban = []
rae = 0
for i in range(len(ex)):
    rae = round(ex[i] / ex_2[i] *100 ,2)
    Rate.append(rae)
print(Rate)

[26.96, 44.77, 7.76, 11.11, 54.57, 41.03, 44.97, 7.22, 33.9, 44.54, 33.1, 35.73, 45.54, 27.71, 42.24, 36.99, 48.77, 21.8]

In [31]:
Rate3 = pd.Series(Rate)
Rate3

# Final = pd.concat([Final , Rate3])
# Final

0    27
1    45
2     8
3    11
4    55
5    41
6    45
7     7
8    34
9    45
10   33
11   36
12   46
13   28
14   42
15   37
16   49
17   22
dtype: float64

In [32]:
for j in range(len(Rate)):
    ilban.append('일반용')
#print(Rate)

Rate2 = pd.DataFrame()
Rate2['시군구'] = pd.DataFrame(SIGUNGU)
Rate2['계약구분'] = pd.DataFrame(ilban)
Rate2['비율'] = pd.DataFrame(Rate)
Rate2
#print(Rate2.dtypes)

    시군구 계약구분  비율
0   강릉시  일반용  27
1   고성군  일반용  45
2   동해시  일반용   8
3   삼척시  일반용  11
4   속초시  일반용  55
5   양구군  일반용  41
6   양양군  일반용  45
7   영월군  일반용   7
8   원주시  일반용  34
9   인제군  일반용  45
10  정선군  일반용  33
11  철원군  일반용  36
12  춘천시  일반용  46
13  태백시  일반용  28
14  평창군  일반용  42
15  홍천군  일반용  37
16  화천군  일반용  49
17  횡성군  일반용  22

In [33]:
Final = pd.merge(Final , Rate2, on=['시군구', '계약구분'] , how='left')

#Final.drop(['비율_y]' , axis = 1 , inplace = True)
#Final.rename(columns={'비율_y':'전체 계약종별 전력사용량 대비 일반용 사용량 비율'})
Final = Final.sort_values(['시군구' , '계약구분'])
Final

               년월   시구  시군구 계약구분 고객호수(호)    사용량(kWh)  비율
0   201707-201712  강원도  강릉시  일반용   19068   266242504  27
1   201707-201712  강원도  강릉시   합계   21742   987583504 NaN
2   201707-201712  강원도  고성군  일반용    3840    65126190  45
3   201707-201712  강원도  고성군   합계    4759   145474112 NaN
4   201707-201712  강원도  동해시  일반용    6926   102795475   8
5   201707-201712  강원도  동해시   합계    8103  1325379302 NaN
7   201707-201712  강원도  삼척시  일반용    6300    83874821  11
6   201707-201712  강원도  삼척시   합계    9181   754619772 NaN
9   201707-201712  강원도  속초시  일반용    7930   131296599  55
8   201707-201712  강원도  속초시   합계    6542   240584639 NaN
10  201707-201712  강원도  양구군  일반용    2595    41838206  41
11  201707-201712  강원도  양구군   합계    3761   101970597 NaN
13  201707-201712  강원도  양양군  일반용    4124    62152374  45
12  201707-201712  강원도  양양군   합계    4968   138210211 NaN
14  201707-201712  강원도  영월군  일반용    4098    39429038   7
15  201707-201712  강원도  영월군   합계    6680   545924461 NaN
16  201707-201712  강원도  원주시  일반용   24687   394642465  34
17  201707-201712  강원도  원주시   합계   25686  1164126284 NaN
18  201707-201712  강원도  인제군  일반용    4380    68834092  45
19  201707-201712  강원도  인제군   합계    5669   154546694 NaN
21  201707-201712  강원도  정선군  일반용    4942   102533587  33
20  201707-201712  강원도  정선군   합계    6331   309800617 NaN
23  201707-201712  강원도  철원군  일반용    4661    79988662  36
22  201707-201712  강원도  철원군   합계    7074   223879920 NaN
24  201707-201712  강원도  춘천시  일반용   20320   369456789  46
25  201707-201712  강원도  춘천시   합계   23514   811287138 NaN
27  201707-201712  강원도  태백시  일반용    4069    42304356  28
26  201707-201712  강원도  태백시   합계    4629   152652681 NaN
29  201707-201712  강원도  평창군  일반용    6170   120882798  42
28  201707-201712  강원도  평창군   합계    8452   286173139 NaN
31  201707-201712  강원도  홍천군  일반용    7964   125161551  37
30  201707-201712  강원도  홍천군   합계   11736   338348475 NaN
33  201707-201712  강원도  화천군  일반용    3153    56106754  49
32  201707-201712  강원도  화천군   합계    4076   115048476 NaN
34  201707-201712  강원도  횡성군  일반용    4824    58282701  22
35  201707-201712  강원도  횡성군   합계    8511   267317143 NaN

In [34]:
# Final['일반용 전기의 비율'] = Final.append(Rate)
# Final

### 6. 날짜 체크!!!!!!!!!!!!!!!!!!!!1

In [35]:
Final.to_csv("{}_일반용_전력사용량_1707-12.csv".format(City) , mode = 'w' , encoding= 'cp949' , index =False) #파일명 수정

In [36]:
# Sigu = list(set(df_3['시군구'].tolist()))
#
# Sigu.sort()
#
# Sigu

In [37]:
# YearMonth = list(set(df_3['년월'].tolist()))
#
# YearMonth.sort()
# YearMonth

In [38]:
# Gayeak = list(set(df_3['계약구분'].tolist()))
#
# Gayeak.sort()
# Gayeak

In [39]:
# SEOUL = df_3.loc[(df_3['계약구분'] =='일반용')]
# SEOUL.drop(['고객호수(호)' ,'전기요금(원)' , '평균판매단가(원/kWh)'] , axis = 1 , inplace = True)
# #SEOUL.dtypes(['사용량(kWh)'])
# SEOUL

In [40]:
#SEOUL.to_csv("서울특별시_일반용_전력사용량.csv" , mode = 'w' , encoding= 'cp949')

In [41]:
# print(SEOUL.dtypes)
# SEOUL = SEOUL.astype({'사용량(kWh)' : 'float'})

In [42]:
# SEOUL

In [43]:
# a = SEOUL['사용량(kWh)'].tolist()
# int_list = map(int, a)
# b=0
# for i in int_list:
#     b+=i
#
# print(b)